src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
src/Umbraco.Web/Editors/ContentController.cs
src/Umbraco.Web/Models/ContentEditing/ContentTypesByAliases.cs
src/Umbraco.Web/Umbraco.Web.csproj

This PR is working towards giving nested content the same treatment as the blocklist editor. 
The majority of this is changing it so all the empty content types are requested in a single request, additionally, this also allows us to apply the same mapping optimizations as for blocklist by using the `GetEmpties` method on the controller.
I've also made some additional changes to the frontend side of things before we kept calling `initIfAllScaffoldsHaveLoaded` because we did not know exactly when all the scaffolds had been loaded since we loaded them asynchronously one by one. Now we just call `initNestedContent` once the response from `GetEmptyByAliases` has been processed. 
Additionally, I noticed that we would create an array of content type aliases more than once, I've changed this so …

V8: Improve nested content optimization in the backoffice

---

src/Umbraco.Core/Services/Implement/ContentService.cs

I noticed an overload of `SaveAndPublish()` in ContentService which doesn't use `Constants.Security.SuperUserId` by default like the other overloads, but used `userId = 0`.

Save and publish using super user id

---

src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js

After PR https://github.com/umbraco/Umbraco-CMS/pull/10805 was merged I noticed block card didn't show the selected icon color.
The icon name includes color class as well, which is a bit of a mess and color classes are forcing color with `!important` as well. Furthermore the inline color style need `!important` as well to overwrite this 🙀
I could continue the trend with another `!important` rule as in https://github.com/umbraco/Umbraco-CMS/commit/bc5a3815fdd64069e1c8e7d9a5537bc00870e13d to inherit the correct color as well in `<umb-icon>` component.
However I think this would be just another hack.
Instead it should just include the icon and furthermore we don't need to use `!important` on the inline style to get the correct color.

Inherit text color from parent element

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
src/Umbraco.Web/Trees/ContentTreeController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9908
The issue here was that because the language wasn't passed, it would set the language to check with to an empty string. It would then try to find an empty string culture on the content item (which was of course not present) and add the parentheses on the name. Adding a fallback to the default language id solves this issue.
For the language picker, I had to update a bit of JavaScript code that checks if it has a variant or not. Updating this check to always check above 1 fixes the issue here. It'll still show the language picker if there is one 1 published variant and 1 unpublished variant.
How to test:
1. Use starter kit
2. Set the homepage doc type to variant by culture
3. Observe …

9908: No parentheses & language picker with only 1 language

---

src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/CreatedPackagesRepositoryTests.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageInstallationTest.cs

- Updated CreatedPackagesRepositoryTests.Update() to use Assert.Multiple so it is easyer to debug
- Updated CreatedPackagesRepositoryTests.Export_Zip()
- Updated CreatedPackagesRepositoryTests.Export_Xml()
- Updated PackageInstallationTest.Can_Read_Compiled_Package_1()
- Updated PackageInstallationTest.Can_Read_Compiled_Package_2()
- Updated PackageInstallationTest.Can_Read_Compiled_Package_Warnings()
- Run the unit test to see if they pass

v9: Implemented new asserts

---

src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs

Use the culture passed in, instead if the static Thread.CurrentThread.CurrentUICulture

Update LocalizedTextServiceExtensions.cs - use the culture parameter, instead of Thread.CurrentThread.CurrentUICulture

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10903
While optimizing some duplicate code in https://github.com/umbraco/Umbraco-CMS/pull/10762 I also changed to call `hideMenu()` method from navigationService.
However this method also do some other stuff like changing menu state.
Besides this I think it goes longer back as it originally hide backdrop in `select()` function, but may also make sense when the dialog is closed. However in copy and move action when selecting root node, the dialog isn't closed, but the backdrop is hidden.

Hide backdrop when closing/select navigation

---

src/Umbraco.Web/Compose/BlockEditorComponent.cs

If our crude JSON detection gives us a false positive, don't throw an exception if it can't be parsed as JSON
Fixes #10879
To test, follow the scenario in the related issue #10879 and then test again with this fix applied. Note the message appears in the log as well.
I left the content type as a GUID as I didn't want to add overhead in trying to resolve the content type from the GUID to find the name of the content type just so it could be logged, that seemed a bit overkill.

Cannot copy page with Block List block with property that 'looks like' JSON #10879

---

src/Umbraco.Core/PropertyEditors/DataEditor.cs

This reverts commit 990fc118cbd6df423be2107a75970a834ade1f76.
When using the _reusableEditor field to create a BlockEditorPropertyEditor 
it doesn't matter that content type cache has been invalidated (memory cache)
as the content types are also cached in a private field in the BlockEditorValues class.
Closes #10910

Revert "Optimization by returning the same instance"

---

src/Umbraco.Core/UriExtensions.cs
src/Umbraco.Web/HealthCheck/Checks/Security/HttpsCheck.cs

IsClientSideRequest() is called multiple times per request and allocates an array, then loops through all the entries in the array to do an Invariant string comparison.
This PR changes that to an invariant string dictionary lookup to avoid the array allocations.

Avoid allocating an array every call to IsClientSideRequest()

---

src/Umbraco.Core/Logging/Serilog/Enrichers/Log4NetLevelMapperEnricher.cs

Avoid creating a new string for the log level every log message. 
Each log message ends up padding the Log4Net log level, if the log level does match, the assignment of string.Empty is unused.
Avoided the padding call by including the padding in the string, allowing for compile time string interning. Moved the string.Empty assignment to the default case in the switch.

Avoid creating a new string for the log level every log message

---

src/Umbraco.Core/Runtime/MainDomSemaphoreLock.cs

Store and reuse the MainDomId, avoids having to recalculate the Hash.

Avoid generating the maindom hash twice to get the Id.

---

.devcontainer/Dockerfile

Fixes #10981
This adds and trusts a local developer certificate inside the devcontainer, which Kestrel needs to bind for https.
This fix is based on the log message you get when trying to build a fresh container:
```
Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
```

Umbraco v9 devcontainer: Generate a local certificate for Kestrel https

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
src/Umbraco.Web.UI.Client/src/views/content/assigndomain.html
src/Umbraco.Web.UI.Client/src/views/content/create.html
src/Umbraco.Web.UI.Client/src/views/content/createblueprint.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/views/listview/listview.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/views/templates/templates.html
src/Umbraco.Web.UI.Client/src/views/media/create.html
src/Umbraco.Web.UI.Client/src/views/mediatypes/views/listview/listview.html
src/Umbraco.Web.UI.Client/src/views/mediatypes/views/permissions/permissions.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html

I searched view files and found these references where mostly `<localize>` directive was self-closed, but since it is a custom HTML element it isn't a valid void-element and thus it should have a end-closing tag.

Fix self-closing tags which should have a end-closing tag

---

src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs
src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs

I've added a new parameter `urlMode` to the image cropper `.GetCropUrl()` extension methods in order to be able to select which url mode I need in that specific call, like it works now for `.Url()`.
In my case, I have the default url mode set to relative, but for things like the Open Graph image, I need it to be absolute.
I tested my changes by calling some of the extension methods from a view as follows
```
@Model.Image.GetCropUrl(1200, 620)
@Model.Image.GetCropUrl(1200, 620, urlMode: UrlMode.Absolute)
@Model.Image.GetCropUrl("crop1")
@Model.Image.GetCropUrl("crop1", UrlMode.Absolute)
```

Added url mode parameter to the GetCropUrl extension methods

---

src/Umbraco.Core/Serialization/AutoInterningStringKeyCaseInsensitiveDictionaryConverter.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/ContentCacheDataModel.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/MessagePackAutoInterningStringKeyCaseInsensitiveDictionaryFormatter.cs
src/Umbraco.Web/Umbraco.Web.csproj

This fixes #10695 
Turns out the issue was not with MessagePack, but instead with the JsonConverter used when saving the item to the cache after when updating it.
This is also why it seemingly worked the first time after booting, but once you've saved and published it, it stopped working. The fix is fairly straightforward, instead of creating a new dictionary normally, we call `Create` on the parent class which creates a dictionary with `StringComparer.OrdinalIgnoreCase`, making the dictionary case insensitive. 
* Create a document type and make it multi-language 
* Add the following to the template (thanks to the original issue create 😄 )
```html
Published with culture: @Model.IsPublished(Culture)
<br />
Published with en-US: @Model.IsPublished("en-US")
<br />
Published with lower case …
```

V8: Fix IsPublished only working with lowercase.

---

src/Umbraco.Core/Cache/IValueEditorCache.cs
src/Umbraco.Core/Cache/ValueEditorCache.cs
src/Umbraco.Core/Cache/ValueEditorCacheRefresher.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
src/Umbraco.Infrastructure/Cache/DistributedCacheExtensions.cs
src/Umbraco.Infrastructure/Services/Implement/PropertyValidationService.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/ValueEditorCacheTests.cs
src/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs
src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs

This PR introduces a ValueEditorCache, this cache will be used by the `PropertyValidationService`, meaning that we no longer create a new `valueEditor` every time something needs to be validated.  This should optimize validation for all data types, but in particular for nested content and the blocklist editor, since these calls validate on their children recursively.
To ensure that the value editors are up to date I've also added a `ValueEditorCacheRefresher` which listens to `DataTypeSavedNotification` and `DataTypeDeletedNoticiation`, and clears the cache accordingly. 
Since everything should be the same it can be kind of hard to test, but a good thing to test is to try and create a document type with some custom data types like blocklist and nested content, create a content node, and …

V9: Reuse value editors for validation

---

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js

The ChooseMediaTypeDialog is shown even if there are no queue items, for example due file errors. 
Checking the queue lenght in _requestChooseMediaTypeDialog prevents showing the dialog unnecessary.
When a user uploads an file that exceeds the maxFileSize an error is shown but also the ChooseMediaTypeDialog.
Checking the queue length before showing prevents this.
To test: upload an file to media via the dropzone that exceeds the maxFileSize.

Check if umbFileDropzone has queued items before showing ChooseMediaTypeDialog

---

src/Umbraco.Core/IO/PhysicalFileSystem.cs

- [X ] I have added steps to test this contribution in the description below
Fixes #10912 
This PR fixes a problem where GetRelativePath fails on Unix systems. It resolves a fullPathOrUrl as a Path before trying to resolve it as a URL. This is done by simply moving the path handling code above the url handling code.
The following tests were run and passed:
- From Umbraco.Tests.Integration I ran Umbraco.Cms.Tests.Integration.Umbraco.Core.IO.FileSystemsTests
- All tests in Umbraco.Tests.UnitTests project
This bug was showing up when choosing a thumbnail for a block list. Here it can be seen working as expected on MacOS
And I also tested on a windows system, where the results look also as expected.

Fix PhysicalFileSystem.GetRelaitvePath for *nix

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

This PR updates the settingsData to contain the correct contentTypeKey for a settingsModel if it has been changed after a value has been saved.
How to test:
See testing details on the issue: https://github.com/umbraco/Umbraco-CMS/issues/10373#issuecomment-906490036
fixes #10373

Block List Editor - update settingsData with correct contentTypeKey when settings model is changed

---

src/Umbraco.Core/PropertyEditors/ValueConverters/TagsValueConverter.cs

Avoid array allocations for splitting csv tags by using existing array.

Avoid array allocations for splitting csv tags

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.prevalues.html
src/Umbraco.Web/PropertyEditors/MultiUrlPickerConfiguration.cs

This PR is a suggestion to add a configuration option for the size of the overlay width when using the multiurlpicker - Currently it's always displayed using the small width overlay. Recently I have found it a wee bit frustrating to work with since it can be hard to actually see the full url in the link input field and then it hit me - With the block list editor we can define whether the size should be "Small", "Medium" or "Large" and I figured why not do the same for the multiurlpicker property editor as well? So therefore I made this PR enabling us to define the desired size - What do you think about the idea?
If one does not change the configuration the size defaults to "small".
Below you can see a GIF illustrating how it all works 👍🏻

Suggestion: Make the overlay size width in multiurlpicker configurable

---

src/Umbraco.Core/Constants-Web.cs
src/Umbraco.Core/HealthChecks/NotificationMethods/EmailNotificationMethod.cs
src/Umbraco.Core/Mail/IEmailSender.cs
src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
src/Umbraco.Core/Notifications/SendEmailNotification.cs
src/Umbraco.Infrastructure/Mail/EmailSender.cs
src/Umbraco.Infrastructure/Services/Implement/NotificationService.cs
src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
src/Umbraco.Web.BackOffice/Controllers/UsersController.cs

Without this there is no way to handle the `SendEmailNotification` when it is triggered (currently only for user invites) to know what the email is for. It is not reasonable to inspect the subject or message body to see if the notification should handle it or not because those things are dynamic based on the current user's culture.
This is just a simple way to know what type of email it is for.

Updates email sender to have some metadata

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

After the merge of the tabs branch, an extra close button has shown up for the split view. This PR removes that one.
The PR also adds a helper text to the direct properties dropzone.

Tabs fixes: Remove the extra split view close button + Add helper text to properties dropzone

---

src/Umbraco.Core/Persistence/IUmbracoDatabaseFactory.cs
src/Umbraco.Core/Persistence/UmbracoDatabaseFactory.cs
src/Umbraco.Core/Runtime/CoreRuntime.cs

1. Set a connectionString to a non-existing SQL CE database
2. Enable unattended install
3. See that the  empty SQL CE database is created before unattended install will create the schema
When using unattended install an empty database must be manually created before you start up the application. 
This PR will automatically create an empty SQL CE database on the location configured in the connectionString if the provider name is "System.Data.SqlServerCe.4.0" before the unattended install tries to create the schema.

Automatically create emtpy SQL CE database with unattended install

---

src/Umbraco.Web.UI.Client/src/less/components/check-circle.less

I noticed the "Selected" icon was showing a bit misplaced in the current release and had a stab at the stylesheet to ensure it's centered and showing like it used to 👼🏻 
**Before**
**After**

Color swatch "selected" state - Icon looks weird

---

src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs

If there's an existing issue for this PR then this fixes #10609
This PR fixes #10609
In v7 the id for the default admin user is 0, while in v8 it's -1.
The bug made it impossible to login from v8 to a v7 DB in order to perform an upgrade.
Haven't verified the fix yet, hence the "Draft pull request"

Removed check for default 

---

src/Umbraco.Web/Editors/AuthenticationController.cs
src/Umbraco.Web/Security/GetUserSecondsMiddleWare.cs

1. Login to the backoffice
2. Look for the `Cache-control` response header on requests made to the `AuthenticationController` (`/umbraco/backoffice/UmbracoApi/Authentication/`)
3. Verify the value is always `no-store, must-revalidate, no-cache, max-age=0`
Example for the `IsAuthenticated` request:
Example for the `GetRemainingTimeoutSeconds` request:
Fixes #11011 
I added the `[DisableBrowserCache]` attribute on the `AuthenticationController` because the controller doesn't inherit from `UmbracoAuthorizedApiController ` as @Shazwazza mentionned in the linked issue.
For the `GetRemainingTimeoutSeconds` request specifically, I added the missing parts of the `Cache-control` header manually in the string array that already existed.
So now, when a caching server is setup in front of an Umbraco …

Don't cache AuthenticationController calls including GetRemainingTimeoutSeconds

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

This fixes #10644.
The problem here has to do with the way `System.Text.Json` serializes `Dictionary<string, object>`, to fix this my goal was to instead use Newtonsoft to serialize the grid editor values. 
After looking around for a while I think that using a `IResultFilter` is the best approach to achieve this. However I did notice an additional thing when looking into this, the response from `GetGridConfig` does not contain the angular protection bit `)]}',`, that all other calls like `GetById` has. This seems like a mistake to me since this should be a resource for angular and there should have it.
In this PR I'm currently just applying the `AngularJsonOnlyConfiguration` to the `GetGridConfig`. this means that the config values now serialize correctly (no more [[]]), and that the …

V9: Fix grid editor config values in package manifest

---

src/Umbraco.Core/Routing/DomainUtilities.cs

Just a small improvement to #10845 to make sure we use case insensitive comparison of cultures.

Improvement for #10845 - Changed culture comparison of domain to be case insensitive

---

src/Umbraco.Core/Logging/DisposableTimer.cs
src/Umbraco.Core/Logging/ProfilingLogger.cs

This fixes https://github.com/umbraco/Umbraco-CMS/issues/11033
Turns out we weren't sending our startMessageArgs in the constructor, while digging i also found that even if we were sending the
args, we wouldn't see the message in the log, cause it was LogLevel Debug, so i corrected it to LogLevel Information so it will display when using IProflingLogger
- Updated call to correctly have startMessageArgs & endMessageArgs
- Updated LogLevel so it correctly is also LogInformation so you can actually see the logmessage
- Set up a NotificationHandler to alert you when saving content
I used: 
```
public class NotificationTester : INotificationHandler<ContentTypeSavedNotification>
{
private IProfilingLogger _profilingLogger;
public NotificationTester(IProfilingLogger profilingLogger)
{ …
```

v9: Fixed Profilling logger to correctly send args in call

---

src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
src/Umbraco.Infrastructure/Logging/Serilog/UmbracoFileConfiguration.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/10965
Added support for configuring the Umbraco File "Sink" in appsettings.
```json
{
"Serilog": {
"WriteTo": [
{
"Name": "UmbracoFile",
"Args": {
"RestrictedToMinimumLevel": "Warning",
"FileSizeLimitBytes": 1073741824,
"RollingInterval" : "Day",
"FlushToDiskInterval": null,
"RollOnFileSizeLimit": false,
"RetainedFileCountLimit": 31
}
}
]
},
}
```
This is not handled by default, because the UmbracoFile  "Sink" is not just a regular File sink due to performance and file-locking concerns. 
Sadly this means reading the serilog configuration ourself. A cool future cycle hack could be to implement the UmbracoFile as a real Sink, and have that in an assembly containing name "Serilog" so it would be picked up by default.
- Change the logging …

Added support for configuring the UmbraocFile "sink", using IConfiguration

---

build/templates/UmbracoPackage/.template.config/template.json
build/templates/UmbracoPackage/UmbracoPackage.csproj
build/templates/UmbracoPackage/build/UmbracoPackage.targets

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/10641
- Fixed issues with invalid namespace, when using characters like "-"
- Fixed issues with invalid characters in MSBuilder property names, like "."
- Build the templates using build.ps1
- Uninstall existing templates: `dotnet new -u Umbraco.Templates`
- Install new templates: `dotnet new -i Umbraco.Templates::9.0.0-* --nuget-source={Repo Path}\build.out`
- Replace {Repo Path} with your repo path
- Install the Umbraco Package template using crazy names, like:
- Umbraco.MyPackage
- Umbraco.MyPackage.a12313asd
- U-m-b-r-a-c-o
....
- Ensure the build/*.targets are valid.
- Create a class and ensure the namespace are valid

Fixes a couple of issues with the Umbraco Package dotnet new template.

---

src/Umbraco.Web.UI.Client/src/views/datatypes/create.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html

PR: https://github.com/umbraco/Umbraco-CMS/pull/10983 introduces a bug where you can't create folders for doctypes and data types anymore.
I have updated the view to use `ng-show` instead of `ng-if.` Ng-if introduces a new scope that breaks the relation to the form. I have also updated the focus directive to use `focus-when` instead of `auto-focus`. It makes it possible to control when a field should have focus.
How to test:
* Make sure the input field has focus when you create a new folder for doctypes and datatypes
* Make sure you can save and the folder gets created

Fixes folder creation for doc, data, and media types

---

src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
src/Umbraco.Web.UI.Client/test/unit/common/services/content-type-helper.spec.js

When converting a group to a tab, we need to change the group sortOrder to fit into the tab's sortOrder.
This PR sets the correct sort order on the new tab.
How to test:
- Create a doctype with a couple of groups
- Drag one of the groups to the "Convert to Tab"-area next to the compositions button. It is only visible when you drag a group.
https://user-images.githubusercontent.com/6078361/132348005-608d38e4-74ae-4618-a08e-2dcb7b15e0f7.mp4

Set correct sort order on converted tab

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

This PR fixes a bug where you could only drag one group to the generic tab.
It also adds an error notification when you can't drag a group to the generic tab because it will end up with the same alias as a tab.
How To Test:
* set up a doctype with 1 tab and multiple groups. The tab and one of the groups should have the same name, ex: "Content".
* Make sure you can move more than one group to the Generic Tab
* Make sure you can't move the "Content" group to the generic tab
https://user-images.githubusercontent.com/6078361/132518083-86f56a95-378b-4d65-b85f-ffaa44de7eb3.mp4

Fix move group to Generic tab only work once

---

src/Umbraco.Examine.Lucene/LuceneIndexDiagnostics.cs
src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndexDiagnostics.cs
src/Umbraco.Examine.Lucene/UmbracoMemberIndex.cs
src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
src/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexInitializer.cs
src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj

The latest Examine version has some API breaking changes - namely it shouldn't have been relying on IOptionsSnapshot and instead IOptionsMonitor.

Updates to latest Examine version

---

src/Umbraco.Web.Common/Extensions/UmbracoApplicationBuilder.Identity.cs

Added friendly extension method to replace the backoffice Usermanager.
- Try to implement a custom backoffice usermanager
```cs
public class CustomBackOfficeUserManager : BackOfficeUserManager
{
public CustomBackOfficeUserManager(IIpResolver ipResolver, IUserStore<BackOfficeIdentityUser> store, IOptions<BackOfficeIdentityOptions> optionsAccessor, IPasswordHasher<BackOfficeIdentityUser> passwordHasher, IEnumerable<IUserValidator<BackOfficeIdentityUser>> userValidators, IEnumerable<IPasswordValidator<BackOfficeIdentityUser>> passwordValidators, BackOfficeErrorDescriber errors, IServiceProvider services, IHttpContextAccessor httpContextAccessor, ILogger<UserManager<BackOfficeIdentityUser>> logger, IOptions<UserPasswordConfigurationSettings> passwordConfiguration, IEventAggregator …
```

Added SetBackOfficeUserManager extension method to IUmbracoBuilder

---

src/Umbraco.Web.BackOffice/Controllers/EntityController.cs

Added missing actions
- Use mediapicker 3
- upload image into a folder
- Choose that image on a content
- Go to the edit image and " Open in Media Library"
- Verify it works and the `GetAncestors` are called with a guid and not a int.

V9: Fixed missing action

---

src/Umbraco.Core/Events/INotificationAsyncHandler.cs
src/Umbraco.Core/Events/INotificationHandler.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Mail/EmailSender.cs

This fixes an issue where we weren't properly handling the detection of existing `SendEmailNotification` handlers. 
* DI by default wasn't using the ctor with the most params
* We weren't detecting async handlers
* I've changed all usages of AddUnique to AddSingleton in the UmbracoBuilder.CoreServices.cs (AddUniqe should really be marked as obsolete).

Fixes email handler detection

---

src/Umbraco.Core/PropertyEditors/MediaUrlGeneratorCollection.cs
src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyEditor.cs

After installing the Starter Kit on a clean `v9/dev` installation (`dotnet add package Umbraco.TheStarterKit --version 9.0.0-rc001`), the front-end throws an `ArgumentException` on every page that tries to get the media path from an Image Cropper:
```
System.ArgumentException: path cannot be null or whitespace (Parameter 'path')
at Umbraco.Cms.Core.Routing.DefaultMediaUrlProvider.AssembleUrl(String path, Uri current, UrlMode mode)
at Umbraco.Cms.Core.Routing.DefaultMediaUrlProvider.GetMediaUrl(IPublishedContent content, String propertyAlias, UrlMode mode, String culture, Uri current)
at Umbraco.Cms.Core.Routing.UrlProvider.<>c__DisplayClass19_0.<GetMediaUrl>b__0(IMediaUrlProvider provider)
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at …
```

Fix Image Cropper media path parsing

---

src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs

This fixes an issue where if you specify your umbraco application URL in the appsettings, it would never actually get set as the `AspNetCoreHostingEnvironment.ApplicationMainUrl`, causing `TouchServerTask` to log `No umbracoApplicationUrl for service (yet), skip.` over and over and over again indefinitely.
This was simply just an oversight, in `EnsureApplicationMainUrl` we simply return if `_webRoutingSettings.CurrentValue.UmbracoApplicationUrl is not null` assuming it has been set, however it hadn't, to remedy this I've added a check in the constructor where we set the URL if it's specified in the settings.
Manually specify the UmbracoApplicationUrl in appsettings.json
```json
"WebRouting": {
"UmbracoApplicationUrl": "https://localhost:44331/umbraco"
}
```
Ensure that `TouchServerTask` …

V9: Fix ApplicationMainUrl not being set from appsettings.json

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Install/InstallHelper.cs
src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseUpgradeStep.cs
src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
src/Umbraco.Infrastructure/Runtime/SqlMainDomLock.cs
src/Umbraco.Tests.Integration/Testing/TestUmbracoDatabaseFactoryProvider.cs
src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs

The issue was discovered when testing Umbraco Id. If you have an existing install and there is a pending Umbraco migration (upgrade), but you clear out the connection string to force a new install screen, fill out the existing connection string details, it all works and redirects to the back office. This will throw exceptions because the runtime state is in an upgrade state (which is fixed in #11064) but if you then logout and try to log in with an active OAuth provider, it means there is a redirect outside of Umbraco and back again and you'll end up back on the installer screen - but it will not show you the upgrade screen, instead it shows you the normal install screen. This is because we are not using IOptionsMonitor for connection string settings which means it's already read the …

Fixes reading connection strings after install

---

src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/10650
Added a redirect to root (which redirects to installer) if you are not in runtime state = Run.
- Open backoffice
- Add a fake migration in Umbraco Plan
- Reboot
- Refresh browser in backoffice 
-  verify you are redirected to the upgrader.

Add redirect to /umbraco if you are not in run state.

---

src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs
src/Umbraco.Infrastructure/Search/IUmbracoIndexingHandler.cs
src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.Content.cs
src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.Media.cs

Currently when the recycle bin is empty, it is going to individually delete each item from the index. This is going to cause tons of allocations in Umbraco for DeferedDeleteIndex objects for each item and then down within Examine is going to process each one individually instead of just doing it in bulk. There will be a lot of allocations made there too along with a bunch of extra and unnecessary threads.
@nul800sebastiaan I haven't looked at v8 but it's most likely doing the same thing and this logic should be back ported.

Fixes empty recycle bin performance with indexing

---

src/Umbraco.Core/CustomBooleanTypeConverter.cs
src/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/TryConvertToTests.cs

Fixes #9661 boolean conversion issue where the property editor is passing in "No" or "Yes" for the value but its not getting converted. The fix is easy to just allow for this conversion with our custom boolean converter.
This may need to be backported, though if this was an issue in v8 we'd surely know about it since it would mean you couldn't lock or unlock members.

Fixes #9661 boolean conversion

---

src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs

Fix message template to not mix string interpolating and formatting. Message template parameter gets cached, using $"" will create more unique message templates, increasing memory and cpu consumption.

Fix message template to not mix string interpolating and formatting.

---

src/Umbraco.Web/HealthCheck/Checks/Security/BaseHttpHeaderCheck.cs

Security header health check messages in 8.15+ are not retrieving their localised values, this is due to the changes made here https://github.com/umbraco/Umbraco-CMS/commit/dd111226090642cd6777630ff45e432ce8349656#diff-4e1e06ab6889463c603c0face1da054732d42dfea0e81aad113191b2ba048980R90 
This PR fixes the interpolation oversight

Fix string interpolation for health check messages

---

src/Umbraco.Core/Umbraco.Core.csproj

The project include extensions for `ContentService` and ` MediaService` to get by `Udi[]`.
However `MediaServiceExtensions.cs` wasn't included in project and thus not compiled.
Originally included in PR https://github.com/umbraco/Umbraco-CMS/pull/9465 but should be safe to include, so the extension is available to use. It was orignally added in https://github.com/umbraco/Umbraco-CMS/commit/d54658009cdeb676257747bf0992599feee24554#diff-0703ef93a614d4373794998ca03f46e6c6703b6abe0cdfaecf5642f36f0ea30e, but actually not used anywhere in core. However in PR https://github.com/umbraco/Umbraco-CMS/pull/9465 it is used to fetch media by `int[]`, `Guid[]` and `Udi[]`.
Furthermore it would also be great to look at this PR https://github.com/umbraco/Umbraco-CMS/pull/9467 we can fetch member groups …

Include MediaService extensions in project

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

This updates:
- jQuery from 3.5.1 to 3.6.0 https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/
- AngularJs from 1.8.0 to 1.8.2 - https://github.com/angular/angular.js/blob/master/CHANGELOG.md
From the changelogs I can't see any conflicts that we would run into so should be good.

Updating Angular and jQuery to the latest available version

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/overlaysize.controller.js
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/overlaysize.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/markdowneditor/markdowneditor.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/markdowneditor/markdowneditor.prevalues.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
src/Umbraco.Web/PropertyEditors/MarkdownConfiguration.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerConfiguration.cs
src/Umbraco.Web/PropertyEditors/RichTextConfiguration.cs

... instead of redundant prevalue editor for each property editor.
So instead of three redundant prevalue editors, we just need one!
If we later need only to show e.g. "Small" and "Medium" options in prevalues for a specific property editor, we can configurate the prevalue editor further or add a specific prevalue editor for that property editor. But it most scenarios we don't need a specific prevalue for a property editor, but one that can be re-used in other property editors and/or by package developers.
I have renamed the property from "Overlay Size Width" to just "Overlay Size" to keep it simple and instead use the description property to add a more detailed explanation.
I don't like that we now have redundant prevalue editors for each property editor - we should have a global …

Introduce overlaysize prevalue editor

---

src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs

Cloudflare adds the header "Server" with the value "cloudflare". As this header cannot be removed it should be excluded from the healthcheck excessive headers check - https://community.cloudflare.com/t/how-to-remove-server-cloudflare-header/133417
All UmbracoCloud sites that have been migrated to the new infrastructure currently show this healthcheck warning.

Exclude "Server" header from excessive check if the value is "cloudflare"

---

src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less

In the v8.16 release I noticed that the grid labels looked a bit "cramped" - I'm not sure what is causing the issue but it needs to have `top: 15px;` in order to look correct, which is what this PR addresses.
**Before**
**After**

Grid: labels offset fix

---

src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.less

Previous I added checkered background to image cropper preview in https://github.com/umbraco/Umbraco-CMS/pull/10621
However I noticed it was an issue in Media Picker 3 as well and pretty much impossible to see a white SVG, GIF or PNG.
It also better visualize when a transparent image is selected, e.g. a SVG.
Furthermore it center the image vertical and horizontal.
**Before**
**After**

Media picker 3 preview with checkered background

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbprogressbar.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbprogresscircle.directive.js
src/Umbraco.Web.UI.Client/src/less/components/umb-progress-bar.less
src/Umbraco.Web.UI.Client/src/less/components/umb-progress-circle.less
src/Umbraco.Web.UI.Client/src/views/components/umb-progress-bar.html

This PR stream line `<umb-progress-bar>` and `<umb-progress-cirlcle>` to be more consistent with percentage, size and color. Furthermore `color` is optional in `<umb-progress-cirlcle>` component.
Dashboard as shown in screenshot:
[MyDashboard.zip](https://github.com/umbraco/Umbraco-CMS/files/7035029/MyDashboard.zip)

Streamline <umb-progress-bar> and <umb-progress-circle>

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js

Fixes: #11070
The PR sets the content type form to dirty when adding a new tab, deleting a tab, adding a group, and deleting a group.
How to test:
* Add tab (don't enter a name) - navigate to another node. Make sure the discard changes dialog is shown
* Do the same for delete tab, add group, delete group.

Set content type form to dirty when add tab, delete tab, add group, and delete group

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediaentryeditor/mediaentryeditor.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediaentryeditor/mediaentryeditor.less
src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-gravity.html

With Media Picker 3 and opening e.g. a SVG image (which doesn't have dimensions) I noticed the image preview is quite small (limited to max 200px with and 200px height).
**Before**
**After**

Remove restricted image size when opening media

---

src/Umbraco.Core/Constants-SystemDirectories.cs

Added this so we don't need to have hard-coded strings in any dependent project that needs access to this folder.

Added a constant for reference to the umbraco/Licenses folder.

---

build/templates/UmbracoProject/appsettings.Development.json

Remove condition around connection string needed to have all unattended arguments in dotnet new template set such as friendly name, email and password just to set a connection string.
This is for Umbraco cloud team as they want to set a connection string with the dotnet new template but not set the rest of the unattended arguments
`dotnet new umbraco --name mynewproject --SqlCe --connection-string "Data Source=|DataDirectory|\\Umbraco.sdf;Flush Interval=1;"`

V9 dotnet new template - allow just setting connection string on its own

---

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html

We don't get the invalid files from the uploader as part of the "files"-array anymore but instead as a separate array. I am not sure when this has changed.
This PR handles the new array of invalid files. It combines it with the files array, so everything works the way it used to.
After the PR is applied the errors are back in the UI.
Relates to #10920

Show UI errors for invalid files in media upload

---

build/templates/UmbracoProject/.template.config/dotnetcli.host.json
build/templates/UmbracoProject/.template.config/ide.host.json
build/templates/UmbracoProject/.template.config/template.json
build/templates/UmbracoProject/appsettings.Development.json
build/templates/UmbracoProject/appsettings.json

This is required for Cloud to be able to create a project with the necessary configuration for the custom "no nodes" page that's presented when you first restore a project.
To Test (at least this is how I did it):
- Check out the PR and amend your local `src\Directory.Build.props` file to create a new version, e.g. `<InformationalVersion>9.0.0-rc003a</InformationalVersion>`
- Run `builf\build.ps`
- Copy the resulting `Umbraco.Templates.9.0.0-rc003a.nupkg` from `build.out` into a local folder set up as a NuGet feed
- Run:
```
dotnet new -i Umbraco.Templates::9.0.0-rc003a
dotnet new umbraco --name TestWithNoNodes --no-nodes-view-path "/my-custom-path"
cd .\TestWithNoNodes\
code .
```
And check that the `appSettings.Development.json` file has the appropriate setting for …

Added option to set NoNodesViewPath in umbraco template.

---

build/templates/UmbracoProject/.template.config/template.json
build/templates/UmbracoProject/appsettings.Development.json

Fixes issue with dotnet new template if you did not specify a connection string it was adding an empty one in appsettings.dev
----
To Test (at least this is how I did it):
- Check out the PR and amend your local `src\Directory.Build.props` file to create a new version, e.g. `<InformationalVersion>9.0.0-rc003abc</InformationalVersion>`
- Run `build\build.ps`
- Copy the resulting `Umbraco.Templates.9.0.0-rc003abc.nupkg` from `build.out` into a local folder set up as a NuGet feed
- Run:
```
dotnet new -i Umbraco.Templates::9.0.0-rc003abc
dotnet new umbraco --name NoConnectionString"
cd .\NoConnectionString\
code .
```
And check that the `appSettings.Development.json` file does not include `ConnectionStrings:umbracoDbDSN`
Retest with the following and verify something does get set for the …

Fixes issue with dotnet new template if you did not specify a connection string

---

src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html

…has a proper true/false value
Playing around with the new tabs I by coincidence noticed that the `aria-selected` value was rendering `{tab.active}` instead of either `true/false` due to the expression missing a set of extra curly braces so the code would read `aria-selected="{{tab.active}}"` in order to render `true/false`.

Bugfix: Accessibility in Tabs - Ensure the selected tab is properly exposed to aria-selected

---

src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/11116
The unique ID/key of property groups wasn't posted back to the server when saving document, media or member types, which caused it to re-generate a new GUID in the database. This fix ensures the existing `key` is used by not filtering it out of the 'save model' (the `alias` and `type` fields were already correctly added here).
Testing can be done by following the reproduction steps on the linked issue.

Add property group key to save model

---

src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11123
Initializing the `IVariationContextAccessor `if the `UmbracoRequestMiddleware`. This is similar to before where it was initialized when `UmbracoContext `was created..
In case it is needed, the `PublishedRouter` will update for the website-requests.
The bug was introduced in RC2, when `IVariationContextAccessor ` was removed from UmbracoContext.

Initializing the IVariationContextAccessor in the UmbracoRequestMiddleware.

---

src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformerTests.cs
src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Website/Routing/NotFoundSelectorPolicy.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

There are some issues with our current implementation which make it almost impossible for other DynamicRouteValueTransformer to play nicely with Umbraco especially those that integrate with Umbraco using `UmbracoRouteValues` (i.e. Articulate).
* UmbracoRouteValueTransformer as singleton - this will save memory, there only needs to be one instance and it doesn't need to be scoped. It was only scoped based on some old example code in the aspnet repo.
* Return `null` when we don't match. See https://github.com/dotnet/aspnetcore/pull/36653.
* Don't execute if there is already `UmbracoRouteValues` available. In this case it would mean that another `DynamicRouteValueTransformer` has already executed and routed an Umbraco route and we shouldn't overwrite it.
* Don't modify the passed in …

UmbracoRouteValueTransformer fixes

---

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less

I think the check icon in `<umb-checkbox>` with recent changes was a bit too large compared to the size of the surrounding box.
I have adjusted this a bit.
**Before**
**After**

Adjust icon size in umb-checkbox

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

I'm a big fan of the Block List Editor! And especially love how powerful the label templating feature is, allowing us to give our editors more context. Where a block content has a title / heading property we usually opt for this as our label.
However, sometimes properties are optional... and therefore the label can be empty...
The way to combat this is to have a condition in the label template `{{title || 'My Block Name'}}` but this means hardcoding content type names...
This PR adds a null check around the result of the label interpolator, and if there is no output falls back to the default value: the block list content type name.
There are some cases where hardcoding the content type names is necessary, such as `Block name: {{title}}`. This PR also introduces a variable to easily access …

Falling back to contentTypeName when Block List label is empty

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
src/Umbraco.Web/PropertyEditors/NestedContentController.cs

This PR fixes the rendering of nested content after the tabs feature has been added. To prevent any breaking changes, we had to limit the allowed nested content groups to generic groups. Tabs and groups inside a tab are not supported in nested content. The Block List Editor can be used if tab support is needed.
**How to test:**
* Create an element type with a generic group, a tab, and a group inside the tab
* Set up a doctype with nested content.
* Make sure you can only select the group from "Generic" in nested content.
* Make sure nested content renders correctly in the content section. 
fixes #11114

Fixes Nested Content not rendering

---

src/Umbraco.Core/Packaging/InstallationSummary.cs
src/Umbraco.Core/Packaging/PackageDefinition.cs
src/Umbraco.Core/Packaging/PackagesRepository.cs
src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
src/Umbraco.Infrastructure/Packaging/PackageInstallation.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs

When a package migration tried to save macro partial views from an embedded package.xml file (like in The Starter Kit), it directly used `File.WriteAllText()` instead of the `IFileService.SavePartialViewMacro()`. If the `Views/MacroPartials` directory didn't exist yet, this also caused a `DirectoryNotFoundException` to be thrown (which would cause a `BootFailedException` when the migrations are automatically run).
Testing steps:
1. Before applying this PR on a clean install, remove the `Views/MacroPartials` directory and try to install The Starter Kit (`dotnet add package Umbraco.TheStarterKit --version 9.0.0-rc002`): this will throw an exception while booting up;
2. Manually create the `Views/MacroPartials` directory and start the site: the package migration will now successfully run and …

Use IFileService to save macro partial views in package migration

---

src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Security/BackOfficeUserStoreTests.cs

Setting IsApproved on the `BackOfficeIdentityUser` didn't persist when saving the member. This fixes that and adds an integration test for it.

Fixes persisting the IsApproved for users

---

src/Umbraco.Core/PropertyEditors/MediaPicker3Configuration.cs

Fixes #11150 V9: MediaPicker3 casing incorrect

Fixes #11150 V9: MediaPicker3 casing incorrect

---

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/hidden.html

At some point the hidden prevalue editor has changed, so it set name attribute twice and not id attribute.
Strange nobody has noticed this since in was added in https://github.com/umbraco/Umbraco-CMS/commit/5b289a4971ccb0f6d431377e9e199c6d27bb2839#diff-5712c2b4c44f9e8368d7437b866a916290dfcd5814e062c74ed99362329ca19eR1
It seems the latter one would be ignored https://stackoverflow.com/a/26341866/1693918 .. but you never know if that's the case in future browsers.

Fix incorrect attribute in hidden prevalue attribute

---

src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less

With the current release of version 8.16 I noticed the "Add button" in the grid was no longer a perfect square after the icon was converted to using the `<umb-icon>` directive. That's addressed with a few tweaks to the `.iconBox` class in this PR.
Furthermore some unused classes and uneeded CSS properties have been removed 😃 
**Before**
**After**

Grid: Add button styling fix

---

src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
src/Umbraco.Web.UI.Client/src/views/media/apps/content/content.html
src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html

fixes #11100
Properties from tabs were rendered twice. One for direct properties for a tab and one for groups because they are part of the groups' array. This PR prevents a group to be rendered in the groups' array if it is a "tab".
Multi URL Picker listens for a form submit event and sets the value based on a render value. Because the property is rendered twice, when it is a direct property on a tab, it resets its own value. 
The reset only happens in the Block List editor because of how it syncs its values. I have added the fix to the content, media, and members section for performance reasons. We don't want more properties in the DOM than needed.
How to test:
* See the issue for testing instructions for the bug. 
* Please also do some "general" testing of tabs and groups in content, …

Fix Multi URL Picker in Block List Editor

---

src/Umbraco.Tests.AcceptanceTest/cypress/integration/Users/userGroups.js

- Updated Usergroup test to get a better element, and made the timeout larger to account for slower run times on azure
- Open up umbraco 
- Go to Umbraco.Tests.AcceptanceTest
- open up the cmd and run `npm install` and `npm run test`

v9: fixed flaky usergroup test

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/UmbracoServerColumn.cs
src/Umbraco.Infrastructure/Persistence/Dtos/ServerRegistrationDto.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRegistrationRepository.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/NPocoTests/NPocoBulkInsertTests.cs

Following on from https://github.com/umbraco/Umbraco-CMS/pull/10480 In this PR I added a migration for isMaster column to isSchedulingPublisher in UmbracoServer table
Creating this as a draft PR for now as my local v9 is having problems so I've not yet verified it works

Add migration for isMaster column to isSchedulingPublisher in UmbracoServer table

---

src/Umbraco.Core/ContentApps/ContentTypeDesignContentAppFactory.cs
src/Umbraco.Core/ContentApps/ContentTypeListViewContentAppFactory.cs
src/Umbraco.Core/ContentApps/ContentTypePermissionsContentAppFactory.cs
src/Umbraco.Core/ContentApps/ContentTypeTemplatesContentAppFactory.cs
src/Umbraco.Core/PropertyEditors/ListViewConfiguration.cs
src/Umbraco.Web.UI.Client/gulp/tasks/views.js
src/Umbraco.Web.UI.Client/gulp/tasks/watchTask.js
src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/users/changepassword.directive.js
src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.controller.js
src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
src/Umbraco.Web.UI.Client/src/views/dataTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/dataTypes/datatype.edit.controller.js
src/Umbraco.Web.UI.Client/src/views/dataTypes/rename.html
src/Umbraco.Web.UI.Client/src/views/documentTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/documentTypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/documentTypes/rename.html
src/Umbraco.Web.UI.Client/src/views/mediaTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/mediaTypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/mediaTypes/rename.html
src/Umbraco.Web.UI.Client/src/views/memberTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/memberTypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialViewMacros/create.controller.js
src/Umbraco.Web.UI.Client/src/views/partialViews/create.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js

Fixes: #10937
- When copying the static files into `wwwroot/umbraco` through gulp tasks, we were changing all filenames to lower case;
- There were places in the code where the file references used were with incorrect casing;
- Now we will use the names that are chosen in the **Umbraco.Web.UI.Client** project - we will no longer rename them.
- A potential test scenario is described in #10937
❗ remember to run `npm run build` as there are gulp changes.

V9: Fix incorrect static filenames references 

---

src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs

Fixes #11118 
Adds the `System.Diagnostics.CodeAnalysis.MaybeNull` attribute on composition/mixin properties so nullability can be determined when using Nullable Reference Types in a project.
Before:
After:
To test:
1. Enable SourceCode/SourceCodeAuto mode for ModelsBuilder
2. Add a composition with a nullable property type to a doctype.
3. Generate models.
4. nullable property type should have the `MayBeNull` attribute applied.

add MaybeNull attribute to mixin properties

---

src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformerTests.cs
src/Umbraco.Web.Common/Security/ConfigureMemberCookieOptions.cs
src/Umbraco.Web.Website/Routing/PublicAccessRequestHandler.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

Fixes #11189 + #11183
The problem was with a previous fix to route hijacking for members. Which meant the protected page would continue to redirect. That is because the auth middleware wasn't executing yet since our transformer runs first. So to fix, we force the auth for members to run when it's a protected page.
This also just ensures that when a member signs in, that the current HttpContext.User is assigned.
For 11183, the problem was a change in returning null where I presumed if there was no published content we would assume it's a 404. I didn't take into account that a finder would just redirect. So the code changes now check exactly for this.
* Makes sure public access works as expected
* Make sure you can still hijack routes for all public access pages 
* Make sure that the …

Fixes #11189 - protected content not working

---

build/NuSpecs/build/Umbraco.Cms.StaticAssets.targets

Fixes issue #11215 when using `Rebuild` option in Visual Studio/msbuild where every second rebuild would fail due to missing static asset files
msbuild output prior to this change:
```
1>Target _CopyOutOfDateSourceItemsToOutputDirectoryAlways:
1>  Microsoft.Common.CurrentVersion.targets(4996,5): error MSB3030: Could not copy the file "C:\Umbraco9Test\umbraco\config\appsettings-schema.json" because it was not found.
1>  Microsoft.Common.CurrentVersion.targets(4996,5): error MSB3030: Could not copy the file "C:\Umbraco9Test\umbraco\config\lang\cy.xml" because it was not found.
1>  Microsoft.Common.CurrentVersion.targets(4996,5): error MSB3030: Could not copy the file "C:\Umbraco9Test\umbraco\config\lang\en.xml" because it was not found.
1>  Microsoft.Common.CurrentVersion.targets(4996,5): …
```

Copy static assets during BeforeBuild target to fix Visual Studio "rebuild" failures

---

src/Umbraco.Core/Runtime/MainDom.cs
src/Umbraco.Core/Runtime/SqlMainDomLock.cs
src/Umbraco.Web/UmbracoApplication.cs

There are some cases where there is a complex hosting strategy and folks want a readonly database and are hosting on Azure. In that case, it is not entirely possible to have a readonly Umbraco database because SqlMainDom is required and part of that requirement is to have read/write access to the umbraco key value table.
This PR allows for the default MainDom to be replaced and to allow for an SqlMainDomLock to use an alternate connection string so that a separate read/write database can be used.
This is specifically regarding these docs: https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/Load-Balancing/flexible-advanced#front-end-servers---read-only-database-access
> SQL Server Replica databases cannot be used as they are read-only without replacing the default …

Allows replacing MainDom with alternate DB

---

src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11221.
While testing 8.17 RC1 we noticed all property group keys were re-generated on every save, because they weren't posted back to the server (which caused issues in Umbraco Deploy). This was fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/11121 that was part of 8.17 RC2 (and the final 9.0.0 release).
One minor oversight/regression was that when you added properties to an inherited tab or group, we can't use the same id/key, as it needs to store that property into a new group that's local to the content type (and not the composition). This caused an exception while trying to save the new local group with the same uniqueId/key as the group from the composition.
This PR ensures …

Remove inherited property group id/key when local properties are added

---

src/Umbraco.Core/Udi.cs
src/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs

This issue raised this this should resolve is [here](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/72), where it seemed to matter whether or not a template had a master template defined or not as to whether you could successfully deploy content.
After a bit of digging I found that Deploy was reporting a schema mismatch between two entities that were identical, due to differences in how the dependencies were ordered within the serialized output.  This wasn't reproducible between two local environments, only between local and Cloud.
Initially I thought we weren't ensuring the order and were relying on the collection to come back in a particular way, but actually we are doing this.  However the difference in behaviour looks to be due to differences in globalization settings (as …

Ensure dependency order for Deploy artifacts

---

src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js
src/Umbraco.Web.UI.Client/test/unit/common/services/template-helper.spec.js

If there's an existing issue for this PR then this fixes #11220
Changes the templatehelper service so that when inserting a partial view in the template editor it uses the recommended approach of async partials.
To test this create a new document type with a template and create a content page for it. Now create a partial with some example content. Now return to the document type template and use the editor to insert a partial view and pick the one you just created. You should then save this and view your content page and see that it renders the partial content correctly.

Change template helper to use async partials

---

src/Umbraco.Core/HealthChecks/Checks/Security/ExcessiveHeadersCheck.cs

Bug fixed the check as TryGetValues returns a collection so need FirstOrDefault

Fix for Excessive header health check when excluding Cloudflare

---

src/Umbraco.Tests.AcceptanceTest/cypress/integration/DataTypes/dataTypes.ts
src/Umbraco.Tests.AcceptanceTest/cypress/integration/Members/memberGroups.js

Added Cypress test for testing the textbox datatype's maxlength setting.
It roughly does this:
- Creates a doctype with a new textbox datatype with max chars 10
- Creates a content node based on that and add 8 chars to the textbox - asserts no helptext occurs
- Adds another char - assert it tells the user there is only 1 char left
- Adds 2 more - asserts it now errors as we are above the limit
Also renamed the member group test group from user group to member group as that confused me a bit 😁
Let me know if anything here isn't how it should be!
PS: Runs for around 4s on my machine - could probably shave a bit off if we skipped the initial save and publish assertion, already removed the middle one as it seemed unnecessary - the …

Cypress test for textbox max length

---

src/Umbraco.Web.UI/Views/Partials/blocklist/default.cshtml

Changed the case of BlockList to blocklist as it breaks on Linux Mint. Thanks to @craigs100 for spotting this.

Changed the case of BlockList to blocklist as it breaks on Linux Mint

---

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs

If there's an existing issue for this PR then this fixes #10095
Added a null check to the `Validate` method of the `BlockEditorPropertyEditor`.
I was able to reproduce the issue mentioned in #10095 by doing the following steps:
1. Create a document type containing a block list property that has a minimum amount set.
2. Create a new block list, select any block as an available block and set the settings model to the document created in the previous step
3. Select `Inline editing mode`
4. Save
5. Add the block list you just created to a document type and try to add a block to a node of that type (without filling in the settings)
6. Try to publish and see the error reported in [#10095](https://github.com/umbraco/Umbraco-CMS/issues/10095)

Fixed missing null check in BlockEditorPropertyEditor

---

src/Umbraco.Core/Routing/PublishedRouter.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11227
When rewriting the published content due to public access. E.g. redirect to login page, the culture was not specified. Thereby the dictionary item culture falled back to the default from config. If is not the correct one, no translations was shown.

Fixed issue with culture not set when doing internal redirects due to public access

---

src/Umbraco.Web.BackOffice/Controllers/UsersController.cs

https://github.com/umbraco/Umbraco-CMS/issues/11263
Fixes issue where we used the current users email when sending invite emails. Now we use the one from SMTP settings like in v8

Use email from SMTP settings instead of current users email when sending invite emails

---

src/Umbraco.Core/Configuration/Models/RuntimeMinificationSettings.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11188
Fixes Missing JSON Schema Property for RuntimeMinification:Version
- Execute the JsonSchema project in release mode and check the generated schema file contains Version and xml docs

Fixes Missing JSON Schema Property for RuntimeMinification:Version

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/nucache.html
src/Umbraco.Web.UI/Umbraco/config/lang/cs.xml
src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml

On the Published Status dashboard, when loading or working, there is an incredibly annoying (Wait) text, that causes the layout to shift.
See this gif, where I've throttled my connection to emphasize the effect.
I have removed the text, and the dictionary keys, as they aren't used anywhere else. I also added a z-index value to the overlay, to make it lay above the buttons of the dashboard.
Now it looks like this:
To test:
Go to the Published Status dashboard, and verify that no (Wait) text is flashing while loading or working.

Removes annoying wait text, which causes layout jank

---

src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-group.html
src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-property.html
src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-tab.html

It seems after the new tabs feature has been merged https://github.com/umbraco/Umbraco-CMS/pull/10606 it doesn't consistent use `<umb-icon>` for icons as cleaned up in https://github.com/umbraco/Umbraco-CMS/pull/10805

Use umb-icon component for icons in content type groups and tabs

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html

When creating a folder in the mediapicker, by clicking the + button, you have to unfocus the input field to make it create the folder. Previously you could press return / enter (13) on your keyboard to make it create the folder.
I found out the ng-keydown attribute was missing `vm.` in the reference to the method.
**To test**
- Open a media picker
- Click the + to start creating a new folder
- Type something and press return /enter
- The folder should be created

Fixes wrong reference to enterSubmitFolder method in ng-keydown in mediapicker

---

src/Umbraco.Web.UI.Client/src/common/mocks/resources/entity.mocks.js
src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
src/Umbraco.Web/Editors/EntityController.cs

When loading MNTP's in the backoffice with existing entities associated, a request was made per entity to umbraco/backoffice/UmbracoApi/Entity/GetUrl
All URLs are now resolved in a single request.
Tested
+ Media
+ Content (including vary by culture URL changes, items in recycle bin)
+ Members (no urls expected to render)

Combine GetUrl requests when loading a MNTP with many entries

---

src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs

Fixed bug where the wrong schema was signed in when using 2fa. We used the MS schema instead of our own, and thereby 2fa do not work

Fixed bug where the wrong schema was signed in when using 2fa.

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/MemberTypeQueryController.cs
src/Umbraco.Web.UI.Client/src/common/resources/membertype.resource.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11258
The issue is the auth policies cannot be overridden.. You need all of them, and the old controller requires you to have access to member types

Moved endpoint to new controller to avoid issue with too hard access requirements

---

build/templates/UmbracoProject/UmbracoProject.csproj

This PR forces new projects to use ICU.
By default Linux+Mac+Windows 10 (2019 may update) did use ICU, but Windows server 2016+2019 and Windows 10 (before 2019 may update) is using NLS.

Force ICU usage on windows.

---

src/Umbraco.Core/Packaging/InstallationSummary.cs
src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs

These are currently not exposed, and hence not handled by Umbraco Deploy to create the `.uda` files after a package installation.  With this information we'll be able to create the schema files on disk for these two and resolve remaining schema mismatch errors following a package installation locally and on Cloud.

Exposes the entity containers (folders) created during a package installation in the summary available from the ImportedPackageNotification.

---

src/Umbraco.Web.UI.Docs/umb-docs.css

Tiny, tiny PR 😎 
For another PR I'm working on for the API documentation, I noticed that only `<code>` elements inside normal `<p>` text blocks has any styling, but not when inside a `<li>`. This PR fixes that.
The styling and use of class names is a bit weird for the API documentation in general, so I'm not sure the CSS selector can be made less specific. For instance, there is also `<code>` elements within the `<h1>` elements of the different pages 😱

API Documentation: Added extra selector for styling <code> elements in the content

---

src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js

As the `overlayService` had no ngdocs comments, not even the methods of the service would be shown in the API docs, meaning I as a developer would have to check the source code to determine how it works and which options I can use.
With this PR, I've added ngdocs comments to the individual methods, with the result being visible below:

Added ngdocs documentation for overlay.service.js

---

src/Umbraco.Web/Search/UmbracoTreeSearcherFields.cs

Following the [docs](https://our.umbraco.com/documentation/extending/Backoffice-Search/) for extending backoffice search, it recommends extending the defaults in the `UmbracoTreeSearcherFields` class.
As this class isn't abstract, and the methods aren't virtual, you have to extend with the `new` keyword (this is missing from the docs). Without the `new` keyword you get a warning in Visual Studio.
I have made the methods virtual, this way people can override it to get rid of the warnings and intelisense will suggest these methods too.
This also applies to V9, so hopefully this can be merged up there too!

Making UmbracoTreeSearcherFields virtual for easier overriding

---

src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs
src/Umbraco.Infrastructure/PublishedContentQuery.cs
src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs

Skipping is done as part of the query now, causing `skip` to be applied twice
Related to #11377
Whilst investigating the problem with `skip` and `take` returning inconsistent results, I found that more items were skipped than intended. 
`QueryOptions.SkipTake(skip, take)` handles the skipping now, so the later `skip` is not required

Published Content Query has "skip" applied twice

---

build/templates/UmbracoProject/appsettings.json
src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.Core/HealthChecks/Checks/Security/BaseHttpHeaderCheck.cs
src/Umbraco.Infrastructure/Search/UmbracoTreeSearcherFields.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
src/Umbraco.Web.UI.Docs/umb-docs.css
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configurations/LanguageXmlTests.cs

V9: Merge v8: 03-11-2021

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html

Fixes and issue where when you pressed the edit user button:
This would trigger a full page reload, and thus show tours/email subscription notifications again.
- Changed button to now use editUser function
- implemented editUser function
- Run a clean install of umbraco
- When you get the tour notification, just close it (**do not press "don't show this again"**)
- Press the edit user button, it should not give you the tours popup anymore

v9: don't reload page when navigating to edit user

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card.html
src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
src/Umbraco.Web.UI.Client/src/views/components/umb-child-selector.html
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html
src/Umbraco.Web.UI.Client/src/views/content/notify.html
src/Umbraco.Web.UI.Client/src/views/content/rights.html
src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/views/templates/templates.html
src/Umbraco.Web.UI.Client/src/views/languages/edit.html
src/Umbraco.Web.UI.Client/src/views/languages/overlays/delete.html
src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html
src/Umbraco.Web.UI.Client/src/views/mediatypes/views/listview/listview.html
src/Umbraco.Web.UI.Client/src/views/membertypes/create.html
src/Umbraco.Web.UI.Client/src/views/partialviewmacros/create.html
src/Umbraco.Web.UI.Client/src/views/partialviews/create.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/delete.html
src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
src/Umbraco.Web.UI.Client/src/views/stylesheets/create.html
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html

In this PR I have added fallback texts in several views where one key has been missing in order to not spam the PR tracker too much with these kind of PR - It's done to ensure that in case a translation key is missing then we at least show an English fallback text 😃

Add missing fallback texts in various views

---

tests/Umbraco.Tests.AcceptanceTest/cypress/integration/HelpPanel/systemInformation.ts

- Removed tour steps closing - this would only pop up of you ran an unattended install
- Run a clean umbraco installation
- Click "don't show again" to tours
- Run the cypress tests

v9: fix helppanel tests locally

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json

Fixes the build pipeline issues where tests run forever, this is a quirk with cypress 8.7.0
- Downgraded cypress to 8.4.1
- The acceptance test pipeline should actually run this time and not be timed out after 60 minutes

v9: Downgrade cypress to 8.4.1

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js

I noticed that when the `localize` AngularJS directive was used on attributes (e.g. `<input type="text" localize="placeholder" placeholder="@section_key" />`), the localization key was visible while it was still loading the translations. Although this is probably not visible for most users, if you have a slower connection (or change your language), you might see it change from the key to the actual translated value, for example:
To get rid of it, this PR removes the attribute before loading the translation, so you'll only see the translated value. To test, you can disable the browser cache and throttle the connection speed:

Hide localization key while loading

---

src/Umbraco.Infrastructure/Mail/EmailSender.cs

Fixes issue #11575 - I mimicked the string.IsNullOrWhitespace from code in the same method.

Allow appsettings.json to set SMTP authentication to string.Empty

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/fr.xml

Currently the back office Health Check tab references the old way of turning HTTPS on in the web.config rather than appsettings.json
Old:
New:

v9: Health Check still references web.config instead of appsettings.json

---

src/Umbraco.Core/Notifications/UmbracoApplicationComponentsInstallingNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationMainDomAcquiredNotification.cs
src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs

Given they are non-documented and have no use, have obsoleted the notification classes and added comments for their removal in V10.

Obsoletes events added for local database initialization for Umbraco Cloud that are no longer required.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js

Updated docs to add information about tokens and watch-tokens.
Simple updates to the docs to reflect features that was added in Umbraco 8.1 so that we can show them in the backoffice docs: https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:localize

Update docs for localize.directive.js

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
src/Umbraco.Web.BackOffice/Security/ExternalLoginSignInResult.cs

If there's an existing issue for this PR then this fixes #11591 
This change fixes an issue where returning `false` in `OnExternalLogin` in a custom `BackOfficeExternalLoginProviderOptions` would still create the user and log them in.
Testing:
- Create a custom `BackOfficeExternalLoginProviderOptions`
- Set `OnExternalLogin` to return false
```csharp
public void Configure(BackOfficeExternalLoginProviderOptions options)
{
options.AutoLinkOptions = new ExternalSignInAutoLinkOptions(
autoLinkExternalAccount: true,
defaultUserGroups: new[] { global::Umbraco.Cms.Core.Constants.Security.EditorGroupAlias },
defaultCulture: null,
allowManualLinking: false
)
{
// Optional callback
OnAutoLinking = (autoLinkUser, loginInfo) => { ... },
OnExternalLogin = (user, loginInfo) =>
{
// There's code here to …
```

v9: Fix for OAuth ExternalLogin

---

src/Umbraco.Web.BackOffice/Controllers/UsersController.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/11453
The issue occurs only on Umbraco Cloud due to a special "send email flow" which broke because of the change introduced in https://github.com/umbraco/Umbraco-CMS/pull/11266. More specifically, there, the SMTP settings are not in the config files and sending `null` will make the `emailMessage.From` to always be `null`  while the `configuredEmailAddress` won't also be setup:
https://github.com/umbraco/Umbraco-CMS/blob/f5ea5df8f3eef8e84d5495e372ec90dfaaa57873/src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs#L82
</br>
This PR makes sure to fall back to the current user's email if the SMTP settings are not configured.

Fix sending invite emails

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html

If there's an existing issue for this PR then this fixes #11633 
Fixes the following issues:
- When both `minNumber` and `maxNumber` is `0`, adding 1 or more items fails validation with `You can only have 0 items selected`.
- When `minNumber` is `0` and `maxNumber` is N, contentpicker displays both `Add between 0 and N items` and `Add up to N items`. If more than N items are added, error message `You can only have N items selected` is displayed twice.
- When `minNumber` is N and `maxNumber` is `0`, contentpicker displays `Add between N and 0 items`.

contentpicker: Don't validate minNumber/maxNumber if 0

---

src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml

By coincidence I noticed that the `http-equiv` meta tag was still present in the `head` section but since Umbraco does no longer support any version of IE it's no longer needed since the functionality according to Microsoft will not be implemented in Edge anyway, which they state here https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/380e2488-f5eb-4457-a07a-0cb1b6e4b4b5
While I did this removal I noticed the "Enable" JavaScript message and tried disabling JavaScript for fun to see what it actually looked like and decided to make the styling a wee bit nicer and switch the .png icon with the .svg icon instead making it easy to change the logo color to match the current brand style (If anyone else ever come across this 😂 ).
Please see the before and after look of the message …

Remove http-equiv meta tag and update the "enable JS" message a wee bit

---

src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html

I noticed that in most other sections whenever there is some text, it's wrapped in the `<umb-box>` directive. Under "Translation" if there has not been added any the "There are no dictionary items." text is wrapped in this directive and therefore I was thinking it would make sense to do the same in the Redirect Dashboard where the texts for "empty" and "no search results" are wrapped this way as well. See the before and after below.
**Before**
**After**

Redirect Dashboard: Wrap Texts in <umb-box> directive

---

src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html

"Oh my god I'm back again...." 🎶 😄 
Turns out I missed a few views where localization fallbacks are still missing - So this PR addresses a single missing fallback value ensuring a text will be displayed in case the value is missing from other language files 👍🏻

Content grid: Add missing fallback value

---

src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
src/Umbraco.Web.UI.Client/src/common/filters/simpleMarkdown.filter.js.js
src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html

This one adds the ability to use simple markdown in property descriptions.
I've added a filter for converting simple markdown like `**bold**` `*italics*` `![images](url)` and `[links](url)`
In addition to that, a new convention where if you put a line with `--` in your description, the description will split up in a default description, and an extended description that you can show by clicking Read more.
This makes for a less crowded editor experience, with easy access to more detailed descriptions of each field.
In the above examples the following description is used:
```
Write some text in this field.
**Important!**
This is going to be live on the website
--
If you write something you *don't like*, you have to apologize. 
[Umbraco HQ](https://www.umbraco.com)
```
Could be especially …

Adds support for simple markdown in property descriptions, and extended property descriptions

---

src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml

- [V ] I have added steps to test this contribution in the description below
When changing your password after forgetting it, the Dutch version said 'bevestig nieuw password' and we've had a complaint from a customer, saying this is not consistent. This should be 'bevestig nieuw wachtwoord'.
This can be tested by requesting a resetlink.

V8 Changed 'bevestig nieuw password' to 'bevestig nieuw wachtwoord'

---

src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html

in media selection, made folder name clickable to select into a folder.  Added not allowed cursor on not allowed items.
- [ X] I have added steps to test this contribution in the description below
Some updates to the media selection list view to better align it to the grid view option: 
*  Update the folders so whole name is selectable to drill into the folder, instead of just the arrow (which is hard to find).  Also made the text underline on hover to signal that it does something different.  
* Updated the pointer to not allowed on items that are not allowed to be selected, in the same way that the grid view does.

Updates to Media Selection list view to better match Grid View

---

src/Umbraco.Web.UI.Client/src/views/mediatypes/views/permissions/permissions.html

Add missing fallback texts ensruing a text will be rendered in case language files are out of sync.

Mediatypes permissions view: Add missing fallback texts

---

src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-crop.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html

In case you configured a slim thumbnail size (portrait) in image cropper, the label breaks on multiple lines, so you didn't see the full size "width x height" label.
Furthermore since it is always configured in pixels, I think we should simplify it from `width px x height px` to just `width x height px`.
https://user-images.githubusercontent.com/2919859/138600166-b4c0c664-faee-47a9-b8c5-e3874738584d.mp4

Ensure crop size in shown for slim thumbnails

---

src/Umbraco.Web.UI.Client/src/views/datatypes/views/datatype.info.html

Adding fallback text for "labelUsedByMediaTypes".

Datatype info view: Add missing fallback text

---

src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Ensuring a fallback text will be displayed in case the language files are missing some of the keys.
Furthermore I noticed the styling of the "history info" could be improved, so I changed it to use the "umb-alert umb-alert--info" classes instead and wrapping the "NOTE!" part in bold.
**Before**
**After**

Documenttypes Permissions view: Add missing fallback texts and fix styling

---

src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-state.html
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

I have mapped all the missing fallback values in this view as well as adding the "notCreated" key into the en.xml where it was missing. I also noticed that in the en.xml the value of the "unpublished" key was "Unpublished" and in the en-us.xml it was "Draft". I have changed the "Draft" text to be "Unpublished" as well. Please let me know if it should be the other way around - As long as they're aligned I think we're good 👍🏻 😃

Variant state: Add missing fallback texts

---

build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.targets
build/templates/UmbracoPackage/.template.config/template.json
build/templates/UmbracoProject/.template.config/template.json
src/Directory.Build.props

Ensure Umbraco static assets included when publish --no-build

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js

V9/feature/merge v8 22/11/2021

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js

I noticed this issue #11334 and was wondering what the issue could be since the focus lock was thoroughly tested but apparently this scenario was overlooked. The issue boils down to the fact that we used to check for `includeContentLoaded`, which kinda works when the views are transcluded but when they're not the focus lock is not being activated.
I have fixed this by resorting to using a timeout value of 500ms, which is not ideal but it appears to actually work more stable and in all tested scenarios so far, which is why I think we should to down this route instead.
Furthermore I have ensured that input fields with `type="hidden"` will not be selected as some of the focusable elements either and I have also added a check to ensure that when content editors want to edit block content that …

Focus lock improvements

---

src/Umbraco.Core/Constants-Conventions.cs
src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
src/Umbraco.Core/Services/Implement/MemberService.cs
src/Umbraco.Tests/Persistence/Repositories/MemberTypeRepositoryTest.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
src/Umbraco.Web.UI.Client/src/views/components/member/umb-member-node-info.html
src/Umbraco.Web.UI.Client/src/views/components/member/umb-membergroup-node-info.html
src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.controller.js
src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
src/Umbraco.Web.UI.Client/src/views/member/apps/membership/membership.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html
src/Umbraco.Web/ContentApps/MemberEditorContentAppFactory.cs
src/Umbraco.Web/Models/ContentEditing/MemberDisplay.cs
src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MemberMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MemberTabsAndPropertiesMapper.cs
src/Umbraco.Web/Models/Mapping/TabsAndPropertiesMapper.cs
src/Umbraco.Web/Runtime/WebInitialComposer.cs
src/Umbraco.Web/Umbraco.Web.csproj

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11255 and resolves https://github.com/umbraco/Umbraco-CMS/issues/11132.
Members in Umbraco require the following default properties:
- `umbracoMemberPasswordRetrievalQuestion`
- `umbracoMemberPasswordRetrievalAnswer`
- `umbracoMemberComments`
- `umbracoMemberApproved`
- `umbracoMemberLockedOut`
- `umbracoMemberLastLogin`
- `umbracoMemberLastPasswordChangeDate`
- `umbracoMemberLastLockoutDate`
- `umbracoMemberFailedPasswordAttempts`
These are added to the `Membership` group by default, but Umbraco created this group even when these properties are already present in another group (or since Umbraco 8.17 in another tab). This PR makes sure the group is only created when one of the properties …

Move member properties to Member Content App

---

src/Umbraco.Core/Constants-HttpContextItemsKeys.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.BackOffice/Controllers/ParameterSwapControllerActionSelectorAttribute.cs
src/Umbraco.Web.BackOffice/ModelBinders/FromJsonPathAttribute.cs
src/Umbraco.Web.UI.Client/src/common/mocks/resources/entity.mocks.js
src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/Controllers/EntityControllerTests.cs

Closes #11631 & #11448.
Probably also closes #11647
If you follow manual reproducing steps from  #11631
e.g. 
1. Create a partial view macro with MNTP property
1. Create doctype with grid
1. Create page with macro in grid -- makes request GetUrlsByIds(int[])
--
If you also add a regular MNTP to the doc type - makes request GetUrlsByIds(Udi[])
Populate all the pickers with content, then you have covered testing for both issues at onces.
---

Bugfixes for MNTP / EntityController

---

src/Umbraco.Web.UI/Umbraco/config/lang/zh.xml
src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs

httpsCheckInvalidUrl was changed to healthCheckInvalidUrl in language files (except zh) at some point however it wasn't changed in the excessive header health check.

[v8] Change httpsCheckInvalidUrl to healthCheckInvalidUrl

---

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Common/RuntimeMinification/SmidgeRequestHelper.cs
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj

This fixes #10252 and #11393
The problem was that, `umbraco-backoffice-js.js` and `umbraco-backoffice-extensions-js.js` loaded extremely slowly (~10 seconds for each), when the debug was set to false in the appsettings.
Turns out this was actually two separate issues, but this PR fixes both, the `umbraco-backoffice-extensions-js.js` problem was actually a bug in Smidge, see [this](https://github.com/Shazwazza/Smidge/pull/133) for more information.
The `umbraco-backoffice-js.js` was simply because the Brotli compression for some reason is extremely slow, and smidge will always prefer this. This fix this issue I've replaced the `RequestHelper` that comes with Smidge with our own `SmidgeRequestHelper` which then wraps the smidge `RequestHelper`, but changes the default, so Smidge will now …

V9: Fix backoffice javascript loading slowly

---

src/Umbraco.Web.BackOffice/Install/InstallController.cs
src/Umbraco.Web.Common/Attributes/IgnoreFromNotFoundSelectorPolicyAttribute.cs
src/Umbraco.Web.Website/Routing/NotFoundSelectorPolicy.cs

fixes: https://github.com/umbraco/Umbraco-CMS/issues/11589
- Added IgnoreFromNotFoundPolicyAttribute
- Added new Attribute to installer redirect so we actually ignore that endpoint when 404'ing
- Install umbraco (run a dummy migration if you already have it installed)
- Try to navigate to a URL that doesn't exist, example: https://localhost:44331/abcdefg
- Assert that you get the new pretty 404 page
Heres the migration class I used to run the installer:
```
namespace Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_9_2_0
{
public class NikolajsMig : MigrationBase
{
public NikolajsMig(IMigrationContext context) : base(context)
{
}
protected override void Migrate()
{
}
}
}
```

v9: Remove install endpoint as valid endpoint 

---

.gitignore
src/Umbraco.Core/Configuration/EntryAssemblyMetadata.cs
src/Umbraco.Core/Configuration/IEntryAssemblyMetadata.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/WebAssets/IRuntimeMinifier.cs
src/Umbraco.Web.BackOffice/Install/InstallController.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
src/Umbraco.Web.Common/RuntimeMinification/UmbracoSmidgeConfigCacheBuster.cs
tests/.editorconfig
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/RuntimeMinification/UmbracoSmidgeConfigCacheBusterTests.cs
umbraco.sln.DotSettings

Closes #11698 additional details can be found there.
Run the unit tests.
+ Ensure RuntimeMinificationSettings CacheBuster = Version (defaults to Timestamp in appsettings.Development.json
+ Try combinations of  `<InformationalVersion>` in Directory.Build.Props + Umbraco.Web.UI.csproj.
+ Add a Version string to [RuntimeMinificationSettings](https://our.umbraco.com/Documentation/Reference/V9-Config/RuntimeMinificationSettings/) 
+ Look at the network tab for js urls in the backoffice especially /umbraco/js/umbraco.controllers etc

Fix smidge bundles not always invalidated between backoffice versions.

---

src/Umbraco.Core/Models/IContentType.cs
src/Umbraco.Core/Models/Mapping/ContentTypeMapDefinition.cs
src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepository.cs
src/Umbraco.Infrastructure/Services/Implement/EntityXmlSerializer.cs
src/Umbraco.Web.UI.Client/src/views/documentTypes/views/permissions/permissions.html
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityXmlSerializerTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.Designer.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.resx
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/SingleDocType-WithCleanupPolicy.xml

Support import/export for doc type history cleanup policy (#11660)
* Support import/export for doc type history cleanup policy
* Support unset/null history cleanup value
* Resolve issue when api endpoints called without cleanup policy. noop isn't good enough as map fails for response.
* null conditional vs null coalesce assignment
* Don't overwrite existing policy if omitted in import XML
* Update history cleanup warning and translations
* Change history cleanup alert to infomational styling
* Remove margin around history cleanup config

Cherry-pick: support import/export for doc type history cleanup policy

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/removeListViewLayout.html
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

This PR aligns the UX of the backoffice by switching to using the "Remove" text instead of the "remove/delete" icon as displayed in the GIF's below.
**Before**
**After**

Listview Datatype: Change from using delete icon to "Remove" text in layouts

---

src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs

Closes #11598
For steps to test follow instructions from issue then apply this patch and re-publish.
This is pretty low effort in terms of code changes but it seems to work just fine.
Left side json is one I saved and published before patch, right is saved and published after patch.
Backoffice block list editor works for both.

Map both settings and content data via property editors.

---

src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Manifest/PackageManifest.cs
src/Umbraco.Core/Telemetry/ITelemetryService.cs
src/Umbraco.Core/Telemetry/Models/PackageTelemetry.cs
src/Umbraco.Core/Telemetry/Models/TelemetryReportData.cs
src/Umbraco.Core/Telemetry/TelemetryService.cs
src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/ManifestParserTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

This adds the functionality to send telemetry information about installed packages.
The `TelemetryService` uses the `IManifestParser` to look for `package.manifests` in the App_Plugins folder. By default the names and versions of the installed packages will be sent, provided that the package has specified a version in the new `version` property  in the `package.manifest`. For the name of the package, the name of the folder will be used, unless the package creator has specified a different name with the `name` property in the `package.manifest`
If a package creator does not wish for there to be sent telemetry information about their package at all they can set `allowPackageTelemetry` to false in their `package.manifest` and then the package will be skipped entirely.
If a site developer …

Package telemetry

---

src/Umbraco.Core/Models/Mapping/MemberTabsAndPropertiesMapper.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs

This fixes a regression after merging https://github.com/umbraco/Umbraco-CMS/pull/11587 to v9, which caused some very minor issues with the new Member Content App change:
- The 'Is Locked Out' property wasn't using the checkbox/toggle and readonly-state
- The Member Content App also displayed the 'Id' and 'Member Type' (which were removed, as this is already visible in the Info Content App)
---
_This item has been added to our backlog [AB#15619](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15619)_

Move member properties to Member Content App (V9 merge regression)

---

src/Umbraco.Web/BatchedDatabaseServerMessenger.cs
src/Umbraco.Web/Cache/DistributedCacheBinder.cs

This PR relates to [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/90) raised on the Deploy tracker.  The problem and cause is well described there, and I've replicated with a load balanced setup and found the same behaviour.
It looks like we need to fix this in CMS rather than Deploy though, as Deploy is raising the expected events following a content deployment operation.
What's going wrong though is that when the events are handled in `DistributedCacheBinder`, we ensure an Umbraco context, using the `HttpContext` if available, but creating one if not.  For the events triggered from Deploy, we don't have an `HttpContext` so one is created.  When the events related to cache instructions are handled, the `BatchedDatabaseServerMessenger` is used to create a batch of …

Handled flushing of cache instruction messages when created from handling events in a background thread

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_2_0/AddDefaultForNotificationsToggle.cs

As discussed @bergmania - to test, after upgrading to 9.2, you will see the added "N" in the database
And if you have SMTP set up properly, you will see the notifications option in the right-click menu
---
_This item has been added to our backlog [AB#15615](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15615)_

Adds migration back for v9 for #10450

---

src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web/HealthCheck/Checks/Security/UmbracoApplicationUrlCheck.cs
src/Umbraco.Web/Umbraco.Web.csproj

- Adding a new health check which checks if the value of `umbracoApplicationUrl` is set in the [umbracoSettings.config](https://our.umbraco.com/documentation/reference/config/umbracosettings/#umbracoapplicationurl) file;
- There is also the option to set it according to the site URL that you are currently using.
- Navigate to the **Settings** section > Health Check > Security 
- Use the _Check group_ button
- Verify that the information displayed in **Application URL Configuration** part is correct
- Ex: If `umbracoApplicationUrl=""` in your **umbracoSettings.config** file, you will see a warning (⚠️)  and you will be able to set its value through the newly added button (_Set Umbraco application URL in Config_)
- After clicking the button it should result in success (✔️) and the value in …

Add a health check for umbraco application url

---

src/Umbraco.Core/Constants-HealthChecks.cs
src/Umbraco.Core/HealthChecks/Checks/Security/UmbracoApplicationUrlCheck.cs
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

- V9 implementation for #11776; 
- Adding a new health check which checks if the value of `UmbracoApplicationUrl` appSetting is set;
- If it isn't set, we will direct to a "Read more" documentation link _**that has to be made**_. ❗ 
(_Since it isn't possible to change the value in v9 programmatically, we link to a page with all the configurations instead_)
---  
**NB** ❗ Something like https://umbra.co/healthchecks-umbraco-application-url  
---
- Navigate to the **Settings** section > Health Check > Security 
- Use the _Check group_ button
- Verify that the information displayed in **Application URL Configuration** part is correct
- Ex: If the appSetting `Umbraco:CMS:WebRouting:UmbracoApplicationUrl` is not set, you will see a warning (⚠️) 
- You can set it to, for example:
```json …
```

V9: Add a health check for umbraco application url

---

src/JsonSchema/AppSettings.cs
src/JsonSchema/JsonSchema.csproj

This updates the Forms reference and introduces the Deploy package references to the JSON schema project and adds the new properties.  I've tested this by generating the schema file and copying into a V9 project, where I see the updates.
If there's a concern with a dependency on an RC we can hold this and I'll update when the full release of Forms 9.2. is out.

Updates Forms and adds Deploy JSON schema.

---

src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
src/Umbraco.Web.UI/umbraco/config/lang/cs.xml
src/Umbraco.Web.UI/umbraco/config/lang/cy.xml
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/de.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/es.xml
src/Umbraco.Web.UI/umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/umbraco/config/lang/he.xml
src/Umbraco.Web.UI/umbraco/config/lang/it.xml
src/Umbraco.Web.UI/umbraco/config/lang/ja.xml
src/Umbraco.Web.UI/umbraco/config/lang/ko.xml
src/Umbraco.Web.UI/umbraco/config/lang/nb.xml
src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/umbraco/config/lang/pl.xml
src/Umbraco.Web.UI/umbraco/config/lang/pt.xml
src/Umbraco.Web.UI/umbraco/config/lang/ru.xml
src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
src/Umbraco.Web.UI/umbraco/config/lang/tr.xml
src/Umbraco.Web.UI/umbraco/config/lang/zh.xml
src/Umbraco.Web.UI/umbraco/config/lang/zh_tw.xml

1. Run a default umbraco installation on a linux container.
2. login to backend
3. go to settings
4. Right click Document types
5. Click Import Document Type
closes  #11752
Update camelcasing in for the import document link.

Fix incorrect camelcasing for import document type

---

src/Umbraco.Core/Services/IConflictingRouteService.cs
src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.BackOffice/Services/ConflictingRouteService.cs
tests/Umbraco.Tests.Integration/Testing/TestConflictingRouteService.cs
tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs

fixes https://github.com/umbraco/Umbraco-CMS/issues/11584
- Created IConflictingRouteService interface
- Created ConflictingRouteService class
- Create 2 controllers that derive from `UmbracoAuthorizedApiController`, remember to use 2 different namespaces
- Run umbraco and assert that you now get an error.
- Please also test this with making a controller with the same name as one of the umbraco API controllers, like TourController

v9: Throw error on duplicate routes

---

src/Umbraco.Web.UI.Client/src/less/pages/login.less

When adding logos that are not square - especially if they are wide, they turn out really small.
This PR removes the width constraint on the logo, and makes its max-height the original 30px, allowing wider logos to take up the necessary width, while keeping the vertical size of the original logo.
Before
After
The logo used: [Buy_n_Large.zip](https://github.com/umbraco/Umbraco-CMS/files/7755387/Buy_n_Large.zip)

Makes the width of .login-overlay__logo dynamic

---

src/Umbraco.Core/Routing/DefaultUrlProvider.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11695
Redirects was no longer shown redirected URLs in redirect management dashboard.
**Before**
**After**

Fix issue with missing URLs shown in redirect management

---

src/Umbraco.Web.UI.Client/src/less/components/umb-tags-editor.less
src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html

It seems the styling of tags editor at some point has changed, so the delete button didn't have correct cursor style and not prevented selection of tags text behind, when clicking delete button.
Furthermore the confirm prompt was move too much to left.
**Before**
https://user-images.githubusercontent.com/2919859/147571556-a04ffd25-210f-415a-acce-f8e7fc527cdf.mp4
**After**
https://user-images.githubusercontent.com/2919859/147570816-348821d4-17cb-43db-bf75-b12eb439b28c.mp4

Fix incorrect styling of actions in tags editor

---

src/Umbraco.Core/Actions/ActionAssignDomain.cs
src/Umbraco.Web.UI/umbraco/config/lang/cs.xml
src/Umbraco.Web.UI/umbraco/config/lang/cy.xml
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/de.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/es.xml
src/Umbraco.Web.UI/umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/umbraco/config/lang/he.xml
src/Umbraco.Web.UI/umbraco/config/lang/it.xml
src/Umbraco.Web.UI/umbraco/config/lang/ja.xml
src/Umbraco.Web.UI/umbraco/config/lang/ko.xml
src/Umbraco.Web.UI/umbraco/config/lang/nb.xml
src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/umbraco/config/lang/pl.xml
src/Umbraco.Web.UI/umbraco/config/lang/pt.xml
src/Umbraco.Web.UI/umbraco/config/lang/ru.xml
src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
src/Umbraco.Web.UI/umbraco/config/lang/tr.xml
src/Umbraco.Web.UI/umbraco/config/lang/zh.xml
src/Umbraco.Web.UI/umbraco/config/lang/zh_tw.xml

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/11670
- recase assignDomain to assigndomain
- If you're on Windows, navigate to your umbraco folder and run the powershell script `(Get-ChildItem -Recurse -Directory).FullName | ForEach-Object {fsutil.exe file setCaseSensitiveInfo $_ enable}`
- Run umbraco
- Create an empty document type and allow as root
- Create a content page for the document type
- Right click the content and click "Culture and Hostnames" this should now give you a menu and not an error

v9: some url paths are not correct on case sensitive filesystems

---

src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
src/Umbraco.Core/Manifest/ManifestParser.cs
src/Umbraco.Core/Manifest/PackageManifest.cs
src/Umbraco.Core/Telemetry/ITelemetryService.cs
src/Umbraco.Core/Telemetry/Models/PackageTelemetry.cs
src/Umbraco.Core/Telemetry/Models/TelemetryReportData.cs
src/Umbraco.Core/Telemetry/TelemetryService.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/Manifest/ManifestParserTests.cs
src/Umbraco.Web/Telemetry/ReportSiteTask.cs
src/Umbraco.Web/Telemetry/TelemetryComponent.cs

Merges the package telemetry functionality down from V9, see the original PR for more information and testing steps: #11738.
I had to make `ManifestParser.GetManifests()` internal instead of private since we otherwise can't match the name/version/etc specified in the package.manifest to the correct package 
~~I'm marking this as a draft, for now~~, everything functionally is merged, however, the `TelemetryServiceTests` are still missing, theses a proving quite difficult to merge since `UmbracoVersion` is static, and `ManifestParser` doesn't have an interface making them impossible to mock/fake. After talking about this we've decided to skip the unit tests due to what's above.

V8: Merge package telemetry from V9

---

src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs
src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
src/Umbraco.Web/PropertyEditors/ImageCropperPropertyValueEditor.cs
src/Umbraco.Web/PropertyEditors/MediaPicker3PropertyEditor.cs

By default, Umbraco stores indented JSON values with redundant crop/default focal point values to the database for all Image Cropper and Media Picker (v3, with local crops) property data. You can view the existing data for both editors by doing the following database queries:
```sql
-- Get all Umbraco.ImageCropper property data
SELECT * FROM [umbracoPropertyData] WHERE propertyTypeId IN (
SELECT id FROM cmsPropertyType INNER JOIN umbracoDataType ON cmsPropertyType.dataTypeId = umbracoDataType.nodeId AND umbracoDataType.propertyEditorAlias = 'Umbraco.ImageCropper'
);
-- Get all Umbraco.MediaPicker3 property data
SELECT * FROM [umbracoPropertyData] WHERE propertyTypeId IN (
SELECT id FROM cmsPropertyType INNER JOIN umbracoDataType ON cmsPropertyType.dataTypeId = umbracoDataType.nodeId AND …
```

Prune Image Cropper and Media Picker (v3) values

---

tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Packages/packages.ts
tests/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
tests/Umbraco.Tests.AcceptanceTest/cypress/support/commands.js
tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/tsconfig.json

- Added create package test
- Added delete package test
- Added download package test
- Updated cypress-helper package
- Added cy-verify-downloads package
- Run umbraco & install
- navigate to the` tests/Umbraco.Tests.AcceptanceTest` folder and run `npm ci & npm run ui`
- Run the package.ts tests

Add package tests

---

src/Umbraco.Core/Models/PropertyTagsExtensions.cs
src/Umbraco.Core/PropertyEditors/ComplexPropertyEditorContentEventHandler.cs
src/Umbraco.Core/PropertyEditors/ConfigurationEditor.cs
src/Umbraco.Core/PropertyEditors/DataValueEditor.cs
src/Umbraco.Core/Serialization/JsonToStringConverter.cs
src/Umbraco.Tests/PropertyEditors/BlockEditorComponentTests.cs
src/Umbraco.Tests/PropertyEditors/NestedContentPropertyComponentTests.cs
src/Umbraco.Web/Compose/BlockEditorComponent.cs
src/Umbraco.Web/Compose/NestedContentPropertyComponent.cs
src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/ColorPickerConfigurationEditor.cs
src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/ImageCropperPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/ImageCropperPropertyValueEditor.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
src/Umbraco.Web/PropertyEditors/MultipleTextStringPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/MultipleValueEditor.cs
src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/TagsPropertyEditor.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/2996 (again, but for v8, as the changes from https://github.com/umbraco/Umbraco-CMS/pull/6416 probably weren't correctly merged up).
While working on PR https://github.com/umbraco/Umbraco-CMS/pull/11805, I noticed we're not only storing verbose property values for the Image Cropper and Media Picker (v3), but a lot of other complex editors also stored redundant data (e.g. empty strings/arrays, whitespace/indented JSON, etc.).
Most issues are caused by converting to/from JSON types and strings over and over again, eventually returning serialized JSON that contains indentation or even converting a `null` value into an empty JSON array again (and storing `[]`).
One very important thing to …

Prune/remove indentation from JSON property values

---

src/Umbraco.Core/Extensions/TypeExtensions.cs
src/Umbraco.Web.BackOffice/Trees/TreeCollectionBuilder.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11793
This PR fixes issues when adding custom trees to e.g. content section to a different tree group, because existing content tree (core tree) had null value in `TreeGroup` and thus end up with empty string as group key.
https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Services/TreeService.cs#L37-L43
This mean the existing content tree was shown in "Third Party" tree group, which is confusing:
https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs#L173
We could by default use section as tree group is TreeGroup isn't set, but that would affect …

Set default tree group for core trees

---

src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

Fixed issue that exists in 9.x
The `ufprt` value is now taken from the Form data instead of the query data if the request is a post. This aligns with Umbraco 8.
- This can be tested by having both a ufprt as query string and formdata.

Take `ufprt` from form data if post, fallback to query

---

src/Umbraco.Web/Editors/ContentTypeController.cs

Minor amend to a previous fix, this PR ensures we delete any invalid file uploaded using the "import document type" feature

V8: Delete temp document type file if validation fails

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

In Dutch, both word 'types' and the word 'typen' can be used, but it is nice to do this consistently.

Localization: Rename RelatieTypen to RelatieTypes (Dutch)

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Translate History Cleanup labels and descriptions to Dutch.

Localization: Translate history cleanup labels/descriptions to Dutch

---

src/Umbraco.Core/Runtime/MainDom.cs

Following a [question in the Discord](https://discord.com/channels/869656431308189746/882984410432012360/928278060015448145), which I also had wondered about, I feel it could be good to further inform the user/developer about what the "Acquiring" part of the startup does.
So I added MainDom here and there in the log messages, to make it more obvious what that step does.

Add "MainDom" to log messages, when acquiring MainDom at startup

---

src/Umbraco.Core/Notifications/UmbracoApplicationStartedNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStartingNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStoppedNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStoppingNotification.cs
src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs

Umbraco currently doesn't have it's own started/stopped notifications and the `UmbracoApplicationStartingNotification` is published before the request processing pipeline is configured (this is the [default behavior](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#startasync-1) of `IHostedService`, which `CoreRuntime` implements).
You can already [use the ASP.NET Core `IHostApplicationLifetime` and register a callback](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#ihostapplicationlifetime-1), but that's linked to the application lifetime and not specifically to Umbraco's runtime. The Umbraco runtime is restarted after completing a new install, which doesn't trigger any …

Add UmbracoApplicationStartedNotification and UmbracoApplicationStoppedNotification

---

src/Umbraco.Web.Common/Controllers/RenderController.cs
src/Umbraco.Web.Common/Controllers/UmbracoPageController.cs

Fixes: #11846
If there is a document type without a template, a "Page Not Found" is returned. (Same as the v8 logic)
- Follow the "Steps to reproduce" in the original issue;
- Make sure the "Page Not Found" page is returned instead of the error.
- Check that there is an entry in the log with the document type alias (_as the template name will be null_)

V9: Visiting a page without a template returns "Page Not Found"

---

src/Umbraco.Core/Constants-AppSettings.cs
src/Umbraco.Core/Dashboards/ContentDashboardSettings.cs
src/Umbraco.Core/Dashboards/IContentDashboardSettings.cs
src/Umbraco.Web.UI/web.Template.config
src/Umbraco.Web/Editors/DashboardController.cs

- Removed a non-existent setting from the Web.config (`ContentDashboardBaseUrl`), left out after the renaming done in commit c6bf78e6728caf15afa186597ee105d6de121937;
- Added the ability to allowlist the remote URLs for the "Getting Started" dashboard in config.
- If no addresses are specified, any address is allowed.
- Without specifying any addresses, the "Getting Started" dashboard should display the content as before.
- Add the following line in Web.config and verify that the behaviour persists:
```
<appSettings>
...
<add key="Umbraco.Core.ContentDashboardUrl-Allowlist" value="https://dashboard.umbraco.org/,https://dashboard.umbraco.com/,https://www.google.com/"/>
...
</appSettings>
```
- Remove either https://dashboard.umbraco.com/ (and observe that the content is not fetched) or …

Allowlisting remote URLs for displaying content on the content dashboard

---

src/Umbraco.Web/WebApi/EnableDetailedErrorsAttribute.cs

Fixes and issue where you were able to see exception stack traces while you were running Umbraco in production mode.
- Added check to see if we're in debug mode
- Set proper Error detail policy if we're in production
- In your `web.config` file set your debug attirubute in compilation to false like so: `<compilation debug=false />` to enable production mode, this can be found under the `<system.web>` tag
- Also set the customError mode to on like so: `<customErrors mode="On" />` this can be found under the `<system.web>` tag
- Finally in a API controller, throw an exception
- Assert that you cannot see the stack trace in the browser, or in the dev tools console.
- I tested this with the TourController cause it pops as soon as you log in like this:
```
public …
```

Don't show stack trace in production mode

---

src/Umbraco.Web.UI.Client/src/common/mocks/resources/entity.mocks.js
src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
src/Umbraco.Web/Editors/EntityController.cs

Fixes issue with MNTP (for 8.18) in a partial view macro - GH #11631
Renamed GetUrlsByUdis to match, don't do this in v9 as it would be
breaking there, instead mark it obsolete.
TODO: v9 ensure integration test coverage, more painful here as no 
WebApplicationFactory.

Added EntityController.GetUrlsByIds support for int & guid + update MNTP

---

src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs

I noticed when searching in Examine dashboard using an empty term the search throw and exception, because if use `Trim()` on null.
It seems it has been there since it was added with the Examine 2.0 implementation here:
https://github.com/umbraco/Umbraco-CMS/pull/10241/files#diff-1dc528437321649518d3c1dd7fb92a81ac141b066b68200aaba2605061a754c0R67
**Before**
https://user-images.githubusercontent.com/2919859/147887086-032e0b10-11e1-4de2-be71-fd8f357c0ef1.mp4
**After**
https://user-images.githubusercontent.com/2919859/147887034-93d68395-7962-43f9-b255-0c46f1b227d8.mp4

Null check in Examine backoffice search

---

src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js

I have being going through the Backoffice UI API Documentation. And noticed that a description for `getSafeAlias`. I just wanted to add it since people might miss it otherwise. (I sure did).

Added description to entityResource.getSafeAlias

---

src/Umbraco.Core/Notifications/IUmbracoApplicationLifetimeNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStartedNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStartingNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStoppedNotification.cs
src/Umbraco.Core/Notifications/UmbracoApplicationStoppingNotification.cs
src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs

This is a minor addition to PR https://github.com/umbraco/Umbraco-CMS/pull/11857 that adds a very useful `IsRestarting` property to the `UmbracoApplicationStartingNotification`, `UmbracoApplicationStartedNotification`, `UmbracoApplicationStoppingNotification` and `UmbracoApplicationStoppedNotification`.
In 'normal' applications the running process is killed when it's stopped (and the application state is clean when started again), but that's not the case when Umbraco restarts: it's only stopping and starting the runtime, not the whole application.
So if you only want to execute some code on the initial startup of Umbraco, handling the `UmbracoApplicationStartingNotification` could result in running it twice when Umbraco has installed or upgraded (as that's when the Umbraco runtime gets …

Add IsRestarting property to Umbraco application notifications

---

src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
src/Umbraco.Core/Security/IHtmlSanitizer.cs
src/Umbraco.Core/Security/NoOpHtmlSanitizer.cs
src/Umbraco.Core/Security/NoopHtmlSanitizer.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs

* Adds IHtmlSanitizer interface to be replaced in DI
* Adds NoOpHtmlSanitizer as a default placeholder
* Use IHtmlSanitizer in RTE when persisted to DB
This PR allows people to implement their own HTML sanitizer which will be used server side when storing the output of the RTE in the database.
* Implement a custom test `IHtmlSanitizer` and register it in DI with a composer
* Ensure the output of the sanitizer is what's stored in the database, and therefore displayed on the frontend
I used this code to test with:
```c#
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Security;
namespace Umbraco.Web.UI
{
public class CustomSanitizer : IHtmlSanitizer
{
public string Sanitize(string html)
{
return "<h1>Custom value</h1>";
}
}
{
public …
```

V8: Add ability to implement your own HtmlSanitizer

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Security/IHtmlSanitizer.cs
src/Umbraco.Core/Security/NoOpHtmlSanitizer.cs
src/Umbraco.Core/Security/NoopHtmlSanitizer.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs

Migrates #11897 to V9
See original PR for more information, including testing steps.
I've updated the constructor of `RichTextPropertyValueEditor`, however this class is internal, so it shouldn't be a breaking change.
```c#
using Umbraco.Cms.Core.Security;
using Umbraco.Extensions;
namespace Umbraco.Cms.Web.UI
{
public class CustomSanitizer : IHtmlSanitizer
{
public string Sanitize(string html) => "<h1>Custom value</h1>";
}
{
public void Compose(IUmbracoBuilder builder) => builder.Services.AddUnique<IHtmlSanitizer, CustomSanitizer>();
}
}
```

V9: Add ability to implement your own HtmlSanitizer

---

src/Umbraco.Core/ConfigsExtensions.cs
src/Umbraco.Core/Constants-AppSettings.cs
src/Umbraco.Core/Help/HelpPageSettings.cs
src/Umbraco.Core/Help/IHelpPageSettings.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Web.UI/web.Template.config
src/Umbraco.Web/Editors/HelpController.cs

Adds and allowlist for the help page.
I had to update the constructor for the `HelpController`, I'm not sure about the rules for breaking changes in V8, but I guess we can resolve the new settings object with `Current.Factory.GetInstance<IHelpPageSettings>();` in the constructor if this is considered a breaking change.
* Ensure everything still works as normal (easiest way is to enter the media section and open the help panel, you should see additional help information for media)
* Add `<add key="Umbraco.Core.HelpPage-Allowlist" value="https://our.umbraco.com,https://www.google.com/"/>` to the appsettings in `Web.config`, and ensure everything still works
* Remove the `https://our.umbraco.com` from the allow list, now the addtitonal help information should fail to load with an error 400.

V8: Add allowlist for HelpPage

---

src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less

**Description**
This PR changes the border radius of umb-notifications component in backoffice to match the border radius of buttons.
**Before**
**After**

Updated border radius of notification to match button

---

src/Umbraco.Web.UI.Client/src/less/components/umb-package-local-install.less
src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.controller.js
src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.html

Similar to the fix in #11061 this also pass in invalidfiles to `handleFiles` function ... and further fix the accepted extension to only zip-files in dropzone / file upload for local package to install. Note the dropzone also get some additional classes after reading the file, e.g. `ng-invalid` and `ng-invalid-pattern` if trying to upload a .nupkg file.
We could enhance this further like style the dropzone and/or show an error message.
**Before**
**After**

Accept zip as extension in local package installer

---

src/Umbraco.Core/Routing/DefaultUrlProvider.cs
src/Umbraco.PublishedCache.NuCache/DomainCacheExtensions.cs

Fixes #11687
The issue is that in multilingual setups `Model.Url(culture)` might return nothing (#), depending on the casing of the culture.
The issue was that when we initially create the route for the cache in `ContentCache.GetRouteByIdInternal`, we have a check:
```
var hasDomains = _domainCache.GetAssignedWithCulture(culture, n.Id);
```
this method `GetAssignedWithCulture`, tries to find a domain with the culture in all the domains in the cache, however this check was done without ignoring casing, leading to the route being unable to be created, this PR fixes this by ignoring the casing in the check.
Additionally I've added a minor fix where we tried to match the culture to the default culture, again without ignoring casing. 
Same as the original issue: 
1. Set up a basic 2 language …

Fix URL with culture

---

src/Umbraco.Core/Configuration/Models/HostingSettings.cs
src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs

In ASP.Netcore the `IWebHostEnvironment.ApplicationName` will always be the assembly name. This may cause confusion and issues when load balancing a site, since all the instances will have the same site name. 
* Added a `SiteName` to `HostingSettings`
* Using the new `SiteName` proberty to set the `IHostingEnvironment.SiteName`
* Registered event handler for when SiteName changes 
I had to work around an existing hack with the `IOptionsMonitor`. We currently have an `OptionsMonitorAdapter` that's used for `HostingSettings` when the site is initially launched, which doesn't implement monitoring, this is used to build a `TypeLoader` berfore the actual ServiceProvider is built. To get around this I've added a check that ensures the `IOptionsMonitor` is an actual `OptionsMonitor` and only …

Allow setting the site name from appsettings

---

src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTaskTests.cs

Fixes #11928 
When the implementation of `IServerRoleAccessor` was switched we would still write to the `umbracoServer` table, which is not desired if load balancing. 
I added a check to the `TouchServerTask` and stop the task if we're not using `ElectedServerRoleAccessor`, this mimicks the behaviour of [V8](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs#L40).
In order to be able to stop the task, I had to make minor changes to `RecurringHostedServiceBase`. I had to make the period not read only, in order to be able to set it to an infinite timespan in the stop method, otherwise the task would still continue to execute, since we update the timer in a finally block in `ExecuteAsync`.
Lastly I added an additional …

Don't write to server table if not using ElectedServerRoleAccessor

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

Fixes #11942 
If you removed a block from a block list editor, the editor would fail to load in any content that used that block.
The issue is that a [change was made](https://github.com/umbraco/Umbraco-CMS/commit/405ed44bb18ab6f5de3b2372b511497470198f89#diff-1917457fd201c21b7a9c50c34e6527656a0707186c40df0c7f79293b0245d54f) to try and fall back to `contentTypeName`, in that change we now also pass the content type name in the label vars. However if a block is no longer allowed `blockObject.content` is null, leading to the error. I fixed this by checking the content for null, and if was null try to fall back to the label in the config, if that too is null we give up and fall back to an empty string. After this you now see the expected "Unsupported" block.
* Run `npm run build`
* Follow the …

V9: Fix removing element from BlockList

---

src/Umbraco.Web.UI.Client/src/init.js

The backoffice shows the current section name in the page title (shown in the browser tab).
The current logic is to take the current section alias and uppercase the first character. Sure, kind of smart, but has some limitations:
- If your section name is multiple words these aren't super friendly to read (e.g. "Demo Section" displays as "DemoSection")
- It's not possible to translate these section names
This PR utilises the `localizationService` to lookup the correct name for the section if it exists.
Umbraco already has the convention of looking for section names under `sections_` so I've made it check there for a value. If no value is found the alias is displayed in square brackets (as it does elsewhere): `[sections_demoSection]`.
This issue is present in both V8 and V9, so it would be …

Lookup backoffice section name in route locationTitle

---

src/Umbraco.Web.UI.Client/src/less/pages/login.less

This PR fixes #11830 
The Umbraco Logo could not be seen because it's containing element had no intrinsic width. By adding a width value, the logo will render correctly.

fixes umbraco logo appearance on backoffice login page, issue #11830

---

src/Umbraco.Web.UI.Client/src/views/components/umb-keyboard-shortcuts-overview.html

I noticed when hover the keyboard shortcuts overview element it no longer use pointer cursor.
It is probably caused by either the element was changed or the previous removed styling which added `cursor: pointer` style to elements with `ng-click` attribute.
We have now a `cursor-pointer` class, which we can use here.

Use pointer cursor pointer for keyboard shortcuts overview

---

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-property.html

I noticed the tags in properties on a content type wasn't really aligned vertically on a content type, so I have adjusted this a bit.
**Before**
**After**

Align tags vertically in content type property component

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js

The Issue This Pull request fixed : 
**THE FIX IS ON UMBRACO V9**
#https://github.com/umbraco/Umbraco-CMS/issues/11424
**Issue brief :** 
Media Multinodepicker not working after opening second time , (open then close then open)
**debugging result :** 
In `mediapicker.controller.js` there is a function called `setTitle();` its called from `onInit();`
this function has two responsibilities 
1-set the title of the picker.
2-set the active tab.
this function has an` If `statement `inside of it :
**root cause:** 
the if statement mentioned above 
has the value of `$scope.model.title` undefined because its a first loading of the controller.so in the second call of `onInit();`
the object attached to $scope with persist the data until the page is reloaded. 
for the `navigation ` its not attached …

refactor setTitle in MediaPicker.Controller.js

---

src/Umbraco.Web.Common/Extensions/FriendlyUrlHelperExtensions.cs

Fixes #11951 by changing `UmbracoContext` to be an expression rather than being a static setter thus ensuring the current umbraco context is always returned, rather than a cached version from initial execution
See issue for replication / testing steps

Don't hold static UmbracoContext reference

---

src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
src/Umbraco.Core/Extensions/ObjectExtensions.cs
src/Umbraco.Core/Routing/UrlProviderExtensions.cs
src/Umbraco.Infrastructure/Persistence/Querying/ExpressionVisitorBase.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
src/Umbraco.Web.Common/Routing/RoutableDocumentFilter.cs
src/Umbraco.Web.Common/Security/MemberManager.cs

During yesterday's UmbraCollab Thursday we looked at this report from PVS Studio: https://pvs-studio.com/en/blog/posts/csharp/0898/
We found that most of the problems were valid, in short:
- 01: `ExpressionVisitorBase` - seems like a copy-paste error, indeed the intention would have been to take the second parameter and not the third.
- 02: `ObjectExtensions` - clear and correct, we were doing the exact same thing twice, no need.
- 03: `ModelsBuilderSettings` - a bit more of a puzzle but we all agreed that if the models mode is any of the "auto" ones then it makes no sense to flag the models to be out of date, the "auto" handler will take care of it so no need to flag it and put a button in the backoffice to reload the models. 
- 04: `RoutableDocumentFilter` - indeed a null check was …

Fix items found in PVS-Studio analysis

---

src/Umbraco.Web.UI.Client/src/common/resources/ourpackagerrepository.resource.js
src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js
src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

This PR adds an additional panel to the Umbraco back-office Packages section, so between "Popular" and "New releases", we can have a "Promoted" section.  The intention here is to have the option to highlight HQ, technical partner and selected community packages.
To Test:
- Check with the PR in place that the back-office presents a new panel showing the HQ packages.
- Via the our back-office, remove the "Is Promoted?" flag from one, and check the display is updated (given a little time for index updates and cache invalidation).
- Then remove both and ensure the panel and the header is removed.

Added section for promoted packages in the back-office.

---

src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
src/Umbraco.Core/Configuration/UmbracoSettings/IContentSection.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
src/Umbraco.Web/Editors/BackOfficeServerVariables.cs

Adding config to hide the logo from backoffice
The following setting can be set in `umbracoSettings.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<settings>
<content>
<hideBackofficeLogo>true</hideBackofficeLogo>
</content>
</settings>
```
vs
Related to https://github.com/umbraco/Umbraco-CMS/pull/11949

Add config to hide backoffice logo

---

src/Umbraco.Infrastructure/IPublishedContentQuery.cs
src/Umbraco.Infrastructure/PublishedContentQuery.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/9823 introduced a new `loadedFields` parameter to one of the  `IPublishedContentQuery.Search()` overloads, which should be used to limit the amount of fields to load in the Examine search results. However, this method doesn't expose the actual search results, but maps them to a `PublishedSearchResult` by fetching the content from the published snapshot by only using the results item ID.
Long story short: we only ever need to select the item ID field, so the `loadedFields` parameter should currently always be set to `new HashSet<string>() { ExamineFieldNames.ItemIdFieldName }` for optimal performance. This PR ensures that's always the case and ignores this parameter (which should be cleaned up in the v10 branch).
I've also added an additional …

Only select ItemIdFieldName in PublishedContentQuery.Search to improve performance

---

build/templates/UmbracoProject/.gitignore

Exclude the Umbraco Log files from UmbracoProject template gitignore. 
I think the current gitignore was possibly created when the log files were inside the TEMP folder

Exclude the Umbraco Log files from UmbracoProject template gitignore

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html

When adding name templates to Nested Content data types, it's most of the time incredibly hard to overview what's in the template field.
This one tries to help, by making it possible to expand the column containing the template field, thus making the field wider.

Makes the template column in NC config expandable

---

src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/components/notifications/umb-notifications.html
src/Umbraco.Web.UI/umbraco/UmbracoBackOffice/Default.cshtml

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11701
This PR adjust the changes made in https://github.com/umbraco/Umbraco-CMS/pull/10518
- Store the z-index in a variable
- Decrease the z-index (I don't see the reason to use z-index 999999 unless we needed to overwrite some third party overlays etc.). We can't guard us against e.g. package developer doing stuff with an even higher z-index e.g. 1000000 or using `!important`, but we know the z-indexes used in core CSS. Not sure there is a specific use-case where notifications should be above tour overlay?
- Only show `<ul>` when any notifications are appended to list.
If saving a content node and open a block list item, the notification is since https://github.com/umbraco/Umbraco-CMS/pull/10518 above block overlay, but the …

Adjust z-index of notifications

---

src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

-  [X] If there's an existing issue for this PR then this fixes #11659 
Since it looks like the `hideIcon `handles as a string instead of a bool. Changing the ng-if to check if it's a string does the trick.

UmbEditorHeaders hide-icon on "true"

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html

It has been possible to mark content properties as read-only from code since at least [Umbraco 7](https://our.umbraco.com/apidocs/v7/csharp/api/Umbraco.Web.Models.ContentEditing.ContentPropertyDisplay.html#Umbraco_Web_Models_ContentEditing_ContentPropertyDisplay_Readonly) (and this is still possible in [v8](https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.Models.ContentEditing.ContentPropertyDisplay.html#Umbraco_Web_Models_ContentEditing_ContentPropertyDisplay_Readonly) and [v9](https://apidocs.umbraco.com/v9/csharp/api/Umbraco.Cms.Core.Models.ContentEditing.ContentPropertyDisplay.html#Umbraco_Cms_Core_Models_ContentEditing_ContentPropertyDisplay_Readonly)), by using the `EditorModelEventManager` (or `SendingContentNotification` in v9). Setting this to `true` should ensure the …

Add support for readonly properties

---

src/Umbraco.Web/Editors/CodeFileController.cs

This fixes #11963 
The issue was exactly as @rasmusjp mentioned in the issue that when deleting a codefile, we use the local filesystem to check if we're trying to delete afolder, which of course won't work with external filesystems.
Unfortunately there's no really good way to achieve this with the `IFileSystem` abstraction, so what I've had to do is to first check if the registered `IFileSystem` is a physical file system using `CanAddPhysical`, if it's a physical file system, we rely on the old method, however, if it's not we instead use the `DirectoryExists` method in the `IFileSystem` to see if it's a folder. This method will of course only return true if the folder actually exists, but since this is only used to check if we need to delete a file or a folder, I think it's a fair …

V8: Fix deleting file on external filesystem

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.FileSystems.cs

This ensures we are not calling `hostingEnvironment.MapPathWebRoot` when the path is already rooted.
- Set `Umbraco:CMS:Global:UmbracoMediaPhysicalRootPath` to an UNC path (e.g. `\\ServerName\SharedFolderName\Media`)
- Boot umbraco
- Upload media to media section
- Verity the media is updated to the specified path.

Fix media paths with UNC format

---

src/Umbraco.Core/PropertyEditors/DataValueEditor.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/11989.
PR https://github.com/umbraco/Umbraco-CMS/pull/11806 ensured JSON property values weren't serialized with indentation in v8, because the value type could be a Newtonsoft.Json type like `JArray` or `JObject` and calling `ToString()` on them would use  `Formatting.Indented` by default. This was fixed by type checking and using a `ToString()` overload to disable formatting:
https://github.com/umbraco/Umbraco-CMS/blob/f38124839c354f312b1f9653465b1c8bc25bb199/src/Umbraco.Core/PropertyEditors/DataValueEditor.cs#L148-L159
However, in v9 the dependency on Newtonsoft.Json is abstracted to the `IJsonSerializer`, so the checks from this PR couldn't be merged up and required some fixes that …

Fix DataValueEditor incorrectly serializing JSON value

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js

When using the `navigation` parameter for the `umbEditorHeader` directive, one must specify an alias for each of the sections - otherwise the Angular repeater will trigger an error as the repeater is tracking the sections by their aliases.
Since the examples didn't include the alias, and because there appears to be no other information about the aliases, I've updated the example to include the aliases.

Fixed issue in umbeditorheader.directive.js example

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbavatar.directive.js

I used the `umbAvatar` directive in a component. And noticed that the default `umbAvatar` (with no images) just became a `?`. After some digging I found out that I could pass in name & color as parameters. And that fixed the default `umbAvatar`. So I just wanted to add them to the description.
I Don't know if my wording is correct for the description though.

Added name & color description for umbAvatar

---

src/Umbraco.Web.UI.Client/src/less/rte.less

This PR fixes #11870
The tab nav bar takes up a height of `50px`. So we need to adjust the sticky top position for the RTE toolbar accordingly.
I updated this:
```
.umb-rte .mce-top-part {
position: sticky;
top: 0;
}
```
To this:
```
.umb-rte .mce-top-part {
position: sticky;
top: 0;
umb-editor-tab-bar ~ div & {
top: 50px;
}
}
```
I didn't see an easier way to detect whether the RTE is contained inside of a tab. So I used the sibling selector.
The following recordings show two use cases. 
**Left side** shows an RTE on the page under a tab.
**Right side** shows an RTE with no tabs.
**Desktop:**
https://user-images.githubusercontent.com/713355/150907350-731ca8fb-8b00-4389-9785-722d06ba7ca2.mp4
**Mobile:**
https://user-images.githubusercontent.com/713355/150907354-3727b8c6-ad39-4d8e-8a71-58fb …

new stick top position for rte toolbar if tabs are present, issue #11870

---

src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
src/Umbraco.Infrastructure/Security/ClaimsIdentityExtensions.cs
src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs

This PR fixes multiple problems I found with timeout, ensuring that it now works as expected. This fixes #11965
There were two major problems a couple of minor ones
The frontend requests GetRemainingTimeout every 30 seconds to see if it should redirect the user to the login page. The Problem with this is a real chicken or egg scenario without previous implementation. In order to get the remaining time out seconds from the  `TicketExpiresClaimType`, we **must** authenticate the user, but with the old implementation the very act of authenticating the user counts as a "backoffice request", which automatically refreshed the cookie **and** our database login session, meaning that in effect you would never get logged out! 
To fix this I've had to do two things, first of all, I've our auth …

V9: Fix login timeout

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/membergrouppicker/membergrouppicker.html

If there's an existing issue for this PR then this fixes #11777 
The issue here was that there was an ordering on the name in the template, while the angular code relies on the position of the item.
So, if you were to add in the following order: "Test2", "Test3", "Test1". It would show up as "Test1", "Test2", "Test3" because of the ordering on the name while the data object still used the first ordering. So when you would want to remove "Test2", it would remove "Test3" because it is trying to remove the item on index 1.
I think the ordering on the name isn't needed here anyway, so I removed it.

11777: Remove sorting because we need the correct order

---

src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.Core/Persistence/Constants-Locks.cs
src/Umbraco.Core/Runtime/IMainDomKeyGenerator.cs
src/Umbraco.Core/Runtime/MainDom.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_4_0/AddScheduledPublishingLock.cs
src/Umbraco.Infrastructure/Runtime/DefaultMainDomKeyGenerator.cs
src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
src/Umbraco.Infrastructure/Runtime/SqlMainDomLock.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Runtime/FileSystemMainDomLockTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ScheduledPublishingTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Runtime/DefaultMainDomKeyGeneratorTests.cs

Fixes for #11935
To test, give the issue a good read and follow the reproduction steps.
Should be able to reproduce the issue with SqlMainDomLock if a discriminator isn't set e.g.
```json
"Umbraco": {
"CMS": {
"Global": {
"MainDomLock": "SqlMainDomLock"
}
}
}
```
To confirm fix, add a slot specific MainDomKeyDiscriminator value and try again
```json
"Umbraco": {
"CMS": {
"Global": {
"MainDomLock": "SqlMainDomLock",
"MainDomKeyDiscriminator": "{{slot name - set this in azure config slot specific}}"
}
}
}
```
Please also confirm issue doesn't occur for FileSystemMainDomLock (doesn't require discriminator, should just work OOTB)
```json
"Umbraco": {
"CMS": {
"Global": {
"MainDomLock": "FileSystemMainDomLock"
}
}
}
```
Pushed pre-release to myget
```xml
// NuGet.config
<?xml version="1.0" …
```

Filesystem based MainDomLock & extract interface for MainDomKey generation

---

src/Umbraco.Core/Configuration/Models/GlobalSettings.cs

The `SanitizeTinyMce` wasn't settable, being always false, even though the new project template tried to set it to true.
The option should now be configurable, allowing TinyMCE scripting sanitization to be enabled.

v9 - Allow configuring TinyMCE scripting sanitization

---

src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs

I implement fix to this issue #11921 . After fix, notification display correct language name :)
After changing the language option "swedish" to "dutch" it does use the dutch language for the pages but when you publish a page the notification popup at the bottom says "Content published: Swedish (Sweden) published and visible on the website" whilst it should be referring to "dutch (netherlands)".
Steps to reproduce:
1. Change the swedish language option to Dutch (netherlands) and save.
2. Publish a page in the changed language.

11921: Update CultureName after language change

---

src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
src/Umbraco.Web.BackOffice/Trees/TreeNodesRenderingNotification.cs

Async support for TreeController
Add id to TreeNodesRenderingNotification.

Support async in TreeController

---

src/Umbraco.Web.UI.Client/src/common/filters/umbCmsBlockCard.filter.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html

Currently filtering block cards also filter by data included it block model, but may not be relevant to content editors, e.g. filtering on the term "image", doesn't really filter any blocks containing "image".
I have modified this to use a custom filter (it could also be a local function, but I guess it could be useful to have a filter if developer made a custom block editor or similar using `<block-card>` component).
It filter on the following properties:
- Id
- Key (Guid)
- Udi
- Alias
- Name
- Description
Including Id, Key and Udi makes it easy to developers to filter to a specific block by an identifier - at least that is what is possible in the current behaviour. It also add an empty message in case no blocks are found via the filtering.
Not sure about the naming convention of the …

Filter block cards and show empty message

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

If there's an existing issue for this PR then this fixes [](https://github.com/umbraco/Umbraco-CMS/issues/11792)
When saving a blueprint / content template it used same localization texts as for regular content, which was confusing.
https://user-images.githubusercontent.com/2919859/147567444-1500771a-f0f0-4bec-b70f-fcc71716470e.mp4

Vary localization based on content or blueprint

---

src/Umbraco.Core/Persistence/LocalDb.cs

Raised as an issue in the Cloud tracker [here](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/550) is a situation where LocalDb is available locally, but can't be successfully used.  The fix is needed in Umbraco 8 CMS.
I've extended the check to include the most recent version 15.
Assuming you the latest version locally, this can be tested with a temporarily added unit test, which I've not checked in as it depends on the local file system.  
```
using NUnit.Framework;
using Umbraco.Core.Persistence;
namespace Umbraco.Tests.Persistence
{
internal class LocalDbTests
{
[Test]
public void DetectsVersion()
{
var localDb = new LocalDb();
Assert.IsTrue(localDb.IsAvailable);
Assert.AreEqual(15, localDb.Version);
}
}
}
```

Extended check for locally installed LocalDb to include the most recent version 15.

---

src/Umbraco.Web.BackOffice/Trees/TreeCollectionBuilder.cs

… and add method to remove Tree definition
Previous this PR https://github.com/umbraco/Umbraco-CMS/pull/11250 introduced `RemoveTreeController()` methods. However this didn't require the controller should inherits from `TreeControllerBase` like  `AddTreeController()` methods.
So you could pass in any type:
```
public class TreeComposer : IComposer
{
{
builder.Trees().RemoveTreeController<string>();
builder.Trees().RemoveTreeController<int>();
builder.Trees().RemoveTreeController<DateTime>();
builder.Trees().RemoveTreeController<ContentBlueprintTreeController>();
}
}
```
but only the latter one would work. This may be considered as a breaking change, but shouldn't really have worked if any class was specified, which not inherits from …

Update RemoveTreeController to use TController 

---

src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs

Database upgrades currently fail when no JSON configuration file is present (e.g. `appsettings.json`).
This is because `JsonConfigManipulator` always expects a JSON configuration file to be present, which isn't consistent with `Host.CreateDefaultBuilder` which considers the JSON files to be optional.
All of the public methods defined in `JsonConfigManipulator` and `IConfigManipulator` are susceptible to this crash.
Exceptions are also being encountered during fresh installs, but unlike upgrades, the install can still proceed:
I encountered this issue when running Umbraco `9.0.0` under a Docker container and trying to configure the application purely with environment variables.
Presumably, using any configuration method that is **not** JSON files is affected by this (command line …

Fix JsonConfigManipulator causing upgrades to fail when appsettings.json files are not present

---

src/Umbraco.Core/Telemetry/ISiteIdentifierService.cs
src/Umbraco.Core/Telemetry/TelemetryService.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Web/Editors/DashboardController.cs
src/Umbraco.Web/Install/InstallSteps/TelemetryIdentifierStep.cs
src/Umbraco.Web/Runtime/WebInitialComposer.cs
src/Umbraco.Web/Telemetry/ReportSiteTask.cs
src/Umbraco.Web/Telemetry/SiteIdentifierService.cs
src/Umbraco.Web/Telemetry/TelemetryComponent.cs
src/Umbraco.Web/Umbraco.Web.csproj

Fixes an issue where the site ID might not exist, for instance if unattended install is used or the site has been updated. This also removes the one second timeout from `ReportSiteTask`, since it's a background task, there's no reason why we demand an answer so fast, and it might cause issues where the telemetry is not sent because it times out. We'll also include the site identifier when requesting the dashboard now.
Adds a new `SiteIdentifierService` for creating/getting the site Id, which is then used in `TelemetryIdentifierStep`, and `TelemetryService`. Now if the site identifier does not exists or is invalid when `ReportSiteTask` a new valid GUID will be generated and stored in `umbracoSettings.config`
The site identifier is located in `umbracoSettings.config` under the `backOffice` …

V8: Fix missing site identifier

---

src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs

To prevent open redirects, the imagePath should point to a relative path (i.e. not point to a different domain).
This PR implements a simple control on the imagePath to prevent open redirects. Since there is no reason for the imagePath to point to a different domain (i.e. imagePath="https://..../image.jpg"), we should return an Unauthorized() response when the path is not UriKind.Relative.

Validate that imageUrl param is a relative path

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbimagelazyload.directive.js
src/Umbraco.Web.UI.Client/src/less/main.less

This PR adjust the `umb-image-lazy-load` directive by adding a `lazy` class and `loaded` class when image has been loaded making a smoother transition from the temporary transparent image to the loaded image.
https://user-images.githubusercontent.com/2919859/146643177-6f992c9e-c375-4927-815e-0850f2614d96.mp4
I have attached the custom listview layout used in a custom listview for "People".
[ListviewLayouts.zip](https://github.com/umbraco/Umbraco-CMS/files/7739314/ListviewLayouts.zip)
I have hardcoded the `imageProp.value` though as each `photo` properties return null in value property.
Not sure if something has changed in 9.2.0-RC because it is working just fine in 9.1.2
I am using this listview layout in a few projects and works with both Media Picker 3 and legacy media picker.
``` …
```

Transition of lazy loaded image

---

src/Umbraco.PublishedCache.NuCache/ContentStore.cs

Check Debug logs are enabled for contentstore hot path. The more content you have, the slower the startup due to debug logging for content items.

Tune Debug logging to improve ContentStore boot performance

---

src/Umbraco.Web.Common/Extensions/ControllerExtensions.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12030
- Added extra check for generic types
- Follow step by step in issue

v9: Fix cannot replace default Rendercontroller with generic

---

src/Umbraco.Web/Editors/ContentController.cs

This fixes #12051.
The original issue reported that using the `ContentSavingNotification` on V9 you couldn't access the content that was being saved. 
After some additional testing, I found that this only happened when the content being saved had "allow varying by culture"  enabled and that the data was actually there, it was just buried inside the `CultureInfos` property but I do see how this can be confusing and not really obvious. 
Furthermore, I found that `EditedCultures` would never return any results making this even harder to work with.
To fix this I've changed the behaviour so now if you're renaming a multilingual content nodes default language variant that new name will be set as the name of the saved entity on the event if you, however, rename nodes non-default language this is …

V8: Fix missing EditedCultures and Name in content saving notifications

---

src/Umbraco.Core/Routing/DefaultUrlProvider.cs
src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
src/Umbraco.PublishedCache.NuCache/CacheKeys.cs

This closes #11984.
While testing the above issue I was unable to replicate the exact issue, and the original issue creator has returned and mentioned that they can no longer reproduce this. 
However when doing some testing I noticed that redirect tracking is broken for invariant content types, as is also confirmed by a commenter on issue #11695, this PR fixes this issue with invariant redirect tracking.
I found two problems, the first of which are that whenever you publish or move some content a notification is handled by a `RedirectTrackingHandler`, in this request the culture of an invariant content node will have a culture as an empty string `""`, and not null. This mean that when we tried to generate the route from the cache it looked for something with a culture of empty string, …

Fix invariant redirect tracking

---

src/Umbraco.Core/Models/ContentEditing/HistoryCleanup.cs
src/Umbraco.Core/Models/ContentType.cs
src/Umbraco.Core/Models/Mapping/ContentTypeMapDefinition.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTypeHistoryCleanupTests.cs

Migrates #12058 to V9.
This is essentially identical to the other PR, I did find another issue in the V9 branch though, we always re-created the `AllowedContentTypes` property, meaning that this would also always be dirty, I've added an additional check to ensure we only re-create this collection when something has actually been changed. 
```c#
using System.Collections.Generic;
using System.Linq;
namespace Umbraco.Cms.Web.UI
{
public class ContentTypeSavingHandler :
INotificationHandler<ContentTypeSavingNotification>,
INotificationHandler<ContentTypeSavedNotification>
{
public void …
```

V9: Fix history cleanup not making content type dirty

---

src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
src/Umbraco.Web.Common/Filters/ValidateUmbracoFormRouteStringAttribute.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

Fixes #11956
Checks to see if the request has form data before validating the `ufprt` parameter in the forms data collection, and if it doesn't assumes it must be on the querystring.
I'm not sure if this then makes this attributes name a little wrong depending on what `Form` refers to in it's name? Another option could be to product a second attribute for validating `QueryString` instead and then people have to explicitly select which approach they are expecting?

Check form and querystring when validating `ufprt` in `ValidateUmbracoFormRouteStringAttribute`

---

src/Umbraco.Infrastructure/Security/MemberUserStore.cs
src/Umbraco.Web.Website/Security/MemberAuthenticationBuilder.cs

Resolves a couple of issues with external logins.
- Exception message was misleading for auth scheme validation, when missing "UmbracoMembers." prefix  it suggested to use "Umbraco." 
- SetTokenAsync implementation was missing for MemberUserStore which made login impossible for some IdPs
- Persist new tokens on update

v9 fix misc issues external member login

---

src/Umbraco.Core/Models/Content.cs

Currently if you pass `null` into `IsCulturePublished` it throws an `ArgumentNullException` - this is because (rightfully) the `publishedInfos` dictionary cannot contain `null` keys. Passing an empty string for the culture instead returns `false`. It seems to have been this way since V8.
Many of the other methods on `IContent` that take a culture defend against this, e.g. `GetCultureName`, so I found it weird that this method didn't. For now I have just [added a null check in my package](https://github.com/callumbwhyte/meganav/blob/v9/dev/src/Our.Umbraco.Meganav/PropertyEditors/MeganavValueEditor.cs#L81) when calling the method.
This PR adds a NullOrWhitespace check on the culture before checking the dictionary to prevent any issues.

Adding null check to IsCulturePublished on IContent

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12095
The currentForm.$setDirty(); was missing when removing an control from a grid.
- Install Umbraco with the starterkit;
- In Umbraco Backoffice go to "About us"
- Remove the headline "Oooh la la";
- Navigate to any other page
The "You have unsaved changes" prompt should now appear;

Make GridPropertyEditor dirty if a control is removed

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/relationTypes.ts

There's been a change to the `ContentController.PostSaveInternal` that moved where we mapped to persisted content to display up before it was actually persisted, to check if it was a blueprint. 
This broke the UI (and cypress tests) when saving a piece of content causing it to not reload the page (see gif below), this is because certain properties like the ID is only set when the content is actually persisted. 
To fix this I moved the mapping back to where it was before, and get `isBlueprint` from `contentItem.PersistedContent.Blueprint`, all mapping to `ContentItemDisplay` does in this regard is 
```c# 
target.IsBlueprint = source.Blueprint;
```
So it's not needed to map to display twice.
This also fixes a broken cypress tests, this was just because there is a new option when creating a …

Fix saving content not updating the page

---

src/Umbraco.Infrastructure/Services/Implement/TrackedReferencesService.cs

Fixes issue with `pageindex` used as `pagenumber` and thereby all pages being off by one.

V9.4RC - Fixed issue with pageindex (0-indexed) vs pagenumber (1 indexed)

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs

If the value for a MultiUrlPicker is an empty string or other invalid input, and you are using the Newtonsoft.Json deserializer, it will return a null in the value converter. This is the piece of code affected from MultiUrlPickerValueConverter.cs:
```
var links = new List<Link>();
var dtos = _jsonSerializer.Deserialize<IEnumerable<MultiUrlPickerValueEditor.LinkDto>>(inter.ToString());
var publishedSnapshot = _publishedSnapshotAccessor.GetRequiredPublishedSnapshot(); 
foreach (var dto in dtos)
```
The call to _jsonSerializer.Deserialize results in the dtos variable being null if the input was invalid, but there is no check for this, so the following exception occurs when the foreach loop is reached:
> System.NullReferenceException: Object reference not set to an instance of an object.
> at …

Possible NullReferenceException in MultiUrlPickerValueConverter

---

src/Umbraco.Core/Constants-SystemDirectories.cs
src/Umbraco.Core/Packaging/PackagesRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CreatedPackageSchemaRepository.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/11654 already moved the `umbraco/Data/Packages/createdPackages.config` file into the database, but the new service still saved the actual `package.xml`/`package.zip` into the media folder in the webroot (`wwwroot/media/created-packages`). PR https://github.com/umbraco/Umbraco-CMS/pull/11783 unintentionally changed this to `wwwroot/created-packages` (because of the leading slash on the `Constants.SystemDirectories.CreatedPackages`, making it relative to the webroot).
By saving these files inside the webroot, they are automatically downloadable by everyone (if you can guess the package name). This has always been the case, but because the package manifest can contain sensitive data (author names, dates, unpublished content, source code of …

Move created packages out of webroot

---

build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.targets

Umbraco content files are being included early in the build process to ensure that if the files didn't exist before, then are taken into account during the build process.
The issue is that, if the files already existed (e.g. incremental builds) they are now being included twice.
In .Net 5 I don't think this caused any observable issue, but in .Net 6 it causes Razer View Compilation to fail for incremental builds.
- Activate Razor View Compilation
- Upgrade to .Net 6 (Although this is necessary to easily observe the issue, the incorrect behavior was present nonetheless)
- Compile the code
- Perform any code change and recompile the code without cleaning first.
- The following warning/error will be thrown:
```
CS8785	Generator 'RazorSourceGenerator' failed to generate source. It will not …
```

Fixes Umbraco including content files twice

---

src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
src/Umbraco.Web.BackOffice/Trees/MemberGroupTreeController.cs
src/Umbraco.Web.BackOffice/Trees/MemberTypeAndGroupTreeControllerBase.cs
src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs

For some reason the copy member type feature included in v8, wasn't merged up to v9. The copy dialog etc. exists, but the tree menu action wasn't added.
https://github.com/umbraco/Umbraco-CMS/pull/10020
However it seems we don't have access to `Services.MemberTypeService` like in v8 and I guess it would be a breaking change when changing the signature of the constructor.
https://user-images.githubusercontent.com/2919859/156375440-216c9bba-3761-4e81-8b2d-e7b90f48b01b.mp4
Furthermore I am not sure why the `PostSave` method dosn't have `[Authorize(Policy = AuthorizationPolicies.TreeAccessMemberTypes)]` https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs#L193
In MediaTypeController it does have `[Authorize(Policy = …

Add  missing copy member type menu action

---

src/Umbraco.Core/Security/LegacyPasswordSecurity.cs
src/Umbraco.Infrastructure/Security/MemberPasswordHasher.cs
src/Umbraco.Infrastructure/Security/UmbracoPasswordHasher.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Security/LegacyPasswordSecurityTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/UmbracoPasswordHasherTests.cs

For users - try new style passwords first and fallback on failure seeing
as a valid modern password is the norm, rehash is only one time.
For both users and members also deals with the fact that for
useLegacyEncoding we could store any old thing in passwordConfig
e.g. it's possible to get Umbraco8 to store "HMACSHA384" alongside
the hash even though it's really HMACSHA1 with password used as key
(try it out by tweaking machine key settings and setting
useLegacyEncoding=true).
Has behavioral breaking changes in LegacyPasswordSecurity as the
code now expects consumers to to respect SupportedHashAlgorithm
rather than ignoring it.

Further enhancements for legacy password support.

---

src/Umbraco.Core/Composing/TypeFinder.cs

Removed some unnecessary `.ToList()` calls.
This also improves performance a little bit when checking the typefinder benchmark tests
Make sure Umbraco is still starting as always.

Removed unnecessary tolist()'s

---

src/Umbraco.Core/Notifications/SendingAllowedChildrenNotification.cs
src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs

This is a ported version of this v8 PR: https://github.com/umbraco/Umbraco-CMS/pull/9906
Most of the description of that PR still applies to this one. Although, the code example is a bit different now.
https://user-images.githubusercontent.com/11466511/109339815-77656e00-7868-11eb-8aef-3a93076da116.gif
Can be done with the following handler:
```
public class TestCode : INotificationHandler<SendingAllowedChildrenNotification>
{
public void Handle(SendingAllowedChildrenNotification notification)
{
var children = notification.Children.ToArray();
if (children.All(it => it.Alias != "settings"))
return;
var currentSettings = notification.UmbracoContext.Content.GetSingleByXPath("//settings");
if (currentSettings is null)
return;
notification.Children = children.Where(it => it.Alias != …
```

Add allowedChildren call to Outgoing Editor events

---

src/Umbraco.Core/PropertyEditors/DataValueEditor.cs

The 8.18.0 release changed some of the internal logic for the `DataValueEditor.TryConvertValueToCrlType` method:
8.17 and earlier checks whether `value` is an instance of `JValue`, and if so, calls the parameterless `ToString` method. This hits the [overriden method of the `JValue` class](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JValue.cs#L898) ensuring the value is correctly formatted.
The implementation in 8.18 has been updated to check against `JToken` instead, and then call the `ToString(Formatting)` method instead. This method is [declared in the `JToken` class](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JToken.cs#L442), but not overriden in the `JValue` class (which extends `JToken`).
The result is then that …

[8.18] Fixed issue with DataValueEditor.TryConvertValueToCrlType method incorrectly enclosing string values in double quotes

---

src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12105
Seems that when we call the GetResized function the url is not encoded (as expected) but we never encode it ourselfs and therefore it will fail if url contains non-ascii characters.
- Added url encoding to GetResized()
- Go to the media section and add some images with non-ascii characters in the filename like "ččřiřiřiřičr" (please do test other characters aswell)
- Create a document type with a Image media picker
- Create some content and when using the media picker you should now see a thumbnail for the image, even if the filename contains non ascii characters

v9: Fix image thumbnails not showing if filename contains non ascii characters

---

src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs
src/Umbraco.Core/Services/ITrackedReferencesService.cs
src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
src/Umbraco.Infrastructure/Services/Implement/TrackedReferencesService.cs
src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
src/Umbraco.Web.BackOffice/Controllers/TrackedReferencesController.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/references/umbtrackedreferences.component.js
src/Umbraco.Web.UI.Client/src/common/resources/trackedreferences.resource.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references-table.html
src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references.html
src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

This PR fixes some of the issues mentioned as comments in https://github.com/umbraco/Umbraco-CMS/pull/11919, together with a bug where duplicate items were displayed on the items tracking result:
- Adding xdoc comments on public interfaces;
- Fixing some wording and other minor fixes;
- Removing duplicate items when displaying references. 
- Reference the same items in several different places;
- Make sure all the references appear;
- Make sure that when this item is part of bulk deletion/unpublishing or when deleting/unpublishing the parent of the item, it doesn't appear several times in the result since it has more than 1 reference.

Item tracking fixes

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/Media/EmbedProviders/LottieFiles.cs

LottieFiles (https://lottiefiles.com/) - The popular opensource JSON-based animation file format that enables designers to ship animations on any platform, has just started supporting OEmbed, from their gallery of community animations, which makes it a lovely candidate for adding an OEmbedProvider to Umbraco's Embed functionality for LottieFiles.
I was going to create a package for this but then it would be called Our.Umbraco.Lottie and I think that would be confusing for people, as they consider Our Umbraco Lottie to be @LottePitcher ... so I think therefore it MUST go in the core.
How to test?
Visit the LottieFiles gallery of 'free animations'
https://lottiefiles.com/featured
search and find the animation you want to embed, on …

Add a basic oEmbedProvider for LottieFiles animations

---

src/Umbraco.Core/Cache/MacroCacheRefresher.cs
src/Umbraco.Core/Persistence/Repositories/IMacroWithAliasRepository.cs
src/Umbraco.Core/PropertyEditors/ParameterEditors/MultipleContentPickerParameterEditor.cs
src/Umbraco.Core/PropertyEditors/ParameterEditors/MultipleMediaPickerParameterEditor.cs
src/Umbraco.Core/PropertyEditors/ParameterEditors/MultiplePickerParamateterValueEditorBase.cs
src/Umbraco.Core/Services/IMacroService.cs
src/Umbraco.Core/Services/IMacroWithAliasService.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs
src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
src/Umbraco.Infrastructure/Services/Implement/MacroService.cs
src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs
src/Umbraco.Infrastructure/Templates/IHtmlMacroParameterParser.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MacroServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.PublishedCache.NuCache/SnapDictionaryTests.cs

Fixes #8131 for Umbraco 9
After adding the [item tracking improvements](https://github.com/umbraco/Umbraco-CMS/pull/11919), there was still the issue that media items were not tracked when added via macro parameters in Rich Text Editor and Grid layout. @marcemarc had made a [PR](https://github.com/umbraco/Umbraco-CMS/pull/8614) for Umbraco 8 resolving the issue (🎉 H5YR! 💪 ) and this is the fix for Umbraco 9. 
- Have the SK installed
- Create a Partial View Macro File called `InsertFiles.cshtml` ( ❗ _Note: code below_)
- Allow the macro with the same name to be used in Rich Text Editor and the Grid
- Add a macro parameter (ex: `Files (files) :  Umbraco.MultipleMediaPicker`)
- In a **Rich Text area** on a content node, insert the macro and pick a media item as the macro param
- It should …

Fix media tracking of items added via macro parameters in RTE and Grid 

---

src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs
src/Umbraco.Infrastructure/HostedServices/HealthCheckNotifier.cs
src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
src/Umbraco.Infrastructure/HostedServices/LogScrubber.cs
src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
src/Umbraco.Infrastructure/HostedServices/TempFileCleanup.cs
src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs

If there's an existing issue for this PR then this fixes #12022
`RecurringHostServices` used by Umbraco are currently implemented with the usage of Timers.
The problem is that, by default, the execution context will flow, resulting in the Ambient context scope being shared by different threads.
Compounding this issue is the fact that any exception in these services isn't being caught, causing the whole AppDomain to be terminated.

Fixes RecurringHostServices leaking the execution context / ambient scope

---

src/Umbraco.Core/StaticApplicationLogging.cs
src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12170.
There's a regression in 9.4 when you've inheriting from `RecurringHostedServiceBase` and using the previous (now obsoleted) constructor, because the `StaticServiceProvider.Instance` is still `null` here:
https://github.com/umbraco/Umbraco-CMS/blob/7114c564da5f0b753e2f42d01a4a1cf4e08d78fb/src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs#L52
This is because it's set when the `IRuntime` is started, which is also an `IHostedService` and resolved from the service provider at the same time:
https://github.com/umbraco/Umbraco-CMS/blob/864fd2a45a6afba067cc2d03cafed0d54b602889/src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs#L159
I've first tried fixing this by …

Fix obsolete constructor in RecurringHostedServiceBase

---

src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.controller.js

Currently users can see groups they don't have access to.
This PR will fix this based on the suggestion made by [lbras](https://github.com/lbras) in issue #12168
There's an existing issue for this PR:  #12168
- Create a user
- Assign him a group that has access to the User section
- Login as the created user go to the User section, open the Groups list and make sure he can only see Groups he has access to
- For more detail see #12168

Only show groups the user has access to

---

src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs
src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
src/Umbraco.Web.Common/Routing/UmbracoRequestOptions.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12083
As described in the issue, this stems from "/sitemap.xml" being treated as a Client request and therefore we have no UmbracoContext and it throws an exception, I've come up with a solution that I hope is satisfying, where you can now "AllowList" some routes in your startup.cs/ConfigureServices
For a single route: 
```
services.Configure<UmbracoRequestOptions>(options =>
{
options.HandleAsClientSideRequest = httpRequest =>
{
return httpRequest.Path.StartsWithSegments("/sitemap.xml");
};
});
``` 
For multiple routes:
``` 
services.Configure<UmbracoRequestOptions>(options =>
{
string[] allowList = new[] {"/sitemap.xml", ...};
options.HandleAsServerSideRequest = httpRequest =>
{
foreach (string route in allowList)
{
if …
```

v9: fix cannot map mvc route to client side request

---

src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
src/Umbraco.Web.UI.Client/src/views/content/content.protect.controller.js

This fixes [issue 12177](https://github.com/umbraco/Umbraco-CMS/issues/12177), but there may be a little more investigation needed.
This definitely worked in an earlier V9 version as I have it set up in a local test project, and I haven't figured out where the bug crept in.  It's also a little odd that we have these methods defined both on the `contentResource` (which is being used here), but also on the `publicAccessResource`, which isn't.

Corrected the base URL to use when retrieving and setting public access details.

---

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs

Pass culture code into GetAtRoot method in Siblings extensions to ensure the passed culture code is respected
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12143
The Siblings extension method accepts a culture parameter, but for root nodes this was not respected. This was due to the parameter not being passed down to the GetAtRoot method. I have added the culture parameter to the three relevant extension methods.
Note that @patrickdemooij9 confirmed that this was not considered a breaking change.
To test this, do the following:
1. Set up a clean Umbraco install
2. Create a document type called Site which is allowed at root and varies by culture
3. Set up French (France) (fr-FR) as an additional language (or any other language)
4. …

Pass culture code into GetAtRoot method in Siblings extensions

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

If there's an existing issue for this PR then this fixes it
When you are editing a ListView Block the headlineEditorAppearance key is used but the current text for the dictionary key is 'Editor apperance' and should be 'Editor appearance' for UK and US languages...
Thanks for accepting this contribution to Umbraco CMS!

Making an update for appearances sake

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs

Fixing issue #12186 by adding an additional null check
- Make sure there are 2 languages, for example Dutch, with fallback to English.
- Add culture variant property to documenttype with Multi Url Picker type.
- Create node in Dutch, don't fill the newly added property
-  Publish
- Go to English and pick random node to property
-  Publish
-  Publish
-  In the view try to get value for property: Model.Value<IEnumerable<Umbraco.Cms.Core.Models.Link>>("newProperty", "nl", Culture, fallback: Fallback.ToLanguage)
- this should show the value of the english language
For more information see #12186

Fix MultiUrlPickerValueConvert IsValue function

---

src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html

I have previous replaced most icons in backoffice to use `<umb-icon>` component, instead of the legacy `<i>` element, which was mainly used/needed for font icons.
However it seems we not have a few of these back in the UI, e.g. in trash icon in file upload component.

Use icon component for icons

---

src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs

Closes #12110
1) Checkout a v8 branch e.g. v8/8.18
2) Ensure models builder mode isn't PureLive i.e. set the following appsetting in `web.config` **IMPORTANT**
```xml
<add key="Umbraco.ModelsBuilder.ModelsMode" value="Nothing"/>
```
3) Add the following demo controller to project
```csharp
public class DemoController : UmbracoApiController
{
[HttpGet]
public IHttpActionResult Demo()
{
var rootNodes = Current.PublishedSnapshot.Content.GetAtRoot();
return Ok(rootNodes.Select(x => x.Id));
}
}
```
4) Run site & create three identical doc types with a single textstring property (DoctypeA, DoctypeB, DoctypeC)
4) Allow all of these doc types to be created at root
5) Create 3 content nodes at root, one for each doc type
6) Visit demo controller - note 3 entries (makes sense)
7) In back office …

Fix issue - changing a document type broke the nucache data structure

---

src/Umbraco.Web.UI.Client/src/views/users/user.controller.js

Found a typo in user controller - `busy` was spelled `busfy`. This PR corrects the typo, which will ensure the button state is set correctly when enabling a user.

busfy => busy

---

src/Umbraco.Core/Configuration/Models/KeepAliveSettings.cs

Fix KeepAlive Config so that value from appsettings.json is used if present
Currently, any value in appsettings.json is ignored

Fix KeepAlive Config so that value from appsettings.json is used

---

src/Umbraco.PublishedCache.NuCache/ContentStore.cs

Cherry picked fix from v8 - see #12208 for details
Steps to repro as before but with v9 style e.g.
```json
{
"Umbraco": {
"CMS": {
"ModelsBuilder": {
"ModelsMode": "Nothing"
}
}
}
}
```
```csharp
public class DemoController : Controller
{
private readonly IPublishedSnapshotAccessor _accessor;
public DemoController(IPublishedSnapshotAccessor accessor)
=> _accessor = accessor;
[HttpGet("demo")]
public IActionResult Demo()
{
_accessor.TryGetPublishedSnapshot(out var snapshot);
return Ok(snapshot.Content.GetAtRoot().Select(x => x.Id));
}
}
```

v9 - Fix issue - changing a document type broke the nucache data structure

---

.gitignore
templates/Umbraco.Templates.nuspec

When locally debugging Umbraco, I always boot it up and install the starter kit (or some other package with views). When I switch branches though, I do a proper clean (`git reset && git clean -df && git checkout -- . `) before checking out a new branch. This means the custom views of the starter kit / other package get deleted. 
I've always thought this was because of a package reinstall, but it turns out it's because of the branch switching! In this PR we're ignoring the whole Views folder, except for the required files that we do need in there for blocklist, grid and the default ViewImports. Now when switching branches (I do this anywhere between 2 and 30 times a day!) I don't have to jump through hoops to restore the views to be able to test something. 
Also, I don't have to be scared …

Ignore the views folder apart from required files

---

src/Umbraco.Web.Website/ActionResults/RedirectToUmbracoPageResult.cs

Fixes #12258.
To Test:
- Following the reproduction steps described on the issue, and confirm that the redirect occurs as expected whether or not a domain is defined.
- Check that providing a querystring (e.g. with the code below) works too with both pages with domains defined and those without.
```
var querystring = QueryString.Create("foo", "bar");
return RedirectToUmbracoPage(Guid.Parse("f62a9934-0491-439c-9a04-f2562a597718"), querystring);
```

Fixes RedirectToUmbracoPageResult to handle redirects to pages with domains defined on them

---

src/Umbraco.Infrastructure/Security/MemberUserStore.cs

This fixes #11931
When a member is created through the backoffice the `umbracoMemberLastLogin` property is not created since the member isn't logged in, this causes the property to remain nonexisting until a member fails to log in, meaning the value is never set. 
The reason for this is that we have an optimization in `MemberUserStore` where we will try to only update the value of the `umbracoMemberLastLogin` property data when a member is logging in, instead of re-saving the member, but we of course can't do this to property data row that does not exist.
To fix this I've added a check, so if the members `LastLoginDate` is default we will do a full save on login, creating the property. 
* Create a content node that has the login snippet 
* Create a member in the backoffice
* Try and log …

Fix member last login date not being set

---

src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs

This fixes #11931 
For more information on the bug and what caused it see: #12207, in V8 it's just a bit harder to reproduce.
There's a  bit of testing to test this. Essentially the bug only occurs when you create a member "manually" through the `IMemberService.CreateMember`, so to test this you must:
1. Create a surface controller that uses `MemberService` to create a member (see below)
2. Create a partial view that sends a form to the surface controller (see below)
3. Render the partial view in a content node
4. Render the default login partial in a content node
5. Create a member using the rendered partial view
6. Observe in the backoffice that no "Last Login Date" is set
7. Log in on the front end, and ensure that "Last Login Date" is now set
Surface controller code: 
```C#
using …
```

V8: Fix member last login date not being set

---

src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web/Editors/MediaController.cs

Ported over the fixes in the v9 PR #11858 **Check media Parent for permissions when setting correct MediaType** to v8.
If there's an existing issue for this PR then this fixes [#7735](https://github.com/umbraco/Umbraco-CMS/issues/7735)
I have ported over fixes from the v9 PR #11858, as the fixed issue also affected v8, the fixes have been tweaked slightly to work with v8's codebase.
**Description from the v9 PR:**
> Ever since Umbraco version 8.14, the way media gets uploaded has changed. In the past, uploading media directly from a MediaPicker would respect the permissions set on the upload folder when not using the default mediaType of "Image". Ever since version 8.14 this has changed, and even if the folder does not allow the default "Image" item to be uploaded, it still forces the …

Ported over the fixes in #11858 "Check media Parent for permissions when setting correct MediaType" to target v8

---

src/Umbraco.Core/Models/MemberType.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTypeTests.cs

Fixes a bug where no matter what custom member properties will always be marked as sensitive (see gif)
This was caused by a combination of 2 things. 
1. When mapping the content type DTO, "Is sensitive" is always set first
2. If "Is sensitive" was updated as the first custom member acces modifier, a `MemberTypePropertyProfileAccess` will be created and here the `isSensitive` parameter was hardcoded to true, instead of using the `value` parameter
Follow the same steps as in the GIF and ensure that "Is Sensitive" is correctly set.

V9: Fix member properties always being sensitive

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.LocalizedText.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs

Issue #11986  
Uses the WebHost FileProviders to get the files
this means they don't have to be in the physical root of the site and can be in other places,
so Razor class libraries which use a virtual path provider can be loaded along side files on the site
For testing - i have checked : 
- Place a lang xml file (like the example below) in to the following locations 
- /App_Plugins/Test/lang/en-us.xml
- /config/lang/en-us.user.xml
- /wwwroot/app_plugins/text/lang/en-us.xml
when you load the back office you shoud see the values in the `LocalizedText` file returned by umbraco (viewed via the browser console)
_Building the nuget packages for Umbraco and then starting a new site with dotnet new / package-ref_
- check the tests as above 
To check razor class libraries (RCL) work : 
- create a …

Get lang files via FileProviders (and support Razor Class Libraries) 

---

src/Umbraco.Core/Cache/IRepositoryCachePolicy.cs
src/Umbraco.Core/IO/FileSystemExtensions.cs
src/Umbraco.Core/IO/IFileSystem.cs
src/Umbraco.Core/IO/MediaFileManager.cs
src/Umbraco.Core/IO/ShadowFileSystem.cs
src/Umbraco.Core/IO/ShadowWrapper.cs
src/Umbraco.Core/IO/ViewHelper.cs
src/Umbraco.Core/Mapping/IUmbracoMapper.cs
src/Umbraco.Core/Mapping/MapperContext.cs
src/Umbraco.Core/Media/UploadAutoFillProperties.cs
src/Umbraco.Core/Models/PublishedContent/IPublishedElement.cs
src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs
src/Umbraco.Core/Models/PublishedContent/PublishedElementWrapped.cs
src/Umbraco.Core/Packaging/PackagesRepository.cs
src/Umbraco.Core/Persistence/Repositories/IFileRepository.cs
src/Umbraco.Core/Persistence/Repositories/IMacroWithAliasRepository.cs
src/Umbraco.Core/PublishedCache/Internal/InternalPublishedContent.cs
src/Umbraco.Core/PublishedCache/PublishedElement.cs
src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Infrastructure/Mapping/UmbracoMapper.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepositoryBase.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/FileRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PartialViewRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs

I found the following in taking a dependency on the latest CMS nightly for Forms, and looking to implement NRT in there.  I found these issues that seemed like they could be implemented differently in CMS.
There's one update per commit, so if you agree with some and not all it should be fairly easy to adjust.
- Amended IFileSystem OpenFile to return Stream.Null rather than a nullable stream.
- Amended EntityRepositoryBase to not return null collections.
- Made IPublishedElement.Properties a non-nullable collection.
- Updated IUmbracoMapper to map enumerables without null elements given non-null inputs.

Updates to null reference types

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.LocalizedText.cs

Turns out in .net 6 - getting directory contents with the Composite file provider on `IWebHostEnvironment `no longer includes the physical path. 
this version of the method builds the path to the lang folder then requests the files directly via the provider to get the physical file locations. 
also in .net 6 the `WebRootFileProvider `returns a complete composite of /app_plugins that includes files in the physical /app_plugins, wwwroot/app_plugins and and files in app_plugins from a razor class library, so there is no longer the need perform the check twice (once for each folder location) as was being done previously
testing as before 
Issue #11986  
Uses the WebHost FileProviders to get the files
this means they don't have to be in the physical root of the site and can be in other places, …

Updated for v10 - Get lang files via FileProviders (and support Razor Class Libraries)

---

src/Umbraco.Core/Strings/DefaultShortStringHelper.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/DefaultShortStringHelperTests.cs

Skip surrogate pairs (e.g. emojis) when making clean stings, instead of throwing exceptions
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12276

Skip surrogate pairs (e.g. emojis) when making clean stings.

---

src/Umbraco.Web.BackOffice/Security/BackOfficeAntiforgery.cs

Addresses issue: https://github.com/umbraco/Umbraco-CMS/issues/12285
I added the setting of the securitypolicy on the UMB-XSRF-V cookie based on the value global usehttps setting.  
Testing can be done by logging into backoffice.  Examine the cookie list in the browser.  The secure should be marked on the UMB-XSRF-V cookie.  Like this:
The before image can be see on the issue link above.

Added secure to the UMB-XSRF-V cookie when global https is true.

---

src/Umbraco.Core/Extensions/EnumerableExtensions.cs
src/Umbraco.Core/Packaging/PackagesRepository.cs
src/Umbraco.Core/Routing/UrlProviderExtensions.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Infrastructure/Manifest/ManifestParser.cs
src/Umbraco.Infrastructure/Migrations/Expressions/Delete/KeysAndIndexes/DeleteKeysAndIndexesBuilder.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/11652 updated the target framework to .NET 6 and renamed the existing `DistinctBy` extension method to `LegacyDistinctBy`, because that was clashing with the [one introduced in .NET 6](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinctby?view=net-6.0).
I've split the work into 3 commits, so we can optionally cherry-pick/revert parts if we want:
1. Obsolete `LegacyDistinctBy` - users should use the default framework extension method instead
2. Remove usage of `LegacyDistinctBy` - we don't want to use obsolete methods in our own codebase (this also includes some performance enhancements, because you can pass in a custom `IEqualityComparer` to do case insensitive comparisons, instead of converting the key into …

v10: Remove LegacyDistinctBy

---

src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs
src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs
src/Umbraco.Infrastructure/Examine/ValueSetValidator.cs
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExtensions.cs
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Examine/UmbracoContentValueSetValidatorTests.cs

This PR updates examine to version 3.
And fixes the breaking changes..
- Examine 3 breaking changes
- `ValueSet` immutable. 
- `ValueSetValidationResult` is renamed to `ValueSetValidationStatus` and `ValueSetValidationResult` is now a type

Update examine to version 3

---

src/Umbraco.Web.UI/Views/Partials/grid/editors/base.cshtml

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12262
If there's an existing issue for this PR then this fixes [https://github.com/umbraco/Umbraco-CMS/issues/12262]
Pretty small change - remove the ToLower() when finding the path to a grid editor so it works on Linux.

Grid editors not working on Linux frontend

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12309
When having multiple tree root nodes in content section besides default configuration, e.g. moving Content Templates and Dictionary trees, the link picker was showing all trees and not limited to just content tree.
**Before**
**After**
Content Picker / MNTP already restrict the tree picker to content tree here:
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L190

Limit link picker to content tree in content section

---

src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
src/Umbraco.Cms.StaticAssets/buildTransitive/Umbraco.Cms.StaticAssets.props
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj

Reintroduces `DefaultItemExcludes` in Umbraco.Cms.StaticAssets

Bugfix: Reintroduces DefaultItemExcludes in Umbraco.Cms.StaticAssets

---

src/Umbraco.Core/Models/ContentEditing/EntitySearchResults.cs
src/Umbraco.Core/Models/ContentEditing/SearchResultEntity.cs
src/Umbraco.Core/Trees/ISearchableTree.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
src/Umbraco.Web.BackOffice/Trees/DataTypeTreeController.cs
src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs
src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs
src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs

Async support for umbraco tree search. Example use case: Azure Search index.
How to test?
Run a search from each of:
Backoffice global search
MultiNodeTreePicker search
```cs
IEnumerable<SearchResultEntity?> Search(string query, int pageSize, long pageIndex, out long totalFound, string? searchFrom 
= null)
``` 
changed to
```cs
Task<EntitySearchResults> SearchAsync(string query, int pageSize, long pageIndex, string? searchFrom = null);
```

v10: Async tree search

---

src/Umbraco.Core/Routing/ContentFinderByIdPath.cs
src/Umbraco.Core/Routing/ContentFinderByPageIdQuery.cs
src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
src/Umbraco.Core/Routing/ContentFinderByUrl.cs
src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
src/Umbraco.Core/Routing/ContentFinderByUrlAndTemplate.cs
src/Umbraco.Core/Routing/IContentFinder.cs
src/Umbraco.Core/Routing/PublishedRouter.cs
src/Umbraco.Infrastructure/Routing/ContentFinderByConfigured404.cs
tests/Umbraco.Tests.Common/TestLastChanceFinder.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasWithDomainsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByIdTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByPageIdQueryTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAndTemplateTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlWithDomainsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/DomainsAndCulturesTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UrlsWithNestedDomains.cs

The published router is async, however the content finders are not. This limits routing scalability as we are unable to use async code to route.
This changes contentfinders to be async, and improves logging by not calling log debug when debug level logging is not enabled, saving on allocations.
How to test?
Existing tests pass.

v10: Async support for content finders. Improve loging performance.

---

src/Umbraco.Web.UI.Client/lib/bootstrap/less/button-groups.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/code.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/forms.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/hero-unit.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/labels-badges.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/mixins.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/navbar.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/popovers.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/responsive-1200px-min.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/thumbnails.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/tooltip.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/type.less
src/Umbraco.Web.UI.Client/lib/bootstrap/less/variables.less
src/Umbraco.Web.UI.Client/src/less/button-groups.less
src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less
src/Umbraco.Web.UI.Client/src/less/components/card.less
src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
src/Umbraco.Web.UI.Client/src/less/components/umb-box.less
src/Umbraco.Web.UI.Client/src/less/forms.less
src/Umbraco.Web.UI.Client/src/less/hacks.less
src/Umbraco.Web.UI.Client/src/less/mixins.less
src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card-grid.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/notsupported/notsupported.less

PR https://github.com/umbraco/Umbraco-CMS/pull/12288 updated `less` from 3.10.3 to 4.1.2, but this new major version uses a different default math option (see docs: https://lesscss.org/usage/#less-options-math), resulting in invalid CSS output and thus broken layouts. The previous default `always` option is now deprecated, so instead of changing the build script to use that option again, I've fixed all math calculations.
The new default `parens-division` option requires all divisions to be performed within parentheses, so after a quick regex search (using `(?<![/*])/(?![/*])` to exclude comments) and a lot of opening and closing parentheses, the diffs were the same again. Next up, I changed the option to `strict` and did the same for all other math operations and ensured we don't do …

v10: Fix LESS math

---

src/Umbraco.Core/Collections/StackQueue.cs
src/Umbraco.Infrastructure/Scoping/Scope.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Collections/StackQueueTests.cs

This was originally merged into v9 without updating the namespace to the new "Umbraco.Cms" pattern.
- `StackQueue` has been moved from `Umbraco.Core.Collections` to `Umbraco.Cms.Core.Collections`  namespace.

Moved StackQueue to correct namespace

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

This is a continuation of #12348 where the package-lock.json file has been updated and the slider has been tested in the backoffice.
NoUiSlider v15.6.0 has been released which allow [smooth steps behaviour](https://github.com/leongersen/noUiSlider/releases/tag/15.6.0) combined with steps.
See demo here: https://refreshless.com/nouislider/behaviour-option/#section-smooth-steps

Update NoUiSlider to 15.6.0

---

src/Umbraco.Core/Deploy/ArtifactDeployState.cs
src/Umbraco.Core/Deploy/ArtifactDeployStateOfTArtifactTEntity.cs
src/Umbraco.Core/Deploy/ILocalLinkParser.cs
src/Umbraco.Core/Deploy/IServiceConnector.cs
src/Umbraco.Core/Deploy/IValueConnector.cs
src/Umbraco.Core/Persistence/Repositories/IMemberTypeContainerRepository.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Core/Services/EntityXmlSerializer.cs
src/Umbraco.Core/Services/IContentTypeServiceBase.cs
src/Umbraco.Core/Services/IRelationService.cs
src/Umbraco.Core/Services/MemberTypeService.cs
src/Umbraco.Core/Services/RelationService.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs
src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberTypeContainerRepository.cs
src/Umbraco.Web.BackOffice/Controllers/ContentTypeControllerBase.cs

One more set of collections that should really return empty rather than nullable results.
Note that in this PR I've also created a `IMemberTypeContainerRepository` and a no-op implementation.  Members don't support containers, but by having this we can be a bit more consistent in the different types of content type services and repositories (i.e. content, media and member) and avoid having a null dependency.

Ensured container collections retrieved from content type services return empty rather than nullable.

---

build/azure-pipelines.yml

This PR fixed deprecation warning (-p changed to --project) and sets the global id as an environment variable instead of pushing directly into each ´dotnet run´. Also fixed to use valid guid 🤦

Use static global id in pipelines

---

src/Umbraco.Core/Composing/ComponentComposer.cs
src/Umbraco.Core/DependencyInjection/IUmbracoBuilder.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.MappingProfiles.cs
src/Umbraco.Web.BackOffice/Extensions/WebMappingProfiles.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs

I noticed `WithCollectionBuilder()` and any of the shortcuts/helper methods retuned a nullable type, which can't occur (it throws an exception otherwise).
This requires all calls to these methods to include a null-check or use the null-conditional operator, making the API a bit more verbose then necessary:
```c#
builder.ContentFinders()?.Append<MyCustomContentFinder>();
// vs
builder.ContentFinders().Append<MyCustomContentFinder>();
```

NRT amends for WithCollectionBuilder to improve API

---

src/Umbraco.Web/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs

Possible NullReferenceException in MultiUrlPickerValueConverter, seems to work for v8 too with bugging Multi Url Pickers in Doc Type Grid Editor.
If there's an existing issue for this PR then this fixes #12109

Porting fix from #12109

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
src/Umbraco.Core/Models/CultureImpact.cs
src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Core/Services/CultureImpactService.cs
src/Umbraco.Core/Services/ICultureImpactService.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/CultureImpactTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/ContentControllerTests.cs

Added the necessary backend changes to allow you to publish invariant properties from the non-default culture. 
This can be toggled on/off with the new `Umbraco:CMS:Security:AllowEditInvariantFromNonDefault` appsetting.
For now, I've also added the appsetting to server variables in case it's needed. 
While I'm here I've also tried to do a bit of cleaning up around the `CultureImpact` class, basically, I've tried to move as much logic as I can into the new `ICultureImpactService`, instead of having it in the "model". However currently we rely on some of the `CultureImpact`s to be static in order to do comparisons, so I've left those static in `CultureImpact` and just proxy them from the service.
Set `Umbraco:CMS:Security:AllowEditInvariantFromNonDefault` to true and try and publish an …

Publish invariant properties

---

tests/Umbraco.Tests.UnitTests/Umbraco.Core/EmbeddedResources/LanguageXmlTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs

- Since language files are now embedded resources, this PR reintroduces the language files tests removed in #12324
- Make sure the tests succeed;
- Make one of the language files located in `~\Umbraco.Core\EmbeddedResources\Lang` folder invalid and verify that the `Can_Load_Language_Xml_Files()` test fails;
- Add a new file in the same folder with an upper case name (ex: _BG.xml_) and verify that the `LanguageFilesAreLowerCase()` test fails with a message: `Language files must be all lowercase but BG.xml is not lowercase.`.

Reintroduce language files tests

---

src/Umbraco.Cms.Persistence.SqlServer/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Persistence.Sqlite/UmbracoBuilderExtensions.cs
src/Umbraco.Core/Configuration/ConfigureConnectionStrings.cs

When using the [connection string environment variables](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#connection-string-prefixes), the provider name is set to `System.Data.SqlClient`. Umbraco/NPoco 5 however uses the `Microsoft.Data.SqlClient` provider and would therefore not find the correct provider to use.
You can test this by setting this environment variable and running the Umbraco.Web.UI project:
```powershell
❯ Set-Item Env:\SQLCONNSTR_umbracoDbDSN "Data Source=(localdb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Umbraco.mdf;Integrated Security=True"
❯ dotnet run
Building...
[INF] Acquiring MainDom.
[INF] Acquired MainDom.
[WRN] Could not check the upgrade state.
System.ArgumentException: The specified invariant name 'System.Data.SqlClient' …
```

v10: Support System.Data.SqlClient provider name

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs

This fixes https://github.com/umbraco/Umbraco-CMS/issues/12310
Together with `ContentItemDisplay.Name` also translate `ContentItemDisplay.Description`.
This allows editors to use the `#label` notation.
Fixes issue for Block List and Nested Content

Fix Dictionary item not working in block description

---

src/Umbraco.Core/Models/Trees/ActionMenuItem.cs
src/Umbraco.Core/Models/Trees/ExportMember.cs
src/Umbraco.Core/Models/Trees/MenuItem.cs

A minor oversight in https://github.com/umbraco/Umbraco-CMS/pull/12403 where the export member action is missing the `icon-` prefix as it now specify full icon name (for future development and sometime later we can probably remove the `useLegacyIcon` property).
// @nathanwoulfe

Menu action icons

---

src/Umbraco.PublishedCache.NuCache/ContentCache.cs
src/Umbraco.PublishedCache.NuCache/DomainCacheExtensions.cs

This fixes #12331.
This is another issue related to the fact that invariant culture is sometimes referenced with an empty string sometimes, and other times a null value.
The issue was that we have an extension method `GetAssignedWithCulture` which returns true if there's a domain associated with a node, otherwise false. 
This endpoint will try and find the specific domain for a particular culture if a culture is specified, and only return true if it finds something, however, with invariant nodes it should just return true if there are **any** domains. This invariant node check would sometimes fail because an empty string was passed in, instead of null, however, both mean invariant, so I've updated the check with a  `string.IsNullOrEmpty(culture)`, so it's always caught now. 
Follow the …

V9: Fix URL generation when publishing invariant content with domains

---

src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js

This fixes #12306.
The problem was that #11587 mobed the password property from the tabs list to the `membershipProperties` property, this meant that when posting the member save the reset value was never set to anything, causing the password reset to fail. I've fixed this so we now look in the correct property.
1. Ensure that you can't change member passwords
1. Enable the `allowManuallyChangingPassword` config in web.config
2. Ensure that you can now change member passwords

V8: Fix changing member password

---

src/Umbraco.Web.BackOffice/Controllers/TwoFactorLoginController.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12384
We need to use invariant culture when doing ToString of user ints
To test change user culture to e.g Swedish and open the user panel

Fixed ICU problem with userId (int) converted to string

---

src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
src/Umbraco.Cms/buildTransitive/Umbraco.Cms.targets

The msbuild target that copies Umbraco folders was not in a target file, and thereby not part of the nuget file.

Move msbuild target to correct location

---

src/Umbraco.Infrastructure/TypeForwards.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12457
- Added TypeForwards file
- Install 9.5 templates with `dotnet new -i Umbraco.Templates`
- Create 9.5 project with `dotnet new umbraco -n TestProject`
- Download my UmbraPack nupkg
[UmbraPack.1.0.0.nupkg.zip](https://github.com/umbraco/Umbraco-CMS/files/8761826/UmbraPack.1.0.0.nupkg.zip)
(Remove the .zip after download)
- Add the folder as a local nuget feed
- Install the UmbraPack nupkg in your new 9.5 project
- Run the project and install
- Try creating a new Datatype, you should see the test property editor
- Stop your project and upgrade it to 10.0.0-rc3 (remember to update your .NET version to 6 if it isn't)
- Run again and you should now get an error!
- Run dotnet pack in the root of this branch to generate nuget packages: …

Add TypeForwards file with type forwarding

---

src/Umbraco.Core/PropertyEditors/NestedContentConfiguration.cs
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js

This feature is a reimplementation of PR: https://github.com/umbraco/Umbraco-CMS/pull/9883 of @patrickdemooij9 to add an option to disable nested content automatically expanding if the max items is set to 1 and the slider is turned off.
Visual of how this works is posted in attached closed PR.
Can be checked with:
- Create a new nested content with min 0, max 1.
- Whenever you open it on a node, it will automatically open if you have an item in it.
- If you uncheck the new option, it'll not automatically open on load.

added option to disable automatic expand of single nc item

---

src/Umbraco.Infrastructure/Services/CacheInstructionService.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12473 which caused load balanced clients not to refresh content caches.
Really only changed `is not null` to `is null` to make the refreshers process the instructions properly.

Fixed null check typo in CacheInstructionService. Fixes #12473.

---

src/Umbraco.Core/Configuration/Models/ConnectionStrings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
src/Umbraco.Core/Extensions/ConfigurationExtensions.cs
src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
src/Umbraco.Infrastructure/Install/InstallHelper.cs
src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseUpgradeStep.cs
src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/12464.
Extending on PR https://github.com/umbraco/Umbraco-CMS/pull/12472, this ensures the `JsonConfigurationManipulator` also updates the `IConfiguration` values and forces a reload (even when no JSON file is found). I've also ensured we don't throw an `InvalidOperationException` anymore when no `JsonConfigurationProvider` can be found.
By forcing the reload, all `IOptionsMonitor<ConnectionStrings>` values are removed from the internal cache, ensuring the options factory creates new instances based on the updated values from `IConfiguration` and ensuring all `Configure` callbacks are run again (which for SQLite changes the mode from `ReadWriteCreate` to `ReadWrite`).
This also removes …

v10: Instantly reload ConnectionStrings after saving configuration

---

templates/UmbracoProject/.gitignore

Remove the rules for umbraco static assets as these are now served from a Razor Class Library
I have also updated the path of `appsettings-schema.json` in anticipation of https://github.com/umbraco/Umbraco-CMS/pull/12416 (it doesn't currently exist at all in v10)

Update template gitignore for static assets now in Razor Class Library

---

src/Umbraco.Core/Actions/ActionDelete.cs

`ActionDelete.ActionAlias` used to be public but it seems to have been made private without warning. This reverses that change and makes it public again.

v10: Make ActionDelete.ActionAlias public again

---

src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs

This PR migrates #12330 to V9, adding the missing content type events when copying:
* MemberTypes
* DocumentTypes
* MediaTypes
These missing events are: 
* Saving
* Changed
* Saved
Add notifications handlers the the expected event and try and copy the different content types.
I used this notification handler and put a breakpoint on each handle method:
```C#
using Microsoft.Extensions.Logging;
namespace Umbraco.Cms.Web.UI
{
public class TestHandler :
INotificationHandler<MemberTypeSavedNotification>,
INotificationHandler<MemberTypeChangedNotification>,
INotificationHandler<MemberTypeSavingNotification>, …
```

V9: Send content type notifications on copy

---

src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12464.
We've seen some intermittent exceptions when the attended installer is used in the latest v10 RCs, but couldn't easily reproduce it when debugging (which indicates some kind of race-condition/timing issue).
The ASP.NET Core configuration system does support reloading, but when calling [`IConfigurationRoot.Reload()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationroot.reload?view=dotnet-plat-ext-6.0), it will reload all providers and apparently trigger `IOptionsMonitor<ConnectionStrings>.OnChange` multiple times: sometimes with the correct/updated value, but also sometimes with an empty value. The JSON configuration provider however …

v10: Wait for updated ConnectionStrings during install

---

src/Umbraco.Core/Actions/ActionAssignDomain.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12358
- As @nathanwoulfe mentions in the issue, this is related to https://github.com/umbraco/Umbraco-CMS/pull/11784, here we fixed the casing of `assignDomain` to be all lowercase to handle case sensitive file-systems.
- After this, it seems a merge conflict was not handled correctly here: https://github.com/umbraco/Umbraco-CMS/commit/235918ecfccf3501fa1a046fdac6c77f8ddf6ea4, and this was reverted to camelCase
Which is also why this is not a problem in v9
- Create an empty document type and allow as root
- Create some content
- Right click on your new action node, it should now display "Culture and Hostnames"
- Please also verify this is the same by click the "Action" button when on a content node

V10: assigndomain key not found

---

src/Umbraco.Core/Scoping/ICoreScope.cs
src/Umbraco.Infrastructure/Scoping/Scope.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Scoping/ScopeUnitTests.cs

Adds a depth property to ICoreScope so that you know how far a child scope is from the root scope.
This doesn't resolve any issues in particular but adds some clarity when debugging issues with nested scopes.

v10: Add depth property to ICoreScope

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Scoping/AmbientScopeContextStack.cs
src/Umbraco.Infrastructure/Scoping/AmbientScopeStack.cs
src/Umbraco.Infrastructure/Scoping/IAmbientScopeContextStack.cs
src/Umbraco.Infrastructure/Scoping/IAmbientScopeStack.cs
src/Umbraco.Infrastructure/Scoping/Scope.cs
src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopeTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ThreadSafetyServiceTest.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Scoping/ScopedNotificationPublisherTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Scoping/ScopeUnitTests.cs

This change makes it easier to use service calls in parallel whilst a httpcontext is available.

v10: Remove ambient scope stack from httpcontext.items.

---

src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs

Whilst SQLite has a flexible typing system it makes sense to stick to the natively supported types i.e TEXT,BLOB,INTEGER,REAL.
This PR ensures that we stick to one of the above types where possible when creating a database from scratch or running a migration for SQLite.
Should close #12524

v10: Prefer SQLite primitive types to flexible types

---

src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.LocalizedText.cs

Languages files were discovered when placed at `~/App_Plugins/{{PackageName}}/lang/foo.xml` but not from sub directories e.g. `~/App_Plugins/{{PackageName}}/foo/bar/lang/foo.xml`.
This PR fixes the issue by recursively scanning for lang directories under a package directory.
Closes  #12521

v10: Fix issue where languages files are not found in subdir of package dir

---

src/Umbraco.Web.Common/Controllers/IVirtualPageController.cs

Makes FindContent of `IVirtualPageController`.
This is because in this context null is handled as "Not Found", otherwise you have to throw an error, which isn't the greatest idea since not found is expected behaviour

Make FindContent return type nullable

---

src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs

FlagOutOfDateModels should occur when using SourceCodeManual.
At present this is always set to false when ModelsMode is not one of
+ InMemoryAuto 
+ SourceCodeAuto
In v8 this was forcibly set to false when ModelsMode is any of the following (via IsLive extension)
+ Nothing
+ PureLive
+ LiveAppData
IsLive was replaced by IsAuto in #10272
This was spotted whilst looking into https://our.umbraco.com/forum/using-umbraco-and-getting-started/108700-modelsbuilder-stopped-working

v9: Fix logic error WRT models builder flag out of date models.

---

src/Umbraco.Core/Models/RelationItem.cs

Fixes exception when viewing an item in recycle bin, that was deleted from root.
This is now fixed, but the UX is still a bit weird, due to the fact the roots are fake nodes, and especially the name is a bit unfriendly.

V9: fix relation issue when moving root item to recycle bin

---

src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs

Prevents DirectoryNotFoundException being thrown for /tmp/UmbracoData/{{hash}} thrown when trying to create lock / lock release files as the path doesn't exist yet when using LocalTempStorageLocation = EnvironmentTemp.
Fixes #12562

v10 Fix attempting to write lock files to LocalTempPath before it exists

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umblightbox.directive.js

Current issue: [v10 - Packages section - Umbraco Lightbox close problem](https://github.com/umbraco/Umbraco-CMS/issues/12477)
Go to the dashboard
Visit the packages page,
Select a package that has some images( like Vendr)
Click by mouse on one of the images
Then if press the browser back button, the Umbraco lightbox must be closed properly.

Close umbraco lightbox when user press browser back button

---

src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
src/Umbraco.Examine.Lucene/ConfigurationEnabledDirectoryFactory.cs
src/Umbraco.Examine.Lucene/DependencyInjection/ConfigureIndexOptions.cs
src/Umbraco.Examine.Lucene/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Examine.Lucene/Extensions/ExamineExtensions.cs
src/Umbraco.Examine.Lucene/LuceneIndexDiagnostics.cs
src/Umbraco.Examine.Lucene/LuceneIndexDiagnosticsFactory.cs
src/Umbraco.Examine.Lucene/LuceneRAMDirectoryFactory.cs
src/Umbraco.Examine.Lucene/NoPrefixSimpleFsLockFactory.cs
src/Umbraco.Examine.Lucene/UmbracoApplicationRoot.cs
src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndexDiagnostics.cs
src/Umbraco.Examine.Lucene/UmbracoLockFactory.cs
src/Umbraco.Examine.Lucene/UmbracoMemberIndex.cs

For notes, please read https://github.com/umbraco/Umbraco-CMS/pull/12479

V10: fix build warnings Examine.Lucene

---

src/Umbraco.Web/PropertyEditors/ValueConverters/BlockEditorConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentSingleValueConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentValueConverterBase.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/11712.
This is a backport of v9 PR https://github.com/umbraco/Umbraco-CMS/pull/12256 to fix a regression bug introduced by in 8.17.0 (by PR https://github.com/umbraco/Umbraco-CMS/pull/8854) when using Block List settings and ModelsBuilder mode `Nothing` together (see the first PR for details on the issue).
Testing can be done using similar steps as for v9, but using slightly different settings/code:
- Create a document type with 2 properties:
- `blocks` using the Block List editor with 2 configured blocks:
1. Content model: `Text`, settings model: `TextSettings`
2. Content model: `Text2`
- `nested` using Nested Content with 2 element types:
1. `Text`
2. `Text2`
- Add the following to …

v8: Fix Block List settings exception and optimize PVCs

---

src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs

The report site task will throw an annoying error if you don't install within one minute, since it'll try to read from a non-existing database.
I've added a check so we now only try to send if the runtime level is run, otherwise we'll just skip.
I've also increased the initial delay to 5 minutes instead of one, to minimize this being skipped.
I don't think it's a major issue if we have to wait another day regardless, since people are likely running locally when installing.
Related issue #12584

Only send telemetry when runtime level is run

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js

I've unescaped `$location.search().returnPath` because `searchParams.append` will escape it.
This prevents the double escaping of `redirectUrl` parameter.
To test the change, you simply need an Umbraco with an External Login and connect with it.

Unescape returnPath.

---

src/Umbraco.Web.UI.Client/src/less/application/grid.less
src/Umbraco.Web.UI.Client/src/less/components/tree/umb-actions.less

Preventing wrapping means that buttons can overflow their container.
Preventing text from wrapping means things can overflow their container.
Since action links have hover states / centred icons there is no need to force a single line and hide content from users.
Perhaps it's sensible to increase the minimum width of `#contextMenu` from 250px as well?
Before
After

Allow action links to wrap

---

src/Umbraco.Web.UI.Client/src/less/navs.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

If there's an existing issue for this PR then this fixes [V10 - Media Section - Create button dropdown - Fix the spacing between icons and text](https://github.com/umbraco/Umbraco-CMS/issues/12476)
- Going to the Media page
- Press Create menu
- A 15px space must exist between the menu icon and label
I added span with an inline style of 15px space to:
- make the gap size consistent with other menus
- Keep the change as simple as possible

add a gap between icon and label of media menu

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12427
Previously value in textbox property editor was always valid (or at least below 512 characters), but not it is invalid based on the validation limit. The same for textarea property editor.
Note it isn't enough to check on form `$invalid` property and this only change on submit and not when changing from invalid to valid.

Update `aria-invalid` based on valid length

---

src/Umbraco.Web.Website/Routing/PublicAccessRequestHandler.cs

Bypass the redirect to login page if the current page is the login page. 
Same for access denied page.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12007

Bypass the redirect to login page if the current page is the login page.

---

src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.LocalizedText.cs

With #12206  Lang files are loaded via the `WebRootFileProvider` - which if called once the site has started up, contains all the file providers to find lang files in app_plugins, wwwroot and and Razor class libraries. 
however if for what ever reason the LanguageServices are called before startup the `WebRootFileProvider` doesn't contain the UmbracoStatic provider for app_plugins. 
As the Languages are loaded only once and cached, if this happens then any lang files in the app_plugins folder are not loaded. 
this PR 'fixes' this by also loading and files it finds via the `ContentRootFileProvider`. (we removed this in the last PR becuase we thought it was redundant). 
This means if the languages are loaded early the `app_plugins` folder is still found (and the RCL and `wwwroot` as they …

Also read the plugin files using the content provider.

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs

Remove `AddOEmbedProvider` extension method because it should have been removed in v10. Not sure if this should go to v10 or  v11 branch now? 😄

Remove Obsolete AddOEmbedProvider extension method

---

src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerDistributedLockingMechanism.cs
src/Umbraco.Cms.Persistence.Sqlite/Constants.cs
src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDistributedLockingMechanism.cs
src/Umbraco.Cms.Persistence.Sqlite/UmbracoBuilderExtensions.cs
src/Umbraco.Infrastructure/Persistence/DatabaseProviderMetadataExtensions.cs
src/Umbraco.Infrastructure/Persistence/DbProviderFactoryCreator.cs

Changed const to return "Microsoft.Data.Sqlite" instead of "Microsoft.Data.SQLite" and made our checks case insensitive where possible. Sadly DbProviderFactories is still case sensitive so for that we support both strings.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12604

Make DB Provider names case insensitive where possible

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs

https://github.com/umbraco/Umbraco-CMS/issues/12227
These changes ensures that a member's `EmailConfirmed` property changes persists when using `ConfirmEmailAsync()` located in the `IMemberManager` interface. Before these changes, the property would be set to true temporarily in memory, but then never actually saved to the database, continuing to read false for all following requests/calls. This was happening because the `emailConfirmedDate` is only added to the list of changed columns if the member's login name or email had also been changed, resulting in `emailConfirmedDate` always being null and `EmailConfirmed` not being set.
To test, do the following:
- Create a new member in Umbraco
- Use `IMemberManager` to generate a string token
- Without these changes, use `IMemberManager` to …

Ensuring that MemberManager.ConfirmEmailAsync persists.

---

src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.PublishedCache.NuCache/ContentCache.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/12621
Added configuration to avoid a behavioral breaking changes
- Set the new `Umbraco:CMS:Global:ForceCombineUrlPathLeftToRight` setting to `false`
- Create urls and add a RTL culture..
- Ensure the URL is RTL for the RTL cultures and still LTR for LTR cultures.

Added configuration to allow RTL cultures to opt-in to reverse the url hierarchy

---

src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
src/Umbraco.Web.UI.Client/src/less/components/umb-readonlyvalue.less
src/Umbraco.Web.UI.Client/src/less/mixins.less

Add break word to avoid overflowing content / account for label values which are often used to store random data
When storing certain data in labels (in this case base64 strings), the content overflows.
Similarly with url pickers, sometimes you will paste a long url which also can overflow.
Adjusted the styling so that content wraps more elegantly.
To replicate, add some long strings / urls to relevant properties.
Before
After

Prevent overflowing property values

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js

#12596 
I Updated the umbraco content info directive in javascript to set the `isInfoTab` flag to true onInit if the currently active app is the info tab.
Steps to test:
1. Log in to backoffice
2. Create new document (use a document type without any properties!)
3. Save & Publish
4. Notice that the date property is properly updated now, whereas it wouldn't be without the change.

set isInfoTab to true if active tab is info tab

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Infrastructure/Telemetry/Providers/SystemInformationTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserDataServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SystemInformationTelemetryProviderTests.cs

Added the Current Server Role to the System Information table. Not sure if this is a desired addition but in some cases it's useful to know what the current role is.

Add Current Server Role to system information

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs

Same changes are in pull request https://github.com/umbraco/Umbraco-CMS/pull/12640, but for v9 instead of v10
https://github.com/umbraco/Umbraco-CMS/issues/12227
These changes ensures that a member's `EmailConfirmed` property changes persists when using `ConfirmEmailAsync()` located in the `IMemberManager` interface. Before these changes, the property would be set to true temporarily in memory, but then never actually saved to the database, continuing to read false for all following requests/calls. This was happening because the `emailConfirmedDate` is only added to the list of changed columns if the member's login name or email had also been changed, resulting in `emailConfirmedDate` always being null and `EmailConfirmed` not being set.
To test, do the following:
- Create a new member in …

Ensuring that MemberManager.ConfirmEmailAsync persists for v9

---

src/Umbraco.Core/Trees/ISearchableTree.cs
src/Umbraco.Core/Trees/ISearchableTreeWithCulture.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs

The backoffice search doesn't support localization, which is a shame because the underlying search implementation does.
As shown in the screencast below, backoffice searches always yield content results in the default culture, no matter which main culture is selected by the editor. The content results even list with URLs from the default culture:
This PR ensures that localization is present in the search results:
Backoffice tree search is performed by implementations of `ISearchableTree`. This interface has no culture support, so fixing the issue in the right way would mean extending the interface, which would be a breaking change.
To avoid breakage, I have chosen to fix the issue in a somewhat cumbersome way. I have introduced a specialized interface `ISearchableTreeWithCulture`, which …

Support localization for content search (backoffice)

---

src/Umbraco.Infrastructure/Scoping/IScopeProvider.cs

- Fixes breaking change in IScopeProvider by removing Context property

Remove context from IScopeProvider.cs

---

src/Umbraco.Core/FireAndForgetRunner.cs
src/Umbraco.Core/IFireAndForgetRunner.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Install/InstallHelper.cs

Fixes #12583
When intializing and completing the installer a request is sent off, in some circumstances this can take up to 100 seconds, however, this request is not required to finish for the installer to continue, so I've put it in a fire and forget task. 
Installer and Upgrader should still run.
Testing that it no longer hangs is a bit more tricky, however you can test it by changing the URL in `InstallationRepository`, to a local server that responds slowly, there is a python one here: 
```python
import json
import time
from flask import Flask, app
from flask.globals import request
app = Flask("JsonDumpServer")
@app.route("/installs/", methods=['POST'])
def dump_json():
print("Received request\n\n")
print(f"{json.dumps(request.get_json(), indent=2)}\n\n")
print("Waiting 10 …
```

V10: Use FireAndForget when logging install

---

src/Umbraco.Web.UI.Client/src/less/components/umb-avatar.less
src/Umbraco.Web.UI.Client/src/less/components/umb-logviewer.less

This PR fixes the broken dropdown in "Saved searches" of log viewer in low resolution screens (screen resolution used is 1200x700).

Fixes alignment issue for "Saved searches" dropdown in log viewer

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CreatedPackageSchemaRepository.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12672
- Adds missing null check in CreatedPackageSchemaRepository.cs
- Do note that while this will no longer throw an error, it will still not save your images in that folder, this is also the behavior in 9.5.2

Fix save package with folder-media throws an error

---

src/Umbraco.Infrastructure/PublishedContentQuery.cs

Fixes reported bug introduced in PR #11950
Fixes #12551 
To replicate create a document type, and add a property.
In this case I used `Test Document` with a property `Test Property`.
I created a page, and populated the property with the word `yes`.
This code is used in the view for ease:
```
@inject IPublishedContentQuery PublishedContentQuery;
@inject IExamineManager ExamineManager;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.TestDocument>
@using Umbraco.Cms.Core
@using Examine
@using Umbraco.Cms.Infrastructure.Examine
@{
if (!ExamineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var index) || index is not IUmbracoIndex umbIndex)
{
throw new Exception("Index not found");
}
var …
```

Issue 12551 search bug

---

src/Umbraco.Web.UI.Client/src/common/services/history.service.js

If within a section you navigate to a node and select it in the tree, but then click the section tree heading to view the section dashboard, if you then navigate away to a new section and then navigate back, it sends you back to the last node you selected, evern though the last thing you viewed in that section was the dashboard.
The PR allows dashboards to also be resolved from the navigationServices `getLastAccessedItemForSection` by allowing exact matches on the item link, as well as just sub paths of the section.
This way, when changing sections, Umbraco will actually send you back to the last thing you viewed in a section, rather than just "the last NODE you viewed".

Allow dashboards to also be the "last accessed item"

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Runtime/RuntimeModeValidationService.cs
src/Umbraco.Infrastructure/Runtime/RuntimeModeValidatorCollection.cs
src/Umbraco.Infrastructure/Runtime/RuntimeModeValidatorCollectionBuilder.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/12631 added `IRuntimeModeValidator`s that were directly added to the service collection, making opting-out of specific validators a bit awkward (even when assuming it's registered as generic type, so this doesn't even support factory or instance registrations):
```c#
using Umbraco.Cms.Infrastructure.Runtime.RuntimeModeValidators;
public class RuntimeModeValidatorComposer : IComposer
{
=> builder.Services.RemoveAll(x => x.ImplementationType == typeof(UmbracoApplicationUrlValidator));
}
```
This PR fixes that by adding a `RuntimeModeValidatorCollection` and `RuntimeModeValidatorCollectionBuilder` that is exposed on the `IUmbracoBuilder` using a new …

Add RuntimeModeValidator collection builder

---

src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html

I noticed the template picker in the info tab on a content node is slightly off center. This is because the select box has a bottom margin. I've removed it with this PR.
Before:
After:

Removes bottom margin from template select box in content node info

---

src/Umbraco.Core/PropertyEditors/BlockListConfiguration.cs

- Consistent casing for first word of description (all others start with a capital letter)
- css => CSS
- Use "override" instead of "overwrite" (if this isn't what's intended here let me know and I'll update the PR free of charge)
(Did not feel like tackling the discrepancy of descriptions ending with or without a period this time 😅)

Update description for `maxPropertyWidth`

---

src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs

There's no reason to allocate new object[] array instances for each ValueSet created for the "y" or "n" values going into the index. This just creates a single object[] for each "y" or "n" value which will save on a ton of allocations when re indexing a bunch of content.
There's an easy way to make further allocation reductions too (prob a separate PR) since there is no reason to create new object[] allocations for: CreatorId, WriterId, Level, TemplateId, Culture. Each of these can be returned from a concurrent dictionary since these values are finite and there won't be too many of each so we can just keep an internal dictionary of these object[] instances.

Don't allocate new object array instances when indexing

---

src/Umbraco.Web.UI.Client/src/less/components/umb-checkbox-list.less
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html

This ones tweaks the compositions dialog a little, in order to make it look prettier.
- removes the search field if no content types is available
- change the styling on the info text regarding missing content types
- moves the search field closer to the content type list
Before:
After:
Verify that the composition dialog looks like the screenshots above, and that the necessary information/UI is available.

Tweaks the composition dialog in the content type editor

---

src/Umbraco.Web.Common/Mvc/HtmlStringUtilities.cs

If there's an existing issue for this PR then this fixes #12400 
The additional `<p>` tag around the html string should only be added if the string is not already starting with a tag.
If the string is already starting with an html tag and additionally is getting added another `<p>` tag the `doc.DocumentNode.FirstChild.SelectNodes(".//*")` is not finding any nodes.
Add `@Html.StripHtml("<p>Some text<span>More text</span></p>", "p")` to a razor view and check if the string is stripped correctly.

Fix StripHtmlTagsMethod by adding Regex

---

src/Umbraco.Web.UI.Client/src/installer/steps/user.html

Fixes #12623
This bugfix restores the quick-install options in the installer and also allows the user to quickly see what database configuration will be added (provider and database name) with an option to change that if the server allows it.

v10: restore one-click install

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs

This fixes #12732 
I'm not entirely sure if this is the correct fix, but it prevents the `OverflowOrFormatException` and it still gets all the cultures from the ancestors. 
The other fix I tried was to add `StringSplitOptions.RemoveEmptyEntries` in `GetAncestorIds`:
```csharp
public static IEnumerable<int>? GetAncestorIds(this IContent content) =>
content.Path?.Split(Constants.CharArrays.Comma, StringSplitOptions.RemoveEmptyEntries)
```
This works, but it would just return an empty collection. The fix in this PR still gets the cultures of the ancestors.

Check if content has an identity before attempting to get it's ancestors

---

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
src/Umbraco.Web.UI.Client/src/less/forms.less
src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html

Improvements to the label styling to handle long words, and the mandatory asterisk not being on its own line.
Also reduced the width of the document type creation label / descriptions to match that of the content editor so you can more accurately see what your labels will look like
Before
After 
Note: The additional xx in the property name is due to removing some padding, so extra characters needed to be added to demonstrate the change.

Adjust label styles to allow wrapping

---

src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-tab.html

Possible fix for #12603
Would like for this to be tested in multiple browsers!
This fix prevents Firefox (and possibly others) from preventing the click event, which now bubbles up as it should. I have not looked into why the input field might be stopping events from bubbling, because it seems to me that a better solution would be to simply not show any input fields in the DOM before a tab is actually active (i.e. the `is-open` property is set to true).
Firefox 102 on MacOS:

V10: fix for editable tabs in Firefox

---

src/Umbraco.Web.UI.Client/src/init.js

Link to the issue: [#12709](https://github.com/umbraco/Umbraco-CMS/issues/12709)
After investigation, found out that `isRouteChangingNavigation` method in `navigation.service.js` also compares query strings (though shouldn't based on comment on 195 line).
It happens because `current.params` during `$routeChangeSuccess` event (in init.js) returns also query strings parameters, while it should be `current.pathParams` which returns only routing parameters.
I changed initialization of `currentRouteParams` variable so it now stores entire `current` parameter and passes to `isRouteChangingNavigation` method only `pathParams` routing parameters.
**Before**
**After**
Also switching  between tabs is smooth again.
**Testing**
Steps for reproducing are available in the issue.

Issue 12709: fixed issue with reloading of dashboard tabs.

---

src/Umbraco.Web.UI.Client/src/views/components/users/umb-user-group-preview.html
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html

- In sections right now, if no sections are selected, it displays as you have access to "All sections", while this means exactly the opposite, this PR remedies that
- Run umbraco
- Navigate to Users > Groups
- Assert that it now says "No sections" instead of "All Sections"

Fix sections wording

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/installer/steps/database.html
src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js
src/Umbraco.Web.UI.Client/src/installer/steps/user.html
src/Umbraco.Web.UI.Client/src/less/installer.less
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/analytics.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/analytics.html

This fixes #12738 
I have experimented a bit with the installer with the help of @JesmoDev to look into the UX issue of #12738. We are proposing to extend the installer into two columns to be able to show the telemetry slider in its entirety - just like it is being shown inside the backoffice.
Installer screen
Backoffice settings telemetry:
Among other changes, we also managed to:
- Make the installer screen a bit more responsive; removing the absolute positioning of the box and making sure the installer supports reacting to various types of content on small monitors
- Convert input[type=submit] to actual buttons
- Place the buttons in the same way and order as the rest of the system
- Get rid of the invisible tooltips

V10: Show more telemetry info on the installer

---

src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs
src/Umbraco.Infrastructure/Migrations/MigrationExpressionBase.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
src/Umbraco.Infrastructure/Security/BackOfficeClaimsPrincipalFactory.cs
src/Umbraco.Infrastructure/Services/CacheInstructionService.cs
src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
src/Umbraco.Infrastructure/Sync/ServerMessengerBase.cs
src/Umbraco.Infrastructure/WebAssets/Resources.Designer.cs

For some reason the Docfx generation broke when we did the clean up of warnings.
I honestly still have no idea what broke, but it seems like the fix was to re-add an unused using statement for System to SqlSyntaxProviderBase, I have 0 idea why this is nececary, but it seems to be 🤷 
I did also find a couple of other malformed XML docs which I have fixed.

Fix docfx generation

---

src/Umbraco.Web.Website/Extensions/WebsiteUmbracoBuilderExtensions.cs

When giving a workshop this week on some more of the hidden features & customisations in Umbraco, I discovered `IUmbracoTreeSearcherFields` from our docs.
https://our.umbraco.com/documentation/Extending/Backoffice-Search/#adding-custom-properties-to-backoffice-search
I always think we should be having extension methods for DX to help with discoverability by exploring the UmbracoBuilder. As you would not find out about this unless you stumble over it in our docs.
* Install the starter kit
* In backoffice search for the word `codegarden` - note no results shown
* On the blog content nodes we have a property called categories that contains tags that we want to search on
* Add example class below
* Update Startup.cs or create an IComposer to call …

Feature: UmbracoBuilder extensions  - SetTreeSearcherFields

---

src/Umbraco.Core/CryptoServiceProviderExtensions.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Web/Security/BackOfficeUserManager.cs

Migrates #12759 to V8.
Unfortunately `RandomNumberGenerator.GetInt32` does not exists for framwork, so instead I've had to use the `RNGCryptoServiceProvider` to generate random bytes and turn that into an int 32 within the specified range.
Ensure that you can still create a user, and that user gets a password with the required configuration

V8: Replace usage of Random().Next with RNGCryptoServiceProvider

---

src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs

This PR changes so the temp folder location is not exposed in API.

Only expose the filename when uploading content types

---

src/Umbraco.Core/Packaging/InstalledPackage.cs
src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html

Adds the package version from Package Manifest JSON file or C# ManifestFilter approach in the list of installed packages in the Umbraco backoffice.
* Makes it clear to end users which version of a package they have installed.
* For package developers it will make them aware of the Version property if they have not set the value already.
* Package Version is used in the anonymous Telemetry data so its helpful to know what version of a package is installed/used
* Create a package.manifest file with no 'version' property set
* Should display `Version Unknown`
* Create a package.manifest JSON file with version property set
* Verify correct information is displayed
* Use ManifestFilter with C# to register a package
* Verify correct version shown
```csharp
public class PackageManifestComposer : …
```

Display package version in Installed Packages

---

src/Umbraco.Web.BackOffice/Extensions/HtmlHelperBackOfficeExtensions.cs

If you attempt to reset your backoffice user password twice using the same password reset link, the backoffice goes blank with a JS error:
This PR restores the expected behavior:
Steps:
1. Configure SMTP settings (to enable password reset) - perhaps something like this: <img width="431" alt="image" src="https://user-images.githubusercontent.com/7405322/184804213-e87efeef-7f76-48b3-97c3-4db747cf37ed.png">
2. Go to /umbraco and request a password reset.
3. Click the link in the mail and perform a password reset.
4. Click the link in the mail again - backoffice goes blank.

Fix JS error when clicking a reset password link twice

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs

The server variables "maxFileSize", "minimumPasswordLength" and "minimumPasswordNonAlphaNum" should not be exposed to unauthenticated users.
Test that:
- The page source does not contain the server variables when accessing /umbraco as unauthenticated.
- The page source *does* contain the server variables after logging in.
- The page source *does* contain the server variables when accepting an invitation to the backoffice (the invite user flow).
- _Note: It seems the "upload avatar" step of the invite user flow is broken; it just flashes briefly into view before skipping straight to the backoffice. This behaviour is also seen on v10/dev, so it's not something introduced by this PR._ 
- The reset password flow displays the "Minimum XX character(s) to go!" message:

Only expose server vars for password policy rules and max file size for authenticated users

---

src/Umbraco.Cms.ManagementApi/Controllers/UpgradeController.cs
src/Umbraco.Cms.ManagementApi/DependencyInjection/InstallerBuilderExtensions.cs
src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
src/Umbraco.Cms.ManagementApi/Mapping/Installer/InstallerViewModelsMapDefinition.cs
src/Umbraco.Cms.ManagementApi/ViewModels/Installer/UpgradeSettingsViewModel.cs
src/Umbraco.New.Cms.Core/Factories/IUpgradeSettingsFactory.cs
src/Umbraco.New.Cms.Core/Factories/UpgradeSettingsFactory.cs
src/Umbraco.New.Cms.Core/Installer/IInstallStep.cs
src/Umbraco.New.Cms.Core/Installer/IUpgradeStep.cs
src/Umbraco.New.Cms.Core/Installer/Steps/FilePermissionsStep.cs
src/Umbraco.New.Cms.Core/Installer/Steps/RestartRuntimeStep.cs
src/Umbraco.New.Cms.Core/Installer/Steps/TelemetryIdentifierStep.cs
src/Umbraco.New.Cms.Core/Installer/UpgradeStepCollection.cs
src/Umbraco.New.Cms.Core/Installer/UpgradeStepCollectionBuilder.cs
src/Umbraco.New.Cms.Core/Models/Installer/UpgradeSettingsModel.cs
src/Umbraco.New.Cms.Core/Services/Installer/IUpgradeService.cs
src/Umbraco.New.Cms.Core/Services/Installer/InstallService.cs
src/Umbraco.New.Cms.Core/Services/Installer/UpgradeService.cs
src/Umbraco.New.Cms.Infrastructure/Installer/Steps/DatabaseInstallStep.cs
src/Umbraco.New.Cms.Infrastructure/Installer/Steps/DatabaseUpgradeStep.cs
src/Umbraco.New.Cms.Infrastructure/Installer/Steps/RegisterInstallCompleteStep.cs
tests/Umbraco.Tests.UnitTests/Umbraco.New.Cms.Core/Services/UpgradeServiceTests.cs

This is a continuation of #12790.
This implements the versions upgrades, there's not an awful lot to mention here that's not already mentioned in #12790, so read that for more information. 
The only thing really worth mentioning is that authorizing (starting) the upgrade used to be part of the `InstallApiController`, this is now its own controller `UpgradeController`
Just like #12790, you must add this to Umbraco.Cms.csproj and Umbraco.Web.BackOffice.csproj
```XML
<ProjectReference Include="..\Umbraco.Cms.ManagementApi\Umbraco.Cms.ManagementApi.csproj" />
```
Other than that add a migration to enter the upgrade runtime state, and test away. 
Auth is still not implemented, so currently the upgrade endpoint is not secured.

Implement new backoffice upgrader

---

src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
src/Umbraco.Infrastructure/Security/MemberUserStore.cs

Fixes: #12749
The problem is that the umbracoExternalLoginToken does not get updated when a new login token is issued.
This was due to a misunderstanding with the observable collection, essentially an observable collection will only raise its event if an item is added or removed, and we use this event to determine if the login tokens are dirty. 
This meant that the tokens would never be dirty, and would therefore never be updated.

V10: Fix external login token table

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js
src/Umbraco.Web.UI.Client/src/installer/steps/user.html
src/Umbraco.Web.UI.Client/src/less/components/umb-range-slider.less
src/Umbraco.Web.UI.Client/src/less/installer.less

If there's an existing issue for this PR then this fixes [12773](https://github.com/umbraco/Umbraco-CMS/issues/12773)
Adds a class to the active pip (slider on the install screen) that makes it darker to contrast with the non-active pips.
To test build and start an installation, choose a new telemetry "level" and observe that the active class moves to the selected value.

Makes active pip text darker to contrast with non-active pips

---

src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
src/Umbraco.Web.UI.Client/src/less/modals.less

After merging the above PR #12702 the styling of the headings h1 in the content and create modal were styled incorrectly:
whereas the styling of h2's on the content groups had too much white space above and below.
This occurs because of a global property for H tags that applies a default lineheight for all headings.
As a result I have:
- reset the lineheight to 0 for headings that use the class .umb-group-panel__header:
```
.umb-group-panel__header h2 {
font-size: @fontSizeMedium;
font-weight: bold;
line-height: 0;
}
```
- fixed the h1 styling for modals by applying the same styling that was previously applied when the element was a div:
```
.umb-modalcolumn-header h1,
.umb-modalcolumn-header h2 {
margin: 0;
white-space: nowrap;
font-size: @fontSizeMedium;
font-weight: 400;
}
``` …

Content modal heading fix

---

.github/config/codeql-config.yml

Add the Umbraco.Cms.StaticAssets folder to ignored paths for the CodeQL scanner so it doesn't pick up compiled assets which are generated after build.

CodeQL should not scan compiled assets

---

src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references-table.html

The tracked references table is showing icons like inside `<umb-table>` and other parts of backoffice UI.
This work for core font icons, but not custom SVG icons.
**Before**
**After**

Use `umb-icon` component in tracked references to support custom SVG icons

---

.github/workflows/codeql-analysis.yml

Upgrade the CodeQL scanner to v2 since v1 will be deprecated [later this year](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/).

Upgrade CodeQL from v1 to v2

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12743
At the moment you can't use the members list views in content types. List views are built with the assumption that they are supposed to list items based on their current context, i.e. a list view on a content type will attempt to list content (specifically children of the currently edited content).
This PR does not make it possible to use the members list view on content types, but it does aim to make the error message a little friendlier, or at least easier to decipher:

Make the error message friendlier when attempting to use unsupported sorting in listviews

---

src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/es.xml
src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
src/Umbraco.Core/EmbeddedResources/Lang/he.xml
src/Umbraco.Core/EmbeddedResources/Lang/it.xml
src/Umbraco.Core/EmbeddedResources/Lang/ja.xml
src/Umbraco.Core/EmbeddedResources/Lang/ko.xml
src/Umbraco.Core/EmbeddedResources/Lang/nb.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
src/Umbraco.Core/EmbeddedResources/Lang/zh.xml
src/Umbraco.Core/EmbeddedResources/Lang/zh_tw.xml

Fix #12770 
1. Replace "umbraco" with "Umbraco" in all Translation Files
2. Replace `<i>` and `<b>` tag with `<em>` and `<strong>` in all Translation Files

Fix #12770

---

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.MembersIdentity.cs
src/Umbraco.Web.Common/Security/MemberClaimsPrincipalFactory.cs

Fixes #12873
The issue was that if you add extra claims in `OnExternalLogin`, these claims would not be added to the identity. 
This was because there was no custom implementation of `MemberClaimsPrincipalFactory` to ensure that these claims flowed from the `MemberIdentityUser` to the new `ClaimsIdentity`

V10: Fix adding extra claims in OnExternalLogin

---

src/Umbraco.Web.UI.Client/src/common/services/user.service.js
src/Umbraco.Web.UI.Client/src/views/users/group.controller.js

When adding languages that can be edited by a user group changes in Translation do not take effect for the current user before the site is reloaded (F5) and GetCurrentUser is called.  
This PR ensures that the cache is updated when changes are made to both languages and user groups.
How to test:
* Create new languages and makes sure the permissions in the translation section reflect the changes.
* Update user group permissions and ensure the translation section reflects the changes
* Update user groups on a user and ensure the translation section reflects the changes

Bugfix: Variant permission languages needs a clear cache to work fully for current user

---

src/Umbraco.Infrastructure/Security/MemberUserStore.cs

Fixed issue with saving member groups, that was not persisted, if only the member groups  was changed.
Save a member when only adding/removing groups

Fixed issue with saving member groups, that was not persisted,

---

src/Umbraco.Web.UI.Client/src/less/components/umb-tabs.less
src/Umbraco.Web.UI.Client/src/less/navs.less
src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html

I came across a scenario where it would make sense that individual tabs in an `<umb-tabs-nav />` element can be in a disabled state.
As the tabs are essentially buttons, this PR adds `ng-disabled="tab.disabled"` to the tabs, and a bit of LESS styling so the tabs also looks disabled in the UI (text color is dimmed down and no background on hover).
I set up a quick dashboard to test my changes. The dashboard may be replicated with the following files:
**/src/Umbraco.Web.UI/App_Plugins/Hello/package.manifest**
```json
{
"$schema": "https://json.schemastore.org/package.manifest",
"javascript": [
"/App_Plugins/Hello/Dashboard.js"
],
"dashboards":  [
{
"alias": "hello",
"view":  "/App_Plugins/Hello/Dashboard.html",
"sections":  [ "content" ],
"weight": -10
}
]
}
``` …

Added support for disabling tabs in <umbTabsNav /> elements

---

tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12911
- Having your test class deriving from `UmbracoIntegrationTest` was throwing errors, due to `GlobalSetupTeardown` not running, as it would only run, if you are in the `Umbraco.Tests.Integration` assembly  
- Added new virtual SetUpTestConfiguration method, that can be overridden in your own code, if you wish to change the Test configurations
- Create your own NUnit test project
- Create a class deriving from `UmbracoIntegrationTest` with a sample test
- Run your sample test
Code snippet for NUnit class:
```
using Umbraco.Cms.Tests.Integration.Testing;
namespace NUnitTestProject;
public class Tests : UmbracoIntegrationTest
{
[SetUp]
public void Setup()
{
}
[Test]
public void Test1()
{
Assert.Pass();
}
}
```

Test configuration throwing errors

---

.github/workflows/add-issues-to-review-project.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

src/Umbraco.Core/Configuration/Models/ContentSettings.cs
src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Models/Mapping/ContentVariantMapper.cs
src/Umbraco.Core/Services/CultureImpactFactory.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/CultureImpactTests.cs

This moves the `AllowEditInvariantFromNonDefault` setting from `SecuritySettings` to `ContentSettings` based on user feedback. 
This move is done while remaining backwards compatible, meaning that you can use either setting, but `ContentSettings` will always take priority.

Hotfix: Move allow edit invariant from non default setting to content settings

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js

Add support for a block list item which only contains settings
If you create a block list item whereby the "Content" part of the item doesn't have any properties but you do add a "Settings" component, there are some issues.
- You can't access the settings section unless you first create the block list item and then press the "edit settings" button
- If the settings has a mandatory field, you can't create the item at all.
This PR checks to see if there is an active app, and if there isn't, it sets the first app to be active. This handles this specific scenario, and any scenario where you have a custom content app yet no properties in the "Content" section.
Hopefully that all makes sense!

Set the first app to active if no active apps in block list item

---

src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs
src/Umbraco.Web.Common/Media/MediaPrependBasePathFileProvider.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12903
This PR introduces `MediaPrependBasePathFileProvider`, which is a clone-and-own version of `PrependBasePathFileProvider` from [`Dazinator.Extensions.FileProviders`](https://github.com/dazinator/Dazinator.Extensions.FileProviders/). This version can handle special characters in file names.
I have placed a PR in the original project: https://github.com/dazinator/Dazinator.Extensions.FileProviders/pull/53 - if this is merged in, we could update our `Dazinator.Extensions.FileProviders` and be rid of this cloned version.
Special characters have been explicitly replaced from media file names during upload since V9. Thus testing this PR is a little bit cumbersome:
1. Remove one or more …

Add custom PrependBasePathFileProvider to handle media files with special characters

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.html

Add label key to prevent/enable cleanup button so it can be translated. 
**English:**
**Dutch:**

Add label-key to prevent cleanup button

---

src/Umbraco.Core/Extensions/StringExtensions.cs

I noticed while working on a project that IsNullOrWhiteSpace always demanded that you null check the result even if you are 100% sure that result cannot be NULL. This is because there were no helper classes on it that could help with this. If `defaultValue` is not null, then we can be sure that the return value is not null. So I've added the helpers to the function.
Take the following code:
```
public void Test()
{
string? testNullString = null;
string testString = "Hello";
string test = testNullString.IfNullOrWhiteSpace("Hello")!;
string? test2 = testNullString.IfNullOrWhiteSpace(null);
string test3 = testString.IfNullOrWhiteSpace(null)!;
}
```
This is how you would have to write it now. Even though we know test cannot be null, we still have to add the `!` to the end of the statement to …

Added nullable helper for IfNullOrWhiteSpace

---

src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.list.controller.js
src/Umbraco.Web.UI.Client/src/views/dictionary/list.html

With the new filtering to dictionary tree I noticed when there are no filtered result, the table is still visible.
I think it makes more sense to show it only when any filtered results are found.
**No dictionary items**
**Filtered dictionary items**
https://user-images.githubusercontent.com/2919859/190276262-6d6f51c6-6b22-4e9d-9fa7-b17a75daa9fd.mp4
Apparently there was also an issue in the controller is logging `vm.items.length` after the foreach setting the `style` property as `vm.items` was null here, but not before the foreach. With these changes it now works.
I tried using `ng-if` on the table which also worked, but when filtering didn't return any results and clearing the search field, the dictionary items apparently didn't show up again. It works with `ng-show` though.

Only show table when any filtered result

---

src/Umbraco.Core/Services/MemberService.cs

Creating a member with identity needs name and email to be passed in. 
The PR fixes this by passing in the parameters rather than `string.Empty`

pass in parameters needed to member service

---

src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html

This PR fixes [Accessibility Issue 16](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/16)
This fix required moving the icons for the search and help buttons in the main navigation into a span element. 
Steps to replicate:
Navigate to top navigation using a keyboard
Focus on the Search or Help icon  (should have the same focus state as the profile icon now)

fix: focus state for search and help icons

---

src/Umbraco.Core/Services/IMemberService.cs
src/Umbraco.Core/Services/MemberService.cs

- This is an extension of this PR: https://github.com/umbraco/Umbraco-CMS/pull/13020
- As @bjarnef pointed out, we missed a method, where a name was still passed as `string.Empty` and thus would throw exceptions. This has now been change to pass the username instead 💪
- There where several methods missing from the `IMemberService` interface, these has now been added with default implementations to avoid breaking changes
- I tested this by calling the method from a NotificationHandler, here is the code snippet:
```
public class NotificationTest : INotificationHandler<ContentTypeSavedNotification>
{
private readonly …
```

Missing methods from IMemberService

---

src/Umbraco.Core/Extensions/StringExtensions.cs
src/Umbraco.Core/IO/IOHelper.cs
src/Umbraco.Core/IO/IOHelperLinux.cs
src/Umbraco.Core/IO/IOHelperOSX.cs
src/Umbraco.Core/IO/IOHelperWindows.cs
src/Umbraco.Web.BackOffice/Controllers/TinyMceController.cs
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs

While upgrading TinyMCE for v11, we discovered that drag&drop of images did not work as intended in TinyMCE, where the images would be pasted as base64 inline data, and after fixing that, they did not land in the correct tmp folder on the server (needed to use ContentRoot instead of WebRoot in TinymceController). Also, absolute paths on MacOS at least was erroneously being handled as relative paths which further resulted in the server not being able to find the tmp images. The last key to the fix was to parse the returned JSON response from the `UploadImage` endpoint since it uses the special AngularJS prefix so we needed to split by newlines and take the second line of the response since we are working with a raw XHR object.

V10: Fix to allow dragged images in the rich text editor to be correctly uploaded

---

src/Umbraco.Web.Common/Extensions/TypeExtensions.cs
src/Umbraco.Web.Common/Mvc/UmbracoMvcConfigureOptions.cs
src/Umbraco.Web.Common/Validators/BypassRenderingModelValidationMetadataProvider.cs
src/Umbraco.Web.Common/Validators/BypassRenderingModelValidatorProvider.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12579
The slow rendering described in the linked issue is tied to how ASP.NET Core performs validation; specifically validation of object graphs. The more content items exist in near vicinity (parent, children, siblings) of the item being rendered, the larger object graph is traversed.
The only reasonable fix is to disable validation of rendering models, namely models built upon `ContentModel` or `IPublishedContent` (ModelsBuilder models).
As this is a behavioral breaking change, we cannot target V10, so the target of this PR is V11.
The files needed for testing is attached in [this ZIP file](https://github.com/umbraco/Umbraco-CMS/files/9566646/12579.zip).
1. Use the attached DB to get …

Bypass model validation for rendering models

---

src/JsonSchema/UmbracoJsonSchemaGenerator.cs
src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Infrastructure/Telemetry/Providers/SystemInformationTelemetryProvider.cs
src/Umbraco.Web.UI/appsettings.template.json
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/GlobalSettingsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserDataServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SystemInformationTelemetryProviderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Controllers/RenderNoContentControllerTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12593
This PR removes the option to configure `UmbracoPath`. 
It is a behavioural breaking change, but as the feature does not work as-is and will not be fixed, we have accepted this change.
The code changes however have been made non-breakable with a few TODOs for cleaning up obsoletes in V12.

UmbracoPath should no longer be configurable

---

src/Umbraco.Web.UI.Client/src/less/components/umb-property-editor.less

This PR fixes problems with umb-overlay not rendering after a property-editor was changed to contain layout.
fixes #12989

Only contain style instead of full layout

---

src/JsonSchema/UmbracoJsonSchemaGenerator.cs

The online appsettings schema https://json.schemastore.org/appsettings.json no longer has any notion of the removed `UmbracoPath` config, so we no longer need the workaround that removes it when generating our local schema.
The workaround was introduced here: https://github.com/umbraco/Umbraco-CMS/pull/13032
The completed PR for the online schema store is here: https://github.com/SchemaStore/schemastore/pull/2492

Remove temporary workaround from schema generator

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js

Fixes #13029 
Fixes [AB#22651](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22651)
Earlier in 10.2 we tried to make the noUiSlider (umb-range-slider) more useful by marking the active pip (if you are using pips) with an extra class so it could be styled. This implementation did not take into account that not all pips might exist and had thus a need for an extra if-check. Upon further inspection, we were able to improve the code a bit to avoid having an intermediary variable as well.
The issue was particularly noticeable with pre-configuration of the slider data type.
With this fix it will stop throwing an immediate javascript error when configuring the slider, and it will still work even with decimals with this configuration:
```js
"pips": {
mode: …
```

Fix regression of active pips handling with noUiSlider

---

src/Umbraco.Cms.ManagementApi/Controllers/Profiling/ProfilingControllerBase.cs
src/Umbraco.Cms.ManagementApi/Controllers/Profiling/StatusProfilingController.cs
src/Umbraco.Cms.ManagementApi/OpenApi.json
src/Umbraco.Cms.ManagementApi/ViewModels/Profiling/ProfilingStatusViewModel.cs

This PR adds the endpoint required for the "web profiling" dashboard:
Call `https://localhost:44331/umbraco/api/v1.0/profiling/status` - when running in debug mode, the response should be:
```json
{
"enabled": true
}
```
...while not running in debug mode should yield:
```json
{
"enabled": false
}
```

New endpoint for web profiling dashboard

---

src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
src/Umbraco.Cms.ManagementApi/OpenApi.json

The paths and tags in the Swagger UI are currently unsorted. It's fine now, but as the API grows it'll be harder to find things:
This PR adds explicit sorting to Swagger UI and also explicit sorting to the tags of the OpenApi JSON output (unfortunately it is no longer possible so sort the paths in the OpenApi JSON output):

Make sure swagger tags and operations are sorted alphabetically

---

src/Umbraco.Web.UI.Client/lib/bootstrap/less/tests/css-tests.html
src/Umbraco.Web.UI.Client/lib/bootstrap/less/tests/forms.html
src/Umbraco.Web.UI.Client/src/installer/steps/database.html
src/Umbraco.Web.UI.Client/src/installer/steps/user.html
src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html

Disables spellchecking on password inputs.
1. Run `npm build`
2. Check that spellchecking is disabled when:
1. Creating your user in the install screen
2. Loggin in to the CMS

Disable spellcheck on password inputs

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js

Fixes #12994
Find details and testing instructions in issue description

Fixes: Grid property editors not loading after Umbraco 10.2.0 update

---

src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs

Umbraco has the `MemberPasswordHasher` which then calls `LegacyPasswordSecurity`.
This successfully validates the correct legacy password hash and returns true.
As it's a legacy password the `MemberPasswordHasher` returns `PasswordVerificationResult.SuccessRehashNeeded` which seems helpful because it allows you to perform different logic.
But `UmbracoUserManager` checks this method returns `PasswordVerificationResult.Success` to determine if the password is valid. Therefore it's always false for every legacy password.
The `MemberManager` should check both `Success` or `SuccessRehashNeeded` states when validating a password.
If this isn't suitable perhaps there should be a config that allows this check (off by default).

Fixes #12972 for validating legacy member passwords

---

src/Umbraco.Web.Common/Umbraco.Web.Common.csproj

Smidge v4.1.1 updates Nuglify from v1.13.12 to v1.20.2 with tons of bug fixes for many issues some are detailed in this forum thread https://our.umbraco.com/forum/using-umbraco-and-getting-started/108469-backofficeadmin-css-smidgenuglify-error-breaking-package-styling

Bump Smidge up to v4.1.1

---

src/Umbraco.Core/PropertyEditors/ConfigurationFieldAttribute.cs

Just a minor a incorrect comment I noticed when working on https://github.com/umbraco/Umbraco-CMS/pull/13075 as the `View` property is readonly.

Fix comment of view property in `ConfigurationFieldAttribute`

---

src/Umbraco.Core/Extensions/StringExtensions.cs
tests/Umbraco.Tests.Benchmarks/DetectJsonBenchmarks.cs

Using chars instead of strings in the DetectJson improves the performance of the function, which will probably add up due to all the value converters using it.
```
|           Method |      Mean |      Error |     StdDev | Ratio | RatioSD | Allocated |
|----------------- |----------:|-----------:|-----------:|------:|--------:|----------:|
| StringDetectJson | 96.580 ns | 285.565 ns | 15.6528 ns |  1.00 |    0.00 |         - |
|   CharDetectJson |  8.846 ns |   1.220 ns |  0.0669 ns |  0.09 |    0.02 |         - |
```
How to test: Make sure that the value converters still work, but I don't see a reason why this would break anything.

Use char instead of string for DetectJson

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html

Addresses issue #13083 
When right-click pasting inside of a TextArea there is no `KeyUp` event fired, this PR introduces a change away from listing for keyup and listens for [ng-change](https://www.w3schools.com/angular/ng_ng-change.asp).

Refactor event handler away from keyup to ng-change

---

src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs

I noticed from time to time when opening the action delete, the icon was sometimes missing. It seems it required `icon-icon-delete` because `useLegacyIcon` wasn't set.
In https://github.com/umbraco/Umbraco-CMS/pull/12403 this was changes so full icon name should be specified and core icons updated to use full icon name, but to be backward compatible it added the `useLecacyIcon` which is `true` by default, which mean it always requested an icon with `icon-` prefix + specified icon name.
However this was fixed here https://github.com/umbraco/Umbraco-CMS/pull/12403/files#diff-5233dfc5cb8dcc04b74ba67fc13b7c8833c80b63a76ed965e4d0d89cc7f04dcaR134 but somehow is reverted in core. I guess it has been a merge conflict somewhere, which discarded this change.
**Before** …

Don't use legacy icon for action delete

---

src/Umbraco.Core/Extensions/StringExtensions.cs

The following code:
```
public void Test()
{
string? nullableString = null;
if (!nullableString.IsNullOrWhiteSpace())
{
string test = nullableString;
}
}
```
Throws an error because it cannot convert `nullableString` to a `string` because it could be null. But the system should know that the string isn't null due to the `IsNullOrWhiteSpace`.
This PR fixes that. When IsNullOrWhiteSpace returns false, it will tell the system that the string cannot be null.

Added nullability attribute to IsNullOrWhitespace

---

src/Umbraco.Core/Constants-DeploySelector.cs
src/Umbraco.Core/UdiRange.cs

This adds a new selector we have added to Deploy, and means for V11 we can avoid a reflection hack needed to be able to use this when constructing a `UdiRange` (as there's an exception thrown in the constructor if the provided selector isn't known by the CMS.

Adds additional deploy selector.

---

src/Umbraco.Web.Common/Security/MemberSignInManager.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12914
- Removed deleting of member when failed autolinking
- Disapprove member on failed autolinking
- Setup external login providers for members from: https://our.umbraco.com/Documentation/Reference/Security/External-login-providers/
Autolinking via https://our.umbraco.com/documentation/Reference/Security/Auto-linking/
- Way to reproduce in comments on the original issue 🙌

V10: Dont delete member on failed autolink

---

src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/60
Adding text-decoration styling to make it clear to visually distinguish links from texts.
**Before**
**After**

Fixes umbraco/Umbraco-CMS.Accessibility.Issues#60

---

.gitignore
build/azure-pipelines.yml
src/Umbraco.Cms/Umbraco.Cms.csproj
tests/Umbraco.Tests.AcceptanceTest/misc/umbraco-linux.docker

The E2E tests are currently not always starting up correctly, which causes the `Wait for app` step to finally timeout. Because the application is started in the background (either in Docker on Linux or using PowerShell on Windows), the application logs aren't currently available in the build log.
This should ensure we can inspect the logs and see why the application couldn't correctly start...
After a completed (or failed) build pipeline, the logs should be available as an artifact. We might need to re-run the build multiple times to verify whether this also works when it fails (and fix the root issue).

Publish E2E application logs

---

src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.settings.html
src/Umbraco.Web.UI.Client/src/views/macros/views/macro.settings.controller.js
src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13099
- Added validation message to macro-settings view
- This is done by changing the `<umb-control-group>` to a `<umb-property>`
- Added `help-inline` class to datatype view, to make validation text red

V10: 13099 fix validation error

---

src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/IDataTypeService.cs
src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs

Based on the feedback of @KevinJump in https://github.com/umbraco/Umbraco-CMS/pull/11867#issuecomment-1259178819
By using the actual Save function of the service, it'll go through all the needed notifications.

Use the actual save function for saving the copy

---

src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs
src/Umbraco.Web.Common/Extensions/BlockListTemplateExtensions.cs

As the title says: This PR aligns the rendering extensions for block grid and block list by:
1. Adding synchronous options for block grid
2. Adding asynchronous options for block list
1. Create content with block grid and block list.
2. Render both synchronous and asynchronous using the appropriate extension methods (see example templates below).
3. Verify that the synchronous and asynchronous rendering outputs are identical.
Docs for block grid default rendering: https://our.umbraco.com/documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-Grid-Editor/#1-default-rendering
Docs for block list default rendering: https://our.umbraco.com/documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Block-Editor/Block-List-Editor …

Add sync rendering extensions for block grid and async ones for block list

---

src/Umbraco.Web.Common/AspNetCore/ApplicationUrlRequestBeginNotificationHandler.cs
src/Umbraco.Web.Common/AspNetCore/AspNetCoreRequestAccessor.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs

This PR fixes #13098.
As described in the issue there was a memory leak in `AspNetCoreRequestAccessor`
The reason for this memory leak was that it was set up as a notification handler, which is transient. This meant that every time a request was sent, a new`AspNetCoreRequestAccessor` was initialized, and an OnChange even registered on the `IOptionsMonitor`, this meant that the `AspNetCoreRequestAccessor` alongside its delegate in the `IOptionsMonitor` would never be GC'ed. 
To add insult to injury, since the notification handler is transient, the `_isInit` and `_hasAppUrl` would re-default to false each time, meaning that `GetApplicationUrl` is called unnecessarily on *every* request.
Unfortunately, this is not that simple to fix in a nice way without breaking changes. What I've done is …

V10: Fix request accessor memory leak

---

src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutItem.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueConverter.cs

This fixes #13154
The issue was that the `ForceLeft` and `ForceRight` properties would always default to false when you're trying to render your blocks on the frontend. 
This was a fairly simple oversight, the issue was that `ForceLeft` and `ForceRight` wasn't added to the `BlockGridLayoutItem`, and were therefore not subsequently mapped to the `BlockGridItem` later, because they didn't exist. 
Create a BlockGridEditor with a couple of blocks, some that are force left/right, and ensure that it's reflected on the frontend, I used a view like so 
```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using Umbraco.Cms.Core.Models.Blocks
@{
Layout = null;
} …
```

V10: Fix missing ForceLeft and ForceRight in BlockGrid

---

src/Umbraco.Core/Models/PropertyTagsExtensions.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTagsTests.cs

Fixes #13132
The problem is related to how tags, configured with CSV storage type, are saved in the database. As mentioned in the issue, the UI behaves correctly, ex: splitting up tags that include comma-separated values when the storage type is CSV, while allowing those to be a single tag when the choice is JSON. _Check [docs](https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Tags/#storage-type) for more info on the storage type differences._
The bug is present since Umbraco 10.0 when we introduced NRT. When the storage type format is CSV, we are splitting the tags based on a delimiter that we have to set in case it is the default "`\0`" value for the char type. But with the old check in place, `configuration?.Delimiter == default` …

Fix tags with CSV storage type

---

src/Umbraco.Infrastructure/Examine/MemberValueSetValidator.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13036
- Made constructor parameters nullable, as these directly pass them to `base()`, which is the `ValueSetValidator` constructor, which has all the parameters as nullable 😅 Therefore i think it makes good sense, to also have the `MemberValueSetValidator` parameters as nullable, as also described in the issue 👍

V11: Make MemberValueSetValidator ctor parameters nullable

---

src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs

Unlike block list, the default rendering for block grid utilizes built-in views within the `Umbraco.Cms.StaticAssets` class library to construct the rendered grid output. 
Some have reported this as being strange and bad for DX and discoverability. 
Unfortunately, due to limitations on package formats we cannot move the files to a more easily discovered location, so this PR adds additional notes to the appropriate block grid rendering extensions about where to find these built-in views, in case one wants to change them (or simply want to figure out what's going on).
The docs should show up if you hover over the rendering extension in a template:
```cshtml
@{
Layout = null; …
```

Add documentation for default block grid partial views in the rendering extension methods

---

src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/macro.spec.ts

- Adds ``data-element` to the umb-properties so we can find them in our acceptance tests.
- Changes the acceptance-test locator to look up the new data-element

v10: Add data-element to umb property so we can find it

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts

- Bumbed version of `playwright-testhelpers` as it used a removed endpoint
- Fixed up selector in macro, as the selector no longer existed

V11: fix failing acceptance tests

---

src/Umbraco.Cms.ManagementApi/OpenApi.json
src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj

The v11/dev build seems to be failing for new PRs. This PR aims to fix it.
- A little glitch in the parameter list for the JSON schema generator causes the OpenQL pipeline step to fail. 
- The integration tests need a re-generated version of the OpenAPI schema to succeed. Weirdly enough these tests run fine locally.

Fix pipeline errors for V11

---

src/Umbraco.Core/Constants-Configuration.cs
src/Umbraco.Core/Extensions/ConfigurationExtensions.cs
src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs

#13107 Accidentally broke SourceCode memory models. 
The reason for this is that we would replace the ViewCompiler regardless of ModelsMode, this meant that it would break when using SourceCodeAuto because the `CollectibleRuntimeViewCompiler` directly creates a reference to the `InMemoryAuto` models assembly, but since we're not in InMemoryAuto mode, this does not work. 
Now if we really wanted to we could make a workaround and only add a reference if there is an `InMemoryAuto` models assembly, however I don't think this is is the best solution, since we really only want to replace these services when in `InMemoryAuto`, so I think it's nice that it fails if this is not the case 😄 
So the fix was to add a check and only register the services when we're in `InMemoryAuto`. 
Ensure that …

V11: Fix SourceCode modelsbuilder

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umb-property-info-button.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridentry.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html

Merging https://github.com/umbraco/Umbraco-CMS/pull/12851 into 10.3
Including one extra fix for keyboard navigation.

Merge BjarneF fix into 10.3

---

src/Umbraco.Core/Services/LocalizedTextServiceFileSources.cs
src/Umbraco.Core/Services/LocalizedTextServiceSupplementaryFileSource.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.LocalizedText.cs

- Gets .xml files for new languages (languages that [Umbraco doesn't support](https://our.umbraco.com/documentation/extending/language-files/#supported-languages)) from other sources than `umbraco/config/lang/`, like:
- _/App_Plugins/mypackage/Lang/_ - physical files or from RCLs
- _config/lang/_ - physical files
- Pick a language from [the list](https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes);
- For the example, I chose Bulgarian (`bg`);
- Create the following `bg.xml` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<language alias="bg" intName="Bulgarian" localName="български" lcid="" culture="bg-BG">
<area alias="login">
<key alias="greeting0">(BG) Happy super Sunday</key>
<key alias="greeting1">(BG) Happy marvelous …
```

Collect new .xml language files from different sources

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/dataTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/ModelsBuilder/modelsbuilder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/packages.spec.ts

Seems like some of the tests where still flaky on the pipelines, turns out its a timing issue, because the success notifications still display, if we're going to fast.
The changes in this PR makes it so we will just close the success notification after we've asserted it is there.

V11: fix more unstable acceptance tests

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13226
Updates the editors when the content model is changed.
- Please verify that you can replicate the issue before checking out this PR.
- Verify that the issue is gone with this change.
- Test other cases where the content model might change, to verify that the update isn't breaking other stuff.

13226 resync content model on change

---

src/Umbraco.Core/Constants-PropertyEditors.cs
src/Umbraco.Core/Models/Blocks/BlockGridArea.cs
src/Umbraco.Core/Models/Blocks/BlockGridItem.cs
src/Umbraco.Core/Models/Blocks/BlockGridModel.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridEditorDataConverter.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutAreaItem.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutItem.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs

This PR disables the BlockGridEditor.
It does so by removing the `DataEditor` property and adding `HideFromTypeFinder` this ensure that it doesn't get picked up by the type finder and wont be displayed in the backoffice. 
For some additional QoL I've also added `[EditorBrowsable(EditorBrowsableState.Never)]` to some of the BlockGrid classes, so they won't show up in IntelliSense, most notably `BlockGridTemplateExtensions` so you only see the render methods for the BlockListEditor.
To test I did the following: 
* Pack the solution with `dotnet pack -c Release -o build_output` (EditorBrowsable only works for DLL references) 
* Add the build nuget files to a localfeed
* Create a new project using the template
* Run the site and ensure that the BlockGridEditor is no longer present 
* Create a …

Disable BlockGridEditor

---

src/Umbraco.Core/Constants-PropertyEditors.cs
src/Umbraco.Core/Models/Blocks/BlockGridArea.cs
src/Umbraco.Core/Models/Blocks/BlockGridItem.cs
src/Umbraco.Core/Models/Blocks/BlockGridModel.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridEditorDataConverter.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutAreaItem.cs
src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutItem.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs

This Reverts #13229 re-enabling the block grid editor

V10.4: Re-enable block grid editor

---

tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj

This marks the management api project reference in Umbraco.Tests.Integration as PrivateAssets=All 
Ensuring we don't have dependency to a project that's not release.

Mark management API reference as PrivateAssets in Integration Tests project

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html

Left aligned message about no index populator
**Before**
**After**
You can see this in action if you create a index without a populator

Left aligned message - "This index cannot be rebuilt because it has no assigned IIndexPopulator"

---

src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less

Should solve [#12127](https://github.com/umbraco/Umbraco-CMS/issues/12127)
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12127
As described in the issue, this fix helps to ensure that actions for a block list editor remain visible, even if a custom view uses z-index (as long as the custom view doesn't go above z-index: 500, I guess).

Fixes #12127 - sets z-index on block list actions element

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/codeeditor.html

I've been meaning to fix this for a while, so I've created this PR after seeing that the issue still exists in the new 10.3.
For most of the overlays in the backoffice, the overlay can be closed by pressing the ESC key, as it's typically the shortcut for the overlay's close button.
However when editing the raw HTML of an RTE property editor, the close button doesn't have a shortcut. This PR therefore adds the shortcut so the overlay can be closed by pressing the ESC key.
Reproducing the issue would be something like creating new content type with a property holding an RTE, creating a new content item of said content type, and then clicking the *View Source Code* in the RTE.

Added  shortcut="esc" to RTE HTML editor close button

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js

This is kind of a follow-up to PR #12721 which was solving issue #12617 
I noticed that there was still an issue if you just entered and got out of the date field itself without changing anything, when leaving the page you would also get an "unsaved changes" alert.
So this PR fixes this.
1. Create Date Picker property on a media type
2. Create a new node of that type
3. Touch or change the date picker
4. Save the media node
5. Leave and reopen the node
6. Touch the date picker but do not change the value
7. Leve the page
8. You get an "unsaved changes" alert
When just touching/setting focus in the date picker and then leaving the node, no "You have unsaved changes" pop up should occur.

"You have unsaved changes" on media with date picker even though I don't,  part 2

---

src/Umbraco.Web.UI.Client/src/common/services/usershelper.service.js

If there's an existing issue for this PR then this fixes [Invited tag - Fail minimum contrast #70](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/70)
Previous badge color for 'invited' on user cards in the user section failed to meet color-contrast
This was because the badge colour used the 'warning' color attribute.
Therefore have changed the settings in the user service for the 'invited' property to use the 'primary' color attribute
This now meets color contrast standards (and I think looks better :D )
In order to test:
Ensure that build of Umbraco has SMTP configured
Browse to Users section
On the dashboard find the dropdown to invite new user
Create and send invite to new user
User now appears as a card with 'invited' badge
Invited badge background color and …

Fixed user invited badge color

---

src/Umbraco.Core/Routing/PublishedRouter.cs

Fixes #12781 
The code that tries to find the template is now only executed when `request.PublishedContent.TemplateId` is not `null` and not `default` (= `0`).

Only attempt to find template when TemplateId is not null or default

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/recycleBin.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/routing.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/textBoxVariation.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/HelpPanel/systemInformation.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Languages/languages.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Login/login.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaFiles.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaSection.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/memberGroups.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/members.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/packages.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/dataType.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/documentTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/languages.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/mediaTypes.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/memberTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/partialViewMacroFiles.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/partialViews.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/relationTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/scripts.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/stylesheets.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/templates.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tabs/tabs.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tour/tours.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/userGroups.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/users.spec.ts

We added these because of the SQLite locking issue we were having, which would cause these to fail on the pipelines.
This has now been fixed and therefore the timeouts can be removed 👍

Remove timeouts from acceptance tests

---

src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDistributedLockingMechanism.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13260
- As @bergmania mentions in the original issue, it was indeed the Swedish minus playing tricks on us again!
Here is the error message we got:
```
(0x80004005): SQLite Error 1: 'no such column: −333'.
```
We can clearly see the minus `−` is not the same as `-`
- Run umbraco
- Switch your users language to swedish
- Try to create a document type
- This should no longer throw errors and actually save 👍

V10: parse lock id as invariant

---

src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/IDataTypeService.cs

The fix in #13066 was supposed to be merged before 10.3.0 came out, unfortunately we didn't get that done. #13066 introduces changes to public methods and interfaces, which is a breaking change. This PR should fix those so the new method will be available but the old one is still there as well.

Unbreak breaking change in #13066

---

.github/BUILD.md

Removes references to Build.ps1 and instead describes how to use dotnet pack

Remove references to build.ps1 in build docs

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
src/Umbraco.Web.UI.Client/src/preview/preview.controller.js

In order to support accessibility `iframe` elements should have titles on them (Ref https://www.w3.org/WAI/WCAG21/Techniques/html/H64). 
I have added the titles for the iframes in the preview controller and the YSOD area of the installer.

A11Y added missing iframe title to installer and preview controller.

---

.editorconfig

Prerequisites
I have added steps to test this contribution in the description below
Description
When working with the repo its hard to see any warning due to the amount of the xml docs warnings.
Resubmit of  https://github.com/umbraco/Umbraco-CMS/pull/13257 hopefully without the commit issues :)

Remove xml docs warnings using .editorconfig

---

tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTagsTests.cs

Test had a TODO instead of Asserts, so I added them.
Automated tests should handle testing for us all :)

Added asserts to TagsCanBecomeInvariantByPropertyTypeAndBackToVariant

---

src/Umbraco.Core/PropertyEditors/ListViewConfiguration.cs

While working with list views I found it a bit odd that I would need to choose the "Order By" field, before I had selected the columns I wish to display since if I add more columns it will give me more options to choose from in the "Order By" dropdown. Therefore I propose to place the "Order By" after the "Columns Displayed" setting.
**Before**
**After**

Listview property editor: Change Prevalue placement for "Order By"

---

src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDistributedLockingMechanism.cs
tests/Umbraco.Tests.AcceptanceTest/package-lock.json

The merge from v10 to v11 seems to have caused an error in the `SqliteDistributedLockingMechanism`
After the decoupling of dependencies, the use of `SqlException` had been changed to `SqliteException`
The merge seems to have undone this. This PR reverts it back to the pre-merge state (still including the invariant culture fix though)
It builds and tests pass

V11: Use SqLiteException instead of SqlException in SqliteDistributedLockingMechanism & fix E2E tests

---

src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html

If there's an existing issue for this PR then this fixes [Package details - Skipped heading level(s) #59](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/59)
Fixed skipped heading on the package details page
Navigate to 'Packages' section
Open a package (e.g. Umbraco forms)
Heading levels now read correctly
The 'visual heading' was not configured as a heading:
`<div class="umb-packages-view-title ng-binding ng-scope">Umbraco Forms</div>`
Now is changed to:
`<h2 class="umb-packages-view-title ng-binding ng-scope">Umbraco Forms</h2>`
This heading is unique to the package description page so there does not appear to be any adverse effect elsewhere.  As the classes for the div have been used on the heading - there has not been any impacts on styling either on desktop or …

Added h2 for the package details heading

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/HealthChecks/Checks/Security/HstsCheck.cs

This fixes #13165
The "Strict-Transport-Security" (HSTS) header should not be set on localhost.
This PR inverts the HSTS health check results when running on localhost.
To test: run the security checks on localhost. The HSTS HealthCheck should pass if HSTS is **not** enabled.

Swap HSTS healthcheck status on localhost

---

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs

This is a second go and supersedes [this PR](https://github.com/umbraco/Umbraco-CMS/pull/13286), resolving [this issue](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/605).
To Test:
- Install with default configuration should create the `en-US` language as the default.
- Install with the following configuration should create the English (UK) and Italian languages, with the former as the default
```
"InstallDefaultData": {
"Languages": {
"InstallData": "Values",
"Values": [
"en",
"it"
]
}
},
```

Allow for configuration of additional languages to install and ensure one is set as default.

---

src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
tests/Umbraco.Tests.Common/TestHelpers/TestDatabase.cs

Updated Smidge, Npoco and MailKit
NPoco 5.5 includes some undocumented breaking changes. I found this:
- IDatabase now have `int CommandTimeout { get; set; }`

Updated Smidge, Npoco and MailKit

---

src/Umbraco.Web.BackOffice/Controllers/BlockGridSampleHelper.cs

There was a casing issue in the path in `BlockGridSampleHelper.CreateSamplePartialViews` that caused the example to not work.

V11: Fix Block Grid example on Linux

---

src/Umbraco.Core/Extensions/ContentExtensions.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12732
- GetAncestorIds was throwing exceptions whenever the path to the content was empty.
- Add NullOrWhiteSpaceCheck to GetAncestorIds to avoid throwing exceptions
- Right now we are returning null when there are no ancestors, but we should probably return an empty collection instead.
- We can't change that for v10 as it would be breaking, but we probably should do a PR for v12 👍 
- Add the notification handler to your project, here is the snippet: 
```
public class StrictNodeNameComposer : IComposer
{
public StrictNodeNameComposer()
{
}
{ …
```

GetAncestorIds throwing exception

---

src/Umbraco.Core/EmbeddedResources/BlockGrid/area.cshtml
src/Umbraco.Core/EmbeddedResources/BlockGrid/areas.cshtml
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_4_0/AddBlockGridPartialViews.cs
src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs
src/Umbraco.Web.UI/Views/Partials/blockgrid/area.cshtml
src/Umbraco.Web.UI/Views/Partials/blockgrid/areas.cshtml

When rendering the block grid, some use cases requires rendering specific item areas individually, instead of looping through all areas within the same area container. That is currently not supported by the built-in rendering mechanisms.
This PR introduces that level of granularity in the rendering - namely moving the rendering of a single item area to its own view. The single area rendering is powered by different variations of extension methods (both synchronous and asynchronous):
- One for passing the specific area (this one is used by the default `areas.cshtml`)
- One for passing the container item and the alias of the desired area.
A new migration has been added to push the new `area.cshtml` view to disk at upgrade time.
1. Delete `area.cshtml` from `/Views/Partials/blockgrid` if it …

Move block grid single area rendering to its own dedicated view

---

src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs

@Zeegaan We have a use case where we need to set a value in the AdditionalData dictionary in a NotificationHandler, but as it can be null, it requires reflection to make sure that is not the case. As such, it would be nice if the following change could be implemented to ensure it is never null.

Remove nullability from AdditionalData on ContentItemDisplay

---

.devcontainer/devcontainer.json

This updates the .devcontainer json file to add in the .NET7 SDK as a feature, as Microsoft has not yet published the .NET7 Container image for CodeSpaces just yet.
Suggestion from GitHub/Microsoft/CodeSpaces team @samruddhikhandale
https://github.com/devcontainers/templates/issues/38#issuecomment-1310803259
https://containers.dev/features
https://github.com/devcontainers/features/tree/main/src/dotnet
After using the feature JSON in the devcontainer.json you can see that .NET7 SDK is available along with the .NET6 from the main image in the terminal.
Working screenshot of Umbraco CMS 11 running on .NET7 with the extra part of the image for a development local SMTP server to see test emails sent out.

Adds in .NET 7 SDK to GitHub CodeSpaces

---

src/Umbraco.Web.Common/ModelsBuilder/InMemoryAuto/CollectibleRuntimeViewCompiler.cs

This fixes an issue if you replace a default view (like the no-nodes) page with a non-precompiled one. 
This would cause the RuntimeViewCompiler to explode because it couldn't find the InMemory model assembly to add as a reference. 
This PR switches it over so the reference is ignored if the InMemory models assembly doesn't exist.

V11: InMemory - only add models assembly as runtime view reference if it exists

---

.devcontainer/devcontainer.json

Adds support for the GitHub CLI command `gh codespaces ssh` to work and allow you to SSH into the running machine/codespace
https://cli.github.com
https://cli.github.com/manual/gh_codespace_ssh

Adds the SSH feature to allow the GitHub CLI SSH command to work

---

.devcontainer/devcontainer.json

For GitHub CodeSpaces the first time you perform `dotnet build umbraco.sln` at the root of the folder in the terminal in VSCode it can take a long time to perform (around ~10mins) to do Nuget downloads and restore, along with NPM installs of client side stuff needed for Umbraco backoffice to run.
With this set in the `onCreateCommand` in the devcontainer.json it will make the first time run of the CodeSpace image to be a lot faster for anyone wanting to contribute to Umbraco CMS project.
*It will increase the build time in our GitHub Action `Codespaces Prebuilds` and could eat up more minutes quicker.*

Adds dotnet build command for onCreateCommand to use in Prebuilds of CodeSpaces

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html

This mode is now being removed and merged with the 'inline' mode. This allows us to simplify the rich text editor and on top of that, make a nicer experience for the editors in inline mode using the "quickbars" plugin.
**Prevalues config**
There are now only two modes, and any older databases set to 'distraction-free' is automatically mapped to 'inline':
**The editor**
Now using the "quickbars" plugin, it gives the editor a nice hovering toolbar to edit their content:

v11: Rich text editor - remove distraction-free mode and optimise inline mode

---

.devcontainer/devcontainer.json

For GitHub CodeSpaces the first time you perform dotnet build umbraco.sln at the root of the folder in the terminal in VSCode it can take a long time to perform (around ~10mins) to do Nuget downloads and restore, along with NPM installs of client side stuff needed for Umbraco backoffice to run.
This should be a different approach of using `updateContentCommand` as opposed to `onCreateCommand` and replaces PR #13395
https://docs.github.com/en/codespaces/prebuilding-your-codespaces/configuring-prebuilds#configuring-time-consuming-tasks-to-be-included-in-the-prebuild

Trying Codespace prebuilds to use updateContentCommand that the docs refer to

---

.devcontainer/devcontainer.json

This PR adds config for Port Forwarding to give the ports meaningful labels and to ensure the correct protocol is used.
When changing to the prebuilds it does not auto show the SMTP4Dev port anymore so this adds it so it can be discovered easier.

Enable CodeSpaces PortForwarding Config

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

The command for adding the developer SSL certificate command from dotnet cli was not working as part of the docker image so moved into `updateContentCommand`

Codespaces: dotnet devcert in the docker was not working so moved to updateContentCommand

---

.vscode/launch.json

Codespaces: Removes the explicit build before attaching debugger launch task now that we have prebuilt CodeSpaces now.

Codespaces: Removes the explicit build before attaching debugger launch task

---

src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
src/Umbraco.Cms.ManagementApi/OpenApi/OperationIdRegexes.cs

Moves the source code generated regexes into its own file so we don't have to make the composer partial.

V11: Refactor operation ID regexes

---

.devcontainer/devcontainer.json
.github/codespaces-readme.md

When CodeSpace opens up it will open up a new readme specific to CodeSpaces and helping to get new contributors onboarded.

CodeSpaces: Scaffold out a file for a specific Codespace readme to auto open

---

src/Umbraco.Web.UI.Client/src/less/rte.less

Set higher z-index for TinyMCE overlays as they were set below that of our property editor overlays. The z-index value is now the same as it was for Tiny v4/Umbraco 10.
Fixes #13414

v11: Fix for TinyMCE dropdowns

---

src/Umbraco.Core/Configuration/ContentSettingsExtensions.cs
src/Umbraco.Core/Configuration/Models/ContentSettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13308
- Added 2 new AppSettings to ContentSettings: 
`AllowedUploadedFileExtensions` & `DisAllowedUploadedFileExtensions`
- Added logic in `UmbracoBuilder.Configuration` to copy the Value of `AllowedUploadFiles` to the new `AllowedUploadedFileExtensions`
- Could argue as this is not necessary because the setting has never worked.
- Try to upload a file in the media library filed (besides the disallowed ones: ashx,aspx,ascx,config,cshtml,vbhtml,asmx,air,axd,xamlx)
- This should upload the file.
- Try setting the Old AllowedUploadFiles:
```
"Umbraco": {
"CMS": {
"Content": {
"AllowedUploadFiles": ["pdf"],
}
}
}
```
- Restart the site and try uploading a pdf in the media library, this should work
- Try uploading anything else than a pdf, …

V10: AllowedUploadFiles appsetting not working

---

src/Umbraco.Core/Extensions/StringExtensions.cs

I noticed that code analyses complains when using the `NullOrWhiteSpaceAsNull` extension on a `string?` value, while the implementation does support `null` values internally.
Changing the parameter from `string` to `string?` should take care of this 😄

NullOrWhiteSpaceAsNull should be nullable

---

src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs

This is a v10 port of https://github.com/umbraco/Umbraco-CMS/pull/11998
- Create a storage account, and a blob container
- In your Appsettings, add the `Storage:AzureBlob` (paste in your connection string and container name from step 1)
```
"Umbraco": {
"Storage": {
"AzureBlob": {
"Stylesheets": {
"ConnectionString": "yourConnectionStringHere",
"ContainerName": "BlobContainerNameHere"
}
}
},
```
- Add the `Umbraco.StorageProvider.AzureBlob` nuget package to the `Web.UI` project
- In your startupcs in the `ConfigureServices` method, add `AddAzureBlobFileSystem` like this:
``` 
services.AddUmbraco(_env, _config)
.AddBackOffice()
.AddWebsite()
.AddComposers()
.AddAzureBlobFileSystem("Stylesheets", options => options.VirtualPath = "~/css")
.Build();
```
- Create a composer to swap out the …

V10: merge v8 blobstorage file deletion fix

---

src/Umbraco.Cms.ManagementApi/Controllers/Search/SearcherSearchSearchController.cs
src/Umbraco.Cms.ManagementApi/Factories/IndexViewModelFactory.cs
src/Umbraco.Cms.ManagementApi/OpenApi.json
src/Umbraco.Cms.ManagementApi/ViewModels/Search/IndexViewModel.cs

Optimizations of the search controller.
1. PagedViewModel was listed twice in a response type - removed one layer
2. ProviderProperties was missing from the IndexViewModel, but it worked a lot better in the old backoffice API with NewtonsoftJson, so I could not just add it again as we are now using System.Text.Json. I'm trying here to format the properties so they match our expectations in the frontend for this specific endpoint. We might want to improve on this on a more general level in the output formatter eventually.
Example output for MembersIndex, which has both arrays, objects, and primitives:

Management API: SearchController improvements

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-configuration-area-entry.html

Having a play with the Block Grid Editor I noticed hovering the options in the areas it said "TODO". Unfortunately I can't grab a screendump of it but I guess it reads from looking at the code in the PR.
Now it will say "Configure Area" or "Delete area" depending, which option is hovered.

Block Grid Editor: Replace "TODO" text in titles

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umb-block-grid-entry.html

Fix issue with inline create button at root level not taking the right width.
in other words, make sure that the calculated width can be used in the CSS calculations not just overwriting them.
Fixies this issue:
To make it appear like this (only visible for root blocks):

use custom prop for calculated width

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.html

Partly solves the concern of https://github.com/umbraco/Umbraco-CMS/issues/13177
For now, the hiding of size options is kept to ensure the first impression of the BlockType overlay is as calm as it gets, to avoid giving users an overwhelming experience. This also helps newcomers ignore the sizing options until they need them.

Remove the hidding of catelouge appearance

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13180
Adjusted sortable options for groups in block grid editor to y-axis, so it doesn't cause horizontal scroll.
I tried with `containment: "parent"` as well, but it currently doesn't work well when sorting to the bottom, because the placeholder doesn't take up the space of the original item.
https://user-images.githubusercontent.com/2919859/196242235-554b2e6f-8a38-49f0-9d62-47a88b885d4c.mp4

Adjust sorting of block grid editor groups to y-axis only

---

.github/README.md
src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/es.xml
src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
src/Umbraco.Core/EmbeddedResources/Lang/he.xml
src/Umbraco.Core/EmbeddedResources/Lang/it.xml
src/Umbraco.Core/EmbeddedResources/Lang/ja.xml
src/Umbraco.Core/EmbeddedResources/Lang/ko.xml
src/Umbraco.Core/EmbeddedResources/Lang/nb.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Core/EmbeddedResources/Lang/pl.xml
src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
src/Umbraco.Core/EmbeddedResources/Lang/zh.xml
src/Umbraco.Core/EmbeddedResources/Lang/zh_tw.xml
src/Umbraco.Web.Common/Extensions/BlockGridTemplateExtensions.cs
src/Umbraco.Web.UI.Client/src/installer/steps/permissionsreport.html
src/Umbraco.Web.UI.Client/src/views/dashboard/dashboard.tabs.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

As we've migrated the documentation to a new platform I've updated most docs links I could find in the CMS project.
I found a few links to the article about the web.config, which is not relevant to 9+.
Let me know if I should also update those - as that will require some updates to the text with the links as well.

Updated docs links to point to new platform

---

.devcontainer/devcontainer.json

The repo & package for the SQLite DevContainer feature has moved after I renamed the repo
The repo was previously called `sqlite-codespace-feature`
```
"features": {
"ghcr.io/warrenbuckley/codespace-features/sqlite:1": {}
}
```

Codespaces: Updated SQLite DevContainer feature after rename

---

src/Umbraco.Core/Constants-Conventions.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13364
When implementing `GetReferences()` method in a property editor using `UmbracoEntityReference` this didn't work for custom relation types, where it tries to insert records which already exists and doesn't remove any previous saved relations after removing items from picker.
An example with a custom property editor using `contentpicker` property editor and `myCustomRelation`:
```
using Umbraco.Cms.Core.IO;
using Umbraco.Cms.Core.Models.Editors;
using Umbraco.Cms.Core.PropertyEditors;
using Umbraco.Cms.Core.Serialization;
using Umbraco.Cms.Core.Strings;
namespace Umbraco.Cms.Web.UI.Editors; …
```

Delete references using custom relation types

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/healthChecks.spec.ts

Add's health-check tests that:
1) Clicks on the "Check all groups" buttons
2) Ensure that the default settings labels are accurate

add health-check basic tests

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs

This fixes #13301.
The issue was that if you ordered your content by published the sort order would be incorrect.
Looking at this it was because we relied on the content version to return an id with a value of "null", however that will only happen if the content has never been published, leading to the weird behaviour described in the issue.
Looking a bit further it seems that the entire reason we use this query to order by published is because of variants (if a content node doesn't exist in a variant, we "fall back" to the default culture in the UI, which may be published).
Since we already have a check to see if the content varies, I just updated it to instead use the `Published` value of the umbracoDocument, since this is perfectly accurate for a non-varying piece of content. 
Try the …

V11: Fix ordering by published in list of content

---

src/Umbraco.Core/Models/PropertyTagsExtensions.cs
src/Umbraco.Core/PropertyEditors/IDataValueTags.cs
src/Umbraco.Core/PropertyEditors/PropertyEditorTagsExtensions.cs
src/Umbraco.Core/PropertyEditors/TagsPropertyEditorAttribute.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/TagsPropertyEditor.cs
src/Umbraco.Web.BackOffice/Controllers/ContentControllerBase.cs
src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js

by introducing a new `IDataValueTags` that has a single `GetTags` method. When implemented on a `DataValueEditor` it gets called when the content is being saved so the tags can be updated in the tags repository. The tags will be associated with the outmost property (the one directly on the content item).
The block list and nested conten data value editors implements the interface and gets the tags from each nested property editor where the data value editor implements the `IDataValueTags` interface. 
The old implementation is still there but it isn't used if the editor implements `IDataValueTags`, its also marked as obsolete so it can be removed in a future version.
To test this add an element type with a tags property (both csv and json) editor to a block or nested content, create some …

Add support for tags in block editors and nested content

---

src/Umbraco.Core/Constants-Conventions.cs
src/Umbraco.Core/PropertyEditors/IDataValueReference.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs

This is a continuation of #13389, see that PR and associated issue for more information. 
As I mention in that PR I realised that the solution wouldn't work in all cases, in particular, it won't allow you to remove a relation again, since it relies on the existing relation itself to tell you that it exists (by alias). 
Instead to solve this what I've done is added a new method to the `IDataValueReference` interface: `GetAutomaticRelationTypesAliases` this allows you to specify the aliases of your custom automatic relation types. This new method comes with a default implementation to make it non-breaking. 
This is then used to determine what relations to recreate.
To test this add a custom property editor implementing `IDataValueReference` (see appendix), and ensure that all relevant …

Ensure that all automatic relation types are updated

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml

As per #13480, changed the allowBlockInAreasHelp translation text in English, and added various Dutch translations having to do with the Block Grid Editor while I was at it! (Not all of them yet, at this point in time!) 🙂

Added various Block Grid translations (EN & NL)

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js

Addresses issue #13009 
the `setDirty()` logic was missing from remove-able actions, this PR adds them

add setDirty() logic to remove actions on mediaPicker3 property editor

---

src/Umbraco.Core/Deploy/DataTypeConfigurationConnectorExtensions.cs
src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector2.cs
src/Umbraco.Core/Deploy/IServiceConnector.cs
src/Umbraco.Core/Deploy/IServiceConnector2.cs
src/Umbraco.Core/Deploy/IValueConnector.cs
src/Umbraco.Core/Deploy/IValueConnector2.cs
src/Umbraco.Core/Deploy/ServiceConnectorExtensions.cs
src/Umbraco.Core/Deploy/ValueConnectorExtensions.cs
src/Umbraco.Infrastructure/Deploy/GridCellValueConnectorExtensions.cs
src/Umbraco.Infrastructure/Deploy/IGridCellValueConnector.cs
src/Umbraco.Infrastructure/Deploy/IGridCellValueConnector2.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/13287 contained breaking changes that affected implementations of `IDataTypeConfigurationConnector`, `IServiceConnector`, `IValueConnector` and `IGridCellValueConnector`. This PR reverts these breaking changes by moving them into a new interface and providing extension methods that tries to use the overload accepting `IContextCache` when available.
Testing should ensure the breaking changes are reverted and after merging/releasing this, the Deploy/Deploy Contrib implementations should be updated and tested separately.

Revert breaking changes adding IContextCache to deploy connectors

---

src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
src/Umbraco.Cms/Umbraco.Cms.csproj

Both the `Umbraco.Cms` and `Umbraco.Cms.Targets` packages don't include any framework specific contents, causing MSBuild to raise a [NU5128 warning during packaging](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128) and NuGet.org not showing any supported frameworks.
This PR uses the `Add an empty _._ file` solution from the linked MS documentation:
> If your package does not contain any assemblies, such as a meta-package, consider adding an empty `_._` file to the `lib/<tfm>/` directories for the TFMs listed in the warning message.
Instead of creating and adding this file to the repository (and updating the path when the target framework changes), I've added an MSBuild task that automatically takes care of this.
Testing can be done by inspecting the generated …

Create and pack empty file to add TFM dependency to Umbraco.Cms and Umbraco.Cms.Targets

---

src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js

This fixes #9145.
The issue is that the view list doesn't replace "Loading..." with the actual value. This happens because angular filters don't work with data that is loaded asynchronously. It will show the correct values if the user leaves the page and goes back to it, since **ncNodeName** caches the data, but it doesn't help for that first visit.
To work around this problem, a timer is set to check the result of the angular expression until it changes from "Loading..." or hits the check limit (currently set to 5). Once it detects the change, it replaces the loading text with the actual value.
This is definitely a hack, but I'm not sure there is a better way to handle this. Thought about tweaking it to only apply to expressions with "ncNodeName," but I do have a couple custom …

added fix for ncNodeName filter in list view

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

The `<umb-editor-header />` directive already contains a load indicator, but it can't really be controlled from outside of the directive. 
Showing a load indicator in the header could be useful when content within the parent `<umb-editor-view />`, so this PR adds a new `loading` parameter to the `<umb-editor-header />` .
In the current codebase, the `<umb-editor-header />` directive already defines a `loading` variable in the scope of the directive. While this is only used when the header component is being initialized, I've taken the liberty to rename the `loading` variable to `initializing` (it's not used outside of the directive). This then makes room for naming the new parameter `loading`.
To test this PR, I've set up a small dashboard to test the new parameter. As the loading state …

Added "loading" parameter to "umbEditorHeader" directive

---

src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html

This fixes https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/39
Related to: [V9: Fix A & AA accessibility issues throughout Backoffice #12546](https://github.com/umbraco/Umbraco-CMS/issues/12546)
**What did you do?**
Added the `aria-labelledby` attribute to the umbraco tags property editor input. 
**Why did you do it?**
The umbraco tags property editor input was failing WCAG Level AA compliance since the input was missing a label. The label for the property editor already existed, it just needed to be linked up to the input that constantly updates as a user adds or removes tags.
Screenshot prior to fix:
Screenshot after fix:
**How to test the changes:**
1. Install v10
2. Install Paul Seal Clean Starterkit Package
3. Navigate to Home Content Node
4. Click SEO Tab
5. Use …

Fixes umbraco/Umbraco-CMS.Accessibility.Issues#39

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

If there's an existing issue for this PR then this fixes [#13149](https://github.com/umbraco/Umbraco-CMS/issues/13149)
With this fix it should work, but I struggle testing locally for now.

Ensure culture is always set in `LocalizeText`

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs

In addition to: https://github.com/umbraco/Umbraco-CMS/pull/11691 . It would be nice to add a `ManifestFilter` directly from the `Startup.cs` class.

Add AddManifestFilter extension method to UmbracoBuilder.CollectionBuilders.cs

---

src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
tests/Umbraco.Tests.Benchmarks/CollectionBenchmarks.cs

It would be better to use `.ToArray` instead of `.ToList` as first of all it is faster, as you can see in the benchmarks, and secondly if you go further down the line in `Database.BulkInsertRecords(items)` it would be converted to an array anyways.
- Upload some images in the backoffice
- Go to the Settings sections
- Open the _Published Status_ dashboard
- Check if in the _Published Cache Status_ the  _MediaStore_ items count matches the amount of images uploaded

Use array instead of list when rebuilding mediacache

---

src/Umbraco.Core/Configuration/Models/LoggingSettings.cs
src/Umbraco.Core/Constants-SystemDirectories.cs
src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs

Related to https://github.com/umbraco/Umbraco-CMS/discussions/13356
- Introduced new setting `Umbraco.CMS.Logging.Directory`
- Obsoleted:
-  `Constants.SystemDirectories.LogFiles` as this is now configurable
-  A series of constructors that now points to new overloads with `IOptions<LoggingSettings>` parameter
- Everything should continue to be like before this PR
- You should now be able to write another path
- Starting with `~` will be relative to the content root
- Absolute paths should work
- Test that log viewer also reads from the custom location

V11: Allow changing logging directory from configuration

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umb-block-grid-entry.html

This PR consists of:
* Make the context bar fit within the available space.
* Remove unnecessary animation (umb-block-grid__block__border-pulse).
* Add before and after elements to make context-bar visually connect, avoiding border disconnecting the bar from the block-border.

Make sure contexbar fits within the available space

---

src/Umbraco.Web.UI.Client/src/views/users/user.controller.js

I noticed in user controller, we have a `getLocalDate` defined, but this already exists in `dateHelper`, so we can just inject `dateHelper` instead and clean up a bit.
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/common/services/util.service.js#L104-L117

Use `getLocalDate` from dateHelper

---

src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs

Added an additional logic which adds the default culture when there's only 1 language configured.
Here's the following use cases made while debugging:
1.) The issue can be replicable if it only have one language and the "Document Type" is set to vary by culture.
2.) The issue cannot be replicable when there's 2 languages configured since the query string for the "culture" is appended before making the request to the [API.](https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs#L172)
This fixes [#12279](https://github.com/umbraco/Umbraco-CMS/issues/12279)

Fix Content Tree Node Not Greyed Out

---

src/JsonSchema/JsonSchema.csproj

There was a configuration key added in the last update, so this dependency bump will include that in the next CMS release.

Updated Forms dependency for JSON schema to the latest version.

---

src/Umbraco.Web.Common/Middleware/BootFailedMiddleware.cs

When Umbraco is configured with `X-Content-Type-Options` `nosniff` as is recommended (there's even a health check for it), any boot failure would simply show the html source code in the browser instead of properly rendering the html, as the content-type wasn't being set.
Reproduction steps:
- Set the `X-Content-Type-Options` header to `nosniff`
- Disable Umbraco's host settings debug mode
- Cause a boot failure
The following snippet can be placed at the top of startup's `Configure` method to set all 3 requirements:
```
app.ApplicationServices.GetRequiredService<IOptionsMonitor<HostingSettings>>().CurrentValue.Debug = false;
app.ApplicationServices.GetRequiredService<IRuntimeState>().Configure(RuntimeLevel.BootFailed, RuntimeLevelReason.BootFailedOnException, new Exception("Boot fail …
```

Added missing content-type header to BootFailedMiddleware response

---

src/Umbraco.Core/Extensions/UriExtensions.cs

Benchmark for GetSafeAbsolutePath
|              Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|----------:|
|                 Old | 40.75 ns | 0.859 ns | 1.990 ns | 0.0048 |      40 B |
|                 New | 17.92 ns | 0.420 ns | 0.747 ns | 0.0048 |      40 B |
Benchmark for GetSafeQuery
|              Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|----------:|
|                 Old | 37.01 ns | 0.750 ns | 0.702 ns | 0.0038 |      32 B |
|                 New | 16.26 ns | 0.359 ns | 0.336 ns | 0.0038 |      32 B |
- Make sure all tests are passing

Use Spans in UriExtensions

---

src/Umbraco.Core/Composing/BuilderCollectionBase.cs
src/Umbraco.Core/Configuration/Models/SmtpSettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/Models/Blocks/BlockListItem.cs
src/Umbraco.Core/Models/Range.cs

Edited some of the comments to try and reduce the warnings that CodeQL is reporting for new pull requests. This PR contains fixes for the obvious issues. In the process I learned things like:
- `<seealso cref` is for referencing code elements, `<seealso href` is for linking to urls
- the compiler respects using statements when looking for types in the cref attribute, so fully qualified namespaces are not usually going to be necessary 
According to my Visual Studio this PR won't have got rid of all the errors, but would be good to see these ones disappear! My VS reports any `cref` that uses nested '{' as malformed. So whilst `cref='IEquatable{T}'` and  `cref='Range{T}'` would be valid, `cref='IEquatable{Range{T}}'` is not. Not sure yet what to do about those. Also remaining are some issues …

Fixing some comments errors to reduce CodeQL warnings

---

src/Umbraco.Web.UI.Client/src/views/logViewer/search.html

This simple PR addes support for "destructed properties" for the log viewer in the back office. 
**What is a destructed property?**
Serilog stores properties associated with a log entry in different ways. *Stringification* is when Serilog will basically just call `.ToString()` on a parameter passed into the log method-call. Serilog also supports storing the property as a object, by *Destructuring* the object. This can be done in different ways but one simple way is to add a @ sign before the the name of the parameter inside the placeholder in the message template, like this:
```csharp
_logger.LogWarning("Not good {@Data1} and {@Data2}", data1, data2);
```
In this scenario, Serilog stores the variables as objects which makes them easier to look at in the logs. Some more info can be found …

LogViewer: Adding support for viewing destructed properties

---

src/Umbraco.Infrastructure/Examine/ContentIndexPopulator.cs
src/Umbraco.Infrastructure/Examine/MediaIndexPopulator.cs
src/Umbraco.Infrastructure/Examine/MemberIndexPopulator.cs

This PR fixes 13254
This PR fixes an issue with examine indexes being rebuilt from the back-office and the screen 'hangs' when the index contains no items.  This happens because the flag indicating the index has been rebuilt is never set for empty indexes.
Currently, when an index is being rebuilt the button is disabled and a loading icon is displayed for the duration until the index rebuild has completed.  This is done by an AJAX call to the back office to check for a flag which is set when the index has been rebuilt.  This flag is never set when the index is empty as the index populator checks for any items in the value-set before indexing.  This fix removes that check in the index populator so empty value-sets are indexed and the completion event is raised (which set the flag).
This …

Allow empty valuesets to be indexed so the back-offce does not hang when rebuilding empty indexes

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbdatetimepicker.directive.js
src/Umbraco.Web.UI.Client/src/views/logViewer/overview.html

This PR fixes #13250
Add an aria labelled by attribute to the umb-date-time-picker directive to allow a label to be set on the Time Period input on the log viewer dashboard.
As per the issue 13250, the input field for the Time Period on the log viewer dashboard is missing a label for accessibility.  I have added a label parameter to the umb-date-time-picker to allow the label to be passed to the input field for the date/time picker.
1. Install the Wave accessibility plugin for your browser (https://wave.webaim.org/extension/)
2. Open the log view in the back office.
3. Run the Wave accessibility plugin on the log viewer dashboard and ensure no errors are displayed relating to missing form labels (there will still be other warnings).
4. Make sure the time period allows you to select a date …

Added aria label to time period on log viewer dashboard

---

src/Umbraco.Cms.ManagementApi/Controllers/Security/BackOfficeController.cs

This PR adds handling for external authentication providers for the new backoffice.
First and foremost you need an external authentication provider configured. For testing we'll use GitHub.
1. Create a GitHub OAuth app at https://github.com/settings/developers (or ask KJA for one).
- The app configuration should looks something like this: 
2. Include the NuGet package `AspNet.Security.OAuth.GitHub` in your site.
3. [Unzip this file](https://github.com/umbraco/Umbraco-CMS/files/10102918/GitHubAuthenticationProvider.zip) and add the code to your site.
4. Add your app ID and secret to `GitHubAuthenticationExtensions`:
5. Add `.AddGitHubAuthentication()` to `ConfigureServices(IServiceCollection services)` in `Startup`.
6. Verify that the Umbraco login screen now says "Sign in with GitHub" …

Handle external authentication providers

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Infrastructure/Telemetry/Providers/SystemInformationTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserDataServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SystemInformationTelemetryProviderTests.cs

I noticed that the system information in the backoffice help menu doesn't differentiate between IIS and IIS Express. I think it probably should, so this adds that distinction.
To test: Open the help menu, then system information, while running in IIS Express and it will tell you that you're using IIS Express.
The IIS & IIS Express check makes sense, as the point of those servers is that they host the site in process. Kestrel is a little different as it's bootstrapped _inside_ of ASP.NET. Kestrel is the default, but presumably the web server _could_ be HTTP.sys or some other IServer implementation.
I think the only way to know for sure is to inject IServer and get the name of the class implementing it, but that adds a dependency on …

Improve system information/telemetry

---

src/Umbraco.Infrastructure/Mapping/UmbracoMapper.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Mapping/MappingTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.New.Cms.Infrastructure/Factories/DatabaseSettingsFactoryTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs

- Refactored _maps field to use a concurrent dictionary
- Changed the .Add to .TryAdd
- Added a helpful log message if we fail to add the item.
- Install Umbraco
- Click "Packages"
- Click "Created"
- Click "Create Package"

Fix concurrency issue in UmbracoMapper

---

src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/12705
This PR fixes the issue where user state filters are forgotten when switching from tabs (dashboard). @nul800sebastiaan  made a video where the bug is visible: https://github.com/umbraco/Umbraco-CMS/issues/12705#issuecomment-1187457346
You can use the steps in the video to verify the bug is fixed in this PR.

Fix check for existing userStatesFilter

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js

Fixes #13463
This adds a feature to support selecting containers (folders) in tree pickers. While the use case is not there at the moment inside the Backoffice, it was possible before to click containers, but all you got was a 404 error with a flashy notification indicating something went wrong.
We are now constructing a shell for a container, so it behaves much like a real entity. Containers are seen primarily for data type and document type pickers.

Tree picker support for selecting containers

---

src/Umbraco.Core/Actions/ActionAssignDomain.cs
src/Umbraco.Core/Actions/ActionBrowse.cs
src/Umbraco.Core/Actions/ActionCopy.cs
src/Umbraco.Core/Actions/ActionCreateBlueprintFromContent.cs
src/Umbraco.Core/Actions/ActionDelete.cs
src/Umbraco.Core/Actions/ActionMove.cs
src/Umbraco.Core/Actions/ActionNew.cs
src/Umbraco.Core/Actions/ActionNotify.cs
src/Umbraco.Core/Actions/ActionProtect.cs
src/Umbraco.Core/Actions/ActionPublish.cs
src/Umbraco.Core/Actions/ActionRestore.cs
src/Umbraco.Core/Actions/ActionRights.cs
src/Umbraco.Core/Actions/ActionRollback.cs
src/Umbraco.Core/Actions/ActionSort.cs
src/Umbraco.Core/Actions/ActionToPublish.cs
src/Umbraco.Core/Actions/ActionUnpublish.cs
src/Umbraco.Core/Actions/ActionUpdate.cs
src/Umbraco.Core/Actions/IAction.cs

Prerequisites
Description
Some actions had these some did not, this standardises the approach, and also allows developers to access these values in notifications etc, without creating their own references to the permissions/aliases
Matt
formally - https://github.com/umbraco/Umbraco-CMS/pull/13215

standardising ActionLetter and ActionName for IAction

---

src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html

If there's an existing issue for this PR then this fixes [User management - Coded as H1 but different to other H1s seen on site #64](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/64)
Sections across the backoffice had a variety of different headings
Previously, if the tree root contained a group it would be tagged with a heading of H1.  If the tree root contains multiple groups, then the items would be coded as H5.  This resulted in some sections having H5 as the main heading.
This has now been changed so that all tree root headings are H1 and styled the same
Log into Umbraco
Browse to any of the sections
The top level heading in the sidebar should always be H1

Tree Roots are H1

---

src/Umbraco.Cms.Api.Management/Controllers/Dictionary/AllDictionaryController.cs
src/Umbraco.Cms.Api.Management/Controllers/Dictionary/CreateDictionaryController.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/AllLanguageController.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/CreateLanguageController.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/UpdateLanguageController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json

Added a few missing `ActionResult` to endpoint signatures.
Made the Dictionary and Language controllers a little more REST-ish.
Verify that you can...
1. Invoke the "create new dictionary item" endpoint by:
```
POST /umbraco/management/api/v1.0/dictionary
{
"key": "5a3ab4fd-9006-476b-a5b5-a63a3c1ca475",
"parentId": "d9276743-c295-4c6a-9fed-185d07e2a228"
}
```
2. Invoke the "create new language" endpoint by:
```
POST /umbraco/management/api/v1.0/language
{
"isoCode": "en-US",
"isDefault": false,
"isMandatory": true
}
```
3. Invoke the "update language" endpoint by:
```
PUT /umbraco/management/api/v1.0/language/1
{
"isoCode": "en-US",
"isDefault": false,
"isMandatory": true
}
```
The dictionary creation endpoint is likely not entirely useful for the new backoffice, as it only acceps a …

REST-ify dictionary and language controllers

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout-flexbox.css
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout.css

Ensures an Area is treated like Flexbox, making it easier to change the vertical alignment of its content. and ensuring it takes full height, so its easier to drag into the Areas.
Notes for testing:
This is already the way the layout is written in the Block Grid Example Website, so already a pretty stable solution.

BGE: Make Areas use Flexbox for easy customisation and better drag n' drop UX

---

src/Umbraco.Core/Configuration/LoggingSettingsExtensions.cs
src/Umbraco.Core/Configuration/Models/LoggingSettings.cs

While changing the JSON schema generation to a .NET tool that loads an assembly to get the type to generate the schema from (see PR https://github.com/umbraco/Umbraco-CMS/pull/13560), I encountered the following error:
```
Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```
I'm not a 100% sure why it can't find this assembly, since Umbraco.Core does have a dependency on Microsoft.Extensions.Hosting.Abstractions 7.0.0, but I see the `LoggingSettings` class does use the `IHostEnvironment` interface from this assembly since a recent change in PR https://github.com/umbraco/Umbraco-CMS/pull/13485.
Since these changes aren't released yet and the method using …

Change `GetAbsoluteLoggingPath` to extension method

---

src/Umbraco.Infrastructure/PropertyEditors/MultipleTextStringPropertyEditor.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco.Deploy.Issues/issues/143.
Although the linked issue was raised as being Umbraco Deploy specific, the `Umbraco.MultipleTextstring` property editor in the CMS is the root cause for not properly saving/showing the newline delimited values.
Because this editor currently uses `Environment.NewLine` for both combining and splitting the multiple text values, the stored data will change depending on the server OS/environment. This is an issue when saving the values locally on a Linux/Mac OS systems that uses `\n` and then deploys that value to a Windows environment (like Umbraco Cloud): when showing the value in the backoffice, it splits the value using `\r\n`, which results in a single value.
The same can …

Umbraco.MultipleTextstring: save using consistent newline and support parsing different newlines

---

src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs
src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs

- Added mapping for AdditionalData
- I Used a SendingContentNoticiationHandler to add some values to additionalData.
- Create a document type with allow as root set to true
- Create a content for it
- Open dev tools and go to network tab
- Refresh the page
- Find the GetById request
- The metadata object should now be filled with your data like so:
Code snippet: 
```
public class PreviewUrlSendingContentNotificationHandler : INotificationAsyncHandler<SendingContentNotification>
{
public PreviewUrlSendingContentNotificationHandler()
{
}
public async Task HandleAsync(SendingContentNotification notification, CancellationToken cancellationToken)
{ …
```

Map AdditionalData

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/Maintenance.cshtml
src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
src/Umbraco.Web.BackOffice/Install/InstallAreaRoutes.cs
src/Umbraco.Web.Common/ActionsResults/MaintenanceResult.cs
src/Umbraco.Web.Common/Authorization/FeatureAuthorizeHandler.cs
src/Umbraco.Web.Common/Controllers/MaintenanceModeActionFilterAttribute.cs
src/Umbraco.Web.Common/Controllers/RenderController.cs
src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/InstallAreaRoutesTests.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13309
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13247
The catch all route that existed to redirect to login/installer when in `RuntimeState.Level` = `Install` or `Upgrade`, made a lot of trouble when `RuntimeState.Level` = `Run`.
This have been an issue since v9, because we can't reboot. Therefore the catch all route still existed when `RuntimeState.Level` = `Run`.
This PR removes the catch all route. Redirects to installer is now handled by `UmbracoRouteValueTransformer` and to handle upgrades nicely, I have introduced a new Maintenance page.
This is by default used, instead of redirecting website visits to the upgrader.  A new configuration is added, to not show the maintenance page, as most migrations can be handled without …

Maintenance page when in upgrade state

---

src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13558
If your content type is set to vary by culture but you only have one language enabled, the unpublished state of a content item is not displayed correctly in the content tree. In the following screen shot, the underlined content item is not published:
Here is the same item with this PR applied:
1. Ensure you only have one language.
2. Create a content type that is allowed to vary by culture.
3. Verify that the published and unpublished state is reflected in the content tree when publishing and unpublishing content of that content type.
4. Change the content type so it is no longer allowed to vary by culture.
5. Repeat step 3.

Fix unpublished state for culture variant content in a single language site

---

src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12883
As described on the linked issue, packages that support package migrations are always reported as having pending migrations under "Installed packages" - even when they don't have any pending migrations.
This is a regression issue caused by [this commit](https://github.com/umbraco/Umbraco-CMS/commit/2009f7585b1d7489f4f9e6c158edae8ff556c762#diff-2d1623773840660fdc71834dc86ebb3904dec868441778aca6f9b4c2bed7848e) as part of a large refactor.
Here is the "Installed packages" view before this PR:
And here is the same view with this PR applied (no migrations have been run in the meantime):
1. Install Umbraco.Forms from NuGet
2. Go to "Installed packages"
3. Verify that there are no pending …

Fix wrongfully reported pending package migrations

---

src/Umbraco.Core/Extensions/ObjectExtensions.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/ObjectExtensionsTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12832
For some reason our `ObjectExtensions.TryConvertTo` doesn't play nice with `StringValues` input types. This is the root cause for the linked issue.
I have added support for `StringValues` (treating them as `string`) and added some unit tests to prove that it works 😆 
As mentioned on the linked issue, this PR can be tested by using editors with limited content access and an MNTP that ignores user start nodes.
1. Create an editor with limited access to the content tree (a start node somewhere below the root).
2. Create an MNTP that is configured to pick content and to ignore user start nodes.
3. Add said MNTP to a content type which the editor is able to reach in the content tree.
4. …

Handle StringValues in ObjectExtensions.TryConvertTo

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13577
This PR improves the handling of TinyMCE custom style formats defined in app settings.
After an internal discussion we've agreed on the following rules:
1. If an RTE is configured with one or more stylesheets in the backoffice, the stylesheet rules should be the only ones available in the TinyMCE style selector (do not merge with any custom or default styles).
2. If custom styles are defined in app settings and no stylesheets are configured for the RTE, the custom styles should be the only ones available in the TinyMCE style selector (do not merge with the default styles).
3. If neither stylesheets are configured for the RTE nor custom styles are defined in app settings, the …

Improved support for TinyMCE custom style formats

---

src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13576
A few issues have turned up for the multi URL picker in V11:
1. It simply doesn't work when used as a culture invariant property on a culture variant content type.
2. The URLs displayed are either broken or wrong.
Turns out the multi URL picker simply doesn't render its items when displayed in "preview" mode. And since invariant properties are in "preview" mode by default, this is quite the issue for the multi URL picker. The resulting behaviour differs with the content item state:
- If the content item only has one saved culture, the multi URL picker seems to work, but only on that one saved culture; as soon as you change culture and attempt to "unlock" it for editing, it becomes …

Multi URL picker improvements for V11

---

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Common/FileProviders/ContentAndWebRootFileProviderFactory.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13565
This introduces a composite file provider for the `IManifestFileProviderFactory` to read from both the web-root and the content-root.
- Follow guide on https://github.com/umbraco/Umbraco-CMS/issues/13565

Load Package.Manifest's from content root too

---

src/Umbraco.Web.BackOffice/Install/InstallAuthorizeAttribute.cs
src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs

This replaces PR https://github.com/umbraco/Umbraco-CMS/pull/12968 (and retargets it to v11): the `GetBackOfficeUrl()` extension methods contained a bug in a type lookup (because of updated namespaces) and a wrong route area that caused it to always return `/`.
Instead of fixing the original extension methods, this obsoletes the existing ones (on both `LinkGenerator` and `IUrlHelper`) and adds new `GetUmbracoBackOfficeUrl()` extension methods.
You can test this by using the following view:
```
@inject Microsoft.AspNetCore.Routing.LinkGenerator LinkGenerator;
@inject Umbraco.Cms.Core.Hosting.IHostingEnvironment HostingEnvironment;
<ul>
<li><a href="@Url.GetBackOfficeUrl()">Url.GetBackOfficeUrl()</a></li>
<li><a …
```

Add `GetUmbracoBackOfficeUrl` extension methods

---

src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
src/Umbraco.Web.Common/Models/DisabledUsersModel.cs
src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/Controllers/UsersControllerTests.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13552
- Added logic to skip invited users on the server
- Disable the "disable" button, when user is invited.
- Don't fake "disabled" state in the frontend.
- Remember to run `npm run build` as there are frontend changes 👍 
- Enable smtp by filling out the values in appSettings.Development.json
- Run umbraco
- Invite a user from the backoffice
- Use the list view of all users: 
- Select and disable the invited user:
YOU SHOULD NO LONGER BE ABLE TO :
- Activate the user
- Change the users password
- You can now login

V10: Dont disable invited users

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less

Really small PR that adds `margin-right: 16px` to the name and subname elements on the block card, to match the current `margin-left` and prevent text running up to the right edge of block cards, like so:

Add margin-right to block card name and subname

---

src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html

This PR fixes #13619 
1. Create a new member based on the default member type.
2. Open the DevTools
3. You can see that the `data-element` attribute of the `umb-property` element is now changing for each property. Previously the alias displayed was from the group containing the property.

fixes data-element attribute on media section

---

src/Umbraco.Infrastructure/Logging/Viewer/ILogViewer.cs
src/Umbraco.Infrastructure/Logging/Viewer/ILogViewerConfig.cs
src/Umbraco.Infrastructure/Logging/Viewer/LogViewerConfig.cs
src/Umbraco.Infrastructure/Logging/Viewer/SerilogLogViewerSourceBase.cs
src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs

Fixing nullability for the log viewer since collections will be empty and not null when no elements.
- Navigate to the Log Viewer dashboard;
- Make sure you are still getting the saved searches;
- Modify them - ex: delete or save new ones;
- Get them again.

V12: Change nullability for the log viewer

---

src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs
src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs

Fixes #12444
This is required for consumers that intend to use `WithCustomMiddleware` in order to customize the middleware order instead of `WithMiddleware`, as otherwise they are forced to re-implement this method.
In order to test the usage of `WithCustomMiddleware` the following example snippet can be used:
```
app.UseUmbraco()
.WithCustomMiddleware(u =>
{
u.RunPrePipeline();
app.UseUmbracoCore();
app.UseUmbracoRequestLogging();
app.UseUmbracoRouting();
app.UseUmbracoMediaFileProvider();
app.UseStaticFiles();
app.UseUmbracoPluginsStaticFiles();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseRequestLocalization();
app.UseSession();
u.RunPostPipeline();
u.UseBackOffice();
u.UseWebsite();
})
.WithEndpoints(u =>
{
u.UseInstallerEndpoints(); …
```

Exposed media file provider configuration method

---

src/Umbraco.Web.UI.Client/src/less/components/umb-iconpicker.less
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html

I noticed it wasn't possible to hide colors from icon picker infinite editor. Sometimes when using this in custom property editors etc. one may not need the colors, just a icon to select.
I also noticed it "jumped" a bit on icon selection, because it add a 1px border (so it need to 1px transparent border by default - or something else to compensate the 1px solid border on selection.
Furthermore it seems the icons didn't align well for different sizes of overlay. While it may work in small overlay, it would be difficult to adjust correct for medium and large overlays also.
I have replaced this with CSS grid instead with fill the icons to its container, a bit gap between and minimum ~~70px~~ 60px width for each icon. `auto-fill` fill the container, while I noticed `auto-fit` would stretch …

Hide colors from icon picker

---

src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs

Fixes an issue where database wouldn't be recreated if already configured.
- Check if connectionstring is there, if it is configured, don't run step
- Set the `umbracoDbDSN` & `umbracoDbDSN_ProviderName` in your `appsettings.json`, example for SQLite:
```
"ConnectionStrings": {
"umbracoDbDSN": "Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True",
"umbracoDbDSN_ProviderName": "Microsoft.Data.SQLite"
},
```
- Try to install

V10: Dont configure database if connectionstring is configured

---

src/Umbraco.New.Cms.Infrastructure/Installer/Steps/DatabaseConfigureStep.cs

Fixes an issue where database wouldn't be recreated if already configured.
- Don't run database configure step if connectionstring is already configured.
- Set the `umbracoDbDSN` & `umbracoDbDSN_ProviderName` in your `appsettings.json`, example for SQLite:
```
"ConnectionStrings": {
"umbracoDbDSN": "Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True",
"umbracoDbDSN_ProviderName": "Microsoft.Data.SQLite"
},
```
- Try to install

V13: Don't execute databaseconfigurestep if configured

---

src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11863
This PR ensures that we use the active client culture (if available) when we render macro HTML for the backoffice.
1. Create a macro with the following partial view (the macro must be configured to render in RTEs):
```html
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage
<b>Culture: @System.Threading.Thread.CurrentThread.CurrentCulture.Name</b>
```
2. Insert the macro in an RTE on a content page that varies by culture.
3. Verify that the macro out the correct culture within the RTE when swapping between cultures.
This does not work with split views - there is generally issues with split views and culture bound property editors. See …

Use the client culture if available when rendering macro HTML

---

src/Umbraco.Core/Configuration/Models/HealthChecksNotificationSettings.cs
src/Umbraco.Core/Configuration/Models/HealthChecksSettings.cs

I came across this issue when trying to add similar configuration, finding that configuration properties defined with `IEnumerable` don't get bound.  They do with `List` which is what I've updated these two examples to.
To Test:
- Prior to applying these code changes, set up the configuration documented [here](https://our.umbraco.com/Documentation/Reference/Configuration/HealthChecks/#health-checks) or as below:
```
"Umbraco": {
"CMS": {      
"HealthChecks": {
"DisabledChecks": [
{
"Id": "D0F7599E-9B2A-4D9E-9883-81C7EDC5616F"
}
]
}
```
- This should disable the _Configuration > Macro Errors_ healthcheck, but you'll see it's still available
- Apply the code changes and you should see it's no longer available.

Changed healthcheck collection configuration to use a concrete type to ensure configuration settings are bound.

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11688
As mentioned on the linked issue there are some problems when certain property editors have the alias `navigation`:
**Block list**
**Media picker 3**
With this PR applied the property editor add/create buttons look as they should:
**Block list**
**Media picker 3**

Fix broken buttons for properties with alias "navigation"

---

src/Umbraco.Web.UI.Client/src/less/listview.less
src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11741
If items in the mini list view are un-selectable, the item gets dimmed down (opacity 0.6) and a not-allowed cursor is applied. Unfortunately this also affects the right-arrow icon that indicates one can expand the un-selectable item. Thus it's not entirely obvious that one can expand the item, as the expand icon is dimmed down and has a not-allowed cursor. But you actually can expand it (and rightfully so!).
Here's how it plays out:
This PR fixes it by making the CSS a tad more deliberate/specific. Here's another screencast with this PR applied:

Make sure the expand icon is never faded in mini list views

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12121
When a content picker (MNTP) is configured with an XPATH query/scope, the scope is not applied in infinite editing; instead the parent scope is reused.
This means a content item in infinite editing will end up with an incorrect starting point when using scoped pickers.
1. Create an MNTP with a `$parent` XPATH scope and "Show open button" enabled:
2. Add the MNTP to a content type and create a content structure based on this content type - at least three levels deep.
3. On a content item at level 2, use the MNTP to pick another content item at level 3. Note that the `$parent` scope is applied correctly when the picker opens.
4. Open the picked content item directly from the MNTP and …

Fix the content picker XPATH scope in infinite editing

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12067
This PR ensures that we use the element type icon colors in the block list catalogue, unless a specific color has been defined for the catalogue appearance of said element.
1. Create a Block List datatype with at least two element types. Both element types must have colored icons.
2. Verify that the element type icon colors are reflected in the Block List datatype configuration:
3. Verify that the element type icon colors are reflected in the Block List property catalogue:
4. Configure an explicit icon color for one of the element types in the Block List datatype configuration:
5. Verify that the configured icon color is applied in both the Block List datatype configuration and the …

Use element type icon colors in block list catalogue

---

src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12033
As stated on #12033 there is a slight weirdness going on when creating new culture variant content "one culture at a time". 
Steps to reproduce:
1. Create a new content item that is allowed to vary by culture. 
2. Add a name for the first culture - do NOT select/edit another culture.
3. Save the content. A "content saved" notification will inform you, that the content has been saved in the given culture.
4. Stay on the same content item and select another culture.
5. Add a name for the other culture and save again. Notice the other culture is the only one available in the "Ready to Save?" dialog.
6. A "content saved" notification will inform you, that the content has been saved in …

Only save selected variant for new content

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12810
Update: This also fixes https://github.com/umbraco/Umbraco-CMS/issues/12144
It is currently kinda hard to move several properties between tabs in succession. It *is* possible, but it requires just the right touch (or rather, just the right drag-fu).
This PR makes property dragging between tabs work as expected when dragging multiple properties in succession.
To test, create a content type with two (or more) tabs and two (or more) properties. Then start dragging properties around between tabs and verify that you can indeed do that several times in a row without getting stuck.

Make it possible to drag multiple properties to other tabs in succession

---

src/Umbraco.Web.UI.Client/src/less/components/umb-property-editor.less

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13495
This PR reverts #13033, which was created for V10 to fix #12989. This has been discussed internally, and it is safe to revert for V11.
Once reverted, the "z-index bleed-through" issue observed in #13495 is solved, because the property editor layout (and thus z-index assignment) is now contained within the property editor container.
1. Create at least three languages.
2. Create a content type that varies by culture.
3. Create a property on this content type that does *not* vary by culture. Note that the property *must* be the topmost one on the content type.
4. Enable editing invariant properties from non-default languages by adding `"AllowEditInvariantFromNonDefault": true` to app …

Make sure the property editor layout is contained within its container

---

src/Umbraco.Core/EmbeddedResources/Snippets/RegisterMember.cshtml
src/Umbraco.Web.Website/Controllers/UmbRegisterController.cs
src/Umbraco.Web.Website/Models/RegisterModel.cs
src/Umbraco.Web.Website/Models/RegisterModelBuilder.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11923
This PR re-introduces the option to conditionally log in members after registration using the built-in macro templates and controllers. Today they are always logged in with no option to bypass that - previously that was configurable in the template.
The default remains as members being automatically logged in.
1. Create three macro using the built-in templates:
- "Register Member"
- "Login"
- "Login Status"  
2. Make sure the macros are allowed in RTEs.
3. Add all macros to an RTE.
4. Render the RTE in the template with something like this:
```html
@{
Layout = null;
}
<html>
<body>
@Model.Value("text")
</body>
</html>
```
5. …

Re-introduce the option to conditionally login members after registration

---

src/Umbraco.Core/Constants-SqlTemplates.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13464
This PR fixes the issue with copy content not preserving the sort order of the content items.
I have added a SortOrderExists function to the code, to check if the sort order already exists in the tree. This was necessary because otherwise the first parent item which we want to copy would not have a new sort order on the main tree.
Steps to test and reproduce the issue are greatly documented in the issue. I have copied the steps to reproduce down below. 
> Hi @denhaandrei, thanks for reaching our 💪 I can confirm that this is an issue **not only** on v10.3.2 but also on previous major Umbraco versions, so the problem has been there for a while... 🤷 The steps I used to reproduce are …

Fix copy content with descendants not copying sort order (#13464)

---

src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs

I noticed in Forms the separator before reload action was a bit inconsistent https://github.com/umbraco/Umbraco.Forms.Issues/issues/869
I had a look at Umbraco core as well and found reload action in root of Media Types tree to be different as well.

Add separator before reload node in Media Types tree

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbstickybar.directive.js
src/Umbraco.Web.UI.Client/src/less/listview.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

This PR fixes the issue described in [Accessibility issue 47 ](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/47)
**Steps to replicate:**
1. Go to Media section
2. Select some existing images on the main dashboard
3. Additional menu options appear
4. Navigate with a keyboard (tab)
5. Focus does will now go to those options after navigating past the list
In order to fix the issue I have moved the selection based tools into their own list sub header that is below the list element. I have then added some CSS to ensure that is stays the same visually. In addition I have update the umb-stickybar directive to fix a bug where and additional element kept getting added to the DOM unnecessarily. I used the Umbraco starter kit for the media
The example gif below demonstrates the …

Selecting media - Revealing content focus order

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Tree/ContentTreeItemViewModel.cs

This PR adds "is trashed" info to content and media tree items.
I have opted to leave this out of the recycle bin controller as it is rather implied 😆 
You'll likely need to use the `items` endpoint to fetch items that are trashed:

Add "is trashed" data for content and media tree controllers

---

src/Umbraco.Infrastructure/Install/PackageMigrationRunner.cs
src/Umbraco.Infrastructure/Migrations/IMigrationContext.cs
src/Umbraco.Infrastructure/Migrations/IMigrationPlanExecutor.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
src/Umbraco.Infrastructure/Migrations/MigrationContext.cs
src/Umbraco.Infrastructure/Migrations/MigrationPlan.cs
src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
src/Umbraco.Infrastructure/Migrations/PostMigrations/ClearCsrfCookies.cs
src/Umbraco.Infrastructure/Migrations/PostMigrations/DeleteLogViewerQueryFile.cs
src/Umbraco.Infrastructure/Migrations/PostMigrations/RebuildPublishedSnapshot.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/Upgrader.cs
tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/PostMigrationTests.cs

This PR obsoletes the things broken in #13654.
Where possible I've tried to provide alternatives, but for some, like `DeleteLogViewerQueryFile` there isn't really an alternative, it'll be removed because it isn't used.

Obsolete things broken in migrations refactor

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

Fixes #13603
Due to how TinyMCE 6 changed the way it works with buttons, we initially failed to replicate the same logic from Umbraco 10 (TinyMCE 4) as to the macro button. We relied too much on the NodeChange event, which is not very performant for one and is not what we need at all. This PR changes the way we detect and work with macros in the following way:
1. We now no longer check if you selected a macro element or not before activating the macro insert button (it is now always active), which allows you to select a macro and then click the button (to edit the parameters)
2. We no longer save each selected element through the NodeChange event but now instead look it up only when you click the "Insert Macro" button
1. We need to do this since you can edit the parameters of an existing …

V11: fix issue where editing a macro was not possible

---

src/Umbraco.Web.UI.Client/gulp/config.js
src/Umbraco.Web.UI.Client/gulp/util/processJs.js

Turn off eslint in gulp when you are watching, which works for 'dev' and 'fastdev' modes making them even faster. We now only lint the files when you are actually building.

v11: gulp should only run eslint on build

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.controller.js

Fixes #13694 
Partly introduced with #13108 since input-id was not generated correctly because the prevalues in one case were not being run through the `DataTypeHelper::createPreValueProps` function.
Prevalues need to have an "alias" key to work properly with the EventsService, which they do not get directly from the server but is instead generated by the client. In one case, this generation did not find place before the prevalues were submitted back to the server (where we also require the "alias" property). This fix ensures that prevalues are always formatted for the display models used in views.
The same logic is already being applied in datatype prevalue configuration (when you open a datatype directly and edit there), so no need to change anything there.

V11: Prevalues as toggles have problems in datatype settings view

---

src/Umbraco.Web.Common/ModelsBuilder/InMemoryAuto/CollectibleRuntimeViewCompiler.cs

We got a report internally that the log message has changed as part of the InMemory fix for V11. 
Previously the specific compilation error would be displayed on the front end if development was enabled, AND logged in the backoffice regardless of development status.
After the changes in #13107 this log message changed to a generic unhelpful message.
Unfortunately, this is logged from the `DeveloperExceptionPageMiddleware` which is dotnet thing, so we can't really change that. 
Instead, I've added a log message in the `CollectibleRuntimeViewCompiler` which will display the helpful message. 
To test this make sure your site is using InMemoryAuto.
Now create a view with a compilation exception, for instance by adding `@Model.ThisPropertyDoesntExist`, and ensure that a helpful message is …

V11: Add improved log message on compilation failure using InMemoryAuto

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.html

I noticed on some Umbraco 10 project that password managers in some cases focused the "hidden" textarea in richtext editor.
Not sure if there's specific reason it can't use `display:none` or `visually:hidden`.
However even width and height is set to 0 the textarea still has a size because of padding and border.
https://user-images.githubusercontent.com/2919859/190515247-b5c14576-9aaa-48b1-a4fe-c6526d211477.mp4

Ensure to reset padding and border as well for textarea in richtext

---

src/Umbraco.PublishedCache.NuCache/DataSource/BTree.cs
src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/12159
The previous hack was only nescessary because the BPlusTree Package did some wrong reflection. 
We now use same mode as Umbraco 8 (default), since we forked the project, and (hopefully) fixed the issues related to that mode.
The info on the enum explains most:
```cs
public enum StoragePerformance
{
/// <summary> (100k rps) Uncommitted changes will be lost, a crash durring commit may corrupt state. </summary>
/// <remarks> 
/// No changes are committed until a call to Commit is made, durring the commit a partial write may corrupt the store.
/// </remarks>
Fastest = 1,
/// <summary> (30k rps) Uses a system-cached transaction log to recover uncommitted changes after a process crash. </summary>
/// <remarks> Will not corrupt state; …
```

Fixes issue with nucache slow on linux, when cold-booting

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13717
- Update the label if the old label is the old color (this should prevent changing of labels if they are custom)
- Run umbraco
- Go to the approved color datatype
- Add the black color & save
- Update the black color to any other.
- Try and add the black color.

Colorpicker: Update label when updating color

---

src/Umbraco.Core/Configuration/Models/UmbracoPluginSettings.cs

The UmbracoPluginPhysicalFileProvider - https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.Common/Plugins/UmbracoPluginPhysicalFileProvider.cs
Reads in browsable File Extensions from configuration, and the default plugin settings that Umbraco ships with have the usual sort of web file extensions you'd expect...
This governs what can be loaded from the App_Plugins folder above wwwroot, eg files shipped with an Umbraco package or perhaps in some customer development
And people can augment this list of files extensions via their own AppSettings...
... but I just noticed that packages and plugins that ship .woff2 files in their App_Plugins folder eg Vendr, end up with a 404 for the .woff2 file...
I mean people can always configure to avoid this, to add woff2 in …

Add .woff2 to BrowsableFileExtensions

---

src/Umbraco.Infrastructure/Logging/Viewer/ExpressionFilter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs

Fixes #13715 
* Ensure unit tests pass
* Search for `index` and ensure it returns results
* Search for `@Message like '%index%'` and ensure it returns the same results as above

Fixes #13715 Simple LogViewer queries not returning results

---

src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs

When a user requests password reset, the SendEmailNotification is not fired. This PR fixes this

Send email notification on password reset

---

src/Umbraco.Core/Extensions/UdiGetterExtensions.cs
tests/Umbraco.Tests.Common/Builders/PartialViewBuilder.cs
tests/Umbraco.Tests.Common/Builders/ScriptBuilder.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UdiGetterExtensionsTests.cs

We had [this issue](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/153) reported on the Deploy tracker, noting an problem when restoring from Windows into a Mac environment, when there were stylesheets held in a folder.
I think cause is how we are generating UDIs for these types of files (stylesheets, scripts and partial views).  We base this off the path, but don't normalize for the different path separators (`\` and `/`) used on Windows and Mac/Linux.  Given we are generating UDIs, which are URI-like, seems we should really be using the `/` here.
So this PR does and verifies this.
- Currently we have e.g. `umb://stylesheet/styles%5Ceditor.css`
- With this update we'd have e.g. `umb://stylesheet/styles/editor.css`
I've tested Deploy having done this, and don't find any issues in …

Uses URL path separator when generating UDIs for files nested in folders.

---

src/Umbraco.Core/Services/DataTypeService.cs

The message for the obsolete `DataTypeService` constructor is somewhat lacking; it currently reads `"Please use constructor that takes an "` 😆 
As the obsolete constructor is going to be removed in V13 I have updated the obsolete message accordingly.

Correct the obsolete message for DataTypeService constructor

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js

If there's an existing issue for this PR then this fixes [#13758](https://github.com/umbraco/Umbraco-CMS/issues/13758)
The initialization values for the buttons have been changed so that the list view buttons are not displayed first, but only when the user when the user has permission to use them.
For information about the bug and steps to reproduce. See  [#13758](https://github.com/umbraco/Umbraco-CMS/issues/13758)

Changed default initialized button permissions for listviews

---

src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs
src/Umbraco.Infrastructure/Examine/UmbracoIndexConfig.cs
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Examine/UmbracoContentValueSetValidatorTests.cs

This PR fixes #13729
- Changed the namespace of the "IScopeProvider" from Umbraco.Cms.Core.Scoping to Umbraco.Cms.Infrastructure.Scoping

IScopeProvider" is now used from Umbraco.Cms.Infrastructure.Scoping

---

src/Umbraco.Core/Media/EmbedProviders/Youtube.cs

If there's an existing issue for this PR then this fixes #13632
- When using shorts url in the umbraco Embed I keep getting the "not supported" error.
- I added the a regex pattern fo youtube shorts urls.
- This fixed the propblem.

Added youtube shorts url pattern.

---

src/Umbraco.Web.Common/Security/MemberManager.cs
src/Umbraco.Web.Common/Security/MemberSignInManager.cs

When you're using external login providers you sometimes want to override the MemberManager and MemberSignInManager classes with custom implementations. By making the methods of these classes virtual you can inherit from those classes and only override what you need to.
This is an example of the CustomMemberSignInManager where I override the virtual ExternalLoginSignInAsync method:
```
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Umbraco_OpenIdConnect_Example.Core.Extensions;
using …
```

Make methods virtual so they can be redefined in derived classes.

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/ByKeyDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/CreateDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/DataTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/DeleteDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/ByKeyDataTypeFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/CreateDataTypeFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/DataTypeFolderControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/DeleteDataTypeFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/UpdateDataTypeFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/ReferencesDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/UpdateDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/FolderManagementControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/LanguageControllerBase.cs
src/Umbraco.Core/CompatibilitySuppressions.xml
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Services/DataTypeContainerService.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/IDataTypeContainerService.cs
src/Umbraco.Core/Services/IDataTypeService.cs
src/Umbraco.Core/Services/OperationStatus/DataTypeContainerOperationStatus.cs
src/Umbraco.Core/Services/OperationStatus/DataTypeOperationStatus.cs
tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/DataTypeContainerServiceTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/DataTypeServiceTests.cs

This PR aligns the data type API with the current standards for CRUD operations, including:
- async interface methods
- explicit create/update instead of generic save
- attempt pattern for operations
The data type container (folder) handling has been split into its own dedicated service, as this really has no place in the data type service. This in turn has an impact on the folder API base controller, which now has to support the current way of doing things. 
Unit tests have been updated to cover the new data type service operations as well as the data type container operations -which, as it turns out, currently aren't covered by any unit tests.
One of the constructors on the data type service has been obsoleted since V10, but has no indication of removal version in the obsolete message. …

Align the data type API

---

src/Umbraco.Core/Models/ContentEditing/Language.cs
src/Umbraco.Core/Models/DictionaryItem.cs
src/Umbraco.Core/Models/DictionaryItemExtensions.cs
src/Umbraco.Core/Models/DictionaryTranslation.cs
src/Umbraco.Core/Models/IDictionaryTranslation.cs
src/Umbraco.Core/Models/ILanguage.cs
src/Umbraco.Core/Models/Language.cs
tests/Umbraco.Tests.Common/Builders/LanguageBuilder.cs

This PR obsoletes all breakage introduced by refactoring language IDs in favor of language ISO codes for V13. 
See https://github.com/umbraco/Umbraco-CMS/pull/13751 for details.
This PR should **NOT** be merged before https://github.com/umbraco/Umbraco-CMS/pull/13751 is merged.

Obsolete language ID related properties and methods for V13

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorContent.spec.ts

Updated the ID of the locator in the test 'can set a minimum of required blocks in content with a block list editor' to match the correct ID.

Fixed a failing test for the BlockListEditor

---

src/Umbraco.Cms.Api.Content/Controllers/ByRouteContentApiController.cs
src/Umbraco.Cms.Api.Content/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Content/Services/StartNodeService.cs
src/Umbraco.Core/ContentApi/IStartNodeService.cs

- Adding a `start-node` header for the GET `/content/{url`;
- Its value will be considered only when `Umbraco:CMS:Global:HideTopLevelNodeFromPath` is set to `false`.
- This also helps resolve url collisions.
- Set up a "_Root_" and a "Child" document types;
- Create a "_Sports_" root content node;
- Create the following child content nodes:
- "_Tennis_";
- "_Dancing_".
- Create another root content node, called "_Competitions_";
- Create the following child content nodes:
- "_Tennis_";
- "_Dancing_".
- Pass "/tennis" to GET `/content/{url`;
- Verify that you get the details for the content node with that path.
- Set `Umbraco:CMS:Global:HideTopLevelNodeFromPath` to `false` in appsettings.json;
- Pass "/tennis" to GET `/content/{url` again;
- Verify that you get a **Not Found** response …

Content API: Add start-node header value to deal with url collisions

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js

Fixes #13705
1. Add check for `editorState.getCurrent()` to find the current editor (relevant in infinite editors), and throw a warning if an editor completely misses the current node context.
2. Disable drag&drop entirely if the property editor did not get a node through bindings or `editorState`
1. Add a Block Grid editor with example blocks
2. Add it to a page and add a media block
3. Verify that images can be dragged onto the media picker inside the dialog (infinite editor)

Fix for mediapicker drag&drop in infinite editing

---

src/Umbraco.Infrastructure/Persistence/Dtos/KeyValueDto.cs
src/Umbraco.Web.Common/Controllers/MaintenanceModeActionFilterAttribute.cs
src/Umbraco.Web.Common/Controllers/PublishedRequestFilterAttribute.cs
src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformerTests.cs

This PR changes the behaviour so the maintenance page is presented in cases where there are migrations in tables needed to build the published content cache.
This also means 404 pages cannot be shown when presenting the Maintenance page (because the  published content cache is required).
Use steps from https://github.com/umbraco/Umbraco-CMS/pull/13551 with the following modifications
- With the change that 404 is not available when the maintenance page should be showed (as that requires the content cache)
- Also try to add a new property on DataTypeDto and make a migration 
- This tests that the content cache is not used

Isolate maintenance page from published content cache

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbavatar.directive.js

One of our customers asked us if it was possible to remove special characters in the initials used in the umbavatar.directive.js.
Of course it is possible to rename the user to prevent special chars will shown but in this case users are created by using auto linking (Active Directory). It would be nice if they don't have to edit each user manually. 
Before: 
After:

Remove special characters in avatar

---

src/Umbraco.Core/Models/Membership/ReadOnlyUserGroup.cs
src/Umbraco.Core/Models/Membership/UserGroupExtensions.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Editors/UserEditorAuthorizationHelperTests.cs

This obsoletes the `ReadOnlyUserGroup` constructor broken by #13672

New backoffice: Obsolete ReadOnlyUserGroup constructor.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js

Fixes #13210, #13774
This aims to fix an issue where the user would be prompted to choose a media type in a dialog, but in the background, the files were already uploaded and assumed to be of the Image type.
Another fix included here is that some files would not be auto-detected correctly, e.g. SVG files were uploaded as images since that would be the default. The goal is now to let the server deduct what the best fitting media type is for a given file if the user was not prompted to choose one and if the dropzone directive was not instructed otherwise with a specific media type alias.
Lastly, I have added jsdocs to the functions in the dropzone directive to improve my understanding of what they do.
Note: At some point we should migrate the upload logic in the Dropzone directive to the …

V11: Fix for media library type dialog

---

src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj

Updated:
- `Microsoft.Data.Sqlite` from `7.0.1` to `7.0.2`
- `Microsoft.Extensions.FileProviders.Embedded` from `7.0.1` to `7.0.2`
- `Microsoft.Extensions.Identity.Core` from `7.0.1` to `7.0.2`
- `System.Security.Cryptography.Xml` from `7.0.0` to `7.0.1`
- `Examine` and `Examine.Core` from `3.0.1` to `3.1.0`
- `IPNetwork2` from `2.6.533` to `2.6.548`
- `MailKit` from `3.4.3` to `3.5.0`
- `Microsoft.Extensions.Identity.Stores` from `7.0.1` to `7.0.2`
- `K4os.Compression.LZ4` from `1.2.16` to `1.3.5`
- `Microsoft.AspNetCore.Mvc.NewtonsoftJson` from `7.0.1` to `7.0.2`
- `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` from `7.0.1` to `7.0.2`
Also updated these that is only relevant while developing Umbraco
- `Microsoft.EntityFrameworkCore.InMemory` from `7.0.1` to `7.0.2`
- …

Updated nuget dependencies

---

src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerSyntaxProvider.cs
src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs
src/Umbraco.Infrastructure/Migrations/MigrationBase_Extra.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_5_0/AddPrimaryKeyConstrainToContentVersionCleanupDtos.cs
src/Umbraco.Infrastructure/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs
src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs

Fixes comments from https://github.com/umbraco/Umbraco-CMS/pull/12684#discussion_r1095655597
- Move guarding TableExist clause up to prevent explosion of migration.
- Added PrimaryKeyExist to ISqlSyntaxProvider
- Added PrimaryKeyExist overrides for SqlServerSyntaxProvicer & SqliteSyntaxProvider
- Run and install umbraco
- Stop umbraco
- Add `To<AddPrimaryKeyConstrainToContentVersionCleanupDtos>("{67CF5353-82A4-4C08-AB7D-99EB0A49715E}");` to last line of UmbracoPlan.DefinePlan()
- Run umbraco and go to /install
- Set a breakpoint in `AddPrimaryKeyConstrainToContentVersionCleanupDtos` on line 16
- PrimaryKeyExists Should return true

V10: fix content version cleanup dto migration

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

* update ace-builds from 1.14.0 to 1.15.0
* update eslint from 8.32.0 to 8.33.0
* update jsdom from 21.0.0 to 21.1.0
* update nouislider from 15.6.1 to 15.7.0

v11: npm updates for february

---

src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/OpenApi/SchemaIdGenerator.cs

This PR adds "Model" as postfix for all models in the Swagger output. This is necessary because some models have unfortunate name clashes with core TypeScript/JavaScript classes (like `Document`).
Verify that the Swagger UI displats both request and return models with a "Model" postfix:

Add "Model" postfix for all models in the Swagger output

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbavatar.directive.js

In addition to https://github.com/umbraco/Umbraco-CMS/pull/13766
This PR updated the regex to remove special charachters as suggested by @ronaldbarendse https://github.com/umbraco/Umbraco-CMS/pull/13766#issuecomment-1419906960
The regex has Unicode mode enabled now.

Remove special characters in avatar [part 2]

---

src/Umbraco.Core/Services/NotificationService.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12194
As stated in #12194, notifications do not work predictably for multiple root nodes. This PR fixes it.
1. Setup a site with two (or more) root nodes and children under each root.
2. Sign up for publish notifications on specific children under each root.
3. Publish the children.
4. Verify that you have received notifications for each published child.
5. Sign up for publish notifications on each root.
6. Publish each root.
7. Verify that you have received notifications for each published root.
A great way of testing this is to use `SpecifiedPickupDirectory` delivery method for mails:
```
"Umbraco": {
"CMS": {
"Examine": {
"LuceneDirectoryFactory": "TempFileSystemDirectoryFactory"
}, …
```

Support notifications for multiple root nodes

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeIdentityOptions.cs
src/Umbraco.Web.Common/Security/ConfigureMemberIdentityOptions.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12985
The default lockout time for users and members is currently hardcoded to 30 days. This PR makes those lockout times configurable by introducing two new configuration options under `Security` - one for members and one for users:
The default values for these configuration options remain as 30 days (43200 minutes).
1. Delete `appsettings-schema.json` under `Umbraco.Cms` if it exists (it is a built-time auto generated file that will only be created if it does not exist).
2. Build the solution. The schema file should be generated by the build.
3. Verify that `appsettings.json` supports auto completion for the two new settings:
4. Configure the settings in `appsettings.json`
5. Restart …

Make the default lockout time configurable for users and members

---

src/Umbraco.Core/Models/PublishedContent/Fallback.cs
src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedContentLanguageVariantTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8349.
This includes most changes done in PR https://github.com/umbraco/Umbraco-CMS/pull/8350 that targeted v8.
This PR adds a new `Fallback.DefaultLanguage` value to get the content/property value from the default language, instead of the configured language fallback chain.
Previously, you had to either configure the fallback language to the default one and/or use very verbose, nested fallback chains:
```cshtml
<h1>@Model.Value("title", fallback: Fallback.To(Fallback.DefaultValue), defaultValue: Model.Value("title", culture: UmbracoContext?.Domains?.DefaultCulture, fallback: Fallback.ToDefaultValue, defaultValue: Model.Name))</h1>
@Model.Value("text", fallback: …
```

Add DefaultLanguage fallback policy for published values

---

src/Umbraco.Core/Models/IDomain.cs
src/Umbraco.Core/Models/UmbracoDomain.cs
src/Umbraco.Core/Routing/Domain.cs
src/Umbraco.Core/Routing/DomainUtilities.cs
src/Umbraco.Core/Services/DomainService.cs
src/Umbraco.Core/Services/IDomainService.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_5_0/AddDomainSortOrder.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_11_3_0/AddDomainSortOrder.cs
src/Umbraco.Infrastructure/Persistence/Dtos/DomainDto.cs
src/Umbraco.Infrastructure/Persistence/Factories/DomainFactory.cs
src/Umbraco.Infrastructure/Persistence/Mappers/DomainMapper.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DomainRepository.cs
src/Umbraco.PublishedCache.NuCache/DomainCache.cs
src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttongroup.directive.js
src/Umbraco.Web.UI.Client/src/less/button-groups.less
src/Umbraco.Web.UI.Client/src/less/forms.less
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
src/Umbraco.Web.UI.Client/src/views/content/assigndomain.html
src/Umbraco.Web.UI.Client/src/views/content/content.assigndomain.controller.js
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/SiteDomainMapperTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UrlsProviderWithDomainsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Web/Routing/PublishedRequestBuilderTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8299.
This includes most changes done in PR https://github.com/umbraco/Umbraco-CMS/pull/8316 that targeted v8.
As mentioned in the above linked issue (and v8 PR), ordering of the node domains is important, since the first one will be treated as the primary domain (when generating absolute URLs and none match the current URL) and this order can also be used to automatically generate a language selector on the front-end.
This PR includes the following changes:
- Adding the `SortOrder` property to the service level models (`Umbraco.Cms.Core.Models.IDomain` and `Umbraco.Cms.Core.Models.UmbracoDomain`), database model (`Umbraco.Cms.Infrastructure.Persistence.Dtos.DomainDto`) and …

Sort domains (Culture and Hostnames)

---

src/Umbraco.Infrastructure/Runtime/RuntimeModeValidators/JITOptimizerValidator.cs

When setting the Runtime mode to `Production`, the project should be built/published in Release mode, and the `JITOptimizerValidator` enforces this.  
However, if you don't build/publish in release mode, then you get the following exception rmessage which doesn't help you understand how to fix the problem:
```
The JIT/runtime optimizer of the entry assembly needs to be enabled in production mode.
```
I recently came across this error message when I didn't realise that my my build server was publishing the using "Debug" configuration.  It took me a couple of hours to figure out that this was the problem, so I figured adding a bit of info to the exception would have helped me and might help others!

Improvement to JITOptimizerValidator exception message.

---

src/Umbraco.Cms.Api.Content/Controllers/ContentApiControllerBase.cs
src/Umbraco.Cms.Api.Content/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Content/Filters/LocalizeFromAcceptLanguageHeaderAttribute.cs
src/Umbraco.Cms.Api.Content/Json/ContentApiJsonTypeResolver.cs

Adds support for passing in an Accept-Language header with a culture code to the Content API.
I have also moved the `ContentApiJsonTypeResolver` to the `Json` namespace where it rightfully belongs - not sure why it was placed under `Filters` to begin with 😆 
At the time of writing we seem to have an issue fetching culture variant content by path, so for now this can only be tested when fetching culture variant content by key:

Content API: Support Accept-Language header

---

build/azure-pipelines.yml

Removed path so we can find the correct template

Removed path so we can generate templates

---

src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/13837
- When a member was returned from `IMemberManager.GetCurrentMemberAsync()`, its `TwoFactorEnabled` property wasn't set.
- Set up 2FA for members (_PR https://github.com/umbraco/Umbraco-CMS/pull/13369 describes in details in the Test section how to_);
- Make sure a member has 2FA enabled;
- Use the following code to verify that `TwoFactorEnabled` property is set correctly (_try enabling and disabling 2FA from the backoffice_):
```c#
var member = await _memberManager.GetCurrentMemberAsync();
bool twoFactorEnabled = member.TwoFactorEnabled;
```

Set TwoFactorEnabled property on MemberIdentityUser

---

src/Umbraco.Core/PropertyEditors/ValueConverters/ContentPickerValueConverter.cs

Changed access modifier of `ContentPickerValueConverter` from `internal` to `public`.
This Value Converter was the only one defined as internal while all others are public.
It was confirmed as bug
Fixes issue #13863 3858

Changed modifier for ContentPickerValueConverter

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs

- Adds nice obsolete messages, as these properties are no longer used, and can trick people into thinking they still work.

Add obsolete messages to no longer used properties

---

src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml

Translates Umbraco backoffice into Bosnian language, so it can be used by people who doesn't understand English.
This language is fully understandable in countries: Bosnia and Herzegovina, Croatia, Serbia, Montenegro, and partially understandable in Slovenia, Albania and Macedonia. I also can add Croatian and Serbian language but these three languages are 99% same.
Additionally, I fixed a few errors in English translation.
This language can be tested by changing language to Bosnian on user account page.
Screenshots:

Add Bosnian language

---

src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ByIdTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/DescendantsTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ItemsTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/Mapping/TrackedReferences/TrackedReferenceViewModelsMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/TrackedReferences/RelationItemViewModel.cs
src/Umbraco.Core/Models/RelationItemModel.cs
src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs
src/Umbraco.Core/Services/ITrackedReferencesService.cs
src/Umbraco.Core/Services/TrackedReferencesService.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs
src/Umbraco.New.Cms.Infrastructure/Persistence/Mappers/RelationModelMapDefinition.cs

Updates the management api endpoints to use keys instead of IDs
- /umbraco/management/api/v1/tracked-reference/{key}
- This is what is used on the content-info tab. This should shown all using this item
-/umbraco/management/api/v1/tracked-reference/descendants/{parentKey}
- This is used when deleting/unpublishing an item.. Should find descendants that have references.
-/umbraco/management/api/v1/tracked-reference/item
- This is used when deleting/unpublishing many items. Should return those of them that have references. (Always a subset of the inputted)

Use keys for tracked references

---

src/Umbraco.Core/Persistence/Repositories/IUserRepository.cs
src/Umbraco.Core/Services/IUserService.cs
src/Umbraco.Core/Services/UserService.cs
src/Umbraco.Core/Services/UserServiceExtensions.cs
src/Umbraco.Infrastructure/Extensions/GuidExtensions.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddGuidsToUserGroups.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddGuidsToUsers.cs
src/Umbraco.Infrastructure/Persistence/Dtos/UserDto.cs
src/Umbraco.Infrastructure/Persistence/Factories/UserFactory.cs
src/Umbraco.Infrastructure/Persistence/Mappers/UserMapper.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
src/Umbraco.Infrastructure/Security/BackOfficeIdentityUser.cs
src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
src/Umbraco.Infrastructure/Security/MemberUserStore.cs
src/Umbraco.Infrastructure/Security/UmbracoUserStore.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/NotificationsRepositoryTest.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs

Adds an actual GUID as a key to users instead of the faked one. 
One of the problems implementing this, is that by adding a new column, you were unable to log in to authorize the upgrade, since we'd error out because we expected the Key column to be there. 
To get around this I've added a new `GetForUpgradeBy*` this will allow you to request a user by id, email or username, as this is needed by identity, these new methods will only return as user while in upgrade, the goal is to have a method that fetches the bare minimum to authorize the upgrade. 
Another issue is that the user already had a fake key, that was used to resolve external logins and 2fa providers, to facility this transition to proper keys I've made a `ResolveEntityIdFromIdentityId` which will resolve the umbraco Entity …

V13: Add Guids to Users

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13749
When selecting an index and then navigating to registered searchers, it was using the previous selected index as searcher name, instead of the actually searcher.

Reset selected index/searcher

---

src/Umbraco.Infrastructure/Macros/MacroTagParser.cs
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/less/rte-content.less
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Macros/MacroParserTests.cs

Let it be possible to have macros inlined (in span) in Rich Text Editor so you can have variables in the middle of a text that can be updated in one content node, instead of updating it on hundreds of different places.
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/13564
Currently it's not possible to have macro in the middle of a sentence/paragraph in the Rich Text Editor, since tinymce splits it up to three paragraphs, as the Macro placeholder in the markup is a div, which is not valid inside a paragraph.
This PR adds the possibility to have the Macro in the middle of a sentence.
The feature is fully backwards compatible, as the behaviour is opt in.
- Create a document type, f.ex. _Document Type A_ and add a property with Rich …

Let it be possible to have macros inlined (in span) in Rich Text Editor

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs

- new up `UserPasswordConfigurationSettings`
- new up `MemberPasswordConfigurationSettings`
- Create a notification handler:
```
using Microsoft.Extensions.Options;
using Umbraco.Cms.Core.Configuration.Models;
public class MyNotificationHandler : INotificationHandler<ContentSavedNotification>
{
private readonly IOptions<SecuritySettings> _options;
private readonly IOptions<MemberPasswordConfigurationSettings> _memberPassword;
public MyNotificationHandler(IOptions<SecuritySettings> options, IOptions<MemberPasswordConfigurationSettings> memberPassword)
{
_options = options;
_memberPassword = memberPassword;
}
public void Handle(ContentSavedNotification …
```

New up the SecuritySettings

---

src/Umbraco.Core/Models/ContentEditing/PublishContent.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js

Link to issue: https://github.com/umbraco/Umbraco-CMS/issues/13755
Modified `PostPublishById` to handle content that is culture variant. Added a new model for the endpoint and modified the JavaScript function that calls said endpoint.
I've tested these changes by creating a new doctype with list view enabled. I've allowed another doctype as it's child. Both doctypes are culture variant. After these changes you can publish one culture from the list view and the other culture will remain unpublished. **I'd like someone else to test these changes as well.** There were a few occasions where it looked like it wasn't working but I wasn't really able to replicate that. 
See gif below for the result:

Listview batch publishing on multi language site, publishes all variants #13755 - Fix

---

src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs

Fixes #13662
In `Umbraco.Extensions.HtmlHelperRenderExtensions.BeginUmbracoForm()`, parameter `additionalRouteVals` was not consistently nullable. Here it is made nullable across the various BeginUmbracoForm() versions.

Make additionalRouteVals nullable in HtmlHelperRenderExtensions.BeginUmbracoForm() - Fixes #13662

---

src/Umbraco.Core/Events/MoveEventInfo.cs
src/Umbraco.Core/Events/MoveEventInfoBase.cs
src/Umbraco.Core/Events/MoveToRecycleBinEventInfo.cs
src/Umbraco.Core/Notifications/ContentCopiedNotification.cs
src/Umbraco.Core/Notifications/ContentCopyingNotification.cs
src/Umbraco.Core/Notifications/ContentMovedToRecycleBinNotification.cs
src/Umbraco.Core/Notifications/ContentMovingToRecycleBinNotification.cs
src/Umbraco.Core/Notifications/CopiedNotification.cs
src/Umbraco.Core/Notifications/CopyingNotification.cs
src/Umbraco.Core/Notifications/MediaMovedToRecycleBinNotification.cs
src/Umbraco.Core/Notifications/MediaMovingToRecycleBinNotification.cs
src/Umbraco.Core/Notifications/MovedToRecycleBinNotification.cs
src/Umbraco.Core/Notifications/MovingToRecycleBinNotification.cs
src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/DictionaryItemService.cs
src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Infrastructure/Events/RelateOnTrashNotificationHandler.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DataTypeRepository.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Events/MoveEventInfoTests.cs

- Added MoveEventInfoBase
- Added MovedToRecycleBinInfo instead, as we don't need to know the parent id/key of the recycle bin, we already know by the notification that it is moving there.
- Added parent key to move info so its passed out in notifications.
- Added FIXME's where it doesn't make sense to use the new ctor of MoveEventInfo, as those methods will be refactored anyways.
- Test the different Notifications and ensure they have parentkeys (Copy notifications and MoveToRecycleBin)
- Lets do an example of ContentTypeMovedNotification:
- Create a document type and an empty folder in the doctype tree
- Stop Umbraco and implement the respective NotificationHandler
```
namespace …
```

V13: Add parentkey to notifications

---

src/Umbraco.Web.Common/ModelsBuilder/InMemoryAuto/CompilationOptionsProvider.cs

Updated to use latest C# version when building runtime views. Seems to be required when using dotnet 8 preview 1

Use latest c# language version instead of csharp 8 in runtime views

---

src/Umbraco.Core/Extensions/PasswordConfigurationExtensions.cs

Change the return value of this extension method to return either 0 or 1. Returning 2 forces all passwords to contain at least 2 special characters when using this extension in code to check if a password meets requirements
Image of  Microsoft.AspNetCore.Identity.PasswordOptions, does not default to 2 special characters (it's not configurable)

Change GetMinNonAlphaNumericChars() to return 1

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

Undefined error when inserting an empty link in the RTE editor
This fixes: #13860

Fix TinyMCE Link Picker - empty link throws JS error #13860

---

src/Umbraco.Infrastructure/Logging/Viewer/SerilogLogViewerSourceBase.cs

- There was a bug where when you requested x amount of logs, the total would always be the same as x
- Scenario:
- Total 1000 logs
- I request 100
- The total would also be 100
- Test the {{baseUrl}}/umbraco/management/api/v1/log-viewer/log?skip=0&take=1 endpoint with a GET request
- Assert that the total > take

V13: fix logviewer total

---

src/Umbraco.Cms.Api.Content/Controllers/ByIdContentApiController.cs
src/Umbraco.Cms.Api.Content/Controllers/ByRouteContentApiController.cs
src/Umbraco.Cms.Api.Content/Routing/VersionedContentApiRouteAttribute.cs

- renamed the ContentApiRoute to `/delivery/api/`;
- added `/item` for the item-based enpoints.

Delivery API: Fix API routes

---

src/Umbraco.Web.Common/Controllers/PublishedRequestFilterAttribute.cs

This fixes #13907.
The problem was that when using the `Error404Collection ` in `appsettings` the correct not found page would be shown. but the request status would be 200. 
Looking at it, it's because the status is set by our `PublishedRequestFilterAttribute` using the route values, however since the result has been set by the `ContentFinderByConfigured404` meaning the route values are never fetched, and therefore the status is never set. 
This was added as a part of #13767 since the maintenance page no longer returns umbraco content (so there's no route values).
I've fixed this by explicitly checking if the result is a `MaintenanceResult` and only then do we skip fetching the route values.
Set up a custom 404:
```json
"Error404Collection": [
{
"Culture": "default",
"ContentKey": …
```

V10: Fix missing 404 status

---

src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs

This fixes #13890.
The issue was that in our searcher we replaced hyphens and underscores with an empty string, this mean that when you searched `some-name` this got turned into `somename` but it's actually indexed as `some` and `name`, so this remedies that, your query will not be `some name` which works. 
Upload an image to the section with a hyphen in the name I.E. `my-image`
Try and search for the image, including the hyphen: `my-image`, before its PR it wouldn't show up, but now it will.

Fix issue with searching internal index with hypen

---

src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js

- This PR enables "Detailed" telemetry by default in the installer, instead of Basic.
- Run the installer
- Assert that the chosen telemetry level is "Detailed" by default

Set detailed telemetry as default in installer

---

src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs

If there's an existing issue for this PR then this fixes #13515 
Adding a null check for the modeltype right after the PropertyValueConverter has been called to check if a type has been set.
That the type returned is null should never happen when using default PropertyValueConverters but if you are using a custom PropertyValueConverter there could be a chance that null is returned.
Sadly we only have the Id of the datatype available, but thats still better than nothing.

Check if PublishedPropertyType modelType is null

---

src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Website/Routing/SurfaceControllerMatcherPolicy.cs

Fixed issue mentioned in #13836 
Now surface controller requests always has higher priority than other. So if this is both a surface controller request and a virtual page request, it will execute the surface controller.
This is done using a `SurfaceControllerMatcherPolicy` that will invalidate all other endpoints than the surface controller, if a surface controller matched the request (This should only ever happen, if the magic query string is added)
There are a couple of usecases to test out. Please follow guide here: https://github.com/umbraco/Umbraco-CMS/pull/13919.
We have to test the combinations:
| - | Regular page ('/') | Hijacked page ('/hijacked') | Virtual page ('/demo') with no http verbs | Virtual page ('/demo') with HttpGet |  Virtual page ('/demo') with HttpPost |  Virtual …

Prioritise surface controller requests highest

---

src/Umbraco.Core/Constants-HealthChecks.cs
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/HealthChecks/Checks/Security/BaseHttpHeaderCheck.cs
src/Umbraco.Core/HealthChecks/Checks/Security/XssProtectionCheck.cs

Resolves# #13341
This reverses the health check to warn if it does exist with a link to the Mozilla website which explains why it should not exist
I have also changed the readmore button to be nullable (it's not always required) and added a bool to reverse the check in the base class

Reversed X-XSS

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

Fixes #13833 
Assigns the config label as the first instance, if this is not set (left empty) then uses the contenttype name of the block. If that fails, which is unlikely, will default to an empty string to prevent failure elsewhere.

update block label not assigning fixes: #13833

---

src/Umbraco.Web.Website/Controllers/UmbLoginStatusController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13925
It seems we're not extracting the redirect URL from the route values when handling member logout in the default controllers.
1. Create a member.
2. Create a "Login" and a "Login Status" macro, and add them to an RTE on any page.
3. Modify the "Login Status" macro template to have a different redirect URL than the page it resides on.
4. Perform login and subsequent logout with the created member (logout is handled by the "Login Status" macro).
5. Verify that you're redirected to the assigned redirect URL upon successful logout.

Extract redirect URL from route values for member logout

---

src/Umbraco.Core/Configuration/Models/ContentSettings.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/ContentControllerTests.cs

Adds a setting to disable the domain warnings. 
1. Add a couple of languages
2. Create a document type that varies by language
3. Try publishing a couple of languages without having set domains up 
4. Ensure that the warnings are shown if the setting is enabled, and that they aren't when it's disabled.

Add setting to disable domain warnings

---

src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs

Client validation is broken without this if there are multiple forms with the same field names on a page.
Fixes #13913
Fixes ViewContext.FormContext not being set by Html.BeginUmbracoForm which is normally set in Html.BeginForm

Fix ViewContext.FormContext not being set during BeginUmbracoForm

---

src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
src/Umbraco.Web/Editors/ImagesController.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12200 by adding an list of allowed media hosts in content settings.

Add allow list for absolute urls

---

src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less

Existing issue  [#13538](https://github.com/umbraco/Umbraco-CMS/issues/13538)
Upon clicking a blocklist item the editor alignment does not properly align to the right and can be seen to jump about towards the left. 
This is jumping bacause the editor class has ```transition: transform 400ms ease-in-out``` and it also runs its inputs within the editor through an auto focus ```$timeout``` function immediately. This focuses the input before its in the viewport causing the editor to jump into view and causes an issue with the left positioning.
There are few ways to fix this but in its simpliest form is setting an editor within the  ```umb-editors``` to ```position: fixed```
Tested by checking various editors in many different sequences and tested on Chrome and Firefox all seems to be working …

Fix editor alignment issues

---

src/Umbraco.Web.UI.Client/test/config/karma.conf.js

From Node.js 17 DNS resolution is different, causing the Karma server to listen to the wrong address by default. This breaks Umbraco's gulp test tasks and default gulp build.
Telling the karma server to listen on `::` fixes the problem - as per [the issue on the Karma repo](https://github.com/karma-runner/karma/issues/3730). This change is backwards compatible down to (at least) Node.js v14 so doesn't change version requirements for Umbraco 🎉
To test: run `gulp build` from `/src/Umbraco.Web.UI.Client` on any version from Node.js from 14+
I've tested on 14, 16, 18 and 19
Once this is merged, it would be worth checking if HQ can bump the Node.js version in the pipelines to latest LTS.

Use correct listenAddress for Karma on node 18+

---

src/Umbraco.Core/Compose/AuditEventsComponent.cs
src/Umbraco.Core/Security/MembershipProviderBase.cs

Since U 8.16 we struggle with the problem of saving members' information.
We modify members' properties in Hangfire jobs and we always has problems with database locks.
That was because this issue:
https://github.com/umbraco/Umbraco-CMS/issues/8090
It was marked as resolved but the wrong code is still here.
So I just add a null-conditional operator to avoid a null reference exception.
Seems the code is self-explainable.
If HttpContext.Current == null we still have null reference in 
httpContext variable.
Also, i fixed another part of the code, by adding .? to the same expression.
The way how we achieve this:
We had hangfire jobs which are executed by schedule.
When nobody is logged in HttpContext.Current will be null.
Probably it will be null even if we made some console app to test this.

Complete fix for https://github.com/umbraco/Umbraco-CMS/issues/8090 issue.

---

src/Umbraco.Core/Constants-Security.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddGuidsToUsers.cs

- Added new Super user key constant
- Update existing super usey key with constant
- Install umbraco 11/12
- Checkout this branch
- Run the migration
- Assert the user now has key `1E70F841-C261-413B-ABB2-2D68CDB96094` in the umbracoUser table

V13: Add default superuser key

---

.github/BUILD.md

Building the current version of the back office is only supported on Node v16 and earlier so have updated the docs to reflect that.

Updated the version requirements for running the current back office

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html

This issue resolves https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/15
This PR adds skip links to the header to allow users to skip to the menu and main content.
To test the change tab through the website and select each skip link. "Skip to menu" will skip the user to the first navigation link and "Skip to content" the user to the first visible focusable element in the main content.  On pages where there is a left column, this will focus on the first element in the left column. On pages where there is no left column (like Packages), it will focus on the first focusable element in the main column.
I had to use buttons instead of links (you would normally use links for skip links that anchor to ids), because the angular routing in Umbraco uses hashes and these were being …

Add skip links to header

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js

We ran into this issue while playing with a NotificationHandler to filter allowed element types.
When `vm.availableBlockTypes` doesn't contain an element type that an area specifically references, the old code would just add an `undefined` to the `allowedElementTypes`. This causes the "add content" overlay to not open anymore.

Fixed issue where Block Grid elements in areas cannot be properly filtered

---

src/Umbraco.Core/Extensions/PublishedElementExtensions.cs
src/Umbraco.Core/Models/PublishedContent/IPublishedValueFallback.cs
src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs
src/Umbraco.Infrastructure/ModelsBuilder/PublishedElementExtensions.cs

This PR fixes this issue: https://github.com/umbraco/Umbraco-CMS/issues/13865.
Added a change in ```Value<T>``` so potential discrepancys between the culture of VariationContext and culture parameter passed to the ```Value<T>``` method, is corrected. This fixes problem when i.e. picking correct localized href for link in Rich text link Editor.
Unit test is not provided, but I have been running all existing tests and they passed. But if you want me to provide som kind of test I could update this PR.
This might not be the best way to fix this issue. I'm gladly replying to any questions on why I did it like this. But please provide feedback 😊

Fixing issue #13865 (i.e. Rich text link picker not resolving correct variant when using .ValueFor()).

---

src/Umbraco.Core/Models/PropertyGroup.cs
src/Umbraco.Core/Models/PropertyTypeCollection.cs

Also fix circular reference on PropertyTypeCollection
If there's an existing issue for this PR then this fixes #12945 
This change should fix equality checks on the PropertyGroup model. The check was insufficient, causing changes in the backoffice to get lost on occasion. While debugging, I also stumbled upon what seemed like a circular reference (visual studio crashed while attempting to read the property), so I fixed that as well.
Steps to test:
- Create a document type with a property group "Content" and a property "My property" and Save
- Refresh the browser and notice that the property has properly saved
- Now delete the property group and add a new one with the name "Content" and a property "My other property" and save
- Refresh the browser and notice that the property has properly …

Fix equality check on property group

---

tests/Directory.Build.props
tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj

Reverse the EnablePackageValidation in tests, so it is explicity opt-in. Otherwise the generated csproj file in Benchmarks will always fail with an error like
```
BenchmarkDotNet.Autogenerated.csproj : error NU1101: Unable to find package {GUID}. No packages exist with this id in source(s): ...
```
- You should be able to run benchmark tests without having to uncomment package validation.

Do not run package validation in benchmark tests
