umbraco/Umbraco-CMS

build/azure-pipelines.yml

This fixes the current build error for v13 backoffice by pulling out the jobs from msbuild (just like the current backoffice is being built) and increases the max allowed heap size for NodeJS.

V13: build new backoffice on Azure

---

Directory.Build.props
src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/Group/AllHealthCheckGroupController.cs
src/Umbraco.Cms.Api.Management/Controllers/LogViewer/AllLogViewerController.cs
src/Umbraco.Cms.Api.Management/Controllers/LogViewer/AllMessageTemplateLogViewerController.cs
src/Umbraco.Cms.Api.Management/Controllers/LogViewer/AllSinkLevelLogViewerController.cs
src/Umbraco.Cms.Api.Management/Controllers/LogViewer/SavedSearch/AllSavedSearchLogViewerController.cs
src/Umbraco.Cms.Api.Management/Controllers/Package/AllMigrationStatusPackageController.cs
src/Umbraco.Cms.Api.Management/Controllers/Package/Created/AllCreatedPackageController.cs
src/Umbraco.Cms.Api.Management/Mapping/HealthCheck/HealthCheckViewModelsMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/LogViewer/LogViewerViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Package/PackageViewModelMapDefinition.cs
src/Umbraco.Core/Services/ILogViewerService.cs
src/Umbraco.Core/Services/IPackagingService.cs
src/Umbraco.Infrastructure/Services/Implement/LogViewerService.cs
src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs

- The total number of items were wrong in controllers related to _health checks_, _log viewer_ and _packages_, due to doing the skip and take operations before constructing a `PagedViewModel`;
- This PR fixes those cases.
- Check that modifying the `skip` and `take` values in the following endpoints still returns the right amount of results based on the values provided & now the total number of items is correct:
- **Health Check**
- `/umbraco/management/api/v1/health-check-group`
- **Log Viewer**
- `/umbraco/management/api/v1/log-viewer/level`
- `/umbraco/management/api/v1/log-viewer/log`
- `/umbraco/management/api/v1/log-viewer/message-template`
- `/umbraco/management/api/v1/log-viewer/saved-search`
- **Package**
- `/umbraco/management/api/v1/package/created`
- …

New Backoffice: Fix total number of items (health checks, log viewer, packages)

---

src/Umbraco.Core/Services/MediaService.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/12748 (after a save of the media item)
Tested with this piece of code:
```
public class TestCode : INotificationHandler<MediaMovedToRecycleBinNotification>
{
public void Handle(MediaMovedToRecycleBinNotification notification)
{
foreach (var media in notification.MoveInfoCollection)
{
var test = media.Entity.WriterId;
}
}
}
public class TestComposer : IComposer
{
{
builder.AddNotificationHandler<MediaMovedToRecycleBinNotification, TestCode>();
}
}
```
I took a look at how the ContentService did this and copied the piece of code from there.

Fix #12748: Make sure to set `writerId` for `MediaService.Thrashed` event

---

src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html

https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/27
Moved the role and aria-selected from the buttons to the child listitem elements to conform with the expectation that tablist child elements have a role of tab. This change will apply to all of the section tab navigation items.

Fixes: listitem: `<li>` elements must be contained in a `<ul>` or `<ol>`

---

src/Umbraco.Cms.Api.Management/Controllers/Document/NotificationsController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateNotificationsController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/DocumentBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/DocumentNotificationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IDocumentNotificationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentNotificationsResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/UpdateDocumentNotificationsRequestModel.cs

This PR adds an API for content notifications.
Content notifications are tied to a backoffice user. Therefore this PR cannot be tested without active authentication. Unfortunately, backoffice auth is not enabled for the API at this time, so in order to test this PR, you have to add it explicitly.
Add the following to the new controllers `NotificationsController` and `UpdateNotificationsController`:
```csharp
[Authorize(Policy = $"New{AuthorizationPolicies.SectionAccessForMediaTree}")]
```
With this you can use the built-in authorization flow in Swagger or Postman to authorize against the management API and subsequently test the notifications API as an authorized backoffice user.
The changes in this PR are fully compatible with the current backoffice, so any changes made while testing the …

Add content notifications API

---

src/Umbraco.Core/Models/PublishedContent/IPublishedPropertyType.cs
src/Umbraco.Core/Models/PublishedContent/PublishedPropertyBase.cs
src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs
src/Umbraco.Core/PropertyEditors/ContentApi/IContentApiPropertyValueConverter.cs
src/Umbraco.Core/PropertyEditors/TextStringValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/ContentPickerValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/MemberGroupPickerValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/MemberPickerValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/MultiNodeTreePickerValueConverter.cs
src/Umbraco.Core/PublishedCache/PublishedElementPropertyBase.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MarkdownEditorValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentSingleValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
src/Umbraco.PublishedCache.NuCache/Property.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/ContentApi/CacheTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/CacheTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/ContentApiTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/NestedContentValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/OutputExpansionStrategyTests.cs

Adds dedicated property cache levels for content API value converters, so they can utilize the lesser need for context awareness when rendering property data.
Peer reviewed 👍

Dedicated property cache level for Content API

---

src/Umbraco.Cms.Persistence.SqlServer/Constants.cs
src/Umbraco.Cms.Persistence.SqlServer/Services/SqlAzureDatabaseProviderMetadata.cs
src/Umbraco.Cms.Persistence.SqlServer/Services/SqlLocalDbDatabaseProviderMetadata.cs
src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerDatabaseProviderMetadata.cs
src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDatabaseProviderMetadata.cs
src/Umbraco.Infrastructure/Install/InstallHelper.cs
src/Umbraco.Infrastructure/Persistence/DatabaseProviderMetadataExtensions.cs
src/Umbraco.Infrastructure/Persistence/IDatabaseProviderMetadata.cs
src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Persistence.SqlServer/SqAzureDatabaseProviderMetadataTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Persistence.SqlServer/SqlLocalDbDatabaseProviderMetadataTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Persistence.SqlServer/SqlServerDatabaseProviderMetadataTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Persistence.Sqlite/SqliteDatabaseProviderMetadataTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.New.Cms.Infrastructure/Factories/DatabaseSettingsFactoryTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj

Fixes issue where some connections strings was determined as  we could create the database while we cannot. 
This can happen if you have LocalDB available but uses a sql-server (or azure)connection string, due to the fact we just used the providername - which is the same for all three databases.
The reason this failed before was because LocalDB was set first in DI.
- Specify a non-existing sqlserver or azure connectionstring, and ensure this ends in a boot failed state
- Specify a non-existing localDb connecitonstring, and ensure this ends in install state

Determine correct if we can create a database with current connectionstring

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TagRepository.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TagRepositoryTest.cs

If there's an existing issue for this PR then this fixes #13981 
I've fixed the case-sensitivity issues with tags in SQLite by using LIKE instead of = when querying and joining tags.
This could be fixed through collations but would require either database-specific SQL or database-specific schema changes. I liked this way because it works everywhere and doesn't need large changes in the database setup.
To test:
- Create an Umbraco site and add a content template with variants enabled and a tag property editor.
- Create one page with tag "Umbraco" and another with tag "umbraco" instead.
- Both pages should save and publish.
- Test SQLite and SQL Server to be sure.
I have also added an integration test, though this only tests the in-memory SQLite database.

Case-insensitive tag names with SQLite provider

---

src/Umbraco.Cms.Api.Management/Controllers/Tag/ByQueryTagController.cs
src/Umbraco.Cms.Api.Management/Controllers/Tag/TagControllerBase.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/TagBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
src/Umbraco.Cms.Api.Management/Mapping/Tag/TagResponseModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tag/TagResponseModel.cs
src/Umbraco.Core/Services/ITagService.cs
src/Umbraco.Core/Services/TagService.cs

- Added TagController
- Added ByQuery endpoint
You cannot create tags in the old backoffice anymore due to model changes.
- Create a document type with allow as root
- Create an empty content
- Stop umbraco
- Implement the sample code
- Run umbraco
- Now you should be able to call the new endpoint via swagger, and get some data back 👍 
```
using Umbraco.Cms.Core.Persistence.Repositories;
using Umbraco.Cms.Infrastructure.Scoping;
{
public void Compose(IUmbracoBuilder builder) => builder.AddNotificationHandler<UmbracoApplicationStartedNotification, MyNotiHandler>();
}
public class MyNotiHandler …
```

New backoffice: Tag controller

---

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/textstringlimited.html

[Reported Issue](https://github.com/umbraco/Umbraco-CMS/issues/14063) #14063 
- Resolved by changing the `Max` to 512

fix for the char limit(512) for textbox datatype

---

src/Umbraco.Cms.Api.Content/Controllers/QueryContentApiController.cs
src/Umbraco.Cms.Api.Content/Services/ApiQueryService.cs
src/Umbraco.Core/Configuration/Models/ContentApiSettings.cs
src/Umbraco.Core/ContentApi/IApiQueryService.cs
src/Umbraco.Core/ContentApi/NoopApiQueryService.cs

- Paginating the output from the query endpoint.
- Apply different `skip` and `take` values to `https://localhost:44331/umbraco/delivery/api/v1/content` endpoint and verify the number of items changes in the output;
- Use different combinations of query parameters - _ex: use `skip` and `take` with `sort`_ - and check that the response is correct.

Delivery API: Adding pagination to query endpoint

---

src/Umbraco.Core/Services/ContentEditingService.cs
src/Umbraco.Core/Services/DataTypeContainerService.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/DictionaryItemService.cs
src/Umbraco.Core/Services/FileService.cs
src/Umbraco.Core/Services/IUserIdKeyResolver.cs
src/Umbraco.Core/Services/LanguageService.cs
src/Umbraco.Core/Services/LocalizationService.cs
src/Umbraco.Core/Services/MediaEditingService.cs
src/Umbraco.Core/Services/RelationService.cs
src/Umbraco.Core/Services/TemplateService.cs
src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/DataTypeContainerServiceTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/LocalizationServiceTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/UserIdKeyResolverTests.cs

Simple refactor, that throws instead of returning null from IUserIdKeyResolver if id/key not found

Throw from IUserIdKeyResolver if id/key not found. 

---

src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less

[When a Block List Editor is the last property on a tab, it's components properties have little to no spacing.](https://github.com/umbraco/Umbraco-CMS/issues/12388)
If there's an existing issue for this PR then this fixes #12388. 
- When the Block List is the last property editor on a tab, and using inline editing, the margin between the properties disappears. There's also a smidge of additional margin at the bottom that could be removed.
- Minimal changes to LESS were made to address this issue.
- Please review the backoffice editing experience thoroughly.

Addresses Issue #12388: When a Block List Editor is the last property on a tab, it's components properties have little to no spacing.

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridblock.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridroot.component.js

1. Create CSS-file in `/wwwroot/block-styles.css`
2. Create a new Document Type (Element Type) called "Test Block", add a textbox-property called "Heading"
3. Create a new Data Type called "Block Grid with Styles", add a block using the content type from step 2. Configure it to use the `block-style.css` file as "Custom styleheet". 
4. Add a new Document type allowed at root and place the `Block Grid with Styles´-data type to the new document type.
5. Create a new content node of the new document type and add a `Test Block` to the Block Grid-editor.
Notice that the request to /wwwroot/block-styles.css now has a cache buster. Cache buster has been added to:
* Custom stylesheet on block-level
* Default stylesheet for the whole Block …

#14016 Fixed, added cache buster to Block Grid Editor stylesheets

---

src/Umbraco.Web.UI.Client/src/less/pages/login.less

Bootstrap Social doesn't work that well with the embedded svg icons in Umbraco, so I've added a little padding to make it look nicer.
To test, add an external login provider and verify that there is padding around the icon. Should look like this:
before:
after:

Adds padding to the icon in btn-social

---

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
src/Umbraco.Core/Constants-Security.cs
src/Umbraco.New.Cms.Core/Models/Configuration/NewBackOfficeSettings.cs
src/Umbraco.Web.UI.New/BackOfficeLoginController.cs
src/Umbraco.Web.UI.New/umbraco/UmbracoLogin/Index.cshtml

This introduces a dedicated cookie setup for the new backoffice, which is necessary for the old and new backoffice to be able to co-exist.
This is a temporary solution. Once the old backoffice is no longer necessary for testing the new one and the new management APIs, the old backoffice login must be merged with this setup (including 2FA handling and external login handling).
The management APIs aren't protected yet, nor does the client handle auth perfectly well yet, so we have to fake the test a bit.
1. Start the new backoffice client.
2. In the browser, go to `/umbraco/management/api/v1.0/security/back-office/authorize?client_id=umbraco-back-office&response_type=code&scope=offline_access&code_challenge=WZRHGrsBESr8wYFZ9sx0tPURuZgG2lmzyvWpwXPKz8U&code_challenge_method=S256`.
3. Verify …

Dedicated cookie setup for new backoffice login

---

src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Tree/ChildrenDictionaryTreeController.cs

The childDictionary was missing the ParentId since its value was set to null. It has now been updated to actually show the parentId of the childDictionary

Updated so it now shows the parentId instead of null

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

If there's an existing issue for this PR then this fixes [Issue mentioned](https://github.com/umbraco/Umbraco-CMS/issues/14052) #14052 
-  I have been trying to replicate an issue, but it seems to occur inconsistently. I have attempted multiple times, and while the issue sometimes does not happen, at other times it does. I suspect that it could be a timing issue, perhaps related to opening the preview window and the URL simultaneously.
-  To address this, I have made a few changes to the code. Firstly, I have replaced the use of $window with window.
> $window with window.
changed back to $window .
-  Secondly, I have added an EventListener for the load event to the preview window, which should ensure that the window has fully loaded before any further actions are taken. Hopefully, these …

Save and Preview blank on second use #14052

---

src/Umbraco.Web.UI.Client/src/common/services/keyboard.service.js

#13838 Typing '1' or '2' into an input inside a web component toggles the content/info content apps instead of writing '1' or '2' 
1. Create the necessary folder structure: `/App_Plugins/WebComponent/`
2. Create a `package.manifest` (below)
3. Create a `template.html` (below)
4. Restart your Umbraco web application as necessary.
5. Update a `content type` with a new `property` and choose the `Web Component` editor.
6. Type "**1**" or "**2**" into the property editor field to see the hotkey actions toggle between apps.
> **package.manifest**
```
{
"propertyEditors": [
{
"alias": "Web Component #13838",
"name": "WebComponent13838",
"icon": "icon-block",
"group": "Common",
"editor": {
"view": "~/App_Plugins/WebComponent/template.html",
}
}
]
}
```
> **template.html**
```
<uui-input …
```

Edge Cases for Issue #13838: Hotkey Actions Triggered from Web Components

---

src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextParser.cs

When configured to render JSON instead of HTML for Delivery API output, the RTE value converter is currently caching an expression to create the output rather than the actual output. Besides being bad for caching, this also yields issues with disposed objects when trying to access published content for rendering local links.
1. Set `Umbraco::CMS::DeliveryApi::RichTextOutputAsJson` to `true` in app settings.
2. Create content with an RTE that contains links to other content.
3. Fetch the content through the Delivery API two times or more.
4. Ensure no errors are thrown.

Fix the "disposed object" error when rendering RTE content as JSON

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridentry.component.js

Fixes the issue of https://github.com/umbraco/Umbraco-CMS/issues/13834
The ideal solution has been coded previously but changes to the code base had broken its ability to be shown. This PR fixes that.
By ensuring an empty array the code can continue as it is and the unsupported block view will be displayed on blocks that do not have a configuration anymore.
Here a screenshot from my test, proving it's working now:

Block Grid: fix situation when config was not available (13834)

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/ResetCache.cs

Fixes a V12 exclusive bug, where when migrating from 11 -> 12, you would get an exception, because we've updated the BPlusTree dependency, this PR remedies that by creating a migration that deletes the old cache files.
- Added a V12 migration, which deletes all the files in the `DistCache` folder & the `NuCache` folder.
- Run umbaco on V11 with the starter kit installed
- Install umbraco.
- Stop the site
- Upgrade to v12
- This should no longer throw exceptions 🙌

V12: Reset cache on migrating

---

src/Umbraco.Core/Services/ContentService.cs

- #14112 points out a problem when trying to update a value in a notification while attempting to "Save and publish" a content item. The issue demonstrates how to do this by using `ContentPublishingNotification`, however using <code>Content<b>Saving</b>Notification</code> is the proper course of action, because:
- When using the `ContentPublishingNotification`, it will be already too late to change the value as the content item will be already saved in a draft version that is going to be published afterwards.
- With the `ContentSavingNotification`approach, we make sure to change the value before we save the content item, and then we will only need to publish it once and all the changes will be gathered together.
- To make use of the <code>Content<b>Saving</b>Notification</code>, however, …

Set PublishedState of content to Publishing before handling ContentSavingNotification

---

src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs

This PR implements the solution suggested by @PerplexDaniel to fix #14096 (Big H5YR! 🎉) 
As mentioned in his comment the issue was because the property was not set to vary by culture/segment, however, the property was resolved in a varying context, this is because it's perfectly possible to have a blocklist or block grid that varies by culture, but its blocks does not (since varying blocks is not a thing...Yet) 
This fixes the issue by specifying that the property varies, when it's parent does, which makes sense because it's essentially "inheriting" the varying.
This is kinda tricky to test, but #14149 has a good repro description. 
Additionally, test that nothing blows up if you add segments into the mix. 
Enabling segments can be quite tricky, so here's a short guide (reach out if more …

V10: Set culture variation when getting property types for indexing

---

src/Umbraco.Core/DeliveryApi/ApiContentRouteBuilder.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentPickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentRouteBuilderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiUrlPickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTests.cs

Content can be published but still be un-routable. The most common scenario is when content has culture variance, but the root content has no culture and hostnames setup. In this case, only the default language will be directly routable within Umbraco.
However, since we handle routing explicitly in the Delivery API, we can handle routing of these otherwise un-routable items.
1. Create a structure of culture variant content, published in both the default language and another language.
- The root content should not have any culture and hostnames setup.
- For testing purposes, the content paths should differ between the languages. Use different content names per language to obtain this.
2. Verify that content in the content structure can be fetched by route in the Delivery API, both in the …

Handle un-routable published content

---

src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs

- If all the query parameters are left out on the querying endpoint (`/umbraco/delivery/api/v1/content`) or no `fetch` parameter is provided, we will retrieve all the items from the index and use that as the base query when querying our `DeliveryApiContentIndex`;
- This PR takes into account that if a `Start-Item` header is present and it denotes a valid root node `id` or `path`, we will query from that starting point.
- The implementation is similar to having a descendants selector handling _"descendants:[start-item header value]"_ query.
- Have multiple root nodes with children;
- Set `Umbraco:CMS:Global:HideTopLevelNodeFromPath` to false;
- Query `umbraco/delivery/api/v1/content`:
- with no params and no headers - things should still work as before (_all published content nodes should …

Delivery API: Apply start-item in the base querying request

---

src/Umbraco.Cms.Api.Delivery/Indexing/Selectors/AncestorsSelectorIndexer.cs
src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoContentIndexBase.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexFieldDefinitionBuilder.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs

The delivery API content index must be updated whenever content is published or unpublished. To this end, a few changes has to be made to the index population and value set creation, in order to reuse the functionality from the existing content indexes (ExternalIndex, InternalIndex).
As it happens, the unpublish handling is primarily implemented in `UmbracoContentIndex`. Unfortunately, the remaining implementation of `UmbracoContentIndex` and the general usage of `UmbracoContentIndex` throughout the codebase is too biased towards the desired functionality for the existing content indexes. Thus I have abstracted the unpublish handling into a new `UmbracoContentIndexBase` base class for both the `UmbracoContentIndex` and `DeliveryApiContentIndex` index implementations to use.
The `id` index …

Update the delivery API content index at un/publish

---

src/Umbraco.Cms.Api.Delivery/Indexing/Sorts/CreateDateSortIndexer.cs
src/Umbraco.Cms.Api.Delivery/Indexing/Sorts/UpdateDateSortIndexer.cs
src/Umbraco.Cms.Api.Delivery/Querying/Filters/NameFilter.cs
src/Umbraco.Cms.Api.Delivery/Querying/Sorts/CreateDateSort.cs
src/Umbraco.Cms.Api.Delivery/Querying/Sorts/UpdateDateSort.cs

This PR adds sort handlers (and accompanying content indexers) for create and update date. 
I also removed a hardcoded field name in `NameFilter` while I was at it.
1. Rebuild the delivery API content index.
2. Verify that content queries can be sorted by content create and update date - i.e.  `createDate:asc` or  `updateDate:desc`.
3. Verify that both sort handlers support `asc` and `desc` sort order.
4. Verify that the sort handlers apply both date and time to the sorting - i.e. when publishing two content items, the last updated content item should be returned first when sorting by `updateDate:desc`. Subsequently publishing the first of the two items, the first one should now be returned by the same sorting due to the time component of the update date.
- Remember you must manually …

Add sort handlers for create and update date

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml

This fixes the issue #14183 where we found some typos in the danish translation of the Block Grid editor :)

Fixing danish typos

---

src/Umbraco.Web/Editors/ImagesController.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/14056
- The image path was missing encoding, as we had in other versions
- Added the missing encoding of image path
- Upload a media file with a special character in the filename like `è`
- Try to pick it with a media picker, this should now display the thumbnail 👍

V8: Encode imagepath to handle special characters

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridentry.component.js

This PR fixes #14161 
If a block is removed from the block grid configuration the back office view would break, interesting this was already fixed in #14148, however for some reason the changes seem to be missing from V10, so this PR cherry picks that PR into v10/dev
Follow the steps in the issue, check out this branch, rebuild, issue no longer occurs

Cherry-Pick #14148 Fixing BlockGrid Editor With Deleted Element Type

---

src/Umbraco.Web.UI.Client/src/views/common/dashboard.html
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tabs/tabs.spec.ts

Remove wrapping form for dashboards and wrap umb-tabs-nav with ngForm instead
If you include a `<form>` tag in a dashboard, it gets removed because of a wrapping form element in `dashboard.html`. Changing the wrapping `<form>` to an `<ng-form>` fixes this. 
It looks like dashboards have a wrapping form because of `<umb-tabs-nav>` element, which has functionality for checking if a contained form is `$invalid`. This functionality still works even with this change. I have also tried installing a few packages that include custom dashboards and those dashboards seem to work.
1. Create a custom dashboard however you like
2. Add a normal HTML form to that dashboard such as
```html
<form>
<input type="text" name="name">
</form>
```
3. See …

Fix: Form elements in thirdparty dashboard views get removed

---

src/Umbraco.Cms.Api.Delivery/Controllers/ContentApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/Controllers/QueryContentApiController.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
src/Umbraco.Core/DeliveryApi/IApiContentQueryService.cs
src/Umbraco.Core/DeliveryApi/NoopApiContentQueryService.cs
src/Umbraco.Core/Services/OperationStatus/ApiContentQueryOperationStatus.cs

Return bad request when the attempted 'fetch', 'filter' or 'sort' option does not exist.
- If valid 'fetch', 'filter' or 'sort' options are applied to the `/umbraco/delivery/api/v1/content` endpoint, the functionality should be as before - only the items that meet the criteria would be returned;
- In an invalid '**_fetch_**' option is applied, i.e. <code>umbraco/delivery/api/v1/content?fetch=<b>childrenasd</b>:605a5fe0-d772-42a8-8ad3-d0683bf1bc08</code>
- Verify that you get a Bad Request with the title "_Selector option not found_" as a response;
- In an invalid '**_filter_**' option is applied, i.e. <code>/umbraco/delivery/api/v1/content?filter=contentType:person&filter=<b>nameasd</b>:Daughter</code>
- Verify that you get a Bad Request with the title "_Filter option not found_" as a …

Delivery API: Handle unhappy paths for the multiple items endpoint

---

src/Umbraco.Core/Services/UserGroupService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserGroupServiceValidationTests.cs

Fixes an issue where you could not rename a user group because it would conflict with the alias.
This is because the check didn't take into account the key of the user groups, so this fixes that. 
I've added an integration test that tests this 👍

New backoffice: Fix renaming user groups

---

src/Umbraco.Cms.Api.Delivery/Controllers/ByRouteContentApiController.cs
src/Umbraco.Cms.Api.Delivery/Controllers/ContentApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/Controllers/DeliveryApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/Controllers/QueryContentApiController.cs
src/Umbraco.Cms.Api.Delivery/Filters/ValidateStartItemAttribute.cs
src/Umbraco.Cms.Api.Delivery/Querying/Filters/ContentTypeFilter.cs
src/Umbraco.Cms.Api.Delivery/Querying/Filters/NameFilter.cs
src/Umbraco.Cms.Api.Delivery/Services/RequestStartItemProvider.cs
src/Umbraco.Core/DeliveryApi/IRequestStartItemProvider.cs
src/Umbraco.Core/DeliveryApi/NoopRequestStartItemProvider.cs

- If the value of the "**Start-Item**" header is representing an invalid start node, `Not Found` response will be returned from all endpoints: <code>umbraco/delivery/api/v1/content/item/<b>{id}</b></code>, <code>umbraco/delivery/api/v1/content/item/<b>{path}</b></code> and `umbraco/delivery/api/v1/content/`.
- Test that without passing a "Start-Item" header, everything works as before;
- Pass invalid Guid or URL segment of a start item and verify that you get a 404 with a meaningful message;
- Test that passing a value with a **wrong** URL segment **casing** in a "Start-Item" header (of a valid item) returns the **found** item;
- Ex: </br> GET https://localhost:44331/umbraco/delivery/api/v1/content/item/article </br> Start-Item: Blog
- Test that passing a URL segment with `/` in a …

Delivery API: Not Found response when the start-item in "Start-Item" header is invalid

---

src/Umbraco.Core/Cache/DictionaryAppCache.cs
src/Umbraco.Core/Cache/FastDictionaryAppCache.cs
src/Umbraco.Core/Cache/IAppCache.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/AppCacheTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/FastDictionaryAppCacheTests.cs

There are currently a few different implementations of `IAppCache`:
- `DeepCloneAppCache`
- `DictionaryAppCache`
- `FastDictionaryAppCache`
- `HttpContextRequestAppCache`
- `NoAppCache`
- `ObjectCacheAppCache`
Of these, only the two concurrency dictionary based ones (`DictionaryAppCache` and `FastDictionaryAppCache`) allow caching of `null` values, while the other ones do not. This causes some unpredictable behaviour in certain edge cases related to routing.
This PR ensures that `null` values are never cached.
While this is not a binary breaking change, it is in principle a functionally breaking change. However, given the discrepancy between the `IAppCache` implementations, I do believe we're best off aligning their functionality across the board.
The routing behaviour is not the easiest …

IAppCache implementations should not cache null values

---

src/Umbraco.Core/Models/PublishedContent/NoopPublishedValueFallback.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/14202
Added missing interface member for the NoopPublishedValueFallback

V10: Fix NoopPublishedValuefallback varation context member not implemented

---

src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
src/Umbraco.Web.BackOffice/Security/IPasswordChanger.cs
src/Umbraco.Web.BackOffice/Security/PasswordChanger.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13942
- Checks when we have no `OldPassword` if we're changing the current users password
This will prevent people hijacking backoffice users sessions, and then changing their password
- Follow steps in issue 🙌

V11: prevent currentuser resetting password without old password

---

src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs
src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandleContentChanges.cs
src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandleContentTypeChanges.cs
src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandlePublicAccessChanges.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexFieldDefinitionBuilder.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiIndexingHandler.cs
src/Umbraco.Infrastructure/Examine/UmbracoExamineFieldNames.cs
src/Umbraco.Infrastructure/Search/IDeliveryApiIndexingHandler.cs
src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.DeliveryApi.cs

This PR ensures that content is automatically removed from the Delivery API content index when public access restrictions are applied.
The distributed cache notifications for public access changes are _extremely_ limited, which in turn means we have to accept that whenever content is _unprotected_, the content must be republished in order to be re-added to the index. This limitation will (likely) be mended once we support protected content in the Delivery API, but for now we'll have to accept it. See also comments in `DeliveryApiContentIndexHandlePublicAccessChanges`.
Other interesting changes:
- The magic index field names have been replaced with constants.
- The integer fields `id` and `contentTypeId` have been turned into with raw (string) fields, because the querying options for …

Handle applied public access restrictions in the Delivery API content index

---

src/Umbraco.Cms.ManagementApi/ViewModels/Installer/InstallViewModel.cs
src/Umbraco.Core/Services/MetricsConsentService.cs
src/Umbraco.New.Cms.Core/Models/Installer/InstallData.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

- This is a follow up of this PR: https://github.com/umbraco/Umbraco-CMS/pull/13918
- We missed also defaulting to Detailed telemetry if its not set at all (this should only happen if you manually delete the entry in the table)
- Install Umbraco
- Open up the `umbracoKeyValue` table
- Delete the telemetry level row
- Navigate to the Telemetry dashboard in the `Settings section`
- Assert that its set to detailed

V11: Fallback to detailed if not telemetry level not set

---

src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerDatabaseProviderMetadata.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/14110
- Enable `ForceCreateDatabase` for `SqlServerDatabaseProviderMetadata`
- Set your connectionString in your `AppSettings.json`, I used my localDb like so:
(If you do not have a SQL server running, create one first)
Note here that although your server should be running, whatever database you set should not, so here my `test` database does not exist
```
"ConnectionStrings": {
"umbracoDbDSN": "Server=(localdb)\\MSSQLLocalDB;Database=test;Integrated Security=true",
"umbracoDbDSN_ProviderName": "Microsoft.Data.SqlClient"
},
```
- Enable UnattendedInstall by setting in your `AppSettings.Json`, in the `Umbraco/CMS` section
```
"Unattended": {
"InstallUnattended": true,
"UnattendedUserName": "Nikolaj Geisle",
"UnattendedUserEmail": "{YOUR …
```

Enable ForceCreateDatabase for SqlServer

---

src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexPopulator.cs
src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.DeliveryApi.cs

Updating content indexes can be an expensive operation for large sites. This PR ensures that we do not update the new content index for the Delivery API unless the Delivery API has been explicitly enabled by configuration.
Prerequisites:
1. Stop the site if it is running.
2. Delete the Delivery API content index from disk. 
- _Hint: Check the Examine dashboard to find the path on disk._
Steps:
1. Update the `Enabled` configuration to `false`:
2. Start the site and let it run undisturbed for a few minutes, until the "DeliveryApiContentIndex" folder is recreated on disk for the index. 
3. Now go to the Examine dashboard and verify that:
- The document count for the index is 0.
- The the "Rebuild index" button is disabled.
4. Publish some content and verify that the document count on the …

Only index content for the Delivery API when it is enabled

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tabs/tabs.spec.ts

Removed test.only, so our other test actually runs on the pipeline.
Updated the test itself so it asserts correctly.

V12: Remove test.only for acceptance tests

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less

This fix makes it possible to keep the focus on a parent block, though a child block is 'overlapping' with the action bar.
Enables to move the mouse to this position without the child getting focused.
Previously this would have happened:
This will still happen but it depends on how your mouse navigated here.
Main reason for this change is to make an acceptable solution for setups like this seen above where the is enough space to see the actions of the parent, but not enough space to actually get to them.
I also removed some CSS that did not have a valid selector, must have been some left over from development period.
**Test steps:**
* Setup a new document type
* Add a property with a Data Type using the Block Grid Editor.
* Setup the demo blocks in the Block Grid Editor Data Type …

Make it possible to keep focus on a parent Block

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

When editing language variant content in an infinite editor, the "Save and close"/"Publish and close" buttons don't really work:
The dev console sheds a little more light on the error: `{"errorMsg":"An error occurred","data":{"Message":"No variants flagged for saving"},"status":404}`
Turns out neither method in the Angular controller has support for language variants. 
This PR fixes it. I have opted to reuse the existing "Save"/"Save and publish" methods for handling "Save and close"/"Publish and close". This results in a slightly increased complexity in these methods, but the alternative would be to duplicate a lot (like a lot!) of code in the controller. I reckon the added complexity is the better solution.
To test this PR, you need something that opens content for editing in an …

V10: Fix "Save and close"/"Publish and close" for infinite editing of language variant content

---

src/Umbraco.Cms.Api.Delivery/Controllers/ByIdContentApiController.cs
src/Umbraco.Cms.Api.Delivery/Controllers/ByRouteContentApiController.cs

- Adding `Unauthorized` as a `ProducesResponseType` for the single-item endpoints.
- Verify that Unauthorized appears as a possible response for both `/umbraco/delivery/api/v1/content/item/{id}` and `/umbraco/delivery/api/v1/content/item/{path}` in Swagger.

Delivery API: Add unauthorized to the produced response types 

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorAdvanced.spec.ts

The test 'can see thumbnail in content for a block grid editor' was failing on the pipeline for v12, the reason for this is because the style has changed, which caused our assertion to fail. The test has now been updated to match the correct style

Fixed: an block grid editor accceptance test on the pipeline for v12

---

src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs
src/Umbraco.Infrastructure/Routing/NotFoundHandlerHelper.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js

This fixes https://github.com/umbraco/Umbraco-CMS/issues/13958
After this commit here https://github.com/umbraco/Umbraco-CMS/commit/8d2ee3a6d4bfbe650750e6980649ee57706248ef we lost the functionality to evaluate `$site` and `$parent` as XPath variables inside a Multinode Treepicker during the creation of a new node where said picker is a property.
Before the commit, the meaning of `$current` and `$parent` was also ambiguous, changing depending on whether or not you are creating a new node or not.
There is a blog entry explaining how you previously could work around the issue:
https://www.dot-see.com/blog/getting-the-right-starting-node-for-multinode-treepicker-with-xpath/
However with today's code one can't use the Multinode Treepicker with XPath correctly during node creation at all, if …

XPath can unambiguously use $site/$parent

---

src/Umbraco.Core/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs

Media picker properties are being cached a bit too hard for the Delivery API, to the point where media changes are not reflected in the API output before a restart.
This PR adjusts these cache leves.
1. Create content with a picked media. It doesn't matter if it's MediaPicker or MediaPicker3.
2. Request the content using the Delivery API.
3. Change the picked media name.
4. Request the content again and verify that the media name is updated in the API repsonse.
If you want to get fancy, also test this with custom media properties (like an ALT text) using output expansion 😄

Fix delivery API cache level for media picker property editors

---

src/Umbraco.Core/Services/StylesheetService.cs

Before we werent able to add a Stylesheet to a folder because it didnt check if the folder existed. We are now checking if the Folder actually exists.

Changed so we are checking if the FolderExits

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MediaPickerWithCropsValueConverterTests.cs

When rendering for the Delivery API, MediaPicker3 currently only outputs local crops and focal point. Crops and focal point on the media item itself are disregarded, which is a bug.
This PR ensures we merge the property (local) crops + focal point and the media (global) crops + focal point when outputting. The local ones takes precedence over the global ones.
In this PR I have also refactored the unit test for MediaPicker3 a bit to avoid repeating the same assertion blocks over and over again.
1. Setup the "image" media type with multiple crops.
2. Setup a media with crops and focal point defined.
3. Create a content type with a MediaPicker3 property that local crops and focal point enabled.
- make sure you setup both unique crop aliases and a crop alias that overlap one of the media …

MediaPicker3 should include media crops and focal point in output

---

src/Umbraco.Cms.Api.Delivery/Querying/Filters/ContentTypeFilter.cs
src/Umbraco.Cms.Api.Delivery/Querying/Filters/NameFilter.cs
src/Umbraco.Cms.Api.Delivery/Querying/QueryOptionBase.cs
src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
src/Umbraco.Cms.Api.Delivery/Services/RequestRoutingService.cs

When passing an empty value to some of our built-in query options, we should have a safe fallback and get 0 items instead of Internal Server Errors.
- Try passing empty values to all built-in query options and verify that there are no Examine errors (_Internal Server_):
- `?fetch=ancestors:`;
- `?fetch=children:`;
- `?fetch=descendants:`;
- `?filter=contentType:`;
- `?filter=name:`;
- `?sort=createDate:`;
- `?sort=level:`;
- `?sort=name:`;
- `?sort=sortOrder:`;
- `?sort=updateDate:`.

Delivery API: Handle more unhappy paths when querying

---

src/Umbraco.Core/Logging/DisposableTimer.cs

When using the following code for the `profilingLogger` the endMessageArgs was not replaced correctly in the end log message with the duration and timing ID.
```csharp
var nodeKey = Guid.NewGuid();
using (_profilingLogger.TraceDuration<MyApiController>("Calculating complex code for node {nodeKey}", 
"Complex code completed for node {nodeKey}", 
startMessageArgs: new object[]{nodeKey}, 
endMessageArgs:new object[]{nodeKey}))
{
Thread.Sleep(2000);
}
```
See attached screenshot of the values being replaced incorrectly.
* Use the following code above in an `UmbracoApiController`
* Test this out before the PR is applied & verify the bug that the values are not correct.
* Apply the PR and verify the issue is fixed 😄

Fix the args used in log endMessages in the profillingLogger

---

src/Umbraco.Web.UI.Client/src/less/components/umb-color-picker.less

After upgrade of spectrum color picker, which had some accessibility enhancements and cleanup https://github.com/seballot/spectrum/pull/38 it affected that Umbraco set the `height: auto` so the checkered background wasn't visible.
https://github.com/umbraco/Umbraco-CMS/pull/14179
Furthermore it wasn't possible to see the current selected color.
**Before**
**After**

Fix transparent background after upgrade of spectrum color picker

---

src/Umbraco.Core/Models/DeliveryApi/RichTextModel.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs

This PR wraps RTE markup in a dedicated output model for the Delivery API, so we can add to that model in the future - should the need arise.
Verify that the output now looks something like this:
...where `content` is the alias of the RTE property.

Wrap RTE content in a dedicated model for future expansion

---

templates/UmbracoPackage/buildTransitive/UmbracoPackage.targets

Similarly to what was already fixed with #11211 package assets also require currently the project to be built and only then published in order to ensure the package assets are correctly copied to the output folder.
This happens because while the aforementioned PR ensures files are published, the current target only seems to run after the build is already finished.
The change ensures the files are copied earlier in the build process, in line with the `CopyUmbracoAssets` target.
- Install a package with assets (e.g uSync 9.1.0)
- Make sure the project is in a clean state and the assets aren't present in App_Plugins yet (`dotnet clean`)
- Run `dotnet publish` 
- The output should now be missing the package assets

Fix build required before initial publish for packages

---

src/Umbraco.Core/PropertyEditors/ValueConverters/MultiNodeTreePickerValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs

Builds on top of https://github.com/umbraco/Umbraco-CMS/pull/14261
Completely ignores macros instead of exploding in delivery api. Thereby output becomes something like
``
"<p>saasd</p>\n<p> </p>\n<?UMBRACO_MACRO macroAlias=\"asdasd\" />\n<p> </p>\n<p>asdasd</p>"
``

Ignore macros completely in deliveryapi

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

>>The Block Label of Block Components is displaying Angular JS code rather than result on first load. If opened again the label displays correctly
Reported issue https://github.com/umbraco/Umbraco-CMS/issues/14105
old code
>>   blockObject.label = (blockObject.config.label || blockObject.content?.contentTypeName) ?? "" ;
new code
>> blockObject.label = (blockObject.labelInterpolator(blockObject.data) || blockObject.content?.contentTypeName) ?? "";
Replace `blockObject.config.label` with  `blockObject.labelInterpolator(blockObject.data)`, because of `blockObject.config.label` always has the property alias eg: {{propertyAlias}}

[Fix] Block editor labels showing Angular JS on first load.

---

src/Umbraco.Core/Persistence/IUmbracoDatabase.cs
src/Umbraco.Core/Persistence/NPocoDatabaseExtensions-Bulk.cs
src/Umbraco.Core/Persistence/UmbracoDatabase.cs
src/Umbraco.Tests/Testing/TestDatabase.cs

When using the latest version of Umbraco 8 on SQL Server 2022, there is an error when rebuilding the NuCache database cache when the serializer is set JSON and not MsgPack in the web.config (which older sites most likely will be).  This can happen from the Settings > Published Status screen in the back-office or when booting, making the site error completely and never load.  If you are able to login to Umbraco the same error can also happen when saving document types.
The following exception is thrown:
```
-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.
-> System.Data.SqlClient.SqlException: Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
at System.Data.SqlClient.SqlConnection.OnError(SqlException …
```

Umbraco 8 - SQL Server 2022 NuCache Error Using JSON Serializer

---

src/Umbraco.Cms.Api.Delivery/Controllers/ContentApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
src/Umbraco.Core/DeliveryApi/IApiContentQueryProvider.cs
src/Umbraco.Core/Services/OperationStatus/ApiContentQueryOperationStatus.cs

This PR splits the Examine querying specifics from `ApiContentQueryService` into a new `IApiContentQueryProvider` interface to make it easier to swap the underlying query technology (i.e. use Elastic instead of Examine).
The corresponding indexing part is not handled by this PR, but will be addressed at a later stage (to whatever degree possible).
This PR should yield absolutely no behavioural changes to the multiple items endpoint. In other words, test that the endpoint continues to produce results.
Make sure to test combinations of selectors, filters and sorts. 
Also test that querying in culture variant setups still works. Pay special attention to testing mixed results (variant and invariant content in the same result).

Split the Examine specifics from API query service

---

src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
src/Umbraco.Core/Configuration/Models/ConnectionStrings.cs
src/Umbraco.Core/Constants-System.cs
src/Umbraco.Core/Extensions/ConfigurationExtensions.cs

- Implements logic that will translate the `|DataDirectory|` part of you connection string, to an actual filepath, 
as this was tripping people up, when registering their DbContexts.
- Created Constants for `DataDirectoryName` & `DataDirectoryPlaceHolder` as they where now used multiple places
- Follow the documentation for EFCore: https://docs.umbraco.com/umbraco-cms/v/12.latest/tutorials/getting-started-with-entity-framework-core
- Try to register your database with just copying your SQLite connection string from your appsettings.json, it should look like this: `Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True`
- You should be able to access your db context now 🙌

V12: Map |DataDirectory| to path in connectionString

---

src/Umbraco.Web.UI.Client/src/installer/installer.service.js

Noticed on an install this morning that this was a bit out of date:
- Links to Codegarden 2018
- Says it's in May
- Uses the wrong capitalization
So this updates it.

Updated the installer text about Codegarden

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13906
In rare conditions, the block editor does not open automatically when new blocks are created in block list or block grid.
It happens if the block is configured having its first tab contain no properties, only groups (with properties). If the first tab has direct properties, or there are no tabs (i.e. only groups with properties), things work just fine.
This has been peer tested due to the special setup prerequisites 😄 
This issue was introduced with the block grid and as such it is a regression towards the block list.

Ensure that blocks always open automatically when added to block list or block grid

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Infrastructure/Telemetry/Interfaces/IDetailedTelemetryProvider.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeIdentity.cs
src/Umbraco.Web.BackOffice/Telemetry/ExternalLoginTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

Adds the amount of backoffice external login providers to the detailed telemetry.
To test I:
* Added 1 external login provider to backoffice.
* Checked it showed in the telemetry
* Added 1 external login provider to **members**
* Checked it still only showed 1 providers in telemetry
* Added 1 more external login provider to backoffice.
* Checked it now showed 2 providers in telemetry.

V10: Add external login provider count to detailed telemetry

---

src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs

The Delivery API fails to execute queries if the `filter` or `sort` parameter is empty in the request - like this:
`/umbraco/delivery/api/v1.0/content/?fetch=children:/&filter=&sort=`
For whatever reason the empty query string parameter is picked up by ASP.Net Core and passed as an `IEnumerable<string>` with one empty string entry. So... this PR filters out these empty strings before attempting to resolve filters and sorts.
The request above should not fail, but yield all children of root - unfiltered and unsorted.

Empty filter and sort values should not be considered when executing queries

---

src/Umbraco.Core/PropertyEditors/DefaultPropertyIndexValueFactory.cs
src/Umbraco.Core/PropertyEditors/IPropertyIndexValueFactory.cs
src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs
src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs
src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/MediaValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/MemberValueSetBuilder.cs
src/Umbraco.Infrastructure/PropertyEditors/GridPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexInitializer.cs
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/14096#issuecomment-1554528945
Apparently we did not cover all use cases, this PR should remedy that.
- Pass Available cultures to iterate through them, when property varies by culture
- Follow steps in original issue comment
- Varies setups we also need to test works:
- Content varies, block does not
- Content varies, block varies
- Content doesn't vary, block doesn't vary

V10: Implement varying blocklist indexing

---

src/Umbraco.Cms.Api.Delivery/Controllers/QueryContentApiController.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
src/Umbraco.Core/CompatibilitySuppressions.xml
src/Umbraco.Core/DeliveryApi/IApiContentQueryProvider.cs
src/Umbraco.Core/DeliveryApi/IApiContentQueryService.cs
src/Umbraco.Core/DeliveryApi/NoopApiContentQueryService.cs
src/Umbraco.Core/Models/PagedModel.cs
src/Umbraco.Core/Services/ILocalizationService.cs
src/Umbraco.Core/Services/ITrackedReferencesService.cs
src/Umbraco.Core/Services/TrackedReferencesService.cs

The `PagedModel` class was copied over from _Project New Backoffice_ ... but we forgot to fix the model namespace, which has then been propagated into various uses throughout the codebase.
We really don't want a `Umbraco.New.Cms.Core.Models` namespace in the core, so this refactoring - while breaking - is necessary 😢

Fix the namespace for PagedModel

---

src/Umbraco.Cms.Api.Delivery/Indexing/Filters/NameFilterIndexer.cs
src/Umbraco.Cms.Api.Delivery/Indexing/Sorts/NameSortIndexer.cs
src/Umbraco.Cms.Api.Delivery/Querying/Filters/NameFilter.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexFieldDefinitionBuilder.cs

NB:❗ This PR should be merged after https://github.com/umbraco/Umbraco-CMS/pull/14257 changes are into `release/12.0` branch. It is important to then merge `release/12.0` into this branch to get the `ApiContentQueryProvider` and `IApiContentQueryProvider` implementations.
- Adds support for "Contains" filters for the Query endpoint of the Delivery API.
- Make sure you can sort and filter on the `"name"` field;
- Test with some exact matches (`FilterOperation.IsNot` and `FilterOperation.Is`) and with contains filters (`FilterOperation.DoesNotContain` and `FilterOperation.Contains`) and verify that the results are correct;
- You can also try creating new filters and test the filtering functionality.

Delivery API: Adding support for "Contains" filters

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/ChildrenDocumentTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/RootDocumentTreeController.cs
src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/ContentType/ContentTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeResponseModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/Item/DocumentItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tree/DocumentTreeItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tree/VariantTreeItemViewModel.cs

This PR adds Variant information and the content type key to the Document Tree entities, as well as the missing SortOrder property to the `PropertyTypeResponseModelBaseModel`.
Request the relevant endpoint and check that the data is there 😄

V14: Add information to tree items

---

src/Umbraco.Web.BackOffice/Controllers/TinyMceController.cs

- Move file checking (count and errors) to the top, so we do not create a folder, if we have no file.
- Added handling of blob images, that will try to map a file extension, as it doesn't have one
- Create a document type with a rich text editor property
- Create a content node with that document type
- Open source code for rich text editor and put in `<p> </p>`
-  past in this base64 image between the paragraph tags: https://github.com/umbraco/Umbraco.Deploy.Issues/files/10091102/base64image.txt
- This should now result in a upload of the file, and it should also show in the media library 👍

V10: Handle blob images

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

If there's an existing issue for this PR then this fixes #14320
Changed the tinymce tooltip from "Media Picker" to "Image Picker"

Change "Media Picker" in RTE to "Image Picker"

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageCropperTest.cs

If there's an existing issue for this PR then this fixes [#14270](https://github.com/umbraco/Umbraco-CMS/issues/14270)
I have changed 
`GetCropBaseOptions(null, crop, useFocalPoint || string.IsNullOrWhiteSpace(alias))`
to
`GetCropBaseOptions(Src, crop, useFocalPoint || string.IsNullOrWhiteSpace(alias))`
in order to prevent returning null.
Also I have changed GetBaseCropUrlFromModelTest to ensure that the full crop URL is returned, not just the crop parameters.

Fix #14270 - ImageCropperValue.GetCropUrl(alias, imageUrlGenerator) always returns null

---

src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
src/Umbraco.Core/EmbeddedResources/Lang/it.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
src/Umbraco.Core/EmbeddedResources/Lang/tr.xml

This PR fixes [Issue 14213](https://github.com/umbraco/Umbraco-CMS/issues/14213)
As described in the original issue, I swapped the sortCreateDateAscending translations with the sortCreateDateDescending translations for all the languages where the keys existed (except for Welsh that seemed to be correct).
As a bonus I added the Portuguese translation for these keys (they were missing).
**Steps to reproduce**
1. Go to the Umbraco backoffice site.
2. Click on the "Users" tab
3. Create a few sample users
4. Order by "Oldest" or "Newest"
After this change, the sorting order should match the translation. When you sort on "Oldest", the users should be sorted on create date in ascending order and when you sort on "Newest", the users should be sorted on create date create in descending order.

Swapped the sortCreateDateAscending and sortCreateDateDescending translation values to match the intended behavior

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/Models/ContentEditing/SearchResults.cs
src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html

In a current working project, we have a custom index and advanced search/lucene queries often returning many results.
We could inspect the request, but I think it would be nice to see to number of results returned and it can be used to compare with the expected results based on the dataset.
https://github.com/umbraco/Umbraco-CMS/assets/2919859/559555fa-6923-416e-864c-211b33fb63cb

Show summary of Examine search results

---

.gitignore
src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props
src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.targets
templates/Umbraco.Templates.csproj
templates/UmbracoProject/.gitignore
templates/UmbracoProject/UmbracoProject.csproj

This PR aims to ensure that the generated schema file for the new `umbraco-package.json` format is preserved through the Cms.Targets project, which in turn copies it out to any referencing projects such as `Umbraco.Web.UI.New`.
**Source version**
1. Build the startup project
2. Check that `umbraco-package-schema.json` is copied into the root of that project
**Packed version**
1. Run `dotnet pack -o .artifacts`
2. Add `.artifacts` as a  nuget source and install `./artifacts/Umbraco.Templates.xxxxxxx` 
3. Create a new project from the "umbraco" template
4. Verify that `umbraco-package-schema.json" and `appsettings-schema.json` are both present in the project folder
The old executable `Umbraco.Web.UI` also references the "Cms.Targets" projects and thus gets the same file, which it of course …

V14: umbraco-package.json schema

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs

If you used something like OpenIdConnect and AzureB2C with tokens enabled, you could not unlink your account.
This was cause by a foreign key constraint between the `umbracoExternalLogin` and `umbracoExternalLoginToken` tables since we did not remove the external login tokens before trying to remove the external logins themselves.
This PR fixes that.

Fix unlinking with external login tokens

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CreateDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CreateUpdateDocumentTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DeleteDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/UpdateDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Mapping/ContentType/ContentTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/CreateContentTypeRequestModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeContainerModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/UpdateContentTypeRequestModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CreateDocumentTypePropertyTypeContainerRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CreateDocumentTypePropertyTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CreateDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypePropertyTypeResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/IDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/UpdateDocumentTypePropertyTypeContainerRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/UpdateDocumentTypePropertyTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/UpdateDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypePropertyTypeContainerResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypePropertyTypeResponseModel.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs

This is a temporary measure to make us able to create, update and delete content types in the management API (we can already get them by ID).
The implementation is _not_ written to be pretty. Hopefully it will prove as a starting point for "the actual" server side implementation. It is littered with FIXME's to that end.
The API contract on the other hand should be OK, so please pay special attention to reviewing that.
Test that content types can be created, updated and deleted. Try with different permutations of properties and tabs/groups, particularly groups in tabs 😄

Temporary CRUD API for content types

---

src/Umbraco.Cms.Api.Management/Controllers/Template/ByKeyTemplateController.cs
src/Umbraco.Cms.Api.Management/Controllers/Template/Item/ItemTemplateItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Template/ScaffoldTemplateController.cs
src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/TemplateBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/ITemplatePresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/TemplatePresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/Items/ItemTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Template/TemplateViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/Template/Item/TemplateItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Template/TemplateResponseModel.cs
src/Umbraco.Core/Services/ITemplateService.cs
src/Umbraco.Core/Services/OperationStatus/TemplateOperationStatus.cs
src/Umbraco.Core/Services/TemplateService.cs
src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContent.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePerformanceTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs

Updates the template controllers to better match the requirements: 
* Adds alias to the document item response - This is needed in case a template is picked as the master template
* Adds master template key to the detailed model - This is needed when opening the editor for a template to populate the name of the master template
* Adds master template key as an optional parameter to scaffolding - This is needed to avoid having to do string magic with the returned scaffold to include the master template, note here that we also need to consider how  we'll handle different models locations/namespaces
* Checks for duplicate aliases when creating/updating templates directly - This boils down to failing fast, previously we'd just change the alias for you, however, this doesn't align very well …

V14: Update template controllers

---

src/Umbraco.Web.UI.New/Startup.cs

Add location header for CORS requests
When Vite Server communicates with backend, we are using Fetch calls over CORS, which then omits some headers. Adding this line will approve the Location for CORS requests. Which we need, thanks

Add location header for CORS requests

---

src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexFieldDefinitionBuilder.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs

The name sorting is rather broken at the moment. Our Examine implementation of querying does not use the correct field definitions.
First and foremost you'll need to rebuild the _DeliveryApiContentIndex_ before testing.
1. Verify that name sorting works both `asc` and `desc` when querying items from the Delivery API.
2. Verify that name sorting is performed case invariant.

Fix broken name sorting in the Delivery API

---

tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs

- We need the database for the `IndexTest` as we're now locating the default ISO code in the `ContentValueSetBuilder.GetValueSetsEnumerable` function (mostly used for blocklists in variant/non-variant mixed setups)
- The integration tests should now pass :)

V12: use database when testing examine

---

src/Umbraco.Infrastructure/Services/Implement/UserIdKeyResolver.cs

This fixes a bug where SQLServer wouldn't work. 
This is because SQLServer knows that the key is a GUID, so it cannot be retrieved as a string. 
For some weird reason NPoco refuses to use our custom mapper when using `ExecuteScalarAsync` so I had to change this back to just be `ExecuteScalar`
If all the tests pass we're good to merge 😄

V14: UserIdKeyResolver fetch GUID directly 

---

src/Umbraco.Cms.Imaging.ImageSharp/Media/ImageSharpImageUrlGenerator.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Media/ImageSharpImageUrlGeneratorTests.cs

During load testing of V12, we noticed that after upgrading to ImageSharp3, sites would occasionally have huge spikes in response times. 
Throwing a profiler on it and doing some digging it seems that this is caused by calling `_requestAuthorizationUtilities.ComputeHMAC` in the `ImageSharpImageUrlGenerator`, the reason for it as far as I can tell is because ImageSharp will use their own utility `AsyncHelper.RunSync` to then run the async method, this, in turn, creates a new Task using the `TaskFactory` however, this seems to be causing major hangs. Without knowing the intricate insides of `TaskFactory` I assume that this is caused by some form of thread pool starvation. Changing the code over to `_requestAuthorizationUtilities.ComputeHMACAsync(uri, …

V12: Fix ImageSharp3 performance issue

---

src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs

At this time, we can't predict if developers will need to add to the Delivery API JSON type info resolver, in order to ensure correct serialization of custom models etc. Therefore I have made the core implementation (`DeliveryApiJsonTypeResolver`) un-sealed, so devs can override it instead of having to re-implement the core type info resolving.
1. Create a custom JSON type info resolver based on `DeliveryApiJsonTypeResolver`.
2. Register the custom resolver instead of the core one.
3. Verify that the custom resolver is invoked at runtime when fetching content from the Delivery API - use the debugger and a breakpoint, that's the easiest way 😄 
Here's some code to get the testing going:
```csharp
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using …
```

Make the Delivery API JSON type info resolver un-sealed

---

src/Umbraco.Cms.Api.Common/Configuration/ConfigureUmbracoSwaggerGenOptions.cs
src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderApiExtensions.cs
src/Umbraco.Cms.Api.Common/OpenApi/IOperationIdSelector.cs
src/Umbraco.Cms.Api.Common/OpenApi/ISchemaIdSelector.cs
src/Umbraco.Cms.Api.Common/OpenApi/MimeTypeDocumentFilter.cs
src/Umbraco.Cms.Api.Common/OpenApi/OperationIdSelector.cs
src/Umbraco.Cms.Api.Common/OpenApi/SchemaIdSelector.cs
src/Umbraco.Cms.Api.Common/OpenApi/SwaggerRouteTemplatePipelineFilter.cs
src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoDeliveryApiSwaggerGenOptions.cs

This PR aims to make the API versioning and Swagger configuration less intrusive than it currently is. With this PR:
- we are no longer forcefully applying operation and schema IDs to custom APIs
- developers can change the location and the availability of the Swagger endpoints and Swagger UI
This PR removes the polymorphism configuration from Swagger (specifically [these lines of code](https://github.com/umbraco/Umbraco-CMS/pull/14363/files#diff-76696450bf7a936b8b45695afab30458c063e36e7240724adec3b98233cf3239L57-L75)), because it is not necessary for V12
However, it is crucial for V14. In other words, when merging this to V14, code that is necessary for the new backoffice will likely go missing. @kjac has a local shelveset of the required changes for V14 on hand, so get in touch when …

Make the API versioning and Swagger config less intrusive

---

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.MembersIdentity.cs
src/Umbraco.Web.Common/Security/ConfigureMemberCookieOptions.cs
src/Umbraco.Web.Common/Security/MemberSecurityStampValidator.cs
src/Umbraco.Web.Common/Security/MemberSecurityStampValidatorOptions.cs
src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs

- Issue was that you could logout as a member, but if somebody stole your cookie, they could use that and still be logged in.
- We have now remedied that by updating the security stamp whenever you logout.
- Note that your cookie will only be validated once every 30 mins, so if you want to change this default behavior to more or less time, you'd have to implement your own ConfigureOptions like so: 
```
public class ConfigureSecurityStampValidatorOptions : IConfigureOptions<MemberSecurityStampValidatorOptions>
{
public void Configure(MemberSecurityStampValidatorOptions options)
{
options.ValidationInterval = TimeSpan.FromSeconds(0);
}
}
```
and remember to register it somewhere: `services.ConfigureOptions<ConfigureSecurityStampValidatorOptions>();`
- Implement said …

Update security stamps on logout

---

src/Umbraco.Core/EmbeddedResources/Lang/hr.xml

Croatian language translation of Umbraco backoffice and culture settings. This language can be tested by changing language to Croatian on the user account page.

Add Croatian backoffice language

---

src/Umbraco.Core/Services/ContentService.cs

Fixes #14380
Adds the `ContentDeletingNotification` to `ContentService.EmptyRecycleBin()`.
To test:
1. Implement simple notification handler with composer like this:
```public class TestComposer : IComposer
{
{
builder.AddNotificationHandler<ContentDeletingNotification, ContentDeletingNotificationHandler>();
}
}
public class ContentDeletingNotificationHandler : INotificationHandler<ContentDeletingNotification>
{
public void Handle(ContentDeletingNotification notification)
{
notification.Cancel = true;
}
}
```
2. Create a new node.
3. Delete a node (move to the Recycle Bin).
4. Empty the Recycle Bin.
Expected result:
The `ContentDeletingNotification` should be triggered, and no nodes should be deleted, because we've cancelled the operation.
N.B. …

Add ContentDeletingNotification to EmptyRecycleBin

---

src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14324
Currently the configuration of richtext didn't show icons for toolbar buttons in configuration after upgrade of TinyMCE v4 to v6 since the old font icons has been replaced by SVG icons: https://www.tiny.cloud/docs/tinymce/6/editor-icon-identifiers/
Further some commands doesn't use icons equal to the alias, e.g. `hr` has the icon `horizontal-rule.svg`.
TinyMCE has as service to get a specific icon set, e.g. `tinymce.IconManager.get('default').icons` to load default icons, but without an instance it just returned an empty object.
In the backoffice rebuild we could use module loading to import the icons (and maybe custom icons):
https://www.tiny.cloud/docs/tinymce/6/bundling-icons/
A …

Show SVG icons for toolbar in configuration of richtext editor

---

src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoDeliveryApiSwaggerGenOptions.cs
src/Umbraco.Cms.Api.Delivery/Configuration/DeliveryApiConfiguration.cs
src/Umbraco.Cms.Api.Delivery/Filters/CommonSwaggerDocumentationFilter.cs
src/Umbraco.Cms.Api.Delivery/Filters/SwaggerDocumentationFilter.cs

- Adding missing query params and optional headers;
- Adding descriptions to params - links to our documentation;
- Adding examples to all our query params to showcase the build-in options.
Overall, making it easier for people to get started using the Delivery API through Swagger.
- Test our endpoints using Swagger;
- Make sure that you still get the correct response when executing `/content` with the newly set default values of params - just press "Try it out" and then "Execute" 😅 ; 
- Try using the examples for our query parameters or headers and make sure the responses from the API are correct;
- Try importing the collection in Postman (from **swagger.json** file in Swagger) and verify that the query params and headers are correctly added (_don't be surprised if you get lorem ipsum or …

Delivery API: Add query params and headers to Swagger document

---

src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Web.UI.Client/lib/markdown/markdown.editor.js
src/Umbraco.Web.UI.Client/src/views/dictionary/import.html

Fixed typo "optinal" to "optional" for translation dictionary import dialog and 2 other occurrences.
If there's an existing issue for this PR then this fixes #14401 
Using the Translation Dictionary import dialog, I noticed a small typo, the word in brackets should be "optional".
Searching the code, I found two other occurrences of the typo "optinal", so I have fixed those two also. I happen to be German, so I can confirm that the fix for the German translation file is correct.
Steps to confirm
- Go to Translation section (enable section for your user type if not enabled)
- Click the meatball icon (...) and select Import
- Select a file
- On the second page of the dialog, note the text in the brackets is corrected: "**Choose where to import dictionary items.** (optional)"

Fixed typo "optinal" to "optional" for translation dictionary import dialog

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.TelemetryProviders.cs
src/Umbraco.Infrastructure/Telemetry/Providers/DeliveryApiTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

Adds deliver API information to detailed telemetry. In particular, it adds two values: 
* DeliverApiEnabled - True if the delivery API is enabled
* DeliveryApiPublicAccess - True if public access is enabled.

V12: Add deliver api information to detailed telemetry

---

src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
src/Umbraco.Web.Common/Profiler/WebProfiler.cs
src/Umbraco.Web.Common/Profiler/WebProfilerHtml.cs
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj

Updated nuget packages
- OpenIddict from 4.4.0 to 4.5.0
- ASP.NET Core / .NET from 7.0.5 to 7.0.7
- MailKit from 4.0.0 to 4.1.0
- Serilog from 2.12.0 to 3.0.0
- Miniprofiler from 4.2.22 to 4.3.8 (Including nullable reference type issues fixed)
- HtmlAgilityPack from 1.11.46 to 1.11.48
- IPNetwork2 from 2.6.560 to 2.6.589
- System.Security.Cryptography.Pkcs from 7.0.1 to 7.0.2
- Smidge from 4.2.1 to 4.3.0
For tests projects only
- NUnit3TestAdapter from 4.4.2 to 4.5.0
- AngleSharp from 1.0.1 to 1.0.3

Updated nuget packages to latest versions

---

.github/README.md

Proposed review of the badges on the README file.
Currently, the badges don't look consistent and overflow to the next line. For the initial badges, this appeared fine, but with the addition of the Codespaces badge, it is larger and feels less consistent.
**Exhibit A**
I'm proposing that the badges could be shifted down to below the header, and tweaked for consistency - using the extra shields.io query parameters for cosmetic updates.
**Exhibit B**
The changes in detail...
- "Azure Pipelines" - changed to use [shields.io's Azure DevOps badge](https://shields.io/badges/azure-dev-ops-builds-job). Also updated to use the ["Umbraco CMS 9+" pipeline (`definitionId: 301`)](https://umbraco.visualstudio.com/Umbraco%20Cms/_build?definitionId=301), as it was previously pointing at `v8/contrib`.
- …

README badges review

---

src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13729
I added an obsolete attribute for the `ContentValueSetValidator` constructor.
I can't create a replacement constructor, because it will have an ambiguous signature.

Obsolete constructor with deprecated IScopeProvider

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MarkdownEditorValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MarkdownEditorValueConverterTests.cs

In the Delivery API, the markdown editor currently returns its value as a HTML transformed representation of the markdown.
This is likely less useful for headless consumption, so this PR ensures that the markdown editor always outputs the raw markdown.
1. Create some content with a markdown editor.
2. Fetch the content through the Delivery API.
3. Verify that the markdown editor value is raw markdown, not HTML.

Return raw markdown in the Delivery API

---

src/Umbraco.Cms.Api.Delivery/Controllers/ByRouteContentApiController.cs

- Make sure that the path parameter starts with a forward slash in all cases.
- Test the Get by path endpoint and verify that things work as expected:
- With and without passing any path;
- Also test with `"///"`.
- Get a node in Preview by path _(pass the preview path of the node - `/preview-GUID`)_;
- The node has to be Unpublished ❗ .

Delivery API: Ensure the path parameter starts with forward slash

---

src/Umbraco.Core/DeliveryApi/ApiContentBuilder.cs
src/Umbraco.Core/DeliveryApi/ApiContentBuilderBase.cs
src/Umbraco.Core/DeliveryApi/ApiContentResponseBuilder.cs
src/Umbraco.Core/Models/DeliveryApi/ApiContent.cs
src/Umbraco.Core/Models/DeliveryApi/ApiContentResponse.cs
src/Umbraco.Core/Models/DeliveryApi/IApiContent.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs

The Delivery API response does not contain any date metadata for published content. The Heartcore REST API (V2) does contain these (ref: https://docs.umbraco.com/umbraco-heartcore/api-documentation/content-delivery/content#get-by-id)
This PR includes create and update date in the API response.
Fetch some content through the Delivery API and verify that create and update dates are part of the response:

Add create and update dates to Delivery API response

---

src/Umbraco.Web.BackOffice/Controllers/MediaController.cs

- Fixes part of #13602;
- When the default Image type was removed from the permissions of a custom media type and replaced by another custom image type, the following error was returned - `"Failed: Cannot upload this file, the media type with alias 'Image' is not allowed here".`;
- If we couldn't interpret the type on drag and drop, and the file extension was part of the supported Image formats - we were always defaulting to `Constants.Conventions.MediaTypes.Image` type;
-  Now, we will check if the default Image type is **part of the allowed content types** and if not, we will try to find the first **custom type with an Image Cropper**.
- In Settings > Media Types create a copy of Image called "Custom Image" under Media Types.  
- Change the icon, so your custom types are easily …

Auto-detect custom Image type on drag and drop

---

src/Umbraco.Web.BackOffice/Controllers/MediaController.cs

- Backend fix for #14310;
- The frontend on **Umbraco 10** is broken for this use case - additional fixes are required to close #14310 as completed;
- No error shown in the backoffice and error in the console:
- In **Umbraco 11**, there is an error in the backoffice, but there is still an error in the console, that has to be handled:
- In appsettings.json add the following configuration:
```json
"CMS": {
"RuntimeMinification": {
"UseInMemoryCache": true,
"CacheBuster": "Timestamp"
},
"Runtime": {
"MaxQueryStringLength": 90,
"MaxRequestLength": 1000
}
}
```
- Upload a file smaller than 1000KB and verify that there are no errors;
- Upload a file **bigger** than 1000KB and verify that you get a Request error Not Found (try that a couple of times);
- There will be some console errors, but we …

Handle upload error when file size is bigger than the configured value

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml

Umbraco's `umbNodePreview` directive supports a change action, but the label doesn't have a Danish translation, so it falls back to the English **Change**, which can seem a bit odd to the user as the other labels related to `umbNodePreview` are translated.
This PR therefore adds a the `general_change` key the Danish language file (`da.xml`) with the value **Skift**.
The key is actually also missing in the English language file (`en_us.xml`), but the English label is still showed correctly as a fallback label is specified in the Angular view. So this PR also adds the `general_change` key to `en_us.xml` with the value **Change**. This way, it should hopefully be easier to see that the translation is missing in other languages.

Added missing Danish translation for `general_change`

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataType.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataTypeFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Dictionary/Dictionary.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Language/Language.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/PartialView/PartialView.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/PartialView/PartialViewFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Script/Script.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Script/ScriptFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/Stylesheet.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/StylesheetFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Template/Template.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/TemporaryFile/TemporaryFile.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/User/User.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/User/UserAvatar.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/UserGroup/UserGroup.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Telemetry.spec.ts

Updated our API acceptance tests to use our updated testHelpers. With our updated testHelpers we are able to have a more API like approach to these test

Updated our API acceptance tests to use our updated testHelpers

---

src/Umbraco.Cms.Api.Management/Controllers/AuditLog/CurrentUserAuditLogController.cs
src/Umbraco.Cms.Api.Management/Controllers/Help/GetHelpController.cs
src/Umbraco.Cms.Api.Management/Controllers/Indexer/AllIndexerController.cs
src/Umbraco.Cms.Api.Management/Controllers/PropertyType/IsUsedPropertyTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/ByKeyRedirectUrlManagementController.cs
src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/GetAllRedirectUrlManagementController.cs
src/Umbraco.Cms.Api.Management/Controllers/Relation/ByChildRelationController.cs
src/Umbraco.Cms.Api.Management/Controllers/Searcher/AllSearcherController.cs
src/Umbraco.Cms.Api.Management/Controllers/Searcher/QuerySearcherController.cs
src/Umbraco.Cms.Api.Management/Controllers/Telemetry/AllTelemetryController.cs
src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ByIdTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/DescendantsTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ItemsTrackedReferenceController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json

- Aligning on `skip` and `take` for pagination between our controllers.
> **Note**
> At the moment, some controllers don't allow for: _for example `?skip=1&take=100`_, because we have to refactor our services to work with `skip` and `take` instead of `pageNumber` and `pageSize`; </br> Like:
> - /**audit-log**?skip=1&take=100 - throws 500 error;
> - /**culture**?skip=1&take=100 - works.
- The changes aren't really changing the functional behaviour so there isn't really anything to test...
- Maybe just verify that `/audit-log` endpoint (_CurrentUserAuditLogController.cs_) works as expected, with the correct skip and take relation, (like `skip = 4, take = 2`, or `skip = 10, take = 5`) as there used to be double pagination. 😉

V14: Skip and take updates

---

src/Umbraco.Core/Models/ContentEditing/ContentVariationDisplay.cs
src/Umbraco.Core/Models/ContentEditing/NamedUrl.cs
src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs

This PR adds the server modelling to have additional preview URLs for content.
The intended use for this feature is when using external preview environments for the Delivery API.
This PR does not include the UI handling of additional preview URLs - this will come at a later time.
We won't be building a management UI for external preview environments in v12. This will come after v14. For the time being, one must utilize the `SendingContentNotification` to pass additional preview URLs to the client.
Try adding a `SendingContentNotification` notification handler like this:
```csharp
using Umbraco.Cms.Core.Models.ContentEditing;
using Umbraco.Cms.Core.PublishedCache;
namespace …
```

Add additional preview URLs option

---

src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web/Editors/ImagesController.cs
src/Umbraco.Web/Editors/TinyMceController.cs

This updates v8 with the latest bug fixes from v10 that we were able to cherry-pick regarding the TinyMCE editor and related media handlers.
- Drag & Drop images will now correctly call the imageProcessHandler and get a temporary file location for the image to append to a data attribute. If this process fails, TinyMCE will revert to storing the image as base64 which can get rather large, so this fix is very important.
- Resizing images will now call a new endpoint to get an updated crop URL to use in the editor ensuring, that we not only set width & height on the `img` element but also reflect that in the URL.
- Sometimes the rich text editor could not be activated on a grid editor if the id started with a number, which is not supported in HTML out-of-the-box, but by wrapping the selector …

V8: TinyMCE - Images upload, drag & drop, and resize

---

src/Umbraco.Cms.Api.Management/Controllers/User/CreateInitialPasswordUserController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/UsersControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/User/VerifyInviteUsersController.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/CreateInitialPasswordUserRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/VerifyInviteUserRequestModel.cs
src/Umbraco.Core/Security/ICoreBackOfficeUserManager.cs
src/Umbraco.Core/Services/IUserService.cs
src/Umbraco.Core/Services/OperationStatus/UserOperationStatus.cs
src/Umbraco.Core/Services/UserService.cs
src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs
src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs

This PR adds two new endpoints
- `/umbraco/management/api/v1/user/invite/verify`
- Used to verify the token. The intension is that the frontend can check this as soon as the link from the email is used.
If the token is not valid there is no need to ask the user to create a password 
- `/umbraco/management/api/v1/user/invite/create-password`
- Used to set an initial password using the token.
- The generated email + link is out of scope of this PR
- Use the existing endpoint to invite a user (`/umbraco/management/api/v1/user/invite`)
- Remember to setup a fake SMTP and get the link from the email
- Read the email and copy the token from the link
- A link could look like this: `https://localhost:44339/umbraco/VerifyInvite?invite=1%257CQ2ZESjhHQXdva3dCb1N0RXEzSDVOdklWVWJ2aXpMRnlzRDVpRGxENVJGck …

Verify user invite token

---

src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-sub-views.html

Fixes #13134 
Render all tabs in the background by replacing `ng-if` with `ng-show`. This ensures they register their initial state on any `$scope.model` in the stack.
Sometimes a tab, e.g. a "block list settings model" might register some default values, but if the user never clicks on the tab, then they are not recorded because of the way AngularJS renders views with "ng-if".
The history of this file is as follows:
- Initially, we had `ng-show` on the _inner sub_view_content_. This must have worked for blocks as well as other tabs for content.
- Due to being able to show certain tabs in full height (the new Marketplace initially), we had to remove the superfluous HTML and moved the `ng-show` to the _outer element_ and changed it to an `ng-if`
- This change semi-reverts it back to an …

V12: Tabs should be rendered to register default values

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html

As we start getting more blocks in Block List /  Block Grid editor and thus creating several groups, we may end up with empty groups when filtering these in block picker.
I think it is cleaner only to show each group, which has any filtered result - currently it check filtered results in any group (or non-grouped blocks).
I also updated search term filtering to be consistent with other freetext filtering, where we have a `searchTerm` as property on a `filter` object.
**Result**
https://github.com/umbraco/Umbraco-CMS/assets/2919859/2625063a-a4f3-49c1-934e-b235088cd709

Only show groups when any filtered results in group

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_7_0/MigrateTagsFromNVarcharToNText.cs
src/Umbraco.Infrastructure/PropertyEditors/TagsPropertyEditor.cs

- Fixes: #14457;
- Changing the `Umbraco.Tags` property editor to explicitly use the `"TEXT"` value type instead of the implicit (default) `"STRING"`:
- Setting the db type for `Umbraco.Tags` to `NText` database type;
- By doing so, we remove the limit (_512_) on the amount of the data allowed to be filled in for this property editor;
- This is the case with both Tags storage types - _JSON or CSV_;
- Previously, the CSV storage type, changed the db type to `STRING` which mapped to `NVarchar`.
- Adding a migration that moves the Tags data from the `umbracoPropertyData.varcharValue` column to the `umbracoPropertyData.textValue` column, while also sets the `umbracoDataType.dbType` for the Tags prop editor to `NText`.
- Test on both SQLite and SQL Server;
- Test with both a clean install and …

Store tags as text (instead of nvarchar)

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorAdvanced.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorAreasContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorRendering.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorSettings.spec.ts

Removed usage of umbracoApi in testhelpers. We had to clean up some of our test so they use the updated testhelpers

Removed usage of sending umbracoApi to our testHelpers

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js

This PR fixes some issues in Block Grid configuration, which was fixed in Block List configuration, but never included in the Block Grid configuration.
Previous PR https://github.com/umbraco/Umbraco-CMS/pull/12851 fixes issues, where blocks couldn't be removed/deleted using keyboard.
This PR fixes issues deleting/removed blocks from Block Grid configuration using keyboard, which is possible in Block List configuration.
https://github.com/umbraco/Umbraco-CMS/assets/2919859/6e5d9a1c-5058-4f6d-a268-ac274f80e98a
There is still an issue with focus/outline, when a block as both area and delete button as the outline is on the actions element, so keyboard focus on the two button, but it isn't clear which button has focus.
Should be fixed in another PR.

Make it possible to remove blocks using tab key in block grid configuration

---

src/JsonSchema/AppSettings.cs

Issue was raised in discussion [here](https://github.com/umbraco/Umbraco-CMS/discussions/14431#discussioncomment-6356476).
Currently the JSON schema generated for the configuration of default install data uses an incorrect property name.  This PR updates it to align with [what is referenced in the documentation](https://docs.umbraco.com/umbraco-cms/reference/configuration/installdefaultdatasettings) and [used in configuration](https://github.com/umbraco/Umbraco-CMS/blob/0c595ccc5f88750a8f547e4bbbe58c457864094d/src/Umbraco.Core/Constants-Configuration.cs#L64).
To Test:
- Check out the PR and run the `JsonSchema` project.
- Open the generated file `appsettings-schema.json`.
- Confirm reference to configuration setting `InstallDefaultData`:
- Copy file into an Umbraco 10 project running in …

Fixes an incorrect property name used for generating JSON schema.

---

src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/Controllers/ContentControllerTests.cs
tests/Umbraco.Tests.Integration/appsettings.Tests.json

Due to troublesome CPU spikes when encountering base64 images, this PR brings a feature that will persist embedded images found in rich text as files in the Media library similar to what we are doing with drag & drop images.

V10: Find and persist embedded images in rich text

---

src/Umbraco.Cms.Api.Common/Serialization/UmbracoJsonTypeInfoResolver.cs
src/Umbraco.Cms.Api.Management/Configuration/ConfigureUmbracoManagementApiSwaggerGenOptions.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs

This fixes the pipelines after #14512
Interestingly it wasn't actually that PR that broke the pipelines, it was sometime before that. Nonetheless, I found that the reason was that for some reason the types found by our typefinder were different on the pipeline. This made our tests fail, because it changed the order of the `oneOff` list in the generate openapi spec. I've fixed this by ordering the found types. 
Testing: The integration tests need to pass

V14: Fix pipelines

---

src/Umbraco.Core/Scoping/CoreScope.cs
src/Umbraco.Infrastructure/Scoping/Scope.cs

Resolves: https://github.com/umbraco/Umbraco-CMS/issues/14572
This PR restored order of operations on scope dispose to that used in Umbraco 11 before refactor into Scope inheriting CoreScope.
Can be tested to confirm it resolves a specific issue with Deploy 12 as noted in the issue, but primarily this needs a visual inspections for any oversights.

Restored order of operations on scope dispose to that used in Umbraco 11 before refactor into Scope inheriting CoreScope.

---

src/Umbraco.Web.UI.Client/src/less/rte-content.less

#14325 - Remove wildcard-background from RTE
Related issue:
https://github.com/umbraco/Umbraco-CMS/issues/14325

#14325 - Remove wildcard-background from RTE

---

src/Umbraco.Core/Services/NotificationService.cs

Suppresses the execution context flow when queuing a task for sending notification emails. This is required because otherwise, the execution context would leak into the async thread that won't be joined. 
This caused issues when trying to replace the `IEmailSender` with a different implementation that creates a scope since the execution context was flowed, it gets added to the same scope stack as the other thread, leading to race conditions that would throw errors because a child scope on the other thread wasn't disposed. This should no longer happen.
It looks like there's a lot of changes in the PR, but all I did was wrapping the implementation of `NotificationService.Process` in a `using (ExecutionContext.SuppressFlow())` block.
Since this is essentially a race condition it's pretty …

V12: Suppress execution context flow when queuing email task

---

tests/Umbraco.Tests.UnitTests/Umbraco.Core/Collections/TopoGraphTests.cs

We realised there's an implementation of a "directed acyclic graph" in both CMS and Deploy, in the form of the class `TopoGraph`.  My guess is that at some point it was extracted out of Deploy, tidied up, and used in the CMS - as they are the same other than some formatting and messaging.
We plan to obsolete/remote the one in Deploy and use the one in CMS.
However I realised that the tests we have for this in Deploy aren't in CMS, and so rather than removing them added them here so they can continue to verify the behaviour of this class.
To test - just confirm the tests pass.

Added tests for TopoGraph.

---

src/JsonSchema/AppSettings.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs

Part two of [this PR](https://github.com/umbraco/Umbraco-CMS/pull/14542).  Sorry @nikolajlauridsen... I missed pushing a commit from the last one.
The previous PR fixed the name used in configuration, and in this update I've also added schema/Intellisense support for the dictionary keys (e.g. "Language", "DataTypes") found within this configuration section.
Also resolved a comment from the last PR related to a private variable name.
To Test:
- See linked PR.

Extends JSON schema/Intellisense to full details of InstallDefaultData settings.

---

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/ConvertRelatedLinksToMultiUrlPicker.cs

Added a check for null `RelatedLink` objects while converting `RelatedLinks` and `RelatedLinks2` properties to `MultiUrlPicker` during the database migration process.
Without this check, it's possible under certain (unknown) circumstances for a `NullReferenceException` to occur on line 64.
Steps to test this contribution:
1. Create an Umbraco v7.15.10 project
2. Add a document type that uses a `RelatedLinks2` editor
3. Add some content that uses said document type, some with related links left blank and others with a variation of internal pages and external links
4. Perform a database migration to Umbraco v8.18.8
To be clear, I am not 100% sure what the root cause of this issue was in the first place - it seems to be undocumented otherwise, and I was not able to find any anomalies in my …

v8: Null check for RelatedLinks during migration from v7

---

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js
src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html

Fixes #14310 by adapting the changes of #14578 to V12.
- **Media library -** Check if `file.$error` is present before trying to upload the file.
- **Rich Text Editor -** Check for maxFileSize before attempting an upload (drag & drop)
- **Image Cropper -** Check for maxFileSize before attempting an upload (select, drag&drop)

V12: Dropzone should handle internal and external errors when uploading

---

src/Umbraco.Infrastructure/PropertyEditors/GridPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs

Fix issue #14556 by changing the method invocation for `Rich Text Editor` and `Grid Legacy` property editors.

Fix method invoke.

---

src/Umbraco.Core/EmbeddedResources/Lang/nl.xml

Fix wrong translation in Dutch language file. Change 'comment' to 'Commentaar'

Change 'Comment' to 'Commentaar' in Dutch translation file

---

src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-tab.html

… to avoid server error due character lenth in database.
If creating a tab with more than 255 characters (yeah I know it's a pretty long tab name and probably never happen in real world use-case - I hope not 😅) it would cause a server error due the maximum length in database, where the column length is 255 characters. 
It is similar issue in node name, where we have `maxlength="255"` set, so let's make this consistent.

Set max length of text input in tab creation

---

src/Umbraco.Core/PropertyEditors/SliderConfiguration.cs
src/Umbraco.Core/PropertyEditors/SliderConfigurationEditor.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14591
A negative value for the Slider step increments can crash the entire back-office. Unfortunately we can't limit the "number" prevalue editor to only positive values. Thus we have to be reactive instead, before the misconfiguration is applied.
This PR explicitly forces a step increment value of `1` if it's configured to a negative value - no matter what the configured negative value actually is. Likely the functionally correct thing would be to invert the configured value to its positive counterpart. However, this hardcoded `1` value will hopefully point people in the direction of their misconfiguration to fix it.
To further aid people configuring the Slider, I have added some field …

Ensure that the Slider does not crash the back-office

---

src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-group.html
src/Umbraco.Web.UI.Client/src/views/components/contenttype/umb-content-type-tab.html

This PR replaces a few ` data-lpignore="true"` I noticed with the `no-password-manager` added a while ago, which handle this https://github.com/umbraco/Umbraco-CMS/blob/1527b2577e7273157cfede70444c65f838a87225/src/Umbraco.Web.UI.Client/src/common/directives/util/noPasswordManager.directive.js#L21
but also other password managers in case added later.

Replace attribute with `noPasswordManager` directive

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-area-allowance-editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-area-allowance-editor.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-area-editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-configuration-area-entry.html

This PR fixes a few issues in block grid area allowance editor, e.g. outline of delete button mentioned here https://github.com/umbraco/Umbraco-CMS/pull/14518#issuecomment-1624417702 which was because of the custom `umb-outline` class and that the button didn't had `position: relative` and it position the outline absolute https://github.com/umbraco/Umbraco-CMS/blob/a936fe09ab9c9c36130d5f8468dd21143ca39dc5/src/Umbraco.Web.UI.Client/src/less/application/umb-outline.less#L10, so the closest relative element was the parent container.
actually I am not sure why we have this?
https://github.com/umbraco/Umbraco-CMS/blob/a936fe09ab9c9c36130d5f8468dd21143ca39dc5/src/Umbraco.Web.UI.Client/src/less/modals.less#L122-L124
why not always …

Block grid area allowance editor

---

src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js

Fixes #14190 
I'm not a frontender. This was labeled as a backend issue. 
But while debugging it appeared that the request payload was wrong.
Anyways..
Feel free to leave suggestions for better code solutions.
The SendToPublish would only the active culture to save = true.
That's why only one language showed up in the audit log. 
- Remove setting the active variant to true
- Disabled sent to approval button as default as no items are selected by default. (I'm not experienced enough in frontend to select the active variant by default :( )
- Updated changeSelection function to add selected variants to array and set save for those variants to true
- Updated changeSelection function to remove unselected variants from array and set save to false for those variants
- Go to user groups and allow …

#14190: Save all languages sent to approval in audit log

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

Fixes #14198 
When using an external authentication method to sign in to Umbraco back office the `returnUrl` is checked if it's absolute and if so (disallowed) resets it to the start page. The check was incorrect though and resulted in every redirectUrl being reset so the redirect url was never honored. (`Uri.TryCreate` would create an absolute `file://` uri out of anything it got).
NOTE: I would use `IUrlHelper.IsLocalUrl` but it's not available to me and the only difference is it will allow `~/` as well, and it's not relevant here.

Fix incorrect redirectUrl check with external authentication (#14198)

---

src/Umbraco.Web.UI.Client/src/common/directives/util/noPasswordManager.directive.js
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

After my comment in https://github.com/umbraco/Umbraco-CMS/pull/14593#issuecomment-1651962698 I investigated this further and came across the thread started by @greystate here https://1password.community/discussion/117501/as-a-web-developer-how-can-i-disable-1password-filling-for-a-specific-field
I have come across that previously, but nothing seemed to happen besides hacky workaround like changing input type to e.g. `search` input type, which was a terrible idea.
But after several years it seems they finally went with the `data-*` attribute solution as well: https://1password.community/discussion/comment/677269/#Comment_677269
and even documented here: https://developer.1password.com/docs/web/compatible-website-design/#build-logical-forms
**Before**
**After**
I noticed 1Password was also …

Ignore 1Password as well in `noPasswordManager` directive

---

src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html

I noticed we only have the legacy media picker as macro parameter editor. I think we should have a macro parameter editor to allow using Media Picker 3 instead of the legacy  media picker, because when/if `Umbraco.MediaPicker` and `Umbraco.MultipleMediaPicker` at some point are removed the macro parameter editors will stop working or be removed as well.
By default it use default configuration of property editor, but we could create more specific macro parameter editors.
In the screenshot above I also have this following, but it including this we probably don't need the pipe syntax to enable the property editor as macro parameter (using default configuration) as we explicit create a macro parameter editor.
```
using …
```

Allow Media Picker 3 to be used as macro parameter editor

---

src/Umbraco.Web.UI.Client/gulp/config.js
src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/icons.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridblock/gridblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridinlineblock/gridinlineblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridsortblock/gridsortblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/unsupportedblock/unsupportedblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14614
When rendering icons inside `<umb-block-grid-root>` and `<umb-block-grid-block>` it only rendered SVG icons and not legacy font icons like `icon-science` which doesn't have a SVG version here: https://github.com/umbraco/Umbraco-CMS/tree/contrib/src/Umbraco.Web.UI.Client/src/assets/icons
We should probably also add `icon-science.svg`, but font icons are still supported and developers may still use custom font icons (font packages) although SVG icons are the modern approach.
The PR also remove some redundant style if we sometime later need to adjust style of `<umb-icon>` component, this ensure icons in block grid are consistent. 
In the block grid view we probably need to adjust the …

Compile css for icons style

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs

Add a simple extension method so that it's possible to register MapDefinitions directly from the Startup.cs class. 
Steps to test:

AddMapDefinition Extension Method

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridblock/gridblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridinlineblock/gridinlineblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridsortblock/gridsortblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/unsupportedblock/unsupportedblock.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridblock.component.js

Follow up on https://github.com/umbraco/Umbraco-CMS/pull/14615
Injecting icons CSS via Shadow DOM in block grid block with cache buster.

Add cache buster to injected icons CSS in block grid

---

src/Umbraco.Core/Events/EventAggregator.Notifications.cs
src/Umbraco.Core/Events/EventAggregator.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14574
Adds missing async-awaits on async methods related to async notifications.
- See description on https://github.com/umbraco/Umbraco-CMS/issues/14574

Fixed issue with disposed objects in async notifications

---

src/Umbraco.Web.BackOffice/Controllers/UsersController.cs

Allow newlines in invite email body.
- Invite a user (Requires SMTP to be setup)
- Use message with new lines (Ensure replaced with html in mail)
- Use message with html (Ensure encoded)

Allow newlines in invite emails

---

src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/es.xml
src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
src/Umbraco.Core/EmbeddedResources/Lang/it.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
src/Umbraco.Core/EmbeddedResources/Lang/ua.xml
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html

Resolves #13727
The avatar screen on the user invite flow on the login page has not worked since around the release of v10. There have been a lot of issues around uploading on the login screen, and it is a potential attack vector, so we have decided to remove the avatar step altogether.
Instead of landing on "step 2: upload avatar" the invite form will now be hidden and you will be redirected to the backoffice shortly thereafter when the app has been initialized:
https://github.com/umbraco/Umbraco-CMS/assets/752371/c6b07289-1481-4182-9fc0-c5adc5a7d177

V12: Remove avatar step from login

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html

I noticed in health check dashboard, when warnings are shown the alert color is yellow and too low contract with the white background color.
In the overview boxes it did use the orange color though.
With changes in this PR:

Fix color of warning icon in health check dashboard

---

src/JsonSchema/AppSettings.cs
src/Umbraco.Core/Configuration/Models/IndexCreatorSettings.cs
src/Umbraco.Core/Configuration/Models/IndexingSettings.cs
src/Umbraco.Core/Constants-Configuration.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs

Added new configuration "Umbraco:CMS:Examine:ExplicitlyIndexEachNestedProperty" that can be used to avoid nested properties like block grid to index each property individually.
- Create content with at least one each of these:
- Block list
- Block grid
- Tags
- Nested Content
- Set `Umbraco:CMS:Indexing:ExplicitlyIndexEachNestedProperty` to `false`
- Verify nested properties are not index, but only available in the summary
- Set `Umbraco:CMS:Indexing:ExplicitlyIndexEachNestedProperty` to `true` (default value)
- Verify everything is indexed like before.

Add config so it is configurable whether to explicitly index each nested property

---

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs

#14433 
Bugfix 31584 - Remove Lazy "caching" that retains keys of deleted Content Types which causes unnecessary validation errors
The validation errors should not happen as the model mapping cleans up block data for entity types that do not longer exist (which is checked on the aforementioned key)
- Create an element doctype named "Asset" with any number of properties
- Create a datatype named "BL - Assets" with property editor "Block List" and add the "Asset" element type to the available blocks
- Create a datatype named "BG - Assets" with property editor "Block Grid" and add the "Asset" element type to the available blocks
- Create an element doctype named "Assets" with a single property named "items" of datatype "BG - Assets"
- Create a datatype named "Grid" with property editor …

Fix Switching property from Block Grid to Block List errors

---

src/Umbraco.Infrastructure/Models/Mapping/EntityMapDefinition.cs
src/Umbraco.Infrastructure/Search/UmbracoTreeSearcherFields.cs
src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-results.html

If there's an existing issue for this PR then this fixes #14590
This adds the 0.6 opacity on nodes that are not published
To test create a multi-node tree picker and have som content that is published and not published and try searching for it. The unpublished content will show as more transparent.

feat: Show published state in tree picker

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14654
Since description for composition is used for both document, media and now member type as well, we should use the generic term "Content Type".

Use generic Content Type instead of Document Type

---

src/Umbraco.Core/Services/ContentService.cs

This PR corrects the user id passed to the Audit log.
Here the user id was for some reason set to 0 which isn't a valid user id in modern Umbraco see #14639
In the best-case scenario, this would anyway audit the incorrect user id.
I've also updated the message to include the content ids as these are not passed in Node id thereby making it easier to track.
Here I've changed the id to come from `userId` like the statement just above it.
Here the super user id was passed instead of the user id argument.

fix: Pass correct user id to Audit log

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/DataTypeFolderControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/CreateUserGroupController.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/UpdateUserGroupController.cs
src/Umbraco.Core/Services/IPartialViewService.cs
src/Umbraco.Core/Services/IScriptService.cs
src/Umbraco.Core/Services/IStylesheetService.cs
src/Umbraco.Core/Services/IUserGroupService.cs
src/Umbraco.Core/Services/IUserService.cs
src/Umbraco.Core/Services/PartialViewService.cs
src/Umbraco.Core/Services/ScriptService.cs
src/Umbraco.Core/Services/StylesheetService.cs
src/Umbraco.Core/Services/UserGroupService.cs
src/Umbraco.Core/Services/UserService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserGroupServiceValidationTests.cs

Ensures that the key of the performing user is always referred to simply as `userKey` in service method signatures. 
It's worth noting that it still exists some places, like in the audit table schema, but for any new service methods it has been aligned.
Ensure tests pass

V14: Consistently refer to user key

---

build/azure-pipelines.yml
tests/Umbraco.Tests.AcceptanceTest/misc/umbraco-linux.docker

Updated the name of the Acceptance test project. The reason we did this is that we encountered an error on the pipeline which mentioned the former name 'Playwright', we ended up going back and forth since we thought the issue was with playwright itself and not the namespace of the Acceptance test project.
Test: 
- Go into the pipeline.
- Click on the 'E2E Tests'
- Go to step  'E2E Test Linux'
- Go to Build and run container (Linux only)
- Check if the command for creating the Umbraco Project looks like this:
- `dotnet new umbraco --name AcceptanceTestProject --no-restore --output .`
- Go to step 'E2E Test Windows'
- Go to Build and run container (Windows only)
- Check if the 'AcceptanceTestProject.csproj ' was restored (Should be on line 32).

Updated the name of our Acceptance test project in the pipeline

---

src/Umbraco.Core/Extensions/TypeExtensions.cs
src/Umbraco.Web.BackOffice/ModelsBuilder/ContentTypeModelValidatorBase.cs

It is currently possible to define content type properties with aliases that conflict with `IPublishedElement` properties - e.g. `ContentType` and `Properties`. This becomes a problem when ModelsBuilder creates strongly typed models:
We're already trying to avoid this scenario in the server side validation. However, we're only testing for properties and methods defined on `IPublishedContent`.
With this PR we also test properties from base interfaces like `IPublishedElement`. Now we can no longer create properties with clashing aliases:
Note that the `TypeExtensions` changes in this PR have been copied over from similar changes in a V14 PR, thus adding more new extension methods than strictly necessary for this PR. This hopefully will make forward merging easier 😄

Do not allow content type property aliases that conflict with IPublishedElement

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/14649
Ensures Labels of Blocks of any Block Editor are rendered though their label does not contain any AngularJS Template code.

Fixes #14649 - Ensure rendering of labels with no angularJS template code

---

src/Umbraco.Core/Services/NotificationService.cs

I was looking at what a call tree is for running the `ContentService.SaveAndPublish` and noticed that we in `NotificationService` make an unnecessary call to `GetNextUsers` that in some cases can be pretty expensive:
_Note: this was captured in Debug mode so don't get too caught up on the specific numbers_
[New Item `SaveAndPublish`]
[2. `SaveAndPublish` on same item]
From what I can see in 
https://github.com/umbraco/Umbraco-CMS/blob/0edee82b0b92876ef336a04fa82eb48832302523/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/NotificationsRepository.cs#L20C78-L20C85
We don't even use the UserIds in the query so therefore we don't need to fetch them unless there's actually a user notification which there isn't if you're …

perf: Don't call GetNextUsers when we don't have to

---

src/Umbraco.Core/PropertyEditors/ValueConverters/SliderValueConverter.cs

This is a proposed amend to #13782 
During testing, I noticed that if you went from a range slider to a non-range slider, the slider value changed to the two values combined and parsed to a double. 
This PR fixes this by using the same approach as when going from a non-range slider to a range slider, that is we check if there is a `,` in the value, and if there is we assume we're going from a ranger slider to a non-range slider, and pick the minimum level.
While I was at it, I also refactored the code a bit to make it easier to work with and understand.
Follow the testing steps from the PR, but try and go from a range slider to a non-range slider, the value presented should be the minimum value.

Fixup: Handle converting from slider to single value

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CreatedPackageSchemaRepository.cs
src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs

Added missing scopes for saving/updating a package
Test:
1. Create a package
2. Update the package
3. Save the package

V14 bugfix. added missing package  scope

---

src/Umbraco.Core/Composing/TypeFinder.cs

When running tests in the JetBrains Rider IDE in a project that calls `.AddUmbraco()`, a `System.IO.FileNotFoundException` is thrown, with an assembly loading error mentioning `ReSharperTestRunner64` not being found. Seems like Umbraco is processing all loaded assemblies in a way that fails when this one is present. By following the stack trace, I noticed that `TypeFinder` already has a "32" version of the assembly name in its exclusion list, so this PR adds the "64" version, which I believe should fix the issue.
Whether this issue is triggered on a given setup probably depends on stuff like OS and Rider version. But I assume one could reproduce by installing the latest version of JetBrains Rider on a 64-bit Windows machine, setting up a new Umbraco project with a test, and finally run …

Add ReSharperTestRunner64 to the assembly exclusion list in TypeFinder

---

src/Umbraco.Infrastructure/Persistence/Factories/UserGroupFactory.cs

Fixes #14690
I think this have been some legacy from sometime in the past where the ids have been a short. Should not be necessary for V10+ at least

Do not parse short into integer

---

src/Umbraco.Cms.Api.Management/Content/ContentControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/SortDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/SortMediaController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Sorting/ItemSortingRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Sorting/SortingRequestModel.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Models/ContentEditing/SortingModel.cs
src/Umbraco.Core/Services/ContentEditingService.cs
src/Umbraco.Core/Services/ContentEditingServiceBase.cs
src/Umbraco.Core/Services/IContentEditingService.cs
src/Umbraco.Core/Services/IMediaEditingService.cs
src/Umbraco.Core/Services/ITreeEntitySortingService.cs
src/Umbraco.Core/Services/MediaEditingService.cs
src/Umbraco.Core/Services/OperationStatus/ContentEditingOperationStatus.cs
src/Umbraco.Core/Services/TreeEntitySortingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.MoveToRecyleBin.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Sort.cs
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/TreeEntitySortingServiceTests.cs

This PR adds content and media sorting to the Management API.
The new endpoints are:
- `/umbraco/management/api/v1.0/document/sort` 
- `/umbraco/management/api/v1.0/media/sort` 
When sorting in the current backoffice, the IDs and updated sort order of all items being sorted are passed to the server as part of the sort update request. This scales really badly, and efficiently makes sorting impossible for large datasets, because all items must be loaded on the client in order to perform the sort.
In the Management API we're going to take a different approach. Here we're _only_ passing the IDs and updated sort order of those items we changed to the server. The server then has to figure out the rest.
Considering this sorting operation:
The sorting request would look like this:
```
POST …
```

Add content and media sorting to the Management API

---

src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
src/Umbraco.Core/Security/FileStreamSecurityValidator.cs
src/Umbraco.Core/Security/IFileStreamSecurityAnalyzer.cs
src/Umbraco.Core/Security/IFileStreamSecurityValidator.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
src/Umbraco.Tests/Security/FileStreamSecurityValidatorTests.cs
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
src/Umbraco.Web/Editors/CurrentUserController.cs
src/Umbraco.Web/Editors/MediaController.cs
src/Umbraco.Web/Editors/UsersController.cs
src/Umbraco.Web/PropertyEditors/FileUploadPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/FileUploadPropertyValueEditor.cs
src/Umbraco.Web/PropertyEditors/ImageCropperPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/ImageCropperPropertyValueEditor.cs

See #14657 for details
Registering the testing implementation looks like this in V8:
```C#
class MyComp : IComposer
{
public void Compose(Composition composition)
{
composition.Register(typeof(IFileStreamSecurityAnalyzer), typeof(SvgXssSecurityAnalyzer), Lifetime.Transient);
}
}
```

Backport #14657 to V8

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs

This is currently returning an incorrect type, as you can see in the `ConvertIntermediateToDeliveryApiObject` it returns an `ApiBlockListModel` and not an `IEnumerable`.

Fixed incorrect BlockListPropertyValueConverter delivery api property value type

---

src/Umbraco.Core/Models/DeliveryApi/ApiElement.cs
src/Umbraco.Core/Models/DeliveryApi/IApiElement.cs

This is needed so the `ContentType` property can be used as a discriminator field by System.Text.Json.
You can read more about it here: https://github.com/dotnet/runtime/issues/72604
Changed both ApiElement and IApiElement to ensure not only ApiContentResponse, but also ApiBlockItem, which uses the interface directly, are adjusted.

DeliveryApi: Ensure the ContentType property is serialized first

---

src/Umbraco.Cms.Api.Management/Controllers/User/BulkDeleteUsersController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/DeleteUsersController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/UsersControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/BulkDeleteUserGroupsController.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/DeleteUsersRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/DisableUserRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/DeleteUserGroupsRequestModel.cs
src/Umbraco.Core/Notifications/UserGroupDeletedNotification.cs
src/Umbraco.Core/Services/IUserGroupService.cs
src/Umbraco.Core/Services/IUserService.cs
src/Umbraco.Core/Services/OperationStatus/UserGroupOperationStatus.cs
src/Umbraco.Core/Services/OperationStatus/UserOperationStatus.cs
src/Umbraco.Core/Services/UserGroupService.cs
src/Umbraco.Core/Services/UserService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Delete.cs

Added missing bulk delete method on users and user groups.
- Ensure the original delele single user still works.
- Ensure the original delele single user groups still works.
- Ensure the new endpoint bulk works as expected

Bulk delete functionality for management api

---

src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs

Umbraco added unattended upgrades in v8.12, which has always been an opt-in feature (see PR https://github.com/umbraco/Umbraco-CMS/pull/9531 and [docs](https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/general-v8#run-an-unattended-upgrade)).
When left disabled, you'll get the `AuthorizeUpgrade` login screen when there are pending database migrations after updating to a newer version, requiring a user to login and manually approve the upgrade. This means all site visitors are redirected to the login screen, until this manual approval is performed.
This manual step seems redundant, as you already explicitly updated the site to a newer version and it previously also opened up the site to a [medium-severity security issue](https://umbraco.com/blog/security-advisory-september-6 …

Change default `UpgradeUnattended` value to true

---

src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs
templates/UmbracoProject/appsettings.json

Reverts #13281 and only sets the `UpgradeUnattended` value to true for new projects (when using the updated `dotnet new umbraco` project template in `Umbraco.Templates`).
After a quick internal discussion, we agreed on only changing default setting values in new major versions and otherwise only add the new value in the project template (so it only affects new projects and the updated value is more visible, since it's explicitly set).
This PR should be merged for the 12.2.0 release (to ensure the default value is reverted). After merging everything to `v13/dev`, we can revert this PR again, so only the next major will have unattended upgrades enabled by default.

Revert #13281 and only set `UpgradeUnattended` value to true for new projects

---

src/Umbraco.Cms.Api.Delivery/Services/RequestStartItemProvider.cs

We are now able to pass an unpublished item to the `Start-Item` header and get the correct response depending on whether we are in Preview mode.
1. Create a Root item and Save and Publish
2. Create a Child item under the Root item and Save and Publish
3. Verify that you can get the child item from any of the `/item` endpoints even when passing the ID or PATH of the start item in the `Start-Item` header
4. Set up Preview
5. Unpublish Root item
6. Try to execute the same API call, this time in Preview
7. Verify that the response hasn't changed
8. Set the Preview header to `false` and verify that you get 404 "The Start-Item could not be found"
- ➕ Test that the Start Item functionality still works in the different endpoints:
- Limiting the results from the Query endpoint through the …

v12: Fix getting an unpublished start item in preview through Start-Item header

---

src/Umbraco.Core/Media/EmbedProviders/Issuu.cs
src/Umbraco.Core/Media/EmbedProviders/OEmbedProviderBase.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/14759
Added a UserAgent header and changed the request so we are receiving our embed as an iframe
1. Create a Document with an RTE
2. Create content with the created Document
3. Enter a link for a flip book from Issuu in the RTE as an embed. (Example: https://issuu.com/educationry/docs/educationry-a40529.docx)
4. Retrieve the embed, there should now be an embed of the flipbook.
5. Submit
6. Confirm that the RTE has the embed
(Optional):
Try to render the embed!

V10 Cherrypicked issuu RTE embed

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml

I have renamed the context module to the app module to remove confusion around context and context-API
See PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/875 for more info.

Feature: rename context module to app module

---

src/Umbraco.Core/EmbeddedResources/Lang/sv.xml

Added validation area and localization key 'entriesShort' and 'entriesExceed'. Keys used are from en-US.

added validation messages in swedish language

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html

Fixes #14722 
Datepicker not working with custom dateformats.
Gave the ng-model of the input element a seperate value with the custom format and let the datepicker value use default formatting to get around the issue. There might be a better solution in here somewhere but this works.
- Create a new page with a datepicker using a custom date format.
- Set a date
- Save and publish
- Refresh the page
- If it works the datepicker will select your date otherwise it will select 1/1.

Fixes #14722 - DateTime picker calendar does not get updated when custom date format

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Datatype/BlockGridEditorDataTypeBlocks.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/routing.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/dataTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/textBoxVariation.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaSection.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/ModelsBuilder/modelsbuilder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/partialViewMacroFiles.spec.ts

We had multiple flaky tests, they should now be fixed. 
We added more timeouts for tests regarding the modelsBuilder and the partialViewMacroFiles. 
We updated a locator in the blockgridEditorContent tests so we would not find two elements resulting in a failing test.
We updated the media move test because the test could sometimes find two elements.
Also updated the test regarding maximum blocks for the blockGridEditor.

V12 Fixed flaky tests

---

src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs
src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/13525
- Implements a `UsePagedSqlQuery` in `NuCacheSettings`, that can now be set to `false`, to instead use `Fetch`
- Would love to use an `IOptionsMonitor` instead to track changes, but we cannot refactor this to be non-breaking (even with `ActivatorUtilitiesConstructor`), as the constructors will be ambiguous 😢
- Set the `UsePagedSqlQuery` to false: 
```
"Umbraco": {
"CMS": {
"NuCache": {
"UsePagedSqlQuery" : false      },
```
- Assert that you can still create doc types & content, and it works as expected
- Go to the settings -> Profiling dashboard
- Assert that you can rebuild the memory cache.
You can even test the times by cherry picking this Profiling PR in: https://github.com/umbraco/Umbraco-CMS/pull/13841
and testing with the …

Add UsePagedSqlQuery setting to NucacheSettings

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html

This PR replaces the current "Save And Preview" button with a button group that can hold multiple preview URLs. 
The new button group renders additional preview URLs. See https://github.com/umbraco/Umbraco-CMS/pull/14479 for info.
The end result looks like this:
**How to test:**
* Follow the steps in PR: https://github.com/umbraco/Umbraco-CMS/pull/14479 to add additional URLs.
* Test that the correct URLs show up on different nodes/variants.
* Test that each button opens the corresponding URL.

Feature: Add buttons for additional preview URLs

---

build/nightly-build-trigger.yml

Not stating a trigger apparently triggers the pipeline on every commit 🙈 
https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers

Disabled nighly build branch trigger

---

src/Umbraco.Core/PropertyEditors/DefaultPropertyValueConverterAttribute.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/14458
- Changed mention of `RelatedLiksEditorValueConverter` to MultiUrlPicker.
- Found out it was the MultiUrlPicker when looking at the `ConvertRelatedLinksToMultiUrlPicker` aptly named migration 🤣

Mention MultiUrlPickerValueConverter instead of old RelatedLinksEditorValueConverter 

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts

Updated locator for the acceptance test 'Preview draft'
Moved from using the alias to data-element.

Updated locator for the acceptance test 'Preview draft'

---

tests/Umbraco.Tests.AcceptanceTest/package-lock.json
tests/Umbraco.Tests.AcceptanceTest/package.json
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorAdvanced.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorAreasContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorRendering.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorSettings.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Datatype/BlockGridEditorDataTypeBlocks.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorContent.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockListEditor/blockListEditorDocument.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/routing.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/dataTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/textBoxVariation.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaSection.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/ModelsBuilder/modelsbuilder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/partialViewMacroFiles.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/partialViews.spec.ts

Fixed multiple tests.
What was done:
Updated playwright, our builders, and our test helpers.
With the updated test helpers we had some changes to different methods.
One of those changes was that we removed the use of umbracoApi as a parameter since it was already in the helpers. We also added a default timeout of 20 seconds for the method isSuccessNotificationVisible(). 
So we had to remove the umbracoApi parameter in the tests that used our test helpers, removed the timeout from notification,  and fixed failing locators

V10 fixed up failing acceptance test

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/JsonValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/JsonValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs

A custom property with value type JSON and no custom property value converter will currently convert into a `JObject` for both Razor rendering and Delivery API output. Unfortunately, `JObject` does not play nice with `System.Text.Json` when serializing the Delivery API output. In effect, these kinds of property values are completely useless.
The only current workaround is to implement a custom value converter.
This PR ensures that the built-in handler for these kinds of properties (the `JsonValueConverter`) implements `IDeliveryApiPropertyValueConverter` and converts the stored value into a `JsonNode`, which serializes nicely with `System.Text.Json`.
The resulting Delivery API output is then changed from:
```json
{
...
"properties": {
"jsonValue": {
"message": [],
"length": []
}
},
...
} …
```

Ensure that value type JSON is translated correctly for Delivery API output

---

src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
src/Umbraco.Web/PublishedCache/NuCache/NuCacheSerializerComponent.cs

- v8 backport of https://github.com/umbraco/Umbraco-CMS/pull/14806
- This introduces a new `appSetting` in `Web.Config`: `<add key="Umbraco.NuCache.UsePagedSqlQuery" value="false" />`
- add `<add key="Umbraco.NuCache.UsePagedSqlQuery" value="false" />` in the appSetting section of your Web.Config
- Assert that content renders as normal by:
- Creating a root document type with some properties (allow as root)
- Add those properties in your Template so we can render out the properties
- Create some content and fill out the properties
- Assert that it renders in the frontend 👍

V8: Backport UsePagedSqlQuery to v8

---

src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
src/Umbraco.Cms.Persistence.EFCore/Factories/UmbracoPooledDbContextFactory.cs

This PR adds own own EF DbContextPool, that basically do not use the pool until Umbraco is in RuntimeLevel == Run.
Because the options are singleton in the pool, it will lead to issues to use the pool before a connection string is set. This is now resolved.
- I tried to use a UmbracoDbContext before the install and then after the install it's connection string was still wrong. After this PR it works as expected
```cs
public class TestComposer : IComposer
{
{
builder.AddNotificationHandler<UmbracoApplicationStartingNotification, MyHandler>();
}
}
public class MyHandler : INotificationHandler<UmbracoApplicationStartingNotification>
{
private readonly UmbracoDbContext _umbracoDbContext;
public MyHandler(UmbracoDbContext umbracoDbContext)
{ …
```

Only use EF DbContext Pool when Runtime level = Run

---

templates/Umbraco.Templates.csproj

Noticed this spelling mistake, quick fix to also update details of other templates included, which shows in the nuget page. This shows in the location below
https://www.nuget.org/packages/Umbraco.Templates#readme-body-tab

Fix spelling mistake, and add details of additional packages

---

src/Umbraco.PublishedCache.NuCache/Property.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/PropertyCacheVarianceTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14758
The NuCache has a problem with culture aware invariant properties in a culture variant setting. Due to the variance calculation, the cache will be populated only with the first invoked culture value. Depending on the property cache level, variance may incidentally be reflected correctly, but still - Umbraco should handle the variance correctly at cache level.
The same problem applies to segment variation. This PR fixes both.
Steps to reproduce:
1. Setup a culture variant content type.
2. Add a culture invariant property that is backed by a value converter which reflects the current request culture in both the intermediate and the "final" value. See below for sample code.
3. Publish …

Fix property variance cache issue

---

src/Umbraco.Core/PropertyEditors/DefaultValueTypePropertyValueConverterAttribute.cs
src/Umbraco.Core/PropertyEditors/PropertyValueConverterCollection.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/BigintValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/DatePickerValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/DateTimeValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/IntegerValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/TextStringValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/TimeValueTypeConverter.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/ValueTypePropertyValueConverterBase.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/XmlValueTypeConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueTypeConverterTests.cs

It is possible to create property editors without backing property value converters. Usually this is done using manifests. These property editors still declare a value type, which should be one of the predefined ones in [`ValueTypes`](https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.Core/PropertyEditors/ValueTypes.cs).
However, the resulting property values for these editor types are not always typed according to their declared value types. Rather, their types tie in part into their storage column in the database, and in part into the de/serialization that goes on within NuCache:
- Value type DECIMAL becomes a `string` instead of a `decimal` (even through it is backed by a decimal column in the database, it still becomes a `string` due to a [known issue with …

Add default property value converters for all value types

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

If there's an existing issue for this PR then this fixes [#14775](https://github.com/umbraco/Umbraco-CMS/issues/14775)
When using external auth providers for user login, the authentication process may complete successfully yet be incomplete in respect to the Umbraco backoffice.
An example could be missing claims - most common use-case is if the external user does not have the correct "email" claim.
At this time we do not handle that scenario very well. The user ends up being presented with a blank screen and with no means to retry, nor perform a sign-out. The console will show a 401 error when trying to reach the `GetCurrentUser` endpoint (as described in the linked issue).
This PR ensures that we forcefully perform a sign-out from the external auth provider if any errors are detected. …

Make sure to sign out external users if an error occurs during sign-in

---

src/Umbraco.Core/UdiParser.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs

This one has annoyed be for some time, so thought I might as well fix it 😁 
The `UdiParser` class has three `TryParse` methods. Two of them have an out parameter of type `Udi`, and both have been marked with the `[MaybeNullWhen(false)]` attribute. So these two are fine.
The third one also has an out parameter, but the type is `T` where `T : Udi?`. The parameter also has a `[MaybeNullWhen(false)]` attribute to indicate that the parameter may be `null` when the method returns `false`. But as the type is essentially a `Udi?`, the method fails to indicate when the out parameter is *not* `null`. This PR therefore replaces the `[MaybeNullWhen(false)]` attribute with a `[NotNullWhen(true)]` attribute instead.
<hr />
To illustrate the effect of this change, I've set up a quick test class. The …

Replaced `[MaybeNullWhen(false)]` with `[NotNullWhen(true)]` for `UdiParser.TryParse` method

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html

Previous Block List only had a single action (delete) in block card in the configuration of the property editor, but with Block Grid there's also an area action and if (package) developers used `<umb-block-card>` component as well there may be addtional actions.
Since the buttons has `umb-outline` the focus if absolute and therefore on top of each other since the closest relative element is the element with `__actions` class.
https://github.com/umbraco/Umbraco-CMS/assets/2919859/a4e36229-d107-4900-b35e-38303de83f74

Ensure focus on specific action in block card

---

src/Umbraco.Core/Services/ContentService.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePublishBranchTests.cs

If there's an existing issue for this PR then this fixes #14543
This PR rolls back the functional breakage introduced by #14763 and fixes the original issue (#14543) in a non-breaking way.
Create a notification handler that logs all "saving", "saved", "publishing" and "published" notifications for content.
Perform "save and publish" on an unpublished structure of content (including all unpublished descendants). Verify that:
1. The same amount of notifications are fired before and after applying this PR, and in the same order.
2. The "published" notification contains state from both the "saving" and the "publishing" notification of the root content being published.

Add notification state to "final" published notification when publishing with descendants

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml

This PR updates the import map because the module files have been moved in the frontend project.
Merge together with: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/892

Improvement: Update import map to repository module

---

src/Umbraco.Web.BackOffice/Controllers/MediaController.cs

In addition to: https://github.com/umbraco/Umbraco-CMS/pull/14514 and as suggested here https://github.com/umbraco/Umbraco-CMS/issues/14468#issuecomment-1658403269 updated the media controller so that media in a listview can be searched by it's id or key.

Update MediaController, search by id or key

---

src/Umbraco.Core/Services/MemberService.cs

In addition to: https://github.com/umbraco/Umbraco-CMS/pull/14514 and https://github.com/umbraco/Umbraco-CMS/pull/14765 and as suggested here https://github.com/umbraco/Umbraco-CMS/issues/14468#issuecomment-1707956599 updated the `MemberService` so that members in a listview can be searched by it's id or key.

Update MemberService, search by id or key

---

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RedirectUrlRepository.cs

This fixes an issue where URL tracking doesn't work for culture invariant pages that have a culture variant ancestor.
The issue is not present if the whole document hierarchy is either variant or invariant, only when mixing and using cultures that have upper case components (country code), which explains why it wasn't caught earlier.
This change ensure the LINQ culture comparison being done doesn't vary by case.
The actual database SQL query `Where` clauses don't need adjustment because the `culture` column collation is already case insensitive.
1. Set up 2 languages whose ISO code have upper case characters (e.g `en-US` and `nl-NL`)
2. Create a root document type which varies by culture
3. Create a child document type that doesn't vary by culture
4. Create some example content, and …

Fixed URL tracking not working for invariant pages with culture variant ancestors

---

src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Core/Services/ContentVersionService.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/DefaultContentVersionCleanupPolicy.cs
src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Core/Services/TwoFactorLoginService.cs
src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
src/Umbraco.Infrastructure/Logging/Viewer/LogViewerConfig.cs
src/Umbraco.Infrastructure/Security/MemberUserStore.cs
src/Umbraco.Web.Website/Controllers/UmbProfileController.cs
src/Umbraco.Web.Website/Controllers/UmbRegisterController.cs
tests/Umbraco.Tests.Common/TestHelperBase.cs
tests/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs

We know auto completed scores can hide real errors, so this PR removes auto completed scopes of a couple of methods actually modifying the state of the db.
See https://github.com/umbraco/Umbraco-CMS/pull/12553 for related info.
Maybe this is the root course of https://github.com/umbraco/Umbraco-CMS/issues/14195
- In theory everything touched should be tested manually 🙈 
- Especially the content clean up background task.

Fixed a couple of occurrences where scopes was auto-completed while modified db state

---

src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14743
* Add aria label to property alias to be in the format "Property alias: MainImage"

Add aria label to umbraco property

---

src/Umbraco.Web.Common/Extensions/UmbracoApplicationBuilder.Identity.cs

Been working on an OpenIdConnect integration recently that required the MemberSignInManager is swapped out.
This was achieved by registering an additional scoped service:
```
builder.Services.AddScoped<IMemberSignInManager, CustomMemberSignInManager>();
```
This works because when you inject `IMemberSignInManager` the **last registered** service wins.
It doesn't work if you try to inject `SignInManager<MemberIdentityUser>` as that is still registered to Umbraco's default `MemberSignInManager`.
Similar applies to the user manager, but Umbraco has a helpful extension methods for replacing it – `SetMemberManager<T>()`.
This PR adds an equivalent `SetMemberSignInManager<T>()` for the same purpose.
_(It would have been cool to do this for the `BackOfficeSignInManager` too but that lives in …

Add SetMemberSignInManager builder extension

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

In the current situation, Lighthouse is reporting an issue regarding the headings ("Heading elements are not in a sequentially-descending order"):
I have changed the h3 to an h1 and the h5 to an h2 while maintaining the styling, so that there are no visible differences but the score improves.

a11y improvement for settingsdashboardintro

---

src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

If there's an existing issue for this PR then this fixes #13052 
1. Create a new Umbraco 10 web app, e.g. using the auto-generated scripts created by [psw.codeshare.co.uk](https://psw.codeshare.co.uk/) as the starting point.
2. Add a home page, a test page, and an error page using the back office.
3. In the view template for the test page add a "throw new Exception(...)" statement which will trigger the exception handling process when you navigate to the page.
4. In Startup.Configure() remove any if (env.IsDevelopment()) clause and the app.UseDeveloperExceptionPage(); call. Instead add a call to app.UseExceptionHandler("/error"); and replace "/error" with your error page's url.
5. Run the app, navigate explicitly to the error page to verify that it's reachable, and then navigate to the …

Add IExceptionHandlerFeature check to dynamic route check

---

src/Umbraco.Web.UI.Client/src/views/common/login-2fa.controller.js
src/Umbraco.Web.UI.Client/src/views/common/login-2fa.html

- Remove duplicate `name` attribute in 2FA login form.
- Use `vm` instead as reference instead of `cvm` to be consistent with other views.
- Define `vm` as `const` instead of `let` as another value isn't assigned - only to it's properties.

Remove duplicate name attribute in 2FA login form

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/HelpPanel/helpLinks.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/HelpPanel/systemInformation.spec.ts

[/ ] I have added steps to test this contribution in the description below
**Description**
This PR contains a new Playwright test to check that the youtube link in the help panel opens to the correct youtube URL. 
I also had to include a check to reject (felt like this would be preferred) the cookies in youtube, if the consent popup displays.
The reason for the System Information clean up is because I originally had my test in here until I felt it would be better suited in its own file. Whilst in there there was an error which I fixed (line 22) and a bit on unused code which I removed. 
**To test:**
1. Make sure to `run npm ci `&` npx playwright install`
2. I would suggest adding test.only to the start of the test so you don't have to watch 20+ tests run.
3. run `npm run ui`
4. check to …

help links tests + clean up of system info

---

src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs

This PR is in draft as I 1) need verification that this is a code bug and not a documentation bug, and 2) need to test a bit more before finalizing.
Should fix #14965 by implementing the change proposed in that same issue.
Test by following the steps to reproduce and verify that the ood.flag file is created upon changing a document type.

Out-of-date models status flag is created when using SourceCodeManual and Development Runtime

---

src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
src/Umbraco.Core/EmbeddedResources/Lang/da.xml
src/Umbraco.Core/EmbeddedResources/Lang/de.xml
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
src/Umbraco.Core/EmbeddedResources/Lang/it.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html

On the content Info content app page we have a audit trail log over the content, what happende to it thouge out the history.
But on the media info content app, it is missing.
I have in many diffendt times acculy need the audit trail for the media, to see how ex delete this file or folder, when did the last save happens and many more. The data is there, when I have need this data I have just go to the Database and search it out. 
But when take the hard way and always figels inside the database "some day I accedentily maby do something stupid" when we can add the same functionallity the content has to the media.
TEST:
1) Start up a new solution.
2) Upload an image and save.
3) Go the info app and se the first entity is saved marked in green
4) Move it, delete it, or resave it and see the …

add Audit Trail to the media info tab just alike the conten

---

src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Delivery/Routing/DeliveryApiItemsEndpointsMatcherPolicy.cs

If there's an existing issue for this PR then this fixes #14875
This PR ensures that we pick the correct endpoint when querying the Delivery API for items - either by route/path or by (multiple) IDs.
The code is a temporary workaround; we will (likely) change the by-IDs endpoint route to be "/items" instead (plural) in V2 of the Delivery API.
See #14875 for steps to test. Note that the issue is also present for media items, albeit less critical as the by-path endpoint does not work with a "/" parameter (but should still be invoked all the same to show the error).

Create matcher policy to pick the correct item endpoint

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeSecurityStampValidatorOptions.cs
src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs
src/Umbraco.Web.Common/Security/MemberSignInManager.cs
src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
templates/UmbracoProject/appsettings.json
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs

This adds new configuration that limits concurrent logins.
- `Umbraco:CMS:Security:AllowConcurrentLogins`
The value will be true for existing projects but false on new projects. We expect to change this so it defaults to false for v13, because this is breaking
- `AllowConcurrentLogins == true`
- Ensure you still concurrently can sign in from two different browsers
- `AllowConcurrentLogins == false`
- Ensure you are signed out from the old browser, when signing in on a new (at most 30 sec wait)

Add config to limit concurrent logins

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeSecurityStampValidatorOptions.cs
src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs
src/Umbraco.Web.Common/Security/MemberSignInManager.cs
src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
templates/UmbracoProject/appsettings.json
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs

- Cherry-picking commits from #14967;
- Changing the default `Umbraco:CMS:Security:AllowConcurrentLogins` setting to `false`;
- Removing the setting from Umbraco's dotnet new templates that was necessary for v12's PR.
Check test steps in #14967.
---
| ⚠️ Breaking changes ⚠️ : </br> Changing the value of `Umbraco:CMS:Security:AllowConcurrentLogins` to `false` which prevents a user account from creating simultaneous sessions by default. Only 1 session is allowed to be active at a time. </br> This setting can always be set to `true` to not invalidate other active user sessions. |
|----------|
Remember❗ : https://docs.umbraco.com/umbraco-cms/reference/configuration/securitysettings article needs to be updated with the new default value for the 13.0.0 release.

V13: Add config to limit concurrent logins

---

src/Umbraco.Core/Extensions/PublishedElementExtensions.cs
src/Umbraco.Core/Models/PublishedContent/IPublishedValueFallback.cs
src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs

If there's an existing issue for this PR then this fixes [#14351](https://github.com/umbraco/Umbraco-CMS/issues/14351)
Fixing the bug where if using the the `.Value()` method with either a culture parameter or the fallback the whole site change state of the initial language set from the PublishedRouter.
This delete code was introduce by the PR [#13889](https://github.com/umbraco/Umbraco-CMS/pull/13889) but it made the VariationContext change now only for the current operation but the rest of the request. This means that if having a Danish site with fallback to english. So if you said `model.Value("someAlias", fallback: "en");` or using `model.Value("someAlias", "en");` the site end result for the users is a mismatch or both Danish and English content.
The best current solution is to reset …

Fixes #14351 - Using Fallback to default langauge on a specific item changes the whole VariationContext 

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

#14773 added UI for the "additional preview URLs" feature implemented in #14479. Unfortunately, the "additional preview URLs" UI currently does not work with culture invariant content.
This PR fixes that issue. It is purely a client-side issue which has to do with the active variant election. See the code change 😄 
Try adding a `SendingContentNotification` notification handler like the following, and ensure that the generated additional preview URLs are displayed for both variant and invariant content.
```csharp
using Umbraco.Cms.Core.PublishedCache;
public class AdditionalPreviewUrlsNotificationHandler : INotificationHandler<SendingContentNotification>
{
private readonly IPublishedSnapshotAccessor …
```

Ensure additional preview URLs work on non-variant content

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html

There is an existing issue that describes this quirk, back in the day, from V8 - here it is: https://github.com/umbraco/Umbraco-CMS/issues/8450
When that issue was raised the discussion led into lots of exciting thoughts about the Url Picker UX/UI and the conclusion was kind of  ooh there are lots of ui/ux challenges with the UX/UI of the picker but we are not actively working on this... and I totally expect this is still the case... but what was welcomed was proposals that might incrementally improve things through a PR...
... so this PR is along those lines, and It's October, and it's a tiny thing, but completely ok if you want to close this PR in exchange for the proper thinking about the UX/UI later down the …

Link Picker Title UI Quirk

---

src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js

If there's an existing issue for this PR then this fixes #14523 
I have added a function, which returns the focus to the trigger element, whenever the "close" event happens in the "Context/Ellipsis" menu.
I might have missed some scenarios - One I can think of is when a node is deleted then the focus currently is not added to anything. I guess that is a challenge for a separate PR. Nevertheless this PR should improve what we already have. It happens whenever the dialog is closed and not just for the "Sort" scenario mentioned in the issue.
**Before**
**After**

14523: Return focus to trigger element when close event occurs

---

src/Umbraco.Core/Services/UserServiceExtensions.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs

We have a project with a lot of user groups. Some groups define startnodes. Others will add permissions like for example Assigning cultures and hostnames.
To reproduce create a user group and call it for example "Domain admin" and assign it only the permission "Culture and hostnames".
Then create a new user and assign the user to the roles Editors, Translators and the Domain Admin group.
Login to the backoffice with this new user and try to assign Culture and hostnames. You will see a error happening because of denied permissions.
We discovered this on 10.6.1, but also on the latest version of the contrib branch.
The problem occurred in a the extension method UserServiceExtensions.GetPermissions. This will retrieve all permissions but only return the first one. If that doesn't have the …

Fix permissions for assign hostname

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js

Prevent form submission when pressing enter in color picker labels, instead execute "add" code.
Also improved validation highlights so fields are updated at more useful times.
Sorry for the whitespace changes, but the editorconfig states 2 spaces for js files, so just updating to convention.

Fix issue with pressing enter on color picker labels

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less

If there's an existing issue for this PR then this fixes: fixes one of the issues in #15011
Stops long names extending across the whole line in block items. 
Steps to replicate:
1. Create a block list editor
2. Add a block with a long name such as "Rich Text Editor with a VERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAMEVERYLONGNAME"
3. Save and observe the effect of the long non-breaking line of text
Before:
After:

Added word-wrap so block item doesn't extend over the whole line

---

src/Umbraco.Cms.Api.Delivery/Querying/QueryOptionBase.cs

Fixed StyleCop warning [SA1116](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1116.md) (_The parameters should begin on the line after the declaration..._) for `Umbraco.Cms.Api.Delivery` project, and no warnings show up in that project now.
If there's an existing issue for this PR then this fixes: part of my issue #15015
Start of removal of warnings per project

Fixed warning SA1116 for Umbraco.Cms.Api.Delivery project

---

src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs

If users don't have access to the root node of the content section they now get access to the recycle bin.
Fixes [10568](https://github.com/umbraco/Umbraco-CMS/issues/10568)

Grant all users access to the content recycle bin

---

src/Umbraco.Web.BackOffice/Controllers/UsersController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14949
When the user is invited, your are able to resend an invitation, from the User page.
But as soon the the VerifyInvite flow has been requested, the `EmailConfirmedDate` has value and therefore the `CheckUniqueUsername` method always return true. But this user witch was invited, only click on the link and left the VerifyInvite  flow undone. 
If the administrator need to request a new invitation they are stuck, now due to the system always sayes true, due to the fact that the email has been confirmed, but the UserState is still Inviteded.
I have change the condition from checking `EmailConfirmedDate` to check the `UserState` as the frontend also do, to show the resend invitation box …

Condition on the userState instead of the dates.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtogglegroup.directive.js
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle-group.html

https://github.com/umbraco/Umbraco-CMS/issues/13251
Added a new guid on the label so we can now reference that guid in the new the aria-labelledby property. 
No more empty-button errors in this part!

Added aria-labelledby so no longer 'empty' on Toggle Group

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js

https://github.com/umbraco/Umbraco-CMS/issues/15009
1) add a new media type or member type
2) go to exiting media type or member type
3) Add the created media type og member from step 1 as a compisition
4) save the type
5) Click on the inhrite link, and see the composition media type or member type open as expteced instead of throw 404
The solution is simple and work without any compromise made, the code is taken from what is allerede done, in the code here:
https://github.com/umbraco/Umbraco-CMS/blob/f8b66aaf507ae575bce0fb85ee55dbab38fb15f8/src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.info.controller.js#L74

Bug fix for compistion on member and media give 404

---

src/Umbraco.Cms.Api.Delivery/Controllers/Content/ContentApiItemControllerBase.cs

When implementing member auth in the V14 branch, a few things were marked for V14 obsoletion in `ContentApiItemControllerBase`, but they were not removed from the source. This was in order to make the backport and subsequent forward merge less conflicting. 
Now that the backport and forward merge is done, this PR removes the obsoleted parts of `ContentApiItemControllerBase`.

Cleaned up V14 TODOs from ContentApiItemControllerBase

---

src/Umbraco.Core/Configuration/Models/IndexingSettings.cs

- Inverts the default setting of `ExplicitlyIndexEachNestedProperty`
- Create an element, with a textstring property "Title", and textarea property named "Body"
- Create a documenttype, with a blocklist using the element you just created
- Create some content (including creating 1 or more blocks)
- Navigate to Examine Management dashboard (Settings -> Examine management)
- Go to the external index, and search the name of the content you just created
- It should no longer index the individual blocks
- Here is a screenshot of how it looks when it indexes the individual blocks:

Dont explicitly index nested property by default

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json
src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
templates/Umbraco.Templates.csproj

**How to reproduce:**
- Enable the delivery API - set `Umbraco:CMS:DeliveryApi:Enabled` to `true` in appsettings.json
- Use the code from a new PR with a partial UI fix https://github.com/umbraco/Umbraco-CMS/pull/14995 or use the examples from the docs: https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/additional-preview-environments-support#configuring-custom-preview-urls
- Have a single language & non-variant content
- Make the content type vary by culture
- Visit the content node & you will see that the button group for previewing additional Preview URLs is not there. We just have the regular "Save and preview" button.
Another issue related to this (continue from the preview steps...):
- Add a new language
- In the Content section - try to create a new content node in …

Bugfix: UI for preview bug related to single language & non variant content

---

src/Umbraco.Core/EmbeddedResources/Lang/da.xml

Typo & grammar fixes to the Danish backoffice, collected over some time using the backoffice in Danish exclusively.

Updates to Danish translations

---

src/Umbraco.Infrastructure/Serialization/ConfigurationEditorJsonSerializer.cs
src/Umbraco.Infrastructure/Serialization/JsonNetSerializer.cs

While working on a Deploy feature involving property/data editor configuration serialization, I noticed `ConfigurationEditorJsonSerializer` adds a converter and sets a custom contract resolver to the `JsonSerializerSettings` field:
https://github.com/umbraco/Umbraco-CMS/blob/f4e333c1782bcb7b614315db42a79702f67d328c/src/Umbraco.Infrastructure/Serialization/ConfigurationEditorJsonSerializer.cs#L9-L17
This class inherits from `JsonNetSerializer`, which defines this field as protected static:
https://github.com/umbraco/Umbraco-CMS/blob/f4e333c1782bcb7b614315db42a79702f67d328c/src/Umbraco.Infrastructure/Serialization/JsonNetSerializer.cs#L8-L15
So both `ConfigurationEditorJsonSerializer` and `JsonNetSerializer` share the same settings instance, resulting in weird side-effects like the …

Fix `JsonNetSerializer` settings leaking into derived implementations

---

src/Umbraco.Core/Deploy/IFileSource.cs
src/Umbraco.Core/Routing/IRedirectTracker.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/Routing/RedirectTracker.cs
src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs

This PR contains two updates that we'd like to make for Umbraco 13 in order to simplify code in Deploy.
I've added an extra parameter to the interface method `IFileSource.GetFilesAsync`.  We have a use for this where we want to continue if a file matching one of the provided UDIs isn't found in some cases, and in others, throw a `FileNotFoundException`.  Hence the need for the parameter.  Currently we are working around this by casting to the concrete type, but it would be cleaner if it were on the interface. 
There are no uses of this interface within the CMS itself.
Currently this logic is within a notification handler - `RedirectTrackingHandler` - which means the logic within can't easily be re-used in Deploy where we also need to track content moves and name changes in order to create …

Updates and support for re-use of CMS logic in Deploy

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/components/media/umbimagepreview/umb-image-preview.less

…  to avoid portrait images of take up much of height.
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14917
Adjusted media grid to set `max-height` to avoid slim portrait images to take up a lot of height.
[Test images](https://github.com/umbraco/Umbraco-CMS/files/13206364/test.zip) to upload.
**Before**
**After**

Set max height of media item in grid

---

src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProvider.cs
src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProviderSetup.cs
src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProvider.cs
src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProviderSetup.cs
src/Umbraco.Cms.Persistence.EFCore/Composition/UmbracoEFCoreComposer.cs
src/Umbraco.Cms.Persistence.EFCore/Constants-ProviderNames.cs
src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
src/Umbraco.Cms.Persistence.EFCore/UmbracoDbContext.cs
tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/DbContext/CustomDbContextTests.cs

If there's an existing issue for this PR then this fixes #14893
This problem described in #14893 stems from the database provider not being registered when adding a custom DbContext. The reason the problem was introduced in #14674 was because it was unclear what the extension methods usage was. I.E you couldn't easily see that you were supposed to use one method internally (In Umbraco source code) and one from a consuming application.
Therefore, I think that the extension methods needs to be unified and follow the same basic behavioral patterns as the original `AddDbContext()` methods from EF Core. In this way I also think it would be easier for experienced EF Core developers to start using it in an Umbraco context.
To solve this problem this PR adds two new extensions:
```csharp …
```

Fix custom dbcontexts extention methods

---

src/Umbraco.Core/Security/ContentPermissions.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.BackOffice/Controllers/ContentControllerBase.cs
src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs

- When `[ContentSaveValidation]` attribute was applied and the authorization wasn't successful - we were not setting the action result which led to executing the next action even though the user doesn't have the necessary permissions;
- When checking the content permissions of a **newly created** content node, we were not taking into account the permissions to check;
- Both are fixed in this PR.
- Make a document type with a property like the RTE or similar. Allow it to be created as a root node;
- Make some test content using the document type you just created and publish it;
- Invite a user and give them either the "Writer" group or any other group without permission to publish nodes;
- Open the Network tab and check the following POST request:
- Have the new user make some changes to …

Check content permissions before performing action

---

src/Umbraco.Infrastructure/Persistence/Dtos/AccessDto.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15024
As outlined in the linked issue, the entire site frontend goes down if an access rule is accidentally deleted. At the time of writing we can't reproduce this in any other way than to delete the access rule from the database, but somehow this has happened in the wild.
Fortunately the fix is straightforward 😄 and has no implications apart from a little bit more allocation when reading the public access rules. 
1. Restrict public access on a content item.
2. Delete the resulting entry in the `umbracoAccessRule` table and restart the site.
3. Without this PR the site will be entirely broken. With this PR, the site still works.
4. It should be possible to re-configure the deleted access …

Ensure that missing access rules do not break the site

---

tests/Umbraco.TestData/LoadTestController.cs

Issue: https://github.com/umbraco/Umbraco-CMS/issues/15015
This PR fixes the following task:
> Remove warnings from Tests/Umbraco.TestData project
This PR can be tested by building the Umbraco source code and checking that this warning is gone:
`LoadTestController.cs(324,13,324,116): warning CS0618: 'IHostingEnvironment.MapPathContentRoot(string)' is obsolete: 'Please use the MapPathContentRoot extension method on an instance of IHostEnvironment (or IWebHostEnvironment) instead'`

Fix warning CS0618: 'IHostingEnvironment.MapPathContentRoot(string)' is obsolete in Umbraco.TestData.

---

src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs

Just a minor update in database constant to use exisitng `Webhook` constant, which is `TableNamePrefix + "Webhook"`.
The table name on webhook log table is unchanged, so full table name is `umbracoWebhookLog`.

Update webhook log table using constant

---

src/Umbraco.Web.UI.Client/src/less/components/application/umb-dashboard.less

While installing `Skybrud.Redirects` package  in dashboard section, I noticed the content area doesn't fill full height, and thus a dropdown may be hidden because of `overflow: auto`.
https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/186
It does make sense to keep overflow auto if content exceeds the height of dashboard content area.
More content in content area.
https://github.com/umbraco/Umbraco-CMS/assets/2919859/b70f72ee-46ec-41dd-90cb-48c70103e08b

Allow dashboard content to grow and fit height

---

src/Umbraco.Web.UI/Startup.cs

N/A
Removed parenthesis from compiler directive as generates warning from Umbraco.Web.UI as part of #15015

Umbraco.Web.UI: Removed parenthesis from compiler directive

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html

If there's an existing issue for this PR then this fixes - [15071](https://github.com/umbraco/Umbraco-CMS/issues/15071)
This PR adds a little bit of screen reader only text to the `select all` button found in the umb table view. It's a little generic at the moment and could probably do with being a little more contextual, but it's an improvement on the nothing that was there
Proof that lighthouse no longer errors for it

Accessibility Issue 15071 - add select all sr-only text to umb table select all button

---

src/Umbraco.Web.UI.Login/src/auth.element.ts
src/Umbraco.Web.UI.Login/src/components/login-input.element.ts

Fixes #15089
This removes the `id` attribute from the inner input element of the `umb-login-input` component to avoid having duplicate id's on the login screen.

V13 RC: Avoid duplicate id's on the login screen

---

src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
src/Umbraco.Web.UI.Client/src/common/resources/mediatype.resource.js
src/Umbraco.Web.UI.Client/src/views/mediaTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/mediaTypes/create.html
src/Umbraco.Web.UI.Client/src/views/memberTypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/memberTypes/create.html

Under a media type it is possible to select folder option, which fails as it isn't supported (only at root or under other folders/containers).
This is also how it works under document types, where folder option is not shown in create dialog under a document/element type.
I also cherry picked a few other changes from https://github.com/umbraco/Umbraco-CMS/pull/14833 like some typos.
**Before**
**After**
It is still possible to select "Folder" option in create dialog at root level and under other folders/containers - just like it work with document types.
The create dialog isn't really used for member types are the moment since it route directly to edit view, but I aligned it with media type create dialog and we may enable containers for member types as well later in …

Don't allow to select folder in create dialog under media type

---

src/Umbraco.Cms.Api.Common/OpenApi/EnumSchemaFilter.cs

By not setting the type and format, it would remain integer is this case, which would result in an invalid specification as the enum members are strings.
Currently I don't think any enums are exposed yet, but I saw this issue as part of some related investigations, checking the feasibility of including the CMS models in the swagger.

Fixed open api enum schema filter not setting type

---

src/Umbraco.Core/Webhooks/Events/ContentDeleteWebhookEvent.cs
src/Umbraco.Core/Webhooks/Events/ContentPublishWebhookEvent.cs
src/Umbraco.Core/Webhooks/Events/ContentUnpublishWebhookEvent.cs
src/Umbraco.Core/Webhooks/Events/MediaDeleteWebhookEvent.cs
src/Umbraco.Core/Webhooks/Events/MediaSaveWebhookEvent.cs
src/Umbraco.Core/Webhooks/WebhookEventBase.cs
src/Umbraco.Core/Webhooks/WebhookEventContentBase.cs

Fixes : #15093
Creates a new `WebhookEventBase` class that doesn't depend on `IContentBase` or any other `IEntity` object.
Means the `WebhookEventBase` class can then be used for any Notification Inheriting `INotification`
Removes the need for other people to do the checks for enabled/server roll etc in their webhooks. 
Renames existing `WebhookEventBase` to `WebhookEventContentBase`. 
```cs
public class CustomWebhookEvent : WebhookEventBase<LanguageSavedNotification>
{
public CustomWebhookEvent(
IWebhookFiringService webhookFiringService,
IWebHookService webHookService,
IOptionsMonitor<WebhookSettings> webhookSettings,
IServerRoleAccessor serverRoleAccessor)
: base(webhookFiringService, webHookService, webhookSettings, serverRoleAccessor, "Language Saved")
{ }
}
```
If you want to …

New WebhookEventBase class

---

src/Umbraco.Web.Common/AspNetCore/AspNetCoreSessionManager.cs

While troubleshooting another issue I ran into a NRE being triggered by the `HttpSessionIdEnricher`, when trying to retrieve the `SessionId`.
I couldn't reliably reproduce this by itself, and it can't be seen in the logs either, as serilog swallows any exception that occur in enrichers, but it can be fairly easily forced to happen by adding the following, before `app.UseUmbraco`:
```c#
app.Use(async (context, func) =>
{
// This is to make the issue reproducible
// The issue does occur without this line, for the log lines in PublishedSnapshotService, but I can't reliably reproduce it
context.Session = null!;
ILogger<Startup> logger = context.RequestServices.GetRequiredService<ILogger<Startup>>();
logger.LogInformation("Test 1");
await func();
});
```
The issue got introduced when cleaning …

Fix potential NullReferenceException

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs

Add `AddWebhookEvent` extension method to `UmbracoBuilderExtensions` so that WebhookEvents can easily added from `Program.cs`

AddWebhookEvent to UmbracoBuilderExtensions

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/DynamicRoot/QuerySteps/FurthestAncestorOrSelfDynamicRootQueryStep.cs
src/Umbraco.Core/DynamicRoot/QuerySteps/FurthestDescendantOrSelfDynamicRootQueryStep.cs
src/Umbraco.Core/DynamicRoot/QuerySteps/IDynamicRootRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DynamicRootRepository.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DynamicRootServiceTests.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/15112 
The aliases of `FarthestAncestorOrSelfDynamicRootQueryStep` and `FarthestDescendantOrSelfDynamicRootQueryStep` were incorrect. Changed the aliases and also updated the class names to be consistent.

Fix FurthestAncestorOrSelfDynamicRootQueryStep and FurthestDescendantOrSelfDynamicRootQueryStep

---

src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs

- Fixes: #15131
- Instead of "Send to Publish" action/permission (`H`), we need the "Publish" (`U`) one.
- This bug surfaced because of a recent fix but has been there for a while.
- Schedule publish both an already Saved/Published node and a newly created one

Update correct action permission for schedule publishing

---

src/Umbraco.Core/Deploy/IImageSourceParser.cs
src/Umbraco.Core/Deploy/ILocalLinkParser.cs
src/Umbraco.Core/Deploy/IMacroParser.cs

This update just aligns the nullability of the parameter and return value of the three interfaces that define parsers for rich text content.  It's not essential, but nice to tidy up.
Implemented in response to [this comment](https://github.com/umbraco/Umbraco-Deploy/pull/800/files#r1381910981).
There is no implementation of this class in the CMS itself.

 Remove parameter value/return nullability in `IImageSourceParser`, `ILocalLinkParser` and `IMacroParser`

---

src/Umbraco.Core/Deploy/IFileSource.cs

This is a small adendum to the work in [this PR](https://github.com/umbraco/Umbraco-CMS/pull/14990), where I added a parameter to a method in `IFileSource`, but omitted to do so for the "sync" equivalent.
This PR adds this to align the signatures on these methods.

Aligned parameters on sync and async methods on IFileSource.

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs

While looking at https://github.com/umbraco/Umbraco-CMS/pull/15138, I noticed the nullability of the `PackageMigrationPlans()` helper method was incorrect (`WithCollectionBuilder()` doesn't return a nullable type anymore). This PR fixes the following helper methods:
- `PartialViewSnippets()`
- `PartialViewMacroSnippets()`
- `Mappers()`
- `NPocoMappers()`
- `PackageMigrationPlans()`

Fix WithCollectionBuilder helper methods nullability

---

src/Umbraco.Web.UI.Login/src/components/pages/mfa.page.element.ts
src/Umbraco.Web.UI.Login/src/context/auth.repository.ts

When a login happens inside the umb-overlay in the backoffice, we emit an event to indicate the success of that to close the overlay. That event needs to hold the user details to let the AngularJS application refresh itself with updated user details. This already happened on the regular login form but not on 2fa, so this PR fixes that.
The other change is that custom 2fa views can benefit to know the returnPath, so that is now also forwarded to them as a property.

V13 RC: Fix issue with 2FA login

---

src/Umbraco.Core/Services/IWebHookService.cs
src/Umbraco.Core/Services/WebhookService.cs

Added comments to methods in new `IWebHookService`.
Not sure if create, update and delete should have `int userId = Constants.Security.SuperUserId` param like many others services, e.g. `IDataTypeService`:
https://github.com/umbraco/Umbraco-CMS/blob/a2a2680defd40ed0ef72fb85bf6d7a9bf1db33bc/src/Umbraco.Core/Services/IDataTypeService.cs#L75
which is used for `Audit()`:
https://github.com/umbraco/Umbraco-CMS/blob/a2a2680defd40ed0ef72fb85bf6d7a9bf1db33bc/src/Umbraco.Core/Services/DataTypeService.cs#L515
while looking into supporting Webhooks in management API, I noticed other services pass in `CurrentUserKey(_backOfficeSecurityAccessor)`, so maybe we need this later anyway?
https://github.com/umbraco/Umbraco-CMS/pull/15147/files#diff-33a00493a31cf8daad754645a3ba59e063c24b6aa7d9a89fc24a3226237f …

Add comments to methods in `IWebHookService`

---

src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoRichTextBlock.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridblock.component.js

If there's an existing issue for this PR then this fixes !-- link to the issue here! -->
https://github.com/umbraco/Umbraco-CMS/issues/14403
Angular's ng-html-bind strips away style tags from the inserted html, rendering most styling in the rich text editor moot when viewed in backoffice through the umbBlockGridDemoRichTextBlock.html. I have updated the BlockGridBlockController to include $sce on the $scope so it's available to use in the custom views for the grid blocks, and updated the custom view to use $sce.trustAsHtml to insert the HTML.
This way it's still the developers choice whether to use potential unsafe html or not, but it's available when you, like in this case, is in control of the content the entire way.
**To test it:**
1. Install the demo blockgrid and create a document …

Add strict contextual escaping on the $scope for grid controller

---

src/Umbraco.Core/PublishedCache/IPublishedSnapshotService.cs
src/Umbraco.Core/PublishedCache/Internal/InternalPublishedSnapshotService.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/ResetCache.cs
src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs

[Link to the issue](https://github.com/umbraco/Umbraco-CMS/issues/14863)
Added a way for the PublishedSnapshot service to clean up it's local files so (for example) Upgrade migrations have a reliable way of removing known invalid cache files without running into locking issues
- Create an 11.x installation, add a doctype, add a document, browse the document on the frontend
- Upgrade Umbraco package to 12
- Make sure `ShowMaintenancePageWhenInUpgradeState` is set to false and no unattended install is configured (see issue for details)
- Boot the site, browse to the backoffice and go trough to the installer

Move localdb file management of PublishedSnapshotService into itself.

---

src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoRichTextBlock.html
src/Umbraco.Web.UI.Client/src/common/filters/nestedcontent.filter.js

This fixes 2 cases where the HTML markup of the RTE wasn't correctly rendered in the backoffice, because the editor now returns an object that stores both the HTML and used blocks (see PR https://github.com/umbraco/Umbraco-CMS/pull/15029 that adds the 'Blocks in RTE' feature).
The default custom view we provide for the RTE in the Block Grid didn't render the actual HTML and if a label used the `ncRichText` filter, it couldn't parse the HTML to text, resulting in:
This fixes both the custom view and `ncRichText` filter, so the HTML markup is correctly rendered/parsed to text:
Testing can be done by installing `Umbraco.TheStarterKit` 12.0.0 and viewing the Home page in the backoffice: applying this PR and rebuilding the front-end assets should fix it.

Fix rendering and parsing new RTE markup object in backoffice

---

Directory.Build.props
src/Umbraco.Cms.Api.Common/CompatibilitySuppressions.xml
src/Umbraco.Cms.Api.Delivery/CompatibilitySuppressions.xml
src/Umbraco.Cms.Imaging.ImageSharp/CompatibilitySuppressions.xml
src/Umbraco.Cms.Imaging.ImageSharp2/CompatibilitySuppressions.xml
src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
src/Umbraco.Cms.Persistence.EFCore.Sqlite/Umbraco.Cms.Persistence.EFCore.Sqlite.csproj
src/Umbraco.Cms.Persistence.EFCore/CompatibilitySuppressions.xml
src/Umbraco.Cms.Persistence.SqlServer/CompatibilitySuppressions.xml
src/Umbraco.Cms.Persistence.Sqlite/CompatibilitySuppressions.xml
src/Umbraco.Cms.StaticAssets/CompatibilitySuppressions.xml
src/Umbraco.Core/CompatibilitySuppressions.xml
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Examine.Lucene/CompatibilitySuppressions.xml
src/Umbraco.Infrastructure/CompatibilitySuppressions.xml
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.PublishedCache.NuCache/CompatibilitySuppressions.xml
src/Umbraco.Web.BackOffice/CompatibilitySuppressions.xml
src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
src/Umbraco.Web.Common/CompatibilitySuppressions.xml
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.Website/CompatibilitySuppressions.xml
tests/Directory.Build.props
tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
tests/Umbraco.Tests.Common/CompatibilitySuppressions.xml
tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
umbraco.sln

While testing v13, I noticed the `Umbraco.Web.UI.Login` project wasn't visible in Visual Studio, which seems to be related to the duplicate/clashing port (`Umbraco.Web.UI` already used port 3961). Updating the port to 3962 and configuring all build configurations (`Debug`, `Release` and `SkipTests`) to not build this project fixed it.
Besides cleaning up the solution file, package validation is temporarily disabled, the suppression files are removed and the baseline version already updated to 13.0.0. Previously no breaking changes would be picked up anyway, because the target framework changed from .NET 7 to .NET 8 (all files only contained a single [PKV0006](https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/diagnostic-ids) suppression).
Finally, I've removed all …

Include Umbraco.Web.UI.Login project, update compatibility suppressions and remove unnecessary package references

---

src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs

Deploy automatically excludes the automatic relation types that are used for reference tracking (because they are always updated in the base content repository during save). However, the CMS doesn't have a built-in helper method to get all of them, so this PR creates a new `GetAutomaticRelationTypesAliases()` method on the `DataValueReferenceFactoryCollection` to get these from:
- The default ones from `Constants.Conventions.RelationTypes.AutomaticRelationTypes` (`umbMedia` and `umbDocument`);
- From any `IDataValueEditor` that also implements `IDataValueReference`;
- From any `IDataValueReferenceFactory` that is registered.
The code in `ContentRepositoryBase` also didn't get the relation types from the factory, so this PR also fixes a bug that would cause any custom relation type alias …

Include automatic relation type aliases from factory and fix SQL parameter overflow

---

src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs

This is the v10+ version of PR https://github.com/umbraco/Umbraco-CMS/pull/14897 and can be tested in the same way... After merging, this should be easily merged up to the latest versions as well.

Publish ContentTreeChangeNotification after saving/deleting blueprints

---

src/Umbraco.Web.UI.Client/src/installer/steps/permissionsreport.html

Fixes #14835
Steps to test / reproduce (as stated in ticket):
Make sure some folders have no app pool's user Modify nor Full control permissions on the server.
Try to install Umbraco, Permissions page will appear prompting to correct permissions on selected folders.
Now the correct link to 10-LTS version will be displayed:
[https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/setup/server-setup/permissions](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/setup/server-setup/permissions)

#14835 Update link on permissionsreport.html

---

src/Umbraco.Web.UI.Login/src/auth.element.ts
src/Umbraco.Web.UI.Login/src/context/auth.context.ts
src/Umbraco.Web.UI.Login/src/context/auth.repository.ts

This tricks the new login screen to work with the Management API by making it more lenient in the way it interprets the response types from both the old `postlogin` as well as the new `authorize` actions.
The caveat is that you probably can't change user after login in the old Backoffice if you run the old executable (Umbraco.Web.UI), but this executable is no longer published on this branch, so should be ok to merge.
~**DO NOT** squash this PR as we want to cherry-pick one of the commits back to v13 for consistency.~

V14: make v13 login screen work initially with Management API

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Mapping/Items/ItemTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DataType/Item/DataTypeItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/Item/DataTypeTreeItemResponseModel.cs
src/Umbraco.Core/PropertyEditors/IDataEditor.cs

The server should not know about data type icons in V14, so the Management API should not be serving them 😄 instead, the client needs the editor UI alias to handle data type icons, groups etc. etc.
1. Verify that the data type tree endpoints return editor UI alias instead of icon for the data type tree items returned.
2. Verify that the data type item endpoints return editor UI alias instead of icon for the data type items returned.

Data type icons should not be served from the Management API

---

src/Umbraco.Infrastructure/Persistence/Dtos/WebhookLogDto.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15092
This worked on SQLite, but not on SqlServer, as the text columns are not the same
This PR sets the column types to NVARCHARMAX, to alleviate this issue 🚀 
- Follow steps in original issue 🙌

v13: Add NVARCHARMAX to WebhookLogDto columns

---

src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs

This pr uses the header value to set culture and segment, if present on the request.
This means the `IVariantionContextAccessor` is usable from backoffice requests
- Try to get the value from the `IVariantionContextAccessor` e.g. on the EntityController.GetDynamicRoot endpoint
- Ensure delivery api etc still works as expected
- Ensure regular razor calls still work as expected

Use header value instead if present to set culture on request

---

src/Umbraco.Core/PropertyEditors/DefaultPropertyIndexValueFactory.cs
src/Umbraco.Core/PropertyEditors/IPropertyIndexValueFactory.cs
src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/MediaValueSetBuilder.cs
src/Umbraco.Infrastructure/Examine/MemberValueSetBuilder.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs

This optimised a few things related to blocks.
Related issues, that is maybe fixed by this is #15056 and #14936.
When indexing, it get all content types once. Even that it is cached by the repository, the deep cloning is too slow, when done a lot (like when indexing)
Also updated MultiUrlPicker.ToEditor. This is called a lot (e.g. when used in blocks). It used to use the entity service, but this do not cache, so each MultiUrlPicker would go to the database up to two times (If it contains both referenced media and content), when editing content.
In general, performance testing is easiest when not using a local database, and when the db have a lot of content.
Ensure:
- Indexing should work like before. 
- Content editing should work like before.

Performance optimisations related to blocks (and multi url picker)

---

src/Umbraco.Cms.Api.Management/Mapping/Dictionary/DictionaryMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/Dictionary/CreateDictionaryItemRequestModel.cs

Frontend needs to specify the Id of a new dictionary items to easily swap between views
Using the managment api
- Create a new dictionary item without specifying the id => return header should give you a new id
- Create a new dictionary item and specify its id, fetching on that ID should return this item

Allow ID for a new dictionary-item to be specified

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/EmbeddedResources/Lang/nl.xml

For now, I have chosen to only add translations for the message displayed in the content section because the rest of the multi-node tree picker does not have translations, and it's also difficult to translate this to Dutch.

Dynamic root feature translations (Dutch)

---

src/Umbraco.Core/Services/ContentVersionService.cs
src/Umbraco.Web.Website/Controllers/UmbProfileController.cs

Added scope complete in a few edge cases after https://github.com/umbraco/Umbraco-CMS/pull/14947.
The two in `ContentVersionService.cs` can't really be tested, as it should only ever be null, when the repository is used outside of a scope.

Added missing scope.Complete in some edge cases.

---

src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs

Fixes #15205
Use explicit query to count media, instead of using content query.

Bugfix: Count existing media correct

---

src/Umbraco.Core/Deploy/IImageSourceParser.cs
src/Umbraco.Core/Deploy/ILocalLinkParser.cs
src/Umbraco.Core/Deploy/IMacroParser.cs

This PR updates three interfaces used only in Umbraco Deploy to add a "context cache" parameter.  Currently we have interfaces in Deploy - e.g. `IMacroParser2` - that include this parameter, and moving this to core means we can clean this up.
Just to note I'm getting a compiler error...
```
Could not load type 'Enumerator' from assembly 'Microsoft.CodeAnalysis, Version=4.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```
...since the upgrade to .NET 8 locally, so haven't been able to verify - so I'll have to rely on the build server to check the changes compile.

Updated rich text parser interfaces to support context cache.

---

src/Umbraco.Web.UI.Client/src/common/services/util.service.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15202
In https://github.com/umbraco/Umbraco-CMS/pull/13500 it adjusted a few functions to allow specifying a known parsing format instead of just default parsing format `YYYY-MM-DD HH:mm:ss`.
However it also passed in `format` to `convertToLocalMomentTime()` here: https://github.com/umbraco/Umbraco-CMS/pull/13500/files#diff-277b13396c90722385a98d599dbfea84855ff088949d00d4b5d14259208ed034R111
which before always used `YYYY-MM-DDTHH:mm:ss` format. Now it passed in format from where `getLocalDate()` is called, e.g. `LLL` or `MMM Do YYYY, HH:mm`.
https://github.com/search?q=repo%3Aumbraco%2FUmbraco-CMS%20getLocalDate&type=code

Don't change format in convertToLocalMomentTime

---

src/Umbraco.Web.UI.Client/src/views/dictionary/list.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15188
Allow to browse the dictionary items from list, by clicking the entire table row, which is consistent with languages.

Click row in dictionary list

---

src/Umbraco.Core/Configuration/Models/WebhookSettings.cs
src/Umbraco.Core/Persistence/Constants-Locks.cs
src/Umbraco.Core/Persistence/Repositories/IWebhookLogRepository.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookLoggingCleanup.cs
src/Umbraco.Infrastructure/HostedServices/WebhookLoggingCleanup.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddWebhookDatabaseLock.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/WebhookLogRepository.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/WebhookRequestServiceTests.cs

- Adds functionality much like `ContentVersionCleanup`, that will clean up webhook logs when they are X days old. This is in form of a `IRecurringBackgroundJob`, which will run every day.
- Adds settings to Enable/Disable this functionality
- Adds settings to configure how many days to keeps logs for
- Create a document type with allow as root set to true
- Create a webhook with the `Content was published` event
- Publish some content with the doc type you created in step 1.
- Go to Settings -> Webhooks -> Logs to assert that you now have logs in there.
- You can change the `webhookLogs = await _webhookLogRepository.GetOlderThanDate(DateTime.Now - TimeSpan.FromDays(_webhookSettings.KeepLogsForDays));` into 
webhookLogs = await _webhookLogRepository.GetOlderThanDate(DateTime.Now + …

V13: Webhook logging cleanup

---

src/Umbraco.PublishedCache.NuCache/ContentStore.cs

Whenever one makes changes to a data type, these changes are immediately available in the published properties that are based on this data type. That is, until a piece of content with a property based on this data type is either saved or published; then the data type data is rolled back to the previous version on _all_ published properties of _all_ content using this data type.
This can be reproduced by printing out the max allowed chars on a text string configuration:
1. Render the page after a restart - the rendered configuration value is (obviously) correct.
2. Change the configuration value and re-render the page - the rendered configuration value is the updated value (correct).
3. Save (or publish) a piece of content using this text string configuration and re-render the page  - the …

Ensure content types are updated in ContentStore when a data type changes

---

src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15232
- Problem was that we were trying to serialize and already serialized object, this no longer happens.
- Create a document type with allow as root: `true`
- Create a webhook with Url using webhook.site (or whatever endpoint you want) and content published event.
- Create some content with your doc type from step 1.
- You should now receive proper JSON in your endpoint:

V13: Fix proper serialization of webhook object

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.html

Fixes #15240
This reverts an accidental change that changed the property on which user dashboards are shown.

V13 RC: Revert change to user dialog that accidentally removed user dashboards

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.less

Update `blockgrid.blockconfiguration.overlay.less` & `blocklist.blockconfiguration.overlay.less` so that the text in the button is visible. Use variables for color in the buttons instead of hardcoded value. 
Before: 
After:

Fix button styling in block list & block grid overlay

---

src/Umbraco.Cms.Api.Delivery/Caching/DeliveryApiOutputCachePolicy.cs
src/Umbraco.Cms.Api.Delivery/Caching/OutputCachePipelineFilter.cs
src/Umbraco.Cms.Api.Delivery/Controllers/Content/ContentApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/Controllers/Media/MediaApiControllerBase.cs
src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Core/Configuration/Models/DeliveryApiSettings.cs
src/Umbraco.Core/Constants-DeliveryApi.cs

This PR adds the option to use output caching with the Delivery API.
Output caching is an optional feature that one enables by means of config:
```json
...
"DeliveryApi": {
"Enabled": true,
"OutputCache": {
"Enabled": true,
"ContentDuration": "00:00:20",
"MediaDuration": "00:00:10"
}
},
...
```
As shown, output caching can be configured individually for content and media.
Output caching is not applied when previewing.
To test this PR you'll need a property that changes with each request, so you can see the cached response being reused until the cache expires. That is, you'll need a custom property value converter. The simplest way is likely to replace the default text value converter with a value converter that outputs the current date and time:
```csharp
using …
```

Add output caching to the Delivery API

---

src/Umbraco.Core/Models/PublishedContent/IPublishedContentTypeFactory.cs
src/Umbraco.Core/Models/PublishedContent/PublishedContentTypeFactory.cs
src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs

Although batching data type cache refresher operations (reported in https://github.com/umbraco/Umbraco-CMS/pull/13978, fixed in https://github.com/umbraco/Umbraco-CMS/pull/14332) has reduced the possibility of getting an `ArgumentException: Could not find a datatype with identifier 1195. (Parameter 'id')`, we discovered it was still possible in the following case:
1. Within a single scope:
1. A content type gets updated;
2. A new data type is saved;
3. A new content type is saved using this data type.
2. When the scope is completed and notifications are published, the following happens:
1. The `ContentTypeCacheRefresher` notifies the `IPublishedSnapshotService` to refresh all `PublishedContentType`s: https://github.com/umbraco/Umbraco-CMS/blob/c989c5e214700ac73c6bff10f4d8f132850e217e/src/U …

Clear cached PublishedDataTypes when content types are updated

---

Directory.Build.props
global.json
src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
src/Umbraco.Cms.Persistence.EFCore.Sqlite/Umbraco.Cms.Persistence.EFCore.Sqlite.csproj
src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
templates/UmbracoProject/UmbracoProject.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs

While updating dependencies on our commercial products, I noticed the version of `Microsoft.SourceLink.GitHub` was bumped from 1.1.1 to 8.0.0 and looking at the [release notes](https://github.com/dotnet/sourcelink/releases/tag/8.0.0), it's now included in .NET 8 SDK and enabled by default. This means the explicit package reference can be removed and because the `EmbedUntrackedSources` property is now also enabled by default (see [SDK target](https://github.com/dotnet/sdk/blob/771a51cd0feee9afd45bca12acca00d4824ff30d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.SourceLink.targets#L23)), so that one could be cleaned up as well.
I've also removed the AngleSharp package reference from `Umbraco.Tests.UnitTests`, since only a custom `GetItemByIndex()` extension method from that …

Update and remove unnecessary package dependencies

---

src/Umbraco.Core/Services/WebhookLogFactory.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddWebhookDatabaseLock.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/ChangeLogStatusCode.cs
src/Umbraco.Web.UI.Client/src/views/webhooks/logs.controller.js
src/Umbraco.Web.UI.Client/src/views/webhooks/logs.html
src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15231 & https://github.com/umbraco/Umbraco-CMS/issues/15230
As mentioned in the original issue, the lone ✔️ didn't really make sense in the details of a log.
This now implements the following suggestion: https://github.com/umbraco/Umbraco-CMS/issues/15231#issuecomment-1814535670
- Create a document type with allow as root set to true
- Create a webhook with a working URL (you can use https://webhook.site) and Content is published event.
- Create some content with the doc type you created in step 1
- Go to Settings -> Webhooks -> Logs
- Click on a log, the details show a ✔️  and the status code side by side.

V13: Change WebhookLog status for clarity

---

src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs

- Allows the backoffice to run from a different host than the API host if `BackOfficeHost` setting is configured:
- by adding a CORS policy for the custom backoffice host - it respects the [middleware order](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0#middleware-order) _(placed after `UseRouting()`, but before `UseAuthorization()`)_
> Setup:
- In `Umbraco.Web.UI.New.Client` project create a file `.env.local` and add the following contents:
```
VITE_UMBRACO_USE_MSW=off # on = turns on MSW, off = disables all mock handlers
VITE_UMBRACO_API_URL=https://localhost:44339
VITE_UMBRACO_INSTALL_STATUS=running # running or must-install or must-upgrade
VITE_MSW_QUIET=off # on = turns off MSW console logs, off = turns on MSW console logs …
```

V14: Allowing custom backoffice host with CORS policy

---

src/Umbraco.Web.BackOffice/EmbeddedResources/Tours/getting-started.json

I've improved punctuation and sentence structure for better readability.
_The sentence before fix_
_The sentence after fix_
To test: Run the solution, start the tour of getting started and the sentence is now more clear and correct.

Improved punctuation and sentence structure for better readability.

---

src/Umbraco.Web.UI.Client/src/views/webhooks/edit.controller.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15244
- Introduces new "Unknown node" when we cannot find the node.
- This way you should be able to delete them from you webhooks.
Follow steps in original issue

V13: Fix missing contenttype in webhook

---

src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js

Adds current culture and current segment when asking for the dynamic root. Can be accessed using `IVariantionContextAccessor` in query steps
Only breaking since 13.0.0-rc1

Dynamic root with culture and segment

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js

Fixed typo in description mentioning `umbImageGravity` component. I only removed a semicolon after a function, which is only needed after a named function.

Fix typo in `umbImageGravity`

---

src/Umbraco.Core/Extensions/UdiGetterExtensions.cs
tests/Umbraco.Tests.Common/Builders/WebhookBuilder.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UdiGetterExtensionsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/WebhookBuilderTests.cs

Although PR https://github.com/umbraco/Umbraco-CMS/pull/15267 includes most of the boilerplate code to make `Webhook` implement `IEntity`, the `GetUdi()` extension method wasn't updated to use the interface and the `IEntity.GetUdi()` extension method didn't support the webhook entity type. This PR fixes both of these issues in the first commit.
I've also taken the opportunity to refactor the code in the second commit, so it's much more compact and readable by using:
- `ArgumentNullException.ThrowIfNull()` for all null checks (although we're already in a nullable context);
- `switch` expressions, which also takes care of detecting unreachable code, in case multiple types would match (e.g. `IContent` and `IContentBase`).
Finally, I've also added a quick unit test to verify the `GetUdi()` …

Fix `IWebhook.GetUdi()` and `IEntity.GetUdi()` extension methods

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml

Fixes #15213
Added missing translations in EN.xml based on EN_US.xml. I also removed translations that are not in the leading dictionary anymore.
Used my own application for managing Umbraco language xml files: https://github.com/SteveVaneeckhout/UmbracoTranslationHelper

Add missing translations in EN

---

src/Umbraco.Cms.Api.Management/Controllers/Document/AllowedChildrenDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/CreatePublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/DeletePublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/GetPublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UnpublishDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UpdatePublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetDocumentPermissionsCurrentUserController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetMediaPermissionsCurrentUserController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json

Some of the Management API controllers are lacking an explicit API version assignment, which means they become available in all API versions. As the Delivery API now has V2, those Management API controllers then map to both V1 and V2:
This PR ensures that all controllers have explicit API version assignments.
The Swagger doc for the Management API should _not_ have any V2 APIs 😄

Add missing API version attributes to Management API controllers

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorPropertyValueConstructorCacheBase.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueConstructorCache.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueCreator.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConstructorCache.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueCreator.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockPropertyValueCreatorBase.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ConstructorCacheClearNotificationHandler.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextBlockPropertyValueConstructorCache.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextBlockPropertyValueCreator.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockGridPropertyValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListPropertyValueConverterTests.cs

When block based editors construct their published values, they use a whole lot of reflection and on-the-fly IL generated types to construct their contained block items. In short, they activate a lot of what's going on in [`ReflectionUtilities`](https://github.com/umbraco/Umbraco-CMS/blob/release/13.0/src/Umbraco.Core/ReflectionUtilities.cs). 
Unfortunately the reflected results are not cached between requests, even though they can never differ as they are type bound. In fact, the results are not even cached between block based editors, so if two block based editors exist on the same page one or more of the same block types, the reflection is repeated for each editor. This also even applies to nested block editors.
The block editors do cache their published values, but all this reflection …

Cache block item constructors for block based editors

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

When a Block editor makes a call to `contentResource.getScaffoldByKeys()` (to get the element type schemas), it currently passed through a hardcoded ID of `-20`.  This patch replaces the hardcoded ID with the current page/node's ID, with a fallback on parent page/node, (and a final fallback on the previous hardcoded ID `-20`.
The motivation behind this pull request is that with my Contentment package's Data List editor has a feature to make use of the current page/node, but it can only do this when the `id` or `parentId` parameters are available in the `GetEmptyByKeys()` content API request.  This works fine within page-level property-editors, but it doesn't work with the BlockList/BlockGrid editors, _(this issue also applies to NestedContent, but since that is deprecated, I didn't look …

Block editors - replaces hardcoded -20 with current node ID

---

src/Umbraco.Web.UI.Client/src/less/application/grid.less

If there's an existing issue for this PR then this fixes #14890 
This should fix a problem (#14890) where an RTE in fullscreen mode would be partly covered by the left "menu" column due to a very high z-index.
To test this specific error, add the "fullscreen" plugin and command to RichTextEditor settings in appsettings.json, enable it on any RTE datatype and verify that clicking the Fullscreen button does in fact show the editor in full, without the left side menu obstructing it.
Test that right clicking in different contexts/sections still works (as in, there's no difference in how a right click context menu is shown, and everything is still clickable).

Prevent RTE in fullscreen being partially covered by the left menu column (should fix #14890)

---

src/Umbraco.Infrastructure/BackgroundJobs/RecurringBackgroundJobHostedServiceRunner.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15302
As described in the linked issue, the new `RecurringBackgroundJobHostedServiceRunner` has a little flaw in its logging: It doesn't log the actual names of the jobs it's starting, but the generic type of the hosted service instead:
This PR makes the logging a little bit more verbose, in order to log both the creation and the start-up of each individual hosted service - this time using the job names:
While I was here, I also changed all logging to use template based log messages.
All recurring jobs (hosted services) should start and run as per usual. The log should display the names of the jobs rather than the generic type of the hosted service.

Log meaningful job names and use template based log messages

---

src/Umbraco.Core/Models/DeliveryApi/ApiLink.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiUrlPickerValueConverterTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15322
See the linked issue for steps to reproduce.
After an internal discussion we have decided to:
1. Append the query string (if present) to the media link URLs just as we do with external link URLs.
2. Add a dedicated `queryString` property to hold the query string on its own. This is mostly useful for content links, as they do not have an URL.

Add query string info to links in API output

---

src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
src/Umbraco.Web.UI.Client/src/views/common/login-2fa.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15259
The well-intended changes in #14816 has the unfortunate downside of breaking 2FA, as described in the linked issue.
I have rolled back the necessary parts of #14816 to make 2FA work again. Also, the `AuthenticationController` should really return an explicit `ActionResult` when the 2FA validation succeeds, so I have updated that as well.
Get in touch with @kjac to do a pair testing session 😄 or setup 2FA as per [the docs](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication) to verify that it works.

Rollback some #14816 changes to fix 2FA

---

src/Umbraco.Core/HealthChecks/HealthCheckResults.cs
src/Umbraco.Core/Notifications/HealthCheckCompletedNotification.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJob.cs
src/Umbraco.Web.BackOffice/HealthChecks/HealthCheckController.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJobTests.cs

I was testing the Webhooks feature that has been added to Umbraco 13 and thought it would be nice if a webhook call could be made when one or more health checks are completed. To achieve this, a notification is needed. This PR introduces a `HealthCheckCompletedNotification`.
I intentionally created this PR in the v13 branch because it causes a breaking change due to modifications in the constructors of the `HealthCheckController` and the `HealthCheckNotifierJob`.
This PR can be tested by creating a notification and registering it in the Program.cs class like so:
```csharp
namespace Umbraco.Cms.Web.UI.Notifications;
public class TestHealthCheckCompletedNotification : INotificationHandler<HealthCheckCompletedNotification> …
```

Add HealthCheckCompletedNotification

---

src/Umbraco.Core/PublishedCache/IPublishedSnapshotAccessor.cs
src/Umbraco.Core/PublishedCache/UmbracoContextPublishedSnapshotAccessor.cs

Since Umbraco 10, the `IPublishedSnapshotAccessor` interface has described a `TryGetPublishedSnapshot` method with a nullable `IPublishedSnapshot` out parameter - using a `?` to indicate that the parameter can possibly be `null`.
Since the parameter has no attributes for code analysis, it should be assumed that it can possibly be null in all situations, regardless of whether the method returns `true` or `false`. Visual Studio and possibly other IDEs will complain about this if you don't do a null check on your own.
But since we know better, we can add the `[NotNullWhen(true)]` attribute to the out parameter. This effectively then tells that if the method returns `true`, the `IPublishedSnapshot` instance in the out parameter is not `null`.
<hr />
I don't think you can test something like …

Added `[NotNullWhen(true)]` attribute to `IPublishedSnapshotAccessor` and `UmbracoContextPublishedSnapshotAccessor`

---

src/Umbraco.Web.BackOffice/Controllers/MemberController.cs

If there's an existing issue for this PR then this fixes #14832 
change persisted IsApprove with user data if user HasAccessToSensitiveData
restore user data  IsApprove  IsLockedOut  IsTwoFactorEnabled  with persisted data

fixed #14832 user without  HasAccessToSensitiveData change sensitive data:  IsApproved IsApproved IsTwoFactorEnabled

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.info.controller.js

Follow-up on https://github.com/umbraco/Umbraco-CMS/pull/15017 to make it a bit simple to open content type editor and reduce some of the same logic based on content type.
I think it could also be useful to (package) developers.
Relates to https://github.com/umbraco/Umbraco-CMS/pull/15080

Add contentTypeEditor to editorService

---

src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js
src/Umbraco.Web.UI.Client/src/installer/steps/user.html
src/Umbraco.Web.UI.Client/src/less/installer.less

If there's an existing issue for this PR then this fixes #15036
I have added the toggle password function, which is used on the login screen to the Umbraco backoffice.
Also, I have changed the password field type from `text` to `password`, so the typed password is hidden per default.

Bugfix: #15036 - Password Is Not Hidden During Installation

---

src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card-grid.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.less

This PR makes add block in Block List consistent with Block Grid configuration.
**Block List**
**Block Grid**

Make Block List configuration consistent with Block Grid

---

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js

Adjust `editorService` to have a dedicated `documentTypePicker`, while the current allow specifying entity type, but fallback to `documentType` which is current behaviour and to avoid a breaking change.
This also streamline the concept that content type is both content, media and member type, while document type is more specific.
Related to https://github.com/umbraco/Umbraco-CMS/pull/15034

Adjust content type picker to support different content types

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs

Fixes AB#35485
If you turn on `AutoRedirectLoginToExternalProvider` it will send you in an endless loop, because we now redirect the user when logging out. This PR adds a check for the parameter `?logout=true` in the BackOfficeController to prevent this scenario. It also refactors the controller to reduce nesting and improve the general understanding of how external login providers work.

V13 RC: Fix regression for external login providers

---

src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs

If during startup any error occurs while generating the nuCache file, the file will be permanently locked and all non backoffice CMS requests will fail with a nuCache locked error.
This is because it will constantly try to run the  `MainDomRegister` method, which in turn tries to open the already opened nuCache files.
A previous attempt to address this issue was done in #12149, but it simply ignores a specific exception which both doesn't cover all the cases, and even when the correct exception is caught, will simply cause the website to load without any content in it's cache, causing 404s for all pages.
We were observing this with uSync configured to import content types and content on first boot, as that would throw a SQL deadlock exception, but it can also be caused by any connection …

Fixed potential NuCache file lock causing unusable website

---

src/Umbraco.Core/Models/PublishedContent/IPublishedPropertyType.cs
src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs

Currently it's not possible to determine the delivery API type of a property without the use of reflection.
The use case for such a feature is to transform the swagger so it returns the proper document types response models, similar to Umbraco's models builder.
(You can check it here: [https://github.com/ByteCrumb/Umbraco.Community.DeliveryApiExtensions](https://github.com/ByteCrumb/Umbraco.Community.DeliveryApiExtensions/blob/main/src/UmbracoDeliveryApiExtensions/Services/ContentTypeInfoService.cs#L77C15))
Example of the code that is currently necessary:
```c#
private static readonly FieldInfo? ConverterField = typeof(PublishedPropertyType).GetField("_converter", BindingFlags.NonPublic | BindingFlags.GetField | BindingFlags.Instance);
private static Type …
```

Expose the Delivery API CLR type

---

src/Umbraco.Web.UI.Client/src/less/variables.less

PR https://github.com/umbraco/Umbraco-CMS/pull/13179 changed z-index of block actions, but it did had a side-effect that the block actions are now on top over `umb-editor` which is shown in infinite editing.
**Before**
**After**

Update z-index of block actions

---

src/Umbraco.Core/ExpressionHelper.cs
tests/Umbraco.Tests.Integration/ManagementApi/AuditLog/ByKeyAuditLogControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/AuditLog/ByTypeAuditLogControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/AuditLog/CurrentUserAuditLogControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Culture/AllCultureControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/DataType/Folder/ByKeyDataTypeFolderControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/DataType/Folder/CreateDataTypeFolderControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/DataType/Folder/DeleteDataTypeFolderControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/DataType/Folder/UpdateDataTypeFolderControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/AllLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/ByIsoCodeLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/CreateLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/DeleteLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/Item/ItemsLanguageEntityControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/UpdateLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiUserGroupTestBase.cs
tests/Umbraco.Tests.Integration/ManagementApi/UserGroupAssertionModel.cs

I've created the ManagementApiUserGroupTestBase Class. 
This allows us to specify if the UserGroup is Allowed or not and which StatusCode is expected for each test. All the tests in the base class are virtual, so they can be overwritten if additional setup for the specific test is needed. 
For each User Group in the test base, there are two tests: 'Have_Access' and 'Dont_Have_Access.' Only one of these tests should run for a particular User Group and endpoint. We determine which test to run by setting the 'Allowed' property to true or false. If 'Allowed' is true, the 'Have_Access' test is executed.
In each base test, we assert the response, excluding the Unauthorized tests. The response is obtained from the 'AuthorizedRequest()' method in the base class. This method authenticates a user …

V14 QA Authorization integration test, DRY base class

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilder.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsContentExtensions.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsContentTypeExtensions.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsExtensions.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsFileExtensions.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsMemberExtensions.cs
src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsUserExtensions.cs

As discussed in https://github.com/umbraco/Umbraco-CMS/pull/15345#discussion_r1413634361, the UI for webhook events now contains a search bar and already orders them by `eventName`, so there's no reason for registering them in any specific order.
Although changing the base class from `OrderedCollectionBuilderBase` to `SetCollectionBuilderBase` is a simple change, it does mean you have to use `Add<T>()` instead of `Append<T>()` to add registrations, which does mean it's a breaking change. I don't think it warrants adding a similar method that simply forwards `Append<T>() => Add<T>()`, as we've only released it in RCs and should keep the final release as clean as possible.

Change `WebhookEventCollectionBuilder` to set collection

---

src/Umbraco.Core/Deploy/IFileTypeCollection.cs

While technically a breaking change, it was not expected this interface was in use by anyone. However, to be safe, this fixes the breaking change by providing a default implementation.

Fixing PR #15318 which updated an interface, which is breaking

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

This fixes #14914 
When the model is being created from the scaffolding to push into the infinite editor it overwrites the default value with `undefined` if the property doesn't exist in the `dataModel` object. This causes an issue when a default value is injected via a notification. The original issue only mentions an issue with this in the content, but this is also an issue with the settings tab. As the code in the fix is ran through by both the content and settings app of the block list, it fixes it in settings too.
This won't impact subsequent saves/loads as all data has a default value, whether that be a 0 or an empty string/array/object etc.
In addition to the recordings below I also tested the copying of block list items, deleting and nested block lists.
Here it is pre-fix, the doc …

Don't overwrite default values in the block list editor

---

src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14913
As the linked issue describes, Media Picker 3 does not work as a macro parameter. 
Since macros are obsolete from V14, this PR removes Media Picker 3 from the list of applicable macro parameters.
1. Create a macro.
2. Add a macro parameter.
3. Verify that Media Picker 3 is _not_ selectable as macro editor - only Multiple Media Picker and the legacy Media Picker should be available.

Media Picker 3 should not be used as a macro parameter

---

src/Umbraco.Cms.Api.Management/Factories/UserGroupPresentationFactory.cs
src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/UserGroupBase.cs
src/Umbraco.Core/Services/UserGroupService.cs

This PR adds the ability to explicitly specify content and media root access when creating/editing user groups via the Management API.
The current backoffice API uses integer IDs when specifying user group start nodes. Thus it's possible to pass the `Constants.System.Root` constant for root access.
The Management API on the other hand uses GUID keys. As no constant exists for "system root key" (rightfully so!), and because a `null` value for start node means "no start node defined", we need to add extra request model properties to explicitly define root access for content and media (`DocumentRootAccess` and `MediaRootAccess` respectively).
These properties do _not_ take precedence over any specified start nodes; if the API request specifies both a start node key (not `null`) _and_ root …

Management API: Allow specifying root access for user groups

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15332
When opening content type editor from content node via infinite editing or directly from setttings section a few console errors happened due to missing `umbVariantContent` in the context and `vm.availableBlockTypes` returning empty array and this `vm.availableBlockTypes[0]` returned undefined.

Fix console errors in content type editor with single block mode

---

src/Umbraco.Core/ExpressionHelper.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/ByIsoCodeLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/DeleteLanguageControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/Item/ItemsLanguageEntityControllerTests.cs
tests/Umbraco.Tests.Integration/ManagementApi/Language/UpdateLanguageControllerTests.cs

Removed change in expression helper which failed on the pipeline.
Refactored language test so we keep in scope.

V14 QA authorization integration tests refactor language

---

src/Umbraco.Core/Constants-HttpClients.cs
src/Umbraco.Core/Media/EmbedProviders/OEmbedProviderBase.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs

- Adds a named `IHttpClient` client for Webhook firing.
- Uses the `IHttpClientFactory` to then create a HttpClient, instead of just newing it up.
- This means that users of umbraco can now overwrite the named HttpClient with their configuration. 
- Create a Document type with allow as root set to true.
- Create a webhook (getting url from webhook.site or other testing environment)
- Set the Content is published event.
- Create some content.
- Assert your endpoint gets called.
- We can assert that you can overwrite configuration, with the test composer down below:
``` 
using System.Diagnostics;
{
{ …
```

Use named HttpClients

---

src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js

Fixes #15341
Ensure the client sends booleans and not integers when using toggles on the members

Ensure the toggles return booleans and not integers.

---

src/Umbraco.Core/Services/WebhookLogFactory.cs

- Retry count was not logged properly when an error occurred, this has been changed to log retry count every time.
- Request headers was not logged correctly:
- This should now log request headers correctly👍 
- Create a doc type with allowed as root set to true
- Create a webhook, with URL set to a given endpoint (use webhook.site or other for testing)
- Also add "Content is published" event to webhook.
- Create some content with the doc type you created in step 1.
- Look in your webhook logs, this should now display the request headers 🙌 
- stop solution
- insert `throw new Exception();` in `WebhookFiring` L102 (just after the try clause)
- Run solution
- Publish the content again.
- Look in your webhooklogs again, this should now have retry count logged 👍

V13: Log retrycount and properly log request headers

---

src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html

- Before when exceptions would happen, the webhook logs would not be helpful.
- This PR remedies that by instead removing all the Reponse/Request information when an exception has occurred, and instead links the user to the logs to inspect 👍 
- Manually throw an exception when webhookfiring, by putting in ` throw new Exception();` on L102 in `WebhookFiring.cs`
- Run umbraco
- Create a doc type with allow as root set.
- Create a webhook with Content Published event.
- Create some content with the doc type you just created.
- Navigate to the webhook logs (this might take up to 10 seconds)
- Click on your webhook request that just failed (should be the latest one)
- This should now display a helpful message and link you to the logs  👍

V13: Link to error when Webhook request exceptions happen

---

src/Umbraco.Core/Models/WebhookLog.cs
src/Umbraco.Core/Models/WebhookResponseModel.cs
src/Umbraco.Core/Services/IWebhookLogFactory.cs
src/Umbraco.Core/Services/WebhookLogFactory.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddExceptionOccured.cs
src/Umbraco.Infrastructure/Persistence/Dtos/WebhookLogDto.cs
src/Umbraco.Infrastructure/Persistence/Factories/WebhookLogFactory.cs
src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
src/Umbraco.Web.Common/Models/WebhookLogViewModel.cs
src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html

- Refactors WebhookLog factory to not take WebhookResponse model, but instead Request & Response, so we can always log request.
- Adds `ExceptionOccured` property to webhook log, so we can display it in the backoffice
- Create doc type
- Create webhook with URL `https://some.where/`
- Select `Content Published` event
- Create some content with doc type from step 1.
- Go to webhook logs, this should now display your error in the response body, and still link you to the logs for more details.

V13: Log webhook firing exceptions when they happen

---

Directory.Packages.props
src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
tests/Directory.Packages.props

Although PR https://github.com/umbraco/Umbraco-CMS/pull/15362 generally improved the Central Package Management setup and ensured we don't depend on any outdated, vulnerable dependencies, it also resulted in having all transitive dependencies listed as direct dependencies.
The main reason for enabling `CentralPackageTransitivePinningEnabled` was to fix a dependency version conflict caused by Umbraco.Code. This PR instead references an updated version that uses the latest Microsoft.CodeAnalysis.CSharp.Workspaces version 4.8 (so it aligns with Microsoft.CodeAnalysis.CSharp that's used by the CMS).
Since Umbraco.Code 2.1.0 isn't released to NuGet yet, I've added a separate commit that adds the prereleases feed, so we can first test out the fix. Once released to NuGet, that commit can be …

Disable transitive package version pinning

---

src/Umbraco.Core/Constants-WebhookEvents.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs

As mentioned in https://github.com/umbraco/Umbraco-CMS/pull/15375#discussion_r1420066349, providing the current date/time in a header doesn't add any real value. The date/time that would be of interest is when the event was raised and the `WebhookRequest` was created (as they're 'fired' some time later in a background thread), but that's not stored in the database yet. So lets ensure we don't sent this header yet! Besides that, I've also moved the header names into constants 👍🏻
For testing, I believe a code review should suffice, as there's no big changes!

Remove date header from webhook request and use constants

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorPropertyValueConstructorCacheBase.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15421
See the linked issue for a detailed description and steps to reproduce.

Ensure thread safety for block editor constructor caches

---

src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
src/Umbraco.Infrastructure/WebAssets/JsInitialize.js
src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
src/Umbraco.Web.UI.Login/index.html
src/Umbraco.Web.UI.Login/package-lock.json
src/Umbraco.Web.UI.Login/package.json
src/Umbraco.Web.UI.Login/src/external.ts
src/Umbraco.Web.UI.Login/src/index.ts
src/Umbraco.Web.UI.Login/vite.config.ts

Fixes #15397 
This PR fixes a regression where the UI library was no longer exported to `window.uui`, because we tried to use the es version of the library. However, since this is expected to be present inside the backoffice, we have reverted to the UMD version of the library.
This affects the login screen, which not only has its own Index.cshtml file, where it can load itself as it pleases, but also has to work inside the backoffice, where only CommonJS is supported. Therefore we will build the login assets in IIFE mode where we can replace imports from `@umbraco-ui/uui` dynamically with `window.uui` in the build process.

V13: Regression with global window.uui export

---

src/Umbraco.Cms.Api.Management/Factories/DataTypePresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/DataType/DataTypeViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeModelBase.cs

Simple renaming of propertyEditorAlias properties on Management api models to better align with the new way of doing things.

PropertyEditor(UI)Alias name refactor

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/ChangeLogStatusCode.cs

- `ChangeLogStatusCode` was using the current `WebhookLogDto` model, and thus makes it no longer idempotent.
- This was causing errors when migrating from rc2 -> final as the database model had changed. (Note this is not a problem if you upgrade from rc2 -> rc3 -> final.
- Create a 13-rc2 database, (check out the `release-13.0.0-rc2` tag, then install)
- Change to this branch
- Run the upgrader

13: Add old databasemodel to ChangeLogStatusCode migration

---

src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs

Following on from #15437, the permissions are still too restrictive. 
Users in groups without access to the content section are not able to load any section tree, because they are not authorise to get all languages.
Fixes #15435
The problem:
* Set up a group with access to settings, but not content
* Set up a user in that group
* Log in to that user
* You are able to view the settings tree

Remove content section access policy from GetAllLanguages endpoint.

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/DataTypeFolderControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Folder/DocumentTypeFolderControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Folder/MediaTypeFolderControllerBase.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs

- Setting the correct policies for folder controller base classes
- User groups with no access to Settings section shouldn't be able to create/delete folders - Editors for example

V14: Tighten permissions for folder controllers

---

build/azure-pipelines.yml
tests/Umbraco.Tests.AcceptanceTest.UmbracoProject/SQLiteMemoryComposer.cs
tests/Umbraco.Tests.AcceptanceTest.UmbracoProject/SqlServerDelayedDurabilityComposer.cs
tests/Umbraco.Tests.AcceptanceTest.UmbracoProject/Umbraco.Tests.AcceptanceTest.UmbracoProject.csproj
umbraco.sln

This builds on top of PR https://github.com/umbraco/Umbraco-CMS/pull/14042 and configures the E2E Acceptance Test build to use a SQLite in-memory database and optimizes the SQL Server database to [force delayed durability](https://learn.microsoft.com/en-us/sql/relational-databases/logs/control-transaction-durability?view=sql-server-ver16#delayed-transaction-durability) (which should improve throughput by minimizing log I/O).

Use SQLite in-memory database and configure database optimizations for E2E tests

---

src/Umbraco.Cms.Api.Management/Controllers/PartialView/Folder/CreatePartialViewFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/PartialView/Folder/DeletePartialViewFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/PathFolderManagementControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Folder/CreateScriptFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Folder/DeleteScriptFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Folder/CreateStylesheetFolderController.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Folder/DeleteStylesheetFolderController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json

The file system folder management endpoints do not follow the rest of the API standard of returning HTTP 201 Created when creating new resources. This PR fixes it.
While I was there, I added the missing response types (HTTP 404, HTTP 400) for all file system "create" and "delete" folder endpoints.
Use Swagger 😄 
1. Verify that the "create folder" endpoints for Partial Views, Stylesheets and Scripts return 201 when folder creation is successful.
2. Verify that the 201 response code is documented in Swagger for all the file system "create folder" endpoints.
3. Verify that 400 and 404 errors are documented in Swagger for all the file system "create folder" and "delete folder" endpoints.

Make "create folder" return HTTP 201 Created for file system folders

---

src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs

This ensures that any assets loaded as "modules" also get the right Access-Control-Allow-* headers, i.e. any javascript modules loaded from the App_Plugins/ folder will be subject to this.

V14: add the cors policy as first item on the pipeline filter

---

src/Umbraco.Infrastructure/Migrations/PreMigration/DataTypeSplitDataCollector.cs

Since we are changing the data structure for datatypes slightly and are removing some classes for v14 we need to collect data on the current state so we can migrate the data when those data points are not there anymore at the start of v14
- Add one or more propertyEditors trough a package manifest, for example:
```
{
"propertyEditors": [
{
"alias": "test.manifestEditor",
"name": "Test Manifest Editor",
"icon": "icon-list",
"group": "Common",
"editor": {
"view": "~/App_Plugins/Test/manifest.html",
"supportsReadOnly": true
}
}
],
"css": [
"~/App_Plugins/Suggestions/suggestion.css"
],
"javascript": [
"~/App_Plugins/Suggestions/suggestion.controller.js"
]
}
```
- Add one ore more propertyEditors trough code, for example
```
using …
```

Added a temporary DataCollector for v14 editorAlias migrations

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeAuth.cs
src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
src/Umbraco.Web.Common/Authorization/AuthorizationPolicies.cs

This adds explicit access policy checks for content template handling (create and delete).
1. When creating content templates from the content tree, the newly introduced `AuthorizationPolicies.ContentPermissionCreateBlueprintFromId` policy must be fulfilled (user must have "Create content template" permission within the scope of the content targeted as a blueprint).
2. When creating or deleting content templates from the settings section, the `AuthorizationPolicies.TreeAccessDocumentTypes` must be fulfilled (user must have access to content types).
Besides added security, this also ensures that uses without access to the content root is still allowed to create content templates, provided they fulfil the access requirements outlined above.
- Admin users should be able to create content …

Add policies for content template handling

---

src/Umbraco.Core/Deploy/ArtifactDependency.cs
src/Umbraco.Core/Deploy/ArtifactDependencyCollection.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/15318 causes a regression in adding artifact dependencies to `ArtifactDependencyCollection` for the same UDI, but with a different ordering flag set. Instead of not adding the artifact when the dependency mode was the same, the logic was changed to only prevent downgrading it from `ArtifactDependencyMode.Match` to `ArtifactDependencyMode.Exist`. So dependencies with the same mode would override an already added one and thereby potentially reset the ordering flag.
Deploy actually relied on this implementation detail, because a dependency to the parent content node would first be added using `new ArtifactDependency(art.Parent, true, ArtifactDependencyMode.Exist)` (with ordering enabled), before any dependencies/references within the content …

Ensure artifact dependency keeps correct mode, ordering and checksum values

---

src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs

- Added support for token revocation and session sign-out for backoffice auth.
> [!NOTE]  
> Both **Umbraco.Web.UI** and **Umbraco.Web.UI.New** projects can be used for testing.
> Revoke a token (Postman):
- Get a token (_through `/umbraco/management/api/v1/security/back-office/authorize` and then `/umbraco/management/api/v1/security/back-office/token`_);
- Verify that you can use it in a Management API endpoint;
- Call the revocation endpoint with that token:
```http
POST /umbraco/management/api/v1/security/back-office/revoke
client_id=umbraco-back-office
token={token to revoke}
Content-Type: application/x-www-form-urlencoded
```
- Verify that it returns 200 OK;
- Verify that you can no longer use the revoked token.
</br>
> Terminate a session (browser):
- Login to Umbraco;
- Verify that …

V14: User token revocation and session sign-out

---

src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
src/Umbraco.Cms.Api.Delivery/Services/QueryBuilders/ApiContentQueryFactory.cs
src/Umbraco.Cms.Api.Delivery/Services/QueryBuilders/ApiContentQuerySelectorBuilder.cs
src/Umbraco.Cms.Api.Delivery/Services/QueryBuilders/IApiContentQueryFactory.cs

Currently the Content Delivery API is tightly coupled to Lucene. That means that any other Examine implementation cannot work currently with the Content Delivery API without re-writing the entire `IApiContentQueryProvider` which is a substantial amount of code. 
This change introduces the `IApiContentQueryFactory` which is responsible for creating the IQuery used to as the entry point Examine query for the content delivery API. 
This means that implementations like ExamineX can work without copying/rewriting the whole IApiContentQueryProvider which is a substantial amount of code that is very opinionated.
All tests should pass

Decouple Lucene from Content Delivery API

---

src/Umbraco.Core/Webhooks/Events/Content/ContentDeletedWebhookEvent.cs
src/Umbraco.Core/Webhooks/Events/Content/ContentUnpublishedWebhookEvent.cs

The aliases for the `ContentDeletedWebhook` and the `ContentUnpublishedWebhook` were wrong.
Fixes:  https://github.com/umbraco/Umbraco-CMS/issues/15486

Correct aliases for ContentDeletedWebhook and ContentUnpublishedWebhook

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html

I noticed clear of date picker input no longer works and clicking the clear button opens the datepicker popup as well.
It is a regression in this PR https://github.com/umbraco/Umbraco-CMS/pull/14767 because it changed model binding to input from `datetimePickerValue` to `datetimePickerInputValue`, but in `clearDate()` function it only reset `datetimePickerValue` and `value` - not `datetimePickerInputValue` which is added in this line: https://github.com/umbraco/Umbraco-CMS/pull/15338/files#diff-9264addb1e938ef2573ad77a7ee5e17a6b7dbf35e87f727de1010406b318f43aR91
The date is however cleared after save and refreshing the page, but not directly after clicking the clear button.
**Before**
https://github.com/umbraco/Umbraco-CMS/assets/2919859/fd8c993b-0558-4134-ab31-f219da79878a
**After** …

Ensure datepicker input is cleared

---

src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs

- Create an implementation of ie `NestedContentSingleValueConverter`
- Override `GetPropertyCacheLevel`
- Check that your overridden property cache level is respected
We, on the heartcore saw, that our custom ValueConverters wasn't respected. This caused a few headaches, where when content containing nestedcontent had been copied, sometimes the key would be copied - causing incorrect data to be returned from the cache.
Investigation showed that our cache level wasn't being respected, hence we came up with this fix.
A more proper fix would be to ensure that nested content keys isn't copied when content is, we will discuss a potential fix for this.

Pass cache level defined in value converters

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

This fixes the issues described here: https://github.com/umbraco/Umbraco-CMS/issues/15512
The PR changes the way that `createLink` inside `tinymce.service.js` parses a locallink. The old implementation used `lastIndexOf` which made it impossible to use `}` as part of the anchor/query string (see the issue).
I've replaced this with simply using `indexOf` to get the frist occurrence of `}` which will be the closing curly brace for the locallink-placeholder.
Examples:
| Value | Before | After |
|------|------|-------|
| `/{localLink:umb://document/dd2b2f19a23f41fb891e22567cf9eda1}` | ✅ | ✅ |
| `/{localLink:1061}` | ✅ | ✅ |
| `/{localLink:umb://document/dd2b2f19a23f41fb891e22567cf9eda1}?key=value` | ✅ | ✅ |
| `/{localLink:umb://document/dd2b2f19a23f41fb891e22567cf9eda1}?key={{value}}` | ⛔ | ✅ …

Fixes #15512 to allow curly braces in anchors

---

src/Umbraco.Cms.Api.Management/DependencyInjection/MediaBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/MediaPresentationModelFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Routing/DefaultAbsoluteUrlBuilder.cs
src/Umbraco.Cms.Api.Management/Routing/IAbsoluteUrlBuilder.cs
src/Umbraco.Core/Routing/DefaultMediaUrlProvider.cs
src/Umbraco.Core/Routing/DefaultUrlAssembler.cs
src/Umbraco.Core/Routing/IUrlAssembler.cs

Made a replaceble solution to support absolute urls for media/user av…atars in the management API as the host for the frontoffice app and backend might be different.
- extracted a private method from DefaultMediaUrlProvider into its own class (IUrlAssembler)
- used it with absolute mode together with the current host url obtained from UmbracoContext to turn a url into an absolute one (IAsoluteUrlBuilder)
- used that turn the media/avatar urls into absolutes during mapping
- Upload and set a user avatar, then retrieve it. AvatarUrls should be absolute and correct.
- Upload and media item, then retrieve it. Urls should be absolute and correct.

[v14] Absolute media urls

---

src/Umbraco.Core/Notifications/ContentScaffoldedNotification.cs
src/Umbraco.Core/Notifications/ScaffoldedNotification.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
src/Umbraco.Infrastructure/PropertyEditors/ComplexPropertyEditorContentNotificationHandler.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs

Issue: https://github.com/umbraco/Umbraco-CMS/issues/14870
- Added a new ContentScaffoldedNotification
- Published the notification when a new scaffold has been created from a blueprint (content template)
- Linked up the ComplextPEContent handler to do the same cleanup for the new notification as when copying.
- registered handlers to the event for blocklist, blockgrid and nested content
See reproduction steps in linked issue https://github.com/umbraco/Umbraco-CMS/issues/13698

Run the same cleanup with scaffolding content as when copying.

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js

To continue supporting Rich Text Editor Property Editor implemented via `<umb-property>` without any further Backoffice implementations in its surroundings, this PR introduces a No Blocks Mode that will be active when the requirements for Blocks aren't meet.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/15474

Fix: No Blocks Mode for RTE when required context for Blocks is not present

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

After the upgrade to TinyMCE 6, they removed the `stateSelector` configuration and replaced it with the more complex `onSetup` method to properly toggle buttons. Also, it is now pertinent that we add buttons to the UI by invoking the `addToggleButton()` rather than the `addButton()` function.
**Before**
```js
stateSelector: 'img[data-udi]'
```
**After**
```js
onSetup: function (api) {
const changed = editor.selection.selectorChangedWithUnbind('img[data-udi]', (state) =>
api.setActive(state)
);
return () => changed.unbind();
},
```

V13: TinyMCE does not toggle plugin buttons

---

tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataType.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataTypeFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ApprovedColor.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Label.spec.ts

Updated api tests for DataType
Added ui tests for basic functions of DataType
Added ui tests for Approved color
Added ui tests for Label

V14 Added acceptance test for basic functions of Data Type, Approved Color and Label

---

src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
src/Umbraco.Web.Common/Security/MemberSignInManager.cs
src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15496
This ensures the security stamp is only updated once per request.

Only update security stamp once per request

---

src/Umbraco.Cms.Api.Management/Controllers/Security/ConfigurationSecurityController.cs
src/Umbraco.Cms.Api.Management/Controllers/Security/ResetPasswordController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/ConfigurationUserController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Current/ConfigurationCurrentUserController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/PasswordBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/IPasswordConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IUserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/PasswordConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/ViewModels/Security/PasswordConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Security/SecurityConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/Current/CurrenUserConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/UserConfigurationResponseModel.cs

- Adds new `security/configuration` endpoint. This only has password configuration property
- Adds new `user/current/configuration` endpoint. Which has some current user configuration and the password configuration.
- Adds new `user/configuration` endpoint. Which also has some user configuration and password configuration.
- Adds new `PasswordConfigurationPresentationFactory`, which can create the Password configuration for the 3 new endpoints.
- use swagger to test the three new endpoints.

V14: Add security related configurations

---

src/Umbraco.Core/PublishedCache/PublishedCacheBase.cs
src/Umbraco.PublishedCache.NuCache/ContentCache.cs
src/Umbraco.PublishedCache.NuCache/MediaCache.cs

- Fixes https://github.com/umbraco/Umbraco-CMS/issues/15473;
- The reason for the bug was that we were using the wrong ctor which wasn't setting the variation context that is used in the implementation of `GetByContentType()` - this was why it returned different results when the content type varied by culture.
- Create the following **ProductsController**:
```c#
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
public class ProductsController : UmbracoApiController
{
private readonly IUmbracoContextFactory _umbracoContextFactory;
public ProductsController(IUmbracoContextFactory umbracoContextFactory)
=> _umbracoContextFactory = umbracoContextFactory;
// /umbraco/api/products/test
public …
```

V10: Pass in variation context to published cache

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/MoveDataTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/Dictionary/MoveDictionaryController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CopyDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/MoveDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/CopyMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/MediaTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/MoveMediaTypeController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CopyDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/MoveDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/CopyMediaTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MoveMediaTypeRequestModel.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Core/Services/IContentTypeServiceBase.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeStructureOperationStatus.cs

- Created endpoints for copying and moving content and media types;
- The functionality is similar to how it works in the current (old) backoffice;
- The implementation is shared between content and media types.
- Verify that you can copy and move content/media types to folders or root (`"targetId":null`).

V14: Copy and move endpoints for content and media types

---

src/Umbraco.Core/Services/FileServiceBase.cs
src/Umbraco.Core/Services/ScriptService.cs
src/Umbraco.Core/Services/StylesheetService.cs

There was an issue where you were unable to create scripts in root from the backoffice, this was because the validation was a bit too strict. 
The scripts and CSS folders have always been created automatically when the first file was created in root, and this behaviour is still there in V14, but only when root was specified with an empty string, this PR also adds "/" as a valid way to specify root.

V14: Fix not being able to create scripts in root

---

src/Umbraco.Cms.Api.Delivery/Services/ApiMediaQueryService.cs

The Delivery API Media Query Service logs direct query inputs. This could theoretically be subject to malicious abuse towards people with log viewer access.
This is theoretically a security vulnerability and was originally reported as a security advisory. But the threat is so very low that we've decided to handle it as a regular fix.
See the original security advisory for details to reproduce.
With this PR applied, the log messages look like this:

Do not log direct query inputs

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/views/webhooks/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/webhooks/edit.html

Add localization keys for webhooks edit view. Add keys for:

Add localization keys for webhooks edit view

---

src/Umbraco.Cms.Api.Common/Mvc/ActionResults/EmptyCreatedAtActionResult.cs
src/Umbraco.Cms.Api.Management/Controllers/ManagementApiControllerBase.cs

Currently the "Created at" responses from the Management API contain a response body with `"null"`. Turns out the built-in `CreatedAtActionResult` is built upon `ObjectResult`, which outputs `null` values in the response body.
The `"null"` response is messing with the new back-office client.
To work around this, a new `EmptyCreatedAtActionResult` has been added to the `Api.Common`, and this is then used for all "Created at" responses created by Management API base controller.
The `EmptyCreatedAtActionResult` is purposely placed in `Api.Common` and made public (sealed), so it can be reused in other APIs.
"Created at" responses are built in different ways depending on the action performed. To test this PR, verify that the following API operations return a HTTP201 status code, and that the …

"Created at" responses should not have a response body

---

src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/rte.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js

Fixes #15515
Fixes #15581
Potentially fixes #14911
This has been a problem probably since Umbraco 11, where we upgraded TinyMCE from v4 to v6. A lot of functionality was lost or replaced with built-in configuration including the sticky toolbar. The grid layout uses the option `toolbar_sticky` from TinyMCE, but at some point, it stopped showing the toolbar in certain scenarios where multiple rich text editors are shown in a grid layout on the same page.
The code for `rte.component.js` and `grid.rte.directive.js` has now been aligned so the behavior of the rich text editor should be the same whether shown on a page or in a grid layout editor. However, blocks are not supported in the grid layout editor so that is still disabled. This PR fixes a small typo where the `umbblockpicker` was not …

V13: Rich text editor does not show its toolbar on grid layout rte's

---

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextParsingRegexes.cs

If there's an existing issue for this PR then this fixes #15494
This adds an optional class attribute in the regex for finding block placeholders in the RTE markup, to make it work with the class attribute added by the rich text editor.
Create a rich text editor with a block. Insert the block in the rich text editor, make sure the class attribute is added to (or add it manually). Verify that the block actually renders in the frontend.

Adds optional class attribute to regex for parsing RTE blocks

---

src/Umbraco.Cms.Api.Delivery/Configuration/DeliveryApiConfiguration.cs

See details in PR https://github.com/umbraco/Umbraco-CMS/issues/15610 
The `DeliveryApiConfiguration.cs` file had the incorrect link, with a TODO intending to correct it. I removed the TODO, and added the correct link.

Updates DeliveryApiConfiguration to include link to new media delivery api article 

---

src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs

Decription/reproduction can be found in the original issue: 
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/14561
The line:
`target.LockoutEnd = source.IsLockedOut ? DateTime.MaxValue.ToUniversalTime() : (DateTime?)null;`
only would set the LockedOut value to the maxvalue (so basically, infinite) so I've changed the following to fix this:
- Injected the `_securitySettings` (not entirely sure if it's considers as breaking, also because of the interaction with the obsolete method) 
- Added the configured minutes to the configured value (default 43200minutes / 30 days)
This will set the lockedout date correclty.
**However**
I feel like this is an issue, but mostly in `Microsoft.AspNetCore.Identity` as it seems to have no check for this.
When a user is locked out, and the locked out …

Now properly checks the lockedoutdate

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

Fixes #15588
A minor regression was introduced with #15063 where the `editorState` held an actual id when used in the Document Type Editor as well, but since this is not real content, the request to GetEmptyByKeys would throw an error whenever you insert any block capable editor on a document type (e.g. rich text editor, block list, and block grid).
This has been fixed by checking if we are inside a content editor context or editing a document type by checking for the presence of the property `contentTypeKey` on `editorState.getCurrent()`, which should only be present when editing actual content, which has an actual id representing content in the database.

V13 RC: Document types throw an error when inserting a block capable editor

---

src/Umbraco.Cms.Api.Management/Controllers/Document/DeleteDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/RecycleBin/DeleteDocumentRecycleBinController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/RecycleBin/DocumentRecycleBinControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/RecycleBin/RecycleBinControllerBase.cs
src/Umbraco.Cms.Api.Management/Umbraco.Cms.Api.Management.csproj
src/Umbraco.Core/Services/ContentEditingService.cs
src/Umbraco.Core/Services/ContentEditingServiceBase.cs
src/Umbraco.Core/Services/IContentEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.DeleteFromRecycleBin.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.MoveToRecyleBin.cs
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj

This PR adds missing endpoints for deleting documents from anywhere and from the recycle bin specifically.
Create document type
```
{
"alias": "testDocType",
"name": "testDocType",
"description": "testDocType",
"icon": "umb:wand",
"allowedAsRoot": true,
"variesByCulture": false,
"variesBySegment": false,
"isElement": false,
"properties": [
{
"id": "7A9B8D0F-EC59-440F-A47A-79C9C4E65D25",
"sortOrder": 0,
"alias": "testProperty",
"name": "testProperty",
"description": "testProperty",
"dataTypeId": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
"variesByCulture": false,
"variesBySegment": false
}
]
}
```
create document (use ID from location header in previous request)
```
{
"values": [
{
"culture": null,
"segment": null,
"alias": "testProperty",
"value": "testValue"
}
],
"variants": [
{
"culture": …
```

Add management api delete document endpoints

---

src/Umbraco.Cms.Api.Management/Controllers/Dictionary/CreateDictionaryController.cs
src/Umbraco.Cms.Api.Management/Controllers/Dictionary/UpdateDictionaryController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/CreateDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UnpublishDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Content/ContentPermissionAuthorizer.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Content/ContentPermissionHandler.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Content/ContentPermissionResource.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Content/IContentPermissionAuthorizer.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Dictionary/DictionaryPermissionAuthorizer.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Dictionary/DictionaryPermissionHandler.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Dictionary/DictionaryPermissionRequirement.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Dictionary/DictionaryPermissionResource.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/Dictionary/IDictionaryPermissionAuthorizer.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Persistence/Repositories/ILanguageRepository.cs
src/Umbraco.Core/Services/AuthorizationStatus/ContentAuthorizationStatus.cs
src/Umbraco.Core/Services/AuthorizationStatus/DictionaryAuthorizationStatus.cs
src/Umbraco.Core/Services/ContentPermissionService.cs
src/Umbraco.Core/Services/DictionaryPermissionService.cs
src/Umbraco.Core/Services/IContentPermissionService.cs
src/Umbraco.Core/Services/IDictionaryPermissionService.cs
src/Umbraco.Core/Services/ILanguageService.cs
src/Umbraco.Core/Services/LanguageService.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LanguageRepository.cs
src/Umbraco.Web.Common/Authorization/AuthorizationPolicies.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentEditingServiceTests.cs

The Management API is lacking support to deny access to certain actions on resources based on the allowed cultures configured on User Groups. This PR aims to resolve this in the following way
- Expand the contentPermission Authorization design to take into account an optional Set of cultures on the ContentPermission resource. When set, all these cultures must be accessible to the user trough its configured groups
- Add this list to the auth request made on controller level for: document creation, document editing, document publishing and document unpublishing.
- Do something similar for Dictionary items create/update
- It might be prudent to apply similar logic to
- document deletion: if the user has access to all languages for which content data exists
- document move/sort: if the user …

Implemented culture based authorization for content

---

src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs

When @bergmania was merging https://github.com/umbraco/Umbraco-CMS/pull/15593 up to the latest versions, he noticed that the changes didn't affect parsing references from macros. Although the `RichTextPropertyValueEditor` and `GridPropertyValueEditor` already used `IHtmlMacroParameterParser` to get references from the macro parameter editors, this implementation didn't use the `IDataValueReferenceFactory` (and relied on value editor implementing `IDataValueReference` directly). After applying this PR, the factories will also be used when getting references, ensuring full compatibility.
To test this, first create a macro that uses e.g. the Multiple Media Picker as parameter. Add this macro to a RTE or (legacy) Grid editor property, pick some media items and save/publish the page. Even …

Get references from macro parameters using IDataValueReferenceFactory

---

src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs

https://github.com/umbraco/Umbraco-CMS/issues/15598
The problem that causes the issue above is that the `TagPropertyIndexValueFactory` uses the JSON base class which tries to detect JSON in the property value. However, since the tags are stored as CSV, it isn't valid JSON and therefore no values get added to the value set. I've changed the `TagPropertyIndexValueFactory` to first try the usual JSON values, if that comes back empty, it will then try to get values as if they were stored as CSV.
To test, set the default Tags property editor to be stored as CSV and then add a property to any document type that uses said property editor. Add some values and save. Check the ExternalIndex and you should now see that the tags property is indexed.

Fix for issue 15598

---

src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs

When saving an existing or creating a new webhook the id is updated to 0, because the id property isn't mapped.
In a future release `int` id may be removed in favor of `Guid` id/key, but for now `IWebhook` inherits `IEntity` which has `int` id property, so we should map this like other mappings, e.g. `LanguageMapDefinition`.
**Before**
https://github.com/umbraco/Umbraco-CMS/assets/2919859/4ec73ad2-55d7-487e-b3d6-067d9c3d368b
**After**
https://github.com/umbraco/Umbraco-CMS/assets/2919859/634f34a8-1376-487b-a4eb-88043795c394

Map webhook id property

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tags/umbtagseditor.directive.js

If there's an existing issue for this PR then this fixes #14519
This adds a check to validate that a tag value marked as a JSON type is valid JSON and if not falls back to try and parse as a CSV value.
Steps to reproduce
- Create a document type with a tags property;
- Create some content and add a few tags;
- Change the tags datatype to store data as CSV;
- Add another set of tags, like a,b,c;
- Change the tags storage type back to JSON;
The description in #14519 is great if more information is needed.

feat: Make JSON tag value fallback

---

src/Umbraco.Core/IO/ShadowWrapper.cs

When Umbraco Deploy creates a scope to process a deployment (e.g. content transfers or restores between environments), it enables scoped file systems, so any changes to files are only applied when the scope successfully completes. This is done by creating 'shadow' file systems, which track all changes and stores the files in a temporary directory.
We received some support tickets from customers that got the following exception during these deployments: `System.IO.IOException: There is not enough space on the disk. : 'C:\home\site\wwwroot\umbraco\Data\TEMP\ShadowFs\dzpd2b0c\media\[...]`. This can happen if they are trying to deploy a large amount and/or very big media files between environments, which exceeds the free/allowed disk space on the server.
I noticed the path was using the …

Create shadow file systems in configured LocalTempPath

---

src/Umbraco.Core/Routing/AliasUrlProvider.cs

If there's an existing issue for this PR then this fixes #14088.
Match content finder functionality in the url provider for `umbracoUrlAlias`, specifically when domains with paths are specified (e.g. `/en`). This allows the Info tab in the back office to show the correct url when an alias is specified with an `umbracoUrlAlias` field, as well as returning correct urls when the various url providers are queried in dotnet.
To test, add a domain to the root node that contains a path, e.g. `/en`. Add a text field with the alias `umbracoUrlAlias` to a document type for content under the root node. Add a value to the content, e.g. `aliased-url`, and save and publish. The resulting aliased url shown in the Info tab for the content should contain the domain root and **not** the domain path, e.g. …

Fixing #14088 (Info tab alias url incorrect).

---

src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10383.
Updating the `Vary by culture` setting of a property still resulted in an exception being thrown, as mentioned in https://github.com/umbraco/Umbraco-CMS/pull/11369#issuecomment-1134277678. This PR adds grouping on 2 bulk updates to ensure they also don't exceed the maximum amount of SQL parameters.
I've targeted v8, as that's what the above issue/PR used and we should be able to merge this up to the latest versions (the file moved from the `Umbraco.Core` to `Umbraco.Infrastructure` project though).
To test, you need a lot of content/variants (more than 2000) and then change the `Vary by culture` as described in the linked issue.

Fix bulk property variant data updates

---

src/Umbraco.Web/Editors/Binders/BlueprintItemBinder.cs
src/Umbraco.Web/Editors/Binders/ContentItemBinder.cs
src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
src/Umbraco.Web/WebApi/Filters/FileUploadCleanupFilterAttribute.cs

Made some internal classes public, so its possible to bypass security for packages like DTGE.
Related: https://github.com/umbraco/Umbraco-CMS/issues/15572
Fixes: https://github.com/umbraco/Umbraco-CMS/discussions/15560
```cs
using Umbraco.Core;
using Umbraco.Core.Cache;
using Umbraco.Core.Configuration;
using Umbraco.Core.Logging;
using Umbraco.Core.Persistence;
using Umbraco.Core.PropertyEditors;
using Umbraco.Core.Scoping;
using Umbraco.Core.Services;
using Umbraco.Web;
using Umbraco.Web.Editors;
using Umbraco.Web.Models.ContentEditing;
using Umbraco.Web.WebApi.Filters;
using Umbraco.Web.Editors.Filters;
using Umbraco.Web.Editors.Binders;
using System.Web.Http.ModelBinding;
namespace ClassLibrary2
{
[Umbraco.Web.Mvc.PluginController("dtge")] …
```

Made some internal classes public

---

src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/MediaControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/RecycleBin/RecycleBinControllerBase.cs

For whatever reason, `ContentControllerBase` is located outside the `Controllers` namespace in the API 😆 this PR cleans it up.

Move the ContentControllerBase to the correct location

---

src/Umbraco.Core/Cache/ContentCacheRefresher.cs
src/Umbraco.Core/Cache/LanguageCacheRefresher.cs
src/Umbraco.Infrastructure/Cache/DistributedCacheExtensions.cs
src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.Content.cs
src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/RefresherTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedSnapshotServiceCollectionTests.cs

Although PR https://github.com/umbraco/Umbraco-CMS/pull/14898 ensures the caches are updated when content blueprints (templates) are saved/deleted, it also caused additional cache refresher operations to be executed for content IDs that aren't stored in the content cache (NuCache) or Examine index.
I've added a new `Blueprint` property to the `ContentCacheRefresher.Payload` and added checks to skip blueprints from these operations, which should avoid taking locks on the published snapshot and updates to the Examine index when not necessary.

Skip cache refresher operations for content blueprints

---

src/Umbraco.Cms.Api.Management/Controllers/Media/ByKeyMediaController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/ItemMediaItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/ChildrenMediaRecycleBinController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/EmptyMediaRecycleBinController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/MediaRecycleBinControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/RootMediaRecycleBinController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/ChildrenMediaTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/RootMediaTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/PartialView/Item/ItemPartialViewItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Item/ItemScriptItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Item/ItemStaticFileItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Item/ItemStylesheetItemController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/EntityBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/MediaBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/FileItemPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IFileItemPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IMediaPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MediaPresentationFactory.cs

We have a little inconsistency in our naming of presentation factories:
- `PresentationModelFactory` (e.g. `MediaPresentationModelFactory`)
- `PresentationFactory` (e.g. `DocumentPresentationFactory`)
`PresentationFactory` is most widely adopted, so this PR renames the `PresentationModelFactory` ones to align.

Align presentation model factory naming

---

src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs

I was looking to create a unit test around a method that calls into GetCropUrl.  I found I could do it, but only with the small update in this PR.  The extension method here is using the "friendly" extension methods that use service location, but it doesn't need to do so as the parameter it needs is passed in already.
To test I think visual inspection will suffice, but otherwise confirm rendering a media item's crop works [as per the docs](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/image-cropper).

Allow methods that call GetCropUrl to be verified in unit tests.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js

Previous slider min and max values caused home and end keys to behave incorrectly. Min is now 0 to reflect 0% zoom and max is now 100 to reflect max zoom. Additionally, adjusted step to 0.01 to avoid slow adjustments when using arrow keys or page up / page down keys.
Issue: #15578
If there's an existing issue for this PR then this fixes [15578](https://github.com/umbraco/Umbraco-CMS/issues/15578)
1. Create new document type.
2. Add image cropper property to document.
3. Open the image cropper settings and use crops defined below.
4. Add new media picker property to document.
5. Open media picker settings and provide image crops defined below.
6. Use document type to create new document.
7. Upload desired image.
8. Click "Square" crop.
9. Drag slider using mouse and verify that moving …

Update nouislider options for image cropper.

---

src/Umbraco.Core/UriUtilityCore.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UriUtilityCoreTests.cs

EndPathWithSlash and TrimPathEndSlash,  `pos` calculation if one of them is 0 they pos will always be 0. Changing this to Max doesnt work for the case where both are greater than 0.

 UriUtilityCore not handling QueryString and Anchors correctly.

---

src/Umbraco.Core/Models/ContentEditing/DataTypeReferences.cs
src/Umbraco.Core/Persistence/Repositories/IDataTypeRepository.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/IDataTypeService.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DataTypeRepository.cs
src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.info.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14485
Please see the issue for the description of the bug including the steps to reproduce. 
My changes do show the content types which use a list view as a container under references on the info tab of a datatype. However my changes are not the ideal solution to the problem. A better solution for the future would be a change in the database schema to add a relation between the list view (the isContainer field on contentType is now a boolean, without any relation). 
My solution finds the relation between the datatype and list views as a container as follows:
- We check if the current data type is a list view, if it is we continue 
- Next we check if the name of the datatype matches the …

Add missing list view usages to data type references (#14485)

---

src/Umbraco.Core/PropertyEditors/IRichTextEditorIntermediateValue.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs

Fixes this issue by adding a interface for the internal intermediate value-class for the Rich Text Editor PVC.
https://github.com/umbraco/Umbraco-CMS/discussions/15568#discussioncomment-8256627
Adds the interface `IRichTextEditorIntermediateValue` so that sub-classes to `RteMacroRenderingValueConverter` can provide values for the methods in the base class.

#15568 fixed by adding IRichTextEditorIntermediateValue

---

src/Umbraco.Web.BackOffice/Filters/DataTypeValidateAttribute.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15529
as this bug descript it https://github.com/umbraco/Umbraco-CMS/issues/15529 create a new data type or edit an exiting one. Change name to something containing a / or : 
What happens is, the / or : is replaced with a whitespace so "True / false" -> "True   False" <- 3 whitespace.
When saving the datatype it runs a cleanForXss method witch replace / or : and other special chars with a whitespace.
I have removed the cleanforxss, to allow using the special chars to create names for the datatype.
Idon´t belive it makes a securtiy risk do to the fact that the rest of umbraco don´t do the same validation for the name property or alias. So in Doctype /: you name it is allowed, also due to …

Remove clean xss from datatype name and alias.

---

src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs

When running the Security health checks for a second time the certificate check will fail with "Your website's SSL certificate has expired" - https://github.com/umbraco/Umbraco.Cloud.Issues/issues/665
This PR fixes the issue and also switches the deprecated use of `request.Properties` to `request.Options`

Fix certificate health check so that it validates multiple times

---

src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs

This is related to the issue https://github.com/umbraco/Umbraco-CMS/issues/14556, which has been partially fixed for `RichTextPropertyEditor`, but not for property editors that use `NoopPropertyIndexValueFactory`.
Removed recursive call from the `GetIndexValues` method of `NoopPropertyIndexValueFactory` which is now marked as `obsolete`. Even though it is an obsolete method and it is not directly called within Umbraco CMS codebase anymore, I thought it would be good to fix it for backward compatibility with modules and libraries that may be still using it, for example https://github.com/umbraco/Umbraco.Cms.Integrations.
This is how this method looked prior to this change, see the recursive call in red:
Instead of making a recursive call it now calls the other method overload with 5 …

Fixed StackOverflow exception when using NoopPropertyIndexValueFactory

---

tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts

Decreased the number of times we try to retry running a failing test. The tests are running slower which results in the pipeline timing out. And there is no real reason to retry a test more than 2-3 times

V14 QA Decreased retry of failing test from 5 to 3.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tabs/umbtabsnav.directive.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html

If there's an existing issue for this PR then this fixes #14742 
I have implemented the missing aria attributes and keyboard behavior as provided in the guidelines here https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/ - See a demo here https://codepen.io/pen
Changes
- Removed the "ng-disabled" attribute since the `tab` object did not contain a `disabled` property. Even if it did, it should have been removed anyway since using the disabled attribute comes with a bunch of accessibility issues too.
- Added the a bunch of attributes to connect the tabs with the content (tabpanel) they actually refer to.
- Added a keydown event handler to check for whether arrow left, arrow right, home or end keys are being pushed
- Added an aria-label on the `tablist` - I have not created a …

Bugfix: #14742 - Tabs not coded according to best practice

---

src/Umbraco.Cms.Api.Management/OpenApi/BackOfficeSecurityRequirementsOperationFilter.cs
src/Umbraco.Cms.Api.Management/OpenApi/BackOfficeSecurityRequirementsOperationFilterBase.cs

The `BackOfficeSecurityRequirementsOperationFilter` enables back-office authentication for Swagger UI. It is currently both internal and hardcoded to be applied only to controllers within the Management API group (`"management"`).
If one would like to use back-office out for Swagger UI with a custom API, but also use a custom group instead of `"management"`, one has to clone-and-own the entire implementation. That seems a little silly, so this PR introduces an abstract base class that can be reused for custom APIs.
Using the code snippet below, the custom API within the `"my-api-v1"` group should be able to use back-office auth with Swagger UI:
```csharp
using Asp.Versioning;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options; …
```

Enable reuse of BackOfficeSecurityRequirementsOperationFilter for custom APIs

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
src/Umbraco.Web.Common/Extensions/ViewDataExtensions.cs

This fixes a regression compared from V12 to V13 where the new login screen UI did not show external login errors that happened on the server side. The is two-fold: `BackOfficeController` needed to have its built-in error messages migrated from V12, and the `UmbracoLogin/Index.cshtml` needed to hook on to those errors and forward them to the login screen UI.
Fixes #15622
Set a cookie containing external login errors somewhere, e.g. in the BackOfficeController:
```cs
var someerrormessage = @"{""errors"":[""Some error message""]}";
_httpContextAccessor.Response.Cookies.Append(ViewDataExtensions.TokenExternalSignInError, Convert.ToBase64String(Encoding.UTF8.GetBytes(someerrormessage)), new CookieOptions() { HttpOnly = true, Secure = true });
```
Verify that the error message shows up on the …

V13: The login screen does not display external login errors

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/DataTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Mapping/DataType/DataTypeViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/Item/DataTypeItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/Item/DataTypeTreeItemResponseModel.cs
src/Umbraco.Core/Models/DataTypeExtensions.cs
src/Umbraco.Core/Services/DataTypeService.cs
src/Umbraco.Core/Services/OperationStatus/DataTypeOperationStatus.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/DataTypeServiceTests.cs

The core cannot handle if certain of the default data types are deleted. Until we can remove this dependency, the following default data types may not be deleted:
- The checkbox (Toggle)
- The textbox
- The date/time label
- The content, media and member list views
Use Swagger to try deleting any of the above mentioned data types through the Management API. It should fail.
It should still be possible to delete other data types (including default ones).

Ensure that data types required by the core cannot be deleted.

---

src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/FilterMemberFilterController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/MemberFilterControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/TemporaryFile/TemporaryFileControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Filter/FilterUserFilterController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Filter/UserFilterControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/User/UserControllerBase.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Core/Constants-Web.cs

- Fixing the routes for Temporary file APIs;
- Changing the route of user and member filter endpoints - `"filter"` is now treated as a viewport (same as `"item"`).
- Add a few members and users and verify the /filter endpoints still work.

V14: Align routes

---

src/Umbraco.Examine.Lucene/ConfigurationEnabledDirectoryFactory.cs
src/Umbraco.Examine.Lucene/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Examine.Lucene/UmbracoTempEnvFileSystemDirectoryFactory.cs

When Examine is set to use either SyncedTempFileSystemDirectoryFactory or TempFileSystemDirectoryFactory the SiteName property should be used in the hash for the folder name in the same way as LocalTempStorageLocation does (https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs#L136).
This PR implements this change by creating a custom TempEnvFileSystemDirectoryFactory (https://github.com/Shazwazza/Examine/blob/release/3.0/src/Examine.Lucene/Directories/TempEnvFileSystemDirectoryFactory.cs).
This should help with Azure App Slot Swapping indexing locking as the SiteName property can be made sticky to each slot with a different value (as we can do for the published cache already).  It also can be used when debugging locally with …

Add custom Examine FileSystemDirectoryFactory using Umbraco SiteName

---

build/azure-pipelines.yml

This is a temp fix until we stop getting timeouts: sql server tests should only be run manually

V14: Run SQL Server Integration/Acceptance tests manually

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddListViewKeysToDocumentTypes.cs

The newly introduced listview migration (https://github.com/umbraco/Umbraco-CMS/pull/15687) does not play nice on SQL server due to the default value constraint on the `isContainer` column.
This PR ensures that the constraint is explicitly removed before we delete the column
As it turns out, the listview migration and the new datatype configuration migration (https://github.com/umbraco/Umbraco-CMS/pull/15733) also clash with each other, so the latter has to be moved to the end of `UmbracoPlan`. This unfortunately might affect any currently updated V14 databases, but there really is not much we can do about it.
Install V13 using SQL Server. Upgrade the DB to V14. The upgrade should complete 😄

Remove the default value constraint on "isContainer" before deleting the column

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/ChildrenDataTypeTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/ChildrenMediaTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/RootMediaTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Tree/ChildrenMediaTypeTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Tree/MediaTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Tree/RootMediaTypeTreeController.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tree/DataTypeTreeItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tree/MediaTreeItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Tree/MediaTypeTreeItemResponseModel.cs

Some of the Management API "tree item" models have been leaking out of the `Umbraco.Cms.Api.Management.ViewModels.Tree` namespace. This aligns them all again.

Align tree item namespaces

---

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs

The install adds invalid data type configurations for V14. As it happens, at least one of these (the RTE configuration) is even invalid for V13 🙈 
Install a fresh V14 DB. Use Swagger to verify that the default data type configurations make sense. For example:
- The RTE should have separate configuration values (`toolbar`, `maxImageSize`, ...). This used to be one big config.
- File uploads should have their allowed file extensions listed as a string array. This used to be an array of "value list" items.
- Media pickers that are limited to specific media types should use the keys of the media types in the `filter` configuration. This used to be the media type aliases.

Fix datatype configs for new installs

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml

This fixes a regression that occurs due to #15715 where parts of the backoffice still rely on some of the removed variables.
It should now work again and be able to show external login providers:

V13.2 RC: The user panel does not work

---

src/Umbraco.Core/PropertyEditors/ConfigurationEditor.cs

A left-over from the data type configuration and validation refactoring effort; we need to validate the data type configuration values.
Unline content, the data type configuration validation does not need to supply JSON path responses, because their schema is expected to be well-known and honoured by the client.
Use Swagger to attempt both create and update with invalid data type configurations. The attempts should yield a bad request in both cases.
The following data type configuration payload can be used to test, since the color picker validates the configured HEX codes:
```json
{
"name": "Color Picker - Validation Test",
"editorAlias": "Umbraco.ColorPicker",
"editorUiAlias": null,
"values": [
{
"alias": "useLabel",
"value": true
},
{
"alias": "items",
"value": [
{
"value": "invalid", …
```

Validate data type configuration values

---

src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDomainsController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/DocumentBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/DomainPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IDomainPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DomainAssignmentModel.cs
src/Umbraco.Core/Models/ContentEditing/DomainUpdateResult.cs
src/Umbraco.Core/Services/DomainService.cs
src/Umbraco.Core/Services/IDomainService.cs
src/Umbraco.Core/Services/OperationStatus/DomainOperationStatus.cs
tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UrlAndDomains/DomainAndUrlsTests.cs

This PR ensures that the Management API detects and reports collisions in domain assignments.
Assign the same domain to two different documents. The last assignment should fail with some helpful instructions in the resulting problem details.

Validate collisions in domain assignments

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs

This PR cleans up the remaining TODOs from the V14 data type configuration migration:
- Inject the configuration serializer into the migration.
- Translate layout "path" to "collection view".
Upgrade a V13 database with list views to V14. Ideally construct additional list views with custom layouts for testing.
Verify that the listview (collection) data type configurations have been migrated, and their layout paths have been translated to "collection view" properties:
- The system "grid.html" layout should have `Umb.CollectionView.Document.Grid` or `Umb.CollectionView.Media.Grid` as collection view for document and media list views, respectively.
- The system "list.html" layout should have `Umb.CollectionView.Document.Table` or `Umb.CollectionView.Media.Table` as collection view for …

Finalized the data type config migration

---

src/Umbraco.Core/Models/ContentCultureInfosCollection.cs
src/Umbraco.Core/Models/Property.cs
src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs

- When calling GET `/umbraco/management/api/v1/document/{id}`, the cultures casing in the response wasn't the same: 
<code>{
"urls": [
{
<b>"culture": "da-DK",</b>
"url": "/da/"
},
{
<b> "culture": "en-US",</b>
"url": "/en/"
}
...
],
...
"id": "e1cd7d17-63d8-4b92-859c-b93cd0a2d475",
"values": [
{
"$type": "DocumentValueModel",
<b>"culture": "en-us",</b>
"segment": null,
"alias": "description",
"value": "Home page text."
},
...
</code>
- This PR removes `ToLowerInvariant()` from culture and segment which was the underlying issue;
- And we make sure that the values in the indexes are unchanged (so people don't have to rebuild their indexes);
- We will keep the value there to lowercase - this was already the case for External and Internal indexes; now we handle that in the DeliveryAPI one as …

V14: Align cultures & segments casing

---

src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs

This removes the Newtonsoft.Json dependency from Multi URL picker. In fact, it removes all explicit JSON implementation dependencies 😄 
Create and update content with a multi URL picker property. It ShouldJustWork™ - the configured links should be saved and retrieved without any fuss.

Remove Newtonsoft.Json from Multi URL picker

---

src/Umbraco.Cms.Api.Management/Controllers/Dictionary/AllDictionaryController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Core/Persistence/Repositories/IDictionaryRepository.cs
src/Umbraco.Core/Services/DictionaryItemService.cs
src/Umbraco.Core/Services/IDictionaryItemService.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs

It should be possible to perform a free text search for dictionary items in the "dictionary overview" UI. However, the backing API endpoint (`/umbraco/management/api/v1/dictionary`) has so far been lacking that option - this PR adds it.
Verify that:
1. The dictionary overview endpoint returns all items by default (paginated, but still).
2. It is possible to use the `filter` parameter to perform free text search for dictionary items. The endpoint should perform a "starts-with" search.

Add filter option to the "dictionary overview" endpoint

---

src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html

Implements this [#15297](https://github.com/umbraco/Umbraco-CMS/discussions/15297) 
Added a new checkbox on the top of the cultures' list inside the save/save&publish dialogs to allow editors to select all the items at once.
1. Add at least 2 languages in your Umbraco backoffice
2. Create a document type which vary by culture
3. Create a new node, edit at least 2 cultures and click save or save&publish
4. Click the checkbox "Select all variants" and all the cultures in the list will be selected
If you edit just 1 culture the checkbox "Select all variants" should be hidden
--
While editing multiple cultures:
While editing one single culture:

Added the possibility to select all the cultures at once in the save and save&publish dialogs

---

src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs

I suspect PR #15687 introduced a small regression.
re: https://github.com/umbraco/Umbraco-CMS/pull/15687/files#diff-2ad7a39ca3a7e9fd7c4cbc72a2a28b28bf0d24c12449beff76ff8eb3b0a3ce99L192
I'd noticed on the frontend that the Media root was throwing an error for the Collection view, so debugging through it, I found that in the ListView Service, the `contentType` would be `null`, and not have a `.ListView` configured, so it'd throw an error - but really it needs to fallback to the default collection configuration (data-type).

V14: ListView Service - Checks that `contentType` isn't `null` before checking for `.ListView`

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ListView.spec.ts

Our pipeline times out, so we are skipping these as they are failing constantly.

V14 QA Skips failing test so the pipeline can run

---

src/Umbraco.Web.BackOffice/Controllers/ContentController.cs

When publishing, if the selected page does not yet have a page created, handle the FailedPublishNothingToPublish error so that the user is not presented with an exception. A warning is shown to the user that some languages failed to publish due to nothing to publish and to check that a page has been created for selected languages. Additionally fixed a validation issue where publish would always succeed if all languages were selected.
Issue: 15352
If there's an existing issue for this PR then this fixes [15352](https://github.com/umbraco/Umbraco-CMS/issues/15352)
This pull request contains the following changes:
- Handle the FailedPublishNothingtoPublish publish result in ContentController.cs. A warning now appears when the user attempts to publish a language for which no page has been …

Add handling of failed publish.

---

src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/ValidateUpdateDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/UpdateMediaController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/UpdateMediaControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/ValidateUpdateMediaController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/UpdateMemberController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/ValidateUpdateMemberController.cs
src/Umbraco.Core/Models/ContentEditing/ContentUpdateResultBase.cs
src/Umbraco.Core/Services/ContentEditingService.cs
src/Umbraco.Core/Services/IContentEditingService.cs
src/Umbraco.Core/Services/IMediaEditingService.cs
src/Umbraco.Core/Services/IMemberEditingService.cs
src/Umbraco.Core/Services/MediaEditingService.cs
src/Umbraco.Infrastructure/Services/MemberEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentEditingServiceTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberEditingServiceTests.cs

This shifts a little responsibility downwards to the service layer. There are no functional changes, only architectural ones 😄 
Note that members work a little differently than documents and media, and that the whole "editing" thing is split across two separate services to isolate responsibility as best possible. This has no actual impact on the PR, but it might help explain some of the slight quirkyness going on with member editing as a whole.
Nothing has changed at API level. It should still be possible to update and perform update validations on documents, media and members.
The unit tests have been updated to cover the detailed test scenarios.

Refactor content updates to shift responsibility downwards

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs

- Enables the calculation of user start nodes for content and media
- This is really tricky to do from a clean v14 install as you have to use swagger for almost everthing
- So I recommend going from a v13 database with:
- A root and child document type
- Allow the `child` document type as child on `root`
- Allow the `root` document type as root
- Create a root content node
- Create a child content node
- Go to user groups and set the "Editor" user groups start node to child
- Create a new user that's only part of the editor user group
- (Migrate to v14 on this step if you did it on v13)
- Login as the new user, assert that you cannot navigate to the `Root` content node
- Assert you can see the child content node

V14: Enable user start node calculation

---

src/Umbraco.Cms.Api.Management/Controllers/FolderManagementControllerBase.cs
src/Umbraco.Cms.Api.Management/Factories/DocumentTypeEditingPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MediaTypeEditingPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/DataType/DataTypeViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/ContentType/CreateContentTypeWithParentRequestModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CreateDocumentTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Folder/FolderResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/CreateMediaTypeRequestModel.cs

This PR aligns the `parent` contexts throughout the Management API:
1. Do not output a `parent` at resource detail level.
2. Use `parent` everywhere (instead of `folder`).

Align parent contexts

---

src/Umbraco.Core/Models/Mapping/ContentPropertyDisplayMapper.cs
src/Umbraco.Core/Services/PropertyValidationService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs

Although currently undocumented, it is possible to use [user lang files](https://docs.umbraco.com/umbraco-cms/extending/language-files#user-language-files) to localize the backoffice (instead of using dictionary items). However, that kind of localization does not extend to property validation messages.
Create a user language file like this in `[site root]\config\lang`:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<language>
<area alias="validation">
<key alias="mandatory-field">It's mandatory</key>
<key alias="numeric-field">It's got to be a number</key>
</area>
</language>
```
Use these language keys to configure property validation messages:
Now verify that the validation messages are indeed utilized by the backoffice:
...also in block based editors:

Localize validation messages with user lang files

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Filter/DataTypeFilterControllerBase.cs
src/Umbraco.Core/Constants-DataTypes.cs
src/Umbraco.Core/Models/DataTypeExtensions.cs
src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs

This PR ensures we do not install the legacy media picker in V14 databases.
Also the datatype `filter` endpoint still has the temporary "New" auth policy applied, efficiently preventing it from being queried. This has been fixed too.
1. Install a fresh V14 database. There should be no "legacy" media pickers in it.
2. It should be possible to query the datatype `filter` endpoint.

Remove legacy media picker from install

---

src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
src/Umbraco.Core/Services/MediaEditingService.cs
src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Core/Services/OperationResultType.cs
src/Umbraco.Core/Services/OperationStatus/ContentEditingOperationStatus.cs

The media create endpoint returns a very generic 500 when you try to create a media item with a key that already exists. This PR aims to fix this by checking if a media entity exists with the supplied key when we know the IMedia does not have an identity (constructed from outside of the repository)
- Create a media Item with key xxx <= success
- Create another media Item with key xxx <= fail with proper message
- Create a media Item with key yyy <= success
- Update media Item with key xxx <= success

Check for duplicate keys on media if we know it's a fresh entity

---

src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15792
- As a result of the new https://github.com/umbraco/Umbraco-CMS/pull/15305, we didn't parse a noncomposite id correctly, so we returned an empty string instead of `null`, resulting in Lucene error _(seen in the logs):_
-
- Which on its hand caused incorrect data in DeliveryApiContentIndex when a content item has been deleted.
- This PR fixes that and makes sure we follow the practice: `int.ToString(CultureInfo.InvariantCulture)` when converting ints to strings.
- Follow the Steps to reproduce in the original issue
- Make sure that the total amount of items and the number of items in the `items` collection is correct after deleting a content item (**both variant and invariant**) and making a GET request to …

V13: Incorrectly parsing item id by DeliveryApiContentIndex caused incorrect information when deleting a content item

---

src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/MemberFilterControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/MemberControllerBase.cs

Enabled section based authorization for member management endpoints.
The following endpoints should only be available if you have access to the member section
The following endpoint should be available when have access to either of the following sections: content, media, member (for use in pickers used in those sections)

Enable member management authorization

---

src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertymsg.directive.js

If there's an existing issue for this PR then this fixes (https://github.com/umbraco/Umbraco-CMS/issues/15697)
Updated valpropertymsg.directive.js to show error messages correctly as HTML rather than escaped text.
Works specifically on Blocklist fields where the minimum / maximum number of elements has not been met.
Create a document type with a block list, with the number of required components as at least 1. Create one, and attempt to save it without adding any components.
The error message should display as HTML rather than "Minimum 1 entries, requires <strong>1</strong> more"
Before: 
After:

Validation messages for blocklists no longer show HTML markup. #15697

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js

Default behavior:
If you have only one available module for an area Umbraco will open a dialog for adding the module. If you have more than one module you will get a dialog to choose a module and that dialog will have a Paste option in the top right corner.
New behavior:
If there is a module in the clipboard, Umbraco will open a dialog with the Paste option even thou there is only one available module in the area. In other cases, it will work as usual.
Reported issue: https://github.com/umbraco/Umbraco-CMS/issues/15755

Show BlockGrid Create Dialog if there are items in clipboard

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/ConfigurationDataTypeController.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DatatypeConfigurationResponseModel.cs

Exposes the default list view ids in the datatype configuration endpoint

V14: Expose default list view ids in datatype configuration endpoint

---

src/Umbraco.Core/PublishedCache/ITagQuery.cs

If there's an existing issue for this PR then this fixes <[!-- link to the issue here!](https://github.com/umbraco/Umbraco-CMS/issues/15707) -->

Update documentation for GetAllContentTags method in ITagQuery interface

---

src/Umbraco.Core/Logging/IProfiler.cs
src/Umbraco.Core/Logging/LogProfiler.cs
src/Umbraco.Core/Logging/NoopProfiler.cs
src/Umbraco.Web.Common/Profiler/WebProfiler.cs
src/Umbraco.Web.Website/ViewEngines/ProfilingViewEngine.cs
tests/Umbraco.Tests.Common/TestHelpers/Stubs/TestProfiler.cs

Each time ProfilingViewEngine.FindView and ProfilingViewEngine.GetView is called (each time a view is used) the ProfilingViewEngine calls string.Format for a log message as part of profiling. However, if Umbraco is not in debug mode, this is unnecessary as the IProfiler will be a NoOp and will discard the formatted string, however this formatted string is still allocated.
This PR adds a IsEnabled property to IProfiler, so the string.Format allocations can be avoided when the IProfiler is not enabled.
How to test?
Check that IProfiler.Step is not called when IProfiler is not enabled.

Avoid string.Format allocations by ProfilingViewEngine when profiler is not enabled.

---

src/Umbraco.Core/HealthChecks/Checks/Security/ExcessiveHeadersCheck.cs
src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
src/Umbraco.Core/Media/EmbedProviders/OEmbedProviderBase.cs
src/Umbraco.Core/Persistence/Repositories/InstallationRepository.cs
src/Umbraco.Core/Persistence/Repositories/UpgradeCheckRepository.cs
src/Umbraco.Core/Security/LegacyPasswordSecurity.cs
src/Umbraco.Core/Security/PasswordGenerator.cs

Dispose IDisposable instances to free resources.

Dispose IDisposable instances

---

src/Umbraco.Infrastructure/Mapping/UmbracoMapper.cs

Fixes issue [#15830](https://github.com/umbraco/Umbraco-CMS/issues/15830) by changing the inner Dictionary of _ctors to a ConcurrentDictionary.
This concurrency issue was encountered when mapping one type of object to multiple other objects (multiple mapping definitions) and performing multiple concurrent requests when Umbraco boots to a url with a view that did all the mappings at once.
```
Error: Umbraco.Cms.Web.Common.PublishedModels.FrontPage => Site.MyModel
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
at …
```

Fix UmbracoMapper InvalidOperationException due to concurrent modification of inner dictionary

---

src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/FilterMemberFilterController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Core/Models/Membership/MemberFilter.cs
src/Umbraco.Core/Persistence/Repositories/IMemberRepository.cs
src/Umbraco.Core/Services/IMemberService.cs
src/Umbraco.Core/Services/MemberService.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs

- Adds capability to filter by membergroup name, isAllowed & isLocked out on the filter endpoint
- Adds `MemberFilter`, to mimic the behavior of the user filter endpoint.
- Implements `FilterAsync` on the IMemberService
- Create lots of groups and member groups on a v13 instance (you can also do this in the new backoffice, just a bit more tedious and buggy 😛)
- Upgrade your database to v14
- Use the new filter endpoint, and assert all the new filter properties work (group name, isApproved, isLocked)
- Assert that it also works in combination with others

V14: Create member filter

---

src/Umbraco.Cms.Api.Management/Configuration/ConfigureBackOfficeCookieOptions.cs
src/Umbraco.Cms.Api.Management/Configuration/ConfigureBackOfficeSecurityStampValidatorOptions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Security/BackOfficeSecurityStampValidator.cs
src/Umbraco.Cms.Api.Management/Security/BackOfficeSecurityStampValidatorOptions.cs

Right now, the cookie validation for V14 is lacking a lot of basic stuff. For starters, if a user has authenticated against one database, the user authentication survives swapping out the entire DB with another DB (or delete and recreate the DB), as long as the user exist by the same email in both databases 🤦 
This PR ports over all (almost all) the current cookie validation from V13 to V14, to handle these silly things.
A few things have been explicitly omitted, because they seems to have little meaning in the Management API. Please consider if this is as meaningful as I think 😆 
- [`BackOfficeCookieManager`](https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.Web.BackOffice/Security/BackOfficeCookieManager.cs).
- [`IsRemainingSecondsRequest`](https://github.com/umbraco/Umbrac …

Port V13 backoffice cookie validation to V14

---

src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Tree/DictionaryTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/PartialView/Tree/PartialViewTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/RelationType/Tree/RelationTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Tree/ScriptTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Tree/StaticFileTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Tree/StylesheetTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Tree/EntityTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Tree/FileSystemTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Tree/TreeItemPresentationModel.cs

This PR removes the "type" property of tree item response models in the Management API. It has long since been decided that this property was a client concern, so we need to remove it for clarity.
This PR modifies the current API contract, thus it is breaking 👍 
The Management API should work as per usual 😄

Removed "type" from tree item response models

---

src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Services/ConflictingRouteService.cs
templates/UmbracoPackage/UmbracoPackage.csproj
templates/UmbracoPackageRcl/UmbracoPackage.csproj

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15881
- Removes the last mentions of `Umbraco.Cms.Web.Backoffice`
- Adds reference to `Umbraco.Cms.Web.Common` as they have the swagger classes needed for packages 👍 
- In the root of the repository, open a terminal and run following commands:
-  `dotnet pack -o nugetFolder`
- `dotnet nuget add source [PATH TO "nugetFolder" HERE]`
- `cd nugetFolder`
- `dotnet new install ./Umbraco.Templates.14.0.0--beta002.preview.471.g1e8d117.nupkg`
- Navigate to another folder where you want to install your template
- `dotnet new umbracopackage -n "TestName"`
This should now work 🙌

v14: Fix umbracopackage template

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataType.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypeFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DatePicker.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/LogViewer/LogViewer.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/CreatedPackages.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Relation Types/RelationTypes.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialView.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Template/Templates.spec.ts

These failing tests should be fixed. Currently, they are skipped to ensure better reliability of the acceptance tests

V14 QA Skipped failing acceptance test

---

src/Umbraco.Infrastructure/Migrations/PreMigration/DataTypeSplitDataCollector.cs

Quick fix for https://github.com/umbraco/Umbraco-CMS/issues/15872
It is possible to have the same Alias for a dataEditor used as a propertyEditor and a dataEditor used as a macroparameterEditor.
The DataTypeSplit Datacollector does not care about the macroParameterEditors as they will not be migrated to v14. => only get the DataEditors from code that are used as propertyEditors thus using aliases (which should be unique) safely as dictionary keys again.

DataTypeSplit datacollector should not care about propertyEditors

---

src/Umbraco.Core/Cache/ObjectCacheAppCache.cs

This PR ensures we have locks every time we interfere with the memory cache and hashset.  Further, to ensure we do not potentially end in infinite deadlocks, I added a timeout to all of them
Fixes a comment here https://github.com/umbraco/Umbraco-CMS/pull/15173#issuecomment-2004264906
Ensure the cache still works.. I would expect the test suites to test this pretty intensive.
Ultimately, this fix is due to our hunt for the issue where the hashset suddenly is out of sync with the memory cache. So what ever you can think of as a test, would be nice.

Added missing locks and use timeout on all of them in ObjectCacheAppCache

---

src/Umbraco.Core/Extensions/LineEndingsExtensions.cs
src/Umbraco.Core/Snippets/PartialViewSnippetCollectionBuilder.cs
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialView.spec.ts

Created an extension method to ensure we have the correct line endings based on the OS. Added a usage of the extension method for Partial View Snippets.
Fixed acceptance test, which actually tests the content for the snippets, both for Windows and Linux

V14 Bugfix ensures correct line endings for partial view snippets

---

src/Umbraco.Core/Cache/ObjectCacheAppCache.cs

This extends PR https://github.com/umbraco/Umbraco-CMS/pull/15902 with additional lock timeouts in `SearchByPredicate()` when entering the upgradable read lock and in `Clear()` when taking the write lock. The timeout exception messages are also updated to clearly state when it occurred, which should make debugging easier.
I've also cleaned up the constructor, as that still had the `IHostEnvironment` parameter (kept in PR https://github.com/umbraco/Umbraco-CMS/pull/15173 to maintain backwards compatibility, but this got merged to v14, so can be breaking now).

Add additional lock timeouts and clean-up `ObjectCacheAppCache`

---

tests/Umbraco.Tests.AcceptanceTest/tests/auth.setup.ts

Bumped timeout, since the test on the pipeline can fail sometimes.

V14 QA login acceptance test fix

---

src/Umbraco.Cms.Api.Management/Controllers/Package/AllPackageManifestController.cs
src/Umbraco.Cms.Api.Management/Controllers/Package/PublicPackageManifestController.cs
src/Umbraco.Core/Manifest/IPackageManifestService.cs
src/Umbraco.Core/Manifest/PackageManifest.cs
src/Umbraco.Infrastructure/Manifest/PackageManifestService.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/PackageManifestServiceTests.cs

Currently the editor needs access to the packages section in order to load package manifests. This won't do, because everyone with access to the backoffice potentially has to load package manifests.
Also, we need publicly available manifests, i.e. manifests that are allowed to load without backoffice access. These are necessary to power customizations of the login screen. It must be an explicit opt-in to be a "public" manifest.
Example of a manifest with public access:
```json
{
"name": "My Public Package #1",
"version": "1.0.0",
"allowPublicAccess": true,
"extensions": [{
"alias": "My.Whatever",
"name": "My Whatever"
}
]
}
```
1. The "all package manifests" endpoint should be available for users without access to packages, settings or the like. That is, a "simple" content editor with …

Ensure correct access to all manifests + introduce "public" package manifests

---

src/Umbraco.Core/Constants-Validation.cs

When performing document/media/member property validation, there are three core validation errors that can occur:
- A mandatory value was not supplied.
- A mandatory value was empty.
- A value did not match the configured validation (regex) pattern.
Per property one can configure specific validation error messages, but by default these are blank - which means we use error messages defined in the core instead.
Since these core error messages are localized in the client, the server has to return a localization key. And as of right now, the localization keys returned are wrong 😆 so this PR fixes the localization keys returned by the server to match those known by the client.

Use the correct localization keys for core property validation errors

---

src/Umbraco.Cms.Api.Management/Controllers/Document/ConfigurationDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/ConfigurationMediaController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/ConfigurationMemberController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/ConfigurationBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/ConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberConfigurationResponseModel.cs
src/Umbraco.Core/Models/ContentPropertySettings.cs
src/Umbraco.Core/Models/MediaPropertySettings.cs
src/Umbraco.Core/Models/MemberPropertySettings.cs
src/Umbraco.Core/Services/IReservedFieldNamesService.cs
src/Umbraco.PublishedCache.NuCache/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.PublishedCache.NuCache/ReservedFieldNamesService.cs

- Added configuration endpoint for members
- Added new ConfigurationPresentationFactory, that is responsible for creating the configuration models
- Added new `IReservedNamesService` that will return all the reserved names for a given model (Member, Media, Content)
- Added 3 new property settings, so that users (or package devs) can define their own reserved names.
- Using the 3 configuration endpoint, assert that you get the correct list of reserved names
- Try configuring the property settings & add some reserved names yourself, assert these also get returned via the endpoints
- You can use this code to configure the property settings:
```
public class TestComposer : IComposer
{
public void Compose(IUmbracoBuilder builder) =>
builder.Services.Configure<ContentPropertySettings>(
x =>
{ …
```

V14: Add reserved fields to config endpoints

---

src/Umbraco.Cms.Api.Delivery/Controllers/Content/ByRouteContentApiController.cs
src/Umbraco.Core/DeliveryApi/ApiContentPathProvider.cs
src/Umbraco.Core/DeliveryApi/ApiContentPathResolver.cs
src/Umbraco.Core/DeliveryApi/ApiContentRouteBuilder.cs
src/Umbraco.Core/DeliveryApi/IApiContentPathProvider.cs
src/Umbraco.Core/DeliveryApi/IApiContentPathResolver.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentPickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentRouteBuilderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/DeliveryApiTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiUrlPickerValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTestBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PropertyValueConverterTests.cs

In certain cases it would be nice to be able to customise the content paths returned by the Content Delivery API - for example if one has a collection of shared content that is reused between multiple roots (sites).
This PR introduces the _content path provider_ and the matching _content path resolver_. Think of these as URL Provider and Content Finder for the Content Delivery API here.
The core implementations (`ApiContentPathProvider`, `ApiContentPathResolver`) are left public and unsealed to enable extendability.
Consider a content structure like this:
The following code adds custom paths to "Root One" and everything below (prefixes the content path with `/my-path`):
```csharp
using Umbraco.Cms.Core.DeliveryApi;
using …
```

Introduce path provider and resolver for the Content Delivery API

---

src/Umbraco.Core/Models/ContentRepositoryExtensions.cs

A new check for ContentVariation.Nothing is necessary when copying from documents to ensure that if there is no content variation as defined by the Nothing property, values are still copied even if variation is not supported since the content itself will not vary.
If there's an existing issue for this PR then this fixes [14687](https://github.com/umbraco/Umbraco-CMS/issues/14687)
**Changes made:**
- Added additional check when copying. If the ContentVariation for a property is "Nothing" then regardless of whether variation is supported or not, the content of the property will not vary by culture so copying can continue.
**Steps to Test**
1. Create document type "Home"
2. Add a text field "Title". 
3. Enable "Allow as root" 
4. Enable "Allow vary by culture". Ensure Title is still not …

Add check for ContentVariation.Nothing when copying documents.

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/ByKeyMemberController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/FilterMemberFilterController.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberType/ByKeyMemberTypeController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/MemberTypeBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/IMemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IMemberTypePresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MemberTypeEditingPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MemberTypePresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/CreateMemberTypePropertyTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/MemberTypePropertyTypeModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/MemberTypePropertyTypeResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/MemberTypePropertyTypeVisibility.cs
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/UpdateMemberTypePropertyTypeRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/Current/CurrentUserResponseModel.cs
src/Umbraco.Core/Extensions/MemberTypeExtensions.cs
src/Umbraco.Core/Models/ContentTypeEditing/MemberTypePropertyTypeModel.cs
src/Umbraco.Core/Services/ContentTypeEditing/MemberTypeEditingService.cs
src/Umbraco.Core/Services/MemberContentEditingService.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs
src/Umbraco.Infrastructure/Services/MemberEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTestsBase.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MemberTypeEditingServiceTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberEditingServiceTests.cs

This PR adds sensitive property handling to the Management API.
Create members with sensitive properties. You'll need a V13 to do this - and a subsequent migration of the V13 database to test the rest.
As a user _with_ the "Sensitive data" user group assigned, the sensitive properties should be visible and editable through the Management API.
As a user _without_ the "Sensitive data" user group assigned, the sensitive properties should _not_ be visible nor editable through the Management API. In fact, the API should yield an error if attempts are made to hack the API (read: pass in property aliases that match a sensitive property)

Handle sensitive properties in the Management API

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_3_0/AlignUpgradedDatabase.cs

This PR adds a migration that aligns the schemas of migrated V7 and brand-new V13 databases. 
To compare I've used the schema compare tool in VS, with column order disabled, after the migration the schemas align. 
To test this I've migrated a v7 database, with a piece of simple content up to v13/dev and run the migration, after this I've verified that the content still works and that the schemas are now aligned.
Additionally I've tested that on a fresh V13 data base no SQL queries are executed.

V13: Align database schemas of migrated and new database

---

src/Umbraco.Cms.Api.Management/Services/DictionaryItemImportService.cs
src/Umbraco.Core/Extensions/UserServiceExtensions.cs
src/Umbraco.Core/Services/AuditService.cs
src/Umbraco.Core/Services/MediaImportService.cs
src/Umbraco.Core/Services/MemberContentEditingService.cs
src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiTest.cs

There are a few places where we expect a user to exist, and throw an exception if the user is not found. This PR adds an extension method to handle that kind of "required user fetching" in the same way across the codebase, instead of having individually implemented exception handling.

Use an extension method for fetching a required user in a common way

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Version/ByKeyDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Version/DocumentVersionControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Version/GetDocumentVersionsController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Version/RollbackDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Version/UpdatePreventCleanupDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Versions/DocumentVersionControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Versions/RollbackDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/AllDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/ByKeyDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/DocumentVersionControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/RollbackDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/UpdatePreventCleanupDocumentVersionController.cs
src/Umbraco.Cms.Api.Management/Factories/DocumentVersionPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IDocumentVersionPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentVersionMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVersionItemResponseModel.cs
src/Umbraco.Core/Services/ContentVersionService.cs
src/Umbraco.Core/Services/IContentVersionService.cs
src/Umbraco.Core/Services/Pagination/PaginationConverter.cs
src/Umbraco.Infrastructure/Security/UmbracoUserStore.cs
tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/IntGuidIntConversionTests.cs

Adds management API endpoints for
- getting a list of version for a given document
- get details about a version with a specific id
- toggle the preventCleanup for a specific version
- rollback to a specific version
- Publish a document
- Update the document and publish again (repeat a few times)
- IContentVersionService methods have been brought into the async age
- IContentVersionService default constructor has been changed

Document version endpoints

---

src/Umbraco.Core/Sync/RefreshMethodType.cs

Define RefreshMethodType enum values to be the existing values. Prevent errors in future if these are reordered as the number is being serialized.

Define RefreshMethodType enum values

---

src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVersionResponseModel.cs

Following the merge of #15946 the Swagger schema generation reports this error:
```
An unhandled exception has occurred while executing the request.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Umbraco.Cms.Api.Management.Controllers.DocumentVersion.ByKeyDocumentVersionController.ByKey (Umbraco.Cms.Api.Management). See inner exception
---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - Umbraco.Cms.Api.Management.ViewModels.Document.DocumentVersionResponseModel. See inner exception
---> System.InvalidOperationException: Can't use schemaId "$ContentForDocumentResponseModel" for type "$Umbraco.Cms.Api.Management.ViewModels.Content.ContentResponseModelBase`2[Umbraco.Cms.Api.Management.Vi …
```

Fix swagger schema error after #15946

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Item/SearchMemberItemController.cs
src/Umbraco.Core/Services/IExamineEntitySearchService.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Infrastructure/Services/Implement/ExamineEntitySearchService.cs

This is the follow-up for #15951 - this time with Examine powering the entity search for documents, media and members. At the same time, this PR ensures that the entity search respects any user start node limitations for the current user.
The results from the search endpoints in V14 should match the results in V13. In other words, upgrade a database from V13 to V14 and compare the search results.
Also test that user start nodes are being respected. Thus the searches should yield no document or media results "outside" of the current user start nodes.
Don't forget to rebuild the Examine indexes in both versions before comparing 😅

Examine powered entity search for documents, media and members

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Create.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Update.cs

At this time, container types (groups and tabs) are known enum values on the serverside, but exposed as string values to the client. The idea behind this is that we'll likely set container types free later on, since they are really none of the server's concern. For now, though, we need to ensure proper container types for various reasons - nesting containers correctly for one.
This PR ensures that we are very explicit about parsing container types, and return meaningful errors if an invalid container type is supplied. This also includes incorrect casing.

Make property container type parsing explicit

---

src/Umbraco.Cms.Api.Management/Controllers/Package/Created/DownloadCreatedPackageController.cs

Sets the appropriate MIME type of the Created Package download, this would be either an XML string or a ZIP file.
The MIME type will be used on the v14 client-side to handle the response content accordingly.

V14: Download Created Package MIME type

---

tests/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs

Implementors using Umbraco.Tests.Integration won't have to override GetLocalizedTextService
If there's an existing issue for this PR then this fixes #11782 
For a long while implementors have had to replace the LocalizedTextService factory when deriving from UmbracoIntegrationTest et. al.  
With these changes the code will detect whether if found the Umbraco UI project or not, and if not an empty folder is created in the user's temp folder.

Fix 11782: Create missing UI folder on temp path when using Umbraco.Tests.Integration

---

src/Umbraco.Cms.Api.Management/Controllers/RecycleBin/RecycleBinControllerBase.cs

The API explicitly returns a 500 response code if the "original parent" of a "restore from recycle bin" attempt is not found:
This seems very dramatic 😄 specially since this is a normal, expected scenario; the "original parent" has simply been deleted from the recycle bin, before the attempt to restore the previous child is made.
This PR changes the response code to be a 404 instead. Less dramatic 😛 
1. Create a parent and a child document.
2. Move the child to the recycle bin.
3. Delete the parent entirely.
4. Request the "original parent" from `/umbraco/management/api/v1/recycle-bin/document/{key}/original-parent`.
5. Verify that a 404 is returned.
Rinse and repeat for media.
Note that "move to recycle bin" and "delete" operations are currently only functional through the API (in other …

Return 404 instead of 500 when an "original parent" has been deleted

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Item/SearchMemberItemController.cs
src/Umbraco.Core/Services/IEntitySearchService.cs
src/Umbraco.Core/Services/IIndexedEntitySearchService.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs

As correctly pointed out in [this comment](https://github.com/umbraco/Umbraco-CMS/pull/15972#issuecomment-2035474833), the newly introduced `IExamineEntitySearchService` is counter productive towards the eventual goal of decoupling ourselves a little more from Examine.
Furthermore, the naming in itself bleeds technology, which is clearly a mistake on yours truly when implementing the thing.
This PR renames it to `IIndexedEntitySearchService` instead. It was the best I could come up with 🙈 
Everything should still work exactly as before. Steps from https://github.com/umbraco/Umbraco-CMS/pull/15972 can be reused, but basically - if document items can be searched, all is good. Don't forget to rebuild the Examine indexes, though 👍

Rename Examine based entity search service

---

src/Umbraco.Web.Common/Profiler/ConfigureMiniProfilerOptions.cs
src/Umbraco.Web.Common/Repositories/WebProfilerRepository.cs

This PR solves a FIXME, and ensure you are authenticated to see the miniprofiler logs
- Enable the dashboard in backend (Ensure frontend is updated, because there was a bug)
- Go to https://localhost:44339/umbraco/profiler/results-index
- If authenticated in backend and access to settings, you can see it
- Otherwise not

Ensure authenticated to see webprofiler log

---

src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs

Updates the `DocumentPresentationFactory` to use the `ITemplateService` instead of the obsoleted `IFileService`.
When getting a document the correct template key should be shown if any, and null if there is no template

V14: Use ITemplateService in DocumentPresentationFactory

---

src/Umbraco.Core/Deploy/ArtifactBase.cs
src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
src/Umbraco.Core/Deploy/IDeployContext.cs
src/Umbraco.Core/Deploy/IFileSource.cs
src/Umbraco.Core/Deploy/IFileTypeCollection.cs
src/Umbraco.Core/Deploy/IImageSourceParser.cs
src/Umbraco.Core/Deploy/ILocalLinkParser.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs

This cleans up some of the Deploy interfaces within the CMS:
- Align the `IDataTypeConfigurationConnector.FromArtifact(...)` return type with `IDataType.ConfigurationData` (following the data type refactor done in PR https://github.com/umbraco/Umbraco-CMS/pull/13605);
- Align the `ArtifactBase<>.Alias` property nullability with the `IArtifact` interface;
- Ensure the `ArtifactBase<>.Dependencies` collection is lazily set when empty (only allocating when being iterated);
- Remove `ShouldSerializeChecksum()`, since that was specific to the Newtonsoft.Json implementation (to avoid serializing the `Checksum` property without having to take a reference to add `JsonIgnore` attribute);
- Remove obsolete methods and default interface implementations.

v14: Align Deploy interfaces, remove obsolete methods and default interface implementations

---

tests/Directory.Packages.props
tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TagServiceTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/RefresherTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTypeTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/DictionaryItemTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/DictionaryTranslationTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/DocumentEntityTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/LanguageTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/MemberGroupTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/MemberTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/PropertyGroupTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/PropertyTypeTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/RelationTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/RelationTypeTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/StylesheetTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/TemplateTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/UserGroupTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/UserTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RichTextPropertyEditorHelperTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DataTypeTests.cs

This removes the dependency on `Newtonsoft.Json` from all tests and instead uses `System.Text.Json`.

v14: Remove `Newtonsoft.Json` from tests

---

src/Umbraco.Core/PropertyEditors/FileUploadConfiguration.cs
src/Umbraco.Core/PropertyEditors/IFileExtensionConfig.cs
src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyValueEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImagesTests.cs

The embedded image handling for the RTE (introduced in #14546) was written for TinyMCE 4 and no longer needs to happen in V14. As it has not yet been ported over to V14, I have simply deleted the empty stub (`FindAndPersistEmbeddedImages`).
In a previous PR (#16021) I actually ported the functionality to V14. While implementing tests for that PR, I encountered a silly error in our file upload configuration; the `FileExtensions` should be a simple string collection, not a collection of `FileExtensionConfigItem`. In fact we no longer need `FileExtensionConfigItem` for V14.
As it turns out, the marker interface `IFileExtensionsConfig` is also a V13 specific thing, so that can be removed for V14 as well.
Since I had most of the test setup in place for the previous PR, I have reused that to …

Remove RTE embedded image handling + clean up file upload configuration

---

src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs
src/Umbraco.Core/Services/OperationStatus/TemplateOperationStatus.cs
src/Umbraco.Core/Services/TemplateService.cs

It is currently possible to make circular references when updating/creating templates trough the management api. This PR makes those type of requests fail gracefully instead.
Create any kind of circular dependency trough the backoffice UI. It will allow you to select templates as a master that lead to circular references, but when trying to save the change you should get a nice warning
Saving valid templates should still work

Prevent template circular references

---

src/Umbraco.Cms.Api.Management/Controllers/BackOfficeLoginController.cs

- In some scenarios, you could manually navigate to the login screen (`/umbraco/login`), where you were not really supposed to be able to do that:
1. When you are already logged in, you should not be able to see the login screen
2. When you are resetting a password, and already logged in
3. When you are invited, but already logged in
From a server perspective, we needed a way to tell the client about the logged in status of the user, thus we have added a property to the model that get's send with, with whether the user is logged in or not.
- Log in the backoffice
- Manually navigate to `/umbraco/login`, if you set a breakpoint, you should be able to see the `UserIsAlreadyLoggedIn` property being set to true.

V14: Deny login screen access

---

src/Umbraco.Cms.Api.Management/Controllers/BackOfficeLoginController.cs

Negated a check for relative path.
The reason is because `/asd/` is also an absolute path on Linux/Unix.

Fixed check to support unix/linux OS

---

src/Umbraco.Core/Serialization/IJsonSerializer.cs
src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyValueEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/SliderPropertyEditor.cs
src/Umbraco.Infrastructure/Serialization/SystemTextConfigurationEditorJsonSerializer.cs
src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializer.cs
src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializerBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializerTests.cs

A few property value editors have a direct dependency on `System.Text.Json`. While this works just fine, they really should not have that dependency. But at this point they're forced to.
This PR introduces a new method on `IJsonSerializer`, which allows for attempting a deserialization of any (JSON) object, thus removing the need for direct dependencies on the concrete JSON implementation.
Unit tests included.
As the current `IJsonSerializer` and `IConfigurationEditorJsonSerializer` implementations are virtually identical apart from the JSON configurations, I have abstracted their implementation into a base class, so I didn't have to duplicate the implementation of the `TryDeserialize` method too.
Nothing should change functionality wise.
Verify that you are still able to save content …

Removed leftover System.Text.Json dependencies

---

src/Umbraco.Core/Services/TemplateService.cs

Calling TemplateService.GetAll any keys in the array results in a sql error.
(backoffice usecase: template selection on a doctype with template)
Since this is a params object we can not supply null, so we check versus any

Only add a SQL in statement if there are keys to filter on

---

src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
tools/Umbraco.JsonSchema/Options.cs
tools/Umbraco.JsonSchema/Program.cs
tools/Umbraco.JsonSchema/UmbracoCmsSchema.cs
tools/Umbraco.JsonSchema/UmbracoJsonSchemaGenerator.cs

After updating the JsonSchema tool in PR https://github.com/umbraco/Umbraco-CMS/pull/16030, I copied over the same changes to our commercial products (because this tool isn't reusable yet, see PR https://github.com/umbraco/Umbraco-CMS/pull/13560). This required doing some adjustments, which can be brought back to the CMS.
The biggest change is that the JSON schema generator now checks the `IgnoreReadOnlyProperties` setting to conditionally remove read-only properties (which probably should be supported OOTB by `NJsonSchema`). All properties on the schema class now use the required modifier instead of setting null-suppressed default values and I've made the full `UmbracoPath` property obsolete, so the obsolete setter work-around can be removed as well.
To test, rebuild the …

v14: JSON schema tool improvements

---

src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs

- Check if any external login providers has `DenyLocalLogin` set to true, and if yes, set CanInviteUsers to false.
- To test this, you have to setup an external login provider, (luckily it doesn't have to work)
- This example is with the google nuget package. 
- Install `Microsoft.AspNetCore.Authentication.Google` in the `Umbraco.Web.UI` project.
- Add a new class `GoogleAuthenticationExtensions.cs`
```
using MyCustomUmbracoProject.ExternalUserLogin.GoogleAuthentication;
public static class GoogleAuthenticationExtensions
{
public static IUmbracoBuilder AddGoogleAuthentication(this IUmbracoBuilder builder)
{
// Register ProviderBackOfficeExternalLoginProviderOptions here rather than require it in startup
builder.Services.ConfigureOptions<GoogleBackOfficeExternalLoginProviderOptions>(); …
```

Set invite users to false if deny local login is true

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentBlueprint/Item/ItemDocumentBlueprintController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentBlueprint/Tree/AncestorsDocumentBlueprintTreeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentBlueprintForDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeBlueprintItemResponseModel.cs
src/Umbraco.Core/Services/ContentBlueprintEditingService.cs
src/Umbraco.Core/Services/IContentBlueprintEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.Get.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.GetPagedByContentTypeKey.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Get.cs
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj

- Fixed `/item` endpoint to return 0 items when no items' keys are passed in, as opposed to returning all items (_there is a task to align this behaviour across all item endpoints_);
- Added 2 new blueprint endpoints:
- GET `/umbraco/management/api/v1/tree/document-blueprint/ancestors` - used for breadcrumbs.
- GET `/umbraco/management/api/v1/document-type/{id}/blueprint` - used when creating new content, to show the blueprints available for a document type.
- Fixed some test cases + added some more; 
- Create some blueprints;
- Test the 3 endpoints:
- Make sure that you can get the items you expect through the `/item` endpoint and that you get 0 items when no keys are passed;
- Pass the blueprint key to the `/ancestors` endpoint and verify that you get the folder and the item in …

V14: Additional blueprint endpoints

---

src/Umbraco.Cms.Api.Management/Controllers/Security/ConfigurationSecurityController.cs
src/Umbraco.Cms.Api.Management/Controllers/Security/ResetPasswordController.cs

This PR ensures that the security configuration endpoint mimics the "reset password" endpoints, disallowing access if "deny local login" is configured.
The other change is just a leftover, that was not removed. The controller (`ResetPasswordController`) already adheres to the same auth requirements as [the corresponding endpoint in V13](https://github.com/umbraco/Umbraco-CMS/blob/8a9e6ee82dc265dc86983fd1dcb5aec526252851/src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs#L463).

Clean up FIXMEs in security controllers

---

src/Umbraco.Core/Deploy/IContextCache.cs
src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
src/Umbraco.Core/Deploy/IFileSource.cs
src/Umbraco.Core/Deploy/IFileType.cs
src/Umbraco.Core/Deploy/IImageSourceParser.cs
src/Umbraco.Core/Deploy/ILocalLinkParser.cs
src/Umbraco.Core/Deploy/IServiceConnector.cs
src/Umbraco.Core/Deploy/IValueConnector.cs
src/Umbraco.Core/Deploy/PassThroughCache.cs

With most (if not all) services in v14 having async implementations (and new services even exclusively), this adds async methods to the Deploy interfaces, so we can implement '[async all the way](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way)'.
I've added these new async methods in a backwards-compatible way using default implementations that return `Task.FromResult(...)` and call the existing sync method. To signal to all callers and implementers to use the async methods, I've made the sync methods obsolete. This should allow us to first ensure the new async methods are implemented and called everywhere, remove the default implementations in the next major and finally remove the sync methods …

v14: Add async methods to Deploy interfaces

---

src/Umbraco.PublishedCache.NuCache/Property.cs

If there's an existing issue for this PR then this fixes #15827
Due to some V14 branch merges, #15928 is unable to target V13.3, so I have moved over the changes to this PR. See #15928 for more details. All credits go to the original contributors ❤️ 
For the time being I have _not_ moved over the `Lazy` dictionary changes, because I wanted to see how the other changes worked without `Lazy`. It seems to work just as fine. Please comment if they should be re-introduced.
Here's the K6 script execution (from #15827) on this branch:
The first execution is _without_ this PR applied, second is _with_ this PR applied.

Ported over #15928 changes for 13.3 RC

---

src/Umbraco.Core/PropertyEditors/MediaPicker3Configuration.cs
src/Umbraco.Core/PropertyEditors/MultiNodePickerConfigurationTreeSource.cs
src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs

As discussed with @Migaroez, I suspect these were missed during the data type configuration migration work.
Strange thing is that the frontend (beta002) had been working with these fine until yesterday, when it started to throw errors about the MediaPicker and MNTP configurations, so I'm not sure if something else changed on the server-side, but correcting the object-type appears to fix this.

V14: MediaPicker/MNTP - Changed `StartNodeId` from a `Udi` to `Guid`

---

Directory.Packages.props
src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj

While building `v14/dev` I noticed getting a `NU1504` error: `Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: SixLabors.ImageSharp , SixLabors.ImageSharp 2.1.7; SixLabors.ImageSharp.Web , SixLabors.ImageSharp.Web 2.0.2.`.
This PR removes the duplicate PackageReference and also updated both ImageSharp (v2 and v3) and MailKit dependencies to the latest versions.

v14: Update ImageSharp and MailKit dependencies

---

src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs
src/Umbraco.Core/DeliveryApi/ApiContentResponseBuilder.cs

This PR makes the default API content response builder extendable, thus making it easier to customize the output of the Delivery API.
Due to how System.Text.Json handles polymorphism, the default JSON type resolver also needs to be extendable, in order to add custom response models to the allow-list for API responses.
Build a custom `IApiContentResponseBuilder` by extending the default `ApiContentResponseBuilder`. The custom API response builder should be able to:
1. Return its own content model (an extension of `ApiContentResponse`).
2. Manipulate the properties collection created by the `ApiContentResponseBuilder` base before they are returned by the API.
The following test code can be used, or at least serve as inspiration for testing 😉 
```cs
using System.Text.Json;
using …
```

Make the API content response builder extendable

---

src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs

Fixed a small issue with collection views (List views) when ordering by a custom property, it was not determined as custom and did not work
- Test a collection view and order by one of the properties from the doc type.

Fix Collection views with custom field ordering

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ReportSiteJob.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.TelemetryProviders.cs
src/Umbraco.Infrastructure/Telemetry/Providers/WebhookTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

Adds webhook information to detailed telemetry, a sample payload looks like the following: 
```
{
"name": "WebhookCount_Total",
"data": 3
},
{
"name": "WebhookCount_Umbraco.ContentDelete",
"data": 1
},
{
"name": "WebhookCount_Umbraco.ContentPublish",
"data": 1
},
{
"name": "WebhookCount_Umbraco.ContentUnpublish",
"data": 1
},
{
"name": "WebhookCount_Umbraco.MediaDelete",
"data": 1
},
{
"name": "WebhookCount_Umbraco.MediaSave",
"data": 1
},
{
"name": "WebhookCount_CustomEvent",
"data": 1
},
{
"name": "WebhookCount_CustomHeaders",
"data": 1
}
```
Ensure that the payload is accurate, then can be achieved by setting a breakpoint in `ReportSiteJob` and ensure that the contents of `telemetryReportData` is as expected

V13: Add webhook information to detailed telemetry

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddGuidsToUsers.cs
src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializer.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/PackageManifestReaderTests.cs

This PR contains two small changes required.
1. Adding the JsonObjectConverter by default is required for the block editors to work
1. Adding a safety check around creating an index, so it is not created if it already exists.

Add JsonObjectConverter to the default serializer and make a safe check before adding index

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
src/Umbraco.Web.UI.Login/package-lock.json
src/Umbraco.Web.UI.Login/package.json
src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts
src/Umbraco.Web.UI.Login/src/index.ts

- Do not load entrypoints on the login screen (the screen only supports simple extensions)
- Remove dependency on uui-css and load from the built backoffice client instead (we get the javascript through the importmap anyway)

V14: Optimise login screen javascript

---

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilder.BackOffice.cs
src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
src/Umbraco.Cms.Api.Management/Security/BackOfficeAuthenticationBuilder.cs
src/Umbraco.Cms.Api.Management/ViewModels/Security/UnLinkLoginRequestModel.cs
src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Common/Extensions/OAuthOptionsExtensions.cs
src/Umbraco.Web.Common/Helpers/OAuthOptionsHelper.cs

This PR introduces some proposed helper methods to uniformly communicate external login errors that come into the backend trough the configured callback methods to a specific frontend path.
[ExampleGithubCode.zip](https://github.com/umbraco/Umbraco-CMS/files/14978456/ExampleGithubCode.zip) (requires installation of `AspNet.Security.OAuth.GitHub`)
This adds all the necessary bits to register github as an external login provider and some bad frontend code to link/unlink.
When starting the linking process from the backend, you will need to open your devtools and click on the CORS blocked link manually to continue, the Frontend team has a task to improve this behaviour
If you use the endpoints, make sure to set the Umbraco authentication cookie as it is needed to figure out what user the …

V14 External login linking + Proposed error handling

---

build/azure-pipelines.yml

Do not refer to `$npmTag` which does not exist and `--access` is not required either since we now specify that in the package.json file.

V14: Fix npmjs.org publish

---

src/Umbraco.Core/Constants-Telemetry.cs
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.TelemetryProviders.cs
src/Umbraco.Infrastructure/Telemetry/Providers/BlocksInRichTextTelemetryProvider.cs
src/Umbraco.Infrastructure/Telemetry/Providers/PropertyEditorTelemetryProvider.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

Adds a telemetry provider that reports on the total amount of registered rich text editors data types, and the amount of blocks used in rich text editors.
```json
{
"name": "RichTextEditorCount",
"data": 3
},
{
"name": "RichTextBlockCount",
"data": 3
}
```

Add blocks in RTE telemetry

---

src/Umbraco.Cms.Api.Management/Factories/MemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/CreateMemberRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/UpdateMemberRequestModel.cs
src/Umbraco.Core/Models/ContentEditing/MemberEditingModelBase.cs
src/Umbraco.Infrastructure/Services/MemberEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberEditingServiceTests.cs

There was a bug, that when you created a member with a member group, an additional member group was created.
This comes down to do with how member groups are created, as these are created based by role (name).
In v14 however, these member groups are referenced by key, and thus a new member group with the key as name, was created.
This PR remedies that, by mapping the keys over to names when its inbound, and then mapping the names back to key when it's outbound
- Via the UI, create a member group
- Create a member with that member group assigned.
- This should no longer create an extra member group
- Start on v13
- Create some members and member groups
- migrate to v14
- Assert that you can get the members without any errors

V14: Fix member mapping

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Item/ItemDatatypeItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Item/ItemDictionaryItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Item/ItemDocumentItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/ItemDocumentTypeItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/Item/ItemsLanguageEntityController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/ItemMediaItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/ItemMediaTypeItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Item/ItemMemberItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/Item/ItemMemberGroupItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/ItemMemberTypeItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/PartialView/Item/ItemPartialViewItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/RelationType/Item/ItemRelationTypeItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Item/ItemScriptItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Item/ItemStaticFileItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Item/ItemStylesheetItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Template/Item/ItemTemplateItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Item/ItemUserItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/Item/ItemUserGroupItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Webhook/Item/ItemsWebhookEntityController.cs

This pr builds on https://github.com/umbraco/Umbraco-CMS/pull/16047, where we have started to return 0 items, on the `items` endpoint, if the ids / paths are 0.
- For consistency, I've added the count check to ALL the endpoints, although it isn't always neccesary.
- Lets take `ItemRelationTypeItemController` as an example, this will get out ALL the relation types, and then filter by ids, which will end up still return 0 items, so the behavior is the same. We do however save on performance, as we don't need to make a db/cache call to get out all the relation types
- Test the 19 different endpoints, and assert when you send 0 ids/paths, you do not get any items

V14: Refactor items endpoint to return 0 items when ids/paths are empty

---

src/Umbraco.Core/Constants-SystemDirectories.cs

`Constants.SystemDirectories` contains a fair few constants that are related to the V13 implementation of the backoffice. This PR cleans up those constants.

Cleaned up V13 related and obsoleted system directory constants

---

src/Umbraco.Cms.Api.Management/Controllers/Webhook/AllWebhookController.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/WebhookRepository.cs

- The `webhook` get endpoint to get all webhooks did not work, as it would throw an error about not knowing how to map, this has been fixed by using the Presentation factory instead, as there is no `WebhookMapDefinition`
- The `item` endpoint would always return 0 items, as the `GetByIdsAsync` webhook repository method did not work, this has been remedied by refactoring the method to have similar functionality to `GetAsync`
- Start on v13
- Create a couple of webhooks
- Migrate to v14 (this branch)
- Call the `webhook` get endpoint to get all webhooks, this should return the correct number.
- Call the `item` endpoint for webhook, with one or more ids (you can get these ids from the all endpoint you just called), and assert it returns the correct number of items

V14: Fixup webhook endpoints

---

src/Umbraco.Cms.Api.Common/OpenApi/IOpenApiDiscriminator.cs
src/Umbraco.Cms.Api.Common/Serialization/IUmbracoJsonTypeInfoResolver.cs
src/Umbraco.Cms.Api.Common/Serialization/UmbracoJsonTypeInfoResolver.cs
src/Umbraco.Cms.Api.Management/Configuration/ConfigureUmbracoManagementApiSwaggerGenOptions.cs
src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/Permissions/IPermissionPresentationModel.cs

At the moment it's only possible to create a polymorphic output from the Management API by basing the return models on an interface.
This is a little too strict, so we need another way of opting into polymorphic output - by means of class annotation. Enter `JsonDerivedType`.
This PR allows you to apply `JsonDerivedType` to a return model base class. The Management API will pick up on the annotations automatically.
When using annotation, it is important that you explicitly specify the type discriminator in `JsonDerivedType` - like this:
```csharp
[JsonDerivedType(typeof(MyItem1), nameof(MyItem1))]
[JsonDerivedType(typeof(MyItem2), nameof(MyItem2))]
public abstract class MyItemBase(string value)
{
public Guid Id { get; } = Guid.NewGuid();
public string Value { get; set; } = value;
}
public …
```

Support OpenAPI polymorphic output with `JsonDerivedType`

---

src/Umbraco.Cms.Api.Common/OpenApi/SwaggerRouteTemplatePipelineFilter.cs

Configured the swagger UI  to persist the authentication token (still only valid for 5 minutes, as it cannot use refreshtoken) and added filtering.

Configured the swagger UI

---

src/Umbraco.Infrastructure/PropertyEditors/MultipleValueEditor.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/16080
See linked issue for details.
**Note:** The issue does _not_ affect ratio button list as it is mentioned in the linked issue.
It should be possible to edit and reload documents with checkbox list and dropdown (single and multiple configurations).

Fix data parsing error for dropdown and checkbox list

---

src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Tree/StaticFileTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Extensions/StringPathExtensions.cs

The Management API fails miserable at retrieving stylesheets for an RTE.
As it happens, our file system trees are not acting correctly. This PR fixes it.
1. An RTE with one or more stylesheets configured should _not_ fail in loading said stylesheets.
2. The "static files" API endpoints should still work (allowing access to "/App_Plugins" and "/wwwroot").

Fix RTEs stylesheet loading error

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateCharPermissionsToStrings.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateNotificationCharsToStrings.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateUserGroup2PermissionPermissionColumnType.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateUserGroup2PermissionPermissions.cs
src/Umbraco.Infrastructure/Persistence/Dtos/User2NodeNotifyDto.cs
src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2PermissionDto.cs

Migrates the `umbracoUser2NodeNotify.action` column use the new action strings instead of the action letters. This involves changing the column type to `Nvarchar(255)`, and mapping the action letters to the new action strings. 
Additionally this also migrates the `umbracoUserGroup2Permission.permission` column to use `Nvarchar(255)`, partly just to align the two, since it's referencing the same thing, but this will also allow for a compound key in the future. 
On both Sqlite and MSSQL: 
0. Ensure SMTP is configured
1. Create some content in v13
2. Enable notifications for the content 
3. Migrate the database to v14.
4. The values in the mentioned tables should now be updated (except for 'H', since that's a deploy thing) 
5. Content notifications should now work

V14: Migrate notify action from char to string 

---

src/Umbraco.Core/PropertyEditors/RichTextConfiguration.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs

If there's an existing issue for this PR then this fixes #16083
The RTE config for default media upload folder has been migrated from an `Udi` in V13 to a `Guid` in V14 ([see migration here](https://github.com/umbraco/Umbraco-CMS/blob/v14/dev/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs#L495)).
Unfortunately the implementation of the strongly typed RTE config `RichTextConfiguration` has not followed suit, which causes the config parsing error reported in the linked issue.
See the linked issue for details.

RTE media folder config is stored as a GUID in V14

---

src/Umbraco.Cms.Api.Management/Controllers/Document/CreatePublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/GetPublicAccessDocumentController.cs
src/Umbraco.Cms.Api.Management/Factories/IMemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/MemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/PublicAccessPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/MemberType/MemberTypeMapDefinition.cs
src/Umbraco.Core/Services/PublicAccessService.cs

There are a few issues with the "get" and "create" endpoints for public access.
1. Upon successful creation of a public access rule, the endpoint yields the wrong "created at" location. The correct location to retrieve the created rule is `/document/[document key]/public-access`.
1. The HTTP 200 OK response is not documented towards OpenAPI.
2. When queried for a non-existing public access rule, the endpoint should return HTTP 404 NotFound.
3. When queried for a public access rule with one or more explicit members, the operation fails because the umbraco mapper does not know how to map `IMember` to `MemberItemResponseModel`.
4. Fixing the previous problem uncovers that public access rules with explicit members yields a `MemberItemResponseModel` that contains _all_ existing member groups …

Make public access endpoints work correctly

---

src/Umbraco.Core/PropertyEditors/UserPickerPropertyEditor.cs

_This is the user equivalent of https://github.com/umbraco/Umbraco-CMS/pull/16149_
The user picker property editor stores the integer ID of the picked user. However, the V14 client needs the user key to resolve the user data in the editor UI, so we need to translate the value back and forth.
Note that we still need to retain the integer ID when storing data. Eventually we should migrate this, but a content migration is not desirable for V14.
The user picker property editor UI should work and should be able to store and retrieve a picked user.

Translate user picker property editor value to V14 compatible format (and back again)

---

src/Umbraco.Core/Cache/DistributedCacheExtensions.cs
src/Umbraco.Core/Cache/Refreshers/Implement/UserCacheRefresher.cs
src/Umbraco.Core/Persistence/Repositories/IUserRepository.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/UserRepositoryTest.cs

- We need to cache user by id aswell, because all content have creatorId (as int) and thus when we index content, user by id gets called for each content item, therefore we need to cache the user to avoid a lot of db calls.
- Put a breakpoint in the `UserRepository.Get(int id)` method
- Assert that first time a user gets retrieved, the `GetCacheItem` should return null (not in the cache
- Assert that the second time the user gets retrieved `GetCacheItem` should now have a user.
- Update the users name (or something else, name is easiest)
- Get the user again, and assert that the `GetCacheItem` returns null (Updated user should NOT be in the cache)
- Get the user once last time, and assert that it is indeed cached again, with the updated name

V14: Cache user by id

---

src/Umbraco.Infrastructure/PropertyEditors/TemporaryFileUploadValidator.cs

- There was a bug that did not allow us to save and publish a document, when you had uploaded a file to a file upload field.
- This was because the `TemporaryFileUploadValidator` would fail validation for the temporary file, as  it would fail when `contentSettings.IsFileAllowedForUpload(extension)` was true, which is the wrong way around 🙈 This has been remedied by checking if its false instead 😛 
- Create a document type, with a file upload property
- Try to create some content with that document type, make sure to upload an image (jpg for example)
- Save and publish, this should now no longer yield errors 😁 
Image I used for testing:

V14: Allow file uploads when save and publishing

---

src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
src/Umbraco.Core/Configuration/Models/SecuritySettings.cs

This adds an extra option to allow configuration of the authorized logout path, which enables any client to allow the user to get redirected back to a certain path following a successful logout. The default is `/umbraco/logout`.
We want the user to land on a dedicated logout page so that we know they were logged out and not. This allows us to let the user stay on the logout page rather than, say, redirect them to a login provider with automatic redirect setup.
Also, this was hardcoded before, which wasn't the nicest solution and didn't work when you accessed the Management API from another host. By moving this to a configuration option, we can allow developers to set the value specifically for their usecase.

V14: add authorized logout callback path

---

src/Umbraco.Core/PropertyEditors/MemberGroupPickerPropertyEditor.cs

_This is the member groups equivalent of #16149_
The member group picker property editor stores a CSV of the picked member group integer IDs. However, the V14 client needs the member group keys to resolve the member group data in the editor UI, so we need to translate the value back and forth.
Note that we still need to retain the integer IDs when storing data. Eventually we should migrate these, but a content migration is not desirable for V14.
The member group picker property editor UI should work and should be able to store and retrieve one or more picked member groups.

Translate member group picker property editor value to V14 compatible format (and back again)

---

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs

This PR Ensures claims added in the OnExternalLogin are actually persisted in the tokens we store.
The issue before was we did not use the same ClaimsPricipal when calling OpenIddict as the one used doing External Login

Persist claims from OnExternalLogin event

---

src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts

chore: remove import from backoffice icons since we now only have to rely on the ui library
this also fixes an issue where icons did not work anymore due to changes in the backoffice taking over
it can be tested by checking if the "check" or "cross" icons show up on the main login button.

V14: the login page only needs UUI icons

---

src/Umbraco.Core/Models/Blocks/BlockEditorData.cs
src/Umbraco.Core/Models/Blocks/BlockEditorDataConverter.cs
src/Umbraco.Core/Models/Blocks/BlockGridEditorDataConverter.cs
src/Umbraco.Core/Models/Blocks/BlockGridValue.cs
src/Umbraco.Core/Models/Blocks/BlockListValue.cs
src/Umbraco.Core/Models/Blocks/BlockValue.cs
src/Umbraco.Core/Models/Blocks/RichTextBlockValue.cs
src/Umbraco.Core/Models/Blocks/RichTextEditorBlockDataConverter.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextBlockPropertyValueCreator.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteBlockRenderingValueConverter.cs
src/Umbraco.Infrastructure/Serialization/JsonBlockValueConverter.cs
src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializer.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/PropertyIndexValueFactoryTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockGridPropertyValueConverterTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/JsonBlockValueConverterTests.cs

The original [RFC for block editors](https://github.com/umbraco/rfcs/blob/main/cms/0011-block-data-structure.md) states that a Block Editor should theoretically be able to store multiple simultaneous block layouts.
However, while removing the explicit JSON technology dependencies in the Block Editor implementation in favour of a strongly typed approach, we (yours truly) accidentally managed to enforce _one_ type of block layout for _all_ layouts in any given Block Editor. And that's obviously incorrect.
Unfortunately we cannot know about the concrete block layout implementations of other Block Editors when (de)serializing a concrete Block Editor instance. This means we can only (de)serialize layouts that belong to the concrete Block Editor instance in question.
To that end, this PR …

Handle multiple simultaneous block editor layouts

---

src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/AllowedMediaTypeItemController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Core/Services/ContentTypeEditing/IMediaTypeEditingService.cs
src/Umbraco.Core/Services/ContentTypeEditing/MediaTypeEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.GetMediaTypesForFileExtension.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.cs

This PR adds an endpoint which returns allowed media types based on a file extension.
The media types returned should be the combination of:
- All media types with image cropper configured as the `umbracoFile` property, provided the image cropper is able to handle the file extension.
- All media types with a file upload configured as the `umbracoFile` property, where the file upload configuration explicitly allows the file extension.
If no media types are found, the endpoint should return all media types with a file upload configured as the `umbracoFile` property, where the file upload configuration has _no_ allowed file extensions (which means "allow all").
Use Swagger to verify that:
1. Image file extensions yield the "Image" media type.
2. File extensions explicitly defined on media …

Add endpoint for retrieving allowed media types for file extensions

---

src/Umbraco.Cms.Api.Management/Controllers/MemberType/Tree/MemberTypeTreeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberType/Tree/RootMemberTypeTreeController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Tree/MemberTypeTreeItemResponseModel.cs

The member types tree output does not contain the configured member type icons. That's a mistake, so this PR fixes it 😄 
Use Swagger to verify that the API output contains member type icons.

Add member type icon to member type tree output

---

src/Umbraco.Cms.Api.Management/Controllers/User/Item/ItemUserItemController.cs
src/Umbraco.Cms.Api.Management/Factories/IUserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/Item/UserItemResponseModel.cs

Frontend needs avatarUrls on the item endpoint as it is a crucial aspect to display users in pickers.
After setting an avatar on a user (you should be able to use the client), check that the item endpoint returns the crop urls for the avatar on the selected user.

Add avatarUrls to the userItem responsemodel

---

src/Umbraco.Cms.Api.Management/Mapping/DataType/DataTypeViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeModelBase.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddEditorUiToDataType.cs

As of #15463 we have been tracking data type configurations with the intent of correctly migrating the split into "editor alias" and "editor UI alias". This PR performs the actual migration 😄 
The idea is:
1. All data types for core editors are migrated with their new editor UI aliases hardcoded.
2. All data types for custom editors are migrated based on the data collected by the [`DataTypeSplitDataCollector`](https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.Infrastructure/Migrations/PreMigration/DataTypeSplitDataCollector.cs) in V13.
Note that there are different ways to build a property editor, thus we have been assuming the following:
1. If a property editor is declared by means of a manifest:
- The V14 editor alias must be the "plain" `DataEditor` that corresponds to …

Add data type editor UI aliases on upgrade

---

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs

_This is the install equivalent to #16183_
Currently, all data types have missing icons on a freshly installed V14:
...despite them seemingly being correctly configured when edited:
This PR ensures that all data types are created with their correct editor UI aliases, thus ensuring that the icons are correct from the get-go:
☝️ As with #16183, this PR sets also the list view editor UI alias to "Umb.PropertyEditorUi.Collection" as a preemptive measure, because this is what it will be eventually on the client (it is currently "Umb.PropertyEditorUi.CollectionView", which is wrong). Thus the list view icons might not show up correctly, depending on when you test this.
Spin up a brand new V14 database and verify that all data types (possibly except the list view ones) have correct icons in the …

Set the data type editor UI aliases at install time

---

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs

- Remove the validation of credentials first, as this is not needed.
Brif history on why: it's because deploy needed a way to validate credentials, without logging the user in, thus `ValidateCredentialsAsync` was created.
Thus it is safe to remove this validation, as `PasswordSignInAsync` will validate the password, increment the lockout count etc all on its own.
- Create a new user (remember the email and password)
- Log in with the user just to activate it
- Log out again
- Try to log in with the WRONG password more than 5 times
- Try to log in with the right password, this should now fail as the user is locked out 😁

V14: Lock out users

---

src/Umbraco.Cms.Api.Management/Factories/PackagePresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Package/CreatePackageRequestModel.cs

Allowing to specify the ID on the create package endpoint aligns it with the rest of our create endpoints
- Validate whether a chosen ID is respected in the response headers and the resource can be fetched.
- Validate the ID is optional and a random one will be assigned if not supplied

[V14] Allow specifying ID on the create package endpoint

---

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
src/Umbraco.Web.Common/Helpers/OAuthOptionsHelper.cs

> [!WARNING]
> Should not be merged before https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1720 is merged
This allows the server to send the user back to a route on the backoffice client where nothing is loaded. This is useful in case the user is being logged in inside a popup, where you don't need to load the whole backoffice client, since the popup will be closed by itself.

V14: Unique OAuth callback route

---

src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs

Following the feature in #16194 we need to add the new "oauth_complete" path to the list of exemptions for the backoffice client.

V14: The `/umbraco/oauth_complete` route should show the Backoffice client

---

src/Umbraco.Core/Xml/XPath/NavigableNavigator.cs

This was unexpected in the XPath navigator code, faulting it into the exception state.
Fixes #15582
The cause of the error is that there is a block list editor on the Error page that we're trying to select by XPath.
Since we're trying to find property values on content items to be able to match the XPath specified in appsettings, we need to  look at all the properties (which is also why it's inefficient and this code is removed in v14).
This works for most things but not for content items with an RTE any more. Since we added blocks to the RTE in v13, the RTE property is no longer a simple string, instead it is an `RichTextEditorIntermediateValue` (as per PR #15645). Our XPath navigator code is not expecting this value.
To test: 
- Install the Clean starterkit
- Set 404 error collection …

Since v13 properties can sometimes be of new type `RichTextEditorIntermediateValue`

---

src/Umbraco.Cms.Api.Management/Controllers/Webhook/CreateWebhookController.cs
src/Umbraco.Cms.Api.Management/Controllers/Webhook/DeleteWebhookController.cs
src/Umbraco.Cms.Api.Management/Controllers/Webhook/UpdateWebhookController.cs
src/Umbraco.Cms.Api.Management/Factories/IWebhookPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/WebhookPresentationFactory.cs

- Fixes various webhook endpoints, as they were using mapping definition and not presentation factory
- Create and delete webhooks via swagger, this should now work

V14: Webhook endpoint fixes

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddEditorUiToDataType.cs

The editor UI for MNTP has changed from `Umb.PropertyEditorUi.TreePicker` to `Umb.PropertyEditorUi.ContentPicker` - this change needs reflecting in the upgrade migration (we do not install a default MNTP, so _only_ the upgrade migration is affected).

Use the correct editor UI for MNTP

---

.github/release.yml

This needs to reside on the main branch to work for release notes.

Add release.yml to categorize release notes

---

src/Umbraco.Core/Models/WebhookLog.cs
src/Umbraco.Core/Services/WebhookLogFactory.cs
src/Umbraco.Infrastructure/Persistence/Factories/WebhookLogFactory.cs
src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
src/Umbraco.Web.Common/Models/WebhookLogViewModel.cs
src/Umbraco.Web.UI.Client/src/views/webhooks/logs.controller.js
src/Umbraco.Web.UI.Client/src/views/webhooks/logs.html
src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.controller.js
src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html
src/Umbraco.Web.UI.Client/src/views/webhooks/overview.controller.js

Made some improvements to the webhook logs.
- Ensured all headers gets persisted by including the http messages `Content.Headers`
- Moved is success check to the server (in Heartcore we store this value, so we would like to reuse that), and return success for all `2xx` responses
- Made logs deep linkable and ensure the sub views are only loaded when their tab are active (fixes logs being loaded as soon as visiting the webhooks page)
- Added pagination to webhook logs
- Improved request/response preview by using the content type header
- Moved Webhook Key from overview to details popup
Before:
After:

Webhook log improvements

---

src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs

- Allows for items in a collection view to be sortable by "creator", aka "Created by" field;
- Changing the order of transforming "creator" to "owner" since we are performing a check against the collection view properties and there it is named "creator" => we need to do the check first.
- Create a root doc type with collection view enabled & a child doc type;
- Create some content to be able to sort items in the collection view;
- **Use at least 2 users** when creating the content items, so that you can see a difference when sorting.
- Modify the "Columns Displayed" on the "List View - Content" data type to have the "Created by" property - _you can find it under "Document type" > the child doc type > "Created by"_ 
- In the Content section, navigate to the Collection app;
- Verify that by …

V14: Fix sorting by "creator" on collection view

---

src/Umbraco.Cms.Api.Management/Factories/IndexPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Indexer/HealthStatusResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Indexer/IndexResponseModel.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Factories/IndexPresentationFactoryTests.cs

- Fixes the backend part of the following issue, reported in https://github.com/umbraco/Umbraco-CMS/issues/16213:
> When the IIndexDiagnostics reports unhealthy, the dashboard not longer uses the Attempt<string> result to display the unhealthy error message. The string returned from this attempt should be displayed.
- Change [_this line_](https://github.com/umbraco/Umbraco-CMS/blob/v14/dev/src/Umbraco.Cms.Api.Management/Factories/IndexPresentationFactory.cs#L38) to the following:
```c#
Attempt<string?> isHealthy = Attempt.Fail("something went wrong");
```
- Verify that when an index is unhealthy, you get the `"something went wrong"` message using `GET /umbraco/management/api/v1/indexer` endpoint;
- Verify that the `healthStatus::message` (in the output) is null when there is no message, …

V14: Return the unhealthy error message from Examine index

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs
src/Umbraco.Core/Services/DataTypeService.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/14665 added `GetAllAsync(params Guid[] keys)` to `IDataTypeService`, but the implementation returns 0 data types when no keys are specified, which is different to the existing `GetAll(params int[] ids)` that returns all data types of no IDs are specified.
This PR fixes the `GetAllAsync()` implementation and also removes some unnecessary async/awaits (on methods that use `Task.FromResult()`.

v14: Return all data types from `DataTypeService.GetAllAsync()`

---

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs

Return 401 in case the signin was not successfully, so the client can show a message

Return 401 in case the signin was not successfully

---

src/Umbraco.Core/Constants-Web.cs
src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Website/Extensions/UmbracoApplicationBuilder.Website.cs
src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs
src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs

This optimizes the routing of custom MVC routes, both with and without `UmbracoPageController` by ensuring that the `UmbracoRouteValueTransformer` is only hit when needed, this fixes #16015.
This problem is caused by the behaviour of asp.net core as [explained in this comment:](https://github.com/dotnet/aspnetcore/issues/45175#issuecomment-1322497958)
"all routes get evaluated, they get to produce candidates and then the best candidate is selected. Since you have a dynamic route, it needs to run to produce the final endpoints and then those are ranked in along with the rest of the candidates to choose the final endpoint." 
This means that no matter what the `UmbracoRouteValueTransformer` would always be called, requiring it to run through **all** content finders. 
The fix for this is to …

V13: Optimize custom MVC routing

---

src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
src/Umbraco.Core/UmbracoApiControllerTypeCollection.cs
src/Umbraco.Web.Common/Attributes/UmbracoApiControllerAttribute.cs
src/Umbraco.Web.Common/Controllers/UmbracoApiController.cs
src/Umbraco.Web.Common/Controllers/UmbracoApiControllerBase.cs
src/Umbraco.Web.Common/Controllers/UmbracoApiControllerTypeCollectionBuilder.cs
src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
src/Umbraco.Web.Common/Extensions/TypeLoaderExtensions.cs
src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
src/Umbraco.Web.Common/Security/ConfigureMemberCookieOptions.cs
src/Umbraco.Web.Website/Extensions/TypeLoaderExtensions.cs
src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
tests/Umbraco.Tests.Integration/Umbraco.Web.Website/Security/MemberAuthorizeTests.cs
tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/BackOfficeAreaRoutesTests.cs

This PR Reintroduces the UmbracoApiController with a massive obsolete warning.
- The routing should still work
- It is expected serialization is now using System.Text.Json with camel case etc.

V14: Reintroduce umbraco api controller as obsolete

---

src/Umbraco.Cms.Api.Common/OpenApi/SwaggerRouteTemplatePipelineFilter.cs
src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs

Since #16028, the developer clients (Swagger, Postman) have been subject to very short-lived access tokens (five minutes by default). This is quite annoying when testing APIs 😞 
OpenIddict 5.0 introduced a solution for per-client token lifetimes (see this [reference article](https://kevinchalet.com/2023/10/20/introducing-native-applications-per-client-token-lifetimes-and-client-assertions-support-in-openiddict-5-0-preview1/))
. This PR utilizes that feature to set a fixed token lifetime (20 minutes at the time of writing) for the developer clients.
Also, the Swagger client is currently configured to persist auth, in part as a workaround for the short-lived access tokens. While well meant, this persistence far outlives the token lifetimes, which causes the Swagger UI to indicate successful …

Use a fixed access token timeout for developer clients

---

src/Umbraco.Cms.Api.Management/Controllers/Culture/AllCultureController.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
src/Umbraco.Core/Services/CultureService.cs
src/Umbraco.Core/Services/ICultureService.cs
src/Umbraco.Core/Services/IIsoCodeValidator.cs
src/Umbraco.Core/Services/IsoCodeValidator.cs

This PR ensures we do not expose any cultures we do not accept in languages.
Furthermore, I moved it to a service to people can replace the logic

Do not expose culture we do not accept for languages

---

src/Umbraco.Core/Services/TemplateService.cs

_This is the `TemplateService` equivalent of #16230_
To align functionality of our services, `GetAllAsync(params Guid[] keys)` must return _all_ templates if _no_ keys have been passed to the method.
This is functionally breaking, but "only" towards the new V14 service methods.
I have verified that all consumers of this method are guarded by an explicit check for zero results, thus ensuring we don't accidentally return _all_ templates when we're in fact wanting to return _none_.
`GetAllAsync(params Guid[] keys)` is only used by the template "item" and "search" endpoints. Both should still work 😄 
- The "item" endpoint should return no templates if no item keys are passed.
- The "search" endpoint should return no templates if there are zero matches to the search query.
- The "search" …

TemplateService should return all templates from GetAllAsync if no keys are passed

---

src/Umbraco.Cms.Api.Management/Security/TwoFactorLoginViewOptions.cs
src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
src/Umbraco.Web.UI.Login/src/components/pages/mfa.page.element.ts
src/Umbraco.Web.UI.Login/src/contexts/auth.repository.ts
src/Umbraco.Web.UI.Login/src/localization/lang/da-dk.ts
src/Umbraco.Web.UI.Login/src/localization/lang/de-de.ts
src/Umbraco.Web.UI.Login/src/localization/lang/en-us.ts
src/Umbraco.Web.UI.Login/src/localization/lang/en.ts
src/Umbraco.Web.UI.Login/src/localization/lang/nb-no.ts
src/Umbraco.Web.UI.Login/src/localization/lang/nl-nl.ts
src/Umbraco.Web.UI.Login/src/localization/lang/sv-se.ts

Fixes #16240
The login page does not handle certain error codes coming from the API, nor does it allow to submit the form in certain circumstances.
**Login**
* 403 (user is locked out) - no error message to show the user, and the fallback error message did not work
**Two-Factor**
* 400 (wrong authorization code) - the error fell through and was considered as a success, but naturally, the user was not logged in and therefore stayed on the login page with no error message being shown
* 401-500 errors - the errors did not have appropriate error messages
Setup a fake two-factor authenticator, or follow the [newly updated guide on the UmbracoDocs](https://docs.umbraco.com/umbraco-cms/v/14.latest-rc/reference/security/two-factor-authentication#two-factor-authentication-for-users).

V14: The login page does not respect certain error codes

---

src/Umbraco.PublishedCache.NuCache/Property.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/PublishedContentVarianceTests.cs

If there's an existing issue for this PR then this fixes #16186
This PR fixes #16186
The property level variance has been a problem child for a while now. These issues are related to the same thing:
- https://github.com/umbraco/Umbraco-CMS/issues/15117
- https://github.com/umbraco/Umbraco-CMS/issues/14758
First and foremost, make sure everything works in respect to the original issue (#16186). I have attached testing resources at the end of this PR description, so you don't have to set everything up from scratch. The "Home" item is setup for testing #16186.
Second make sure that property level expansion still works (see #14758 for details). Remember to enable the Content Delivery API 😉 If you're using the test DB attached below, this content item (`f9f25aed-4a73-4ed2-aa6e-efb4359a39ce`) …

Property source level variation should only be applied when configured

---

src/Umbraco.Core/Models/Blocks/BlockEditorData.cs
src/Umbraco.Core/Models/Blocks/BlockEditorDataConverter.cs
src/Umbraco.Core/Models/Blocks/BlockGridLayoutAreaItem.cs
src/Umbraco.Core/Models/Blocks/BlockGridLayoutItem.cs
src/Umbraco.Core/Models/Blocks/BlockGridValue.cs
src/Umbraco.Core/Models/Blocks/BlockItemData.cs
src/Umbraco.Core/Models/Blocks/BlockListLayoutItem.cs
src/Umbraco.Core/Models/Blocks/BlockListValue.cs
src/Umbraco.Core/Models/Blocks/BlockValue.cs
src/Umbraco.Core/Models/Blocks/RichTextBlockLayoutItem.cs
src/Umbraco.Core/Models/Blocks/RichTextBlockValue.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/PropertyIndexValueFactoryTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/JsonBlockValueConverterTests.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/16184 fixed the `BlockValue` implementation when serializing/deserializing, but creating a new value still required you to use the correct property editor alias and layout item type. For example, it was easy to get the following wrong:
```c#
var blockListValue = new BlockListValue()
{
Layout =
{
// This won't store the layout, because it's not the correct one for BlockListValue
[Constants.PropertyEditors.Aliases.BlockGrid] =
[
// Even if the type got updated to BlockGridValue, this layout item shouldn't be allowed
new BlockListLayoutItem()
]
}
};
````
Although the CMS codebase only manually creates these values in tests, users might want to programmatically create them. One use case is the Deploy artifact migrators, e.g. if you want to …

DX: Add `BlockValue` constructors to force correct property editor alias and layout item type

---

src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs

We'll explode if you try to install while there are comments in the `appsettings.json`
To fix this I've added some `JsonDocumentOptions` to skip comments, unfortunately, this means that any comments will be removed, because they're not read in when manipulating the JSON. 
The reason for this is that since .NET Core 3.1 the `JsonDocument` and `JsonSerializer` do not support allowing comments, you'll just get an error if you try. 
The underlying reason is that the JSON spec does not support comments, and the dotnet team seems to feel very strongly about adhering to the spec, which is fair enough but means we cannot support having the comments in the app settings JSON document. For more information see the following discussion https://github.com/dotnet/runtime/issues/35251 (Warning: It's a …

V14: Add JsonDocumentOptions skipping comments in appsettings

---

src/Umbraco.Core/Services/IRedirectUrlService.cs

Fixes the `GetAllRedirectUrlManagementController` filter query parameter. 
This didn't work because the `SearchRedirectUrls` taking skip/take didn't use the `SearchRedirectUrls` with a search term, but just called get all
1. Crate a child content node
2. Rename the node to create a redirect. 
3. Ensure you can search for the redirect (the previous name)

V14: Fix redirect search

---

src/Umbraco.Cms.Api.Management/Controllers/User/UpdateUserGroupsUserController.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/AddUsersToUserGroupController.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/RemoveUsersFromUserGroupController.cs
src/Umbraco.Core/Services/IUserGroupService.cs
src/Umbraco.Core/Services/UserGroupService.cs

- Fixes the `umbraco/management/api/v1/user/set-user-groups`, as it did not know how to map success status code (we didn't check for succeed first)
- Refactored a few methods to use attempt so it lines up with the rest of the API 👍
- Use the `umbraco/management/api/v1/user/set-user-groups`, to set groups for a user
- It should now work

V14: fix user set user group endpoint

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddEditorUiToDataType.cs

The editor UI alias migration is flawed - it does not run unless there are custom property editors in the source (V13) database. The result is that a default V13 database is upgraded to V14 with _no_ editor UI aliases, which causes havoc in the UI.
This PR ensures that the migration _always_ runs.
As the flawed migration has already run on RC3, I have opted to re-run it during upgrade. Other than potential duplicate warning messages for any misconfigured/missing data types, it is entirely harmless to run the migration twice (in all likelihood there will be no warnings).
Create a blank V13 site and migrate it to V14. The data types should be migrated to have the correct editor UI aliases; if the data type icons show correctly in V14, the migration worked as it should.

Fix the editor UI alias migration and re-run it

---

src/Umbraco.Cms.Api.Management/Preview/IPreviewHub.cs
src/Umbraco.Cms.Api.Management/Preview/PreviewHubUpdater.cs
src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
src/Umbraco.Core/Configuration/Models/WebRoutingSettings.cs
src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/Routing/ContentFinderByIdPath.cs
src/Umbraco.Core/Routing/ContentFinderByIdentifierPathBase.cs
src/Umbraco.Core/Routing/ContentFinderByKeyPath.cs
src/Umbraco.Core/Services/PreviewService.cs
src/Umbraco.Core/Web/ICookieManager.cs
src/Umbraco.Infrastructure/Install/InstallHelper.cs
src/Umbraco.Web.Common/AspNetCore/AspNetCoreCookieManager.cs
src/Umbraco.Web.Common/Profiler/WebProfiler.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByIdentifierTestsBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByKeyTests.cs

- Updating SignalR Preview Hub to send Guid instead of int id;
- Make `UMB_PREVIEW` cookie HttpOnly so that we are able to make a request to the server from a client on a different host;
- Enable routing for the preview feature based on a Guid since we no longer expose integer ids by creating a new `ContentFinderByKeyPath`.
- Creating a base class for common logic between `ContentFinderByIdPath` and `ContentFinderByKeyPath`;
- Refactoring content finder tests.
- Make sure tests pass ✅ ;
- Enable preview mode and verify that `UMB_PREVIEW` cookie is HttpOnly (_see appendix*_)
- Create a simple content node with a template saying "Hello, World!";
- Find its int id and guid key.
- Verify that visiting `https://localhost:44339/<nodeKey>` and `https://localhost:44339/<nodeId>`:
- Resolves to …

V14: Backend changes to facilitate Preview mode in Bellissimma

---

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CreatedPackageSchemaRepository.cs

Fixes package creation. 
The first half was changed to use keys, however the `CreatedPackageSchemaRepository` tried to parse them as ints, leading to nothing being added to the package.xml
This PR fixes this by using guids instead. 
1. Try making a package with various entities, documents, templates etc. 
2. Check the package.xml and ensure the entities are present

V14: Fix package creation

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataType.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypeFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/LogViewer/LogViewer.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/CreatedPackages.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Language/Language.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialView.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialViewFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Script/Script.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Script/ScriptFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Stylesheet/Stylesheet.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Stylesheet/StylesheetFolder.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Template/Templates.spec.ts
tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Translation/Translation.spec.ts

With the current syntax, the tags are visible in the HTML report in the title as well as a label. This can be confusing and unclear.
So in this PR, I tried to apply new syntax for adding smoke tags to the tests.

V14 QA Apply new syntax for adding smoke tags

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AllowedAtRootDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AllowedChildrenDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AvailableCompositionDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CompositionReferenceDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ConfigurationDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CopyDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CreateDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DeleteDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/MoveDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/UpdateDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/AllowedAtRootMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/AllowedChildrenMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/CopyMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/CreateMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/DeleteMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/MediaTypeControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/MoveMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/UpdateMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/MemberTypeItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/User/Item/UserItemControllerBase.cs
src/Umbraco.Core/Models/UserExtensions.cs

- You could not browse various content nodes, if you only had access to the content section, as you did not have sufficient permissions to get doc types.
- This PR refactors these silos to ensure you can get content types even if you only have access to content section
- Also relaxes permissions on the item endpoint, as you only need to be logged in to access those
- Create a user with a start node
- Login as that user
- YOu should be able to browse that node

V14; Refactor permissions for Document/Media/Member

---

src/Umbraco.Cms.Api.Management/Preview/PreviewHubUpdater.cs

The preview hub sometimes throws an exception when upgrading a DB:
```
An unhandled exception has occurred while executing the request.
Umbraco.Cms.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
-> Umbraco.Cms.Core.Exceptions.BootFailedException: An error occurred while running the unattended upgrade.
The database configuration failed with the following message: One or more errors occurred. (No key is set for payload with id 0)
Please check log file for additional information (can be found in 'LoggingSettings.Directory')
```
I can't entirely put my finger on when and why, but it has to do with content cache refreshing at the end of the upgrade process:
This PR adds a little extra logic to the preview hub, so it strictly only …

The preview hub throws an exception during DB upgrade

---

src/Umbraco.Core/Services/ContentService.cs

- Implements suggestion from: https://github.com/umbraco/Umbraco-CMS/discussions/14034
- In short: Publishing notification was fired before validation, this has now been moved to afterwards. (As we only want to publish valid content)
- Follow steps from discussion

V13: Move publishing notification after validation

---

src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs

Fixes routing when a string parameter is used
This was caused by #16218 not considering invalid candidates
Fixes #16332 and #16341 
Teting: 
Create a site with a URL with more than one segment I.E
* Root
* Child
* Grandchild
Add an attribute routed endpoint with a string I.E.: 
```
[HttpGet("sitemap-{group}-xml")]
public IActionResult AttributeRoute(string group)
{
_logger.LogInformation("Got request: {GroupValue}", group);
return Ok();
}
```
Ensure you can request both `/child/grandchild` and  `/sitemap-something-xml`

V13: Fix routing with string parameter

---

src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs

This PR ensures the `UmbracoRouteValueTransformer` is used if the request contains the `ufprt` in query string
More details here: https://github.com/umbraco/Umbraco-CMS/issues/16332

Ensure ufprt-token requests are handle in the UmbracoRouteValueTransformer

---

src/Umbraco.Web.UI.Login/src/auth.element.ts

The login username/email field should have autofocus.
This field will be automatically focused when the user sees the login screen, and it should be valid according to a11y best practices as this is the first and main element on the page ([source](https://www.boia.org/blog/accessibility-tips-be-cautious-when-using-autofocus)).
Fixes #16276

V14: login should autofocus

---

src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/FolderMediaTypeItemController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Core/Services/ContentTypeEditing/IMediaTypeEditingService.cs
src/Umbraco.Core/Services/ContentTypeEditing/MediaTypeEditingService.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.GetFolderMediaTypes.cs
tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj

This adds a new endpoint for retrieving the media types that are considered "folder" media types.
A "folder" media type has the following characteristics:
1. It has no "umbracoFile" property.
2. It has allowed child content types.
For backwards compatability however, the system "Folder" media type should _always_ be considered a "folder" media type, no matter if it does match the characteristics above.
Use Swagger to test the new endpoint:
- In a default install, the endpoint should yield only the system "Folder" media type.
- If you add more media types that match the above-mentioned characteristics, the endpoint should include these.
- If you change the "Folder" media type so it does not match the expected characteristics, it should still be included in the endpoint output.

Add endpoint for retrieving "folder" media types.

---

src/Umbraco.Cms.Api.Management/Controllers/DataType/Item/DatatypeItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Item/DictionaryItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Item/DocumentItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentBlueprint/Item/DocumentBlueprintItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/DocumentTypeItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Language/Item/LanguageItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/MediaItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/MediaTypeItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Member/Item/MemberItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/Item/MemberGroupItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/PartialView/Item/PartialViewItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/RelationType/Item/RelationTypeItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Script/Item/ScriptItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Item/StylesheetItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Template/Item/TemplateItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/UserGroup/Item/UserGroupItemControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Webhook/Item/WebhookItemControllerBase.cs

The point of the "item" endpoints is to have a representation of any item that is accessible to anyone - much like the "entity" endpoint in V13.
As a follow-up to https://github.com/umbraco/Umbraco-CMS/pull/16310, this PR removes all access restrictions from all "item" endpoints - except of course that you have to be a back-office user to access them 😄 
Verify that you can access any "item" endpoint. Or, in other words, if the API still works, nothing broke 👍

The "item" endpoints should be accessible for all users

---

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs

The default listviews are not created correctly - they still use the V13 format 🤦 this PR fixes them.
Initialize a fresh DB and verify that the list views have the correct view components listed in the backoffice UI:

Make sure listviews are initialized correctly in a new DB

---

src/Umbraco.Cms.Api.Management/Factories/DataTypeReferencePresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeContentTypeReferenceModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeReferenceResponseModel.cs

🚨 **Do not merge this until the client is ready** 🚨 
The datatype references output is very limited. If it is to be utilized as-is, it will require a lot of additional API requests to create meaningful UI on top.
The corresponding references outputs for document and media types have been enriched with these data, so it seems fitting to do it for datatypes also.
**NOTE:** The `type` property in the datatype references output has moved into the new `contentType` property.
Fetch references for a datatype that is used on a doc/media/member type. Verify that the new output format contains the doc/media/member type name and icon.

Enrich the datatype references output with content type data

---

src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyValueEditor.cs

This PR fixes an issue with the FileUpload when used on documents, it could only save, but not publish.
The reason is because the value from the DB is just the path and we did not handle that case when doing validation before publish.
- Verify you can create a document type with a file upload property editor and publish that document

Fix issue when FileUpload exists on a document, it cannot publish

---

src/Umbraco.Cms.Api.Management/Mapping/Manifest/ManifestViewModelMapDefinition.cs
src/Umbraco.Cms.Api.Management/ViewModels/Manifest/ManifestResponseModel.cs
src/Umbraco.Core/Manifest/PackageManifest.cs
src/Umbraco.Core/Services/IPackagingService.cs
src/Umbraco.Core/Telemetry/TelemetryService.cs
src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ReportSiteJob.cs
src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/TelemetryServiceTests.cs

PR https://github.com/umbraco/Umbraco-CMS/pull/15744 removed the legacy package manifest parser, but also removed the code from `PackagingService` that returned the combined the package migrations _and manifests_. This data is used in the telemetry service to report the installed packages (if the consent level of the installation is set to Basic or Detailed and the package hasn't opted-out), which is mainly used in the Marketplace to sort the packages by most active installs.
Another important detail that was missing, is being able to specify the (NuGet) package ID in the manifest, so the Marketplace can do a 1:1 match when aggregating the data.
Besides re-introducing the package manifests as installed packages and adding the package ID, I've ensured the ID is also exposed in the …

Include umbraco-package.json manifests in telemetry data

---

src/Umbraco.Core/Services/FileServiceOperationBase.cs

- If the file name contains `/`, it is invalid, as we do have `parenpath`, it would make no sense to have a `/` in a filename
- call the `umbraco/management/api/v1/script` endpoint with:
```
{
"name": "hell/o.js",
"content": "<string>"
}
```
- This should now yield a `InvalidName` error, not a `ParentNotFound` error

v14: Validate file name to return correct error

---

src/Umbraco.Core/Events/AddDomainWarningsWhenPublishingNotificationHandler.cs
src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs

This PR adds a `Umb-Notifications` header when publishing variants without a domain.
- Setup two languages
- Create document type that vary by culture. Allow in root and as child of itselves
- Create a document of that type
- Create a child with the same name on two langauges (Thereby the url should conflict)
- Verify the `Umb-Notification` header is added

Added a Notification warnings when publishing variants without a domain

---

src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs

Handle the case, where a master template (layout) is references that do not exist.
Before
after
- Create a template and reference a master that do not exist

Handle master template not found as bad request

---

src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts

Fixes #15686 (was originally fixed in 2022/2023)
See issue for detailed info and how to reproduce.
Looks like while implementing the new login screen a typo was made that means the redirect url is never carried on.
There is however another part to this: in some situations when you try to directly go to a protected backoffice page (e.g. `/umbraco#/settings`) while not being logged in and not using basic authentication as in the issue, you are redirected to the login page but without the `returnPath` query parm. The redirect itself is done here https://github.com/umbraco/Umbraco-CMS/blob/v13/contrib/src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs#L141 but I'm not sure how/where the hash part of the query is carried on on the client.

Respect backoffice login returnPath regression

---

src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs

Fixes a bug where the ValueSetValidator is null which will cause a NullReferenceException.
When creating a custom index based on Umbraco content/media via this code:
```cs
services.AddExamineLuceneIndex<UmbracoContentIndex, ConfigurationEnabledDirectoryFactory>("TestIndex");
```
It will mean that this index's `LuceneDirectoryIndexOptions.ValueSetValidator` will be null and when rebuilding the index, a null reference exception will occur.
To resolve this, it is required that an explicit value set validator is applied to the options, like:
```cs
public class LuceneEditorialIndexOptions : IConfigureNamedOptions<LuceneDirectoryIndexOptions>
{
private readonly IUmbracoIndexConfig _umbracoIndexConfig;
public LuceneEditorialIndexOptions(IUmbracoIndexConfig umbracoIndexConfig)
{ …
```

Fixes a NullReferenceException bug when the ValueSetValidator is null

---

src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderApiExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16516
- Adds registration to management API aswell
- Adds check to see if we have already registered, to not register again
- Remove `.AddDeliveryApi()` from `Program.cs`
- Program should be able to run

V14: Add required dependency to management api

---

.github/BUILD.md

**Before**
- Try with an older git version.
- In my case, it was git version - 2.32.0.windows.2
**After**
- Works with any git version
- Submodule path 'src/Umbraco.Web.UI.Client': checked out

Added "git submodule update --init" command to the documentation

---

src/Umbraco.Core/DeliveryApi/ApiMediaUrlProvider.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextElementParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextParserBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ApiMediaUrlProviderTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs

If there's an existing issue for this PR then this fixes #16416
As described in #16416, the Delivery API outputs different media routes for the media picker and medias in RTE. This PR ensures that:
1. Media picker and RTE uses the same implementation (`IApiMediaUrlProvider`) to calculate media routes in the Delivery API.
2. The Delivery API respects `WebRoutingSettings.UrlProviderMode`.
Given a document with a media picker and an RTE (with a media inside), verify that the Delivery API output:
1. Contains the same media route (URL) for both properties.
2. Respects `WebRoutingSettings.UrlProviderMode` - e.g. setting it to explicitly render absolute URLs.
3. Also works when outputting RTE as JSON.
This PR is behaviourally breaking. But the current behaviour is a bug - it should not behave …

RTE and media picker should route medias the same way in the Delivery API

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Create.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16502
- Adds new OperationStatus to give clearer error, when you have the same property type alias, as the doc type alias.
- Create a document type
- Add a property with the same alias as the content type
- You should now see a better error, telling you that it cannot have the same alias as the doc type

V14: Add clearer error for invalid property type

---

src/Umbraco.Cms.Api.Management/Mapping/HealthCheck/HealthCheckViewModelsMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckActionRequestModel.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16477
- Adds missing mapping for `ActionParameter`, I suspect this mapping was missing, because we had trouble mapping Dictionary<string, object> earlier on in the development process.
- Implement the following healthcheck:
```
using Umbraco.Cms.Core.Extensions;
using Umbraco.Cms.Core.HealthChecks;
[HealthCheck("3A482719-3D90-4BC1-B9F8-910CD9CF5B32", "Tests the healthchecks",
Description = "Runs a tests of the healthchecks for a PR", Group = "TestingGroup")]
public class HealthCheckNotifier : HealthCheck
{
private readonly IHostEnvironment _hostEnvironment;
private readonly ILogger<HealthCheckNotifier> _logger;
private readonly ILocalizedTextService _textService;
public …
```

V14: Add missing action parameters mapping

---

src/Umbraco.Core/Routing/IPublishedRouter.cs
src/Umbraco.Core/Routing/PublishedRouter.cs
src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs
src/Umbraco.Web.Common/Routing/UmbracoVirtualPageRoute.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasWithDomainsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlWithDomainsTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/DomainsAndCulturesTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UrlsWithNestedDomains.cs

Fixes #16555.
Following #16218 `VirtualPageController` requests no longer hit the `UmbracoRouteValueTransformer`. This had the side effect that the request culture was no longer properly set in the `VariationContext` and `PublishedRequest`.
To fix this I've: 
* Split `FindDomain` into `FindDomain` and `FindAndSetDomain`
* This allowed me to create two new methods: `RouteDomain` and `UpdateVariationContext`
* Call `UpdateVariationContext` before `FindContent` is invoked, ensuring that the variation context is correctly configured for finding the content 
* Call `FindDomain` to ensure the `PublishedRequest` and `VariationContext` have the correct cultures configured. 
Configure a virtual page controller like in the issue, and ensure that the culture specified in the domains is set …

V13: Set request culture for VirtualPageController

---

src/Umbraco.Cms.Api.Common/DependencyInjection/ProcessRequestContextHandler.cs
src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs

OpenIddict performs initial request context processing for every last request to the server - including front-end requests. While this handling is not terribly costly, there really is no reason for it unless a `/umbraco/` request is in progress.
1. First and foremost, the backoffice should work as per usual 😄 
2. Enable verbose logging and verify that the OpenIddict request processing is only invoked for `/umbraco/` requests.
3. Setup [member auth](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api) for the Delivery API and verify that this still works.
Particularly the last point is a little tricky to get right. Get in touch with @kjac for a pair testing session 👍

OpenIddict should only handle `/umbraco/` requests

---

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tour/tours.spec.ts

The tours test run for quite a bit of time since there are a lot of steps involved. We are updating the retry count to 1 as it could result in failing the E2E stage on the pipeline.

V13 QA Decreased to 1 retry for the tour file 

---

src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Handlers/RevokeUserAuthenticationTokensNotificationHandler.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/User/AllowedApplicationHandler.cs
src/Umbraco.Cms.Api.Management/Security/Authorization/User/AllowedApplicationRequirement.cs
src/Umbraco.Core/Constants-Security.cs
src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
src/Umbraco.Core/Models/UserExtensions.cs
src/Umbraco.Core/Services/UserGroupService.cs

We're currently challenged by our claims and how they're tied to the tokens. Specifically, whenever we change something on a user or a user group, we need to revoke all issued tokens. But we won't revoke admin tokens, because we don't want to risk logging the current admin out.
This PR addresses these challenges by obsoleting the claims for user start nodes and "allowed apps" (sections). These are now resolved directly from the user instance, not from the token bound claims.
Eventually these claims will be removed. There will be a separate announcement for this, as it is potentially quite breaking for some.
We _could_ in principle also remove the role claims (`ClaimsIdentity.DefaultRoleClaimType`). At this point I'm a little weary about doing that, though. 
In effect this means an access …

Do not rely on claims to figure out user access + prepare for claims removal

---

src/Umbraco.Cms.Api.Common/Configuration/PostConfigureOpenIddict.cs
src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs

Added post configuration of OpenIddictServerOptions that removes the `ValidateTransportSecurityRequirement` iff `GlobalSettings.UseHttps` is `false`.
Fixing: https://github.com/umbraco/Umbraco-CMS/issues/16605
Please note that openiddict only allow connections from the host that first attempted to access backoffice. It can make it easier to set `launchBrowser` to `false` in `launchSettings.json`
- Set `Umbraco:CMS:Global:UseHttps` = `false`
- Boot solution and verify you **_can_** sign-in using http: http://localhost:11000/umbraco/
- Reboot solution and verify you _**can**_ sign-in using https: https://localhost:44339/umbraco/
- Set `Umbraco:CMS:Global:UseHttps` = `true`
- Boot solution and verify you **_cannot_** sign-in using http: http://localhost:11000/umbraco/
- Reboot solution and …

Allow http for openiddict

---

src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs

Fixes #16626 
This was caused because the `Thread.CurrentThread.CurrentUICulture` is set by `UmbracoPublishedContentCultureProvider` which runs before any of the filters, meaning that `CurrentUICulture` was never set correctly, so to fix this I've made the `EagerMatcherPolicy` detect if it's a `UmbracoPageController` and then do the domain routing and setting a dummy `UmbracoRouteValues` which is then used to assign the correct `CurrentUICulture` by the `UmbracoPublishedContentCultureProvider`.

V13: Eaglery route domains for virtual page controllers

---

tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs

In order to use `UmbracoTestServerTestBase` with view files outside the test project, we need to be able to customize the `IMvcBuilder` setup. This addition opens up the setup so that the builder can be modified during setup.
For instance:
I would love for this to be backported to 13 as well.
(Here's to hoping all the bugs aren't found yet)

Add custom mvc setup method to testserver base class

---

src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderApiExtensions.cs
src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/LocksTests.cs
tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreLockTests.cs

No known existing issue that I could find.
This PR updates the calls to ServiceDescriptor.ImplementationType by checking IsKeyedService first.
Currently, if you register a keyed service before UmbracoBuilder does its work, you'll get an exception like below (running the ComponentRuntimeTests.Start_And_Stop_Umbraco_With_Components_Enabled test):
```csharp
System.InvalidOperationException : This service descriptor is keyed. Your service provider may not support keyed services.
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.ThrowKeyedDescriptor()
at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.get_ImplementationType()
at …
```

Fix unguarded calls to ServiceDescriptor.ImplementationType for keyed services

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js

Checking the [focusabeElements](https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js#L49) object it contains the following fields:
I didn't see any `parent` field, so used the `parentElement` instead.
This fixes #16256

Use parentElement instead of parent

---

src/Umbraco.Cms.Api.Management/Controllers/User/CalculateStartNodesUserController.cs
src/Umbraco.Cms.Api.Management/Factories/IUserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/User/CalculatedUserStartNodesResponseModel.cs

We need to list the effective user start nodes (directly applied to the user + inherited via group membership). Instead of cluttering the existing "get user" endpoint, I have decided to add a new endpoint for this calculation.
First and foremost, be aware that we have a few caching issues with users and start nodes (see https://github.com/umbraco/Umbraco-CMS/pull/16552). When making chances to user start nodes, the only really reliable way to have these reflected is currently to restart the site.
1. Create some users with different start node setups - both direct and inherited.
2. Verify that the effective start nodes are calculated correctly with this new endpoint.

Add endpoint for calculating effective user start nodes

---

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateRichTextConfiguration.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16579
- Seems that in v14, we have changed the source code editor in the toolbar, so now the alias is "sourcecode" instead of "ace"
- This PR changes the default when installing to sourcecode
- Also creates a migration to migrate the "ace" value to "sourcecode", so it again will show after migrating 👍 
- Fresh install
- Create a document type with the default rich text editor (allow as root).
- Create some content with that document type
- Assert that the source code editor now shows.

V14: Fix source code editor not showing on fresh install / upgrade

---

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
src/Umbraco.Core/Media/EmbedProviders/Twitter.cs
src/Umbraco.Core/Media/EmbedProviders/X.cs

- Fixes: #16645
- Create a doc type with RTE;
- Make sure you have "**Embed**" option included in the toolbar.
- Create a content node from that document type;
- Insert an embedded media by clicking on the "**Embed**" button in the RTE;
- Verify that both `https://x.com/SpaceX/status/1732824684683784516` and `https://twitter.com/SpaceX/status/1732824684683784516` render;

V13: Update url scheme for Twitter OEmbedProvider

---

src/Umbraco.Cms.Api.Management/Middleware/BackOfficeAuthorizationInitializationMiddleware.cs

Use the application url from configuration to initialise openiddict. If it is not available, it will fallback to the requested path (like before)
This fixes issues where umbraco is behind a proxy.
Fixes #16179
- Ensure login works with the configured application url
- Ensure login works without a configured application url

Use configured backoffice route if available

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_1_0/MigrateOldRichTextSeedConfiguration.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_1_0/MigrateRichTextConfiguration.cs

There is a chance that a seeded RTE datatype configuration from the early days of v13 (or before) was never touched and thus its configuration data never upgraded to a newer format. This results in new backoffice not being able to read that configuration and simply not display a toolbar, when editing the configuration all checkboxes for the different tools are unchecked.
This PR introduces a migration that looks for that exact seed value and relaces it with the value that a newly created default RTE datatype would have.
- Create a new v13 project, add a document type with the default RTE datatype and add some content for good measure
- Update the project to v14 => when editing the content, the RTE toolbar should be visible
- Custom RTE's from v13 with other options should not be affected, …

[V14] Fix old rte seed value causing the toolbar not to appear

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingService.cs
src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
src/Umbraco.Core/Services/IContentTypeServiceBase.cs
src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16711
- Separates `SaveAsync` into Create & Update on the `src/Umbraco.Core/Services/IContentTypeServiceBase.cs`
- This also makes it, so we can return better ContentTypeOperation statuses.
- Follow steps in original issue 🧪

V14: Create seperate Create and Update in ContentTypeServiceBase

---

build/azure-pipelines.yml

Automates the build and publication of the typedoc docs available at https://apidocs.umbraco.com/v14/ui-api/
A successful run can be seen here: https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=172681&view=results
With the artifact published as [ui-api-docs](https://artprodsu6weu.artifacts.visualstudio.com/A1efe4343-f52d-4f92-995c-ba5b2f46070d/0fe81d3e-adbd-40f4-af17-796887948029/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3VtYnJhY28vcHJvamVjdElkLzBmZTgxZDNlLWFkYmQtNDBmNC1hZjE3LTc5Njg4Nzk0ODAyOS9idWlsZElkLzE3MjY4MS9hcnRpZmFjdE5hbWUvdWktYXBpLWRvY3M1/content?format=file&subPath=%2Fui-api-docs.zip).

V14: Build and publish Typedoc docs

---

src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextElementParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextParserBase.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParserTests.cs

The new backoffice has removed UDI notation from the locallinks format in RTE <a> tags and split up the type and key into 2 attributes (href and type).
The backend was not fully updated and so when rendering the content trough razor pages, or retrieving trough the content delivery api, the locallink notation was not properly replaced by the actual content/media urls.
This PR aims to fix this and update/improve the unittests along the way.
The old format was not migrated to the new format in the v14 migration and this is currently not changing as the backend can handle both.
Consider both RTEs on a document type and RTEs in block
Both migrated and new data should work as expected
Both Razor rendering and delivery api parsing should create similar output when comparing v13 and v14 data, …

[V14] Make the backend work with the new localLinks format

---

src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
src/Umbraco.Cms.Api.Management/Routing/BackofficeHub.cs
src/Umbraco.Core/Constants-Web.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/BackOfficeAreaRoutesTests.cs

- This PR implements a new SignalR hub for the backoffice, with route `/umbraco/backofficeHub`
- This is basically just a relay hub, that takes in a message, and sends it to all current connections. We could in the future implement `OnConnect` & `OnDisconnect` to notify clients that they are in offline mode.
- Unpack the following in your wwwroot folder
[js.zip](https://github.com/user-attachments/files/16052321/js.zip)
- Run umbraco
- Create a doctype with a template, remember to allow as root
- In the template, paste the following:
```
@{
Layout = null;
}
<div class="container">
<div class="row p-1">
<div class="col-1">User</div>
<div class="col-5"><input type="text" id="userInput" …
```

v14: Implement backoffice signalR hub

---

src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs

Adds the `Umb-Notifications` HTTP header to the `"Access-Control-Expose-Headers"` list.
This is to enable the client-side development environment to access the custom `Umb-Notifications` HTTP header.

V14: Expose `Umb-Notifications` HTTP header

---

src/Umbraco.Cms.Api.Management/Controllers/Relation/ByRelationTypeKeyRelationController.cs
src/Umbraco.Cms.Api.Management/OpenApi.json

It was noticed that in the [OpenAPI.json (Swagger) file](https://github.com/umbraco/Umbraco-CMS/blob/release-14.0.0/src/Umbraco.Cms.Api.Management/OpenApi.json), there were two `operationId` values for `"GetRelationTypeById"`.
1. https://github.com/umbraco/Umbraco-CMS/blob/release-14.0.0/src/Umbraco.Cms.Api.Management/OpenApi.json#L23186
2. https://github.com/umbraco/Umbraco-CMS/blob/release-14.0.0/src/Umbraco.Cms.Api.Management/OpenApi.json#L23246
Given that the `operationId` value should be unique across the OpenAPI spec file, one of these endpoints would need to be named explicitly.
I have opted to rename 
[`ByRelationTypeKeyRelationController.ByRelationTypeKey`](https://github.com/umbraco/Umbraco-CMS/blob/release-14.0.0/src/Umbraco.Cms.Api.Management/Controllers/Relation/ByRelationType …

V14: OpenAPI: Explicitly set `ByRelationTypeKey` endpoint name

---

src/Umbraco.Infrastructure/Serialization/JsonObjectConverter.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/16587.
Although [I initially thought](https://github.com/umbraco/Umbraco-CMS/issues/16587#issuecomment-2194236383) the CMS data type configuration migration (executed when upgrading v13 to v14) caused Deploy to write updated UDA files, it is actually due to the `JsonObjectConverter` (that's used by the `IConfigurationEditorJsonSerializer` for reading and writing data type configuration) not correctly parsing `DataTimeOffset` values.
This custom JsonConverter takes care of deserializing JSON values into `object` instances to their simple/primitive types (boolean, integer, date or string), instead of a boxed `JsonElement` (see https://learn.microsoft.com/en-us/dotnet/standard/serialization/ …

Support JSON parsing object to DateTimeOffset and preserve timezone offset in `JsonObjectConverter`

---

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ConfigurationDocumentTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MediaType/ConfigurationMediaTypeController.cs
src/Umbraco.Cms.Api.Management/Controllers/MemberType/ConfigurationMemberTypeController.cs
src/Umbraco.Cms.Api.Management/Factories/ConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/IConfigurationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypeConfigurationModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberConfigurationResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/MemberType/MemberTypeConfigurationResponseModel.cs

Moves the `ReservedFIeldNames` property into configuration endpoints for Document, Media, and Member, since these are required when creating the type, not the entity. 
Request the endpoints and ensure they work

Move ReservedFieldNames to type configuration endpoints

---

src/Umbraco.Web.UI/Properties/launchSettings.json

- Keeping `"launchBrowser"` setting consistent with v13 -> `true`.
- Verify that when running the **Umbraco.Web.UI** project, the browser is launched automatically.

V14: Launch browser settings to true

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstep.directive.js

Fixes #16742
This reverts one of the changes made in #15133, where the `inert` attribute was added when a Tour is active. This caused a few issues where:
- The `close` code was never called for the "email marketing" tour causing Cloud sites to be unresponsive until you refresh
- The "getting started" tour did not work on the steps, where you are supposed to click a button in the Backoffice UI
I think the `inert` attribute is useful in some cases where there is no "click-through" in a tour step, but we will have to be more clever about when to place it and when to remove it again.

V13: Tours prevent you from interacting with the Backoffice on first log in

---

src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs

- Fixes #16589;
- We chose to add an overridable property for the special index value transformations that we check for, so we don't break any custom indexes deriving from `UmbracoExamineIndex`;
- The`DeliveryApiContentIndex` overrides it to `false` and that way we ensure the `TransformingIndexValues` event is also raised for the `DeliveryApiContentIndex` - "_You can use this event to add additional field values or modify existing field values._" ([Examine docs](https://shazwazza.github.io/Examine/articles/indexing.html#iindextransformingindexvalues)).
> On `v13/dev`
1. Enable the Delivery API is **appsettings.json**:
```json
{
. . .
"Umbraco": {
"CMS": {
"DeliveryApi": {
"Enabled": true
},
. . .
}
```
2. Create some content;
3. In the Settings section > Examine Management > …

V13: Ensure `TransformingIndexValues` event is also raised from the `DeliveryApiContentIndex`

---

src/Umbraco.Cms.Imaging.ImageSharp/ConfigureImageSharpMiddlewareOptions.cs

Fixes #16768, please see the issue for all details.

Configure ImageSharp WebP encoder to use Lossy by default

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Index.cshtml
src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
src/Umbraco.Web.UI.Login/index.html
src/Umbraco.Web.UI.Login/public/user-defined.css

These files intended that we would place them in the StaticAssets RCL and developers could overwrite them in their projects.
We need to devise a different way to do this as you cannot just overwrite assets in an RCL.

V14: Remove user-defined.css

---

src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs
src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs

V14: Merge

---

src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs
src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParser.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParserTests.cs

This is a follow up on https://github.com/umbraco/Umbraco-CMS/pull/16661 to remove the internal `type `attribute from the parsed local links.
Same test steps apply

Removed Type attribute from parsed local links

---

src/Umbraco.Core/Constants-HealthChecks.cs
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/HealthChecks/Checks/LiveEnvironment/RuntimeModeCheck.cs

I thought it might be a good idea to add a health check to make sure the runtime mode is set to Production. 😄

Add Health Check for Runtime mode

---

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidator.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs
src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/16757
This update makes the block editor base classes public in order to allow for external package developers to also create custom block editors. This is necessary for Umbraco Commerces variants property editor which is also a block based editor.

Make block editor base classes public

---

src/Umbraco.Cms.Api.Delivery/Controllers/Security/MemberController.cs

When the client scope is set to "openid offline_access", the returned scope only has the "offline_access" scope. The "openid" scope and the "id_token" are missing. By combining the OpenId and OfflineAccess as return scope, the refresh_token and id_token are returned.
This change checks if the OpenId and/or OfflineAccess scope is set and combines them.
To test I've used the Client app of this repro from Jeroen Breuer: https://github.com/jbreuer/UmbracoDeliveryApiAuthDemo
Change https://github.com/jbreuer/UmbracoDeliveryApiAuthDemo/blob/a799b307302f7189d7ddd69b9554ae2b24612eb4/src/Client/src/App.js#L22 to `const scope = 'openid offline_access';`
Copy the "OpenIdConnect" section in the appsettings.json to your own installation.
The …

Combining OpenId and OfflineAccess scope

---

src/Umbraco.Cms.Api.Management/Security/Authorization/User/AllowedApplicationHandler.cs
src/Umbraco.Core/Security/Authorization/AuthorizationHelper.cs
src/Umbraco.Core/Security/Authorization/IAuthorizationHelper.cs

#16552 has had the unfortunate side-effect that exceptions are being thrown by the `AllowedApplicationHandler`, whenever a request is made to an endpoint that is guarded by this handler ("section" based access), resulting in a 500 error instead of the expected 401:
This PR changes `AllowedApplicationHandler` so it doesn't assume a logged-in user by default.
1. Make an _unauthorized_ request to any endpoint that requires "section" access (e.g. to `/umbraco/management/api/v1/tree/data-type/root?skip=0&take=100`) and verify that the response is a 401.
2. Log into the backoffice and make sure things still work 😄

Graceful handling of unauthorized requests to the Management API

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_7_0/MigrateTagsFromNVarcharToNText.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/UseNvarcharInsteadOfNText.cs

This PR updates 2 existing migrations to be more performant. Both Cloud and heartcore have had issues with timeout regarding these performances.
The Heartcore team made a workaround (pre migration) on which these changes are based.
**v12 migration**
A result differential has been performed between the old and new migration with a large production copy database. No differences were found in the result.
**v10 migration**
A large amount of nodes with tags were generated, the differential again showed no differences in the result.
**note**
Testing should be done against a Sql-Server DB.

Improve migration performance

---

src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs

Fixing regression bug introduced in #14806 and found during investigation of #16803 - well tested on db with 300k+ nodes
Fixing regression bug introduced in #14806 and found during investigation of #16803 - well tested on db with 300k+ nodes
Please consider merging this PR as a quick fix for bug introduced in the #14806 by @Zeegaan.
There is lack of the WHERE clause in the sql count queries.
It has massive impact on publish/unpublish operations in Umbraco instances with huge amount of content.
In our case it's not possible to use the CMS by editors after upgrading to the 13.4.1.

Fixing regression bug introduced in #14806

---

src/Umbraco.Cms.Api.Common/DependencyInjection/ProcessRequestContextHandler.cs

Somewhere between 14.0 and 14.1, our .well-known endpoint for OpenID (/.well-known/openid-configuration) has gone missing. We need it back.
- Request https://localhost:[port]/.well-known/openid-configuration
It should return something like ![image](https://github.com/user-attachments/assets/57b1edf9-75f6-4627-a530-d2667b70afe0)
- Make sure the backoffice requests are still working and openiddict is processing them (see console output)
- Make sure frontoffice requests are still working and openIddict skips them (see console output)

Fix: .well-known/openid-configuration doesn't work anymore

---

templates/Umbraco.Templates.csproj

Following a discussion about websites accidentally appearing in Google with an Umbraco favicon, I noted that Umbraco's dotnet templates automatically include this.
It's something I see time and again on our own + inherited projects, that people don't realise there is a default favicon.ico file shipped within the template. This makes it very easy to overlook and deploy a new Umbraco site with the Umbraco logo as a favicon.
I can't really see any good reason for this, other than for the wwwroot folder to appear in the project... which there must surely be better ways of doing!
This change seems like it could be backported to v13 also without any issues 🤞

Remove favicon from dotnet templates

---

src/Umbraco.Cms.Api.Management/Factories/UserGroupPresentationFactory.cs

When a language is deleted and that language was set as allowed languages on one of the user groups of the current user, then the Backoffice client can no longer load due to /user/current throwing an error.
- Perform a default (unattended) install
- Login with the admin
- Add a language
- Set this language as the allowed language of the admin user group
- Delete said language
- Refresh the client => All should be fine

FIX: Deleting language can make the backoffice client unusable

---

src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDomainsController.cs
src/Umbraco.Core/Services/DomainService.cs
src/Umbraco.Core/Services/OperationStatus/DomainOperationStatus.cs
tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UrlAndDomains/DomainAndUrlsTests.cs

Do not allow creation of invalid domains when assigning hostnames to documents. They will fail hard later anyway.
- Ensure you can create valid domains, both absolute and relative
- Ensure you cannot create invalid domains

Do not allow save of invalid domains

---

src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj

Fixes vulnerability in Nuget dependency by upgrading to a newer version

Upgrade imagesharp2 dependency

---

src/Umbraco.Core/Constants-HealthChecks.cs
src/Umbraco.Core/EmbeddedResources/Lang/en.xml
src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
src/Umbraco.Core/HealthChecks/Checks/Security/CspCheck.cs

Added a health check to see if a CSP header is present.
When present:
If not:
This can be tested by adding a CSP header and running the health checks:
```csharp
app.Use(async (context, next) =>
{
context.Response.Headers.Append("Content-Security-Policy", "default-src 'self' www.gravatar.com; script-src 'self' 'unsafe-eval' code.jquery.com ajax.aspnetcdn.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: i.ytimg.com dashboard.umbraco.com; font-src 'self' data:; connect-src 'self'; media-src 'self'; frame-src 'self';");
await next();
});
```

Add Content-Security-Policy (CSP) health check

---

src/Umbraco.Core/Extensions/ObjectExtensions.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/DatePickerValueConverter.cs
tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/ObjectExtensionsTests.cs

If there's an existing issue for this PR then this fixes #16795 (and #16779)
The `DateTimeOffset` parsing added in #16732 is the root cause of both #16795 and #16779. #16779 was fixed by a client-side change in the 14.1.1 patch, but #16795 still happens in that patch.
By the looks of it, any "date without time" property value saved before 14.1 will not work in 14.1 and 14.1.1 😱 
This PR fixes the problem at server level by:
1. Handling `DateTimeOffset` > `DateTime` conversion and vice versa for `object` types.
2. Making the value converter for the Date property editor more resilient.
Unit tests have been added to guard against this issue later on.
1. Create a V13 site.
2. Create some content with:
- A "date without time" and a "date with time" property at content root level.
- A block …

Fix date conversion on the server-side

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_2_0/AddMissingDateTimeConfiguration.cs

In V13 (and below), the default "Date Picker with time" data-type _seems_ to have a stored configuration:
But in fact, this is just a default value on the server-side implementation of `DateTimeConfiguration`:
The database contains no configuration data for ID -36 (`Constants.DataTypes.DateTime`):
This works in V13, but not in V14, because the V14 UI honours the fallback/default behavior mentioned on the data-type configuration:
In effect, this means that unless the default "Date Picker with time" has been explicitly saved in V13 (and thus the configuration has been persisted in the database), any upgraded "Date Picker with time" property will no longer have the time UI in V14 - they will appear and function as plan date editors.
The content property data, however, still contains the time …

Add the default date-with-time configuration if missing

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js

Since the merge of issue [#15115](https://github.com/umbraco/Umbraco-CMS/pull/15115), uploaded items are not selected anymore. 
Steps to test: 
* Create an Media Picker (Pick multiple items should be off) and upload an image into the media picker. 
Latest uploaded file should be selected.
With the option "Pick multiple items" no item is selected, but this functionality did not do this before the bug was introduced either. That is why no change has been made to this behaviour.
Extra remark:
issue [#15115](https://github.com/umbraco/Umbraco-CMS/pull/15115) does not appear to have resolved the problem either. I can still produce the bug.

fix: uploaded item not selected in media picker

---

src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/blocks/umb-rte-block.component.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15516

V13: fix 15516

---

src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Infrastructure/Events/RelateOnTrashNotificationHandler.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16876
- Fixes the delete to now display the deleting user, instead of always the super user 😁

V14: Don't duplicate audit loggin for media trashing

---

src/Umbraco.Cms.Api.Management/Controllers/Document/GetAuditLogDocumentController.cs

- Fixes an issue, where if a user only had access to content section and browse node permission, it would still throw an error, as audit log would fail to authenticate
- This PR fixes that issue, by using the `Browse` action letter instead of the `Protect`
- Create some content in the content section (Use a doc type with allow as root, with no properties)
- Create a user group with access to only the content section and only browse permission
- ( I did this by changing the editor user group, disabling all permissions except for browse)
- Create a user, that is part of the user group.
- Login to the user
- Navigate to the content you created in step 1, this should no longer throw errors

V14: Align permissions for audit log

---

src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs

Issue:
[#15712](https://github.com/umbraco/Umbraco-CMS/issues/15712)
Description:
UserDefaultLockoutTimeInMinutes was wrongly used instead of MemberDefaultLockoutTimeInMinutes to configure lockout time.
Testing:
enter wrong password needed amount of times to be locked out, and you will be locked out on UserDefaultLockoutTimeInMinutes amount of minutes without this fix.

Fix for MemberDefaultLockoutTimeInMinutes lockout time

---

src/Umbraco.Web.Common/UmbracoHelper.cs

Fixes #15765
The current implementation only allows for one culture dictionary to be cached at a time. This would result in the cached culture dictionary being whatever the last culture you requested was, which would have confusing results. This new implementation allows for caching all cultures.
- Create a site with two or more cultures
- Add some dictionary items
- Add the following to your view 
```
@Umbraco.GetDictionaryValue("Key")
@Umbraco.GetDictionaryValue("Key", CultureInfo.GetCultureInfo("your-other-culture"))
@Umbraco.GetDictionaryValue("Key")
```
- Observe that the values are for the correct culture

Cache a dictionary of dictionaries

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateTours.cs

#16817 introduced the "User type" as a new property on `User`, and ultimately on `UserDto`. This had the unfortunate side effect of breaking the tours data migration introduced in V14, because it attempts to load `UserDto` from the DB. This is no longer possible with the new field on `UserDto`.
To fix it, I've retrofitted the migration with `NewUserDto` - pretty much the same way the ["add GUID to Users"](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddGuidsToUsers.cs#L294) migration works for V14.
Upgrade a DB from V13 to V15. If things do not explode, things work 😆

Fix broken Tours migration for V15

---

src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_3_0/AlignUpgradedDatabase.cs

Fixes #16267
Due to older versions of Umbraco not always having had explicit constraint names, some older databases have "system-named constraints" resulting in constraint names not matching up what what we expect in later versions.
This PR takes that behavior into account to change a [prior migration](https://github.com/umbraco/Umbraco-CMS/pull/15934) that relied on the constraint name being a fixed value. By utilizing the know table name, column name and constraint type (default, which only exists ones per column) we can identify the constraint without relying on it's name.
Since it is not straight forward to get a DB in a state where it used system-named constraints, I have asked the community to test out this PR on their DB's
I have also tested on the following scenarios to cover as …

Fix Mismatching constraint names in old migration

---

Directory.Packages.props
src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
tests/Directory.Packages.props

Updated the NuGet packages to latest minor/patch and take an explicit dependency on Microsoft.IdentityModel.JsonWebTokens, do avoid implicit dependency on vulnerable version

Update to latest nuget packages 2024-08-20

---

tests/Umbraco.Tests.AcceptanceTest.UmbracoProject/.gitignore

The Umbraco.Tests.AcceptanceTest.UmbracoProject project is not a _real_ web application and can't be run, but when Visual Studio sees the SDK it adds a launchSettings file.
This PR just ignores the file to prevent contributors that are using Visual Studio from accidentally adding it in their PRs.

Ignore Visual Studio's generated launchSettings file.

---

src/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactory.cs

If there's an existing issue for this PR then this fixes #15724 
In Umbraco 8 it used to be possible to have a doctype with no template assigned and an 'umbracoRedirect' field present that when hit would redirect a user to a chosen page. In Umbraco 10 onwards, this functionality will only work if a template has also been assigned to the doctype. This PR restores the original behaviour.
This appears to happen because:-
* In Umbraco 8, as part of the 'GetHandlerForRoute()' method in 'Mvc\RenderRouteHandler.cs' a check is initially performed to see if the request has no template. If so it would begin to update it to a 404 via 'UpdateRequestToNotFound', before promptly exiting if it is detected it is a redirect and not following through any further on the 404 behaviour.
* In the newer Umbraco …

Update valid reasons to not have a template on a content node to include having umbracoRedirect

---

src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
src/Umbraco.Core/Services/IIndexedEntitySearchService.cs
src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs

The document/media item search endpoints need to be enhanced with the ability to limit the search results based on the parentId for certain pickers to work better.
Setting up a multi layer content structure (root-parents-children) and querying the updated endpoint with one of the parent ids should only return (some) of that parent's children.
Leaving out the parentId should work just like the old endpoint.

Support parentId in document/media item search endpoints

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/16046
See linked issue
See updated reproduction steps in the linked issue.
Instead of an unresponsive editor, a message is displayed.

Fix unresponsive block grid editor

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js
src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/15996
This PR. turns a document/node into read only mode while saving.
This prevent making changes while saving, because when done saving we reset everything till the state of the latest saved data.
This gives a better solution in general, try testing this with a normal text box.
The issue mentioned above, is not necessary fixed by this, cause that case is just opening a Block while saving(Not necessary editing it while its still saving). This PR will then leave the user with a Block Modal opened as in read only mode, where we have removed the Submit button. Potentially leaving the user a little confused, but having hidden away the problem. Let me describe furhter:
The main problem is that Blocks are edited via Modals, and the Modal is …

V13: Read only mode while saving

---

src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts

AppEntryPoints should be executed on the login screen.
1. Add an `umbraco-package.json` file containing an extension with type `appEntryPoint`
2. Make sure `allowPublicAccess` is set to `true` in the manifest file itself
3. Ensure the code is being run inside the entrypoint

V14: Extensions of type `AppEntryPoint` are not being executed on the login screen

---

global.json

There is an SDK requirement mismatch between the the CMS repo and the Umbraco.code which currently shows up as a warning.
This mismatch showed itself during the pipeline run of [the warnings as errors PR](https://github.com/umbraco/Umbraco-CMS/pull/15019) as it will become a warning at that point. We chose to fix it as it is something we should keep in sync anyway
Test whether you can still build the solution locally, you might have to install a newer sdk version.

FIX sdk version mismatch

---

src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml

Tag helpers are currently broken in .NET 9 preview which results in the `type="module"` attribute being removed from our login screen script tag.
This PR is a temporary fix to make the login screen work again for everybody. The issue is targeted to be fixed in .NET 9 rc where we will have to revert these changes again.
https://github.com/dotnet/aspnetcore/pull/57170

V15 Bugfix: Temp remove tag helpers on login screen

---

build/azure-pipelines.yml
templates/UmbracoProject/.template.config/template.json

It used dotnet 8 to build the Umbraco project. This PR updates to use dotnet 9

V15 QA fix e2e build pipeline

---

src/Umbraco.Cms.Api.Management/DependencyInjection/MemberBuilderExtensions.cs
src/Umbraco.Cms.Api.Management/Factories/MemberPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
src/Umbraco.Cms.Api.Management/Mapping/Member/MemberMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Member/Item/MemberItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/CreateUserRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/CreateUserRequestModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/InviteUserRequestModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/Item/UserItemResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/User/UserResponseModel.cs
src/Umbraco.Core/Models/Membership/IUser.cs
src/Umbraco.Core/Models/Membership/MemberKind.cs
src/Umbraco.Core/Models/Membership/User.cs
src/Umbraco.Core/Models/Membership/UserKind.cs
src/Umbraco.Core/Models/UserCreateModel.cs
src/Umbraco.Core/Services/UserService.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/AddKindToUser.cs
src/Umbraco.Infrastructure/Persistence/Dtos/UserDto.cs
src/Umbraco.Infrastructure/Persistence/Factories/UserFactory.cs
src/Umbraco.Infrastructure/Security/BackOfficeIdentityUser.cs
src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.ChangePassword.cs
tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Create.cs

#16817 introduced the user "type" (`Default` or `Api`) to distinguish API users from regular ones.
The same kind of thing is needed for API members (the ones configured in `ClientCredentialsFlow`, see #16817 for details). But as it happens, members already have a "type" - the `MemberType`... so it would be confusing to add another "type" to members.
We have decided to go with "kind" instead of "type". This means that the user "type" becomes the user "kind" for consistency.
Also, this PR removes "kind" from the invite user endpoint, as it makes no sense to invite an API user 😃 
Please note that existing V15 DBs won't survive this change, since the migration that originally added "type" now adds "kind" instead. It's not breaking, though, because the original PR was also for V15 😄 if need be …

Add member "kind" - and refactor user "type" to "kind" for consistency

---

src/Umbraco.Cms.Api.Delivery/Controllers/Security/MemberController.cs
src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs

This PR aligns the custom error responses from the auth parts of the Management and Delivery APIs with those of OpenIddict, which in turn are aligned with the [OpenID Connect standard](https://openid.net/specs/openid-connect-core-1_0.html).
Invalid auth requests should have responses that conform to the standard.
For example attempting to use an invalid `client_id` (this is a custom error response in `MemberController`):
....compared to using an invalid `redirect_uri` (this is a response from OpenIddict):

Ensure correct OpenID Connect error responses

---

src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
umbraco.sln

The Azure DevOps build randomly times out the `Build Umbraco CMS` stage at 1 hour, while it otherwise completes within 5-10 minutes. When it times out, it always happens on the `Run dotnet build and generate NuGet packages` build step and other runs started around the same time also timeout in most cases. Restarting the build sometime later results in a successful build, indicating this is an intermittent issue, potentially due to limited available resources on the agent.
One potential issue could be that the `Umbraco.JsonSchema` is build as part of the solution (in no specific order, as it isn't referenced by any other project), but also implicitly build as part of the `dotnet run` execution when building `Umbraco.Cms.Targets`. I've disabled building this project in the solution …

Avoid concurrent build of `Umbraco.JsonSchema` tool and add execution timeouts to `Exec` build tasks

---

src/Umbraco.Cms.Api.Management/Controllers/ModelsBuilder/BuildModelsBuilderController.cs

This fixes https://github.com/umbraco/Umbraco-CMS/issues/16918
I have changed BuildModelsBuilderController to use IModelsGenerator so the functionality is the same as the SourceCodeAuto functionality. 
It should have no impact on Umbraco out of the box, but allow easlier ModelsBuilder-replacement for developers.

ModelsGenerator to IModelsGenerator in BuildModelsBuilderController

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

Content.EditorDirectiveController: added formSubmittedValidationFailed broadcast to prevent fields to stay disabled
If there's an existing issue for this PR then this fixes #17019
v13.5.0 RC
#16961 resolved an issue with content saving.
We discovered that when attempting to save and publish with invalid fields, those fields remained disabled. After some investigation, we found that triggering the formSubmittedValidationFailed broadcast resolved the problem.
1. Add a mandatory text field to a doctype
2. Add a non mandatory text field to that doctype
3. Create an instance of that doctype
4. Save and publish without value
=> After validation text fields (and blocklist, mediapicker, ...) will stay disabled
In collab with @NielsAudoor ;)

Content.EditorDirectiveController: added formSubmittedValidationFailed broadcast to prevent fields to stay disabled

---

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_5_0/ChangeRedirectUrlToNvarcharMax.cs
src/Umbraco.Infrastructure/Persistence/Dtos/RedirectUrlDto.cs

HotFixes #16974
Will have to be rerun in v14 that were upgraded to v14 prior to this PR. The migration has a check to see if the column was migrated before.
Proof it creates the redirects in the database now and length is larger than what it could handle

Expand RedirectUrl.Url storage type to avoid truncation

---

src/Umbraco.Cms.Api.Management/Controllers/Content/ContentCollectionControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Document/Collection/DocumentCollectionControllerBase.cs
src/Umbraco.Cms.Api.Management/Controllers/Media/Collection/MediaCollectionControllerBase.cs
src/Umbraco.Cms.Api.Management/Mapping/Content/ContentMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentVersionMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Media/MediaMapDefinition.cs
src/Umbraco.Cms.Api.Management/Mapping/Member/MemberMapDefinition.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentCollectionResponseModelBase.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/Collection/DocumentCollectionResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentValueResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVersionResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/DocumentBlueprint/DocumentBlueprintResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Media/Collection/MediaCollectionResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaValueResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberResponseModel.cs
src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberValueResponseModel.cs
src/Umbraco.Core/Models/ContentEditing/ValueResponseModelBase.cs

The pending clipboard feature (and in part also block level variance) would benefit greatly from knowing up-front what kind of value editor is backing a content property value. To achieve this, we need an "editorAlias" property to each value in the content endpoint outputs (documents, media, member).
There will be a follow-up to this at block level for block level variance.
1. It should be possible to edit and save existing documents, media and members. Make sure you test this on items _with_ properties 😄 
2. Also verify that collection views still work as per usual (try a media folder).
3. Lastly, the output from a content endpoint (i.e. GET document) should contain `editorAlias` for each property value:

Add EditorAlias to content value outputs

---

build/nightly-E2E-test-pipelines.yml

Added fetch depth, if not we would get issues with NerdBank

V14 QA update fetch depth

---

src/Umbraco.Web.UI.Client/src/common/services/rte-blockeditor-clipboard.service.js

Clipboard pasting Blocks, which has a property which value is a object but not a Block fails.
This PR fixes that.
A test case is making a block list editor with a Block that has a Media Picker, check that you can copy and paste that block.

Fix: V13.5 RTE block paste resolver issue

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/17054
Instead of using existing events, this PR created a new set of events that can be trusted.
The problem with the other events was that they where fired by many different cases and not necessary firing the ending event 'formSubmitted'.

Bug: v13.5 17054 (take 2)

---

src/Umbraco.Cms.Api.Management/Factories/DocumentNotificationPresentationFactory.cs
src/Umbraco.Cms.Api.Management/OpenApi.json
src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentNotificationsResponseModel.cs

To ease localization of the "Document notifications" dialog, the document notification aliases have been added to the output of the supporting endpoint.
Verify that the output from the document notifications endpoint contains an `alias` for each notification type.

Add notification alias to document notifications endpoint output

---

src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
src/Umbraco.Core/Services/LocalizedTextService.cs

New Swedish translation crashes Umbraco
LocalizedTextService.GetAreaStoredTranslations crashes on duplicate area-keys
Removed duplicate areas

v13.5 - New Swedish translation crashes Umbraco, removed duplicate areas.

---

src/Umbraco.Core/Constants-Composing.cs

Updated the assembly names to avoid an debug-error message in the log, about the missing backoffice assembly
- Verify Umbraco runs
- Set verbose debugging, and ensure there is not message in the beginning about assemblies that cannot be found.

Updated the assembly names to avoid a debug-warning in the log
