umbraco/Umbraco-CMS

src/Umbraco.Cms.Api.Management/Controllers/Document/CreateDocumentControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentControllerBase.cs, src/Umbraco.Core/Services/ContentEditingService.cs
Allows the client to send all content values for all languages when saving, even if the user do not have permissions to alter these.
The server ensures to rollback values the user do not have permission to alter.
This is a hack, but currently the only short-term solution to implement the language permissions feature in v14. Longer term, we should have a patch endpoint that can do the logic instead of the post endpoint.
- Setup multiple languages
- Setup a user that do not have permissions to all languages
- Try to save the content for all languages (Not publish, as it requires client changes)
-  Verify only the content for the languages the user is allowed to change, is actually updated. (You will need to update the browser, to get the data again.)
=> Allow client to send language values, that user cannot persist

src/Umbraco.Core/Composing/AsyncComponentBase.cs, src/Umbraco.Core/Composing/ComponentCollection.cs, src/Umbraco.Core/Composing/ComponentCollectionBuilder.cs, src/Umbraco.Core/Composing/ComponentComposer.cs, src/Umbraco.Core/Composing/IAsyncComponent.cs, src/Umbraco.Core/Composing/IComponent.cs, src/Umbraco.Core/Composing/RuntimeAsyncComponentBase.cs, src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs, src/Umbraco.Core/Extensions/ObjectExtensions.cs, src/Umbraco.Core/Notifications/UmbracoApplicationStartingNotification.cs, src/Umbraco.Core/Notifications/UmbracoApplicationStoppingNotification.cs, src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
As mentioned in https://github.com/umbraco/Umbraco-CMS/pull/16430#issuecomment-2139162134, it's currently not possible to (correctly) use async methods in components. This adds `IAsyncComponent` and refactors the code to call the `InitializeAsync()`/`TerminateAsync()` methods instead, which does mean a breaking change in the `ComponentCollection` (the item type and methods have changed). I did make `IComponent` inherit from `IAsyncComponent` and added default interface methods, so any existing (synchronous) components are still backwards compatible.
I've also added 2 base classes to make usage easier:
- `AsyncComponentBase` - this only initializes/terminates when the application isn't restarting (aka the actual start/stop of the application) and implements a no-op `TerminateAsync()` …
=> Add `IAsyncComponent` to allow async initialize/terminate

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextParsingRegexes.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RichTextPropertyEditorHelperTests.cs
Allows blocks in rte to leave out the "Umbraco-Block" comment from their bodies
=> V15: Allows blocks in rich text editor to leave out the "Umbraco-Block" HTML comment

src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/AddUserClientId.cs
The `AddUserClientId` migration should be able to run twice, in the odd case that migrations need to be re-run.
=> Make AddUserClientId able to run twice if needed

src/Umbraco.Cms.Imaging.ImageSharp/ConfigureImageSharpMiddlewareOptions.cs
There is an issue when passing an invalid value in the width or height parameter, it could get a FormatException thrown.
Example: domain.com/media/jk4feiat/image.png?width=foo&height=150
OR
domain.com/media/jk4feiat/image.png?width=200&height=bar
OR
domain.com/media/jk4feiat/image.png?width=foo&height=bar
Solution: Check width and height in ConfigureImageSharpMiddlewareOptions and parse it with invariant culture into an integer.
=> Update ImageSharpMiddlewareOption for fixing invalid width and height

src/Umbraco.Core/Extensions/UdiGetterExtensions.cs, tests/Umbraco.Tests.Common/Builders/ContentBuilder.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UdiGetterExtensionsTests.cs
While implementing document blueprint container support in Deploy 14, I noticed document blueprints (`IContent` with `Blueprint = true`) were returning UDIs using the document entity type (e.g. `umb://document/{GUID}`, instead of `umb://document-blueprint/{GUID}`).
This PR adds tests for all supported entity types, fixes the issue and cleans up the `UdiGetterExtensions` class to remove redundant code. The added tests should be sufficient to verify the issue, but reverting to the first commit will show the failing test:
```
Expected string length 57 but was 47. Strings differ at index 14.
Expected: "umb://document-blueprint/6ad82c70685c4e049b36d81bd779d16f"
But was:  "umb://document/6ad82c70685c4e049b36d81bd779d16f"
-------------------------^
```
=> Fix `IContentBase.GetUdi()` extension method to support document-blueprint entity type

src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
After PR https://github.com/umbraco/Umbraco-CMS/pull/16430 got merged that now includes `umbraco-package.json` manifests in telemetry data, I noticed that the package version is only automatically determined for package migration plans.
The previous `package.manifest` format contained a `versionAssemblyName` property that allows package developers to automatically populate the version based on the assembly informational version (see PR https://github.com/umbraco/Umbraco-CMS/pull/14046). This got updated to consider the package `id` as fallback, as the package ID should align with the NuGet package ID and that (by default) aligns with the assembly name (see PR https://github.com/umbraco/Umbraco-CMS/pull/14047).
This PR automatically populates the package version (if it's empty) based on …
=> Use version of the assembly with the same name as the package ID (for telemetry data)

src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsExtensions.cs
PR https://github.com/umbraco/Umbraco-CMS/pull/15345 added a fluent API for adding webhook events, but because the CMS adds a subset of events by default, you had to first clear all events to make sure you only end up with the configured ones. However, if other packages (like Deploy) also add events by default, those will also be cleared.
To address this, I've added a `RemoveDefault()` extension method, so the following example ensures all CMS default events are removed and only the content ones are added, without affecting other custom/non-CMS events:
```c#
public class WebhookComposer : IComposer
{
=> builder.WebhookEvents()
.AddCms(cmsBuilder => cmsBuilder.RemoveDefault().AddContent());
}
```
=> Add `RemoveDefault()` extension method to fluent API for CMS webhook events

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPremigrationPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddGuidsToUserGroups.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddGuidsToUsers.cs
Attended upgrades have started failing for V14. These failures happen because the User and User Group DB schemas are not up to date when attempting to log in to initiate the upgrade (because the upgrade has not yet run).
This PR moves all User and User Group migrations for V14 into the pre-migrations plan, so attended upgrade only starts _after_ ensuring an up-to-date schema for Users and User Groups.
Verify that both attended and unattended upgrades work from V13 to V14.latest.
Run these tests for both SQLite and SQL Server.
=> Move all V14 User and User Group migration to pre-migrations

build/azure-pipelines.yml
Due to the current situation with both NuCache and HybridCache we randomly hit out-of-memory exceptions that we cannot reproduce locally.
=> Temporarily disable of windows integration tests

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPremigrationPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateTours.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/AddKindToUser.cs
Similarly to #17130, we also need execute the V15 migrations affecting User data as pre-migrations.
As it happens, one of the V14 migrations (`MigrateTours`) must run before the V15 ones can run, so that one has been moved to pre-migrations as well. To achieve a smooth transition to V15 from both V14 _and_ V13:
1. `MigrateTours` has been replaced with a no-op migration in the regular upgrade plan.
2. `MigrateTours` has slightly altered to exit fast, in case it has already run (which will be the case in a V14 to V15 upgrade).
Verify that both attended and unattended upgrades work from V14 to V15 _and_ from V13 to V15.
Run these tests for both SQLite and SQL Server.
=> Execute V15 User data migrations as pre-migrations

src/Umbraco.Cms.Api.Common/Configuration/ConfigureUmbracoSwaggerGenOptions.cs, src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderApiExtensions.cs, src/Umbraco.Cms.Api.Common/OpenApi/ISubTypesHandler.cs, src/Umbraco.Cms.Api.Common/OpenApi/ISubTypesSelector.cs, src/Umbraco.Cms.Api.Common/OpenApi/SubTypesHandler.cs, src/Umbraco.Cms.Api.Common/OpenApi/SubTypesSelector.cs, src/Umbraco.Cms.Api.Management/Configuration/ConfigureUmbracoManagementApiSwaggerGenOptions.cs
_This is a replacement PR for #17072 ... description is still valid, and originates from the original PR._ 
This PR introduces a new `ISubTypesSelector` and `ISubTypesHandler` implementation to allow overriding how Swagger resolves subtypes of a type based on both the base type and the API document name.
This is required as the current default behaviour is to resolve all type implementations of the base type across all app domain assemblies. This poses a problem if you have (like we do in Umbraco Commerce) a shared base class used by multiple Swagger documents. In this scenario Swagger will throw an exception as it attempts to load the types from all endpoint definitions, not just the for the given API, casing duplicate schema to be generated.
With this PR in the same way …
=> Swagger sub types selectors (take 2)

src/Umbraco.Cms.Api.Delivery/Services/ApiMediaQueryService.cs, src/Umbraco.Core/EmbeddedResources/Snippets/ListDescendantsFromCurrentPage.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/SiteMap.cshtml, src/Umbraco.Core/Extensions/PublishedContentExtensions.cs, src/Umbraco.Core/Models/PublishedContent/IPublishedContent.cs, src/Umbraco.Core/Models/PublishedContent/PublishedContentBase.cs, src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs, src/Umbraco.Core/PublishedCache/Internal/InternalPublishedContent.cs, src/Umbraco.PublishedCache.HybridCache/PublishedContent.cs
- Replacing the usages of the `Children` property from `IPublishedContent` since we now can retrieve the navigation data from a dedicated `IDocumentNavigationQueryService` or `IMediaNavigationQueryService`;
- Updating params in **PublishedContentExtensions.cs** to the general interfaces (`IPublishedCache` and `INavigationQueryService`), so that we can use the extension methods on both documents and media;
- Introducing `GetParent()` in **PublishedContent.cs** to inject the right services;
- Introducing `GetChildren()` in **PublishedContentBase.cs** to inject the right services;
- Fixing some obsolete messages.
=> V15: Replacing the usages of `Children` (navigation data) from `IPublishedContent`

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
On fresh v15 installations, the default data-type for the **Richtext editor** should use the [new Tiptap editor](https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2347).
This PR updates the database creation script to replace TinyMCE with Tiptap configuration.
Existing/upgraded installations will remain using TinyMCE configuration as the default **Richtext editor** data-type.
=> V15: Swap default Richtext Editor data-type from TinyMCE to Tiptap

src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/RichTextElementLevelVariationTests.cs
Block level variance (#17120) inadvertently broke RTEs _without_ blocks 🙈 
Specifically, RTE properties will not render any output if they're _invariant_ as part of a _variant_ document type, unless there are blocks added to the RTE.
=> Make RTE work without blocks in a culture variant context

src/Umbraco.PublishedCache.HybridCache/DatabaseCacheRebuilder.cs, src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs
Fixes multiple issues with the cache:
- Media was created as published
- Rebuild did nothing in the repository
- Rebuild was not executed in an ambiant scope.
- Upload an image to the media section
- Restart - And verify the seeding to not fail anymore.
- change a value in the cmsContentNu table and use the rebuild functionality from backoffice, and verify it is back to the original value.
=> Bugfix: Media in new cache was created as published

templates/UmbracoProject/.template.config/template.json, templates/UmbracoProject/UmbracoProject.csproj
Updates the dotnet version in the template and removes the duplicate in the csproj file.
We now use the `UmbracoRelease` value to calculate the dotnet version, since we want to use dotnet 8 for v13 and dotnet 9 for V15
=> V15: Update dotnet version in template

.github/workflows/codeql-analysis.yml
Ensured compatibility with .NET 9 to fix failing CodeQL checks
=> Fix failing CodeQL due to needing .NET 9

src/Umbraco.Core/Cache/Refreshers/Implement/ContentTypeCacheRefresher.cs, src/Umbraco.Core/Cache/Refreshers/Implement/DataTypeCacheRefresher.cs, tests/Umbraco.Tests.Common/TestHelpers/ContentTypeUpdateHelper.cs, tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContentEditing.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Cache/PublishedContentTypeCacheTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/PublishedContent/PublishContentTypeFactoryTest.cs
Fixes an issue where updating document types with new datatypes broke publishing.
This was because the datatype cache in `PublishedContentTypeFactory` never got refreshed, I've re-added this in the cache refreshers. 
Testing: 
* Create DocumentType
* Create Document with DocumentType
* Create a Custom DataType
* Add Custom DataType to DocumentType
* Try to publish the Document
=> V15: Refresh IPublishedContentTypeFactory when data types change

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs, src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
Reintroduces the extensions that is possible on `PublishedContentExtensions`, but as obsolete.
To avoid unnecessary breaking changes
I tested with the following render controller and a doc type called Root.
```cs
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
public class RootController : RenderController
{
private readonly IVariationContextAccessor _variationContextAccessor;
private readonly IContentTypeService _contentTypeService;
private readonly IMediaTypeService _mediaTypeService;
private readonly IMemberTypeService _memberTypeService;
private …
```
=> Reintroduced a lot of extension methods as obsolete to avoid breaking change

src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs
Return the correct models from the media cache service
Fixes #17204
=> Fix internal class being returned from media cache service

src/Umbraco.Core/Services/EntityTypeContainerService.cs, src/Umbraco.Core/Services/IEntityTypeContainerService.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17202
Introduce two methods on the `IEntityTypeContainerService<T>`:
- Task<IEnumerable<EntityContainer>> GetAsync(string name, int level);
- Task<IEnumerable<EntityContainer>> GetAllAsync();
You can test it out by creating some data type folders and request them, e.g. just in a view like this
```cshtml
@using Umbraco.Cms.Core.Services
@inject IDataTypeContainerService DataTypeContainerService;
@{
Layout = null;
var x = await DataTypeContainerService.GetAllAsync(); // returns all three
var y = await DataTypeContainerService.GetAsync("Subfolder", 1); // Returns only the subfolder in the root
var z = await DataTypeContainerService.GetAsync("Subfolder", 2); // Returns only the subfolder …
```
=> Introduce methods on new service to have alternative to obsoleted methods

Directory.Packages.props, global.json, src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs, src/Umbraco.Cms.Api.Delivery/Security/MemberApplicationManager.cs, src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs, src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj, src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj, src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj, src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml, src/Umbraco.PublishedCache.HybridCache/DependencyInjection/UmbracoBuilderExtensions.cs, tests/Directory.Packages.props
This PR updates to .NET 9 RC2.
Furthermore all NuGet packages have been updated. Most notable is also the preview of OpenIddict v6, that supports v9 and eliminates the error in the console we saw.
- Tests should pass
- make a small manual smoke tests, signing in to back office etc.
=> Updated to .NET9 RC2 + other nuget packageds

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/ItemDocumentTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/SearchDocumentTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Tree/DocumentTypeTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/ItemMediaTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/SearchMediaTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/MediaType/Tree/MediaTypeTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/ItemMemberTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/SearchMemberTypeItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/MemberType/Tree/MemberTypeTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Template/Query/ExecuteTemplateQueryController.cs, src/Umbraco.Cms.Api.Management/Factories/DataTypeReferencePresentationFactory.cs, src/Umbraco.Core/Handlers/WarnDocumentTypeElementSwitchNotificationHandler.cs, src/Umbraco.Core/Services/ContentTypeEditing/ElementSwitchValidator.cs, src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs, src/Umbraco.Core/Services/IContentTypeServiceBase.cs, src/Umbraco.Infrastructure/Cache/PropertyEditors/BlockEditorElementTypeCache.cs, src/Umbraco.Infrastructure/Cache/PropertyEditors/IBlockEditorElementTypeCache.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs, src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.ContentType.cs
According to https://github.com/umbraco/Announcements/issues/15 all services' `GetAll` method has changed behavior, but a a few was not migrated yet.
Changed the behavior to not return all items, renamed to `GetMany`, when no keys received. Instead a new `GetAll` method is introduced that do not take any parameters.
=> Fixed last remains of `GetAll` vs `GetMany`

src/Umbraco.Core/Routing/UmbracoRequestPaths.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
Fixes #17017
The logic that determines whether a request path is part of the installer will no longer greedily return true when the first segment of the url starts with the installer path (install), ie: installation
As described in the original issue, setup a standard site with everything under 1 "site" node, protect one of the pages directly under the site node with a standard member setup and make sure the name of the page's name starts with `install`.
Unit tests have been added to cover the buggy case and some other possible issues.
This bug is most likely also present in all other active majors.
=> Fix greedy Install url detection

src/Umbraco.Core/MonitorLock.cs, src/Umbraco.PublishedCache.NuCache/ContentStore.cs, src/Umbraco.PublishedCache.NuCache/SnapDictionary.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PublishedCache/ContentCacheTests.cs
After large Deploy operations (like an environment restore) has completed and the CMS tries to update the content cache (NuCache) as part of completing the Umbraco scope, the following exceptions were thrown:
```
System.AggregateException: One or more errors occurred. (Write lock must be acquried.) (Exceptions were thrown by listed actions. (Object synchronization method was called from an unsynchronized block of code.) (Object synchronization method was called from an unsynchronized block of code.) (Object synchronization method was called from an unsynchronized block of code.))
at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)
at Umbraco.Cms.Infrastructure.Scoping.Scope.RobustExit(Boolean completed, Boolean onException)
at …
```
=> Fix ContentStore locking exceptions in async code

tests/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs, tests/Umbraco.Tests.Common/Builders/MediaTypeEditingBuilder.cs
I found that when I built the project in Visual Studio I got StyleCop errors on these two files.  I fixed the errors by making params on one line.  This fix the errors and the project successfully ran.
Also, this is part of Hacktoberfest2024!
=> Fix stylecop errors with function parameters on separate lines

src/Umbraco.Core/PropertyEditors/Validators/DateTimeValidator.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/DateTimeValidatorTests.cs
If there's an existing issue for this PR then this fixes [](https://github.com/umbraco/Umbraco-CMS/issues/17253)
when having languages such as Arabic as the default culture UI .Net automatic changes the Time format to Hjiri. 
this caused an issue in the back-end validation for all datatype
as Peer the bug  https://github.com/umbraco/Umbraco-CMS/issues/17253
To fix this I just make the convert statement in datetime fallback to the default format which is the old good gregorian format 
To Test This:
1. Create a new Document type that has date time picker.
2. logout then login for language cookie to reset
3. Make Your Back office default UI Culture Arabic ==> العربية
4. Create a new node from that document type and fill the date
5. Click save and publish successfully
=> Making Culture Invariant When Validating Date to negate deferent formats 

src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs
Fixes issue with draft template used for published data.
Basically same logic as here https://github.com/umbraco/Umbraco-CMS/blob/9dfb3005bcd68f5399ee13263bfc462c69b39a66/src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs#L950
- Publish content normally
- Change template and save (without publish) 
- Reboot
- Verify correct template is used
=> Bugfix: Use published template on load from database

src/Umbraco.Core/PublishedCache/IDatabaseCacheRebuilder.cs, src/Umbraco.PublishedCache.HybridCache/DatabaseCacheRebuilder.cs, src/Umbraco.PublishedCache.HybridCache/DependencyInjection/UmbracoBuilderExtensions.cs, src/Umbraco.PublishedCache.HybridCache/NotificationHandlers/HybridCacheStartupNotificationHandler.cs
- Reimplements the `NuCacheStartupHandler`, now renamed to `HybridCacheStartupNotificationHandler`.
- This will rebuild the cache, if the `NuCacheSettings.NuCacheSerializerType` changes (on startup).
- Create some content in umbraco.
- Checkout that content, thus loading it into the cache.
- Stop umbraco, and change the setting in "Umbraco:CMS:Nucache"
```
"NuCache": {
"NuCacheSerializerType": "JSON"
},
```
- Start umbraco and checkout the content, assert that it still works.
=> V15: Reimplement cache startup handler

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
This PR ensures that tags are collected correctly when used in combination with block level variance.
1. Verify that tags are collected and assigned to the correct language when configuring blocks, both with and without block level variance.
2. Verify that tags are still collected correctly at document level.
=> Support block level variant tags

src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs, src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs, src/Umbraco.Core/Persistence/Repositories/IPublishStatusRepository.cs, src/Umbraco.Core/Routing/ContentFinderByUrlNew.cs, src/Umbraco.Core/Services/DocumentUrlService.cs, src/Umbraco.Core/Services/PublishStatus/IPublishStatusManagementService.cs, src/Umbraco.Core/Services/PublishStatus/IPublishStatusQueryService.cs, src/Umbraco.Core/Services/PublishStatus/PublishStatusInitializationHostedService.cs, src/Umbraco.Core/Services/PublishStatus/PublishStatusService.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs, src/Umbraco.Infrastructure/Persistence/Dtos/ContentTypeDto.cs, src/Umbraco.Infrastructure/Persistence/Dtos/DocumentCultureVariationDto.cs, src/Umbraco.Infrastructure/Persistence/Dtos/DocumentDto.cs, src/Umbraco.Infrastructure/Persistence/Dtos/LanguageDto.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PublishStatusRepository.cs, src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishStatusServiceTest.cs
Ensures urls are not available if an item or one of the ancestors are unpublished.
To do this in a fast way, I needed to introduce a cached version of the publish status, as we cannot rely on IPublishedCache anymore.
The new `IPublishStatusQueryService` can be requested and is used by `DocumentUrlService`. It initialises itself on boot with a fast query of the status of all content.
- Setup a two languages and a culture variant doctype with some content (also nested)
- Unpublish a single culture and verify you get 404 but the published cultures are still available
- Unpublish all cultures and verify all pages gives 404.
=> Bugfix: Do not allow routing content that is unpublished

src/Umbraco.PublishedCache.HybridCache/NotificationHandlers/SeedingNotificationHandler.cs
So a bug was discovered upgrading from 13 to 15, with seeding running while we are migrating, thus causing errors.
The solution is to only run the seeding, when we are in run mode. 
There is however one case were we want to run seeding, and that is when you have the maintenance page disabled, (as in, you still want to access the site while in upgrade state, and thus we want that content to be seeded).
I do however think this case is fine to get errors, as this would also be the case when accessing content, where the data models no longer match, and thus would cause errors anyways.
- From a v13 database
- Try to run v15 with unattended upgrades enabled
- The error should no longer occur.
=> V15: Dont seed when in upgrade mode, and maintenance page is enabled

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Fix for #17187
This PR unlocks the form in the case of a failed Save and Publish, fixing the regression introduced in 13.5.1.
This only fixes the regression itself - there's still an unhandled error, and the UX after a failed save of a new document is not right.
To test, try to Save and Publish a document without filling in some mandatory fields
The document will still be editable after the unsuccessful publish.
Before: 
https://sharing.clickup.com/clip/p/t9015063813/b1a7fa9b-7bec-41bb-9a21-1a220fe2b259/Umbraco%2013-5-1%20bug.webm
After: 
https://github.com/user-attachments/assets/be9746fd-6e6e-49fd-ba92-dba35c789bac
=> Fix for #17187, unlock form after unsuccessful save and publish

src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
Fixes #17219
Fixes #17272
Partly fixes #17009 (which still needs a frontend fix)
Since the change from UDIs to "localLinks" in the `href` attribute (>=14.1), the pattern matched a little too much in the href section completely ignoring any "extras" such as query strings and anchors after the locallink, which meant that the locallink did not get replaced at all if they were present. This is fixed by limiting the regexp a bit.
Because we are no longer matching the whole `href` attribute but only some of its contents, we need to fix the old pattern. It has been simplified into a main RegExp that finds all a-tags with local links inside, then another regex is run on each component subset to find its `type` attribute value.
I have added more test cases to cover what did not work before. In …
=> V15: Rich Text Editor links do not work with query strings and anchors

src/Umbraco.Core/DynamicRoot/Origin/RootDynamicRootOriginFinder.cs, src/Umbraco.Core/DynamicRoot/Origin/SiteDynamicRootOriginFinder.cs
If there's an existing issue for this PR then this fixes #15770 (in part)
This PR fixes the contextual issues for newly created content, raised in [this comment](https://github.com/umbraco/Umbraco-CMS/issues/15770#issuecomment-2076739278) on #15770.
By performing a fallback to the parent key, the "Root" and "Site" qualifiers for dynamic roots also work for content that has yet to be created.
Verify that MNTP "Root" and "Site" dynamic roots can be used when creating new content (before it's created, that is).
=> MNTP: Improve site and root context for dynamic root

src/Umbraco.Core/PropertyEditors/DefaultPropertyIndexValueFactory.cs, src/Umbraco.Core/PropertyEditors/IPropertyIndexValueFactory.cs, src/Umbraco.Core/PropertyEditors/IndexValue.cs, src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs, src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs, src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs, src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactoryBase.cs, src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyIndexValueFactory.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Indexing.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/PropertyIndexValueFactoryTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/RichTextElementLevelVariationTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
This fixes search indexing for block level variants.
Setup various permutations of variant, invariant and block level variant content, and test that search indexing works for these content items.
Pay special attention to block level variance in RTEs, as this has proven rather tricky to handle indexing wise.
The signature for all property indexing change quite a bit, to allow an invariant property value to yield multiple index values across different language variants. For example, the `IPropertyIndexValueFactory` now yields an `IEnumerable<IndexValue>` instead of `IEnumerable<KeyValuePair<string, IEnumerable<object?>>>`, where the `IndexValue` has language variance built into it.
This change is impossible to do in a backwards compatible fashion, because the current implementation with …
=> Block level variants - search indexing

build/azure-pipelines.yml, src/Umbraco.PublishedCache.NuCache/DependencyInjection/UmbracoBuilderExtensions.cs
Fixes #17182
Doing migrations we need to lookup ids for keys and keys for ids. The IIdKeyMap is implemented using Nucache, and if any change to the nucache content happens, it will fail.
This is the safer approach as the comment also says. This changes as already been made in V15
- Setup v13 with some granular permissions
- Migrate to this branch
- Verify success
=> Do not rely on NuCache to do key/id lookups

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs
Fixes #17128 
This PR fixes the issue raised in #17128 where media is uploaded to the media library with dimensions in the file name but then cannot be queried using IMediaService.GetMediaByPath (see issue details for more information).
All tests have run and pass.
1. Upload a file to the media library which has the name in the format [name]_[width]x[height].[ext], i.e. test_200x200.jpg.
2. Add the following code into a template to test that the GetMediaByPath finds the media item:
```
@inject IMediaService MediaService;
var media = MediaService.GetMediaByPath("add path to media file here which includes the dimensions");
if (media != null)
{
<p>Media Found! @media.Id</p>
}
else
{
<p>Media not found!</p>
}
```
3. Repeat the same …
=> Issue 17128 - Fix GetMediaByPath when querying for media which has been uploaded with dimensions in the file name

tests/Umbraco.Tests.AcceptanceTest/package-lock.json, tests/Umbraco.Tests.AcceptanceTest/package.json, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithApprovedColor.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithNumeric.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTags.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTextarea.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTextstring.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTrueFalse.spec.ts
Added tests for rendering content with these values:
- Textarea
- Tags
- TrueFalse
- Numeric
- Approved Color
And fix the tests for rendering content with textstring due to the test helper changes
=> V14 QA Added the acceptance tests for rendering content with different value

Directory.Build.props
Adds a condition to enable the `<TreatWarningsAsErrors>` when not in "Debug" compilation mode, (e.g. "Release", or other).
This is to help towards bypassing NuGet dependency vulnerability checks during active development builds.
=> Chore: Adds condition to `<TreatWarningsAsErrors>` for not in Debug mode

src/Umbraco.Core/Services/ContentEditingService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Editing.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.cs
- This now uses the `AllowEditInvariantFromNonDefault` to check when we have to overwrite the edited value.
- Create multiple languages
- Create User with access to only 1 language (has to be a non default one)
- Create a Doctype with allow variance, with 2 properties, one variant and one invariant
- Create a document in each language
- Login with the user you just updated
- Update both the variant and invariant properties in the language you have access to, you should not be able to edit the invariant property, and it should not change.
=> Account for AllowEditInvariantFromNonDefault when updating properties

src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
- Updated the `cy` lang file to include missing keys found in the `en_us` lang file.
- `runtimeModeCheckSuccessMessage`
- `runtimeModeCheckErrorMessage`
- `contentSecurityPolicyCheckHeaderFound`
- `contentSecurityPolicyCheckHeaderNotFound`
- Translations have been checked using:
- Cysgliad: https://www.cysgliad.com/
- BydTermCymru: https://www.gov.wales/bydtermcymru
- Gweiadur: https://www.gweiadur.com/
=> Update Welsh lang file

tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/ContentNavigationServiceBaseTests.cs
- Testing the functionality of `INavigationQueryService.TryGetRootKeys()`.
=> V15: Adding unit tests for `INavigationQueryService.TryGetRootKeys()`

src/Umbraco.Core/Services/Navigation/ContentNavigationServiceBase.cs, src/Umbraco.Core/Services/Navigation/INavigationQueryService.cs, src/Umbraco.PublishedCache.HybridCache/PublishedContent.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/ContentNavigationServiceBaseTests.cs
- Fixing implementation to return `null` when the level cannot be retrieved, instead of level `1`;
- Adding tests.
=> V15: Adding tests for `INavigationQueryService.TryGetLevel()`

src/Umbraco.Core/Services/Navigation/ContentNavigationServiceBase.cs, src/Umbraco.Core/Services/Navigation/INavigationQueryService.cs
- Since the `level` param was made nullable in https://github.com/umbraco/Umbraco-CMS/pull/17375, we can use the `[NotNullWhen(true)]` annotation. This PR adds that.
=> V15: Adding not null when annotation

src/Umbraco.PublishedCache.HybridCache/DependencyInjection/UmbracoBuilderExtensions.cs
Defaults the cache `MaximumPayloadBytes` to  100MB instead of 1 MB, otherwise large content nodes may throw an error, especially if there's multiple languages and large properties like blockgrid is used. 
This setting can always be overwritten using 
```C#
{
{
#pragma warning disable EXTEXP0018
builder.Services.AddOptions<HybridCacheOptions>().Configure(x =>
{
x.MaximumPayloadBytes = 1024*1024;
});
#pragma warning restore EXTEXP0018
}
}
```
=> V15: Make default max payload size more friendly 

src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.targets
If there's an existing issue for this PR then this fixes #16659 
As noted in #16659, everything from `App_Plugins` is copied into the web output. This is unneeded and in the case of the `node_modules` directory unwanted behavior, these files are sources and not output that Umbracco needs to serve packages/extensions.
- The old behavior has led to many of the "path too long" errors we've been seeing while building extensions. 
- It also makes the regular `dotnet build` step needlessly long on the first run as it needs to copy over loads of small files. 
- This also affects `dotnet publish` commands, the whole `node_modules` folder is included in the published output that people will try to put on a server, again leading to very slow copying times AND path too long errors
The new behavior …
=> Fix #16659 - Unwanted node modules copying

Directory.Packages.props, src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
It was updated to 4.8.0-beta00017 to avoid package vulnerability
=> Updated lucene net replicator package 

src/Umbraco.Cms.Api.Common/OpenApi/RemoveSecuritySchemesDocumentFilter.cs, src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoDeliveryApiSwaggerGenOptions.cs, src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoMemberAuthenticationDeliveryApiSwaggerGenOptions.cs
If there's an existing issue for this PR then this fixes #17300
The Delivery API OpenAPI spec wrongfully includes the back-office security scheme, because this is added to all OpenAPI specs by default.
This PR ensures that the Delivery API OpenAPI spec has _no_ security scheme by default, but still allows for opting into the Umbraco member security scheme as [per the docs](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api#testing-with-swagger).
The Umbraco member security scheme has been renamed from `Umbraco Member` to `UmbracoMember`,  as whitespaces are not allowed in OpenAPI security scheme identifiers.
1. Verify that the Delivery API OpenAPI spec does _not_ include any security schemes by default.
2. Verify that it's possible to …
=> Fix security scheme issues in Delivery API OpenAPI spec

src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockEditorPropertiesBase.cs
If there's an existing issue for this PR then this fixes #17400
SQLite has a tendency to lock files, causing problems for multiple simultaneous writes. In other words, the block content migration should not be performed with parallel execution when migrating an SQLite DB.
Tested on both SQL Server and SQLite.
=> Do not migrate blocks in parallel on SQLite

src/Umbraco.Cms.Api.Delivery/Caching/NoOutputCachePolicy.cs, src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
It seems that [enabling output caching](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/output-caching) for the Delivery API causes other custom API controllers to have a one minute output cache. That's not really ideal.
This PR fixes the issue by explicitly applying a "no cache" policy as the default policy when enabling output caching for the Delivery API.
First and foremost, make sure the Delivery API produces output without output caching by default. An easy way to test this is to replace the default property editor value converter for text strings with one that outputs the current date and time - like this:
```cs
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors; …
```
=> Prevent Delivery API output cache configuration from affecting other controllers

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17430
Due to a wrong base constructor used, was the attribute defining the storage type not used for block based types.
=> Fix block based types to not use their storage value type

src/Umbraco.Cms.Api.Management/Controllers/User/ClientCredentials/ClientCredentialsUserControllerBase.cs, src/Umbraco.Core/Services/OperationStatus/UserClientCredentialsOperationStatus.cs, src/Umbraco.Core/Services/UserService.cs, src/Umbraco.Infrastructure/Security/BackOfficeUserClientCredentialsManager.cs, src/Umbraco.Infrastructure/Security/OperationStatus/BackOfficeUserClientCredentialsOperationStatus.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/UserServiceTests.cs
OpenId Connect Client IDs should only be made up of "unreserved characters" - that is, [a-z], [A-Z], [0-9] and [-._~] (see https://en.wikipedia.org/wiki/Percent-encoding).
The back-office client already limits the Client ID input to alphanumerical chars and dash, but of course the API also needs a validation - and that's what this PR adds 😄 
You'll need to use Swagger to test this, due to the above-mentioned restrictions in the back-office.
1. It should be possible to create Client IDs for API Users which consists of valid chars.
2. It should _not_ be possible to create Client IDs for API Users containing one or more invalid chars.
=> Validate client IDs before applying them

src/Umbraco.Cms.Api.Management/Controllers/PublishedCache/CollectPublishedCacheController.cs, src/Umbraco.Cms.Api.Management/Controllers/PublishedCache/StatusPublishedCacheController.cs, src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs
- Moves the check for ID further down, as all the cache refreshing have logic for (when TreeChangeTypes.RefreshAll) where an id is not needed
- Use the endpoints either from swagger, or in the Published Status management dashboard in settings.
=> V15: Fix reload memory cache endpoint

src/Umbraco.Core/Services/DocumentUrlService.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17443
Fixes two bugs
1.  A bug that made the urls available on the info tab, even when the domain-item was not published in the specific culture
1. The bug mentioned in https://github.com/umbraco/Umbraco-CMS/issues/17443 where url segments was combined right-to-left no matter culture
=> Fix wrong urls returned from Url() extension and do not show unavailable paths on info tab

src/Umbraco.Core/Services/ContentService.cs
This fixes #17273
* When a new document `node A` is created under a parent node, it is assigned a SortOrder value of 0.
* Now if you created another document `node B` under the parenr node, it is assigned a SortOrder value of 1.
* Now delete `node A`
* Create a new `node C`, here the [SortOrderExists](https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs#L1018) looks to find any item with sortOrder as 0.
* But the `SortOrderExists` can't find such an item with SortOrder as 0, so it returns false, and this results in setting the [SortOrder as 0](https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Reposit …
=> Sort the children of a parent node after either deleting or moving a child node

src/Umbraco.Core/Media/EmbedProviders/Youtube.cs
If there's an existing issue for this PR then this fixes  [#16948](https://github.com/umbraco/Umbraco-CMS/issues/16948)
When trying to embed a youtube live link (youtube.com/live/.*) in a rich text editor, you get an "not supported" error.
To fix this I appended a regex, that matches youtube live links, to the Youtube OEmbed provider class (Umbraco.Cms.Core.Media.EmbedProviders.Youtube).
To test it:
1.  Create a page with a rich text editor property
2.  Try to embed a link to a youtube live video e.g. https://www.youtube.com/live/jfKfPfyJRdk?si=E9dea9hKldX81B83
3.  Save the changes
4. Observe that an error notification isn't popping up
5.  Create a view for the page doctype and render the RTE property content
6.  Observe that the embedded youtube video is rendered and can be played
=> append 'YouTube Live' url scheme regex to Youtube embed provider class

src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
Issue: 17383
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/17383
After some investigation, I found that the issue lies in the GetId method in Umbraco.Extensions.ClaimsIdentityExtensions.
The identity, after the external login from Entra ID, already contains a NameIdentifier claim. The format of this claim is not an integer; therefore, int.Parse will throw an error.
I tried changing int.Parse to int.TryParse. This will leave the UserId as null until Umbraco fills the NameIdentifier claim with the correct userID. This fixed the error for Entra ID, but I don’t know if this could cause other issues with other providers.
=> Use TryParse when parsing ID from claims

src/Umbraco.Core/EmbeddedResources/Lang/de_ch.xml, src/Umbraco.Core/EmbeddedResources/Lang/fr_ch.xml, src/Umbraco.Core/EmbeddedResources/Lang/it_ch.xml
Add missing backoffice languages as properties etc. are translated via translation section (e.g. with "#Backoffice Settings"). At the moment the swiss languages always need to be added via the umbraco/Config folder.
=> Add swiss languages as backoffice languages

Directory.Packages.props
Updated NuGet dependencies before release of v15.0
| Name  | Old Version | New Version | Note |
| ------------- | ------------- | ------------- | ------------- |
| Microsoft.IdentityModel.JsonWebTokens  | 8.0.8  | 8.0.10  |  |
| Microsoft.EntityFrameworkCore.Design  | 8.0.8  | 8.0.10  |  Not shipped, but used in our executable |
=> Update NuGet packages 2024-11-09

src/Umbraco.Cms.Api.Management/Controllers/PartialView/ByPathPartialViewController.cs, src/Umbraco.Cms.Api.Management/Controllers/PartialView/DeletePartialViewController.cs, src/Umbraco.Cms.Api.Management/Controllers/PartialView/Folder/ByPathPartialViewFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/PartialView/Folder/DeletePartialViewFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/PartialView/UpdatePartialViewController.cs, src/Umbraco.Cms.Api.Management/Controllers/Script/ByPathScriptController.cs, src/Umbraco.Cms.Api.Management/Controllers/Script/DeleteScriptController.cs, src/Umbraco.Cms.Api.Management/Controllers/Script/Folder/ByPathScriptFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/Script/Folder/DeleteScriptFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/Script/UpdateScriptController.cs, src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/ByPathStylesheetController.cs, src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/DeleteStylesheetController.cs, src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Folder/ByPathStylesheetFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Folder/DeleteStylesheetFolderController.cs, src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/UpdateStylesheetController.cs
Hopefully fixes https://github.com/umbraco/Umbraco.Cloud.Issues/issues/806
Adds catch all patches for the endpoints that end with a path to make Azure Web Apps happy
- Ensure endpoints still work locally
=> Make catch all endpoints for those ending with a path

src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/menu/section-sidebar-menu/section-sidebar-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
A few UI Updates, to test new git setup.
adding auto-height and auto-width to some fields and adjusting the h3 in the sidebar menu.
=> Feature: minor UI updates

src/Umbraco.Core/Constants-Configuration.cs, src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs, src/Umbraco.Core/Models/CacheEntrySettings.cs, src/Umbraco.Core/Models/CacheSettings.cs, src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs, src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheMockTests.cs, tools/Umbraco.JsonSchema/UmbracoCmsSchema.cs
Exposes the cache settings in the json-schema file. To make it completely explicit I changed from named options to regular entries in the settings class.
- Ensure the Cache settings are exposed
- Ensure the cache logic works as expected
=> Explicit cache entry settings and expose cache settings in json schema

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
This PR removes a lot of obsolete attributes from the extension methods.
As long as you would like to actually have IPublishedContent returned, this is stille the most effective way.
We need to document cases where you only need the keys.
=> Removed a series of obsolete attributes

src/Umbraco.Core/Services/DocumentUrlService.cs
After https://github.com/umbraco/Umbraco-CMS/issues/17443 the urls without a domain is reversed twice.
- Setup structure without setting a domain. E.g. the starter kit and verify urls looks correct both inbound and outbound
=> Fixed issue with double reversed url segments

src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/bind-server-validation-to-form-control.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/mixins/form-control.mixin.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/types.ts
Validate on pristine change to avoid empty messages floating the system.
As well optimizing some of the general implementation.
**This fixes the following case:**
- Have a variant document with Block List (should not vary, no mandatory or validation configured)
- Add a Blocks.
- Save & Publish
- Open Split view, and see validation issues appearing.
This will fix the case so no validation issues appears.
=> Hotfix: Validate form control on pristine change

src/Umbraco.Cms.Api.Delivery/Services/RequestCultureService.cs, src/Umbraco.Core/DeliveryApi/ApiPublishedContentCache.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17476
Since the underlying code expects `null`, `*` or a valid culture, I found it best to handle this in the Delivery api code that determines what culture was set on the request.
###Testing
Check the reproduction steps in the linked issue, but be sure to either run raw curl commands or run it trough postman as the swagger UI adds language headers to the request. And don't forget to test the negatives either 😉
=> Fix invalid culture on delivery api request

src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
When navigating away from the Document Workspace Info view, the Links component will throw an error as the `_unique` is `undefined`.
Given how `observeMultiple` works, it should be expected that `_unique` may be `undefined` when navigating away from the Info view, so rather than throw a console error, we don't attempt to request the link URLs.
=> Bugfix: Document Workspace Info Links error

src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
The media section modal is not closed and the media tree is not updated immediately after creating a media folder/ item
Fix: When creating a new media item we used the wrong URL param to get the parent entity type. 
https://github.com/user-attachments/assets/273cd77d-de79-4541-b356-56383441f10b
=> Hotfix: Media section modal is not closed and the media tree is not updated immediately after creating an media folder/ item

src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-button.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/base.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/types.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-extensions-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
In a scenario where a user would like to switch back from Tiptap to TinyMCE, the data structure of the "toolbar" configuration triggered an infinite loop, causing the browser tab to become unresponsive. This PR resolves that issue.
In doing so, we found that it is possible to attempt the migration of a TinyMCE toolbar configuration over to the new Tiptap toolbar data structure. To note, not all toolbar features are available, (e.g. style select, character map, et al), but the majority are available.
It was also noticed that the Tiptap toolbar (on the property-editor) was still displaying buttons as enabled regardless whether the underlying Tiptap Extension had been registered. This PR adds support to disable toolbar buttons if the Tiptap Extension is unavailable.
=> Hotfix: Tiptap toolbar data fix

src/Umbraco.Core/Services/DocumentUrlService.cs, src/Umbraco.Infrastructure/Routing/RedirectTracker.cs
Fixed issue with redirects due to culture being empty string when null was expected.
Furthermore, using IPublishedUrlProvider instead of DocumentUrlService directly. to ensure you can use your own routing stuff
- Ensure redirects are created as expected when publishing under new names.
=> Fixes to redirect management

src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/media-upload.extension.ts
Fixes #17505.
When using the browser's "Copy image" feature, a HTML fragment is copied to the Clipboard, when pasting this into the Tiptap RTE, both the Image and Media Upload extensions were being triggered, showing duplicate images (one remote, one uploaded).
This fix prevents any image references that are pasted in from a HTML fragment to be uploaded to the server. The original (source) URL will be used for external image references.
=> Hotfix: Tiptap media upload, prevent pasted HTML fragments

Directory.Packages.props, global.json, tests/Directory.Packages.props
Updated nuget packages 2024-11-12
| Name  | Old Version | New Version | Note |
| ------------- | ------------- | ------------- | ------------- |
| OpenIddict.*  | 6.0.0-preview1.24504.78 | 6.0.0-preview3.24551.41  |  |
| HtmlAgilityPack  | 1.11.70  | 1.11.71  |   |
| MessagePack  | 2.5.187  | 2.5.192  |   |
| Microsoft.*  | 9.0.0-rc.2.*  | 9.0.0  |   |
| System.*  | 9.0.0-rc.2.*  | 9.0.0  |   |
| Microsoft.Extensions.Caching.Hybrid  | 9.0.0-preview.9.24507.7  | 9.0.0-preview.9.24556.5  | will not be in final as part of .NET 9 release   |
=> Update NuGet packages 2024-11-12 + Final .NET 9

src/Umbraco.Core/PublishedCache/IMediaCacheService.cs, src/Umbraco.PublishedCache.HybridCache/DocumentCache.cs, src/Umbraco.PublishedCache.HybridCache/MediaCache.cs, src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheMockTests.cs
- Implements the rest of the `NotImplemented` methods for media cache.
- Removes use of StaticServiceProvider in document cache
- To test the publish URL provider in document cache, you can use `@Model.GetCultureFromDomains()` in the template
- To test the media cache, use the delivery API to query the media.
=> V15: Implement not-implemented methods for media cache

src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/templates/document-type-workspace-view-templates.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17513
Fixed issue where it was not possible to remove the last (default) template from a doc type.
The issue was because the payload was wrong 
```json
{
...
"defaultTemplate": {
"id": ""
}
...
}
```
instead of the expected
```json
{
...
"defaultTemplate": null
...
}
```
=> Allow removing the default template from doc types

src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-entries.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts
An oversight in relation to hot fix of https://github.com/umbraco/Umbraco-CMS/pull/17482
Its needed to ensure that we in general always use the Block Variant ID, as this one can de different depending on the configuration of the Block Element.
This fixes this case:
Have a project with two languages.
Create a document type that varies by culture with a property with a Block Editor of choice.
Create a Block using a Element that does not vary by culture.
Create a document with one block.
Experience that the block was not exposed — this has been fixed as of this PR (so it gets exposed)
Notice in calls to the server that the expose entry for the Block was with a culture, and with this fix it is without.
=> Hotfix: expose using block variant

Directory.Build.props, src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs, src/Umbraco.Core/IO/ViewHelper.cs, src/Umbraco.Core/Services/OperationStatus/TemplateOperationStatus.cs, src/Umbraco.Core/Services/TemplateService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TemplateServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17458
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16443
Template file names should be Pascal-case. We can do this my having a titlecase on the original alias.
Furthermore, ensure templates cannot be delete when it is a master template
- See original issues but use swagger to delete a master template
=> Fixes to templates: Do not allow deletion of masters and  ensure file names are pascal case

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/16303
Since settings element type can be nullable, but deleting (settings) element type, doesn't remove reference in block configuration itself, we should use a fallback value if element type isn't found.
I used `icon-science` as fallback icon as this is the default element type icon and to align text at content/setting element type node previews.
Besides that it also just show the edit button only if the settings element type is found (the alias has a value as we add a fallback for name and icon), as opening an element type that doesn't exists would fail anyway.
As the new backoffice in Umbraco 14 it close to release, this is just a simple fix for current backoffice, but we should …
=> Block settings unavailable element type

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
If there's an existing issue for this PR then this fixes issues described here https://github.com/umbraco/Umbraco-CMS/discussions/17531
TinyMCE property editor supports readonly mode, but it didn't work, because it sets `readonly: 1`.
According to documentation https://www.tiny.cloud/docs/tinymce/6/editor-important-options/#readonly `readonly` is a boolean property, so value should be `true/false`.
Readonly mode of TinyMCE allows to select/highlight text, but not edit, insert/paste, use toolbar actions or shortcuts to modify content.
**Before**
**After**
Tested with TheStarterKit package and include the following `SendingContentNotification` handler and composer in `Umbraco.Web.UI` project: [Test.zip](https://github.com/user-attachments/files/17781839/Test.zip)
It may not strictly require …
=> TinyMCE readonly mode

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediaentryeditor/mediaentryeditor.less
I noticed on a few on our projects the image (mainly at "root" Media item in crops sidebar) in flexbox container can grow and thus shrink crops on right side.
In v14 this looks correct.
**Before**
**After**
=> Don't shrink crops container on right side

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs, src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs, src/Umbraco.Infrastructure/Mail/BasicSmtpEmailSenderClient.cs, src/Umbraco.Infrastructure/Mail/EmailSender.cs, src/Umbraco.Infrastructure/Mail/Interfaces/IEmailSenderClient.cs, tests/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
This pull request is a response to the following discussion  [Support for SMTP OAuth authentication](https://github.com/umbraco/Umbraco-CMS/discussions/17142)
This pull-request separates til SmtpClient out from EmailSender.cs to it's own abstraction of IEmailSenderClient/BasicSmtpEmailSenderClient to make it easier for package-authors and umbraco developers to support more ways of sending out e-mails without Umbraco having to take on supporting every variation of OAuth authentication imaginable.
The linked discussion contains more details as to why and actual OAuth2 implementation for SMTP doesn't seem feasible.
The pull request will allow developers to replace the client like so (microsoft.graph example) …
=> Support for SMTP OAuth authentication through easier IEmailSenderClient implementation

src/Umbraco.Infrastructure/PropertyEditors/SliderPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/SliderValueEditorTests.cs
Fixes the backend part of #17546.
The issue was that the `SliderPropertyEditor` assumed that sliders could not be decimal values; however, they can. This can also be seen in the `SliderValueConverter` and in the models generated by the model builder, which all assume a `Decimal` value. 
This fixes the backend issues, however, the UI looks quite weird still, when not in range mode the decimals aren't showing, and when in range mode they show but aren't properly formatted showing float imprecision I.E `0.30000000001`. Edit: This turned out to be a UUI bug, I've made a fix that has already been merged in UUI
For testing see original issue
=> V14: Use decimal in slider property editor

src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs, src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
Fixes #17436 
The problem was that the upgrader only ever ran either CMS upgrades or package upgrades, this has been updated so both are run if needed. 
Not that the CMS and package upgrades run in their own separate scopes, so it's safe to do it in a single notification handler 😄 
Add both a CMS NoopMigration in `UmbracoPlan` and a package plan, unable unattended upgrades, and ensure both are run if needed. 
Example package migration plan 
```C#
using Umbraco.Cms.Core.Packaging;
using Umbraco.Cms.Infrastructure.Migrations;
public class MyMigrationPlan : PackageMigrationPlan
{
public MyMigrationPlan() : base("MyPackage")
{
}
protected override void DefinePlan() {
To<NoopMigration>(Guid.Parse("AD8AF4BF-9AE1-42BC-9709-CA64891BA92D"));
}
}
````
=> Run both cms and package migrations in upgrader

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttongroup.directive.js, src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
As requested by @nul800sebastiaan, this PR targets the `release/13.0` branch. My changes should however fix the issue both Umbraco 12.3 and 13.0.
For Umbraco 12.3, @madsrasmussen made some changes to the `<umb-button-group />` directive which adds support for labels on sub buttons. Previously a label was only supported on the default button: https://github.com/umbraco/Umbraco-CMS/commit/cb4d8e34ce9e2b124a2b1c74b4a4309ae456d64f
In my [**Skybrud Redirects Import**](https://github.com/skybrud/Skybrud.Umbraco.Redirects.Import) package I had specified both a label and a label key for the sub buttons (as this worked on the default button). But with the changes to the `<umb-button-group />` directive, both the label and the localized label associated with the label key are now shown.
This PR …
=> Added fix for <umb-button-group /> label issues

src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/table/media-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/order-by/order-by.element.ts
Fixes #17461.
Given that "Name" is a default column in both the Document and Media collections, the option to set the Name as the default sorting column was not possible.  This PR adds the "Name" option to the Order By select configuration.
This PR also adds localization support to the column header labels.
=> V15: Collection: Adds "Name" to Order By options

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
If there's an existing issue for this PR then this fixes #16011
See #16011 for an issue description 😄 
1. Blocks in RTEs should still work for content.
2. There should be no issues creating new media items with RTEs.
- Test this both by uploading media directly to a media folder, and by creating media items explicitly (as outlined in the linked issue).
**Friendly testing note:** Blocks in RTEs are not supported for media items, so don't spend time trying to get them to work there 😛
=> Fix RTE console error when blocks are not available

src/Umbraco.Web.UI.Client/src/packages/settings/welcome/settings-welcome-dashboard.element.ts
We are currently using h1 for headlines in the settings welcome dashboard. I have updated these to use the box headline prop instead to keep the UI consistent.
**Updated dashboard**
=> Aligning Settings welcome dashboard headlines

src/Umbraco.Web.UI.Client/src/packages/core/collection/components/collection-selection-actions.element.ts
Fixes #16698.
Previously, in an Entity Bulk Action, the `entityType` property was empty.
This PR wires up the `entityType` value for the bulk actions.
=> V15: Entity Bulk Actions: Pass in `entityType`

src/Umbraco.Infrastructure/Manifest/ManifestParser.cs
This fixes #14462
Issue #14462 denotes that on Linux `Directory.GetFiles` as used by `GetManifestFiles` to load package manifest files from disk is not guaranteed to return the list of files in a set order. This is a problem because the order the manifests are loaded also dictates the order any manifest script files are loaded in the back office. This can become a problem if you have scripts that rely on scripts from another package to be loaded first, such as Vendr Checkout needing Vendr to be loaded first.
This PR updates the `GetManifestFiles` method to sort the list of retrieved file paths alphabetically before returning them thus ensuring a consistent and expected behabiour.
=> Sort manifest file paths alphabetically

src/Umbraco.Core/Routing/UriUtility.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UriUtilityTests.cs
If there's an existing issue for this PR then this fixes #16585
The content routing has a strange discrepancy in routing:
- When requesting `http://some.where/path/////`, the routing resolves `http://some.where/path`
- When requesting `http://some.where/////`, the routing explodes 💥
See #16585 for details.
Content routing should work both at root and page level, despite being requested with multiple trailing slashes.
=> Handle "all slashes" routes

src/Umbraco.Core/EmbeddedResources/Snippets/Breadcrumb.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/ListAncestorsFromCurrentPage.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/ListChildPagesFromCurrentPage.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/ListChildPagesOrderedByDate.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/ListChildPagesOrderedByName.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/ListChildPagesWithDoctype.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/Navigation.cshtml, src/Umbraco.Core/EmbeddedResources/Snippets/SiteMap.cshtml, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/StandardMvc-Package.xml
- Use the updated `PublishedContentExtensions` methods in the following partial view snippets:
- Breadcrumb;
- List Ancestors From Current Page;
- List Child Pages From Current Page;
- List Child Pages Ordered By Date;
- List Child Pages Ordered By Name;
- List Child Pages With Doctype;
- Navigation;
- Site Map.
- Create a simple content type **with template** and a `title` string property;
- Create a nested content tree structure, something like:
```
Home
- Child 1
- Grandchild 1
- Grandchild 2
- Child 2
- Grandchild 3
- Great-grandchild 1
- Child 3
- Grandchild 4
```
- Create new Partial Views from the following snippets (using the Partial View tree in the Settings section):
- Breadcrumb;
- List Ancestors From Current Page;
- List Child Pages From Current Page;
- List Child Pages …
=> V15: Update navigation references in Partial Views

src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Factories/MediaPresentationFactory.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Document/Item/DocumentItemResponseModel.cs, src/Umbraco.Cms.Api.Management/ViewModels/Media/Item/MediaItemResponseModel.cs
Adds structural information to the document and media item endpoints, specifically `parentId` and `hasChildren`.
Create a document and media item with children, and without
Ensure that the child has the parent key, and the parent has `hasChildren` set to true. and the one without has neither
=> V15: Add information to item endpoints

src/Umbraco.Infrastructure/Cache/MemberRepositoryUsernameCachePolicy.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17097
- Adds a cache key for `GetByUserName`
=> Add cache key to GetByUserName

src/Umbraco.Web.UI.Client/src/apps/app/app-oauth.element.ts, src/Umbraco.Web.UI.Client/src/apps/app/app.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/utils/path/has-own-opener.function.ts
Fixes #17453
* Shows only a loader for a normal login flow
* Shows the umb-app-error component only if the flow fails (either in the main window or a popup)
* Fixes an error where `hasOwnOpener` did not work (at least not on the Vite server)
1. Log in as normal and verify that you do not see a "flash of oddly styled content" but instead a uui-loader (you probably have to slow down the network requests)
2. Try and force a session timeout, e.g. by changing the access_token in Local Storage and performing some request, e.g. going to a content page
3. You should now see the login timeout overlay
4. Verify that the popup is closed after login and that you only see a loader inside the popup
**Hint:** You can force the "login landing page" by going to …
=> V15: Show a loader during the login procedures rather than oddly styled content

src/Umbraco.Core/Services/DocumentUrlService.cs, src/Umbraco.Core/Services/IDocumentUrlService.cs, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest_hidetoplevel_false.cs
Fixes #17548
This fixes two issues with routing
1. If multiple domains was assigned with the same culture (#17548) it exploded when showing the urls in backoffice
2. If you have multiple roots  (and HideTopLevelNodeFromPath = true), then only children of the first root respected the HideTopLevelNodeFromPath.
1. Assign multiple domains with the same culture to one item, and ensure it can still list urls.
2. Setup multiple roots and have children of each with the same name. - Verify only the top one is routable (like in v13)
- Also just be creative in weird cases - all test is welcome :)
=> Fixes routing issues

src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs, src/Umbraco.Core/Strings/DefaultShortStringHelperConfig.cs
If there's an existing issue for this PR then this fixes #15939
#15939 describes a difference between how content URL segments and media file names are encoded. However, the issue description is slightly off point - and as it happens, the difference is a feature 😄 albeit a somewhat confusing one, specially when char replacements are added to the mix.
Starting with the latter, with `RequestHandler:EnableDefaultCharReplacements` set to `true` (which is the default), specific characters to be replaced with URL friendly alternatives (e.g. "å" is replaced by "aa" in the default configuration). These char replacements apply to both URL segments and file paths.
On top of the char replacements we have `RequestHandler:ConvertUrlsToAscii`, which is set to `"try"` by default. This setting _only_ …
=> Add ASCII file name conversion

src/Umbraco.Web.UI.Client/src/packages/ufm/components/link/link.component.ts, src/Umbraco.Web.UI.Client/src/packages/ufm/components/link/link.element.ts, src/Umbraco.Web.UI.Client/src/packages/ufm/components/manifests.ts
To support rendering values from the Multi-URL Picker editor, a new UFM Link component has been added,
using the syntax `{umbLink: propertyAlias}`.
=> Adds UFM Link component

src/Umbraco.Core/Models/MediaType.cs, src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
- Makes system media types clonable
- Note that the solution is kinda hacky. We cannot change the alias of a system media types, and thus this PR, enables changing of the alias of a system media type, only if we're cloning.
- We also need to make the `ContentTypeBase.DeepCloneWithResetIdentities` overrideable, so we don't have to have this weird function in `MediaType`.
- Try to copy the "Folder" Media type.
=> V15: Make system media types clonable

src/Umbraco.Web.UI.Client/src/packages/core/debug/context-debug.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/debug/debug.element.ts
Fixes #17410
This pull request addresses issue #17410 by enhancing how asynchronous contexts are handled during the UmbContextDebugRequest event. Some contexts, such as globalContexts, do not react instantly to the event, causing incomplete debug information. The solution implemented in this pull request involves storing the inner `event.instances` map in a state property and rendering it out on the fly instead, which ensures that Lit can figure out the changes to the object.
**Before (3 contexts on the news dashboard)**
**After (83 contexts available)**
1. Add <umb-debug visible></umb-debug> to the news dashboard or in a modal.
2. Verify that all contexts are accurately displayed.
=> V15: Debug missing contexts

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Fixes #17573
The lead char should be kept (`#` or `?`) even when re-opening a link. Otherwise, the editors will not be able to see whether it is an anchor or a querystring, nor will they be able to edit it. The placeholder of the field also suggests that the editor put in a `#` or `?` to indicate whether it is an anchor or a querystring.
=> V13: Lead char gets removed when reopening a link in the rich text editor

src/Umbraco.Web.UI.Client/src/packages/core/entity-action/entity-action.event.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/event/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/event/server-file-renamed.entity-event.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/event/types.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/modal/rename-server-file-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/modal/rename-server-file-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/rename-server-file.action.kind.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/rename-server-file.action.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/workspace-redirect/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/workspace-redirect/workspace-redirect.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/workspace/partial-view-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/templating/scripts/workspace/script-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/templating/scripts/workspace/script-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/stylesheet-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/views/code-editor/stylesheet-code-editor-workspace-view.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16488
This (PR) addresses the issue where a renamed file system workspace enters an "undefined" state. The problem arises because the file name serves as the unique identifier for the workspace. When the file name is changed, the unique identifier is also changed, causing the workspace to become "undefined." To resolve this, we need to notify the workspace about both the unique before the change and after the change, allowing us to target the correct workspace and redirect it to the new path.
The PR introduces the `UmbServerFileRenameWorkspaceRedirectController`, which listens for a `ServerFileRenamed` action event. This event includes both the previous and new uniques. If the currently open workspace matches the event, the controller …
=> Bugfix: Redirect when server file is renamed

src/Umbraco.Core/Services/ContentService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Copy.cs
In v14+ it is possible to target the origin of a branch copy. There is a bug though where it copies the origin twice instead of just once.
Setup
Faulty behavior
Fixed behavior
=> Fix copy document with descendants onto self

build/azure-pipelines.yml, build/nightly-E2E-test-pipelines.yml, tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Template/Templates.spec.ts
We have updated our pipeline to run our E2E in parralization to decreased the time it takes for out tests to run. To do this we have implemented the usage of [Sharding  ](https://playwright.dev/docs/test-sharding)from playwright, which allows us to split our tests up. Currently we have split our tests into 3 shards
=> V15 QA add parallelization of e2e tests

src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17670
The PR aims to clean up how we set/update the RTE property value so we don't get the "Discard Changes" dialog unless there has been user updates to the value.
How I went about this:
**Allow the internal property _value to be undefined.**
The property value can be undefined but the internal _value could only be the full value object with blocks. By aligning these it is easier to keep them in sync. The new code clears all internal the values and only sets the block data if we get a markup value.
**Handles the Tip Tap empty `<p></p>` tag (https://github.com/ueberdosis/tiptap/issues/154)**
This issue wasn't directly linked to this issue but for us to be able to check for an empty tip tap editor I encountered this issue. Tip Tap has a …
=> Hotfix: unnecessary Discard Changes dialog for RTEs

src/Umbraco.PublishedCache.NuCache/ContentStore.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15569 and https://github.com/umbraco/Umbraco.Deploy.Issues/issues/145.
When content types (document or media types) are saved/changed, the content cache (NuCache) is updated via cache refreshers to ensure all content items are stored using the updated schema. However, sometimes a `PanicException` was thrown in `ContentStore`. This was especially noticeable when doing a large amount of changes in a single scope (Unit of Work), like Deploy does when deploying schema changes or importing content and/or schema. So much so, that we decided to add a special error message if a Deploy import failed due to an unhandled exception 🙃
However, with the recent Deploy feature that imports a ZIP archive …
=> Fix `PanicException: failed to get child with id=` after updating content types

Directory.Packages.props, src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj, src/Umbraco.Cms.Persistence.EFCore/Locking/SqlServerEFCoreDistributedLockingMechanism.cs, src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj, src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj, src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj, src/Umbraco.Web.Common/Umbraco.Web.Common.csproj, tests/Directory.Packages.props, tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs, tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
Updated nuget packages and took explicit dependencies on a series of new, to avoid nested dependencies having vulnerabilities 
Also cherry picked the fix to the memory leak in the integration tests + a fix for sqlserver
=> Updated NuGet Packages for v13

src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17571
- Adds Content to `TreeAccessTemplate`, as if you have access to content, you are allowed to choose a template for said content.
- Create multiple templates
- Create a content type, with multiple allowed templates
- Create a user that is only part of the editor user group
- Login
- Create some content with the content type, assert you are able to choose a template
=> V15: Add content access to access templates

src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16882
The fix has been applied to tree items in general, media, and document tree items.
=> Hotfix: Do not set icon color if item is active

src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry-inline.test.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.test.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.test.ts, src/Umbraco.Web.UI.Client/src/packages/ufm/controllers/ufm-virtual-render.controller.ts
Fixes a regression in 15.1-rc where the block element did not render its default view in the Tiptap editor.
Due to the way browsers treat custom elements, they are not allowed to add attributes and/or child elements upon creation. They must wait until the `connectedCallback`. That means any controller that wants to add elements should also wait until the host is connected (`hostConnected`).
This moves the logic from the constructor to the `hostConnected` callback in the UFM render controller.
1. Test that blocks work in Tiptap and TinyMCE
2. Test that the UFM syntax works in property descriptions as well as block labels
=> V15 RC: Blocks do not work in the rich text editors

src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueConverter.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17655
- When in a block and using Model.Value(), the actual value gets passed (integer), and thus we were missing a check for that in the converter, this PR remedies that
- Follow steps in original issue, or if you want a quick test:
- Create an element type with a decimal property called "dec"
- Create a doc type with allowed as root, with a decimal property called "decimal", and a blocklist using the prior element type called "blocklist"
- Create content with that doc type, with the values being whole numbers (aka integers).
- Use this template for the doc type:
```
@using Umbraco.Cms.Core.Models.Blocks
@{
Layout = null;
BlockListModel …
```
=> v14: DecimalConverter - add check for integer

src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user.context.ts
Make the is-current user context load method wait until value is set — this should fix the flaky tests
=> Fix: is-current user text

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entries.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-entries.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/content-property-dataset.context-token.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/content-property-dataset.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/index.ts
This improves the modal path specification of Block Editors. But there is still a case to be handled — So I have created a task for such. But introducing this solve most cases for now.
Test by following:
Have a document that varies by culture.
Open split view.
Have a Block Editor that does not vary.
Verifying that opening a modal from a Block only opens a single modal — before this fix it would open two.
=> Feat: Content Property Datatset Context Token

src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs
- Clicking the "Reload memory cache" button in the PublishStatus button was extremely slow, turns out we where getting all the document URLs from the database.
- Switched to InitAsync to mimic behavior from when we start the site.
- Have a site with lots of nodes
- Click the "Rebuild memory cache" button in the PublishedStatus dashboard
- It should no longer be extremely slow
=> v15: Use init instead of rebuild for urls when refreshing cache

src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_1_0/RebuildCacheMigration.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_2_0/RebuildCacheMigration.cs, src/Umbraco.PublishedCache.HybridCache/ContentCacheNode.cs, src/Umbraco.PublishedCache.HybridCache/ContentData.cs, src/Umbraco.PublishedCache.HybridCache/DependencyInjection/UmbracoBuilderExtensions.cs, src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs, src/Umbraco.PublishedCache.HybridCache/Persistence/IDatabaseCacheRepository.cs, src/Umbraco.PublishedCache.HybridCache/Serialization/HybridCacheSerializer.cs, src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs, src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheMockTests.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17649
- The root cause of the issue, was that Redis was serializing `object` properties differently than the memory cache, resulting in value converters nok being able to convert the value.
A `string` value on a `object` property serializes to a `JsonElement` with Redis: 
And to a string with memory cache: 
This PR remedies this issue, by implementing a custom serializer.
- Setup redis, i used docker and the `redis/redis-stack:latest` image
- It can be done with this command in your terminal`docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest`
- Add this snippet to your program.cs, to enable redis caching 
```
builder.Services.AddStackExchangeRedisCache(options =>
{
options.Configuration = …
```
=> V15: Add custom serializer for hybrid cache

src/Umbraco.Cms.Api.Common/Configuration/ConfigureUmbracoSwaggerGenOptions.cs, src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
This is a simplified (alternate) approach to #15383 
All credits go to @nikcio for excellent investigation 🚀 
Custom APIs and OpenAPI docs are required to test this PR.
**Add this to configure a custom OpenAPI doc called "My API":**
```csharp
public class MyCustomSchemaOptions : IConfigureOptions<SwaggerGenOptions>
{
public void Configure(SwaggerGenOptions swaggerGenOptions)
{
swaggerGenOptions.SwaggerDoc(
"My API",
new OpenApiInfo
{
Title = "My API pretty-name",
Version = "1",
Description = "All endpoints for My API"
});
}
}
public class MyCustomSchemaOptionsComposer : IComposer
{
=> builder.Services.ConfigureOptions<MyCustomSchemaOptions>();
}
```
**Add this to `Program.cs` to setup minimal APIs:**
```csharp
ApiVersionSet apiVersionSet = …
```
=> Support minimal APIs in OpenAPI spec and Swagger UI

src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs, src/Umbraco.Cms.Api.Common/Security/Paths.cs, src/Umbraco.Cms.Api.Delivery/Controllers/Security/CurrentMemberController.cs, src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs, src/Umbraco.Cms.Api.Delivery/Services/CurrentMemberClaimsProvider.cs, src/Umbraco.Cms.Api.Delivery/Services/ICurrentMemberClaimsProvider.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/17508
This PR adds a "user info" endpoint to the Delivery API, to access basic information about authorized members. See the linked discussion for details on the motivation for adding this endpoint.
The "user info" endpoint is part of the [OpenId Connect core spec](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo).
This implementation returns a few of the [standard claims](https://openid.net/specs/openid-connect-basic-1_0.html#StandardClaims), all of which are subject of availability:
- `sub` (required claim)
- `name` (if available)
- `email` (if available)
On top of this, the member groups (if any) are returned in the `role` claim.
The implementation is build to be …
=> Add "user info" endpoint for the Delivery API

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Web.BackOffice/Controllers/ContentController.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/ContentControllerTests.cs
If there's an existing issue for this PR then this fixes #15943 and #15850
When content items with similar (not exactly the same) names are created, URL collisions can happen. See the linked issues for examples.
The content items _can_ still be published and become available via the Delivery API (by ID), but they will not be routable. However, at this point, there is no indication of that, unless one looks at the "Info" section:
This PR adds a warning at publish time, to emphasise the issue:
We already have a potential warning at play when publishing content - the "no domains have been configured" warning:
The purpose of this warning is partly the same as the new warning added by this PR: to tell the editors that content is not routable.
As it happens, the default culture is always …
=> Warn about un-routable content at publish time

.gitattributes, templates/UmbracoProject/Dockerfile
Fixes issues with Docker in v15, fixes #17648. There is 2 issues
1. The image currently tries to build using dotnet 9
2. We changed the build server to windows, resulting in files having `CRLF` line endings, however the Docker images are running on Linux containers which expects `LF` 
Download the artifacts and follow #16815
=> V15: Fix docker

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17650
Block List and Block Grid editors both set an empty block object property value when they are loaded. This results in a "discard changes" dialog because the stored data isn't the same as the new one.
The PR prevents the editors from setting the initial empty value.
=> 15.1/hotfix/block editors discard changes on document load

src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
Fixes #17748
Tinymce inserts links using the a-tag, which is triggering our navigation because we cannot control tinymce's rendering. We can however control which links we trigger on the for the 'click' event by using `composedPath()` and ensuring that we are inside one of the block entry elements.
=> V15: TinyMce triggers navigation when clicking links

src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Fixes issue when removing tab from a document type, but it was only a problem when user was on another tab than the one to be deleted.
Fixes #17771
see
https://umbraco.slack.com/archives/C027U315T54/p1733894530378609?thread_ts=1733894482.267889&cid=C027U315T54
Notice, the problem seemed to be a re-direct and this was not needed anymore, the router seems to handle this fine by its own redirects.
=> hotfix: no need to redirect when removing tab. router handles this fine

src/Umbraco.Web.UI.Client/src/packages/core/workspace/controllers/workspace-is-new-redirect.controller.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace-editor.element.ts
This fixes so you can navigate between documents via the browser navigation (forth and back in history)
=> Hotfix: Browser navigation between Documents

src/Umbraco.Core/DeliveryApi/ApiContentRouteBuilder.cs, src/Umbraco.Core/Extensions/PublishedContentExtensions.cs, src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs, src/Umbraco.Core/Routing/UrlProvider.cs, src/Umbraco.Core/Services/PublishStatus/PublishStatusService.cs, src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishStatusServiceTest.cs, tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentRouteBuilderTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/DeliveryApiTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlImageSourceParserTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
FIxes https://github.com/umbraco/Umbraco-CMS/issues/17768
- We stopped caching null values with https://github.com/umbraco/Umbraco-CMS/pull/17727, this uncovered a bug with all our FriendlyPublishedContentExtensions, as it would not filter by only published content
- This PR refactors every single one of those (and obsoleted the old ones), to use the `IPublishStatusQuery` service, to check if a given key is published or not, this turns a 30s operation into 0.5s (and this is cached), and after caching, down to 1-10ms depending on size 😁 
- Create a doc type with allow as root set to true
- Create a doc type named "Child"
- Allow "Child" as child on the first doc type
- Create a parent node
- Create 500 child nodes
- Try using the methods, like `Children` or `Descendants` it should no …
=> V15: Fix friendly content extension performance

src/Umbraco.Core/Services/DomainService.cs
- Fixes issue found by @nhudinh0309, where you could not change the language on a domain.
- This happen because we did not change if the language changed, only if the domain name changed, this PR remedies that.
- Create another language, so that you have at least 2
- Create a content type with allow as root set to true
- Create some content with that type
- On the document, go to culture and hostnames, and create 2 of the English language, for example `/en/test` & `/en/testtwo`
-  Now try switching on of them to another language, this should now work 🙌
=> V15: Check if language has changed when updating domains

src/Umbraco.Cms.Api.Management/Controllers/Document/GetPublicAccessDocumentController.cs, src/Umbraco.Core/Services/IPublicAccessService.cs, src/Umbraco.Core/Services/PublicAccessService.cs, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/repository/public-access.server.data.ts
If there's an existing issue for this PR then this fixes #17709
See the linked issue for a description and steps to reproduce 😃 
Verify that:
1. Public access can be _added_ and _updated_ in the structure below a protected document, without affecting the ancestor protection.
2. Public access can be _removed_ from the structure below a protected document, without affecting the ancestor protection.
3. Public access can be _removed_ from an ancestor document, without affecting any descendants with explicit public access configuration.
=> Don't overwrite ancestor configurations for public access

src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs, src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
Improves the dashboard resilience reported in https://github.com/umbraco/Umbraco-CMS/issues/17114 for v13 and the logs hold better information when things go wrong with rebuilding
=> Make sure Examine dashboard still functions when an index is corrupt

src/Umbraco.Web.UI.Client/src/common/filters/simpleMarkdown.filter.js, src/Umbraco.Web.UI.Client/src/common/filters/simpleMarkdown.filter.js.js
Fixed an issue where bold markdown would not work inside a property description #17646 
- Add a property description to a new or existing property which contains `**` around a couple of different words. 
- Save the document type.
- Go to Content and view an instance of that Document Type
- View the lovely formatted property description. Previously the style would break. This fix now renders the wrapped markdown words using `**` in bold.
=> V13 Fixes #17646 where bold markdown does not work in a property description 

src/Umbraco.Infrastructure/Cache/MemberRepositoryUsernameCachePolicy.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
- There was a bug where you could still login as a member for a little while, after you've deleted the member.
This was caused by the userNameCache not being cleared in the member repository.
- Clears the user name cache in the `MemberRepository` when members are updated/deleted
- Create RegisterMember.cshtml partial view from snippet
- Create Login.cshtml partial view from snippet
- Create LoginStatus.cshtml partial view from snippet
- Create a doc type `ContentPage` and in its template add:
```
@using Umbraco.Cms.Core.Services;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ContentPage>
@inject IMemberService MemberService
@{
Layout = null;
var isLoggedIn = …
```
=> V13: Clear username cache

src/Umbraco.Web.Website/Controllers/UmbLoginStatusController.cs
- Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17013
- You can log out after the member you are logged in as has been deleted.
- Create `RegisterMember.cshtml` partial view from snippet;
- Create `Login.cshtml` partial view from snippet;
- Create `LoginStatus.cshtml` partial view from snippet;
- Create a doc type `contentPage` and in its template add:
```cshtml
@using Umbraco.Cms.Core.Services;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.ContentPage>
@inject IMemberService MemberService
@{
Layout = null;
var isLoggedIn = Context.User?.Identity?.IsAuthenticated ?? false;
}
@if (!isLoggedIn)
{
@await Html.PartialAsync("RegisterMember")
<hr/>
<br/> …
```
=> V13: Allow anonymous calls for `UmbLoginStatusController.HandleLogout` action

src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs, src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiVersionAwareJsonConverterBase.cs, src/Umbraco.Core/DeliveryApi/IncludeInApiVersionAttribute.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Delivery/Json/DeliveryApiVersionAwareJsonConverterBaseTests.cs
- Adding support for property-level versioning for the Delivery API;
- Introducing `IncludeInApiVersionAttribute` to define API version bounds for properties. It supports both an inclusive minimum and maximum API version;
- Properties annotated with this attribute will be included in the Delivery API response only if the API version falls within the specified bounds. 
- Adding a base converter class that you can inherit from in your custom JsonConverters. It handles the System.Text.Json serialization of properties based on the Delivery API version bounds.
- Uses `IHttpContextAccessor` to access and act upon the current API version.
</br>
> Example:
```c#
public class MyModel
{
[IncludeInApiVersion(3)] // Only available from version 3 onwards
public string Property1 { get; set; } …
```
=> V14: Adding the ability to conditionally serialize version bound properties for the Delivery API

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17431
- DictionaryRepository is a little weird, as you can get dictionary items by int id, GUID & string, this means we have private classes like `DictionaryByKeyRepository` in there, wich derives from `SimpleGetRepository`
This bug was caused by not having the `.FetchOneToMany<DictionaryDto>(x => x.LanguageTextDtos, sql)`, as there is no way to put this in, in the default overrides of `SimpleGetRepository` (as this makes it no longer simple 😛)
- Long story short, this is solved by simply overriding the `PerformGetAll`, mirroring the implementation of the original <int> DictionaryRepository 👍 
- Follow steps in original issue. Here is a test controller i used to make calling the service easy (put your own keys in there instead of my …
=> v14: DictionaryRepository - override PerformGetAll

src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockEditorPropertiesBase.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockEditorPropertiesOptions.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockGridEditorProperties.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockListEditorProperties.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertRichTextEditorProperties.cs
If there's an existing issue for this PR then this fixes #17810
we're migrating all block editor data for V15 to a new data format that supports block level variance. For SQL Server, we run this migration in parallel to speed things up. Unfortunately, it turns out that certain content architectures won't support that - #17810 is an example of this.
This PR makes the parallel migration an opt-in thing, meaning one must explicitly choose to use parallel migration. It utilises the migration options that have already been put in place for opting out of the migration entirely (see [this docs article](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific/migrate-content-to-umbraco-15)).
Setup a V13 or V14 site using SQL Server. Make sure you have a backup of the …
=> Make parallel block editor migration optional

src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertLocalLinks.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/LocalLinks/ConvertLocalLinkComposer.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/LocalLinks/LocalLinkMigrationTracker.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/LocalLinks/LocalLinkProcessorForFaultyLinks.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/LocalLinks/LocalLinkRteProcessor.cs, src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_1_0/FixConvertLocalLinks.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
In v15.0.0, 2 migrations were introduced that dealt with RTE and Blocks. 
ConvertLocalLinks, which has an error regarding the string manipulation of locallinks that results in broken links.
ConvertRichTextEditorProperties, which has RTE markup transformation logic that is not executed on RTE's inside a nested structure (like blocks)
To fix this, this PR
- Updates the (original) LocalLinkRteProcessor that is ran recursively by the ConvertLocalLinks migration to execute the same markup transformation as ConvertRichTextEditorProperties
- Fixes LocalLinkProcessor to correctly transform the links
- Introduces LocalLinkProcessorForFaultyLinks that has a detector and fix for the very specifically identifiable incorrect locallink <a/> tags
- A secondary Migration that runs (a copy) of the …
=> Fix mistakes in 15.0.0 migrations

src/Umbraco.Cms.Api.Management/Factories/ReziseImageUrlFactory.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17597
- Svg's weren't support in the thumbnail endpoint, this is now fixed by just returning the SVG URL. as svg's are always scalable anyways.
=> v15: Support SVGs in thumbnail endpoint

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
This is an attempt to fix a problem after multiple reports of v15 not working on Linux machines:
- https://discord-chats.umbraco.com/t/26718591/iis-exception-at-start-up-when-running-umbraco-v15-on-rocky-
- https://discord-chats.umbraco.com/t/26747783/umbraco-15-and-dotnet-9-exception
- https://discord-chats.umbraco.com/t/23442398/umbraco-15-deploy-on-ubuntu-24-missing-microsoft-aspnetcore-
- https://our.umbraco.com/forum/using-umbraco-and-getting-started/115012-cut-by-the-bleeding-edge-has-anyone-managed-to-get-u15-stood-up-on-linux
- https://x.com/DavidBuckell/status/1869520293330670070
The problem is that we're trying to configure IIS options on a machine that doesn't have IIS installed. Curiously, if you install .NET not from the simple packages that Microsoft provides, but manually …
=> Don't add a blanket rule to allow synchronous IO, should not be necessary for the new management API

src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16884, tracked under [AB 47563](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47563) (internal HQ tracker).
This PR adds the missing change event to the re-ordering of multiple text string properties.
**To Test:**
- Create a document type with a multiple text string property.
- Create some content using the property with two or more strings and save.
- Re-order the strings, save again and confirm the re-ordering change has persisted.
=> Call change event after update of multiple text string order

src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17758
The issue is not that present any longer, but this change resolves the underlying issue.
The underlying issue was that when requesting the data-type we did not await its request, which most likely was fine for the main document type, but for data-types only used in the composition document types this was a problem.
This change simplifies things a bit by using a DataType Item Manager instead.
=> Fix #17758: V15 - Race condition breaks navigation between documents

src/Umbraco.Cms.Api.Management/Controllers/Webhook/Logs/AllWebhookLogController.cs, src/Umbraco.Cms.Api.Management/Controllers/Webhook/Logs/WebhookLogControllerBase.cs, src/Umbraco.Cms.Api.Management/Factories/IWebhookPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Factories/WebhookPresentationFactory.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Webhook/Logs/WebhookLogResponseModel.cs
- Adds the missing webhook logs endpoint.
- The entire webhook logs view is missing, so this is the backend part of that 😁 
- Using swagger
- Create some webhooks and fire them (use webhook.site to test)
- Call the logs endpoint via swagger, assert you get logs.
=> V15: Add webhooklogs endpoint

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17844
- Orders children by their sortorder.
- This is only a feature for children, so does not apply to descendants/ancestors etc.
- Create a doc type called child, with a property textstring called "Title"
- Create a doc type called root, with allow as root set to true, and the "child" doc type allowed as child.
- Create this structure in your content:
- Root
- Child One
- Child Two
- Child Three
- Child four
- Now swap the order, by clicking on root and selection the action "sort children"
- You can then use a  controller, or somewhere other, where you call the .Children on your root node,
- I did this by creating a controller, and calling `https://localhost:44339/test/index` via postman
```
using …
```
=> V15: Order children by sortorder

src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17559
by updating the container ID when a property is moved to a new container.
=> update property container id when container changed

src/Umbraco.Web.BackOffice/Authorization/ContentPermissionsQueryStringHandler.cs, src/Umbraco.Web.BackOffice/Authorization/ContentPermissionsResourceHandler.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17701
As the ContentPermissions.CheckPermissions() implicetly throws an error, I chose to fix the null ref in the consuming handlers as from a AuthorizationHandler it makes sense that we have a logged in user before checking it's permissions.
Check the steps in the linked issue and keep in mind that this fix delivers a result that is in line with other Authorization Handlers failing in any way.
=> Fix null exceptions when requesting specific content trough the backoffice APIs

src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17829, tracked under [AB 47498](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47498) (internal HQ tracker).
The linked issue raises two points:
1. Sorting is indicated by the presence of a "drag" icon, but it's not actually implemented.
2. No message displays the need for the width and height.
I don't think there's anything to do for point 2.  Whilst no message is displayed, you can't enter a new crop unless you provide all fields, so it's fairly clear the information needs to be provided, and is consistent with the other required fields of name and alias.
It should be possible to sort though, and when merged this PR will provide that functionality.
**To Test:**
- Create a few crops on a media picker data type.
- Verify …
=> Implemented sorting for media picker crops

src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/components/extension-with-api-slot/extension-with-api-slot.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/components/user-group-granular-permission-list.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17860, tracked under [AB 47493](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47493) (internal HQ tracker).
This was tricky to replicate as it doesn't happen all the time, but I could fairly consistently find that after five or six refreshes of a user group detail page open in the backoffice - i.e. `/umbraco/section/user-management/workspace/user-group/edit/{id}` - you would see what's reported in the linked issue (no granular permission details displayed, and the error in the console).
With the updates in this PR in place I could no longer see the issue.
**To Test:**
- Other than visual code inspection that the updates make sense, refresh and navigate multiple times to the user group detail and ensure the granular …
=> Timing updates for rendering and preparation of user group granular permissions details to resolve intermittent error on race condition

src/Umbraco.Core/Routing/DomainUtilities.cs, src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs, src/Umbraco.Web.Common/Extensions/PublishedContentExtensions.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17605, tracked under [AB 47518](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47518) (internal HQ tracker).
As reported in the linked issue, the recommended way of implementing a "language switcher" no longer works as of 15, due to changes in the routing and published cache.
Previously it seems we had methods to retrieve the route from a content ID, which are now obsoleted in favour of `IPublishedUrlProvider.GetUrl`.  However the old methods had a variation in that they would prefix the content ID of the node that defines the domains - see [here](https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.PublishedCache.NuCache/ContentCache.cs#L208) - which doesn't look to have been carried over.
Rather than …
=> Fix to GetCultureFromDomains extensions following changes to routing and published content cache

src/Umbraco.Infrastructure/DeliveryApi/ApiMediaWithCropsResponseBuilder.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17841, tracked under [AB 47486](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47486) (internal HQ tracker).
When requesting a media item contained within a folder by ID via the media delivery API, an infinite loop would be triggered when calculating the path.  With the PR applied the code is corrected such that this does not occur.
**To Test:**
- Create a media folder
- Create an image inside the folder
- Enable the [media delivery API](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api)
- Request the media item via the `/umbraco/delivery/api/v2/media/item/{id}` endpoint
=> Fixed infinite loop triggered when requesting media by ID in a folder via the media delivery API

src/Umbraco.Core/PropertyEditors/SliderConfiguration.cs, src/Umbraco.Core/PropertyEditors/TrueFalseConfiguration.cs, src/Umbraco.Core/PropertyEditors/TrueFalseConfigurationEditor.cs, src/Umbraco.Core/PropertyEditors/ValueConverters/SliderValueConverter.cs, src/Umbraco.Core/PropertyEditors/ValueConverters/YesNoValueConverter.cs, src/Umbraco.Infrastructure/PropertyEditors/TrueFalsePropertyEditor.cs, src/Umbraco.Infrastructure/Serialization/SystemTextConfigurationEditorJsonSerializer.cs, tests/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17833, tracked under [AB 45702](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/45702) (internal HQ tracker)
Also Fixes https://github.com/umbraco/Umbraco-CMS/issues/17099, tracked under [AB 47510](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47510)
**Reported issue:** For toggle properties set to the initial value of true, this is not working. The value is stored as false even though it is displayed as “on” in the UI.
**Background:**  If the user does not interact with a Property Editor, we do not store anything.
This is how the Client works as of v.14, and this plays well with the fact that we do not render Property Editors that the user haven't navigated to, meaning we do not guarantee that the …
=> Use data type configuration to determine default value for empty toggle and slider property values

src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/RecycleBin/RecycleBinControllerBase.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/RecycleBin/RecycleBinItemResponseModelBase.cs, src/Umbraco.Cms.Api.Management/ViewModels/Tree/ContentTreeItemResponseModel.cs, src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.db.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document.db.ts, src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/media/media.db.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/document-recycle-bin-tree.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/types.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/tree/media-tree.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/tree/types.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16850, tracked under [AB 47578](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/47578).
The raised issue notes that we are missing the option to sort children by name or create date, only allowing the movement of each item one at a time.
This PR restores that behaviour available in Umbraco 13.
I've made an amend to the management API, introducing the create date field for document and media trees, in order to have that information available in the UI for sorting.
**To Test:**
- Create a content item and/or media folder with a few child items.
- Access the "Sort children..." tree entity action and experiment with moving items via the table headers and individually.  Confirm when the modal is submitted that the new order is …
=> Allow sort of children by name and create date

src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
Fixes #17895 
The raised issue notes that we have the wrong validation message for the maximum and minimum amount Block List items.
**To Test:**
- Create a Block List that has configuration **Amount**  minimum = 1 and maximum = 2
- Go to Content that has the Block List, the first validation will be "Minimum 1 entries, requires <strong>2</strong> more"
- After creating 3 items in the  Block list, the validation message will be "Maximum 2 entries, <strong>3</strong> too many"
=> Block list amount valivation message

src/Umbraco.Core/Services/ContentEditingServiceBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs
If there's an existing issue for this PR then this fixes #16615 (and #17889 and #17906)
As described in the linked issues, read-only properties (e.g. labels) are reset upon save.
It should not be possible to edit read-only properties, so that's what this PR ensures 😄 
Create some content with a label property, and add a value to that label property .... for example, use this controller to update exiting content:
```cs
[ApiController]
[Route("api/[controller]")]
public class Issue16615Controller : ControllerBase
{
private readonly IContentService _contentService;
public Issue16615Controller(IContentService contentService)
=> _contentService = contentService; …
```
=> Do not allow editing read-only properties

src/Umbraco.Web.UI.Client/src/libs/controller-api/controller-host-element.mixin.ts
For some reason the destroy method was overwritten here. Its not suppose to do that, cause that prevents Umb Elements from destroying their Controllers when the element is asked to be destroyed.
=> Fix: ensure controllers are destroyed

src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
Addresses issues https://github.com/umbraco/Umbraco-CMS/issues/17925 and https://github.com/umbraco/Umbraco-CMS/issues/17791
This PR addresses the issue that not all URLs as configured under "Culture and Hostnames" are displayed in the document info workspace view, and that if protocol less URLs (like "www,example.com" the link rendered doesn't work correctly).
For the first issue I've switched the logic around so that rather than rendering the first URL found per culture, we render all URLs along with their culture.
And for the second I've added a function to prepend "https://" to protocol-less URLs.
**To Test:**
- Set up a variant and an invariant page with culture and host names.
- Make sure to add more than one host name per language.
- Create at least one host name as a root folder - …
=> Render all URLs in document workspace info tab and ensure protocol-less links can be used to access the intended URL.

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs, src/Umbraco.Cms.Api.Management/DependencyInjection/AuditLogBuilderExtensions.cs, src/Umbraco.Cms.Api.Management/Security/BackOfficeUserManagerAuditer.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17308
- Looks like `BackOfficeUserManagerAuditer` was removed during the backoffice update from v13 to v14, and this causes the missing audit logs
- Follow steps in original issue.
=> V14: Reintroduce BackOfficeUserManagerAuditer

src/Umbraco.Web.UI.Client/src/libs/class-api/class.mixin.ts, src/Umbraco.Web.UI.Client/src/libs/element-api/element.mixin.ts
We had a bit of code not complying with the omitted callback method.
Now that we use the omitted callback method for the sysinfo repository. Then this error has been revealed.
Fixes this error when logged in:
=> Fix omitted callback

src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/17165
This PR ensures that the "ancestors" selector for the Delivery API works for unpublished content.
1. Create a content structure and publish it.
2. Add an unpublished child (or structure) somewhere in the published structure.
3. Query ancestors of the unpublished child using the Delivery API.
Expected result:
1. When querying without an API key (or not for preview), nothing should be returned.
2. When querying for preview, the ancestors should be returned.
Also test that ancestors can be retrieved for published content outside of preview 😄
=> Make the Delivery API "ancestors" selector work with preview

src/Umbraco.Core/Services/DocumentUrlService.cs
Fixes an issue where domains was broken for invariant content, given the following setup 
* EN Root - Has domain `/en` with English culture
* Child
* DA Root - Has domain `/da` with Danish culture
* Child
You would expect that the URLs return by `Url()` to be `/da/` for the danish root, and `/da/text-da/` for the danish child, however this was not the case, and it would instead return the "default" URL 
The reason for this is that `GetLegacyRouteFormat` would always look for a domain with the passed in culture, however this doesn't make sense in an invariant setup like this, since the culture will always be null, and we'll never find any domains.
We can see that similar logic was applied in `DomainCacheExtensions.GetAssignedWithCulture` in the old routing system 
Create a setup like above …
=> V15: Handle domains in invariant content

tools/Umbraco.JsonSchema/UmbracoCmsSchema.cs
Addresses the issue raised here: https://github.com/umbraco/Umbraco-CMS/issues/17945
As reported in the linked issue, the JSON schema generation for the default data you can configure for install isn't correct.
When merged this PR will ensure that the JSON schema generated is correct and matches the paths used in code.  This will correct the intellisense provided when configuring Umbraco.
To Test:
- With the PR merged, rebuild the whole solution.
- Verify the generated schema file found at `src\Umbraco.Web.UI\appsettings-schema.Umbraco.Cms.json`.  You should now see the following elements:
```
"InstallDefaultData": {
"$ref": "#/definitions/InstallDefaultDataNamedOptions"
},
"InstallDefaultDataNamedOptions": {
"type": "object",
"properties": {
"Languages": {
"$ref": …
```
=> Corrected property names and structure used in JSON schema generation for configuration of default data to install.

src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
This is a follow up on #17886 which, after some discussion, seemed like a bad idea as there was a small possibility that we would break behavior that package developers might rely on.
Instead of not setting the global config, this catches errors while adding global rule to allow synchronous IO for IIS only (Kestrel one should run anywhere regardless, so I've kept it as it was before).
This has been tested on a Ubuntu machine with [the apt package manager using these 3 commands](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install?tabs=dotnet9&pivots=os-linux-ubuntu-2410):
```bash
sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-9.0
```
```bash
sudo apt-get update && \
sudo apt-get install -y aspnetcore-runtime-9.0
```
```bash
sudo apt-get install -y …
```
=> Fixing problem on Linux where `dotnet run` fails because we try to set an IIS config

src/Umbraco.Web.UI.Client/devops/eslint/rules/enforce-element-suffix-on-element-class-name.cjs
Updated rule to accept that abstract element class names ends with of 'ElementBase'.
=> Prettier rule for element base

src/Umbraco.Web.Website/Controllers/UmbLoginStatusController.cs, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorContent.spec.ts
Updated failing acceptance test
=> V13 QA updated locator for failing E2E test

src/Umbraco.PublishedCache.HybridCache/PublishedContent.cs
The `IsPreviewing` property of `PublishedContent` is always `false` - even when previewing.
Besides being somewhat clearly wrong, it also causes problems for property values using `PropertyCacheLevel.Elements`; their cached values are not updated correctly when moving in and out of preview. This causes either preview or the published rendering to be broken:
- If a document is previewed before it's published version is requested for rendering, the draft property value will be rendered for both preview and published rendering.
- If a document is requested for rendering in its published version before it's previewed, the published property value will be rendered for both preview and published rendering.
1. Create a document with a content picker.
- IMPORTANT: the document must have a …
=> Published Content should handle "is previewing"

src/Umbraco.Cms.Api.Delivery/Querying/Filters/ContentTypeFilter.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/17917
See the linked discussion for details 😄 
As described in the linked discussion, the content type filtering syntax now becomes:
- `filter=contentType:article,news` = finds documents of type `article` or `news`
- `filter=contentType:!article,news` = finds all other documents that those of type `article` and `news`
Test that:
1. Multiple content types can be applied to the filter, both with and without negation.
2. The current functionality (filtering for only a single content type) still works.
=> Allow filtering for multiple content types

src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17932
- returns a validation error, instead of showing a 403 forbidden error, when saving invalid media.
- This means you can still save invalid media as you have always been able to do, but you get a proper validation error like this:
- Follow steps in original issue.
=> V13: Show validation error, when saving invalid media

src/Umbraco.Cms.Api.Delivery/Controllers/Content/ContentApiControllerBase.cs, src/Umbraco.Cms.Api.Delivery/Filters/AddVaryHeaderAttribute.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/17953
See the linked discussion for details.
Use the [test setup provided](https://github.com/umbraco/Umbraco-CMS/discussions/17953#discussion-7818624) in the linked discussion.
Get in touch with @kjac for an amended version of the test setup which includes preview and start item setup 👍
=> Add Vary header to all content API operations

src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
Addresses issue: https://github.com/umbraco/Umbraco-CMS/issues/17050
When selecting to send a language variant for approval, there's a glitch if you open the dialog, select a language and close.  When you re-open, the checkbox and enabled button are "out of sync", so you can't complete the operation without reloading the node.
**To Test:**
- For setup, see "steps to reproduce" on the linked issue.
- Click to send the content for approval.
- Check the language checkbox
- Close the dialog.
- Confirm you can select and send the content for approval.
=> Resets send to approval dialog on close such that when re-opening the selection and operation can still be triggered.

src/Umbraco.Web.UI.Client/src/libs/observable-api/observer.ts
When an observer has no callback, it has no purpose after resolving the Promise. So then lets clean up and get it destroyed.
=> Feature: no callback then destroy

src/Umbraco.Web.UI.Client/package-lock.json, src/Umbraco.Web.UI.Client/package.json
Update the version of @microsoft/signalr to version 8 to match the .NET version. In general, we should aim to have them match each other.
=> V13: Update @microsoft/signalr from 7.0.12 to 8.0.7

src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs, src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12232
- Implements solution from https://github.com/umbraco/Umbraco-CMS/issues/12232#issuecomment-1371911209
- This implements the IsLockedOut on the ´UmbracoUserManager´ itself instead, so we can align behavior with members & users.
- Follow steps in original issue.
=> V15: Implement IsLockedOut on base class instead

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
If there's an existing issue for this PR then this fixes #16911
Adding a custom content app introduces a weird behaviour for the "Save and preview" button; if you go to the custom content app and back again to the "Content" or "Info" content apps, the "Save and preview" button has disappeared - the "Save" and the "Publish" buttons are still there, though.
⚠️ Remember to rebuild the client before testing ⚠️
Extract [this custom content app](https://github.com/user-attachments/files/18420104/WordCounter.zip) into `/App_Plugins` and restart the site.
Navigate between the content apps and verify that the "Save and preview" button disappears and re-appears along with the rest of the buttons.
=> Enforce the "Save and preview" button after when switching content app

.github/workflows/test-backoffice.yml, src/Umbraco.Web.UI.Client/devops/circular/index.js, src/Umbraco.Web.UI.Client/package.json
This is setting up a script to run Madge (effectively `npm run check:circular` but with Node.js) so the build can either fail or warn if circular dependencies are detected.
There are 11 circular dependencies, so we might want to set this to **warn** until they are fixed.
Check this previous run to see what it looks like in **error** mode: https://github.com/umbraco/Umbraco-CMS/actions/runs/12689060972/job/35366940767
If you have changed one of the files that has a circular dependency, the error will also pop up as an annotation on that file in the "**Files changed**" view.
Run the script locally:
```bash
cd src/Umbraco.Web.UI.Client
node devops/circular/index.js src
```
Check that it shows the currently known circular dependencies.
=> Build: Detect circular dependencies with Madge

src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextElementParser.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs
If there's an existing issue for this PR then this fixes #17037
See the linked issue 👍 
Setup the Delivery API to [render RTEs as JSON](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#additional-configuration).
Create and publish a document containing an RTE with this content:
```html
<p>What follows from <strong>here</strong> <em>is</em> <a href="#">just</a> a bunch of text.</p>
```
...you'll likely need to insert it directly into the RTE code editor.
Verify that the Delivery API output for the document has `#text` elements with single whitespaces between the inline elements (`strong`, `em` and `a`):
=> Make the RTE handle inline elements gracefully for JSON

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17847
Solution is to only fire this event if the instance is available, it seems to me if not available an update is not necessary.
=> Fix: only fire event when instance is available (issue 17847)

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
If there's an existing issue for this PR then this fixes #16854
Even if a user is not allowed to save or send to publish, they will still see the "Save and preview" button. Fortunately it doesn't work, but it's still wrong.
⚠️ Remember to rebuild the client before testing ⚠️
1. Create a user with only "Browse" permissions to content.
2. Login with this user and verify that no buttons are shown for content.
3. Verify that the "Save and publish" button still works for users with content save permission.
=> Do not show "Save and preview" by default

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
=> Fix: Do not re-map schedule modal on error as it leads to broken bindings

src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
When a short search query is used, irrelevant results may arise because the query appears in the Key guide.
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/16003
When a short search query is used in the Backoffice Search, irrelevant results may arise because the query appears in the Key value.
Before:
After:
[Added by HQ] Breaking changes:
This PR introduces a functional breaking change that can have an impact on how people interact with the Backoffice: it disables partial key searches.
=> Remove __Key field from Backoffice Search if query is not a Guid

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16368
Currently the regular expression pattern field allows entry of any length of text.  On SQL Server, the limit is 255 characters, so you'll get an exception thrown if you try to enter a longer pattern.  With SQLite, the longer text is accepted, but then errors will occur if you deploy to an environment running SQL Server.
This PR adds a `maxlength` attribute to the field to prevent entry of a value that's too long.
I've also increased the height of the box slightly to better present longer patterns.
This resolves the issue for Umbraco 13.  Will check and if necessary create a separate PR for the same on Umbraco 15.
=> Added a maxlength setting to the regular expression pattern field

build/azure-pipelines.yml, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js, tests/Umbraco.Tests.AcceptanceTest/package.json
Added parallelization to our E2E tests on the pipeline, this reduces the time spent for a PR
=> V13 QA added parallelization for E2E tests

src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17796
=> Fix: Empty groups appear in block grid editor Add content UI

src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/action/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/manifests.ts
This PR registers a create button in the Document Type Folder Collection workspace. The Create action utilizes the already-registered create options.
=> Feature: Create button in Document Type Folder collection

src/Umbraco.Core/Services/DocumentUrlService.cs
The first root document has been given special meaning when routing content. I can't find any background for this, nor any reasoning why it should have.
Given this document structure:
All the blog posts are routable both at their expected path `/[blog post URL segment]/`, but also at `/posts/[blog post URL segment]/`. The latter should not be the case - at least not by default (more on that below).
For comparison, the authors are _not_ routable at `/authors/[author URL segment]/` - only at `/[author URL segment]/`, as expected.
The `HideTopLevelNodeFromPath` config setting (see [docs](https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings)) is by default `true` ... setting it to `false` should include the root document URL segment in the blog post and author paths - …
=> First document at root should not have special meaning when routing

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/input-block-type/input-block-type.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/modal/entity-create-option-action-list-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/modal/common/confirm/confirm-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/sorter/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/sorter/replacement-resolver-as-grid.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/sorter/sorter.controller.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
A few different fixes that was a bit related. Generally this improves the sorting algorithm, so it is much more intuitive where things gets dropped. Especially for Block Grid Editor, where the drag n' drop feature is very important.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17798
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17967
This contains:
* Fixes for the placement algorithm for Sorter.
* Makes Confirm Modal localizable.
* Fixes Block Type Input so it works when deleting and moving Blocks, generally made it much simpler.
=> Fix: Improve sorter placement algorithm

src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
Since Umbraco 7.7 it has been possible to configure the behaviour when creating new content via AngularJS – to require the user to select a blueprint / content template, or auto-select one.
If `skipSelect` is enabled, the first available blueprint is selected. The issue has been if multiple blueprints exist for a specific type the user has no way to select which blueprint to use.
This PR includes an additional check to only skip the content template select dialog if just one option exists – otherwise the user is presented a dialog to select.
=> Allow skipSelect blueprints only when one blueprint exists

src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.context.ts, src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-logo.element.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/server.handlers.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/components/new-version.element.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/modals/new-version-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/types.ts
This pull request introduces several changes to improve the server upgrade check functionality in the Umbraco backoffice. The changes include modifying the server upgrade check logic to utilize the current server version, updating the UI to reflect the new version, and enhancing the data structure for storing upgrade check results.
Fixes #17910
Enhancements to server upgrade check functionality:
* [`src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.context.ts`](diffhunk://#diff-22f78d737bc251c99310a4c8405b391655d93060a58297ee778749f1e46af8e2R82-R84): Updated the `serverUpgradeCheck` method to pass the current server version to the repository's `serverUpgradeCheck` method.
* [`src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts`](diffhunk://#diff-d54f58f2f …
=> V15: "New version available" text is not reverified after an upgrade

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Fixes #17999
- Adds placeholder to the main entity field
- Adds a `.focus()` call to the main input using a forward ref and a timeout (also tested with **requestAnimationFrame** however it did not work when changing from a different workspace, only within the same workspace)
1. Test that a placeholder is shown when deleting the value in the name field
2. Verify that the input has focus upon creating a new entity
3. Verify that the input has focus when editing an existing entity
4. Try and switch between workspaces and/or sections, then click "Create" on a document to create a new page
=> V15: Main entity name field lacks placeholder and auto-focus

src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-group.element.ts
After running a health check in the settings section, and then clicking on an individual health check section, you press "back to overview" (probably shouldn't be hardcoded text?). This would push a URL missing the `umbraco/` portion. Whilst the CMS continues to work, if you refresh your page you're taken away from the backoffice, probably ending up on the 404 page.
Image to show the area I mean specifically
=> Health Check items "back to overview" link omits backoffice url segment

src/Umbraco.Cms.Api.Delivery/Controllers/Security/CurrentMemberController.cs, src/Umbraco.Cms.Api.Delivery/Services/CurrentMemberClaimsProvider.cs, src/Umbraco.Core/DeliveryApi/ICurrentMemberClaimsProvider.cs, src/Umbraco.Core/DeliveryApi/NoopCurrentMemberClaimsProvider.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
The introduction of the "current member info" endpoint for the Delivery API unfortunately means Umbraco no longer can boot without the Delivery API 😢 
This PR fixes it, by adding a `NoopCurrentMemberClaimsProvider` and moving the `ICurrentMemberClaimsProvider` interface to core. This follows the pattern of all the other Delivery API services required for boot.
This _looks_ very breaking, but as it happens, the feature is not yet released (slated for 13.6), so we can break it 👍
=> Add NoopCurrentMemberClaimsProvider so Umbraco can boot without the Delivery API enabled

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes #13355 
The linked issue is for v10 but I ran into the same issue in 13.5.2.
Based on @dKumarmj 's analysis in the issue I have tried to fix the problem.
Instead of using the id in the route to fetch the allowed child items we should use the contentId from the scope which represents the active item in the infinite editor.
With this fix in place the repro steps in the issue now work as expected, i.e. it is possible to create a third level item under the second level.
=> Fix create child issue in list view with infinite editor (#13355).

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/members/member-group/components/member-group-picker-modal/member-group-picker-modal.element.ts
This PR changes the dialog label for Choose Groups under Members making the action clearer.
This PR aims to resolve the Group label mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668
=> Updated the dialog labels for Member -> Choose Groups

src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
This PR changes the headline modal in the document picker property
The PR aims to resolve the heading for the Umb.PropertyEditorUi.DocumentPicker mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668
=> updated the modal headline

src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.controller.js
This fixes #13156 
Browser OS information uses the deprecated method navigator.platform. So I replaced it with `navigator.userAgent`, exactly the same as how it is used in umbraco v15.
**Note:** Though the issue is reported for v10 and v11. It is present in v13 LTS as well.
1. Log into the Umbraco Backoffice.
2. Click on the Help icon in the top right of the screen.
3. View the System Information from the sidebar that appears.
4. Check the Browser (user agent) string
=> Replaced deprecated navigator.platform with navigator.userAgent for platform detection.

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/modals/user-group-picker/user-group-picker-modal.element.ts
This PR changes the dialog label for the User—Assign Access—Groups dialog, making the action clearer.
This PR aims to resolve the dialog label for the User - Assign Access - Groups picker mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668
=> Updated the dialog label for the User - Assign Access - Groups

src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.repository.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18058
The document tree root for the recycle bin was localized, but not the media one.  With this PR merged, it is.
**To Test:**
- Login to the backoffice and set your user's language to something other than English (that we have translations for - e.g. Danish).
- View the document (content) and media trees, and note that both recycle bin nodes are now translated into the selected language.
=> Localize the recycle bin tree root

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Fixes #17680.
Adds a `max-height` to the Workspace's Variant Selector scroll container. This has been set to 50% of the browser's current viewport (`50dvh`), so that it can account for dynamic resizing.
To test this, you either need several language/cultures enabled or use the mock API to add them, then open the variant selector and resize the browser window/viewport, notice the scrollbar.
=> Sets `max-height` for Workspace Variant Selector scroll container

src/Umbraco.Web.UI.Client/src/css/umb-css.css, src/Umbraco.Web.UI.Client/src/rollup.config.js
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17958
If you edit a template in the backoffice it uses the code editor component.  Clicking Ctrl + F opens the "Find" window and you can see the buttons on this control don't render correctly.
This PR resolves that by ensuring the font file is copied to the "dist" output and the page rendered for the Umbraco backoffice has the appropriate CSS for the font to be used.  This didn't work when I added the CSS rule to the `<umb-code-editor>` element, and [from what I read](https://github.com/lit/lit-element/issues/793#issuecomment-535536364), needs to be on the first page that the browser loads.
**To Test:**
- Load up the code editor by editing a template or script file, click Ctrl + F and check the buttons render correctly.
=> Fixes rendering of the font icons used for buttons in the code editor.

src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17989
aligning the methods, the issue was that the settingsValues was not comparing property alias.
=> Fix settings value begin indifference (17989)

src/Umbraco.Core/Services/IMemberService.cs, src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.ContentType.cs
Fixes #17046 
- You can use this code to create 500 members, I personally threw it in a media saving notification just because i had one lying around 😅 
```
for (int i = 0; i < 550; i++)
{
var member = _memberService.CreateMember($"Test{i}", $"test{i}@gmail.com", $"TestName{i}", Constants.Security.DefaultMemberTypeAlias);
_memberService.Save(member);
}
```
```
{
{
builder.AddNotificationHandler<MediaSavingNotification, MyNotificationHandler>();
}
}
public class MyNotificationHandler : …
```
=> 15: Convert pagesize properly to skip and take

src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_3_0/AlignUpgradedDatabase.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17855
We have a migration as part of the 13.3 release that amongst other things attempts to rename a constraint.  It fails if the constraint doesn't exist.  It's not obvious why the constraint shouldn't exist, but must be possible via some upgrade scenarios as it's been seen in the wild.
When this PR is merged the migration will no longer fail, and will create the constraint if it doesn't find it rather than attempting to rename it.
**To Test:**
- Wind back the migration history of an Umbraco 13 site running on SQL Server with:
```
update umbracoKeyValue
set value = '{6158F3A3-4902-4201-835E-1ED7F810B2D8}'
where [key] = 'Umbraco.Core.Upgrader.State+Umbraco.Core'
```
- Remove the constraint you should already have on …
=> Handles migration case where an expected constraint is renamed but the constraint does not exist

src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeGraphicsController.cs
- Fixes an issue, where you could not get the logos on windows.
This was because of the newly introduced https://github.com/umbraco/Umbraco-CMS/pull/17696. Which uses `Path.Combine`, which in turn on windows, combines paths with `\`, but all our static paths are `/`.
- Note: The jumbled path works with Physical Files, but as when we ship this, its in an RCL, it does not work with that.
- This PR remedies that by just not using Path.Combine, and instead just having the `/` in there always
- Run the backoffice, you should still see the Logos
- You can also pack the project, and run the template to make sure its still there.
=> Replace paths, so they are equal on every OS

Directory.Build.props, src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs, src/Umbraco.Infrastructure/Examine/UmbracoIndexConfig.cs, tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Examine/UmbracoContentValueSetValidatorTests.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12887
- This will be the start of the working going into removing the obsolete IScopeProvider in Core, this has been obsolete for many years, and was slated to be removed in v14..
=> v16: Start removing scope references

src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
Affected version: V15.2 RC2
An exception is thrown when attempting to save a variant document with an an invariant RTE property:
[18085.webm](https://github.com/user-attachments/assets/5b579193-7e84-4d74-8f95-dd3e0da242aa)
The screencast above was recorded using [this SQLite DB](https://github.com/user-attachments/files/18518512/Umbraco.sqlite.18085.db.zip), so it can be used to verify the fix as well 😄 
Admin login is:
- Username: admin@localhost
- Password: SuperSecret123
=> Fix parsing exception for RTEs

src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
If there's an existing issue for this PR then this fixes #7922
Following the discussion on #7922, when exiting document previews we should not blindly redirect to the "by ID" route. Instead we should:
1. Attempt to redirect to the published URL of the document being previewed, or
2. Redirect to the "by ID" route if permitted for published documents, or
3. Redirect to root if the "by ID" route is not permitted.
This PR implements that 👍 
When exiting preview for a given document, verify that:
1. If the document is already published, the client is redirected to the published URL of the document.
2. If the document is _not_ published (draft-only), the client is redirected to the site root (in lieu of better options).
Test this both for culture variant and invariant content.
Remove all URL …
=> Redirect to the published URL when exiting preview

src/Umbraco.Web.UI.Client/src/packages/core/collection/collection-view.manager.ts
This is not a certain fix, but we generally seen redirects as bad. 
Its because we sometimes have a case where the browser loads the Media section before Content, and a redirect of the Media Section changes the URl so they user now stays on Media, despite the user did not want to navigate to the media section.
It only happens occasionally so this is more of a try, by doing the thing we have done elsewhere to fix this issue — which is stop using redirects. :-D
=> Fix: stop using redirects in collections

src/Umbraco.Web.UI.Client/src/packages/core/section/section-sidebar/section-sidebar.element.ts
Currently we have this annoying white space in the bottom of the sidebar.. this pr removes it.
=> Bugfix: Remove sidebar bottom space

src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
I was profiling an Umbraco v15 solution last week and noticed that about 1% of the CPU time was spent... sleeping 😱
Turns out a whole thread was spending most of their time sleeping on the job! Woken up every 2 seconds to do a miniscule amount of work, then sent back to sleep. 
That thread's clearly not pulling their weight - so I figured I'd send them to the pool to hang out with their friends and maybe do something else useful in the meantime. Serve some webpages, run a scheduled task or two, anything except sleeping!
Profile the site (I used DotTrace) before and after the change and notice how much CPU time is spent sleeping...
Idling on my test site - 2.6% 😴
Absolutely none 😃
---
As an aside, the approach in this method isn't ideal. There are more efficient and robust ways to handle …
=> Avoid wasting a whole thread watching for a filesystem change 😬

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
This PR changes the dialog label under User -> Assign Access -> Media Start nodes making the action clearer when clicking the button.
This PR aims to resolve the Media Start nodes label mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668
=> Updated the dialog label for User -> Assign Access -> Media Start nodes

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/monaco-markdown-editor-action/url-picker-monaco-markdown-editor-action.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/link.tiptap-toolbar-api.ts
This PR updates the modals for the link picker and the property editors using it. (TinyMCE, Tiptap, Monaco markdown editors)
The PR aims to resolve the modals mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668.
=> updated the link picker modal and the property editors using it.

src/Umbraco.Web.UI.Client/src/packages/code-editor/code-editor-modal/code-editor-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/code-editor/code-editor-modal/code-editor-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/source-editor.tiptap-toolbar-api.ts
Adds `formatOnLoad` option to the Code Editor modal configuration.
When enabled, once the Monaco editor has loaded, the `'editor.action.formatDocument'` action is ran against it to pretty-print the code contents. Currently, this only seems to work when using `setTimeout` to delay the action execution.
Load up a Tiptap RTE, (the more content the better, e.g. more than a couple of paragraphs), press the "View Source Code" toolbar button. See the Code Editor modal opens and that the code contents is formatted, (e.g. on multiple lines, not on a single line).
=> Feature: Code Editor modal, adds pretty-print support

src/Umbraco.Web.UI.Client/src/packages/core/entity-action/global-components/entity-actions-table-column-view/entity-actions-table-column-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/views/data-type-tree-item-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/views/document-type-tree-item-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/extension-insights/collection/views/table/extension-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/language/collection/views/table/language-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media-types/tree/tree-item-children/collection/views/media-type-tree-item-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/table/media-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member-group/collection/views/table/member-group-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/collection/views/table/member-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/collection/views/user-group-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user/collection/views/table/user-table-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/webhook/collection/views/table/webhook-table-collection-view.element.ts
This PR aligns the UX of entity actions on a collection item with a menu item.
Until now we have always rendered a dropdown with the entity actions. It doesn't make a lot of sense if there is only 1 action available. This PR changes to code to reuse the same element as in a menu item so it will "highlight" the first action but also skip the dropdown if there is only 1 entity action available.
**Single Action Before**
**Single Action After**
**Multiple Actions Before**
**Multiple Actions After**
=> Bugfix: Align collection item entity actions with menu item entity actions

src/Umbraco.Web.UI.Client/src/packages/health-check/health-check-dashboard.context.ts, src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-group.element.ts, src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-overview.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18122
This PR fixes the issue raised where if you click "Perform all checks" on the health checks screen the results aren't displayed.
**To Test:**
- Click "Perform all checks" on the health checks dashboard in the settings section.
- Note that the results are now displayed.
=> Refreshed display of check results after all checks are complete

src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
this fixes #13716 where unused parameters were published as supported, but they were in fact never supported, nor are they needed
=> V13: remove unused parameters and documentation

src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
In internal testing we found an issue with rollback and variant pages - in that the variant page name wasn't rolled back.  This PR fixes a string comparison casing issue such that it is.
**To Test:**
- Create a piece of variant content and publish it.
- Change the page name for one of the cultures and publish again.
- Roll back to the first version and verify that the page name for the culture is now updated.
=> Fixes rollback of variant page name

src/Umbraco.Core/Services/MemberService.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18116
As noted in the linked issue, we have details of the user performing the action in the service methods for saving and deleting members, but we aren't passing those to the audit recording.
With this PR merged, the audit log will record the performing user for these actions.
To Test:
- Save and/or delete a member
- Query the audit records and note that the record written is associated with the user you are logged in as:
```
select top 5 * from umbracoAudit order by id desc
```
=> Pass user Id to audit when saving and deleting members

src/Umbraco.Core/Composing/TypeFinder.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/14857
Adds a couple more assemblies to exclude from `TypeFinder`.
**To Test:**
- Visual inspection will suffice here.
=> Added Resharper test assemblies to exclude list on TypeFinder

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyeditor.directive.js, src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html, src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
If there's an existing issue for this PR then this fixes #16022
It is possible to edit simple properties despite them being read-only; clicking their labels will do the trick:
[16022.webm](https://github.com/user-attachments/assets/00b2f763-be8a-445e-ae67-b84da4c712dd)
This of course won't stand, so here's a PR to fix 😆 
1. It should _only_ be possible to edit "shared" properties in the default language when `AllowEditInvariantFromNonDefault` is configured as `false`.
2. It should _not_ be possible to edit "shared" properties in _any_ language when `AllowEditInvariantFromNonDefault` is configured as `true`, until the properties have explicitly been "unlocked" for editing.
Also test that invariant content (and media) can be edited as per usual.
=> Do not allow editing read-only properties by clicking their labels

src/Umbraco.Core/PublishedCache/PublishedElement.cs, src/Umbraco.Core/PublishedCache/PublishedElementPropertyBase.cs, src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorConverter.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Publishing.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/CacheTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentPickerValueConverterTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTestBase.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PropertyValueConverterTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ConvertersTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/ConvertersTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/PropertyCacheLevelTests.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/17700
Any property values cached at `Elements` level will be reused across variance when used in combination with block level variance.
The issue is most apparent in the Delivery API output, because the value converters for the Delivery API use `Elements` level caching more than "regular" value converters do. However, the Document Picker value converters does use `Elements` caching for regular rendering, so it's a good candidate for reproduction:
1. Create a document with a Block List editor that uses block level variation.
2. Add a block containing a Document Picker.
3. Pick different documents for different languages.
4. Render the document; the first rendered language "wins" for the …
=> Elements level property cache should cache by variation

src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.db.ts, src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/media/detail.handlers.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/media/imaging.handlers.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/media/index.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/media/tree.handlers.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/temporary-file/temporary-file.handlers.ts, src/Umbraco.Web.UI.Client/src/packages/core/resources/tryXhrRequest.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/components/temporary-file-badge.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/types.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/types.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-manager.class.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/types.ts
With the change from Fetch to XHR in #18113 we now can follow along on the upload progress on dropped files on the dropzone in the Media Library. This PR aims to wire up the code from the **upload** function all the way back to the **temporary file badge**.
- Wires up `onProgress` -> `progress()` through the **progressItems** and into the media collection grid view to show on the temporary file badge
- Changes the design of the **temporary file badge** to fill out the placeholder container, so that it is more visible
- Replaces the **arrow-up** icon in the temporary file badge with the actual **progress in percent** when uploading
- Introduces a new warning message if a dropped file has **no media types** (it was just ignored before)
- Fixes a lot of mock endpoints and data that were …
=> V15: Show upload progress for dropped files in the Media Library

src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs, src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/15597
The linked issue started with a point raised on why we include the commit hash in the version number.  This does no harm to keep.  But the discussion continued to ask if it's necessary to output the version number at all and established that it's not essential, but could be useful for debugging.
The downside - and we found this when working on umbraco.com - is every Umbraco upgrade leads to a lot of changes to these files, which are seemingly unnecessary and can clutter pull requests.
To avoid a behavioural breaking change, even if a harmless one, I've added configuration option to allow you to switch off the inclusion of the version number.
We could consider making this option default to `false` in a future version, but it's …
=> Provides an option to remove the inessential version number from the generated models

src/Umbraco.Cms.Api.Management/Factories/DocumentUrlFactory.cs, src/Umbraco.Cms.Api.Management/Factories/IDocumentUrlFactory.cs, src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs, src/Umbraco.Core/Routing/IPublishedUrlInfoProvider.cs, src/Umbraco.Core/Routing/PublishedUrlInfoProvider.cs, src/Umbraco.Core/Services/DocumentUrlService.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest_hidetoplevel_false.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTestsBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProvider_hidetoplevel_false.cs, tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Fixes #17952
There was both a functional and an architectural issue here. 
Fucntionally the `IUrlProvider.GetOtherUrls` wasn't listed in the V15 backoffice, in fact, custom IUrlProviders wasn't taken into account at all.
This was because a new method `IDocumentUrlService.ListUrlsAsync` was used. This does not work, because `IDocumentUrlService` is what's used by the default `IUrlProvider` internally, meaning that the `IUrlProviders` can never be taken into account here, due to circular references, additionally this would only take into account "default" urls. 
To fix this I've moved the responsibility of listing urls into its own service `IPublishedUrlInfoProvider` which uses the `IUrlProviders` to generate the urls. This is very simiklar to the old behaviour in `GetContentUrlsAsync`. …
=> V15: Fix Url Preview

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TagRepository.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TagRepositoryTest.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/15524
This PR backports the fix provided by @rammi987 in https://github.com/umbraco/Umbraco-CMS/pull/15554.
I found in testing that PR that we didn't need the part around excluding unpublished content and it was sufficient to port over just the part relating to trashed content and media.
Other than the provided integration test, it can be reviewed using the following code added to a template:
```
@{
@inject ITagQuery _tagQuery;
var contentTags = _tagQuery.GetAllContentTags().OrderBy(x => x?.Text);
<div>Content Tags: @string.Join(", ", contentTags.Select(x => x?.Text))</div>
var mediaTags = _tagQuery.GetAllMediaTags().OrderBy(x => x?.Text);
<div>Media Tags: @string.Join(", ", mediaTags.Select(x => x?.Text))</div>
}
```
And verifying that …
=> Excluded tags from trashed content

src/Umbraco.Web.UI.Client/src/packages/templating/utils/index.ts
If there's an existing issue for this PR then this fixes #12805
When inserting default values in templates, the client always adds them as `HtmlString` - for example
```cshtml
@Model.Value("title", fallback: Fallback.ToDefaultValue, defaultValue: new HtmlString("Fallback for title"))
```
It ends up invoking `Value<T>()` method from `FriendlyPublishedContentExtensions` ([source](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs#L233)).
This results in a `null` value being rendered for any property editor whose value convert does _not_ yield an `HtmlString` output - which, incidentally, none of the core property value converters seem to do.
In other words: The default value is rendered as long as the property is _not_ …
=> Don't assume HtmlString when inserting default values in templates

src/Umbraco.Cms.Api.Delivery/Querying/QueryOptionBase.cs, src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs, src/Umbraco.Cms.Api.Delivery/Querying/Selectors/ChildrenSelector.cs, src/Umbraco.Cms.Api.Delivery/Querying/Selectors/DescendantsSelector.cs, src/Umbraco.Core/DeliveryApi/ApiPublishedContentCache.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PublishedContentCacheTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/AncestorsSelectorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/ChildrenSelectorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/DescendantsSelectorTests.cs
It seems the Delivery API is broadly using `IRequestCultureService` to determine the requested culture, when it should be using the variant context.
While it works splendidly when actively providing the expected culture context in the `accept-language` header, it works less well when using domain mappings to achieve culture context.
The whole thing seems to originate in the V15 redo of routing, and #18036 (by yours truly) has only made it worse 🙈 
This PR ensures that we only use `IRequestCultureService` the way it was intended (the way it's used in V13), and use the variant context to figure out the request culture context when needed.
First and foremost, the steps for testing #18036 should be re-iterated, because this PR changes a lot of the same code.
Next, given the languages `en-US` …
=> Use variant context for determining requested culture

src/Umbraco.Cms.Api.Delivery/Services/RequestRedirectService.cs
If there's an existing issue for this PR then this fixes #16901
As described in the linked issue, URL redirects can fail to resolve under certain conditions.
The culprit is how URL redirects are tracked - and how it changes over time, depending on content configuration:
- Sometimes a redirect is tracked solely by the original relative path
- Sometimes a redirect is tracked using the magic "root ID prefix" for the relative path - i.e. `1234/original/path` 
The magic "root ID prefix" seems generally to be applied when there are domains configured. Since redirects can be created both before and after domain configurations, we potentially have to look for both permutations when resolving redirect URLs for the Delivery API.
This PR updates the logic to be as follows:
1. If a redirect URL can …
=> More robust resolving of Delivery API redirects

src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
According to the [v13 docs](https://docs.umbraco.com/umbraco-cms/13.latest-lts/reference/configuration/maximumuploadsizesettings) you can set the max filesize using maxAllowedContentLength to 4GB, however when you drag/drop a 2gb+ file in the media library it will throw an out of memory error.
This bug was introduced with the security SVG XSS hotfix #14657 by using a MemoryStream which has a max size of 2GB instead of the FileStream which does allow for 4GB files.
=> Fix out of memory file upload of 2gb+ files introduced by #14657 SVG xss

src/Umbraco.Core/DynamicRoot/Origin/SiteDynamicRootOriginFinder.cs, src/Umbraco.Core/Extensions/StringExtensions.cs, src/Umbraco.Core/Extensions/TreeEntityExtensions.cs, src/Umbraco.Core/Models/PropertyTagsExtensions.cs, src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/TreeEntityExtensionsTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
Less parsing, allocation & LINQ when splitting strings
=> Less parsing, allocation & LINQ when splitting strings

src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
If there's an existing issue for this PR then this fixes #17292
See the linked issue 👍 
See the linked issue 🚀
=> Enforce user start nodes for media uploads through the RTE

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
Fixes #18195.
Corrects filename label on the Upload File component.
Previously, the component had assumed that the `path` was absolute (containing the server URL), so tried to substring it accordingly. This fix will split the string by slash and pop off the last entry, to display the filename.
This PR also does a general tidy-up of the `input-upload-field-file.element.ts` code, to align with other element classes.
=> Corrects filename label on the Upload File component

src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/mixins/form-control.mixin.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/replace-start-of-path.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/replace-start-of-path.test.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17206
Correcting validation context inheritance when the sub path is identical to the path of a message.
Before the path got messed-up when there was an exact match(because the old method expected there to be a dot after the match) resulting in not giving the right path and therefor never begin able to remove that again. Fixed with a improve the replacer method and writing tests.
After this PR there will be errors if similar should happen again.
=> Fixes #17206

src/Umbraco.Web.UI.Client/src/packages/members/member/collection/action/create-member-collection-action.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/collection/repository/member-collection.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/components/member-picker-modal/member-picker-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/repository/detail/member-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/types.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/17022
There are a few issues raised with member icons on the linked issue.  Some appear to have already been resolved but I could see that:
- The create dialog for members didn't display the icons.
- The member picker didn't display the icons.
These are both resolved with this PR:
=> Corrected rendering of member type icons on create button and picker

src/Umbraco.Core/EmbeddedResources/Snippets/LoginStatus.cshtml, src/Umbraco.Web.Common/Extensions/HttpContextExtensions.cs, src/Umbraco.Web.Common/Extensions/MemberClaimsPrincipalExtensions.cs, src/Umbraco.Web.Common/Security/MemberManager.cs
Fixes #18186.
Using basic auth breaks member functionality. This turned out to be multiple issues.
1.  `AuthenticateBackOfficeAsync` updated the HttpContext user to the backoffice authenticated one, this breaks members entirely when using basic auth since the backoffice identity will then be the only one ever assigned to the user. I've fixed this by any authenticated identity that is not the backoffice one to the new principal.
2. The Member manager always assumed that the member was the only identity, I've fixed this by now specifically looking for the identity with `IdentityConstants.ApplicationScheme' as the authentication type, I've created an extension for this since it's also used in 3. 
3. The login status snippet also assumed that the member identity would be the only one, I've …
=> V13: Fix members while using basic auth.

src/Umbraco.Web.Common/RuntimeMinification/SmidgeOptionsSetup.cs, src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
This fixes : [15165](https://github.com/umbraco/Umbraco-CMS/issues/15165)
Sets the cachebuster type for Smidge correctly, so that the version is correctly set on the URL
Replication steps for the bug from HQ are here:
https://github.com/umbraco/Umbraco-CMS/issues/15165#issuecomment-1818799724
Set the smidge cache buster to AppDomain
Confirm that the version in the URLs is no longer 1
=> Set Smidge cachebuster type

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/block-type-card/block-type-card.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-type/workspace/block-type-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts, src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/repository/detail/webhook-detail.repository.ts
This PR deprecates the obsolete `getUnique` parameter on the `UmbPickerInputContext` and `UmbRepositoryItemsManager`, as we now require a unique field for all models.
=> Deprecate get unique param on UmbPickerInputContext and UmbRepositoryItemsManager

src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Fixes #18132.
In the TinyMCE RTE input, the `blur` event triggers the `#onChange` event, which in turn triggers an `UmbPropertyValueChangeEvent` event, causing the "You have unsaved changes" prompt. However if the RTE value is empty or unchanged, then this is unnecessarily triggered.
This fix adds a check to compare the current RTE value to the previous value, if they are equal, then the change event is not triggered.
Without this fix, go to a document with an RTE TinyMCE editor, click inside the RTE, then click outside the RTE (but do not navigate to a different document yet), then navigate to a different document, you should be prompted with the "You have unsaved changes" modal.
With the fix, the "You have unsaved changes" prompt will not appear, (unless you do have RTE content changes, …
=> RTE TinyMCE: Compares previous value in `#onChange` event

src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Implements the label rename intended in https://github.com/umbraco/Umbraco-CMS/pull/18226
Consideration is that whilst we have a developer distinctions between documents and content - with the latter being a general term for documents, media and members - editors have a "content" section so that's a better term to use here.
=> Renamed URL picker document link to content (more familiar to editors).

src/Umbraco.Core/Models/Blocks/BlockGridLayoutAreaItem.cs, src/Umbraco.Core/Models/Blocks/BlockGridLayoutItem.cs, src/Umbraco.Core/Models/Blocks/BlockLayoutItemBase.cs, src/Umbraco.Core/Models/Blocks/IBlockLayoutItem.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
Fixes a bug introduced in https://github.com/umbraco/Umbraco-CMS/pull/17707/ where a blockgrid with sub layout would have its sub layout data (not the definition) removed.
- element type with a textbox
- element type without properties
- block grid datatype with
- textbox element type allowed at root and areas, spanning all columns
- layout element type allowed at root and areas, with 2 areas setup
- doctype with the grid datatype defined above
- a new page with the content setup like this
Adding a layout with data like shown below
Should result in the same thing when saving and refreshing the page
Example of the data being removed before this fix
Would be appreciated if the logic introduced in https://github.com/umbraco/Umbraco-CMS/pull/17707/ could be retested as well for sub layouts. I …
=> Hotfix block grid area data disappearing

src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/RollbackDocumentVersionController.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18232#issuecomment-2636279603
The linked issue notes that a user without explicit rollback permission can still perform the action.
As far as I can see it's resolved in the UI now.  The rollback button has a condition on it, and only appears if the user has permission for the operations.  But we should also validate this on the server, which is what this PR does.
**To Test:**
- Open two independent browser windows, log in as one as an admin and one as an editor.
- Make sure the editor has rollback permissions.
- In the editor browser, navigate to the screen where you can rollback content and verify you can do it.
- In the admin one, disable the rollback permission for the editor.
- In the editor browser, rollback again and verify you …
=> Management API authorization for requests to rollback.

src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace.context.ts
Fixes #17458.
When creating a "Document Type with Template", the Document Type **name** is now passed to the server, instead of the **alias**, so that the server can case the Template filename appropriately, (using PascalCase). re: https://github.com/umbraco/Umbraco-CMS/issues/17458#issuecomment-2639213085.
=> Fixes new "Document Type with Template" filename casing

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/user-group-workspace-editor.element.ts
Translated granular permissions label and description EN, US-EN, and DK for the backoffice UI, as these were missing.
Changes can be verified in the backoffice, under User Group settings, at the bottom of the page.
=> Granular permissions translation DK, EN, US

src/Umbraco.Core/Configuration/Models/Validation/GlobalSettingsValidator.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/GlobalSettingsValidatorTests.cs
If there's an existing issue for this PR then this fixes #18143
As mentioned in #18143, there is a somewhat arbitrary hard upper limit of 20s for obtaining the distributed SQL write lock. While this limit is more than sufficient in any normal scenario, there is really no reason for us imposing a hard upper limit.
This PR removes the hard upper limit 😄
=> Remove the hard upper limit for SQL write lock timeout

src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-context.interface.ts
This PR removes a temporary solution for communicating with the parent of a tree item through a custom event, replacing it with the context API and the "skipHost" method.  
By using the skipHost method, the context API bypasses the current tree item's context and stops at the parent tree item instead. When we reach the root of the tree (which has no parent item), we revert to reloading the root items.
What to test:
* The tree should have the same behavior as before this PR.
=> Tree: replace temporary event hack with context and skipHost

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
Description
Translated property editor settings for DK and EN-US, as these keys did not exist before. 
Changes can be verified in the backoffice, in the Add property overlay.
=> Property editor settings translation for DK&US

src/Umbraco.Web.BackOffice/Controllers/MemberController.cs, src/Umbraco.Web.BackOffice/Controllers/UsersController.cs, src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17347 and https://github.com/umbraco/Umbraco-CMS/issues/14823
The core of both reported issues is that whilst we can rely on ASP.NET Identity validating the user name characters, for updates we need to do it ourselves.  So I've added that into the validation checks for both users and members.
I also fixed an annoyance with LastPass attempting to fill the user name and leading to accidental updates.
**To Test:**
- Allow for example a space to be a valid character by configuring:
```
"Umbraco": {
"CMS": {
"Security": {
"UsernameIsEmail": false,
"AllowedUserNameCharacters": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._ @+\\",
```
- Create a member and a user with a space in the user name.
- Update configuration to …
=> Add validation to prevent update of a user or member to an invalid username (13)

src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.context.ts, src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-main.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/section/section-main-views/section-main-views.element.ts
Use fewer redirects, this should ideally kill the eventual situation where we as developers end up on another URL then the one we where working on.
Notes for test:
This means that the URL for the first item of a location is nothing, so be aware about active states. And paths continuing from there — Does it give any problems that the first item has a empty path option — Ideally it should not, we use this approach in many other places, but this PR makes it very central as it deals with sections and dashboards.
=> Feature: Fewer redirects

src/Umbraco.Web.UI.Client/src/packages/core/picker/search/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/default/default-picker-search-result-item.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/default/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/picker-search-result-item-element-base.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/picker/document-picker-search-result-item.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/picker/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/picker/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/picker/member-picker-search-result-item.element.ts
Partial fix for #17664, _(this PR only fixes the icon not the URL part)_.
Added `pickerSearchResultItem` elements for Document and Member pickers.
To do cut down on the boilerplate code, I've abstracted `UmbDefaultPickerSearchResultItemElement` to `UmbPickerSearchResultItemElementBase<T>`, so to reuse the base class on the Document and Member elements.
Let me know if any files/folders need moving around or renaming.
=> Picker search result item icons for Documents and Members

src/Umbraco.Web.UI.Client/src/packages/core/auth/modals/umb-app-auth-modal.element.ts
To replicate the issue:
- Log into the back office of Umbraco 15 
- Change into the "Dark" theme
- Wait for your session to expire
- Try and use the back office, it should redirect you to log back in again
This is where the issue appears, because you are using the dark theme, the fonts are all light fonts, but the background color is not using the theme, so the text disappears.
The fix is to correctly us the theme color and fall back to the default, which is what I have done :)
Tiny change, far more typing for this description :)
=> Fixing the background color of the "re-login" screen when your session has timed out.

src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
fixes #18252
Since the RTE wraps its block values into its own custom model, we need to pull them apart before letting the base class handle the actual merging.
We also need to merge the html as you might not be allowed to update this based on language settings
=> Add custom sub variancy support for the RTE

src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
This backports the changes applied in PRs https://github.com/umbraco/Umbraco-CMS/pull/18119 and https://github.com/umbraco/Umbraco-CMS/pull/18147.
Test steps are described in the second linked PR.  I've verified these on this PR for Umbraco 13.
=> Backport use of thread delay over sleep and handle dispose in FileSystemMainDomLock

src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/modals/save-modal/document-save-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/modal/document-publish-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/modal/document-unpublish-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
Preventing an issue where a user without consent sends of not created variant.
This happend because we pre-selected all active and mandatory variants, but these might not be created and therefor not a valid choice, but the selection was never filtered based on the pickableFilter, and the pickableFilter was not sensitive enough about created variants.
This PR moves some pickableFilter logic into the modal as that one knows the best in regards to the variant and what is required for the action.
**test notes:**
Have two languages that are mandatory
Create a culture variant document.
Only write a name for Language A.
Open split view for Language A & B.
and then try to Save or Save &  Publish.
And you should see a complaint that something went wrong.
=> Prevent saving or publishing not created variants

src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/collection/action/collection-action-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/collection/action/collection-action-button.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/collection/action/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/core/collection/extensions/collection-action.extension.ts, src/Umbraco.Web.UI.Client/src/packages/core/entity-action/default/entity-action.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/action/create-document-collection-action.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user/invite/collection-action/manifests.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16407
=> Removes collection action state

src/Umbraco.Web.UI.Client/src/packages/property-editors/accepted-types/manifests.ts
I'd noticed that the "Accepted Upload Types" property-editor was showing up in the available editors when creating a Data Type.
This is currently an internal property-editor, and by removing the associated `propertyEditorSchemaAlias`, it will be hidden from the available list.
=> Chore: Remove the `propertyEditorSchemaAlias` for "Accepted Upload Types"

src/Umbraco.Web.UI.Client/src/packages/help/header-app/help-header-app.element.ts
I found that the placement of the Help header-app felt too close to the right of the browser screen, so I wanted to try out setting the popover to be `placement="top-end"` ...and then I got carried away refactoring, removing unused code and localizing the button label.
=> Help Header App, popover placement + code tidy-up

src/Umbraco.Web.UI.Client/src/packages/umbraco-news/umbraco-news-dashboard.element.ts
On the Content welcome dashboard, the 4 info boxes didn't have a drop-shadow, I've added it in.
(It's been bugging me for a long time now. 😅)
=> Content dashboard, info box drop-shadow

src/Umbraco.Web.UI.Client/src/packages/core/property-action/kinds/default/property-action.element.ts
I'd noticed during Contentment development that the label for Property Actions wasn't being localized.
This PR adds localization support.
=> Property actions: adds localization support

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/data-type/entity-actions/create/default/manifests.ts
Fixes #18328.
Adds a description to the Data Type create option.
I'd also noticed that the text for "create_folderDescription" was different between English US and English fallback, so updated English fallback. At some point we should align these localisations, so that English US only contains texts that are culturally different from generic English, e.g. colour vs color, etc. Fewer strings to manage and process.
=> Data Type create option description

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts, src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-date.element.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-date.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-relative-time.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
- Adds helper functions to show a localized duration between two points in time using the [Intl.DurationFormat API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat), which is available in most browsers (Firefox behind a flag).
- Uses the helper function in the `<umb-localize-date />` element to show the duration between **now** and the time in the  title attribute
- Improves the **UmbLocalizeDateElement** to avoid re-rendering
- The longer-term idea is to use this in the schedule publishing modal to let the user know more details about their scheduling
=> V15: Show duration on time displays

src/Umbraco.Web.UI.Client/src/assets/lang/bs.ts, src/Umbraco.Web.UI.Client/src/assets/lang/cs-cz.ts, src/Umbraco.Web.UI.Client/src/assets/lang/cy-gb.ts, src/Umbraco.Web.UI.Client/src/assets/lang/de-de.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/es-es.ts, src/Umbraco.Web.UI.Client/src/assets/lang/fr-fr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/hr-hr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/it-it.ts, src/Umbraco.Web.UI.Client/src/assets/lang/nl-nl.ts, src/Umbraco.Web.UI.Client/src/assets/lang/ru-ru.ts, src/Umbraco.Web.UI.Client/src/assets/lang/tr-tr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/uk-ua.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document-publishing.manager.ts, src/Umbraco.Web.UI.Client/src/mocks/handlers/document/publishing.handlers.ts, src/Umbraco.Web.UI.Client/src/packages/core/components/input-date/input-date.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Fixes [AB#45942](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/45942)
- Adds a button to clear a set schedule.
- Adds a text if a schedule has changed.
- Removes an unused old body for emails of scheduled content
1. Schedule a document and try to set a schedule
2. Try to clear the schedule
3. Test that the text does not show up unless there are changes
=> V15: Add a button to clear schedule

src/Umbraco.Cms.Api.Management/Middleware/BackOfficeAuthorizationInitializationMiddleware.cs, src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs, src/Umbraco.Cms.Api.Management/Umbraco.Cms.Api.Management.csproj, src/Umbraco.Infrastructure/Security/IBackOfficeApplicationManager.cs, tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiTest.cs
It is currently not possible to have multiple backoffice hosts. This poses an issue for sites that require multiple hostnames providing access to the backoffice.
Here's a PR to fix 😄 
As-is, the first backoffice request "wins"; if I request _my.host/umbraco_, _my.host_ becomes the allowed backoffice host. If I subsequently request _my-other.host/umbraco_ (provided both hostnames point to the same Umbraco instance), I will be met with a somewhat unfriendly message stating that it is not permitted.
This is all because we need to explicitly configure hosts as allowed for redirection in OpenId Connect (via OpenIddict).
With this PR, backoffice hosts are accumulated over time instead of the current "first in wins" strategy.
To retain backwards compatability, the …
=> Allow for multiple backoffice hosts

src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18286
As the issue notes, you can't retrieve any members via the "All members" view of the member picker (although you do get the paging information).  This was due to some code looking to filter post retrieval into a paged model for user start nodes.
I've modified this so it only applies for documents and media, which are the only entities that support start nodes.
**To Test:**
- Set up one or two member accounts.
- Add a member picker to a document type.
- Use the member picker when editing content and verify that you can now pick a member via the "All members" search.
=> Only filter post retrieval of entities for start nodes if working with entities that support start nodes

src/Umbraco.Infrastructure/Security/MemberUserStore.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/14713
This PR applies a similar fix as https://github.com/umbraco/Umbraco-CMS/pull/18078 for back-office members, where we want to be a bit more defensive about handling user Ids read from the HttpContext that may not be an expected integer or Guid, as can be the case with external member providers.
I don't have a test setup to reproduce this but I think visual inspection should suffice for reviewing this update.
=> Avoid exception when attempting to find member by Id when Id is not an expected Guid or integer, as can be the case with external member providers

src/Umbraco.Cms.Api.Management/Controllers/Document/References/ReferencedByDocumentController.cs, src/Umbraco.Cms.Api.Management/Controllers/Media/References/ReferencedByMediaController.cs
The existing `/referenced-by/` endpoints for documents and media return all relations, but really it seems the intention of these endpoints is just to show where the item is used elsewhere.  We aren't interested in exposing the "system references", such as the folder or root to restore to from a deleted item.  As such I've modified the endpoints to only return the relations that are marked with "is dependency".
This does change behaviour, but I would argue only in a correcting way for what the intention of these endpoints are.
See (internal) discussion here:
https://umbraco.slack.com/archives/C07K2QDB7DY/p1739802387977499
To Test:
- Delete a document from the root of the content section so that it's in the recycle bin.
- Request 
`/umbraco/management/api/v1/document/{id}/referenced-by` …
=> Limit referenced-by document and media endpoints to references only

src/Umbraco.Core/Routing/NewDefaultUrlProvider.cs, src/Umbraco.Core/Routing/PublishedUrlInfoProvider.cs
Avoids an exception triggered when attempting to resolve "other URLs" for a content item when it's trashed, and their is no ancestor structure available to walk up to find the domains.
See (internal) discussion at:
https://umbraco.slack.com/archives/C027U315T54/p1739795960326179
**To Test:**
- Delete a node and try to view it in the recycle bin.
- Note that now no exception is thrown.
=> On retrieving other URLs, don't attempt to walk up the navigation structure to find parents when content is trashed

src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-level-tag.element.ts
[Issue 18374](https://github.com/umbraco/Umbraco-CMS/issues/18374)
- Open up Umbraco 15
- Navigate to Settings
- Navigate to Log Viewer
- Open one of the detailed logs, like "All"
- Change your Umbraco settings to use "Dark Mode"
If you are using the client project, you should see a "Fatal" error icon and the text is too dark to be able to read, dark grey on black.
This PR fixes that :)
=> Fixes the Fatal icon text so it's readable in Dark Mode.

src/Umbraco.Web.UI.Login/package-lock.json, src/Umbraco.Web.UI.Login/package.json
- updated types from backoffice
- msw updated to 2.7.0
- typescript updated to 5.7.3
- vite updated to 6.1.0 (no migrations needed)
- vite-tsconfig-paths updated to 5.1.4
=> build(deps-dev): update npm dependencies for login screen

src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
We previously moved some of the Tiptap RTE core extensions to a bundled "Rich Text Essentials" extension, however we found that our unit test doesn't register the manifests, so the core extension isn't loaded in. This PR refactors how the core extension is loaded to use the `api` class directly.
Try running the test and checking if there are any errors/warnings/logs.
```
npx web-test-runner .\src\packages\tiptap\property-editors\tiptap\property-editor-ui-tiptap.test.ts
```
=> Tiptap RTE: Ensure core extension is loaded

src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
Issue discussed here:
https://umbracare.net/blog/disabling-webhooks-for-maximum-performance-in-umbraco
I saw this blog post go by in Umb-FYI and seemed to me it was providing a workaround that shouldn't be necessary.
So I've disabled the firing of webhooks if webhooks are disabled in configuration, as I believe that should be what is happening.
**To Test:**
- Disable webhooks in configuration.
- Put a breakpoint in the `WebhookFiring` job and verify that it doesn't run.
=> Disable webhook firing if disable in configuration.

src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-id.class.ts, src/Umbraco.Web.UI.Client/src/packages/language/global-contexts/app-language.context.ts
This changes nothing of great interest, marks a method that was not used as deprecated.
Added some new features to the VariantId.
And refactors a bit of code.
=> Chore: Block Manager + Variant ID Polishing

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17500
Above issue was already fixed for list in a previous PR. This PR does the same for grid.
What happens is that we need to use super.value to trigger validation check when the value changes.
=> Fix: #17500

src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/settings/document-type-workspace-view-settings.element.ts
I found two toggle buttons that weren't translated when I changed my Backoffice language to Danish.
To match the rest of the translation I translated the buttons.
- Removed the hardcoded label in document-type-workspace-view-settings.element.ts and made the toggle buttons for variesByCulture and variesBySegment dynamic with the contentTypeEditor category and the keys cultureVariantLabel and segmentVariantLabel
=> Add Localization to Document Type - Settings - Vary by Culture and Segments

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/color-picker/Umbraco.ColorPicker.ts
The data type for Approved color/Color Picker, wasn't translated when I changed my Backoffice language to Danish. 
I translated the missing translations into Danish to match the rest of the Danish Backoffice. 
- Created a colorPickerConfigurations category to the code in the en.ts, en-us.ts, and da-dk.ts file
- Added a translation for the label title and description and the color title and description. 
- Removed the hardcoded label in Umbraco.ColorPicker.ts and made it dynamic with the new colorPickerConfigurations category and key.
=> Add localization for Approved color/Color Picker Data type

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.ts
If a user changes the UI language in their profile settings, they will not be able to switch back to the default language, or any other language that they may have loaded due to a caching mechanism.
This PR splits up the caching to calculate the "diff of languages to load" side-by-side with the browser language switcher. That ensures that the browser is updated even if you switch back to a previously loaded language.
1. Go to the current user profile and switch from English (US) to English (UK)
2. Verify that the browser HTML tag is updated to `lang="en"`
3. Verify, if possible, that the translations are actually coming from the en.js file, check the approved color picker for example
=> V15: A user cannot switch back to the default language 

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.element.ts
This is addition to https://github.com/umbraco/Umbraco-CMS/pull/18270 tackling issue https://github.com/umbraco/Umbraco-CMS/issues/13739
It was brought to my attention that we should include a warning on the "force re-publish" option, just to avoid people getting into the habit of selecting this option when it's not necessary.
**To Test:**
- Activate the "Publish unchanged items" option when publishing with descendants.
- Verify the warning message is displayed when you proceed to publish.
=> Adds warning to publish descendants dialog when force re-publish is selected (15)

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
This is addition to https://github.com/umbraco/Umbraco-CMS/pull/18249 tackling issue https://github.com/umbraco/Umbraco-CMS/issues/13739
It was brought to my attention that we should include a warning on the "force re-publish" option, just to avoid people getting into the habit of selecting this option when it's not necessary.
**To Test:**
- Activate the "Publish unchanged items" option when publishing with descendants.
- Verify the warning message is displayed.
=> Adds warning to publish descendants dialog when force re-publish is selected (13)

src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18415
Currently the block list range validator is presenting the wrong number of blocks that are "too many".   This corrects it.
**To Test:**
- Create a block list with a maximum amount
- Add more than the amount to the list so that the validation triggers.
- Note that with one too many, you'll see "Maximum 3 entries, 1 too many." rather than "Maximum 3 entries, 4 too many."
=> Blocklist can count not only count but also do subtraction

src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
After an update to the item manager to include loading and error states, we have changed the logic to append the requested data instead of replacing it. This has resulted in a bug when removing items from the picker. Because the data is appended, removing items will not work correctly when new data with fewer items is returned.
This PR is ignored from release as this bug hasn't been part of any released versions.
=> Bugfix: can't remove items from a picker

src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18350
By not preventing an update when lastMarkup is not set... This is because maybe the markup was set in another session, so its okay for that to be undefined.
=> Fix: #18350

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Validation.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.cs
If there's an existing issue for this PR then this fixes #17753
See the linked issue for an excellent guide to reproduction and test 💪 
Note that the issue is generic and applies to all block editors.
=> Fix validation for blocks in variant block editors

src/Umbraco.Web.UI.Client/src/packages/core/utils/state-manager/state.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/controllers/workspace-is-new-redirect.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
Does not reset state when going from 'create' to 'edit'. There is still a flash going on, but that must be resolved later. But for now it does remember the validation which this sets out to fix.
As well resets the trash state, minor discovery by looking into this.
=> Fix: remember validation state when creating

src/Umbraco.Web.UI.Client/src/packages/core/content/manager/content-data-manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/manager/element-data-manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/variant/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/variant/types.ts, src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-id.class.ts, src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-object-compare.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity/entity-workspace-data-manager.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18431
Does so by making sure the current data respects the order from the persisted data.
This both fixes the case represented in the issue, but also ensures a similar issue that happens with Property Value Presets.
The problem is that we cannot in general be indifferent about array orders in our difference comparison, but in the case of Content Values and Content Variants we can and therefor we can sort them to be like the persisted.
The reason why we go with the persisted, is because persisted is set directly to the version we get back from the server, keeping the order the server insists on. meaning once we got a persisted version we can adjust our to it and avoid differences on values or variant sort orders.
=> Fix #18431

src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
https://github.com/umbraco/Umbraco-CMS/pull/17433 (part of the obsoletion clean-up for 15, specifically [this commit](https://github.com/umbraco/Umbraco-CMS/pull/17433/commits/cee72a317ae51159e67ff47ff5f56b7cf9b2ad31)) inadvertently removed the default minimal permissions the writer user group receives, and which we document [here](https://docs.umbraco.com/umbraco-cms/fundamentals/data/users#default-user-groups).
This PR restores them.
To test, do a clean install and verify the writer user group has some permissions:
=> Restored minimal default permissions for the writer user group

src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Adds the following validation to the date inputs:
- Publish time cannot be in the user's past
- Unpublish time cannot be in the user's past
- Unpublish time cannot be before publish time
Fixes [AB#49139](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/49139)
1. Try to set different values in the dialog
=> V15: Adds validation on date from/to inputs in the schedule modal

src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18402
When creating a container this makes sure to duplicate the parent container, so the parent as well exists on the owner document. This is the same approach used on creation of properties, was just never implemented on Container Creation.
=> Fix: Front-end/UX of #18402

src/Umbraco.Core/Configuration/Models/ContentSettings.cs, src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
#17837 introduced a configuration option (`ShowUnroutableContentWarnings`) to disable warnings for unroutable content in V15 (the warnings were originally introduced for V13 in #17705).
This PR backports the same configuration from V15 to V13 😄 
1. Create content with conflicting routes.
2. Verify that warnings are conditionally displayed at publish time for that content, depending on the current value of  `ShowUnroutableContentWarnings` 
Note that you must have `ShowDomainWarnings` disabled to reliably test this, because `ShowDomainWarnings` overrules `ShowUnroutableContentWarnings` in certain scenarios:
```
"Umbraco": {
"CMS": {
"Content": {
"ShowDomainWarnings": false,
"ShowUnroutableContentWarnings": true/false
}
```
=> Backport `ShowUnroutableContentWarnings` to V13

src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
This PR aligns the tag colors with the document info view.
Ideally, we had an element to render to tag, but they will be for another day 😄
=> Document collection: align status tag colors

src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
We currently have a placeholder in Tip Tap that says "Write something amazing...". We don’t use similar placeholders anywhere else, so I don't think it fits here either.
=> Remove Tip tap placeholder text

src/Umbraco.Core/PropertyEditors/Validators/EmailValidator.cs, src/Umbraco.Infrastructure/PropertyEditors/EmailAddressPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/EmailValidatorTests.cs
Next one for server-side validation was the email address property editor.  This already had the necessary validation so I've just updated to use localization and added some tests.
Unlike the others I've looked at this didn't have a custom nested `DataValueEditor` class.  I didn't think it necessary to introduce it so have kept the class structure as is.  Means the unit test is on the `EmailValidator` itself but I think this is OK, as the property editor itself just delegates to this.
To test I've used Swagger, manipulating requests to `PUT /umbraco/management/api/v1.1/document/{id}/validate`.
=> Localize the email property editor validation and add tests

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Core/PropertyEditors/RadioValueEditor.cs, src/Umbraco.Core/PropertyEditors/Validators/RadioValueValidator.cs, src/Umbraco.Infrastructure/PropertyEditors/RadioButtonsPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RadioButtonsPropertyValueEditorTests.cs
This adds localization and unit tests to the existing server-side validation for radio button lists.
To test, I've been using Swagger and manipulating values to the `/umbraco/management/api/v1.1/document/{id}/validate` endpoint.  You should find if you supply a value not in the configured options, you'll get a localized validation message in response.
Once again - thanks if you can provide the Danish.
=> Added tests and localization to radio button validation

src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Create.cs
#16421 introduced guards against (and warnings for) element type mismatch for document types. Unfortunately, while the PR actually added guards at document type creation time, these guards were never actually applied 😢 
You'll need to use Swagger UI to test this, as the backoffice client UI doesn't support creating inherited document types yet.
1. Create a document type.
2. Using Swagger UI, attempt to create a child element type to the document type.
3. Verify that this fails with a "mismatched" error status.
Now do the same, but with a parent element type and a child document type. The result should be the same.
You can use the following payload when testing with with Swagger UI. Remember to:
- Replace the parent document type key.
- Add your preferred document/element …
=> Guard against element type mismatch at document type creation

src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AllowedChildrenDocumentTypeController.cs, src/Umbraco.Cms.Api.Management/Controllers/MediaType/AllowedChildrenMediaTypeController.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs, src/Umbraco.Core/Services/Filters/IContentTypeFilter.cs, src/Umbraco.Core/Services/IContentTypeServiceBase.cs, src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts, src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-data-source.interface.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-repository.interface.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-server-data-source-base.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/repository/structure/document-type-structure.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/action/create-document-collection-action.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/structure/media-type-structure.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/collection/action/create-media-collection-action.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-manager.class.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/components/media-picker-create-item.element.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Resolves issue raised in discussion: https://github.com/umbraco/Umbraco-CMS/discussions/16329#discussioncomment-12239268
We discussed and introduced a server-side replacement for "sending allowed children notification" in 15.2, via [this PR](https://github.com/umbraco/Umbraco-CMS/pull/18029), but it had a bit of a design flaw for use for a typical use case where you want to allow only a certain number of items of content of a given type to be created.
We made available the parent document type to the filter, but not the parent content item.  So when filtering allowed types under a given item, you didn't have the details of that item available.
I've resolved with this PR but it needed a bit more update than the previous, as we need to pass the detail of which item we are creating under up …
=>  Added option for filtering the content types allowed as children based on the parent node

src/Umbraco.Cms.Api.Management/Controllers/Template/Query/ExecuteTemplateQueryController.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18536
This fixes the exception triggered for this controller that has obsoleted constructors but none marked as the active one.
Looking at the history you may also be able to remove one of the obsolete constructors as it seems both obsoletions were done in the same PR.
_Should be cherry-picked into the release branch once approved and merged._
=> Fixes multiple available constructors exception for execute template query constructor

src/Umbraco.Web.UI.Client/public-assets/App_Plugins/custom-bundle-package/index.js, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/workspace-action-default-kind.element.ts
Fixes #16700
Fixes [AB#48884](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/48884) (internal HQ tracker)
This pull request includes several changes to improve code readability and maintainability in the `Umbraco.Web.UI.Client` project. The most important changes include refactoring import statements, improving condition checks, and simplifying code logic.
Code readability and maintainability:
* [`src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts`](diffhunk://#diff-a876568cbfcba7766d103e269be6d6d5d8a5851068b5e730a9a4f5a9c1ff81bcL30-R32): Simplified the `render` method by removing redundant ternary operator and using early return for better readability. …
=> V15: Workspace buttons cannot be overwritten in all cases

src/Umbraco.Web.UI.Client/src/packages/core/content-type/global-components/content-type-workspace-editor-header.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/global-components/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/index.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/content-type-workspace-context-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/content-type-workspace-context.interface.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
This PR introduces a `<umb-content-type-workspace-editor-header>` element to align the three Content Type workspace headers.
With this element, it has been possible to remove some duplicated code.
=> Feature: Content Type Workspace Editor Header Element

src/Umbraco.Core/PropertyEditors/Validation/ValidationHelper.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DecimalValueEditorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/IntegerValueEditorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/SliderValueEditorTests.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18528
The linked issue highlights a problem with the property step validation we've added, which will fail if the step is zero due to a divide by zero error.
I've resolved this by always passing validation if the step is zero (which avoids the error, and is also correct as any value is valid for a zero step).
To test, see the tests, and manually see the replication steps on the issue.
_Should be cherry-picked to the release branch once merged._
=> Correct handling of step values of zero

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
The block grid editor doesn't render a Block grid custom view because of a race condition in the extension-slot filtering function.
=> 15.3: Hotfix: block grid custom views

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Infrastructure/PropertyEditors/ColorPickerPropertyEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/SliderPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ColorPickerValueEditorTests.cs
This adds server-side validation to the colour picker, to ensure that the colour you have selected matches one of the configured ones.
As well as the unit tests, to verify manually I've used Swagger and manipulated values to the `PUT /umbraco/management/api/v1.1/document/{id}/validate` endpoint. You should find if you supply a value not in the configured options, you'll get a localized validation message in response.
=> Server side validation for property editors (colour picker)

src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-culture.element.ts, src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-device.element.ts, src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-exit.element.ts, src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-open-website.element.ts, src/Umbraco.Web.UI.Client/src/apps/preview/preview.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Fixes [AB#48437](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/48437) (internal HQ tracker)
When pressing the "Save and preview" workspace action for a document, the preview will open in a new tab and the backoffice tab would refresh in certain circumstances.
It appears that the construction of the URL for the preview tab was being misconfigured if there were extra slashes in the path of the URL. Why this triggers the backoffice tab to refresh, I still can't say for sure. But with the preview URL fix in place, the "Save and preview" workspace action no longer forces a refresh.
=> V15: Resolves "Save and Preview" backoffice refresh

src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/views/edit/block-workspace-view-edit-tab.element.ts
Fixes this issue: https://github.com/umbraco/Umbraco-CMS/issues/18571
Wrapping ungrouped properties with uui-box when editing a block.
Before:
After:
Steps to reproduce can be found in the issue: https://github.com/umbraco/Umbraco-CMS/issues/18571
=> Added uui-box around ungrouped properties during block editing

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorBlockValidator.cs
The base implementation of the block validator does not take into account that the actual implementation can wrap its content/settings data in another object.
This causes issues with the jsonpath returned in validation messages not matching with the actual property path.
To fix this, the hardcoded mapping was moved into a get only overridable string.
The RTE block validator can now signal the correct path to the base class with an override.
Ask Niels 😅
Or setup a doctype with a blocklist/grid and an RTE using the same element doctype that has properties with validation that fails on the backend. Create the node add a block to each property => Save and publish => the validate endpoint should return a jsonpath for the invalid properties in the RTE block that starts with …
=> Fix Rich text block validation path

src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
If there's an existing issue for this PR then this fixes #18379
See the linked issue for details and steps to reproduce/test.
Also, a setup for reproduction has been mentioned in [this forum post](https://forum.umbraco.com/t/block-grid-data-serialization-issue-in-umbraco-backoffice-upgrading-from-15-1-1-to-15-2-2/599/4).
=> Match source block both on culture and alias

src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-extensions-configuration.element.ts
Fixes #18541.
In the Tiptap configuration, the Block extension option detects whether it should be enabled or disabled (based on if there are any Blocks configured for the property-editor). On initial render, the checkbox is enabled, then once a re-render of the component is triggered, it'd become disabled.
This PR resolves this by manually triggering a re-render of the component once the Blocks state has been determined.
=> Tiptap RTE: Block extension enabled/disabled checkbox state

src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
- Removes duplicate registration of Webhooks, seems like this has been there a long time due to a merge conflict 🙈 
Thanks to @bjarnef for raising this 😁
=> v15: Remove duplicate webhook registration

src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/dictionary/entity-action/import/import-dictionary-modal.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18543
Adds missing dictionary import translation keys and aligns instructions with UI.
=> Added missing translations for dictionary import

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Core/PropertyEditors/TextOnlyValueEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/TextOnlyValueEditorValidatorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs
Adds serverside validation to both textbox and text area. 
I've added unit tests, but can also be tested by sending a put request to `/umbraco/management/api/v1.1/document/{id}/validate` or by create a document with a textbox and text area, publishing valid values, and then changing the configurations of the textbox and text area and trying to publish again.
=> V15: Add textbox and text area serverside validation

Directory.Packages.props, src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
Updated dependencies for SixLabors.ImageSharp:
SixLabors.ImageSharp@3.1.6 -> 3.1.7
SixLabors.ImageSharp@2.1.9 -> 2.1.10
https://github.com/advisories/GHSA-2cmq-823j-5qj8
=> V13: bumped imagesharp to prevent CVE-2025-27598

src/Umbraco.Infrastructure/PropertyEditors/SliderPropertyEditor.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/SliderValueEditorTests.cs
Found in testing the release candidate with the starter kit - we need to handle a non-configured maximum for the slider which will be considered as zero.
@nikolajlauridsen - this is a similar issue that you found with a later property editor where we support maximum validation on the server.
=> Fixed issue with slider max validation using default 0 value

src/Umbraco.Web.UI.Client/src/packages/block/block-list/workspace/views/block-list-type-workspace-view.element.ts
This PR fixes issue #17835.
Added a short description to the **hide content editor** section in the block element configuration
=> Added description to block list properties hide content editor

src/Umbraco.Web.UI.Client/src/packages/core/components/input-dropdown/input-dropdown-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Fixes #17271
Adds client-side validation to Dropdown property editor.
- Configure a document-type with a **Dropdown List** property-editor and set the property as mandatory
- Create a new document of the above document-type, enter a name, but do not select a dropdown value
- Attempt to **Save & Publish**, the validation error should appear
- Select a dropdown value, the validation error should disappear
- Press Save & Publish, all should be good.
=> Adds client-side validation to Dropdown property editor

src/Umbraco.Web.UI.Client/src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
Fixes #17271
Fixes #18268
Adds client-side validation to Radio Button List property editor.
- Configure a document-type with a **Radio Button List** property-editor and set the property as mandatory
- Create a new document of the above document-type, enter a name, but do not select a radio button value
- Attempt to **Save & Publish**, the validation error should appear
- Select a radio button value, the validation error should disappear
- Press Save & Publish, all should be good.
=> Adds client-side validation to Radio Button List property editor

src/Umbraco.Web.UI.Client/src/packages/templating/templates/modals/query-builder/query-builder-modal.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18082
I couldn't quite put my finger on why we were getting an intermittent failure here, but seems likely it was related to the separate updates to the sort property and direction, each of which were triggering their own update and server call.  I've combined these in this PR so we update and refresh together, and I no longer see the issue any more.
To test - see reproduction steps on the linked issue.
=> Updates sort property and direction together to avoid intermittent failures

src/Umbraco.Web.UI.Client/src/external/monaco-editor/index.ts, src/Umbraco.Web.UI.Client/src/rollup.config.js, src/Umbraco.Web.UI.Client/vite.config.ts
**Reason**: The cause of this error is due to missing copy files from `node_modules `to `dist-cms` while running build. In addition, the path pointing to js files in web worker has an extra `esm` in it. This leads to not being able to load some js files needed by monoca-editor.
**Solution**: 
Add missing js files to copy from monaco-editor in `rollup.config.js.`
Remove `esm` in the path to some js files.
**How to test?**
Before:
After fixed:
=> Fix bug RTE code editor modal - pretty print not working

src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/move/move-to.action.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.token.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18544
The linked issue notes that it's possible to select the current item as the parent for a move, which isn't valid.
Ideally this would be solved via the `pickableFilter` I would imagine, but I had trouble getting that to work.  So instead have just checked for this condition after selection and presented a friendlier error message.
It would be better to not allow selection in the first place, so if you can find a way to do that, please do, and close this!  But if it's actually tricky, this would probably be an improvement on what we have currently.
=> Prevents attempt to move an item to itself as a parent

src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
Follows on from #18629 and #18632 
Adds client-side validation to Dropdown property editor.
- Configure a document-type with a **Checkbox List** property-editor and set the property as mandatory
- Create a new document of the above document-type, enter a name, but do not select any checkbox list values
- Attempt to **Save & Publish**, the validation error should appear
- Select a checkbox list value, the validation error should disappear
- Press Save & Publish, all should be good.
=> Adds client-side validation to Checkbox List property editor

src/Umbraco.Core/Manifest/PackageManifest.cs, src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs, src/Umbraco.Web.UI.Client/src/json-schema/umbraco-package-schema.ts
Due to an unfortunate mistake in the Umbraco.Cms.Targets generated JSON schema, we alluded to supporting `allowPackageTelemetry` in the JSON files, however the backend didn't support this, but it does now.
=> V15: Support legacy allowPackageTelemetry option

src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Document/PublishDocumentWithDescendantsRequestModel.cs, src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.repository.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
Relates to: https://github.com/umbraco/Umbraco-CMS/issues/13739
Following discussions and release candidate feedback it's been decided that the publish with descendants dialog should not be updated as was proposed in https://github.com/umbraco/Umbraco-CMS/pull/18410
This PR reverts the UI aspects of these changes, so the service level methods are available but we don't clutter the UI for editors that won't normally have need of this option.
**To Test:**
- Verify that the publish descendants dialog now shows only the option to publish unpublished documents, and that the functionality works as expected when selecting or not selecting this option.
_Should be cherry-picked into `release/15.3` when approved and merged._
=> Reverts UI updates from publish with descendants dialog (15)

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Core/Models/ContentEditing/ContentSaveAction.cs, src/Umbraco.Web.BackOffice/Controllers/ContentController.cs, src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs, src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js, src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js, src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
Relates to: https://github.com/umbraco/Umbraco-CMS/issues/13739
Following discussions and release candidate feedback it's been decided that the publish with descendants dialog should not be updated as was proposed in https://github.com/umbraco/Umbraco-CMS/pull/18409
This PR reverts the UI aspects of these changes, so the service level methods are available but we don't clutter the UI for editors that won't normally have need of this option.
**To Test:**
- Verify that the publish descendants dialog now shows only the option to publish unpublished documents, and that the functionality works as expected when selecting or not selecting this option.
=> Reverts UI updates from publish with descendants dialog (13)

build/azure-pipelines.yml
Updated so we only download the chromium browser for our E2E tests as it is the only browser we currently test with
=> V15 QA reduced amount of browser downloaded on pipeline to reduce download time

src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.context.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.context.ts
Fixes #18493.
Awaits the `super.openPicker()` call for Document, Media and Member picker contexts.
=> 15.3: Hotfix: Awaits Open Content Picker

src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-message.element.ts
When using Dark mode in the Back Office, the text you see in the error messages in the log viewer is hardcoded to a black color, which makes it pretty impossible to read.
By removing the hard-coded color, it defaults to the --uui-color-text for all the themes, giving the text the right color.
=> Remove the hardcoded color for the text in error message

src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-cards.less, src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
This PR fixes the issue https://github.com/umbraco/Umbraco-CMS/issues/18535
We will display the user name with an ellipsis at the end and when hovering, the user can see the full text.
Result after fixed:
=> Fix issue text overflow when user name is too long

src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-text-indent-extension.ts, src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts, src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/text-indent.tiptap-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-indent.tiptap-toolbar-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-outdent.tiptap-toolbar-api.ts
Adds the **Text Indent** extension + toolbar button to Tiptap RTE, for text indent/outdent in the text contents.
Another step towards feature parity with TinyMCE RTE.
If using the mock data, then go to the "All RTEs" page and see how it works. If using the server, then configure the Tiptap RTE with the "Text Indent" extension and add the "Indent" and "Outdent" toolbar items, then try it out on a document.
=> Tiptap RTE: Text Indent extension + toolbar items

Directory.Packages.props
Updates to the [latest Examine release](https://github.com/Shazwazza/Examine/releases/tag/v3.7.0) which has fixes for issues surfacing in Umbraco.
To test I've verified that I can still interrogate and rebuild indexes in the backoffice and a simple search implementation based on what we use on umbraco.com still functions as before.
=> Updates dependency on Examine to 3.7

src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-tab.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18684
Took me a while to replicate this one, as I didn't see the issue with Umbraco's starter kit, only the "Clean" one used in the originally posted issue.  But turned out the difference was in properties that are in tabs but not in groups - in this case the root part of the link wasn't set.  It is now following this PR.
**To Test:**
- Create a property on a document type that sits in a tab but not in a group.
- Create a document type that uses this first document type as a composition.
- Make sure you can click the link from the property to access the composition in  a modal editor (see screenshots on linked issue).
=> Fixes link for access to composition from document type property outside of group.

src/Umbraco.Cms.Api.Management/Controllers/User/ClientCredentials/ClientCredentialsUserControllerBase.cs, src/Umbraco.Core/Services/UserService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/UserServiceTests.cs
Fixes: [17506](https://github.com/umbraco/Umbraco-CMS/issues/17506)
This issue already had a fix https://github.com/umbraco/Umbraco-CMS/pull/17536, but it looks like it didn't go far enough.
In this PR a max characters of 255 was set for a client ID, allowing it to fit into the `umbracoUser2ClientId.clientId` field.
But it's also written to `umbracoOpenIddictApplications.ClientId`, and that only allows 100 characters.
So this PR reduces the limit to 100 character and updates the message and testss.
**To Test:**
- Follow reproduction steps in https://github.com/umbraco/Umbraco-CMS/issues/17506
=> Restrict valid API user client IDs to 100 characters

src/Umbraco.Core/Services/ContentService.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18696
The linked issue surfaces that we are currently issuing two content publishing notifications, when there should just be one.  In this PR I've removed the first of these.
Looking back at 13, I think I can see how it came about.  In that version "Save and Publish" was a single operation at the service level, and the notification that I've removed previously was a "ContentSavingNotification".  It was converted to a "ContentPublishingNotification" when the method was changed to just do a "Publish", but we were already issuing one of these later in the operation.  So I believe it's correct we remove the first one, which is what I've done in this PR.
**To Test:**
- Create a simple handler for the `ContentPublishingNotification` such as …
=> Removes one of the two duplicate ContentPublishingNotification publishings

src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18698
The linked issue notes that the files are rendered before the folders in the list of child items when using a static file picker.  This corrects that, so the folders appear first - which is more expected from viewing file systems and aligns with those coming from the file provider ("wwwroot" folder) that are presented below.
Here's the new ordering:
**To Test:**
- Add some files and folders into `App_Plugins`
- From a data type based on a block list, select one of the available blocks and attempt to choose a "Custom stylesheet"
=> Render folders before files in static files picker

src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16129
Seems we do support backoffice routes using GUIDs in Umbraco 13, so this fixes an issue reported when making use of this with macro rendering.  I've amended the request to accept either a GUID or an integer when looking up the content the macros is rendering on.
**To Test:**
- Add a macro in an RTE that renders in the backoffice (e.g. using the simple Partial View Macro File below).
- Amend the URL of the backoffice page that renders the document for editing, amending the integer ID with the page's GUID.
- Make sure the macro renders and no error is thrown.
```
@inherits Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage
<p>Test Macro Rendering</p>
```
=> Fixes issue with macro rendering in an RTE when GUIDs are used for backoffice document routes

src/Umbraco.Cms.Api.Management/Controllers/Media/ConfigurationMediaController.cs, src/Umbraco.Cms.Api.Management/Factories/ConfigurationPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Factories/IConfigurationPresentationFactory.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentConfigurationResponseModel.cs, src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaConfigurationResponseModel.cs, src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberConfigurationResponseModel.cs, src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts, src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document.db.ts
Here I've removed obsolete properties on the configuration response models.
=> Removed obsoletion properties on configuration response  models

src/Umbraco.Core/Strings/Utf8ToAsciiConverter.cs
Here I've just removed the obsoletion, as I think it was incorrectly applied in the first place.  It's the obsoleted method that we are calling from `DefaultShortStringHelper`, and if we change this to use the obsoleted one, all it does is move and repeat the `.ToSpan()` call.  So in this case I think it's cleaner the calling code can stick to working with strings, and just pass a string in, that can then defer to the optimized method.
=> Removed obsoletion of Utf8ToAsciiConverter.ToAsciiString overload

src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18717
The linked issue indicates that we aren't using the [cache settings that we document](https://docs.umbraco.com/umbraco-cms/reference/configuration/cache-settings#seedcacheduration) for seeding the hybrid cache for media.  This PR fixes that, aligning with what we have in `DocumentCacheService`.
Was wondering if this was a breaking concern - but seems to me that it's fixing a bug (i.e. we aren't using the setting we document), and worst case is that it'll revert to default values if someone is using the incorrect settings.
=> Used documented settings for the media seed cache

src/Umbraco.Core/EmbeddedResources/Lang/da.xml, src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Core/PropertyEditors/TextOnlyValueEditor.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18720
As per raised issue, the validation message for text field length was a little friendlier in 13.  This PR updates it to align.
**To Test:**
- Create some content in a text field or text area.
- After the content has been created, amend the data type to set maximum length of less than the amount of characters entered.
- Attempt to re-publish the content, and you should see something like:
=> Adds detail of how many characters you are over when validating text fields for length

src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-bubble-menu.extension.ts, src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-table.extension.ts, src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/base.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-column-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-row-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
Adds a contextual actions menu (bubble menu) when selecting a table's column or row in the Tiptap RTE.
https://github.com/user-attachments/assets/b513edf7-9bd3-4788-bf14-de4b796b9aef
If using the mock data, then go to the "All RTEs" page and see how it works. If using the server, then configure the Tiptap RTE with the "Table" extension enabled and try it out on a document that has `<table>` content.
=> Tiptap RTE: Table column/row bubble menu

src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-toolbar-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
With the Tiptap RTE Table toolbar button, I'd noticed that the menu items are available/enabled when table content is not currently active. I have modified the behaviour of the Table toolbar button to only show the menu items when a table is active, and the Insert Table feature otherwise.
https://github.com/user-attachments/assets/0d0b3610-e1f2-40a3-bbe5-82e9cd522909
From a UI/UX consistency perspective, I am undecided if this is a good modification, or whether the Table toolbar menu items should be disabled when inactive. I'm open to feedback.
=> Tiptap RTE: Refactored Table toolbar button

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
There is currently a bug that prevents random clicking to select a new focal point for an image (on both Chrome and Firefox). This PR fixed that issue by adding a method to listen to the click event to change the focal point.
=> Fix focal point drag not working on firefox

src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/components/user-group-granular-permission-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.token.ts
This PR updates the the UX for document granular user permission to set the user group fallback permissions as a preset for the granular permissions.
See video for example:
https://github.com/user-attachments/assets/f68adfbf-542a-425d-9aac-211b14a13304
What to test:
* ensure that the toggles are correctly checked when adding/editing
* ensure that the correct permission verbs are persisted.
=> Bugfix: Document granular user permission preset

src/Umbraco.Web.UI.Client/src/packages/models-builder/models-builder-dashboard.element.ts
Removes GIIANT header for models builder dashboard and uses UUI-box like other dashboards and sets headline property/attribute
=> Updates dashboard to use uui-box headline property/attribute & place

src/Umbraco.Cms.Api.Delivery/Services/RequestPreviewService.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Delivery/Services/RequestPreviewServiceTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/18730
This PR makes the preview check for delivery API content case insensitive, thus supporting `true` or `True` as is required in the linked issue.
**To Test:**
- See "Steps to Reproduce" in the linked issue.
=> Make preview check for delivery API content case insensitive

build/azure-pipelines.yml
Skips running the SQL Server integration tests on release builds as we are running into issues on the pipeline when running the tests  '      Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Success)
'
=> V13 hotfix sqlserver integration tests

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/libs/context-api/provide/context-provider.controller.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/form-control-validator.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/json-path.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/json-path.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/replace-start-of-path.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/accepted-types/property-editor-ui-accepted-upload-types.element.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/pull/18185 and https://github.com/umbraco/Umbraco-CMS/issues/18734
Mainly based on Cherry Picks from another PR that is not merged yet.
=> hotfix #18735

src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-table.extension.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/constants.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/index.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/constants.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-insert.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-properties-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-properties-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/index.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
Adds a **Table Properties** menu item to the Table toolbar menu in the Tiptap RTE.
Selecting this option will open a sidebar modal with the configurable table properties.
To note, this PR contains customisations to the [Tiptap `TableView` class](https://github.com/ueberdosis/tiptap/blob/v2.11.5/packages/extension-table/src/TableView.ts). We'll need to keep an eye on its behaviour of custom CSS styles.
=> Tiptap RTE: Table Properties toolbar menu + modal

src/Umbraco.Web.UI.Client/src/packages/property-editors/icon-picker/property-editor-ui-icon-picker.element.ts
Aligning Icon Picker style with other inputs
result:
=> style adjustments for Icon Picker, make it look like another input

src/Umbraco.Cms.Api.Management/Security/ExternalSignInAutoLinkOptions.cs, src/Umbraco.Core/Constants-Security.cs, src/Umbraco.Core/Models/UserExtensions.cs, src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Filter.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/UserRepositoryTest.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserGroupServiceTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Editors/UserEditorAuthorizationHelperTests.cs
Here I've removed the obsolete group alias keys from being publicly available and moved them into internal constants to be used for database seeding.  I've then updated the tests and checks that used aliases that could be switched to keys.
There's a behavioural change in that external login auto linking with no options provided will link a user with no groups rather than putting them in editors.  This seems reasonable though - it's best for implementors to be specific about this rather than them defaulting into a group that typically has full content permissions.
=> Removed obsoleted group alias keys from being publicly available

src/Umbraco.Core/Services/PreviewService.cs, src/Umbraco.Core/Web/ICookieManager.cs, src/Umbraco.Infrastructure/Install/InstallHelper.cs, src/Umbraco.Web.Common/AspNetCore/AspNetCoreCookieManager.cs, src/Umbraco.Web.Common/Profiler/WebProfiler.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/PreviewServiceTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/AspNetCore/AspNetCoreCookieManagerTests.cs
This issue was raised as an internal work item so I'll copy it here in lieu of a public issue:
> When previewing documents, the first page view does indeed render draft data as expected. But if you follow a link to another page, the preview session ends.
>This does not happen if you open the site in preview outside the preview IFRAME.
>The culprit is the preview cookie (UMB_PREVIEW). It is not carried along in the subsequent requests within the preview IFRAME due to its missing "SameSite" configuration.
> ![image](https://github.com/user-attachments/assets/f9229954-2bd6-48f3-a6ba-21bbecd8f90b)
On investigation this does look to be the issue.  I experimented with other settings - `strict` and `lax` - but the only one that worked was `none` (which requires also setting the `secure` …
=> Uses correct preview cookie same site and secure settings to allow preview mode to flow between links in the preview frame

src/Umbraco.Core/PropertyEditors/ValueConverters/MemberPickerValueConverter.cs, src/Umbraco.Core/PropertyEditors/ValueConverters/MultiNodeTreePickerValueConverter.cs, src/Umbraco.Core/Services/IMemberService.cs, src/Umbraco.Core/Services/MemberService.cs, src/Umbraco.Infrastructure/Security/MemberUserStore.cs, src/Umbraco.Infrastructure/Services/MemberEditingService.cs, src/Umbraco.Web.Website/Controllers/UmbProfileController.cs, src/Umbraco.Web.Website/Controllers/UmbRegisterController.cs, src/Umbraco.Web.Website/Models/ProfileModelBuilder.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
Here I've removed one obsoleted method in `MemberService` and added an obsoletion message onto it's definition in the interface.  I can't remove this as it wasn't already obsoleted.
In one other case I've removed an obsoletion as again it isn't obsoleted on the interface, and it's inconsistent as the equivalent method for a single member isn't obsoleted.  It's tricky to amend the interface as the change is to a return type, and that would mean introducing a new, non-obsolete method with a different name.  So I think that's better left for a future services refactor.
=> Clean-up obsoletions on MemberService

src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
Resolve an internally reported issue.
After clean-up of an obsolete constructor for Umbraco 16, this error pops up if you try to start Umbraco without the [delivery API enabled in the `Program.cs` file](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#enable-the-content-delivery-api).
To fix I've moved the registration of this component up into the infrastructure project.  This is where it's already defined and implemented, so it works fine.  I'm not sure though why it didn't work before, as the controller that was throwing the error is only used as part of the delivery API.  But I guess it's something to do with controller registration that these delivery API controllers are still loaded into the application even if the delivery API itself isn't enabled.
=> Move registration of delivery API component to infrastructure to resolve issue resolve it from controller

src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/he-il.ts, src/Umbraco.Web.UI.Client/src/assets/lang/ja-jp.ts, src/Umbraco.Web.UI.Client/src/assets/lang/ko-kr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/pt-br.ts, src/Umbraco.Web.UI.Client/src/packages/core/modal/common/discard-changes/discard-changes-modal.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18761
Summary some might press the green button in a fast reaction. So to make the dialog message clear the button will be changed from green to red. Making the message very clear, underlining that "you are discarding something by this action".
And then changing the headline slightly, so it fits with the action.
=> UX: Make discard changes button red

src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/he-il.ts, src/Umbraco.Web.UI.Client/src/assets/lang/ja-jp.ts, src/Umbraco.Web.UI.Client/src/assets/lang/ko-kr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/pt-br.ts
The localizations were the same across all the files so I have removed the duplicated code.
=> Dictionary cleanup: Remove duplicate keys for discard changes

.vscode/settings.json, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts, src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Changes to Validation Controllers that inherit do not automatically sync/report back to the parent.
Instead its possible to report, or setup auto-report.
This gives us support for having user performer changes in modals happen that then get rejected. Today if a user did so and that resulted in validation errors(messages) then those would stay around despite the modal being rejected.
=> Feature: validation synchronization as opt in

src/Umbraco.Web.UI.Client/src/css/dark.theme.css
Adjusting some of the colors for the dark theme so the UI looks a bit better when using the dark theme.
This helps make the coloring a bit more aligned with the standard theme:
Before:
After:
It also fixes the number not being shown when using pagination:
Before:
After:
=> Adjusting some of the colors for the dark theme.

src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-level-tag.element.ts
I adjusted the colors so it ends up looking better on the dark theme.
It is now done in a similar way as the fatal tag.
=> Changes for the debug tag that makes it look better in dark mode

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18788
It looks like this error has crept in as part of https://github.com/umbraco/Umbraco-CMS/pull/18281.  As far as I can see we should be treating filtering out unpublished items at the root in the same was as we are for children in the method I've updated.
Automated test would be nice for this I know - but we don't have any around the published content extensions at the moment, only the services they depend on.  So not sure it makes sense to embark on that (there are many of these extension of course).
To manually test, create items of different types at the root and experiment with code like the following:
```
@{
var allSiblings = Model.Siblings();
var siblingsOfType = Model.SiblingsOfType("testPage");
<div>Siblings: @string.Join(", …
```
=> Fixed issue where siblings of type at route are omitted from the result

src/Umbraco.Core/Actions/IAction.cs, src/Umbraco.Core/Models/TemplateQuery/QueryResultModel.cs, src/Umbraco.Core/Models/TemplateQuery/TemplateQueryResult.cs
Added obsoletion annotations to a few unused things from the days of the old backoffice - particularly things mentioning `Icon` 😆 
- [`IAction.Icon`](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Core/Actions/IAction.cs#L40) and [`IAction.Category`](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Core/Actions/IAction.cs#L54).
- [`QueryResultModel`](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Core/Models/TemplateQuery/QueryResultModel.cs) and its contained [`TemplateQueryResult`](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Core/Models/TemplateQuery/TemplateQueryResult.cs)
Verify that the above-mentioned things are indeed not referenced in the codebase 👍
=> Obsolete a few unused things.

src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts
This issue has not been released yet, so the PR is ignored for release.
Details here: https://github.com/umbraco/Umbraco-CMS/pull/18756#pullrequestreview-2714128108
=> Fix entity user permission modal preset logic

src/Umbraco.Core/Exceptions/DataOperationException.cs, src/Umbraco.Core/Exceptions/InvalidCompositionException.cs, src/Umbraco.Core/Install/InstallException.cs, src/Umbraco.Core/Semver/Semver.cs
This PR removes some dependencies on obsoleted dotnet code that according to their docs wasn't working anymore anyway.
Followed guidance in https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0051 and https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0003
=> Remove syslib003 & syslib0051 obsoleted code dependencies

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-preview.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
The Image Cropper now uses the new dropzone input `<umb-dropzone-input />` to share the logic and user experience. The dropzone input features an uploader UI with manual and auto cancel of uploads, and users can follow the upload progress.
Additionally, the Image Cropper now supports hosting the Backoffice on another URL by prefixing the image URLs with the server URL.
Lastly, an update has been made to read the object URL directly from the `File` object rather than try to load the entire image into memory. This is usually not a problem for images, but we fixed it elsewhere as well, allowing browsers to handle files in the gigabyte range.
Fixes [AB#49148](https://dev.azure.com/umbraco/D-Team%20Tracker/_workitems/edit/49148)
1. Create an Image Cropper property and verify that you can drag …
=> V15: Improve the dropzone for Image Cropper

src/Umbraco.Core/Services/ContentService.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18834
The linked issue demonstrated a problem with a package relying on a property for the parent item that we aren't populating on the copy and move notifications, even though it's the non-obsolete version of the property that they are using.
There's clearly a much bigger refactor to do at some point here - removing all references to integer IDs and replacing them with GUIDs - but for now seems like it makes sense to use the `IIdKeyMap` to populate the parent ID properties as integers and GUIDs.  That's what I've done in this PR.
Can be tested using the following notification handler and inspecting the log messages after a move and copy operation is carried out in the backoffice.
```
using …
```
=> Populate parent key on move and copy notifications

src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Fixes #18842.
The underlying bug was that the Dropdown property-editor's `_options` items wasn't being updated with the `selected` value.
Causing the `input-dropdown` to reset its own `value`.
=> Fixes Dropdown property-editor validation

src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
It is currently possible to drag another file over a "single-mode" dropzone whilst an upload is pending because the **multiple** property is only sent to the internal dropzone as `?multiple`, meaning that only one file could be selected _at a time_. However, we would like its behavior to reflect that `multiple = false` means only one file _ever_ can be uploaded, unless you clear that file.
This disables the internal dropzone if `multiple = false` and an upload is in progress. You need to clear the files/queue before trying to upload something else, unless multiple=true.
A bonus feature is that we allow to show the "uploader UI" to be shown even though the dropzone is disabled, because otherwise the files would be hidden.
1. This is best tested by creating a new media item as the File type …
=> V15: Dropzone single mode should only allow one file at a time

src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.ts
Fixes #18801.
The localization registry filters out the translations by matching the manifest's culture alias, but it was case-sensitive. This patch makes the check case-insensitive by making the culture alias to be lowercase.
=> 15.3: Hotfix: Localization culture alias case-insensitive check

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs, src/Umbraco.Core/Services/IMemberTwoFactorLoginService.cs, src/Umbraco.Core/Services/ITwoFactorLoginService.cs, src/Umbraco.Core/Services/MemberTwoFactorLoginService.cs, src/Umbraco.Core/Services/UserTwoFactorLoginService.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18803
The linked issue indicates that we aren't currently consistent in the obsoletions on `ITwoFactorLoginService` in that we have a newer implementation for users but not members.  This PR adds that.
I've tested by setting up [member two factor authentication as per our documentation](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication) and verified all still works as expected.  I used the following adapted template so we no longer need to use the obsoleted methods.
```
@using Umbraco.Cms.Core.Services;
@using Umbraco.Cms.Core.Services.OperationStatus
@using Umbraco.Cms.Web.UI.Custom.Google2FA
@using Umbraco.Cms.Web.Website.Controllers;
@using Umbraco.Cms.Web.Website.Models;
@inject …
```
=> Adds MemberTwoFactorLoginService

src/Umbraco.Core/Services/UserService.cs, tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Filter.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18812
This PR corrects the logic where we combine the user provided filter with that derived from configuration and the current users permissions, such that setting `HideDisabledUsersInBackOffice` doesn't trigger an exception.
In updating the existing integration tests to verify I found also that it didn't look like the `All` filter was being handled correctly, so I've corrected that too and updated the test.
See steps to reproduce on the linked issue.
=> Fixes null reference exception triggered when configuring to hide disabled users in the backoffice

src/Umbraco.Web.UI.Client/src/packages/documents/documents/modals/save-modal/document-save-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/modal/document-publish-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/modal/document-unpublish-modal.element.ts
Align the UX for "center" dialogs by switching from 'umb-body-layout' to' uui-dialog-layout'.
=> Use uui-dialog-layout for all save + publishing dialogs

src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
If there's an existing issue for this PR then this fixes #18555
This PR fixed for the 'Select All' checkbox in Scheduled Publishing behaves unexpectedly.
**Reason:** 
`selectionManager.selection` not recognized changed value.
**Solution:** 
I added ` this.requestUpdate();` after observing the change of `selectionManager.selection`
**Result:**
https://github.com/user-attachments/assets/0f3d4d91-68bb-4d35-8597-bcb2aeb3b0d8
=> Fix select all checkbox in scheduled publishing

src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
The tests depend on a specific time interval, but the test runner does not guarantee that, and the tests are not strictly necessary anyway
=> V15: Removes flaky localization tests

src/Umbraco.Core/Extensions/DateTimeExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.cs
We have started seeing failures on date comparisons in integration tests run on pipelines, where the extra part of the dates beyond the seconds is used, e.g.:
```
Expected: 2025-04-01 11:45:51.9524108
But was:  2025-04-01 11:45:51.953
```
This updates to ensure that only the date part is compared.
Run the affected integration tests (or let the pipeline do it).
We can cherry-pick this into the 15.3.1 release branch.
=> Ensures date comparisons in schedule integration tests are made only on the datetime part to the second

src/Umbraco.Web.UI.Client/src/apps/preview/preview.element.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18887
Scripts marked with `type="module"` currently fail when previewed due to CORS issues as described in the linked issue.  This can be resolved by amending the `sandbox` element of the preview IFRAME.
See the linked issue.
Consider security implications.  I can't see any downside here as preview is for authenticated users and uses templates provided by the developer's of the Umbraco website.
=> Adds allow-same-origin to preview IFRAME

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/utils.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18862
As described on the linked issue, the preview for the file upload property editor doesn't work for `.webp` files.
And as also indicated there, it's because we don't have the mime type defined for this.
- Setup an upload file data type on a document type.
- Create content using that document type and upload a `.webp` image.
- Refresh and verify that the image preview is shown.
=> Adds webp to mime type map to support preview on upload file property

src/Umbraco.Examine.Lucene/LuceneIndexDiagnostics.cs
The LuceneIndexFolder is not currently showing in the Examine Dashboard, this due to a change to the LuceneDirectory to use NRTCachingDirectory which was not being checked. This PR supports getting LuceneIndexFolder from a NRTCachingDirectory.
The NRTCachingDirectory contains additional information that may be useful to be able to view so I have not extracted only the file path from it but this could be done if deemed relevant.
=> Check for NRT directory when populating LuceneIndexFolder for Examine Dashboard

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
Fixes an issue where the serverUrl was shown twice and changes the component to use `<uui-card-media />` instead.
Benefits include:
- better href
- no custom file symbols
- better a11y
- you can now see the filename
🔴  **BEFORE**
✅ **AFTER**
=> V15: Upload Field should use a better file preview

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-audio.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-image.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-svg.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-video.element.ts
Similar to #18899, this changes the preview of SVGs on the Upload Field to use `<uui-card-media />`.
Fixes #18861
- Adds same preview for SVG and Image using `<uui-card-media />`
- Adds `loading="lazy"` on SVG and Image
- Ensures that neither SVG nor Image can exceed its bounds (try testing with `width: 10000px` for example)
- Adds a `title` attribute on Audio and Video
<details>
<summary>JPG/PNG</summary>
🔴  **BEFORE**
✅  **AFTER**
</details>
<details>
<summary>SVG</summary>
🔴  **BEFORE**
✅  **AFTER**
</details>
=> V15: File upload should use better Image & SVG preview

src/Umbraco.Cms.Api.Management/Controllers/Tree/UserStartNodeTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Services/Entities/IUserStartNodeEntitiesService.cs, src/Umbraco.Cms.Api.Management/Services/Entities/UserStartNodeEntitiesService.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceMediaTests.RootUserAccessEntities.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceMediaTests.childUserAccessEntities.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceMediaTests.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceTests.ChildUserAccessEntities.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceTests.RootUserAccessEntities.cs, tests/Umbraco.Tests.Integration/ManagementApi/Services/UserStartNodeEntitiesServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
If there's an existing issue for this PR then this fixes #18442
See the linked issue for details.
I have added integration tests to prove that the fix works. Since we do not have any tests covering the start items at root level, I have added tests for that as well 👍
Remember to test this for both documents and media.
Also remember that start nodes are additive between user and user groups. Testing might be less confusing if you remove all start nodes from the user group of the user you're using when testing, and only use start nodes defined on the user itself. Of course, a combination of user and user group start nodes would be best.
Note that the default page size is 50 when fetching children in the trees. Thus, it will quickly get cumbersome to test this PR, since a proper test requires …
=> Fix pagination for users restricted by start nodes

src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18912
It appears that the introduction of the property value presets had an inadvertent effect of preventing the scaffolded values to come from content blueprints.  This PR resolves that by ensuring we don't overwrite the values that have been scaffolded from blueprints with and empty set of presets.
- Create a content blueprint for a document with one or more properties filled out
- Create a document based on the blueprint.
- Verify that before the update in this PR the values from the blueprint are not pre-filled, but with this update in place they are.
=> Fix issue preventing blueprint derived values from being scaffolded

src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
I found this issue when testing the 13.8 RC.  It's not a regression introduced in 13.8 as far as I can tell, but still something we could fix up.
You can reproduce by:
- Open up a page on the front-end website.
- In another tab, open the backoffice, edit that page and click "Save and Preview"
- Refresh the first page and you'll see the "View published version?" dialog
- Click "View Published Version" and that would lead to an error as we attempt to parse a non-integer value as an integer.
With the PR in place this will no longer error.
=> Check we have matched a preview URL by ID when exiting preview

src/Umbraco.Cms.Api.Management/Controllers/User/ConfigurationUserController.cs
Support request ([link for HQ](https://umbraco.slack.com/archives/C02JJQU9B/p1742910633947649))
You currently can't create a "User Manager" role - i.e. a set of users that only have access to the Users section.  Whilst you can create the group, a user in it can't access the user's section without being an administrator.  It appears that the only issue here is that a management API endpoint to retrieve configuration for user information is locked down to administrators only.
I've loosened this in this PR, such that it's now restricted to those with access to the Users section.
The endpoint exposes the following - so not something we need to hide from someone with access to the Users section but not being an administrator:
```
public class UserConfigurationResponseModel
{
public bool …
```
=> Remove admin permission on user configuration, allowing users with user section access only to manage users and groups

src/Umbraco.Core/PublishedCache/IPublishedSnapshotService.cs, src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs, src/Umbraco.PublishedCache.NuCache/PublishedSnapshotStatus.cs, src/Umbraco.Web.BackOffice/Controllers/PublishedSnapshotCacheStatusController.cs, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/publishedsnapshotcache.controller.js, tests/Umbraco.Tests.UnitTests/TestHelpers/PublishedSnapshotServiceTestBase.cs
This was raised as an issue in Umbraco Cloud for large sites where the time to rebuild the database cache is quite long. It may go over the hard limit imposed by Cloudflare and although the work continues, the user has no indication that it's completed.
We already implemented this for 15 in https://github.com/umbraco/Umbraco-CMS/pull/18496 but it was felt useful to backport to 13 to support customers on that version.
This PR updates the database cache rebuild operation to move it from a single request/response to a pattern where we submit the task, run in in the background and poll for completion.
It is based on what we are already doing for Examine index rebuilds, so it's a pattern and technique already in use in the CMS that I've just applied to this operation.
To test you can use the …
=> Move database cache rebuild to a background task with polling (13)

src/Umbraco.Cms.Api.Management/Controllers/Document/ValidateCreateDocumentController.cs, src/Umbraco.Cms.Api.Management/Controllers/Document/ValidateUpdateDocumentController.cs, src/Umbraco.Core/Services/ContentEditingService.cs, src/Umbraco.Core/Services/IContentEditingService.cs, tests/Umbraco.Tests.Common/Builders/UserGroupBuilder.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Validate.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Validation errors are currently reported for cultures that exist on a content item but that the editor doesn't have permissions for.  
With this PR I've ensured that we provide the appropriate cultures to validate based on the current backoffice user's permissions.
**To Test:**
You can see this with the following setup:
- Create a document type that varies by culture.
- Create a single text string property, that also varies by culture, and mark it as mandatory.
- Create a second language.
- Create a user group that has access only to the default language.
- Create a user that is only in this user group.
- Make the following request to the management API via Swagger when authenticated as this editor (replacing the document ID, property alias and language as appropriate for your setup):
``` …
```
=> Only apply validation on content update to variant cultures where the editor has permission for the culture

src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
- Create a new doctype with a Date Picker
- Create a new node of that Doctype
- Paste or type a date that matches the format into the input field
- Save and publish node
- The value in the field is saved
If there's an existing issue for this PR then this fixes #16008 
Issue:
The inputChanged method in v13 failed to properly update model values when copying and pasting dates, as it referenced model.datetimePickerValue instead of the raw input value, model.datetimePickerInputValue, leading to incorrect handling and parsing of the input.
Solution:
The logic was updated to use model.datetimePickerInputValue, which contains the raw string input from the user.
By using model.datetimePickerInputValue instead of model.datetimePickerValue, the method now correctly handles user input, ensuring that …
=> V13: attempted fix for Datepicker v13 issue #16008

src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Factories/DocumentCollectionPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Document/Collection/DocumentCollectionResponseModel.cs, src/Umbraco.Cms.Api.Management/ViewModels/Tree/DocumentTreeItemResponseModel.cs, src/Umbraco.Core/Services/EntityService.cs, src/Umbraco.Core/Services/IEntityService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
Relates to the fix necessary for  https://github.com/umbraco/Umbraco-CMS/issues/18517
When evaluating document permissions on the client, there's a need to know the ancestors of the current item.  This is because granular permissions can be assigned on an ancestor document, and they should apply to the current one.
From internal discussion:
> ... I think I have it working correctly for the workspace now. To check the inheritance path, we currently use the /tree/document/ancestors endpoint. It all works fine, but "unfortunately," we have made some updates to the UI which give me some challenges with this endpoint.
We now show the first available "Entity Action" on all tree items and collection items. This means that I would need to check for permissions already when rendering the tree and …
=> Adds ancestor ID details on document tree and collection responses

src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListEditorPropertyValueEditorTests.cs
This fix came from a support issue - [internal link](https://umbraco.slack.com/archives/C02JJQU9B/p1743580444937869) - which noted that with an invariant block list on variant content leads to "Published (pending changes)" being displayed on the info panel - even with no changes pending.  After a fair bit of debugging I found the problem isn't actually with the display, rather it comes from the initial save of the data, which leads to a value of `"null"` being stored as the value in `umbracoPropertyData`.
We then have a comparison of `"null"` v `null` which is detected as a change, hence the display.
It happens in the block value property editor, where we end up serializing `null` - which comes out as `"null"`.  So I've put a check in for that, so we return actual `null`, along with a …
=> Fixes save of empty, invariant block list on variant content

src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
Removes a piece of code that is unnecessary as Modal Discard changes works now.
=> Remove temporary modal skip check

src/Umbraco.Web.UI.Client/src/packages/block/block-rte/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-editors/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-editors/property-editor-ui-block-rte-type-configuration.element.ts
I'd accidentally removed the RTE Block Type Configuration property-editor in PR #18889.
(e.g. the **Available Blocks** field in the Tiptap data-type was blank! 😲)
Adding it back to the codebase, inside to the "block-rte" package.
=> V16: Revert removal of RTE Block Type Configuration property-editor

src/Umbraco.Cms.Api.Management/Controllers/Document/RecycleBin/ReferencedByDocumentRecycleBinController.cs, src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/ReferencedByMediaRecycleBinController.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs, src/Umbraco.Core/Services/ITrackedReferencesService.cs, src/Umbraco.Core/Services/TrackedReferencesService.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs, tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TrackedReferencesServiceTests.cs
Handles an internal work item (HQ link) to support alerting the user with details of referenced item being removed from the recycle bin. // @madsrasmussen 
This PR adds management API endpoints and the upstream service and repository methods to retrieve a list of referenced item from the items in the recycle bin.
- Create a document and a media item
- Create a second document with a content and media picker, where you select the other items
- Delete the referenced items such that they are in the recycle bin
- Query the new endpoints and verify the response.
```
GET /umbraco/management/api/v1/recycle-bin/document/referenced-by?skip=0&take=20
GET /umbraco/management/api/v1/recycle-bin/media/referenced-by?skip=0&take=20
```
Example response:
```
{
"total": 1,
"items": [
{
"$type": …
```
=> Added management API endpoint, service and repository for retrieval of references from the recycle bin

src/Umbraco.Core/Collections/ObservableDictionary.cs, src/Umbraco.Core/Models/Content.cs, src/Umbraco.Core/Models/Navigation/NavigationNode.cs, src/Umbraco.Core/Services/LocalizedTextService.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberTypeRepository.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PublishStatusRepository.cs, src/Umbraco.Web.Common/Helpers/OAuthOptionsHelper.cs
Avoid unneeded Dictionary operations
=> Avoid unneeded Dictionary operations

src/Umbraco.Core/Media/TypeDetector/RasterizedTypeDetector.cs
Remove unneeded double seek.  
Seems to originate from a manual merge.
=> Remove unneeded double seek

src/Umbraco.Core/Extensions/StringExtensions.cs, src/Umbraco.Core/Services/PublicAccessService.cs, src/Umbraco.Core/Services/UserService.cs, tests/Umbraco.Tests.Benchmarks/StringExtensionsBenchmarks.cs
Parse integers directly from stack allocated spans.  
~~I suppose umbraco do quite a few `GetPermissionsForPath` for every page view?  
Especially if a site menu is rendered? 😅~~
The array of strings from the "normal" string `Split` are all allocated on the heap, and needs to be garbage collected at some point.  
That is, both all the strings and also array that contains them, and they are not used outside this method.
Here, I parse integers from spans of the string, none of the beforementioned intermediate parsing allocations are needed.
Only drawback is that we do not know the destination max length, so we might need to resize the list, or a micro 🤏🏻 overallocation.  
To make sure this tweak is worthwhile, I made a benchmark.  
Compared to the production LINQ
71% reduced allocations
56% …
=> Avoid allocating strings for parsing comma separated int values

src/Umbraco.Web.UI.Client/devops/circular/index.js, src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts
This pull request includes changes to improve the handling of circular dependencies and to correct import statements in the icon picker modal element.
Improvements to circular dependency handling:
* [`src/Umbraco.Web.UI.Client/devops/circular/index.js`](diffhunk://#diff-f88d4fba2df8b9c7edc7c1b10e590d32e1ade66d384dbd66cc1f09b633e559a9L55-R60): Introduced a constant `MAX_CIRCULAR_DEPENDENCIES` to limit the number of circular dependencies and added logging to inform the user when the number of circular dependencies is below the threshold.
Corrections to import statements:
* [`src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts`](diffhunk://#diff-79cd0f1d64b23a081cd5861392218d06af8c6c844365a350e5fd2f591f31425eR1-L7): Corrected the import …
=> V16: Remove circular dependency for icon-picker-modal

src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts, src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.test.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/utils/sanitize/escape-html.function.ts
Fixes #18885, #18166 and #18692.
Relocates the `escapeHTML()` call from the localization controller to the `umb-localize` element.
The reason for this is that any arguments passed to the `UmbLocalizationController.term(key, args)` method needed to be HTML entity encoded (to prevent XSS exploits). This has led to Lit's ``` html`` ``` directive double-encoding the resulting HTML entities, (as described in the issues #18885, #18166 and #18692). The `umb-localize` element makes use of the `unsafeHTML()` directive, meaning that it doesn't attempt further HTML entity encoding.
The proposed solution here is to move the `escapeHTML` call from the localization controller - so that Lit can handle the encoding natively, (without double-encoding), and place it in the `umb-localize` element …
=> `umb-localize` encode HTML arguments

src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Dictionary/DictionaryItemTranslationModel.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/18970
As the linked issue shows, you can't remove a specific language translation for a dictionary item, but the backoffice does allow you to create one with not all languages completed.
The reason this works as it does currently is that the backoffice will only send populated translations on create, but on update it sends all.  And in the latter case, we have a `[Required]` attribute which prevents the incoming model from being considered valid.
It's possible to argue that the API is correct and the UI is inconsistent.  But even if on update we only send populated languages, the API endpoint wouldn't remove any not provided (and it's arguably correct that it doesn't).  So given the dictionary entry is updated as one item - the key, …
=> Allow save of empty translations for dictionary items

src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/entity-action/rollback.action.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/modal/rollback-modal.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18945
Issue was a misnamed property in the request update after the change was triggered.
I also notice a console error in passing after cancelling the dialog, so resolved that too.
- Make and publish a few updates for a document.
- Click through to the "Rollback" feature from the "Info" workspace view for the document.
- Click "Prevent cleanup" for one of the version and verify that the button label immediately updates.
- Cancel the dialog and verify that there's no console error.
=> Fixes label of enable/prevent clean up button after update

src/Umbraco.Web.UI.Client/src/apps/installer/database/installer-database.element.ts, src/Umbraco.Web.UI.Client/src/apps/installer/installer.context.ts
Moves logic from installation step to context in order not to destroy the host for the request.
The request is cancelled because the host is destroyed, which now happens because the UmbResourceController actually works again and calls its cancel() mechanism when a host goes away.
=> V16: Installer does not proceed from last step

src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilder.BackOffice.cs, src/Umbraco.Examine.Lucene/AddExamineComposer.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs, src/Umbraco.Infrastructure/Examine/NoopExamineManager.cs, src/Umbraco.Infrastructure/Examine/NoopIndexRebuilder.cs
The upcoming search abstraction layer will need to work as an add-on to V16. For this to happen, we need to be able to disable the current Examine indexes, to let the search abstraction take over.
This PR moves the Examine DI setup to a composer, because composers can be omitted by code 😄 
First and foremost, make sure Examine still works as per usual - that is, indexing and search still works.
Now add a new composer which disables the `AddExamineComposer` of this PR. Something along these lines:
```cs
using Umbraco.Cms.Infrastructure.Examine;
namespace Umbraco.Cms.Web.UI.Custom.Search;
[Disable(typeof(AddExamineComposer))]
public class DisableExamineComposer : IComposer
{
{
}
}
```
Restart Umbraco. The Examine …
=> Make it possible to disable Examine indexes by composition

src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Fixing when appending the layout or other missing properties to ´blocks´ that already is existing and therefor frozen.
So by expanding existing Blocks property it is unfrozen and can have properties appended.
=> Fix: append to frozen object fix for RTE Base

.vscode/settings.json
Makes ESLint able to work despite opening the whole repository in VSCode.
=> set ESLint working directory

src/Umbraco.Core/Services/PublicAccessService.cs
This will avoid allocating strings when parsing the integers, using improvements in #18199 
Also reducing nearly duplicated code
=> Use GetIdsFromPathReversed to avoid allocating the string values of the integers parsed

src/Umbraco.Core/Extensions/ContentExtensions.cs, tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContent.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTests_HideTopLevel_False.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishStatusServiceTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProvider_hidetoplevel_false.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Scheduling.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/ContentExtensionsTests.GetStatus.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/ContentExtensionsTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Since V14, the content schedule dates have been stored in UTC time (for reference, see [this V14 migration](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateSchduledPublishesToUtc.cs) from #15680).
...but we still compare them against the local server time (`DateTime.Now`) when [guarding against scheduling conflicts](https://github.com/umbraco/Umbraco-CMS/blob/v15/dev/src/Umbraco.Core/Extensions/ContentExtensions.cs#L247-L257).
This has some unfortunate side effects when setting up both publish _and_ unpublish schedules within the timespan of the local server time offset against UTC.
Let's say the server runs in UTC+2. If I schedule a publish two minutes from now, and an unpublish a few minutes later, the server eventually …
=> Treat content schedule dates as UTC

src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18973
This was most of a day of debugging to end up with a tiny change!  The issue manifests itself when you try to publish a parent node that has an unpublished child and a published grandchild, i.e.
The publish would appear to succeed from the API and UI perspective, but if you check the database, the published page or the history, you can see it hasn't actually published.
When debugging I could see all the expected database updates were made, but they weren't being persisted.
After a bit of trial and error I found the cause to be in the redirect tracker, which is triggered on a `ContentPublishingNotification`.  This makes a call to `DescendantsOrSelf` which eventually gets to the method I've amended.  At this point we have retrieved a …
=> Make sure not to early return when verifying ancestor path is published without completing scope

.github/CONTRIBUTING.md
Simple fix to "Finding your first issue: Up for grabs" link as this is incorrectly pointing to contributing-before-you-start.md
=> CONTRIBUTING.md - fix incorrect link to contributing-first-issue.md

src/Umbraco.Core/EmbeddedResources/Lang/en.xml, src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml, src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17895
Following discussion in the linked issue, this clarifies the validation message when too many entries are provided.
See reproduction steps in https://github.com/umbraco/Umbraco-CMS/issues/17895#issuecomment-2803658223
Found in RC testing, so seems reasonable this is cherry-picked into the release branch and included in 15.4.
=> Clarified "too many" entries validation message.

src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs, src/Umbraco.Core/Services/IIndexedEntitySearchService.cs, src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs
This PR adds async overloads to the search methods of `IIndexedEntitySearchService`, thus preparing it for any out-of-process search providers that might be built after introducing the ["future of search"](https://github.com/umbraco/rfcs/blob/0027-the-future-of-search/cms/0027-the-future-of-search.md).
Test that global search still works for documents and media.
=> Make the entity search service async

src/Umbraco.Web.UI.Client/src/libs/element-api/element.interface.ts, src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts, src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/localization/stories/localization.mdx
I'd noticed that `UmbLocalizationController` was being references as `UmbLocalizeController` in the code comments/docs/tests.
=> V16: Chore: Corrects `UmbLocalizationController` usage in comments/docs

src/Umbraco.Web.UI.Client/src/packages/core/collection/conditions/collection-alias.condition.ts, src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/recycle-bin-tree-item.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
Marked various context's `.getManifest()` methods as deprecated, (for removal in v18).
Added `UmbDeprecation` warnings with a resolution of using the `.manifest` property instead.
=> V16: Chore: Deprecate `getManifest()` methods

src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/duplicate/modal/duplicate-document-modal.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/19025
Removes the actions from the tree shown in the duplicate document dialog (which aren't required, and can't be used).
Launch the duplicate content dialog from the entity action and verify that the actions aren't displayed.
When approved and merged, consider whether to include in 15.4 or 16.0, and label the issue accordingly.  If 15.4, it needs cherry-picking into `release/15.4`.  If 16, it can be merged as is to `v15/dev` and that branch merged up to `v16/dev`.
=> Removes tree actions from tree selection in duplicate document dialog

src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search-result-item.element.ts
In the backoffice search, the results for Documents would not display the current state.
Now, for Trashed items, the result has faded text + strike-through, along with a "Trashed" tag.
For Draft documents, the result text is faded, along with a "Draft" tag.
If you have a variety of published, unpublished and trashed document content, then open the search modal and query for those documents.
=> Adds trashed/draft state to document search result items

src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/types.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/search/media-search.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/search/types.ts
Adds an option to include/exclude trashed items in the Content Picker Search (for Documents `<umb-input-document>` and Media `<umb-input-media>` configurations).
_Please note, Content Picker is the artist formerly known as MNTP._
_...and this option has not yet been added to the Media Picker property-editor Picker Search, e.g. `<umb-input-rich-media>`._
With a Content Picker property-editor, configured with either Documents or Media, use the Search feature in the picker modal. Try to search for Documents or Media that are in the trash.
=> Content Picker Search: Option to exclude trashed items

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
The focal point should not be pink. As the pink color is for the active location.
We could have used our blue selection color. But to have the highest contrast between the outer and inner borders, then black and white works best:
=> Transparent Focal Point

src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/repository/dynamic-root.repository.ts, src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Whilst investigating issue #18768 (_Content Picker's Dynamic Root on new documents_), I found that PR #18935 introduced the `UmbAncestorsEntityContext`.
For the Content Picker property-editor, we were using `UmbMenuStructureWorkspaceContext` to get the unique IDs for the current and parent documents, (at the time of development, there was no other approach). I've refactored the code to use `UmbAncestorsEntityContext` instead, making the intention of the code clearer.
Initial test is to check if a Content Picker property-editor that is configured to use Dynamic Root still works.
For a more comprehensive test, try the bug reproduction steps outlined in issue #18768.
=> Dynamic Root: Refactored to use `UmbAncestorsEntityContext`

src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/modals/document-type-picker-modal.token.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/picker/document-type-picker-search-result-item.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/picker/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type-search.repository.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type-search.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type.search-provider.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/types.ts
Adds support for a search provider to the Document Type picker.
Adds a `pickerSearchResultItem` element to display the result items, including a tag for Element Types.
Open a Document Type picker, (e.g. on a Document Type workspace > Structure > "Allowed child node types" field), try searching for a document type and/or element type.
=> Adds search to Document Type picker

src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.ts
@iOvergaard I've refined the `umb-localize` render method further after #18960, making use of `when()` to have the `text` argument and remove the `const` assignment.
=> V16: Chore: Refine `umb-localize` rendering

src/Umbraco.Cms.Api.Delivery/Controllers/Content/ByRouteContentApiController.cs, src/Umbraco.Core/DeliveryApi/ApiContentPathResolver.cs, src/Umbraco.Core/DeliveryApi/IApiContentPathResolver.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ApiContentPathResolverTests.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19051
As the linked issue shows, a request to the delivery API to retrieve a content item by route will fail with a 500 rather than a 404 for a file path request.  This is because there's no Umbraco context available for these requests and an exception is thrown as one is expected to exist.
In this update I've checked for a file request and where found, immediately return null and hence 404 to the caller.
Note that this doesn't happen on 15 - due to the removal of the "published snapshot" - a 404 is returned already on this version.  So the fix is needed only for 15.
- Make a delivery API request to an existing route, e.g. `/umbraco/delivery/api/v2/content/item/my-folder/my-page`, and verify the expected 200 response is returned.
- …
=> Handle file paths as not found in delivery API by route requests

.github/ISSUE_TEMPLATE/config.yml
The "create new issue" popup is still pointing at the Our forum, and the security url has changed on .com
=> Incorrect forum and security urls when raising issue

Directory.Packages.props
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19100
The problem shown in the linked issue indicates that we have a mismatched set of dependencies for MiniProfiler.  I've updated them so they align which resolves the linked issue.
Verify using the reproduction steps on the linked issue.
=> Update version of MiniProfiler.AspNetCore.Mvc to align with MiniProfiler.Shared

src/Umbraco.Cms.Api.Management/Serialization/ConfigureUmbracoBackofficeJsonOptions.cs, src/Umbraco.Cms.Api.Management/Serialization/ValidationProblemDetailsConverter.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Serialization/BackOfficeSerializationTests.cs
Fixes #16926 
This PR aims to align the custom complex (nested) validation messages with the default MVC attribute ones. Since the ValidationMetaDataProvider approuch in #18771 was insufficient, a more brute force approach was taken by changing the serialization writing for the `ValidationProblemDetails` class.
See the linked issue for the happy flow, but please do try to break this.
=> Custom serialization for ValidationProblemDetails to allign paths in custom and mvc error messages

src/Umbraco.Web.UI.Client/examples/custom-validation-workspace-context/README.md, src/Umbraco.Web.UI.Client/examples/custom-validation-workspace-context/custom-validation-validator.ts, src/Umbraco.Web.UI.Client/examples/custom-validation-workspace-context/custom-validation-workspace-context.ts, src/Umbraco.Web.UI.Client/examples/custom-validation-workspace-context/index.ts, src/Umbraco.Web.UI.Client/examples/entity-content-type-condition/index.ts, src/Umbraco.Web.UI.Client/src/libs/class-api/class.mixin.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document-type/document-type.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-value-cloner/property-value-cloner-block-rte.cloner.test.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-value-cloner/property-value-cloner-block-rte.cloner.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/property-value-resolver/block-value-resolver.api.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/conditions/constants.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/conditions/types.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/constants.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/types.ts, src/Umbraco.Web.UI.Client/src/packages/core/sorter/sorter.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/form-control-validator.controller.ts, src/Umbraco.Web.UI.Client/src/packages/rte/property-value-resolver/rte-block-value-resolver.api.ts, src/Umbraco.Web.UI.Client/src/packages/rte/types.ts
Example demonstrating how you can build a custom validator that will always have an effect despite the UI not being rendered.
As well, this includes a few updates to make this happen properly.
Watch this intro to get a better idea about how it works:
https://github.com/user-attachments/assets/bc3b658c-1ec3-448f-9f5c-95276c3bdcfc
=> Custom validator example take2

Directory.Packages.props, src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs, src/Umbraco.Web.Common/Mvc/HtmlStringUtilities.cs, tests/Directory.Packages.props, tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs
This PR updates Umbraco's server-side dependencies to their latest non-pre-release versions.
Note that I couldn't update `Microsoft.CodeAnalysis.CSharp` without a similar update in `Umbraco.Code`.  It's not too important though, so we can handle that another time - I've added a `TODO`.
I've removed `Umbraco.CSharpTest.Net.Collections` - as this doesn't look to be used any more.  IIRC it was a dependency of NuCache, which is now replaced with Microsoft's Hybrid Cache.
There are a few major version bumps here, but reading through release notes nothing jumped out as being of concern (e.g. license changes, data format changes).
There were a couple of minor breaking changes.
I've verified that Umbraco builds without any dependency warnings, runs, and unit tests all pass.  Will see on the …
=> Updated server-side dependencies to latest versions for Umbraco 16

src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
If a workspace that extends the content-detail workspace base doesn't include a save token, we currently show an error.
The save token is used to open a dialog that allows you to change a preselection of changed variants.
I have updated the code so that instead of throwing an error for the missing token, we will save what would have been the preselected variants directly. This way, the dialog can be seen as an additional UX improvement to change your selection. If the save token is not provided, we will save all variants with changes.
With these changes, the Document Blueprint workspace is able to create and save again. If we want to provide a similar experience as the Document Workspace, we can introduce a specific modal to handle the blueprint variants.
=> Fix UI creation and updating of Document Blueprints

src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts, src/Umbraco.Web.UI.Client/src/packages/tags/components/tags-input/tags-input.element.ts
Minor style adjustments for Image Cropper and Tags inputs.
Includes Round borders and hover state.
Result:
=> Image Cropper + Tags style adjustments

src/Umbraco.Cms.Api.Management/Mapping/Content/ContentMapDefinition.cs
The server fails to return the default segment for a document when:
- No property values have been defined for the default segment, and
- Other segments have been defined with values.
Kinda hard to explain, so here's a screencast:
[default-variant-with-no-property-values.webm](https://github.com/user-attachments/assets/2c97d6d7-5e8a-4efc-afc4-a9b50d2c9502)
All documents no matter their variance should _always_ yield the default segment from the Management API.
=> Ensure the default segment is always included in API responses

src/Umbraco.Web.UI.Client/package-lock.json, src/Umbraco.Web.UI.Client/package.json, src/Umbraco.Web.UI.Client/src/packages/core/openapi-ts.dev.config.js, src/Umbraco.Web.UI.Client/src/packages/core/package.json
Updates the @umbraco-cms/core dependencies and removes the `server-api-dev` script that has started injecting its own baseUrl rendering it useless.
=> V16: Bumps core dependencies openapi-ts and uuid to latest

src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/extensions/header-app.extension.ts
Fixes: #18979 
Adds `ManifestWithDynamicConditions` to `ManifestHeaderApp` so Header Apps can be conditionally shown/loaded like other Manifest/Extension types.
* Checkout PR
* Verify it builds
* Update or create a new Header App manifest
* Verify Conditions can be added
* Ensure conditions run and load/unload Header App as needed
Add a  simple condition such as this to verify that should make a header app only show if in the Settings section
```json
{
...
"conditions": [
{
"alias": "Umb.Condition.SectionAlias",
"match": "Umb.Section.Settings",
},
]
}
```
=> Add Conditions to ManifestHeaderApp

src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs, src/Umbraco.Core/Cache/Refreshers/Implement/MediaCacheRefresher.cs, src/Umbraco.PublishedCache.HybridCache/NotificationHandlers/CacheRefreshingNotificationHandler.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Cache/DistributedCacheRefresherTests.cs
Fixes #18467
Previously, the `CacheRefreshingNotificationHandler` was used to clear the `IElements` cache, this notification is only published on the publisher, meaning the elements cache wasn't cleared on subscribers. 
This PR changes this behaviour so the distributed cache refreshers are used instead.
I've already tested this on a load balanced setup, and both servers are updated correctly now, maybe follow the steps in #18467 on a single server setup :smile: 
I've also added some super simple integration tests that ensure the elements cache is always cleared when the content or media cache is cleared.
=> V15: Ensure elements cache is cleared on subscribers in load balanced scenarios

src/Umbraco.Cms.Api.Management/Factories/MediaPresentationFactory.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaResponseModel.cs, src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts, src/Umbraco.Web.UI.Client/src/packages/core/backend-api/types.gen.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-caption-alt-text/media-caption-alt-text-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/repository/detail/media-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/types.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/url/info-app/media-links-workspace-info-app.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Following https://github.com/umbraco/Umbraco-CMS/pull/19030 it was raised that we hadn't made the analogous update for media URLs.  These are less critical to remove from the media response model, as there is only one no matter what languages, variants and URL providers that are in place, but for consistency it makes sense to align media and documents here.  Especially as there is already an API endpoint for retrieving media URLs.
So server-side I've obsoleted the `Urls` property on the media response model and am no longer populating it.
Client-side I've reworked the link picker and the media URLs display on the "Info" workspace view to use the dedicated `/urls/` endpoint for retrieving the URL information.
Verify that media and in particular the links on the "Info" workspace view are …
=> Removed population of Urls on media response model and obsoleted property

src/Umbraco.Web.UI.Client/src/packages/core/repository/detail/detail-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/data/tree-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/data-type/collection/repository/data-type-collection.repository.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/duplicate-to.repository.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-bulk-actions/move-to/repository/move-to.repository.ts, src/Umbraco.Web.UI.Client/src/packages/media/imaging/imaging.repository.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/entity-bulk-actions/move-to/repository/move-to.repository.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/repository/member-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/relations/relation-types/repository/detail/relation-type-detail.repository.ts, src/Umbraco.Web.UI.Client/src/packages/user/current-user/repository/current-user.repository.ts, src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/current-user-config.repository.ts, src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/user-config.repository.ts, src/Umbraco.Web.UI.Client/src/packages/user/user/repository/user-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/webhook/webhook-event/repository/webhook-event.repository.ts
With latest update of Context API we do want the Repositories to work as previously, remembering the Stores so they still can update the stores despite being removed from the DOM.
=> make repositories remember their stores

src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/culture-and-hostnames/modal/culture-and-hostnames-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/culture-and-hostnames/repository/culture-and-hostnames.repository.ts
This PR fixes an issue in the "Cultures and hostnames" modal, where the modal would close even if an update failed. This also resulted in the error notification never appearing since the host had disappeared, meaning the user wouldn't know the update didn't happen.
The PR adds a check to close the modal only if the update is successful. Additionally, I have removed the success notification to align with the new notification UX - when the modal closes, the action has been successful.
How to test:
- Insert two identical domains in the list
- Expect an error notification to show
Example
=> Prevent Culture and Hostnames modal close on error

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
- Create a new content node
- Publish the node
- Save and Preview the node (Adding throttling to the request would help test this easily) 
- Progress animation appears until the preview window is open
If there's an existing issue for this PR then this fixes #15360 
Added logic to update `page.previewButtonState` so the spinner is visible when the state is set to 'busy'.
**Bug:**
**Fix:**
=> attempted fix for Save and Preview button #15360

src/Umbraco.Core/Models/ContentBase.cs, src/Umbraco.Core/Models/Entities/BeingDirtyBase.cs, src/Umbraco.Core/Models/IProperty.cs, src/Umbraco.Core/Models/Property.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.Publish.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTests.cs
While working on another task, I realized we have introduced a behavioural change for variant update dates in V14 (and beyond).
In V14, the [`CultureDate`](https://github.com/umbraco/Umbraco-CMS/blob/release/16.0/src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs#L139) of a published culture variant updates when _any_ variant is published on the document.
In V13, the `CultureDate` of a specific published variant only updates when:
- The variant is explicitly published.
- `CultureDate` becomes the datetime of the publish action.
- The variant is edited, and another variant is published.
- `CultureDate` becomes the datetime of the name edit action.
While the latter kinda seems like a mistake, it really is the V13 behaviour, and we need to align with it for V16. So this …
=> Make culture specific update dates work again

src/Umbraco.Cms.Api.Delivery/Filters/AddVaryHeaderAttribute.cs
This fixed as oversight in #19082 - I forgot to add the new "Accept-Segment" to the "vary" response header 🤦 
Request anything from the Delivery API. The "vary" response header should contain "Accept-Segment":
=> Include "Accept-Segment" in the "vary" response header

src/Umbraco.Cms.Api.Management/DependencyInjection/ApplicationBuilderExtensions.cs
When uploading files that exceed the max request body size, we get a HTTP500 from the Management API. It would be preferable to get a HTTP413 instead.
This PR adds a little extra error checking to the generic error handling of the Management API, ensuring to return the actual status code if possible, instead of the currently hardcoded HTTP500.
Configure a low max request body size - something like this in `Program.cs`:
```cs
builder.Services.Configure<KestrelServerOptions>(options =>
{
// 512 kb
options.Limits.MaxRequestBodySize = 1024 * 512;
});
```
Then use Swagger to upload a temporary file larger than the configured max and verify that you'll get a HTTP413 instead of the HTTP500.
=> Output the correct error status code from the Management API

.github/README.md
The current readme has the following shields, which includes "read | discord" that takes you to discord-chats
We surely don't want this link any more as there is no more Q&A on Discord. Instead we should have a link to the forum (and perhaps prioritise this over discord now)?
This PR updates the readme to use a static badge that links to https://forum.umbraco.com that looks like this:
Another option would be to use the dynamic shield that lists the number of users on Discourse. This could look like this:
Not sure if we want the user count. If we think this is preferable to the static badge then I can update this PR accordingly
=> readme shield for forum instead of discord-chats

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
This PR ensures that the workspace split view entity actions are not rendered for new content 
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19050
=> Remove workspace split view entity actions for new content

src/Umbraco.Cms.Api.Management/Controllers/Webhook/Item/WebhookItemControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Webhook/Logs/WebhookLogControllerBase.cs, src/Umbraco.Core/IO/PhysicalFileSystem.cs
This PR handles a couple of low severity security concerns:
- Webhook logs are readable by backoffice users without access to the webhooks feature.
- The validation for reading from the file system outside of the root exposes the resolved path.
For the first issue, verify that the webhook logs are still displayed when logged into the backoffice with a user that has access to webhooks.
Verify that this request to the management API fails with a 403 response when signed in as a user without access to webhooks.
```
GET /umbraco/management/api/v1/webhook/{id}/logs?skip=0&take=100
```
For the second, verify this request to the management API fails but only reveals the originally requested relative path.
```
GET /umbraco/management/api/v1/tree/partial-view/children?parentPath=..%2F&skip=0&take=1 …
```
=> Webhook log authorization and file system path checks

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/copy/copy-to-clipboard.property-action.ts, src/Umbraco.Web.UI.Client/src/packages/clipboard/property/context/clipboard.property-context.ts
After PR https://github.com/umbraco/Umbraco-CMS/pull/19119, the user no longer gets a notification when using the clipboard feature.
The PR adds a success notification when a property value is copied to the clipboard. A notification is necessary here as no other UI indicates that the action has been successful.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18516
=> Add copy to clipboard success notification

src/Umbraco.Core/DeliveryApi/ApiContentBuilder.cs, src/Umbraco.Core/DeliveryApi/ApiContentResponseBuilder.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/Request/ApiContentResponseBuilderTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentPickerValueConverterTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/DeliveryApiTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTestBase.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyV2Tests.cs
The Delivery API current outputs the "global" update date for culture variant content, which makes it hard to detect culture specific changes.
This PR updates the Delivery API output, so the `updateDate` property reflects the "culture date" of the requested content.
Verify that:
- `updateDate` reflects the "culture date" for culture variant content.
- More info on how these are supposed to work and when they should update can be found in the description of #19145
- `updateDate` still works for invariant content.
=> Output culture variant update dates from the Delivery API

src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
Some people have noticed how the Backoffice seems to build even though no files are changed. Our theory is that this happens simply because there are too many input files to consider for the MSBuild target.
In v13, the StaticAssets build was only triggered by the existence of either the output folder or a preserve.* marker file. Here, we also check for the node_modules/.package-lock.json file before reinstalling npm dependencies. Additionally, we now only run `npm install` rather than `npm ci` to optimise the build.
As an aide, you can check how it was done in V13 here: https://github.com/umbraco/Umbraco-CMS/blob/v13/dev/src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
1. Check out this branch
2. Run `dotnet clean` or Clean Solution
3. Run `dotnet run`
4. Check that both the …
=> Build: Avoids rebuilding Backoffice unless it is required

build/azure-pipelines.yml, tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
We were having issues installing some packages when using the `npx playwright install --with-deps` command on linux. We now only install the chromium browser as it is the only one we currently use. 
The test artifacts were also updated to output to junit so we can inspect failed tests directly on the pipeline run
=> V13 QA updated pipeline for acceptance to avoid issue when installing playwright

src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/entity-action/entity-action-list.element.ts
This PR aligns the way we open the entity actions menu in the sidebar with the rest of the backoffice. The benefit of this is to introduce familiarity with the actions so they behave consistently and reduce the necessary mouse movement to access an action.
**Before**
**After**
=> Open entity actions menu as pop up instead of modal

src/Umbraco.Core/Cache/CacheKeys.cs, src/Umbraco.Core/Cache/Refreshers/Implement/MemberCacheRefresher.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
Fixes #18781
The issue was that after #17350 the member username key wasn't evicted from the cache. 
To fix this, I've for now added an extra line clearing this in the `MemberCacheRefresher`
I think a separate task is warranted to align how we generate these cache keys. Currently, each repository generates this cache key internally, which is why this "extension" of the member cache is added as `MemberRepositoryUsernameCachePolicy`; however, at the same time, we have `RepositoryCacheKeys`, which is used to generate the cache keys when clearing the cache in cache refreshers. `RepositoryCacheKeys` also has an optimization to avoid allocation of strings, however, we're missing out on this when populating the caches. I think we should use something like `RepositoryCacheKeys` both places, …
=> V13: Clear Member Username Cache in Load Balanced Environments

src/Umbraco.Web.UI.Client/src/packages/core/modal/types.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/types.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
This PR ensures that all query parameters set through the picker search config are always included in the server request.
Fixes the second part of this issue: https://github.com/umbraco/Umbraco-CMS/issues/19150 - see comment https://github.com/umbraco/Umbraco-CMS/issues/19150#issuecomment-2838055742
This PR will be ignored for the release as it resolves a bug found during the internal testing phase.
=> Ensure picker search config query params are always included in the server request

Directory.Packages.props, src/Umbraco.Web.UI/Umbraco.Web.UI.csproj, version.json
This updates to the latest `Umbraco.Code` which, having had it's dependencies updated, allows us to upgrade some more.
I've also added a couple more related explicit dependencies, which allows us to avoid a couple of warnings we otherwise see in our `Web.UI` project, noted in https://github.com/dotnet/efcore/issues/35143.
=> Further dependency upgrades

src/Umbraco.Web.UI.Client/src/packages/content/content-type/global-components/content-type-workspace-editor-header.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/components/body-layout/body-layout.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-entity-action-menu/workspace-entity-action-menu.element.ts, src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/webhook-workspace-editor.element.ts, tests/Umbraco.Tests.AcceptanceTest/package-lock.json, tests/Umbraco.Tests.AcceptanceTest/package.json, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/MemberGroups.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/Members.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/UserGroups.spec.ts
Experiment with a different location for the entity actions menu within a workspace to align with how we present it in the rest of the UI and to ensure the workspace views are always positioned to the right:
**Before:**
**After:**
=> Reposition workspace entity actions

src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
We do not have the same model in the tree and during the search, so theoretically, we cannot use the same filter. The search item model does not include "isFolder," so it checks for falsy intentionally. We need to investigate getting this typed correctly.
=> Fix filter logic

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts
Today if no Block Types have been created the UI is missing for the Block Area Permissions, this writes a text about why.
=> block grid spell out why there is no permissions UI

src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-cropper/Umbraco.ImageCropper.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
Changed the old Image Crops setting UI to fit the new Backoffice UI
**Old UI**
**Image Cropper**
**Image Media Picker**
Below is a combined image of all the states the new UI component looks like
🔵Blue - View state
🟠Orange - Create/edit state
🔴 Red - Create button
=> Changed the Image crop UI component to fit the new Backoffice UI design

src/Umbraco.Core/DeliveryApi/ApiContentPathResolver.cs, src/Umbraco.Core/DeliveryApi/IApiContentPathResolver.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ApiContentPathResolverTests.cs
#19063 has introduced a regression the Delivery API: It is no longer possible to fetch the route item by path (`/`). 
Additionally, #19063 introduced the new method `IsResolvablePath(string path)` on `IApiContentPathResolver`, as part a fix for handling file requests correctly. But since this handling is not necessary for V15+ due to the changes in caching, the fix has not been forward merged - nor should it. For good measure I've added an obsoletion message to the method in this PR 👍
=> Fix root path regression for the Delivery API

src/Umbraco.Core/HostedServices/IBackgroundTaskQueue.cs, src/Umbraco.Infrastructure/HostedServices/IBackgroundTaskQueue.cs
Resolves https://github.com/umbraco/Umbraco.Forms.Issues/issues/1393
This PR addresses the inadvertent breaking change introduced in 15.4 (see discussion in comment on [linked issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1393#issuecomment-2848621699)).
Although this didn't get picked up by the usual static package validation checks, it wasn't sufficient to inherit from the newly introduced interface in the core project and expect the methods defined on the obsolete one to be found.  Rather we need to keep the methods on the obsoleted interface too.
I've verified the following using a standalone install of the CMS with Forms, comparing before and after using the packages generated from the build pipeline for this PR.
Install CMS 15.4 and Forms 15.1.1 and after submitting a …
=> Restored interface methods on obsolete IBackgroundTaskQueue

src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19086 by adding a variable for `top`.
=> Tiptap cannot set the top position of the toolbar

src/Umbraco.Core/Models/ContentEditing/PropertyTypeBasic.cs, src/Umbraco.Web.UI.Client/src/views/components/umb-locked-field.html
Fixes Umbraco 13.X Back Office exception caused by a user attempting to save a PropertyType with an alias over 255 characters long.
This is fixed by adding a MaxLength attribute to the property in the PropertyTypeBasic class.
Fixes #18421.
=> Fix: #18421 - Added Max Length validation to PropertyTypeBasic Alias

src/Umbraco.Web.UI.Client/src/packages/core/auth/auth.context.ts, templates/UmbracoExtension/Client/package.json, templates/UmbracoExtension/Client/src/dashboards/dashboard.element.ts, templates/UmbracoExtension/Client/src/entrypoints/entrypoint.ts
One line accidentally got changed compared to V15, so getting the latest token through the helpful "openApiConfiguration" object was no longer possible.
This pull request reverts the line to V15, where the token is proxied through the AuthContext, so we don't accidentally call a private member of AuthFlow.
Additionally, I have updated the **umbraco-extension** template to reflect that all contexts are now potentially undefined, because they can be revoked.
This fixes #19207 
Go to a random element like the umbraco-news-dashboard.element.ts and test that you can get the token through the two officially supported methods:
```js
override firstUpdated() {
this.consumeContext(UMB_AUTH_CONTEXT, async (auth) => {
console.log('token 1', await auth?.getLatestToken());
console.log('token 2', await …
```
=> V16 RC: getOpenApiConfiguration().token does not work

src/Umbraco.Web.UI.Client/src/packages/language/app-language-select/app-language-select.element.ts
Edit on - https://github.com/umbraco/Umbraco-CMS/pull/19209 due to changing the release to target v16.0.0
Fixes ↓
[Issue - 19197](https://github.com/umbraco/Umbraco-CMS/issues/19197)
The Language popover in the content tree did not support scrolling, so if you had more languages than the view height, you'd not be able to choose the languages lower down, see below GIF
The language popover does not support scrolling,g and you are able to pick the language you need 
---
_This item has been added to our backlog AB#52593_
=> V16: Main language dropdown does not scroll

src/Umbraco.Web.UI.Client/src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
Edit on - https://github.com/umbraco/Umbraco-CMS/pull/19208 due to changing the release to target 
Fixes ↓
https://github.com/umbraco/Umbraco-CMS/issues/19200
Description
Changed the Block List configuration item limit that is shown from 100
=> V16: Block selector is limited to 100 blocks

src/Umbraco.Core/Services/ContentService.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19252
The linked issue shows that for sites with lots of languages, we can overrun the available field size when logging the details of a save or publish operation.  I've resolved this by recognising that we don't really need to log the full language name.  The ISO code is sufficient and more consistent to be able to identify it, and is much shorter.
I realised having completed this we already had a partial fix from https://github.com/umbraco/Umbraco-CMS/pull/15263 - but this was only for new installs, so we could have more upgrade sites in future that run into this.  Hence I still felt it was worth changing what we log here.
Although only logging, it's theoretically a behavioural breaking change - perhaps someone was relying on and …
=> Log language ISO codes instead of language names

src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
I thought I'd resolved this in reviewing and testing https://github.com/umbraco/Umbraco-CMS/pull/19110, but seems something got missed.
I've added a null check that is necessary for some of the unit tests that call into this code, even though in production we will never have a null here.
=> Handle null for retrieval of content section in unit tests

build/nightly-E2E-test-pipelines.yml
Since the v16/dev branch is deleted and the main branch is new default branch from now on,  I updated the nightly test pipeline to run against the main branch.
=> V16 QA Updated the nightly test pipeline to run against the main branch

src/Umbraco.Core/Configuration/Models/SecuritySettings.cs, src/Umbraco.Core/TimedScope.cs, src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
Although the changes in the latest (security) patches do fix the issue, I noticed `TimedScope` (backported from https://github.com/umbraco/Umbraco-CMS/commit/65bb2801b0d7bf9eb5099dd56ec306050bf7897c or https://github.com/umbraco/Umbraco-CMS/commit/839b6816f2ae3e5f54459a0f09dad6b17e2d1e07) doesn't dispose the `CancellationTokenSource` that's created in the constructors. Also, `CancellationToken.None` was used in the login method, instead of using `HttpContext.RequestAborted` (which would be the same as adding a new action parameter, see [Model Binding in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-9.0#cancellationtoken)): this ensures the server stops waiting as soon as the request is aborted.
The …
=> `TimedScope` improvements and login duration clean-up

src/Umbraco.Web.UI.Client/eslint.config.js
This PR updates the list of allowed tags for our jsDocs to support the tags from https://github.com/runem/web-component-analyzer.
It also lowers the number of warnings a bit.
=> Chore: Update the list of allowed tags for jsdocs

src/Umbraco.Core/PropertyEditors/Validators/RegexValidator.cs, src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs, src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/Validators/IRichTextRegexValidator.cs, src/Umbraco.Infrastructure/PropertyEditors/Validators/RichTextRegexValidator.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/19044
I've taken inspiration from a previous change where a custom required validator was added for RTE fields: https://github.com/umbraco/Umbraco-CMS/pull/16962
In the same style I added `RichTextRegexValidator` which inherits the default `RegexValidator` and ensures that it gets the RTE's Markup value before passing it to the base `ValidateFormat` method.
In the `RichTextPropertyEditor` class I have overridden the default `FormatValidator` with the new custom one.
To test this, please follow the same reproduction steps as mentioned in the issue and confirm that the node containing the RTE with a custom regular expression now can be saved & published successfully.
---
_This item has …
=> Added custom RichTextRegexValidator to validate markup instead of JSON

src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs, src/Umbraco.Web.UI.Client/src/packages/packages/package-section/views/installed/installed-packages-section-view-item.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19275
When a package doesn't define a package Id, it's name is used to identify it's migration status in the `umbracoKeyValue` table.  But when looking for the status, we were only using the ID.
This PR corrects that and also resolves a small localization issue with the "Run pending package migrations" button.
=> Correct the display of pending package migrations

src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-dataset-context/document-property-dataset.context.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
This PR fixes the implementation of the `allowEditInvariantFromNonDefault` config.
This now means that when `allowEditInvariantFromNonDefault` is `false`, it won't be possible to edit invariant culture fields from other cultures than the default.
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/19241
=> Enforce: allowEditInvariantFromNonDefault configuration in the Backoffice UI

src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu-item-layout/menu-item-layout.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
This PR improves the active state check for menu and tree items to prevent highlighting multiple items when paths include the same part.
Currently, these items are both shown as active:
* `/test-1`
* `/test-1-2`
Because `/test-1` is part of both of them.
With the new solution, we add a slash at the end of the part we compare, so the check now looks like this:
* `/test-1/`
* `/test-1-2/`
`/test-1/` is not part of `/test-1-2/`.
=> Improve active state check for menu and tree item

src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19294
The linked issue notes that that the validation we have in place currently prevents selection of an unpublished document in the link picker, and that we supported that in 13.
This PR allows that now, but moving the validation to look at the `name` for the selected URL, which we will always have, rather than the URL.  It also fixes an error that occurred when we didn't get a URL back from the request to retrieve it for the document.
I also noticed that when selecting a document or media URL, we see it's actual URL displayed in the picker.  But on the opening of the picker for a pre-selected link, we see the `localLink` syntax.  So I've also aligned this by requesting the actual URL for display when the picker is loaded.
- Verify …
=> Allow selection of unpublished documents in link picker and align display of URLs

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridblock/gridblock.editor.html
Fixes #15973
Font size and font family styling updated to ensure block grid text styling matches the block list text styling.
Issue:
Fix:
=> Fix for block grid styling regression issue #15973

src/Umbraco.Cms.Api.Management/Controllers/Document/CopyDocumentController.cs, src/Umbraco.Cms.Api.Management/Controllers/Document/MoveDocumentController.cs, src/Umbraco.Web.UI.Client/src/packages/core/resources/api-interceptor.controller.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/duplicate/repository/document-duplicate.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/move-to/repository/document-move.server.data-source.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/19269
This PR corrects the copy and move document operations to check for the "create" permission on the target.
It also adds an interceptor for 403 responses so we can display a more informative error message.
- Set up an editor with permissions to copy, move, delete update and publish only.
- Use the editor to copy or move an existing document
- Verify that an API error is now surfaced.
=> Authorize copy and move destination for the create granular permission

src/Umbraco.Cms.Api.Management/Controllers/Segment/AllSegmentController.cs, src/Umbraco.Cms.Api.Management/Controllers/Segment/SegmentControllerBase.cs
Noticed in a testing that with a user that didn't have access to "Settings" and with segments setup, you'd get a permissions error.  This resolves it by asking only for "Document" section permissions.
Unless you already have segments set up for another reason, likely sufficient to visually inspect this one.
No harm if this goes into 16.0-rc2, since it's a fix to an 16 specific issue.
=> Allow segment access to editors with access to documents, not only settings

src/Umbraco.Web.UI.Client/src/packages/core/components/dropdown/dropdown.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
This PR is a workaround for the bug and fixes #19295
For one reason or another, the 'umb-dropdown` doesn't toggle the popover when the `.open` property is set. I have added two methods to open and close the dropdown, which do the same thing but actually work.
=> Close dropdown after executed action workaround

src/Umbraco.Web.UI.Client/src/libs/observable-api/states/array-state.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-container-structure-helper.class.ts, src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-details.manager.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19299
Only one little breaking change, which is that `getRootContainers` of `UmbContentTypeStructureManager` is now an async method.
=> hotfix: #19299

src/Umbraco.Core/Extensions/StringExtensions.cs, src/Umbraco.Core/Models/ContentBase.cs, src/Umbraco.Core/Services/ContentService.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceVariantTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19287
The linked issue shows that Umbraco was previously a little more accepting of mixed case cultures, presenting a case that will blow up with invalid content if programatically created in the way demonstrated.
As is noted, the problem can be avoided by the developer ensuring to provide correctly cased culture codes.  But it seems we can correct for this ourselves by ensuring to create a `CultureInfo` from the code, which will accept mixed case but once created have a `Name` property that is consistently and correctly cased.
See the linked issue or review the integration tests that I've created based on the provided case.  The second test that accepts mixed case was verified to fail before the amends in this PR were made.
=> Ensures cultures set on content are correctly cased

src/Umbraco.Core/Services/DomainService.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19104
The behaviour described in the linked issue occurs due to two operations being requested on the domains collection:
- A save for each domain
- A sort for each domain that's not already sorted
In most cases, we aren't sorting as well as saving, so we can short-circuit and not publish the second notification when we aren't making any changes to sort order.
When we are sorting, it's strictly correct to publish two notifications as we are making two separate saves.
=> Avoids unnecessary additional domain save notification publishing when sorting an already sorted collection of domains

src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19182
Although integer IDs are used for backoffice routes in Umbraco 13, we mostly support replacing the integer ID with it's GUID equivalent.  But not for data type references as shown in the linked issue.
This PR adds that support so that these requests are resolved.
- Navigate to a data type that's used on a document type and verify you see the references shown on the "Info" panel.
- Look-up the data type's GUID and manually change the route so this is used in place of the integer ID.
- Verify the references are still shown.
=> Adds support for retrieval of data type references when data type is routed using a GUID

src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
#17681
This PR looks to reset the security stamp back to previous when doing the signin behind the scenes in the same way lastlogindate is being reset. This allows the action to happen again until the user completes the process.
=> User invite email fails if visited more than once without completing

src/Umbraco.Web.UI.Client/src/packages/user/current-user/action/current-user-app-button.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user-action.extension.ts, src/Umbraco.Web.UI.Client/src/packages/user/current-user/external-login/manifests.ts, src/Umbraco.Web.UI.Client/src/packages/user/current-user/mfa-login/manifests.ts
Removes the option to set a `look` and `color` for the current user actions — we are not interested in this type of customization, as it pollutes the visuals, by taking unnecessary attention or unnecessary inconsistency. As well this is making it hard for us to move ahead with the future plans of this dialogue, where these buttons might have to be relocated to a more proper place. Therefore, these buttons will stay normal buttons with equal visual attention.
=> hotfix: remove current user action look and color

src/Umbraco.Web.UI.Client/src/packages/core/utils/media/image-size.function.ts, src/Umbraco.Web.UI.Client/src/packages/core/utils/media/image-size.test.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/media-upload.tiptap-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/media-picker.tiptap-toolbar-api.ts
Fixes #18020.
Modifies the Tiptap Media Picker code to make use of the imaging repository, to get the resized URLs from the server.
This adds support for ImageSharp's HMAC security parameter.
Related PR: #19331.
=> Tiptap Media Picker: ImageSharp HMAC support

src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts, src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/components/sysinfo.element.ts, src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts
* Rearrange sysinfo debug for a better overview
* See if we can pull in the client version directly from the package.json to verify against the server version
* Adds information directly from the TemporaryFileConfiguration repository such as allowed/disallowed upload types and file max size
* Fixes a small UI issue where `#code-block` and `#codeblock` were used intermittently in the CSS
**Before:**
**After:**
Example output:
```
Umbraco system information
--------------------------------
Server Troubleshooting: 
Server OS: Darwin 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000
Server Framework: .NET 9.0.2
Default Language: en-US
Umbraco Version: 16.1.0-rc.preview.21
Current Culture: en-US
Current UI Culture: en-US
Current …
```
=> V16 RC: Add more debug info to System Information

src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
This pull request refines error handling in the `UmbTemporaryFileManager` class to improve robustness and user feedback. The key change is the introduction of a more structured check for `UmbApiError` instances and the addition of a fallback notification mechanism for unhandled server errors.
* [`src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts`](diffhunk://#diff-00488f81a35c2e66a81060a6f5fb0f6e44cab57b4cc9b350e8fa44624a86b76aL191-R204): Replaced a direct instance check of `UmbApiError` with a static method `isUmbApiError` for better type safety and readability. Added a fallback to display a user notification for unexpected server errors, ensuring all error cases are handled gracefully.
* Made sure that not only 413 errors but all errors are shown …
=> V16 RC: File upload errors should be shown to the user

src/Umbraco.Web.UI.Client/src/packages/core/workspace/info-app/global-components/workspace-info-app-layout.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/document-item-data-resolver.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/document-urls-data-resolver.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/index.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/info-app/document-links-workspace-info-app.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/repository/types.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18317
This PR updates the Multi URL Picker UI to render variant-aware URLs and adds the variant name to the URL title field. It introduces a DocumentURLsDataResolver to obtain the variant-aware URLs. This resolver is now reused for both the workspace URLs in the info app and the Multi URL Picker.
The workspace URLs now display only the URLs for the active variant unless the document is invariant; in that case, it will show all URLs.
**Updates to the Multi URL Picker**
https://github.com/user-attachments/assets/f6f8a7b7-f747-4aad-8250-c2edfeb175ac
**Updates to the document URLs app**
https://github.com/user-attachments/assets/f3fc25ee-8ee4-42e8-8459-a6272dcd67fd
=> Document URLs Data Resolver

src/Umbraco.Core/Templates/HtmlImageSourceParser.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlImageSourceParserTests.cs
Similar to the fix we did for the local link parser in #17288, the `HtmlImageSourceParser` should not care for the order of attributes. This fixes an up until now unknown bug with Tiptap, which switches the attributes `src` and `data-udi` around and is hard to control.
1. Insert an image in a Tiptap editor
2. Edit the image path to something like `/media/test`
3. Verify that the original path is still set and works on the website frontend
=> V16 RC: HtmlImageSourceParser should not care for order of attributes

build/nightly-E2E-test-pipelines.yml
Disabled SQLite tests and made it run against the release/16.0 branch
=> V16 QA Updated E2E nightly pipeline

src/Umbraco.Infrastructure/Serialization/JsonBlockValueConverter.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/JsonBlockValueConverterTests.cs
If there's an existing issue for this PR then this fixes #19332
When JsonBlockValueConverter.cs encounters an unsupported block alias and its children contains an array the reader will end up in an invalid position to continue reading due to reading to the next `JsonTokenType.EndArray` even if it ends on a nested array.
Not sure how to recreate this by hand since we encountered it with existing content during an upgrade from Umbraco 13 to 15.
=> Fix for invalid state in JsonBlockValueConverter when an unused layout has a nested array

.github/ISSUE_TEMPLATE/config.yml, .github/README.md, build/azure-pipelines.yml, build/nightly-E2E-test-pipelines.yml, src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockGrid/ComplexBlockGridTest.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockGrid/SecondLevelBlockProperties.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockList/SecondLevelBlockProperties.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/RichTextEditor/SecondLevelBlockProperties.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/RichTextEditor/TiptapStyleSelect.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/RichTextEditor/TiptapToolbar.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/TrashContent/BulkTrashContent.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/TrashContent/TrashContent.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/RichTextEditor.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Tiptap.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/Media.spec.ts, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MemberRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListEditorPropertyValueEditorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
This PR handles the merge of changes from v15/dev to release/16.0
=> Merged v15 dev to release 16

src/Umbraco.Cms.Api.Management/Factories/DocumentVersionPresentationFactory.cs
This relates to issue #17149, as it was also being caused by having entries with user id 0.
Details regarding the initial issue and how to test can be found in PR #19263.
In this case, instead of just opening the info tab, you will need to open the Rollback section.
The following code can be used to perform a publish with user id 0.
```cs
[Route("api/test")]
public class TestController : ControllerBase
{
private readonly IContentService _contentService;
public TestController(IContentService contentService)
{
_contentService = contentService;
}
[HttpGet("")]
public IActionResult Get()
{
// Replace the GUID with the id of the content you created to test
IContent content = _contentService.GetById(Guid.Parse("efd8a078-14d8-47f7-b22c-52d34944b6b0")) ?? throw new InvalidOperationException(); …
```
=> Handle user id 0 (Unknown/System) when building content version response

src/Umbraco.Web.UI.Client/examples/validation-context/validation-context-dashboard.ts, src/Umbraco.Web.UI.Client/src/libs/context-api/consume/context-consumer.ts, src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultiURLPicker.spec.ts
Fix example and make sure super.destroy is handled first. And only trigger the callback with undefined once.
=> Validation Context destroys self destroy before clean up

src/Umbraco.Core/Cache/AppCacheExtensions.cs, src/Umbraco.Core/Constants-Cache.cs, src/Umbraco.Infrastructure/Cache/DefaultRepositoryCachePolicy.cs
I have noticed the back-office being noticeably slow during development of some websites (V13). The console output is **flooded** with the following while navigating the CMS:
```
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in Umbraco.Core.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidCastException' in Umbraco.Core.dll
...(thousands of times)...
```
This PR updates `GetCacheItem` to check for `NullRepresentationInCache`. This prevents the above flood of exception handling and also improves performance. Umbraco was seemingly trying to cast the string `"*NULL*"` to `IDictionaryItem` thousands of times while doing basic operations such as …
=> fix: check for NullRepresentationInCache in AppCacheExtensions

src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/index.ts, src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.context-token.ts, src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.context.ts, src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.element.ts, src/Umbraco.Web.UI.Client/src/packages/content/content/content-property.context-token.ts, src/Umbraco.Web.UI.Client/src/packages/content/content/index.ts
Providing 'content property context' under the name 'property type based property context'. keeping the old and marked that as deprecated, with removal in v.18.
=> additional context name for 'content property context' 

src/Umbraco.Cms.Api.Delivery/Services/RoutingServiceBase.cs, src/Umbraco.Cms.Api.Delivery/Umbraco.Cms.Api.Delivery.csproj, tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/RequestRoutingServiceTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/18982
The linked issue presents an example where the delivery API isn't able to route by path due to the path containing special characters.  The issue seems to be related to the conversion of the requested route as a string to a `Uri`, and then using the `AbsolutePath` property.  This encodes the values which then doesn't match with the cached URL segment and routing fails.  Using `LocalPath` retains the decoded values.
Replicate the scenario provided in the linked issue (there's a uSync export that can be imported to setup - I had a bit of trouble when trying to do so solely from the description).  I've done this though, so you may consider it's not necessary to repeat, particularly given some integration tests are provided, one of …
=> Fix issue with requests to delivery API by path where URL segment contains special characters

src/Umbraco.Core/PublishedCache/IPublishedCache.cs
Just correcting an obsoletion message
=> Use correct service name in obsoletion method

src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextElementParser.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19388
This PR removes unnecessary newlines between HTML elements in the JSON output for rich text in the delivery API, retaining the spaces between inline elements applied via https://github.com/umbraco/Umbraco-CMS/pull/17983.
Add mark-up to a rich text editor with line breaks.
Verify the output when requesting an the content item with the rich text property that unnecessary line breaks are removed, but spaces are retained between inline elements.  See the unit tests for samples.
The delivery API needs to be enabled with the following configuration:
```
"DeliveryApi": {
"Enabled": true,
"RichTextOutputAsJson": true,
```
=> Removes unnecessary newlines from rich text as JSON delivery API output

templates/UmbracoProject/.template.config/starterkits.template.json, version.json
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19389
This PR updates the starter kit reference to align with Umbraco 16 and adds a `TODO` to remember to remove the RC suffix with 16 final is prepared.
See linked issue.
=> References correct starter kit version for Umbraco 16

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
fix the variant selector so hover uses themes colors (previously it was white in white, so not readable)
=> hotfix: correct dark theme color for variant selector

src/Umbraco.Core/Routing/NewDefaultUrlProvider.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19402 (although the complete resolution won't come until 17, we can close this after this PR is merged as there are no further immediate actions and those needed later are indicated in the obsoletion messages).
This PR is just some minor refactoring and preparation for Umbraco 17 when we can finally remove the obsolete parameters in the constructor for this class.  I added a new constructor using the replacement for the obsolete `ILocalizationService`, removed the unnecessary regions and resolved the remaining warnings in the class.
Should be clear from visual inspection there's no concern with the changes, but I have verified that URLs continue to be generated having booted up Umbraco.
=> Cleaned up constructors, regions and variables in NewDefaultUrlProvider

src/Umbraco.Web.UI.Client/src/libs/context-api/consume/context-consumer.test.ts
Fixes the units tests as the context API does not call callback with undefined unless there was a instance send earlier.
the issue originates from this PR https://github.com/umbraco/Umbraco-CMS/pull/19367
=> fix context api test

src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-property.element.ts
There was a naming mistake here, which does not affect anything currently, but should be corrected — cause I think that is just a coincidence.
(This code is new for 16)
=> Fix observe property string name

src/Umbraco.Web.UI.Client/src/libs/controller-api/controller-host.mixin.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultiURLPicker.spec.ts
Ensure a controller is still present to avoid calling hostConnected on a controller that already have been removed again.
Its a bit of an edge case, but if the user navigates super fast, or the router resolved a route that then gets replaced within a JS cycle after then this can occur.
=> Ensure controller is still present

src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-repository-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-repository.interface.ts, src/Umbraco.Web.UI.Client/src/packages/core/router/router-slot/router-slot.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/controllers/workspace-is-new-redirect.controller.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts
Fixes issue with creating Documents from a Collection, on a real server, where 2. 3. or 4. time ends up the the modal URL stay despite the modal closing. which prevents the user from navigating to that exact URL again.
Please carefully test various deep modals etc. complex URL situations.
=> Closing redirecting modals fix

src/Umbraco.Web.UI.Client/src/packages/documents/documents/types.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/index.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/types.ts
Exports new types from documents/documents/url
Fixes #19413
=> V16-RC: Not all types are exported from 'documents'

src/Umbraco.Web.UI.Login/package-lock.json, src/Umbraco.Web.UI.Login/package.json, src/Umbraco.Web.UI.Login/src/components/layouts/new-password-layout.element.ts, src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts, src/Umbraco.Web.UI.Login/src/components/pages/reset-password.page.element.ts, src/Umbraco.Web.UI.Login/src/contexts/auth.context.ts, src/Umbraco.Web.UI.Login/src/contexts/auth.repository.ts, src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts
> [!NOTE]
> We can upgrade to a public Umbraco 16 RC version on the login screen because we only need to match the typings
This pull request introduces several updates to the `Umbraco.Web.UI.Login` project, focusing on dependency upgrades, improved error handling, and code consistency. The most important changes include upgrading dependencies in `package.json`, enhancing error handling in various components, and improving code readability and consistency by updating imports and formatting.
* Updated `@umbraco-cms/backoffice` to version `16.0.0-rc3`, `@hey-api/openapi-ts` to `^0.67.3`, `typescript` to `^5.8.3`, and `vite` to `^6.3.5` in `package.json` for compatibility with the latest features and bug fixes.
* Added checks for `authContext` availability in `UmbNewPasswordLayoutElement` and …
=> V16: Upgrade Login dependencies to Umbraco 16

src/Umbraco.Core/IO/MediaPathSchemes/UniqueMediaPathScheme.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/IO/MediaPathSchemes/UniqueMediaPathSchemeTests.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19377
The linked issue raises the concern that it's possible to create overlapping media file paths with certain pairs of unique GUIDs.  This is known, but the historical consideration has been that the chance is very low and it's better not to chase 100% uniqueness at the cost of very long folder paths.  It's always possible to register a custom `IMediaPathScheme` - either the `TwoGuidsMediaPathScheme` we ship with or a custom implementation as provided in the linked issue.
What's new is version 7 of GUIDs, that contain timestamps, and as such if raised in very quick succession could have the same first eight characters and hence generate colliding paths.  Umbraco doesn't use these, so there's no problem with backoffice operations. …
=> Throw if attempting to use the default unique media path scheme with version 7 GUIDs

src/Umbraco.Web.UI.Client/src/packages/log-viewer/components/log-viewer-date-range-selector.element.ts
The log viewer date range input was changed from using `input` to `umb-input-date`, but the event handlers weren't updated accordingly.
If there's an existing issue for this PR then this fixes #19382.
=> Use the proper `umb-input-date` events in the log viewer date range element

src/Umbraco.Web.UI.Client/src/packages/log-viewer/repository/sources/log-viewer.server.data.ts, src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-message.element.ts, src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/entity-actions/rename/rename-partial-view.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/repository/partial-view-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/tree/folder/repository/partial-view-folder.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/scripts/entity-actions/rename/rename-script.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/scripts/repository/script-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/scripts/tree/folder/repository/script-folder.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/rename/rename-stylesheet.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/repository/stylesheet-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/tree/folder/repository/stylesheet-folder.server.data-source.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/19446
In testing we found that when running under IIS errors were thrown when requesting script, stylesheet and partial view files.  Using Kestrel didn't show these issues.  The requested path string was being double encoded - once in our own code and once automatically via the typed HTTP client.  Seemingly the latter web server could handle this, but not the former.
Removing the double encoding by removing our initial encoding before the request is passed to the typed API client looks to resolve the issue.
Verify script, stylesheet and partial view files and folders can be created, retrieved, updated and deleted (I've done this on Windows, using both IISExpress and Kestrel).
=> Removed encoding of request to retrieve files and folders by path, to avoid double encoding via the typed client

src/Umbraco.Web.UI.Client/src/packages/core/collection/components/collection-filter-field.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/create-blueprint/modal/create-blueprint-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/user/user-group/collection/user-group-collection.element.ts
Fixes the styling of the uui-input in various locations, mainly when used as a filtering input on collections and extensions insights:
=> Fix: filter input styling

src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.context-token.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/tree/media-tree.context.ts
Fixes #19449.
Due to a name change in #19375, the `UMB_CONTENT_PROPERTY_CONTEXT` token no longer resolved.
This hot-fix updates the context alias (with `UmbPropertyTypeBasedPropertyContext`) so that the context can be resolved.
I have also updated the references of deprecated `UMB_CONTENT_PROPERTY_CONTEXT` to use `UMB_PROPERTY_TYPE_BASED_PROPERTY_CONTEXT` instead.
=> V16 Ensures backwards compatibility of deprecated `UMB_CONTENT_PROPERTY_CONTEXT`

src/Umbraco.Cms.Api.Management/Controllers/ManagementApiControllerBase.cs
Came up via an internal support request.
It's been identified that in Umbraco 13 we specifically disabled caching on any backoffice API requests, but we don't do the same on the management API.  Although there's no evidence this has caused issues with usage via the backoffice, this can lead to cached responses being returned when a CDN is in the mix.
As such I've added the existing attribute for disabling the browser cache to the base management API controller.
Verify the headers you see on the response.
Before:
After:
=> Adds attribute to ensure management API requests are never cached in the browser or via a CDN

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19499
The linked issue describes an error that occurs with the implementation provided in https://github.com/umbraco/Umbraco-CMS/pull/19273, which is intended to ensure logins relating to backoffice users associated with external login providers are removed when the provider is removed from configuration.  This was added to improve security with the [Umbraco Cloud external login provider feature](https://docs.umbraco.com/umbraco-cloud/set-up/external-login-providers), but provides the same benefit to other setups where external login providers are used.
Investigating revealed two issues, both of which are resolved in this PR:
- Some external login provider setups will store tokens as well as user logins.  These need to be deleted …
=> Fix issues with removal of user logins on change to external login provider configuration (13)

src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-statusbar-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
Fixes #19009.
Prevents setting the toolbar/statusbar `value` until after the component has been initialized.
To test, follow instructions from issue #19009.
=> Tiptap RTE: Toolbar/statusbar config initial value state

src/Umbraco.Core/Services/DocumentUrlService.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/DocumentUrlServiceTests.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19497 reporting a significant deterioration in start-up time for sites with many published documents.
The linked issue reveals a poor choice of data structure used to convert the persisted document URLs (stored with a record for each document/language/state/segment) to the model used for caching. This runs on start-up for all document URLs and the existing use of a `List` is exponentially slower than an implementation with a `Dictionary` as provided here.  And as the benchmark unit test has shown.
The regression was introduced via https://github.com/umbraco/Umbraco-CMS/pull/18603.  
Verify existing integration tests pass and check routing of a document requested via it's URL works as expected.
=> Optimize initialization of document URLs on start-up

src/Umbraco.Core/Services/ContentService.cs, src/Umbraco.Core/Services/IContentService.cs
Closes #19352
A proper fix was done for V16 in #19528, but for V13 it would be more tricky as we wouldn't want to introduce new methods or a behavioral change. Instead, a remark was added to the method's xml docs to warn users.
=> Add a warning to the `CreateContentFromBlueprint` method xml docs

src/Umbraco.Cms.Api.Management/Controllers/Document/MoveDocumentController.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19547
Looks like this was a bad merge at some point, as we have the correct permission checks in place but then also were calling the old, incorrect ones.
See linked issue - with a setup like this for a user, previously the move operation would be denied.  With these changes in place, it succeeds.
Permissions: Read, UI Read, UI Write
Granular Permissions:
=> Removed duplicate/obsolete code fixing issue with document move permission checks

src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/create-blueprint/modal/create-blueprint-modal.element.ts
Noticed in testing functionality related to blueprints that the dialog isn't really styled very well.  This updates it to match other similar screens.
Before:
After:
=> Improves the layout on the create blueprint dialog

tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithImageCropper.spec.ts
Removed flaky test from running on each PR until we have fixed the test, currently the test only fails occasionally on the pipeline. I cannot recreate the issue locally
=> v16 QA Remove smoke tag from flaky test 

src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/constants.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-statusbar-configuration.context-token.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-statusbar-configuration.context.ts
Adds and exports a `UMB_TIPTAP_STATUSBAR_CONFIGURATION_CONTEXT` token, for the Tiptap RTE statusbar context.
This has no impact on functionality, it is more from an API perspective and to feature match the toolbar's `UMB_TIPTAP_TOOLBAR_CONFIGURATION_CONTEXT` token.
=> Tiptap RTE: Adds token for statusbar context

src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/repository/detail/media-detail.server.data-source.ts, src/Umbraco.Web.UI.Client/src/packages/members/member/repository/detail/member-detail.server.data-source.ts
This issue was introduced in https://github.com/umbraco/Umbraco-CMS/pull/19292 (to be released in `16.1.0`) and was preventing the fields from being filled in (based on the blueprint) in the UI.
Due to the usage of `umbDeepMerge(defaultData, preset)`, since the `values` and `variants` were set to `[]`in `defaultData`, they wouldn't be `overridden` by the ones in `preset`.
By changing the order of the parameters to `umbDeepMerge(preset, defaultData)`, the `preset` values now take precedence.
With a blueprint:
Before the fix:
After the fix:
=> V16.1: Fix broken content creation when using blueprints

src/Umbraco.Web.UI.Client/src/packages/core/components/table/table.element.ts
Fixes #19563.
The reason for the misalignment with the table row's icon and checkbox (on hover), is that the `<uui-checkbox>` component had whitespace (newline) within the slotted content, causing the component's `flex` layout to add a `gap` between the checkbox input and the whitespace. By removing the whitespace, the gap is removed, realigning the icon and checkbox.
=> Table checkbox/icon alignment

src/Umbraco.Core/Configuration/Models/NuCacheSerializerType.cs
Relates to https://github.com/umbraco/Umbraco-CMS/issues/19544
We currently offer a legacy configuration option for cache serialization that's no longer supported since the introduction of the hybrid cache implementation, and has some issues with particular property types such as integers.
To make it work changes would be needed to property type converters, e.g. 
```
public override object ConvertSourceToIntermediate(
IPublishedElement owner,
IPublishedPropertyType propertyType,
object? source,
bool preview)
{
if (source is JsonElement jsonElementSource && jsonElementSource.ValueKind == JsonValueKind.Number)
{
return jsonElementSource.GetInt32();
}
return source.TryConvertTo<int>().Result;
}
```
I considered that as there's no reason to use this option over the faster and more compact …
=> Adds XML header docs indicating usage of options on NuCacheSerializerType

src/Umbraco.Core/Extensions/DateTimeExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/DateTimeExtensionsTests.cs
Have seen some tests failing on `main` due to date comparisons going beyond the millisecond and see dates as different when we should consider them the same.
E.g.:
```
Failed Updating_Single_Variant_Property_Does_Not_Change_Update_Dates_Of_Other_Variants
Error Message:
Expected: 2025-06-07 00:32:57.9074126
But was:  2025-06-07 00:32:57.907
```
This fixes that for the two cases seen on a recent pipeline run.  Maybe we'll need to cherry-pick this into `release/16.0` and perhaps branches for older versions.
=> Assert dates in content editing integration tests to millisecond only

src/Umbraco.Web.UI.Client/src/packages/media/media/url/info-app/media-links-workspace-info-app.element.ts
Potential fix for [https://github.com/umbraco/Umbraco-CMS/security/code-scanning/1719](https://github.com/umbraco/Umbraco-CMS/security/code-scanning/1719)
To fix the issue, we need to sanitize or encode the `window.location.href` value before including it in the `html` string. The best approach is to use a library like `DOMPurify` to sanitize the value or encode it using a utility function to ensure it is safe for inclusion in HTML. This will prevent any malicious scripts from being executed.
Steps to fix:
1. Import a library like `DOMPurify` or use a built-in encoding function to sanitize or encode the `window.location.href` value.
2. Replace the direct usage of `window.location.href` in the `html` string with its sanitized or encoded version.
3. Ensure that the rest of the functionality …
=> Fix for code scanning alert no. 1719: Client-side cross-site scripting

src/Umbraco.PublishedCache.HybridCache/Serialization/JsonContentNestedDataSerializer.cs, src/Umbraco.PublishedCache.HybridCache/Serialization/JsonObjectConverter.cs
This PR fixes https://github.com/umbraco/Umbraco-CMS/issues/19544
If NuCacheSerializerType is set to JSON, values in PropertyData are not deserialized correctly when the underlying store contains JSON strings.
What I did
Updated the JsonConverter logic to ensure proper deserialization of string values.
How to test
Create a content item that uses a Block Grid property.
Inspect the strongly typed property value.
Without the fix, the property is null; with the fix, it is correctly deserialized.
✅ No breaking changes introduced.
=> fix: json serialization and deserialization for NuCacheSerializerType

src/Umbraco.Core/CompatibilitySuppressions.xml, src/Umbraco.Core/Configuration/Models/ContentSettings.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/ContentSettingsValidatorTests.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19567
The cause of this issue was another cases of issues involved in the fix https://github.com/umbraco/Umbraco-CMS/pull/19229, where `ISet` in configuration classes aren't bound.
Note that I've added a compatibility suppression for the breaking change, which I don't see how we can otherwise avoid.
Prepare a custom 404 page as per the [instructions in the documentation](https://docs.umbraco.com/umbraco-cms/tutorials/custom-error-page#create-a-404-page-in-the-backoffice) (though note that I found this didn't work when using the name "404" for the document type and template, and instead used "File Not Found").  With this PR in place, the custom 404 should be displayed as expected.
To check via debugging, put a breaking point at the …
=> Further fix to configuration classes using ISet, resolving regression with custom 404 pages

src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user.context.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19638
Just a small fix in the exposed client-side API type details.  This now aligned with what is defined in `UmbCurrentUserModel`:
```
export interface UmbCurrentUserModel {
...
permissions: Array<unknown>;
...
}
```
=> Aligned jsdoc and inferred function type on UmbCurrentUserContext

src/Umbraco.Core/Services/ICacheInstructionService.cs, src/Umbraco.Core/Services/ProcessInstructionsResult.cs, src/Umbraco.Infrastructure/BackgroundJobs/Jobs/CacheInstructionsPruningJob.cs, src/Umbraco.Infrastructure/Services/CacheInstructionService.cs, src/Umbraco.Infrastructure/Sync/BatchedDatabaseServerMessenger.cs, src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs, src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/CacheInstructionServiceTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/CacheInstructionsPruningJobTests.cs
Moves the cache instructions pruning from the `CacheInstructionService.ProcessInstructions()` method to a new `CacheInstructionsPruningJob` background job.
Make sure that the instructions are still pruned as expected, by checking the `umbracoCacheInstruction` database table.
To help with testing, adjust the following app settings to lower values:
```json
"Umbraco": {
"CMS": {
..
"Global": {
...
"DatabaseServerMessenger": {
"TimeBetweenPruneOperations": "0:00:30",
"TimeToRetainInstructions": "0:05:00"
}
},
}
}
```
This should make it so that the job will run every 30 seconds, and will delete all instructions older than 5 minutes (always leaving at least 1).
Be aware that there is a default delay of 3 minutes (default) from startup to when the background job actually starts running.
=> Move cache instructions pruning to background job

src/Umbraco.PublishedCache.NuCache/Property.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19609
I haven't been able to replicate the problem, which looks from the reported issue that it bubbles up from Commerce.  But it does look to be similar to the fix applied for https://github.com/umbraco/Umbraco-CMS/issues/16753 in https://github.com/umbraco/Umbraco-CMS/pull/17024, and this is a further case.
The problem is that the constructor of `CompositeStringStringKey` accepts null values but throws if they are passed.  So we ned to make sure we use `string.Empty` as we did in the other case.
Visual inspection will need to suffice here I believe.
=> Ensures that null values aren't used to create a CompositeStringStringKey

.github/workflows/azure-backoffice.yml, .github/workflows/azure-storybook.yml
This alleviates the problem that the deploymentToken for Azure only exists within the repository.
According to CoPilot, this is the correct way to check if you are on a fork or not: https://docs.github.com/?search-overlay-open=true&search-overlay-ask-ai=true&search-overlay-input=how%20can%20I%20determine%20through%20environment%20variables%20that%20a%20pull%20request%20runs%20in%20a%20fork%20of%20the%20repository%3F
=> GitHub: Only deploy to Azure on direct pull requests

src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/try-execute.controller.ts
This allows 400 errors to have a default notification unless silenced manually by `disableNotifications`. 
We must not forcefully silence them. The callers can do that little by little when they support UI to show the error.
=> V16.1: 400 errors are being wrongfully ignored

src/Umbraco.Cms.Api.Management/DependencyInjection/ApplicationBuilderExtensions.cs
If there's an existing issue for this PR then this fixes [19664](https://github.com/umbraco/Umbraco-CMS/issues/19664)
This fix adds a condition for the title.
I am not sure of the value of the title for non-debug mode. The value was copied from [here](https://github.com/umbraco/Umbraco-CMS/blob/9812630bb4664026150732d850d56672b178fa2e/src/Umbraco.Web.UI.Client/src/packages/core/resources/api-interceptor.controller.ts#L110)
How to test:
- Set in appsettings Umbraco:CMS:Hosting:Debug = false
- Add `throw new Exception("Example error message")` for any ManagementApiController
- Trigger this action from backoffice UI and look at the error notificaiton
For non-debug mode we must not see the exception details. But for debug mode we must see the exception details.
=> Title returns "Server Error" in non-debug mode

src/Umbraco.Web.UI.Login/src/auth.element.ts, src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
With the mindset of better anything than nothing: partial fix for https://github.com/umbraco/Umbraco-CMS/issues/16772
Seems to enable login screen for local (hash needed) and OpenId login (reason for encoding).
This does not fix the flow when `AutoRedirectLoginToExternalProvider` is enabled since I have no idea yet how I would get the anchor value serverside or work around that issue.
=> #16772 partial fix backoffice redirect after login

src/Umbraco.Core/Cache/DistributedCacheExtensions.cs, src/Umbraco.Core/Cache/Refreshers/Implement/MemberCacheRefresher.cs, src/Umbraco.Core/Constants-Entities.cs, src/Umbraco.Core/Handlers/PublicAccessHandler.cs, src/Umbraco.Core/Models/MemberGroup.cs, src/Umbraco.Core/Services/MemberService.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/DistributedCacheExtensionsTests.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19618
The linked issue discusses the problem where updating a user in the backoffice to change the user name still leaves the member cached and retrievable by the old user name.
This PR uses the `AdditionalData` collection available on entities to provide the previous user name to the cache refresher, so it can clear by the old user name as well as the new.
I've also added a constant for the `AdditionalData` key and used it for one other instance.
With code like the following, retrieve a member by the user name:
```
@inject IMemberService MemberService;
@{
var fred = MemberService.GetByUsername("fred@test.com");
@if (fred is null)
{
<div>Fred not found</div>
}
else
{
<div>Found Fred: @fred.Email</div>
}
}
```
Update the member's user …
=> Clear member cache by older user name when member user name is updated.

src/Umbraco.Core/Cache/PartialViewCacheInvalidators/NoopMemberPartialViewCacheInvalidator.cs, src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19661
As the linked issue discusses, when we don't have a call to `.AddWebsite()` in `Program.cs`, the `IMemberPartialViewCacheInvalidator` has no registered implementation, which causes an error when logging in.
This PR registers a no-op implementation of this interface that'll be overridden by the primary implementation if `.AddWebsite()` is used.
Setup `Program.cs` like the following, so there's no front-end website but you should be able log into the backoffice.
Verify that you can't before this PR is applied but you can after.
Revert to the standard setup for Umbraco with the front-end rendering, put a breaking point in `MemberPartialViewCacheInvalidator.ClearPartialViewCacheItems` and verify that the primary implementation is …
=> Register no-op implementation of IMemberPartialViewCacheInvalidator in headless setups

src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document-type/document-type.data.ts, src/Umbraco.Web.UI.Client/src/mocks/data/document-type/document-type.db.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
Fixes #19427.
Refactors the Block Catalogue Modal to make the filter/search work with a block-type's label, and element-type's name and description.
This refactor has removed the need to use the `<umb-block-type-card>` component, as all element-type metadata is batch requested upfront.
On a Block editor (Grid, List or RTE), when you have more than 8 block types, the search filter bar will appear. Try out the search filter with querying for a block-type's label, name and description.
=> Fixes Block Catalogue Modal Filter

src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs, src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19674
The linked issue highlights some discrepancies with how the link picker works in 16 compared to 13.  Although the title field is optional - i.e. whilst it's pre-populated on selecting content or media, you can remove it and leave it blank - with 16 the blank title comes through to the front-end when rendering.  In 13 it would be populated with the content or media name if it was empty.
Also in the backoffice, the name isn't displayed if the title is empty.  Again in 13, the name of the content or media name would be shown (aligning with what would render on the front-end.
This PR addresses both of those issues.
In testing I also noted and fixed the display of the manually entered URLs in the backoffice link listing.
- With a …
=> Populate name for content and media on URL picker if title is left empty

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepository.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaTypeRepository.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberTypeRepository.cs, tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaTypeRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MemberTypeRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceTests.cs
This is a forward merge of #19720 to V16.
As per @AndyButland's comment on the original PR, the use of `Lazy` has been removed.
> When applying for 16, check to see if the use of Lazy is needed (an initial look suggests it may not be).
=> Forward merge #19720 to V16

src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/19743
Add the includeTrashed as false, to exclude all trashed media on the search result for the media-picker.
As the issue description when using the browser UI trashed media is exclude but when you began to search everything is showed, witch doesn´t make any point, that you can search for trashed media and select it.
How to test.
* Add a document type and add a media picker property
* Add two medias. give the name as ex. "Lucas-portrait", "Lucas-wide"
* Trash one of the medias.
* Create a new node and in the media picker, in the browser see only media witch is not trashed.
* Then search ex. "Lucas" and see only the items witch is not trashed.
=> Add flag to exclude trashed media

src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/workspace/document-blueprint-workspace-editor.element.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
Fixes #19506
The style changes were based on `UmbDocumentWorkspaceContext._handleSave()`.
Since we only want to show warnings, and never errors, the `document-blueprint-workspace-editor` host element styles was adjusted instead.
In order to test, create a blueprint from a document type with a required field and attempt to save the blueprint without filling in that field.
=> Allow saving blueprints with validation errors

src/Umbraco.Cms.Api.Management/DependencyInjection/ManagementApiConfiguration.cs, src/Umbraco.Cms.Api.Management/OpenApi.json
If there's an existing issue for this PR then this fixes #19729
This PR changes the OpenAPI security scheme name for the Management API from `Backoffice User` to `Backoffice-User`.
See the linked issue for an excellent description of the reasoning behind 👍 
I have verified that the change does not affect any auto generated code for the backoffice client.
First and foremost, the backoffice should still work 😆 
Grab the OpenAPI json for the Management API from `/umbraco/swagger`, and use the [OpenAPI validator at swagger.io](https://validator.swagger.io/#/Validator/validateByContent) to validate it. You should see a fine little badge:
=> Make the OpenAPI security scheme name for the Management API valid

src/Umbraco.Cms.Api.Delivery/Handlers/InitializeMemberApplicationNotificationHandler.cs
https://github.com/umbraco/Umbraco-CMS/pull/19760 cherry-picked for 16 with conflicts resolved.
=> Add defensive coding to the member application initializer (16)

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
Resolves https://github.com/umbraco/Umbraco-CMS/issues/19742
The initial implementation of https://github.com/umbraco/Umbraco-CMS/pull/19273, added to ensure backoffice user sessions relating to removed login providers are invalidated, distinguished between users and members, such that only the former were invalidated.
It did so though by retrieving all logins, and filtering out those that were users based on the fact that the GUID could be recognised as one derived from an integer.
That causes the linked issue though if there are 2000+ members, as we aren't retrieving them in groups as we do usually when this situation could occur.
There's a better way though, in that we filter at the database to only retrieve the users in the first place - which we can do, as we know the prefix of the …
=> Retrieve only user external logins when invalidate following removal of backoffice external user login

src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-details.manager.ts
Fixes #19604.
In the Repository Details Manager ([`UmbRepositoryDetailsManager`](https://github.com/umbraco/Umbraco-CMS/blob/main/src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-details.manager.ts)), when the `uniques` are initialized with an empty array, the observer is triggered and a call to `#requestNewDetails()` is made, (but there are no uniques or details to request).
With issue #19604 for the Block Grid, a race condition occurs, that when the unique of an element-type is set with the Repository Details Manager, the `#init` Promise made by the initialized value (empty array) had not been resolved, so by the time it is resolved, the `#requestNewDetails()` method resumes with the uniques of the element-types (due to microtask scheduling between the Promise …
=> Repository Details Manager: Prevent making requests for empty arrays

src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/content-type-workspace-context-base.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19738
As noted on the linked issue, the content type workspace overrides the update method from the entity detail workspace base, but doesn't fire the updated event like the base method does.  This PR adds it.
To confirm the event fires I made a temporary local change to `UmbRepositoryDetailsManager` that already handles the event, adding `console.log(eventUnique + " updated.");` in `#onEntityUpdatedEvent`.
=> Fires the updated event when content types are updated

src/Umbraco.Web.UI.Client/src/packages/tags/components/tags-input/tags-input.element.ts
Fixes: #19693 
As per issue description, when the Tags property editor is used inside an `umb-property-dataset` element the culture provided to the property editor is null.
I found that culture is not required by the Tag's Repository, Data Source, or Management API.  So, the check for undefined value is not needed.  I've modified the code to replace undefined values with null which can be handled by the subsequent call chain.
I've tested this by modifying the `dashboard-with-property-dataset` example with the following additions (not committed)
Added additional property to data set.
```
data: UmbPropertyValueData[] = [
{
alias: 'textProperty',
value: 'Hello',
},
{
alias: 'tagsProperty',
value: [],
}];
```
Added the tags property editor to the dashboard with configuration
```
<umb-property …
```
=> Fix missing tag suggestions when no culture available.

src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/clear-formatting.tiptap-toolbar-api.ts
Fixes #19752.
Updated Tiptap RTE's **Clear Formatting** toolbar button feature to reset any nodes (e.g. headings) back to the default _paragraph_.
In a Tiptap RTE, (with Clear Formatting toolbar button added), enter a variety of rich-text, (e.g. headings, bold, italic, etc.); press the Clear Formatting button, the formatting of the text should be removed, leaved plain-text paragraphs.
=> Tiptap RTE: Clear Formatting, resets nodes to "paragraph"

src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts, src/Umbraco.Web.UI.Client/src/packages/ufm/components/ufm-render/ufm-render.element.ts, tests/Umbraco.Tests.AcceptanceTest/package-lock.json, tests/Umbraco.Tests.AcceptanceTest/package.json, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockGrid/ComplexBlockGridTest.spec.ts, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/RichTextEditor/VariantTipTapBlocks.spec.ts
Fixes #19790.
Adds support to make RTE block appear selected when surrounding text is highlighted.
This is a slight CSS hack, as it adds an element with a single full-width space (`&emsp;`) to the `<umb-ref-rte-block>` component, so when the block is selected, it will appear highlighted.
Go to an RTE that has Block elements, make a text selection (by click+drag, or a select all <kbd>CTRL + A</kbd>) and notice that the blocks appear selected.
To note, if the text selection is copied, the text-content of the block is not copied, but the markup is, e.g. it can be pasted within Tiptap RTE, but not a text-editor/notepad.
=> Tiptap RTE: Block selection

src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
Fixes #19835.
The `labelTemplate` property was not wired up in the Media Table Collection View component, meaning that dynamic labels and UFM syntax did not work.
In the built-in data-type "List View - Media", use UFM syntax inside any of the column's label template field.
As an example, you could add a new column, using the `umbracoBytes` property-alias and use the label template `{=value | bytes}`.
On the Media section dashboard, view the Table (List) layout of the root collection, the value should be rendered using UFM. For the above example, any value in bytes should be rendered in kilobytes/megabytes.
=> Media Table Collection View: Adds support for Label Templates

src/Umbraco.Web.UI.Client/src/assets/lang/da.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts, src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Resolves #19588.
Whilst reviewing PR #19739 (that offered a fix for #19588), it added a new option to the Tiptap RTE data-type configuration for **Minimum dimensions**. This offered a way for an implementor to configure the RTE with both a minimum and maximum height.
The introduction of a new input field to the Tiptap RTE would add to an already complex set of configuration options.
After exploring alternative options, I decided to follow an approach that we've offered with styling other property-editors, by using CSS Variables.
This PR adds the following CSS Variables to the Tiptap RTE, (note that they are prefixed with a generic `rte` not `tiptap`):
- `--umb-rte-width`
- `--umb-rte-min-width`
- `--umb-rte-max-width`
- `--umb-rte-height`
- `--umb-rte-min-height`
- `--umb-rte-max-height` …
=> Tiptap RTE: Custom CSS Variables for min/max height/width

src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs, src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs, src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs, src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs, tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
Fixes #19432
When using a Content Picker, selecting a start node and leaving "Ignore User Start Nodes" unselected, a user with no permissions to see that node or its children, would still be able to see them if using the search box.
This PR re-arranges the logic to handle this scenario.
V16 also has the same issue, independently of whether list view is enabled or not. It does seem that more changes might be required to handle "Ignore User Start Nodes" appropriately. Once this is PR is approved, I will try to cherry pick and see what additional changes are required.
**Testing**
Follow the instructions in the reported issue and create different accounts with different permission configurations to ensure that the search returns the expected results when:
- User has no start node restriction …
=> Content picker search with start node configured not taking user start nodes into account

src/Umbraco.Web.UI.Client/src/packages/media/media/audit-log/info-app/media-history-workspace-info-app.element.ts
This PR fixes the issue https://github.com/umbraco/Umbraco-CMS/issues/19649.
`requestAuditLogs()` is used to get data for this history in media detail, but after clicking save, the close modal action is immediately called, so it will destroy the `workspaceContext `=>` #requestAuditLogs()` will throw an Error.
I will add to check the existence of `#workspaceContext` in `requestAuditLogs()` before doing other things.|
And because requestAuditLogs() is already called when opening the media detail, so the log is always getting updated when opening it.
=> Fix issue create media folder throw error

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs, src/Umbraco.Infrastructure/Persistence/DefaultDatabaseAvailabilityCheck.cs, src/Umbraco.Infrastructure/Persistence/IDatabaseAvailabilityCheck.cs, src/Umbraco.Infrastructure/Runtime/RuntimeState.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/DefaultDatabaseAvailabilityCheckTests.cs
Addresses https://github.com/umbraco/Umbraco-CMS/issues/17363
The linked issue notes some problems that can occur at boot time when the database isn't yet available.  We currently have a hard-coded behaviour to try 5 times with a 1 second delay in between, and if following that we can't connect to the database, we throw an exception and stop.
It seemed it might be better if we gave developers more control here, so this update doesn't change behaviour, but abstracts what we have behind an interface so it could be swapped for something more appropriate for the hosting environment.  Maybe waiting for some other result, or using a different strategy like exponential back-off or just increased delay, to give more time for the database to come online.
Verify Umbraco continues to behave as …
=> Adds abstraction around boot time checks for database availability

src/Umbraco.Web.UI.Client/src/packages/content/content/global-components/content-workspace-property.element.ts
This PR fixes the issue https://github.com/umbraco/Umbraco-CMS/issues/19627.
I hid properties that have isSensitive = true and the current does not have access to sensitive data
=> Hide property has sensitive data with normal user

src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/PreviewControllerTests.cs
Addresses: https://github.com/umbraco/Umbraco-CMS/issues/19817
The linked issue flags a security hardening introduced to ensure that the culture code provided in the preview URL is valid.  We did this by verifying that the culture code provided one can be used to construct a `CultureInfo`.  However this failed unnecessarily for culture codes that were valid syntactically but not installed on the operation system and exposed by .NET.
Given we have this to prevent XSS vulnerabilities, it would seem enough to verify the culture code contains only valid characters.  So that's what this PR does.
Preview a page in Umbraco and verify that the provided culture code is accepted and the preview shown.
Manipulate the culture code provided in the querystring to create an invalid one and verify that …
=> Use a regex to filter our invalid culture codes rather than relying on the culture being installed on the operating system

src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-search-input.element.ts
Previously this displayed as:
> Are you sure you want to delete? {saved search name}?
Now it's:
> Are you sure you want to delete {saved search name}?
Create a saved search via the log viewer and try to delete it.
=> Fixed layout and formatting of saved search delete dialog on the log viewer

src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-span.extension.ts, src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-embedded-media.extension.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/embedded-media.tiptap-api.ts
Fixes #19521.
This patch alters how Tiptap RTE renders embedded media items. Previous they were rendered using a `<div>`, but this caused issues ([as explained in my comment on the original issue](http://github.com/umbraco/Umbraco-CMS/issues/19521#issuecomment-2961848399)), this has been altered to use a `<span>` to make the embedded media item act as a native inline block.
Also, I've taken this opportunity to align the styling of the selection of embedded media items with other rich-media selections within the RTE, e.g. blue border outline.
See #19521 for reproduction steps.
Prior to this fix, view a Tiptap RTE with an existing embedded media item, notice that each save of the document will add extra paragraphs before & after the embedded media item.
With this fix, notice that the each …
=> Tiptap RTE: Fixes embedded media spacing

src/Umbraco.Web.UI.Client/src/assets/lang/da.ts, src/Umbraco.Web.UI.Client/src/assets/lang/de.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts, src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/imaging/imaging.repository.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts, src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
This PR cleans up the `<umb-input-rich-media />` component, resolving the TODOs and other comments. The inner dropzone was listening on the "complete" event, which is deprecated, so we changed to the `change` event, which is what fixes #19401 as well.
* Refactored the `UmbInputRichMediaElement` to use a dedicated `UmbMediaPickerInputContext` for managing selection and removal of media items, simplifying the picker logic and improving maintainability. (This is exactly what the UmbInputMedia element does as well to ensure that already selected images are pre-selected when opening the media picker modal.)
* Added loading state indicators to media cards and ensured picker context selection updates the displayed items. (Thereby fixing a TODO left in the element)
* Updated localization strings …
=> V16: Media Picker property editor does not handle dropped files appropriately

tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/SimilarNodeNameTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/RuntimeAppCacheTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/SliderPropertyValueEditorTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/Repositories/SimilarNodeNameTests.cs
This PR fixes: #19909 
Run test. Result should be:
=> Fix and enable some unit tests which are not running locally or on pipeline builds

src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs, src/Umbraco.PublishedCache.HybridCache/Persistence/IDatabaseCacheRepository.cs
In attempts to investigate and improve performance I did some clean-up of this class - de-duplicating code and resolving warnings.
There's nothing concrete in here performance-wise but seems like it'll be useful to have the refactoring in anyway.  In particular it cleans up three database queries that were duplicated three times.
Visual inspection, pipeline will verify that existing tests pass.
For manual testing put a break point in `DatabaseCacheRepository.Rebuild` and save content types to check flow of data being removed and added.
=> Refactoring DatabaseCacheRepository to de-duplicate code and remove warnings

src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Webhook/Item/WebhookItemResponseModel.cs
Adds the `Id` property to the webhook item response model that was found to be missing.
Manual testing can be done on the endpoint:
```
/umbraco/management/api/v1/item/webhook?id={id}
```
Which should give a response like:
``
[
{
"enabled": true,
"name": "Test",
"events": "Umbraco.ContentMoved,Umbraco.ContentPublish",
"url": "https://webhook.site/33d2002e-cca7-479d-aee1-575d659a4820",
"types": "",
"id": "9249cbb3-9d0c-4d1c-8520-fab30ed565da",
"signs": []
}
]
```
=> Adds id to the webhook item response model

src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs, src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs, src/Umbraco.Cms.Api.Management/OpenApi.json, src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentResponseModelBase.cs, src/Umbraco.Cms.Api.Management/ViewModels/Item/ItemResponseModelBase.cs, src/Umbraco.Cms.Api.Management/ViewModels/Tree/EntityTreeItemResponseModel.cs, src/Umbraco.Web.UI.Client/src/packages/core/backend-api/types.gen.ts
This removes a read-only property that was added to the base item, collection and tree models that leads to breaking changes to the client-side generated types.
=> Fix to management API models reverting addition of read-only property

src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
error 40 have been made on this check. It is suppose to check if the Validation Context is already present, if so then not create a new one. It turned out in other works that this was not working, cause `filter` always returns an array that was truthy.
=> fix validation context initialization

src/Umbraco.Web.UI.Client/src/packages/data-type/repository/detail/server-data-source/data-type-detail.server.request-manager.ts, src/Umbraco.Web.UI.Client/src/packages/documents/document-types/repository/detail/server-data-source/document-type-detail.server.request-manager.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/detail/cache.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/detail/detail-data.request-manager.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/inflight-request/cache.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/item/cache.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/server-event/global-context/server-event.context.ts, src/Umbraco.Web.UI.Client/src/packages/management-api/server-event/global-context/types.ts
Add a timestamp to server events and client cache entries
=> Add timestamps to cache entries and server events

src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/tiptap-toolbar-group-configuration.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/tiptap-toolbar-group/tiptap-toolbar-group.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
This PR fixes the issue https://github.com/umbraco/Umbraco-CMS/issues/19571
https://github.com/user-attachments/assets/07710f06-982a-4c10-ae36-a488f99d8409
I used the Umbraco Sorter controller for drag and drop Tiptap toolbar buttons.
=> Tiptap RTE: Toolbar configuration sorter

src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDatabaseCreator.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19948
This linked issue indicates a problem when using unattended installs with a SQLite database for a newly cloned repository.  The `/umbraco/Data` directory doesn't exist which leads to an exception being thrown.
I couldn't actually replicate this.  In my tests I would always find a `MainDom_*.lock` file written into `/umbraco/Data/Temp`, so by the time the SQLite database was being created in the unattended install, the directory was already there.
Nonetheless it's fairly easy to see what the fix would be if it wasn't - and if using storage in another location ensuring the directory exists would still be useful.  So I've applied it here - a check to see if the directory where the SQLite database is going to be copied to exists, …
=> Ensure the directory exists before creating the SQLite database

src/Umbraco.PublishedCache.HybridCache/Factories/IPublishedContentFactory.cs, src/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactory.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactoryTests.cs
Relates to https://github.com/umbraco/Umbraco-CMS/issues/18892
We've had some discussion on the linked issue and internally about the potential performance concern of having to translate from the object stored into the hybrid cache and the `IPublishedContent` instance.  It can be argued if this is likely to be a concern in typical page generation, but, as noted, it seems straightforward to at least request cache this.
As such I've applied that in this PR.
Given it's only cached for the request, we don't have to be concerned about cache invalidation.
Looking at a small site - the Umbraco starter kit - it does seem we can instantiate the same `IPublishedContent` multiple times in a single page request.
When this update is applied, loading a product page, which has the navigation bar, from …
=> Add request caching around published content factory

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Fixed a problem that was never released
=> Fix: Workspace Editor slotted fallback content should be displayed when no routes

templates/UmbracoExtension/Client/package.json
This is a quick fix to handle the NPM error that is currently there because the Backoffice NPM client has moved on to another version. There will be a more comprehensive fix for 16.3, however this PR aims to make the 16.2 UmbracoExtension usable without running custom commands.
1. Install the 16.2.0-rc template
2. Run the `dotnet new umbraco-extension --version 16.2.0-rc -ex`
3. Verify that `npm install` initially fails
4. Now change the versions in package.json to the proposed changes here in this PR
5. Run `npm install` again and verify it now works
=> fix: pins the UmbracoExtension `@hey-api/*` versions to that of the Backoffice client

src/Umbraco.PublishedCache.HybridCache/PublishedProperty.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/PropertyValueLevelDetectionTests.cs
If there's an existing issue for this PR then this fixes #20051
See #20051 for a description.
As the linked issue describes, this is "only" a problem for document, media and member properties - not element properties. I have added tests that prove it works for elements as-is.
See the steps to reproduce in the linked issue. You can re-apply the property value converter from the tests, if that's easier:
```csharp
public class PropertyValueLevelDetectionTestsConverter : PropertyValueConverterBase
{
public override bool IsConverter(IPublishedPropertyType propertyType)
=> propertyType.EditorAlias == Constants.PropertyEditors.Aliases.TextBox;
public override Type GetPropertyValueType(IPublishedPropertyType propertyType)
=> typeof(string);
public override PropertyCacheLevel …
```
=> Perform value detection at all property value levels

src/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactory.cs, tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactoryTests.cs
Rectifies an omission in https://github.com/umbraco/Umbraco-CMS/pull/19990
In https://github.com/umbraco/Umbraco-CMS/pull/19990 a request cache was added around the construction of `IPublishedContent` instances.  It didn't have a check that the request cache was available.  As far as I can see this doesn't cause any issues at runtime as the calls to the cache gracefully handle if it can't be supported, but I figured it was better to be explicit and make this check.
Verify existing integration tests pass, and consider adding breaking points or debug logging configuration to verify the cache is used when the item has already been retrieved in the current request.
=> Verify that the request cache is available before using it in PublishedContentFactory

src/Umbraco.Web.UI.Client/src/packages/content/content/collection/content-collection-workspace.context-token.ts
Fixing a minor mistake, to avoid js errors in console.
=> JS-fix: test the existence of collection as well

src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Fixes #20029.
If a dropdown property-editor is not marked as mandatory and is in single-mode, then an empty option is added to the top of the dropdown, so that the value can be unset.
This doesn't apply to multiple-mode, as values can already be deselected.
=> Dropdown: Allow empty option

src/Umbraco.Cms.Api.Management/Controllers/Content/ContentCollectionControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Document/Collection/ByKeyDocumentCollectionController.cs, src/Umbraco.Cms.Api.Management/Controllers/Document/Item/ItemDocumentItemController.cs, src/Umbraco.Cms.Api.Management/Controllers/Media/Collection/ByKeyMediaCollectionController.cs, src/Umbraco.Cms.Api.Management/Factories/ContentCollectionPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs, src/Umbraco.Cms.Api.Management/Services/Signs/HasPendingChangesSignProvider.cs, src/Umbraco.Cms.Api.Management/Services/Signs/HasScheduleSignProvider.cs, src/Umbraco.Cms.Api.Management/Services/Signs/ISignProvider.cs, src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantItemResponseModel.cs, src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantResponseModel.cs, src/Umbraco.Core/Persistence/Repositories/IDocumentRepository.cs, src/Umbraco.Core/Services/ContentService.cs, src/Umbraco.Core/Services/IContentService.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Services/Signs/HasPendingChangesSignProviderTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Services/Signs/HasScheduleSignProviderTests.cs
This PR Makes it so the SignProviders `HasPendingChangesSignProvider` & `HasScheduleSignProvider` applies its signs to the given variants of the the document. The purpose of this, is to make it easier to tell which variant of the document has theese specifications.
A part of this PR is also moving some of the code, to the respective factories, due to it being more logical to handle these variant changes within the factories where the variants are being created. For future reference, a restructuring of the other sign providers, to also make use of factories could be a good change, since some of them still has their uses applied in controllers.¨
To accompany this, i have also reinstated some constructors that has been marked as obsolete - As far as i could tell, these have not been included …
=> V16 - Introducing signs to variants

src/Umbraco.Core/Services/EntityService.cs
Fixes an issue found in internal testing where a request for `take` of `0` would trigger an error when the skip/take options were converted to paging parameters.  The fix aligns with the same done for retrieving document root and other collections where skip/take options are available.
Request the following management API endpoint:
```
/umbraco/management/api/v1/recycle-bin/document/root?skip=0&take=0
```
Previously this would fail with a 500 error.  Now you should get back a response like:
```
{
"total": 1,
"items": []
}
```
=> Fixes divide by zero error on retrieving take 0 from the recycle bin root API endpoint

src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs, src/Umbraco.Infrastructure/Persistence/Relations/ContentRelationsUpdate.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs, src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/RelationServiceTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TrackRelationsTests.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TrackedReferencesServiceTests.cs
See https://github.com/umbraco/Umbraco-CMS/pull/20079#pullrequestreview-3189173692 for the background to raising this PR, which relate to optimising and making more reliable save operations to support Deploy operations.
Also https://github.com/umbraco/Umbraco-CMS/discussions/20094.
I've moved the persistence of relations from the repositories into a notification handler.
In testing I can see it working as it did before.
Referencing some discussion from when this was first implemented around whether this should be carried out in an event (at the time, as it was Umbraco 8), or in the repository itself:
https://github.com/umbraco/Umbraco-CMS/pull/6843/files#r338926734
Via a database query, find the references for a given parent item - e.g. a document, that has pickers for documents, media or …
=> Move persistence of relations from repository into notification handlers

src/Umbraco.Cms.Api.Management/Controllers/Tree/EntityTreeControllerBase.cs, src/Umbraco.Cms.Api.Management/Controllers/Tree/FolderTreeControllerBase.cs
This PR resolves the following issue found in testing:
> I am running into an issue with the siblings endpoints where the parentId of items in a folder is "00000000-0000-0000-0000-000000000000". The screenshot is specifically for the Document Type Tree, but I looks like a problem for all Trees with folders.
To resolve I've introduced and overridden a method for retrieving the parent key for an entity, such that for entities that have folder support, the folder object type is checked in addition to the item object type when retrieving the key.
=> Correct the population of the parent for sibling items when retrieved under a folder

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.context.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts, src/Umbraco.Web.UI.Client/src/packages/clipboard/clipboard-entry/picker/clipboard-entry-picker.element.ts, src/Umbraco.Web.UI.Client/src/packages/ufm/controllers/ufm-virtual-render.controller.ts
Fixes #19548.
When a block item is copied to the clipboard, if the label is using UFM syntax, it will be resolved (at the point of copying).
Whilst looking at the initial bug, I noticed a couple of issues with the Clipboard entry rendering, and UFM Virtual Renderer, which I've also fixed in this PR.
=> Block editors: resolves clipboard UFM label

src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-sections.element.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/17076
This PR introduces a feature to store the last visited item/path for a section, so that when navigating back to the same section, the user will be redirected to that path.
What to test:
- Ensure that when navigating between sections, the last visited path is retained.
- Ensure that when using Ctrl + click, the regular section path opens in a new tab.
=> Feature: Redirect to the last visited path when navigating between sections

src/Umbraco.Infrastructure/Services/MemberEditingService.cs, src/Umbraco.Web.UI.Client/src/packages/members/member/repository/validation/member-validation.server.data-source.ts
- The validation endpoint for members would only validate the properties given by the MemberType, and not all the default one for members, such as name, email etc.
- This PR remedies that, by refactoring the validation methods to also call the `ValidateMemberData` method, which was already used to validate these properties, when saving or creating.
- This will only return 1 problem at a time for now, might need to refactor the `ValidateMemberData` function to return a list of errors, instead of just 1.
- You can test the member create validation endpoitn, by calling xx and using this json, this should an error, you can tweak this values to be correct, to get different errors/ no errors if everything is passed correctly 😁 
```
{
"values": [
],
"variants": [
{
"name": "TestName"
}
], …
```
=> V16: Fix member validation endpoints

src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/heading/heading.tiptap-api.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap-rte/property-editor-ui-tiptap.element.ts
Fixes #20076.
When the Tiptap RTE is empty, the internal value is set to `undefined`, however in a scenario when the RTE has content and then all content is removed (think <kbd>CTRL + A</kbd>, <kbd>DEL</kbd>), it is not possible to restore any Block data, (since the underlying value was `undefined`).
The fix here is to not intentionally set the underlying value as `undefined`.
This PR contains a couple of other cosmetic fixes related to RTE selection and heading styles.
With a Tiptap RTE that has some rich-text and Block data; select and delete all contents, try to undo, notice that the Block data can now be restored.
=> Tiptap RTE: Fixes undo when RTE is emptied

src/Umbraco.Web.UI/appsettings.Development.template.json, src/Umbraco.Web.UI/appsettings.template.json
This pull request updates the configuration templates in `appsettings.template.json` and `appsettings.Development.template.json` for the Umbraco Web UI. The changes mainly focus on cleaning up unused or outdated settings, updating timeout configuration, and fixing a property name for consistency.
Configuration cleanup and updates:
* Removed the entire `RuntimeMinification` section from both `appsettings.template.json` and `appsettings.Development.template.json` to eliminate unused or deprecated configuration options. [[1]](diffhunk://#diff-83ccafe367c91b7e9d98144af4cd5b19f25f5aa498b2bd770697988bd4c06877L36-R38) [[2]](diffhunk://#diff-ecfc096d00bc4074cac9eb390fe6a6aa1c1f8143800db7abbfca1b4baaf23fa6L40-L43)
* Removed the `Tours` section from `appsettings.template.json`, disabling …
=> AppSettings: Improves the templates so they reflect the latest recommended settings

src/Umbraco.Core/Models/DeliveryApi/ApiContentRoute.cs, src/Umbraco.Core/Models/DeliveryApi/IApiContentRoute.cs, src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParser.cs, src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextParserBase.cs, tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs, tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParserTests.cs
This is a cherry-pick of #20142 for V16.
Due to changes in V14, we now treat UDI based local links as "legacy", and GUID based local links as "present". This caused some merge conflicts. It also required a few extra unit tests to prove that the fix for the original issue works for both types of local links. Hence this cherry-pick being a PR 😄 
See #20142
=> Cherry-pick #20142 for V16

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs
Resolves: https://github.com/umbraco/Umbraco-CMS/issues/19784
This PR adds an option to log rather than throw when encountering an exception deserializating block values, that can be used to avoid an exception when retrieving references.
We have had cases where content is being migrated to a new data type via uSync or Deploy, where the parsed content is in a format for nested content rather than block list, and this then blows up, preventing the migration.  It happens when retrieving references, which isn't essential to the operation, so it's reasonable to to just skip values that can't be parsed into an excepted format, and from where references can be obtained.
Testing is tricky, so it maybe that visual inspection is enough here.  But I've been able to trigger the problem from a clean …
=> Avoid throwing an exception on getting references when migrating content with changed data types

src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs, src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
Forward port of https://github.com/umbraco/Umbraco-CMS/pull/20079 for Umbraco 16.
See linked PR for details.
=> Avoid throwing an exception on getting references when migrating content with changed data types (16)

src/Umbraco.Core/EmbeddedResources/BlockGrid/default.cshtml, src/Umbraco.Web.UI/Views/Partials/blockgrid/default.cshtml, src/Umbraco.Web.UI/Views/Partials/blocklist/default.cshtml
**Note:** I think that the EmbeddedResources files could be removed altogether, as they do not seem to be used. What do you think?
This pull request refactors how grid column values are handled in block grid view templates and updates a property check in the block list template. The main focus is on improving code readability and consistency by assigning the grid columns value to a variable and updating a property reference for block identification.
**Block Grid Templates:**
* Assigned the grid columns value to a `gridColumns` variable for reuse, improving readability in both `default.cshtml` templates (`src/Umbraco.Core/EmbeddedResources/BlockGrid/default.cshtml` and `src/Umbraco.Web.UI/Views/Partials/blockgrid/default.cshtml`). …
=> Generated Partial Views: Improves the generated code slightly for a better developer experience

src/Umbraco.Core/Services/NotificationService.cs
If there's an existing issue for this PR then this fixes #20045
See the linked issue for a description.
You'll need to be able to receive notification emails from Umbraco. An easy way to do that is to configure the SMTP options to use the `SpecifiedPickupDirectory` in `appsettings.json`:
```json
{
"Umbraco": {
"CMS": {
"Global": {
"Smtp": {
"From": "your@email.here",
"DeliveryMethod": "SpecifiedPickupDirectory",
"PickupDirectoryLocation": "C:\\Temp\\MailDrop"
}
},
....
```
You'll also need to enable segments for document types. This code snippet should do the trick in V13:
```cs
public class ServerVariablesParsingNotificationHandler : …
```
=> Make notification service able to handle segmented content

src/Umbraco.Web.UI.Client/src/packages/core/entity-item/entity-item-ref/entity-item-ref.element.ts, src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts, src/Umbraco.Web.UI.Client/src/packages/core/repository/types.ts, src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19018
Fixes https://github.com/umbraco/Umbraco-CMS/issues/20087
By displaying not existing items in this way:
=> Content/Document Picker: make not existing items appear

src/Umbraco.Core/Extensions/PublishedContentExtensions.cs, src/Umbraco.Infrastructure/IPublishedContentQuery.cs, src/Umbraco.Infrastructure/PublishedContentQuery.cs, src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs, src/Umbraco.Web.Common/UmbracoHelper.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/20117
This PR allow `ContentAtRoot()` to query specific culture just like `GetAtRoot()` in published content query.
=> Querying extensions: Allow `ContentAtRoot()` to accept culture

src/Umbraco.Web.UI.Client/src/assets/lang/cy.ts, src/Umbraco.Web.UI.Client/src/assets/lang/da.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/fr.ts, src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts, src/Umbraco.Web.UI.Client/src/assets/lang/sv.ts, src/Umbraco.Web.UI.Client/src/assets/lang/vi.ts, src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts, src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Added localized term on label for tree item caret button, to say expand or collapse, depending on the state.
I am currently unsure if this should be implemented in [\menu-item-layout\menu-item-layout.element.ts](https://github.com/umbraco/Umbraco-CMS/blob/main/src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu-item-layout/menu-item-layout.element.ts) as well.
=> Update label for tree item caret to identify if open or closed 

src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Added a border on TipTap RTE editor input field when hovering and in focus mode to provide a visible indication when they have the input in focus.
=> Tiptap RTE: Adds hover and focus border input states

src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18892
- Thanks to some investigate work from @enkelmedia, fetching deleted nodes from for example a MultiNodeTree picker, will try to fetch the deleted content, resulting in a Database hit.
- This PR remedies that, by also caching null values.
- A little background on the decision not to cache null values, was that we had no way of deleting nodes with keys that we did not know. Now we can delete all content by tags, so we have a way of removing them again 😁 
- Make content picker datatype which can choose multiple content
- Make a content type using that datatype
- Create 2 different documents, 1 referencing the other, save and publish, then delete the referenced content.
- In your template for the existing content, try getting the value …
=> Caching: Don't remove null values from hybrid cache to avoid broken content references repeatedly requiring a database hit (closes #18892)

src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/20166
Adjusted height of input append in image crop.
=> Adjust height of image crop input append

src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
If there's an existing issue for this PR then this fixes #19988
When a document has collection view configured and its children vary by culture, the `Last edited` / `updateDate` displayed per document was the `updateDate` of the first variant returned by the API, and not the actual last update date (independently of the variant), which is what the server uses to sort on.
This has now been adjusted to always display the last update date.
1. Add a new language to the backoffice, example: `German (Switzerland)`.
2. Create a document type, with name "News", allowed at root, with a collection view configured (it can be the default `List View - Content`).
3. Create another document type, "News Item", which varies by culture.
4. Allow the "News Item" as a child of the "News" document type.
5. …
=> Collection view: Wrong `Last edited` date displayed in document collection view (closes #19988)

src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Lit started compalining about missing getter methods, therefor this fix.
=> Workspace Base: make nonesense getter method to make Lit happy

src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/20167
Make remove button in configuration of (approved) color picker consistent with other datatype configuration.
=> Make remove button consistent with other multi value item remove button

src/Umbraco.Web.UI.Client/src/assets/lang/da.ts, src/Umbraco.Web.UI.Client/src/assets/lang/en.ts, src/Umbraco.Web.UI.Client/src/assets/lang/nb.ts, src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts, src/Umbraco.Web.UI.Client/src/assets/lang/vi.ts, src/Umbraco.Web.UI.Client/src/packages/search/examine-management-dashboard/modal/fields-settings/examine-fields-settings-modal.element.ts, src/Umbraco.Web.UI.Client/src/packages/search/examine-management-dashboard/views/section-view-examine-searchers.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/20234
As the title says - added a new translation key for "Fields", while preserving the original one `examineManagement_fields` in lowercase.
This new translation key can be used in other parts of backoffice along with the existing `general_field` translation.
I also made the `uui-scroll-container` 100% height.
I think we can just use `overflow-y: auto` instead of `overflow-y: scroll;`?
So it looks like this:
but ideally remove padding in modal `#main` and add to scroll container instead?
=> Localization/UX: Add a new general translation for "Fields"

src/Umbraco.Web.UI.Client/src/packages/content/content/global-components/content-workspace-property.element.ts
=> AllowEditInvariantFromNonDefault : Fix property write guard to use correct variant ID (closes #20250)

Directory.Packages.props, src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
Updates Umbraco 13's dependencies on ImageSharp to the latest patch releases for ImageSharp 2 and 3.
=> Dependencies: Update ImageSharp to latest patch releases (13)

src/Umbraco.Cms.Api.Management/DependencyInjection/InstallerBuilderExtensions.cs, src/Umbraco.Cms.Api.Management/Install/PostUnattendedInstallNotificationHandler.cs, src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs, templates/UmbracoProject/.template.config/dotnetcli.host.json, templates/UmbracoProject/.template.config/ide.host.json, templates/UmbracoProject/.template.config/template.json, templates/UmbracoProject/appsettings.Development.json
I added 'UnattendedTelemetryLevel' to the unattended installer configuration, I used the already existing unattended installer notification handler and renamed it to a better suiting more generic name so I could include the setting of telemetry level.
Also fixed some formatting and comments in the files I edited.
I noticed I could set the telemetry level from the regular installer but not from an unattended installation. 
I already applied a patch akin to this one in my own Umbraco project but I thought other people might also want the functionality to set the telemetry level from an unattended install hence this pull request.
Add the already present [unattended installation settings](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/unattended-install#enable-the-unattended-i …
=> Unattended install: Added the ability to set the telemetry level

src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/logviewer-workspace.context.ts
Fixes #20274.
Stops the log viewer from polling the server when the user has navigated away from the log viewer workspace.
Go to the Log Viewer workspace (Search view), start the polling. Notice in the browser dev-tools (Network tab) that the requests are being made at the set interval. Navigate away from the Log Viewer workspace. Notice that the server requests have now stopped.
=> Log Viewer: Fixes continuous polling (closes #20274)

src/Umbraco.Infrastructure/BackgroundJobs/RecurringBackgroundJobHostedServiceRunner.cs
A very small PR to extend the `RecurringBackgroundJobHostedServiceRunner`. At the moment we make extensive use of RecurringBackgroundJobs, and it’s quite useful to have a bit more information in the logging about the configured delay and how often the job runs.
=> Extend logging (add delay and period)

src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/upload-field/Umbraco.UploadField.ts
Addresses https://github.com/umbraco/Umbraco-CMS/issues/20331
Removed the dot "." in the file extension example, otherwise the validation will fail and you will not be able to upload the jpg image.
=> Removed the dot "." in front of the jpg file extension example.

src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-svg.element.ts
This PR fixes issue 19832 (https://github.com/umbraco/Umbraco-CMS/issues/19832)
When resizing the window to a smaller width value the svg image is extending outside the bounds of its parent
In order to test the change go to Backoffice and click on `Media` tab, then create a new SVG media with the following image:
Resize the window horizontally so the width value changes. Now the svg image should not exceed its parent.
Before:
After (setting `max-width: 100%`):
=> Media: Prevent svg image to extend outside the editor bounds

src/Umbraco.Core/Cache/AppCacheExtensions.cs, tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DictionaryRepositoryTest.cs
Addresses https://github.com/umbraco/Umbraco-CMS/issues/20336
In an earlier PR, we added an update to the dictionary repository such that it cached null values, and prevented multiple database hits for dictionary keys that did not exist: https://github.com/umbraco/Umbraco-CMS/pull/15576
We then resolved this issue raised that identified some issues resulting when using localised text in the backoffice (supported in Umbraco 13): https://github.com/umbraco/Umbraco-CMS/pull/19350
Unfortunately it seems this caused a regression on the original feature.
In this PR I've resolved the regression and tested that the backoffice translations work as expected.
I've also added integration tests to verify the cache behaviour.
See replication steps described in …
=> Caching: Fixes regression of the caching of null representations for missing dictionary items

src/Umbraco.Web.Common/Security/ConfigureFormOptions.cs, src/Umbraco.Web.Common/Security/ConfigureKestrelServerOptions.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/20343
We have an integer overflow exception when we attempt to convert a configured KB value into bytes.  It's caused by multiplying two ints together to make a long - if the two ints go over int.MaxValue the result is zero.
I've fixed this by casting one of the ints to a long before doing the calculation.
You can test this via breakpoints at the places of the changed code on start up, veryfiny that the value is set to a non-zero value when configured in `Umbraco:Cms` to be, e.g. as follows:
```
"Runtime": {
"MaxRequestLength": 4194304
},
```
And verify that you can save and publish nodes (previously having this value coerced to zero would cause an exception to be thrown).
Once verified and merged for 13, needs to be cherry-picked up to …
=> Configuration: Fixed integer overflow in setting MaxRequestBodySize and MultipartBodyLengthLimit

build/nightly-E2E-run-tests-template.yml, tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockGrid/BlockGridArea.spec.ts
This PR removes the continueOnError as it resulted in smokeTests not being caught on github
=> E2E Pipeline: QA Remove continue on error condition

src/Umbraco.Web.UI.Client/src/packages/core/property/components/property/property.context.ts
Still does not fix the problem of viewing segmented statuses on the default variant. but it fixes the other cases.
Like this:
=> Shared status: improve for segmented scenario

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts
Follow-up on https://github.com/umbraco/Umbraco-CMS/pull/20364 adding a bit more spacing in combobox group header.
**Before**
**After**
=> Block Grid: Add more spacing in combobox group header

src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-area-config-entry/block-grid-area-config-entry.element.ts, src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
A bit more spacing and alignment in block grid areas config.
**Before**
**After**
=> Block Grid: Add a bit more spacing and align button in block grid areas config

build/nightly-E2E-test-pipelines.yml
This PR updates the YAML configuration to run E2E tests against the v17/dev branch and include acceptance tests for different setting apps by default, since they are stable and quick to run.
=> Nightly E2E test pipeline: QA Run E2E tests on v17/dev and enable the different setting app tests by default

src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs, src/Umbraco.Infrastructure/ModelsBuilder/Building/ModelsGenerator.cs, src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
In an effort to make Umbraco support 🔥 [Hot Reload](https://learn.microsoft.com/en-us/aspnet/core/test/hot-reload), the Models Builder models generation needs to change a little:
1. It must not delete and recreate files. This constitutes a "rude edit" towards Hot Reload, which in turn requires an application restart.
2. It must not generate `virtual` properties, as adding `virtual` members is an [unsupported edit](https://learn.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp#unsupported-changes-to-code) for Hot Reload.
The first change is relatively simple; I have made Models Builder a bit more conscious about file deletions.
The second is harder. Models Builder has generated `virtual` properties ~~since forever~~ for the past five years, so simply removing that …
=> Models Builder: Make Models Builder better at not performing "rude edits"

src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
Fixes issue #18420 for **v13**
- Issue is fixed in v16.4/17 but still persists in v13 as referenced in original issue https://github.com/umbraco/Umbraco-CMS/issues/18420#issuecomment-3380349524
- Applied FetchByGroups() extension method like before to batch queries
- Clone and deploy from v13 branch
- Have/create 6000+ users
- Add them all to the same group
- Call userService.GetAllInGroup( groupId ) manually in code to see exception (I quickly created a new Controller endpoint and manually called it from Postman)
=> Repositories: v13 UserService.GetAllInGroup fix

src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
Fixes #16988
Back when Identity was upgraded to identity core, an oversight was made in the code conversion that ended up in a UTC time being stored inside a dateTimeOffset which results in Identity `LockoutEnd` value being set to values that do not correspond to the intend with the following timezone ranges
- For timezones in the +X range this results in lockouts taking longer than intended.
- For timezones in the -X range this results in a lockout never happening if the offset was bigger than the configured `DefaultLockoutTimeInMinutes`.
- Set the `Umbraco::CMS::Security::MemberDefaultLockoutTimeInMinutes` setting to a managable time (like 1 minute)
- Implement a member login/logout flow, member group, member and protected content
- Lock the member out by trying to login with an …
=> Do not convert calculated lockedOutUntil time to UTC

src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor-property.element.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/20169
Adjusted styling for inherited properties to be more consistent with other properties, but slightly different.
=> Adjust styling for inherited content type property
