src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5894
As described in #5894, a server error is displayed when you try editing a media type:
1. Verify that you can add a new property (of any type) to an existing media type.
2. Verify that you can remote the property again.
=> V8: Fix YSOD when editing media types

src/Umbraco.Core/Constants-PropertyEditors.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/ConvertRelatedLinksToMultiUrlPicker.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypeMigration.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/ContentPickerPreValueMigrator.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/MediaPickerPreValueMigrator.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/MergeDateAndDateTimePropertyEditor.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/PropertyEditorsMigration.cs
https://github.com/umbraco/Umbraco-CMS/issues/5902
- Fixed issue with migration of Umbraco.Date if it was never saved in v7, the default format was added the time-part.
- Fixed issue with warnings of migrations of build in types, that was renamed between v7 and v8. These are handled correct.
- Added constants for some of the legacy property editor aliases.
=> V8: Migration should not warn about build in data types that is handled correct but renamed

src/Umbraco.Core/PublishedContentExtensions.cs, src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
Fixes #5886 Variant Children of non-variant node are not listed 
Removes the quirky logic that resets the culture to an empty string and adds unit tests.
See testing notes https://github.com/umbraco/Umbraco-CMS/issues/5886#issuecomment-513100527
=> Fixes issue with Children(culture) method

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/ValueListPreValueMigrator.cs
ValueListPreValueMigrator converts the items config for RadioButtonList and the various dropdowns, but not CheckBoxList. It needs the same conversion.
Testing:
- In 7.15.0, create a CheckBoxList property and add some items. Create a document with some items selected.
- Upgrade to 8.1.0
- Check that the items are still listed, and that the previously selected items are still selected.
---
_This item has been added to our backlog [AB#1872](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1872)_
=> Content migration - Include CheckBoxList in ValueListPreValueMigrator

src/Umbraco.Web/Security/MembershipHelper.cs
Small change but it saves some debugging.
In the summary of MembershipHelper.GetCurrentLoginStatus() it states that null will be returned when no member is logged in but that isn't the case (anymore?).
=> Fixed GetCurrentLoginStatus() summary

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5845
As described in #5845, the save options aren't updated when you publish or unpublish the current content, making it impossible to unpublish content after it's been published without forcing a page reload.
This PR ensures that the save options are always up to date with the state of the current content after save/publish/unpublish:
1. Create some new content and save it. Verify that "Unpublish" is not an option.
2. Publish the content. Verify that "Unpublish" is now available as an option.
3. Unpublish the content. Veify that "Unpublish" is no longer an option.
=> V8: Make sure save options are up to date with the content state

src/Umbraco.Web/PropertyEditors/TagsPropertyEditor.cs
If there's an existing issue for this PR then this fixes #5855
Handles CSV values being returned from the tags editor, which happens when the data type is configured for CSV storage and the page is saved without modifying the tags,
To test:
- Create a Tags property with storage type set to CSV
- Create and save a document with some tags populated
- Reopen the document and save it without making any changes to the tags
- Reopen the document again and confirm that the tags are not blank
=> Handle CSV values in TagsPropertyEditor (#5855)

src/Umbraco.Examine/ExamineExtensions.cs, src/Umbraco.Tests/TestHelpers/RandomIdRamDirectory.cs, src/Umbraco.Tests/Umbraco.Tests.csproj, src/Umbraco.Tests/Web/PublishedContentQueryTests.cs, src/Umbraco.Tests/Web/UmbracoHelperTests.cs, src/Umbraco.Web/IPublishedContentQuery.cs, src/Umbraco.Web/PublishedContentQuery.cs, src/Umbraco.Web/UmbracoContextFactory.cs
See #5789 
To test follow the steps provided in the issue and make sure the expected results work.
Have a look at the code changes - the reason why this problem occurred is because passing in 'null' for a culture should mean it only searches invariant but this was defaulting to `_variationContextAccessor.VariationContext.Culture;` which always returns a culture. Further to that, the method's optional parameter value was incorrect. A "*" is what should be the default indicating that all cultures will be searched (this is consistent with our other culture methods in Umbraco APIs). Specifying an explicit null will be an invariant search or specifying a culture will only search that culture.
=> Fixes #5789 - PublishedContentQuery Search always searches on culture

src/Umbraco.Core/Exceptions/PanicException.cs, src/Umbraco.Core/Mapping/UmbracoMapper.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/RenamingPreValueMigrator.cs, src/Umbraco.Core/Models/PublishedContent/ModelType.cs, src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Tests/Testing/TestOptionAttributeBase.cs, src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs, src/Umbraco.Web/PropertyEditors/MultipleTextStringPropertyEditor.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs, src/Umbraco.Web/PublishedCache/NuCache/SnapDictionary.cs
Several places we are just throwing `new Exception("panic")` which indicates that this should __never__ happen, however in cases that it might, it is better to have a custom exception with some actual details, so this does that.
=> Adds PanicException with details instead of throwing "panic" strings

src/Umbraco.Examine/ContentValueSetBuilder.cs, src/Umbraco.Examine/ExamineExtensions.cs, src/Umbraco.Examine/IndexRebuilder.cs, src/Umbraco.Examine/LuceneIndexDiagnostics.cs, src/Umbraco.Examine/Umbraco.Examine.csproj, src/Umbraco.Examine/UmbracoExamineIndexDiagnostics.cs, src/Umbraco.Web/Search/BackgroundIndexRebuilder.cs, src/Umbraco.Web/Search/ExamineComponent.cs, src/Umbraco.Web/Search/ExamineComposer.cs, src/Umbraco.Web/Search/ExamineFinalComponent.cs, src/Umbraco.Web/Search/ExamineFinalComposer.cs, src/Umbraco.Web/Search/ExamineUserComponent.cs, src/Umbraco.Web/Search/GenericIndexDiagnostics.cs, src/Umbraco.Web/Suspendable.cs, src/Umbraco.Web/Umbraco.Web.csproj
There's an issue currently for developers creating custom lucene based indexes that most times requires that the index be manually unlocked on startup in their custom IComponent. This was never the intention and the reason is because Umbraco unlocks all of the indexes at startup but unfortunately this was happening before the developers component was executing.
This solves a couple of problems:
* Ensures the indexes are unlocked and the rebuild logic for empty indexes is queued AFTER all user components
* Creates a base class for custom index developers `ExamineUserComponent` so that developers can inherit from this instead of just `IComponent` and this will also ensure that no initialization is done if MainDom was not acquired. This is very important for Lucene and by inheriting from …
=> Fixes how examine starts up to make it easier for custom index developers

src/Umbraco.Tests/TestHelpers/ControllerTesting/TestRunner.cs, src/Umbraco.Tests/Umbraco.Tests.csproj, src/Umbraco.Tests/Web/Controllers/AuthenticationControllerTests.cs, src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs, src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
This fixes #5976
This fixes #5976 and allows for viewing the User list in the back-office when FIPS is enabled.  It also includes unit tests to verify that user mapping (the most common FIPS-breaking change) is FIPS compliant.
To verify this fix:
1. Follow the directions at https://our.umbraco.com/documentation/Reference/Security/Setup-Umbraco-for-a-Fips-Server/ to install Umbraco v8.1 on a FIPS-enabled server.
2. Go through the install wizard
3. Log in to the back office, and navigate to the Users section
4. You should not see any error in the users list, but should see a list of currently active users (see attached screenshot ![FIPS_Enabled_User_List](https://user-images.githubusercontent.com/702500/61664328-6a919900-ac87-11e9-8845-92ac3df953b7.png))
=> Fix FIPS compliance, add FIPS tests

src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5995
See #5995 for details.
As it turns out, the user editing implementation already supports removal of user start nodes - it's just not been enabled in the view. So... this PR just does that.
When this PR is applied, user start nodes can be removed for both content and media:
=> V8: Allow removing user start nodes

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
In the DocType Editor, when sorting the groups and properties, the draggable direction is freeform (horizontal, vertical or even diagonal).
We can restrict the direction, by setting the `axis` property in the sort options.
---
To test, in the DocType Editor, press "Reorder", then drag the groups and/or properties, the direction will be restricted to the vertical axis.
=> DocType Editor sorting - vertical direction

src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js, src/Umbraco.Web.UI.Client/src/views/content/create.html
The direct access to assign allowed child types to a content type from the "Create" dialog is currently broken:
Looks like this is caused by the changes in #5729 (swapping the link for a button, thus making the `href` attribute meaningless).
This PR amends it, so the button works again:
=> V8: Fix broken button to open content type from create dialog

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes #5504
The order of execution when setting up a media picker has changed in v8, so that `$scope.isMultiPicker` is read before it has been initialized. This leads to sorting being disabled, because sortableOptions is always set up as though it's a single media picker.
Testing:
- Add some items to a multiple media picker property editor
- Check that you can sort them by dragging
=> V8: Sorting of images in multiple media picker

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js, src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less, src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editors.html
If there's an existing issue for this PR then this fixes #6058
This PR fixes the "infinityMode" typo originating from the `umbEditors` directive.
As it turns out, `umbEditors` attempts to dictate infinite mode - only it kinda fails as it's setting `infinityMode`, not `infiniteMode` which is used throughout the app. But `umbEditors` really shouldn't be messing with infinite mode. This is determined and handled by `editorService` [here](https://github.com/umbraco/Umbraco-CMS/blob/a398881fa1e7eebda4ad74d505a592d4178bfa64/src/Umbraco.Web.UI.Client/src/common/services/editor.service.js#L265).
Bottom line: We can safely remove the `infinityMode` assignment from `umbEditors` and rely on the `infiniteMode` assignment from `editorService`. That's what this PR does 😄 
Browse around the backoffice …
=> V8: Fix "infinityMode" typo

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
_This is the V8-ification of #6081_
If Umbraco can figure out which media folder you last visited, the "Upload" button in the media picker is disabled. If you browse around within the media picker, the "Upload" button immediately becomes enabled, even for the folder where it was initially disabled:
This PR fixes the issue; when it's applied the "Upload" button works as expected:
=> V8: Fix the disabled upload button in media picker

src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6075
If Umbraco can figure out which media folder you last visited, the "Upload" button in the media picker is disabled. If you browse around within the media picker, the "Upload" button immediately becomes enabled, even for the folder where it was initially disabled:
The issue was introduced with 1dd2c1cb. Basically it's due to a missing `path` property in the starting node of the media picker, whichever node that might be (except the root).
This PR fixes the issue; when it's applied the "Upload" button works as expected:
=> V7: Fix the disabled upload button in media picker

src/Umbraco.Web.UI.Client/src/less/tree.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6079
As described in #6079 you can't tell if a node is protected if it's a container (list view) node. As it turns out, the same thing applies to nodes with pending changes:
This PR changes the priority of the tree node annotations to be:
1. Is protected
2. Has pending changes
3. Is container (list view)
When the PR is applied, the same nodes will look like this:
=> V7: Change the priority of the tree node annotations for containers

src/Umbraco.Web/Cache/TemplateCacheRefresher.cs
_Original source for this issue here: https://github.com/umbraco/Umbraco-CMS/issues/6006#issuecomment-515677337_ 
When you delete a template that's assigned to a content type, the content type remains in the cache with the template assigned:
Turns out the template cache refresher doesn't clear the "common" cache for content types, only the isolated content type cache. This PR amends that, and thus deleting a template also forces a content type cache refresh:
1. Create a content type with a template assigned.
2. Delete the template.
3. Verify that the content type does not list the (now deleted) template in its "Templates" section.
=> V8: Clear the content type "common" cache when deleting templates

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
If there's an existing issue for this PR then this fixes #6006 (in part)
When opening the content template from the content "info" section, the currently assigned template is always opened no matter if you selected another one (assuming you have multiple templates allowed):
The same issue is the root cause of a slightly more annoying (and rather less likely to happen) error, which can be produced by the following steps:
1. Create a content type without a template.
2. Create a content item based on this content type.
3. Assign a template to the content type.
4. Open the content item and switch to the "info" section. The template will list as being already assigned to the content item because it will be once the content item is saved.
5. Open the template in infinite editing. 404 error …
=> V8: Always open the selected content template in infinite editing

src/Umbraco.Web.UI.Client/src/views/content/content.edit.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6022
Looks like 88d9e332 introduced a bit of weird behavior for multilingual content; the selected main culture (`mculture`) is never applied to content when browsing around, thus unless `cculture` is explicitly specified, content is by default displayed in the default language no matter what is selected as main culture.
Here's a GIF that demonstrates the problem:
This PR fixes it by reverting [this change](https://github.com/umbraco/Umbraco-CMS/commit/88d9e3321c4dce97dc6122c919ee3c6226631dd4#diff-aa230801fb161647c66f06257a18665bR27) from 88d9e332. When the PR is applied, the content editor once again conforms to the selected main culture:
1. Verify that the selected main culture is …
=> V8: Use mculture in content editor for multilingual content

src/Umbraco.Core/Composing/CompositionExtensions/FileSystems.cs
It was not possible to change the media path without using a custom composer like this:
```
public class CoreComposer : IUserComposer
{
public void Compose(Composition composition)
{
composition.SetMediaFileSystem(() => new PhysicalFileSystem(SystemDirectories.Media));
}
}
```
That's because the FileSystems composer uses a hard-coded folder `~/media` for the `PhysicalFileSystem` and ignores the `SystemDirectories.Media` path which can be changed via the appSettings configuration.
`composition.SetMediaFileSystem(() => new PhysicalFileSystem("~/media"));`
It's basically a one liner which replaces the mentioned hard-coded string with:
`composition.SetMediaFileSystem(() => new PhysicalFileSystem(SystemDirectories.Media));`
=> use modifiable media path in file system composition

src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js, src/Umbraco.Web.UI.Client/src/views/components/grid/grid-rte.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
This PR uses TinyMCE's init event for us to hide our own loader, as opposed to previously hiding the loader once the main TinyMCE library was loaded as opposed to all it's plugins/buttons and the HTML content to be loaded.
This should link to [AB#2190](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2190)
* Please test with a TinyMCE richtext editor on a doctype with all the plugins/options enabled
* Try before & after the PR applied
* Use browser devtools & force a hard cache refresh of a content page with a RTE
* Throttle the connection speed to Slow 3G to highlight the problem easier
=> AB#2190 - Improve jarring TinyMCE editor loading experience

src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs, src/Umbraco.Tests/Persistence/Repositories/LanguageRepositoryTest.cs, src/Umbraco.Web/Dictionary/UmbracoCultureDictionary.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5959
This is a new take on the issue outlined in #4519. The PR reverts the changes from #4519 and handles dictionary based localization via region-less languages in a different way.
First and foremost make sure you have created both a region specific and a region-less language - e.g. add "da" if you still have the default "en-US":
Create a doctype that localizes both its name and a property label via the dictionary (using the "#" notation):
Add two dictionary entries, one for the name of the doctype and one for the name property label:
Set your user language to match the region-less language you created above - e.g. use "da-DK" as your user language if you created "da". 
Verify that the …
=> V8: Allow localization of the backoffice using parent cultures to the editor culture

src/Umbraco.Core/Logging/Viewer/ILogViewer.cs, src/Umbraco.Core/Logging/Viewer/LogViewerSourceBase.cs, src/Umbraco.Web.UI.Client/src/common/resources/logviewer.resource.js, src/Umbraco.Web.UI.Client/src/less/components/umb-box.less, src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js, src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html, src/Umbraco.Web/Editors/LogViewerController.cs
If there's an existing issue for this PR then this fixes #6055 
Changes here display the current log level in the sidebar of the log viewer dashboard. Will look like this:
What's changed?
- updated LogViewerSourceBase.cs to add a method for fetching the current Serilog level.
- added endpoint to LogViewerController.cs to call into that new method
- updated logViewerResource.js to add a client-side function. Also tidied up to remove a heap of duplication (refactors call to umbRequestHelper into a separate function)
- updated overview.controller.js to request the log level, and uses the returned value to set the display color for the level to match the pie chart colors
- updates UI to display the new bit - I've added a variation for the `umb-box` directive to display these inline, by …
=> V8: Display current log level in log viewer sidebar

src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
If there's an existing issue for this PR then this fixes #6065
As described in issue step to test that:
Steps to reproduce
Create a custom tree in BackOffice.
Add a menu alternative that opens a dialog and trigger either success, error or warning in notificationsService.
Expected result
You can see the full notification, and read the text
=> v7 Change z-index for notification

src/Umbraco.Web/Editors/MediaTypeController.cs
When creating a new MediaType beneath an existing MediaType, the composition is not set correctly, and any properties from the parent MediaType are not inherited by the child MediaType.
This PR fixes #6047
=> Fix for #6047 - Ensure a media type correctly inherits it's selected parent

src/Umbraco.Web/Editors/MediaTypeController.cs
When creating a new MediaType beneath an existing MediaType, the composition is not set correctly, and any properties from the parent MediaType are not inherited by the child MediaType.
This PR fixes #6047
=> v8: Fix for #6047 to Ensure a media type correctly inherits it's selected parent

src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree-item.less, src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6063
This PR fixes a few issues, where the action menu button wasn't visible on hover on tree nodes with longer node names and some strange behavior when focus through the tree, where the tree items was pushed when the focus was on the action menu button.
=> v8: Allow tree item label to shrink

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js
If there's an existing issue for this PR then this fixes #6098
There is no warning to discard changes if you navigate away from a content type after making changes to its properties (add, remove or edit property).
This applies to both document types, media types and member types.
With this PR applied, the warning shows as you'd expect:
Verify for document types, media types and member types that a warning appears when you navigate away after:
- Adding a new property
- Removing an existing property
- Editing an existing property
=> V8: Make sure to mark the current form as dirty when altering content types

src/Umbraco.Web.UI.Client/src/views/components/application/umb-tour.html, src/Umbraco.Web.UI.Client/src/views/components/application/umbtour/umb-tour-step.html
This fixes issue 11 from #5277 
It appears to me that the "X" is possible to tab to using the keyboard - However I noticed that the "Don't show this tour again" was not, so I have been fixing that.
I have also added a sr-only text to the close button so "Close" is read out to screen readers.
**Before**
**After**
=> Accessibility: Unable to navigate to close 'X' icon with keyboard

src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html, src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.html, src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html, src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html, src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
This fixes issue 104 and 117 from #5277 
This PR wraps every found instance of the unicode character &larr; in a aria-hidden="true" element so screen reader don't read it out loud, since it does not make much sense.
Also all of the places where the back button was used are refactored from `<a>` to `<button>` and styling has been fixed accordingly. Once this PR is approved I'll have a look at making some kind of button component since I noticed the exact same look and feel being implemented differently in the examine dashboard 😃
=> Accessibility: Open Package - Identifies back button as "Left hand arrow back button"

src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
Slightly odd scenario here:
1. Start creating content based on a content template. Don't save.
2. Now create content of another type that does *not* use a content template.
3. The editor still attempts to create content of the other type based on the previously selected content template.
Similar (and slightly less odd) scenario:
1. Start creating content based on a content template. Don't save.
2. Now create content of the same content type but _not_ based on a content template.
3. The previously selected content template data still lingers in the editor.
This PR fixes both of these scenarios - here's how it works when the PR is applied:
=> V8: Don't reuse previously used content templates when creating new content

src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.controller.js
A default browser confirm modal is still used when deleting user groups:
This PR changes it to use an Umbraco confirm dialog:
=> V8: Use an Umbraco confirm dialog when deleting groups

src/Umbraco.Web/Editors/ContentController.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6057
This PR updates the public access functionality of V8 so it behaves like V7 when configuring public access for children of a protected parent. See #6057 (specifically https://github.com/umbraco/Umbraco-CMS/issues/6057#issuecomment-520720833) for additional details.
With this PR applied, you no longer change the parent protection by accident when editing the public access settings for a child. Here's a GIF demonstrating it:
1. Assign protection to a node with multiple children.
2. Assign protection to one of the children; verify that you're tasked with setting public access up all over again, _not_ editing the settings of the protected parent.
3. Once assigned, verify that the …
=> V8: Don't change parent protection when editing child protection

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
For some odd reason the media picker doesn't flag the current form as dirty when its value changes:
This applies to:
- Picking new media.
- Removing existing media.
- Sorting (which may not be testable until #6037 is merged).
When this PR is applied, the dirty flag is set on the current form as soon as the media picker value changes:
=> V8: Set media picker dirty when the value changes

src/Umbraco.Web.UI/config/tinyMceConfig.Release.config, src/Umbraco.Web.UI/config/tinyMceConfig.config
This changes the mode of the styleselect command in the Rich Text Editor to all, making it possible to select styles on selected text in distraction free mode.
To test:
Set a Rich Text Editor to distraction free mode, enable style select. Write some text in the editor, select it and notice the Formats dropdown.
=> Make it possible to select styles on selected text in distraction free mode.

src/Umbraco.Core/Packaging/PackageDataInstallation.cs, src/Umbraco.Core/Services/Implement/EntityXmlSerializer.cs
This PR writes and reads XML elements for the "allow varying by culture" field into the package definition, so this information can be saved and restored by the creation and installation of packages.
Reported in issue #5993.
=> V8: Import and export of document type and property variations setting in packages (5993)

src/Umbraco.Web/Profiling/WebProfilerProvider.cs
Mini Profiler will be disabled when a solution is not in a debug mode, therefore Mini Profiler Startup Profiler won't be accessible.
Fixes: [AB#2178](https://umbraco.visualstudio.com/D-Team%20Tracker/_workitems/edit/2178)
=> Disable Mini Profiler

src/Umbraco.Web/umbraco.presentation/umbraco/webservices/legacyAjaxCalls.asmx.cs
Removes an old web service endpoint which that can be used to bypass account lockout when validating credentials.
A work around can be put in place to prevent access to this endpoint using an IIS Rewrite rule.
In the Web.config, inside `<rewrite><rules>` tags:
```xml
<rule name="Fail bad requests" patternSyntax="ECMAScript">
<match url="umbraco/webservices/legacyajaxcalls\.asmx"/>
<conditions>
<add input="{QUERY_STRING}" pattern="op=ValidateUser" />
</conditions>
<action type="CustomResponse" statusCode="403" statusReason="Forbidden: Access is denied." statusDescription="You do not have permission to view this directory or page." />
</rule>
```
And with the CustomResponse you can put response of your choice.
Any doubts about IIS Rewrite Rules setup -> …
=> Removing legacyAjaxCalls.ValidateUser method

src/Umbraco.Core/Migrations/Expressions/Delete/KeysAndIndexes/DeleteKeysAndIndexesBuilder.cs
Fixes: v8.1 migration from v7 results in an error due to a unique index on cmsContent #5804
A couple of issues:
* The code was trying to drop unique constraints as if they were normal indexes which is not allowed
* Some older DBs have very oddly named things so this deals with oddly named FKs by checking firstly if the name is prefixed with FK, otherwise if its not prefixed with PK and it doesn't exist in our index list, then we can only assume it's an FK
=> Fixes: v8.1 migration from v7 results in an error due to a unique index on cmsContent #5804

src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js, src/Umbraco.Web/Editors/EntityController.cs
If there's an existing issue for this PR then this fixes #6100
When selecting content using either a Content Picker or a Multinode Treepicker, the URLs of the picked content are shown for the default culture - not (necessarily) the current editor culture. See #6100 for details.
This PR ensures that the URLs returned by `entityResource.getUrl()` are always for the current editor culture unless it is explicitly overridden in the method. When the PR is applied, URLs are rendered like this:
For properties of both Content Picker and Multinode Treepicker (configured for picking content), verify that the URLs of the picked items are always rendered in the current editor culture for:
1. Culture variant properties.
2. Culture invariant properties on culture variant content types.
3. Properties on …
=> V8: Make sure treepicker URLs are displayed for the current editor culture

src/Umbraco.Web.UI.Client/src/common/directives/components/umbloader.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/umbloadindicator.directive.js, src/Umbraco.Web.UI.Client/src/less/belle.less, src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less, src/Umbraco.Web.UI.Client/src/less/components/umb-loader.less, src/Umbraco.Web.UI.Client/src/less/main.less, src/Umbraco.Web.UI.Client/src/views/components/application/umb-tour.html, src/Umbraco.Web.UI.Client/src/views/components/umb-loader.html, src/Umbraco.Web.UI.Client/src/views/content/copy.html, src/Umbraco.Web.UI.Client/src/views/content/emptyrecyclebin.html, src/Umbraco.Web.UI.Client/src/views/content/move.html, src/Umbraco.Web.UI.Client/src/views/datatypes/move.html, src/Umbraco.Web.UI.Client/src/views/documenttypes/copy.html, src/Umbraco.Web.UI.Client/src/views/documenttypes/move.html, src/Umbraco.Web.UI.Client/src/views/media/emptyrecyclebin.html, src/Umbraco.Web.UI.Client/src/views/mediatypes/copy.html, src/Umbraco.Web.UI.Client/src/views/mediatypes/move.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4958
This PR replaces a few places where `.umb-loader` is used with this `<umb-loader>` directive.
The `umb-loader` added in embed preview here https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.controller.js#L40 is replaced by `<umb-load-indicator>` directive is this PR https://github.com/umbraco/Umbraco-CMS/pull/4899
=> v8: Add umbLoader directive

src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
Prevent malicious JS content from .svg media files to be running inside of the back office.
Fixes: [AB#2180](https://umbraco.visualstudio.com/D-Team%20Tracker/_workitems/edit/2180)
=> Secure svg media files preview

src/Umbraco.Core/Constants-PropertyEditors.cs, src/Umbraco.Tests/Composing/TypeLoaderTests.cs, src/Umbraco.Web/PropertyEditors/ParameterEditors/MultipleMediaPickerParameterEditor.cs, src/Umbraco.Web/Umbraco.Web.csproj
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5335
Seemingly due to an oversight, multiple media picker was not available for macro parameters. This corrects that problem. 
Test steps:
- Add a Partial View Macro File from snippet "Gallery"
- Go to the macro this has created and enable it to be used in a RTE
- Go to the macro parameters and add a new parameter with the name "Media Picker", the alias `mediaIds` and of type "Multiple Media Picker"
- Add the "Gallery" macro in a RTE
- You get asked to pick one or more items, make sure you can pick multiple items
- When you're done picking, the macro preview should show you the picked items
=> Fix #5335 - Multiple Media Picker not available as macro parameter

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
This pull request updates the **Nested Content** property editor so you can distinguish document types which have the same name by appending the alias.
It also disables the "Add" button in case no available document types are left.
=> Ability to distinguish document types with same name in Nested Content config

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6172
If you add a link with only an anchor or a query string value in a Multi URL Picker property and then go to edit the link again *without saving the content first*, the Multi URL Picker editor crashes with a JS error:
=> V8: Don't crash the Multi URL Picker if only an anchor has been entered

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.editor.html
Related issue: [#6148 ](https://github.com/umbraco/Umbraco-CMS/issues/6148)
NestedContent items are missing a data-attribute that is added to property editors by default.
I added that data-attribute (data-property), tested it and everything works just the way it should work.
Here's a screenshot of the NestedContent item with the data-attribute added to it:
=> Fix #6148 - added data element to NestedContent - V7

src/Umbraco.Web/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
If there's an existing issue for this PR then this fixes #5984, #5987, #6141
Macro results are being cached as part of RTE values even if the macro has all caching disabled.
`RteMacroRenderingValueConverter` sets its cache level to Snapshot, but that isn't actually doing what we want it to. That cache level is used when caching the ObjectValue and XPathValue, but the macro rendering is happening in `ConvertSourceToIntermediate`. The intermediate value is effectively always cached at the Element level.
This PR moves the processing into `ConvertIntermediateToObject` and `ConvertIntermediateToXPath`.
Testing:
- Create a Partial Macro with an @DateTime.Now.Ticks output
- Create a Macro which uses the Partial Macro and Use in rich text editor and the grid enabled, Cache Period 0, Cache by Page …
=> V8: Fix caching of macro results in RTE

src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6097
This PR allows plugins to place their localization files anywhere in the plugin folder sub structure, as long as they reside within a folder called `Lang`.
To test this PR:
1. Unzip the attached plugin in `App_Plugins`
2. Log in with a user in `en-US` backoffice locale
3. Verify that the "Language test dashboard" is localized correctly. It'll use the localization files in `~/App_Plugins/LanguageTest/Some/Another/Lang/`, and it should look something like this:
The test plugin is here: 
[LanguageTest.zip](https://github.com/umbraco/Umbraco-CMS/files/3519659/LanguageTest.zip)
=> V8: Allow plugin "Lang" folders to reside in nested directories

src/Umbraco.Tests/Routing/RenderRouteHandlerTests.cs, src/Umbraco.Web/Runtime/WebFinalComponent.cs, src/Umbraco.Web/Runtime/WebInitialComponent.cs
If there's an existing issue for this PR then this fixes #6045
This implements Solution 1 discussed in #6045, moving the registration of Umbraco's routes into WebInitialComponent so that custom routes can more easily be placed after Umbraco's routes.
To test:
- Create an IUserComposer and IComponent registering a very general custom route, such as the standard `{controller}/{action}`.
- Check that the route doesn't take priority over more specific routes needed by Umbraco.
=> Move CreateRoutes from WebFinalComponent to WebInitialComponent

src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
Prevent malicious JS content from .svg media files to be running inside of the back office.
Fixes: [AB#2180](https://umbraco.visualstudio.com/D-Team%20Tracker/_workitems/edit/2180)
Test notes can be found on [AB#2293](https://umbraco.visualstudio.com/D-Team%20Tracker/_workitems/edit/2293) for now.
=> Secure svg media files preview - v8

src/Umbraco.Web.UI.Client/src/main.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js, src/Umbraco.Web.UI.Client/test/unit/app/propertyeditors/rte-controller.spec.js, src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml, src/Umbraco.Web.UI/Umbraco/js/main.controller.js, src/Umbraco.Web/Editors/BackOfficeController.cs, src/Umbraco.Web/HtmlHelperBackOfficeExtensions.cs, src/Umbraco.Web/JavaScript/JsInitialization.cs, src/Umbraco.Web/JavaScript/Resources.Designer.cs, src/Umbraco.Web/JavaScript/Resources.resx, src/Umbraco.Web/JavaScript/TinyMceInitialize.js, src/Umbraco.Web/Umbraco.Web.csproj
Adds TinyMCE JS assets into init page load via script in default.cshtml view for Umbraco backoffice ng-app
* Add TinyMCE JS assets array via NG app.value & uses assetsService to load (if not loaded in time by main init script above)
Fixes [AB#2196](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2196)
=> Improve JS Asset load of TinyMCE Editor

src/Umbraco.Core/Migrations/Upgrade/V_8_1_0/ConvertTinyMceAndGridMediaUrlsToLocalLink.cs, src/Umbraco.Web/PropertyEditors/GridPropertyIndexValueFactory.cs
If there's an existing issue for this PR then this fixes #6060
The `ConvertTinyMceAndGridMediaUrlsToLocalLink` migration and `GridPropertyIndexValueFactory` fail if a grid control has no `value` property, stopping the upgrade.
Testing:
- Modify a grid value in a 7.15 database to include something like
```json
controls:[{
"value": null,
"editor": {
"alias": "rte",
"view": null
},
"styles": null,
"config": null
}, {
"editor": {
"alias": "rte",
"view": null
},
"styles": null,
"config": null
}]
```
- Upgrade to v8 and confirm that the modified grid value has been indexed in Examine.
=> V8: Handle missing grid values in migration from 7.15

src/Umbraco.Core/Persistence/Factories/MediaFactory.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6202
Replaced hard-coded media string and used the SystemDirectories.Media path.
=> use SystemDirectories.Media instead of hardcoded string media

src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5771
See #5771 for steps to reproduce/test. 
The issue happens because the tree searcher assumes that the icon "icon-document" in a media search result means a bad mapping from the search result; it's the default icon used by the mapper. However, "icon-document" is also used for the default file media type, so it doesn't have to be a mapping error.
With this PR applied, the search feature in the tree picker works as expected for file results:
=> V7: Fix media file icon in search results

src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js, src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5769
See #5769 for details on the issue. 
This is pretty much just a backport of the same bugfix for V8 (#5213).
When this PR is applied, the items in the blueprint selection dialog are listed in the order in which they're defined in the Nested Content configuration:
=> V7: Make sure Nested Content blueprints are listed in defined sort order

src/Umbraco.Web.UI.Client/src/views/content/content.delete.controller.js, src/Umbraco.Web.UI.Client/src/views/content/delete.html, src/Umbraco.Web.UI.Client/src/views/media/delete.html, src/Umbraco.Web.UI.Client/src/views/media/media.delete.controller.js, src/Umbraco.Web.UI/umbraco/config/lang/da.xml, src/Umbraco.Web.UI/umbraco/config/lang/en.xml, src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5975
There is no confirmation when deleting items in the content and media sections; all you get is that little node animation as it "jumps" out of the tree.
This PR adds a confirmation in the same style that applies to the move, copy and restore actions. See #5975 for more info.
Here are previews of this PR in action:
=> V7: Add confirmation when deleting content and media

src/Umbraco.Web.UI.Client/src/views/content/content.delete.controller.js, src/Umbraco.Web.UI.Client/src/views/content/delete.html, src/Umbraco.Web.UI.Client/src/views/media/delete.html, src/Umbraco.Web.UI.Client/src/views/media/media.delete.controller.js, src/Umbraco.Web.UI/Umbraco/config/lang/da.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5975 (for V8)
_Note: This is the V8-ification of #6004_
There is no confirmation when deleting items in the content and media sections; all you get is that little node animation as it "jumps" out of the tree.
This PR adds a confirmation in the same style that applies to the move, copy and restore actions. See #5975 for more info.
Here are previews of this PR in action:
=> V8: Add confirmation when deleting content and media

.github/CONTRIBUTION_GUIDELINES.md
In the [ Contributing](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md), in the section for [guidelines](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md#guidelines-for-contributions-we-welcome) the link for documentation for small and large changes currently leads to a 404 page. I have added that back in from the v7/dev branch.
=> Added contribution guidelines file which was otherwise leading to a 404 from the Contributing.md file

src/Umbraco.Web.UI.Client/src/less/components/umb-table.less, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
It's not immediately obvious that items in a mini listview can be picked, since the cursor isn't of type `pointer` when the items are hovered:
With this PR applied it becomes marginally more obvious that the items are selectable 😄 
Note that the "expand" arrow has been dimmed down a little until it's hovered, to provide a hint that clicking it will expand the item, not select it.
=> V8: Use a pointer cursor for selectable items in mini listviews

src/Umbraco.Web.UI.Client/src/less/components/editor.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/overlays/confirmremove.html
When you remove an existing composition from a content type, the confirmation dialog that pops up is rather unlike any other place in the backoffice. It is also kinda broken, as you can scroll it out of view:
This PR moves the confirmation to a default dialog (overlay), which is first and foremost in line with the other dialogs, and as an added bonus you can't scroll it out of view 😆 
Here's how things work with this PR applied:
=> V8: Use a standard confirm dialog when removing content type compositions

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/RefactorMacroColumns.cs
If there's an existing issue for this PR then this fixes #5827 
The RefactorMacroColumns migration assumes that unused columns in `cmsMacro` will be NULL. This is true when a macro is first created while adding a partial view file, but they'll be empty strings if the macro has then been edited. It also assumes that at least one column will be non-NULL (which should be true, but apparently not always).
Testing:
- In 7.15, create a macro but don't save it. The row in `cmsMacro` should have NULL in `macroPython`, `macroScriptType`, `macroScriptAssembly`, `macroXSLT`.
- Create an XSLT macro and save it. The row in `cmsMacro` should have empty strings in `macroPython`, `macroScriptType`, `macroScriptAssembly`.
- Upgrade to 8.1.
- Both macros should be `macroType` 4. The ex-XSLT macro should …
=> Handle null/empty values in RefactorMacroColumns migration

src/Umbraco.Core/Services/Implement/ContentService.cs
When debugging deployments I ran into this error message, and I had to attach the Umbraco Core code to figure out which node had an issue being saved. 
Would be awesome to have more info on which specific content item it is that is failing for when you are looping through this call.
Not entirely sure how the site got into an error state where the content service couldn't save a node, so not sure on the steps to reproduce to get this error message. All this PR does is improve a bit on info in errors though.
=> Improve error messages

src/Umbraco.Web/PropertyEditors/GridPropertyIndexValueFactory.cs
If there's an existing issue for this PR then this fixes #6164
If a grid control stores a JSON value rather than a string, the value is not indexed by Examine. This PR indexes any string values found within the JSON.
Testing:
- Add a macro control to a grid, with a unique value in a macro parameter.
- Search for the unique value in the Examine dashboard, the document should be found.
=> V8: Indexing of grid values containing JSON

src/Umbraco.Core/Persistence/Repositories/Implement/EntityRepository.cs
If there's an existing issue for this PR then this fixes #6158
The upgrade to 7.8.0 would not create rows in `cmsMedia` for folders (or any media type without an `umbracoFile` property). From 7.15 the media tree used an inner join to `cmsMedia`, so folders created before the upgrade to 7.8.0 disappeared.
The problem was fixed for 7.15 in PR #5865., but v8 has a similar issue with those media folders (except that the table is now `umbracoMediaVersion`). This PR applies the equivalent fix for v8.
=> V8 - missing media folders after migration

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/MarkdownEditorPreValueMigrator.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/PreValueMigratorComposer.cs, src/Umbraco.Core/Umbraco.Core.csproj
If there's an existing issue for this PR then this fixes  #6194 
Adds a PreValueMigrator for the markdown editor, converting the `preview` value to a bool,
Testing:
- In 7.15, create a Markdown data type, and upgrade to 8.1
- Check that the config for the migrated data type has `preview:true` or `preview:false`, rather than the original string value.
=> V8: Migration of MarkdownEditor prevalues

src/Umbraco.Web.UI.Client/src/less/property-editors.less
If no results are found when searching for items in list views, the label that should tell you so is rather hidden behind the sticky header bar:
With this PR applied, the label displays as expected:
The offending line of CSS was added in d17022d8 to solve something sticky header bar related. However, I haven't been able to find any sticky header bar related issues when removing the CSS, neither in the grid nor in list views.
=> V8: Make sure the empty search result is visible for list views

src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6033
If you configure a media picker to pick only images, the media picker value converter assumes that all picked elements in the media picker are of a content type with the alias `Image` (which is the default "Image" media type).
This is handy as you can access the built-in image properties of `Image` like `UmbracoHeight` and `UmbracoWidth` directly without having to cast it or use e.g. `.Value<int>("umbracoHeight")`.
Unfortunately this hard coded content type alias also results in a YSOD when rendering, if an editor has picked another "image" media type - e.g. if you have a custom "image" media type alongside the built-in one. Here's a GIF that demonstrates it:
Clearly the media …
=> V8: Hard coded "image" type in media picker value converter causes YSOD

src/Umbraco.Core/Sync/ApplicationUrlHelper.cs
**Note**: I've left the above unchecked, I do not believe a new test is appropriate for this change
When deciding whether to use SSL, ApplicationUrlHelper.GetApplicationUrlFromCurrentRequest() has an expression `port == "443"` which is always `false`. The variable `port` is set to to either `""` or `":" + request.ServerVariables["SERVER_PORT"]`, so it might sometimes be ":443" but it will _never_ be just "443". 
This code has been this way for at least a year, and I don't know if the situation it tried to handle makes any sense (using port 443 over plain HTTP, for some reason??) so I've just removed it.
=> Remove comparison in ApplicationUrlHelper.GetApplicationUrlFromCurrentRequest that is always false

src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs
Fixes #6143.
Without this additional field, the greyed out display you see below on the second item isn't seen, so you can't distinguish published and unpublished items.
=> V8: Restored indication of unpublished content in content picker display

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
Originally described by @pgregorynz here: https://twitter.com/pgregorynz/status/1161947910050725893
It can take a bit of time from you click the "Compositions..." button until the compositions dialog is shown. But if you click the button again before the dialog is shown, things go very wrong and you're stuck; you need to reload the browser, and thus any unsaved changes are lost:
Ideally the dialog should be displayed immediately in a loading state when the button is clicked. However that's not at all feasible with the current code structure, so this PR fixes the problem by adding a loading spinner to the button instead:
=> V8: Prevent double click errors when editing compositions

src/Umbraco.Web.UI.Client/lib/markdown/markdown.editor.js
The markdown editor has a tendency to steal input focus if you hit Enter in an input field that doesn't support multiple lines (and thus doesn't explicitly handle the Enter keystroke). It's probably easier to understand with this GIF:
It's got something to do with the way the markdown editor buttons are being built. However I can't seem to reliably disable the button focus, so this PR tackles the problem by ensuring that the button actions are only executed if the markdown editor is actually the currently active element on the page.
1. Create a doctype with a markdown editor and a textbox property.
2. Create some content based on this doctype. Verify that the markdown editor does not automatically obtain focus when you:
- Hit Enter in the content name input field.
- Hit Enter in the …
=> V8: Prevent markdown editor from stealing input focus on enter

src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree-item.less, src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less, src/Umbraco.Web.UI.Client/src/less/installer.less, src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html, src/Umbraco.Web.UI/Umbraco/Install/Views/Index.cshtml
This PR removes the specific markup and styling for the tree loading animation and instead re-use ´umb-loader` component.
To test it open any tree node with children.
I have also replaced the loader in the installer with `umb-loader` component, where it in most cases just need adjustments on color and thickness of the loader.
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/less/installer.less#L169-L204
https://github.com/umbraco/Umbraco-CMS/blob/80d1d73d7c4fa9010fa0bcb7fb774681544e220b/src/Umbraco.Web.UI/Umbraco/Install/Views/Index.cshtml#L22-L24
But I can't see the class `umb-loader-done` is being used anymore, so it has been removed.
=> v8: Replace tree loader with umbLoader component

src/Umbraco.Web.UI.Client/src/views/packages/edit.html
- Go to Packages -> Created Packages -> Click Create Package
- Scroll down to the bottom of the form, the _documentation_ link opens up in the same window
Before
After
=> Documentation link on edit packages open up in the same window

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
The paste plugin was already enabled as it comes from the legacy XML `config/tinymceconfig.config` file so we only needed the additional property `paste_data_images` in the config of every RTE editor init code.
This first step of adding support for pasting images in will put them in as base64 images in the HTML source code - further follow up PRs will make these upload to the media section & be replaced by the real URL as opposed to base64 images.
- Create a doctype with a RTE
- Take a screenshot or similar and copy to your clipboard
- Paste image into RTE
- Find an image on your machine and drag and drop this into the RTE
- Repeat: For a RTE inside a Grid & Nested Content or anything similar
Fixes [AB#2240](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/e …
=> AB 2440 - Enable Paste & Drag n Drop of images into RTE editors

src/Umbraco.Web.UI.Client/src/less/dashboards/healthcheck.less, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html
This fixes issue 99 from #5277
I have added a button beneath the container looping over the health checks and moved the click event onto the button in order to make them keyboard accessible - The styling has been adjusted accordingly and everything looks like it's usual self here 😃 
But when tabbing there is a difference illustrated in the below GIF's. Before it was not possible to tab to the checks one would be tabbing through the navigation after tabbing past the link "the documentation for more information" - After one will tab straight through the groups 👍 😃 
Also I added aria-hidden to the `<i>` elements since they don't make sense to screen readers - This means that at some point a visually hidden text fallback needs to be added. But I'm going to wait doing that until I know if my …
=> Accessibility: Health Check - unable to navigate to additional options via keyboard

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
This PR aims to give the user more context as to what the page is displaying by setting the `<title>` element
I have made this a draft PR because whilst is solves the issue on the login page, it isn't generic enough.
Ideally a `SetTitle` method based on this `init.js` routine should be created:
`$rootScope.$on('$routeChangeSuccess', function (event, current, previous) {..}`
Currently it relies  on a `.params` property which doesn't exist in the context of the login page.
A refactored "`SetTitle`" routine could then be reused once logged into Umbraco to provide more context as to what action the user is performing (currently on the section the user is in is displayed in the title, not what area within that section/ or if the user is creating/ editing something).  More information would …
=> V8: Accessibility Changes For Title On Login Page

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
This PR sets the page title when the user is in the content section and builds on the work in #5888 
The aim is to help screen reader users and also content editors which have multiple tabs open determine what they are doing in the content section.
The logic for the title being set is in umbeditorcontentheader.directive.js as opposed to init.js to prevent multiple hits on the database to retrieve the content name/ content type being edited.
=> V8: Accessibility Changes For Title On Content Section

src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
This PR has a couple of changes for accessibility on the password forgotten screen (accessed via the forgotten password link on the login screen)
- Screen readers can now read the contents of the paragraphs
- Added an alert for the "email will be sent..." message displayed after submit is clicked, allowing screen reader users to hear the newly displayed message
=> v8: Accessibility changes for Forgotten Password Screen

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6270
See #6270 for a description of the issue. Note that this applies to both MNTP and Content Picker properties.
With this PR applied, both property types expect at least one selected item before clientside validation passes:
=> V8: Fix mandatory validation clientside for Content Picker and MNTP

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/SuperZero.cs
If there's an existing issue for this PR then this fixes #6280
The SuperZero migration moves the superuser from ID 0 to -1, but it doesn't update `umbracoUser2NodeNotify`. If there are any notifications configured for user ID 0, the migration fails with a foreign key violation.
This PR just adds the missing SQL update.
Testing:
- In 7.15, set up some notifications for user ID 0 on any content.
- Upgrade to 8.1.
=> V8: Update umbracoUser2NodeNotify in SuperZero migration

src/Umbraco.Web.UI.Client/src/views/common/overlays/embed/embed.html
This is a patch for [Issue 6276](https://github.com/umbraco/Umbraco-CMS/issues/6276).
When Umbraco's RTE Embed dialog is opened, the URL input does not automatically get focus. If a user tries to paste an embed url without first clicking on the URL input, they will unknowingly be pasting the embed url into the RTE behind the dialog. This could result in the url being rendered directly on the front end next to the embed iframe.
This is the RTE embed that I patched:
This is the input that should automatically be getting focus
I saw that the `focus-when` directive was used to solve this problem for other overlays like the `Umbraco.Web.UI.Client/src/views/common/overlays/linkpicker/linkpicker.html`. I applied the same `focus-when` directive to the embed overlay at …
=> Apply focus to URL input on embed overlay open. Issue #6276

src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html, src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4678
This PR fixes an issue where the old password field in change password form was not highlighted, because of the name of the form which returned `vm.passwordForm` and not the interpolated value `{{vm.passwordForm}}`, but `vm.passwordForm` is an object anyway. It seems this was changed here https://github.com/umbraco/Umbraco-CMS/blame/d2be30a228af13e34967e89fe11010749b1bad1b/src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html#L19
I have changed this name to `changePasswordForm` since the parent regular form has the name `passwordForm` here: https://github.com/umbraco/Umbraco-CMS/blob/db6714d3b8f8e04dceb607c3a25117331f6b525d/src/Umbraco.Web.UI.Client/src/views/comm …
=> v8: Highlight of old password in change password form

src/Umbraco.Web.UI.Client/src/less/utilities/_flexbox.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/sectionpicker/sectionpicker.html
I noticed the section picker in users section > group no longer was showing checkmark of the selected sections of when toggle selection of any of these.
**Before**
**After**
=> v8: Fix missing checkmark selection in section picker

src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html, src/Umbraco.Web.UI.Client/src/views/packages/views/created.html, src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
I have tried to improve consistency around buttons in the backoffice in the following places. The following buttons have a `size="xxs"` on the directive making it look tiny and inconsistent from the rest of the application
- Packages section -> Installed Packages -> **Uninstall Package** button
- Packages section -> Created Packages -> **Delete** button
- Help drawer -> **Start** button on completed tours
- Help drawer -> **Rerun** button on tours
**Before**
**After**
Any clarification you need, let me know.
Poornima
=> Improve consistency around some buttons in the backoffice

src/Umbraco.Core/PropertyEditors/ConfigurationFieldsExtensions.cs, src/Umbraco.Core/Umbraco.Core.csproj
Added an extension method for `List<ConfigurationField>` to simplify adding fields.
Currently on a `ConfigurationEditor` implementation, you can either have a strongly-typed class for the fields, or manually each of the fields, _(the latter is my personal preference)._ Adding manually it can become quite verbose...
e.g. 
```csharp
Fields.Add(new ConfigurationField() {
Key = "myFieldAlias",
Name = "My Field Name",
Description = "This is description for my field.",
View = "textstring"
});
```
For my package dev, I do this a lot ... so wrote an extension method to reduce my keystrokes...
```csharp
Fields.Add("myFieldAlias", "My Field Name", "This is description for my field.", "textstring");
```
> Here's my original code from my own package. 
> …
=> ConfigurationFields - `Add` extension method

src/Umbraco.Core/Services/ContentTypeServiceExtensions.cs, src/Umbraco.Web/PropertyEditors/NestedContentController.cs
Added an extension method for `ContentTypeService` to get all the Element Types.
> This is something I've developed for my own package. Thought it would be useful to share.
> https://github.com/leekelleher/umbraco-contentment/blob/6938fba139b45fab6d353027a6e2e3964cb12690/src/Umbraco.Community.Contentment/DataEditors/_/ContentTypeServiceExtensions.cs#L16-L19
I've done this as an extension method, as I wasn't sure whether adding to the concrete implementation would be considered a breaking-change or not?
This PR also updates NestedContent's controller for getting the Element Types.
I haven't added any unit-tests, etc.
_(To be honest, I haven't spent that much time on this - was more of a "I've coded this already, it could be useful in core?" - I could add unit-tests, etc - if it's deemed …
=> Added GetAllElementTypes extension method to ContentTypeService

src/Umbraco.Core/Mapping/UmbracoMapper.cs
UmbracoMapper has an issue whereby if you have some explicit maps for a type, but then also have some base class maps, when you trigger the base class map functions, the explicit maps gets replaced.
With this update, when resolving the base class maps, it now merges any maps for the source type, rather than replacing them.
=> Fixes #6255: Don't replace maps for existing keys

src/Umbraco.Web.UI.Client/src/less/components/umb-content-grid.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5813
This PR add a bit margin before the value in the listview grid layout, so there is some space between the label and value.
**Before**
**After**
=> v8: Add margin before value in listview grid layout

src/Umbraco.Web.UI.Client/src/less/components/application/umb-drawer.less
If you look at the help drawer you can see a space (left margin) by the article title and the tour step names.
**Before**
**After**
=> fix the left margin which causes a space in the help drawer article titles

src/Umbraco.Web.UI.Client/src/views/macros/create.html, src/Umbraco.Web/Editors/MacrosController.cs
The issue [4633 ](https://github.com/umbraco/Umbraco-CMS/issues/4633) mentions how an exception occurs on various parts of the CMS when the name exceeds 255 characters. I have added better exception upon saving on macros. I havent added maxlength attribute to the input field on the right hand panel as that would be a sweeping change. It can be introduced once all the entities have this check in place. I have not added the validation to the `EntityBasic `class either as that would be a sweeping change as well
**Before**
**After**
You should not be able to create a macro with more than 255 characters in the name to begin with. Even if you manually edit the name in the right hand panel name input field, it should give a friendly error message rather than the generic error message.
=> Maxlength attribute on macro name

src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
The issue [4633 ](https://github.com/umbraco/Umbraco-CMS/issues/4633) mentions how an exception occurs on various parts of the CMS when the name exceeds 255 characters. I have added better exception on the MediaTypeService. I havent added maxlength attribute to the input field as that would be a sweeping change. It can be introduced once all the entities have this check in place
Before
After
Let me know if anything is needed.
Poornima
=> Better exception message on media type save

src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs, src/Umbraco.Core/Services/Implement/FileService.cs
The issue [4633 ](https://github.com/umbraco/Umbraco-CMS/issues/4633) mentions how an exception occurs on various parts of the CMS when the name exceeds 255 characters. I have added better exception upon saving on content types. A check has been put in place before the content type is saved as well as template creation. I havent added maxlength attribute to the input field as that would be a sweeping change. It can be introduced once all the entities have this check in place. This should also fix the same issue on MemberType save
Before
After
Regards,
Poornima
=> better exception message on content type save

src/Umbraco.Core/Services/Implement/MediaService.cs
This is a very similar issue to [5007](https://github.com/umbraco/Umbraco-CMS/issues/5007). When you try and save a media (image/file) with name exceeding 255 characters it throws an exception. I have added a check to throw an exception with an error message.
I havent added a maxlength attribute to the input field as that would be a sweeping change. I will try and address this issue for doc types, data types, media types and so on before the maxlength can be introduced on the name fields for all the entities.
Poornima
=> Better exception message when media name exceeds 255 characters

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
Issue: #5724 (Unable to add multiple property groups in membertype/doctype editor)
Moved initGroup to the addGroup function so that it'll create a new initial group every time a new group is added.
Also changed the deleteProperty function so that it doesn't remove the init group when the last property is removed, because there should always be an init group.
=> 5724: Unable to add multiple property groups

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes #6175 and #6176 
Sort and filter (search) state is not applied when going back to a list view from a list view item. See #6175 and #6176 for details on the issue.
When this PR is applied, sorting and filtering will be re-applied when the editor goes back to the list view:
While fixing this I uncovered another issue which this PR also implicitly handles. When you navigate to a child of a list view, and said child also is list view enabled, the pagination of the parent list view is applied to the child list view:
Here's the same operation with this PR applied:
When testing multiple levels of list views, remember that the "Back to list view" functionality only remembers the state of the parent. If you work your way downwards in a …
=> V8: Include sort and filter in list view back link

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html, src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/packages/edit.html
This PR replaces the traditional checkboxes in the packager with `umb-checkbox` component used in many other parts of backoffice UI, e.g. in configuration of TinyMCE.
For some of the properties we might later re-consider if e.g. a tree picker is a better options for examples with many data types, templates etc... at the moment it could potentially be a very long list of checkboxes or we could consider if these should be collapsible?
For now I have re-placed these for `umb-checkbox` to be more consistent for the UI.
**Before**
**After**
Furthermore it seems `umb-checkbox` has been updated with scope properties, so e.g. disabled property is binded to `vm.disabled` while the ng-class evaluated `disabled`, so at the moment when setting `disabled="true"` on `umb-checkbox` it doesn't set the …
=> v8: Use umbCheckbox in packager

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/nucache.html
If there's an existing issue for this PR then this fixes <https://github.com/umbraco/Umbraco-CMS/issues/4253>
The above issue points out some inconsistencies to the modelsbuilder and the published status dashboards. While the modelsbuilder dashboard looks consistent now, the published status dashboard could do with some tweaks. I have got rid of the massive textarea and changed the orange colour buttons to red(similar to modelsbuilder dashboard). I was wondering whether it should be made to look like the Examine Management dashboard, with each title having the blue background, with the text and button within but decided against it as the styling seems to be used for panels. This also raises another question in my head - Should the rebuild indexes button on Examine Management dashboard be …
=> Cleanup to the published status dashboard

src/Umbraco.Core/Services/ContentTypeServiceExtensions.cs, src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js, src/Umbraco.Web/Editors/ContentTypeController.cs, src/Umbraco.Web/Editors/ContentTypeControllerBase.cs, src/Umbraco.Web/Editors/MediaTypeController.cs, src/Umbraco.Web/Editors/MemberTypeController.cs, src/Umbraco.Web/Models/ContentEditing/GetAvailableCompositionsFilter.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4863 (in part)
If you pick a non-element type when composing an element type, ModelsBuilder throws up because the resulting content type cannot be expressed in code:
This PR filters out any non-element types in the compositions picker when you compose element types:
Kudos to @callumbwhyte for raising awareness on this issue (https://twitter.com/callumbwhyte/status/1161956628759007232)
This fix is by no means a complete solution to the issue described in #4863. This is only a first step (albeit an important one).
Later on the following should be implemented to improve on things:
1. It should not be possible to turn a non-element type into an element type if it is composed by or inherits …
=> V8: Don't allow selecting non-element types when composing element types

src/Umbraco.Web.UI.Client/src/less/sections.less
If there's an existing issue for this PR then this fixes #6287
Sections tray is purple:
Changes in this PR make it not purple:
There's not really a whole lot more to say... I tidied up the CSS partial a bit too, replacing hardcoded colors with variables, using the same variable when referencing a colour in multiple places, added a bit of nesting/structure to the SCSS to remove duplicated rules. But most importantly, purple is gone.
=> V8: Sections tray dropdown uses old colours

src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
In Umbraco v8.1.4, I'd opened the Help drawer and notices that there were no tours listed _(I'm not sure why exactly),_ but the "Tours" heading was still being displayed, (with no items below it).
In the AngularJS view, there's an `ng-if="vm.tours"` check, but in the controller `vm.tours` is declared as an empty array. Which is one of those weird JS "truthy" quirks, where an empty arrays are true.
Anyway, by adding the array length check, this fixes it.
In terms of testing, it's a case of checking that the "Tours" heading isn't displayed when there are no tours available.
=> Help Drawer - Hide "Tours" heading if there are no tours

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
The delete action isn't disabled when a Nested Content property has a minimum number of items allowed (but nothing happens after confirming the deletion):
Of course the delete confirmation dialog shouldn't be displayed to begin with, nor should the trash icon give any indication that it's active on hover. This PR fixes that; here's that same operation with this PR applied:
To be honest I would rather have hidden the delete action altogether when it's not applicable, but I'm not sure that's the best course of action here.
=> V8: Don't show Nested Content delete confirmation if an item can't be deleted

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html
The `aria-required` attribute of mandatory textbox properties is wrongly set to `model.validation.mandatory` - it should be a `true`/`false` value:
Obviously someone forgot to add the AngularJS curly braces to the mandatory property. This PR adds them, and thus the `aria-required` attribute behaves like you'd expect:
=> V8: Fix `aria-required` for textbox properties

src/Umbraco.Core/PropertyEditors/ValueConverters/LabelValueConverter.cs
The (decimal) label value converter was missing the check to see if the object stored is of type **double** and so was returning 0 instead of the correct decimal figure in the front-end. 
I've added the check now, so it matches the code in the DecimalValueConverter.
=> V8: Added "double" check for the decimal label

src/Umbraco.Web.UI.Client/src/views/propertyeditors/decimal/decimal.html
Decimal properties only validate mandatory validation on the serverside:
This PR ensures that the mandatory validation is also performed clientside:
=> V8: Make decimal properties work with mandatory validation clientside

src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html
This fixes issue **37** from #5277
Unfortunately I can't illustrate the changes with any kind of graphics for this one 😄 
The following is what has been done
- Changed the `<a>` to `<button>` - The `prevent-default` directive has been removed since adding `type="button"` is enough to avoid form submission of any potential outer form the element may be wrapped inside
- Added `id` attribute so the label with the property name is connected/attached to the `button` - This is not possible when using `<a>` for instance but there are many reasons to why `<a>` should not be used in this case
- I have extended the labels array in the controller to also look up "general_add" and added it to the scope since we need to override the default label setup so the "Add" text from the element is also …
=> Links components (e.g. 'Footer links'), 'Add' is identfied as "Add link" but doesn't identify the label

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js, src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html, src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-menu.html
This fixes issue no. **8** and **44** from #5277 
Much of the groundwork for this was done in #5884 so the following things have been fixed
- Addition of `aria-haspopup` and `aria-expanded` attributes on the button that triggers the action dropdown
- The menu items have been changed from `<a>` to `<button>` elements
- the `aria-hidden="true"` attribute has been added to `<i>` and `<span>` elements that are used to display icons (This goes for all the possible outcomes in the umb-button.html view)
- The umb-botton directive has been extended so it's possible to add the above mentioned aria attributes by passing values for "isExpanded" and "hasPopup"
- The deep-blur directive has been added so the dropdown disappears when it's being tabbed out of using keyboard navigation (See the gif …
=> "Actions" is identified as a button, but behaves like a drop down

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html
The Multi URL Picker should show a red help text when its bounds (min/max) fail to validate, just like MNTP does. But it doesn't:
Looks like it's a bit of a copy/paste error from MNTP, because the code is there to show the help text; it just doesn't work. But this PR fixes it all up:
=> V8: Make sure the validation error help is visible for Multi URL Picker

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
*This is the Multi URL Picker equivalent of #6282*
Multi URL Picker does not perform its mandatory validation on the clientside like it does its min/max bounds validation. The validation is performed serverside, but it would be more consistent to have it work clientside as well:
This PR fixes the validation in exactly the same way as MNTP handles mandatory validation clientside:
1. Create a doctype with a mandatory Multi URL Picker property.
2. Ensure you can't create content of this type without picking at least one URL.
3. Update the Multi URL Picker so it requires at least two or more URLs picked.
4. Verify that the new minimum number of URLs is enforced when editing the content.
=> V8: Make Multi URL Picker mandatory validation work clientside

src/Umbraco.Web/PublishedCache/NuCache/ContentNode.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
This is primarily to resolve issues when schema type changes are made (i.e. content types and data types) which until this PR would result in PureLive models being rebuild dozens of times and since package install/uninstall performs many of these changes and restarts, these operations would cause all sorts of odd problems due to the amount of PureLive models being rebuilt. 
With this change, the creation of the models (calls to `CreateModel`) are done lazily so only when the content is actually request. In theory this means that in the ContentTypeCacheRefresher and DataTypeCacheRefresher we wouldn't need to explicitly call `WithSafeLiveFactory` to re-compile the models eagerly, instead we would just leave the re-compilation to execute lazily when the models are needed. 
Some investigation …
=> Lazily create content and models in NuCache

src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html, src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html
This PR fixes some accessibility misunderstandings on my part for some of PR's that has gotten accepted into the core already.
1. The usage of `aria-haspopup="dialog"` will not make screen readers announce that a dialog will be visible currenlty - NVDA for instances will announce that it's a menu. So for now it's better to use the ellipsis convention. Therefore I have added a `<span class="sr-only">...</span>` after having a good chat with Florian Beijers about this. He suggested adding the text "(Opens dialog)" since the ellipsis approach is not used much on the web but mostly in software - But then we agreed that while "(Opens dialog)" would be nice it was less work to use the ellipsis since it does not require translation
2. Which leads me to the next fix addressed in this PR - I …
=> Fix some accessibility misunderstandings

src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
If you have multiple invalid fields in an editor in "submitted" state, the valid state of the fields doesn't *entirely* kick in until all validation errors of that specific type are corrected (e.g. all mandatory validations must be fulfilled before all fields appear completely valid).
It gets a lot worse when you add property editors that utilize `$setValidity` to do custom validation - for example MNTP with min/max count bounds.
Here's a GIF that shows all of the above:
This PR ensures that the validation watcher aggregates all concrete errors and not just the different types of errors (e.g. mandatory, min-count). When it's applied, things work a tad more intuitively:
=> V8: Make validation work properly with multiple invalid properties

src/Umbraco.Web.UI.Client/src/common/directives/components/tabs/umbtabsnav.directive.js
I had a problem when adding dashboards to the settings section they weren't showing up if they actually could fit on the screen. They did show up in the expand menu if they couldn't fit on the screen.
It turned out there was hardcoded a max number of visible tabs set to 7, I've removed the max and now it behaves as it should.
**Before**:
**After**:
To test add a `package.manifest` with some dashboards, e.g. in `App_Plugins\test`
```json
{
"dashboards":[
{
"alias": "newDashboard",
"view": "someview.html",
"sections": ["settings"]
},
{
"alias": "anotherDashboard",
"view": "someview.html",
"sections": ["settings"]
},
{
"alias": "moreDashboards",
"view": "someview.html",
"sections": ["settings"]
}
]
}
```
=> Remove limit of dashboard tabs and fix when expand menu is shown

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/ConvertRelatedLinksToMultiUrlPicker.cs
These changes fix the issue identified in #6367.  To reproduce that problem, you need to have a v7 site with a Related Links picker with data that still references a content node by its ID, rather than a UDI.  This can often happen if you upgrade a previous v7 site with a Related Links picker (and picked data on a content node) to the latest v7 version.  Attempting to migrate the v7 site to v8 results in an exception in the ConvertRelatedLinksToMultiUrlPicker migration.
The problem was that a SQL query in the class which attempts to resolve ID references did not include a FROM clause.  The fix was to add the FROM clause.
=> Add missing FROM clause

src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
If there's an existing issue for this PR then this fixes #6359
This PR grants the default admin group access to the Translation section during install. See #6359 
This PR does *not* migrate existing admin groups on upgrade, as I don't think that makes any kind of sense.
1. Reset your Umbraco installation.
2. Run the installer.
3. Verify that the default admin user has access to the Translation section in the top menu.
=> V8: Grant the default admin group access to the Translation section

src/Umbraco.Web.UI.Client/src/views/components/umb-grid-selector.html
It's a typo correction, doesn't really need steps to test it.
The `umb-grid-selector` view template says "Akk" instead of "All".
The localization would automatically replace it.
But for languages where there is no direct translation, it would display incorrectly.
=> Typo in umb-grid-selector

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
Fix issue where an embedded macro prevents RTE editor from returning to pristine/valid after a publish and causes the save changes dialog to appear.
Tested on the starter kit. v7.15.3
There seems to be a significant TODO comment in this file discussing issues with event handling of the RTE. So this is an interim fix prior to anyone working on a more permanent solution.
During debugging I noticed after a save and publish the editor always returned to valid/pristine despite the editor.on('SetContent') event being called each time immediately after, even if no changes had occurred inside the RTE itself. So it was a simple matter of adding an isDirty check to this event to prevent the syncContent method from being called if the editor had become valid/pristine.
=> v7/bug/6366 - Update rte.controller.js

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
If there's an existing issue for this PR then this fixes #6349
The rollback dialog raises an event when it has made changes, but the content editor did not bind to that event.
Testing:
- Roll back a document to a previous version. The change should be immediately reflected in the editor, breadcrumbs, and tree.
=> V8: Reload content after rollback

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js
If there's an existing issue for this PR then this fixes #5954
Tours include code to scroll the highlighted element into view, but it incorrectly calculates the position of the highlighted item when the element's offsetParent is inside its scrollParent.
This happens in step 12 of the document types tour because property groups are position:relative.
Testing:
- View the Data structure/Document types tour
- On step 12, the page should scroll down to make the highlighted 'Add Property' button visible.
=> V8: Tours - fix scrolling highlighted element into view

src/Umbraco.Web.UI.Client/src/less/canvas-designer.less, src/Umbraco.Web.UI.Client/src/preview/preview.controller.js, src/Umbraco.Web.UI/Umbraco/Views/Preview/Index.cshtml
The preview sidebar doesn't handle multiple cultures very gracefully:
1. You can't scroll the sidebar downwards, leaving you unable to see all cultures (let alone close the preview).
2. The currently active culture isn't highlighted like the currently active device is.
Here, have a GIF:
This PR fixes both of these issues; here's how the sidebar works when the PR is applied:
...and for a site with only a few cultures:
This isn't necessarily a perfect solution to the scrolling issue, since hiding the scrollbar is pretty bad practice. But I can't think of any better way to handle it for the time being... at least not a way that handles both multiple devices (if you expand beyond the default ones) and multiple cultures.
=> V8: Fix preview with multiple cultures + highlight the current culture

src/SolutionInfo.cs, src/Umbraco.Core/Configuration/UmbracoVersion.cs, src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenFifteenFour/PopulateMissingSecurityStamps.cs, src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Tests/Security/UmbracoBackOfficeIdentityTests.cs, src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
Implements the two suggested fixes for #6224 to enable upgrades from pre-7.3.0 to 7.15.x:
- Allow login without a SecurityStamp to authorise upgrade
- Fill in any NULL security stamp values with a migration
=> V7: Error upgrading due to SecurityStamp being null

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/less/utilities/_spacing.less, src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html, src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
Fixes #6309 
This one makes the links to composition doc types open in an infinite editor.
I added a `.p0` utility class for resetting padding, because I changed the `<a>` to `<button>` for opening the infinite editor.
I also added an event handler in the document type editor controller, for reloading the doctype upon closing the infinite editor.
See the gif https://i.imgur.com/luINNJo.gifv
=> Open composition doctypes in infinite editor

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web/Templates/TemplateUtilities.cs
When we choose an image using the media picker in the RTE, when the image is inserted it is resized to a configured width/height, but when you drag/drop an image, it retains the original (probably hi-res) size which isn't very usable. The drag/drop functionality should behave the same as the media picker and resize to the configured width/height.
* Verify code changes
* Test with a RTE & ensure you change/set a desired max width for images in the datatype config
* Test with nested content
* Test in the Grid
Fixes [AB#2737](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2737)
=> Drag/Drop & Pasted images in RTE aren't resized to configured max image width setting

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/test/unit/app/propertyeditors/rte-controller.spec.js, src/Umbraco.Web/Templates/TemplateUtilities.cs
When an image is added to a RTE and is uploaded to the TEMP directory but the content node is not saved, when the image is deleted/removed it would throw an error in the console about the missing blob image.
See attached video from @Shazwazza 
https://www.screencast.com/t/CCdOkqpvkEe
* Have browser devtools open
* Add an image to the editor - wait for it to be uploaded
* Do not save/publish the content node
* Highlight & remove the image
* Verify that no error is no longer thrown in the browser devtools console
This was fixed by removing the following line
`tinymce.activeEditor.editorUpload.blobCache.removeByUri(imgSrc);`
However, this was originally added with @bergmania as if the same image is added to the RTE more than once it would not add the **data-tempimg** attribute and thus this …
=> Bug: RTE Image deletion error for images that has not been saved as media items

src/Umbraco.Core/Mapping/UmbracoMapper.cs
Fixes #6425 - Recent changes in UmbracoMapper cause an exception 
We ensure that duplicate keys are not added
=> Fixes #6425 - Recent changes in UmbracoMapper cause an exception 

src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
Fixes #6419 regression issue in nucache causing a panic exception
The cause of this was a recent fix for nucache when it was getting a linked node but it wasn't requesting by the current generation, see rev: 7fdbb84c04e0837761a173b209cc6c7501be3d8a 
The regression was a change to AddNodeLocked which we don't want to use the current gen, we want to get the latest gen (using `null`). It was causing an error because the change was requesting nodes by the current parent gen which is incorrect because the parent gen doesn't get incremented when changing a branch of children causing the current node to be returned instead of not returned since when we call `RefreshBranch` for a given node, we actually 'Clear' that node and we are expecting it to no longer exist in the next gen when we call …
=> Fixes #6419 regression issue in nucache causing a panic exception

src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
This PR fixes the positioning of overlays which are intialized with the `position: "target"` property.
The problem with the previous code was that once the overlay is displayed it uses the current dimensions for the calculation of the position. 
Sometimes the content has not been rendered yet when the position is already calculated:
Now it recalculates the position in case:
1. The contents of the overlay changes, so it's dimensions change.
2. The content-wrapper area is resized (due to a window resize or a tree resize)
It is using the `ResizeObserver` API which is implemented in (super) modern browsers ([stats](https://caniuse.com/#feat=resizeobserver)) and falls back to the legacy method in case it is not available.
=> Update positioning of umb-overlay on resize/content-changes

src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
Adding visibility:hidden to the un-hovered list fixes the problem, have also tidied up the css a bit to remove duplicate class references (using sensible nesting namespaces the component, and removes lots of `.umb-sub-views-nav-item` declarations)
If there's an existing issue for this PR then this fixes #6430 
Dropdown now stays hidden when hovering the opaque list, and displays correctly when hovering the Content button only. 
Hover under the button, no list. Hover on the button, list.
=> V8: 6430 Content dropdown should only display when hovering button, not the opaque list

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Adds contenteditable=false attribute as for whatever reason the CSS class of .mceNonEditable is not working when a macro is saved & loaded in a content node
* Add a macro into the RTE
* Before saving the page/node (ensure you can not select inside it & can drag/move it around)
* Save the node & retry moving it (Previous to this PR it would not work)
Fixes [AB#2877](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2877)
=> Fixes selecting Macro Content in RTE to be non editable once node is saved

src/Umbraco.Core/Serialization/JsonNetSerializer.cs, src/Umbraco.Web/Editors/BackOfficeController.cs
This fixes #2996.
In areas where Formatting.Indented was previously used, this now adds a check on GlobalSettings.DebugMode to determine whether to use JSON indentation or not (in release mode, this should substantially reduce data storage size). Should not require a unit test, as it merely affects formatting.
=> Don't store JSON property data as indented

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
Using CSS to set the width instead of Javascript. Fixes issue with toolbar staying narrow when there is more space available.
=> lets not set a specific width, but do it by CSS.

src/Umbraco.Web/Editors/ExamineManagementController.cs
Automatically assign LuceneIndexDiagnostics instead of GenericIndexDiagnostics for LuceneIndexes.
This is for custom created `LuceneIndex`'s so that devs don't need to create their own LuceneIndex implementation and then manually implement IIndexDiagnostics. Currently if you don't do that and only create an index with `new LuceneIndex(....)` you will automatically get assigned a `GenericIndexDiagnostics` which returns some ugly data.
=> Automatically assign LuceneIndexDiagnostics instead of GenericIndexDiagnostics for LuceneIndexes

src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less, src/Umbraco.Web.UI.Client/src/less/rte.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/rte.html
Overwritting TinyMCE skin to visually match Umbraco.
How it should look:
=> TinyMCE looking more Umbraco alike

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html, src/Umbraco.Web.UI/Umbraco/config/lang/da.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Co-authored-by: @webdokkeren <thormadsenholm@gmail.com>
This fixes issue **no. 152** from #5277 
In this PR we have added a few next texts for "passed", "warning", "failed" and "suggestion" in the language files.
In the health check view these texts have been added inside a `<span class="sr-only">`, which means a screen reader will announce for instance "Configuration 1 passed, 2 warning" depending on what's exposed to the DOM.
We realise that pluralized texts need to be handled but that is something that needs to be done in another task as it's something that's not available out of the box currently and will affect other scenarios as well. This is a lot better than having no texts at all 😃
=> Health Check - Text alternatives for icons missing

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
* Ensure you can only drag and drop or paste images in when the insert image/media button is enabled in the RTE toolbar/config
* If disallowed then we add a new native browser event for dragover etc to prevent dropping & showing the no/stop sign icon
* Try to drag an image when the insert media button enabled (Upload should work etc)
* Disable button for insert media - ensure you can not drag or paste images into content
* Note: you should see red cross, no entry style sign/icon when you do try
* Test with vanilla RTE, Nested Content that uses RTE & the Grid RTE
* Test with one or more RTEs on the page with different configs to ensure events bound in isolation to the correct editor/s
Fixes #6424 
Fixes [AB#2881](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workite …
=> Fixes #6424 - Prevent drag & drop of images if button to insert media is not enabled

src/Umbraco.Web.UI.Client/src/views/content/content.delete.controller.js, src/Umbraco.Web.UI.Client/src/views/content/delete.html
If there's an existing issue for this PR then this fixes [6436](https://github.com/umbraco/Umbraco-CMS/issues/6436)
When showing delete-node-dialog, it only show warning: "This will delete the node and all its languages", when site has more than one language.
=> Removing unnecessary delete confirmation

src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less
This PR then this fixes #6299 
Lowering the z-index of the sticky directive to 30 fixes the issues where the "reorder" button clashes with the publishing options menu when it's expanded and you scroll.
**Before**
**After**
Thank you and a high 5 you rock to @webdokkeren for helping out 🙌 😃
=> "Save and publish" options clash with "Reorder"

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-locked-field.less, src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html, src/Umbraco.Web.UI.Client/src/views/components/umb-generate-alias.html, src/Umbraco.Web.UI.Client/src/views/users/group.html, src/Umbraco.Web/Editors/Filters/UserGroupValidateAttribute.cs, src/Umbraco.Web/Models/ContentEditing/UserGroupBasic.cs, src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
If there's an existing issue for this PR then this fixes #6379 
I've disabled renaming of system user groups, both in the UI and at the WebAPI controller level.
This is done for the "Administrators", "Sensitive data" and the "Translators" groups
Before:
After (notice the lock is gone):
=> Disable rename alias of system user groups

src/Umbraco.Web.UI.Client/src/less/dashboards/healthcheck.less, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html, src/Umbraco.Web.UI/Umbraco/config/lang/da.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
This fixes issue **no. 161** from the Trello board https://trello.com/c/dpVcuk4x/165-161-health-check-text-alternatives-for-icons-missing-in-groups
There was an `<a>`, which was converted to a button. Furthermore some icons have been hidden using `.sr-only` and some text alternatives have been provided instead.
Currently a screen reader might not pick up the texts at all but this is something that needs to be addressed in another task but the groundwork for making it work has been done 👍
=> Health Check - Text alternatives for icons missing (In Groups)

src/Umbraco.Web/PropertyEditors/GridConfigurationEditor.cs
previously had the same comment as the GridConfiguration. Now matches comment for other configurationEditors
=> fixed xml comment for GridConfigurationEditor

src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js, src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
This PR add a few changes, so the categories are not hidden (while loading) on selection and also set the active class faster instead of it might wait to update the active state here https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js#L128
Furthermore it doesn't show just Popular heading when selecting "Umbraco Pro" with no results.
=> v8: Package repo categories selection updates

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html, src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.html, src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.settings.controller.js
This PR replace the traditional radiobuttons in relation type view with `umb-radiobutton` component.
The `value` property is defined as one-way binding using `@` which also convert the value as a string, while `<` has ability to pass an object with its original data type to component: https://stackoverflow.com/a/36667226/1693918
I tried the latter one, but it seemed to cause some other issues in checkbox list and radibutton list property editor where it use interpolation like this `value="{{item.value}}"`.
When the current behaviour in `umb-radiobutton` and `umb-checkbox` the initial model value passed in to the component could be a boolean true/false, where it didn't select the radiobutton when model and value was equal because model was a boolean, but value is converted to a boolean and …
=> v8: Use umb-radiobutton component in relation types

src/Umbraco.Web.UI.Client/src/views/languages/overview.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6376
This  PR simply change button style to `danger` in delete confirm in listview (both list and grid layout) in content, media and member section. Furthermore it also change button style for delete confirm in languages.
=> v8: Change confirm delete button style

src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js, src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html, src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js, src/Umbraco.Web.UI.Client/src/views/logviewer/search.html, src/Umbraco.Web.UI.Client/src/views/packages/views/created.html
This PR replace the `success` button style for "Create package" with `action` button style (purple) which is now used in most places like users, languages, etc.
It also change button style for "Show more" in log viewer and change this button to use `umb-button` component and I have cleaned up some odd empty class attributes in logviewer. The logviewer also need to be cleaned up for inline styles, but we can do that in another PR :)
=> v8: Change button style for "create package" and "show more" (in the log viewer)

src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less, src/Umbraco.Web.UI.Client/src/views/components/notifications/umb-notifications.html
This issue fixed **no. 158** on the list of the [Trello board](https://trello.com/c/SObDqgG2/161-158-add-aria-live-to-let-screen-readers-announce-notifications) (Added after the intital Github Issue #5277)
Currently the notifications that appear whenever a content node, templates, document type etc. is saved is not announced by screen readers. which leaves screen reader users clueless that a status message telling us whether the save/publish was a success or not.
Therefore I have added `aria-live="assertive"` and `aria-relevant="additions"`, which will make a screen reader prioritize announcing the latest added notification - So if 2 notifications are added quickly after each other it will abort reading the 1st status and start reading the 2 status instead.
I believe that some of the …
=> Add aria-live to let screen readers announce notifications

src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
As noted in #6374, having the settings icon visible when re-ordering document type properties makes the property elements taller than they need to be.
I've resolved that by hiding this when sorting is in operation, and also the delete button (which seems reasonable to remove when sorting, and when in place it has some UI issues as the confirm overlaps the sort number field).
Now looks like this:
=> Resolves #6374: Hide settings and delete option when re-ordering doc type properties

src/Umbraco.Web.UI.Client/src/less/components/overlays.less, src/Umbraco.Web.UI.Client/src/views/components/overlays/umb-overlay.html
This PR addresses issue **no. 157** from the #5277 
This PR adds some modification to the markup of the overlay markup in order to improve its accessibility - I have followed the guideline from https://bitsofco.de/accessible-modal-dialog/ for the markup pattern.
Once this is done there will still be some outstanding issues concerning the focus lock, which I'm still awaiting some feedback on in #4526 since using the suggested polyfill will handle much of the heavy listing for us very easily - Of course we should aim to make a generic directive or whatever makes sense so we can easily reuse it when dealing with different kinds of dialogs/overlays. But I've purposefully left this out of this scope until further discussion has been done in the referenced PR 😃 
What's been done
- Added …
=> Use aria attributes in dialog markup

src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs
Issue here seems to be that the delete operations weren't in the correct order with respect to tags, and a related table wasn't having it's content deleted.
Have fixed by re-ordering and updating the language delete clauses in language repositoy to ensure any tags for the language are deleted before the language itself is deleted.
Fixes #6269.
=> Fixes #6269: Can't delete language because of tags

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js, src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
If there's an existing issue for this PR then this fixes #5238
As described in #5238: When you edit the content type in infinite editing from content that has not yet been saved, everything kinda blows up:
This is a particularly annoying issue when constructing new content types.
When this PR is applied, things work as you would expect:
Make sure to test:
- Creating new content
- Editing existing content
- Editing the content type from newly created content
- Editing the content type from existing content
=> V8: Don't YSOD when editing content type from content that hasn't been saved yet

src/Umbraco.Web/Routing/RedirectTrackingComponent.cs
If there's an existing issue for this PR then this fixes #5050
RedirectTrackingComponent has to go to some effort to work properly with the order of events in V7. 
The order has changed in V8, and redirects are no longer created when a page is moved (because the Publishing event is no longer raised during a move).
The new event order allows the logic to be considerably simplified, recording the old routes in `Publishing` and `Moving`, then creating the redirects in `Published` and `Moved`.
Testing:
- Move a published node and confirm that redirect tracking records the change
- Rename a published node and confirm that redirect tracking records the change (just to check that it still works)
=> V8: Redirect tracking on move

src/Umbraco.Tests/Cache/RefresherTests.cs, src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Web/Cache/ContentCacheRefresher.cs, src/Umbraco.Web/Cache/DistributedCacheExtensions.cs, src/Umbraco.Web/Cache/MediaCacheRefresher.cs, src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
Fixes #2997 - ContentService returns outdated result
This fixes the issue when using ContentService.GetById(Guid) and MediaService.GetById(Guid), the cache for these methods is not refreshed with the cache refreshers since they are only evicting the cache by INT. 
This will need to be backported to 7.x
Testing:
Create a controller:
```cs
public class TestController : SurfaceController
{
public ActionResult GetContentByKey(System.Guid key)
{
var c1 = Services.ContentService.GetById(key);
var c2 = c1 == null ? null : Services.ContentService.GetById(c1.Id);
return Content(c1?.Name + " - " + c2?.Name);
}
public ActionResult GetMediaByKey(System.Guid key)
{
var m1 = Services.MediaService.GetById(key);
var m2 = m1 == null ? null : Services.MediaService.GetById(m1.Id);
return Content(m1?.Name + …
```
=> Fixes #2997 - ContentService returns outdated result

src/Umbraco.Core/ObjectResolution/ApplicationEventsResolver.cs, src/Umbraco.Tests/Resolvers/ApplicationEventsResolverTests.cs, src/Umbraco.Tests/Resolvers/LazyManyObjectResolverTests.cs, src/Umbraco.Tests/Umbraco.Tests.csproj
Fixes ApplicationEventHandler default weight of -100 not set on Umbraco.Web ApplicationEventHandlers #6024
=> Fixes ApplicationEventHandler default weight of -100 not set on Umbraco.Web ApplicationEventHandlers #6024

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
I just noticed that the danish key for savevariant was missing.
=> adds missing language key

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/ConvertRelatedLinksToMultiUrlPicker.cs
- [X ] I have added steps to test this contribution in the description below
If there's an existing issue for this PR then this fixes: #5840 
During the migration from V7 to V8, the relatedLinks picker gets migrated, but fails if the relatedLinks value is null (No selected links). To reproduce, create content with a related links picker and dont pick any links. Then upgrade to V8.
When calling .Tostring() on the RelatedLinks picker during migration, it doesn't check for a null value before calling .Tostring(). The following line checks string.IsNullOrWhiteSpace(), so handles the migration correctly if we parse the value as null.
I have tested this on the website database which caused the original issue.
=> #5840 - RelatedLinks Migration check for null Value before .ToSting()

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
Spotted this one when testing out the new release candidate 😮 
Most other keys related to sorting has already been fixed, but apparently not this one.
=> Sorter -> Sortér

src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
I noticed that the "Save and publish > Publish with descendants" overlay was using `umb-checkbox` when using variants.
But not without any variants as now:
This is how it looks at the moment using a traditional checkbox, while it does use `umb-checkbox` when the document type vary by culture.
=> Add umb-checkbox for publish unpublished content items with no variants

src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
This PR change so `umb-checkbox` is used in loglevel selection in the dropdown.
At the moment the dropdown opens behind the search input. First thing I think we need to change here is that the view only use a single `<umb-editor-sub-header>` element in logviewer search.
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/logviewer/search.html#L20
as in this example https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/common/directives/components/editor/subheader/umbeditorsubheadersection.directive.js#L15-L41
but we can look at this in another PR.
=> Use umb-checkbox for loglevel selection

src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
The four descriptions were missing a period at the end. This PR adds that both for `en.xml` and `en_us.xml`:
=> Added punctuation

src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
In log viewer search the layout was a bit messy and the loglevel dropdown was behind the search input.
Furthermore it looked a bit annoying that each time a loglevel from the dropdown was selected it pushed the dropdown because of the label text change.
We can adjust this further, but this is much better than the current behaviour.
=> Adjust log viewer search layout

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
Added timeout for init, cause rendering is not always complete if not. Ugly solution, but we had this before, and we tried without, but not working everywhere.
=> Fix initialization problem with TinyMCE 4

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less, src/Umbraco.Web.UI.Client/src/less/rte.less
Fixing visual issues with RTE in the Grid.
- Toolbar got solid background, fixing the see-through problem.
- RTE is dynamic width in grid, not limited.
- Toolbar width is corrected both when sticky and non-sticky.
=> fixing toolbar issues when sticky and RTE width in grid.

src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
This PR fixes the issue where the expandedPaths array grows out of control (adding duplicate paths)   [#5484 ](https://github.com/umbraco/Umbraco-CMS/issues/5484)
=> Fix for #5484 - V8 : Back office freeze when opening multiple content nodes

src/Umbraco.Web.UI.Client/src/common/directives/components/umbimagelazyload.directive.js, src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
If there's an existing issue for this PR then this fixes #6389
⚠️ Huge GIFs ahead ⚠️ 
This PR adds lazy loading to the thumbnails in the media grid as explained in #6389. 
With this PR applied, media thumbnails only load when they're scrolled into view; until then it simply shows the transparent background.
Here's a GIF of this PR in action when working with the media library:
...and here's when using the media picker:
=> V8: Lazy load thumbnails in the media grid

src/Umbraco.Web/Editors/BackOfficeController.cs, src/Umbraco.Web/Install/Controllers/InstallController.cs, src/Umbraco.Web/Mvc/StatusCodeFilterAttribute.cs, src/Umbraco.Web/Umbraco.Web.csproj
Fixes #6334 Return 503 status code when in upgrade mode
* Log out of umbraco
* Change the web.config umbraco version to 8.2.0 (since dev/v8 is 8.3.0) , this will force umbraco installer to execute
* Open chrome dev tools and view network tab
* run Umbraco, notice that requests for AuthorizeUpgrade endpoint returns 503 status and that there are no JS errors
* log in and it will redirect to the installer, see that it returns 503 for the Installer endpoint, ensure no JS errors and click through to upgrade
🎉
=> Fixes Return 503 status code when in upgrade mode #6334

src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js, src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js, src/Umbraco.Web.UI.Client/src/init.js
Fixes: #6127
The term "soft redirect" is used for content and blueprints which means that when we create a content item, the URL might be something like 
/content/content/edit/1234?create=true 
and then when the create/save button is pressed, we navigate to it's real URL now that it has an ID, like:
/content/content/edit/9999
In v7, we would actually allow for angular to do a full route and reload the currently edited page. This isn't ideal since you lose state, etc... so in v8 we do a 'soft redirect', meaning the URL changes but the route doesn't actually execute and we don't lose the current editor state.
The way this was done was fairly ugly and had specific checks for the 'create' URL (as above) and the destination URL (as above) and would allow or not allow the route to execute. This …
=> Fixes V8: Can't navigate to another node when the editor is in "create" state #6127

src/ApiDocs/umbracotemplate/styles/main.css
The current API documentation on Our has not been updated to fit the new Umbraco identity. This change will change this:
Into this:
The easiest way to test is to navigate to the .\src\ApiDocs folder and run this command:
`C:\Umbraco\UmbracoRepos\v8Hackathon\build\temp\docfx.console.2.45.1\tools\docfx.exe build --serve` it will build the DocFX site and run it on localhost:8080 for quick and easy testing 🙂
=> Update styles of API docs to match new identity

src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
As confirmed by @nul800sebastiaan and @rasmusjp, the `<umb-overlay />` directive should be marked as deprecated as the newer `editorService` should be used instead.
=> Marking the umb-overlay directive as deprecated

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5674
Enables name editing and footer buttons when in the list view app
=> Allow editing name and saving on on list views

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less, src/Umbraco.Web.UI.Client/src/less/rte.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js, src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs, src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
This is sort of a regression from 8.1 where when we updated the media references within the RTE, the values would be persisted with UDI references and without the actual media paths.
Unfortunately the code for the Grid's RTE's was not updated so this never took place for the Grid.
The images stored in the DB should look something like this within the html:
```html
```
But for the grid rte it would still maintain the path:
```html
```
When the RTE is re-rendered in the back office, the `src` attribute is then re-updated with the correct media path. This was also not happening in the Grid's RTE.
This PR fixes this issue so now the RTE and the Grid RTE behave the same way.
You can test this by:
Inserting an image into a normal RTE and save/publish, go check your DB:
```sql
SELECT TOP (1000) …
```
=> Fixes the media refs within the RTE in the Grid

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
_Fix for incorrect PR base branch: https://github.com/umbraco/Umbraco-CMS/pull/6552_
-----
Try and support images in the RTE that are pasted/dragged in and are NOT in media yet to be able to update the ALT text
**Not all changes in the DIFF are mine,** its because I had to re-target the PR against `v8/8.2-rc` where I was working in `v8/8.2`
* Drag image into RTE (do not save the page/node)
* Click media/image button
* Add some ALT text
* Verify alt text is in code with View Source Code button in RTE
* Ammend alt text again & verify it's updated (be new text or removing it)
* Insert a brand new RTE image
* Ensure width is resized correctly
* Use img button to update/edit ALT text
* Use img button to choose brand new media item (This is kinda weird you can do)
* Verify new width/dimensions …
=> Allow pasted & dragged images that are not yet saved to allow ALT text to be edited 

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediafolderpicker.controller.js
We only want to allow you to pick one folder in the media library for the MediaFolderPicker prevalue editor
A super simple change in passing the options to the underlying MediaPicker component to not `allowMultiple`
Fixes [AB#2996](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2996)
Fixes https://github.com/umbraco/Umbraco-CMS/issues/6513
=> Only allow one media folder to be picked for RTE paste/drag image upload location

src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
Fixes null reference caused in GridPropertyValueEditor when the value is empty.
This can occur when the value stored for the grid is an empty string, in which case we were not checking for that scenario and a null ref exception was thrown.
---
_This item has been added to our backlog [AB#2972](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2972)_
=> Fixes null reference caused in GridPropertyValueEditor when the value is empty

src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
Just a minor change to the PR https://github.com/umbraco/Umbraco-CMS/pull/6493 from @Shazwazza where it don't need to read grid configuration if editor the json string is empty or whitespace.
=> Check if value is null or whitespace before reading grid configuration

src/Umbraco.Web/Models/Mapping/MemberMapDefinition.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6614
Member group nodes was not highlighted because an incorrect path in member group mapping.
The path was missing a comma, so instead of `syncTree` in `navigationService` was using `path: "-1,1159"` it was using  `path: "-11159"`.
=> Fix incorrect path in member group mapping

src/Umbraco.Tests/Integration/ContentEventsTests.cs, src/Umbraco.Tests/Services/ContentServiceTests.cs
When you build the core project you get warnings about needing to pass in the userId to the EmptyRecycleBin method as the method without userId in it is obsolete and marked as so.
There are some tests which use this method without passing the user in. If we update these then the messages will go away.
This PR updates them and therefore fixes the issue #6622
=> - updated usage of EmptyRecycleBin to pass in the user id as instructed

src/Umbraco.Examine/IUmbracoIndexConfig.cs, src/Umbraco.Examine/Umbraco.Examine.csproj, src/Umbraco.Examine/UmbracoIndexConfig.cs, src/Umbraco.Examine/UmbracoUmbracoIndexConfig.cs, src/Umbraco.Web/Search/ExamineComposer.cs, src/Umbraco.Web/Search/UmbracoIndexesCreator.cs
I notice IndexCreator actually has 2 responsibilities, which in my opinion is not the best way of doing that and I think it should be separate as in that case it looks weird: 
I want override index config I have to override whole umbracoindexcreator.
And here I have an additional case which could be useful:
I am preparing the package which creates elasticsearch indexes and second developer @callumbwhyte  have a package which wants override config in examine and actually we are hitting here wall if we want install both packages as both cases overriding umbracoindexcreator. 
In a way what I am proposing we could have both packages without stress about the ordering of components and handling differently situation depends on installed packages.
=> V8: Split IndexCreator and Index config methods

build/NuSpecs/UmbracoCms.nuspec, src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6495
This PR removes the `Microsoft.Net.Compilers` dependency from both the `Umbraco.Web.UI` project and `UmbracoCms` NuGet package, as it's not required (the required version of Visual Studio 2017 v15.9 for local development already ships with the same compiler version).
All code should still build after this change, assuming the build environment also satifies the [local development requirements](https://our.umbraco.com/Documentation/Getting-Started/Setup/Requirements/#local-development).
=> Removed Microsoft.Net.Compilers dependency

src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html
=>  add aria markup to umb-toggle so it behaves like the checkbox it is

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js, src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html, src/Umbraco.Web.UI.Client/src/views/prevalueeditors/boolean.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html
The Boolean editor (aka. TrueFalse, aka. Checkbox 🤔) using the `<umb-toggle>` directive (for both prevalue-editor and property-editor), isn't associated with the property's `<label>`.
Meaning that if a user clicks on the property label, nothing happens.  Previous with the old checkbox (e.g. native HTML input), this would check/uncheck the input.
By adding an `id` attribute, with the property's alias (e.g. `id="{{model.alias}}"`), it will be associated with the toggle control.
In terms of testing, it'd be a case of clicking the label, and see the toggle state change.
=> Boolean editors - adds ID attribute to umbToggle

src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
As-is you can pick the allowed types when configuring MNTP as a media picker. However, the picker doesn't respect the allowed types filtering like it does when configured as a content picker. This was uncovered while working on #5983 (see also [this comment](https://github.com/umbraco/Umbraco-CMS/pull/6177#issuecomment-531805007) on the PR fixing #5983)
This PR implements the filtering; when it's applied here's how the MNTP works in media picker mode:
...and it also works when you browse around the media library in the picker 😄 
To test this:
1. Create a new media type (easiest to clone the default "media" one)
2. Create media of multiple types
3. Configure MNTP as a media picker and only allow one of the media types
4. Verify that the MNTP only lets you pick media of the allowed type
5. …
=> V8; Support allowed types for MNTP media picker

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js, src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
Mandatory properties of types Upload and Image Cropper currently aren't validated clientside - only serverside:
This PR adds mandatory validation clientside as well:
=> V8: Make upload and image cropper mandatory validation work clientside

src/Umbraco.Web.UI.Client/src/less/components/application/umb-language-picker.less, src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html, src/Umbraco.Web.UI/Umbraco/config/lang/da.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
In this PR I have done the following
- Changed `<div>` and `<a>` to `<button>` to fix keyboard navigation and semantics
- Adjusted the styling so the buttons are styled correctly
- Added the `aria-haspopup` and `aria-expanded` attributes
- Added visual hidden texts for providing better non-visual context so a screen reader announces "Current language: English (United States)" instead of just "English (United States)" for instance
- Added the deep-blur directive in order to have the dropdown disappear when it looses tab-focus
The visual changes from before and after can be seen below
**Before**
**After**
I look forward to receive any feedback you might have for this 👍
=> Refactor language picker to improve accessibility

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/profiler.html
This PR just adjust the layout of the profiler dashboard a bit so the label also trigger the toggle, add a loading indicator and a few other minor changes in layout.
**Before**
**After**
=> Adjust layout in profiler dashboard

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/copy/copy.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/copy/copy.html
This PR replaces the traditional checkbox with `umb-checkbox` for "relate to original" in copy infinite editor.
=> Replace checkbox with umb-checkbox for relate to original

src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs, src/Umbraco.Core/Services/Implement/ContentService.cs
If there's an existing issue for this PR then this fixes #5919
`DocumentRepository.PerformDeleteVersion` deletes from tables in the wrong order, leading to foreign key violations.
Also, it checks that it is not deleting the current version, but does not check whether it is deleting the published version.
Create the following controller:
```c#
public class TestController : SurfaceController
{
public ActionResult ListVersions(int contentId)
{
return Content(String.Join("\n",
Services.ContentService.GetVersions(contentId).Select(v => String.Join("\t", v.VersionId, v.UpdateDate, v.VersionId == v.PublishedVersionId))),
"text/plain");
}
public ActionResult DeleteVersion(int versionId)
{
var v = Services.ContentService.GetVersion(versionId);
Services.ContentService.DeleteVersion(v.Id, versionId, …
```
=> Fix ContentService.DeleteVersions

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
If there's an existing issue for this PR then this fixes #6476 
Change replaces `n.indexOf()` with `n.search()` to better manage casing, whitespace, punctuation, attribute order etc.
Verify by dragging an image into an rte, save and publish, image should now be in the media section. Confirm too that the image src in the rte is updated to the correct media asset path.
=> V8: use regex for finding images where src attribute is a blob

src/Umbraco.Web.UI.Client/src/less/components/overlays.less
Opening the help drawer when an overlay (linkpicker, profile etc) is already open causes stacking issues - the overlay is fixed to the right edge of the screen, so obscures the help drawer.
This change pushes the overlay 400px (drawer width) to create space for the drawer to display.
=> push overlay-right when opening help drawer

src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less, src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
If there's an existing issue for this PR then this fixes #5916 
On small screens, the content in the umb-node-preview directive gets all squished because the parent container is a flex element, but doesn't allow wrapping. This change adds flex-wrap:wrap, and updates the view to keep the icon and node name grouped, while allowing the actions (open, edit, remove) to wrap to a new line.
Large-ish screen is unchanged:
Small screen wraps like so (this is a super-small screen example):
Have verified this in nested content and the content picker editor.
=> V8: allow node preview content to wrap

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
As-is the media tree doesn't update when you add or remove media. This can be a tad confusing, because you can see the creation/deletion in the list view (grid view) but the same changes aren't reflected in the tree.
With this PR, the media tree updates whenever folder contents changes (added/removed media):
=> V8: Reload the media tree when folder contents changes

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
This PR enables direct access to the search results in Examine Management simply by clicking the result name. It works like this:
With the upcoming ability to search for GUIDs, this might also come in really handy for Cloud support handling.
It only works for well known entities - for now that's content, media and members.
Well.. no. Anyone having access to Examine Management can see the (raw) values of whatever is found when searching, and they can easily construct the URLs for editing the results by means of these values. 
When testing this PR, verify that you can open content, media and member search results by clicking their names. 
Also test that you can open search results in a new tab by Ctrl-clicking their names.
Lastly someone should probably test this using a "configured …
=> V8: Enable editing the search results directly from Examine Management

src/Umbraco.Web.UI.Client/src/init.js
In addition to #6456 if an `changeTitle` is now called with an empty value for `titlePrefix` the value in `originalTitle` removing the "-" prefix on  the title element
=> v8: Added a test for if an empty titlePrefix is passed into the $changeTitle

src/Umbraco.Web/PublishedContentExtensions.cs
This pull request solves bug #6564.
This adds a null check in the code which is checking for a valid alternate template.  Without this null check, if a node is unpublished the content finder classes (specifically ContentFinderByNiceUrlAndTemplate) will try to check for a valid template on a null node, and this will throw the exception seen in bug report #6564.
To test this, simply unpublish a page and try to access it using an alternate template syntax (for example, /about-us/contentpage on the sample site).  You should get a 404 not found page, not a 500 error page.
=> Add null check in allowed template check

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
Oh my. It's possible to delete property groups that contain locked properties, despite not being able to delete the individual properties:
It used to be so you couldn't delete the property group unless it was empty, but I guess somewhere along the line this was changed (which makes sense).
Anyway. If you go ahead and delete the locked properties on a member type, members of this type start failing miserably (as one might expect):
So... this PR removes the ability to delete a property group if it contains one or more locked properties:
1. Verify that you're not able to delete property groups with locked properties (i.e. on member types).
2. Verify that you're still able to delete property groups *without* locked properties (i.e. on document types).
=> V8: Don't allow deleting property groups with locked properties

src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
Non-sortable list view headers are already not clickable (i.e. clicking has no effect) but it's not obvious, as the default link "hand" cursor is shown.  This PR updates this for non-sortable headers to show the default "arrow" cursor.
Raised in #6477.
=> Updated list view headers styling to have the link/hand cursor visible only if the header is sortable

src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
It was raised in #6477 that the last edited field on the default members list view doesn't allow sorting.
This PR adds that ability, along with two other system fields that developers are able to add to the list view - the created date, and the content type alias.
Also fixes a minor issue that when adding the content type alias as a header on the member list view, it was displaying the localised text of "media type" instead of "member type".
=> Allows members to be ordered by additional system fields

src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
As an unintended side effect of #6538, preceding colons have appeared in the language selector:
The colons are intended for screen readers, so this PR moves these colons inside the `sr-only` block, and thus the language selector looks normal again:
=> V8: Move misplaced colon in language selector

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
When publishing includes unpublished descendants, the content tree doesn't reflect the changes in published status for the descendants:
This PR ensures that the children of the current node are reloaded in the content tree when publishing with unpublished descendants:
=> V8: Reload node children after publishing with descendants

src/Umbraco.Web.UI.Client/src/views/macros/views/macro.settings.controller.js, src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
If there's an existing issue for this PR then this fixes #6590
When picking a partial view in a macro's settings, the picker returns the filename URL-encoded. Any spaces are left encoded as +, and we store `~/Views/MacroPartials/Name+with+spaces.cshtml`. Then when trying to render the macro, the file can't be found.
Testing:
- Create a macro partial view with spaces in the name.
- Create a macro and pick that partial view.
- The filename should be displayed with spaces, not +.
=> Correct URL decoding of macro partial view names

src/Umbraco.Web.UI.Client/src/views/content/delete.html, src/Umbraco.Web.UI.Client/src/views/media/delete.html, src/Umbraco.Web/Trees/TreeControllerBase.cs
When deleting content from the recycle bin, the warning message is the same as when you move content to the recycle bin - and it makes no sense in the context of deleting content from the recycle bin:
With this PR, the warning makes a little more sense when deleting content:
...and the same applies to media:
And as an added bonus, the confirmation button is now red when moving media to the recycle bin (it is currently green):
=> V8: Add irreversible warning when deleting items from the recycle bin

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js, src/Umbraco.Web.UI.Client/src/less/hacks.less, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html, src/Umbraco.Web.UI.Client/src/views/content/protect.html
This PR replace the traditional radiobuttons in the public access overlay using `umb-radiobutton` component. I have also adjusted the layout a bit and the `umbRadiobutton` component has the `inputId` property similar to `umbCheckbox`.
=> Use umb-radiobutton in public access overlay

src/Umbraco.Web.UI.Client/src/less/components/umb-date-time-picker.less
When using the datepicker, today is not highlighted which makes for a poor user experience, as raised in this issue #6618 
I was expecting to see today's date highlighted somehow, perhaps like this:
There is a style for the border colour of the element with the `today` class on it, but there is no border set.
This PR fixes the issue
=> - set the border for the today class on the date picker

src/Umbraco.Core/Mapping/UmbracoMapper.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6425 by incorporating the comment from https://github.com/umbraco/Umbraco-CMS/pull/6426#pullrequestreview-296840812.
The updated code in this PR makes sure the `ConcurrentDictionary<Type, Dictionary<Type, Func<object, MapperContext, object>>>` is accessed in a thread-safe manner and doesn't retrieve unnecessary values from the inner dictionary.
=> Fixed adding/updating UmbracoMapper constructors

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
=> Documenttypes correctly spelled in danish is one word.

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
I keep getting annoyed with how the system save dialog appears whenever I hit Ctrl+S in the RTE:
Turns out there is an easy fix that makes Ctrl+S save the current content instead, just like it should. So this PR implements just that:
While it would be just as easy to handle the shortcut for publishing (Ctrl+P), I have opted not to do it. The editors might hit the shortcut by accident and trigger an unwanted publish of the entire page. 
Of course the editors could just as easily hit the shortcut for save by accident and trigger an unwanted save, but that's nowhere near as problematic. And I do believe the advantage of having a functional shortcut outweighs this potential problem.
=> V8: Handle save keyboard shortcut from within the RTE

src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorswatches.directive.js, src/Umbraco.Web.UI.Client/src/views/components/umb-color-swatches.html
If there's an existing issue for this PR then this fixes #6740
This PR makes it possible to configure the prefix applied to the class name for each color option in the color swatch directive.
The prefix is defined by supplying `color-class-name-prefix="my-prefix"` in the directive. If none is supplied, the directive performs a fallback to "btn" to ensure backwards compatibility.
First and foremost check that the color swatch performs the expected fallback - for example by opening the icon picker for a doctype. If it still looks really colorful, the fallback works.
Now testing it with a customized prefix isn't straightforward. What I did was to edit the color swatch used in the icon picker:
...which caused it to look like this:
Success! It's colorless 😆
=> V8: Make the color class prefix configurable for <umb-color-swatches/>

src/Umbraco.Web.UI.Client/src/less/components/umb-checkbox-list.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
I have attempted a little clean up of the compositions dialog, introducing a bit of margin below the grey line(look at the spacing between the grey line and "Compositions" and removing some inline styles. 
**Before**
**After**
=> Clean up of the compositions dialog

src/Umbraco.Web.UI.Client/src/common/directives/components/html/umbbox/umbboxheader.directive.js, src/Umbraco.Web.UI.Client/src/views/components/html/umb-box/umb-box-header.html
When using the umb-box-header directive you can set a title attribute and a title-key attribute. When both are filled both values are shown. I would expect the value of the localized title-key to be shown when filled. And the title property only when the title-key is not provided or can not be localized.
Same goes for description and description-key
Copy and paste the following code above the umb-box-content directive in /src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html file. 
```
<umb-box-header 
title="Start here" 
title-key="general_add" 
description="Non localized description" 
description-key="general_delete">
</umb-box-header>
```
Build the front end run your umbraco site. If login and go to the settings section you will see the following in the …
=> V8 - umb-box-header shows values for non-localized and localized title and description

build/NuSpecs/tools/Web.config.install.xdt
Noticed that the assembly name in the xdt file still was `umbraco` but that assembly doesn't exist anymore and the module is now located in Umbraco.Web`.
It's not causing any problems which I guess is because it's being replaced somewhere else in the powershell install scripts
=> Fix wrong assembly name for UmbracoModule

src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs, src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
Adds additional null conditionals to the FromEditor method as this method is sometimes executed for front end rendering and in that scenario CurrentUser is null, this throws an exception.
See the Doc Type Grid Editor issue for details of when this issue occurs https://github.com/skttl/umbraco-doc-type-grid-editor/issues/159
=> Add additional null conditionals to the FromEditor method of RichTextPropertyValueEditor

src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Rte.cshtml
Ensures the RTE partial used by the grid, passes its value through the TemplateUtilities to resolve images and urls before rendering out the value.
=> fixes images not showing up when rendering rte from the grid.

src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
A new user can't be created without at least one group assignment. But there is no clientside validation of this, only serverside validation. And there is no meaningful feedback of what went wrong when user creation fails because of missing group assignments:
This PR adds clientside validation to the user group assignment, just as there is clientside validation for the user name and email:
=> V8: Add validation to user groups when creating new users

src/Umbraco.Core/MainDom.cs, src/Umbraco.Core/Models/UserExtensions.cs, src/Umbraco.Core/Persistence/Repositories/Implement/RedirectUrlRepository.cs, src/Umbraco.Core/StringExtensions.cs, src/Umbraco.Web/Editors/UsersController.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6620.
These are all the changes needed to remove the obsoleted `ToMd5()` and `ToSHA1()` internal methods and replace them with a generic `GenerateHash()` method that accepts a hash type (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.create#System_Security_Cryptography_HashAlgorithm_Create_System_String_). See the comments on PR https://github.com/umbraco/Umbraco-CMS/pull/6621.
I've kept the `GenerateHash()` method internal, but maybe this can also be publicly exposed, so everyone can easily create hashes from strings?
=> Allow hash type on GenerateHash and remove obsoleted ToMd5 and ToSHA1 methods

src/Umbraco.Core/Models/ContentEditing/ContentApp.cs, src/Umbraco.Core/Models/ContentEditing/ContentAppBadge.cs, src/Umbraco.Core/Models/ContentEditing/ContentAppBadgeType.cs, src/Umbraco.Core/Umbraco.Core.csproj
In this [PR](https://github.com/umbraco/Umbraco-CMS/pull/3426)  @kjac introduced the option of adding badges to content app icons.
At the moment this is only possible by setting it in the angular controller of the content app.
When you register a content app through a [content app factory](https://our.umbraco.com/documentation/Extending/Content-Apps/#creating-a-content-app-in-c). If you register a content app you can already set the viewmodel from the factory. So it makes sense that you can set the badge as well.
This PR enables you do that.
Copy the code from this [folder](https://github.com/dawoe/umbraco-content-apps-in-depth/tree/master/example-04) in to your umbraco website.
Run the website and make sure the app is visible on a content item (need to be in admin role)
Change the code …
=> V8 - Make it possible to set content app badge through content app factory

src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.controller.js
If there's an existing issue for this PR then this fixes #6711 
This fixes the linked issue.
Before this PR the macro tree would not be reloaded after creating a macro by adding a macro partial view. You were forced to reload the macro tree to see the new macro
To test.
Go in to the backoffice and then to the settings section. Create a new marco by creating a partial macro view. The macro tree should be reloaded after you saved the macro and your newly created macro is immediatly visible. 
I needed to add a fake path to the syncTree method to make the tree reload. Only specifying the root node would not trigger the reload.
Dave
=> 6671 - reload macro tree after creating macro partial view

src/Umbraco.Web.UI.Client/src/less/rte.less
If there's an existing issue for this PR then this fixes #6701
The recent RTE styling updates unfortunately broke the full screen mode:
This PR fixes it - when applied, RTE full screen mode works like it did in 8.1.5:
=> V8: Fix RTE full screen mode

src/Umbraco.Web.UI.Client/src/views/packages/views/created.controller.js
I have changed the button style to be `danger`
**Before**
**After**
=> Style delete package overlay button

src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
The aliases of inherited and locked properties ought to be dimmed down with a "not allowed" hover cursor, but they aren't (you can't see the cursor from these screenshots though):
This PR updates the styling, so it's evident you can't mess around with the aliases of these properties (again... you can't see the hover cursor, but it's supposed to be "not allowed").
=> Dim down the alias of locked/inherited properties

build/NuSpecs/tools/ReadmeUpgrade.txt, src/Umbraco.Web.UI.Client/src/views/logviewer/search.html, src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html, src/Umbraco.Web.UI/Umbraco/config/lang/nb.xml, src/Umbraco.Web.UI/Umbraco/config/lang/zh_tw.xml, src/Umbraco.Web.UI/web.Template.config, src/Umbraco.Web/Editors/DashboardController.cs
I feel cheap for doing this, but it had to be done!
I've cleaned up the last remaining references to the legacy `our.umbraco.org` links in the source code, and updated them to the new `our.umbraco.com` domain.
I went a little nuts and did this for all the other repos too 🙈(sorry)
* https://github.com/umbraco/OurUmbraco/pull/491
* https://github.com/umbraco/UmbracoDocs/pull/1991
=> Updating references to our.umbraco.org

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
When you tab around the content type editor, the active state for the "edit" and "delete" icons for properties is *very* subtle:
This PR adds outlines to these icons, in line with the other elements in the content editor - specially the group "delete" icon:
=> V8: Make the active state clearly visible for property "edit" and "delete" icons

src/Umbraco.Web.UI.Client/src/less/sections.less, src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
On small screens, the rightmost sections in the top menu are collapsed into a tray. While keyboard navigation *does* work as-is, it's a bit confusing and also styling wise not in line with the top menu. Notice in the GIF below how the tray dots `...` aren't highlighted even though they have input focus.
This PR fixes that. It also updates the focused-state style for the menu items in the tray, so they look like the rest of menu items in the top menu when focused:
=> V8: Fix keyboard through the sections tray on small screens

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesourcetypepicker.controller.js, src/Umbraco.Web/Trees/ContentTypeTreeController.cs
The "Allowed items" picker does not impose any limitations when configuring the MNTP. In fact it allows you to select container nodes (folders), even though that makes no sense whatsoever and also leads to an error:
This PR imposes the following restrictions on the "Allowed items" picker:
1. Do not pick containers (folders).
2. Do not pick element types (specifically for content).
3. Do not pick any item that has already been picked.
It all comes together like this:
=> V8: Filter out invalid selections in the MNTP "Allowed items" picker

src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
#6481 seems to have introduced an unfortunate bug: You can no assign users and sections to groups:
This PR fixes it; here are the same operations with this PR applied:
=> V8: Fix section and user assignment to groups

src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
You can't remove the assigned user groups directly when editing a user; the workaround is to select "Add" and then deselect the groups you want removed:
By the looks of the code, there's supposed to be a "Remove" option per group - it just hasn't been enabled. So... this PR enables that:
=> Show the "remove" action for assigned user groups when editing users

src/Umbraco.Web.UI.Client/src/views/content/content.sort.controller.js, src/Umbraco.Web.UI.Client/src/views/media/media.sort.controller.js
If there's an existing issue for this PR then this fixes #6682
See #6682 for a detailed description; the gist of it is as follows:
When an editor has a start node defined, she can't sort the immediate children of that start node despite having permissions to do so:
Same problem exists in the media library, although the error is less gracefully handled: The editor appears to simply be logged out (although she really isn't, it just looks like it):
It all boils down to a faulty perception of which node is the "parent node" for the sorting operation. The JS incorrectly assumes it's the parent node of the start node, when in reality it is the start node itself. This PR corrects that assumption.
When this PR is applied, sorting works for start nodes in both the content and media sections:
=> V8: Fix sorting of the immediate children of editor start nodes

src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs
The member pickers (both the dedicated one and MNTP) do not show the correct member type icons for members of different types. 
In this case I have the members "Hello Mister" and "Hello to you too" of type "Test 1234" (so imaginative) which uses a different icon than the default one:
...yet in the member pickers, all members look the same:
Indeed had I changed the icon for the default member type, the pickers would still show the default icon because it is hard coded 😞 
This PR updates the mapping of the member entities so their member type icons are used in pickers:
=> V8: Use member type icon in member pickers

src/Umbraco.Web/Trees/MemberTreeController.cs
In the Users section we display the user groups with their respective group icons:
But in the Members section we do not; in fact the icon displayed gives next to no value other than to look consistent with the rest of the trees:
This PR ensures that we use the member type icon in the Members section:
=> V8: Use the member type icon in the Members section

src/Umbraco.Web.UI.Client/src/less/components/overlays.less
The header and footer of the `umb-overlay` dialog look rather out of place when the dialog is used in "slide-in-from-right" mode; I think they may be leftovers from V7.
Here's a V8 style dialog:
...and here are a few select samples of `umb-overlay`:
Notice:
- The height of the header and footer (and how they do not align nicely with the main window header and footer)
- The font size of the header
- The border color that separates the dialog content from the header and footer
- The background color of the footer
- The lack of padding in the top of the dialog content 
- The white border near the footer when the dialog has a scrollbar
This PR updates the styling of `umb-overlay` so it looks like a V8 dialog in "slide-in-from-right" mode:
The styling of `umb-overlay` when used e.g. for …
=> V8: Style the umb-overlay header and footer like the rest of the overlays

src/Umbraco.Web.UI.Client/src/common/directives/util/disabletabindex.directive.js, src/Umbraco.Web.UI.Client/src/common/services/tabbable.service.js
When creating content types using the keyboard (i.e. tab a lot), some of the property editors that use lazy loading can actually be interacted with - for example the RTE and Nested Content:
This PR ensures that we observe changes in the editors marked with the `disable-tabindex` directive and apply the tabindex disabling whenever these editors are done loading. Also the RTE `iframe` has been added explicitly to the whitelist of "tab-able elements".
Here's the same operation with this PR applied:
/cc @clausjensen, a.k.a. Sir Tabs-A-Lot 😆
=> V8: Lazy loaded properties can be interacted with when creating content types

src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
If you remove a custom property editor that's currently used by a property on a content type, the content editor handles this rather gracefully by simply displaying the raw property value instead of the missing property editor:
Nested Content... not so much 😆
This is particularly annoying when you're building custom editor experiences in different branches against the same database.
This PR makes Nested Content mimic the content editor handling for missing property editors:
Here's a simple custom property editor you can use for testing: [TestPropertyEditor.zip](https://github.com/umbraco/Umbraco-CMS/files/3745083/TestPropertyEditor.zip)
Steps:
1. Add the property editor to `App_Plugins`.
2. Create a Nested Content configuration with an element type that uses this property editor.
3. …
=> V8: Make Nested Content resilient to missing property editors

src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html, src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html, src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
The save/publish dialogs for multilingual content are a bit inconsistent when you have a mandatory language. In some dialogs an asterisk is displayed next to the language, in some the label "Mandatory language" is added - and some have both. 
On top of that, #5635 has the unintended side effect of pushing the asterisk down below the checkbox, leaving the variant status label somewhat floating.
Considering how the asterisk usually denotes "required" and that it's not necessarily required to tick the mandatory languages in these dialogs, I think we should simply remove them and add the "Mandatory language" everywhere instead. So this PR does just that:
=> V8: Harmonize content save/publish dialogs with mandatory languages

src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
In #5635 the language name was added to the checkbox label in the "Publish with descendants" dialog - which is awesome! Unfortunately the language wasn't removed from its previous location, leaving us with duplicate language labels:
This PR removes the duplicate, and fixes some invalid markup too:
=> V8: Remove duplicate language labels in publish with descendants dialog

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
I'll admit this can be hard to spot and I feel werid for doing this PR - But in this tiny PR I have adjusted the text in the umb-checkbox directive by 1 pixel since I noticed it was a bit off when I made PR #6835 
**Before**
**After**
=> umb-checkbox: Fix text alignment

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
I have changed the good ol' standard checkbox in the media pickers "Include subfolders in search" to use the umb-checkbox directive instead.
**Before**
**After**
=> Replace old checkbox markup with umb-checkbox

src/Umbraco.Web.UI.Client/src/common/directives/components/umbdatetimepicker.directive.js
When you have a datetime picker, I would expect it to submit its value on enter after you input the time. But it doesn't. You have to hit escape to close the datepicker (which incidentally does submit the value... that's arguable):
This PR ensures that the datetime picker submits its value when enter is pressed. It works like this:
=> V8: Datetime picker should submit its value on enter when entering time

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
The backoffice lets us delete inherited groups from content types. Fortunately the server doesn't actually delete the inherited groups, but still... the client shouldn't allow it in the first place:
Fortunately it's a simple fix. With this PR, inherited groups can't be deleted clientside:
=> V8: Do not allow deleting inherited content type groups

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
If you're prone to tabbing your way through the content type creation, it's a bit of a hassle picking the right datatype for properties. You have to tab twice for each datatype when you're moving through the list of datatypes; once to highlight the datatype - the outer `li` element - and once more to highlight the contained `a` element.
What's worse is if you hit enter when the inner `a` element is highlighted, the "new datatype" editor is displayed twice (it's only displayed once if you hit enter on the outer `li` though):
This PR fixes it all up so you can tab your way through the datatype picker like you'd expect:
=> V8: Remove "double tabbing" and duplicate editor for datatype picker

src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html
You can navigate tabs with the keyboard, but you can't open them 😢 ... which is particularly annoying when creating document types:
Added bonus: It also works for dashboard tabs:
=> V8: Make it possible to open tabs with the keyboard

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
Added Swedish translations for the prompt lang section.
Unsaved changes before translation:
Unsaved changes after translation:
Unpublished changes before translation:
Unpublished changes after translation:
=> Add Swedish translations for prompt

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js, src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
If you have multiple groups in the content type builder, the "add property" shortcut (alt+shift+p) only works for the last group:
This is because the shortcut is registered for every group and the last registration simply wins.
This PR moves the shortcut registration outside the property groups and adds logic to figure out which group is currently targeted the "add property" action. It works like this:
=> V8: Make "add property" shortcut work with multiple groups

src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
The number of elements you have to tab your way through in order to navigate down a tree is really quite excessive... and the most prominent looking one of those elements (the outermost node container) has no action attached, despite it looking like it would actually open the node for editing:
I have removed the tab index from a few of these elements to allow for speedier navigation through the tree, without compromising with the functionality at hand. Here's how it works:
=> V8: Limit the number of tabbable elements in tree nodes

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
The umb-radiobutton directive has been extended so it's possible to pass it a labelkey like it was recently added to the umb-checkbox directive in #5635, which will come in handy when it's needed to pass a dictionary item.
=> Extend the umb-radio button directive to handle localizations

src/Umbraco.Core/Services/PropertyValidationService.cs
If you remove custom property editors that are in use on one or more content types, content of these types will replace the missing property editor with a Label property editor that displays the raw property value. This works really well - until you attempt to publish the content:
This is particularly annoying when you're building custom editor experiences in different branches against the same database.
Turns out the validation routine doesn't expect the property editor to be missing... so this PR adds some defensive programming to counter this scenario. When applied, properties with missing property editors always pass validation, and thus things start working again:
Here's a simple custom property editor that can be used for testing: …
=> V8: Don't YSOD when publishing content if a property editor has been removed

src/Umbraco.Tests/Testing/TestingTests/MockTests.cs, src/Umbraco.Web/WebApi/UmbracoApiController.cs, src/Umbraco.Web/WebApi/UmbracoApiControllerBase.cs
From discussion on https://github.com/umbraco/Umbraco-CMS/issues/6578#issuecomment-541977675 it turned out that the UmbracoApiControllerBase used the ServiceLocator to resolve the UmbracoMapper (Current.Mapper) https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/WebApi/UmbracoApiControllerBase.cs#L62, which made it impossible to mock/fake (unless you mock the Current.Mapper, which you shouldn't).
This PR injects the UmbracoMapper in the constructor instead and adds a obsolete attribute on the old constructor, which is kept for backward compatibility. 
One tests has been added to verify that it is possible to mock the new constructor but also one that verifies that the old constructor can still resolve the Current.Mapper dependency, again for backward compatibility. …
=> UmbracoApiController Testable

src/Umbraco.Core/ObjectExtensions.cs, src/Umbraco.Core/Persistence/BulkDataReader.cs, src/Umbraco.Core/Xml/DynamicContext.cs, src/Umbraco.Tests/Composing/TypeHelperTests.cs, src/Umbraco.Web/Media/TypeDetector/SvgDetector.cs
The current .editorconfig file has the following line:
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.editorconfig#L20
```
dotnet_style_predefined_type_for_locals_parameters_members = true:error
```
But the codebase do not follow this guideline. This PR fixe this.
Also removes an unused variable - To remove all errors from resharper/rider.
To test this PR, of cause the automated test should pass and the solution should start. But the most important part is the review.
Before: 
After:
=> V8: Follow guidelines from .editorconfig

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewunpublish.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewunpublish.html
When you have a mandatory language, unpublishing content in that language will unpublish the content in all languages. 
The default unpublish dialog handles this by forcefully selecting and disabling all other language checkboxes if the mandatory languages is selected for unpublishing. But the listview unpublish dialog doesn't handle it at all:
This PR adds the same handling to the listview unpublish dialog:
See also #6854 with regards to the mandatory language styling in the dialog 😄
=> V8: Listview unpublish dialog should automatically select all languages

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/delete.html
_If it feels like deja-vu here, it's because #6600 is a lot along the same lines as this one..._
When you delete items from the recycle bin, the warning dialog is the same as is used when deleting items from any other listview. Among other things it tells you to unpublish languages (for culture variant content), which is meaningless in this context:
This PR adds a proper warning message to the delete dialog when it's used in context of the recycle bin:
...while retaining the warning when deleting (culture variant) content from other list views:
=> V8: Make the listview delete dialog warn about irreversible deletions

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
The listview doesn't allow for publishing and unpublishing items in the recycle bin. That makes perfect sense. Unfortunately this "trashed" state isn't propagated to list view enabled items within the recycle bin:
I have no idea what actually happens if you hit publish on a trashed item... I'm afraid to click it 🙈 - anyway, this PR fixes the problem:
=> V8: Apply trashed state to deleted content items with list view enabled

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
It makes no sense to copy items that currently resides in the recycle bin... but nevertheless it's allowed by the UI:
This PR ensures that the "Copy..." button is hidden from the listview when it displays the recycle bin:
1. Ensure that "Copy..." isn't available in the recycle bin.
2. Ensure that "Copy..." _is_ available in other list views (provided you're allowed to copy).
=> V8: Do not allow copying items in the recycle bin

src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
Implementing https://github.com/umbraco/Umbraco-CMS/issues/6507
Based on [Bjarne's PR for a confirm overlay](https://github.com/umbraco/Umbraco-CMS/pull/5487), this PR adds the `confirm` and `confirmDelete` methods to the Angular overlay service.
The `confirm` function has some default settings:
- Specify the HTML view from Bjarne's PR
- Set `closeButtonLabelKey` to `general_cancel`
- Set `submitButtonLabelKey` to `general_confirm`
- Add a default `close` callback which just closes the overlay
It looks like this:
The `confirmDelete` functions does what `confirm` does, but then also:
- Set `submitButtonStyle` to `danger`
- Set `submitButtonLabelKey` to `contentTypeEditor_yesDelete`
It looks like this:
I haven't updated the code in Bjarne's PR, but:
```js
const overlay = {
view: "confirm", …
```
=> Introduced confirm and confirmDelete functions in the Angular overlay service

src/Umbraco.Web.UI.Client/src/common/directives/components/tags/umbtagseditor.directive.js, src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/tags/tags.html
If there's an existing issue for this PR then this fixes #6605
Allows the Tags property editor to pass the property alias into umb-tags-editor, where it can be used as the ID of the text box to match the label's `for` attribute.
=> Set focus to Umb-Tags when clicking property label

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.html
If there's an existing issue for this PR then this fixes #6602
It feels like there should be a better solution for this, but this seems to work. 
Adds an invisible `input` before the main div to give something for the label to set focus on:
```html
<input type="text" id="{{model.alias}}" ng-focus="focus()" style="position:absolute;top:0;width:0;height:0;" />
```
In the controller, sets focus to the RTE whenever that `input` receives focus:
```javascript
$scope.focus = function () {
tinyMceEditor.focus();
}
```
=> Set focus to RTE when clicking property label 

src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Examine/Umbraco.Examine.csproj, src/Umbraco.Web.UI/Umbraco.Web.UI.csproj, src/Umbraco.Web/Umbraco.Web.csproj
After reading [this blogpost](https://stackoverflow.blog/2019/10/08/adding-static-code-analysis-to-stack-overflow/) and seeing how easy it is to add static code analysis to your code base, it seems like a no-brainer to add this to all Umbraco projects.
This PR adds the [SecurityCodeScan](https://security-code-scan.github.io) analyser and configures it to also include content files like `Web.config`.
When building the projects, additional warnings appear (open redirects, path traversal, weak random generator, etc.) that should be fixed in new PRs. Some will require writing additional guards/checks, others might be false positives and require the [appropriate configuration](https://security-code-scan.github.io/#Customtaintsource,sinks,sanitizersandvalidators).
=> Add SecurityCodeScan static code analyzer

src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
I have updated the Create Dialog on Relation Types to use `umb-radiobutton`. It is currently using `input type="radio"` at the moment
**Before**
**After**
=> Update the create dialog on Relation Types to use umb-radiobutton

src/Umbraco.Web/PropertyEditors/MultipleTextStringPropertyEditor.cs
As reported in #6648, a regular expression added for a multiple text string data type doesn't work (as it attempts to validate the JSON for the full set of text strings).
In this PR I've added a custom `FormatValidator` for this property editor, that will validate each string separately, and fail validation if at least one string doesn't match the configured regular expression.
=> Fixes #6648: MultipleTextstring validation failure

src/Umbraco.Web.UI.Client/test/config/karma.conf.js
Removed `'../Umbraco.Web.UI/Umbraco/js/*.security.js'` from `karma.conf.js` since no `umbraco.security.js` is generated in `gulp/config.js`.
`security: { files: ["./src/common/interceptors/**/*.js"], out: "umbraco.interceptors.js" }` outputs: `umbraco.interceptors.js`
=> Removed *.security.js from karma.conf.js

src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
This fix resolves #5644. Previously `assetsService.load` would not load any assets without an extension (the promise would never resolve).
Per @nul800sebastiaan's suggestion, this change adds an optional  `defaultAssetType` parameter that can be used to specify how to handle unknown assets. If `defaultAssetType` is omitted and an asset is missing an extension the method will throw (much better than dying quietly).
There are currently no unit tests for this service and I didn't have time to add any. To test this change I created another branch [v8/dev/feature/issue-5644-test](https://github.com/harry-gordon/Umbraco-CMS/tree/v8/feature/issue-5644-test) and added a small snippet to the start of `main.controller.js` that loads two dummy files (a script that prints to console and a CSS file …
=> Fix for #5644: assetsService.load now handles assets with no extension

src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
The delete saved searches overlay was not consistent with other delete overlays across the backoffice. I have made it in line with other delete overlays.
**Before**
**After**
=> Changes to delete saved searches overlay

src/Umbraco.Web.UI.Client/src/views/dictionary/delete.html
The delete button should use the `danger` style across the board. I noticed this while I was doing #6725 I dont know whether this is a good move, hence doing this as a separate PR. Will flow it across the board if this is okay.
**Before**
**After**
=> Change the confirm button style on delete dictionary item

src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
Noticed that on user group save or delete the notifications do not span the full width. I have fixed that.
**Before**
**After**
User group Save
User Group Delete
=> Notifications span full width on user group save or delete

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
The "Save" button in the Content Blueprint is "info" style at the moment. Trying to make is consistent with the other parts of the application by making it "primary" style. 
**Before**
After
=> Content Blueprint save button style change

src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.controller.js, src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
I have changed 3 things on the dashboard
- The "Disable" button has been changed to danger style (red bg colour)
- The Disable button on the confirm dialog changed to danger style
- There was duplicate `button-style` on the enable button which I have removed.
Notice the style change on the button on the dashboard and the confirm overlay below.
**Before**
**After**
=> Some changes to the Redirect Url Management dashboard

src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
On the Create Package form the "Include all child nodes" label is missing by Package Content section.
**Before**
**After**
=> Create package form missing "Include all child nodes" label by Package Content Content selector

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
If there's an existing issue for this PR then this fixes #6738
The History section of a document's Info tab converts times to the client's local time, but the "Rollback to" dropdown displays times in the server's timezone.
This PR converts the times in the dropdown to local times.
Testing:
- With a server in a different timezone from the client, compare the times displayed in the History section and the "Rollback to" dropdown. They should match, both in the client's local time.
=> Rollback dropdown - convert version dates to local

src/Umbraco.Core/Cache/CacheKeys.cs, src/Umbraco.Web/Cache/MacroCacheRefresher.cs, src/Umbraco.Web/Macros/MacroRenderer.cs
Rendering a macro always queries the database to get the macro details from the alias. This is true even if the macro result is already cached, since we need the macro's details to generate the correct cache key.
This PR adds caching of the `IMacro` results within `MacroRenderer`.
It may be safe to cache within MacroService.GetByAlias instead, but it seemed better to make MacroRenderer responsible for its own cache, with no risk of side effects for other code using MacroService.
=> Cache lookup of macro by alias

src/Umbraco.Web/Mvc/UmbracoVirtualNodeByUdiRouteHandler.cs, src/Umbraco.Web/Umbraco.Web.csproj
This is the same as [UmbracoVirtualNodeByIdRouteHandler ](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/Mvc/UmbracoVirtualNodeByIdRouteHandler.cs) except it expects a GuidUdi so code can reference the same node across Umbraco Cloud environments etc 
Tested with this example:
var routeGuid = new GuidUdi(Constants.UdiEntityType.Document, new Guid("e8ad9b65-cff6-4952-ac5b-efe56a60db62"));
RouteTable.Routes.MapUmbracoRoute(
"Product list by category",
"category/{customId}",
new
{
controller = "People",
action = "Index",
customId = UrlParameter.Optional,
page = 1
},
new UmbracoVirtualNodeByUdiRouteHandler(routeGuid));
=> Add UmbracoVirtualNodeByUdiRouteHandler

src/Umbraco.Web.UI.Client/src/less/components/overlays.less
There are a number of overlays in the backoffice which has a en extra padding on the header by the left.
Another example is "You have unsaved changes" overlay
I have fixed the padding so the header and the confirmation text align up.
=> Removed the extra padding on the left on the overlay header

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html, src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
I have done 2 things in this PR
1: I extended the umb-checkbox directive with a parameter called "cssClass" making it possible to pass override classes as needed
2: I changed the old checkbox to using the umb-checkbox directive passing css modifiers for making the text smaller and bold like it was using the old pattern
The "no-dirty-check" directive has been removed since the checkbox is a boolean so it should not really be necessary unless I misunderstand something 😅 
**Before**
**After**
=> Confirm uninstall package: Change old checkbox to use umb-checkbox

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
The documentation for the `documentTypeEditor` function in the editor service was missing the `id` and `create` properties, so I've added them as well as improved the surrounding text a bit.
<hr />
I haven't been able to build the documentation locally. The guide on how to do so mentions Grunt, which is no longer in use. There used to be a `docs` task for Grunt, but this also seems to be gone now. I was curious to see how the back ticks would look, and if they would brake anything.
P.S.: Shouldn't the `documentTypeEditor` function be marked as deprecated, and then replaced by a `contentTypeEditor` function instead?
=> Improved the editor service documentation a bit

src/Umbraco.Web.UI.Client/src/less/belle.less, src/Umbraco.Web.UI.Client/src/less/filter-toggle.less, src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
I have improved the filter dropdown, converting the `<a>` to `<button>` and adding appropiate aria attributes as well.
I have also added some empty `alt` attributes on the images rendering the favicons for different searches. This is done in order to let screen readers know they can safely ignore the image since the provided text is adequate in a non-visual context.
Furthermore I have modified some styling so the control aligns with the left edge and looks better in general.
There is more stuff to be done in this view but I'm going to split it all up in smaller PR's since doing one big file, would be confusing for everyone involved 😃 
**Before**
**After**
=> Log viewer: Filter toggle

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
I have replaced the old checkbox with the umb-checkbox directive - I have also temporarily added some inline styling to align the checkbox. But that's only until this PR is merged #6858
So before merging this PR please merge the other one and let me update this PR with a proper modifier CSS class 😉 
You might also wonder "Why not change the other checkboxes that are revealed when the new one is toggled?" - Well, that requires an extension to the umb-checkbox directive, which I'm having a think about these days to make it as flexible as we need it to be. Stay tuned 👀 
**Before**
**After**
=> Grid layout config: Replace the old checkbox with the umb-checbox directive

src/Umbraco.Web/Editors/ContentController.cs
Editors should always be able to delete the content they create - even if deletion is explicitly disallowed by means of group permissions assigned to a (parent) node. That's why the "Delete" action remains in the node menu. 
It just doesn't work, because this special exemption isn't honored when the delete action is executed:
This PR adds this special case handling to the action execution, and thus you're always able to delete the content you have created:
=> V7: Editors should always be allowed to delete their own content

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js
Seems _someone_ (ahem... me) made a tiny mistake when making upload and image cropper mandatory validation work clientside (#6527)... they can no longer be optional:
This PR fixes it right up.
1. Ensure that clientside mandatory validation works for image cropper and upload properties.
2. Ensure that non-mandatory properties of type image cropper and upload do not require uploaded files in order to save the content.
=> V8: Allow file upload and image cropper properties to be optional

src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes #6720 
This was previously fixed as #3022, but a further change is needed after 7.15's changes to the media tree.
Testing:
- In 7.15.x, open the media picker from an RTE and upload a new image.
- The image should be correctly inserted, rather than a reference to "nothing.jpg".
=> V7: Media uploader in RTE doesn't select uploaded image

src/Umbraco.Web/Compose/NotificationsComponent.cs
fixes #6464 
Changes the SendNotification Component to log a warning when the SiteUrl is null as opposed to throwing an error. 
If a content item is updated during startup of the site, then the SiteUrl will not be set, and while the item will be updated the calling method gets an exception returned because the notification failed. 
This PR logs a warning in the log file instead of throwing an argument exception, so the error doesn't give the impression of a failed update. 
This is the 'quick fix' pending a larger task to queue notifications (see https://github.com/umbraco/Umbraco-CMS/issues/6464#issuecomment-542981823)
=> Notification Component should log warning if siteUri is null. 

src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
When calling `navigationService.executeMenuAction`  dialog actions are not aware of the current node. To resolve this `appState.setMenuState("currentNode", node);` needs to be called so that dialogs are aware of this.
=> Sets the appState currentNode when executing a menu action (Fixes #5416)

src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
I noticed some color inconsistencies in the previewer-nav, and also a visible scrollbar in Firefox, so I fixed these.
Steps to reproduce:
Open the previewer
Check if the colors look like the after gif.
Before:
After:
=> Fixes preview-nav css

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgridselector.directive.js
This makes templates in `umb-grid-selector` (used in the doctype editor) open in an infinite editor instead of changing the url.
To test
Open a document type, go to templates. Click "Open" on one of the templates, notice the template opening in an infinite editor.
=> Opens templates from umb-grid-selector in infinite editor

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
If there's an existing issue for this PR then this fixes #6947
While I don't exactly pride myself of being any kind of a Grid expert, I do believe this PR fixes the issues concerning reordering grid rows containing RTE's (described in #6947).
With this PR applied at least I seem able to drag RTE's around without breaking things:
=> V8: Fix broken grid when reordering grid rows that contain RTE's

src/Umbraco.Web.UI.Client/test/unit/common/services/umb-request-helper.spec.js
Require Umbraco module for Umb-Request-Helper test, to make it work again.
=> Fix for Umb Request Helper unit test.

src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs, src/Umbraco.Web/Scheduling/HealthCheckNotifier.cs, src/Umbraco.Web/Scheduling/SchedulerComponent.cs
There is 2x issues fixed here:
Is it possible that the cache file is empty but the database is not? YES... (well, it used to be possible until this fix)
* A new file is created when one doesn't exist, this will only be done when `MainDom` is acquired
* The new file will be populated as soon as `LoadCachesOnStartup` is called
* If the appdomain is going down the moment after `MainDom` was acquired and we've created an empty cache file, then the MainDom release callback is triggered and executes on a different thread, which will close the file and set the cache file reference to `null`. At this moment, it is possible that the file is closed and the reference to the file set to `null` **before** `LoadCachesOnStartup` which would mean that the current appdomain would load in the in-mem cache …
=> Fixes a race condition with nucache

src/Umbraco.Web.UI.Client/src/less/belle.less, src/Umbraco.Web.UI.Client/src/less/components/contextdialogs/umb-dialog-datatype-delete.less, src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
Added specific styling to the DataType Delete dialog for better looks and a better overview.
So now it even looks fairly decent even with this datatype that is used a lot:
=> Styling for the DataType Delete Dialog

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
The loading banner continues to display when in the following sections:
- When the creating/editing users
- When the creating/editing user groups
- When the creating/editing languages
- When in the log viewer
The continually loading banner introduced in  #6315 and this PR removes it
=> Removes continually loading banner if there is no current editor state

src/Umbraco.Web.UI.Client/src/less/components/umb-panel-group.less, src/Umbraco.Web.UI.Client/src/less/dashboards/healthcheck.less, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html
Made the buttons on healthcheck dashboard made more consistent. I have also removed the `h3` heading.
**Before**
**After**
There was also a big space by the description which I have removed
**Before**
**After**
=> Buttons on the healthcheck dashboard made more consistent

src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
- [  + ] I have added steps to test this contribution in the description below
Relates to issue https://github.com/umbraco/Umbraco-CMS/issues/6410
Some of the cool Umbraco folk I know were chatting around the issue #6410 which is essentially is 'all about' adding to the Create Document Type options, a super fast way to create an Element Type, instead of having to create first a Document Type Without Template, and then remember to manually check the Is An Element Type checkbox on the permissions tab...
... why can't they just have a new option to do that on that menu ... speed up everyone's daily workflow...
... well there are concerns on how to present these options, in a way that doesn't confuse people new to Umbraco (what is a Document Type Collection anyway? etc)... which will involve …
=> Allow querystring parameters to set IsElementType checkbox on create document type route

src/Umbraco.Web/Install/InstallSteps/ConfigureMachineKey.cs
use Element to get the root system.web. DescendantsAndSelf can return multiple
Fixes : #6869 Installation of Machine Key fails if config has multiple system.web sections.
When the machine key is added to the config, the code looks for DecendantsOrSelf("system.web").Single - if the file has multiple system.web elements this will throw an exception and installation will fail. 
This PR changes the lookup from DecendantsOrSelf to xml.Root.Element which will only find the `System.Web` element in the root `<configuration>` node. 
-  NuGet Umbraco
- Add a extra system.web to the config 
e.g
```
<location path="some/path">
<system.web>
<httpRuntime maxRequestLength="512000" />
</system.web>
</location>
```
Install Umbraco, ask for a machine key - key will be created in the main `system.web` and …
=> look for the system.web section under the root configuration node

src/Umbraco.Core/Services/Implement/ContentService.cs, src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
At the moment we allow rollback of content in the recycle bin. While it sort of works, it makes very little sense. And you also really quickly end up with something like this:
So... This PR removes the rollback button from elements in the recycle bin, and also (as a precaution) denies rollback of trashed items serverside.
=> V8: Do not allow rollback of deleted content

src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/EditProfile.cshtml, src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Login.cshtml, src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/RegisterMember.cshtml
The `3.3.1` version that was being used has a [vulnerability](https://snyk.io/test/npm/jquery/3.3.1), so i have changed to the `3.4.1` version, even though many people may not use these snippets, the vulnerability can lead to ddos and more.
I tested all 3 on major browsers and they continued to work as expected, with the included validation etc.
I believe this is safe to do, as it wont affect peoples already established partials, with perhaps conflicting content, but only affect **new** partials created via the snippets?
=> Update JQuery CDN In snippets, to use newer version without vulnerability

src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js, src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml, src/Umbraco.Web/Editors/MediaController.cs, src/Umbraco.Web/Models/ContentEditing/MediaReferences.cs, src/Umbraco.Web/Umbraco.Web.csproj
This PR is for two tasks on the Azure Board
Fixes [AB#3608](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3608) - Implement the WebAPI method
Fixes [AB#3609](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3609) - Implement usage report on Info Content App
* This is targeting branch `v8/feature/media-tracking`
* Install SK (Makes life easier)~
* Visit one of the media items and ensure it displays the correct usages in Document/Content nodes
* Ensure the open links work & take you to the correct section/area
* Add a new property to `MemberType` that is a `Media Picker`
* Go and select an image on a member
* Check it shows up on the info tab as a relation
* Ensure the open link works & takes you back to the member …
=> AB3608 - Implement WebAPI & UI for displaying media relations/references

src/Umbraco.Core/Persistence/Repositories/IRelationRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs, src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs, src/Umbraco.Core/Services/IRelationService.cs, src/Umbraco.Core/Services/Implement/RelationService.cs, src/Umbraco.Tests/Services/RelationServiceTests.cs
Adds ability to bulk insert relations and adds tests. This is so we don't end up with an N+1 issue when saving content, media or members since we first clear auto-found relations and then re-add them. Before this, we would add a relation one at a time which is a perf problem, now we bulk insert them.
linked to [AB#3448](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3448)
=> Adds ability to bulk insert relations and adds tests

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
In the Grid Editor, when you hover over the trash icon there is no title which tells you what it is for, but there is one for the Confirm and for Cancel.
This PR adds the Delete title to the trash icon.
=> - added delete title to trash icons in the grid

src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-details.less, src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
The "Resend Invitation" button is a currently an `info` style button (grey). I think it should be an `action` style button as it is an action. It also brings it in line with the **Invite User** screen where the Send Invite button is `action` style. There was also a margin to the left of all the buttons in the sidebar on user details screen which were causing the buttons to shift a little. In addition, I have also introduced a bit of margin after the buttons and before the "Last Login" as it was appearing too close and squished.
Let me know if this is okay :-)
**Before**
**After**
=> Changed the styling of Resend Invitation button and fixed the margin

src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
Currently, in the Info content app on any node the "Open" template is an `<a>` . Changed it to a `<button>` so thats its more accessible.
=> Accessibility Improvement - Open Template in info content app changed from anchor tag to button

src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/RegisterMember.cshtml
The model variable name is registerModel rather than profileModel.
This change corrects the comment's example code.  There is nothing to test as this is just some commented out example code.
=> Corrected the model variable name

src/Umbraco.Web/Editors/MacrosController.cs, src/Umbraco.Web/Editors/TourController.cs, src/Umbraco.Web/Install/FilePermissionHelper.cs
In MB replacement, we have removed the MB plugin, and therefore the folder do not exists..
When having a new user, the tours fail without this fix.
- Do we need to handle this elsewhere?
- Should we have a dummy file to ensure the folder exists?
=> Only enumerate the app plugins folder if it exists

src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js, src/Umbraco.Web.UI/Umbraco/config/lang/da.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
@nielslyngsoe I didn't care much for the "Remove [property name]" label, as it sort of sounded like you'd actually remove the property itself. So I rephrased it to "Remove all items" instead.
Here's how it works 😄
=> Add "delete all items" confirmation and rephrase action link a bit

src/Umbraco.Core/Persistence/Repositories/IRelationRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/EntityRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs, src/Umbraco.Core/Services/IRelationService.cs, src/Umbraco.Core/Services/Implement/RelationService.cs, src/Umbraco.Tests/Services/RelationServiceTests.cs
Adds new `IRelationService.GetPagedByRelationTypeId` to be able to get paged relation by type + unit tests
links [AB#3466](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3466)
=> Adds ability to get paged relations by type

src/Umbraco.Web.UI/Umbraco/config/lang/it.xml
If there's an existing issue for this PR then this fixes: No issue has been created
The `Umbraco.Web.UI/Umbraco/Config/Lang/it.xml` file is broken at line 342, because a key element havnt been closed proper. This fixes it
=> Close unclosed key element in italian language file

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Only replace content if the active element is of type EmbedItem.
If a selection has been we will still be replacing the selection.
Test notes:
One document type with a Rich Text Editor property.
test A:
— Write some text, keep the pointer after the last character (do not make a new line) and then add an EmbedItem. See that text is still present.
test B: 
— Add an image, and then add a EmbedItem, see that Image is still present.
test C:
— Add an embed item, and then add another embed item.
test D:
— Add an embed item, and then select it, for then to be able to edit the EmbedItem by clicking the Embed-button. See the EmbedItem begin replaced with the updated one when you save the EmbedEdit changes.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/7147
---
_This item has been added to our …
=> Embed function in RTE removes previous content from RTE

src/Umbraco.Web.UI.Client/src/common/services/tabbable.service.js
This is a NEW PR for #7201 as this was worked/targeted against v8/dev aka 8.6.0 as opposed to 8.4.0, this PR is just the same commits cherry-picked and target against the correct branch for 8.4
=> Bugfix - AB3875 untouchability checker: do not check style for document fragments

src/Umbraco.Core/Collections/ConcurrentHashSet.cs, src/Umbraco.Core/RuntimeState.cs
`RuntimeState.EnsureApplicationUrl` uses a `HashSet<string>` to store previously-seen URLs, which is not thread-safe. It is possible to corrupt the HashSet in a way that causes calls to `Contains` to enter an infinite loop (I think it creates a loop in a linked list). Since `EnsureApplicationUrl` is called in `BeginRequest`, this breaks everything.
Since there is no `ConcurrentHashSet`, this PR uses a `ConcurrentDictionary<string, byte>`.
=> Thread safety in RuntimeState.EnsureApplicationUrl

src/Umbraco.Web/Editors/MacroRenderingController.cs, src/Umbraco.Web/IUmbracoComponentRenderer.cs, src/Umbraco.Web/UmbracoComponentRenderer.cs, src/Umbraco.Web/UmbracoHelper.cs
`UmbracoHelper.RenderMacro` always renders the macro as though in preview mode. Also, the results of macros rendered inside grid editors or RTEs are cached even though they're based on preview content. That cached result can then be shown when viewing the page.
`MacroRenderingController` explicitly requests the preview version of the content, which is correct since it's used by the editors. However, `UmbracoContext.InPreviewMode` is still false, so `MacroRenderer` will cache the result. Calling `UmbracoContext.ForcedPreview` fixes this.
`UmbracoComponentRenderer` also explicitly requests the preview version. This is necessary when being called from `MacroRenderingController`, but also affects `UmbracoHelper`.
UmbracoHelper:
- Create a doctype with a text string property `text` and an RTE. …
=> Unpublished content appearing in macro results

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.editor.html
If there's an existing issue for this PR then this fixes #7191
This PR adds asterisks to required properties within nested content, as discussed in #7191. Note that this PR does _not_ implement clientside validation of these properties.
It looks like this:
=> V8: Add indicators to required properties within nested content

src/Umbraco.Web/PropertyEditors/NestedContentConfiguration.cs
If there's an existing issue for this PR then this fixes #7218
This PR updates the descriptions (and one label) of the Nested Content configuration options, hopefully making them a bit clearer (and all in present tense)
These are the configuration options as-is:
And here are the configuration options with this PR applied. I have marked the changed ones:
=> V8: Update the descriptions of the Nested Content configuration options

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
The new Nested Content configuration doesn't work very gracefully on smaller screens:
Also there's really no need to invent new styling etc. for displaying an icon and a label, as we have the `umb-node-preview` for just that... so this PR cleans up the code a little bit and ensures we handle smaller screens gracefully:
=> V8: Fix Nested Content configuration overflow on smaller screens

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Minor JS fix, to avoid console error.
=> NC PropertyAction Delete-All, do not test length if value is null

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautoresize.directive.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/7247
Now you can see and edit the DocType Alias in Chrome.
=> adding timeout for Chrome to render before making the correction

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreeitem.directive.js
This fix ensures that the method 'getNodeCssClass' checks whether the given node and the activeNode have the same nodeType. aka. TreeAlias, that's at least what I could conclude. Quite some naming confusion.
This change only affects what nodes get the active class, so it should have a minor impact. But still important to test firmly if anything is broken by this change.
=> Checking nodeType on activeNode to ensure that nodes originate from same treeAlias

build/build.ps1, src/Umbraco.Web.UI.Client/gulp/config.js, src/Umbraco.Web.UI.Client/gulp/modes.js, src/Umbraco.Web.UI.Client/gulp/util/processLess.js, src/Umbraco.Web.UI.Client/gulpfile.js
Only compile CSS sourcemaps when running dev mode.
---
_This item has been added to our backlog [AB#4085](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4085)_
=> Basic setup for differentiating compile modes in gulp

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.component.js
After #7222, Nested Content no longer saves of the item content 😲 only when you copy and paste items is the content saved:
Specifically the refactoring in 503fd188 seems to be the culprit. Basically what happens is the controller wipes its "current node" from state before attempting to sync back the item content into the very same "current node".
This PR fixes things up:
When testing this PR, make sure that all Nested Content operations save back the item content to the correct item - in particular:
1. Create new items with and without collapsing previously edited items
2. Edit existing items with and without collapsing previously edited items
3. Reorder items without collapsing previously edited items
4. Delete items with and without collapsing previously edited items
5. Copy and paste …
=> Make Nested Content actually save the item content again

src/Umbraco.Core/Composing/Composers.cs, src/Umbraco.Core/Composing/TypeLoader.cs, src/Umbraco.Core/Runtime/CoreRuntime.cs, src/Umbraco.Tests/Components/ComponentTests.cs, src/Umbraco.Tests/Runtimes/StandaloneTests.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6624.
The changes in this PR makes sure all `EnableComposer` and `DisableComposer` attributes are loaded from all assemblies and not only those containing `IComposer`s.
I've done what @zpqrtbnk suggested first (https://github.com/umbraco/Umbraco-CMS/issues/6624#issuecomment-539911444): passing all assemblies in the `Composers` constructor. This made testing a lot harder and didn't feel right, as you're also passing in assemblies that aren't even used...
So I've introduced `GetAssemblyAttributes<T>()` and `GetAssemblyAttributes(param Type[] attributeTypes)` to `TypeLoader`, making it easy to retrieve all assembly attributes (from the same assemblies the types are loaded, e.g. without the …
=> Get EnableComposer and DisableComposer attributes from all assemblies

src/Umbraco.Core/Manifest/ManifestContentAppFactory.cs, src/Umbraco.Web.UI.Client/src/common/directives/components/member/umbmembernodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/common/services/editor.service.js, src/Umbraco.Web.UI.Client/src/views/components/member/umb-member-node-info.html, src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.controller.js, src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html, src/Umbraco.Web.UI.Client/src/views/member/apps/info/info.html, src/Umbraco.Web.UI.Client/src/views/member/edit.html, src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js, src/Umbraco.Web/ContentApps/ContentEditorContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentInfoContentAppFactory.cs, src/Umbraco.Web/ContentApps/ListViewContentAppFactory.cs, src/Umbraco.Web/Models/ContentEditing/MemberDisplay.cs, src/Umbraco.Web/Models/Mapping/MemberMapDefinition.cs
This PR enables ContentApps for Members.
Both the Content and the Info ContentApps have been implemented as well.
Some additional work can be done on the content of those tabs, for example Infinite Editing is not yet working for the MemberType in the Info ContentApp.
It is possible to limit the visibility based on the memberType (both manifest and c# definitions), like so:
"show": [
"-member/testType",
"+member/*"
]
**BREAKING**
Please note that this can be a breaking change for sites if they throw Exceptions like Core does, this is discussed in issue: #5843 
The way to fix these issues is to include a IMember case to the switch statements:
switch (source)
{
case IMedia media:
// dosomething(media);
break;
case IContent content:
// dosomething(content);
break;
case IMember _:
// don't …
=> Added ContentApps for Members

src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
Added URL segment to edited content, due to invariant content doesn't have an URL segment in preview, but variant content does have a segment. 
This fixes the bug with not being able to fetch an URL from the GetUrlById when it is invariant and unpublished.
Whether this is the correct way of doing it, I am not 100% sure, because it seems legit that the URL segment should be null when in preview. But having the segment in the DB already, it seems like it doesn't really matter if the segment exists on the preview content, and this makes it possible to use the same service to fetch preview/published URL's. 
Add event to cache refresher, as shown below:
The _preview_ variable should have a proper URL now when unpublishing/saving an unpublished invariant content node.
=> 6830 - fix: url segment null in preview content

src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less, src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
This PR improved to visibility for focus states for media library items. Previously, it was not possible to see the overlay button, and the default focus state wasn't always obvious enough.
=> Improve keyboard accessibility for media library items

src/Umbraco.Web.UI.Client/src/installer/steps/database.html, src/Umbraco.Web.UI.Client/src/installer/steps/permissionsreport.html, src/Umbraco.Web.UI.Client/src/installer/steps/version7upgradereport.html
If there's an existing issue for this PR then this fixes #7033 
Updated the following phrasing and language:
* "Great!, no need to configure..." becomes **"Great! No need to configure anything, you can simply click..."**
* "databaseuser" all one word and inconsistent becomes **"umbraco-database-user"**
* "connectionstring" all one word becomes **"connection string"**
* capitalisation of "Umbraco" on permissionsresport.html
* sentence flow on version7upgradereport.html
=> Updated language discrepancies on database install steps

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
Added missing documentation on the startNodeId property in editorservice.js (mediaPicker)
=> added documentation for param startNodeId (mediaPicker)

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/profiler.html
It seems the label next to toggle didn't changed the toggle anymore. It is because the rendered id on the button was `id="profilerAlwaysOn "` (with a whitespace last) instead of `id="profilerAlwaysOn"`.
I guess the `id` attribute on the toggle in some way conflicted with the internal `id` attribute on the `button` element inside `umb-toggle`.
Instead it now use `input-id="profilerAlwaysOn"`.
The `input-id` property has been added in this PR https://github.com/umbraco/Umbraco-CMS/pull/6512
=> Use input-id on toggle in profiler dashboard

src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
` property.isSensitiveData = propertyModel.isSensitiveData;` wasn't being set, which seems to have caused https://github.com/umbraco/Umbraco-CMS/issues/7270
https://github.com/umbraco/Umbraco-CMS/issues/7270
Allows for the saving of isSensitiveData value in a membertype editor.
=> maps isSensitiveData in groupsbuilder

src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
Currently the disable button in the user details screen is the grey `info` style button. I have changed it to `warning` style.
**Before**
**After**
=> Changed the Disable button in user details to be warning style

src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
On the user profile screen, under the user avatar preview, the remove photo link should only show if there is an avatar already picked. This PR fixes that.
=> - only show remove photo on user avatar when there is an avatar

src/Umbraco.Web.UI.Client/src/less/components/overlays.less
This PR removes an unneccessary change to the css class that was introduced by the PR [6848](https://github.com/umbraco/Umbraco-CMS/pull/6848) . The changes had to be applied to `.umb-overlay.umb-overlay-center .umb-overlay-header` while in reality it has been applied to `.umb-overlay.umb-overlay-center .umb-overlay-drawer `
=> Revert unnecesary changes for the css class

src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html
https://github.com/umbraco/Umbraco-CMS/issues/5277
see the accessibility trello board number 114) Open User Details - 'Change password' fields are all missing form labels - screen readers
=> Added Ids to inputs so the label in umb-control-group gets linked

src/Umbraco.Core/Services/UserServiceExtensions.cs, src/Umbraco.Web/Actions/ActionCollection.cs, src/Umbraco.Web/Editors/ContentController.cs, src/Umbraco.Web/Trees/ContentTreeController.cs, src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
If there's an existing issue for this PR then this fixes #6647
This PR fixes an issue with item context menus permissions for users that are assigned multiple groups. See #6647 for an excellent description of the issue.
1. Create a new user and assign two groups with different permissions defined; e.g. the Writers and the Editors groups.
2. Log in as this user and verify that all actions defined for both groups are available in the context menu for content items.
3. As the administrator, assign specific permissions to a content node, changing the access for the chosen groups.
4. As the new user, verify that the specific node permissions are applied.
=> V8: Handle permissions for users in multiple groups

src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js
Just a small fix to inline documentation. Corrected the @name documentation of the setFiles method in filemanager.service.js, from "addFiles" to "setFiles".
=> Fixed @name label in filemanager.service.js

src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
The option should be named using camel casing similar to pretty much all other options. The fix is made so either "notemplate" or "noTemplate" can be specified, making the fix backwards compatible instead of creating a breaking change.
While I had the controller open, I also fixed so the `id` option is no longer required when the `create` option is is set to `true`. When the latter is the case, the ID is automatically set to `-1` if not already specified.
The PR can be tested by running the following code:
```js
$scope.danger = function() {
editorService.documentTypeEditor({
create: true,
noTemplate: true
});
};
```
=> Fixed casing for the "noTemplate" option

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
- The `id` and `create` options where wrongly specified as being of type `Callback`. They are now `Number` and `Boolean` respectively
- The `noTemplate` was added. This change depends on #7022 being merged.
- The `isElement` and `allowVaryByCulture` was added following #6779
=> Improved the ngdocs for the editor service

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.controller.js
I came across a duplicate method (method **canAdd**) in the angular controller for nested content which I removed.
Functionality should remain unchanged, which I tested with datatype "Product - Features - Nested Content" from the default starter kit.
_Note: this PR replaces [PR7162](https://github.com/umbraco/Umbraco-CMS/pull/7162)_
=> remove duplicate method canAdd

src/Umbraco.Web.UI.Client/src/less/components/overlays.less
`.umb-overlay-container` doesn't have the same padding as `.umb-overlay-header` which makes it look broken. This PR fixes that.
Open the logviewer, do a search, try to save it (click the star icon), make sure the overlay looks like the after image.
=> Aligns the padding of .umb-overlay-container with .umb-overlay-header

src/Umbraco.Web.UI.Client/src/less/components/umb-breadcrumbs.less, src/Umbraco.Web.UI.Client/src/less/components/umb-mini-list-view.less, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
Breadcrumb links were vertically misaligned from the second item. 
Breadcrumb items were already flex but needed to be vertically centered.
Match font-size for  "Back" link, to the other breadcrumb items.
No real impact, but moved height (25px) to a parent container - it should not be a child who sets this. Also moved some inline styles to less.
Test by creating a document type and turn on "Enable list view". 
Allow children for it.
Create a page and add some children.
Add a "Content Picker" property to a document. Try to pick the deepest child.
Watch the breadcrumb-path is fully aligned.
Also test "Copy" and "Move" for an existing page with children as it also uses this breadcrumb
Also footer uses the breadcrumb
=> Avoid breadcrumbs in mini list are misaligned

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes (part of) https://github.com/umbraco/Umbraco-CMS/issues/6844
The media picker used to select media automatically when they were uploaded within the picker. Somewhere along the line this got broken.
This PR fixes it - and thus in part also fixes #6844.
With this PR applied, here's how the media picker works:
This works both for media pickers in "multiple images" and in "single image" mode; for "single image" mode the last uploaded media is automatically selected.
=> V8: Automatically select uploaded media in media pickers

src/Umbraco.Web.UI.Client/package.json
Just a minor update noUiSlider to v14.1.1 for accessibility to support keys Home/End and Page Up/Down. https://github.com/leongersen/noUiSlider/releases
This is e.g. useful in image cropper slider with many steps and only using keyboard. It also seems Page Up/Down move the handle a bit more than e.g. Left/Right arrow keys in image cropper slider.
Maybe we can also specify step size when using keyboard Left/Right arrow keys in a future version https://github.com/leongersen/noUiSlider/issues/992 but for now this seems to be a great improvement.
=> Update noUiSlider to v14.1 for accessibility

src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html
I have changed some `<a>` elements that did not have a valid ng-href/href attribute to `<button>` elements instead to improve the semantics and make screen readers announce "button" instead of link.
Visually things look the same as before the PR 😃
=> Image cropper config: Improve semantics

src/Umbraco.Web.UI.Client/src/navigation.controller.js, src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
On smaller screens, the trees close automatically on mouse leave. That works really well - unless you change to a section where the tree doesn't unfold directly below the mouse:
This PR ensures that trees are (also) hidden when you click outside them:
=> V8: On smaller screens, trees should close when you click outside them

src/Umbraco.Web.UI.Client/src/less/property-editors.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
The inputs for link URL and anchor aren't terribly nicely aligned in the linkpicker dialog:
This PR ensures that they're distributed evenly:
=> V8: Evenly distribute link URL and anchor inputs in linkpicker

src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
When you expand a line in the log viewer you will see a "Search" button, which will list some options of searching the issue on different search engines, on Github etc. I've improved the accessibility and the UX doing the following
- Convert `<a>` to `<button>`
- Added `aria-haspopup="true"` and `aria-expanded="true/false"`
- Removed `data-toggle="dropdown`, which has no impact at all. I think it's an old Bootstrap pattern that has been abandoned at some point
- Added the `deep-blur` directive to the parent element so that the "dropdown" will disappear when it's tabbed out of
**Before**
**After**
=> Log Viewer - Fix search toggle accessibility

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
I noticed that the rich text editor datatype was using the umb-checkbox directive but that there was a `<label>` wrapped around it, which should not be neccessary. But it was in order to ensure that clicking the associated config icon and text would tick the box.
Now that's not needed anymore since I have enabled the directive to accept an `iconClass` parameter, and when it's passed a value it will be rendered. if it's left empty it will not. Then things will look and act like we're used to.
Doing this fixes the markup pattern so we don't have `<label>` nested inside a `<label>` - Visually things look the same as before.
This can be tested in the "rich text editor" datatype 👍
=> Extend umb-checkbox to allow icons

src/Umbraco.Web.UI.Client/src/views/content/assigndomain.html
I have added the umb-auto-focus directive to the domain input field so it becomes focused whenever "Add" is clicked making it easier to start entering a domain name.
**Before**
**After**
=> Assign domain: Add autofocus

src/Umbraco.Web.UI.Client/src/views/documenttypes/importdocumenttype.html
Currrently the Import button is the grey default button, I have changed it to action style (blue background, white text) as I feel Import Doc Type is an action.
=> Changed the style of the Import button on Doctype Import to action style

src/Umbraco.Web.UI.Client/src/less/property-editors.less
Media picker properties that allow multiselect take up the full width of the screen. This doesn't look terribly good when they're used alongside other properties that have the default max width of 800px:
There is a functional merit when you pick a lot of images, but still... it looks a bit awkward:
This PR enforces the same max width of 800px to the media picker:
Obviously this means it takes up more vertical space when you pick a lot of images, but I think it's worth it:
=> V8: Make multiple media property editor same width as other property editors

src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
I have changed the `<a>` to a `<button>` making it possible to navigate the "delete" option using keyboard.
**Before**
**After**
=> Color picker datatype: Improve accessibility

src/Umbraco.Web.UI.Client/src/views/macros/views/parameters.html
In this PR I have added `aria-hidden="true"` on an icon to ensure screen readers don't try to announce them.
I have also changed `<a>` to `<button>`, which makes the "edit" and "remove" options possible to navigate using keyboard.
`Before`
`After`
=> Macro parameters: Improve accessibility

src/Umbraco.Web/Trees/MemberTypeTreeController.cs
Member types do not show up in the global search results. I can't really think of a great reason to leave them out, so this PR makes member types searchable:
=> V8: Make member types searchable

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.html
This PR adds the already existing `.table` class to the column table making it look much better.
Before
After
=> Listview: Add table class

src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Embed.cshtml
Updates the HTML Razor Partial View for grid cell items that use Embed
It has been recently updated in 8.2.0 that the Value stored is a JSON object containing width, height & the raw HTML returned by the oEmbed that was done in PR #4899
This fixes reported bug #7178
=> V8: AB3893 Updates the HTML Razor Partial View for grid cell items that use Embed

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Simple spelling mistake on word Umbraco in comments of JS file.
=> Spelling mistake on word Umbraco in instructional comment.

src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
Dead simple one, the name of the package was right up next to the following object, so i just added a space for formatting, to match the other locations this same code is used.
Can be seen here, just after package name:
https://gyazo.com/8a017d383dc1c07bd61a75287279984f
=> Space missing before name of Installed package and |

src/Umbraco.Web.UI.Client/src/less/components/application/umb-drawer.less, src/Umbraco.Web.UI.Client/src/less/components/umb-progress-circle.less, src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html, src/Umbraco.Web.UI.Client/src/views/components/umb-progress-bar.html
In this PR I have done the following
- Changed `<a>` without a `href` to a `<button>` element
- Fixed some semantics. `<div>` inside `<button>` is not valid and neither is having h-tags inside it either - so refactored those to spans
- Added `aria-expanded="true/false"` making screen readers announce whether the button is collapsed or not
- Fixed styling after the element change
- Added `aria-hidden` to `<i>` elements ensuring screen readers don't try to announce them
All of these changes don't affect anything visually so making before/after images does not make sense in this case 😃 - It should look like it did before the changes.
=> Help drawer: Fix accessibility and semantics for help drawer

src/Umbraco.Web.UI.Client/src/views/content/rights.html
I noticed that the "Set permission" button could use some accessibility improvements so in this PR I have
- Added the deep-blur directive meaning that the popup will disappear when it's tabbed out of
- Added the aria attributes for `aria-haspopup` and `aria-expanded`
- Refactored the `<a>` elements in the dropdown to `<button>`
- Hidden the `<i>` element using `aria-hidden="true`
**Before**
**After**
=> Set permission button accessibility fixes

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7374
This PR add a unique id when `input-id` is empty, so it doesn't render empty `id` attributes. I have also added a prefix for these.
=> Add component unique ids

src/Umbraco.Core/Constants-Icons.cs, src/Umbraco.Web/Trees/DataTypeTreeController.cs
With the same arguments as in #7358 I would propose to use the editor icons in the data type tree. This will make it a lot easier to find data types, and make a better overview of what kind of editors you are using.
To test:
Verify that the data type tree uses different icons for the data types.
=> Use the editor icon for data type trees

src/Umbraco.Web.UI.Client/src/less/panel.less, src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
The button one clicks on a document type has been changed from `<div>` to `<button>` and the icon has been hidden from screen readers.
Looks the same as before the PR 😃
=> Icon picker button: Fix accessibility

src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
When you try to save a search in the logviewer you get an error, because you are sending the complete json object with dates to the controller.
I fixed this by only sending the filterexpression, so it now works.
To test, open the logviewer, perform a search, try to save it.
Find the search in the dropdown of saved searches and verify that it works.
=> Fix bug when saving a search in the logviewer

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html, src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagementresults.html
Warren did a fantastic job of listing the fields of the search result, but I've always felt the overlay was a bit too small for content like this. And not to mention the `umb-overlay` directive is obsolete.
So with this PR, I'm turning this:
into this:
=> Replaced umb-overlay with editorService for listing fields of an Examine search result

src/Umbraco.Web.UI.Client/src/views/components/users/umb-user-group-preview.html
When tabbing through the permissions set on a content node you cannot tab to the Edit/Remove links to edit permissions. Similarly in the user details screen you cannot tab to the Edit/Remove links to make any changes. I have changed the Edit/Remove to be `<button>` rather than `<a>`.
Let me know if I am thoughts are right here :-)
**Before**
**After**
=> Accessibility fix to umb-user-group-preview

src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyeditor.directive.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
This PR exposes a reference to umbProperty on the property scope, so Property Editors can access properties on umbProperty. This will allow Property-Editors made with a Controller to add Property Actions.
This PR as well implements a Property Action for Media Picker in multi-mode, to prove that the implementation works.
Screenshot from solution:
Test notes:
— Have a Document Type with a Media Picker configured to select multiple media.
— See that Property Actions appear on the Media Picker property.
— Test that the action can be used to clear your picks.
— Test that the action is disabled when the Media Picker is empty.
— Test that picks made after a clear is begin saved and that the correct data is still present after a reload.
=> Property Actions for Property Editor with Controllers

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
Just noticed this on 8.4... the Nested Content "Add content" button is always displayed and active, even while the editor is loading (fetching element types). As a result the load indicator is displayed on top of the add button, which looks rather odd:
=> V8 Hide the Nested Content "add" button until the editor has loaded

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.controller.js, src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesourcetypepicker.controller.js
If there's an existing issue for this PR then this fixes #7328
If you've set a start node for an MNTP config, the node types in "Allow items of type" aren't displayed correctly. Every so often you might see them flicker into view before they disappear, but most often they'll just appear to be removed:
It happens because the "Node type" configuration and the "Allow items of type" configuration are connected via events, so "Allow items of type" automatically resets when the "Node type" changes. Unfortunately this event is emitted twice when a start node is present, forcing an unfortunate reset for "Allow items of type".
This PR refactors the event handling somewhat so things start working again:
=> V8: Display MNTP "Allow items of type" correctly when a start node is set

src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
In an effort to make things more accessible, the link that used to open the current content template has been turned into a button (see #7094). As a result, the content editor now saves the current content when you open its template in infinite editing:
If you're editing invariant content you probably won't even notice it being saved. That's not so good.
This issue is much along the lines of #7185, and the fix is the same: Applying an explicit type to the edit button (type="button"), thus explicitly instructing the browser how to interpret it.
Here's the same operation with this PR applied:
=> V8: Do not save content when opening the content template

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
The Multi URL Picker sorting doesn't quite behave like sortable lists generally does in Umbraco (e.g. in MNTP):
Most noticeable is probably how the Multi URL Picker sorting doesn't limit the item movement to the y axis only. But also the Multi URL Picker items behave differently among themselves (when the sort is triggered) and they're not slightly transparent as is the case with other sortables. 
So this PR basically just makes the Multi URL Picker sorting behave the same way as it does for MNTP:
=> V8: Make the Multi URL Picker sorting behave the same as MNTP

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If you're tabbing your way through content editing and you accidentally hit the Enter key twice when adding new items to Nested Content, the itempicker overlay crashes hard:
This is an unintended side effect of #6998 - the new `<button>` element for "Add content" retains focus whereas the previous `<a>` element did not. Thus the Nested Content controller attempts to open the overlay twice, which causes it to fail.
I have tried applying autofocus to the overlay as a solution, but `umb-auto-focus` doesn't really work in this case. So I have opted to let the Nested Content controller handle it instead by ensuring it doesn't open the overlay twice.
=> V8: Prevent the Nested Content item picker from crashing

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
If there's an existing issue for this PR then this fixes #7288
The nested content property label "jumps" a bit when you sort items, specially if you move the topmost item downwards. See #7288 for an excellent issue description.
With this PR applied, the "jumping" stops:
For this to work I had to remove the background color of the "dragged item placeholder". But this is very much in line with the sorting going on in other property editors, e.g. the tree pickers:
=> V8: Avoid UI "jumping" when sorting nested content items

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html
Currently in the `multivalues.html` view the Remove option is an `<a>`. I have changed it to a `button`. 
I have also made the drag and drop hide on-screen readers using `aria-hidden=true`. Don't know whether that is okay on second thoughts..
To test, add prevalues to the following data types and make sure the Remove button can be tabbed into using keyboard. 
- Checkbox list
- Radiobutton list
- Dropdown
- Dropdown multiple
These are the only ones I can think of now. Color Picker has its own prevalues screen.
An example of how it should work..
=> Accessibility improvements to Multivalues view

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
For most of the functions in the editor service, the `size` option is hardcoded, making it impossible to set another size.
Especially with the introduction of a `medium` size, it may be favorable to only set a size if one hasn't already been specified in the editor options.
=> Editor service shouldn't overwrite the size if already set in the options

src/Umbraco.Web.UI.Client/src/less/listview.less, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
I have re-done #7014 as a new PR in this one as the old one introduced too many changes post merging.
In the mini listview, I have cleaned up and moved some inline styling to stylesheets, added some fallback localization text and made the icons hidden on screen readers.
=> Accessibility improvements and clean up of mini list view

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowdeleteconfirm.html, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
This is the PR https://github.com/umbraco/Umbraco-CMS/pull/6959 re-done as the merge went bad there again.
In the grid datatype when you try to delete a row config, the overlay uses warning style all over. Since the application uses danger for deletes I have changed it to danger style. I have also added localization keys
=> Changed the styles from warning to danger for the confirm delete button, added localization keys

src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_6_0/AddPropertyTypeValidationMessageColumns.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_6_0/MissingContentVersionsIndexes.cs, src/Umbraco.Core/Persistence/Dtos/ContentVersionDto.cs, src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs, src/Umbraco.Core/Umbraco.Core.csproj
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/7245
There is a missing in dex on the umbracoContentVersion table (nodeid, current) which is needed for the paging query (among many other things). We were also loading in too much data for content when paging or displaying in the list view so this optimizes that. Normally getting content loads the content, templates, variants, properties and publishing schedule but most of this is not required for list view or paging through content so now for that it just loads in the content and properties. 
* Ensure the db migration works on startup
* Test out paging in content and ensure that you can still display a property value
* You can populate a ton of data in a list view:
* Create a doc type that is a list view and a doc type for it's …
=> Missing indexes on umbracoContentVersion and perf optimizations for content paging

src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
When you create new macros, the macro partial view isn't set. If you then allow those macros in the RTE and enabled rendering within the RTE, this is what happens:
Of course it makes no sense to have a macro without a view, but for newcomers that kind of error probably isn't terribly comforting. So this PR makes it mandatory to pick a view for a macro.
Obviously the macro can still be created without the view (that's how it's created after all), but at least you can't enable it for RTE without picking a view.
=> V8: Make macro partial view mandatory

src/Umbraco.Core/Composing/ComponentCollection.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6616.
This PR makes sure the `Terminate` method of all components are executed and any exceptions are logged as errors.
I first combined all exceptions into a single `AggregateException`, but that would still result in an unhandled exception while terminating the runtime and not run all logic within the `HandleApplicationEnd`:
https://github.com/umbraco/Umbraco-CMS/blob/27223738c6af045b637bb9944b53134e681ce5e5/src/Umbraco.Core/Runtime/CoreRuntime.cs#L281-L284
https://github.com/umbraco/Umbraco-CMS/blob/3332e93d4c2b44fbd11fb86fe89e62b61b28f96d/src/Umbraco.Web/UmbracoApplicationBase.cs#L109-L150
Testing can be done by following the reproduction steps from the linked issue. It should log …
=> Log exceptions thrown while terminating components

src/Umbraco.Web.UI.Docs/umb-docs.css
`<code>` elements in the descriptions are now properly styled 🎉 
The `gulp-ngdocs` task will by default remove all styling from `<code>` elements - probably because it uses them throughout the generated documentation where the styling doesn't make sense (eg. in the `<h1>` element). This PR will therefore only target `<code>` elements in the list of methods.
=> Angular API documentation: Adds styling for <code> elements

src/Umbraco.Web.UI.Client/src/less/main.less, src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
There is some content positioning going on that breaks the status messages of listviews (e.g. "No child items" and "No search results"):
This PR ensures that we display the listview status messages correctly:
=> V8: Ensure that listview status messages are vertically centered

src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js, src/Umbraco.Web.UI.Client/src/less/variables.less, src/Umbraco.Web.UI.Client/test/unit/common/services/notifications.spec.js
https://github.com/umbraco/Umbraco-CMS/issues/7343
- Added a test to the .spec file
Update the notifications so that they appear in the standard umbraco info blue
=> fixes info notifications to appear in blue

src/Umbraco.Abstractions/Configuration/ConfigsExtensions.cs, src/Umbraco.Abstractions/Configuration/MemberPasswordConfiguration.cs, src/Umbraco.Abstractions/Configuration/PasswordConfiguration.cs, src/Umbraco.Abstractions/Configuration/UmbracoSettings/IMemberPasswordConfigurationSection.cs, src/Umbraco.Abstractions/Configuration/UmbracoSettings/IPasswordConfigurationSection.cs, src/Umbraco.Abstractions/Configuration/UmbracoSettings/ISecuritySection.cs, src/Umbraco.Abstractions/Configuration/UmbracoSettings/IUserPasswordConfigurationSection.cs, src/Umbraco.Abstractions/Configuration/UserPasswordConfiguration.cs, src/Umbraco.Configuration/ConfigsFactory.cs, src/Umbraco.Configuration/UmbracoSettings/MemberPasswordConfigurationElement.cs, src/Umbraco.Configuration/UmbracoSettings/PasswordConfigurationElement.cs, src/Umbraco.Configuration/UmbracoSettings/SecurityElement.cs, src/Umbraco.Configuration/UmbracoSettings/UserPasswordConfigurationElement.cs, src/Umbraco.Tests/Configurations/UmbracoSettings/SecurityElementTests.cs, src/Umbraco.Tests/Configurations/UmbracoSettings/WebRoutingElementTests.cs, src/Umbraco.Tests/Configurations/UmbracoSettings/umbracoSettings.config, src/Umbraco.Tests/TestHelpers/SettingsForTests.cs, src/Umbraco.Tests/TestHelpers/Stubs/TestUserPasswordConfig.cs, src/Umbraco.Tests/Umbraco.Tests.csproj, src/Umbraco.Tests/Web/Controllers/AuthenticationControllerTests.cs, src/Umbraco.Web.UI/config/umbracoSettings.Release.config, src/Umbraco.Web.UI/config/umbracoSettings.config, src/Umbraco.Web/UmbracoDefaultOwinStartup.cs
This PR is for #7367 "Introduce configuration of IUserPasswordConfiguration and IMemberPasswordConfiguration".  I've added the necessary settings to `umbracoSettings.config` and amended the configuration loading so they are are read from there.
I wondered about the seeming duplication between `IPasswordConfiguration` and `IPasswordConfigurationSection` (and hence the mapping of fields from one to the other).  It seems like we'd always expect these to have the same values, but being consistent with existing patterns for configuration suggests it's probably best they are separate,
Have checked affected unit tests, and confirmed can still login.  Changing a user's password in the back-office shows the settings are in use.
=> .NET Core transition: Populated user and member password configuration from settings file (#7367)

src/Umbraco.Web.UI.Client/src/less/belle.less, src/Umbraco.Web.UI.Client/src/less/buttons.less, src/Umbraco.Web.UI.Client/src/less/components/umb-layout-selector.less, src/Umbraco.Web.UI.Client/src/less/components/umb-mini-search.less, src/Umbraco.Web.UI.Client/src/less/listview.less, src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html, src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search/umb-mini-search.html, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search/umbminisearch.component.js, src/Umbraco.Web.UI.Client/src/views/components/umb-table.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
This PR updates the looks of items in the subheader in List View, to look as following screenshot:
The reason for this is to keep making the looks of Umbraco simpler and friendlier by ensuring a calm look. Notice how the search input is collapsed until its activated, in this way we make it easier for users to decode the view.
Any thoughts and considerations are welcome.
=> Listview styling adjustments

src/Umbraco.Web.UI.Client/lib/bootstrap/less/code.less, src/Umbraco.Web.UI.Client/src/common/directives/components/umbcodesnippet.directive.js, src/Umbraco.Web.UI.Client/src/less/belle.less, src/Umbraco.Web.UI.Client/src/less/components/umb-code-snippet.less, src/Umbraco.Web.UI.Client/src/less/hacks.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/querybuilder/querybuilder.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/querybuilder/querybuilder.html, src/Umbraco.Web.UI.Client/src/views/components/umb-code-snippet.html
This PR add a `umb-code-snippet` component, which includes a copy button to copy the code and enhance this feature from this PR https://github.com/umbraco/Umbraco-CMS/pull/6584#issuecomment-549855172
I have been inspired by these code samples https://docs.microsoft.com/en-us/odata/webapi/netcore (which are using highlight.js)
The idea is that package developers also can re-use this component in e.g. the view after installation, in dashboard and in another part of backoffice UI in core.
At the moment this doesn't use third parthy plugins like [highlight.js](https://highlightjs.org/) or [Prism](https://prismjs.com/). https://github.com/umbraco/Umbraco-CMS/issues/7060
Prism is lightweight and it supported by default in TinyMCE, but doesn't out of the box support razor (cshtml/vbhtml) …
=> Add code snippet component

src/Umbraco.Web/Editors/ContentController.cs, src/Umbraco.Web/Editors/DataTypeController.cs, src/Umbraco.Web/Editors/MacrosController.cs, src/Umbraco.Web/Models/Mapping/MacroMapDefinition.cs
At the moment it is possible to get content, media and member by id, but also by guid.
For datatypes it request datatype by id and if you try to request it by guid, it returns a console error.
=> Request datatype by guid

src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less, src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
*This is a redo of #6687 based on the comments from @nielslyngsoe*
There's something weird going on when editors have start nodes; the same content nodes are being loaded twice, and things generally feels broken.
Consider an editor with these start nodes configured:
Here's the corresponding editor experience:
Personally I'd be genuinely confused about the duplicate nodes - even more so because the the root nodes isn't duplicated. And also:
- When you select a node in the tree that is built from your start node, the corresponding node underneath the "full" tree is highlighted instead of the one you selected.
- When you right click a node anywhere, both that node and the corresponding duplicate are highlighted.
- All nodes in the "full" tree have a "not-allowed" cursor and are dimmed down - …
=> V8: Prevent/remove duplicate nodes for editors with start nodes (take two)

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html
When a content picker is configured to pick max 1 item, the help text is a little redundant - usually the property label and/or description would be sufficient to help the editors:
This PR hides the help text when max items is set to 0 or 1 _and_ min items is set to 0:
1. Validate that the help text is _not_ shown when max items is set to 0 or 1 and min items is set to 0.
2. Validate that the help text is shown if max items is set to more than 1.
3. Validate that the help text is shown if min items is set to more than 0.
=> V8: Don't show "max items" help text for content pickers in single item configuration

src/Umbraco.Core/Models/MediaTypeExtensions.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.html, src/Umbraco.Web/Models/ContentEditing/MediaTypeDisplay.cs, src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs, src/Umbraco.Web/Trees/MediaTypeTreeController.cs
The default media types "Image", "File" and "Folder" are used in a number of places and expected to be part of any Umbraco installation - things go horribly wrong if they are not present (see for example #6632).
While this dependency on "known media types" is not ideal, we should at least protect these media types from deletion and/or alias changes until a less hardcoded solution can be implemented in the core, so newcomers do not accidentally destroy their Umbraco installation simply by using the backoffice. 
This PR ensures that:
1. "Image", "File" and "Folder" can't be deleted.
2. "Image", "File" and "Folder" can't have their aliases changed (see also #6942).
=> V8: Protect "system media types" from alias changes and deletion

src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
If there's an existing issue for this PR then this fixes #5968
Date pickers cause issues if a non-default format like DD-MM-YYYY is configured. Moment.js is asked to parse the formatted value, which at best causes a javascript warning and at worst leaves the field back or with the wrong date. In a future version, Moment.js will remove support for the fallback parsing which currently triggers the warning, causing further problems.
This change passes the configured format string to Moment.js so that the value can be parsed properly. Since the user could still type a date in another format, it falls back to the browser's date parsing in a way which keeps Moment.js happy.
To test:
- Configure the date picker with a non-default format, such as DD-MM-YYYY.
- Open the picker by clicking in the …
=> V8: Date pickers - parsing non-standard formats

src/Umbraco.Web/PublishedContentExtensions.cs
You can configure Umbraco to generate absolute urls out of the box by changing the web.Routing section umbracoSetttings.config file.  You can do this by settting `urlProviderMode="Absolute"`
So by setting this I would expect umbraco to generate absolute urls when I request the url through the url property of a IPublishedContent item.
However on 8.3.0 it still generates relative urls after setting this in the config. This is cased by the default value for mode being Auto on the Url method in PublishedContentExtensions. 
I changed the default value of the mode to UrlMode.Default. And when it is set it will get the mode configured on the url provider. This is backwards compatible because when there is no urlProvider mode configured in the web.Routing section it will default to Auto.
Can this …
=> Make sure the configured url provider mode is used when getting a url

src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/7457
We need to register the config no matter what which MB is used. The config is used to avoid execution of methods in the internal MB
=> Hotfix - Missing registration in IOC when running external MB

src/Umbraco.Web.UI.Docs/umb-docs.css
As the Angular API documentation uses nested tables for listing options for the options and parameters, the space quickly feels a bit cramped.
With this PR I'm making the documentation fluid. The documentation site uses Bootstrap for creating columns, but only seems to use `.span3` and `.span9`, so I've only updated those to be responsive. The other `.span{n}` classes are still fixed with.
I've set the container to a maximum width of 1500 pixels, so the site doesn't become super wide on wide monitors.
This PR will have a merge conflict with #7029. In my head it make sense to make the site responsive, so as I'm not 100% this will be merged, I've created the changes as two PRs instead of one 😮
With a browser window with a width of 1700 pixels, the same block now looks like:
=> Responsive Angular API documentation

src/Umbraco.Web/Cache/DistributedCacheExtensions.cs, src/Umbraco.Web/Cache/MediaCacheRefresher.cs, src/Umbraco.Web/Cache/UnpublishedPageCacheRefresher.cs, src/Umbraco.Web/PublishedCache/XmlPublishedCache/PublishedMediaCache.cs, src/Umbraco.Web/Search/ExamineEvents.cs
Fix: [AB#4084](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4084)
Backport of: https://github.com/umbraco/Umbraco-CMS/pull/6462
OBS: For some reason do my computer hate V7 formatting... I guess it is because my IDE follows the .editorconfig. - So remember to hide whitespace changes.
- Have updated all the `DistributedCacheExtensions ` for `UnpublishedPageCache` to use `RefreshByJson`
- Have added key to `MediaCacheRefrecher.JsonPayload`.  and clear the cache using key
- OBS: ` DistributedCacheExtensions.RemoveMediaCache` still uses `dc.Remove(guid)`.
- Updated `UnpublishedPageCacheRefresher.Refresh(string jsonPayload)` to handle both delete and refrech
- Was forced to handle the the newly introduced operation type in `ExamineEvents`
The test case from …
=> V7: Backported/reimplemented fix for contentservice returning outdated results

src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
Just a small typo in the contentTypePropertyTypeDeleted label in the French language file : 
"Type de documet sauvegardé" should read "Type de document sauvegardé".
Steps to reproduce : 
1. Open Umbraco backoffice
2. Set language to French
3. Open the "Settings" section
4. Edit and save any document type
5. There's a typo in the word "documet" in the confirmation label (missing a "n").
=> Fix typo in contentTypeSavedHeader French label

src/Umbraco.Web.UI/Umbraco/config/lang/de.xml
(and improve wording: "Abschließen" (~ completing something) instead of "Quit" or "Close" as it was; EN is "Finishing")
=> Fix typo in DE "installFinish" caption

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7452
This fixes the error when you try to schedule content in a multilanguage site.
In the scheduled publishing dialog the save flag was set correctly on the variant. But when the schedule button is clicked the new value for this was not stored in the orignal variant. This PR fixes that.
=> #7452 Fixes schedule publish dialog for multilanguage sites

src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs, src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentSingleValueConverter.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/2925.
The is the V8 version of PR https://github.com/umbraco/Umbraco-CMS/pull/2918. By adding the `DefaultPropertyValueConverterAttribute` to the PVCs, adding a custom one doesn't require [manually removing them](https://gist.github.com/stevemegson/33c24a4b36bf9d7381aa4dc9cc01b117).
=> Add DefaultPropertyValueConverterAttribute to core Nested Content PropertyValueConverters

src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.html
The treepicker isn't super great at displaying the current picked item state when you're moving around in the tree. It's particularly bad when navigating listview nodes and when searching:
This PR makes a brave attempt at fixing these issues, so the currently picked items are always marked with the checkbox on matter how you navigate the tree:
=> V8: Display picked item state when navigating the treepicker

src/Umbraco.Web.UI.Client/src/views/components/umb-generate-alias.html
OK so this is a tiny thing, but...
Some type aliases are uneditable because they're reserved by the system (e.g. the built-in user group aliases). They appear in the UI without the little padlock that usually lets you "unlock" the alias to edit it. 
For some reason these uneditable type aliases do not have a "not allowed" cursor when you hover the mouse above them - they use the default "text highlight" cursor. This PR changes the cursor to "not allowed".
=> V8: Use "not allowed" cursor for locked type aliases

src/Umbraco.Web/Profiling/WebProfiler.cs, src/Umbraco.Web/Profiling/WebProfilerProvider.cs
This PR undos the fix (ugly hack IMHO) applied in https://github.com/umbraco/Umbraco-CMS/pull/6114 and correctly discards the MiniProfiler results when not in debug mode. This ensures the results aren't even stored, which seems the best thing to do (instead of removing the MVC routes to disable accessing them via the results URL).
Because of [this bug in MiniProfiler](https://github.com/MiniProfiler/dotnet/issues/96), the results URL would throw a `NullReferenceException` when nothing is stored and no storage is set. This PR also explicitly sets the storage to the default `HttpRuntimeCacheStorage`, but with a cache duration of 30 minutes (instead of 1 day). This should be enough time to view the profiling results and is actually the [default since MiniProfiler …
=> V7: Discard MiniProfiler results when not in debug mode

src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
Just a tiny step on the way to make Umbraco more efficiently testable.  
The two downcasts doesn't do anything except hinder use of `PublishedContent` in unit tests.  
Feel free to bring into 8.5.3 with the other PR.
My goal with the slow but ongoing process is to make it as efficient as possible to test stuff using serialized content. IE. JSON files and as little stubbing as possible to keep tests clean.  
Things can be followed here if interested:  
https://github.com/lars-erik/umbraco-unit-testing-samples/tree/master-v8
=> Don't downcast `IPublishedSnapshot` unnecessarily in `PublishedContent`

src/Umbraco.Tests/Templates/HtmlImageSourceParserTests.cs, src/Umbraco.Web/Templates/HtmlImageSourceParser.cs
Link to the issue: #7386 
**Changes:**
1. Changed image tag parsing **Regex** to be more performant
2. Added more **tests** (including one which tests performance)
**How to test:**
1. Add any document with a default rich text editor property
2. Use [this page](https://www.base64-image.de/) or any other to transform an image into a **base64** characters.
3. Insert `<img src="{YOUR BASE64 characters}" />` into your document's property source.
4. Ensure that **Saving**, **Publishing**, **Reopening**, **Previewing** works fast.
5. Additionally, add media images and ensure that they are still working correctly.
=> Improve RTE performance when using base64 images

src/Umbraco.Core/Constants-AppSettings.cs, src/Umbraco.Core/IO/SystemDirectories.cs
If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/7336
Changes the magic string in Umbraco.Core.IO.SystemDirectories.Umbraco to use the global constant for the AppSettings.Path. This results in the css being pulled from the correct location when the backoffice is launched.
Tested with these settings:
Then the css files loaded from the correct location:
=> Uses AppSettings.Path constant for SystemDirectories.Umbraco

src/Umbraco.Core/Udi.cs
- [FIX] Changed check of UDI type to check for GUID type and then String type as previously was checking for
GUID type twice. This resulted in the method never creating a String UDI if needed.
- [ISSUE] Github Issue #7507 https://github.com/umbraco/Umbraco-CMS/issues/7507
The change is exactly that described in the issue, however could not find where the code is used within the core to fully test it, but appears related to the UdiRangeJsonConverter
=> [FIX] Corrected Create method so that String UDI is correctly identified

src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs, src/Umbraco.Web/Models/Mapping/MediaMapDefinition.cs
If there's an existing issue for this PR then this fixes #7548 
Renamed "DermineIsChildOfListView" to "DetermineIsChildOfListView" in MediaMapDefinition and ContentMapDefinition (both private methods)
Testing: nothing to test - simple rename of private variables and rebuild.
=> Renamed "DermineIsChildOfListView" to "DetermineIsChildOfListView"

src/Umbraco.Core/Migrations/Upgrade/Common/CreateKeysAndIndexes.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs
Create a temporary index on umbracoPropertyData to speed up remaining migrations.
=> Migrations - Create temporary index on umbracoPropertyData

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs
When creating the new versions for content with published=newest, replace foreach loops with three INSERTs to umbracoContentVersion, umbracoDocumentVersion and umbracoPropertyData.
=> Migrations - Add extra "published=newest" versions with INSERT...SELECT

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/RenameMediaVersionTable.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs
Several places use a SELECT followed by many UPDATES in a foreach loop because SQLCE doesn't support UPDATE...FROM. It's worth the effort to include the UPDATE...FROM version for SQL Server.
=> Migrations - SQLCE does not support UPDATE...FROM

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/AddTypedLabels.cs
The AddTypedLabels migration clears TextValue when setting IntegerValue or DateValue, but should also clear VarcharValue.
=> Migrations - In AddTypedLabels, clear VarcharValue as well as TextValue

src/Umbraco.Core/Migrations/Upgrade/V_8_1_0/ConvertTinyMceAndGridMediaUrlsToLocalLink.cs
In ConvertTinyMceAndGridMediaUrlsToLocalLink, keep track of whether the value changed and don't update the database if there's nothing to update.
=> Migrations - In ConvertTinyMceAndGridMediaUrlsToLocalLink, avoid unnecessary updates

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs
Breaking up #6191 into easier pieces.
Published documents which have unpublished changes are left in an unpublished state after migration. This PR simply checks that any document with a published version is marked as published.
=> Migrations - ensure that documents with a published version are published

src/Umbraco.Abstractions/Constants-ObjectTypes.cs, src/Umbraco.Abstractions/Models/UmbracoObjectTypes.cs, src/Umbraco.Abstractions/UdiEntityTypeHelper.cs, src/Umbraco.Infrastructure/Services/Implement/FileService.cs, src/Umbraco.Web/Editors/RelationTypeController.cs
Fixes for #7368
Removes an obsolete Stylesheet constant, the Stylesheet UmbracoObjectTypes enum value which used it, and references to that enum value.
=> Remove obsolete Stylesheet constant and references

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
😱 Large GIFs ahead 😱 
When inserting images in the RTE it doesn't always resize itself to fit the new content; in fact I find it fails to do so more often than not:
As soon as you click virtually anywhere in the UI, the editor auto-resizes to fit... but it kinda feels like it should do that on its own when the image is inserted. So! This PR forces the RTE to auto-resize after an image is inserted. It works like this:
_In these GIFs I've used the new RTE image upload to demo the issue, but it also happens when inserting images from the media library._
=> V8: Auto-resize the RTE after inserting images

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreesearchbox.directive.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.html, src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-box.html
Media Picker applies autofocus to the search box when the picker is opened, which means the editors can instantly search for the media they want. 
The treepicker component (which powers MNTP and Content Picker) does not apply the same autofocus:
Being a huge fan of the search boxes, I think that's a darn shame. So this PR ensures that the treepicker search box automatically receives focus when the treepicker is opened:
=> V8: Add autofocus to treepicker search box

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
When you navigate the treepicker using the keyboard (tabbing around), you run into all sorts of issues if the tree contains a listview. The default tab focus more often than not moves to the dialog footer in the transition between views:
This PR fixes it by:
1. Applying default input focus to the search box within the list views.
2. Restoring input focus to the last focused element in the tree when you close the last listview.
Here's how it works:
=> V8: Improve treepicker keyboard navigation for trees with listviews

src/Umbraco.Web.UI.Client/src/less/sections.less
When using keyboard to navigate through the sections, these are jumping a bit, because the section name get a border on focus, but no by default. So on focus it is moved a few pixels.
Adding a transparent border ensure the section name not jump on focus.
**Before**
**After**
=> Fix jumping section name on focus

src/Umbraco.Core/Persistence/Repositories/Implement/AuditRepository.cs, src/Umbraco.Core/Services/Implement/AuditService.cs
https://github.com/umbraco/Umbraco-CMS/issues/6812
Create a backoffice user (not the admin) and perform some Saves, Publish, Unpublish in the backoffice.
Then following code in for example a view should all return results.
```
var pagedByUser = Services.AuditService.GetPagedItemsByUser(1, 0, 100, out totalItems);
var byUserBydate = Services.AuditService.GetUserLogs(1,AuditType.Publish,DateTime.Now.AddDays(-15));
var logsByType = Services.AuditService.GetLogs(AuditType.Publish);
// Might need to change the hardcoded id here when testing
var pagedByEntity = Services.AuditService.GetPagedItemsByEntity(1104, 0,100, out totalItems);
```
=> #6812 AuditService some methods not returning any values

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
Tabbing through the content editor is made really hard by pickers and other dialogs spawned by `editorService`. When they're closed, input focus is set to the first applicable element on the page, which is in the top menu:
This PR makes `editorService` attempt to re-apply input focus to the element that had input focus before the dialog was opened:
See also #6934.
=> V8: Re-apply input focus to the last focused element when closing dialogs

src/Umbraco.Web.UI.Client/src/less/components/umb-mini-search.less, src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search/umb-mini-search.html
This PR align the search icon a bit more in center of the search input and also add `aria-hidden="true"` to the icon. Also note that the height of the search box previous didn't align with the height of the layout selector button.
**Before**
**After**
=> Align icon in mini search

src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs, src/Umbraco.Tests/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs, src/Umbraco.Tests/Umbraco.Tests.csproj
With item tracking in 8.6 we weren't tracking references for values in variants/segments. We did this originally because we are planning on tracking references directly to variants/segments but we are not there yet since that requires db changes. For now, we will track item refrences based on any valid variant/invariant property values.
This PR adds support for that and is based on the TODO in this comment https://github.com/umbraco/Umbraco-CMS/blob/v8/feature/media-tracking/src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs#L22
Unit tests have been added too.
=> Ensures that we track relations for values on all variant property values

src/Umbraco.Web.UI.Client/package-lock.json, src/Umbraco.Web.UI.Client/package.json
If there's an existing issue for this PR then this fixes #7572 
Without going into long boring details, the issue was caused by angular-aria, which didn't like finding `contenteditable` elements inside an element decorated with `ng-click`. There are a couple of confusing GitHub issues for anyone looking for a long read...
Bumping angular-aria to 1.7.9 fixes the problem. Happy days.
Can be verified by setting a grid RTE to distraction-free mode, then typing like a sensible person who puts spaces in their sentences. 😃
=> update angular-aria to 1.7.9

src/Umbraco.Web/Install/InstallSteps/SetUmbracoVersionStep.cs
This message bugged me so I fixed it. 
It used to say "Installation is complete!, get ready..."
but now it says,
"Installation is complete! Get ready..."
=> v8: Punctuation and grammar fix on the install screen

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
As described in #7543, the changes in #7130 causes the multi URL picker to crash with JS errors when it contains non-local (absolute) links.
For a piece of content with a multi URL picker:
1. Add a new item to the multi URL picker and enter e.g. "https://somewhere.com" in the link field:
2. Save the content item.
3. Reload the browser.
4. The multi URL picker is not displays as empty, and the JS console is full of errors:
When this PR is applied, the multi URL picker displays all added items after saving the content and reloading the browser:
=> 8.6RC: Prevent multi URL picker from crashing for non-local links

src/Umbraco.Core/Models/PublishedContent/IPublishedContent.cs, src/Umbraco.Web/Macros/PublishedContentHashtableConverter.cs, src/Umbraco.Web/Models/PublishedContentBase.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs, src/Umbraco.Web/PublishedCache/PublishedMember.cs, src/Umbraco.Web/PublishedContentExtensions.cs
_Creating this PR to trigger a discussion on the impact of removing CreatorName and WriterName from IPublishedContent_
We've been looking at things that make the move to netcore more difficult. One of the things that came up is PublishedContent's dependency on IUserService. 
It seemed to the Unicore team that CreatorName and WriterName are rarely used and could easily be replaced by an extension method. This would remove service location from IPublishedContent implementations and a bunch of TODOs and other code that feels a bit hacky.
If we were to remove them in future making them obsolete now would seem sensible so Umbraco developers could see that these are going to vanish and update now.
=> Obsolete CreatorName and WriterName on IPublishedContent

src/Umbraco.Core/Models/PublishedContent/IPublishedContent.cs, src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs, src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs, src/Umbraco.Web/Controllers/UmbLoginController.cs, src/Umbraco.Web/Models/PublishedContentBase.cs, src/Umbraco.Web/PropertyEditors/RichTextEditorPastedImages.cs
Part of the asp-netcore dev work
The Url property on published content, which is very context dependant causes issue to move to netcore. There is already an extension method to replace it so seems sensible to remove it on the next major release. 
Marking obsolete here to start letting developers know that it's likely to be removed.
=> Obsolete Url on IPublishedContent

src/Umbraco.Core/Composing/Current.cs, src/Umbraco.Core/Models/IImageUrlGenerator.cs, src/Umbraco.Core/Models/ImageUrlGenerationOptions.cs, src/Umbraco.Core/Models/UserExtensions.cs, src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Tests/Models/ImageProcessorImageUrlGeneratorTest.cs, src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs, src/Umbraco.Tests/PublishedContent/PublishedContentTestBase.cs, src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs, src/Umbraco.Tests/Runtimes/StandaloneTests.cs, src/Umbraco.Tests/Testing/UmbracoTestBase.cs, src/Umbraco.Tests/Umbraco.Tests.csproj, src/Umbraco.Web.UI.Client/src/common/resources/imageurlgenerator.resource.js, src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Media.cshtml, src/Umbraco.Web/Editors/BackOfficeServerVariables.cs, src/Umbraco.Web/Editors/ImageUrlGeneratorController.cs, src/Umbraco.Web/Editors/ImagesController.cs, src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs, src/Umbraco.Web/Models/ImageProcessorImageUrlGenerator.cs, src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs, src/Umbraco.Web/PropertyEditors/RichTextEditorPastedImages.cs, src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs, src/Umbraco.Web/Runtime/WebInitialComposer.cs, src/Umbraco.Web/Templates/TemplateUtilities.cs, src/Umbraco.Web/Umbraco.Web.csproj
- [ X ] I have added steps to test this contribution in the description below
This resolves issue #7538 
I created an IImageUrlGenerator interface, along with an ImageProcessorImageUrlGenerator implementation.  I injected that implementation at startup, reworked the ImageCropperTemplateExtensions and ImageCropperValue classes to use it, and then updated other classes and tests that were hard-coded with image URL parameters so that they used the implementation.  This included adding constructors to various classes so that they could accept an injected IImageUrlGenerator implementation, and then obsoleting the previous constructor so that we can delete it in the .NET Core project.
To test this you should spin up a new site with the starter pack, and verify that cropped media show up …
=> Introduce Image URL Generator abstraction

src/Umbraco.Web.UI.Client/src/views/propertyeditors/slider/slider.controller.js
If there's an existing issue for this PR then this fixes #7564
In noUiSlider configuration, the format `from` function should return a number. Returning a string works as long as the minimum is non-negative, but causes strange behaviour when minimum is negative.
Testing:
- Create a slider property with the minimum set to any negative number.
- The slider should behave normally, not jump to the maximum and minimum values as seen in #7564.
=> Slider format function should return a number

src/Umbraco.Web.UI.Client/src/common/directives/components/umbchildselector.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-child-selector.less, src/Umbraco.Web.UI.Client/src/views/components/umb-child-selector.html
This PR https://github.com/umbraco/Umbraco-CMS/pull/4927 introduced sorting on the child elements in `umb-child-selector` component. However with these changed add also added the `move` cursor on the add button.
The changes in this PR ensure only the child elements that can be sorted get the `move` cursor, while the add-button still has the `pointer` cursor.
It also add documentation of the previous added `onSort` function.
Furthermore it has a few changed to update buttons using `button` element and add `aria-hidden="true"` to icons.
=> Adjust child selector sorting

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsections.directive.js, src/Umbraco.Web.UI.Client/src/less/sections.less, src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
- This PR is intended to fix #7473.
- The `expand` element now receives the `current` class if the currently active section is found in the overflow.
- If the active section is found in the overflow, the `expand` element shares the same visual appearance.
- Made some of the CSS rulesets more specific, so they didn't cascade to all links underneath the `expand` element.
- To determine if the `current` element should have the class `current` applied, I couldn't find a way to do this with a simple one-liner in the template. I wrote a function `currentSectionInOverflow`. If this is not ideal please give me feedback on how I might update this to a preferred solution.
=> Add an Active State for Expand (...) in the Top Section Navigation

src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
Making the icon of umb-node-preview align vertically.
=> make icon of umb-preview-node align vertically.

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstep.directive.js, src/Umbraco.Web.UI.Client/src/views/components/application/umb-tour.html, src/Umbraco.Web.UI.Client/src/views/components/application/umbtour/umb-tour-step.html
In a clean Umbraco install with no content nodes and running the tour "Create content", it stops after step 2 because it can't find a homepage node and you get the tour step error "Oh, we got lost!". The button "End tour" close the overlay, while the close button does nothing, because there is no `on-close` implemented for this tour step.
Not sure if it makes sense this tour look for a homepage node? I guess some might take this tour to know how to get started creating content?
It would be great if it also was possible to close the tour by using `esc` shortcut like with other overlays in backoffice.
=> Missing onClose for tour

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
This fixes #7643 
Added `type="button"` to the 3 buttons on the mediapicker property editor to prevent them from being clicked when pressing Enter.
You should now be able to add a media picker to a doc type, as well as a text box. Click into the text box and press Enter. The media picker overlay should no longer pop up.
=> #7643: add type="button" to prevent default clicks by pressing Enter

src/Umbraco.Web/Trees/ContentTypeTreeController.cs, src/Umbraco.Web/Trees/MediaTypeTreeController.cs, src/Umbraco.Web/Trees/MemberTypeTreeController.cs
In the Settings section, Document Types tree we see all document types with the exact same default icon like this
In the content type picker that was recently added we can see the icon for the doc type and its colour like this:
As a developer / architect of an umbraco site it would be so useful to be able to see which icons and colours have been chosen for a document type at the tree level. It would save us clicking through to each document type to see which icon has been chosen for it. Also it would give continuity to what we have with the content type picker, showing the icon and colour.
My PR fixes this issue and shows us the chosen icon with its colour instead of just a black default doc type icon. Here is what it will look like:
=> Change the icon in the Document Types Tree to be the chosen icon instead of a default one.

src/Umbraco.Web.UI.Client/src/views/dashboard/members/membersdashboardvideos.html
The members dashboard `h3` heading is not very consistent with the settings welcome dashboard. The heading is bolder in the settings dashboard. The headings are bold across other Settings dashboard like Modelsbuilder and Performance Profiling which makes me think that the members dashboard should reflect the same.
**Settings Dashboard**
**Members Dashoard - Before**
**Members Dashboard -After**
=> CSS class added to the h3 on members dashboard

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
The editor breadcrumb isn't shown for 1st level items under the content and media roots:
For 1st level items under the recycle bin the breadcrumb _is_ shown, but it's pretty useless as it can't be interacted with:
This PR removes the breadcrumb for 1st level items under the recycle bin in both the content and media trees. When applied it works like this:
=> V8: Do not show the breadcrumb for immediate children in the recycle bin

src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less, src/Umbraco.Web.UI.Client/src/less/mixins.less, src/Umbraco.Web.UI.Client/src/less/property-editors.less, src/Umbraco.Web.UI.Client/src/less/variables.less
The upload areas of the image cropper and upload property editors are a bit excessive in size, compared to most other editors:
Also when an image is uploaded to the upload property editor, the applied image border is a tad out of place:
With this PR applied, the upload areas have the same width as other property editors:
...and when images are uploaded, the upload property border doesn't go full width:
Notice how the image cropper is still allowed to span the full browser width when an image is uploaded. I chose this approach in order to leave room for those image cropper configurations with a lot of defined crops.
=> V8: Styling updates to image cropper and upload property editors

src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
In `PublishedSnapshotService.OnMemberRefreshedEntity`, the comment says "refresh the edited data" but `OnRepositoryRefreshed` is called with `published=true`. This causes the Published Status dashboard to report a problem, since it's looking for rows with published=false.
Testing:
- Create a new member
- Check that cmsContentNu contains a row for the new member with published=false
- Check that the Published Status dashboard shows OK
=> OnMemberRefreshedEntity stores data as published rather than edited

.github/BUILD.md
You don't have to read the whole complex documentation. Just build it and then go to the next step :)
=> Make the source code build documentation a bit less complex

src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertymsg.directive.js
If there's an existing issue for this PR then this fixes #7647 
This was due to validation not checking for an empty value, which is a valid state for non-mandatory fields.
Changes here ensure that when we set the validation state on a property form, we check that the property is not mandatory and has no value - if both those flags are true, existing errors are cleared and form controls all reset. 
I'm not really across the intricacies of the client-side validation, but from what I can see, the changes fix the problem, and don't impact on existing validation logic. Needs a good sanity check though from someone saner than I.
I've tested by reproducing the scenario from the original bug report. All works as expected - saving with an invalid value displays the validation messages, clearing …
=> v8: 7647 Can't save content after clearing property with validation error

src/Umbraco.Core/Persistence/Repositories/IContentTypeRepositoryBase.cs, src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs, src/Umbraco.Core/Services/IContentTypeServiceBase.cs, src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs, src/Umbraco.Web/Editors/ContentController.cs, src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs, src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
If you have a user with a start node that is nested within 2 or more list views, the tree will not expand when the user logs in and therefore the user cannot actually navigate to or edit their start node.
Create a tree structure like:
* Home
* List View
* List View
* Content
And then create a new user and set their start node to `Content`. When you log in the tree will expand to show `Content`. Be creative, try nesting a start node in a bunch of list views, maybe even have a content -> list view -> content -> list view type scenario, it should all work.
=> Fixing when a start node is a content item in a nested list view

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
This PR makes it possible to transclude <umb-checkbox> and <umb-radiobutton>. This means the content of the label for the given input can be whatever you put insert inside the component tags.
Enabling us to show the necessary information in relation to a check-input.
Like:
```
<umb-checkbox>
<h1>I wish for a headline in my label...</h1>
</umb-checkbox>
```
---
_This item has been added to our backlog [AB#5158](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5158)_
=> Enabling transclude for umb-form-check

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If a Nested Content property is configured with only one element type and with a minimum number of items required, the editor throws a bunch of JS errors when creating new content:
This happens because the underlying property model isn't updated correctly after the minimum number of items has been enforced by the editor. The errors keep going and going until you collapse one of the added items.
This PR ensures that the underlying property model is updated if items are added to it when the property editor loads.
1. Create a content type with a Nested Content property configured with:
- Only one element type
- Minimum number of elements >= 1 
2. Create some content based on this content type.
3. Verify that the JS console is error free.
=> V8: Fix Nested Content JS errors when enforcing min items

src/Umbraco.Tests/Cache/PublishedCache/PublishedMediaCacheTests.cs, src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedMediaCache.cs
This helps to reduce the references to Current.Services as mentioned in https://github.com/umbraco/Umbraco-CMS/issues/7369
Replaced instances of MediaService with ServiceContext or existing injected MediaService in more unit tests. Using ServiceContext as per the remainder of the first test, and the mediaService field as per the existing code in the second test.
=> Replaced instances of Current.Services.MediaService in more Unit Tests

src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertymsg.directive.js
Fixes regression where validation object doesn't always exist on the property, depending on context - when adding an editor to a content type, the validation logic runs, but the validation property on the editor doesn't exist.
Changes here add an explicit check for `currentProperty.validation` before trying to access `.mandatory`
This relates to the changes from #7662 - ping @poornimanayar since she's across those changes 😄 
To test, edit a content type, adding a new property editor, should be no JS errors logged into the console. Validation should clear as expected when editing the property value on a content item.
=> Fix regression from valpropertymsg directive changes

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
Fix ngdoc description for templateEditor fn => description previously referred to user group picker, should be `template editor`. Quick n easy.
=> Update editor.service.js ngdoc for templateEditor fn

src/Umbraco.Web.UI.Client/src/less/rte.less
If there's an existing issue for this PR then this fixes #7576
As described in #7576, all overlays (style picker, link picker, media picker, embed, macro picker, ...) are hidden behind the RTE when it is in fullscreen mode. This PR fixes it. 
All credits go to @thomashdk for the CSS fixes 👏 
Here's the RTE in fullscreen mode with this PR applied:
=> V8: Fix overlays in fullscreen RTE

src/Umbraco.Web.UI.Client/src/views/dashboard/dashboard.tabs.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes #7590
#7590 outlines the issue quite well. 
The root cause is that the listview assumes it should show content at root if no ID is passed to the listview in `$routeParams.id` (kudos to @stevemegson for investigating). _That is a really dangerous assumption!_
This PR removes that assumption. As a result the listview remains in a loading state because nothing ever loads. 
It is also possible to make the listview appear empty (remove the loading state), but the loading state seems like the better alternative. After all, this is an exception state that _Should Not Happen™_.
I tried getting rid of the layout switcher and search input while the listview is in loading state, but that makes it impossible to search for anything at all in any …
=> V8: Ensure that the recycle bin doesn't delete content at root

src/Umbraco.Web.UI.Client/src/less/components/umb-mini-search.less
When the listview search input field is collapsed it should probably have a pointer cursor because it looks and acts like a button - right now the cursor is the default input field cursor:
With this PR applied the cursor is a pointer by default and turns into an input field cursor when the search field is expanded:
=> V8: Correct cursor for list view search icon

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
It shouldn't be possible to create new content in the recycle bin. Hence the context menus for deleted items do not contain a "Create" option:
But deleted content with listview enabled still allows creation of new content:
That's silly 😄 so this PR removes that option. Turns out this also saves an XHR since we no longer need to fetch the allowed child content types for the current (deleted) content item:
1. Verify that you can still create new content from list views for non-deleted content items.
2. Verify that that you can no longer create new content from list views for deleted content items.
=> V8: Remove create option in listviews for deleted content

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If Nested Content is configured with only one element type, the editor only lets you add a single item - regardless of any upper (or lower) limit being set or not.
The workaround: Add the items one at a time and reload the browser window between adds 😆 
This PR fixes the problem.
=> V8: Nested Content can't add multiple items 

src/Umbraco.Web.UI.Client/src/navigation.controller.js
If there's an existing issue for this PR then this fixes #7674
This PR ensures that `mculture` is set correctly again when you login after having logged out (on a multi lingual site).
1. Open a new browser window and login to Umbraco.
2. Verify that `mculture` is set correctly and that the content tree reflects `mculture`.
3. Change `mculture` to something else in the language selector.
4. Logout.
5. In the same browser window, login again.
6. Verify that `mculture` is set to one selected in step 3 and that the content tree reflects it.
7. Change `mculture` again. 
8. Logout.
9. Reload the browser window.
10. In the same browser window, login again.
11. Verify that `mculture` is set to one selected in step 7 and that the content tree reflects it.
=> V8: Make sure mculture is set after logout and login

src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If your content type has a Nested Content property that's configured in single mode (at least I believe single mode is the culprit here), the content type editor throws an endless series of JS errors in the console:
This is related to the preview of the Nested Content property and does not happen when Nested Content is configured with multiple element types.
1. Create a Nested Content datatype configured with only one element type (a.k.a. single mode).
2. Add the property to a content type and save.
3. Reload the content type editor and have a look at the JS console.
=> V8: Fix JS errors for Nested Content in single mode

src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
If there's an existing issue for this PR then this fixes #7571
The changes added to aid newcomers in #6573 don't exactly work; the create dialog on empty installs still looks very very empty:
This PR fixes it, so the create dialog actually helps newcomers get on with creating content types:
The "Create a new document type" of course only shows if the current editor has access to the Settings section.
If a one or more content types do exist but none are marked as allowed at root, the create dialog contains this message:
=> V8: Fix the create dialog on empty installs (help newcomers)

src/Umbraco.Web/JavaScript/AssetInitialization.cs
If there's an existing issue for this PR then this fixes #7578
See an excellent issue description in #7578. 
1. Add a folder under `App_Plugins` containing a `package.manifest` file with the following contents:
```
{
javascript: [
""
]
}
```
2. Restart the site.
3. Verify that the JS console remains error free.
=> V8: Empty asset URLs in plugin manifests should not break the backoffice

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
I'm not sure why the "Field is mandatory" label for properties isn't set as a label for the toggle button... it seems odd, specially with the recently introduced custom error message text field below:
This PR changes things around so the label becomes part of the toggle button:
=> V8: Align "Field is mandatory" label with the toggle button

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js, src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
The content links on the Info app for culture invariant content always seem to show specific culture indicators, even there is only one culture that applies:
This seems a bit silly, so this PR removes those culture indicator unless there's an actual culture difference between the content links:
1. Create a site with only one language.
2. Edit any content on the site.
3. The culture indicators are shown.
1. The steps above should not yield any culture indicators for the content.
2. Adding a second language *and* binding a hostname to that language should result in hostname specific culture indicators for the same content.
=> V8: Only show culture for content links if there is more than one culture

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
It doesn't take a whole lot of effort to make the rollback panel overflow due to the content of the diffs:
This PR turns the panel from `small` to `medium` to give a little more space for the diff:
=> V8: Open rollback in a medium sized panel

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
If content contains properties of type numeric or decimal (and possibly more), the rollback dialog logs errors in the JS console and the "Rollback" button never gets enabled:
For content with a numeric or decimal property:
1. Enter a value in the numeric/decimal property.
2. Save the content.
3. Reload the browser window.
4. Attempt to rollback the content to a previous version.
This PR ensures that the diff is always performed on string values, thus fixing the error and re-enabling rollback for the content:
=> V8: Rollback fails for content with numeric or decimal property values

src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
If there's an existing issue for this PR then this fixes #7377 
Per the issue description, this PR fixes the bug where (infinite) editing an image from a new (unsaved) content item causes a broken route change, causing a 404, causing a UI error message to display.
The bug was caused by calls to a few methods not required when editing in infinite mode (eg syncing the tree, updating editorState), which then caused unexpected behaviour by updating the ID in the route to that of the edited media item rather than the current content item, which threw the 404. I've fixed this by shifting the non-infinite bits behind the existing infiniteMode check. All seems to be working fine, both editing media in infinite and inline mode, and from new or existing content items.
Other changes in the PR remove …
=> V8: fix route change issue when editing image on new node

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes #7126
Fix for #7126. 
Notice that the issue described in #7126 is not limited to the grid RTE, but is applicable to any RTE.
1. Create some content with an RTE and add an image to this RTE.
2. Save the content.
3. Log out.
4. Log back in and open the previously created content.
5. Select the image in the RTE and open it for editing (by clicking the Media Picker toolbar item).
6. Verify that the image is opened for editing with no errors in the JS console.
=> V8: Make sure the media picker can survive a logout and subsequent login

src/Umbraco.Core/PropertyEditors/DataEditor.cs
Based on #7709, I think it makes good sense to make the `DataEditor.GetValueEditor` method virtual, so it can be overridden by classes inheriting from the `DataEditor` class.
Overriding the method could then be something like:
```csharp
public override IDataValueEditor GetValueEditor(object configuration)
{
var editor = base.GetValueEditor(configuration);
if (editor is DataValueEditor valueEditor && configuration is MyConfiguration config)
{
valueEditor.HideLabel = config.HideLabel;
}
return editor;
}
```
For testing that the overriden method is actually hit, I made this custom property editor:
```csharp
using Umbraco.Core.Logging;
using Umbraco.Core.PropertyEditors;
using Umbraco.Web.PropertyEditors;
namespace Umbraco.Web.Test{
[DataEditor("Test", EditorType.PropertyValue, "Test", …
```
=> Making DataEditor.GetValueEditor method virtual

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
If there's an existing issue for this PR then this fixes #7313
The problem described in #7313 basically happens because the treepicker loads all languages by default, in case it is configured to display an embedded language picker. 
If it isn't configured to do that (which is the default), those loaded languages are never used. So it seems really silly to load them, specially as they're now causing problems. 
This PR ensures that the languages are only loaded if they're required by the treepicker configuration. When applied, the MNTP starts behaving like you'd expect it to - both with and without start nodes configured:
*Note: In reality the problem described in #7313 is dependent on client rendering timing. Sometimes the languages are loaded before the treepicker fetches its nodes, …
=> V8: Don't load languages in treepicker unless they're needed

src/Umbraco.Core/Composing/CollectionBuilderBase.cs, src/Umbraco.Tests/Composing/CollectionBuildersTests.cs
CollectionBuilder's are responsible for registering all plugin types along with many other things in Umbraco. Each collection builder defines it's own lifetime, by default this is Singleton, however as it turns out the collection builder doesn't register the individual items in the container with the same lifetime declared on the collection and they will always end up being Transient. 
This is unexpected behavior since one would assume that if a dependency on an individual item was taken that it would be resolved with the same lifetime as the container that it was registered against. Else an entirely different instance of an item can be resolved than what is contained within it's collection which could cause odd things to happen.
Example: You create and register a custom IContentFinder. …
=> Fixes CollectionBuilder's to ensure that each item in the collectionis registered in DI with the same lifetime as the collection itself

src/Umbraco.Core/Events/UserGroupWithUsers.cs, src/Umbraco.Core/Services/Implement/UserService.cs
If there's an existing issue for this PR then this fixes #7720 
Changes [Saving|Saved]UserGroup events in UserService from internal to public
Looks like these were always intended to be public, but got mixed up in the 7=>8 changes. Have also had to make UserGroupWithUsers public as it's referenced by the event so must be equally accessible.
Have verified by adding an event handler in an existing Composer in Umbraco.Web, events are raised, parameters are correct.
=> 7720 - make internal UserService events public

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
In the latest `v8/contrib` log into back office -> settings -> go to a grid data type config or RTE config, the options looks very messed up.
=> RTE config tool bar options are messed up

src/Umbraco.Core/Persistence/Repositories/Implement/EntityRepository.cs
#7066 introduced `GenericContentEntityDto` for use in `EntityRepository` when fetching paged search results (`GetPagedResultsByQuery`). 
Unfortunately the `MediaPath` property of `GenericContentEntityDto` isn't mapped to the media search results entities. This leaves the thumbnails empty when searching for media in the media picker:
...and adds a bunch of matching warnings in the JS console:
With this PR applied, the image thumbnails are shown as you'd expect:
=> V8: Show image thumbnails for media picker search results (regression)

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
If there's an existing issue for this PR then this fixes #6845
The media picker overlay is currently `small` sized:
This PR makes the media picker open up in a `medium` sized overlay, thus giving more space picking items... particularly useful if you have a lot of media in a folder:
=> V8: Make media picker open in a medium sized overlay

src/Umbraco.Web.UI.Client/src/views/contentblueprints/create.html
As suggested [here](https://github.com/umbraco/Umbraco-CMS/pull/7020#issuecomment-593055598) I have added `type` attribute to `button` and taken away the `prevent-default` attribute.
Mentioning @abjerner as he tested the other PR :-)
=> Create Content Blueprints - Semantic fixes

src/Umbraco.Web.UI.Client/src/views/contentblueprints/create.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html
As suggested [here](https://github.com/umbraco/Umbraco-CMS/pull/6949#issuecomment-593084629) I have added `type` attribute to `button` and taken the `prevent-default` away.
Mentioning @abjerner as he tested the other PR
=> Semantic fixes grid pre values

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes #7739
If you open a media picker from an RTE and upload a new image, the media picker _should_ automatically pick the uploaded media. But it doesn't... instead it throws an error in the JS console.
This PR ensures that the "Edit selected media" dialog is opened after uploading an image in the media picker when it's opened from an RTE:
...and at the same time it fixes the broken "auto select newly uploaded images" in the media picker when it's opened from a media picker property:
=> V8: Fix broken "upload and insert media" in RTE

src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
#7449 introduced some rewriting of the media picker controller to replace lodash methods with native es6 equivalents. For reasons I can't really explain, this has resulted in a completely broken(™) media picker where every picked item renders as trashed even though they're really not:
Moving the code comment outside the one-liner in `.find()` solves it, and brings back the picked items:
=> V8: Fix completely broken(tm) media pickers

src/Umbraco.Web/Routing/ContentFinderByNiceUrlAndTemplate.cs
See https://our.umbraco.com/forum/using-umbraco-and-getting-started/98220-help-with-error-message
It's possible to load a published node via an alternative template by requesting it in the format:
/about-us/our-staff/staffgridlayout
where '/about-us/our-staff/' is the node in Umbraco and 'staffgridlayout' is the alias of the alternative template you want Umbraco to load the content with.
This is implemented by the ContentFinderByNiceUrlAndTemplate Content Finder...
... this is kind of a hidden feature of Umbraco that's been there for years...
Anyway the way this is implemented assumes that if the 'last portion of a url' matches a template, then the request must be a valid request trying to make use of this convention so
/orangey/crows/staffgridlayout
would cause the Content Finder to try …
=> v7: Fix false matches for AltTemplate convention Urls

src/Umbraco.Web/umbraco.presentation/content.cs
If there's an existing issue for this PR then this fixes #6629
Removing a document from the in-memory XML cache also removes it (and all its descendants) from the in-memory XML cache for preview, so it is no longer possible to preview the descendants.
Testing:
- Unpublish a page which has some descendants
- Preview one of the descendants, you should get a correct preview rather than a 404.
=> V7: Don't call ClearPreviewXmlContent from ClearDocumentXmlCache

src/Umbraco.Web/Composing/Current.cs, src/Umbraco.Web/Models/RegisterModel.cs, src/Umbraco.Web/UmbracoHelper.cs
This PR obsolete some of the properties on UmbracoHelper that is removed in the .NET Core branch.
- `ContentQuery`
- `TagQuery`
- `CultureDictionaryFactory`
- `ComponentRenderer`
- `MembershipHelper`
=> Obsoleting UmbracoHelper properties

src/Umbraco.Web.UI.Client/src/less/forms.less
Stop using umb-outline for select — cause it does not work for select input.
=> 7434 do not use umb outline for select

src/Umbraco.Core/Cache/DeepCloneAppCache.cs, src/Umbraco.Core/Cache/DictionaryAppCache.cs, src/Umbraco.Core/Cache/FastDictionaryAppCache.cs, src/Umbraco.Core/Cache/FastDictionaryAppCacheBase.cs, src/Umbraco.Core/Cache/HttpRequestAppCache.cs, src/Umbraco.Core/Cache/IAppCache.cs, src/Umbraco.Core/Cache/NoAppCache.cs, src/Umbraco.Core/Cache/ObjectCacheAppCache.cs, src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs, src/Umbraco.Infrastructure/Runtime/WebRuntime.cs, src/Umbraco.Infrastructure/Scoping/Scope.cs, src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs, src/Umbraco.Tests/Cache/AppCacheTests.cs, src/Umbraco.Tests/Cache/DeepCloneAppCacheTests.cs, src/Umbraco.Tests/Cache/HttpRequestAppCacheTests.cs, src/Umbraco.Tests/Cache/ObjectAppCacheTests.cs, src/Umbraco.Tests/Macros/MacroTests.cs, src/Umbraco.Tests/Models/ContentTests.cs, src/Umbraco.Tests/Persistence/Repositories/DocumentRepositoryTest.cs, src/Umbraco.Tests/Persistence/Repositories/MediaRepositoryTest.cs, src/Umbraco.Tests/Published/PropertyCacheLevelTests.cs, src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Tests/PublishedContent/NuCacheTests.cs, src/Umbraco.Tests/Routing/RenderRouteHandlerTests.cs, src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs, src/Umbraco.Tests/Scoping/ScopedRepositoryTests.cs, src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs, src/Umbraco.Web/Umbraco.Web.csproj, src/Umbraco.Web/UmbracoApplication.cs, src/Umbraco.Web/UmbracoApplicationBase.cs
- Moved `WebRuntime` to Infrastructure
- Updated ` void ClearOfType(string typeName);` in `IAppCache` to ` void ClearOfType(Type type); ` to not have reference on TypeFinder
- Injected `WebProfiler` in `WebRuntime`
- Move initialized of `Current.Factory` out of  `WebRuntime`
=> NetCore: Make WebRuntime netstandard compatible

src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentCache.cs
The problem was located in:
```c#
namespace Umbraco.Web.PublishedCache.NuCache
{
internal class ContentCache : PublishedCacheBase, IPublishedContentCache, INavigableData, IDisposable
{
private static IEnumerable<IPublishedContent> GetByXPath(XPathNodeIterator iterator);
}
}
```
The returned enumerable build all enumerators from the same iterator.
Which causes issue #7798 
The only change I've made is to clone the iterator first to allow all enumerators to have their own iterator.
I've added a unit to test to check this fix:
```c#
[Test]
public void MultipleCacheIteration()
{
//see https://github.com/umbraco/Umbraco-CMS/issues/7798
this.Init(this.GetInvariantKits());
var snapshot = this._snapshotService.CreatePublishedSnapshot(previewToken: null);
this._snapshotAccessor.PublishedSnapshot = …
```
=> Fixes #7798 : Invalid implementation of IEnumerable in Content Cache

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsections.directive.js, src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
Hi! This is my first contribution.
This change is as a result of #7797 in which it was observed that a maximum of 8 navigation items are shown at the top of the dashboard even if room is available for more.
I removed the limit and adjusted the existing code to calculate the remaining space and show as many as possible.
To test, navigate to the dashboard and resize the browser width. Any items too large to fit in the navigation container will be hidden behind the "..." menu.
You can add extra navigation items for testing by editing line 26 in src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsections.directive.js as so
`scope.sections = [...result, {alias: 'test', name: 'Test', routepath: null}];`
If the active page is hidden in the overflow menu, both the overflow …
=> Collapse navigation items based on container size

src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Add exakt 10 users and disable them. The disable filter should be there. 
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7780 
There where a ng-repeat filter that removed filters that hade count = a 0 in it. So 0, 10, 20, 30 and so on did not be visible. Now we romove that filter and use a ng-show with a count more then zero. We could fix this with a custom filter but i don´t think that is not nessasary for this problem. ng-if dont work for we cant have both ng-repeat and ng-if.
=> #7780 Show all filters that is more then 0 hits

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
Following the discussion in #7754, I've updated the grid property editor so it's now using the `overlayService` instead of the deprecated `umbOverlay` directive.
=> Implemented fix for #7754

src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js, src/Umbraco.Web.UI.Client/src/routes.js
Ran a duplication report against the backoffice code. - https://gistpreview.github.io/?600a4f0c2847e37197beba1579403bf6 expand all works no other buttons do.
(raw: https://gist.github.com/Matthew-Wise/600a4f0c2847e37197beba1579403bf6)
Which highlights "copy paste" code. 
Whilst finding a good location to remove the duplication I also found similar code in the navigation service so created a new method they could all use.
Tested this change using the members -> All members route
=> Removed duplications of tree routing

src/Umbraco.Web/HtmlStringUtilities.cs
Fixed the elipsis issue, only adds an elipisis if the text length exceeds the length that is being truncated too.
If there's an existing issue for this PR then this fixes #7728 
Updates the Truncate method, only adds the elipsis if the length of the string passed in exceeds the truncate amount.  If they are equal then no elipsis is added.
=> 7728 - show elipsis only when > length

src/Umbraco.Core/Persistence/Repositories/Implement/StylesheetRepository.cs, src/Umbraco.Tests/Persistence/Repositories/StylesheetRepositoryTest.cs, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
If there's an existing issue for this PR then this fixes #7713 
This is a file system security exception, thrown when the requested file is outside the scope of the current file system's root. The CSS files still exist, we're just not permitted to access them. The exception bubbles up into the backoffice, and the RTE dies. 
Changes here wraps a try-catch around the file-exists check in the stylesheets repo. If the check fails, or throws, the stylesheet request returns null, and it's business as usual in the RTE, just without the requested CSS. 
I don't know how often a dev would be changing the CSS directory on an established site, but this will suppress the error.
Have added a bit of cleanup code in the rte prevalues, nothing flash, but filters out assigned CSS from the RTE config when …
=> 7713 - changing CSS directory breaks RTE

src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-group.less
If there's an existing issue for this PR then this fixes #7716
I removed the border radius from the right of umb-button when used inside a umb-button-grp. The dropdown toggle was underlapping the button slightly so I moved it right 1 pixel.
To test, visit the user management section and observe the "Invite user" button at the top of the page.
I have some more free time this week. If there are any pressing issues that you need help with, let me know. I'm comfortable working on your backend too. Thanks!
=> Remove button border radius when used in a button group

src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs, src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/AddPackagesSectionAccess.cs, src/Umbraco.Core/Umbraco.Core.csproj
Version 8 promotes Packages from a tree in the Developer section to a section of its own, but when migrating from v7 no users will have access to the new section. This PR ensures that any user group which could access the Developer section in v7 is granted access to the Packages section in v8.
Testing:
- In 7.15.3, ensure that you have access to the Developer section.
- Migrate to v8.
- Check that you can access the Packages section.
=> Grant access to Packages section for any user groups with access to the Developer section

src/Umbraco.Core/Cache/WebCachingAppCache.cs
This fixes a memory leak in the `WebCachingAppCache` which is the implementation of `IAppPolicyCache`
It turns out we were allocating an instance of `CacheDependency` any time `Insert` or `Get` was called even if we weren't going to insert/add to the cache. So a new instance of `CacheDependency` was allocated for every Get. But one object allocation isn't the end of the world ... normally. Turns out that this particular ugly object in .NET Framework runs a lot of code in it's constructor and allocates more objects. 
I ran the test mentioned in #7773 with 1,000,000 iterations before the fix and the code took roughly 20 seconds to execute. With the fix and 3,000,000 iterations it took a couple seconds and there's no more memory leak. It seems that just creating a CacheDependency instance …
=> Fixes Memory Leak in GetCacheItem cache dependency #7773

src/Umbraco.Web/HealthCheck/NotificationMethods/EmailNotificationMethod.cs
If we remove the `<notificationMethod alias="email" ...>` element from the `HealthChecks.config` then Settings is null in EmailNotificationMethod constructor.
Just added a check on Settings if it's null then the NotificationMethod disabled itself (same behavior that when there is no `recipientEmail`)
=> Fix #7521 - Runtime error if removing email notificationMethod

src/Umbraco.Core/Models/Blocks/BlockListLayoutReference.cs, src/Umbraco.Core/Models/Blocks/BlockListModel.cs, src/Umbraco.Tests/PropertyEditors/BlockListPropertyValueConverterTests.cs, src/Umbraco.Web.UI/Views/Partials/BlockList/Default.cshtml, src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
This reverts this final commit 45e892f3505059674779c6e1a43084a367c2862f
in this PR #7557 so you use .Data property and not a GetData() method
=> Revert GetData() in Block Editor List model

src/Umbraco.Infrastructure/WebAssets/Resources.resx
Resolves build error on case sensitive file systems
ResXFileRef should match path on filesystem
```
error MSB3103: Invalid Resx file. System.IO.FileNotFoundException: Could not find file '/home/example/Dev/Umbraco-CMS/src/Umbraco.Infrastructure/WebAssets/jsinitialize.js'.
```
=> Netcore: Alter ResXFileRef to match filesystem

src/Umbraco.Core/Models/PublishedContent/PublishedContentType.cs
If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/7919.
This updates the `EnsureMemberProperties` method to use the correct data type IDs, so no exceptions are thrown while generating models using Models Builder.
=> Fix EnsureMemberProperties data type IDs

src/Umbraco.Web/PropertyEditors/MediaPickerPropertyEditor.cs
Resolves #7879 
When trying to resolve the media references for a Media Picker property editor, it splits the value on commas before trying to create a UDI.  If there are multiple media items picked, this will ensure that all picked items get recorded as media references.
=> 7879: Handle for multiple picked media relations

src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js, src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
https://github.com/umbraco/Umbraco-CMS/issues/7658
1. Setup more than one identity provider
2. Login and open up the "user overlay"
3. When clicking either of the connected IDP, it should go to this IDP
=> #7658 Fix linking account if multiple IDP on common user overlay

src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js, src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
https://trello.com/c/HlMCIyiH/11-replace-instances-of-angularisdefined
Replaces the angular.isDefined to the Utilities.isDefined as part of the Umbraco's AngularJS divorce
=> angular.isDefined replace to Utilities.isDefined

.github/CONTRIBUTING.md
Renaming PR team in docs  as discussed on #canConHackathon
=> Renaming PR team name in contributing docs

src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less, src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
I have just decided to close #4526 without having it merged in it's current state since the stuff I made no longer works.
Therefore I decided to have a deeper look at some of the root causes to some of the issues I faced when trying to implement the focus lock. One of them being that regular overlays and infinite overlays got triggered from different places within the source code meaning I had to do so weird little hacks to get it working. Move the infinite overlay out of the source order it will be a lot simpler to implement a well working focus lock - So this is what I have done with this PR 😃 
The `<umb-editors>` component has been moved to the same level in the source code as the `<umb-overlay>` component, since it's an overlay too really. I have also removed the `<div …
=> Move the infinite overlay to the same source order as regular overlays

src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html
It looks like to me there is an 'extra' closing div in this markup... but I think this is because the button isn't closed, there is a closing div where the closing button should be? - eg the icon and span are part of thee button... I've made this change locally and it operates fine, but then it operating fine before hand too...
If there's an existing issue for this PR then this fixes - there isn't one
Was just looking at the markup for the umb layout selector directive to try to fathom how to use it elsewhere, and spotted an additional closing div... which led me to conclude there is in fact a missing closing button tag...
You can view the layout selector in the Media section of Umbraco, it's used to switch between grid and list view...
=> V8-Layout Selector Directive - Button tag isn't closed? leaving invalid markup

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbrawmodel.directive.js, src/Umbraco.Web.UI.Client/src/common/resources/auth.resource.js, src/Umbraco.Web.UI.Client/src/common/resources/currentuser.resource.js, src/Umbraco.Web.UI.Client/src/common/services/macro.service.js, src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js, src/Umbraco.Web.UI.Client/src/common/services/util.service.js, src/Umbraco.Web.UI.Client/src/utilities.js, src/Umbraco.Web.UI.Client/test/unit/utilities.spec.js
https://trello.com/c/UTjBLFQd/17-replace-instances-of-angulartojson
Decouples angulars toJson to es6 this is a direct port of the angular code to ensure we keep its features. I also ported the unit tests to make make testing easier for everyone.
Matt
=> Replaced angular.toJson with Utilities.toJson [#CanConHackathon]

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/fixnumber.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/tags/umbtagseditor.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js, src/Umbraco.Web.UI.Client/src/common/filters/umbwordlimit.filter.js, src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js, src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js, src/Umbraco.Web.UI.Client/src/common/resources/member.resource.js, src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js, src/Umbraco.Web.UI.Client/src/common/services/macro.service.js, src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js, src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js, src/Umbraco.Web.UI.Client/src/common/services/servervalidationmgr.service.js, src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js, src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js, src/Umbraco.Web.UI.Client/src/navigation.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js, src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
This PR replaces the use of `angular.isString` in favour of `Utilities.isString` as part of #7718.
=> V8: Angular Divorce: isString

src/Umbraco.Web.UI.Client/src/less/components/application/umb-dashboard.less, src/Umbraco.Web.UI.Client/src/less/components/umb-tabs.less, src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html, src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
This PR improves the markup for the umb-tab used for example in the settings dashboard.
The old version of the code was using anchor tags etc when it should have been using buttons. I've also added some screen reader only text for the more options toggle when on a narrower screen.
The outcome itself visually is minimal, other than only showing the focus state when using the keyboard to navigate via tabbing.
=> improvement: update umb-tabs to use better semantic markup

.github/CONTRIBUTING.md
Adding Git command line to contrib guidelines after an issue someone had at #canConHackathon
=> Adding Git command line to contrib guidelines [#canConHackathon]

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautoresize.directive.js
Working on #7928 I noticed that there was some IE11 related code in this directive and I could not resist the urge to remove it 😄 
However it appears that back in 2015 a bugfix was made adding a check to Edge in the code as well. So I'm not 100% sure it's safe to remove. However I'm not sure how to test if the original Edge issue is still there since https://issues.umbraco.org/issue/U4-7541 is not very descriptive.
But I have not noticed anything looking/acting weird in regards to the resizing in Edge after removing this functionality. But someone might need to do an extra thourough check 😅
=> Remove code that does UA sniffing and explicit stuff for IE11 only

src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
Accessibility fix.
Active tab is visually identified but not for screen readers, this commit provides some auditory cues to the user to ensure they are not lost within the navigation.
The currently selected section is marked as the ARIA current page `aria-current="page"`. This has limited browser/screen reader support so he word "active" is appended to currently selected section for screen readers (with `aria-label`) as well.
To test, enable a screen reader and move along the section links along the top of the page. The currently selected section will indicate it is selected in the auditory description. Changing section should also update the description of the pages. Also test at a smaller resolution so that the section navigation items collapse into a "..." menu as shown below.
=> Append "active" to currently selected section for screen readers

src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
The issue was originally reported as part of another one here https://github.com/umbraco/Umbraco-CMS/pull/7907#issuecomment-610259393
It is not always possible to replicate this issue since it depends on the state that nucache is in and the issue could 'go away' upon site restart or cache rebuilding in some cases.
I've added a unit test to show the problem and then a commit that fixes it. 
The issue is because when a branch is refreshed and there is already more than 1 cache generation created and when there's a hierarchy in the branch, during the recursive call to `ClearBranchLocked` it was passing in `link.Value` but since we are clearing that `Value` within the method, in this exact case `link.Value` will end up being null once the logic returns from the recursion since it's a …
=> Nucache NullReferenceException when copying

src/Umbraco.Core/PropertyEditors/DataEditor.cs
Possible fix for issue: #7870
This reverts DataEditor.GetValueEditor() to not cache the result of CreateValueEditor() via a property. In my testing this has fixed #7870 but I am not sure if it causes other issues. At the very least it might cause a performance degradation.
=> Possible fix for issue #7870

src/Umbraco.Core/Constants-SqlTemplates.cs, src/Umbraco.Core/ContentExtensions.cs, src/Umbraco.Core/Models/ContentDataIntegrityReport.cs, src/Umbraco.Core/Models/ContentDataIntegrityReportEntry.cs, src/Umbraco.Core/Models/ContentDataIntegrityReportOptions.cs, src/Umbraco.Core/Persistence/Repositories/IContentRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs, src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs, src/Umbraco.Core/Services/IContentService.cs, src/Umbraco.Core/Services/IContentServiceBase.cs, src/Umbraco.Core/Services/Implement/ContentService.cs, src/Umbraco.Core/Services/Implement/MediaService.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Web/HealthCheck/Checks/Data/DatabaseIntegrityCheck.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs, src/Umbraco.Web/PublishedCache/NuCache/Snap/LinkedNode.cs, src/Umbraco.Web/Umbraco.Web.csproj
Turns out that after investigating this issue https://github.com/umbraco/Umbraco-CMS/issues/7868 which was originally reported as a nucache issue that its actually a data issue. 
Nucache did explode because the data in the umbracoNode table was corrupt but how did that data get like that? Luckily a couple community members were able to provide me databse snapshots of before and after they performed some move operations which seemed to be the trigger for seeing errors. More lucky, i was able to replicate the problem locally.
So it turns out we have a bug in the moving logic for both media and content and this same logic is used to delete stuff (move to the bin). The bug only rears it's head if there's a lot of stuff being moved in one operation (i.e. if there are a lot of descendant …
=> Fix moving large amounts of content/media

src/Umbraco.Core/Persistence/NPocoDatabaseExtensions.cs, src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
This is similar to the problem mentioned in v7 preview here https://github.com/umbraco/Umbraco-CMS/issues/7574
When a site cold boots or rebuilds nucache from scratch by querying the DB, if there's a ton of data in the database this could lead to an Sql timeout exception. When we read this data in we use a db reader (cursor) so we don't load all of the data into memory at once (to preserve memory) but this means the connection may stay open longer. Because of that, we should be paging over the data using a db reader. This PR updates this behavior to read in by pages of size 500. 
When in PureLive and a content type is changed, the content/media nucache needs to rebuild from the database data which is also a factor in when sql timeouts can occur. This paging will alleviate that issue but …
=> In Nucache when we are loading in all data that we page over the data as to not cause an SQL timeout

src/Umbraco.Core/Runtime/SqlMainDomLock.cs
Fixes SqlMainDomLock when configured via appSettings cannot be used unless umbraco is installed #7967
=> Fixes #7967 - cannot start site with SqlMainDomLock  when db isn't configured

build/NuSpecs/tools/Views.Web.config.install.xdt
The Models Builder namespace was changed from `Umbraco.Web.PublishedContentModels` to `Umbraco.Web.PublishedModels` in V8...
It seems one of the transforms for `Views/web.config` wasn't updated - so I've done just that!
Weirdly the line I have updated doesn't appear in the `Views/web.config` in my projects, so I don't think this file is even used anymore... 🤷‍♂️
=> Update Models Builder model namespace in Views/web.config

src/Umbraco.Core/Services/UserServiceExtensions.cs, src/Umbraco.Examine/ContentValueSetBuilder.cs, src/Umbraco.Tests/Services/UserServiceTests.cs, src/Umbraco.Tests/UmbracoExamine/IndexInitializer.cs, src/Umbraco.Tests/UmbracoExamine/IndexTest.cs, src/Umbraco.Tests/UmbracoExamine/SearchTests.cs, src/Umbraco.Web/Search/ExamineComposer.cs
Fixing Nasty Exception with Scope/Provider #5151
To replicate this problem it seems that you would need to individually re-index a lot of documents in one operation (i.e. like transferring a lot with Deploy). 
This is actually only a guess at the problem/solution but I think it's correct. The underlying exception is: 
```
System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Umbraco.Core.Scoping.ScopeProvider.SetCallContextObject(String key, IInstanceIdentifiable value)
at Umbraco.Core.Scoping.ScopeProvider.SetAmbient(Scope scope, ScopeContext context)
at …
```
=> Fixing Nasty Exception with Scope/Provider #5151 - when indexing data

src/Umbraco.Core/Models/PublishedContent/ILivePublishedModelFactory.cs, src/Umbraco.Core/PublishedModelFactoryExtensions.cs, src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs, src/Umbraco.Web/PublishedCache/PublishedSnapshotServiceBase.cs
When MB is disabled we were still rebuilding all of nucache linked list data when schema changes are made which is a requirement of PureLive models, but if MB is disabled then PureLive models don't matter. This was causing unnecessary performance and db overhead when modifying document types when mb is disabled.
This is all done with no breaking changes by adding an additive interface: `ILivePublishedModelFactory2` which fixes a TODO that should have been cleared in 8.3 but we are getting to it now and also allows for us to know if the ILivePublishedModelFactory is enabled or not.
=> ModelsBuilder enabled flag not respected

src/Umbraco.Web/UmbracoApplication.cs
Add GetMainDom method to UmbracoApplication so GetRuntime can be overridden.
Prior to v8.6 you could implement a custom web runtime (see https://github.com/umbraco/UmbracoDocs/blob/master/Getting-Started/Code/Debugging/Logging/index.md#advanced) however since changes to allow swapping of the MainDom in v8.6 you can no longer do this, so this PR returns this ability.
That example in the docs would become
```csharp
protected override IRuntime GetRuntime()
{
var logLevelSetting = ConfigurationManager.AppSettings["YourMinimumLoggingLevel"]; //Warning, Debug, Information, etc
const bool ignoreCase = true; //this is to clarify the function of the boolean second parameter in the TryParse
if (!Enum.TryParse(logLevelSetting, ignoreCase, out LogEventLevel minimumLevel))
{
minimumLevel = …
```
=> Add GetMainDom method to UmbracoApplication

src/Umbraco.Web/Editors/ExamineManagementController.cs
when we rebuild indexes in the back office we are actually calling index.CreateIndex() 2 times before populating.
This code is simple, don't call `index.CreateIndex();` because it is called inside `_indexRebuilder.RebuildIndex(indexName);`
=> Don't re-create indexes twice when rebuilding in the back office

build/NuSpecs/tools/Views.Web.config.install.xdt, src/Umbraco.Core/Runtime/SqlMainDomLock.cs, src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs, src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less, src/Umbraco.Web/Editors/ExamineManagementController.cs, src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
Fixes: SqlMainDomLock setting for Azure does not work in Load Balancing #8038
The reason this doesn't work in LB is because there is only a single 'key' for the database table `umbracoKeyValue` to use for this lock which means only a single server/app can be registered for this distributed lock. 
The purpose of MainDom is to synchronize access to certain resources between concurrent AppDomains. This means that the lock needs to be specific to one web application on one web server. This is exactly what the original MainDom did with it's system wide semaphore lock. This would work in load balancing (outside of azure) because implicitly a system-wide semaphore lock is machine specific. This Sql lock needs to take into account this same uniqueness.
So now it does, the key in the DB is a …
=> Fixes SqlMainDomLock setting for Azure does not work in Load Balancing #8038

src/Umbraco.Web.UI.Client/bower.json
This PR addresses issue #8052 
TinyMCE is due to be upgraded in the next Umbraco V7 release to V4.9.9 with PR #7945 (TinyMCE release 25th March 2020). There has since been another release of TinyMCE including an update which address a security bug with version 4.9.10 (released April 23rd 2020 - https://www.tiny.cloud/docs-4x/changelog/#version4910april232020).
This PR updates TinyMCE to v4.9.10 for Umbraco v7.
=> v7 Upgraded TinyMCE to 4.9.10

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
It was raised in #6477 that the last edited field on the default members list view doesn't allow sorting.
This PR adds that ability.
Also fixes a minor issue that when adding the content type.
=> Allows members to be ordered by last edited field

src/Umbraco.Web.UI.Client/lib/angular/1.1.5/angular-mobile.js, src/Umbraco.Web.UI.Client/src/index.html, src/Umbraco.Web.UI/umbraco/Views/Default.cshtml
If there's an existing issue for this PR then this fixes #4934, #6023
V7 version of PR #6203.
Additionally, stops swipe events triggering from mouse events. This can also trigger unexpected dialog closes, and can make it impossible to select text when mousemove events are intercepted.
Testing:
- As for PR #6203
- Also, check that you can select text on the login screen.
=> V7: Selecting text in context menu closes the dialog

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js, src/Umbraco.Web.UI.Client/src/common/services/servervalidationmgr.service.js, src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
This PR makes sure that validation indication in variant-picker only stays as long as an error is present. Plus avoid displaying field-errors, we only want to use property errors for this indication.
This PR is an addition to the work for Segments, the reason for this PR to target this is that Segments will soon be merged and include a ton of changes to variant-picker. This way we minimize merge errors.
fixes https://github.com/umbraco/Umbraco-CMS/issues/7964
---
_This item has been added to our backlog [AB#6512](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6512)_
=> UI: Corrected validation indication in variant-picker

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbrawmodel.directive.js, src/Umbraco.Web.UI.Client/src/common/mocks/resources/_utils.js, src/Umbraco.Web.UI.Client/src/common/services/util.service.js, src/Umbraco.Web.UI.Client/src/utilities.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.controller.js, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js, src/Umbraco.Web.UI.Client/test/unit/utilities.spec.js
This previous PR https://github.com/umbraco/Umbraco-CMS/pull/7952 replacing `angular.fromJson` from `JSON.parse` seems to fail as `angular.fromJson` also checked in the value passed in was equal to an string value.
https://github.com/angular/angular.js/blob/master/src/Angular.js#L1335-L1339
E.g. when inserting an image editor in grid content it is causing an console error, when session storage is empty.
Furthermore we now have a `Utilities.toJson()` function https://github.com/umbraco/Umbraco-CMS/pull/7924 so I think we should have an `Utilities.fromJson` as well.
You can of course always use the traditional `JSON.parse` inside a `try/catch` block in e.g, but this method (similar to the `angular.fromJson()` only try to parse the …
=> Add utility function equivalent to angular.fromJson

src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
Fix for #7758 
Description about the problem and steps to reproduce/test can be found in #7758!
The error that a user with no dashboards was getting when logging in, was that we were trying to get a missing required value parameter (`application`) from the query string -> [code ref](https://github.com/umbraco/Umbraco-CMS/blob/d7469e6576fbe4bf4d23f9046399b3899c0ff58c/src/Umbraco.Web/Trees/ContentTreeControllerBase.cs#L335). 
I suspect that passing `null` as the value of the `queryString` when `hasDashboards` is **false** (in `GetSections()` in the [SectionController.cs](https://github.com/umbraco/Umbraco-CMS/blob/d7469e6576fbe4bf4d23f9046399b3899c0ff58c/src/Umbraco.Web/Editors/SectionController.cs#L60)) might not be the right approach but just to be sure we now check if the `queryString` …
=> Preventive check that will enable sections load for users with no dashboards

src/Umbraco.Web.UI/Umbraco/config/lang/en.xml, src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Adding keys in lang file for custom events. so we can have text and parameters show. 
I've set the custom key to %0% which means the text will be what ever is entered in as parameters in the umbracoLog table for the custom event.
Issue #8050
=> Add keys for custom audit events #8050

src/Umbraco.Web.UI.Client/package.json
This PR addresses issue #8054 
TinyMCE has had an update (version 4.9.10) that includes addressing a security issue (released April 23rd 2020 - https://www.tiny.cloud/docs-4x/changelog/#version4910april232020).
This PR updates TinyMCE to v4.9.10 for Umbraco v8.
=> v8 - Upgraded TinyMCE to 4.9.10

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
This PR addresses issue #8082 
Adds an `ng-trim="false"` attribute to the textarea property editor so that character count functionality updates when the last character of the input is a space. This attribute is present on the textstring property editor which works as expected. 
This can be tested by creating a textarea property with a character limit and entering a number of spaces once the character count appears and observing that it updates with each new character entered.
Newbie PR here, so please shout if I've done something wrong or put something in the wrong place! 👍
=> Adding ng-trim="false" attribute to textarea property editor

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
The (very nicely) revamped data type picker suffers from "double tabbing" when you tab your way through the available datatypes:
And if you happen to hit enter on the innermost focused element of a datatype, you'll get duplicate "Select configuration" dialogs:
This PR shuffles some click handlers around, ensuring that only the innermost elements (the `a` tags) can receive keyboard focus. When applied it's much easier to tab your way through the datatype picker:
=> Remove "double tabbing" in the datatype picker

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypeconfigurationpicker/datatypeconfigurationpicker.html
The datatype configuration picker has a few minor issues:
1. When the datatype configuration picker opens, it does not apply focus to itself. Thus if you use tab to navigate through the available datatype configurations, you're tabbing around behind the overlay. 
2. If you manually set focus in the dialog, it suffers from the same "double tabbing" issues as the datatype picker (see #8102).
3. Lastly the create button hover title is "Create a new configuration of" - it's missing the name of the data type editor.
This PR ensures that the dialog captures focus on load, and fixes the other small issues as well:
=> Enable navigating datatype configuration picker by keyboard

src/Umbraco.Tests/Web/Controllers/ContentControllerTests.cs, src/Umbraco.Tests/Web/ModelStateExtensionsTests.cs, src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js, src/Umbraco.Web/Editors/ContentController.cs, src/Umbraco.Web/ModelStateExtensions.cs
Hi @nielslyngsoe ,
I did some initial work to have validation messages show up in the Save/Publish dialog.
This seems to work pretty well already. I do run into other issues related to Saving/Publishing in general, as you pointed out the `ContentService` does not seem to take segments into account much and will just publish all variants of a culture. So my attention will move to that area next.
However, perhaps you can have a quick look at this when you have time (no rush). Shannon already did some work to add the segment to the ModelState returned from the server. I expanded it a bit, reworked some stuff from `CultureXYZ` to `VariantXYZ` and I believe this already improves things. 
For example, this now renders properly when there are server side validation errors for a segment (except …
=> Validation errors reworked to incorporate segment errors

src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj, src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ContentModelBinderTests.cs, src/Umbraco.Web.Common/Filters/ModelBindingExceptionFilter.cs, src/Umbraco.Web.Common/ModelBinders/ContentModelBinder.cs, src/Umbraco.Web.Common/ModelBinders/ContentModelBinderProvider.cs, src/Umbraco.Web.Common/ModelBinders/ModelBindingException.cs, src/Umbraco.Web.UI.NetCore/Startup.cs, src/Umbraco.Web/Mvc/ContentModelBinder.cs
Relating to issue #7799 
In this PR I've taken the `ContentModelBinder` and related components and migrated them to .Net core.
Am a bit limited by time/understanding/current state of project in terms of what's ported already to properly test it, so really have just translated into the new framework, got everything building and added some unit tests,  Hopefully it's either right or not far off for when other parts are migrated and it can be verified in real use.
=> Netcore: Implemented content model binder.

src/Umbraco.Core/Models/RelationTypeExtensions.cs, src/Umbraco.Core/Umbraco.Core.csproj, src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.html, src/Umbraco.Web/Models/ContentEditing/RelationTypeDisplay.cs, src/Umbraco.Web/Models/Mapping/RelationMapDefinition.cs, src/Umbraco.Web/Trees/RelationTypeTreeController.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8021
This PR lock the core relation types to track content and media, so alias of these relation types is locked and delete action is not available for these. This works similar to the changes in https://github.com/umbraco/Umbraco-CMS/pull/6943
=> Lock core relation types

src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj, src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttributeTests.cs, src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/OnlyLocalRequestsAttributeTests.cs, src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/ValidationFilterAttributeTests.cs, src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ModelBinders/ContentModelBinderTests.cs, src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ModelBinders/HttpQueryStringModelBinderTests.cs, src/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttribute.cs, src/Umbraco.Web.BackOffice/Filters/OnlyLocalRequestsAttribute.cs, src/Umbraco.Web.BackOffice/Filters/ValidationFilterAttribute.cs, src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj, src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs, src/Umbraco.Web.Common/ModelBinders/HttpQueryStringModelBinder.cs, src/Umbraco.Web/Umbraco.Web.csproj, src/Umbraco.Web/WebApi/Filters/AppendUserModifiedHeaderAttribute.cs, src/Umbraco.Web/WebApi/Filters/HttpQueryStringModelBinder.cs, src/Umbraco.Web/WebApi/Filters/OnlyLocalRequestsAttribute.cs, src/Umbraco.Web/WebApi/Filters/ValidationFilterAttribute.cs
Relating to issue #7799.
In this PR I've migrated the followin Web API components into their .Netcore equivalents:
- `HttpQueryStringModelBinder`
- `OnlyLocalRequestsAttribute`
- `ValidationFilterAttribute`
- `AppendUserModifiedHeaderAttribute`
As we can't currently run in the back-office, testing has only carried out via the introduced unit tests.
=> Netcore: Implemented various Web API components

src/Umbraco.Core/Models/Editors/ContentPropertyFile.cs, src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js, src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js, src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html, src/Umbraco.Web/Editors/Binders/ContentModelBinderHelper.cs, src/Umbraco.Web/Editors/ContentControllerBase.cs
As per @nielslyngsoe's [comment](https://github.com/umbraco/Umbraco-CMS/pull/8065#issuecomment-624531758) I'm targeting this to `v8/dev`. 
This adds a "segment" parameter to posted file data, so you can post files for multiple variants (segmented / non segmented) at the same time. I did not completely test all upload related editors yet, but I tested with "File Upload" and "ImageCropper" and it looked good.
As an aside, it seems there is a bug in Umbraco stable when uploading the same file for the same property of different cultures that leads to only 1 file being generated on disk.  The filename of a media file seems determined only based on the content id + property id + sanitized filename, so if I upload `some-image.jpg` for the `image` property of a doctype for cultures `nl-NL` and …
=> Added support for segments to File Uploads

src/Umbraco.Tests.AcceptanceTest/cypress.json, src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/templates.ts, src/Umbraco.Tests.AcceptanceTest/package.json, src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
- Fixed bug with parallel execution of the cache refreshers
- Fixed issue in template test that called postSave twice.
- Updated Cypress to latest + Updated Umbraco Test helpers with longer timeout on close tours modal.
- Added new acceptance test for delete templates
=> Stabilising acceptance tests + Bugfix for hanging saves of media.

src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html
Super quick PR, no tests nor reproduction steps, just a small markup fix.
I noticed in "umb-button.html" that the last the `<button>` was missing its closing bracket.
=> umb-button.html - missing closing bracket

src/Umbraco.Web.UI.Client/src/views/propertyeditors/dropdownFlexible/dropdownFlexible.controller.js, src/Umbraco.Web/PropertyEditors/ValueConverters/FlexibleDropdownPropertyValueConverter.cs
- [yep] I have added steps to test this contribution in the description below
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/8153
An 'empty' dropdown (Umbraco.Dropdown.Flexible) property -  will store a value as a string in the database in the format '[]' or '[null]' when actually 'nothing is selected'- this is after first selecting an item in the dropdown, saving, then unselecting the selected item reverting back to the state where nothing is selected... 
this breaks IsValue and HasValue in 'PropertyValueConverterBase' because they are only determining whether something has a value on the basis of whether it is a string and isn't whitespace... so this also breaks ToAncestors() on a recursive property that uses the dropdown.
~Hopefully this PR illustrates the problem, I'm not saying …
=> Fix HasValue and IsValue for Dropdown Property Types with no Values

src/Umbraco.Web.UI.Docs/gulpfile.js, src/Umbraco.Web.UI.Docs/umb-docs.css
I have caught myself needing to double check the url for the v8 backoffice documentation to make sure I was not looking at the v7 docs since they currently share the same theme and both headlines are identical saying "Umbraco Backoffice UI API Documentation".
Therefore I have changed the headline to say "Umbraco 8 Backoffice UI API Documentation" and then I have themed it so the styles differentiate from the v7 version as well making it very explicit what version the documentation is for - The colors etc. are reused from our.umbraco.com.
I'm of course open for suggestions for changes 😃 
Oh, and btw - It would be nice if the docs could be updated as well since for instance the umbDateTimePicker is still displayed as umbFlatPicker https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directive …
=> Theme backoffice docs for v8 to clearly differentiate it from the v7 docs

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
I noticed the label text for the checkbox was not vertically centered - This is adjusted with this small PR.
**Before**
**After**
=> Fix label alignment in umb-checkbox

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
I have extended the `<umb-checkbox>` directive with a `disable-dirty-check` parameter since I have recently worked on a custom content app where I reused the directive and we wanted to be able to disable the dirty check. But it's not possible to do currently out of the box. I'm reusing the already build in `no-dirty-check` directive if the `disable-dirty-check` is set to true, which will help out others too if they need an easy way to prevent the model from becoming dirty and therefore trigger the "unsaved data overlay" in scenarios where it does not make sense 😃 
I used the "checkboxlist" datatype for demo purposes only and it's not part of this PR.
**Default directive behavior**
**Directive behavior when `disable-cdirty-check="true"` is set**
=> Add disable-dirty-check option

src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/confirm/confirm.controller.js, src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/confirm/confirm.html, src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/emails/emails.controller.js, src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Adds a new confirmation email marketing step to email marketing tour for more visual confirmation.
* Log out of the Umbraco backoffice
* Open DB table `UmbracoUsers`
* Find your user and remove the JSON for email marketing tour
* Log back into backoffice
* Opt into emails & confirm you see a second step with your email address listed
**Before**
```
[{"alias":"umbIntroIntroduction","completed":false,"disabled":true},{"alias":"umbEmailMarketing","completed":true,"disabled":false}]
```
**After**
```
[{"alias":"umbIntroIntroduction","completed":false,"disabled":true}]
```
=> Bugfix: Adds new confirmation email marketing step

src/Umbraco.Web/Mvc/ControllerFactoryExtensions.cs, src/Umbraco.Web/Mvc/MasterControllerFactory.cs
`ControllerFactoryExtensions.GetControllerTypeInternal` and `MasterControllerFactory.GetControllerTypeInternal` will fall back to calling `CreateController` if a custom controller factory is being used.
In this case, it should then call `ReleaseController`. The factory may have retained a reference to the instance, leading to a memory leak if the instance is never released.
=> GetControllerTypeInternal should release the controller instance if it creates one

src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html
In this PR I have added screen reader friendly texts on the buttons and added `aria-hidden="true"` on the `<i>` element ensuring no screen reader announces them.
=> Umb-confirm-directive: Hide icons and add missing screen reader friendly texts

src/Umbraco.Web.UI.Client/src/common/directives/components/umblightbox.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-lightbox.less, src/Umbraco.Web.UI.Client/src/views/components/umb-lightbox.html
✔️  I have added steps to test this contribution in the description below
In this PR I have done some wee styling changes, which are not really noticeable but had to be done after the switch from `<div>` to `<button>` 😃 
So what has happened is
- The `<div>` elements have been converted to `<button>`
- Missing localization texts have been added
- Styling has been modified
Works and looks the same as before. At a later point it would be good to align the backdrop so it's triggered by the backdrop service instead.
=> umb-lightbox improvements

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.html
I've noticed this span was missing a closing >, so I added it.
=> Fix HTML markup of includeproperties.prevalues.html

src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
I've noticed this file was missing a closing div tag, so I added it.
=> Fix HTML markup of umb-list-view-settings.html

src/Umbraco.Web.UI.Client/src/views/components/notifications/umb-notifications.html
A while ago I was trying to figure out why I couldn't get the `url` property to render in the `umb-notifications.html` view.
I commented about it here: https://github.com/umbraco/Umbraco-CMS/pull/2965#discussion_r401619104
I couldn't see how the `ng-switch` statement worked, (as it's intended to work with literal values, not objects).  So I swapped out the `ng-switch` statement with a couple of `ng-if` conditions.
In terms of testing, I made a test dashboard harness...
**package.manifest**
```json
{
"javascript": [
"~/App_Plugins/LeeTest/dashboard.js"
],
"dashboards": [{
"alias": "leeTestDashboard",
"view": "/App_Plugins/LeeTest/dashboard.html",
"sections": ["content"],
}
]
}
```
**dashboard.html**
```html
<div ng-controller="LeeTest.Controller as vm">
<button type="button" …
```
=> umb-notifications.html - refactored switch logic

src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs, src/Umbraco.Web/PublishedCache/NuCache/DataSource/ContentNestedData.cs, src/Umbraco.Web/PublishedCache/NuCache/DataSource/CultureVariation.cs, src/Umbraco.Web/PublishedCache/NuCache/DataSource/PropertyData.cs, src/umbraco.sln
If there's an existing issue for this PR then this fixes N/A
What:
Changes the property names in json for properties on ContentNestedData, CultureVariation and PropertyData types to shorter names.
Also  changes Culture and Segment on PropertyData to not be serialized to json when the value is an empty string, these properties will still deserialize to an empty string.
Why?:
When you have a large number of content/media items with several properties on them, cold boot up time (no NuCache.*.db files on disk) can be very slow. By shortening the json you reduce the number of bytes that need to be read from the data base into memory and then to the nucache.db files on disk. For ~26,000 published content and ~110,000 media items this saved ~2 mins of time for cold boots and reduced …
=> Shorter JSON property names for nucache

src/Umbraco.Core/Compose/AuditEventsComponent.cs
This fixes issue [8090](https://github.com/umbraco/Umbraco-CMS/issues/8090).
When calling `httpContext.GetCurrentRequestIpAddress()` from a spoofed HTTP context then the returned IP is `null`. A use case for this would be calling the MemberService.Save from a Hangfire scheduled task.
Testing is tricky; the way I tested was to make these changes locally then reference the DLL in a project where I had this error. Using the current Core DLL I receive the `NullReference` on line 71, using the updated DLL with this patch completes the MemberService.Save completely.
Since IP can return an empty string anyway this won't have any adverse affect.
=> `IP` null when `GetCurrentRequestIpAddress` called from spoofed context

src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitDownloadStep.cs, src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitInstallStep.cs, src/Umbraco.Infrastructure/Models/Mapping/MemberTabsAndPropertiesMapper.cs, src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttributeTests.cs, src/Umbraco.Tests/Testing/UmbracoTestBase.cs, src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs, src/Umbraco.Web.BackOffice/Controllers/LogController.cs, src/Umbraco.Web.BackOffice/Controllers/PackageController.cs, src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs, src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs, src/Umbraco.Web.BackOffice/Controllers/RedirectUrlManagementController.cs, src/Umbraco.Web.BackOffice/Controllers/TourController.cs, src/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttribute.cs, src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs, src/Umbraco.Web.BackOffice/Filters/UmbracoApplicationAuthorizeAttribute.cs, src/Umbraco.Web.BackOffice/Filters/UmbracoTreeAuthorizeAttribute.cs, src/Umbraco.Web.Common/Install/InstallController.cs, src/Umbraco.Web/Editors/AuthenticationController.cs, src/Umbraco.Web/Editors/Filters/ContentModelValidator.cs, src/Umbraco.Web/Editors/Filters/ContentSaveModelValidator.cs, src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs, src/Umbraco.Web/Editors/Filters/MediaItemSaveValidationAttribute.cs, src/Umbraco.Web/Editors/Filters/MediaSaveModelValidator.cs, src/Umbraco.Web/Editors/Filters/MemberSaveModelValidator.cs, src/Umbraco.Web/Editors/Filters/MemberSaveValidationAttribute.cs, src/Umbraco.Web/Editors/MemberTypeController.cs, src/Umbraco.Web/Editors/UsersController.cs, src/Umbraco.Web/Mvc/UmbracoAuthorizeAttribute.cs, src/Umbraco.Web/WebApi/UmbracoAuthorizeAttribute.cs
Once `IWebSecurity` was added to the DI Container (#8220) we can now directly inject `IWebSecurity` and eliminate the usages of `UmbracoContext.Security`.
=> Netcore: Removing UmbracoContext.Security usages

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
The content editor title seems broken; it reads "Edit: undefined" when editing an existing content item:
This happens for both culture variant and invariant content. But still works fine when creating a new content item:
With this PR, the title goes back to "Edit: [name of content item]" like it used to be:
=> Fix "Edit: undefined" in content editor title

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js, src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json, src/Umbraco.Web/Models/BackOfficeTourStep.cs
Adds a new property to tour step objects **skipStepIfVisible** that is a DOM selector. If found then we can skip the step
* Have the template tree already expanded then start the fourth tour in the getting started group/collection (You will need to complete the other tours first)
* Ensure you can complete the tour & the step about selecting the Templates tree to be expanded is skipped
* Finish the tour
* Close the tree & re-run the tour and ensure all steps including expanding the tree is shown as well
Fixes #8137 
Fixes [AB#6743](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6743)
```JSON
{
"element": "#tree [data-element='tree-item-templates']",
"title": "Expand the Templates node",
"content": "<p>To see all our templates click the <b>small …
```
=> Adds skipStepIfVisible property to JSON Tour Steps to allow skipping if DOM item is present

src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8223
The `copy` code is relying on the `Utilities` class to be there, but this (js) class was added for 8.7 only. So while cherry picking to 8.6 worked (there were no merge conflicts), it's unfortunately relying on a file from 8.7.
I searched for any other mentions of `Utilities.` in the client files and could only find this one.
To test, run this build and check that you can copy and paste a nested content item (each product in the starter kit has "features" which are NC items).
=> Fix nested content clipboard

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
_Note: This is a regression, it was also fixed in #4981_
On some screens I'm seeing a white border in some usages of `umb-checkbox`. It might be a screen resolution/interpolation thing that sets it off. Curiously enough it's on every other checked checkbox on the RTE configuration:
Anyway... the fix is quite harmless - it's adding a background color to the checked state of the checkbox. It looks like this:
=> Fix glitch in umb-checkbox background

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
If there's an existing issue for this PR then this fixes #8175 (side effects on radio button - [reference here](https://github.com/umbraco/Umbraco-CMS/pull/8175#issuecomment-641404313))
#8175 had the unintended side effect of messing up the radio button checked appearence:
This PR turns the radio button checked state back to what it should be:
...while retaining fix for the checkbox checked state originally intended by #8175:
Please note that this PR targets `v8/dev` on purpose as #8175 was merged into that branch.
=> Fix radio button checked appearance

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html, src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
The property editor settings via datatype on a document type has now changed a bit in this PR https://github.com/umbraco/Umbraco-CMS/pull/5677
However this PR didn't take into account the look and feel of macro parameter editors and furthermore my previous PR https://github.com/umbraco/Umbraco-CMS/pull/8071 wasn't merged in time before these changes was made.
I have added a few changes to make it more consistent again and made some accessibility enhancements.
=> Adjust property editor settings

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js, src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
When having multiple allowed media types (e.g. default "Image" and a "Special Image" under e.g. "Folder" media type) and dragging files/images to dropzone, it shows an overlay to select media type. This is however the older/legacy `umb-overlay` instead of using `overlayService` or `editorService`.
In this case we could use `editorService.mediaTypePicker()` however I have chosen to use `overlayService` using `itempicker` view, because this is used when inserting grid editors (where you choose which editor to use).
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js#L320-L341
This is how it looks at the moment:
and when inserting an item in grid:
With these changes after uploading files to dropzone in e.g. …
=> Upload media and select media type

src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less, src/Umbraco.Web.UI.Client/src/less/property-editors.less
This previous PR https://github.com/umbraco/Umbraco-CMS/pull/6962 added the following css:
```
.umb-fileupload {
display: flex;
}
```
Unfortunately it has a side-effect that SVG image preview is no longer is shown on the media edit page.
**Before**
**After**
=> Ensure SVG image is shown in preview

src/Umbraco.Web/Editors/ContentTypeController.cs, src/Umbraco.Web/Models/ContentTypeImportModel.cs
Importing a doctype would never assign a value to UploadedFiles, turns out we don't need UploadedFiles on the model
Additionally added a check to see if temp files were left behind and delete them to prevent errors when the same file has just been uploaded
=> Importing a doctype leaves behind temp files

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.controller.js
Some property editors - eg MultiUrlPicker listen out for the broadcast of the 'formSubmitting' event before setting their value of $scope.model.value... if these editors are used as Macro Parameters they do not save their value. This commit adds the broadcasting of the event when the 'submit' button is called and any parameters have been set.
The MultiUrlPicker is a popular MacroParameter candidate + setting defaultConfig for min/max items, and in V7 this worked... (Possibly only in the RJP package?). 
Having added this broadcast of the 'formSubmitting' event to the closing of the Macro Parameter overlay, the MultiUrlPicker functions as you would expect in the context of a Macro Parameter!
The existing issue that this PR relates to is: https://github.com/umbraco/Umbraco-CMS/issues/7025 …
=> Broadcast 'formSubmitting' event when Macro Parameter Overlay is submit

src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
Fixes umbraco/Umbraco-CMS#8256
When a document type is being deleted, all document types are being iterated to lookup if they have a reference to the document type. If it has, simply update the AllowedContentTypes to reflect the change.
To test:
- Compile the CMS and copy the DLL's from deploy project.
- Run the solution
- Add three document types (dta, dtb, dtc)
- Let the third document types (dtc) be Allowed as child for each of the other two (dta and dtb)
- Locate the uda files and verify that for both dta and dtb, that there is a reference to dtc
- Delete dtc
- Locate the uda files and verify that for both dta and dtb, that the reference to dtc has been deleted.
=> If content type is deleted and other document types have a reference to it, raise an event

src/Umbraco.Web.UI.Client/src/views/propertyeditors/decimal/decimal.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8077
This PR add the `id` attribute as on most other property editors, so clicking property label set focus in the input field.
=> Add id attribute so click on property label focus in input

src/Umbraco.Web/Editors/MacroRenderingController.cs, src/Umbraco.Web/IUmbracoComponentRenderer.cs, src/Umbraco.Web/UmbracoComponentRenderer.cs
Fixes https://github.com/umbraco/Umbraco.Forms.Issues/issues/354
However, this is a core CMS issue as opposed to a Forms issue
* Test before & after PR applied to verify it works
* Have Umbraco Forms installed
* Create a doctype with one property that is a RTE that allows macros to be inserted
* Create new content node and use the Forms Macro in the RTE (Do NOT publish it. only save it)
* Reload/come back to the node & see the error or verify its gone all OK & the macro can render in the RTE
=> Allows unpublished content to render a macro HTML in the RTE

src/Umbraco.Core/Manifest/ManifestContentAppFactory.cs, src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js, src/Umbraco.Web/ContentApps/ContentEditorContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentInfoContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentTypeDesignContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentTypeListViewContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentTypePermissionsContentAppFactory.cs, src/Umbraco.Web/ContentApps/ContentTypeTemplatesContentAppFactory.cs, src/Umbraco.Web/ContentApps/ListViewContentAppFactory.cs, src/Umbraco.Web/Models/ContentEditing/DocumentTypeDisplay.cs, src/Umbraco.Web/Models/Mapping/CommonMapper.cs, src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs, src/Umbraco.Web/Runtime/WebInitialComposer.cs, src/Umbraco.Web/Umbraco.Web.csproj
This PR adds the ability to add content apps to document types.
I updated the tabs that are currently used (design, list view, permissions and templates) to be using the new content apps. 
Why would you want content apps for document types? I think it's always good to have the possibility to extend the backoffice on all spots, but I actually had an idea I couldn't do because this wasn't possible. I want to be able to set SEO settings for all pages that have a certain document type. 
I am not too familiar with the Umbraco code, so I hope everything that I changed is alright! Please let me know if it isn't and I can change it around.
Doc type with 1 custom C# content app
Doc type with 2 custom content apps (1x C# and 1x manifest)
=> Added content apps for document types

src/Umbraco.Web/Mvc/RenderRouteHandler.cs
A fix to issue as reported in https://github.com/umbraco/Umbraco-CMS/issues/7148.
=> v8: fix to Postback to a controller that is named in RouteTable.Routes.MapUmbracoRoute

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
When creating a folder from media picker overlay it use the `umb-loader` class. However this is causing horizontal overflow because of the animationand therefore horizontal scrollbar shown/hidden while animating.
That's why I originally added the `umb-loader` directive which wrap this inside another `<div>` element. It also ensure consistency.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/umb-loader.html
=> Media picker folder create loader

src/Umbraco.Web.UI.Client/package.json, src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
This PR update noUiSlider to latest version, which have fixes some bugs. Furthermore it has added default styling to support merging overlapping tooltips. The documentation has a example to merge overlapping tooltip (like some other slider plugin does, e.g [Ion.RangeSlider](http://ionden.com/a/plugins/ion.rangeSlider/)).
**Before**
**After**
=> Update slider to handle merging of overlapping tooltips

src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyeditor.directive.js
If there's an existing issue for this PR then this fixes #8068
When changing a property type on an existing property, the property preview doesn't reload in the content type builder (like it does in V7):
This PR ensures that we watch for changes and update the property preview accordingly:
=> Reload property preview when changing property type

src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
When tabbing through the content type editor, inputs/buttons/etc. within the property previews can receive focus:
You can't actually interact with the focused elements within the property previews. If you hit enter with one of them is in a focused state, the "edit property" dialog opens up (as you'd expect it to), so the applied focus within the preview doesn't break things as such. It just feels weird when navigating. 
Anyway. This PR fixes it:
=> Prevent property previews from having focus

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
If there's an existing issue for this PR then this fixes #8039
This changes the +-button in grids, if you only have one allowed layout to choose from. If you only have one allowed layout, the row gets inserted on the first click of the + button. In addition to that, a tooltip is added with the name of the layout.
How it looks for one allowed layout:
How it looks for more than one allowed layout:
=> Grid: adds row immediately if only one layout is allowed

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
Working on #8141 I noticed this bug.
I have changes the binding time from @ to < in order to pass the dynamic expression. Currently setting `umb-auto-focus="false"` explicitly will actually evaluate the expression where it's being used to true as well since the check just expects any kind of string not a boolean. However I can't think of an instance currently where you would want to the value to false initially but I think it should be changed for good measure and who knows, there might be scenarios where the current situation would break something, so we better do it this way instead 😅
=> umb-button directive: Change binding type for autoFocus

src/Umbraco.Web.UI.Client/src/less/mixins.less
While I was working on #8141 I noticed some issues with the focus styling in the user dialog overlay for instance - Turns out it was missing the :focus pseudo class, which I have now added.
**Before**
**After**
=> Add missing focus style in .buttonbackground mixin

src/Umbraco.Web.UI/web.Template.Debug.config
This removes the last remaining reference to the legacy Examine config sections.
I encountered some problems while testing my package against for configuring Examine against the Umbraco source as I have a config section named the same thing 🤪
=> Removing references to legacy Examine config

src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js, src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
If there's an existing issue for this PR then this fixes #8073
As discussed in #8073 it makes sense to use the element type descriptions in the Nested Content "Add content" dialog.
This PR shows the element type descriptions as tooltips on hover. I have opted to only show the tooltips when hovering the element type names, as it got too aggressive otherwise.
Obviously no tooltip is displayed if the element type does not have a description. 
Here's a GIF that shows the feature in action (only some of the element types have descriptions):
=> Use element type description as tooltip in the Nested Content "Add content" dialog

src/Umbraco.Web.UI.Client/src/less/main.less, src/Umbraco.Web.UI.Client/src/views/content/sort.html, src/Umbraco.Web.UI.Client/src/views/media/sort.html
Within this PR the following has been changed
- `<a>` is converted to `<button>` since they don't contain any `href` values
- `aria-hidden="true"` has been added to the section containing the arrow icons
- Fallback texts have been added in case localization of the dictionary key has not been added for a certain culture
- Also changed the error display to render the text within a `<p>` and moved the `ng-if` onto the wrapping `<div>`, meaning I removed the outer `<div>`, which is not needed
=> Sort dialog: Accessibility optimizations

src/Umbraco.Web.UI.Client/lib/bootstrap/less/type.less, src/Umbraco.Web.UI.Client/src/less/main.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
- ✔️ I have added steps to test this contribution in the description below
In this PR I have changed the following
- Turned the `<a>` into a `<button>` since the `href` was empty
- Hidden the `<i>` from screen readers by adding `aria-hidden="true"`
- Changed `<h5>` to `<h2>` and `<h3>` to make it easier for screen readers to navigate (In a later PR I will add wrap the "Select editor" text in `<h1>` but it's in a different file)
- Added default texts in case no localization entry exists for certain languages
I hope you like it 😃
=> Infinite overlay: Datatype picker - Semantics and Accessibility fixes

src/Umbraco.Web.UI.Client/src/views/content/content.sort.controller.js, src/Umbraco.Web.UI.Client/src/views/media/media.sort.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes #7995
As discussed in #7995, the listviews do not update after performing a sort of the children displayed, leaving them somewhat out of sync.
This PR ensures that listviews are updated after a sort is performed on the children of the currently displayed content item. This applies to content and media listviews alike.
Since the sort order column is not part of the default listview, I have opted to only update the listviews after sorting if the sort column is indeed part of the listview. Thus the behavior for default listviews remain unchanged, and any performance penalty introduced by this PR will only affect those listviews where sort order is explicitly added as a column.
Here's a quick demo of this PR:
=> Update listviews after sorting children

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypeconfigurationpicker/datatypeconfigurationpicker.html
✔️  I have added steps to test this contribution in the description below
In this PR the following has been done
- Convert `<a>` to `<button>` since the `href` was empty
- Hide the icon by setting `aria-hidden="true"` on it
- Add some visuallyhidden texts to improve the screen reader experience
- Add the umb-auto-focus directive on the button and set the first button to be focused when the overlay opens instead of relying on an empty anchor tag - If no editor exists to configure then the "Add new" button will be focused instead - Below you can see the before and after effect.
I hope you like it and look forward to receive any feedback you might have as usual 😃 
**Before**
**After**
=> Datatype configuration: Improve accessibility and UX

src/Umbraco.Web.UI.Client/src/common/directives/components/umblistviewsettings.directive.js
If there's an existing issue for this PR then this fixes #7340
See #7340 for a detailed issue description. 
TL;DR: When creating a custom listview for a content type, "Sort" is not available as an "Order By" option. It only becomes available after saving and reloading the browser window:
This happens because the listview editor reverts to the built-in listview configuration (formerly known as prevalues) when creating a new custom listview, instead of adhering to the default configuration as dictated by Umbraco. Since the built-in listview configuration is missing "Sort", it appears to be missing when creating the new custom listview. 
This PR fixes it; here's the PR applied in action:
As you can tell, the listview editor reverts back to the built-in listview configuration again after …
=> Ensure that "sort" is available as "order by" for custom listviews

src/Umbraco.Web.UI.Client/src/less/main.less
When editing a listview in infinite editing, the UI looks a tad cramped:
This PR adds some spacing (targeting only controls in infinite editing):
=> Add a bit of spacing in infinite listview editing

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbcontextmenu.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbcontextdialog/umbcontextdialog.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreeitem.directive.js, src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js, src/Umbraco.Web.UI.Client/src/less/application/grid.less, src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
In this PR a backdrop is added whenever we open a menu - I have done this to align the UI behavior throughout the entire backoffice. Should this PR end up being accepted I will do a follow up PR where I refactor the "closeBackdrop" function I have added in 3 files so the close method of the backdrop service can handle the removal of the class based on a parameter instead so it's handled by the service instead of the places where it's called.
I hope you like it 😃 
~~**EDIT**: Ok, so I appear to have missed some spots where the backdrop does is not removed using the context menu - I'm looking into and will update this PR when it's ready for review again 👍~~
**EDIT:** Ok, this is good to go again! 😄 - Ensure to test it thourougly though - I think I covered all the edge cases now and I have …
=> Add backdrop when menu items are opened

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
If there's an existing issue for this PR then this fixes #7976
See #7976 for an issue description.
To test this PR:
1. Create an RTE style rule with a selector in this format: `[HTML tag].[CSS class].[CSS class].[CSS class]` - e.g. `p.some.complex.rule`. You can make it as complex as you want, but it must contain a HTML tag and at least two CSS classes separated by a period:
2. Verify that the RTE picks up this style rule and renders it correctly - both in the style selector and when the style rule is applied to content:
=> Parse complex RTE styles rules correctly

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.controller.js
The "Order by" selector does not update when removing listview columns:
=> Listview "Order by" should not contain removed columns

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/sortby.prevalues.controller.js
There are a few issues in the "Order by" selector when editing listviews:
1. If you remove and add the "Last edited" column, its name won't get translated like the rest of the system fields - it shows as `undefined`.
2. Non-system fields also show as `undefined` until you fill out a heading for them.
I also found some unused code that could be deleted while I was at it. Here's a GIF of the same operations with this PR applied:
=> Fix a few localization glitches in the listview "Order by" selector

src/Umbraco.Web/Mvc/RenderRouteHandler.cs
Fixes #7148
When finding the SurfaceController to post back to when using BeginUmbracoForm we weren't specifically checking for only SurfaceControllers routes since we just assumed it would be a SurfaceController route. This is problematic if using a SurfaceController simultaneously as an IRenderController with a custom front-end route since it will fail to find that controller to post back to. This is fixed by further filtering the controllers looked up to only include SurfaceControllers.
* Includes original changes from community PR https://github.com/umbraco/Umbraco-CMS/pull/7149/files
* Refactored to be changed according to comments in the PR
* Removes additional checks for `if (postedInfo.Area.IsNullOrWhiteSpace())` and simplifies the whole linq query so it's just one query that …
=> Fixes #7148 - ensures we only check for SurfaceController routes

src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
Fixes issue mentioned in the Block List PR, https://github.com/umbraco/Umbraco-CMS/pull/8273#issuecomment-651624122
We never parsed on the documentTypeKey so fixing this.
=> BlockEditor Fix - Parse on contentType key

src/Umbraco.Examine/IndexRebuilder.cs
During some investigations of Examine indexes becoming locked there was a report of this stack trace when Umbraco is populating the indexes (https://github.com/umbraco/Umbraco-CMS/issues/8215#issuecomment-652354745)
```
System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
at System.Data.SqlClient.SqlTransaction.ZombieCheck()
at System.Data.SqlClient.SqlTransaction.Commit()
at NPoco.Database.CompleteTransaction()
at Umbraco.Core.Scoping.Scope.DisposeLastScope() in d:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 388
at Umbraco.Core.Scoping.Scope.Dispose() in d:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 365
at Umbraco.Core.Services.Implement.ContentService.GetPagedDescendants(Int32 id, …
```
=> Remove the usage of Parallel to run the populators

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
This PR replace the legacy `umb-overlay` here to show ysod and instead use `overlayService.ysod()` just like here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/media/media.delete.controller.js#L62
=> Replace ysod umb-overlay using overlayService.ysod

src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
Existing issue https://github.com/umbraco/Umbraco-CMS/issues/8192
Create bunch of users in umbraco and add them a group, ensure that each user is given any number of start nodes.
Then in template run following:
```
IUserService us2 = Services.UserService;
<ul>
@foreach (IUser user in us2.GetAllInGroup(3))
{
<li>@user.Name  - @user.StartContentIds.Count()</li>
}
</ul>
```
For each user the startContentIds count will be 0.  This is because the UserDto is not being hydrated with this data.  I have added extra call to hydrate, its the same call made by GetUsersById in UserService which does give correct counts for StartContentIds
This PR fixes this issue.
=> fix for 8192 make call to add missing bits to userdto

src/Umbraco.Tests.AcceptanceTest/cypress/integration/Tour/backofficeTour.ts
This is part of the overall project to extend Cypress tests for the Umbraco back-office in v8 (and will be able to also merged into .NET Core)
I've done a first pass at a Cypress test for the back-office tour Introduction step, which runs through each step (17% of the overall back-office tour)
- I tried to use the existing extension methods. I couldn't find the Umbraco button by label key though. 
- I don't check Cypress against actual language content, in case that changes - except the tour index indicator 3/12 etc
- There is scope for this to be refactored especially as we add the extra tour steps
- Not sure I'm always targeting the right things, but have tried to follow the existing pattern. 
- I have an act, …
=> Added initial Cypress test for BackOffice tour.

src/Umbraco.Core/Persistence/FaultHandling/Strategies/SqlAzureTransientErrorDetectionStrategy.cs, src/Umbraco.Core/Persistence/Repositories/IDocumentRepository.cs, src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs, src/Umbraco.Core/Runtime/SqlMainDomLock.cs, src/Umbraco.Core/Services/Implement/ContentService.cs, src/Umbraco.Examine/IndexRebuilder.cs, src/Umbraco.TestData/LoadTestController.cs, src/Umbraco.TestData/Umbraco.TestData.csproj, src/Umbraco.Web.UI/Umbraco.Web.UI.csproj, src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs, src/Umbraco.Web/Scheduling/HealthCheckNotifier.cs, src/Umbraco.Web/Scheduling/LogScrubber.cs, src/Umbraco.Web/Scheduling/ScheduledPublishing.cs, src/Umbraco.Web/Scheduling/SchedulerComponent.cs
Details are here: https://github.com/umbraco/Umbraco-CMS/issues/8215
This should also resolve https://github.com/umbraco/Umbraco-CMS/issues/8392
* Improvements to SqlMainDomLock
* Better management of db instances and transactions - previously this was trying to manage a single database instances which isn't what should be done, db instances should exist for a short period of time and disposed of. Changed to more explicit code for managing transactions
* Increase polling times - though according to logs this wasn't causing problems but is still too aggressive for what it's doing
* Don't stop listening (shut down maindom) if there are SQL exceptions, only if the appdomain has actually triggered a shutdown. We cannot just stop listening even if there are errors since it will lead to …
=> Adjustments for SqlMainDomLock and others to make azure operations more resilient

src/Umbraco.Web.UI/Umbraco/config/lang/de.xml, src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml, src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8405
A few translation files included icon HTML for a translation key using for Nested Content add button and also in overlay title. No other languages than `nl` and `tr` did include this.
In general I think HTML should be avoided when possible in translations, since we just want the raw translation and when people contribute with translations they often only make changes to a few languages - not all of them.
This should probably be cherry picked in `v8/8.6`
=> Fix translations files including icon HTML

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multipletextbox/multipletextbox.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/multipletextbox/multipletextbox.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8238
This PR excludes empty string values from saved model, so the underlying json doesn't contain empty values, which made the property value converter return an array with empty values.
=> Remove empty strings from repeatable textstrings whitespace

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less, src/Umbraco.Web.UI.Client/src/less/forms.less, src/Umbraco.Web.UI.Client/src/less/main.less
As pointed out by @bjarnef in #8119 I did unfortunately not get to the root of the problem with the proposed PR, which affected the display of radio buttons making them look worse and the rich text editor settings did not look to good either - They did not look good before but looked worse after, which was not the intent 😅 
With this PR I managed to address the root of the problem and there were several issues that needed to be fixed styling wise. Now both radio buttons and checkboxes look good 👍 
_Relation types_
_Rich text editor_
_Radio- and checkboxes_
_Relation types_
_Rich text editor_
_Radio- and checkboxes_
=> Fix checkbox and radio label alignment

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js, src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
I noticed when creating a new content template (blueprint) the save-button in the edit view (new) is a bit inconsistent from other parts of the UI where only a save-button (green button) is displayed, e.g. in datatype edit view or for an existing created content template.
**Before**
**After**
=> Use primary button style for save-button in content template

src/Umbraco.Web.UI.Client/src/less/property-editors.less, src/Umbraco.Web.UI.Client/src/views/propertyeditors/slider/slider.html
This PR re-use the `umb-property-editor--limit-width` mixin to set the max width and not specific to `66.6%` width also mean it in overlay use more of the width instead only 2/3 of the width in overlays.
**Before**
**After**
=> Use property editor width limit for slider property editor

src/Umbraco.Web.UI.Client/src/less/components/umb-code-snippet.less, src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/insertfield/insertfield.html
This PR re-use the `umb-code-snippet` component which is also used in querybuilder to show the code snippet when inserting af field value to make it a bit more consistent.
=> Use code snippet component for insert field

src/Umbraco.Web/HtmlHelperRenderExtensions.cs
When using variants it's unlikely to need the same Html.Partial result to be cached across all language variations, if we always add the current culture name to the cache key, we ensure this doesn't accidentally happen, and when not using variants, no harm to have the current culture name for the single site included in the key.
We made a very similar change for Macro caching here:
https://github.com/umbraco/Umbraco-CMS/pull/7555/files
I'm not sure why at the time, I didn't think to check whether Html.CachePartial would have the same issue.
=> Add the current culture to the cache key  for the CachedPartial Html Helper

src/Umbraco.Web/PropertyEditors/TrueFalseConfiguration.cs
See Issue: https://github.com/umbraco/Umbraco-CMS/issues/8420 for the explanation of the misconception.
This PR just updates the text of the Checkbox Configuration option to change 'Default Value' To 'Initial State' to try to avoid misconceptions that this option is some kind of 'fall back default value' in code.
Thanks for considering this contribution to Umbraco CMS!
=> Update 'default value' title + description of CheckBox Configuration

src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js, src/Umbraco.Web.UI.Client/src/less/components/overlays.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8424
This PR use similar to this other PR https://github.com/umbraco/Umbraco-CMS/pull/8416 `getBoundingClientRect()` which get the "real" position, when e.g. uisng transform styles via css.
In this case `setTargetPosition()` is only using for overlays having position set to `target`.
When using hotkey the `mousePositionClickX` and `mousePositionClickY` was undefined/null, so in this case it fallback to center of container element.
Furthermore the position was calculate based on container `#contentwrapper`, but like `umb-tooltip` in https://github.com/umbraco/Umbraco-CMS/pull/8416, this would probably be positioned wrong if opening an `target` overlay from an existing overlay.
=> Adjust target overlay position using hotkey

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.html
This PR use `<optgroup>` to group fields for listview columns in two groups: "System Fields" and "Custom Fields".
Furthermore is remove unnecessary use of `ng-if`.
The following part:
```
<span class="list-view-layout__name-text" ng-if="!val.isSystem" ng-bind="val.alias"></span>
<span class="list-view-layout__name-text" ng-if="val.isSystem == 1" ng-bind="val.alias"></span>
```
can be simplified to:
```
<span class="list-view-layout__name-text" ng-bind="val.alias"></span>
```
=> Listview columns grouping

src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html, src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
This PR restrict sorting on y-axis and within parent element. I also noticed the remove button no longer was rendered for custom listviews, because of the self-closing `<umb-checkbox ng-if="layout.isSystem === 1" model="layout.selected" />`. Changing this to `<umb-checkbox ng-if="layout.isSystem === 1" model="layout.selected"></umb-checkbox>` fixes this issue.
Previous it looked like this as the GIF in this PR:
https://github.com/umbraco/Umbraco-CMS/pull/5405
In both `umb-checkbox` and `umb-radiobutton` I noticed the label had child `<div>` elements, which isn't valid for `<label>`, so changing this to `<span>` instead.
Finally the "Add layout" button is also removed outside the sortable placeholder, so it isn't part of the sortable area.
=> Sort on y-axis in listview config layouts

src/Umbraco.Web.UI.Client/src/common/directives/components/umbtooltip.directive.js, src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js, src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
This PR fix the issue, where tooltip wasn't positioned correct when used inside an overlay, e.g. in itempicker, which is now used a overlay in nested content. The tooltip is at the moment using `#contentwrapper` as container to calculate the position of the tooltip: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbtooltip.directive.js#L82
Also note it is now using `getBoundingClientRect()` since `container[0].offsetLeft` and `container[0].offsetTop` return the left and top position, but not the "real" position, when the overlay is using `transform: translate(-50%,-50%);`
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
Furthermore on mouseover in allow child nodes overlay on a document type, …
=> Adjust tooltip position inside overlay

src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html
...on umb-tags-editor.html to avoid a string or binary data would be truncated error when the entered tag exceeds the database column length
This fixes https://github.com/umbraco/Umbraco-CMS/issues/8412
Sets max length on the tag input
To test this, set up a blank site, paste a tag longer than 200 characters in the tag picker
It will be truncated in the UI
Prior to this fix it would throw a server error on save & publish
=> #8412 Set ng-maxlength and maxlength attributes on the tag input 

src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.controller.js
At the moment in `v8/contrib` branch there a console error when navigating to a document type.
It happens because it assign a translated value to a undefined variable and when merging PR https://github.com/umbraco/Umbraco-CMS/pull/8045
and merging with latest changes in this commit: https://github.com/umbraco/Umbraco-CMS/pull/8045/commits/2e0504e00c4ca0da81996d043646a6d76a97c57c
However PR https://github.com/umbraco/Umbraco-CMS/pull/8045 removed the variable `childNodeSelectorOverlayTitle` since it isn't necessary and the translation happens here https://github.com/umbraco/Umbraco-CMS/pull/8045/files#diff-87fde30a6a97c0d78ed91c4470bc78cdR84-R87
=> Remove unnecessary translation to removed variable

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
In property settings overlay when datatype has a longer name the editor info need to shrink, so it doesn't push the remove button out of screen real estate.
**Before**
After
=> Allow editor info to shrink for longer datatype names

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
This PR align the property actions to top in the group builder instead of centered. In might work okay with these centered, but if adding a longer description, it push down these actions.
It seems nicer to have these at same position next to the property editor preview.
**Before**
**After**
=> Align group builder property actions to top

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfileupload.directive.js, src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js, src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less, src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
At the moment when dragging file over dropzone in e.g. image cropper a `drag-over` class is added and return feedback to the user. However when dragging a file over a single file upload field on a File media type the user get no feedback on drag over.
I was a bit inspired from this article https://css-tricks.com/drag-and-drop-file-uploading/ and have for a while noticed the file upload in Umbraco didn't provide any feeback to user on dragover.
This is how the dragover change look for the image cropper dropzone:
This PR add a `drag-over` class here as well, which style the upload button with a border color as in the image cropper dropzone.
**Before**
**After**
=> Register dragover state of file upload

src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js, src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-crop.html, src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html, src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
When uploading creating a new media e.g. "File" or "Image" and selecting or dragging a SVG file to the file upload a preview is not shown, because the `fileSrc` property only is set for images https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js#L248, where SVG at the moment by default not is considered as image and for example is creating as "File" media type under a folder, when uploading SVG files to a folder.
The `fileSrc` is however set for existing uploaded SVG files on init:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js#L121
**Before**
**After**
=> Show SVG preview on upload

src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-group.less, src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
When SMTP mail settings has been configurated in web.config the "Invite user" button is shown with a "Create user" subbutton.
However when this isn't configurated only "Create user" button is show, where the button has rounded corners on the left, but no border radius on the right.
**Before**
**After**
=> Adjust border radius of button in button group if having sub buttons

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.controller.js, src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
This PR replace the traditional checkboxes with `umb-checkbox` component in grid configuration when selecting row configuration for layout and grid editors for cells.
A minor issue with "Allow all row configurations" toggle which doesn't clear previous selected specific row configurations for the layout is mentioned and fixed in https://github.com/umbraco/Umbraco-CMS/pull/8357
=> Grid config row and editor checkboxes

src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.controller.js, src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
If there's an existing issue for this PR then this fixes #8342
As described in #8342 ... custom label properties on a member type are not rendered when editing a member of said type.
For example this member type:
...renders like this in the editor (note the missing label property):
This happens because we don't want to show the system label properties (prefixed with "umbracoMember", e.g. "umbracoMemberFailedPasswordAttempts") when editing the member. So we filter out all label properties. Bit harsh, really.
This PR adds a custom filter which only filters out label properties if they're carrying the "umbracoMember" prefix. When the PR is applied, the custom label property renders in the editor as expected:
=> Show custom label properties on members

src/Umbraco.Web/Editors/MediaController.cs
If there's an existing issue for this PR then this fixes #8325
See #8325 for steps to reproduce.
When this PR is applied, the uploaded folder is created correctly with the "(1)" suffix, and the uploaded images are created inside the folder as one would expect:
=> Fix folder uploads when existing image names clash with the uploaded folder name

src/Umbraco.Web.UI.Client/src/views/content/content.sort.controller.js, src/Umbraco.Web.UI.Client/src/views/content/sort.html
This PR restrict the sorting to y-axis in sort dialog and within parent element.
Furthermore if remove unnecessary use of `ng-if` and use `ng-class` to toggle asc/desc sort icon instead.
One of the button elements also had a wrong end-closing tag, so fixed that as well.
=> Sort on y-axis in sort dialog
