umbraco/Umbraco-CMS

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Added dutch translations for the grid layout

Added dutch translations for the grid layout

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html

Fixes rendering issues in IE by replacing style with ng-style

U4-6103: Replace style with ng-style (again)

---

src/Umbraco.Core/Persistence/Repositories/ContentRepository.cs
src/Umbraco.Core/Persistence/Repositories/Interfaces/IContentRepository.cs
src/Umbraco.Core/Publishing/PublishingStrategy.cs
src/Umbraco.Core/Services/ContentService.cs

See http://issues.umbraco.org/issue/U4-6154
For review by Morten & Shannon

U4-6154 - fix unpublishing a document with changes

---

src/Umbraco.Web.UI.Client/src/less/panel.less

This fixes [U4-4565] (http://issues.umbraco.org/issue/U4-4565) by adding a bottom margin.

Fixes: U4-4565 Add margin to bottom bar

---

src/Umbraco.Web.UI.Client/src/less/gridview.less

Change width of grid cell tools, so it doesn't overlap the input
fields/texteditors.

U4-5942 - change width of grid cell tools

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/dialogs/ChangeDocType.aspx
src/Umbraco.Web.UI/umbraco/dialogs/ChangeDocType.aspx.cs

This adds a filter to the list of types you can select from.

U4 6183 - Only allow change document type to types that would allow the existing children to be created under them

---

src/Umbraco.Web.UI.Client/src/common/directives/grid/grid.rte.directive.js

First Pull Request - be gentle :-)

U4-6288 Changes

---

src/Umbraco.Core/Configuration/UmbracoSettings/IWebRoutingSection.cs
src/Umbraco.Core/Configuration/UmbracoSettings/WebRoutingElement.cs
src/Umbraco.Web.UI/config/umbracoSettings.Release.config
src/Umbraco.Web.UI/config/umbracoSettings.config
src/Umbraco.Web/Routing/ContentFinderByNiceUrlAndTemplate.cs
src/Umbraco.Web/Routing/PublishedContentRequestEngine.cs
src/Umbraco.Web/Templates/TemplateRenderer.cs
src/Umbraco.Web/umbraco.presentation/NotFoundHandlers.cs
src/Umbraco.Web/umbraco.presentation/page.cs

I think I found all areas where we switch out the template for something else. Not very high priority, I would like for someone who is more familiar with these codepaths to go through it and make sure I didn't do something very silly.

U4-274 - Adds config option to disable alternative templates

---

src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Core/Services/MediaService.cs

just a small PR to fix some typos...

Issue#U4-6448 typo fix in pageIndex Mandate checks

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml

The User section has confusing labels.  This makes it clear what the fields actually represent.

Fix for U4-6462

---

src/Umbraco.Web/Mvc/RedirectToUmbracoPageResult.cs
src/Umbraco.Web/Mvc/SurfaceController.cs

Either as a string or as a name/value collection

U4-1733 - Added overloads to RedirectToUmbracoPage methods to allow passing of a querystring

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

I have created an issue on the issue tracker as well: http://issues.umbraco.org/issue/U4-6558

listview.html: the arrows for symbolizing ascending and descending are wrong

---

src/Umbraco.Web.UI.Client/src/init.js
src/Umbraco.Web.UI.Client/src/views/common/login.controller.js

Based on http://www.jonahnisenson.com/angular-js-ui-router-redirect-after-login-to-requested-url/

U4-5213 - Login redirect to originally requested URL

---

src/Umbraco.Web/umbraco.presentation/umbraco/Trees/loadNodeTypes.cs

Added the ability for child doctypes to have "Reload Nodes"
http://issues.umbraco.org/issue/U4-6530

Fix for U4-6530

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

Small fixes to 'en' language file. Update of 'en-us' language file to match 'en' language file.

English Language file updates (Umbraco/config/lang)

---

src/Umbraco.Web/Editors/AuthenticationController.cs

Fixes http://issues.umbraco.org/issue/U4-6603

U4-6603 Log failed login attempts

---

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

Swedish translation was completly missing for the grid-editor

Swedish translation for the grid-editor

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

I have changed the translatation to fix issue U4-6564

Change translation for add row for fix issue U4-6564

---

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

The swedish translation was using {0} instead of %0%. Leading to alot of
texts being weirdly formated.

Swedish was using the wrong format for variables

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Missing keys added, deleted keys deleted, reorderded some keys based on
the english one and corrected couple of wrong translations.

Updating Dutch Translations

---

src/Umbraco.Web/Editors/BackOfficeController.cs

Fix for localization not working some of the time: http://issues.umbraco.org/issue/U4-6665

Fixes U4-6665 (Localization Bug)

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/examinemanagement.html

Add unique id for TextSearch / LuceneSearch for each searcher.
http://issues.umbraco.org/issue/U4-6748

Add unique id for TextSearch / LuceneSearch

---

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

Added a few missing and removed unused translations.

Edited swedish translations

---

src/Umbraco.Core/PropertyEditors/PreValueEditor.cs

See http://issues.umbraco.org/issue/U4-6775

Support virtual paths for PreValueField attributes (U4-6775)

---

src/Umbraco.Web/Media/ThumbnailProviders/ThumbnailProvidersResolver.cs

Just like the ContentFinderResolver.cs

U4-6902 - Changed from internal to public

---

src/Umbraco.Web.UI.Client/src/views/content/content.recyclebin.controller.js
src/Umbraco.Web.UI.Client/src/views/media/media.recyclebin.controller.js

Ensure recycle bin tree node is highlighted when chosen.

Highlight recycle bin tree node

---

src/Umbraco.Web.UI.Client/src/common/directives/umbtreeitem.directive.js
src/Umbraco.Web.UI.Client/src/less/tree.less

Make tree nodes have same position from the left regardless of the arrow
to expand the children.

Make tree nodes consistent

---

src/Umbraco.Web.UI.Client/src/views/common/dialogs/help.html
src/Umbraco.Web.UI.Client/src/views/content/create.html
src/Umbraco.Web.UI.Client/src/views/content/delete.html
src/Umbraco.Web.UI.Client/src/views/datatype/delete.html
src/Umbraco.Web.UI.Client/src/views/media/delete.html
src/Umbraco.Web.UI.Client/src/views/member/create.html
src/Umbraco.Web.UI.Client/src/views/member/delete.html
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Trees/MemberTreeController.cs

Issue: http://issues.umbraco.org/issue/U4-6983
Add localization for text in help dialog, create and delete dialogs and
some minor parts of the member area.

Localize text in help dialog

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Added missing keys in da.xml and removed some duplicate keys.

Add missing Danish translations

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

UI localization: latest updates related to the PR 766 and "U4-6983 Localize text in help dialog"

ru.xml - newest 'member' and 'help' sections

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.controller.js

Rounds grid widths to 8 decimal places (like Bootstrap)

---

src/Umbraco.Core/Persistence/Repositories/EntityRepository.cs

Plenty of info on the issue tracker about the issue and my fix http://issues.umbraco.org/issue/U4-6784 and in this Our thread https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/66697-umbraco-7xx-media-picker-error

Fix for U4-6784 Multiple Media Picker 

---

src/NuGet.Config

Adds the ability for contributors to pull the Umbraco specific Nuget
packages from the Myget repository using package restore.
https://docs.nuget.org/consume/nuget-config-file

Add custom repo package restore

---

build/NuSpecs/UmbracoCms.Core.nuspec
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.UI/packages.config

An update to U4-7053. Reduced memory usage plus web optimised images.

Update ImageProcessor dependency for core

---

README.md

The old link didn't work and this video seems to be an ok replacement ?

Updated readme with working intro video , that is for umbraco v7

---

src/Umbraco.Web/umbraco.presentation/umbraco/Trees/loadDictionary.cs

Fixes issue where dictionary items are displayed in a random order

---

src/Umbraco.Web/Mvc/RenderActionInvoker.cs

The current RenderActionInvoker does not allow for async Index() actions on a controller that implements IRenderMvcController. It will treat any async actions as synchronous actions by storing it's descriptor as a ReflectedActionDescriptor and not it's correct TaskAsyncActionDescriptor. This patch extracts the correct type of descriptor and stores the descriptors as the base ActionDescriptor type.

U4-7270 - Addition of allowance for async/await Index actions

---

src/Umbraco.Web.UI.Client/src/less/login.less

Quick LESS fix for: http://issues.umbraco.org/issue/U4-7302

Login overlay now higher than bootstrap datepicker

---

src/Umbraco.Web.UI.Client/src/common/directives/umbsections.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/umbtreeitem.directive.js
src/Umbraco.Web.UI.Client/src/views/directives/umb-sections.html

http://issues.umbraco.org/issue/U4-6426

Fixing "U4-6426 CTRL click should open in a new window"

---

src/Umbraco.Web/Editors/MemberController.cs

http://issues.umbraco.org/issue/U4-6928

Fixes U4-6928 - Persist Creator ID of member

---

src/Umbraco.Web.UI.Client/src/views/common/dialogs/mediapicker.html

Focus new folder input automatically
http://issues.umbraco.org/issue/U4-7070

Fix for U4-7070

---

src/Umbraco.Web.UI.Client/src/common/directives/grid/grid.rte.directive.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
src/Umbraco.Web/Editors/BackOfficeController.cs

Fixes: http://issues.umbraco.org/issue/U4-5617

UKFest-U4-5617 RTE now respects CSS Directory AppSetting.

---

src/Umbraco.Web.UI.Client/src/common/directives/umbtreeitem.directive.js

http://issues.umbraco.org/issue/U4-5560#

Fixing "U4-5560 White space issue in content tree"

---

src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/RegisterMember.cshtml

http://issues.umbraco.org/issue/U4-6282

U4-6282  Add note to Register Partial Macro

---

src/Umbraco.Web.UI.Client/src/less/panel.less

Safe to use both for mobile and desktop.

Fixes U4-7393

---

src/Umbraco.Web.UI/umbraco/Views/Default.cshtml

"JAVASCRIPT IS DISABLED. PLEASE ENABLE TO CONTINUE!"
http://issues.umbraco.org/issue/U4-6732

U4-6732 - Added message on back office, when JS is disabled.

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js

Fixed media picker Media picker does not set $dirty

fix for issue u4-6515

---

src/Umbraco.Web/Scheduling/ScheduledTasks.cs

@dampeebe suggested we added ConfigureAwait(false) to the async HttpClient request for scheduled tasks. 
Seems to be best practise but needs peer review?
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

Ukfest 7341

---

src/Umbraco.Core/Persistence/UmbracoDatabase.cs

See http://issues.umbraco.org/issue/U4-7325 for details.

U4-7352 Fixed exception logging in UmbracoDatabase.

---

src/Umbraco.Web/umbraco.presentation/item.cs

get the correct alternative recursive field
http://issues.umbraco.org/issue/U4-5581

Uk fest u4 5581

---

src/Umbraco.Core/Constants-Applications.cs

Fixed a typo ("users" -> "forms").

Fixed typo for "forms": http://issues.umbraco.org/issue/U4-7425

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

Increased timeout from 200 to 1000 ms so you can actually type something and added support for manually submit with enter without waiting for the timer.

Fixes U4-7219

---

src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.controller.js
src/Umbraco.Web/Editors/ImagesController.cs

in mediahelper.sevice.js and fileupload.controller.js

Changed web api GetBigThumbnail to image processor

---

src/Umbraco.Web/WebServices/DomainsApiController.cs

Has it ever been? Couldn't find the unit-test, so going cowboy.

Actually save the domain

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js

Fixes: U4-7387 It's not possible to select folders in listview in media section

---

src/Umbraco.Web.UI/umbraco/config/lang/de.xml

Thanks to huge help from @merkledo and the others of the Stuttgart Umbraco Meetup, we pulled together all the bits and pieces for a single solid translation file. More unified and clean wording, typo fixes and more. Even if not perfect it will still be better than everthing we had before and something we hopefully can keep current from now on. Incorporates everything from @hoehler and @SoerenDeger to best knowledge.

Major revamp with keys added and texts fixed everywhere

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
src/Umbraco.Web.UI/Umbraco/config/lang/cs.xml
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/de.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/es.xml
src/Umbraco.Web.UI/umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/umbraco/config/lang/he.xml
src/Umbraco.Web.UI/umbraco/config/lang/it.xml
src/Umbraco.Web.UI/umbraco/config/lang/ja.xml
src/Umbraco.Web.UI/umbraco/config/lang/ko.xml
src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/umbraco/config/lang/no.xml
src/Umbraco.Web.UI/umbraco/config/lang/pl.xml
src/Umbraco.Web.UI/umbraco/config/lang/pt.xml
src/Umbraco.Web.UI/umbraco/config/lang/ru.xml
src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
src/Umbraco.Web.UI/umbraco/config/lang/zh.xml

Grid - Make sure localization works for buttons and help txt

Temp u4 7445

---

src/Umbraco.Core/Models/DeepCloneHelper.cs

See http://issues.umbraco.org/issue/U4-7522 for details.

U4-7522 Removed unnecessary exception from DeepCloneHelper.

---

src/Umbraco.Web.UI/umbraco/config/lang/no.xml

Adds missing translations, removes some old ones and moves some to match current en.xml.

Update Norwegian translations

---

src/Umbraco.Core/Macros/MacroTagParser.cs
src/Umbraco.Tests/Macros/MacroParserTests.cs

See http://issues.umbraco.org/issue/U4-7462 for details

U4-7462 - Fixes bug with macro multiline parameters

---

src/Umbraco.Web.UI.Client/src/less/buttons.less
src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
src/Umbraco.Web.UI.Client/src/less/forms.less
src/Umbraco.Web.UI.Client/src/less/hacks.less
src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/less/navs.less
src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/less/tree.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/common/dashboard.html
src/Umbraco.Web.UI.Client/src/views/dashboard/default/StartupDashboardIntro.html
src/Umbraco.Web.UI.Client/src/views/dashboard/default/StartupDashboardKits.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/developerdashboardintro.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/developerdashboardvideos.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/examinemanagement.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/xmldataintegrityreport.html
src/Umbraco.Web.UI.Client/src/views/dashboard/media/desktopmediauploader.html
src/Umbraco.Web.UI.Client/src/views/dashboard/media/mediadashboardintro.html
src/Umbraco.Web.UI.Client/src/views/dashboard/members/membersdashboardintro.html
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

Fixing _Inconsistent use of border-radius on buttons and input_, together with global styling on links on `umb-dashboard-controls`.
Added underline links stylings to dashboard. Note that this PR will require people to add `btn-link -underline` to their inline links on dashboard in the future, until dashboard gets an overhaul.

Fix for http://issues.umbraco.org/issue/U4-7567

---

src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/imagepicker.html

Changed UI to match existing mediapicker dialogs in the backoffice, which lead to solving the thumbnail text decoration problem.

Fix for http://issues.umbraco.org/issue/U4-7571

---

src/Umbraco.Web.UI.Client/src/less/components/card.less
src/Umbraco.Web.UI.Client/src/views/common/overlays/contenttypeeditor/editorpicker/editorpicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html

Grid editor - insert control: Make blue area clickable (No support for the Item picker in forms, since we need to rethink that part of forms)

Fix for http://issues.umbraco.org/issue/U4-6854

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorview.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor.less
src/Umbraco.Web.UI.Client/src/less/components/overlays.less
src/Umbraco.Web.UI.Client/src/views/common/dashboard.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-view.html

Scrollbar does not stick to bottom-bar

Fix for http://issues.umbraco.org/issue/U4-7573

---

src/Umbraco.Core/Services/EntityXmlSerializer.cs
src/Umbraco.Core/Services/PackagingService.cs

Handling sortOrder property in both import/export.

Fixes: U4-7553 Importing Document Type doesn't respect property sort order

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.html
src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js

…selecting image in some cases + a bit code clean up.

U4-7578 Can't pick folders in any media picker in 7.4 beta

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/markdowneditor/markdowneditor.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js

Dialog option for disabling folder select on media pickers.
Added the option to Markdown and RTE.

Fixes: U4-7578 Can't pick folders in any media picker in 7.4 beta

---

src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html

Added settings to grid controls in v.7.4.

Fixes: U4-6297 Add Settings to Grid Controls

---

src/Umbraco.Web.UI/umbraco/config/lang/ja.xml

I pulled the latest from Umbraco-CMS/dev-v7 and created a new branch off of it.  I then added the translations from Pull Request #1036, which was closed.  These changes still apply to dev-v7.  I hope it was correct, and easiest for you, to create a new pull request like this.
Changes include new translations, fixing existing translations, and removing unused entries to match the en.xml file.

Added translations and removed unused entries

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

According the latest keys added/updated in 7.4 beta2

Update UI language ru.xml

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

Only two new keys in the "sort" section translated. For full merged ru.xml file there are two more PRs (#1042 & #983)

Latest update UI language ru.xml

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

ru.xml UI lang file

---

src/Umbraco.Web.UI.Client/src/common/mocks/services/externalLoginInfo.mocks.js
src/Umbraco.Web.UI.Client/src/loader.dev.js

Fix for http://issues.umbraco.org/issue/U4-7763
Added mock for externalLoginInfo and dependency references required for 'dev' Grunt task

U4-7763 Fix - added mock and references required for 'dev' Grunt task

---

src/Umbraco.Web/Mvc/RenderModelBinder.cs

https://twitter.com/dan_lister/status/699369084765474818
I have no idea on how to repro but it seems an async route hijack thing? Anyway, I dont think this fix can hurt.

Fixes another reported bug for U4-7950

---

build/Build.proj
src/SQLCE4Umbraco/SqlCE4Umbraco.csproj
src/SQLCE4Umbraco/packages.config
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Core/packages.config
src/Umbraco.Tests/App.config
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Tests/packages.config
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.UI/packages.config

http://issues.umbraco.org/issue/U4-7996

Upgrade SQL CE to hopefully fix SQL CE data loss bug

---

src/Umbraco.Web.UI/umbraco_client/Dialogs/SortDialog.js

Adding dates processing for 'dd.MM.yyyy' formats

U4-7616 - Nodes sort dialog - additional date formats

---

src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagegravity.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagethumbnail.directive.js
src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-gravity.html
src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-thumbnail.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html

**Fixes** http://issues.umbraco.org/issue/U4-7570
**Other stuff:**
- Added functionality to click to set a focal point
- Added functionality to keep focal point on resize
- Fixed Hover and Active state on crop thumbnails (UI)
- Fixed crop slider (UI)
- Fixed crops thumbnails doesn't load before images load.

Temp u4 7570

---

src/Umbraco.Web.UI.Client/src/less/components/umb-table.less

http://issues.umbraco.org/issue/U4-7963#

Fixes U4-7963 Listview columns not evenly spaced in Chrome

---

src/Umbraco.Web/Trees/PartialViewsTree.cs

Also updates the icon in the partial view macro files tree

U4-7746 - use flat icon in partial views tree

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/examinemanagement.html

Issue: http://issues.umbraco.org/issue/U4-8163
Don't set dirty on form for examine dashboard search.

U4-8163 - Don't set dirty on form for examine dashboard search

---

src/Umbraco.Web.UI/umbraco/config/lang/fr.xml

Provided French translations for the Grid.

French translations for Grid.

---

src/Umbraco.Web.UI/config/trees.config

This is a PR for http://issues.umbraco.org/issue/U4-7543
I put data types at the top of the settings, is this correct?

U4-7543 Move data type tree to settings

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js

Fixes U4-8034  (http://issues.umbraco.org/issue/U4-8034)

Only restrict to image files when onlyImages is active

---

src/Umbraco.Web.UI.Client/src/less/components/umb-content-grid.less
src/Umbraco.Web.UI.Client/src/less/components/umb-folder-grid.less
src/Umbraco.Web.UI.Client/src/less/components/umb-layout-selector.less
src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/less/tree.less
src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html

Issue: http://issues.umbraco.org/issue/U4-8248
Add tooltip for listview layout selector and change cursor style for listview table row.

U4-8248 - Add tooltip for listview layout + cursor style for listview table row

---

src/Umbraco.Web/Scheduling/KeepAlive.cs

Looks like a copy-paste leftover

Fixed logger context class

---

src/Umbraco.Web.UI.Client/src/common/services/healthcheck.service.js
src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/healthcheck.less
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/healthcheck.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/healthcheck.html
src/Umbraco.Web/HealthCheck/HealthCheckController.cs

My progress on https://github.com/umbraco/Umbraco-CMS/pull/1220 for tonight.
The dashboard will now initially look something like this:
When clicking the **Check** button of a given health check, the list of statuses is fetched from the API. Each status will have an icon indicating the result of the status, and the links for the actions of the status (clicking won't do anything at the moment).
I'm not 100% sure about the UI, so I'll play a bit more around with it later. Also, if anyone has some suggestions to the UI (or in general), I'd be happy to look into that.

Dev v7 health check

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

This fixes the english (uk & us) version of the Publish dialog.

Fix for U4-8377

---

src/Umbraco.Tests/Routing/UrlRoutingTestBase.cs
src/Umbraco.Tests/TestHelpers/BaseDatabaseFactoryTest.cs
src/Umbraco.Tests/TestHelpers/BaseUmbracoApplicationTest.cs

Closed setting up of application context
Opens up a whole bunch of doors. :)

U4-8309 Virtualized creation of ApplicationContext

---

src/Umbraco.Web/umbraco.presentation/content.cs
src/Umbraco.Web/umbraco.presentation/umbraco/webservices/nodeSorter.asmx.cs

before this was storing every single xml node in memory in dictionaries (x2) and then performing the re-organization of all nodes afterwords to construct a document, now we just read each row and organize the document accordingly,

This fixes the LoadContentFromDatabase method

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

Added button to create only available doctype
Hides dropdown when listViewAllowedTypes.length > 1
Shows button for single when listViewAllowedTypes.length === 1

U4-8443 - Immediately create node from list view when only one available document type

---

appveyor.yml

Exported yml file from AppVeyor
Replaced the slack secret token, which is encrypted by AppVeyor, so can't be used with anything other than our own AppVeyor account. https://ci.appveyor.com/tools/encrypt

Temp u4 8495

---

src/Umbraco.Web.UI/config/ExamineIndex.Release.config
src/Umbraco.Web.UI/config/ExamineIndex.config
src/Umbraco.Web.UI/config/ExamineSettings.Release.config
src/Umbraco.Web.UI/config/ExamineSettings.config

The codeplex link points to the github repository.

update examine documentation links

---

src/Umbraco.Web/Routing/ContentFinderByRedirectUrl.cs
src/Umbraco.Web/Umbraco.Web.csproj

Adds an `IContentFinder` implementation to return the correct node from an `IRedirectUrl`

Add IContentFinder implementation.

---

src/Umbraco.Web/HealthCheck/Checks/Security/ClickJackingCheck.cs
src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs
src/Umbraco.Web/HealthCheck/Checks/Security/HttpsCheck.cs

Just one more thing to consider - where we are requesting URLs there's no need really to pull back the full file contents, just the headers would suffice, which is what this PR updates those requests to do.

u4-3805 - performance improvement

---

src/Umbraco.Web.UI.Client/test/unit/app/templates/template-editor-controller.spec.js
src/Umbraco.Web.UI.Client/test/unit/app/templates/template.editor.controller.tests.js

Currently testing that masterpage and layout is set.

Unit test for template editor.

---

src/Umbraco.Core/Services/MediaService.cs
src/Umbraco.Tests/Services/MediaServiceTests.cs
src/Umbraco.Tests/TestHelpers/Entities/MockedMedia.cs

now doing fallbacks to other querys trying to get media from the json value format stored.

U4-6551 GetMediaByPath returning null

---

src/Umbraco.Web.UI.Client/src/installer/steps/database.html
src/Umbraco.Web.UI.Client/src/installer/steps/user.html

.. and only submit button dimmed.
Issue: http://issues.umbraco.org/issue/U4-8598

Focus on input and toggle checkbox when clicking label

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Issue: http://issues.umbraco.org/issue/U4-8526
Fix a few translations in da.xml

Fix a few translations in da.xml

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/services/localization.service.js

Issue: http://issues.umbraco.org/issue/U4-8607
Added some basic documentation for `localizationService` and `localize` directive as these are probably one of the most used.

Document localizationService and localize directive

---

src/Umbraco.Web.UI/Views/Partials/Grid/Editors/TextString.cshtml

Uses Umbraco Helper to replace linebreaks for html in model.value

U4-8579: Replace linebreaks

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/healthcheck.html

Issue: http://issues.umbraco.org/issue/U4-8765

Open documentation link in new browser window/tab

---

src/Umbraco.Web.UI.Client/src/views/packager/views/repo.html

Issue: http://issues.umbraco.org/issue/U4-8746

Open link in new browser window/tab

---

src/Umbraco.Web.UI/web.Template.config

Added the woff2 mime type to the web config to fix http://issues.umbraco.org/issue/U4-8509

U4-8509 - Added woff2 mime type

---

src/Umbraco.Web/UmbracoHelper.cs

rebased on dev-v7 - Closes Issue U4-8657

Closes Issue U4-8657 - Add an overload to GetDictionaryValue to provide fallback text

---

src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

Issue created here: http://issues.umbraco.org/issue/U4-8654

Added a tooltip with icon alias on mouseover

---

src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js

credits to @SorenA https://github.com/umbraco/Umbraco-CMS/pull/630

U4-7475 Feature UA-1736 (element+class styles) for TinyMCE in grid

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

New 'bulk' area and few more corrections

Update UI language ru-RU.xml

---

src/Umbraco.Web/HtmlHelperRenderExtensions.cs

Removed the duplicate addition

U4-8814 - HTml.Wrap adds children twice

---

src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js

Issue: http://issues.umbraco.org/issue/U4-8608
Added comments to `getByQuery`, e.g. used in MNTP.

Document getByQuery

---

src/Umbraco.Web.UI/umbraco/config/lang/tr.xml

Some dictionary items were translated into Turkish language. Ad URLs removed.

Turkish Language file updated

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/HealthCheck/Checks/Security/ClickJackingCheck.cs

U4-8867 (IFRAME casing typos)

---

src/Umbraco.Web.UI.Client/src/common/resources/package.resource.js
src/umbraco.cms/businesslogic/Packager/Installer.cs

Fixes one of the problems with installing packages (when 1 file needs to be copied to multiple places) and adds better logging for other potential problems

U4-8889 Package install fails

---

src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html

Issue here: http://issues.umbraco.org/issue/U4-8935

Added support for progress bar/list for when uploading a single file

---

src/Umbraco.Web.UI/config/UrlRewriting.Release.config
src/Umbraco.Web.UI/config/UrlRewriting.config

http://issues.umbraco.org/issue/U4-9005

U4-9005 Update comments in urlrewriting.config to note it's obsolete

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

Added 'label' key to the ru.xml UI language file

U4-8985 Label for row configurations in the grid editor

---

src/Umbraco.Core/Persistence/Repositories/TagRepository.cs

Quick fix for: http://issues.umbraco.org/issue/U4-6710

Cast tag value to unicoded text before inserting it into database

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

(U4-8183) Changed the link picker dialog from Page Title to Link title

---

src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html

As per this ticket, I have applied the suggested fix and it's now working as expected.
http://issues.umbraco.org/issue/U4-9091

U4-9091 - Fixed the font being used in the Media Picker for files

---

src/Umbraco.Web/PropertyEditors/ValueConverters/UploadPropertyConverter.cs
src/Umbraco.Web/Umbraco.Web.csproj

Added converter for upload field

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Translation of Redirect URL Management to danish

Danish translations related to Redirect URL Management

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml

http://issues.umbraco.org/issue/U4-9146
Added missing colon to health check data integrity section for english language

Health check data integrity colons missing

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs

Modified Configuration and security sections - http://issues.umbraco.org/issue/U4-9147

Modified grammar on health check dashboard

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

Dictionary item editor keys added

Update ru.xml UI language file

---

README.md

the github markdown will show ## at the end of the line if it is followed by a space

readme.md : remove spaces behind ##

---

src/Umbraco.Web/Dictionary/UmbracoCultureDictionary.cs

U4-9332 Language of DefaultCultureDictionary is cached without the current Culture identifier

Fixes issue U4-9332

---

src/Umbraco.Core/Models/ContentExtensions.cs
src/Umbraco.Web/Models/Mapping/TabsAndPropertiesResolver.cs

This pull request fixes the property sorting issue covered by U4-9298.

Fix U4-9298

---

src/Umbraco.Web.UI.Client/src/views/common/notifications/confirmroutechange.html

Closes U4-9323 http://issues.umbraco.org/issue/U4-9323

Add some green to 'stay' option - U4-9323

---

src/Umbraco.Core/CoreBootManager.cs

Just a very tiny grammar change, I hope for such a small change you don't need a issue ticket, I've already typed far more than the code involved in the change here :)

Small English grammar error.

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

Update UI lang file for ru-ru

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/insert/insert.controller.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/insert/insert.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/macropicker/macropicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/querybuilder/querybuilder.controller.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/querybuilder/querybuilder.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/templatesections/templatesections.html
src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/templates/edit.html
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Editors/TemplateQueryController.cs
src/Umbraco.Web/Models/ContentEditing/TemplateDisplay.cs

Creating a PR for Per's localisation changes to the template editor just so we continue our internal development processes.

U4-9363 - Adds in localisation to new template editor

---

src/Umbraco.Web/Editors/CodeFileController.cs
src/Umbraco.Web/Trees/FileSystemTreeController.cs
src/Umbraco.Web/Trees/PartialViewMacrosTreeController.cs
src/Umbraco.Web/Trees/PartialViewsTreeController.cs
src/Umbraco.Web/Trees/ScriptTreeController.cs

Centralized the tree menu logic for partialviews, partialviewmacros and scripts to the FileSystemTreeController and implemented logic to match what we do for Document Types

U4-9484 Implement correct tree menu logic for partialviews, partialviewmacros and scripts

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbkeyboardshortcutsoverview.directive.js
src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
src/Umbraco.Web.UI.Client/src/common/services/platform.service.js
src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js
src/Umbraco.Web.UI.Client/src/views/components/umb-keyboard-shortcuts-overview.html
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.html
src/Umbraco.Web.UI.Client/src/views/scripts/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/scripts/edit.html
src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/templates/edit.html
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

Adds the keyboard shortcuts overview
Adds the hooks in the template editor for the keyboard shortcuts to launch the template editors various insert dialogs.

U4-9538 - Add Keyboard shortcut (overview & template editor)

---

src/Umbraco.Web/Models/ChangingPasswordModel.cs

removed "this" as remark for NewPassword

Removed weird comment

---

src/Umbraco.Core/Constants-ObjectTypes.cs
src/Umbraco.Core/PropertyEditors/ValueConverters/TagsValueConverter.cs
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Tests/Web/TemplateUtilitiesTests.cs
src/Umbraco.Web.UI.Client/lib/tinymce/plugins/umbracolink/plugin.min.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/linkpicker/linkpicker.controller.js
src/Umbraco.Web/Editors/ContentController.cs
src/Umbraco.Web/Editors/EntityController.cs
src/Umbraco.Web/Routing/UrlProvider.cs
src/Umbraco.Web/Templates/TemplateUtilities.cs
src/Umbraco.Web/Trees/ContentTreeController.cs
src/Umbraco.Web/Trees/ContentTypeTreeController.cs
src/Umbraco.Web/Trees/DataTypeTreeController.cs
src/Umbraco.Web/Trees/MediaTreeController.cs
src/Umbraco.Web/Trees/MediaTypeTreeController.cs
src/Umbraco.Web/Trees/MemberTreeController.cs
src/Umbraco.Web/Trees/MemberTypeTreeController.cs
src/Umbraco.Web/Trees/TemplatesTreeController.cs
src/Umbraco.Web/Trees/TreeControllerBase.cs

http://issues.umbraco.org/issue/U4-9498

U4-9498 LocalLinks as UDI

---

src/Umbraco.Tests/Web/TemplateUtilitiesTests.cs
src/Umbraco.Web.UI/web.Template.Release.config
src/Umbraco.Web.UI/web.Template.config

http://issues.umbraco.org/issue/U4-6566

U4-6566 Membership provider `useLegacyEncoding` should default to `false`

---

src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/AddIndexToCmsMemberLoginName.cs
src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/AddIndexToUmbracoNodePath.cs
src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/AddMacroUniqueIdColumn.cs
src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/AddRelationTypeUniqueIdColumn.cs
src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/RemovePropertyDataIdIndex.cs
src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenSixZero/RemoveUmbracoDeployTables.cs

removing unused using statements from other migrations.

U4-9632 Ensure GUID generation on updated entity types in v7.6 is unique

---

src/Umbraco.Web.UI.Client/src/common/directives/components/events/events.directive.js

See http://issues.umbraco.org/issue/U4-8418

Fixes jquery selector bug, http://issues.umbraco.org/issue/U4-8418

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
src/Umbraco.Web.UI.Client/src/common/resources/tree.resource.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/treepicker/treepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/overlays/treepicker/treepicker.html
src/Umbraco.Web/Editors/BackOfficeController.cs
src/Umbraco.Web/Trees/ApplicationTreeController.cs

Is needed for Forms CON-1296 to work

Adds support for loading uninitialized trees in the treepicker

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

Added orderBy name to the listview create new dialog, to match the dialog sort when creating content in the tree view.

U4-9697 - Listview create new node ordering

---

src/Umbraco.Core/Services/ContentTypeService.cs
src/Umbraco.Core/Services/MemberTypeService.cs
src/Umbraco.Tests/Services/ContentTypeServiceTests.cs
src/Umbraco.Tests/Services/MemberTypeServiceTests.cs
src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs

also fixed for member types (and added test for media types also using the ContentTypeService)

U4-9689 Content type description isn't always saved the same way

---

src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

They are present in en.xml now, but not in en_us.xml

Missing some new keys in 'create' area

---

src/Umbraco.Core/PropertyEditors/ParameterEditorResolver.cs
src/Umbraco.Web.UI/config/umbracoSettings.config
src/Umbraco.Web/Models/Mapping/MacroModelMapper.cs
src/Umbraco.Web/PropertyEditors/MediaPicker2PropertyEditor.cs
src/Umbraco.Web/umbraco.presentation/umbraco/developer/Macros/editMacro.aspx.cs
src/umbraco.cms/businesslogic/macro/MacroProperty.cs

http://issues.umbraco.org/issue/U4-9762

U4-9762 ezSearch package complains about pickers in macro parameters

---

src/Umbraco.Web/Cache/DataTypeCacheRefresher.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerPropertyConverter.cs

In the same way as the MultipleMediaPicker

U4-9684 UDI Media Picker Value Converter should cache prevalues

---

src/Umbraco.Web.UI.Client/src/less/installer.less

Change background color to purple to the overlay solid color before we login to backoffice at end of installer

U4-9769 - BG Color change for installer to purple hue

---

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

Added usernamehint to placeholders

Adding login hint to Swedish language file

---

src/Umbraco.Web.UI/umbraco/config/lang/zh.xml

Improve Chinese translation based on en.xml

Improve Chinese translation.

---

src/Umbraco.Web/PropertyEditors/ImageCropperPropertyEditor.cs

Found that when uploading media from the folder browser caused an issue of invalid JSON object being stored in the database.  Added quotes around the property values.

Fixed issue on line 216

---

src/Umbraco.Web.UI/umbraco/users/PermissionEditor.aspx

fix Add basic xss prevention logic

---

src/Umbraco.Core/PropertyEditors/ValueConverters/EmailAddressValueConverter.cs

Fix for http://issues.umbraco.org/issue/U4-9862

Return empty string when e-mail is not filled

---

src/Umbraco.Core/Persistence/Migrations/MigrationBase.cs

http://issues.umbraco.org/issue/U4-9852

Change Context to be public on MigrationBase

---

src/Umbraco.Web.UI.Client/src/installer/steps/upgrade.html

[U4-9869](http://issues.umbraco.org/issue/U4-9869)
Changed _To read a report of changes between your current version 7.5.13 and this version **your** upgrading to 7.6.0_ to read _To read a report of changes between your current version 7.5.13 and this version **you're** upgrading to 7.6.0_

Fix typo error in upgrade installer

---

src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagegravity.directive.js

Added a check to umb-image-gravity directive to verify that onImageLoaded function is passed.

fixed console error on media picker

---

src/Umbraco.Web.UI/umbraco/translation/default.aspx
src/Umbraco.Web/umbraco.presentation/umbraco/developer/Packages/editPackage.aspx

automaticly - > automatically typo fix up

U4 9886 - automaticly - > automatically (typo fix up)

---

src/Umbraco.Core/Services/EntityService.cs
src/Umbraco.Core/Services/IEntityService.cs
src/Umbraco.Web/Extensions/UdiExtensions.cs
src/Umbraco.Web/UmbracoHelper.cs

[Issue](http://issues.umbraco.org/issue/U4-9940).

U4-9940 Make it easy to get the integer Id of an item from it's Udi

---

src/umbraco.businesslogic/ApplicationBase.cs

Spelling and Grammar changes

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

Couple of translation corrections

Update ru.xml UI resources

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Added and changed some dutch translations, especially for members and subnodes (in a listview). The term "kinderen" only relates to children (persons), not items or nodes.

Improved and added dutch translation

---

src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Breadcrumb.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Gallery.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListAncestorsFromCurrentPage.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesFromChangeableSource.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesFromCurrentPage.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesOrderedByDate.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesOrderedByName.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesOrderedByProperty.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesWithDoctype.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListDescendantsFromCurrentPage.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListImagesFromMediaFolder.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/MultinodeTree-picker.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Navigation.cshtml
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/SiteMap.cshtml

These are a PR of Douglas Robar's updates to the partial view templates, with a couple of updates to the comments (by myself).

Updates to partialviews

---

src/Umbraco.Web/Models/ImageCropDataSet.cs

 U4-9710 ImageCropDataSet.HasImage returns wrong value 

---

src/Umbraco.Web/PropertyEditors/ListViewPropertyEditor.cs

U4-9661 Remove "move" button in member section

---

src/Umbraco.Web.UI/umbraco/config/lang/zh.xml

Improve Chinese translation to match the newest version based on en.xml

Improve Chinese translation

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/PropertyEditors/TextAreaPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/TextboxPropertyEditor.cs

http://issues.umbraco.org/issue/U4-4413
Pull request on this issue... Making textbox and textarea having the oppertunity to have a max character limit.
Simple javascript handling of ng-keydown event securing maxchar limit.

U4 4413   maxlength

---

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treepicker.html

resolves U4-10171 can't click remove icon, to remove picker item.

Update treepicker.html [U4-10171] add ability to remove picker item

---

src/Umbraco.Web/umbraco.presentation/library.cs

See http://issues.umbraco.org/issue/U4-10143 and https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/72058-continous-error-in-umbracotracelog.
This will hopefully help track down the issue. This is my first Umbraco PR so feedback welcome.

U4-10143 - Improved error messages when we retrieve current xml node

---

src/Umbraco.Web/PropertyEditors/ValueConverters/LegacyMediaPickerPropertyConverter.cs

Fix for issue http://issues.umbraco.org/issue/U4-10178

Fix value converter work for legacy media picker

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/developerdashboardintro.html
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

As on issue tracker [U4-10187](http://issues.umbraco.org/issue/U4-10187)

U4-10187 - Fix link to training in Backoffice -> Settings->Dashboard

---

src/Umbraco.Core/PropertyEditors/PropertyEditorAttribute.cs

Changed name of argument in validation

---

src/Umbraco.Web.UI/umbraco/config/lang/pl.xml

I've updated pl.xml with new keys to match the newest en.xml version.

Update pl.xml to match en.xml

---

src/Umbraco.Web.UI/umbraco/developer/Packages/editPackage.aspx

http://issues.umbraco.org/issue/U4-10136

U4-10136 Broken link to package action documentation

---

src/Umbraco.Web.UI.Client/src/common/security/securityinterceptor.js
src/Umbraco.Web.UI.Client/src/init.js
src/Umbraco.Web.UI/umbraco_client/Application/Extensions.js
src/Umbraco.Web/WebApi/Filters/AngularAntiForgeryHelper.cs

Changes the cookie and header names to be Umbraco specific

U4-10367 417 missing token error due to cookie being overwritten

---

src/Umbraco.Core/Configuration/ClientDependencyConfiguration.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Core/packages.config
src/Umbraco.Web/Install/Controllers/InstallController.cs

http://issues.umbraco.org/issue/U4-10400

U4-10400 Clear CDF temp files during upgrades

---

src/Umbraco.Web/HealthCheck/HealthCheckResolver.cs

Change HealthCheckResolver to public allowing DI

U4-9562 - HealthCheckResolver from internal to public

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

I've highlighted the translated parts:

Just had to have #2200 (Danish translations for the user section in Umbraco 7.7)

---

src/Umbraco.Core/Persistence/Repositories/AuditRepository.cs
src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Web/Editors/LogController.cs
src/Umbraco.Web/Models/ContentEditing/AuditLog.cs

Fixes:
*userName now holds the name of the user
*timeStamp now has the correct dateTime
*logType has the string equivalent of the enum

U4-10382 Add end point to get a paginated audit trail

---

src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html

div was opened instead of closed

Fix incorrect closed div

---

src/Umbraco.Tests/Models/Mapping/ContentWebModelMappingTests.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
src/Umbraco.Web/Models/ContentEditing/ContentItemDisplay.cs
src/Umbraco.Web/Models/Mapping/ContentModelMapper.cs
src/Umbraco.Web/Models/Mapping/TabsAndPropertiesResolver.cs

http://issues.umbraco.org/issue/U4-10311

U4-10311 Wire up angular with backend

---

src/Umbraco.Web.UI.Client/src/views/users/overview.controller.js
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html
src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/he.xml
src/Umbraco.Web.UI/umbraco/config/lang/ko.xml
src/Umbraco.Web.UI/umbraco/config/lang/pt.xml
src/Umbraco.Web/Trees/UserTreeController.cs

Issue: http://issues.umbraco.org/issue/U4-10442
Added localization of user section in Danish and replaced some static text with localization keys.
I also cleared a few language keys, which only existed in 4 language files and doesn't seem to be used anywhere in the code. https://github.com/umbraco/Umbraco-CMS/pull/2210/commits/ae1702c62a806f858777755759f1be21709a1add

U4-10442 - Localization of users section

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/tabs/umbtabs.directive.js
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
src/Umbraco.Web.UI.Client/src/views/media/edit.html

U4-10420 Only load audit trail when properties tab is active

added event to load audit trail on Properties tab only

---

src/Umbraco.Web.UI.Client/src/less/dashboards.less
src/Umbraco.Web.UI.Client/src/views/dashboard/forms/formsdashboardintro.html

Issue: http://issues.umbraco.org/issue/U4-7044
This fix issue with icon position in IE in form installer dashboard.

U4-7044 - Adjust icon and heading to fix issue with icon position in IE

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/email/email.html

http://issues.umbraco.org/issue/U4-10496

Fix Typo in Email Property Editor

---

src/Umbraco.Web.UI.Client/src/less/buttons.less
src/Umbraco.Web.UI.Client/src/less/canvas-designer.less

Tested on Safari 5.1.7, latest Chrome and Firefox

U4-7721 install button miss aligned

---

src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
src/Umbraco.Web/Models/ContentEditing/MediaItemDisplay.cs
src/Umbraco.Web/Models/Mapping/MediaModelMapper.cs

Created Map in MediaModelMapper to cater for the new property (DocumentType)
Wired front-end to match the new properties

Moved documentType and mediaLink to root node for media section

---

src/Umbraco.Web.UI.Client/src/common/services/assets.service.js

Fixes [issue](http://issues.umbraco.org/issue/U4-8616) with assetsService.load not able to load css files

Fix for U4-8616

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml

Removed duplicate definition of English translations

Removed duplicate translations

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml

Updated the grammar of the email validation messages

Updated grammar

---

src/Umbraco.Web.UI.Client/bower.json

This updates Umbraco to TinyMCE 4.6.x to fix the issue described in http://issues.umbraco.org/issue/U4-10191

U4-10191: Update to TinyMCE 4.6.x

---

src/Umbraco.Core/Services/EntityXmlSerializer.cs
src/UmbracoExamine/UmbracoContentIndexer.cs

Added this property to the index as suggested by Tim
https://twitter.com/attack_monkey/status/776462811962761216
http://issues.umbraco.org/issue/U4-8982

U4-8982 - Adding isPublished value to the index

---

src/Umbraco.Web/Models/Mapping/TabsAndPropertiesResolver.cs

We have formatted the Created Date and Updated Date using the Current Culture of the application. Done at Umbraco UK Festival Hackathon

Format date in backoffice based on Users language

---

src/Umbraco.Web/HealthCheck/Checks/Config/AbstractConfigCheck.cs

AbstractConfigCheck SuccessMessages are missing CurrentValue

Fix U4-10618 - AbstractConfigCheck 

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/redirecturls.html

First URL Tracker button colour for U4-9932

Fixed URL Tracker button colour

---

src/Umbraco.Web/ITypedPublishedContentQuery.cs
src/Umbraco.Web/PublishedContentQuery.cs
src/Umbraco.Web/UmbracoHelper.cs

I've added the overloads so that you can do typed search with skip and take and still get the total records to help you create a pager. As per http://issues.umbraco.org/issue/U4-9291

Adds overloads so you can do paging with the TypedSearch methods.

---

README.md

With a link to the build markdown page

Update README.md with correct location of build.bat

---

src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html

Related to this issue; http://issues.umbraco.org/issue/U4-10192. Made a link to a composition from the current doctype.

Created a link to composition doctype

---

src/Umbraco.Web.UI.Client/src/installer/installer.service.js

U4-10627 Update some of the Umbraco Installer facts. Updated the facts you get when installing umbraco. All facts that were changed were taken from the Umbraco page.
https://umbraco.com/blog/codegarden-2017-the-aftermath/ 
https://umbraco.com/blog/codegarden-2017/

U4-10627 - Updated stats / facts when installing.

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

Make a shiny template for the emails that are sent from Umbraco (only for EN and EN-US).

Make a shiny template for the emails that are sent from Umbraco

---

src/Umbraco.Core/Services/MemberService.cs
src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
src/Umbraco.Web/Editors/MemberController.cs

http://issues.umbraco.org/issue/U4-10589

U4-10589 Login should be sanitized and/or cause validation errors if trying to save with

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Added Danish translations for the new "History" and "Scheduled Publishing" headers

---

src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html

"by" in the new Info tab is now localized

---

src/Umbraco.Core/Services/ContentService.cs
src/Umbraco.Core/Services/IContentService.cs
src/Umbraco.Web/Editors/ContentController.cs
src/Umbraco.Web/umbraco.presentation/umbraco/webservices/nodeSorter.asmx.cs

http://issues.umbraco.org/issue/U4-10646

U4-10646 Sorting nodes in edge cases can lead to blanking out of property data

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

issue: http://issues.umbraco.org/issue/U4-10722
Just a small fix in a Dutch localization error.

U4-10722 fix in Dutch localization

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbnodepreview.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbpasswordtoggle.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js

Issue: http://issues.umbraco.org/issue/U4-10720
I have added some basic documentation to `umb-table` and `umb-password-toggle` so they will appear on Umbraco Backoffice UI API documentation: https://our.umbraco.org/apidocs/ui/#/api

U4-10720 - Add documentation to umb-table component

---

src/Umbraco.Web/PublishedContentQuery.cs

Simplifying this xpath query increases performance with around 30% when looking up items by Guid/UDI in the Our Umbraco database.

Doesn't fix the issue but improves performance by ~30%

---

src/Umbraco.Web.UI.Client/src/views/common/dialogs/iconpicker.html
src/Umbraco.Web.UI.Client/src/views/common/dialogs/mediapicker.html
src/Umbraco.Web.UI.Client/src/views/common/dialogs/membergrouppicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/contenttypeeditor/compositions/compositions.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/contenttypeeditor/editorpicker/editorpicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/iconpicker/iconpicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/macropicker/macropicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/usergrouppicker/usergrouppicker.html
src/Umbraco.Web.UI.Client/src/views/common/overlays/userpicker/userpicker.html
src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html

Pull Request for issue [#U4-4902](http://issues.umbraco.org/issue/U4-4902).
no-dirty-check attribute was added to all search fields in the backoffice.

U4-4902 Added no-dirty-check to search fields in all dialogs

---

src/Umbraco.Core/Cache/HttpRequestCacheProvider.cs
src/Umbraco.Core/DisposableObject.cs
src/Umbraco.Core/DisposableObjectSlim.cs
src/Umbraco.Core/DisposableTimer.cs
src/Umbraco.Core/Events/EventMessages.cs
src/Umbraco.Core/HashGenerator.cs
src/Umbraco.Core/Manifest/ManifestWatcher.cs
src/Umbraco.Core/Persistence/DefaultDatabaseFactory.cs
src/Umbraco.Core/Persistence/Repositories/EntityRepository.cs
src/Umbraco.Core/Persistence/Repositories/FileRepository.cs
src/Umbraco.Core/Persistence/Repositories/RepositoryBase.cs
src/Umbraco.Core/Persistence/UnitOfWork/ScopeUnitOfWork.cs
src/Umbraco.Core/Security/BackOfficeUserStore.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/Scheduling/BackgroundTaskRunnerTests.cs
src/Umbraco.Web/Scheduling/LatchedBackgroundTaskBase.cs
src/Umbraco.Web/Scheduling/RecurringTaskBase.cs
src/Umbraco.Web/Security/WebSecurity.cs
src/Umbraco.Web/UmbracoContext.cs
src/umbraco.cms/businesslogic/Packager/Repositories/Repository.cs

http://issues.umbraco.org/issue/U4-10815

U4-10815 Make DisposableObjectSlim

---

src/Umbraco.Web.UI.Client/src/common/services/tour.service.js

http://issues.umbraco.org/issue/U4-10804

Removed unused tour code from tour.service.js

---

src/Umbraco.Core/Services/MemberService.cs

http://issues.umbraco.org/issue/U4-10825
Re-targeted for dev-v7 :)

U4-10825 Search member by email in member section

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js

Issue: http://issues.umbraco.org/issue/U4-10785
If there are more than 15 items, 5 rows of 3, then show the filter.

U4-10785 - Filtering of Grid Editors

---

src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Trees/UserTreeController.cs

Adds two new context menu items, Create & Invite
http://issues.umbraco.org/issue/U4-10835

U4-10835 Adds context menu items to the User tree

---

src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html

http://issues.umbraco.org/issue/U4-10843

Fixes U4-10843 and allows user detail page to upload a new avatar

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Minor casing change

---

src/umbraco.cms/businesslogic/Packager/PackageInstance/utill.cs

http://issues.umbraco.org/issue/U4-10852

Fixes U4-10852 Where the ZipArchive stream was closed

---

src/Umbraco.Web.UI/umbraco/config/create/UI.Release.xml
src/Umbraco.Web.UI/umbraco/config/create/UI.xml
src/Umbraco.Web/Models/Trees/MenuItemList.cs
src/Umbraco.Web/Trees/MacroTreeController.cs

http://issues.umbraco.org/issue/U4-10840

Added in the create XML for the legacy UserControl based Create Dialog

---

src/Umbraco.Web/Editors/TourController.cs

U4-10847 Users with user group "Translator" are unable to login

Removed authorize attribute from TourControlle

---

src/Umbraco.Web.UI.Client/src/controllers/search.controller.js

http://issues.umbraco.org/issue/U4-10757

Can navigate trough global search results

---

src/Umbraco.Web.UI/umbraco/Views/Default.cshtml

Fixes: http://issues.umbraco.org/issue/U4-10865

Prevent Pinterest messing with media in the back office

---

src/Umbraco.Web.UI.Client/src/common/services/tour.service.js
src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
src/Umbraco.Web/Editors/TourController.cs
src/Umbraco.Web/Models/BackOfficeTour.cs

http://issues.umbraco.org/issue/U4-10869

U4-10869 Make sure the getting started tour is only shown to the right users

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js

Fixes the black bar issue: http://issues.umbraco.org/issue/U4-6309

U4-6309: Fix black bars that appear on a RTE image resize

---

src/Umbraco.Core/PropertyEditors/PropertyValueEditor.cs

http://issues.umbraco.org/issue/U4-10950

Fix checkbox in nested content

---

src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
src/Umbraco.Web/Editors/DashboardHelper.cs

Populate Caption in dashboardhelper
h3 -> h5

U4-10953- Help-drawer, (caption + h3 -> h5

---

src/Umbraco.Web/PropertyEditors/ValueConverters/MultiNodeTreePickerPropertyConverter.cs

http://issues.umbraco.org/issue/CON-1503

Fixes broken MNTP by switching convert cases to the correct DataType

---

src/Umbraco.Web.UI/Umbraco/config/lang/nb.xml
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/de.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

Issue: http://issues.umbraco.org/issue/U4-10965
Just adding a few translations of the "Save and schedule" key.

U4-10965 - Add translations of "Save and schedule"

---

src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.UI/umbraco/webservices/MediaUploader.ashx

The class is removed with https://github.com/umbraco/Umbraco-CMS/commit/a875ede

U4-10969 - Removed legacy file MediaUploader.ashx

---

src/Umbraco.Core/Models/PublishedContent/PublishedContentModelFactory.cs

Improved the grammar of an error message

Grammar improvement

---

src/Umbraco.Web/Mvc/RenderRouteHandler.cs

changed "There is not current UmbracoContext" to "There is no current UmbracoContext"

Typo fix for nullreference in RenderRouteHandler

---

src/Umbraco.Web.UI.Client/src/views/dashboard/developer/examinemanagement.html

http://issues.umbraco.org/issue/U4-11005

U4-11005 Examine Search tools form does not submit when pressing Enter key

---

src/Umbraco.Web/Editors/MemberTypeController.cs

http://issues.umbraco.org/issue/U4-10964

Temp u4 10964

---

src/NuGet.Config
src/Umbraco.Core/Models/PropertyType.cs
src/Umbraco.Core/Services/IMemberService.cs
src/Umbraco.Core/Services/MemberService.cs
src/Umbraco.Web.UI.Client/src/common/resources/member.resource.js
src/Umbraco.Web.UI.Client/src/views/member/Export.html
src/Umbraco.Web.UI.Client/src/views/member/edit.html
src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js
src/Umbraco.Web.UI.Client/src/views/member/member.export.controller.js
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Editors/MemberController.cs
src/Umbraco.Web/Editors/MemberTypeController.cs
src/Umbraco.Web/Trees/MemberTreeController.cs
src/umbraco.cms/Actions/ActionExportMember.cs
src/umbraco.cms/umbraco.cms.csproj

[http://issues.umbraco.org/issue/U4-10900](url)

Export member data functionality

---

src/Umbraco.Web/Editors/BackOfficeServerVariables.cs

Fixes - U4-11021 No login form when trying to authorise 7.9 upgrade
http://issues.umbraco.org/issue/U4-11021

U4-11021 No login form when trying to authorise 7.9 upgrade

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js

Fixed open doc type button

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Added the NL translation for Rectify and permissionDenied keys

Update NL.xml rectify and permissionDenied

---

build/Modules/Umbraco.Build/Get-UmbracoBuildEnv.ps1

U4-9992: Added usage of nuget config in environment setup

---

build/Modules/Umbraco.Build/Umbraco.Build.psm1

missed a single line and @nul800sebastiaan was faster than me, an already merged the first PR

U4-9992: Added nuget config to restore command

---

src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Media.cshtml

…Or empty string if null (for screen readers)

Fix for U4-10821, render alt text attribute from grid image editor (uduf hackathon)

---

src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs

See UAASSCRUM-1441. Changes made in 7.8 break token-based identities used in RestAPI and others.

fixes UAASSCRUM-1441: fix token identity breaking RestAPI and others

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

I have fixes a few translations to Danish and removed a duplicate key in user area.

U4-11093 - Update Danish translations

---

src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js

- Removed lorem ipsum text 
- Fixed casing of subtitle

Fixed documentation of umb-overlay directive

---

src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/prevalues/multivalues.less
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.controller.js
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html

U4-11071 Prevalue editor for multiple values TLC

---

src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js

As per specification in associated issue
http://issues.umbraco.org/issue/U4-11070

Adds support for *not* closing an overlay on enter

---

README.md

Xloud -> Cloud 
Xloud sounds awsome though :)

Fixed typo in Readme.

---

src/Umbraco.Web/Editors/PreviewController.cs
src/Umbraco.Web/Mvc/UmbracoAuthorizeAttribute.cs

http://issues.umbraco.org/issue/U4-11134

redirects preview to login when not authorized

---

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/html/umb-alert.less
src/Umbraco.Web.UI.Client/src/less/components/umb-box.less
src/Umbraco.Web.UI.Client/src/less/components/umb-load-indicator.less
src/Umbraco.Web.UI.Client/src/less/components/users/umb-permission.less
src/Umbraco.Web.UI.Client/src/less/tables.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/languages/edit.html
src/Umbraco.Web.UI.Client/src/views/languages/overview.controller.js
src/Umbraco.Web.UI.Client/src/views/languages/overview.html
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

http://issues.umbraco.org/issue/U4-11120

Temp u4 11120

---

src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

http://issues.umbraco.org/issue/U4-11125
Updates the existing language keys from lorem lipsum text

U4-11125 - Updates Langugae Keys for when changing default language in info bar

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
src/Umbraco.Web.UI.Client/src/less/alerts.less
src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
src/Umbraco.Web.UI.Client/src/views/common/notifications/confirmroutechange.controller.js
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html

http://issues.umbraco.org/issue/U4-11126

Temp u4 11126 variant switch prompt

---

src/Umbraco.Web.UI.Client/src/views/content/delete.html
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

http://issues.umbraco.org/issue/U4-11129
Adds in new info bar & lang/translation for warning about deleting variants

U4-11129 Updates Content Delete Dialog with new copy/warning about variants

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbclipboard.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbdatetimepicker.directive.js
src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
src/Umbraco.Web.UI.Client/src/common/services/user.service.js
src/Umbraco.Web.UI.Client/src/views/common/dialogs/approvedcolorpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/dashboard.tabs.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/googlemaps/googlemaps.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/markdowneditor/markdowneditor.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/slider/slider.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/tags/tags.controller.js
src/Umbraco.Web.UI.Client/src/views/scripts/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js

http://issues.umbraco.org/issue/U4-11164
This is a PR to ensure only the V7.10 regression issue is merged up into dev-v8 (easier to do a compare/diff on GitHub)

Merge upto V8 - U4-11164 Blank Login Screen regression from 7.10

---

src/Umbraco.Web.UI.Client/src/less/application/grid.less
src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-content.less
src/Umbraco.Web.UI/umbraco/Views/Default.cshtml

http://issues.umbraco.org/issue/U4-11171

fixes: U4-11171 Tree panel doesn't vertically scroll

---

src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less

Issue: http://issues.umbraco.org/issue/U4-8961

U4-8961 - Indicate that a row is clickable and highlight with background color.

---

src/Umbraco.Web.UI.Client/src/less/components/card.less
src/Umbraco.Web.UI.Client/src/less/healthcheck.less
src/Umbraco.Web.UI.Client/src/less/tables.less
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/developerdashboardvideos.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/examinemanagement.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/healthcheck.html
src/Umbraco.Web.UI.Client/src/views/dashboard/developer/publishedstatus.html
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

http://issues.umbraco.org/issue/U4-11209

fixes: U4-11209 Update layout for developer dashboards to fit new styles

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js

This is a extra PR for https://github.com/umbraco/Umbraco-CMS/pull/2539
This will add the property to the documentation as well.

U4-11150 added culture property of tour to the docs

---

src/Umbraco.Web.UI.Client/src/less/components/editor.less
src/Umbraco.Web.UI.Client/src/less/forms.less

http://issues.umbraco.org/issue/U4-11196#

Fixes - U4-11196 Validation UI is not working for the content name field

---

src/Umbraco.Web/Trees/ContentTreeControllerBase.cs

http://issues.umbraco.org/issue/U4-10995#

Removed code that populates content tree with duplicate start nodes.

---

src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

…ink (otherwise we will forget)
http://issues.umbraco.org/issue/U4-11290
Super simple commit/PR that comments out the Open in List View link

U4-11290 - Disables Open in List View link from variant/language switcher in node name

---

src/Umbraco.Core/Models/Property.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/components/overlays/umb-overlay.html
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Models/Mapping/ContentPropertyBasicConverter.cs
src/Umbraco.Web/PublishedCache/NuCache/Property.cs

http://issues.umbraco.org/issue/U4-11283

fixes - U4-11283 Cannot save content when a doc type is variant but a property type is invariant

---

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/less/components/card.less
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/dropdownFlexible/dropdownFlexible.html

- [] I have written a descriptive pull-request title
- [] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

fixes: U4-11306 Add load indicators in doc type infinite editors

---

src/Umbraco.Core/PropertyEditors/ConfigurationEditor.cs
src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
src/Umbraco.Web.UI.Client/src/controllers/navigation.controller.js
src/Umbraco.Web/Editors/ContentTypeController.cs

http://issues.umbraco.org/issue/U4-11284

Fixes - U4-11284 When you don't have any doc types that are variant, the tree language drop downs should not be there

---

src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json

Fixed typos in tours

---

src/Umbraco.Web/Routing/ContentFinderByUrlAlias.cs

See http://issues.umbraco.org/issue/U4-11378

U4-11378 - ContentFinderByUrlAlias

---

src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json

Corrected the tool tips for Getting Started. Fixed the spelling in a couple of places, added missings words and amended some grammar and punctuation.

Corrected spelling and grammar in the Getting Started tool tips for v7.

---

src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less

Found this issue and though it was an easy one for me to fix - http://issues.umbraco.org/issue/U4-11367 - After looking through older releases i found the source of the problem, the "position:relative;" was removed, so i tried putting it in again, and i haven't found any issues after :)

U4-11367 - Show trashbin icon again

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html

…element and scope.
Added extension points to the grid so we can make packages of misc. extensions that are currently PRs due to missing extension points. Should also be simple to add more and easily accept further PRs when new events are needed.

U4-11356 Events emitted from the grid on init, row added and item added

---

docs/V8_GETTING_STARTED.md

Just a quick link to the "how to contribute" page on v7 as its the same process for v8.

Linked to "how to contribute" for v7

---

docs/V8_GETTING_STARTED.md

Got bit by my VS2017 version not being new enough so to save others here it is nice and in your face!

Made the need for VS2017 version 15.7+ REALLY clear!

---

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html

fix icon contet flashes + update to new component syntax

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

For all the new / edited keys at the 7.10 state.

U4-11430 - Backoffice UI localization update (ru-RU)

---

src/Umbraco.Web.UI/config/EmbeddedMedia.Release.config
src/Umbraco.Web.UI/config/EmbeddedMedia.config

fixed typo's in EmbeddedMedia.config file
http://issues.umbraco.org/issue/U4-11438
Add issuu.com support for oembed functionality

U4-11438 Add issuu.com oembed functionality

---

src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs

See w42 issue, if you see what I mean.

Fix new media not showing in published cache

---

src/Umbraco.Web.UI/umbraco/config/lang/ru.xml

latest keys for upcoming v 7.11

U4-11430 - adds new UI localization keys (ru-RU) for v7.11

---

src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
src/Umbraco.Core/Configuration/UmbracoSettings/IContentSection.cs
src/Umbraco.Core/IO/MediaFileSystem.cs

New mediapath scheme becomes default

---

src/Umbraco.Web.UI/config/EmbeddedMedia.Release.config
src/Umbraco.Web.UI/config/EmbeddedMedia.config

U4-11461 - Add OEmbed support for Twitter.com

---

src/Umbraco.Web/Trees/ContentTreeController.cs
src/Umbraco.Web/Trees/ContentTreeControllerBase.cs

http://issues.umbraco.org/issue/UAAS-745#

Fixes - User permissions does not work in listview in 7.10.4

---

src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/RegisterMember.cshtml

Spelling correction

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js

What did you do?
1. In chrome go to a website other than the umbraco site, right click - copy image
2. In umbraco site HTML editor paste image
3. Left click on image in HTML editor, left click on "Media Picker"
What did you expect to happen?
No error 
What actually happened?
Error: Failed to retrieve data for media id undefined
Issue: http://issues.umbraco.org/issue/U4-11335

U4-11335 Failed to retrieve data for media id undefined

---

src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
src/Umbraco.Core/Configuration/UmbracoSettings/IContentSection.cs
src/Umbraco.Core/IO/IMediaPathScheme.cs
src/Umbraco.Core/IO/MediaFileSystem.cs
src/Umbraco.Core/IO/MediaPathSchemes/CombinedGuidsMediaPathScheme.cs
src/Umbraco.Core/IO/MediaPathSchemes/OriginalMediaPathScheme.cs
src/Umbraco.Core/IO/MediaPathSchemes/TwoGuidsMediaPathScheme.cs
src/Umbraco.Core/Runtime/CoreRuntimeComponent.cs
src/Umbraco.Core/Umbraco.Core.csproj

media path

---

src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
src/Umbraco.Web.UI.Client/src/views/documenttypes/create.controller.js
src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
src/Umbraco.Web/Editors/ContentTypeController.cs
src/Umbraco.Web/Models/ContentEditing/DocumentTypeCollectionDisplay.cs
src/Umbraco.Web/Umbraco.Web.csproj

Adds a short cut to create a collection of document types, already associated with each other

Implements doc type collections | connects #73

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Update NL.xml with missing translations

---

src/Umbraco.Core/Persistence/DatabaseSchemaHelper.cs

U4-9204: Added a generic TableExists-method

---

src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html

There is a closing i tag which doesn't belong there after the locatize text of the remove buton.
Also the title for the **Edit** button was set as `Open` which needed to be `Edit`.

Fix wrong closing i tag and wrong title for edit button

---

src/Umbraco.Web.UI/umbraco/Views/Default.cshtml

Adds friendlier "Enable JavaScript" message. Adapted from <https://enable-javascript.com/> guidelines.
Moves the `<noscript>` tags into the main body - within `#mainwrapper` (fullscreen overlay), so to allow the link to work.
Additional commits in this PR ... as I got a bit zealous with editing, then thought they'd been good to send over.
- Removed additional whitespace
- Removed the "type" attribute from the `<script>` tags (not required in HTML5)
- Switched to use the correct `BareMinimumServerVariablesScript` extension method

U4-11187 - Adds friendlier "Enable JavaScript" message

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Added translation for key added in PR #2731

Translated unpublish dialog to dutch

---

src/Umbraco.Web.UI/umbraco/config/lang/it.xml

Pushed italian translation of  prompt, bulk and grid area.

Italian translation of prompt, bulk and grid area

---

src/Umbraco.Web.UI.Client/src/installer/steps/database.controller.js

Fix connection validation on database configuration during install.
Javascript clientside check failed (true === "true")

Hackathon custom db config on install

---

src/Umbraco.Core/Logging/WebProfilerProvider.cs
src/Umbraco.Web/Editors/ContentController.cs
src/Umbraco.Web/Editors/EntityController.cs
src/Umbraco.Web/Editors/MediaController.cs
src/Umbraco.Web/GridTemplateExtensions.cs

Started to break down the large task of removing obsolete methods. Focused on the editors and grid template areas, with a quick update in the `WebProfileProvider`. All looks okay as they were no longer being used (and if publicly exposed then alternatives already exist).

V8 Hackathon: remove obsolete methods

---

src/Umbraco.Core/Services/ILocalizedTextService.cs
src/Umbraco.Core/Services/Implement/LocalizedTextService.cs

Picked up during the V8 Hackathon. Marked for deletion in V8 and no references making use of it, but would benefit from a couple of extra checks from HQ.

V8 Hackathon: Removed method marked for deletion

---

docs/CONTRIBUTING.md

Just a markdown file change so hope didn't need to raise an issue first

Correcting broken link to current v8 branch in CONTRIBUTING.md

---

src/Umbraco.Core/Services/IMediaService.cs
src/Umbraco.Core/Services/Implement/MediaService.cs
src/Umbraco.Tests/Models/MediaXmlTest.cs
src/Umbraco.Tests/Persistence/Repositories/MediaRepositoryTest.cs
src/Umbraco.Tests/PublishedContent/PublishedMediaTests.cs
src/Umbraco.Tests/Services/ContentTypeServiceTests.cs
src/Umbraco.Tests/Services/EntityServiceTests.cs
src/Umbraco.Tests/Services/MediaServiceTests.cs
src/Umbraco.Tests/Services/ThreadSafetyServiceTest.cs
src/Umbraco.Web/Editors/MediaController.cs
src/Umbraco.Web/umbraco.presentation/umbraco/webservices/legacyAjaxCalls.asmx.cs

Delete methods from the interface IMediaService that have now been implemented in IMediaServiceOperation. Also removed implementations of the methods in MediaService and modified calls to them.

Merged IMediaServiceOperations [v8hackaton]

---

src/Umbraco.Tests/FrontEnd/UmbracoHelperTests.cs
src/Umbraco.Web/UmbracoHelper.cs

Refactored the v8 versions of the below methods.
```
class Umbraco.Web.UmbracoHelper
bool ConvertIdObjectToGuid(object id, out Guid guidId)
bool ConvertIdObjectToUdi(object id, out Udi guidId)
bool ConvertIdObjectToInt(object id, out int intId)
```

U4-11492 Clean Umbraco.Web.UmbracoHelper [v8]

---

src/Umbraco.Tests/FrontEnd/UmbracoHelperTests.cs
src/Umbraco.Web/UmbracoHelper.cs

Correcting the v7 PR for Umbraco.Web.UmbracoHelper (U4-11429) so it matches the coding standards, as mentioned in the v8 PR I made (U4-11492)

Correct Umbraco.Web.UmbracoHelper and tests to coding standards

---

src/Umbraco.Web.UI.Client/src/views/content/content.copy.controller.js
src/Umbraco.Web.UI.Client/src/views/content/copy.html

Replace the old checkboxes with the lovely looking umb-toggle. See the before and after images in the issue tracker.

U4-11519 - Use the umb-toggle directive in the "Copy" dialog

---

src/Umbraco.Core/Models/ContentTypeCompositionBase.cs
src/Umbraco.Core/Models/ContentVariation.cs
src/Umbraco.Tests/Services/ContentTypeServiceTests.cs

Variations with Compositions

---

docs/README.md

I have updated the links on the download and install readme file to be our.umbraco.com not our.umbraco.org

Updated the umbraco.org URL's to be umbraco.com

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Added dutch translations for labels added in PR #2342

U4-10681 Added dutch translations for labels added in PR #2342

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Adding danish translations for labels added in PR #2342

Adding danish translations for labels added in PR #2342

---

src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js
src/Umbraco.Web/Editors/TemplateQueryController.cs

Updates the template editor query builder to use the new Umbraco V8 APIs

V8 Hackathon: Query builder updates [v8hackaton]

---

src/Umbraco.Web/umbraco.presentation/item.cs

check for recursive value

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

I updated the `en.xml` and `en_us.xml` lang files for a small grammar improvement that I wanted to fix.
There isn't an issue on the tracker as it was just in (regular) passing I noticed an improvement could be made to the grammar used in these English files.

Updated some lang files grammar

---

src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json

[I am unable to link this to an issue on the tracker because the tracker is down. I did try. Several times.]
- [X ] I have written a descriptive pull-request title
Change wording of tour step 7 to from "Click on your user avatar to open the user profile dialog." to "Now click on..." to indicate that clicking on the avatar is a step in the tour, rather than a description of what it does at runtime.

Tour Step 7 Wording

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

Changed the Danish language file - added the Dictionary title

---

src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.edit.controller.js
src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.list.controller.js
src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
src/Umbraco.Web.UI.Client/src/views/dictionary/list.html

fixes: Update UI on the dictionary editor to match V8 styles

---

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.editor.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.html

fixes: 156: Update nested content css/markup so it doesn't collide with the old package

---

src/umbraco.sln

I removed some files that were still included in the solution that are not longer present in the repo

Removed files from solution that are not longer present in repo

---

src/Umbraco.Web.UI/config/Dashboard.config
src/Umbraco.Web/Scheduling/KeepAlive.cs

http://issues.umbraco.org/issue/U4-11570

fixing U4-11570

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsections.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigation.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor.less
src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation.less
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation.html
src/Umbraco.Web/Models/Mapping/ContentAppResolver.cs

https://waffle.io/umbraco/Umbraco.Private/cards/5b6d401f2f5858001b9ecafc

Temp8 w150

---

src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json

http://issues.umbraco.org/issue/U4-11569
Some very small changes to the Getting Started tour text.

Small tweaks to the Getting Started tour text.

---

src/Umbraco.Core/Services/UserService.cs
src/Umbraco.Web/Editors/EntityController.cs

The Umbraco.UserPicker is unsorted. This change sorts the list alphabetically by name.
Here is the issue:
http://issues.umbraco.org/issue/U4-11597

Sort the Umbraco.UserPicker list alphabetically by name

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html

This PR is not ready for review yet - It's still in WIP state. Description of what has been done will follow once it's ready for review.

U4-11577 - Content Item Info Tab: Editors cannot see document type

---

src/Umbraco.Web/BatchedDatabaseServerMessenger.cs

see http://issues.umbraco.org/issue/U4-11599

U4-11599 - do not abort inst processing on error

---

src/Umbraco.Web/HtmlStringUtilities.cs
src/Umbraco.Web/UmbracoHelper.cs

http://issues.umbraco.org/issue/U4-10029

U4-10029 Umbraco.ReplaceLineBreaksForHtml should return an IHtmlString

---

src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
src/Umbraco.Web/Editors/ContentTypeControllerBase.cs

Fixes for http://issues.umbraco.org/issue/U4-8310 issue. 
(Can't change casing of doc type alias)

Temp u4 8310 - Fixed can't rename of a document type alias by changing its casing

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/util/isolateform.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/util/umbisolateform.directive.js
src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/common/dashboard.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
src/Umbraco.Web.UI.Client/src/views/media/apps/content/content.html
src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json

fixes: 190 - Re-enable tours

---

src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/umb-multiple-textbox.less
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj

Introduced some styling rules to make the view look cleaner
The multiple textstring datatype view is congested. I have introduced some styling rules to make it look neater. 
https://github.com/umbraco/Umbraco-CMS/issues/2933
**Existing**
**Proposed**
Fixes #2933

Clean up multiple textstring(repeatable textstring) view - 

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor.less
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content-editors.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html

fixes: Prevent the same language from being open in split view

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigation.directive.js
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content-editors.html
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js

fixes 200: Stay on the same content app when changing language

---

build/NuSpecs/tools/Readme.txt

Text change, no need for prerequisites on this one I think.

update the release notes url

---

src/Umbraco.Web/Models/Mapping/ContentMapperProfile.cs

Connects Umbraco/Umbraco.Private#204

204 V8 - ListView Variants - Get Published State & UpdateDate for Variant

---

src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/AddLockObjects.cs
src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/UpdateDefaultMandatoryLanguage.cs
src/Umbraco.Core/Persistence/Constants-Locks.cs
src/Umbraco.Core/Persistence/Factories/LanguageFactory.cs
src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs
src/Umbraco.Core/Services/Implement/LocalizationService.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/languages/edit.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web/Editors/LanguageController.cs

See issue / work item 103
Review: Should now be possible to check/uncheck mandatory on default language, and should still be possible to change default language etc. Also publishing should not make default mandatory (in fact, should be possible to have no mandatory language).

Remove mandatory constraint on default language

---

src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenTwelveZero/SetDefaultTagsStorageType.cs

Fix casing error when migrating - that causes an issue on some mysql database

fix #3020 - casing errors

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js

Selection in media grid doesn't match when filter has value.

U4-8824 Selection in media grid doesn't match when filter has value

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js

- I have fixed an issue - http://issues.umbraco.org/issue/U4-8143

U4-8143 - MNTP (content picker) does not set $dirty

---

src/Umbraco.Web/PropertyEditors/ValueConverters/MarkdownEditorValueConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/TextStringValueConverter.cs
src/Umbraco.Web/Templates/TemplateUtilities.cs

umbPLfest hackathon - Removed obsolete methods.
This is phase 3 of the work.

umbPLfest hackathon - Removed obsolete methods - phase 3

---

src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-group.less
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.html
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.html
src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/templates/edit.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Temp8 send to publish

---

src/Umbraco.Web.UI.Client/bower.json
src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/src/less/main.less
src/Umbraco.Web.UI.Client/src/views/content/content.rollback.controller.js
src/Umbraco.Web.UI.Client/src/views/content/rollback.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web/Trees/ContentTreeController.cs
src/Umbraco.Web/UI/JavaScript/JsInitialize.js

Temp8 rollback

---

src/Umbraco.Core/Constants-System.cs
src/Umbraco.Web/Trees/DataTypeTreeController.cs

Added the DefaultLabelDataTypeIdas a non-deletable datatype.

U4-6961 Prevent from deleting default used datatypes (e.g. Label)

---

src/Umbraco.Web.UI.Client/package.json

Also updated the version number to reflect the current version.
I have not created an issue for this as it's so small, sorry :)

Updated the URL for the issue tracker.

---

build/NuSpecs/UmbracoCms.nuspec
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.UI/packages.config
src/Umbraco.Web.UI/web.Template.Debug.config
src/Umbraco.Web.UI/web.Template.config

Changes compilation batch mode to true uses Roslyn compiler for views

---

src/Umbraco.Web.UI.Client/src/less/navs.less
src/Umbraco.Web.UI.Client/src/less/panel.less

Issue was brought up where the navigation tabs (when looking at content for example) sometimes jitter on the page and reveal the bottom border that should not be there. [See the original issue for better detail](https://github.com/umbraco/Umbraco-CMS/issues/3051).
I tried to resolve this with minimal effort / changes in mind. I would like some help with QA. I could not longer reproduce the issue now, but want to make sure my changes haven't caused regression in (1) another breakpoint or (2) another page, dialog, etc where this class is used.

Minimal changes to class `nav-tabs` styling

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/less/buttons.less
src/Umbraco.Web.UI.Client/src/less/components/application/umb-dashboard.less
src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-group.less
src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html

Temp8 3094 save button

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstep.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstepcontent.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstepcounter.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstepfooter.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour/umbtourstepheader.directive.js

As described in issue #3099 not all directives for tours are documented.
To test you locally run the docs:serve gulp task.
I noticed the umb-tour-step directive has a size attribute. Setting that will change a css class. But I couldn't find any related styles for this in the less files. 
So I omitted that attribute from the docs for now until we have more clarity on that to avoid confusion.
Maybe @madsrasmussen clarify this one ?

#3099 Added docs for tour directives

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js

Make sure the media grid works in the media section again 😅

#3112 - Media thumbnails no longer visible

---

src/Umbraco.Web/PublishedCache/XmlPublishedCache/XmlPublishedContent.cs

See https://github.com/umbraco/Umbraco-CMS/issues/3063

Lock XmlPublishedContent initialization for thread-safety

---

src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js

PR #3056 broke the "Do something else" button. This PR fixes that
Steps to test 
- Check if do something else button opens the context menu
- Check if a node keeps the active state when right clicking it or bringing up the action menu.

#3141 fixed broken Do something else button

---

src/SolutionInfo.cs

Simple update to the copyright year

Updated copyright year

---

src/Umbraco.Web.UI.Client/src/less/components/application/umb-drawer.less

I have fixed the styling the Learn Umbraco help list see this issue #3183

- fix styling of Learn Umbraco help list

---

src/Umbraco.Core/Manifest/ManifestContentAppDefinition.cs
src/Umbraco.Core/Models/ContentEditing/IContentAppDefinition.cs
src/Umbraco.Tests/Manifest/ManifestContentAppTests.cs
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web/ContentApps/ContentAppDefinitionCollection.cs
src/Umbraco.Web/ContentApps/ContentEditorContentAppDefinition.cs
src/Umbraco.Web/ContentApps/ContentInfoContentAppDefinition.cs
src/Umbraco.Web/ContentApps/ListViewContentAppDefinition.cs

Making content app work for show/hide config in manifest include user roles. For example:
"show": [
"+role/admin"
]
Not sure if this is the best way to do it bu happy to get some feedback and refactor :)

v8 ContentApp Show/Hide per user Role

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Temp8 3092 publish descendants

---

src/Umbraco.Web.UI.Client/src/less/components/card.less

I have added a max-width property to fix and IE issue.  IE doesn't respect the flex with property with padding and box-sizing. Its fixed by setting a max-width to 33.33%

fixing issue in #3292

---

src/Umbraco.Web/Models/Trees/TreeNodeExtensions.cs

While documenting this feature in https://github.com/umbraco/UmbracoDocs/pull/1107, I came across a copy-pasted documentation that was wrong.

Fix documentation of container styling of nodes

---

src/Umbraco.Web/UmbracoHelper.cs

#3314 Adds the right description to UmbracoHelper.Concatenate

---

src/Umbraco.Core/Manifest/ManifestContentAppDefinition.cs

Adding role example to content app manifest.

V8 content apps document new structure

---

src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html

Explicit check if `hideIcons` is `true` and only hide the icons if it is

Only hide icons if hideIcons is set to 'true'

---

src/Umbraco.Core/Models/IContentTypeBase.cs

Saw a question regarding this on the forum, so I might as well update the XML documentation to clarify it a bit 😄

Improved the description for the "Icon" property

---

src/Umbraco.Web/umbraco.presentation/umbraco/Trees/FileSystemTree.cs

Make sure it can find child items in root folders

Update FileSystemTree.cs, fixes #3346

---

src/Umbraco.Core/Persistence/SqlSyntax/MySqlSyntaxProvider.cs
src/Umbraco.Web/Controllers/UmbLoginController.cs
src/Umbraco.Web/Models/TemplateQuery/QueryCondition.cs
src/umbraco.cms/Actions/Action.cs

Hello,
Improve readability by removing commented out code.
What do you think?
Thanks.

Remove this commented out code

---

src/Umbraco.Web.UI/umbraco/config/lang/sv.xml

Fixes incorrect swedish translation

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

The logic is in place now.
need someone to look at
1. Styling of the buttons (dropdown)
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/2927

#2927 - Cannot use content templates in list views

---

src/Umbraco.Web/Trees/MacrosTreeController.cs
src/Umbraco.Web/Trees/MemberGroupTreeController.cs

Fix for Micros and Member Groups trees.

Fixing right-pointing arrow for empty trees.

---

src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
src/Umbraco.Web.UI.Client/src/controllers/navigation.controller.js
src/Umbraco.Web/Templates/TemplateRenderer.cs

Fix spelling mistake

---

src/Umbraco.Core/Services/Implement/ContentService.cs

- [] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
The parameters in the Audit call was in the wrong order

Make temp8 branch build

---

.github/README.md

Added hyphenation to README at desired places
https://github.com/umbraco/Umbraco-CMS/issues/3455

Added hyphenation to README at desired places

---

.github/CONTRIBUTING.md

add a comma

---

src/Umbraco.Core/Services/NotificationService.cs

#3204 outlines the problem nicely. It can be reproduced with any notification, as long as the user with the lowest user ID only signs up to *one* notification on the node in question.
I pointed out the faulty line of code in #3204. However, `NotificationService` has a pair of duplicate methods - apparently to handle sending out notifications for *one* and for *multiple* `IContent` entities, respectively. I have refactored this so there's only one of them that actually does any handling. As it happens, this method didn't have the faulty line to begin with.
Here's a handy SMTP configuration for testing mails by writing them to disk instead of sending them to an SMTP server (saved you a trip to Google, right?).
```xml
<smtp from="me@somewhere.com" deliveryMethod="SpecifiedPickupDirectory"> …
```

Fix #3204 and do some refactoring to avoid duplicate code

---

src/Umbraco.Web.UI.Client/src/controllers/navigation.controller.js

fixed typo

---

src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html

I updated the link to **Community Forum** on the Settings dashboard 😎

Update link to Our Forum

---

.github/README.md

Simple grammar fixes to aid readability.

Various grammar fixes to README.md

---

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/delete.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewpublish.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewpublish.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewunpublish.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/listviewunpublish.html
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web/Models/ContentEditing/ContentItemBasic.cs
src/Umbraco.Web/Models/Mapping/ContentMapperProfile.cs
src/Umbraco.Web/Models/Mapping/MediaMapperProfile.cs
src/Umbraco.Web/Models/Mapping/MemberMapperProfile.cs

Temp8 3469 listview publish

---

src/Umbraco.Web.UI.Client/src/less/property-editors.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html

fix alignment of cropper prevalue inputs

---

src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
src/Umbraco.Web.UI.Client/test/unit/common/services/tree-service.spec.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco.Private/issues/266
https://github.com/umbraco/Umbraco.Private/issues/266 has video with steps to recreate.

Update HasChildren, on removeNode in treeService

---

src/Umbraco.Web.UI/umbraco/config/lang/nl.xml

Typo/spelling/grammar fixes for Dutch translation

---

src/Umbraco.Web.UI.Client/src/common/services/tree.service.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco.Private/issues/264
https://github.com/umbraco/Umbraco.Private/issues/264 shows how to reproduce.
The issue what in a for loop, where we always returned in first iteration.
Fixes: https://github.com/umbraco/Umbraco.Private/issues/264

Bugfix: Can't reload tree Nodes in the Templating area of the Settings section

---

src/Umbraco.Tests/TestHelpers/BaseDatabaseFactoryTest.cs

Fixed a minor typo in BaseDatabaseFactoryTest.cs. 
_My next contribution will be something more helpful_ 😉

Fixed typo in base database factory test class

---

src/Umbraco.Tests/Migrations/Upgrades/SqlCeUpgradeTest.cs

Fix very minor typo in code comment

Fix typo in SqlCeUpgradeTests.cs

---

src/Umbraco.Web.UI/umbraco/developer/RelationTypes/EditRelationType.aspx
src/Umbraco.Web/umbraco.presentation/umbraco/developer/RelationTypes/EditRelationType.aspx
src/Umbraco.Web/umbraco.presentation/umbraco/developer/RelationTypes/EditRelationType.aspx.cs

I have added steps to test this contribution in the description below
This PR adds links to the relation items in the relations view, fixes: #3577 
This PR was done at the Umbraco UK Festival Hackathon

- added links to relation items in relatin view

---

src/Umbraco.Web.UI.Client/src/less/components/overlays.less

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3506
#3506 has steps to recreate.

Fix the flickering on the data type selector

---

src/Umbraco.Web.UI/.eslintignore
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj

Added eslintignore file

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Temp8 3110

---

src/Umbraco.Web.UI.Client/src/controllers/main.controller.js
src/Umbraco.Web.UI.Client/src/controllers/navigation.controller.js
src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml

add overlay to tree when infinite editing is open

---

src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs

Resolved check for removed properties

---

src/Umbraco.Web.UI.Client/src/views/common/dialogs/login.html
src/Umbraco.Web.UI/umbraco/config/lang/da.xml
src/Umbraco.Web.UI/umbraco/config/lang/en.xml
src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3115
This PR updates the "Select avatar" step in the invite user flow as discussed in #3115. It looks like this:
🎄 2/24 🎄

Update the select avatar step for invited users

---

.github/V8_GETTING_STARTED.md

Using HHTTPS as protocol just doesn't work (and yes, it seems I was the one introducing that typo) :-/

V8, Getting Started: typo in URL

---

src/Umbraco.Web/Controllers/UmbLoginController.cs
src/Umbraco.Web/Controllers/UmbLoginStatusController.cs
src/Umbraco.Web/Controllers/UmbProfileController.cs
src/Umbraco.Web/Controllers/UmbRegisterController.cs
src/Umbraco.Web/HtmlHelperRenderExtensions.cs

Making sure the request comes from the right origin before registering a member.

Implementing a validation token when a membership form is submitted.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less

reenable infinite editing animations

---

src/umbraco.sln

The docs seem to have moved at some point and the sln references were not working. This PR fixes that.

Fixes references to docs in sln

---

.github/CONTRIBUTING.md

Fixed minor grammatical error

---

src/Umbraco.Core/Services/MediaService.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/3948

Fix for wrong sorting overload in MediaService (#3948)

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/3656
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/3988
- We now restore the dirty state on the form after save, if any variant is still dirty
- We now save the value of RTE in model.value on change event fired

Temp8 3656 3988 fixes for variants

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js

Temp8 4005

---

src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs

Un-revert of: 
> Identify "element" content types. #4076

unrevert of Identify "element" content types. #4076

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3068
This is the manual V8 merge of #3718. The issues fixed are the same as outlined on #3718, as are the steps to test. Only you need to use the following plugin now due to V8 stuff:
[TestPlugin.zip](https://github.com/umbraco/Umbraco-CMS/files/2756758/TestPlugin.zip)
With this PR applied, the linkpicker behaves like this:
Testing this PR might be a bit hindered due to the fact that the linkpicker is a bit buggy with variant data and that it more often than not fails to load the content tree (with an error in the JS console). Once I have mapped out these issues I'll submit a proper bug report. 
What *can* be tested however is:
1. It doesn't fail miserably if it's opened with a picked …

Fix linkpicker overlay issues - manual merge of #3718 to V8

---

src/Umbraco.Core/Deploy/IValueConnector.cs

- Added PropertyType parameter to IValueConnector.FromArtifact

- Added PropertyType parameter to IValueConnector.FromArtifact

---

src/Umbraco.Core/Deploy/IGridCellValueConnector.cs

Removed Property parameter from IGridCellValueVConnector

Removed Property parameter from IGridCellValueVConnector

---

src/Umbraco.Core/Deploy/IGridCellValueConnector.cs

Decided against remaning after using the new interface in practice.

Redecided on renaming

---

.github/CONTRIBUTING_DETAILED.md
.github/V8_GETTING_STARTED.md
build/build.ps1

The V8 Umbraco.Web.UI project has migrated from Bower to NPM for dependencies. Due to this I have removed mentions of Bower from the documentation and build processes.

Eliminating bower

---

src/Umbraco.Web.UI.Client/src/common/resources/macro.resource.js
src/Umbraco.Web.UI.Client/src/views/macros/delete.html
src/Umbraco.Web.UI.Client/src/views/macros/macros.delete.controller.js
src/Umbraco.Web/Editors/MacroRenderingController.cs
src/Umbraco.Web/Editors/MacrosController.cs
src/Umbraco.Web/Trees/MacrosTreeController.cs

Fixes: #3417
- Added delete functionality
- Using constructor injection i c#

Macro delete

---

src/Umbraco.Core/Constants-PropertyEditors.cs
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html
src/Umbraco.Web/Models/ContentEditing/LinkDisplay.cs
src/Umbraco.Web/Models/Link.cs
src/Umbraco.Web/Models/LinkType.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerConfiguration.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerConfigurationEditor.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs
src/Umbraco.Web/Umbraco.Web.csproj

Hi @nul800sebastiaan 
I've migrated the Multi Url Picker to v8. Not sure if it's the correct way, but I've started a new branch from temp8 and copied the code over and adjusted it.

V8: Add Multi Url Picker

---

src/Umbraco.Web.UI/umbraco/config/lang/da.xml

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4196
This PR fixes localization in Danish of a few tree nodes to be plural instead of singular.

Fix plural localization

---

src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4191
This PR now synctree and the active tree is highlighted.

v8: Sync tree in log viewer overview

---

src/Umbraco.Web.UI.Client/src/less/components/html/umb-expansion-panel.less

Applied hover effect to the expansion panel.

Temp8 ui expansion panel hover

---

src/Umbraco.Core/Cache/HttpRequestAppCache.cs
src/Umbraco.Core/Configuration/UmbracoVersion.cs
src/Umbraco.Core/Persistence/Repositories/Implement/DataTypeRepository.cs
src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
src/Umbraco.Web/PublishedContentExtensions.cs

Simple changes - Only created tasks for fixme and renamed to TODO. 
Fixmes are only allowed for v8.0.0 critical stuff.

Changed Fixme/task to TODO [Link]

---

src/Umbraco.Core/Models/PublishedContent/IPublishedContent.cs
src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs
src/Umbraco.Tests.Benchmarks/XmlPublishedContentInitBenchmarks.cs
src/Umbraco.Tests/Published/NestedContentTests.cs
src/Umbraco.Tests/PublishedContent/PublishedContentDataTableTests.cs
src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
src/Umbraco.Tests/TestHelpers/Stubs/TestPublishedContent.cs
src/Umbraco.Web/Models/PublishedContentBase.cs
src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
src/Umbraco.Web/PublishedCache/PublishedMember.cs
src/Umbraco.Web/PublishedCache/XmlPublishedCache/DictionaryPublishedContent.cs
src/Umbraco.Web/PublishedCache/XmlPublishedCache/XmlPublishedContent.cs
src/Umbraco.Web/umbraco.presentation/page.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/4204
Added IsPublished(string culture = null) to IPublishedContent

Added IsPublished(culture) to IPublishedContent

---

src/Umbraco.Web.UI.Client/src/less/application/grid.less

Changed the UI for resizable handler used to change the width of the left side navigation

Temp8 ui resizeable handler

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html

Fixes #4187 
fix edit links in multi url picker

V8: fix edit links in multi url picker

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/4255
Fixed the UI of the macro picker.
- Added submit button
- Added `block-form`
Before:
Now:

Fixes UI for macropicker and added submit button

---

src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html

Fix for javascript's strict equality

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less

Regarding issue #4257 I have refactored the way infinity editing layers gets added and removed, without lookups of the DOM.

Temp8 4257 refactoring of infinite editor layers

---

src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editors.html

The previous solution with JS-Animation had issues and didn't performe well.
Therefor I want to change it to CSS-Animation, which as well includes a fix for stacking layers.

V8: UI refactoring infinity editing to css animation

---

src/Umbraco.Core/Exceptions/BootFailedException.cs

Don't be sad when boot fails. 🌞

Why so sad! :-)

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js

#4405 - Load history on init if the active tab is info

---

src/Umbraco.Web/Editors/MacroRenderingController.cs

Sets the MacroType when created from Partial View Macro Files

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
src/Umbraco.Web/PropertyEditors/ListViewConfiguration.cs

removes/renames list view settings that don't make sense for v8

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/editconfig.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/editconfig.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowdeleteconfirm.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowdeleteconfirm.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html

#4430 change grid-editor settings to use editorService

---

src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
src/Umbraco.Web/PropertyEditors/TextAreaConfiguration.cs
src/Umbraco.Web/PropertyEditors/TextAreaConfigurationEditor.cs

Fixes: #4490 
- Also fixed a bug, where the `TextAreaConfiguration` was not used for `TextAreas`
Test: 
- Follow the tours.

Updated the tours to match v8

---

src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less

distinguish property group better

Temp8 ui clear distinguish property groups

---

src/Umbraco.Web.UI.Client/src/views/dashboard/content/overlays/delete.html
src/Umbraco.Web.UI.Client/src/views/dashboard/content/overlays/disable.html
src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/Umbraco/config/lang/es.xml
src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/Umbraco/config/lang/pl.xml
src/Umbraco.Web.UI/Umbraco/config/lang/ru.xml
src/Umbraco.Web.UI/Umbraco/config/lang/zh.xml
src/Umbraco.Web.UI/Umbraco/config/lang/zh_tw.xml

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4312
This replaced the traditional javascript confirm with a confirm overlay used in other parts on the v8 UI.

v8: Redirects confirm overlay

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
src/Umbraco.Web/PropertyEditors/MultiUrlPickerPropertyEditor.cs
src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
src/Umbraco.Web/PropertyEditors/ValueConverters/MultiUrlPickerValueConverter.cs

Same fixes as in #4527 but for V8, also fixes anchor/querystring not being saved

V8: Multi Url Picker fixes

---

src/Umbraco.Web.UI/config/serilog.Release.config

Fixes typo defualt -> default

---

src/Umbraco.Core/Composing/CompositionExtensions/FileSystems.cs
src/Umbraco.Core/GuidUtils.cs
src/Umbraco.Core/IO/MediaPathSchemes/CombinedGuidsMediaPathScheme.cs
src/Umbraco.Core/IO/MediaPathSchemes/UniqueMediaPathScheme.cs
src/Umbraco.Core/IO/ShadowWrapper.cs
src/Umbraco.Core/StringExtensions.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/CoreThings/GuidUtilsTests.cs
src/Umbraco.Tests/IO/FileSystemsTests.cs
src/Umbraco.Tests/Strings/StringExtensionsTests.cs
src/Umbraco.Tests/Testing/UmbracoTestBase.cs

See #4674 
Still having problems with deleting media files, in case of directory collision

Fix media paths length issues

---

.github/CONTRIBUTING.md

Was linked to temp8 which no longer exists and results in 404

Updates link to dev-v8

---

src/umbraco.cms/businesslogic/translation/Translation.cs

Replaced Log.Add calls with AuditService.Add in translation.cs
Fixes: #4428

#4428 - Replaced Log.Add calls with AuditService.Add in translations

---

build/NuSpecs/tools/Web.config.install.xdt

Fixes: #4711
Updated versions and added new dependencies to transformation file

Updated versions and added new dependencies to transformation file

---

src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/copy/copy.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/move/move.controller.js
src/Umbraco.Web.UI.Client/src/views/content/content.copy.controller.js
src/Umbraco.Web.UI.Client/src/views/content/content.move.controller.js
src/Umbraco.Web.UI.Client/src/views/content/content.restore.controller.js
src/Umbraco.Web.UI.Client/src/views/media/media.restore.controller.js

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4766
- Fixed list view selected item issue by uncommenting out the umb-table-body__fileicon and umb-table-body__checkicon. 
- Fixed call to nodeSelectHandler in selectListViewNode by removing erroneous first parameter.
- Fixed up other instances where nodeSelectHandler was being passed incorrect number of arguments.
* Install Umbraco 8.0.0 and the starterkit
* Select any item from a list view which is a child item of a document eg following the steps to reproduce given in the linked issue
The Apparel node should be ticked at this stage, but it's not and the above error shows up in the console. It appears to be …

4766 list view selected bug

---

src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.controller.js
src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.html

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4694
The issue outlined in #4694 applies to a bunch of dialogs, all of which have been fixed up here:
- Publish
- Publish with descendants
- Scheduled publish
- Send to publish
- Save
- Unpublish
It looks like this:

V8: Make variant state clickable in various dialogs

---

src/Umbraco.Web/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/4609
Steps to reproduce: See issue

Bugfix: Could not render macros in RTE

---

src/Umbraco.Web/Models/Mapping/RedirectUrlMapperProfile.cs

If there's an existing issue for this PR then this fixes #4580
Inside commit https://github.com/umbraco/Umbraco-CMS/commit/7b55d2f1b2fce1a3bb8eadbd32028598785658e3#diff-8c430fcbade7d23f179204f2d6146c9f there was a small mistake using Id instead of ContentId to lookup the url.

Redirects management is broken #4580

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/4652 for V8, the other PR(https://github.com/umbraco/Umbraco-CMS/pull/4653) couldn't merge.

change insertContent to selection.setContent

---

src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Core/Migrations/Upgrade/V_8_1_0/ChangeNuCacheJsonFormat.cs
src/Umbraco.Core/Models/PublishedContent/PublishedCultureInfos.cs
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
src/Umbraco.Web/Macros/PublishedContentHashtableConverter.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.ContentDataSerializer.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.DictionaryOfCultureVariationSerializer.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/ContentData.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/ContentNestedData.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/CultureVariation.cs
src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs

Fix NuCache url segments

---

build/build.ps1

If there's an existing issue for this PR then this fixes: 
Now we can do: `build.ps1 SetUmbracoVersion 8.1.0` (or `build.ps1 SetUmbracoVersion 8.9.10-alpha` etc).

Temp8 build script

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html

Correction of recent change of checkboxlist to use umb-checkbox, which broke the front-end validation. This PR fixes that, no issue, just this PR.

fix front-end requirement of umb-checkbox

---

.github/CONTRIBUTING_DETAILED.md

Please test that these commands are the only commands required to run front-end setup of V8.
npm cache clean
npm install
npm run build

Updated CONTRIBUTING_DETAILED to fit new npm setup

---

src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
src/Umbraco.Web/Install/InstallHelper.cs

Fix for exit preview with null culture

---

src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/4827

V8: Fix for MediaPickerValueConverter when config is only images

---

src/Umbraco.Core/Composing/Composition.cs
src/Umbraco.Tests/Composing/CompositionTests.cs
src/Umbraco.Tests/Umbraco.Tests.csproj

IFactory is resolvable

---

src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/4967

V8: Fix for ordering by isPublished in list view

---

src/Umbraco.Core/Scoping/ScopeContextualBase.cs
src/Umbraco.Tests/Cache/SnapDictionaryTests.cs
src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
src/Umbraco.Web/PublishedCache/NuCache/Snap/GenObj.cs
src/Umbraco.Web/PublishedCache/NuCache/Snap/GenRef.cs
src/Umbraco.Web/PublishedCache/NuCache/Snap/LinkedNode.cs
src/Umbraco.Web/PublishedCache/NuCache/SnapDictionary.cs
src/Umbraco.Web/Umbraco.Web.csproj

bugfix nucache panic

---

src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-table.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html

This PR makes the Name and Icon of a ListView item turn grey if the item is unpublished. (We had something similar to this before but it somehow got lost)

Make unpublished items in list view show with grey text-color on name

---

src/Umbraco.Web.UI.Client/src/less/components/tooltip/umb-tooltip.less
src/Umbraco.Web.UI.Client/src/less/components/umb-content-grid.less
src/Umbraco.Web.UI.Client/src/less/components/umb-folder-grid.less
src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-cards.less
src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-table.less
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html

Requires https://github.com/umbraco/Umbraco-CMS/pull/5023 to be approved and merged first!
This PR add hover states to grid and list items that can be selected.

Hover state for selectable items in Lists and Grids

---

src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js
src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less

Changed the look of notifications to have rounded corners and margin around for a more light look, which also gives it a bit more attention.
Increased the auto remove time a little (from 7sec to 10sec) to have good enough time to read and understanding the notification.

V8: UI changed notification style

---

src/Umbraco.Core/UriExtensions.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/5019

Changed log level of single error to debug

---

src/Umbraco.Web.UI.Client/src/less/modals.less
src/Umbraco.Web.UI.Client/src/less/properties.less
src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html

fixes https://github.com/umbraco/Umbraco-CMS/issues/4669
fixes https://github.com/umbraco/Umbraco-CMS/issues/5082
Now it should look like:
for non-variants:
for variants:

UI changes for Schedule Publishing

---

src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/umb-logviewer.less
src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html

The logviewer uses the _umb-package_ classes and stylesheet . I have created a new stylesheet _umb-logviewer.less_ and classes specific to logviewer. Also left aligned the saved searches to make it look a bit better
Before
After

General tidy up of styles for logviewer

---

src/Umbraco.Core/CompositionExtensions.cs
src/Umbraco.Web/BatchedDatabaseServerMessenger.cs
src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs

Better ServerMessenger configuration

---

src/Umbraco.Web.UI/Umbraco/Install/Views/Index.cshtml
src/Umbraco.Web.UI/Umbraco/Views/AuthorizeUpgrade.cshtml
src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
src/Umbraco.Web/Editors/BackOfficeController.cs
src/Umbraco.Web/Install/Controllers/InstallController.cs
src/Umbraco.Web/Umbraco.Web.csproj
src/Umbraco.Web/ViewDataExtensions.cs

See priv.284 - adresses some issues with ViewBag
We were using ViewBag in some places and ViewBag is dynamic hence slower + the way we used it caused exceptions to be thrown during boot (captured with PerfView) - this PR simply replaces ViewBag accesses with direct ViewData accesses
Review = code review + all tests (should be green) + site should work, pretty simple.

Replace dynamic ViewBag with ViewData

---

src/Umbraco.Web.UI.Client/src/less/modals.less

Added a dimmed layer for umb-modelcolumn to fix the given issue.
fixes https://github.com/umbraco/Umbraco-CMS/issues/4828
See issue for a good testing description.

fixes 4828 — by adding dimmed-layer for umb-modelcolumn 

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
src/Umbraco.Web.UI.Client/src/less/variables.less
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Fixes https://github.com/umbraco/Umbraco-CMS/issues/4427
Changes behaviour of textString and textArea limits.
This commit only shows text if close to maximum limit. If the amount of characters exceeds the limit we show a different text that are styled with red text.

Fixes 4427

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.controller.js

fixes issue when viewing textarea in doc-type-editor, see code.

check if value exists

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.controller.js

@nielslyngsoe , you forgot to handle the textbox  - Same issue

Added null-check before updating the count.

---

src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs

Fixes #5121 
See the issue for details
**_Note: this is an 8.0.2 fix so please merge the PR and then cherry-pick the commit into v8/8.0_**

NuCache: fix loading the media cache from local files, was missing media

---

src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js

I wanted to see umb-checkbox instead of input-element of type checkbox to select all items in umb-table listview. No issue assigned, just this PR.

Use umb-checkbox for select all in listview

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html

The list didn't show before, now you will see the options with the value displayed next to each. As it should.
How it should look:

Fixing property editor "checkboxlist" to work in v8

---

src/Umbraco.Core/Mapping/MapperContext.cs
src/Umbraco.Core/Mapping/UmbracoMapper.cs
src/Umbraco.Tests/Mapping/MappingTests.cs
src/Umbraco.Web/Editors/ContentController.cs
src/Umbraco.Web/Editors/EntityController.cs
src/Umbraco.Web/Editors/LanguageController.cs
src/Umbraco.Web/Editors/LogController.cs
src/Umbraco.Web/Editors/RedirectUrlManagementController.cs
src/Umbraco.Web/Editors/RelationController.cs
src/Umbraco.Web/Editors/RelationTypeController.cs
src/Umbraco.Web/Editors/UserGroupsController.cs
src/Umbraco.Web/Editors/UsersController.cs
src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
src/Umbraco.Web/Models/Mapping/ContentVariantMapper.cs
src/Umbraco.Web/Models/Mapping/DataTypeMapDefinition.cs
src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs
src/Umbraco.Web/Models/Mapping/LanguageMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MacroMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MediaMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MemberMapDefinition.cs
src/Umbraco.Web/Models/Mapping/TabsAndPropertiesMapper.cs
src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
src/Umbraco.Web/TagQuery.cs
src/Umbraco.Web/Trees/ContentTypeTreeController.cs
src/Umbraco.Web/Trees/DataTypeTreeController.cs
src/Umbraco.Web/Trees/MediaTypeTreeController.cs
src/Umbraco.Web/Trees/TemplatesTreeController.cs

Fix mapping of enumerable

---

src/Umbraco.Web/PublishedCache/ContextualPublishedCache.cs

This PR fixes `ContextualPublishedCache.GetById(bool preview, Guid contentKey)` not passing the specified `preview` value to the actual implementation and therefore always use the value from `UmbracoContext.InPreviewMode`.
I've also added new `GetById` methods that accept an `Udi` and behaves the same way as `PublishedContentQueryExtensions.TypedContent()`, e.g. throw an exception if the UDI isn't of type `GuidUdi`. I've also removed the TODO comment from over 2 years ago 😉

Fixed not using preview in GetById and added UDI support

---

src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs

NuCache: fix vanishing content when refreshing content types

---

src/Umbraco.Core/Composing/Composers.cs
src/Umbraco.Tests/Components/ComponentTests.cs
src/Umbraco.Web/Runtime/WebFinalComposer.cs

Fixes #5174
_**This is an 8.0.2 PR, merge into v8/dev then cherry-pick into v8/v8.0**_

Fix composers ordering

---

src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedContentCache.cs
src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedMediaCache.cs
src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
src/Umbraco.Web/PublishedCache/IPublishedCache.cs
src/Umbraco.Web/PublishedCache/NuCache/ContentCache.cs
src/Umbraco.Web/PublishedCache/NuCache/MediaCache.cs
src/Umbraco.Web/PublishedCache/PublishedCacheBase.cs

See #5216 - issue has been fixed, was adressing v7, and this is adressing v8.

Add GetById(Udi) to published caches

---

src/Umbraco.Core/PropertyEditors/DropDownFlexibleConfiguration.cs

Fixes #5273 
Details, reproduction in issue #5273

Make DropDownFlexibleConfiguration class public

---

src/Umbraco.Web/Strategies/NotificationsHandler.cs

_This is the V7 equivalent of #5287_
You can subscribe to notifications for changes in content permissions. Unfortunately these notifications are never sent.
This PR fixes that.
1. Create two users - A and B.
2. Subscribe user A to the permissions event on a content item 
3. Let user B change the permissions for the content item, e.g. alter the "Editor" role permissions. Verify that user A is notified about it.
4. Let user B undo the changes made, and verify that user A is notified about it.
**Hint:** This SMTP configuration might make testing a bit easier 😄 
```xml
<smtp from="you@rock.dk" deliveryMethod="SpecifiedPickupDirectory">
<specifiedPickupDirectory pickupDirectoryLocation="Path\To\Site\Root\App_Data\MailDump" />
</smtp>
```

V7: Send notifications for changes in permissions

---

src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less
src/Umbraco.Web.UI.Client/src/less/components/umb-checkmark.less
src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-table.less
src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.controller.js
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html
src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html

fixes https://github.com/umbraco/Umbraco-CMS/issues/4682
Before:
Now it should look like:

Selection of users and user groups

---

src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs

Fixes #5315 
Review = code review.
**_Note to reviewer: this is an 8.0.2 fix. Merge into `v8/dev` and then make sure to cherry-pick in `v8/8.0`!_**

Fix paging error in NuCache

---

src/Umbraco.Web.UI.Client/src/common/security/securityinterceptor.js

1. Configure Umbraco to run on a custom backoffice URL, in our example it's `giftapp`
2. Log in
3. Wait for the session to timeout or do a dirty trick: delete the `UMB_CONTEXT` cookies
4. Login screen appears
5. Browser CPU spikes and hundreds of requests are generated for the `GetCurrentUser` endpoint
It seems like this particular file does not expect a custom backend URL:
https://github.com/umbraco/Umbraco-CMS/blob/31084a38a245420d0811b4144c47fd66900830f1/src/Umbraco.Web.UI.Client/src/common/security/securityinterceptor.js#L48
This line seems to do a check to prevent exactly this scenario - an infinite loop, but if fails as it contains the usual backoffice path in the check. The change removes the usual backoffice URL `umbraco` from the URL test. We could get the proper backoffice path …

Backoffice session timeout on custom-URL backoffices leads to high browser CPU and self-inflicted backend DDoS

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

jQuery needed upgrading to 3.4.0 after GitHub gave us a security audit/warning for it

Update jQuery to latest 3.4.0

---

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less

Focus outline for umbraco checkboxes and umbraco radio buttons. And Hovers states for them as well.

focus outline + hover states for umb-checkbox and umb-radio

---

src/Umbraco.Web.UI.Client/src/controllers/main.controller.js

Disables the tabbing-state if the user performes a mouse-click that reaches the window-element.

Disable tabbing state if user clicks

---

src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
src/Umbraco.Web.UI.Client/src/less/sections.less

Added focus outline for app-header-actions

V8: app header action focus outline

---

src/Umbraco.Web.UI.Client/src/less/application/umb-outline.less
src/Umbraco.Web.UI.Client/src/less/belle.less
src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html

I have made a CSS-class called ".umb-outline" to make it easy to apply pretty focus outline for elements.
Like this one:

Created umb-outline to make it easy to apply pretty focus outline for elements.

---

src/Umbraco.Core/Services/Implement/ContentService.cs
src/Umbraco.Core/Services/Implement/MediaService.cs

Fix recycle bin moves

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

Update data-model for TinyMCE in the Grid when changing code or adding a media.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/5075

update RTE model on changing code or media

---

src/Umbraco.Core/Mapping/UmbracoMapper.cs
src/Umbraco.Tests/Mapping/MappingTests.cs

Fix mapper concurrency issue

---

src/Umbraco.Core/Composing/TypeCollectionBuilderBase.cs
src/Umbraco.Web/Mvc/SurfaceControllerTypeCollectionBuilder.cs
src/Umbraco.Web/WebApi/UmbracoApiControllerTypeCollectionBuilder.cs

Make TypeCollectionBuilderBase fluent

---

src/Umbraco.Web.UI.Client/docs/src/api/index.ngdoc

Removing some irrelevant documentation.

Removing a no longer relevant section

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5380
This fixes the issue when selecting an different icon color in listview layout icons. Furthermore the layout didn't preselected (passed in) the existing icon and color as in e.g. document types header.
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js#L227-L248
I have also removed the empty function. It seems silly to have a function, which does nothing.

v8: Fix listview layout icons

---

src/Umbraco.Web/Trees/MacrosTreeController.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5485
Macros aren't sorted alphabetically, as described in #5485:
This PR fixes the sort order:

V8: Sort macros alphabetically

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

This fixes https://github.com/umbraco/Umbraco-CMS/issues/4657
- Fixed animation by wrapping view source editor callback with `safeApply`

V8: Fix TinyMCE source overlay animation

---

src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html

-This is in relation to the accessibility issues on ticket #5277 - Bug number 27 from the table
Added aria labelling and tested with [NVDA](https://www.nvaccess.org/)
Matt

Login errors are not identified for screen reader users

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js

Hi,
This PR should fix the bug with the link picker when using multiple languages.
The problem is described in the following issue: #5360

Fix bug with multi url picker.

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5297
This PR fixes the link picker anchor dropdown as described in #5297:
The only way I found to test this is to insert an anchor link from source view in an RTE and pick the content where that RTE is placed from a link picker or an RTE somewhere else 😄

V8: Fix the link picker anchor list

---

src/Umbraco.Web.UI.Client/src/less/sections.less

This is to fix issue #5277 Number 13
Issue is about visible focus states of the top menu navigation.
Edited the sections.less file, removed the focus state from opacity and added border styling
**nb if you would prefer different styling for the border - I removed the pinklight box shadow and replaced it for a simple grey border as I thought it looked a bit ugly - just let me know

Issue#5277 13

---

src/Umbraco.Web.UI.Client/src/less/components/application/umb-backdrop.less
src/Umbraco.Web.UI.Client/src/less/components/application/umb-search.less
src/Umbraco.Web.UI.Client/src/less/variables.less

If there's an existing issue for this PR then this fixes <https://github.com/umbraco/Umbraco-CMS/issues/5326>
Steps to reproduce available on the issue https://github.com/umbraco/Umbraco-CMS/issues/5326
Post this PR the overlay should look like this

Search shadow-layer should be on top of the user-dialog

---

build/NuSpecs/UmbracoCms.Core.nuspec
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Tests/packages.config
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web.UI/packages.config
src/Umbraco.Web/Umbraco.Web.csproj
src/Umbraco.Web/packages.config
src/UmbracoExamine/UmbracoExamine.csproj
src/UmbracoExamine/packages.config
src/umbraco.MacroEngines/packages.config
src/umbraco.MacroEngines/umbraco.MacroEngines.csproj

This updates to the latest Examine version for v7 (v0.1.90) which contains a [handful of fixes](https://github.com/Shazwazza/Examine/releases/tag/v0.1.90) and [one very important fix](https://github.com/Shazwazza/Examine/issues/113)

Updates to latest Examine

---

src/Umbraco.Web/Routing/IContentFinder.cs

Issue: [5614](https://github.com/umbraco/Umbraco-CMS/issues/5614)

Spelling mistake IContentFinder function

---

src/Umbraco.Web/Editors/UserGroupsController.cs

Fixes #5665
Chery picked from https://github.com/umbraco/Umbraco-CMS/pull/5670  - All credit to @AndyButland :)

V7: Resolved issue where adding non-admin user group editor to group already exists

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js

fixes https://github.com/umbraco/Umbraco-CMS/issues/5345

5345 dragging rte in grid

---

src/Umbraco.Web.UI.Client/src/less/rte.less
src/Umbraco.Web.UI/config/tinyMceConfig.config

Fixes #5600 Adds fullscreen plugin/command to the RTE and allows it to sit in front of the tree when used

Fixes #5600 Adds fullscreen plugin/command to the RTE and allows it to sit in front of the tree when used

---

src/Umbraco.Web.UI.Client/src/views/common/overlays/treepicker/treepicker.controller.js

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5137
As described in #5137: 
When opening a MNTP from a content item somewhere down the tree, the picker automatically syncs to the currently edited content item (feature introduced in 66b0d4e3). However, all the nodes that are loaded in this sync aren't included in the "Allow items of type" filtering. In other words, all the loaded nodes are selectable even if they aren't part of the "Allow items of type" on the MNTP config.
This only happens if you haven't got a specified start node in the content tree (the picker won't sync if you do).
This PR fixes the issue by recursing down the picker tree after it's synced and applying filtering to all nodes in the tree. It's not terribly pretty, …

V7: Setup non-selectable nodes after the treepicker loads

---

src/Umbraco.Web.UI.Client/src/common/mocks/resources/auth.resource.js
src/Umbraco.Web.UI.Client/src/common/mocks/umbraco.httpbackend.js
src/Umbraco.Web.UI.Client/test/unit/app/content/create-content-controller.spec.js

Fixes build as commit 9fffdb4 added a check/call to `GetCurrentUser` and JS test was failing for unexpected HTTP call to GetCurrentUser

Fixes JS Unit Test from commit 9fffdb4 

---

src/Umbraco.Web.UI/config/EmbeddedMedia.Release.config
src/Umbraco.Web.UI/config/EmbeddedMedia.config

- [ x  ] I have added steps to test this contribution in the description below
If there's an existing issue for this PR then this fixes... it!
Added support for embedding Giphy's into rich text area and grid using the Embed option.
To Test:
Use the Embed option and paste your favourite giphy url into the Embed textbox:
https://media.giphy.com/media/xT9IgxiUfXHycuUkRW/giphy.gif
Thanks for accepting my contribution to Umbraco CMS!

V7: Less-Urgent-But-Still-Quite-Important - Add Giphy EmbeddedMedia support

---

src/Umbraco.Core/Persistence/Mappers/AuditItemMapper.cs
src/Umbraco.Core/Persistence/Querying/ModelToSqlExpressionVisitor.cs
src/Umbraco.Core/Persistence/Repositories/IAuditRepository.cs
src/Umbraco.Core/Persistence/Repositories/Implement/AuditRepository.cs
src/Umbraco.Core/Services/Implement/AuditService.cs
src/Umbraco.Tests/Services/AuditServiceTests.cs

Takes care of #5268 in 8.1 - still need PRs for previous versions, though.
See the issue for review/tests + do NOT close the issue when merging - work required for 8.0 and 7.x

Bugfix Audit service

---

src/Umbraco.Tests/Routing/MediaUrlProviderTests.cs
src/Umbraco.Web/Routing/DefaultMediaUrlProvider.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/5906

Fix exception when stored media url is already absolute

---

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js

fix: spelling error in comment :)

---

src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js

Corrected usage examples for entityResource.js
My first Umbraco commit! yay!
Fixes https://github.com/umbraco/Umbraco-CMS/issues/6068
Should be a documentation fix only for https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.resources.entityResource

Fix for 6068 - Corrected usage examples in comments

---

src/Umbraco.Core/Services/NotificationService.cs

Fixes #4713.
When working on this I decided to change the logic so instead of looping over each of the users within a batch, it loops over the notifications associated to the batch of users. 
There are a couple of rules that might require some discussion but can easily be tweaked.
- If one of the entities matches a notification for the user, only send a notification for the entity that first matches
- Only send one notification to a user, don't send multiple notifications for the same action to the same user
These two rules was what made me favour a `while` loop over a `foreach` on `notifications`.  The `isMatched` property and `break` (on line 160) are ensuring multiple notifications aren't sent to the same user.
I've branched from `v7-dev` as we came across this issue with an Umbraco …

Fix notifications not sending when user has multiple of same type

---

src/Umbraco.Web.UI.Client/src/less/main.less

If there's an existing issue for this PR then this fixes #5939 
This PR removes the unused .visuallyhidden class from the main.less file 😃

Remove unused .visuallyhidden class from main.less

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

Fixes #5932, showing "Return to ListView" for new content

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js

Fixes #5931, show breadcrumb for new content

---

src/Umbraco.Web.UI.Client/src/views/content/create.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html

Fix for https://github.com/umbraco/Umbraco-CMS/issues/6155 in v7 seperate PR submitted for v8 fix.

Added track by $index to handle duplicate names in blueprints

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js

Shamelessly taking credit for @viksohal's fix for #6193 by putting his change into a PR...

V7: Core Multi Url Picker doesn't work inside Macro

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js

Fixed #5907 by reloading content on bulk publish / unpublish

---

src/Umbraco.Web.UI.Client/src/views/member/create.html
src/Umbraco.Web.UI.Client/src/views/member/member.create.controller.js

If there's an existing issue for this PR then this fixes <https://github.com/umbraco/Umbraco-CMS/issues/6237>
Steps to reproduce are in the issue
**Before**
**After**

Fix- Unable to create members in the members section using the create option in the overlay

---

src/Umbraco.Web/HtmlStringUtilities.cs

Before returning the html string, referencing issue #6226

Correctly html encode text

---

src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html

Labels and input fields on the login page are not connected to each other, this is a accessibility problem.
So I have added an id to all the input fields and a for attr on the labels.

Loginpage: Added an id to input fields and a for attr on the labels so they are connected

---

.github/REVIEW_PROCESS.md

In the [Contributing.md](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md) , [reviews](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md#reviews) section mentions a review process, the link to which currently 404's. 
Poornima

Added ReviewProcess.md file

---

src/Umbraco.Web.UI.Client/src/installer/installer.service.js

related to, but doesn't resolve, this issue: https://github.com/umbraco/Umbraco-CMS/issues/6271
Just updates the number of people who attend CG last year

updated to 700 people

---

src/Umbraco.Core/Models/PublishedContent/IPublishedContentTypeFactory.cs
src/Umbraco.Core/Models/PublishedContent/PublishedContentType.cs
src/Umbraco.Core/Models/PublishedContent/PublishedContentTypeFactory.cs
src/Umbraco.Tests/Services/MemberServiceTests.cs

Fix member properties [#6227]

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html

This PR cherry picks a few commits merged to `v8/dev` in https://github.com/umbraco/Umbraco-CMS/pull/6258
We should probably also change this comment in docs from `<code>id</code>` to `<code>input-id</code>`.
It also seems the documentation needs to be updated since none of these components are shown here https://our.umbraco.com/apidocs/v8/ui/#/api

v8: umbCheckbox and umbRadiobutton fixes

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html
src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html

This PR fixes an issue, where `onChange` in `umbCheckbox` and `umbRadiobutton` didn't work as expected and didn't return the expected parameters in the callback function.

v8: Fix onChange callback in umbCheckbox and umbRadiobutton

---

src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs

Bugfix NuCache ContentStore

---

src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html

Just a few fixes to work with optional `on-change` and make radiobuttons a bit more consistent with checkboxlist.

v8: Checkbox radio onchange fix

---

src/Umbraco.Web.UI.Client/src/installer/steps/user.html

This PR fixes [https://github.com/umbraco/Umbraco-CMS/issues/6381](https://github.com/umbraco/Umbraco-CMS/issues/6381)
Changed the anchor tag for the 'customize' button to a button element on the first Install screen.

Changed 'customize' anchor tag to a button element

---

src/Umbraco.Web.UI.Client/src/installer/steps/starterkit.html
src/Umbraco.Web.UI.Client/src/less/installer.less

This PR fixes [https://github.com/umbraco/Umbraco-CMS/issues/6383](https://github.com/umbraco/Umbraco-CMS/issues/6383)

Change link text for installing starter kit thumbnail & update styles

---

src/Umbraco.Web.UI.Client/src/views/languages/overview.html

Fix Issue #6380
Change the button style from success style to action style

Set add language button to correct colour

---

src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js

Fix RTE Upload (Due to merge conflict & refactor) 🙈 
* Check code
* Test, test and test again to make sure nothing was missed
@bergmania you have been good at catching issues with this, so please test this 😄

Fix RTE Upload (Due to merge conflict & refactor) 🙈 

---

src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html

Updated all umb-password id's in `umb-login.html` to be unique
`[DOM] Found 2 elements with non-unique id #umb-password`

Use unique IDs for all password fields in umb-login

---

src/Umbraco.Web.UI.Client/src/views/member/edit.html
src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js

I am trying to enable infinite editors for Diplo God Mode, and noticed that members didn't support this. So I added that, in this PR 🙂

enables infinite editing for members

---

src/Umbraco.Web.UI.Client/src/views/partialviews/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/partialviews/edit.html

I am trying to enable infinite editors for Diplo God Mode, and noticed that partial views didn't support this. So I added that, in this PR 🙂

enables infinite editing for partial views

---

src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

<### Prerequisites
If there's an existing issue for this PR then this fixes #6455 
I have changed the following
- Added language keys so the non-visual texts can be translated
- Hidden the `<i>` tag from screen readers
- Removed some inline styling
@nul800sebastiaan This one is ready for review 👍

Fix minor issues in umb-app-header

---

src/Umbraco.Web.UI.Client/package.json

This PR updates noUiSlider to latest patch version 14.0.2 to fix a minor bug in the sliders used in Umbraco.
https://github.com/leongersen/noUiSlider/issues/1000

v8: Update noUiSlider to latest patch version

---

src/Umbraco.Web.UI/Umbraco/config/lang/de.xml

This is a PR for feature/request:
https://github.com/umbraco/Umbraco-CMS/issues/5678
I have taken the en_us.xml as basis and added all missing keys and translated them.
Did my best to validate them in the back office too.
Yours
Dirk

Idseefeld umbraco config lang de

---

src/Umbraco.Web/Media/EmbedProviders/Flickr.cs

Seems to have been missing in quite a lot of versions :)

fix: Missing "=" in Flickr markup

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

More punctuation for the Danish descriptions

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

Added missing translations for Danish

---

src/Umbraco.Web/Editors/UsersController.cs

Just one wee change to make the repo that bit more inclusive :)

More inclusive language

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

Added new translation for issue #6484

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html

Added missing class to apply correct font family to custom icons

Added missing class

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js

Noticed that I've added `$scope` in my last PR where it should't be, this fixes it.

Too much scope

---

src/Umbraco.Web.UI.Client/src/views/relationtypes/create.controller.js

Added missing semi colons to the Umbraco.Editors.RelationTypes.CreateController

Added missing syntax to Umbraco.Editors.RelationTypes.CreateController controller

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

I found some missing dictionary keys, and added them.
Also changed the one for "Last locked out date", as I think the wording could be better.

Adds missing danish dictionary keys, and changes a few others

---

src/Umbraco.Core/Models/Membership/UserGroupExtensions.cs
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.controller.js
src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html
src/Umbraco.Web/Editors/Filters/UserGroupValidateAttribute.cs
src/Umbraco.Web/Editors/UserGroupsController.cs
src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs

If there's an existing issue for this PR then this fixes #6377
I've disabled the possibility to select and delete the "Sensitive data" user group

Disallow deleting "Sensitive data" user group

---

src/Umbraco.Examine/ContentIndexPopulator.cs

If there's an existing issue for this PR then this fixes #6655 
setting the publishedQuery if not already set

Fix ContetIndexPopulator publishedQuery

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js

Fixes #6499 
Steps to test this contribution are outlined in #6499 by creating the required doc types and performing the bulk actions copy and move and verifying that list view is refreshed after the bulk operations have been completed

Fixes #6499 by reloading the content in list view after bulk copy/move

---

src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/3604
Added Publish date and unpublish date to info app, they are only shown if they have a value

Add publish and unpublish date to info app

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.html
src/Umbraco.Web/ContentApps/ListViewContentAppFactory.cs
src/Umbraco.Web/PropertyEditors/ListViewConfiguration.cs

If there's an existing issue for this PR then this fixes #4747
This PR adds the ability to change the icon for the list view content app.
To test, open the list view configuration and select an icon. Then open the node containing the list view, to verify that the icon is now custom :)
Or see the gif

Makes it possible to change the icon for list view content apps

---

.github/BUILD.md
.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/CONTRIBUTION_GUIDELINES.md

If there's an existing issue for this PR then this fixes (none)
I was browsing through and found the spelling mistake 'occassion' -> 'occasion'.  
Afterward, I decided to quickly proofread the rest of the .md's, and found a couple smaller errors, mostly verb-noun agreement.  
The edits do not break the structure of the mds, so there's no need to test.
Signed-off-by: Kewbish <kewbish@gmail.com>

Grammar and spelling changes

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

Changed **Installeret pakker** to **Installerede pakker**:

Fixed title to proper danish

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

Added apostrophe to Filtrer... in danish

---

src/Umbraco.Web.UI/Umbraco/config/lang/de.xml

Keep it similar to "addGridLayout" or "addRowConfiguration" and also in line with "areAdded".

Keep wording consistent in DE language file

---

src/Umbraco.Web.UI.Client/gulp/tasks/watchTask.js

fixes https://github.com/umbraco/Umbraco-CMS/issues/6819

Correct mistake in WatchTask of our Gulp Script

---

.github/CONTRIBUTING.md

I know it's cheesy to update a .md for hacktoberfest but I have been dying to put some things in here and to switch some things around. Perhaps you'll disagree on the 'easiest way to build the source code' but I wanted to invert the two because I find clicking lots easier. If not, we can fight it out! 😄

Let's say more about contributing

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html

When I worked on #4526 this weekend I discovered that some of the editors that open don't have focus set on the first focusable item.
I have fixed it for the "media picker" and the "link picker" with this PR. If the first element does not have focus then the focus lock will not work as expected 😃

Add "umb-auto-focus" on media and link pickers

---

src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs

The more items you add to a Nested Content property, the longer the containing page takes to load and save. Here's a comparison between an empty Nested Content property and one with some items:
This PR optimizes the way `NestedContentPropertyValueEditor` fetches the element type blueprints of the contained items. This yields a surprisingly high performance gain:
To validate this I created a silly little profiling session within the save operation of `ContentController`. Here's the time spent collecting Nested Content property values before this PR is applied:
...and here is after:
That's something! And that's only for saving. A similar gain can be found in both the validation and the load operations.

V8: Performance boost for loading and saving Nested Content

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

Improved a few Danish translations for the Users section

---

src/Umbraco.Web/HealthCheck/Checks/Security/BaseHttpHeaderCheck.cs

Slight update for #6748 to address the issue raised in https://github.com/umbraco/Umbraco-CMS/pull/3551#issuecomment-438000340

V8: Health check http header case sensitivity

---

src/Umbraco.Web.UI.Client/src/less/components/umb-logviewer.less
src/Umbraco.Web.UI.Client/src/views/logviewer/search.html

I have moved all inline styles in the log viewer search screen to a stylesheet.

Move all inline styles in the log viewer search screen to a stylesheet

---

src/Umbraco.Web.UI/Umbraco/config/lang/da.xml

added apostrophe so Installer becomes Installér

---

.github/CONTRIBUTING.md
.github/README.md

Fixed the grammatical errors in Contributing and Readme files.

Fixed Grammatical errors

---

src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

Browsing through some files i the backoffice I noticed the log viewer lacked some translations so I added a new ara in the language files called "logViewer" and added the different keys in there and mapped the texts and titles in the view to using the language keys.
Keys are added for en, en_us and da.

Log viewer: Localize texts and titles

---

src/Umbraco.Examine/ContentIndexPopulator.cs
src/Umbraco.Examine/IUmbracoContentIndex.cs
src/Umbraco.Examine/IUmbracoMemberIndex.cs
src/Umbraco.Examine/MemberIndexPopulator.cs
src/Umbraco.Examine/Umbraco.Examine.csproj
src/Umbraco.Examine/UmbracoContentIndex.cs
src/Umbraco.Examine/UmbracoMemberIndex.cs

If there's an existing issue for this PR then this fixes #6705 
In Following of conversation with Shannon I prepared interfaces to use in Populators instead of using Lucene base type.
@Shazwazza as promised :)

Create Interface for Member and Content Index to use in Populators

---

.github/CONTRIBUTING.md

I always forget this.... And it's nowhere in the documentation

Added to switch to the correct repository

---

.github/BUILD.md

I always do this wrong and never know which repo to switch to

Add some help if you're on the wrong repo

---

src/Umbraco.Examine/Umbraco.Examine.csproj
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
src/Umbraco.Web/Umbraco.Web.csproj

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7125

V8: Update the projects to use the same dependencies as required by our nuspec

---

src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
src/Umbraco.Web.UI.Client/src/common/resources/relationtype.resource.js
src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relations.html
src/Umbraco.Web/Editors/RelationTypeController.cs
src/Umbraco.Web/Models/ContentEditing/RelationTypeDisplay.cs
src/Umbraco.Web/Models/Mapping/RelationMapDefinition.cs

This adds pagination to the Relation Type on the 'Relations' content app with a new API controller, Angular JS resource & other UI/JS changes as needed.
Fixes [AB#3621](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3621)
* Verify code implemented correctly
* Test you can page correctly & the correct data is returned

AB3621 - Paging Relations UI

---

src/Umbraco.Core/Models/Entities/MemberEntitySlim.cs
src/Umbraco.Core/Models/ObjectTypes.cs
src/Umbraco.Core/Persistence/NPocoDatabaseExtensions-Bulk.cs
src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
src/Umbraco.Core/Persistence/UmbracoDatabase.cs
src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
src/Umbraco.Web/Editors/MediaController.cs
src/Umbraco.Web/Models/ContentEditing/MediaReferences.cs
src/Umbraco.Web/Umbraco.Web.csproj

This adds in pagination to media references (each group/entity type has its own pager)

AB3610 - Pagination of Media References

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7181

check if template tree exists, to avoid error if its not present.

---

src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
src/Umbraco.Web.UI/Umbraco.Web.UI.csproj

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7181

7181 check if the template tree exists before sync.

---

src/Umbraco.Web.UI.Client/src/less/main.less

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7236
Reproduce, install DTGE and see that the styling is fixed.

7236 property action toggle position corrected for non horizontal form for 8.4

---

src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
src/Umbraco.Web/PropertyEditors/GridConfiguration.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7258

7258 hide label for grid rte pre value for 8.4

---

src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
src/Umbraco.Web.UI/Umbraco/Views/Preview/Index.cshtml

This PR updates the UI of the Preview to accommodate more choices. This is mainly made to enable segments and enable the user to switch segments in Preview.
Here a screenshot of how it's supposed to look:
Test notes:
- Test dropdowns and switching between different choices.
- Test you can navigate the UI by keyboard.

Preview UI supporting multiple choices

---

src/Umbraco.Web/Cache/LanguageCacheRefresher.cs

Removed unused _domainService which shows as warning in the build output.

removed unused _domainService

---

src/Umbraco.Web.UI.Client/src/common/services/editor.service.js

added documentation for param startNodeId

---

src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

This is a super simple PR to add a message bar to give context that this node you are viewing is in the recycle bin. This should make a @JeffreyPerplex a little happier too as this improvement was from one of his dreams at his CG19 talk :)
- Adds language keys to en_us.xml and en.xml
- New CSS style rule added
- New HTML markup added to display message based off the trashed bool that's in the API response/data we already have

V8: Add in Recycle Bin context message

---

src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js

Fixes #7209.
Currently when you apply a filter or sort to the user management screen, click to view a user's detail and then click to return to the list of users, the state of the filter/sort isn't saved, and you see the default view.
In this PR I've saved these selections to `$rootScope` and, if present, restored the user view filter and sort from here when returning to the list of users.  `$rootScope` isn't something to overuse of course as it's effectively a global variable, but it seems an appropriate use case here.

V8: #7209 fixes filter in User Management not keeping state

---

src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html

I this PR I have made the following changes
- Changed `<a>` without a `href` value to `<button>`
- Added a visually hidden `<label>` for the search field
- Added `aria-hidden="true"` to `<i>` elements
- Fixed styling accordingly with the changed elements
The repo looks the same as before the changes so makes no sense to add before/after images 😃

Package repo: Accessibility improvements

---

src/Umbraco.Web.UI.Client/src/views/content/create.html

Added aria labelled by to improve screen reader use ability:
Menu improved:
**before**
Blog
**after**
Create an item under Home  list  with 5 items
Blog
**Testing**
Used the starter kit, using keyboard navigation open the context menu of the home node.
Matt

Added aria labeled by to the create document list options

---

src/Umbraco.Web/Mvc/ValidateMvcAngularAntiForgeryTokenAttribute.cs
src/Umbraco.Web/Security/BackOfficeCookieAuthenticationProvider.cs
src/Umbraco.Web/WebApi/Filters/ValidateAngularAntiForgeryTokenAttribute.cs

Adding a cookie path claim for cookie-based authentication which helps verifying that requests contain xsrf token.

Adding extra validation for anti forgery tokens

---

src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs

This fixes the deadlock issue raisedin #7404 as a patch fix for 8.4.1.
There will be a larger fix/refactor of much of this as part of 8.6.0 but this is the smallest change needed to address the problem for now.
Since it's not the simplest thing to replicate without some tools, I've recorded some videos showing the problem and fix.
This video shows the deadlock before the fix which occurs when requests are reading + writing + app is restarting:
https://www.screencast.com/t/UvRsH6Oz
This video shows the application working as it should without any deadlock when requests are reading + writing + app is restarting:
https://www.screencast.com/t/HocqHTCBn
This should be part of an 8.4.1 release.

Fixes #7404 - Deadlock issue

---

src/Umbraco.ModelsBuilder.Embedded/Configuration/ModelsBuilderConfig.cs

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/7466
Minimum test:
- Run using external MB in Dll and DllMode
- Try to save a doc type

V8: Bugfix - Lazy evaluate MB mode

---

src/Umbraco.ModelsBuilder.Embedded/Configuration/ModelsBuilderConfig.cs

Merge of 8.5 into v8/dev

---

src/Umbraco.Tests/Routing/RenderRouteHandlerTests.cs
src/Umbraco.Tests/TestHelpers/ControllerTesting/TestControllerActivatorBase.cs
src/Umbraco.Tests/Testing/TestingTests/MockTests.cs
src/Umbraco.Tests/Web/Mvc/SurfaceControllerTests.cs
src/Umbraco.Web/Compose/PublicAccessComponent.cs
src/Umbraco.Web/Editors/MediaTypeController.cs
src/Umbraco.Web/Macros/PublishedContentHashtableConverter.cs
src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MediaMapDefinition.cs
src/Umbraco.Web/Models/Mapping/MemberTabsAndPropertiesMapper.cs
src/Umbraco.Web/Models/Mapping/TabsAndPropertiesMapper.cs
src/Umbraco.Web/Security/MembershipHelper.cs

Resolves some of #7369 
Replaces Current.Services references with dependency injection where possible in the Umbraco.Web project.

Replace Current.Services references with DI where possible

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

I would like to upgrade AngularJS + NPM to the latest version.

upgrade npm dependencies

---

src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
src/Umbraco.Core/Migrations/Upgrade/V_8_6_0/AddDatabaseIndexesMissingOnForeignKeys.cs
src/Umbraco.Core/Persistence/Dtos/DictionaryDto.cs
src/Umbraco.Core/Umbraco.Core.csproj

Issue for this #6601 
Adds fk index for `cmsDictionary -> parent`

Add missing fk index

---

src/Umbraco.Tests/Cache/PublishedCache/PublishedContentCacheTests.cs

Unit test Current.Service references replaced with mocks to assist with https://github.com/umbraco/Umbraco-CMS/issues/7369
Unit test Current.Service references replaced with mocks

Unit tests update to replace Current.Service references

---

src/Umbraco.Core/Migrations/MigrationBase_Extra.cs

In SQL Server, use sp_rename in ReplaceColumn rather than adding a new column and copying the data.

Migrations - Use sp_rename in ReplaceColumn when available

---

src/Umbraco.Web/umbraco.presentation/umbraco/developer/RelationTypes/EditRelationType.aspx.cs

Html encoding document names when rendered in the Relation Types views

---

src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs

Changes to setting the `edited` flag on content versions:
- Mark unpublished versions as edited
- Handle NULL `languageId` or `segment` when matching newest and published versions
- Only update the `edited` flag once per node ID, in case there are changes to multiple properties

Migrations - setting edited flag for versions

---

src/Umbraco.Core/Collections/TopoGraph.cs

If there's an existing issue for this PR then this fixes #7585 
I added more name and type of missing dependency.
Testing:
Try to install package from the issue and you should receive:
```System.Exception: Missing dependency for type Node`2, with key meta.```
instead
```System.Exception: Missing dependency.```

Add more descriptive exception

---

src/Umbraco.Web.UI.Client/src/views/users/group.html
src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html

This PR replaces add buttons in user detail and user group views to use `button` element instead of anchor element and improves accessibility.

Use button element in user detail and user group views

---

src/Umbraco.Core/Cache/WebCachingAppCache.cs
src/Umbraco.Core/HashGenerator.cs
src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/MergeDateAndDateTimePropertyEditor.cs
src/Umbraco.Core/Packaging/ConflictingPackageData.cs
src/Umbraco.Core/Packaging/PackagesRepository.cs
src/Umbraco.Core/Persistence/Repositories/Implement/MacroRepository.cs
src/Umbraco.Core/Persistence/Repositories/Implement/TemplateRepository.cs
src/Umbraco.Core/Xml/XmlHelper.cs
src/Umbraco.TestData/UmbracoTestDataController.cs
src/Umbraco.Tests/Logging/LogviewerTests.cs
src/Umbraco.Tests/Persistence/Repositories/MacroRepositoryTest.cs
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Gallery.cshtml
src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3.cshtml
src/Umbraco.Web/Cache/MacroCacheRefresher.cs
src/Umbraco.Web/Editors/DataTypeController.cs
src/Umbraco.Web/Editors/PackageInstallController.cs
src/Umbraco.Web/Media/Exif/ExifBitConverter.cs
src/Umbraco.Web/Media/Exif/ExifExtendedProperty.cs
src/Umbraco.Web/Media/Exif/JFIFExtendedProperty.cs
src/Umbraco.Web/Media/Exif/JPEGSection.cs
src/Umbraco.Web/Media/Exif/MathEx.cs

Hello Guys,
I was reviewing code and notice a lot of empty statements in code.
I decide to clean up that little :)

Remove Empty Statements

---

src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
src/Umbraco.Web.UI.Client/src/less/components/umb-property-actions.less

Fixes https://github.com/umbraco/Umbraco-CMS/issues/7285
plus it makes nested content items actions appear on focus
---
_This item has been added to our backlog [AB#4098](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4098)_

7285 making property actions show on focus within

---

src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less

Hey @emmaburstow, this is the re-do of the one I destroyed. Same change, same file, same result.

add pointer-events:none on disabled checkbox/radio

---

src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle.less

Slightly brighter disabled state.

Umb-toggle: Slightly brighter disable state

---

src/Umbraco.Configuration/Umbraco.Configuration.csproj
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
src/Umbraco.Examine/Umbraco.Examine.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.ModelsBuilder.Embedded/Umbraco.ModelsBuilder.Embedded.csproj
src/Umbraco.Persistance.SqlCe/Umbraco.Persistance.SqlCe.csproj
src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
src/Umbraco.TestData/Umbraco.TestData.csproj
src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
src/Umbraco.Tests/Umbraco.Tests.csproj
src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj

This is just a temp PR that helps me while updating the build pipeline

Netcore: Updated projects to have C# 8 support

---

src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValueConverter.cs

If the image cropper value is null or invalid, then a YSOD will occur because `value` will be null. 
The stack trace is like this:
```
Server Error in '/' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
Source Error:
Line 30:                         </div>
Line 31:                         <div class="col-s-6">
Line 32:                             @if (Model.CroppedPostImageUrl != null && !Model.CroppedPostImageUrl.IsNullOrWhiteSpace())
Line 33:                             { …
```

Missing null check which will cause a YSOD if empty value

---

src/Umbraco.Web/Models/PartialViewMacroModel.cs

Implement IContentModel on PartialViewMacroModel - fixing #7504

Ensure macromodel implements IContentModel, fixing #7504

---

src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs
src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/GridPropertyIndexValueFactory.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
src/Umbraco.Tests/PublishedContent/PublishedContentTestBase.cs
src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
src/Umbraco.Web/Umbraco.Web.csproj

❗️  **PR https://github.com/umbraco/Umbraco-CMS/pull/7712 should be merged first!**  ❗️ 
Moving the rest of the property editors to Infrastructure.

Netcore: Move property editors to Infrastructure

---

src/Umbraco.Web.UI.Client/src/common/mocks/services/localization.mocks.js
src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
src/Umbraco.Web.UI/Umbraco/config/lang/cs.xml
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/de.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
src/Umbraco.Web.UI/Umbraco/config/lang/es.xml
src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
src/Umbraco.Web.UI/Umbraco/config/lang/he.xml
src/Umbraco.Web.UI/Umbraco/config/lang/it.xml
src/Umbraco.Web.UI/Umbraco/config/lang/ja.xml
src/Umbraco.Web.UI/Umbraco/config/lang/ko.xml
src/Umbraco.Web.UI/Umbraco/config/lang/nb.xml
src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
src/Umbraco.Web.UI/Umbraco/config/lang/pl.xml
src/Umbraco.Web.UI/Umbraco/config/lang/pt.xml
src/Umbraco.Web.UI/Umbraco/config/lang/ru.xml
src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
src/Umbraco.Web.UI/Umbraco/config/lang/zh.xml
src/Umbraco.Web.UI/Umbraco/config/lang/zh_tw.xml

Changed showPage to Save and publish updated button style to link

---

src/Umbraco.Web/Routing/PublishedContentNotFoundHandler.cs

Fixed document outline on built-in 404.

Corrected document outline

---

src/Umbraco.Core/Models/Property.cs
src/Umbraco.Tests/Services/ContentServiceTests.cs

Fixes https://github.com/umbraco/Umbraco-CMS/issues/5513
Turns out that property values weren't being properly cloned at all 😱
This could cause all sorts of other repercussions since any content (and media, members) resolved from the cache, if their values are updated without saving, those values are actually persisted in the cache because the values were never being cloned. That is a simple explanation but could have larger unknown consequences.

Fixes issue with deep cloning property values

---

src/Umbraco.Core/Services/IMembershipRoleService.cs
src/Umbraco.Core/Services/Implement/MemberService.cs
src/Umbraco.Tests/Services/MemberServiceTests.cs

Quite often you need a list of IDs instead of names for groups, but actually Umbraco didn't have to retrieve that using member service,  I added them to Umbraco as I think it could be actually helpful to have them instead of using directly repository

GetAllIds for Roles

---

src/Umbraco.Web.UI.Client/src/installer/installer.service.js
src/Umbraco.Web.UI.Client/src/installer/steps/database.controller.js
src/Umbraco.Web.UI.Client/src/installer/steps/machinekey.controller.js
src/Umbraco.Web.UI.Client/src/installer/steps/starterkit.html
src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js

A few adjustments to installer where some properties in `installerService` get assigned a value `null` instead of `undefined`. Furhermore the anchor element on starterkit view is changed to a `button` element.

Installer adjustments

---

src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js

Simple copy/paste to document a useful method

Add documentation to downloadFile-method

---

src/Umbraco.Configuration/Models/GlobalSettings.cs
src/Umbraco.Core/Constants-Configuration.cs
src/Umbraco.Tests.Common/Builders/Interfaces/IWithApprovedBuilder.cs
src/Umbraco.Tests.Common/Builders/UserBuilder.cs
src/Umbraco.Tests.Common/Builders/UserGroupBuilder.cs
src/Umbraco.Tests.Integration/Extensions/ApplicationBuilderExtensions.cs
src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Gallery.cshtml
src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Media.cshtml

Aligned User and UserGroup builders to the other builders

NetCore: Aligned User and UserGroup builders to the other builders

---

src/Umbraco.Web/GridTemplateExtensions.cs

This PR fixes #7916 - I've added extension methods to implement GetGridHtml() for IPublishedElement

Added support for Grid Editor in an IPublishedElement - resolves #7916

---

src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs

This PR is to address #7874 
Similar to #7058 which has already been fixed and closed, this PR addresses another case where the error is happening

PR to address #7874 (Error with grids in Nested Content)

---

src/Umbraco.Web.UI.Client/src/common/directives/components/users/changepassword.directive.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js
src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js
src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/changepassword/changepassword.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/dropdownFlexible/dropdownFlexible.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.controller.js
src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js

https://trello.com/c/ZQ6Pv900/13-replace-instances-of-angularisobject
Replaces the angular.isObject to the Utilities.isObject as part of the Umbraco's AngularJS divorce

angular.isObject replace to Utilities.isObject

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

This PR add localisation text for the "add new row" button, and also fixes a typo.

V8: Add localisation for add new row button

---

src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
src/Umbraco.Web.UI.Client/src/common/resources/member.resource.js
src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
src/Umbraco.Web.UI.Client/src/common/services/user.service.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.controller.js

https://trello.com/c/rIHJLfDM/12-replace-instances-of-angularisnumber
Decouples IsNumber from angular

Moved from angular.IsNumber to Utilities.IsNumber

---

.github/CONTRIBUTING.md

No exisiting issue
Added links to the required tools list to aid first-time users find the tools.
Expanded the requirement to fill in the PR template to make it clearer where it is.

Added links to the required tools. Added more detail to the PR list

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbkeyboardshortcutsoverview.directive.js
src/Umbraco.Web.UI.Client/src/common/services/tour.service.js
src/Umbraco.Web.UI.Client/src/navigation.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.controller.js

https://trello.com/c/71Cjd6cq/8-replace-instances-of-angularforeach
This PR refactors each instance of angular.forEach to vanilla JS forEach as mentione din the Trello link above 😃 
I realize it's a TON of files to review so please let me know if there is anything I can do to make your jobs easier 👼

Replace instances of angular.forEach with vanilla JS forEach

---

src/Umbraco.Web.UI.Client/bower.json

Upgraded TinyMCE to version 4.9.9
Changelog can be found here https://www.tiny.cloud/docs-4x/changelog/ changed from version 4.9.4 to 4.9.9

v7 Upgraded TinyMCE to version 4.9.9

---

src/Umbraco.Web.UI.Client/package-lock.json
src/Umbraco.Web.UI.Client/package.json

Upgraded TinyMCE to 4.9.9
Changelog can be found here https://www.tiny.cloud/docs-4x/changelog/ changed from version 4.9.7 to 4.9.9

v8: Upgraded TinyMCE to 4.9.9

---

src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbrawmodel.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbnestedcontent.directive.js
src/Umbraco.Web.UI.Client/src/common/interceptors/donotpostdollarvariablesrequest.interceptor.js
src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
src/Umbraco.Web.UI.Client/src/init.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js

This PR fixes https://trello.com/c/kiVAk6fb/1-replaces-instances-angularcopy
I've replaced every relevant instance of `angular.copy` with `Utilties.copy`

Replace angular.copy with Utilities.copy

---

src/Umbraco.Core/Persistence/Repositories/ContentRepository.cs

for https://github.com/umbraco/Umbraco-CMS/issues/7574

loads preview via sql paging instead of one single query

---

src/Umbraco.Core/Models/Identity/BackOfficeIdentityUser.cs
src/Umbraco.Core/Security/BackOfficeUserManager.cs

If there's an existing issue for this PR then this fixes #7127
This issue may be difficult to reproduce, as it seems to depend on the speed of the Web-server.
@kjac made an exelent screen shot of the proglem in the related issue #3979:

fix #7127 Unlock user account doesn't work on 7.14.0 and 15

---

src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
src/Umbraco.Web.UI.Client/src/common/directives/components/umbkeyboardshortcutsoverview.directive.js
src/Umbraco.Web.UI.Client/src/common/services/tour.service.js
src/Umbraco.Web.UI.Client/src/navigation.controller.js
src/Umbraco.Web.UI.Client/src/utilities.js
src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.controller.js

fixes https://github.com/umbraco/Umbraco-CMS/issues/8087

8087 forEach utility method

---

build/V8-Docs-Pipeline.yml

This has been running here currently - https://dev.azure.com/umbraco/Umbraco%20Cms/_build?definitionId=271&_a=summary

Azure DevOps YML pipeline for creating C# & JS Docs

---

src/Umbraco.Web.UI.Docs/gulpfile.js
src/Umbraco.Web.UI.Docs/package.json

I've had trouble running jsDocs and fixed it by adding this pre-install script.
I was as well missing the ability to run a server and watch for file changes, so this goes as well.
:-)

Improve jsDocs

---

src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html

Replacing anchor element with `<button>` element in macro partial view picker in macro settings.

Use button element for add-button in macro partial view

---

src/Umbraco.Tests.AcceptanceTest/cypress/integration/Members/memberGroups.js
src/Umbraco.Tests.AcceptanceTest/cypress/integration/Members/members.js
src/Umbraco.Tests.AcceptanceTest/cypress/integration/Users/userGroups.js
src/Umbraco.Tests.AcceptanceTest/package.json

This PR simply adds two new acceptance tests and update Cypress to v4.9.0 
- Create simple member
- Create simple member group

Added Acceptance Tests of Create Member and MemberGroup + update cypress to latest

---

src/Umbraco.Web.UI/Views/Partials/BlockList/Default.cshtml

Removes the try/catch block that got missed before the MEGA PR was merged into v8/8.7

Improve block list default razor view

---

src/Umbraco.Web/PublishedCache/NuCache/DataSource/SerializerBase.cs

support uInt32

---

src/Umbraco.Web.UI/Umbraco/config/lang/cs.xml

Update czech translation for admin section

Admin czech translation

---

src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
src/Umbraco.Tests/Services/UserServiceTests.cs

Added working integration test for recent PR for issue 8192

8192 with integration test

---

src/Umbraco.Web.UI.Client/package.json

This PR update noUiSlider dependency to v14.6.0 which includes a few bug fixes and enhancements.
https://github.com/leongersen/noUiSlider/releases

Update nouislider dependency to latest version

---

build/NuSpecs/UmbracoCms.SqlCe.nuspec
build/build.ps1
src/Umbraco.Configuration/Umbraco.Configuration.csproj
src/Umbraco.Core/Umbraco.Core.csproj
src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
src/Umbraco.Persistance.SqlCe/Umbraco.Persistance.SqlCe.csproj
src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
src/Umbraco.Web.Website/Umbraco.Web.Website.csproj

- In Powershell execute `$uenv=build/build.ps1 -get ` at the root folder to get the environment variable and download all the necessary tools
- OBS: this needs to be done just the first time, after that, you can just use `$uenv=build/build.ps1 -get -loc` so you stop downloading over and over again and assume everything is ready (_build.temp_ folder will be deleted every time you run this command)
- Then `$uenv.CompileUmbraco()` will create a **bin** and **WebApp** folder into _build.temp_ with their contents
- Run `$uenv.CompileTests()` to get the _Umbraco.Persistance.SqlCe.*_ files into **WebApp\bin** folder 
- Next command is `$uenv.PreparePackages()` 
- Finally, `$uenv.PackageNuGet()` will generate the 4 NuGet packages (one of them being **UmbracoCms.SqlCe**) in **build.out** folder …

NuGet package specifications for SQL CE

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/tags/tags.html

Same as https://github.com/umbraco/Umbraco-CMS/pull/8413 but for u7

#8412 Set ng-maxlength and maxlength attributes on the tag input

---

src/Umbraco.Core/Persistence/Repositories/UserRepository.cs

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7648

Avoid potential deadlock when Clearing login session

---

src/Umbraco.Core/Services/ContentService.cs

If there's an existing issue for this PR then this fixes #8393
@nul800sebastiaan  here you have PR with proposed fixed

Fix issue with Removing after unpublish parent

---

src/Umbraco.Web/Editors/RelationTypeController.cs

This PR enable the option to access relations types by guid and udi and not only by id in url.

Access relation type by id, guid and udi

---

src/Umbraco.Web/Editors/TemplateController.cs

This PR enable the option to access templates by guid and udi and not only by id in url.

Access template by id, guid and udi

---

src/Umbraco.Web/Editors/DictionaryController.cs

This PR enable the option to access dictionary items by guid and udi and not only by id in url.

Access dictionary item by id, guid and udi

---

src/Umbraco.Web.UI.Client/src/views/prevalueeditors/imagepicker.html
src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediapicker.html

Replace anchor elements with `<button>` element in imagepicker and mediapicker prevalue editors.

Replace anchor elements with button element in image/media picker

---

src/Umbraco.Core/Services/IMemberGroupService.cs
src/Umbraco.Core/Services/Implement/MemberGroupService.cs
src/Umbraco.Web/Editors/MemberGroupController.cs

This PR enable the option to access member groups by guid and udi and not only by id in url.

Access member group by id, guid and udi

---

src/Umbraco.Web.UI.Client/src/views/templates/edit.html

This PR update the master template with some minor adjustments
- Update styling for master template button
- Replace remove button with `<button>` element
- Ensure template editor can be closed vis `esc` shortcut in infinite mode
- Localize tooltip for remove button

Update master template button

---

src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/documentTypes.ts
src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/mediaTypes.ts
src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/memberTypes.ts

I Changed the selectors in the cypress tests to match the selectors on the site.

Fix selectors causing acceptance test to give false errors.

---

src/Umbraco.Web.BackOffice/Controllers/BackOfficeNotificationsController.cs
src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/ContentTypeControllerBase.cs
src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
src/Umbraco.Web.BackOffice/Controllers/HelpController.cs
src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
src/Umbraco.Web.BackOffice/Controllers/MemberGroupController.cs
src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/RelationTypeController.cs
src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
src/Umbraco.Web.BackOffice/Controllers/TemplateQueryController.cs
src/Umbraco.Web.BackOffice/Controllers/UserGroupsController.cs
src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
src/Umbraco.Web.BackOffice/HealthCheck/HealthCheckController.cs
src/Umbraco.Web.BackOffice/Profiling/WebProfilingController.cs
src/Umbraco.Web.UI.NetCore/appsettings.json
src/Umbraco.Web/Editors/AuthenticationController.cs

ref [AB#6332](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6332)
PluginController attributes means controllers are routed with MapAreaControllerRoute instead of MapControllerRoute which the latter means can be routed with the default route which we don't want.

Ensure all back office controllers are plugin controllers and use constant

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html

Display the validation state error or success in the submit button.

Display validation state in submit button

---

src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml

If form is dirty, aka. has been changed, we now ask the user if they are sure about discarding those changes in a dialog.

Ask user if they are sure about discarding changes

---

src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js

Fixing deleteAllBlocks
don't know whats up with whitespace now, don't have time for that ****

deleteAllBlocks fix
