- src/Umbraco.Core/Services/ContentService.cs
- src/Umbraco.Tests/Services/ContentServiceTests.cs
- src/Umbraco.Web/umbraco.presentation/content.cs
In previous PR #8455 , we fixed issue which was occurring but in time of QA for client we find out that change is actually causing more issues in different places, it is why I continue to research on issue. and find out it is enough to force Xml writer to be writer and all issues are solved.
@nul800sebastiaan  I am doing PR to check again unit tests results as I already notice they could be different on local and CI env (not sure why)
> v7: Revert previous changes, force writer in update of cache

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
While implementing a new backoffice UI I found the docs for the `umb-button` to be inaccurate.
In order for the `href` attribute to work the `type` attribute must be set to "link", else you end up with a button that doesn't do anything on click...
This was missing from the docs, it now isn't! 🎉
> Improving umb-button link docs

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle.less
- src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html
At the moment when `umb-toggle` is checked and disabled, it is not clear the toggle is checked. This was changed in PR https://github.com/umbraco/Umbraco-CMS/pull/7626
For example in languages where default language here is checked and disabled.
I have adjusted the toggle background color, so it looks more look the active checked state and a bit dimmed, which is a common pattern used accross different web interfaces, e.g https://css-tricks.com/custom-styling-form-inputs-with-modern-css-features/
Finally it removes unneccessary use of `ng-if`.
> Adjust toggle styling when checked and disabled

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
Recently features has been added to `umb-checkbox`, but not to `umb-radiobutton`.
I think these two components should be as consistent as possible. If new features are added to one of them, it should probably also been included on the other one.
> Streamline umb-checkbox and umb-radiobutton components

- src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Fixes #7461
This PR contains two changes to grid RTE editor code;
a) GridRteDirective now finds the `currentForm` using the parent scope from the GridController above the GridRte directive. The GridRte directive creates its own isolated scope and therefore we need to search for the form in `$scope.parent` and not the isolated `$scope`. This does NOT fix the issue mentioned but fixes the dirty event handler in the RTE so that `form.$setDirty()` is called correctly.
b) `syncContent()` is now called on TinyMCE Dirty events so that model.value is set to the RTE's contents whenever a macro is edited or inserted. This fixes the issue mentioned above.
GIF before where the text isn't saved after saving and publishing content:
GIF after the fix:
> Fix for issue #7461 ("Inserting a macro in the rich test editor (RTE) in the Grid makes it disappear on Save & Publish")

- src/Umbraco.Web.UI.Client/src/views/dictionary/create.html
- src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.create.controller.js
- src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
**Dictionary List Page**
On the dictionary list page it wasn't possible for a screen reader to determine correctly the number of rows in the dictionary list.  By changing from a click event on the table row to hrefs and adding a table caption this has been resolved
Previously colours were used to denote the state of the translation
Screen reader only text has been added to the columns to indicate the state of the translation
**Dictionary Create**
A label for has been added to the name label.  And the screen reader user can now tab onto the `<h5>` text box. Giving more indication of where they are in the dictionary flow.
An id has been added to the name textbox allowing the label for to correctly identify the textbox.
Name box now has maxlength field matching match length in db. …
> v8: Improvements to accessibility of translations section

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
To save having to manually track the current variant (`$watch` === 👿), this PR uses the events service to broadcast the update of the selected content variant. How that event is used is up the subscribing code, but will be useful in variant-aware content apps, and can be used when working on #8345 (by triggering Nested Content's sync method when the variant changes). Event is raised when the culture changes and when returning from split view. It does not fire on initial load, as the active variant is already available from editorState.
To test, unzip [CultureClub.zip](https://github.com/umbraco/Umbraco-CMS/files/4849928/CultureClub.zip) into App_plugins. It adds a quick content app, displaying the current culture. Switch cultures, app updates 🍾 
For those playing along at home and not …
> Use eventsService to tell everyone the current culture has changed

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediafolderpicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
I noticed when picking a folder from media picker and media folder picker in richtext editor datatype configuration, it was showing the default `icon-document` icon instead of `icon-folder`.
This PR fixes this. Furthermore I have updated the `<button>` elements in media folder picker to use `type="button"` like added in this PR https://github.com/umbraco/Umbraco-CMS/pull/7651 (and recommended since browsers may have different default behaviour). Finally it also re-use the `umb-file-icon` component here.
> Media picker folder icon

- src/Umbraco.Core/IO/SystemDirectories.cs
- src/Umbraco.Core/Logging/Serilog/LoggerConfigExtensions.cs
- src/Umbraco.Core/Logging/Viewer/JsonLogViewer.cs
#8280
Adjusted code around logging to use IOHelper over hardcoded paths with AppDomain.CurrentDomain.BaseDirectory ie. to support virtual directories for log files.
I've adjusted the environment variable called "BASEDIR" to also use the IOHelper, I had to trim the string in the end since the IOHelper return a trailing slash but the configuration in serilog.config does not expect this. So the Trim is to keep backwards compatibility for sites that is upgrading.
Also added a property for the LogFiles in the SystemDirectories-class to avoid having it hardcoded in lots of places. 
Since the JsonLogViewer reads this setting we still have an "issue" if someone wants to store log files in a custom folder (ie out of the root), we could address this by making SystemDirectories.LogFile simular to …
> Using IOHelper for Log files

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html
If there's an existing issue for this PR then this fixes #8241 
I've updated the date-format string check to catch all (most) time variants, replacing the old string comparisons with a regex match to catch lots more for less effort. Also updated the view to show clock icon when the picker is time-only, rather than the calendar. This won't catch absolutely every time format, but it's a lot broader than the previous solution which forced 24-hour formatting with a leading 0
Verify by updating the date picker config to `h:mm:ss a` or any combination of 1-2 `H/h`, 1-2 `m`, 1/2 `s`, all colon-separated, with or without a trailing `a`, with or without a leading space (aka any valid [momentjs time format](https://momentjs.com/docs/#/displaying/format/)). Picker will not display the calendar, and …
> update date-format matching for formats with am/pm

- src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js
- src/Umbraco.Web.UI.Client/src/views/components/notifications/umb-notifications.html
Following the discussion in https://github.com/umbraco/Umbraco-CMS/pull/8207, I've now added a `target` property to control the corresponding target attribute of the `<a/>` element of the notification.
With this PR, the target will no longer be `_blank` by default, but instead leaves it up to the developer to set so if needed.
The PR also adds `rel="noreferrer"` to the `<a/>` element for security and privacy reasons. While this is primarily for when the link opens in a new window/tab, I don't see a problem always having it on the link.
> umb-notifications.html - added option for setting the target attribute

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
The `<a>` has been converted to a `<button>` and non-visual texts have been added in order to make provide a more specific context to screen reader users instead of just "Add" it will now read the computed label name for the property + "Add url(s)", which is much more specific.
> Multi Url picker datatype: a11y fixes

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
✔️ I have added steps to test this contribution in the description below
Currently the settings cog icon in the grid is wrapped in a div and has no screen reader friendly text, which this PR aims to fix.
- I have wrapped the icon in a `<button>` and hidden the icon using `aria-hidden="true"`
- I have also added a generic text for screen readers announcing "Open column settings" - At a later stage we need to make this a tad more specific towards the context of the cog's placement. But baby steps! 👶 😃 
- I have also added some fallback texts and wrapped them in `<p></p>` in case dictionary items have not been added for some reason while I was at it 👍
> Improve the accessibility of the cog icon

- src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
✔️ I have added steps to test this contribution in the description below
I noticed some fallback texts were missing if the dictionary labels for certain language don't exists so I added some fallback texts.
Apart from that I made a tiny accessibility improvement adding the `aria-disabled` attribute and whenever the max limit of allowed blocks in nested content screen readers will announce either "disabled" or "dimmed" letting screen reader users know the button won't be doing anything.
In order to disable it totally from being clicked we would need to set `disabled="true"` but screen readers currently have varying support for this, so it works inconsistently and could leave some users in the dark. So click events will still be …
> Random fixes for nested content "add" button

- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
This PR removes the auto-focus on the package search box. 
This issue was identified in the  Accessibility audit for version 8.4
**Rational**
> The search field receives focus on page load.
> 
> This differs from other pages within the menu as their focus remains within the menu when the page loads.
> 
> It is good that the focus goes into the page when the menu item is activated, but because of the focus it misses the secondary nav (Packages, Installed etc.)
This PR makes the experience consistent with the rest of the pages in the backoffice.
> fix: remove auto focus from package search box

- src/Umbraco.Core/Services/Implement/ContentService.cs
Similar to #8140 I am trying to log the saving of a content template into the `umbracoLog` table. Currently it does not save into the `umbracoLog` table.
with this PR applied, when a content template is saved the following SQL query should bring back results on content template as well.
SELECT TOP (10) [id]
,[userId]
,[NodeId]
,[entityType]
,[Datestamp]
,[logHeader]
,[logComment]
,[parameters]
FROM [dbo].[umbracoLog]
order by Datestamp desc
> Logging content template save in back office to log table

- src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
Tested in Chrome Version 79.0.3945.130
This PR update the button element in package overview to not use flexbox, but instead use flexbox for a inner wrapping div. The issues where the "umb-package-icon" overflow the container was affected after changes in this PR https://github.com/umbraco/Umbraco-CMS/pull/6955 where the anchor elements was changed to `button` elements.
It also ensure the border color change on hover works as previous.
In some browers it is not supported to use `button` element as flexbox container or doesn't allow to change its `display` value.
https://stackoverflow.com/a/35466231/1693918
> `<button>` is not implementable (by browsers) in pure CSS, so they are a bit of a black box, from the perspective of CSS. This means that they don't necessarily react in the same way …
> Update button in package overview not to use flexbox

- src/Umbraco.Web/Editors/ContentTypeController.cs
- src/Umbraco.Web/Editors/MediaTypeController.cs
- src/Umbraco.Web/Editors/MemberTypeController.cs
This PR enable the option to access document, media and member types by guid and udi and not only by id.
At the moment this it already possible for content, media and member nodes (and in Umbraco Forms as I remember) ... and also for datatypes and macros https://github.com/umbraco/Umbraco-CMS/pull/6847
> Access document, media and member types by guid and udi

- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
I just noticed when installing a package, the accept terms checkbox was a traditional checkbox. I have replaced this with `umb-checkbox` component to make it consistent with the rest of the backoffice UI.
**Before**
**After**
> Replace traditional checkbox with umb-checkbox component

- src/Umbraco.Web.UI.Client/src/views/content/protect.html
Replacing anchor element with `<button>` element in public access overlay/dialog.
> Replace anchor elements with button elements in public access overlay

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treepicker.html
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.html
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesourcetypepicker.html
Replace anchor elements with `<button>` elements in treepicker and treesource picker.
> Replace anchor elements with button elements in treepicker

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
It would have been great if the `umb-checkbox` and `umb-radiobutton` just used `icon` instead of `icon-class` attribute to be consistent with other components in core using icons as well. This was introduced in https://github.com/umbraco/Umbraco-CMS/pull/6979
At the moment this is only used for icons in richtext editor configuration in core.
This PR add an `icon` parameter as other components and and mark `iconClass` as deprecated. Maybe this can be removed in a minor version. Note sure if the `@deprecated` in `ngdoc` is entirely correct.
**umbButton**
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js#L65
**umbFileIcon**
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Cl …
> Make icon property for checkbox and radiobutton consistent with other components

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button.less
- src/Umbraco.Web.UI.Client/src/less/components/editor.less
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-menu.html
This PR replaces #7312 
As discussed on #7312, the  actions menu button in the editor header shouldn't be enabled until there are any actions to show. 
This PR implements that. When applied, the actions menu button is disabled and subtly dimmed down until the actions for the current content loads:
If no actions are loaded, the actions menu button simply remains disabled and dimmed down.
> V8: Disable the actions menu button until there are actions available

- src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs
This fixes issue #5737 and Replaces pull request #5739 
When you add a crop alias to Image Cropper after media already exists in your Media library it doesn't pick up any of the crops. This PR updates ImageCropperTemplateExtensions to check for this condition and configure crops from the DataType.Configuration. 
As per issue #5737 
- V8 with SK installed
- Update Image Media Type -> Update umbracoFile Image Cropper DataType settings to include a crop type (ie test)
- Update Products.cshtml / template to use that crop ie ```@product.Pho0tos.GetCropUrl("test")``` 
- View page on frontend & confirm images render (they don't before PR)
- Goto Media Section & Choose a Product Image
- Set manual crops for an image
- View page on frontend & confirm all images render (only the updated image does …
> Get missing crops from configuration

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
Custom angular element directives/components can't be self-closing elements like navtive elements, e.g. `<input type="checkbox value="" />`:
https://stackoverflow.com/a/25012451/1693918
This was previous fixed in https://github.com/umbraco/Umbraco-CMS/pull/8422 but overwritten in https://github.com/umbraco/Umbraco-CMS/commit/1cd79d81af821470de2123e1c6febe2980d98111#diff-c84512d9cc059db603911cd477e1d82e
**Before**
**After**
> Remove button for custom listview layouts isn't rendered

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagementresults.html
When opening member search result overlay with title "Field values" from MembersIndex it isn't possible to close this overlay via `esc` shortcut.
> Add missing esc shortcut to close examine result field values overlay

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html
- src/Umbraco.Web/PropertyEditors/TrueFalseConfiguration.cs
- src/Umbraco.Web/PropertyEditors/TrueFalsePropertyEditor.cs
The True/False property editor aka Checkbox has at the moment a prevalue in the configuration to set a label text, but "Write a label text" is not very informative. Furthermore it both used this for "label-on" and "label-off".
Instead it now has two prevalues to set text for "Label On" and "Label Off". If the developer want the same text whether the toggle is checked or not, is it quite easy to set same label text in both prevalues.
Maybe some even prefer it only show a specific label when the toggle in checked of not checked?
At the moment it would only show labels if the toggle has a "labelOn" value and not if "labelOff" actual has a value:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html#L6
So the …
> Update boolean/toggle/checkbox label prevalues

- src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.controller.js
- src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
This PR change the button style to `danger` in redirect delete confirm to be consistent with other delete confirm overlays, e.g. in language delete confirm.
**Before**
**After**
> Change button style for redirect delete confirm

- src/Umbraco.Web.UI.Client/src/less/components/umb-stylesheet.less
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html
- src/Umbraco.Web.UI.Client/src/views/stylesheets/infiniteeditors/richtextrule/richtextrule.html
- src/Umbraco.Web.UI.Client/src/views/stylesheets/views/rules/rules.controller.js
- src/Umbraco.Web.UI.Client/src/views/stylesheets/views/rules/rules.html
A few adjustments to richtext styles editor using `<button>` elements instead of `<a>` elements.
Furthermore is replace a few fonts using `@monoFontFamily` variable, where it makes the textarea look more like an css editor.
I considered it ace editor code be used here as well, but I think it need to include the selector as readonly line. https://stackoverflow.com/a/39640987/1693918
Might be possible, but a bit more complex and would require another PR.
> Richtext rules adjustments

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-box.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
This previous PR https://github.com/umbraco/Umbraco-CMS/pull/8132 introduced a `umb-button-ellipsis` components and replaced with this various placed with "ellipsis" button. One of these placed is the action button in tree.
However `umb-tree` has an options to `hideoptions` which set a class `hide-options` and the following styling which hide the button with class `umb-options`: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less#L217-L219
The new button in tree does however no longer has this class, so it is always shown on hover (e.g. in macro partial view picker) even `hideoptions` is set. Note this is used quite many places: https://github.com/umbraco/Umbraco-CMS/search?q=hideoptions&unscoped_q=hideoptions where this …
> Hide action button in tree

- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
If there's an existing issue for this PR then this fixes #8465
See #8465 for an issue description and a screencast of the issue as it plays out.
The issue happens because the content type editor is rebound with data from the server after an unsuccessful save event. The way the rebind callback is implemented, it accidentally assigns duplicate IDs to the groups with matching names, and thus one of them ends up overwritten on the next successful save.
I don't believe it makes sense to rebind the content type editor if the save fails. Nothing has been persisted on the server anyway. So this PR simply removes the rebinding upon failed saves.
With this PR applied, the editor behaves like you'd expect - preserving the previously duplicated groups after renaming them appropriately:
> Do not rebind content types on save errors

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
This fixes #8345
Thanks to the steps by @snedled and @nathanwoulfe (including the work done for emitting an event when changing variant, and the example code in #8355, this should now work as the nestedcontent controller listens for the now emitted editors.content.cultureChanged event, and when destroyed updates the editor model prior to the language variant changing.
I've been able to test this by:
- Create a content type with a nested content field, and set it to use 2 language variants.
- Add some example content to the nested content field - leave the nested content item expanded and don't save the node.
- Swap the language variant on the node itself, this will reload the editor.
- Swap back to the original language variant - the nested content editor will be minimized, but expanding …
> #8345  - Nested content not remembering value on variant switch

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
The previous merged PR https://github.com/umbraco/Umbraco-CMS/pull/8023 moved the `umb-overlay` for crop details in media picker to a separate overlay, where the function `shouldShowUrl` is used.
However when merging PR https://github.com/umbraco/Umbraco-CMS/pull/7912 the function was re-added to mediapicker infinite editor. The function is only used in this overlay.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/overlays/mediacropdetails.html#L13
> Cleanup unused function shouldShowUrl

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
If there's an existing issue for this PR then this fixes #8324
_See also #8324 for a brilliant issue description_
If a Grid configuration has only one layout and one row configuration, the property editor will automatically initialize itself with one layout + row. This makes sense. However, in combination with the excellent accessibility effort in #6804, this causes the grid to steal focus on init - most noticeably when creating new content:
This PR ensures that the auto-focus is not performed on init, but is retained on subsequent row additions to preserve the accessibility:
> Don't allow the grid to steal focus on init

- src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
While fixing the "more" button styling in the content app navigation, I noticed how the content anchor list kept expanding on small screens, making the content apps behind it unreachable:
Turns out the CSS selector that expands the anchor list is a tad too greedy. This PR narrows it down a tad, and once applied the content app navigation works somewhat nicer on small screens:
...and of course it still works on larger screens:
> Don't auto-expand all content anchors on small screens

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttonellipsis.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
- src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-ellipsis.html
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation.html
@nul800sebastiaan This is my approach to fix the issue filed by @kjac in #8486 and the alternate approach in #8492 
I have passed the css classes used on the "Content app" buttons, which fixes the height issue and also fixed the general styling of the "more" button actually using the "css-class" attribute provided by the directive.
Furthermore in order to vertically align the ellispsis and the text I've added a "content" wrapper around the 2 existing spans in order to be able to do this in the directive itself. This does not affect the usage where there is no text to display.
I can't see any downsides to this approach since the only change added to the component is a span that wraps the icon and text and otherwise it's just accepting the passed css class, which was the intention from the …
> umb-ellispsis-component: Fix visuals when used in the content app section

- src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
It seems #5606 made the "Selected"-checkbox visible at all times for all items in mini list views, despite these items not being selected:
> "Selected"-checkbox in mini listview is always visible

- src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
If there's an existing issue for this PR then this fixes #8328 
As described in #8328 the RTE loads un-minified resources in release mode. As it turns out it's not only plugins but also themes that are loaded un-minified:
This issue _does_ indeed affect both normal and grid RTEs.
This PR forces TinyMCE to always load minified resources, no matter if Umbraco runs in debug or release mode. When applied the loaded resources are significantly smaller:
While I was at it I also redid the way the grid RTE loads TinyMCE resources to match that of the normal RTE (as implemented in #6147).
After building the frontend (`gulp dev`), be sure to set `debug="false"` in web.config:
Then increment `version` in ClientDependency.config:
Now reload any content item with an RTE with the Network tab open in …
> Make sure the RTE always loads minified resources

- src/Umbraco.Web.UI.Client/src/less/panel.less
The editor panel header has lost its (top) spacing when a description is present underneath the name input field:
This applies to every editor under Templating in the Settings section (Templates, Partial Views, Partial View Macro Files, Stylesheets and Scripts).
This PR brings back the spacing:
> Fix panel header spacing when a description is present

- src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less
The property editors for file upload and image cropper do not show the keyboard input focus when you're tabbing through the editor interface:
...but with this PR - they do 😄
> Show keyboard input focus on file property editors

- src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
Somewhere along the lines, the "delete property" button on the content type builder has gone and got itself a bit crooked:
This PR fixes the button so it goes back to being centered under the "property settings" button:
> Fix the alignment of the "delete property" button

- src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
If you attempt to insert a link in an empty RTE, a JS error is thrown:
Turns out `getAnchors.getAnchors(...)` has varying return types; it returns an empty array if the RTE is empty and a promise if the RTE is _not_ empty. 
This PR ensures that `getAnchors.getAnchors(...)` always returns a promise, and thus the linkpicker no longer throws an error:
_Note: Inserting a link in the RTE without a selection results in a sort of weird behavior where the link text is empty. This should probably be addressed in another PR as it affects non-empty RTEs as well._
> V8: Fix JS error when trying to insert a link in an empty RTE

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreesearchresults.directive.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-results.html
If you search for a page in the linkpicker (e.g. from an RTE) and the page can't be found, the "no search results" text is shown rather clumsily on top of the search input field:
It happens because the search results directive is hardcoded to display the empty state at position `center`. This PR lets us specify a position for the empty state (it still defaults to `center`), and thus the empty state for the linkpicker can be positioned better:
> V8: Fix for "no search results" text shown on top of the search input field

- src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.list.controller.js
- src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
- src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
If there's an existing issue for this PR then this fixes #7718 (in part)
Continuing the effort to minimize the angular dependency, I have rewritten all usages of angular.forEach with the native equivalent in the settings and translation sections.
Basically there should be no noticeable difference when applying this PR; the settings and translation sections should "just work". Here are a few things to test and try out:
> Remove usages of angular.forEach in settings and translation

- src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
If there's an existing issue for this PR then this fixes #7718 (in part)
Continuing the effort to minimize the angular dependency, I have rewritten all usages of angular.forEach with the native equivalent in the users and groups section.
Basically there should be no noticeable difference when applying this PR; users and groups editing and management should "just work". Here are a few things to test and try out:
> Remove usages of angular.forEach in users and groups editing

- src/Umbraco.Core/PropertyEditors/PropertyValueConverterBase.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8259.
This PR cleans up the `PropertyValueConverterBase` by:
- Fixing `IsValue`, so it doesn't throw `NotSupportedException` for valid enum values, but returns `null` when it can't determine whether it's an actual value;
- Obsoleting `HasValue`, as it's not included in the `IPropertyValueConverter` contract and might confuse developers overriding this unused method;
- Simplifying the value check using type pattern matching (`value is string stringValue`);
- Adding XML documentation
> PropertyValueConverterBase cleanup: fix IsValue, obsolete HasValue, add documentation

- src/Umbraco.Core/Persistence/Querying/ExpressionVisitorBase.cs
- src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
If you try to use a `*` in any search field (global search, copy/move dialog search, treepicker search, ...), things tend to go horribly wrong:
This PR explicitly removes the `*` character in the search queries to avoid that:
This doesn't change the fact that the tree searcher still performs wildcard queries:
> V8: Wildcards in tree searches causes YSODs

- src/Umbraco.Web/Editors/IconController.cs
At the moment the changes regarding `umb-icon` directive extended IconController to look for svg icons and log an error if it isn't found.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/IconController.cs#L95
However this will fill log with errors, when using custom font icons where svg icons are not available, e.g. when Umbraco Forms is installed.
> Don't log message if svg icon isn't found

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbicon.directive.js
- src/Umbraco.Web.UI.Client/src/less/belle.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-iconpicker.less
- src/Umbraco.Web.UI.Client/src/less/helveticons.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-icon.html
After merging PR https://github.com/umbraco/Umbraco-CMS/pull/5606 I have noticed some issues with custom font icons. At the moment it expect the font-family is `icomoon`, but it could be something else like `icomoonforms` shipped with Umbraco Forms.
Furthermore these fonts didn't look nice in the iconpicker.
**Before**
**After**
> Adjustments to umb-icon with custom font icons

- src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button-group.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
This PR use `<umb-icon>` in the listview layout selector and removes a few unnecessary `prevent-default` on the button elements.
I also noticed a few missing icons, while looking at the listview.
**Before**
**After**
**Before**
**After**
> Use umb-icon in listview layout selector

- src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html
After merging https://github.com/umbraco/Umbraco-CMS/pull/5606 it seems the success or error icon after save isn't shown.
I have fixed this and also replaced the additional icons with `<umb-icon>` components. These are used in e.g. bulk actions in listviews.
Demo of saving a user.
**Before**
**After**
> Button doesn't show success or error icon after save

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbicon.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/editor.less
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-icon.html
This PR replace the close button when splitview is opened with `<button>` element and futhermore use `umb-icon`.
It also removes a unnecessary use of `ng-if`.
It does however seems to be a bit strange I need to set `icon-delete` twice. Maybe when setting `icon` attribute it should set this as class in the `umb-icon` component.
```
<umb-icon icon="icon-delete" class="icon-delete"></umb-icon>
```
> Replace splitview close button with button element

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/querybuilder/querybuilder.html
- src/Umbraco.Web/Editors/TemplateQueryController.cs
I have replaced a few anchor elements with `<button>` elements in template query builder.
Furthermore the samle result didn't use the icon from the json, so I changed that and use `icon-document` since `icon-file` doesn't exist.
It would be nice if it could use the respective icons for the nodes, but `IPublishedContentType` doesn't have a `Icon` property like `IContentType`. So I guess that would require looking up the specific content types from the results.
> Query builder buttons

- src/Umbraco.Web.UI.Client/src/less/components/umb-badge.less
- src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js
- src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
This PR updates a few things in log viewer:
- Replace anchors with `<button>` elements
- Use `<umb-icon>` and fixes issue with toggle arrow up/down icon when open/close "saved searches"
- Fixes issue with self-closing angular `<umb-checkbox>` component in log levels dropdown (in this case the self-closing custom angular element didn't cause issues except additional whitespace)
- Updates log levels colors to better match the log level type
- Empty state message isn't showm while loading (e.g. when selecting the different log levels from the dropdown)
I think the colors of the log levels was a bit off. Often "orange" is associated with "warning" and "red" is associated with "error".
I have then chosen a dark gray (close to black for "Fatal" log level). Furthermore I have updated "Debug" to …
> Logviewer adjustments

- src/Umbraco.Web.UI.Client/src/less/components/editor.less
- src/Umbraco.Web.UI.Client/src/less/components/editor/umb-variant-switcher.less
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
I think the variant switcher looked a bit off and the "Open in split view" button wasn't center aligned vertically.
**Before**
**After**
Not sure about the "+" icon in front since it doesn't align the languages, but we can look at that in another PR.
When the language (not created) is selected I am not sure if this styling should also be applied. Otherwise it seems to be a few pixels off to align with other languages.
> Adjust styling of variant switcher for not created variant

- src/Umbraco.Core/Persistence/Repositories/IMemberGroupRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberGroupRepository.cs
- src/Umbraco.Core/Services/Implement/MemberGroupService.cs
This PR adjust previous merged PR https://github.com/umbraco/Umbraco-CMS/pull/7528 to fetch member group by Guid (uniqueId in umbracoNode) table.
It seems many of the repository classes use a `GetBaseWhereClause()` which query by id. Some of these use the constant for table name, while others don't.
https://github.com/umbraco/Umbraco-CMS/search?p=3&q=GetBaseWhereClause&unscoped_q=GetBaseWhereClause
I have updated this in https://github.com/umbraco/Umbraco-CMS/commit/d5d5d077c5d5bfc8634fc57745429cd81300f6e1 (but we could probably do with the other repositories as well).
> Fetch membergroup by guid

- src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbsearch.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreeitem.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
- src/Umbraco.Web.UI.Client/src/common/mocks/resources/media.mocks.js
- src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/membergroup.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/membertype.resource.js
- src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
- src/Umbraco.Web.UI.Client/src/common/services/search.service.js
- src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
- src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/usershelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/util.service.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypeconfigurationpicker/datatypeconfigurationpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
Changes replace `_.each` with native `.forEach` in directives (components) and resources - I've sanity checked these locally, all seems to be fine. This is related to #7731 but does not yet complete the _.each removal (figured it's better to have multiple smaller PRs rather than one big one with 50 files modified).
Most are like-for-like replacements, with the exception of some like the changes in umbsearch.directive.js where the value is a dictionary not an array, so uses `Object.keys().forEach()` because the value is not directly iterable.
Made related syntax changes to replace some indexOf calls with includes (easier to read `x.includes(y)` compared to `x.indexOf(y) !== -1`), and converted a few functions to single-line fat-arrows where it made sense to be terser.
> 7731 bye bye underscore => _.each

- src/Umbraco.Web/Scheduling/SchedulerComponent.cs
- src/Umbraco.Web/Scheduling/TempFileCleanup.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7675.
This adds the `TempFileCleanup` task to the right background runner, skips nonexistent directories and also allows read-only files to be deleted (by removing this flag before deletion).
Testing can be done by ensuring the `~\App_Data\TEMP\FileUploads` directory doesn't exist, optionally set the logging level to debug (so you can see the `The cleanup folder doesn't exist...` message), wait for the background task to run (default 3 minutes delay) and check whether the exception/error isn't logged anymore.
> Fix LogScrubber exception when cleaning up temp files

- src/Umbraco.Web/Editors/DictionaryController.cs
As the dictionary grows larger, the dictionary dashboard turns slower. When you have a somewhat sizable dictionary, the dashboard takes ages to load.
This PR improves the dashboard load speed significantly... in my test scenario about 75 times - load time is cut from ~30s to ~400ms on average:
Those ~30s can mainly be credited to recursive operations on the database whereas this PR fetches all dictionary items in one go. So there is a significant performance improvement towards the database as well.
First and foremost you must have a somewhat large dictionary to test this. You can use the following SQL to generate one (do backup your database first, though!).
[Add dictionary items.txt](https://github.com/umbraco/Umbraco-CMS/files/4693318/Add.dictionary.items.txt)
The SQL generates the …
> Improve dictionary dashboard performance significantly

- src/Umbraco.Web.UI.Client/src/installer/steps/database.html
While demonstrating the Umbraco installer, I noticed the labels shown in the database fields aren't particularly helpful.
When configuring an Azure database the placeholder hostname shown is a local hostname, when Azure SQL will always be `*.database.azure.net`.
Additionally the password label field might also encourage bad security practices, with the placeholder saying "umbraco-cms".
I also fixed up the whitespace formatting of this file... 😬 You might want to [view the changes with whitespace ignored](https://github.com/umbraco/Umbraco-CMS/pull/8172/files?w=1)
> Improving database field labels in installer

- src/Umbraco.Core/Services/Implement/RelationService.cs
- src/Umbraco.Tests/TestHelpers/TestObjects.cs
When a relation type is saved, it is not logged to the `umbracoLog` table. I have tried to enable logging when a relation type is saved.
> RelationService - Log to audit on RelationType Save

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbtextarea.directive.js
- src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
fix #7842 - Render a larger textarea for editing dictionary items
Textareas in the dictionary section only will now expand vertically depending on the amount of content in them. I have also made each textarea full width of the available space.
> fix #7842 - Render a larger textarea for editing dictionary items

- src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.controller.js
This is an addition to #8475, splitting into multiple PRs to avoid giant merges. These changes remove underscore from the content overlay controllers (the ones used for the publish/save/unpublish overlays). Also fixes the sort order of variants displayed in the overlays (were previously in reverse alphabetical order, now in alpha order).
Change replace all underscore methods with native JS, and makes some general improvements (avoids iterating collections multiple times where possible, syntax fixes etc). Functionally, nothing has changed.
Testing requirement is to verify everything still works. Can save, publish, save+publish, unpublish, schedule with variant and invariant content. Changes are pretty safe and predictable as most relate to iterating the variants collection, which is always …
> 7731 bye bye underscore => _.each pt2 => content overlays

- src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
This PR align a few icons on the document type page after merging PR https://github.com/umbraco/Umbraco-CMS/pull/5293
- Vary by culture tag icon
- Datatype editor icon
- Inherit tag icon
> Align icons on document type

- src/Umbraco.Web.UI.Client/lib/bootstrap/less/pager.less
- src/Umbraco.Web.UI.Client/lib/bootstrap/less/pagination.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-pagination.less
- src/Umbraco.Web.UI.Client/src/views/components/umb-pagination.html
- src/Umbraco.Web.UI.Client/src/views/partialviews/create.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
This PR fixes a few oversights after changing anchor elements to `<button>` elements.:
- Remove `href` attributes from `<button>` elements.
- Remove `prevent-default` directive on `<button>` elements.
- Adding missing type attributes (browsers may have different default behavior).
- Replace anchor elements in pagination with `<button>` elements + disable button for current page and prev/next when on first/last page. This also ensure when using keyboard it doesn't focus "inactive" buttons.
> Buttons cleanup

- src/Umbraco.Web.UI.Client/src/less/belle.less
- src/Umbraco.Web.UI.Client/src/less/buttons.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-confirm-action.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-tags-editor.less
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8526
This PR fixes some styling issues after merging https://github.com/umbraco/Umbraco-CMS/pull/5293 and moved trash icon inside `umb-confirm-action` in https://github.com/umbraco/Umbraco-CMS/pull/8198
It also fixes issues where no outline was shown on focus.
Since `umb-tags-editor` is a separate component I have moved the styling to `umb-tags-editor.less`, so it re-used developers will get the same styling. The property editor still has the `umb-tags` class which has styling with the limited width.
> Fix styling of confirm actions in tags editor

- src/Umbraco.Web.UI.Client/src/less/components/umb-multiple-textbox.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/multipletextbox/multipletextbox.html
The PR fixes some styling issues in textbox multiple aka repeatable textstrings, so the actions are aligned next to each other.
**Before**
**After**
> Fix styling of actions in textbox multiple

- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
- src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
This PR adjust styling of buttons in grid cells and optimize the buttons for accessibility.
**Before**
**After**
> Fix styling of buttons in grid cells

- src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/sectionpicker/sectionpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/usergrouppicker/usergrouppicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/content.notify.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/content.rights.controller.js
If there's an existing issue for this PR then this fixes #7718 (in part)
Continuing the effort to minimize the angular dependency, I have rewritten the remaining usages of angular.forEach with the native equivalent in the help drawer, the remaining content editing and infinite editors.
Basically there should be no noticeable difference when applying this PR; the UI should "just work" as it does now. Validate the following:
_Easiest to test by editing a group._
_Easiest to test by editing a user._
_Can be tested with a MNTP configured to allow only certain content types._
_Can be tested setting up member based public access for content._
> Remove usages of angular.forEach in help drawer, content and infinite editors

- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
A slight error snuck into the grid LESS in #8543. Unfortunately this error causes the entire client build to fail:
I believe this PR fixes it; the grid styling at least looks like what's shown in #8543
/cc @bjarnef
> Fix broken grid LESS causing the client build to fail

- src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
- When the Get started tour is executed, the tour is locked at step 8 of 12 because the next button is not clickable
- Moved the `<umb-tour>` tag out of the current scope. 
- Run the get started tour. Before the next butten of step `8/12` was not clickable.
- Now
> Bugfix: Tour's next button not clickable when infinite editing bar is open

- src/Umbraco.Core/Packaging/PackagesRepository.cs
- src/Umbraco.Infrastructure/Composing/CompositionExtensions/Services.cs
- src/Umbraco.Tests/Packaging/CreatedPackagesRepositoryTests.cs
- src/Umbraco.Tests/TestHelpers/TestObjects.cs
Just a quick fix for the packaging service to use the data files in the content root, not the webroot. More will be required for this service once we get into packages but i saw that files were created in the wrong place so i just went ahead and fixed this part for now.
> Fixes package service paths so that it's using content and web roots not just web

- src/Umbraco.Web.UI.Client/lib/bootstrap/less/alerts.less
- src/Umbraco.Web.UI.Client/src/less/alerts.less
- src/Umbraco.Web.UI.Client/src/less/components/editor/umb-variant-switcher.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
- src/Umbraco.Web.UI.Client/src/less/main.less
- src/Umbraco.Web.UI.Client/src/less/mixins.less
- src/Umbraco.Web.UI.Client/src/less/variables.less
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation-item.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
Making the property-error message into a speech bubble style, so it yells less in your face.
Shows a error-badge on content-apps if no badge already is present, and colors the badge in red to make it even more visible that there is issues.
> Some UI update to validation messages

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Sometimes load happens instant, so to avoid runtime issues this needs to be placed in the bottom of init.
> moving load to the bottom of init

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
The "blockelement__draggable-element" class was present on the scoped block list block components before validation was merged in, but it somehow got lost. Its appended cause the scoping makes it unable to search and find it inside the scoped component, therefore we need to make the full entry draggable.
> append lost drag class

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
correcting udi to contentUdi for createFromElementType to work again.. used for clipboard features.
> correct for the new spelling

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
we need to always set active, in order for it to become false on second visit.
> always set active in order to reset it

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/dropdownFlexible/dropdownFlexible.controller.js
I experience this issue when a dropdown is used in a content-app that is not active on submit in the block list editor.
This is because the value gets set to null, and if the control isn't initialized, aka. not shown. Then this value never gets reset to anything and therefor this event handler fails cause it cant check the length of null. So there I added this check.
> Check for null before checking the length or value of first entry.

- src/Umbraco.Core/Models/Blocks/BlockItemData.cs
- src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
- src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Fixes [AB#7590](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7590)
The problem is that the block editor or any other complex editor might not post a key/value for a given property if that property is empty. Before this PR it meant that this property was not actually validated. I think this solves the issue that might have been seen in [AB#7599](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7599). This fix also covers Nested Content server side validation for the same issue.
Previous to this PR if you setup a block editor that has a property of type textfield that is 'required'. Create a content item and create a single row with this value filled in and save it which should be successful. Now if you refresh that …
> Ensure that we validate all properties for a block based on it's element type properties, not just the property values that are POSTed

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
When preview the Block List editor in the DocumentTypeEditor we do not have umbVariantContent available which resulted in this error: "Could not find umbVariantContent in the $scope chain".
But we can use "vm.umbProperty" to check whether we are in this weird context of the DocumentTypeEditor, and then not start the scope searching.
> Do not require the umbVariantContent in the context of the DocumentTypeEditor

- src/Umbraco.Core/IUmbracoContextFactory.cs
- src/Umbraco.Core/Install/InstallSteps/StarterKitCleanupStep.cs
- src/Umbraco.Core/Models/PublishedContent/IndexedArrayItem.cs
- src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
- src/Umbraco.Core/Routing/RoutableAttemptEventArgs.cs
- src/Umbraco.Core/Routing/UmbracoRequestEventArgs.cs
- src/Umbraco.Core/Routing/UriUtility.cs
- src/Umbraco.Core/Templates/UmbracoComponentRenderer.cs
- src/Umbraco.Infrastructure/Media/EmbedProviders/Flickr.cs
- src/Umbraco.Infrastructure/Media/EmbedProviders/OEmbedResponse.cs
- src/Umbraco.Infrastructure/Runtime/SqlMainDomLock.cs
- src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
- src/Umbraco.Web.BackOffice/Trees/FileSystemTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/UrlHelperExtensions.cs
- src/Umbraco.Web.Website/ActionResults/RedirectToUmbracoPageResult.cs
- src/Umbraco.Web.Website/Controllers/SurfaceController.cs
- Replaced `System.Web.HttpUtility` with `System.Net.WebUtility`
- Replaced querystrings as `String`s and `NameValueCollection`s with the `QueryString` type
> Netcore: Get rid of System.Web in netcore and netstandard projects

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/test/unit/common/services/block-editor-service.spec.js
- src/Umbraco.Web/PropertyEditors/BlockListConfiguration.cs
Rename JSON property contentTypeKey to contentElementTypeKey.
the naming of contentTypeKey is inconsistent with others in src/Umbraco.Web/PropertyEditors/BlockListConfiguration.cs this PR changes that.
> rename contentTypeKey for consistency.

- src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
- src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8602
The `umb-toggle` is a custom angular directive, where custom angular directives/components can't be void elements (self-closing), so it needs to be non-void element - in this case has a end-closing `</umb-toggle>`.
There is a great explanation of it here: https://stackoverflow.com/a/25012451/1693918
**Before**
**After**
> Fix self closing umb-toggle

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
The publish descendants dialog was broken at some point going from 8.6->8.7.
I've fixed it up, using the label on the toggle directive instead of using a separate label.
Also updated the localized texts to better reflect what is happening here:
- The toggle allows you to include or exclude publishing of items that have a published state.
- The old help text could indicate that items in a published state but with a "draft" on top would not be published if deselected ... they would be - so this is now more clear.
The last fix done here is that the selected value would not be pushed back to the scope which means your selection would never make it back.
---
_This item has been added to our backlog [AB#7682](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7682 …
> Fixing publish descendants dialog

- src/Umbraco.Core/Security/AuthenticationExtensions.cs
- src/Umbraco.Web.Common/ApplicationModels/BackOfficeApplicationModelProvider.cs
- src/Umbraco.Web.Common/ApplicationModels/BackOfficeIdentityCultureConvention.cs
- src/Umbraco.Web.Common/ApplicationModels/UmbracoApiBehaviorApplicationModelProvider.cs
- src/Umbraco.Web.Common/Extensions/UmbracoBackOfficeIdentityCultureProvider.cs
- src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
- src/Umbraco.Web.Common/Extensions/UmbracoWebServiceCollectionExtensions.cs
- src/Umbraco.Web.Common/Filters/BackOfficeCultureFilter.cs
- src/Umbraco.Web.UI.NetCore/Startup.cs
Added a custom `RequestCultureProvider` to use the BackOffice user's language as culture.
Even that we already call `EnsureCulture` from the `OnValidatePrincipal` event. This is not enough, as the culture is reset when the thread hits the controller. 
1. Set the users language to a non-English language. E.g. danish.
1. Sign out
1. Sign in again
1. Verify the localization are updated. 
Note: I tested with multiple users with different languages.
> Netcore: Added request localization from the current user.

- src/Umbraco.Core/IEmailSender.cs
- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.Common/ActionsResults/ValidationErrorResult.cs
- src/Umbraco.Web/Editors/AuthenticationController.cs
for [AB#6972](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6972)
migrates remaining non-oauth AuthenticationController actions to netcore. This migration is nearly 1:1. There's barely any code changes between the two and we can't really test right now without email functionality which i don't think we've ever tried yet.
> Migrates remaining non-oauth AuthenticationController actions to netcore

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Update for Validation UI changes how issues in content of a block are presented.
With the default look, the items will look like this:
With a custom view, we have this look instead:
> UI for highlighting validation issues

- src/Umbraco.Web/Models/Mapping/CommonMapper.cs
* Create a block list editor datatype on a content node
* Create a new user with NO access to the Settings section
* Add a block to the block list editor in a content node
* Verify you have a list of empty block cards with no names, description or icons
* Apply PR & retest to ensure name, icon & description is visible
> (Rework) Block editor - Fix for when you have no access to settings

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
Added the option to define name-required, which sets required on the name-input. This defaults to true and therefor this does not change anything. unless the attribute is defined.
This fix corrects an issue with form-validation begin invalid when the name is an empty string, though the name is locked.
> umb-editor-header name-required attribute

- src/Umbraco.Web/PublishedCache/NuCache/DataSource/AppSettingsNucachePropertyMapFactory.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.ContentDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.ContentNodeKitSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.DictionaryOfPropertyDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/IDictionaryOfPropertyDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/INucachePropertyOptionsFactory.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/LazyCompressedString.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/Lz4DictionaryOfPropertyDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/NucachePropertyOptions.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/SerializerBase.cs
- src/Umbraco.Web/PublishedCache/NuCache/NuCacheComposer.cs
- src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
- src/Umbraco.Web/Umbraco.Web.csproj
- src/umbraco.sln
RE: https://github.com/umbraco/Umbraco-CMS/pull/8365
What?
Compress custom properties at cmsContentNu table level or nucache.db level.
Decompress properties when reading the property from nucache.db or lazily when the property is read / converted.
Map property alias to a shorter key in nucache
Why?
Reduce memory consumption by keeping large string / rich text properties compressed till read.
TODO: Update propertyconverterbase logic for IsValue and HasValue as these check for strings which may not work with lazy decompression.
TODO: Configuration per property editor / per property.
How to test:
Enable MessagePack Nucache Serializer
`<add key="Umbraco.Web.PublishedCache.NuCache.Serializer" value="MsgPack"/>
` …
> WIP Option C - Compress custom properties for nucache to reduce memory consumption

- src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
- src/Umbraco.Infrastructure/Services/Implement/KeyValueService.cs
- src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
- src/Umbraco.Web.UI.NetCore/Umbraco/UmbracoBackOffice/AuthorizeUpgrade.cshtml
- src/Umbraco.Web/Editors/BackOfficeController.cs
ref [AB#6970](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6970)
Migrates remaining non-oauth actions on back office controller to netcore including the authorize upgrade cshtml view.
* Log out of the back office, or clear cookies
* Update the table in the Db `umbracoKeyValue`, change the value for `Umbraco.Core.Upgrader.State+Umbraco.Core` to be a previous step found in the `UmbracoPlan.cs`. For example, use the step before the final: "{2AB29964-02A1-474D-BD6B-72148D2A53A2}" 
* go to the back office, it will redirect to the authorize upgrade page, ensure it works, login and it will redirect to the upgrader
As for the invite user i think we'll need to test that later but the code is basically identical, almost no changes.
> Migrates remaining non-oauth actions on back office controller to netcore

- src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
- src/Umbraco.Core/Persistence/UmbracoDatabaseFactory.cs
Add support for SQL server 2019 to use SQL Server 2012 syntax.
Use SQL Server 2019, check that queries use OFFSET and FETCH.
> Support SQL Server 2012 syntax on SQL Server 2019

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
- src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs
Resolves an issue caused by the `[FromQuery]` parameter binding for arrays, which [needs the parameter name explicitly provided](https://stackoverflow.com/a/55516012/489433).
Without this the array comes through as empty so no level filter is applied.
> Fixed log viewer level filter by correcting binding for provided array of selected values to filter by.

- src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
Ability to perform publish on a single variant when other variants is in the "PublishedPendingChanges" state.
Plus consider the name as data, if new this ensures to save that variant no matter the choice.
**Steps to reproduce UX problem:**
Have a variant document and two languages that both are mandatory.
save and publish content for the secondary language.
make new data for the secondary language and then just save it.
Refresh browser
Try to save and publish data for the primary language. (Before the secondary language would be required/mandatory, but it is already published)
> Accept PublishedPendingChanges state as a published state

- src/Umbraco.Web.UI.Client/src/less/properties.less
- src/Umbraco.Web.UI.Client/src/views/components/umb-date-time-picker.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html
This PR replaces a few `<a>` (anchor) elements in schedule overlay with `<button>` elements for accessibility.
At the moment it seems the datepicker doesn't open when focusing the button and hitting enter, which might because of the transcluded content, but we can look at this in another PR.
> Use button elements in schedule overlay

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
- src/Umbraco.Web.UI.Client/test/unit/common/services/block-editor-service.spec.js
Fixing the issue of missing the use of ´convertVirtualToAbsolutePath´. Plus refactored to the init of a BlockObject, so Devs don't need to worry about this.
> Use convertVirtualToAbsolutePath for all file URLs of a block config

- src/Umbraco.Web/PropertyEditors/EmailAddressConfiguration.cs
For issue https://github.com/umbraco/Umbraco-CMS/issues/3013
On the email datatype there is a field IsRequired, which when true makes the field mandatory overriding the mandatory selection when the datatype is added to a doctype making it mandatory without showing the * etc for a mandatory field. 
This then has confusing and unexpected validation. In discussion with @nul800sebastiaan we thought it would be best to hide the IsRequired field for now. The best I could do was make it hidden and including a deprecated message.
To reproduce the issue, add an email datatype with Is Required set to true to a doctype with mandatory set to false. You'll see it doesn't have the UI of a mandatory field but does have validation for a mandatory field.
> Deprecate IsRequired on Email datatype

- src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
- src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
I want to make the property group header slightly more discreet, and hide property description if not present.
Minor adjustments made to accomplish a simple UI in Block Editors.
> property group header adjustment

- src/Umbraco.Web/Dashboards/DashboardCollectionBuilder.cs
As you start piling 3rd party dashboards onto a solution, sometimes you find yourself wanting to move them around in an order that makes more sense to the editors. As of right now, the only way to do so is pretty cumbersome:
1. Create your own implementation (specialization) of the dashboards in question. 
2. Set the applicable `[Weight]` attribute on your own dashboard classes (it denotes the dashboard sort order).
3. Replace the dashboards in your composer.
[Check the docs](https://our.umbraco.com/documentation/extending/dashboards/#remove-an-umbraco-dashboard) for guidance on how to pull off something along those lines.
This PR allows you to change the weight of dashboards in code, so you don't have to go through the hassle of creating your own implementations. It allows you to do …
> Allow for changing the weight of built-in and 3rd party dashboards

- src/Umbraco.Infrastructure/Examine/NoopBackOfficeExamineSearcher.cs
- src/Umbraco.Infrastructure/Examine/NoopUmbracoIndexesCreator.cs
- src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- Registers noop implementations of required Examine interfaces in core. These are replaced by the `ExamineLuceneComposer`.
- Add conditions on project references of .net framework assemblies to only be used on windows
> Netcore: Optimizations for non-windows development

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreeitem.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js
Now that content types (document, media and member types) use the specific content type icon in tree, it would be great if the node icon updated if icon is changing (icon or color).
With the PR it update the node icon in tree if the content type icon is different from the current content type icon. At the moment the event name is `editors.tree.icon.changed` - not sure if we have something better?
> Update content type icon on save

- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
- src/Umbraco.Web.UI.Client/src/common/resources/auth.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/currentuser.resource.js
- src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js
- src/Umbraco.Web/Editors/AuthenticationController.cs
Migrated the `Authentication/GetCurrentUserLinkedLogins`, and resolved the TODO by moving it to `CurrentUserController`
- Go to backoffice and click to current user button.
> NetCore: Migrate GetCurrentUserLinkedLogins api

- src/Umbraco.Web.Common/Security/BackOfficeSignInManager.cs
Move the code that updates the user on successful login into the netcore `BackofficeSignInManager`
From here https://github.com/umbraco/Umbraco-CMS/blob/netcore/netcore/src/Umbraco.Web/Security/BackOfficeSignInManager.cs#L204-L209
Even that it works on this location, please review it is the correct spot to do this.
- Login the user, and go to user section and ensure the user last login is updated (and the user is not inactive anymore)
> Netcore: Update user on successful login

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/textstring.html
Whilst using the textstring grid editor (aka. Headline), I'd noticed in Chrome Dev Tools there was a warning of multiple/duplicated ID attributes of `id="_text"`.
Digging deeper, turns out to be a small bug when setting the ID in [views/propertyeditors/grid/editors/textstring.html#L6](https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.4/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/textstring.html#L6), the `uniqueId` property is missing the leading `$` symbol, (a-la `$uniqueId`, [as it's set in the Grid controller](https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.4/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js#L917).)
Steps for reproduction, add multiple Headline editors to a Grid, view Chrome Dev Tools _(other web browsers are …
> Grid Textstring editor - Bug with unique ID.

- src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
- src/Umbraco.Infrastructure/Search/ExamineComponent.cs
- src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
See TODO notes in code for some explanation. I will need to fix this up and have a look at v8 next week.
Also fixed a critical issue with DatabaseServerMessenger.LocalIdentity being set incorrectly and not as a property. This means it was recalculated every time with a new GUID so it was changing every time. This meant that this local identity was processing it's own DB instructions which meant that it was processing it's own events twice - essentially double publishing, double indexing, etc... every time. (careful using => assignments! ;)
> Fixes issue with scopes being disposed or referenced incorrectly

- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
It turns out that `!important` doesn't work with the `ng-style` attribute, so I have switched to use `ng-attr-style` instead, which works by setting the exact string, instead of using an object.
Fixes #8688 
* Create a new property on a document type and use the BlockList property editor for it
* In the Editor settings, create a new block and assign it an icon using the red color
* In the Configuration for the block, in its "Catalogue appearance" section, set its **Background color** to `#ff8000` and the **Icon color** to `#000000`
* When using the block editor in the Content section, observe that the block's icon color will be the black color, thus correctly overriding the red color initially chosen for the document type's icon.
> Add `!important' to the color in the style attribute

- src/Umbraco.Core/Persistence/DatabaseAnnotations/IndexAttribute.cs
- src/Umbraco.Core/Persistence/DatabaseModelDefinitions/DefinitionFactory.cs
- src/Umbraco.Core/Persistence/DatabaseModelDefinitions/IndexDefinition.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
RE https://github.com/umbraco/Umbraco-CMS/pull/8365
Use the new IncludeColumns property in the same way as ForColumns property for the Index attribute during a db migration. This will allow for inclusion of columns that don't make up the key of an index
> Support include in sql server indexes

- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
Make thumbnails paths work and don't scale SVGs
---
_This item has been added to our backlog [AB#7910](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7910)_
> 8.7RC umb-block-card absolute path and dont scale SVGs

- src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3.cshtml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8721.
This changes the `@Html.If()` helper method that now correctly HTML encodes the passed in value to prevent XSS attacks with a normal conditional statement.
> V8.7RC: Change grid view @Html.If to conditional statement

- src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8717.
This removes the empty white line in an active Nested Content heading, see linked issue.
> 8.7RC: Fix Nested Content active heading styling

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
When open media picker and clicking media item name, I noticed a console error. This is because it call `$scope.clickHandler()` but it should just be `clickHandler()`.
> Fix media picker clickhandler

- src/Umbraco.Web.UI.Client/src/common/filters/compareArrays.filter.js
- src/Umbraco.Web.UI.Client/src/common/services/angularhelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/search.service.js
- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
If there's an existing issue for this PR then this fixes (in part) #7718 
Continuing the effort to minimize the angular dependency, I have rewritten the remaining usages of angular.forEach with the native equivalent in services and filters.
Basically there should be no noticeable difference when applying this PR; the UI should "just work" as it does now. Validate the following:
> Remove usages of angular.forEach in help services and filters

- src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
Just a minor change, so info icon is aligned in media grid item name.
**Before**
**After**
> Align icon in media grid item overlay

- src/Umbraco.Web.UI.Client/src/less/components/prevalues/multivalues.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
At the moment is was assumed that left column in multivalues prevalue editor is always sortable and therefore added `cursor:move`.
However that is not always the case e.g. in macro parameter editors, where only the icon was acting as sortable handle.
I have updated this to be move specific on `handle` class which is often used or `ui-sortable-handle` which is added on sortable items.
Also note the move cursor is still shown in colorpicker prevalue editor, when hover the color preview and hex code.
> Update prevalues multivalues sortable styling

- src/Umbraco.Web.UI.Client/src/less/listview.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
This PR adjust the styling of listview layouts add button, where it extend styling from `umb-node-preview-add` class instead, so the styling is consistent, e.g. note the bold text of the button label.
**Before**
**After**
> Update styling of listview layouts add button

- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
When invoking a menu item from the tree, a nice backdrop is added behind the resulting dialog. The same backdrop does not appear if you invoke the same menu item from the "Actions" button:
...but this PR takes care of it:
> Add missing backdrop when using the "Actions" button

- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
It's a tad annoying how the tree menu ellipsis button is only clickable at the very center, despite the hover effect and mouse cursor indicating that the entire button should be clickable:
Kinda get the feeling that there are no menu items available when the menu doesn't appear 🤔 
This PR makes the entire button clickable:
> Make the entire tree menu ellipsis button clickable

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
Slight unintended side effect of #8538 is the JS error that occurs when a listview is empty - try searching the "all members" view for a member that does not exist and see the JS console:
This PR adds some defensive coding around the failing method to remove the JS error.
> Fix JS error in empty listviews

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.controller.js
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html
This PR adjust of few things in image cropper prevalues.
- Restrict sortable within parent container
- Add new item on enter instead of submitting form and therefore saving datatype
> Adjust image cropper crops

- src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
At the moment when a media is deleted, but the media picker still has the stored reference, the edit button is shown and when clicking this button the infinite mode of media is opened. However because the media isn't available `$scope.page.loading` is never set to false and `$scope.content` is not set.
So basically it keeps showing the loading indicator
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/media/edit.html#L3
and because content isn't shown while loading, content editors doesn't have the option to click close or using `esc` shortcut.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/media/edit.html#L9
the only option is to refresh page.
I have improved the error handling and only show the edit …
> Only show mediapicker edit button if media is found

- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
This PR add some minor updates to the styling of grid editor add button, so the icon is aligned in the button and the button itself is more round.
**Before**
**After**
> Update styling of grid editor add button

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8575
This PR fixes an issue where it was no longer possible to edit existing embed in grid editor as in PR https://github.com/umbraco/Umbraco-CMS/pull/4899
After this was merged a few days later another PR https://github.com/umbraco/Umbraco-CMS/pull/6341 was made to edit embed from TinyMCE editor. However this PR also changed the scope property in the infinite embed editor from `original` to `modify` in https://github.com/umbraco/Umbraco-CMS/commit/bf9eeb4e373a6c4c44586b4cdfba7b26c7c2ad11 but wasn't aware it was passed in from embed grid editor.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.controller.js#L25
> Make embed grid editor editable again

- src/Umbraco.Web.UI.Client/src/views/media/media.move.controller.js
If you attempt to move a media item to its parent folder, the operation will fail with a big ol' red error message. But the cancel/move buttons are never re-enabled, thus leaving the editor with no visible ways out (you can still click outside the dialog to close it, but still... not nice):
This PR ensures that the "busy" state (which removes the cancel button and disables the move button) is not retained when an error occurs during the move operation:
> Don't retain "move media" in busy state on error

- src/Umbraco.Web.UI.Client/src/less/components/application/umb-language-picker.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.html
- src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
The introduction of SVG icons has had a slight unintended side effect: The language selector arrow always points to the right:
> Fix the arrow direction in the content language picker

- src/Umbraco.Web/Templates/TemplateUtilities.cs
Issue: https://github.com/umbraco/Umbraco-CMS/issues/7386
This is fixed in v8: https://github.com/umbraco/Umbraco-CMS/pull/7530 
I believe this should be fixed in v7 as well. This issue causes server wide CPU spikes which can negatively influence multiple environments/processes on a single server. This makes it have a higher risk than just a performance issue.
To respect the changes already in v8, this is implemented very minimal.
- Updated the Regex to match the v8 fix
- Test with latest v7
1. Put an `<img src="[your base64 image string]" />` in a Rich Text Editor. (https://www.base64-image.de/)
2. Save and publish -> The process takes a long time
- Test with branch
1. Put an `<img src="[your base64 image string]" />` in a Rich Text Editor. (https://www.base64-image.de/)
2. Save and …
> Fix: v7 Base64 image performance in rich text editor

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
If there's an existing issue for this PR then this fixes #8599
As @stefankip describes in #8599, `ContentTypeService.GetAllContentTypeAliases` has a bug when called with parameters (it works fine when there are no parameters).
To verify the problem (and that this PR fixes it), create a template with the contents below and render some content with the template. It will YSOD in the current codebase, and work as expected with this PR applied.
```cshtml
@using Umbraco.Web.Composing
@using Umbraco.Core
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
Layout = null;
var contentTypeAliases = Current.Services.ContentTypeService.GetAllContentTypeAliases(Constants.ObjectTypes.MediaType, Constants.ObjectTypes.MemberType);
}
<html>
<body>
<ul>
@foreach(var contentTypeAlias in contentTypeAliases) { …
```
> Fix parametrized query for specific content types

- src/Umbraco.Web.UI.Client/src/less/listview.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
This PR adjust the styling of listview layout icons a bit, so the are aligned and same sizes: 30x30px + 1px border = 32x32px
**Before**
**After**
> Update styling of listview layout icons

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
Noticed a few missing `shortcut` attributes, so it is possible to close overlays via `esc` key.
> Vv8.7RC Add missing shortcut to close overlay via esc key

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
I noticed various console errors in document type editor where the block list property preview is shown.
I have fixed some of these.
**Before**
**After**
> V8.7RC Fix block list console errors in document type

- src/Umbraco.Web/PropertyEditors/BlockListConfiguration.cs
- src/Umbraco.Web/PropertyEditors/BlockListConfigurationEditor.cs
The block list live editing property in prevalues says it is for live updated custom views. However it also works without custom views, when using dynamic expression in label, e.g. `{{myPropertyAlias}}`.
When live editing is enabled the label text updates as you type. When it is disabled it only update the label text after submitting the overlay.
> V8.7RC Update block list live editing description

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
This PR makes the sorting of items in block list and nested content works within parent container instead of dragging items way out of the block list or nested content area.
> V8.7RC Block list sort within containment

- src/Umbraco.Web.UI.Client/src/less/components/umb-insert-code-box.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/insertcodesnippet/insertcodesnippet.html
During the work on #8522 I discovered that this view did not contain proper `<button>` elements, for the different insert options, which means the focus lock won't be able to pickup the first focusable element properly and puts the focus on the "close" button making one unable to tab to the options inside the overlay. This is fixed in this PR with the added buttons. While I had the view opened I fixed some HTML semantics as well adding `h2` for the title and wrapped the description in `<p>` - I also added proper fallback texts in case the dictionary keys have not been translated for a certain language.
The view visually appears the same as before these changes - I decided to make this an independent PR in an attempt to keep the #8522 as clean as possible 👍
> Accessibility: Fixes for "insert code snippet" view in macro pickers

- src/Umbraco.Web.UI.Client/src/less/gridview.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
During my work on the focus lock for the infinite editor in #8522 I noticed during the testing that the "button" for adding layout or row configurations on the grid content datatype was not tabable since it was wrapped in `<a>` without a `href` attribute. But since it's not really a link I've refactored it to be `<button>` instead and fixed the CSS to add hover and focus styles for the button element.
Furthermore I have added some screen reader friendly text labels as well.
> Accessibility: Grid config datatype improvements

- src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Fixes #8720 
* Install Umbraco CMS without Starter Kit (As this ships with its own tours)
* Verify all tours work
> Fixes #8720 DocType Tour selector fix for 8.7

- src/Umbraco.Web.UI.Client/src/views/packages/edit.html
- src/Umbraco.Web.UI.Client/src/views/packages/views/created.html
- src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.html
- src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
This PR add a few adjustsments to the packages section:
- Accessibility enhancements
- Added `rel="noopener"` for security reasons
- Replace traditional checkbox with `umb-checkbox` component in local package installer
- Use same button size for repo and local package installer
> Packages adjustments

- src/Umbraco.Web.UI.Client/src/less/panel.less
@KevinJump Discovered that the styling was a bit off after the merge of #8160 /cc @nul800sebastiaan 
I did not notice intially since the margin and line-height issues did not appear in the scenarios I tested. Now I realise that the reason why is becuase flexbox is used to center the headline vertically in a box with a height that means one won't notice the neither the margin nor the line-height default styling on h1 elements.
This is addressed and fixed with this PR setting the margin to 0 and the line-height to 1.2 (For the h1 in the umb-editor-header view).
@KevinJump Can you give this one a spin and ensure that this fix don't have any unexpected side effects please? 😃
> umb-editor-header view: Fix h1 styling

- src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyactions.component.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-property-actions.less
- src/Umbraco.Web.UI.Client/src/views/components/property/umb-property-actions.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8537
This PR removes the additional close button and use the toggle button, which change the text when dropdown is open/closed.
For some reason this component was located in [src/views/components/property/property-actions](https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/property/property-actions) folder and not consistent with all other components/directives which are located in [/src/common/directives/components/](https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components)
For the view it was located in a subfolder, but I don't think we need an additional folder for just this …
> Update umb-property-actions toggle button

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
During the work I'm currently doing on #8522 I noticed that there were some issues in this view where tabbing between the items would have a weird double effect. This PR addresses those issues + hides the `<i>` element from screen readers and provides an English fallback text in case the dictionary key does not exist for a certain language.
In the gif's below I display what the filter acts like as well since it's 2 different parts of the code.
**Before**
**After**
> Various fixes for macroparameterpicker view

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
This PR add the `not-allowed` cursor style when however not allowed files in block thumbnail picker similar to file picker in packager: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js#L286
> V8.7RC Add filter css class for not allowed thumbnail extensions

- src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/views/overlays/remove.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
I have added a warning dialog when one hits the "Remove" button next to a user listed in the user picker so that the user is not removed immediately but you have to confirm your action - This is aligning the UI with what happens in other places in the backoffice as well.
**Before**
**After**
> Userpicker: Add warning overlay when the "Remove" button is hit

- src/Umbraco.Core/Persistence/PetaPoco.cs
- src/Umbraco.Core/Scoping/Scope.cs
After executing custom migrations, the following null reference exceptions was often encountered.
This caused the migration version to not be updated and all custom migrations to run again on start-up. The null reference could be easily fixed by using an existing property that has a built in null check. However, this was not the underlying issue since another exception would take its place:
The underlying issue is that PetaPoco's _transactionDepth could be a negative number. This was caused by an IDisposable implementation on the database to always close the transaction and reducing the _transactionDepth, even if no transaction was active/present.
- Replace direct object reference with property that has built in null check
- Add a check to close transaction only if db is in transaction …
> Fix: v7 BeginTransaction null reference after custom migrations

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
While working on a solution for https://github.com/umbraco/Umbraco-CMS/issues/8689 I noticed various issues, which I have fixed in this PR.
- Accessibility enhancements.
- Added `rel="noopener"` for security reasons.
- Stored path `views/propertyeditors/blocklist/blocklistentryeditors/` in a variable.
- Added properties to `vm.labels` after localization.
- The add/plus button didn't had same width and height. Furthermore it looked like you never hit the button because it is moving when the cursor position change. Instead this is updated in `transform` property where it is vertically centered and moved 80% to the left, so the cursor doesn't cover the icon, but it still feels like you hit the button.
> V8.7RC Block list adjustments

- src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
It's been bugging me for a bit now... when you have more than a few languages, the dictionary translations become annoying to manage, because they're not sorted by language display name but rather by the order of which the languages were created (apparently):
This PR ensures that both the dictionary overview and the dictionary item editing sorts the translations by language display name:
> Sort dictionary translations by display name

- src/Umbraco.Web.UI.Client/src/views/languages/overview.html
Following up on #8768, the list of languages seems to be sorted by the order of which they're created. 
This probably doesn't make a whole lot of sense to most people, so this PR ensures that the languages are explicitly sorted by name:
> Sort the languages by their display name

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
- src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/config.html
I just noticed a few other issues with void elements (self-closing) with directives, which are custom HTML elements.
In this case is was causing layout issues in grid configuration settings/styles.
**Before**
**After**
I have the following json configuration in grid settings:
```
[
{
"label": "Background color of row",
"description": "Choose background color",
"key": "background-color",
"view": "colorpicker",
"applyTo": "row",
"prevalues": [
"#D30535",
{
"value": "#32CD32"
},
"#81E6E0",
"#109D95",
"red",
{
"label": "White",
"value": "#fff"
},
"#53B3AE",
{
"value": "#f00",
"label": "Red"
}
]
},
{
"label": "Position",
"description": "Set position",
"key": "position",
"view": "radiobuttonlist",
"applyTo": "row",
"prevalues": [
"left",
{
"value": "center"
},
{
"label": "Right",
"value": …
```
> Ensure directives use end-closing tag

- src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-picker-list.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/userpicker/userpicker.html
This is a very very small PR changing the `<a>` tag to a `<button>` since it's not a link pointing to anywhere - Improves accessibility and screen reader announcement.
> Userpicker view: Change anchor element to button

- src/Umbraco.Core/Services/Implement/ContentService.cs
- src/Umbraco.Tests/Services/ContentServiceTests.cs
If there's an existing issue for this PR then this fixes #7199 8033
As described in #8033, the sort order isn't preserved when copying content; instead the copied content is sorted by creation order of the original content:
This PR ensures that we copy descendants by order of their original sort order. Here's the same operation with this PR applied:
> Preserve sort order when copying content

- src/Umbraco.Web/Mvc/RedirectToUmbracoPageResult.cs
- src/Umbraco.Web/Mvc/SurfaceController.cs
Currently the RedirectToUmbracoPageResult only allows a `pageId` or an `IPublishedContent`.  I think it will be good if we can extend it to handle a `Guid key`. 
To test this use the following code. I have used it on my local install which has the starter kit
_TestSurfaceController.cs_
```
public class TestSurfaceController : SurfaceController
{
public ActionResult Index()
{
return this.PartialView("TestIndex");
}
[HttpPost]
public ActionResult PostToProductsPage()
{
var firstChild = CurrentPage.FirstChild();
return this.RedirectToUmbracoPage(firstChild.Key);
}
[HttpPost]
public ActionResult PostToProductsPageWithQueryString()
{
var firstChild = CurrentPage.FirstChild();
return this.RedirectToUmbracoPage(firstChild.Key, "param=1");
}
[HttpPost]
public ActionResult …
```
> RedirectToUmbracoPageResult - Extended to allow a Guid

- src/Umbraco.Core/Persistence/DatabaseAnnotations/SpecialDbTypes.cs
- src/Umbraco.Core/Persistence/PocoDataDataReader.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
This fixes #5204
A `SpecialDbTypes.NVARCHARMAX` has been added to the enum in order to allow the definition of nvarchar(max) fields in Migration schemas:
```
[SpecialDbType(SpecialDbTypes.NVARCHARMAX)]
public string Body {get; set;}
```
The implementation for this new enum member has been added in `SqlSyntaxProviderBase`, and overriden in `SqlCeSyntaxProvider`  because SqlCE does not implement nvarchar(max) - ntext should be used instead.
> Add varchar(max) support in DTO attributes

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
This fixes #7672 
1. Set the Image Media Types AllowAtRoot property to false in Setting>Media Types>Image.
2. Create a Doc Type with a Media Picker property on it and create a node with this Doc Type.
3. Open the Media Picker.
4. Click upload while viewing the root of the Media folder. This will not open the file upload window.
5. Create a new media folder.
6. Go into the folder.
7. Click to return to the root.
8. Click upload while viewing the root. This will **no longer** open the file upload window.
> #7672 checking allowed image types on each folder switch

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/querybuilder/querybuilder.html
In this PR I have converted the `<a>` tags containing an empty `href` attribute to `<button>` instead improving accessibility and semantics. I have checked that the styling remains intact after the change 😉 
It's hard to show using a GIF but it's the query builder view that opens in the template editor when clicking the "Query builder" button and the changes affect the highlighted dropdowns. It also affects some of the dropdowns that appear depending on, what you select in the first dropdown.
> Query builder: Convert `<a>` to `<button>`

- src/Umbraco.Web.UI.Client/package.json
Updating noUiSlider to v14.6.1 to fix a minor issue with pips not being rendered.
https://github.com/leongersen/noUiSlider/issues/1088
Can be cherry picked to v8.7 branch as well.
> Update to nouislider v14.6.1

- .github/CONTRIBUTING.md
As the contrib branch now contains C# 8 language features, I have updated the required Visual Studio version number accordingly 😄
> Bump required Visual Studio version number in contrib guidelines

- src/Umbraco.Web.UI.Client/src/common/filters/compareArrays.filter.js
Somewhat similar to #8795 but the source of the error is different... as an unintended side effect of #8552, the `compareArrays` filter throws an error if the array being compared to is not defined. Previously this was safeguarded by AngularJS (when AngularJS was used to perform the array iteration) .
It becomes quite evident in the Block Editor when selecting a model for block settings - you're unable to pick any existing element types for the settings model:
This PR amends the `compareArrays` filter, and now the element settings picker works as you'd expect:
> V8.7RC Block Editor: Cannot select an existing element type as settings model

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html
Create more unique id for radiobutton list when using splitview and where two properties on each culture has same alias
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8787
When using splitview and the property using radiobuttons property editor, it is shown for both cultures and with same value of radiobutton `name` attribute, because the property alias is the same.
However this also cause the two radiobutton lists being seen as same group, so when changing selected option it remove the selected option in the another culture.
Note it is both a issue when the property vary by culture and don't vary by culture.
It could most likely in this case also use value from `mculture` and `cculture` querystrings, but it seems a bit safer to use …
> Create more unique id for radiobutton list when using splitview

- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/package.json
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
I noticed that we at the moment are using the spectrum color picker here:
https://bgrins.github.io/spectrum/
However it seems this is unmaintained and another developer has taken over the project and continued the work:
https://seballot.github.io/spectrum/
With some minor adjustments this PR replaces spectrum-colorpicker with spectrum-colorpicker2. The configuration is pretty much the same as this existing one, but with some enhancements.
**Before**
**After**
> Spectrum colorpicker v2

- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
This PR converts 2 `<a>` elements with an empty `href` to `<button>` and cleans up the markup a tiny little bit removing a wrapping `<span>` element since it's not needed nor valid to wrap a `<button>` inside it. The styling handled by the `<span>` has been attached to the `<button>` instead.
> Dictionary list - convert a to button and remove wrapping span element

- src/Umbraco.Web.UI.Client/src/less/forms.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
…ckable items
With this PR I have changed the `<a>` element containing an empty `href` attribute to be `<button>`. I have also made a little styling adjustment so that there is 10px button margin from the search form and down to the card items so when one hovers the items there is a little space between the search box and the items.
> Macropicker: Fix semantics

- src/Umbraco.Web.UI.Client/src/less/components/umb-checkmark.less
- src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
I converted 2 `<a>` elements with empty `href` attributes to be `<button>` instead. I also added som styling in order to ensure that the "checkbox" in the "list layout" of the users would receive focus styles when tabbing. Currently the `<umb-checkmark>` directive only consists of a single icon - I will soon address this specifically in another PR unless someone beats me to it wrapping the icon in the directive inside a button by default and adjust the styling accordingly.
Attached are some screendumps of the areas that have been changed and need to be tested 😄 
**Create user add button**
**View users in list layout**
> Users - fix semantics + fix focus on umb-checkmark directive

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/itempicker/itempicker.html
I have changed the `<a>` to `<button>` since it had an empty `href` attribute. I have also attached the click event to the `<button>` element instead of on the `<li>` element making the tabbing behave better since the `<li>` will no more be band-aided by the ngAria component 😃
> Convert a to button

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
If there's an existing issue for this PR then this fixes #8705
As described in #8705: 
- Rename a node while the built-in URL tracker is enabled
- Go to the info panel and see if the redirect panel (see below) shows up
- Before applying this change it won't show up, after applying this it will show up
- Also test that the redirect panel is still hidden on items that have no redirects.
> Adding `display: none;` prevents `ng-show` from working

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
We have several issues in regards to use NC in BL. But there is no reason to have NC now that BL is available. Therefore we want to nudge Devs to use Block List, and mark the usage of NestedContent as unsupported in the context of Block Editors.
---
_This item has been added to our backlog [AB#7946](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7946)_
> V8.7RC Prevent usage of NestedContent in BlockEditors

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html
- src/Umbraco.Web/PropertyEditors/TextboxConfiguration.cs
We should not place vars use internally by property-editor in the model. The model will be replaced with a model from server on save, so we will loose these vars. They can be maintained by `model.onValueChanged` but there is no need for this. Instead we just keep them in $scope.
This issue was seen on TextArea and TextBox, Which this PR fixes.
Previously validation errors would appear on model after model has been returned from server, as the maxChar variable was stored on model and therefor lost.
Screenshot of issue appearing in TextBox:
> AC7976 dont place runtime vars in model

- src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Our front-end rendering uses the UDIs of ElementTypes for caching, meaning that we have to ensure these are unique. Before this fix, we just copied the raw data of an elementType without manipulating it. Though pasted entries are created as new, their data is parsed on, leaving the inner properties of Block Editors with the same UDIs as their source. This problem is first visible when rendering these in the front-end as the first rendered ElementType with that UDI will be cached and stay as the data shown for other Blocks/ElementTypes using the same UDI.
This PR replaces UDIs on Paste, ensuring they are unique.
To reproduce, make this scenario happen:
You need three levels of Block Editors to imitate the scenario of copying data that contains an inner property of Block List Editor. The …
> V8.7RC: Recreate UDIs for pasted Block Editor entries

- build/NuSpecs/tools/Web.config.install.xdt
- src/Umbraco.Web.UI/web.Template.config
The MIME types for `.woff` and `.woff2` file extensions are updated by Umbraco and set to outdated/incorrect values:
https://github.com/umbraco/Umbraco-CMS/blob/44fbc29541604973df5311af9898fc4ceaad583d/src/Umbraco.Web.UI/web.Template.config#L196-L197
https://github.com/umbraco/Umbraco-CMS/blob/3f5729767d362c86011865845cebea28f1ea5c92/src/Umbraco.Web.UI/web.Template.config#L320-L321
The correct MIME types are `font/woff` and `font/woff2` (see [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) and the [official IANA list](http://www.iana.org/assignments/media-types/media-types.xhtml#font)). This PR makes sure these are set in the default `web.Template.config` (new installs) and updated in `Web.config.install.xdt` (when upgrading via …
> Use correct woff and woff2 MIME types

- src/Umbraco.Web.UI.Client/src/installer/steps/database.html
On the installer's SQL Server configuration textbox, the placeholder value is missing an escape character. Due to this, the placeholder value looks like this "127.0.0.1SQLEXPRESS".
After this fix, the placeholder value should look like "127.0.0.1\SQLEXPRESS"
**Before the fix:**
**After the fix:**
> Added missing escape character on installer's DB config page

- src/Umbraco.Web.UI.Client/src/views/macros/macros.create.controller.js
- src/Umbraco.Web.UI.Client/src/views/relationtypes/create.controller.js
If there's an existing issue for this PR then this fixes #8805
This PR fixes the JS errors that occur in V8.7RC when creating macros and relation types (see #8805).
When applied, macro and relation type creation work once more:
> Fix JS error when creating macros and relation types

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
As a slight regression (possibly a merge conflict), we're no longer able to add items to Nested Content; the editor simply throws a JS error:
> Fix broken Nested Content "add content" dialog

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
The refactoring of the Nested Content "add content" dialog in #8044 has left the handling of the clipboard somewhat broken.
First of all the header ("Add content") should be hidden if the clipboard contains any applicable items, as the other dialog headers ("Paste from clipboard" and "Create new") take its place:
Second when you attempt to clear the clipboard you'll see an error in the JS console (even if the clipboard is actually cleared):
This PR fixes the clipboard handling - the JS error is removed and the header is hidden when the clipboard contains items:
> Fix the Nested Content "add content" dialog handling of the clipboard

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
With this PR the custom views of Block List, don't need to use the API object anymore(it will still be available). As this PR appends methods to the Block Object. Making it possible to just call 'block.edit()' instead of 'api.editBlock(block, true, index, parentForm)'.
The options available are:
block.edit();
block.editSettings();
block.copy();
block.requestDelete();
block.delete();
---
_This item has been added to our backlog [AB#7968](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7968)_
> V8.7RC: Block List property editor api methods available on blockObject

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
In regards to a Block of Bloc List with a custom stylesheet.
Before this fix, the validation indication was not visible cause it was target to an element inside the scoped stylesheet.
This fix moves the CSS to the parent element, making it display cause it's then out of the scoped element.
Result:
---
_This item has been added to our backlog [AB#7978](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7978)_
> V8.7RC: Moved validation indication one element up.

- src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8723
There is no need to call hideDialog, as the two options that need to hide the menu does that already. The third option is a shift of UI, so it should not hide the menu.
This PR removes that method call and thereby solving the above issue.
> Should not call hideDialog

- src/Umbraco.Web/BlockListTemplateExtensions.cs
Changed the return type from MvcHtmlString to IHtmlString in the BlockListTemplateExtensions as suggested in #8727. 
I'm having a hard time testing it since I still don't really understand how to get blocklist to actually work.
---
Edit:
Managed to figure out Block List and get it tested. It works just fine apart from having to edit the /Views/Partials/BlockList/Default.cshtml  from:
```
@inherits UmbracoViewPage<BlockListModel>
@using Umbraco.Core.Models.Blocks
@{
if (Model?.Layout == null || !Model.Layout.Any()) { return; }
}
<div class="umb-block-list">
@foreach (var layout in Model.Layout)
{
if (layout?.Udi == null) { continue; }
var data = layout.Data;
@Html.Partial("BlockList/Components/" + data.ContentType.Alias, layout)        
}
</div>
```
to: 
```
@inherits …
```
> V8/bugfix/return IHtmlString from GetBlockListHtml

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
When user creates a new block, not in inline-editing mode, the editor overlay will appear after block type selection. If user wants to cancel at this point, we want to cancel the whole creation and not just the editing of its properties.
This PR changes the buttons when in creation flow, showing "cancel" and "create". If cancel the user will be asked if they are sure about discarding this creation.
As seen in this screenshot:
> Different user flow when creating a new blocks

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html
Recently I fixed a issue with radiobuttonlist in splitview in this PR https://github.com/umbraco/Umbraco-CMS/pull/8792
But I then noticed that when the property was mandatory and using default or a custom validation message, this wasn't shown.
This has been fixed in https://github.com/umbraco/Umbraco-CMS/commit/f5aeca5f3dacae8016488139d38ca14dba39681d
Furthermore I noticed checkboxlist didn't show this message either and the value of `name` attribute was identical in splitview although this didn't cause issues as with radiobuttons as multiple options are allowed, but could cause issues with validation of the correct "group".
So I have now made this consistent with radiobuttonlist.
> Checkboxlist and radiobuttonlist validation

- src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8801
Mistakenly we have forgotten to make resolvers specific to entry types. Making it impossible to use the clipboard service for other types than ElementTypes. This is an error that will be corrected by this PR.
-- Breaking Change --
This PR is slightly breaking as copy and pasting elementTypeArray has changed.
In general, this PR requires resolvers to provide the entry-type that it will be used for, this simplifies writing resolvers as you can define the type it should be used for.
Due to this, copying an array of elementTypes should be using the entry-type ElementType, as we will start using this type for which resolvers that match. Meaning that array and single entries will have the same type. and code for pasting should be checking …
> V8.7RC: Clipboard resolvers should target specific entry types

- src/Umbraco.Web/BlockListTemplateExtensions.cs
These are "duplicates" of the extension method on HtmlHelper (just with the input switched around) and should not be needed.
It can actually encourage people to do bad things, when they think they need to instantiate the HtmlHelper dependency by newing it up, so we've decided to simply just remove this to avoid having that happen.
This is part of the changes proposed by @ronaldbarendse in his latest PRs (see: https://github.com/umbraco/Umbraco-CMS/issues/8727) but as we will not be pulling all of it in currently, we decided to break this one out from the rest and include it in 8.7.
@ronaldbarendse we'll be following up on the rest of the proposed additions (esp. the Partials stuff which looks really good) we're just not ready to include it in the 8.7 release.
> V8.7RC: Removing extensions for GetBlockListHtml on IPublishedContent

- src/Umbraco.Core/Models/Blocks/BlockListItem.cs
- src/Umbraco.Core/Models/Blocks/BlockListModel.cs
- src/Umbraco.Core/Models/Blocks/ContentAndSettingsReference.cs
- src/Umbraco.Core/Models/Blocks/IBlockReference.cs
- src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8727.
Currently, you have to cast the content and settings from the `BlockListItem` to the correct type, before you can access the strongly typed models, e.g.:
```cshtml
@model BlockListItem
@{
var content = Model.Content as Feature;
var settings = Model.Settings as FeatureSettings;
}
<h1 class="@settings.CssClass">@content.FeatureName</h1>
```
This PR adds the generic classes `BlockListItem<T>` and `BlockListItem<TContent, TSettings>` that both inherit from `BlockListItem`. The PVC is updated to create instances of the most explicit, matching generic type, so that can be used in the (partial) views:
```cshtml
@model BlockListItem<Feature, FeatureSettings>
<h1 …
```
> 8.7RC Add generic BlockListItem classes

- src/Umbraco.Core/ContentExtensions.cs
- src/Umbraco.Core/Models/Blocks/BlockEditorDataConverter.cs
- src/Umbraco.Core/Models/Blocks/BlockListLayoutItem.cs
- src/Umbraco.Core/Models/PropertyCollection.cs
- src/Umbraco.Core/PropertyEditors/ComplexPropertyEditorContentEventHandler.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/PropertyEditors/BlockEditorComponentTests.cs
- src/Umbraco.Tests/PropertyEditors/NestedContentPropertyComponentTests.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/Compose/BlockEditorComponent.cs
- src/Umbraco.Web/Compose/BlockEditorComposer.cs
- src/Umbraco.Web/Compose/NestedContentPropertyComponent.cs
- src/Umbraco.Web/Umbraco.Web.csproj
This is when we do a full node copy (not a JS copy). When that occurs we need to re-generate new UDIs for each block in the block list value. We do this already for Nested Content too and just like NC this code will deal with nested block editors and even nested block editors within nested other complex editors that are in a block editor.
I've come to realize however that this is still problematic and it's the same for Nested Content. If there's a block editor, or nested content within another complex editor where the root editor is not itself then the GUIDs/UDIs won't be replaced in that nested json data. I'm not too worried about that scenario for now for the 8.7 release since that scenario probably won't exist very often but it's something to consider in the future. 
All of this logic …
> Ensure new UDIs for blocks when copying

- src/Umbraco.Core/Configuration/IConfigManipulator.cs
- src/Umbraco.Core/Configuration/XmlConfigManipulator.cs
- src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
- src/Umbraco.Infrastructure/Routing/RedirectTrackingComponent.cs
- src/Umbraco.Web.BackOffice/Controllers/RedirectUrlManagementController.cs
Issue: https://github.com/umbraco/Umbraco-CMS/issues/8835 reported on alpha001.
Testing notes:
- Navigate to the _Redirect Url Management_ dashboard in the **Content** section;
- Clicking "Disable URL tracker" and confirming will present you with a success notification stating _"**URL tracker has now been disabled.**"_ 
- check appsettings.json ➡️ there needs to be a new property object like:
```
"Umbraco": {
"CMS": {
. . .
"WebRouting": {
"DisableRedirectUrlTracking": "true"
}
}
}
```
- Clicking then "Enable URL tracker" will present you once more with a success notification this time saying _"**URL tracker has now been enabled.**"_ 
- check appsettings.json ➡️ the value of `DisableRedirectUrlTracking` should be set to `"false"`
> NetCore: Fix for disabling/enabling url tracking

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
At the moment grid editor is using its own local function to create a guid for an unique id of e.g. controls.
However most places in backoffice we already use `String.CreateGuid()` extension method: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/lib/umbraco/Extensions.js#L49-L59
So I think we should remove this function and use the extension method instead to create an unique id. No need to reinvent the wheel 😄🎡
Here is an example with the current function vs `String.CreateGuid()`:
```
$scope.setUniqueId = function () {
var guid1 = guid();
var guid2 = String.CreateGuid();
console.log("guid1", guid1);
console.log("guid2", guid2);
return guid1;
};
```
Furthermore I couldn't find any references where the parameters in `setUniqueId()` function was used, so I …
> Use String.CreateGuid in grid editor

- src/Umbraco.Web.UI/config/umbracoSettings.config
The XML comments for KeepAlive mention the URL for the KeepAlive.Ping action but incorrectly omit 'umbraco' from the path.
The change adds the 'umbraco' section to the path.
> Change wrong URL in KeepAlive XML Comments

- src/Umbraco.Core/Compose/AuditEventsComponent.cs
- src/Umbraco.Core/Compose/RelateOnCopyComponent.cs
- src/Umbraco.Core/Compose/RelateOnTrashComponent.cs
- src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComponent.cs
- src/Umbraco.Web/Compose/BackOfficeUserAuditEventsComponent.cs
- src/Umbraco.Web/Compose/NotificationsComponent.cs
- src/Umbraco.Web/Compose/PublicAccessComponent.cs
- src/Umbraco.Web/Logging/WebProfilerComponent.cs
- src/Umbraco.Web/PropertyEditors/PropertyEditorsComponent.cs
- src/Umbraco.Web/Routing/RedirectTrackingComponent.cs
- src/Umbraco.Web/Search/ExamineComponent.cs
Static events are pretty evil because if you don't unsubscribe from them the event handler will pin an object that should be GC'd to the root of the app. This can cause memory leaks but worse can cause really odd things to happen. I'm surprised this hasn't been an issue in our integration tests. There's a chance it is causing problems but we don't visibly see it happening. There's also a chance this is causing problems in websites in rare circumstances like overlapping appdomains but I can't be sure. What is clear is that we absolutely must unsubscribe from these events so this fixes that to ensure there isn't weird problems occuring. 
This is a backport from the netcore project because this was absolutely causing problems with integration tests so it's strange we don't see these in the …
> Ensure event handlers are unsubscribed  in Core Components

- src/Umbraco.Web.UI.Client/src/common/services/iconhelper.service.js
- src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
- src/Umbraco.Web.UI/config/umbracoSettings.config
- src/Umbraco.Web/Composing/Current.cs
- src/Umbraco.Web/Editors/BackOfficeController.cs
- src/Umbraco.Web/Editors/BackOfficeModel.cs
- src/Umbraco.Web/Editors/BackOfficePreviewModel.cs
- src/Umbraco.Web/Editors/IconController.cs
- src/Umbraco.Web/Editors/PreviewController.cs
- src/Umbraco.Web/Runtime/WebInitialComposer.cs
- src/Umbraco.Web/Services/IIconService.cs
- src/Umbraco.Web/Services/IconService.cs
- src/Umbraco.Web/Umbraco.Web.csproj
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8919
As you are required to be authorized to retrieve icons through the getIcon end-point, we cannot retrieve icons on the client-side when the user is not authorized. Meaning that the icons used in the login view cannot be loaded in the same manner.
To fix this we will inject the two known icons into the runtime cache through the razor document, which is allowed to retrieve the icons no matter authorization.
This Draft PR does not retrieve the icons from disc, meaning that we have to replace line 128 and 129 in Default.cshtml with razor code that gets the correct SVG.
This draft PR solve the client-side part and needs some Razor work to be done.
> Inject icons used in login screen to the runtime icon cache

- src/Umbraco.Examine/ContentValueSetBuilder.cs
- src/Umbraco.Examine/UmbracoContentIndex.cs
- src/Umbraco.Web/Scheduling/SimpleTask.cs
- src/Umbraco.Web/Search/ExamineComponent.cs
- src/Umbraco.Web/Umbraco.Web.csproj
Fixes issue with scopes being disposed or referenced incorrectly due to yield returns as this can capture a scope in the enumerator which will get passed to a background thread in Examine and cause some issues.
We saw this issue in netcore but the issue must still exist in v8 but we don't visibly see it for some reason.
The other issue is that the ValueSet lookup for content was done 3x when an IContent is saved and it should only be done 2x, one for published, one for unpublished.
The other issue is that the data lookups to build a ValueSet are intended to be done on a background thread. This is the case in v7 because the IEnumerable is lazy and passed all the way down to Examine's background thread but this doesn't occur in v8 because we need to iterate/split that value set before it's …
> Umbraco to re-index data on background thread and fix potential Scope issue

- src/Umbraco.Core/Persistence/Repositories/IMemberRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/SimpleGetRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
- src/Umbraco.Core/Services/IMembershipMemberService.cs
- src/Umbraco.Core/Services/Implement/MemberService.cs
- src/Umbraco.Core/Services/Implement/UserService.cs
- src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs
- src/Umbraco.Tests/Services/MemberServiceTests.cs
- src/Umbraco.Web/Cache/DistributedCacheExtensions.cs
- src/Umbraco.Web/Cache/MemberCacheRefresher.cs
- src/Umbraco.Web/Security/MembershipHelper.cs
- src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs
Fixes #8433 
Ensures there are no write locks when updating members during login
This also finalizes an outstanding TODO that has been there for a very very long time that will hugely boost performance for sites that are membership heavy and have a lot of active logins at once. We never cached members by username but that is how they login and how they re-authenticate each request which is a huge amount of database calls. 
---
_This item has been added to our backlog [AB#8415](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8415)_
> Fixes #8433 ensures there are no write locks when updating members during login

- src/Umbraco.Tests.AcceptanceTest/README.md
- src/Umbraco.Tests.AcceptanceTest/config.js
- src/Umbraco.Tests.AcceptanceTest/createEnviromentConfiguration.js
- src/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
- src/Umbraco.Tests.AcceptanceTest/package.json
- src/Umbraco.Tests.AcceptanceTest/postinstall.js
Ask user about username and password for the Umbraco User to be used for Cypress as part of the installation script.
This is how it will look running the npm installation script, which will result in an environment configuration file that contains the username and password.
Test notes:
- Test that "npm i" askes for user credentials if NO cypress.env.json exist.
- Test that "npm i" DOES NOT askes for user credentials if the cypress.env.json already exist.
- Test that you can change credentials by running "npm run config"
- Test that baseUrl does not get set when leaving prompt question 'baseUrl' empty.
- Test that defining baseUrl in prompt gets set in cypress.env.json
- Test that cypress uses the environment baseUrl, if defined.
- Read the readme file
> create enviroment configuration through install script

- src/Umbraco.Web.UI.Client/src/common/services/iconhelper.service.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-iconpicker.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
- src/Umbraco.Web.UI.Client/src/less/helveticons.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.html
Reverting parts of helveticons.less and other parts from the umb-icon PR to ensure backwards compatibility
---
_This item has been added to our backlog [AB#8567](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8567)_
> 8.8 Revert icon styling, to ensure backwards compatibility

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree-root.less
- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
changes the appearance of umb-button-ellipsis for a more balanced look. As well aligns its appearance in the tree
---
_This item has been added to our backlog [AB#8585](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8585)_
> adjust default size of umb-button-ellipsis and its apperance in umb-tree

- src/Umbraco.Web.UI.Client/src/less/components/card.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/8702
Break(Linebreak..) the text in item picker so long text doesn't go on top of each other.
---
_This item has been added to our backlog [AB#8609](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8609)_
> Review: Break text in item-picker cards

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8894
Test that we always show if limits are exceeded...
---
_This item has been added to our backlog [AB#8614](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8614)_
> Review: Always show if limit are exceeded

- src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/mediatypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/membertypes/delete.html
This PR always shows the dialog actions, so the user always can cancel the dialog.
Now the delete-action button says delete to be explicit and it's disabled until the user has checked the checkbox.
---
_This item has been added to our backlog [AB#8615](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8615)_
> Review: Always show action buttons in delete dialogs & enable once checked

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautofocus.directive.js
This PR allow to pass in truthy values (0/1, 'true'/'false', true/false) to `umbAutoFocus` similar to `preventEnterSubmit ` and `preventDefault` directives.
Originally added to this PR https://github.com/umbraco/Umbraco-CMS/pull/8639 but moved to a separate PR instead.
> Allow to pass in boolean to umbAutoFocus directive

- src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.create.controller.js
I spotted another bug along the lines of what is described in #8805 - same problem, only related to creating new dictionary items:
With this PR the JS error is removed, and newly created dictionary items are opened automatically for editing:
> Fix JS error preventing newly created dictionary items from opening automatically

- src/Umbraco.Web.UI.Client/src/views/datatypes/create.controller.js
- src/Umbraco.Web.UI.Client/src/views/datatypes/create.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/create.controller.js
- src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
- src/Umbraco.Web.UI.Client/src/views/mediatypes/create.controller.js
- src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html
Somewhat related to #8805... when creating folders in the Settings section (document type folders, media type folders, data type folders) a nasty JS erorr appears in the console:
This PR removes the JS error 😄
> Fix JS errors when creating folders in the settings section

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js
- src/Umbraco.Web.UI.Client/src/less/belle.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-color-picker.less
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
Currently we have color picker using spectrum plugin and used in prevalues of Color Picker property editor. It would howeever be great to re-use this various places in backoffice. E.g. in a custom dashboard, a custom property editor or as prevalue editor in grid configuration. We have a `colorpicker` prevalue editor, but with this it would make it easier to add a new prevalue editor (or your own prevalue editor) allowing to re-use this.
So this it adding a new component `<umb-color-picker>`.
I have recently released a new property editor `Color Pickr` https://our.umbraco.com/packages/backoffice-extensions/color-pickr/ inspired from this vanilla JS plugin called Pickr: https://simonwep.github.io/pickr/ 🥳🎉🚀
I could use much of the same approach to create this component wrapping spectrum …
> Add color picker component

- src/Umbraco.Web.UI.Client/src/less/components/umb-tags-editor.less
When opening splitview the tags editor overflow its container a bit which in causing horizontal scroll.
I have adjusted the styling, so the input fit within its container.
**Before**
**After**
> Adjust tags editor typeahead to fit within container in splitview

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtogglegroup.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle-group.html
If there's an existing issue for this PR then this fixes #8716 
Specify `input-id` for `umb-toggle` and add a label to refer to that id.
Before:
After:
> Associate existing label to the button for a umb-toggle-group item (#8716)

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/config.html
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
When there is no grid configuration for settings and styles two empty boxes are shown for these. It would be nicer to show an empty message here.
Furtheremore if you only use e.g. styles there is no need to use valuable space to show an empty settings box. So instead we can just show each box it any items are available. I have also changes, so the submit button only is visible when any configuration is available.
> Show only settings and styles boxes when each of them has configuration

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.less
When a block is unsupported in block list editor, we can use `<umb-code-snippet>` to show the json, which also makes it easy to copy the snippet.
It is also a bit more consistent with grid error https://github.com/umbraco/Umbraco-CMS/pull/8548 and query builder https://github.com/umbraco/Umbraco-CMS/pull/7294
For testing I has just comment out this line locally https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js#L200
**Before**
**After**
> Use umb-code-snippet in unsupported block

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/checkboxlist.controller.js
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/checkboxlist.html
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/radiobuttonlist.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
This PR add a checkboxlist prevalue editor similar to that we have radiobuttonlist prevalue editor.
Previous this PR https://github.com/umbraco/Umbraco-CMS/pull/1496 was rejected but I have now submitted this one a made it a bit simpler as a start.
This can be useful in both grid configuration, but also as prevalue editor in a property editor without the need to add your own in most cases.
Much of the logic it similar to the checkboxlist property editor. Radiobuttonlist prevalue editor both support `model.config.prevalues` and `model.prevalues` (I guess one of them is legacy format) so I think it makes sense to make checkboxlist prevalue editor support similar format.
An example JSON for grid configuration using a string array and object array of prevalues.
```
[
{
"label": "Weekdays", …
```
> Checkboxlist prevalue editor

- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/sectionpicker/sectionpicker.html
Depending on whether or not the "mediatypepicker.html" and controller is actively being used or not this PR is probably the final of it's kind turning `<a>` containing and empty `href` into a proper `<button>` and adding `aria-hidden="true"` on the icon 😃 
I've fixed some styling as well.
This is the view in question and the screendump is taken after the changes were made 👍
> Section picker: Fix accessibility and semantic issues

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/colorpicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.html
This PR has a few adjustments to colorpicker prevalue and property editors.
While looking at this issue https://github.com/umbraco/Umbraco-CMS/issues/8825 (although I didn't find a solution for now) I noticed a few other things to update.
- `$scope.isConfigured` was defined twice in colorpicker property editor (exact same line)
- Update to use `vm` in colorpicker property editor
- In colorpicker property editor we have an `isTrue()` function - however we have a `Object.toBoolean()` extension method, so we can use this instead.
> Adjustments of colorpicker prevalue and property editor

- src/Umbraco.Web.UI.Client/src/less/buttons.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
This PR add a few adjustments to grid editor to use `<button>` elements and adjust the styling a bit for `btn-icon` class.
> Use button elements in grid editor

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8920
Previous in https://github.com/umbraco/Umbraco-CMS/pull/8569 the edit button was only shown if the media item was found. However right after a media item has been picked, this property was not set and therefore the condition evaluated as false.
@kjac submitted an alternative fix for this in https://github.com/umbraco/Umbraco-CMS/pull/7406
I have used part of the changes he requested to fix this issue 🎉 🥳
> Show mediapicker edit button after adding media items

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
I noticed while using the Backoffice UI API Docs that the `descriptionLocked` parameter for the umbEditorHeader directive was not documented, found here:
https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbEditorHeader
I've added a description for the parameter!
> Add documentation for descriptionLocked parameter

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
I thought I had already addressed this with #8779 but apparently I somehow managed to forget it... doh! 🤦‍♂️ However this PR moves the click event from the `<li>` element to the `<button>` element where it belongs meaning we don't see the current weird "double tab" issue since the ng-aria band aid adds `role="button"` to the `<li>` element making that tabable as well 😬
> Macropicker view: Avoid weird double tabbing behavior

- src/Umbraco.Web.UI.Client/src/less/pages/login.less
- src/Umbraco.Web.UI.Client/src/less/panel.less
- src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
Turned out there were a few `<a>` elements with empty `href` attributes in this view, which I have now converted to be `<button>` and fixed the styling accordingly.
> Login screen: Convert a to button

- src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
I have converted the `<i>` icons to use the new and shiny `<umb-icon>` directive instead.
> App header: Use umb-icon

- src/Umbraco.Web.UI.Client/src/less/main.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/8924
+ added word-break for description to avoid having long words in description overlapping the property controls.
---
_This item has been added to our backlog [AB#8649](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8649)_
> fixes 8924, Always clear both

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.html
We should use block.edit() as we recommend others to do.
---
_This item has been added to our backlog [AB#8574](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8574)_
> use block.edit()

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/8839
use "icon-add" instead of plus character from font. This has to be done to make sure the sign aligns correct on MacOS and Windows.
This PR also includes other small UI adjustments.
---
_This item has been added to our backlog [AB#8129](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8129)_
> Review 8839 use icon for plus sign

- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
In the previous versions of Umbraco, the variant picker entries were sorted alphabetically:
Somewhere along the line this stopped working, leaving the variants to appear in a somewhat random order (I suspect by order of which the languages were created):
This PR re-introduces the alphabetical sorting in the variant picker:
> Sort the variant picker entries by display name

- src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
This is somewhat related to #9006 - the languages in the global language selector aren't sorted in any particular way:
The languages used to be sorted alphabetically, which I think makes perfect sense...to this PR adds sorting to the language selector:
> Sort the languages in the global language selector

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
@nul800sebastiaan We need to put a hold on the party - Turns out there were more `<a>` with an empty `href` - Only it's just set without a value some places. More PR's incoming - Fixed this one by converting `<a>` to `<button>`. 👍
> Linkpicker: Convert a to button

- src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
A thing I have been missing from the Diplo Tracelog viewer package, is the ability to have the log viewer poll for changes and update automatically.
So I added this functionality.
As you can see in the gif, you can poll every 2, 5, 10, 20 and 30 seconds, and it will keep any open log items open, upon loading more log items.
To test, open two browser windows with umbraco in them. In the first one go to the logviewer, and start polling. Open one of the log items.
In the other window, do some stuff that triggers logging, like logging in, publishing content etc.
Verify that the log items update, and the open log items keeps being open, when new items are added.
> Adds polling function to the Logviewer

- .github/CONTRIBUTING.md
I'm not sure you need to restate the version here, having got it specified in the list above, but if you do, then a vanilla 2017 won't build the source because of the c#8 stuff introduced recently.
> Update 'working with the code' to remove reference to VS2017

- src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Fix for issue found in https://github.com/umbraco/Umbraco-CMS/pull/9008#issuecomment-702565353 which was backtracked down to v8.
This fixes the issue about "Render in template"
It seems like an issue since https://github.com/umbraco/Umbraco-CMS/pull/5606.
Basically the issue is that the class `icon-navigation-down` is now set on the `umb-icon` instead of directly on the `button`
- Run the tour "Render in template" in a setup without starter kit
- Ensure the template folder is open when the tour is started (E.g. by running the first tours)
> Bugfix: Updated tour skip-step condition to the new format after umb-icon

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
If the type-value updates it might still be 'nothing' and therefore we should ensure it gets the fallback value.
Removes the issue of the publish button disappearing in the content editor.
And other places where we use the umb-button-group.
> Ensure the fallback value if value updates

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautofocus.directive.js
Seems like #8799 broke the `umb-auto-focus` directive... it now assumes it's enabled by default, causing focus to be applied to all the wrong things out of order.
As an example: The data type selector should automatically be focused when it's opened, so you can start typing right away; but it's not:
This PR fixes the directive, so it only applies focus if `umb-auto-focus` is actually meant to be applied (either by supplying `umb-auto-focus` without a value or by using `umb-auto-focus="true"`). Now the data type selector does receive focus automatically:
> Fix broken auto-focus

- src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
Angular elements are custom HTML elements, which are not meant to be void elements (self-closing) although it did seem to work in previous Angular versions.
I already fixed this issue in https://github.com/umbraco/Umbraco-CMS/commit/12a4dbc7052aad1e0018396be27be82feb5b7827#diff-144204f44d67201e4a96574595d21b13 but is seems this was reverted when merging https://github.com/umbraco/Umbraco-CMS/pull/8213
In the case it only cause some addtional spacing in the logviewer filter.
**Current**
**After**
> Fix void element of umb-checkbox component

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbsearchfilter.directive.js
- src/Umbraco.Web.UI.Client/src/less/belle.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
- src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
I had a look around in the backoffice and was suprised to see that the `<umb-search-filter>` directive was not being used more since I had a vague memory that I switced some of the old patterns to use this directive - Turns out I was wrong. So some more PR's changing those patterns to use the `<umb-search-filter>` will be incoming 😄 
**Update:** The directive has also been extended to accept a css-class parameter, since I foresee we might need it in some scenarios 😃 
**Update 2:** I realised that we needed to add some more "scoped" styling for the directive since currently we would run into issues with using CSS modifiers in other context - Therefore the 3 places where the directive is being used already has also been updated.
Therefore I want to start out by changing the `<i>` to …
> umb-search-filter: Convert i to use umb-icon

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
I have changed the search box to use the `<umb-search-filter>` directive in order to keep things DRY and ensure any potential fixes in regards to semantics, styling accessibility etc. only needs to be done in one place.
**Edit:** Please hold on merging this PR until #9037 has been merged since I decided to refactor a few things in the directive that needs to be in the core before this change is merged. Once the changes to the directive has been merged I need to tweak this PR a little bit as well - Cheers 👍
> Composition: Refactor search box to use umb-search-filter directive

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
This PR changes the search markup to use the `<umb-search-filter>` ensuring the markup is aligned throughout the entire backoffice.
**Edit:** Please hold on merging this PR until #9037 has been merged since I decided to refactor a few things in the directive that needs to be in the core before this change is merged. Once the changes to the directive has been merged I need to tweak this PR a little bit as well - Cheers 👍
> Iconpicker: Switch to umb-search-filter

- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-box.html
This PR updates the `umb-tree-item` and `umb-tree-search-box` views to use the `umb-icon` directive.
> Add umb-icon to umb-tree-item and umb-tree-search-box

- src/Umbraco.ModelsBuilder.Embedded/BackOffice/ContentTypeModelValidatorBase.cs
Creating a content type named "System" has the quite unintended side effect of breaking Umbraco entirely:
This was achieved with ModelsBuilder in `PureLive` (default) mode:
1. Create the content type "System" - an empty content type is fine.
2. Reload the backoffice.
This PR adds validation to prevent this specific case of unfortunate content type naming; it looks like this when you attempt to create a "System" content type:
There are likely other cases to be found down the road, and once found we can add them to the `reservedModelAliases` collection in the validator.
> Creating a "System" content type breaks Umbraco

- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
The current delete confirmations for block list (content editing) and block list configuration (data type editing) aren't exactly formulated as questions:
This PR updates the confirmation dialog messages so they are actual questions:
And yes... I know. Hacktober. Translation PR's. Buuuuut I have already fulfilled my quota for Hacktober, so I swear I'm not up to anything dubious (well not with this PR anyway!).
> Formlulate the block list delete confirmation as a question

- src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
@nul800sebastiaan This PR fixes the issue where the search filter was not being displayed when used in the "template" context - Since the model is not immutable it's not enough to assume that the filter should be displayed or hidden if model.filter is true or false since it can also be undefined. Therefore it's now changed from `ng-if="model.filter"` to `ng-if="model.filter !== false` 👍 
**Before**
**After**
> Itempicker: Fix filter check

- src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
This PR change the style of listview settings button, so this is more consistent with edit/setting buttons in group builder on a document type.
> Change button style for listview settings

- src/Umbraco.Web.UI.Client/src/less/components/umb-badge.less
- src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
This PR add a badge in user state filter similar to log level filter. Furthermore I have also added icons in user group filter. However I haven't used `<umb-icon>` here at the moment since with the latest changes this seems to be a be slow and these icons are first loaded quite a while after the user group filter has been opened.
> Show badge in user state filter and icon in user group filter

- src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
- src/Umbraco.Core/Migrations/Upgrade/V_8_9_0/ExternalLoginTableUserData.cs
- src/Umbraco.Core/Umbraco.Core.csproj
While retargeting a migration for another open PR (https://github.com/umbraco/Umbraco-CMS/pull/8316), I noticed the `ExternalLoginTableUserData` migration was targeted to Umbraco 8.8.0, instead of 8.9.0.
This isn't an issue by itself, but might be confusing when debugging the current migration state and being on version 8.8.0 and not seeing the right state in the database (compared to the source code)...
> 8.9RC: Retarget ExternalLoginTableUserData migration to Umbraco 8.9.0

- src/Umbraco.Web/PropertyEditors/ValueConverters/ContentPickerValueConverter.cs
Prevent InvalidCastException being thrown when ContentPicker has picked a Udi. Trying to convert to an int will fail for Udis with an InvalidCastException.
Checks if the value starts with umb to determine if it is a udi, if Udi, don't try cast to int.
How to test?
Use a content picker on a document, pick a udi. InvalidCastException should not be thrown when the property converter runs
> Prevent InvalidCastException being thrown when ContentPicker has picked a Udi

- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
Added a Welsh back-office language file, it is based on and contains Welsh translations of all of the keys found in the _en.xml_ and _en_us.xml_ translation files.
This translation file was originally created for Umbraco 7, but I finally updated it to include all of the new translations found in Umbraco 8 and thought it was about time that I actually put it up for a PR! 😄
> Added a Welsh translations file

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
Fixes #8646 
If there's an existing issue for this PR then this fixes #8646
I added the noTemplate property to the model used for creating the document type.
To test:
Create a block list, add a block, add a new doctype for the block. Verify that no templates are being created for the new doctype.
> Prevents templates being created when adding DocTypes through the block list config

- src/Umbraco.Web.UI.Client/src/common/directives/components/html/umbcontrolgroup.directive.js
I have added the metadata required to the `umbControlGroup` directive so that the attributes available can be listed in the backoffice documentation.
I did my best to give an accurate description of the purpose for each attribute, but this was inferred from how they are used in the code itself. Perhaps someone can double-check my understanding is correct, and propose any better descriptions if anything is unclear.
> Added documentation for umbControlGroup directive

- src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
Another `umb-icon` from me. I have replaced the `<i>` with `umb-icon` in `umb-node-preview` . This is quite a sweeping change as the `umb-node-preview` is used in many many places. Would recommend testing the following
1) Info content apps in content, media, members
2) Icons in grid editor config
3) icons in content picker in content edit
4) icons for user groups in users section
> Replaced <i> with umb-icon in umb-node-preview

- src/Umbraco.Web.UI.Client/src/views/media/edit.html
For whatever reason the "Save" button on media items is of type "submit". This causes the editor to save automatically if you hit enter after loading the editor:
For content items, the "Save" button is of type "button", which prevents this behavior... so I have changed the "Save" button on media items to be of type "button" as well.
> Do not save media items when hitting enter

- src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
- src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
- src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
I enabled session by adding the session service and middleware. 
This is to replace the previous use of IRequiresSessionState since this is no longer a thing in net core
The way this is implemented now means that the session will be available everywhere HttpContext is, unfortunately, I was not able to find a way to enable/disable session for specific controllers. 
In regards to customizing session for users, this should still be possible by calling AddSession on services after using AddUmbraco, because the last call to AddSession is the one that's used. 
Setting session up to use redis, database or memory cache, should also be possible adding whatever implementation of IDistributedCache to the service collection before adding session I.E
```c#
services.AddUmbraco(); …
```
> Netcore: Enable session

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle-group.less
The changes in #8826 has unfortunately resulted in misaligned labels for toggle groups:
Also the checkbox label is no longer clickable - or rather, clicking it does not have any effect (because the label element swallows up the click event on the parent, which is supposed to be toggling the checkbox):
This PR removes the additional padding and margin on the checkbox label, and ensures that it doesn't steal click events from the parent element:
> Make toggle group labels clickable and aligned correctly

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9129
When server resets the value to a primative value (null or undefined, does not matter) we lose the reference between the BlockEditorModelObject and the Data Model of the Content. This update makes sure when resetting the value its bound on the model and that reference is parsed.
Read test notes on issue.
> 9129 keep model value reference after empty

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Members/members.js
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/templates.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Tour/backofficeTour.ts
- src/Umbraco.Tests.AcceptanceTest/package.json
I added the content with contentpicker test. 
I also did some tweaks to the existing tests, to make them more stable. 
I fetch the content node tree after refreshing content, this is just to wait for the content to appear after refreshing if we don't do this the tests will fail because it tries to click an item that does not exist yet, while doing so I also put in in a function since it's used in almost all test.
A very minor thing but I indented function calls to child builders, making it easier to see what belongs where
I also changed the content rollback test, we no longer expect the badges to be in a certain order since it's not deterministic in this version of the UI, I managed to get this result when doing rollback manually 
The first time it's Rollback -> Save
The other time it's …
> V8: stabilize cypress tests and add content with contentpicker test 

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Tests/Services/ContentServiceTests.cs
- src/Umbraco.Tests/Services/MediaServiceTests.cs
- src/Umbraco.Tests/Services/MemberServiceTests.cs
- src/Umbraco.Web/Search/ExamineComponent.cs
Fixes #9095 - caused by #8525 with changes here https://github.com/umbraco/Umbraco-CMS/pull/8525/files#diff-2ab7be5e592894a2e3dfac615d7a94a5ae6ab11e1948312fb515749caca04b79R12 because the ExamineComponent.MemberCacheRefresherUpdated event wasn't updated to handle the RefreshByPayload message type
Fixes #9093 - caused by #8525 with changes here https://github.com/umbraco/Umbraco-CMS/pull/8525/files#diff-0f4c2578706d75656978e4cccd48671380730283de0ec98f0d8e79ef7d7d0ef7R388. The problem was a change to the Member Repository that was not taking into account removed property values. The change was required because the previous way that content properties were persisted was not done atomically and was unsafe with high DB concurrency. This change was also required because a new member service …
> Fixes regression issue with property values being updated in content repositories

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html
Issue: https://github.com/umbraco/Umbraco-CMS/issues/9238
A simple fix by having the localization key point to the validation section (which is where the key is actually located instead of the default section).
How to check:
- Create a new data type 'Multi Url Picker' with a maximum.
- Add the data type to a page and check it out.
> 9238: Fixed invalid multi url picker label

- src/Umbraco.Examine/ContentIndexPopulator.cs
- src/Umbraco.Examine/IUmbracoContentIndex.cs
- src/Umbraco.Examine/IndexPopulator.cs
- src/Umbraco.Examine/UmbracoContentIndex.cs
Fixes issue that the non-published content index populator is executing for the ExternalIndex
As mentioned in https://github.com/umbraco/Umbraco-CMS/pull/9010 the index populator for non-published items will always execute for the ExternalIndex that has a validator to declare that it does not support published items.
This fixes that issue.
> Non-published content indexed in ExternalIndex

- src/Umbraco.Core/Configuration/Models/ImagingCacheSettings.cs
- src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/CoreXml/RenamedRootNavigatorTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Packaging/PackageExtractionTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HealthChecks/HealthCheckResultsTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/StylesheetBuilderTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Macros/MacroParserTests.cs
- Changes small things to ensure the tests are runnable on linux.. 
If tests passes on buildserver, we know the unit tests can be executed on both windows and linux
- The umbraco folder needs to be lowercase
- We can't force test results to be CRLF, but the line endings must be native
- Can't use hardcode directory separators + Line endings
> Netcore: Ensure unit tests are runnable on linux

- src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/8963
Makes the star(*) appear on mandatory fields of NC, as previously.
---
_This item has been added to our backlog [AB#9010](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9010)_
> updates CSS selector to match latest

- src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
Hi,
This PR fixes the issue mentioned in #8967 
When a backoffice user is deleted the notification is shown twice. This PR fixes it.
Poornima
> Fix - user delete shows notifications twice

- src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
If there's an existing issue for this PR then this fixes #8988
As described in #8988, the media editors tend to remove their associated files when enter is pressed elsewhere when editing media items:
Looks like this is caused by the accessibility changes in #6919 (approved by yours truly 🙈)... the `<button>` tags need to have `type="button"` to stop acting like a submit button. So this PR adds `type="button"` to those buttons.
Note that the issue fixed in #9019 makes this a tad hard to test, but if you look closely on this GIF, the issue *is* indeed fixed by this PR:
> Do not remove files from media editors when hitting enter

- src/Umbraco.Web.UI.Client/src/installer/steps/starterkit.html
Noticed that we also had an `<a>` tag without an `href` attribute in the installer process where one picks the starterkit. Converted to `<button>` with this PR 👍
> Installer: Starterkit - Convert <a> to <button>

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbbreadcrumbs.directive.js
#4637 # Prerequisites
Whilst creating tags for VS Code plugin (umbSense), the documentation on umb-breadcrumb is unclear at the API docs: https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbBreadcrumbs. The property marked as "Callback" is actually referenced as `on-open`. E.g. from the [mini list view](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html):
```
<umb-breadcrumbs
ng-if="breadcrumb && breadcrumb.length > 0"
ancestors="breadcrumb"
entity-type="content"
on-open="clickBreadcrumb(ancestor)">
</umb-breadcrumbs>
```
I have made the following changes to rectify this: 
- Reflect optional nature of the callback method in the functionality
- Show actual property name to reference in usage
> Update usage guidance for umb-breadcrumbs

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttonellipsis.directive.js
The documentation at https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbButtonEllipsis is unclear on the parameter optionality - I have updated the parameters to reflect whether they are required based on the functionality in the directive.
(this is for the work done on directive tags for umbSense: https://github.com/KevinJump/UmbSense/pull/41)
> Updated optional params on umb-button-ellipsis

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
Fixes #9176 
Can be tested by going to a color picker and using the edit buttons to edit the colors and labels.
> 9176: Fix editing labels and added functionality to edit colors

- src/Umbraco.Core/Persistence/Repositories/IRelationRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
- src/Umbraco.Core/Services/IRelationService.cs
- src/Umbraco.Core/Services/Implement/RelationService.cs
- src/Umbraco.Tests/Services/RelationServiceTests.cs
- src/Umbraco.Web.UI.Client/src/common/directives/components/references/umbtrackedreferences.component.js
- src/Umbraco.Web.UI.Client/src/common/resources/trackedreferences.resource.js
- src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web/Editors/TrackedReferencesController.cs
If there's an existing issue for this PR then this fixes #8699
With this PR you can now see if one of the underlying items (descendants) is being used in content. It doesn't show which content items yet, that is for a future PR.
To have good performance I needed to introduce a new repository and service method.
For testing the default starter kit can be used
1. Create a folder structure several levels deep in the media section. 
2. Upload some photo's in a sub folder
3. Link one of the photo's from content
4. On the top level folder check the info tab. It should indicate that one of the underlying items is in use.
1. Create a content structure several levels deep in the content section. 
2. Link content on the lowest level in another page.
3. On the top level content item of the newly …
> V8 - Show that underlying item is used on the info tab

- src/Umbraco.Core/Persistence/Repositories/IRedirectUrlRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RedirectUrlRepository.cs
- src/Umbraco.Core/Services/IRedirectUrlService.cs
- src/Umbraco.Core/Services/Implement/RedirectUrlService.cs
- src/Umbraco.Tests/Persistence/Repositories/RedirectUrlRepositoryTests.cs
- src/Umbraco.Tests/Services/RedirectUrlServiceTests.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/Routing/ContentFinderByRedirectUrl.cs
Prerequisites
[@ ] I have added steps to test this contribution in the description below
If there's an existing issue for this PR then this fixes #8568
Description
The issue #8568 describes how the RedirectUrl Content Finder doesn't take into account the culture of the request, so if multiple urls that are the same exist in different cultures it returns the first one.
This is addressed by passing in the identified culture from the request through to the RedirectUrlService and the RedirectUrlRepository. In addition more unit tests were added for the following classe:
* RedirectUrlRepository
* RedirectUrlService
> Add an override for GetMostRecentRedirectUrl to allow for culture

- src/Umbraco.Web.UI.Client/src/views/components/umb-confirm.html
If there's an existing issue for this PR then this fixes #8945
This PR enables `auto-focus` for confirm button (`OK` button) in `umb-confirm`.
This mainly enables autofocus for the contextual menu delete (see #8945), but also the Empty Recycle Bin confirmation.
> Enable auto-focus for confirm button in umb-confirm

- src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
- src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
If there's an existing issue for this PR then this fixes related, but not complete fix for #8673 and #8303 
This PR adds some automatic scaling of the preview iframe in the preview viewer, to make it fit the current viewport. This way you can preview your page as if it was shown in ie. a desktop sized browser window, but you don't need a window of the same size.
Modern browser dev tools (seen in Chrome, Edge and Firefox) does the same in responsive mode.
To test:
Open a node in the previewer, make sure your browser window is reasonably small. Change the viewmode in the bottom right corner, and notice how the iframe scales up and down when needed, to fit in your viewport. When in fullscreen, no scaling should be applied though.
> Scale the preview iframe to fit the viewport

- src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
I have created this PR to ensure the lang element is set based on the user's culture when the page is loaded.
This is important for screen readers, it ensures the correct pronunciation of the words.  This YouTube video demonstrates the importance of setting the language https://www.youtube.com/watch?v=QwOoU8T24UY#
> Accessibilty: set the html lang element

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/usergrouppicker/usergrouppicker.html
I have replaced the search markup with the `<umb-search-filter>` directive making maintaining the search box easier not re-implementing the same markup pattern multiple times.
**Usergroup search field after the change has been made**
> User group picker: Use <umb-search-filter> directive

- src/Umbraco.Web.UI.Client/src/less/rte.less
Fixes #9315
CSS update to the RTE toolbar to make it sticky. Now if the RTE area is larger than the viewport, as you scroll down the RTE toolbar will remain sticky to the content area meaning you don't have to scroll back up to access it.
To test, create an RTE in "classic" mode then enter a lot of content that forces it scroll beyond the view port height. When you scroll down, the RTE toolbar should now stick to the top of the viewport.
> Make RTE toolbar sticky

- src/Umbraco.Core/ServiceCollectionExtensions.cs
- src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
Following the MSDI refactor, I found a problem where a singleton class's field was null when it had previously been set (specifically the `UmbracoRequestLifetime.RequestStart` event).
Tracked it down to the fact that this class has two interfaces, and the recent changes meant two implementations were getting registered, when I think there should be just one.
The amend in this PR resolves the issue and restores the expected behaviour.
For reference, previously (before the MSDI refactor), we had this:
```
composition.RegisterMultipleUnique<IUmbracoRequestLifetime, IUmbracoRequestLifetimeManager, UmbracoRequestLifetime>();
```
> NetCore: Fixes registration issue

- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
Make ```<umb-block-card>``` work without blockConfigModel as we need that for pasting a list of items.
Fixes this issue:
test-notes:
Copy all items of a Block List Property Editor, go to "Add content" and go to the clipboard.
---
_This item has been added to our backlog [AB#9001](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9001)_
> Make blockConfigModel optional

- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
Use umb-outline for a more visible focus outline.
The default one was stuck behind some parts, so it was hard to see.
---
_This item has been added to our backlog [AB#9004](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9004)_
> use umb-outline for umb-block-card

- src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
When working with the `umbrequesthelper.downloadFile` in the backoffice it would be handy to be able to access the response object, e.g. to check values from the response headers. Currently this function doesn't return anything...
This change makes the function return the `response` object on success. The `error` promise already returns the `response` so it's a little unclear why `success` doesn't too...
This change also brings it inline with the other methods in this helper.
The impact is thankfully minimal and won't won't break any existing implementations as promise parameters are optional.
> Returning response from downloadFile promise

- src/Umbraco.Web/Editors/LogViewerController.cs
The access was a bit too broad before.
> Limit access to logviewer endpoints to people with access to the settings section

- src/Umbraco.Web/Trees/ApplicationTreeController.cs
As described in #9357 you get a cast error when trying to register multiple trees in the same section and tree group without using the `[Tree(...)]` attribute to declare it.
To create a tree without using the attribute you must inherit from `TreeControllerBase` and not `TreeController` - here the logic expects `TreeController` and so breaks in cases when not inheriting from it.
It transpires the cast causing the error is actually unnecessary, as the methods being accessed are part of `TreeControllerBase` and being inherited by `TreeController` anyway, so changing to cast to `TreeControllerBase` seems like a nice solution.
> Casting tree controllers to TreeControllerBase

- .github/workflows/codeql-analysis.yml
- .github/workflows/codeql-config.yml
Turns out this was failing on at least the `node_modules` directory, so we'll try to ignore directories that are not relevant for building a release.
> Get CodeQL to only scan the relevant directories

- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
Fixes #9209 
A regression caused by #9064 The tree views no longer show the green tick icon when you select an item.
The check icon was previously enabled/disabled by css (line 177 of `umb-tree.less`) which targeted `<i>`, but the icon now uses `<umb-icon>` so the CSS no longer targets it.
I've changed it so the icon is changed in the view if the node is selected rather than via CSS.
However I'm unsure if:
- This is the correct approach
- The icon needs to be green (it is on some views but isn't on others)
@MMasey @poornimanayar I would appreciate your input on this as I understand you have done alot of work on icons recently - thank you!
> Conditionally show check icon if umb-tree-item is selected

- src/Umbraco.Web.UI.Client/src/less/main.less
- src/Umbraco.Web.UI.Client/src/views/components/html/umb-control-group.html
- ✔ I have added steps to test this contribution in the description below
@bjarnef found this issue and we had a chat about whether it could be introduced by a former PR of mine but we figured out it was not but I of course got a bit curious to figure out what was going on and after a little digging it appears to be the use of `.controls-row` class that offsets the padding on the "Title" by 10 pixels. Removing the class appears to be fixing the issue.
Therefore I have simply removed this class and that seems to fix the issue - I have checked the view that appears when you right click on a content node and select "Do something else" and select "Permissions" and then choose a group to setup permissions for in the dropdown. I have checked it in the users section as well. Can't remember the …
> umb-control-group directive: Fix styling issue

- src/Umbraco.Web.UI.Docs/umb-docs.css
As highlighted by @abjerner in #9160 there's no styling for `<code>` blocks in the Umbraco backoffice docs styles. Well, there is, but it's only for method info.
This change makes sure all `<code>` blocks in the "content" section of a docs page are formatted correctly. I feel this is more future proof than specifically targeting which section of the page the block appears in.
I cleaned up some of the styles whilst I was at it too...
> Styling all code elements in backoffice UI docs

- src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
- src/Umbraco.Web/Editors/UsersController.cs
Mis-spelt "occurred" in the error messages that get thrown in the back office
This might seem trivial, but this error message bugs me everyyyyyy time!
> Fix mis-spelt "occurred"

- src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings-overlay.html
This PR add the `shortcut="esc"` to close button, so it is possible to close overlay via `esc` key.
> Allow to close list view settings overlay via esc shortcut

- src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/group.html
If there's an existing issue for this PR then this fixes #9036
Looks like #8739 was a tad too eager in showing confirmation dialogs. It resulted in somewhat cryptic dialogs when removing sections or granular permissions from a user group:
This PR ensures that we retain the confirmation dialog when removing users from groups, but avoid showing confirmation dialogs when removing sections or granular permissions:
> Do not show cryptic confirm dialog when editing group

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/membergrouppicker/membergrouppicker.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9299
See original issue for detailed info.
`editorService.close()` is being hit twice because it exists inside both if/else and outside the statements.
> Remove double editorService.close()

- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
Hello Umbraco World 👋
closes 9182
This PR removes a single line of css that hard-coded the position of the label. 
This made the text display over the icons if the text spanned multiple lines. 
Before Change:
After Change:
> Remove CSS: bottom offset in umb-grid.less

- src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
If there's an existing issue for this PR then this fixes #8922
As described in #8922, the Nested Content item icons have gone a bit askew:
This PR centers them again, and also increases the icon sizes to match those of Block Editor:
> Make Nested Content icons centered and same size as Block Editor

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigationitem.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation-item.html
If there's an existing issue for this PR then this fixes https://trello.com/c/pd2QnSjI/17-the-content-drop-down-menu-opens-automatically-when-tabbing
The drop down for 'Content' (within the 'Content' tab) opens when user is tabbing through. 
This behaviour differs from all other drop downs on the CMS (that remain closed until user opens).
I replaced the custom markup with the umb-dropdown directive, but also allowed the existing hover functionality to remain.
To test:
Open up a content node and tab from the name field over to the content tab. Tabbing again will take you to the next tab (Info) rather than entering the dropdown. Hit space/enter to open while the Content tab button is selected. Then tabbing will take you into the dropdown menu.
Hitting Esc or tabbing past the bottom item in …
> Accessibility (keyboard navigation): The 'Content' drop down menu opens automatically when tabbing

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
As described in #6089 a large-ish diff for the Grid (and also for any other prop editor that stores JSON data) will kill a browser tab if you try to roll back.
The suggestion there to have a look at `diffJson` was a good one and very easy to implement since we already detect items as being a json blob versus stored text. I tested this with 150 paragraphs of text from https://baconipsum.com/ and saved the node a few times. Trying to do a rollback definitely killed by browser tab. After this fix, selecting a version to roll back to is really fast.
This doesn't fix all of the problems, it is still slow when you have many words in a regular textarea/RTE/etc. So that's an improvement that could be made at a later stage by capping the amount of words to do a diff on or something else. I think …
> Fixes #6089 JsDiff.diffWords in Rollback freezes browser

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
If you attempt to remove all items of a Nested Content or Block Editor property (by use of the property actions), you're asked to confirm this. However, this is not the case when you do the same for a Media Picker:
This PR adds the same confirmation dialog to Media Picker:
> Add confirmation dialog to media picker "remove all entries" action

- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-results.html
In this PR I have fixed the following
- Converted `<a>` to `<button`
- Added english fallback for "no search result" localization
- Changed `<i>` to use `<umb-icon>` - Please not an extra icon directive has been added to display the green checkmark when an item is checked. Previously this was handled using CSS on the `<i>` tag
- Some minor styling issues
** Where to find it **
The directive is being used in more places but one of them is in the "Copy" dialog on a node when using the search box.
> umb-tree-search-results directive view fixes

- src/Umbraco.Web.UI.Client/src/views/components/tree/umbcontextdialog/umb-context-dialog.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
I have improved the accessibility of the context dialog overlay adding `role="dialog`, ´aria-labelledby´, `aria-describedby` and a description text + of course added keys in the languages files for `en` and `en_us`.
I would have loved to add the focus lock as well but in it's current state it's not quite ready yet - I will give it a try again once I've finished the #8522, which contain some changes that takes view changes into account. View changes are exactly the issue here - The current focus lock is not aware if something change state and becomes visible. But once it's fixed I'll give this another shot :-)
> ContextDialog: Accessibility improvements

- src/Umbraco.Web.UI.Client/src/less/forms.less
- src/Umbraco.Web.UI.Client/src/less/installer.less
There's an existing issue for this PR see https://github.com/umbraco/Umbraco-CMS/issues/8353
To reproduce the issue reduce the issue on the install screen width to less than 767px and form labels are placed on a new line, however the labels are still right aligned.
With this fix it sets them back to default:
> Issue 8353 - Fix of issue that caused small screens labels alignment

- src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
This PR fixes a few issues in help drawer:
- Ensure help drawer can be closed via `esc` key.
- Adding `rel="noopener"` to anchor elements with `target="_blank"` for security reasons.
> Help drawer adjustments

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
With this PR I have changes a `<div>` with an `ng-click` handler to a `<button>` instead and I fixed the semantics accordingly. I also added a proper fallback text to a localization element, which was missing.
**The changed area**
> Grid: Layoutconfig improvements

- src/Umbraco.Core/Logging/LoggingTaskExtension.cs
- src/Umbraco.Core/Runtime/MainDom.cs
- src/Umbraco.Core/Runtime/SqlMainDomLock.cs
- src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
- src/Umbraco.Web/PublishedCache/NuCache/SnapDictionary.cs
- src/Umbraco.Web/Scheduling/BackgroundTaskRunner.cs
- src/Umbraco.Web/Scheduling/TaskAndFactoryExtensions.cs
- src/Umbraco.Web/WebApi/HttpActionContextExtensions.cs
Ensure that TaskScheduler.Default is used anywhere that ContinueWith is used and adds more debug logging to MainDom operations.
ContinueWith should always have `TaskScheduler.Default` explicitly declared. There's a few instances in the codebase where this is not the case. It hasn't caused problems in the past that we know about but it is the safe thing to do. For more reading see https://blog.stephencleary.com/2013/10/continuewith-is-dangerous-too.html
This adds a little bit more debug logging to MainDom. This is for debugging purposes only because there's one known site where MainDom shuts down without the application being shutdown and without any SqlMainDomLock logging taking place which is truly odd. 
* Configure your site to use SqlMainDomLock
* Add this logging config to your …
> Ensure that TaskScheduler.Default is used anywhere that ContinueWith is used, adds more debug logging to MainDom operations

- src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
If there's an existing issue for this PR then this fixes N/A
What?
Change from using a list to using an array when we know the size of the array in advance.
Why?
Speed up publish content query and reduce memory use by reducing array allocations for PublishedContent properties.
How to test?
Existing tests pass.
> Speed up publish content query and reduce memory use by reducing array allocations for PublishedContent properties

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
- src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
- src/Umbraco.Web.UI.Client/src/views/components/member/umb-member-node-info.html
- src/Umbraco.Web.UI.Client/src/views/media/apps/content/content.html
- src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
If there's an existing issue for this PR then this fixes #9291 
The error is caused by multiple groups having the same label. I changed the loop to use `group.id` for tracking. I did a search to see if there were any other components using label for tracking and found `umb-tabbed-content` using it too.
To reproduce:
1) Set your backoffice language to Dutch - nl.
2) Go to Settings (Instellingen) -> Member types (Ledentypes)
3) Add another group called `Eigenschappen` and put a text field in it.
4) Create/Edit a member
> Track ng-repeat with id instead of label

- src/Umbraco.Web/UmbracoHelper.cs
47 of 123 (or roughly 40%) of the solution build warnings all originate from internal usages of `Obsolete` marked properties in `UmbracoHelper.cs`. 
Since the relevant services are already injected into `UmbracoHelper`, I figure there is no reason not to use them directly and thus get rid of those warnings. So I have done just that. 
There are no noticeable changes to test. But in order to validate the change, you can use this template (it assumes the content being rendered has a published and render-able child). If the template renders successfully, everything works 😄 
```cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
Layout = null;
}
<html>
<body>
<ul>
<li>What does Culture Dictionary think the current culture is? <b>@Umbraco.CultureDictionary.Culture</b></li>
<li>Does Membership …
```
> Replace obsolete usages with injected services in UmbracoHelper

- src/Umbraco.Web.UI.Client/gulp/tasks/test.js
- src/Umbraco.Web.UI.Client/gulpfile.js
This PR makes the JS Unit test server run when you run the dev npm script, in this way it becomes more clear if Unit Tests are broken.
---
_This item has been added to our backlog [AB#8663](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8663)_
> run JS unit test in development script

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8689
Make properties from Block settings available for the Block label on $settings.
**Test notes**
Use {{$settings.myprop}} in a label.
Test that the label does not fail for Blocks created before settings ElementType has been added for a Block.
— create a block with only Content-ElementType.
- create content of it.
- add Settings ElementType to your block (settings should have a property with alias "myProp")
- write a label like this. {{$settings.myProp}}
- view previously created content, and notice that no errors appear in the console.
Use {{$index}} in a label.
Test that the index is correct on init. When reordering and for nested Block Editors.
The index starts from 1 as opposed to a zero based index so that it is more editor …
> Make index, settings and layout props available for labels

- src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
If there's an existing issue for this PR then this fixes #8845
Property actions are usually used to edit the content of a property in one way or another... this is troublesome if said properties are culture invariant; you end up being able to edit the property in other languages than the default language:
This is not limited to the Media Picker only, it applies to any property editor with property actions (i.e. Nested Content, Block Editor etc.).
This PR removes the property actions for culture invariant properties outside of the default language:
> Hide property actions for culture invariant properties

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html
I noticed that that `ng-click` was being used on a `div` some places here so it's been changed to be using `<button>` elements instead and the child elements have been changed to be `<span>` elements since having block level elements as childs of `<button>` elements is invalid markup.
I've also added a `<p>` around some texts and added a fallback value, which was missing in the view as well.
I tried changing from `<i>` to `<umb-icon>` but there were some styling issues that requires a bit more effort to resolve properly. So that's for another PR some time by someone.
**What things look like after the changes and what I've been changing the markup for**
> Grid prevalues: Improve accessibility and semantics

- src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
Adds a check so ensure the converted treenode icon is not undefined before calling converted.startswith(.) which will throw.
This issue causes  the content/settings/media trees not to work. No way to fix the issue from the cms
> Bugfix: Add null check for null converted treenode icon so .startsWith does not throw

- src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
Added round corners on items in media-picker.
> added round corners in umb-media-grid for media-picker

- src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
This change adds max-width:100%; to the .umb-editor css-class. This is done to ensure that umb-editor in infinite editing stays inside the viewport-width. See medium sized editors.
Should be tested to see if this change affect other parts of the system where umb-editor is used.
> keep umb-editor inside viewport width

- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
+ danish translation  for entriesShort and entriesExceed
[Fixed invalid multi url picker label](https://github.com/umbraco/Umbraco-CMS/issues/9475)
> #9476 danish translations for addUpTo 

- src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
If there's an existing issue for this PR then this fixes #6960
As discussed in #6960, when attempting to open an external link in the same tab inside preview, a browser error is displayed. This is because the link is attempted to be opened inside the iframe, which will not be allowed for most external URLs.
This PR modifies all external links that did not have their target set already to open in the same browser window, outside the iframe. This is not 100% ideal UX, but as per the discussion in #6960, it's likely the best option for now.
- Place a link to an external page (without 'open in new tab' set). I used the About Us page of the Starter Kit.
- Preview the page and click the link. Verify that you do not get a browser error, but the link is opened instead.
I have also tested the …
> Make sure external links are not attempted to be opened inside preview iframe

- build/NuSpecs/UmbracoCms.Web.nuspec
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- Fix wrong version of `Smidge.Nuglify` in nuspec file
- Updated `Smidge` and  `Smidge.Nuglify` from build version of 3.2.0 to the official 3.2.0 on nuget
> NetCore: Fix wrong version of Smidge in nuspec + Updated to official 3.2.0

- src/Umbraco.Web/Editors/ContentController.cs
This fixes issue #8936.  The testing steps are specified there.
The fix was correcting defaultCulture from using the culture's display name to is ISO name.  The one consideration I had to look into was to make sure the one other place default culture was used would handle it correctly.  This was on line 703 of ContentController where it called CultureImpact.GetCultureForInvariantErrors.  However in my debugging, the other values passed in, which would have been used if not equal to the default culture, were also in the ISO name format, not the display name format, and so this change probably fixes another potential bug in that call.
The unit tests all passed locally, and when running through the test scenario from the issue above, I was able to verify that the comparison was between two …
> Get default culture comparable to the variant culture

- src/Umbraco.Web.UI.Client/src/common/directives/validation/showvalidationonsubmit.directive.js
This is a left-over bit from work on #8894. In fiddling with that issue, I found that the showValidationOnSubmit directive used `.show()` and `.hide()` to control element visibility. That's all good until we want to change the visibility of the validation messages using the `ng-show` or `ng-hide` directive in a view. `.show()` and `.hide()` set an inline style attribute, which has higher specificity than the class added by `ng-show` or `ng-hide` so it's not possible to control the element visibility outside the events in validation directive.
To fix that, I've removed `.show()` and `.hide()` in favour of toggling the `ng-hide` class name on the outermost element. End result is the same (display property is set to `none!important' but it's done via a class rather than the style attribute, …
> v8 - use ng-hide in validation directive

- src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
The query result will always be -1, as the result is the amount of rows affected, but that is not applicable in these create queries. This may cause confusion as devs may wonder why for example 'CreatedIndex' is -1. This also seemed to be the only place where we actually use the result of `database.Execute`.
If there's an existing issue for this PR then this fixes #7108
Logging these parameters leads to confusion, so let's remove them. Logging the name of the created indexes and keys requires some rework of the code and I'm not sure it's really needed at this point, as the SQL already contains the name if needed.
- Run the site on a clean database or without database
- Ensure the database is constructed correctly and the log entries do not contain the removed parameters
> Don't log query result to avoid confusion

- src/Umbraco.Core/Configuration/Models/UmbracoPluginSettings.cs
- src/Umbraco.Core/Constants-Configuration.cs
- src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
- src/Umbraco.Web.BackOffice/Plugins/UmbracoPluginPhysicalFileProvider.cs
- src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.UI.NetCore/Startup.cs
Adds support for reading static files from the `App_Plugins` folder, by introducing a new `UseStaticFiles` that reads from the `/App_Plugins` folder. To ensure we are not exposing any unintended files I added a AllowList for extensions. Default is 
```
".html", // markup
".css", // styles
".js", // scripts
".jpg", ".jpeg", ".gif", ".png", ".svg", // images
".eot", ".ttf", ".woff" // fonts
```
- Ensure static files can be read from the `App_Plugins` folder
- An easy way to do this, is to follow these guides to create a simple plugin
- https://our.umbraco.com/documentation/extending/Content-Apps/#creating-a-custom-content-app
- Ensure static files that is not allowed can't be read from the browser.
- E.g https://localhost:44331/App_Plugins/WordCounter/package.manifest if you followed the …
> Netcore: Read static files from app_plugins folder

- src/Umbraco.Web/Editors/PreviewController.cs
Fixes #9153 
This uses the .Cultures of the content node instead of always using all the languages on the website.
I tested it the following way:
1. Using the Umbraco starter kit.
2. Set the People document type to Varies by Culture.
3. Add another language to the website.
4. Add two domains to the root node.
5. Preview the people node and see 2 languages listed in preview modes.
6. Preview the products node and see that no languages are shown.
Now, this will work most of the time, but there is one situation where this doesn't work. If I make the People document Varies by Culture then you'll also have 2 versions of the children under there (Like Matt Brailsford), but those 2 languages will not show up in the language selector for the preview version. This is because .Cultures only returns …
> 9153: Only show the cultures of the node in preview

- src/Umbraco.Web/Security/MembershipHelper.cs
The method as it currently stands will only return true for a path that is protected _and_ the member has access. However, it should return true for paths which are also unprotected.
To test, call the method passing in paths of nodes which are unprotected. It should return false for all of these paths.
There are 3 possible scenarios that this method should deal with:
1. Node is unprotected
2. Node is protected and member does not have access
3. Node is protected and member does have access
At the moment the code only satisfies options 2 and 3.
> Change to MemberHasAccess to return true for unprotected paths.

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8359.
Because the `NodeObjectTypeId` of the current implementing repository (`DocumentRepository`, `MediaRepository` and `MemberRepository`) ended up in the SQL template of the base class/method `ContentRepositoryBase.GetNewChildSortOrder()`, the sort order was only correctly returned for the repository that did the first database query (as that cached the SQL template).
This PR moves the `NodeObjectTypeId` to an SQL parameter and removes the `first` parameter from the SQL query (as that was also incorrectly cached in the template). This ensures the sort order is correctly retrieved from the database for all repositories and if none are found, the correct first sort order/number is …
> Fix SQL parameters in GetNewChildSortOrder

- src/Umbraco.Web.UI/Views/Partials/Grid/Editors/TextString.cshtml
ReplaceLineBreaksForHtml is deprecated and the alternative ReplaceLineBreaks includes HtmlEncode.
This update will remove an error in Visual Studio.
> Remove deprecated ReplaceLineBreaksForHtml

- .gitattributes
- build/azure-pipelines.yml
- src/Umbraco.Infrastructure/Persistence/LocalDb.cs
- src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
- src/Umbraco.Tests.Integration/GlobalSetupTeardown.cs
- src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
- src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/ITestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/IntegrationTestComposer.cs
- src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/SqlDeveloperTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/TestDatabaseFactory.cs
- src/Umbraco.Tests.Integration/Testing/TestDbMeta.cs
- src/Umbraco.Tests.Integration/Testing/TestUmbracoDatabaseFactoryProvider.cs
- src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/PartialViewRepositoryTests.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/ScriptRepositoryTest.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/StylesheetRepositoryTest.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.resx
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Tests/TestHelpers/TestWithDatabaseBase.cs
Off the back of the discussions on #9452
@bergmania It aint pretty, it aint fast but at least it works on Linux.
Wouldn't take much to fit this into the CI build pipeline (perhaps the yaml one in #9459)
```bash
$ cd src/Umbraco.Tests.Integration
$ export SA_PASSWORD=Foobar123! # Must meet password strength requirements
$ export UmbracoIntegrationTestConnectionString="Server=localhost,1433;User Id=sa;Password=$SA_PASSWORD;"
$ docker run \
-e 'ACCEPT_EULA=Y' \
-e "SA_PASSWORD=$SA_PASSWORD" \
-e 'MSSQL_PID=Developer' \
-p 1433:1433 \
-d \
mcr.microsoft.com/mssql/server:2017-latest-ubuntu
$ dotnet test
```
> Netcore: Enable running integrations tests on Linux

- src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9286
See original issue for full details. The buttons work again when the type is set to "button", which is the default (as shown below) so the types in the PR can be safely removed.
https://github.com/umbraco/Umbraco-CMS/blob/e9e8a0354ddb36d12ebdecddf0569132dc96f4be/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js#L128
> Fix save buttons not working when using non-live models builder

- src/Umbraco.Web.UI.Client/src/less/application/grid.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8950
This PR a probably a temporary workaround, but it would be great to investigate further how to reset the inline left position on `contentwrapper`, when using the vertical size handle to change size of navigation panel and afterwards switch to another section without trees like packages, users, forms, etc.
It does seems there is still a tree in background but this is hidden here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/application/grid.less#L180
For now the workaround in this PR seems to do the trick, where the left position with `!important` gets a higher priority than the inline left position.
> Ensure content wrapper is positioned to left in section without tree

- src/Umbraco.Web/Scheduling/RecurringTaskBase.cs
As discussed in issue #9172 it is useful for recurring task to be able to repeat them longer than int milliseconds allows. This pull request adds an overloaded method for the constructor and changes the underlying property. This should be safe since Timer has a overloaded constructor aswell that accepts a long.
> Add overloaded method for RecurringTaskBase

- src/Umbraco.Core/Constants-SqlTemplates.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
If there's an existing issue for this PR then this fixes N/A
What?
Improve query for Delete relationship by parent.
Why?
Faster deletion of relationships = reduced time to publish.
How to test?
Existing tests pass. Existing relationships on existing content are removed when the content is saved.
Execution time should be reduced on sql server/ sql azure
> Speed up deleting relationship by parent. (Speeds up publishing/ saving)

- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/packages/edit.html
At the moment package actions input in packages section is a simple textarea. However since package actions at the moment is in xml format, is would be great to use the xml mode in ace editor.
https://our.umbraco.com/documentation/Extending/Packages/Package-Actions/
> Use ace xml mode for package actions

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
This PR replaces the old search markup using the `<umb-search-filter>` directive keeping things DRY etc. 😃 
**What it looks like after the change**
> Mediapicker: Use <umb-search-filter>

- src/Umbraco.Web.UI.Client/src/views/media/edit.html
If there's an existing issue for this PR then this fixes #9600 
Per the discussion on #9600, changing the button type broke the click event (since there's no handler defined for the button, and changing from submit means no more default form submit action). This change reverts the button type back to `submit`
This does mean the issue raised in #9019 is also reverted, but we can find a more appropriate way to fix.
> Reverts button type change in media edit

- src/Umbraco.Core/Exceptions/UnattendedInstallException.cs
- src/Umbraco.Core/Migrations/Install/DatabaseBuilder.cs
- src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
- src/Umbraco.Core/Migrations/Install/DatabaseSchemaResult.cs
- src/Umbraco.Core/Persistence/UmbracoDatabaseExtensions.cs
- src/Umbraco.Core/Runtime/CoreRuntime.cs
- src/Umbraco.Core/Runtime/SqlMainDomLock.cs
- src/Umbraco.Core/RuntimeOptions.cs
- src/Umbraco.Core/RuntimeState.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/Runtimes/CoreRuntimeTests.cs
- src/Umbraco.Tests/Runtimes/StandaloneTests.cs
- src/Umbraco.Web/Install/InstallHelper.cs
- src/Umbraco.Web/Install/InstallSteps/NewInstallStep.cs
- src/Umbraco.Web/UmbracoApplication.cs
To enable unattended install the `Umbraco.Core.ConfigurationStatus` app setting needs to have the current version and the `umbracoDbDSN` connection string needs to be configured. Then on boot we'll check if the database is empty (has no tables) and if it is, the database schema and default data will be created.
The unattended install can be disabled by adding an app setting `Umbraco.Core.RuntimeState.InstallUnattended` with the value `false`. Umbraco will then fail to boot if the version and connection string is present but the database is empty.
Note: You will not be able to login to Umbraco since no password has been set for the default user, you either need to have an external login provider configured or setting a password in some other way.
---
_This item has been added to our …
> Add support for unattended installs

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
- src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
This should fix the bug where if you allowed varying culture in a composition and property field, that property field would be lost in any content using the property type. 
The underlying issue was that when we were checking for a change in variation we only looked at the previous state of the property type, however, when you're using it in an element type, the element type and property type can allow variation, while the document type you're using it in as a composition does not allow it. When you later allow variation in you document type the property type will already allow variation (because it's allowed in the element type), and therefore we did not copy the property data to a new column that has a language ID associated with it, causing this bug.
We now also check the source …
> V8: Fix bug where allowing culture variation would delete content from element types #7471

- src/Umbraco.Core/Collections/EventClearingObservableCollection.cs
- src/Umbraco.Core/Collections/ObservableDictionary.cs
- src/Umbraco.Core/Models/Content.cs
- src/Umbraco.Core/Models/ContentBase.cs
- src/Umbraco.Core/Models/ContentCultureInfosCollection.cs
- src/Umbraco.Core/Models/ContentScheduleCollection.cs
- src/Umbraco.Core/Models/ContentTypeBase.cs
- src/Umbraco.Core/Models/Identity/BackOfficeIdentityUser.cs
- src/Umbraco.Core/Models/Media.cs
- src/Umbraco.Core/Models/PropertyCollection.cs
- src/Umbraco.Core/Models/PropertyGroup.cs
- src/Umbraco.Core/Models/PropertyGroupCollection.cs
- src/Umbraco.Core/Models/PropertyTypeCollection.cs
- src/Umbraco.Core/Models/PublicAccessEntry.cs
- src/Umbraco.Core/Umbraco.Core.csproj
Resolves #9348 
There was a memory leak with PublicAccessEntry during even unassignment which was not clearing the correct handler.
This goes a step further and adds a new ClearCollectionChangedEvents method for all observable collections used in umbraco
which allows fully clearing ALL event handlers instead of having to track specific ones. This will ensure there are no
unintended memory leaks in case end-users have assigned event handlers to the collection changed event which would
not be unassigned during deep cloning. This is much safer.
This memory leak will be present in all Umbraco 8.x versions if there is any public access assigned. The more public access entries configured (i.e. the more nodes that have explicit public access settings applied) the faster the leak.
There is still …
> Fixes a memory leak caused by deep cloning

- src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
The fix changes the search term model from being a primitive to being part of an object. That way the double databinding works again.
How to test:
- Open the "Allowed Child Nodes"-picker on a Document Type
- Make sure you can filter the document types
Fixes #9394
> fixes #9394 "Allowed child nodes" picker filter not working in v8.9.1 

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
Check if node.urls is null and set scope.currentUrls to null and return
Related to issue #7215
When setting node urls to null using EditorModelEventManager.SendingContentModel += (sender, e) => e.Model.Urls = null; then urls box is shown if the node has variants. A check is now added to set scope.currentUrls to null same as for Elements.
To test create a component with the above-mentioned code and open a content node that has variants. The urls box should be hidden.
> Check if urls is null

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
I noticed we have a few references using jQuery trim method `$.trim(string)`, but there is no need to use this in modern browsers, where we can just use vanilla `trim()` method, which already is use most places.
http://youmightnotneedjquery.com/#trim
> Replace jQuery trim() using vanilla JS

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-checkbox-list.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
I have made a couple of updates with the PR to make sure that the following functionality works as expected:
- Disable checkboxes while loading a composition
- Disable and fade the doc types which are not allowed to be added
- Highlight the doc types that is selected
How to test:
1. Open an Umbraco with The Starter Kit installed
2. Create a new doctype
3. Add the Home doc type as a composition
4. Make sure you can't select the Product and Content Base doc types
5. Select any other doc type
6. Make sure the checkmark is still in the checkbox for both Home and the new doc type
7. Make sure you can still deselect both Home and the new doc type
8. Make sure you can't select or deselect any doc types while the overlay is loading
I have also moved the loading indicator. It is now next to the …
> V8/bug/9432: Backoffice UI - checkboxes on doctype compositions uncheck after selecting an item

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.html
This PR fixes a minor issue with xpath help button, which didn't do anything. Now it act as a simple toggle button instead 🔛
> MNTP xpath help button doesn't do anything

- src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9541
This PR fixes some styling issues with search icon inside search filter after the `<umb-search-filter>` component has been introduced and changed to `<umb-icon>` inside search filter component, where the `icon-search` was removed. I have kept to old class so it still looks nice if packages used the old markup.
It seems a bit unnecessary to have the `w-100` class here
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less#L6-L8 since we already have the utility class here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/utilities/_width.less#L24
but removing this + the `html` …
> Fix styling of search icon in search filter

- src/Umbraco.Core/Runtime/CoreRuntime.cs
- src/Umbraco.Core/RuntimeOptions.cs
- src/Umbraco.Core/RuntimeState.cs
- src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html
- src/Umbraco.Web/Composing/ModuleInjector.cs
- src/Umbraco.Web/UmbracoApplication.cs
- src/Umbraco.Web/UmbracoApplicationBase.cs
- src/Umbraco.Web/UmbracoInjectedModule.cs
There are two parts to this PR.
The first part is unattended upgrades, it's an opt-in feature and can be enabled by adding an app setting `Umbraco.Core.RuntimeState.UpgradeUnattended=true`.
In addition to the above setting the `Umbraco.Core.ConfigurationStatus` app setting must match the assembly version before unattended upgrades are run.
If the conditions are met, the Runtime level will be `Run` instead of `Upgrade`, this allows us to do run the migrations and continue with the normal boot when the migrations succeed without requiring to restart the application. 
The upgrade is run after Composers but before Components. This is because the migrations requires services that are registered in Composers and Components requires that Umbraco (and the database) is ready.
To test the …
> Add support for unattended upgrades (and custom boot failed error page)

- src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9665
I noticed in users section some icons were missing 🙈 
I figured out that I removed the icon name from the class here, because I thought it wasn't necessary:
https://github.com/umbraco/Umbraco-CMS/commit/a9a4b0894a626adaea407f3a2bab4a6bca77e5f6#diff-6a8c6488e5f6832a8854541a572ad9893f004e32733a52fe2591fec34a0344deL3
Now it works again!
Mostly you won't notice in core, because we have SVG icons for most of the old font icon classes. But currently it IS necessary currently, when the icon isn't available as SVG icon: https://github.com/umbraco/Umbraco-CMS/pull/9255
At least until we find a better way to handle this and since many packages are using `<umb-node-preview>` component and …
> Add back icon name in class attribute to work again with font icons

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9683
It seems `localizationService` is used in controller of umbRadioButton component, which was added in this PR https://github.com/umbraco/Umbraco-CMS/pull/6797, but wasn't injected like in umbCheckbox component.
> Inject missing localization service

- src/Umbraco.Web.UI.Client/src/common/services/angularhelper.service.js
This PR fixes the issue where the browser crashes when validating complex nested content and block list editors.
How to test:
- Follow guide from issue #9360 to set up nested content
- Make sure validation messages are shown and updated correctly for all nested content levels.
- Make sure you can nest "nested content" more than 3 levels.
fixes #9360 
---
_This item has been added to our backlog [AB#10061](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10061)_
> Fixes: 9360: Nested validation freezes browser

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautofocus.directive.js
In order to still accept an empty attribute value for the directive umb-auto-focus, I have removed the if-sentence. Meaning that we will always observe the value. Basicly Enabling the auto-focus when it's not explicitly set to either: "false", false or 0.
Test-notes:
Before this fix, the Document Type Editor didn't focus on the Name input.
Neither for when creating a new property group and again not when creating a new property.
This has been fixed with this issue, but I'm not sure if this ruins other expected behavior, not from my understanding, but please test concerns.
> Makes #9004 backwards compatible

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9341
When new content is created and saved with errors, it's still begin saved and therefore it's not new anymore and future saves should be changes of this. Therefore it's important that ID, Key, and other identifiers of this new content are parsed on. This is done by the rebindCallback and therefor we should call it despite validation issues.
I do have concerns: we have several Property Editors that react when the Content Model is updated, I hope these will still work as intended, our test focus should be around this topic.
> Call rebindCallback on errors as well

- src/Umbraco.Web.UI.Client/src/less/components/card.less
I have updated the CSS for the item picker. It now supports items with long titles. With the updated styles the picker now looks like this:
We use it in a couple of places so we need to make sure that these still work/look as expected.
Where and how to test:
- Add some doc types with long titles
- Add some data types with long titles
- Make sure adding "Allowed child nodes", "properties", and templates to a Doc Type still looks correct
- Make sure adding and copying nested content items still looks correct.
- Make sure adding questions to a form still looks correct.
fixes: #9564
> fixes: #9564: Infinite Editing, document type template list - fonts are oversized and truncated

- src/Umbraco.Web/Mvc/EnsurePublishedContentRequestAttribute.cs
If there's an existing issue for this PR then this fixes NA
Minor optimisation by passing int instead of int? to Umbraco.Content. 
Pass int to Umbraco.Content instead of int? given we know _contentId has value.
> Minor optimisation by passing int instead of int? to Umbraco.Content()

- src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
What?
Optimized Count for the remaining QueryPaged calls in order to speed up paging in the database over content and media. Avoids unnecessary joins and selects.
Why?
Reduce database utilisation, speed up boot times.
How to test?
Existing tests pass.
> Optimize content and media count queries when paging

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Events.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/Events/EventAggregator.Notifications.cs
- src/Umbraco.Core/Events/EventAggregator.cs
- src/Umbraco.Core/Events/IEventAggregator.cs
- src/Umbraco.Core/Events/INotificationHandler.cs
- src/Umbraco.Core/Runtime/AppPluginsManifestWatcherNotificationHandler.cs
- src/Umbraco.Core/Runtime/EssentialDirectoryCreator.cs
- src/Umbraco.Infrastructure/Cache/DatabaseServerMessengerNotificationHandler.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Events/EventAggregatorTests.cs
- src/Umbraco.Web.Common/Profiler/InitializeWebProfiling.cs
- Added support for sync notification handlers in the `EventAggregator`
- Updated async handlers that was not using the async parts to be sync.
- Everything should work as before. E.g Set a breakpoint in one of the sync handlers and see it breaks as expected
> Netcore: Add support for sync notification handlers in event aggregator

- src/Umbraco.Web/PublishedCache/NuCache/DataSource/LazyCompressedString.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/SerializerBase.cs
What?
Support serializing more primitives to nucache
Why?
More efficient to serialize.
> Support more primitives in nucache

- src/Umbraco.Web.UI.Client/src/less/main.less
- src/Umbraco.Web.UI.Client/src/views/languages/overview.html
Hi,
I have replaced `<i>` with an `umb-icon` in the languages overview screen
Poornima
> Replaced <i> with umb-icon directive in languages overview

- src/Umbraco.Web/Trees/ContentTreeController.cs
- src/Umbraco.Web/Trees/MediaTreeController.cs
The Actions menu/dropdown in Content and Media contains a Sort link. It should end with an ellipsis ... because it opens a dialog just like the other items, like Move, Copy, Permissions.
To reproduce:
- Open the Content section
- Right-click on a content item and notice that Sort ends with an ellipsis ...
- Open the content item and click on the Actions dropdown in the top-right and notice that Sort ends with an ellipsis ...
- Reproduce these same steps in the Media section.
> Add ellipsis to the Sort action in Content and Media

- src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
When using a laptop width a viewport size on 1280 × 720 px the sidebar in e.g. content and media is moved below the main content. This is because the main content is set to a minimum width on 500px where the sidebar flow under the main content.
In packages section this in fine, because the navigation area is not shown here, but in content and media I think it would be great to adjust this a bit, so the sidebar is shown on right with the default width of navigation area on 360 px on since 1280px is a pretty standard screen width.
**Before**
**After**
> Adjust minimum width of main content

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
When creating a new content new there is no versions yet, so I think we should also hide the rollback button in this case as there is no versions to rollback to anyway.
> Hide rollback button for content that hasn't been created yet

- src/Umbraco.Core/DependencyInjection/ServiceProviderExtensions.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Events.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/DependencyInjection/UniqueServiceDescriptor.cs
- src/Umbraco.Core/Models/PublishedContent/PublishedModelFactory.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.DistributedCache.cs
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.ModelsBuilder.Embedded/Building/ModelsGenerator.cs
- src/Umbraco.ModelsBuilder.Embedded/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
- src/Umbraco.ModelsBuilder.Embedded/ModelsBuilderNotificationHandler.cs
- src/Umbraco.ModelsBuilder.Embedded/ModelsGenerationError.cs
- src/Umbraco.ModelsBuilder.Embedded/OutOfDateModelsStatus.cs
- src/Umbraco.ModelsBuilder.Embedded/UmbracoServices.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ModelBinders/ContentModelBinderTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Views/UmbracoViewPageTests.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web.Common/Events/UmbracoRequestEnd.cs
- src/Umbraco.Web.Common/ModelBinders/ContentModelBinder.cs
- src/Umbraco.Web.Common/ModelBinders/ModelBindingError.cs
- src/Umbraco.Web.UI.NetCore/Startup.cs
- src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
- src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
- src/Umbraco.Web/Umbraco.Web.csproj
Just a follow up PR to #9672 
* We always must have a default PublishedModelFactory registered since that is required for Umbraco to operate. Previously this was only being registered in the MB extensions which isn't right. Now the default is always registered and the MB ext replaces it if MB is enabled (not required for the back office)
* Ensures the embedded models builder is added when adding the website
* Adds some code to detect if AddModelsBuilder or AddDistributedCache are called more than once and if so it just ignores the additional calls.
* Makes the model binding error an event aggregator notification
* streamlines the htmlagilitypack dependency
* other minor cleanup
> Cleanup some of the MB changes for netcore

- src/Umbraco.Web.UI.Client/src/common/services/search.service.js
We found out that when the searchbox in the linkpicker is used, the URL of a page is not being shown anymore since Umbraco 8.7 and later. This is because of the searchResultFormatter wasn't applied correct.
Fixes #9737
> Fix for applying searchResultFormatter on found searchresults

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
Noticed the history box on the info app doesn't have a label - looks like there were potentially conflicts in a previous merge and the wrong changes were kept. Changes here restore the label and tidy up a clunky bit of JS to use destructuring assignment rather than accessing each array index.
History label has been missing since at least 8.8, can't see any existing issue reporting it 😃
> fix history box label, destructure localization response

- src/Umbraco.Core/Configuration/GlobalSettings.cs
- src/Umbraco.Core/Configuration/IGlobalSettings.cs
- src/Umbraco.Core/Constants-AppSettings.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
- src/Umbraco.Tests/TestHelpers/SettingsForTests.cs
When acquiring a SQL write lock, we currently have hardcoded this to 1.8 seconds (1800ms). This has been the case since version 8.4.0 - https://github.com/umbraco/Umbraco-CMS/pull/6688
In some cases, people seem to be getting the error `Lock request time out period exceeded.`. From what I gather from Shannon this indicates the followin:
> Has to do with distributed locks when writing/reading from the database at the same time as another thread/process. This means that while something else is holding a write lock, something else is waiting for the readlock and it cannot acquire it because it waited too long. Normally do to too many write locks trying to be used or queries executing slowly.
From what I understand from conversations at HQ, the value of 1800ms is rather arbitrary and there's …
> Add the ability to change the SQL Write Lock TimeOut

- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-results.html
Inside view of `<umb-tree-search-results>` component I noticed some unnecessary use of `ng-if`. Instead the classes can be added using inline conditional statements.
Furthermore after the link in the result item has been changed to a `<button>` element, it no longer used the full width of the container.
This is shown in eg. Move dialog when filtering, where the `<umb-tree-search-results>` component is used the list the result items.
> Update icons in umb-tree-search-results component

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
After this fix(https://github.com/umbraco/Umbraco-CMS/pull/9690) I sometimes get JS error for `err` being undefined.
This PR add a check for that.
To reproduce: make a DocType with Mandatory Media Picker, try to save without a media picked.
> Add Check for ´err´

- src/Umbraco.Web.UI.Client/src/common/services/formhelper.service.js
As I was getting this error;
I stumbled upon this code which is a bit tricky as it's using some JQuery and some Native code. Most of the code is using the jQuery find(), which always returns a jQuery collection. But the last part is using native find() of an Array, which will return undefined if nothing is found.
Therefor i have changed this.
> Stop using .length !== 0 when its not jQuery

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbpagination.directive.js
I noticed `onChange` function is used several placed, but not documented.
Furthermore inside `goToPage` it has double conditional check of `scope.onChange`.
It seems the `onChange` function wasn't originally added https://github.com/umbraco/Umbraco-CMS/commit/46826ad5900528858ff1ee7b51fc0c81fec63b19 on some places in core it use `on-change` while other places in use `on-go-to-page`.
> Document onChange in umbPagination

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
This PR replace the icon `icon-check` using `<i>` element with `<umb-icon>` in tree, where `enablecheckboxes` is used, e.g. in Move dialog.
> Use umb-icon component in tree item

- src/Umbraco.Core/Constants-Icons.cs
- src/Umbraco.Web/Trees/DataTypeTreeController.cs
- src/Umbraco.Web/Trees/DictionaryTreeController.cs
- src/Umbraco.Web/Trees/LanguageTreeController.cs
- src/Umbraco.Web/Trees/LogViewerTreeController.cs
- src/Umbraco.Web/Trees/PackagesTreeController.cs
Most trees was using icons from a constants static class, so I have updated this with more icons for tree nodes. Especially a constant for the generic `icon-folder` folder icon would be useful and since more areas in backoffice allow creating folders in tree.
> Add more constants for tree icons

- src/Umbraco.Core/HealthChecks/Checks/Security/BaseHttpHeaderCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/ClickJackingCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/ExcessiveHeadersCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/HstsCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/NoSniffCheck.cs
- src/Umbraco.Core/HealthChecks/Checks/Security/XssProtectionCheck.cs
- src/Umbraco.Core/HealthChecks/NotificationMethods/EmailNotificationMethod.cs
- src/Umbraco.Core/Hosting/IHostingEnvironment.cs
- src/Umbraco.Core/Web/IRequestAccessor.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComponent.cs
- src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
- src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
- src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
- src/Umbraco.Tests.Integration/Implementations/TestHostingEnvironment.cs
- src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UriExtensionsTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/KeepAliveTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTaskTests.cs
- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
- src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
- src/Umbraco.Web/AspNet/AspNetHostingEnvironment.cs
Fix issues with the current ApplicationUrl.
- Now it is available on IHostingEnvironment
- Now it is set in UmbracoRequestMiddelware
> Netcore: Fix missing application url

- src/Umbraco.Core/PropertyEditors/BlockListConfiguration.cs
- src/Umbraco.Web.Common/Extensions/BlockListTemplateExtensions.cs
Validation didn't work for the Block List Editor, because the NumberRange missed a DataContract attribute, so I've added that.
Blick List Editor couldn't render either because the GetBlockListHtml extensions were made on HtmlHelper instead of IHtmlHelper, so I added that as well.
> Netcore: Fix block list bugs

- src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
- src/Umbraco.Web.UI.Client/src/less/main.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/overlays/mediacropdetails.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/overlays/mediacropdetails.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
If there's an existing issue for this PR then this fixes #5596 
This PR replaces the stale one in #5607 (which I will close)
Changes here separate the alt text and caption into distinct values - previously the text set as alt text was stored as the caption, which doesn't make sense. To make this work, I've added two buttons to the grid media view, one to change the existing image, one to edit the existing image. 
Previously clicking the existing image opened the media picker overlay, which then opened a nested overlay to edit the details. That wasn't the nicest UX as closing the details overlay then returned to the picker, which is unrelated to the action the user had taken. Separating the two actions makes it clear which action will be triggered, and by adding buttons introduces text …
> 5596 allow editing alt text in grid

- src/Umbraco.Web/Logging/WebProfiler.cs
- src/Umbraco.Web/Logging/WebProfilerProvider.cs
Mini profiler was not profiling Umbraco Content API endpoints in the back office because mini profiler has a default ignore path of `/content/` and this path is applied with a 'Contains' check. This means that all requests to get/post content in the back office was not profiled.
This fixes it and you can test by using mini profiler with `/umbraco?umbdebug=true` and seeing that things like /umbraco/backoffice/UmbracoApi/Content/PostSave are profiled. You can also see all latest sessions profiled by going to `/mini-profiler-resources/results-index`
> Fix mini profiler so that it actually profiles the Content APIs in the back office

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html
It's inconvenient and not intuitive that the click area of the remove button laps over the label of settings and styles in the Grid Layout property editor. Simply as an editor may remove the style/setting by accident by clicking the label – especially since there isn't an undo option.
Known issue: Linebreak of long text labels doesn't appear pretty, but this is cosmetic and can be fixed.
Before:
After:
> Separate remove button and label for settings and styles in Grid Layout

- src/Umbraco.Infrastructure/Routing/RedirectTrackingComponent.cs
- src/Umbraco.Web.BackOffice/Controllers/RedirectUrlManagementController.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9813
- The values of `WebRoutingSettings` was cache due to the injection as `IOptions<WebRoutingSettings>` and not `IOptionsMonitor<WebRoutingSettings>`
- In the method that updates the configuration value, we need to wait the configuration delay time, before we return. Otherwise, the old value will still be read. I couldn't find any way to the set real delay time, so I used the default 250ms and added TODO.
> Netcore bugfix: DisableRedirectUrlTrackingValue was cached

- src/Umbraco.Web.UI.Client/src/less/components/umb-content-grid.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9755
Changed grid view labels and values to display: inline instead of display: inline-block to fix weird line break.
This is how it looked like with display: inline-block
And this is how it looks like with display: inline
This can be tested with any grid list view.
> Changed grid view labels and values to display: inline

- src/Umbraco.Web/Routing/PublishedRouter.cs
- src/Umbraco.Web/Routing/UrlProviderExtensions.cs
This fixes the logging done with PublishedRouter where it was always reporting "no document was found" for every request. This was because it was resolving the HasPublishedContent flag before the finders were even executed. Now it logs correctly and also adds a much nicer verbose debug log to help with debugging.
Have also added a log output for when `DetectCollision` fails - which is used in a couple places but namely this is used when showing the URL in the back office for a content item. It will run the inbound routing for that item to see if it can be routed to. If this fails we will get the "This document is published but its url cannot be routed" error. This now adds a warning to the log for when that occurs when "IgnorePublishedContentCollisions" is false (this is always false …
> Fixes logging issue with Published Router and adds logging for Collision Detection

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
- src/Umbraco.Web.UI.Client/src/utilities.js
I noticed this PR https://github.com/umbraco/Umbraco-CMS/pull/8213 introduced a private method `isEmptyOrSpaces()` which use `trim` as property instead of `trim()` as a method.
I also renamed the function to `isNullOrWhitespace()`.
I considered adding this as a `String` prototype extension in [Extensions.js](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/lib/umbraco/Extensions.js), but is seems to throw an error if called as `str.isNullOrWhitespace()` and `str` is `null`.
For now I have omitted this, but it could be useful as we use check for `null`, `undefined` and empty string in many part of the code.
```
if (!String.prototype.isNullOrEmpty) {
/** isNullOrEmpty extension method for string*/
String.prototype.isNullOrEmpty = function () {
var s = this; …
```
> Use trim method as trim isn't a property

- src/Umbraco.Web.UI.Client/src/less/forms.less
- src/Umbraco.Web.UI.Client/src/views/datatypes/edit.html
I noticed the properties wasn't aligned in "General" box under datatypes. It is a similar issue as this for member groups: https://github.com/umbraco/Umbraco-CMS/issues/9466
**Before**
**After**
> Align datatype sidebar box properties

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
- src/Umbraco.Web.UI.Client/src/views/content/recyclebin.html
- src/Umbraco.Web.UI.Client/src/views/media/edit.html
- src/Umbraco.Web.UI.Client/src/views/media/recyclebin.html
- src/Umbraco.Web.UI.Client/src/views/member/edit.html
- src/Umbraco.Web.UI.Client/src/views/member/list.html
I noticed we have several uses of `<umb-editor-sub-view>` as self-closed (void) elements, but with latest AngularJS v1.x.x version recently upgraded to, we have noticed several issues - mostly that any following sibling elements wouldn't be rendered.
In this case it isn't an issue at the moment, because it is the only child element where used, but if we later add text or elements after the component, it would cause issues rendering these elements.
> Ensure sub-view components are not self-closed elements

- src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
- src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.html
In backoffice we mostly have id + guid show in an sidebar box, e.g. in content, media, member group, datatype, etc.
So I think it would be a bit more consistent to move this under relation types as well.
Note part of this PR relies on the following PRs as well:
https://github.com/umbraco/Umbraco-CMS/pull/9632
https://github.com/umbraco/Umbraco-CMS/pull/9656
**Before**
**After**
> Move relation type id and macro id to sidebar box

- src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
- src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
- src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
- src/Umbraco.Web/UmbracoInjectedModule.cs
In these statements, the exception was passed as a log message parameter instead of as the exception. This meant the exception and including stack trace was not logged and thus lost.
As above, the log messages were missing important context as the exception was not logged. By switching around the parameters the correct overload is called.
It was calling https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Core/Logging/LoggerExtensions.cs#L65
But it intended to call https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Core/Logging/LoggerExtensions.cs#L37 or https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Core/Logging/LoggerExtensions.cs#L26
- Trigger …
> Fix some exceptions being logged the wrong way

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.createButton.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
While looking at https://github.com/umbraco/Umbraco-CMS/issues/9663 I found a few things in block list editor to cleanup.
- Semi colons after named functions
- Use `<umb-editor-container>` component instead of hard coded markup.
> Block editor cleanup

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/sectionpicker/sectionpicker.html
This PR replace the icon `icon-check` using `<i>` element with `<umb-icon>` in tree in section picker used in user groups.
> Replace tree icon in section picker with umb-icon component

- src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
- src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3.cshtml
The null check for Model.section fails in the event that:
* the grid editor has been added as composition to a page
* the partial `@Html.GetGridHtml(Model, "pageContentGrid")` has been added to the page template
* and the page hasn't been published with the new grid content yet
In this case the `Model` passed into `Html.GetGridHtml` will be `IPublishedContent` and not a `JObject`, and this will cause the grid render to fail.
> Fix: Verify that grid model is JSON object and not IPublishedContent

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
Issue: https://github.com/umbraco/Umbraco-CMS/issues/9569 (Has the old situation however, some parts were already fixed)
With the fix in place:
Just noticed that I forgot to record with the mouse. Hopefully, the gif is still enough!
> 9569: Fix image cropper buttons

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
If there's an existing issue for this PR then this fixes #9769 
I ran into this issue in a v8 migration, where the migration completes but the site failed to boot - code was falling into an infinite loop where it kept checking the same composition parentId, and would continue to do so until the inevitable heat-death of the universe. I didn't have that long to wait, hence the PR.
I'm not sure though how to test this - if it was an issue affecting all installs, it would have been noticed before, so I'm thinking it was likely due to something special in my database (db was updated from inheritance to composition a while back, so may have some stale data from that change). Can confirm though with the change my site starts and everything in the backoffice appears correct...
> 9769 - shift index increment before tryget to allow loop to continue if current iteration exits early

- src/Umbraco.Web/Cache/DistributedCacheExtensions.cs
- src/Umbraco.Web/Cache/MemberCacheRefresher.cs
- src/Umbraco.Web/Search/ExamineComponent.cs
Fixes #9684 
The member index was not removing deleted members and was actually throwing exceptions when this occurred.
> Fixes: After deleting a member, a reindex is attempted, which fails

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9824
Currently the block picker is showing filter, when enough blocks are available. However the filtering didn't work.
Furthermore when opening the block picker it was scrolling down to last block, because the auto focus set here was stealing focus from the filter. Event worse when start typing in the search input you suddently lost focus, probably because the filtered results now changes the indexes and the `umb-auto-focus` watched these block cards. For now I have removing the, but we can always add it again, when we fix this. For now it works better without the auto focus on the block cards. https://github.com/umbraco/Umbraco-CMS/pull/9831/commits/f6a316802c0b777c99898c63aab7c0bfbeed3 …
> Fixes #9824 - Filtering in block picker doesn't work

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9625
This PR fixes issues with filtering in icon picker and searching for terms like `box`, `view` and `svg` because these are included in the `svgString` property. We only need to filter on name property. In future releases we might be able to filter on tags or similar - see https://github.com/umbraco/Umbraco-CMS/issues/9122
Btw in this GIF I have installed the [Material Design Icon Pack](https://our.umbraco.com/packages/backoffice-extensions/material-design-icon-pack/), which doen't use SVG icons, but demonstrate the filtering also works with custom icons.
This is similar to other filtering where we are working with objects, e.g. in block picker where filter on "image" doesn't really …
> Fixes #9625 - Searching icons for "box" returns all icons

- src/Umbraco.Web.UI.Client/src/views/media/media.sort.controller.js
- src/Umbraco.Web.UI.Client/src/views/media/sort.html
I noticed the sorting in Content and Media currently isn't consistent. In Content section the sorting is restricted to y-axis and within parent container, so this PR updates this as well for media sorting.
I previous worked on that in https://github.com/umbraco/Umbraco-CMS/pull/8419 but somehow I forgot to add this the media as well.
I have also cleaned up the sort view as in the old PR.
> Make sorting in media consistent with sorting in content

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/notsupported/notsupported.html
- src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
When adding a property like Nested Content to the block editor you get an error like this:
> Property XYZ uses editor Nested Content which is not supported in **Element Types**.
The exact reasons for this have been discussed in #8732 - I'm not going to argue here and now... ;-)
But this error message is rather unhelpful, and in many cases inaccurate. It is possible to put Nested Content properties inside Element Types as Nested Content itself uses elements!
I have updated all instances of this message to be more Block Editor specific. The message now reads:
> Property XYZ uses editor Nested Content which is not supported in **blocks**.
> Unhelpful unsupported property message in Block Editor

- src/Umbraco.Core/IO/FileSystemWrapper.cs
The `FileSystemWrapper` class is abstract but frustratingly none of the methods are marked as abstract / virtual so can't be replaced...
The purpose of this class is to have the ability for custom file system providers to wrap existing / core providers.
In my case I have a package where I am shipping a custom file system provider but want to allow it to be wrapped and replaced, e.g. to use Azure Blob Storage. However I also want to manipulate the path before it goes to storage.
Perhaps my case is unique, but I personally can't see a reason for none of the methods to be overridable... 😊
> Make abstract FileSystemWrapper class methods virtual

- src/Umbraco.ModelsBuilder.Embedded/Building/TextBuilder.cs
- src/Umbraco.Tests/ModelsBuilder/BuilderTests.cs
When trying to unit test using models builder models, we are unable to mock these without writing a lot of code - https://our.umbraco.com/forum/using-umbraco-and-getting-started/81058-unit-testing-moq-mocking-for-umbraco-models-builder-object
Making the properties virtual will mean we can mock them using something like Moq with no additional code. 
**Testing**
I have updated the unit tests to reflect the virtual property change.
Thanks
Matt
> Make models builder properties virtual to allow mocking

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
The onUploadComplete function returns the last files that are added to a mediafolder. While this works correct by default and in most situations, it doesn't work as expected when a diffrent sorting is used for Media-items. For example, we've added events to sort Media-items automatically by name alphabetically when they are created/uploaded to keep them better organised. 
By sorting the $scope.files array by the Id-property, it ensures that the function returns the uploaded files, instead of the last files in the folder.
> Ensure that upload file(s) in the MediaPicker is returned

- src/Umbraco.Core/Extensions/StringExtensions.cs
- src/Umbraco.Core/IO/IIOHelper.cs
- src/Umbraco.Core/IO/IOHelper.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
There really is no testing this one 😄 I have performed a little housekeeping on `IIOHelper`:
- `TryResolveUrl` has been removed entirely, since it was only called from the unused method `DetectIsJavaScriptPath` on `StringExtensions` (deprecated/legacy JS handling that is no longer in use).
- `ResolveUrl` has been marked as obsolete, as it only forwards the call to `IHostingEnvironment.ToAbsolute` now.
- `IsPathFullyQualified` has been removed from the interface. Its implementation is retained in (and used by) `IOHelper`, but it's likely to be replaced by the .net standard implementation down the line. The method it is never used outside of `IOHelper`, so there is no acute need for it to be part of the interface.
> Clean up the IO Helper interface

- src/Umbraco.Infrastructure/Migrations/Expressions/Rename/Expressions/RenameColumnExpression.cs
- src/Umbraco.Infrastructure/Migrations/IMigrationExpression.cs
- src/Umbraco.Infrastructure/Migrations/MigrationExpressionBase.cs
The `Process()` method of the public interface `IMigrationExpression` is unused and has also been flagged for removal, so I removed it 😄 
Both implementations of `Process()` have also been removed, as all they did was to call `ToString()` eventually.
> Removed unused method from migration expression interface

- src/Umbraco.Core/Configuration/IUmbracoVersion.cs
- src/Umbraco.Core/Configuration/UmbracoVersion.cs
- src/Umbraco.Core/Models/UpgradeCheckResponse.cs
- src/Umbraco.Core/Packaging/PackageDefinitionXmlParser.cs
- src/Umbraco.Infrastructure/Install/InstallHelper.cs
- src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitDownloadStep.cs
- src/Umbraco.Infrastructure/RuntimeState.cs
- src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
- src/Umbraco.Web.BackOffice/Controllers/UpdateCheckController.cs
- src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs
Renaming `UmbracoVersion.Current` to `UmbracoVersion.Version` is an old TODO from the V8 code. 
I figured it would be nice to get that done, before the Unicore betas start rolling out, as runtime access to the Umbraco version is likely to be used by all sorts of 3rd party packages out there. Best to break it before the betas.
If you feel the urge to test this, create a template with the following content and observe how the current Umbraco version is very neatly printed when it's rendered 😆 
```cshtml
@using Umbraco.Cms.Core.Configuration
@inject IUmbracoVersion umbracoVersion
@inherits Umbraco.Cms.Web.Common.AspNetCore.UmbracoViewPage
@{
Layout = null;
}
<html>
<body>
<h1>Version is: @umbracoVersion.Version</h1>
</body>
</html>
```
> Rename UmbracoVersion.Current to UmbracoVersion.Version

- src/Umbraco.Tests/TestHelpers/BaseUsingSqlCeSyntax.cs
- src/Umbraco.Tests/TestHelpers/TestHelper.cs
- src/Umbraco.Tests/Testing/UmbracoTestBase.cs
- src/Umbraco.Web/UmbracoBuilderExtensions.cs
The extension method `CreateServiceProvider` on `UmbracoBuilderExtensions` is marked as obsolete. 
As of now the extension method is solely used for wiring up tests, so I have moved the implementation to `TestHelper` instead, so the method doesn't clutter the `UmbracoBuilderExtensions` class.
> Remove obsolete method in UmbracoBuilderExtensions

- src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
No DB writing will work as it is in SQL Server without this fix. 
It was missing a space.
> Fixes the Sql server SET LOCK_TIMEOUT call which was missing a space.

- src/Umbraco.Core/Services/Implement/PublicAccessService.cs
- src/Umbraco.Examine/ContentValueSetValidator.cs
- src/Umbraco.Tests/UmbracoExamine/UmbracoContentValueSetValidatorTests.cs
- src/Umbraco.Web/Search/ExamineComponent.cs
Follow up to https://github.com/umbraco/Umbraco-CMS/issues/8030#issuecomment-732232597 and https://github.com/umbraco/Umbraco-CMS/pull/7994
There is still one area of the background task logic in Umbraco Examine that wasn't using an explicit scope and if the call to that isn't cached we may get unexpected exceptions. 
This update should solve all of this now. With the previous change we put all indexing operations explicitly on a background thread which is good but we assumed that all DB/Scope operations were also being done in explicit scopes. Turns out one area was missing. This change ensures that this area has an explicit scope, but this change also goes ahead and just wraps the entire indexing logic on the background task in one outer scope so any new changes done within there will …
> Ensure there's explicit scopes used for all service access in the Examine indexing logic

- src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
PR containing the css fix supplied by @seanhakbb to solve the grid placeholder breaking out of the container.
This resolves #9808
> 9808 .umb-editor-placeholder - render overflows the container.

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9841
How to check (based on starter install):
- Create a new data type (Nested content with Feature as item. Min items: 0, Max items: 1).
- Add this data type to a document type
- Open a node that is of type of that document type
- Create a new nested content node
- Save and publish and reload the page
- The page shouldn't focus on the nested content data type anymore
The nested content item will still focus if you create a new one, so you are able to tab through it.
> 9841: Don't focus on nested content node at page load

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.html
Currently, there is a small bug that shows the configuration header for a data type even if there is no configuration:
This PR makes it so that the configuration header is only shown if there actually is one:
The best way to check this is:
- Go to a document type
- Add a new property
- Click on "Select editor"
- Choose the member picker
- Click on the member picker so that the editor settings window opens
Now, you won't see the configuration header if there is none.
> Don't show configuration header if there is none

- src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
Follow up on: https://github.com/umbraco/Umbraco-CMS/pull/9302
I was about make the changes from the PR above, only to realize I had already made those changes, but they haven't been deployed to the documentation site yet 😱 
But I also had another look through the file, and fixed a few things:
- Added missing period at the end of sentences without period
- Replaced quotes with ticks for value examples
- Added missing `* @param {object} editor rendering options.` to expose underlying parameters of the editor object
- Improved some descriptions
> Minor adjustments to ngdocs in editor.service.js

- src/Umbraco.Web.BackOffice/Filters/ValidateAngularAntiForgeryTokenAttribute.cs
- src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.controller.js
Fixed an issue where you could no longer install packages.
The issue was that the ValidateAngularAntiForgeryTokenFilter checked for a cookie path if that path didn't exist it called next but didn't return causing next to be called twice leading to some issues. I ~~removed this since it seems like legacy code, we check for `ClaimTypes.CookiePath` but never use it~~, added a return statement, see the comment below.
The second issue was with the UI, if the server hasn't restarted within 2 seconds we called install error, we now wait longer.
Made these changes with help from @bergmania so this has in effect already been reviewed.
> Netcore: Fix installing packages

- src/Umbraco.Core/Manifest/DataEditorConverter.cs
- src/Umbraco.Tests/Manifest/ManifestParserTests.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9842
The manifest was only loading in the defaultConfig if the prevalues were present. This has now been fixed, meaning that the following manifest now works:
```
{
"propertyEditors": [
{
"alias": "UrlPickerMacro",
"name": "Url Picker (Macro)",
"group": "Macro Parameter Editors",
"icon": "icon-link",
"isParameterEditor": true,
"editor": {
"view": "~/umbraco/views/propertyeditors/multiurlpicker/multiurlpicker.html",
"valueType": "JSON"
},
"defaultConfig": {
"ignoreUserStartNodes": "0",
"minNumber": "0",
"maxNumber": "1"
}
}
]
}
```
Also updated a test to make sure that it checks the defaultconfig. Something it didn't do before this.
> 9842: Fix for defaultConfig not working without prevalues

- src/Umbraco.Infrastructure/Packaging/PackageInstallation.cs
- src/Umbraco.Web.UI.Client/src/views/packages/edit.html
This PR actually fixes two bugs, one in the backend and one in the front end, but the frontend one is so minor I just added it to this. 
When trying to install a package with actions you would get an error from trying to parse the stored package XML, this was because "Undo" actions were saved improperly leading to XML with multiple root nodes like this: 
`<actions></actions><Action runat="install" alias="publishRootDocument" documentName="Home" />`
This stemmed from `RunPackageActions` where we just appended to the actions string in the PackageDefinition, this is set to `<action></action>` from initially parsing the XML (since there can be more than one action) so we can't do this. I changed it, so that we now parse the XML in `packageDefiniton.Actions` into an XElement and use that to …
> Netcore: Fix packages with actions

- src/Umbraco.Web.UI.Client/src/navigation.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9826
Bug could be reproduced like this:
- Update People and Person to be "Allow vary by culture"
- Add a new language
- Go to the log viewer and click on the "Not(@Level='Verbose') and Not(@Level='Debug')". There might be other ways of doing this, but I just managed to find this one. Basically, what you want to do is to get rid of the mculture query string.
- Go back to content and click on the People node
- You'll see an error. 
The whole stacktrace can be found in the issue. The problem here was that mculture wasn't in the url anymore and the getChildren call to Umbraco requires a culture to be given.
> 9826: Make sure to set mculture after switching sections

- src/Umbraco.Web/Security/AppBuilderExtensions.cs
- src/Umbraco.Web/Security/BackOfficeClaimsIdentityFactory.cs
- src/Umbraco.Web/Security/ClaimsIdentityExtensions.cs
- src/Umbraco.Web/Umbraco.Web.csproj
When auto linking with callbacks such as OnExternalLogin, custom claims can be added to the user which are flowed to the auth ticket/identity. However, when the security stamp validator executes, the identity is re-created manually without any knowledge of those custom claims so they are lost. 
This ensures that those custom claims flow through to the re-generated identity during the security stamp validation phase.
This is annoying to test. The easiest way is to modify source code and breakpoint to verify that it's working.
* Change BackOfficeSignInManager and add a custom claim on sign in. This code will go in the method `PasswordSignInAsyncImpl` above the line: `// We need to verify that the user belongs to one or more groups that define content and media start nodes.` This is …
> Keep custom claims that are flowed during security stamp validation

- src/Umbraco.Web/PublishedContentExtensions.cs
- src/Umbraco.Web/PublishedPropertyExtension.cs
The method PublishedPropertyExtension `public static T Value<T>(this IPublishedProperty property, string culture = null, string segment = null, Fallback fallback = default, T defaultValue = default)` does not pass along the `defaultValue` and instead just returns `default` which isn't correct.
The method `public static T Value<T>(this IPublishedContent content, string alias, string culture = null, string segment = null, Fallback fallback = default, T defaultValue = default)` was not passing defaultValue to the inner property.Value call
> The Value() method for IPublishedContent was not working with the defaultValue parameter

- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9940
The ordering in the translation tab was being used on the wrong ng-repeat element. Moving it to the correct one fixes the issue.
Steps to reproduce can be found in the issue.
> 9940: Make sure that ordering is correct

- src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
- src/Umbraco.Web.UI.Client/src/views/languages/overview.html
This fixes regressions introduced in PRs #9006 and #9007.
As per https://github.com/umbraco/Umbraco-CMS/pull/9006#issuecomment-708682932, the languages/variants were correctly sorted alphabetically, but with the default language first. This reverts the custom `orderBy` filters in the AngularJS views and ensures the ordering retrieved from the server is used instead.
This ordering is done on the server in the `LanguageMapDefinition`, so even though the `ILanguageRepository` always returns the languages sorted on ID (which can be different per environment), this ensures the first is always the default and the rest is sorted on name:
https://github.com/umbraco/Umbraco-CMS/blob/b29fd4ada3c1eb7a703c3a3a0131ecfa990c3f97/src/Umbraco.Web/Models/Mapping/LanguageMapDefinition.cs#L41-L56
> Remove orderBy filter for languages/variants

- src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
When content is displayed inside a "small" editor window (e.g. in the grid or block list) the property labels take up 50% of the available space, making many properties so small they are unusable.
This isn't so much of an issue in other larger sizes, e.g. medium, as the properties have enough space.
Since the introduction of the "labels-on-top" feature in Umbraco 8.10, I propose properties in small editor windows are treated the same by default. This PR changes the labels and properties in these cases to be full width.
After the change here's how it looks:
> Make properties full width in small infinite editors

- src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfileupload.directive.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9886
No need to preventDefault or stopPropagation. As this prevents the input from retrieving the dropped-file.
It was introduced in this PR: https://github.com/umbraco/Umbraco-CMS/pull/8390
And those lines didn't serve any purpose towards the goal of that PR. As well it's not used anywhere else, so I conclude it has no purpose and can go away.
> #9886 drag n drop files for upload

- src/Umbraco.Web.BackOffice/DependencyInjection/ServiceCollectionExtensions.cs
- src/Umbraco.Web.UI.NetCore/appsettings.json
Fixes #9938 
* A duplicated `TreeAccessDocumentTypes` policy had a requirement for user access to the Dictionary tree, which a user failed to achieve by removing the Translation section from their user group;
* By removing this policy as well as fixing the one for `TreeAccessDictionary` the issue is resolved
Follow the steps to reproduce listed on the original issue and verify that we meet the **Expected result**.
----
Bonus: 
* This PR also contains a change for reverting to the default state of appsettings.json.
> NetCore: Fix authorization policies bound to Translation section

- src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
- src/Umbraco.Web.Common/Middleware/PreviewAuthenticationMiddleware.cs
The preview function does not display draft versions: 
Turns out the current backoffice user isn't authenticated, because the middleware to do so (`PreviewAuthenticationMiddleware`) never gets executed. I have rearranged the order of the middleware, so `PreviewAuthenticationMiddleware` is placed before `UmbracoRequestMiddleware` in the pipeline. This fixes the lack of authentication for the preview function:
I also added a bit of logging to the middleware while I was at it.
I know you're working on rearranging the codebase right now. I suspect I may have done things upside down here - perhaps `UmbracoRequestMiddleware` should have been moved to `Umbraco.Cms.Web.BackOffice`, instead of moving `PreviewAuthenticationMiddleware` to `Umbraco.Cms.Web.Common`? Let me know if it's all wrong and …
> Preview does display draft versions

- src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
As part of the [Community Models Builder Team](https://github.com/modelsbuilder)'s work we will be releasing a new version of Models Builder.
We cannot continue using the `Umbraco.ModelsBuilder` namespace, for many obvious reasons, and so we'll be introducing a new namespace: `ModelsBuilder.Umbraco`. This offers the flexibility we need to drive the project in the direction we want.
Umbraco identifies whether to use the built in "Embedded" Models Builder or the "legacy" / external one by scanning for the `Umbraco.ModelsBuilder` assembly...
Longer term I think we need a better way of registering a Models Builder, but for now this change adds the new namespace to the list treated as external.
> Including ModelsBuilder.Umbraco in list of external Models Builders

- src/Umbraco.Core/Configuration/Models/ContentSettings.cs
- src/Umbraco.Core/WebAssets/IRuntimeMinifier.cs
- src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
- src/Umbraco.Infrastructure/WebAssets/JsInitialize.js
- src/Umbraco.Infrastructure/WebAssets/PreviewInitialize.js
- src/Umbraco.Infrastructure/WebAssets/RuntimeMinifierExtensions.cs
- src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
- src/Umbraco.Web.UI.Client/gulp/config.js
- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/gulp/tasks/js.js
- src/Umbraco.Web.UI.Client/gulp/util/processJs.js
- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
- src/Umbraco.Web.UI.Client/src/install.loader.js
- src/Umbraco.Web.UI.Client/test/config/karma.conf.js
As-is we let Smidge perform runtime optimization and bundling of all client scripts - both the ones shipped with Umbraco and the ones for backoffice extensions. We even optimize some 3rd party libraries runtime, because we ship Umbraco with un-minified versions of these libraries.
This PR aims at minimizing the runtime overhead by never optimizing any of the scripts shipped with Umbraco. This is done by:
1. Ensuring we only ship minified versions of 3rd party libraries.
2. Minifying the core scripts as part of the build process.
3. Splitting the "main script bundle" into two separate bundles - a bundle for the core scripts and a bundle for the backoffice extensions scripts.
4. Only performing optimization/minification on the backoffice extensions bundle. The core bundles now only exist to …
> Do not apply runtime optimization to core scripts and script libraries

- src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9948
Added a copy action to the media picker. Here is a video showing it:
> Add copy logic to Media Picker

- .gitignore
- src/Umbraco.Web.UI.NetCore/Program.cs
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- src/Umbraco.Web.UI.NetCore/appsettings.json
This file is not checked in and can be used to overwrite any custom settings that are in the repo without worrying about accidentally checking in developer settings as you work.
This also fixes up a couple other very minor settings.
How does it work?
Just create a file in the root of the Umbraco.Web.UI.NetCore project called: `appsettings.local.json` and it will automagicaly just be put underneath the appsettings.json.
Then any settings you apply here overwrite the defaults. This means you can have your own persistent connection string in there without having to worry about checking it in or merging when pulling, etc...
For example, mine looks like:
```json
{
"ConnectionStrings": {
"umbracoDbDSN": "server=MyServer;database=MyDatabase;user id=MyUser;password='MyPassword'"
},
"Serilog": { …
```
> Allow for having appsettings.local.json

- src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
This PR just removes an unnecessary `aria-hidden` on `<umb-icon>` introduced in https://github.com/umbraco/Umbraco-CMS/pull/9264 since it is already taken care of in the component itself https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/umb-icon.html#L1
In fact it was the only place I could find where this was added to `<umb-icon>`.
> Remove unnecessary aria-hidden attribute from umb-icon

- src/Umbraco.Web/PublishedContentExtensions.cs
- src/Umbraco.Web/PublishedPropertyExtension.cs
Partially reverts umbraco/Umbraco-CMS#9888
PR #9888 introduced an unintended breaking change, so reverting it but with keeping one change: we send the fallback + default value parameter to the inner Value method.
> Revert "The Value() method for IPublishedContent was not working with the defaultValue parameter"

- src/Umbraco.Core/IO/IOHelper.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/9964
Removes a unneeded check from IOHelper.MapPath that makes virtual directories in IIS not work, see the issue for details.
> #9964 Removed unneeded check for HttpContext

- src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs
- src/Umbraco.Web/HealthCheck/Checks/Security/HttpsCheck.cs
Fix for #9950
Updated HttpsCheck to request background login image if ApplicationUrl returns 301/302.
Note: a HEAD request to /umbraco with UmbracoID will return a 404 and throw an exception, this is why I've changed to a GET request but have disabled auto-follow.
Changed ExcessiveHeaders to make the test request to the root instead of the /umbraco path. Also fixed a long gone localisation alias. 
Tested on Umbraco Cloud enabled with UmbracoID. Note that Cloud "Public Access" restrictions will cause 401 on both checks unless all Umbraco Cloud IPs are added to the whitelist.
> Fix for #9950 - HttpsCheck/ExcessiveHeaders when UmbracoID is in use

- src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
If there's an existing issue for this PR then this fixes #9993 
As described in #9993 you can't save a Grid sometimes due to an error.
- Add a new item to the grid of type image
- Do not pick an image, so just the placeholder is there
- Attempt to save the page
- Notice error popping up
In recent changes in the Grid it seems like the model was changed slightly, which now requires us to make sure items have values before we try to parse those values. I believe this might have been due to the change here: https://github.com/umbraco/Umbraco-CMS/pull/9681/files#diff-16bf5e50f31cc4c3ef3f2af6bf0a399b98e5e2e926e793184cffdc9d0f0ecbcdR112-R120
Not entirely sure. 
So far this error is the only side-effect we've seen, but there may be more, we'll need to investigate //cc: @nathanwoulfe
> Fixes #9993 - Cannot save empty image in Grid

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/userpicker/userpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/userpicker/userpicker.controller.js
Temporary fix for this issue. using the entityservice like before.
If there's an existing issue for this PR then this fixes #9983 
The new user picker only works properly if you're an admin user because it calls an API that is only available to people who have access to the Users section of the backoffice. If you try to use it without having access you get logged out of the backoffice.
In PR https://github.com/umbraco/Umbraco-CMS/pull/7613/ the endpoint usage changed, before that the user picker would use the entity service to get information about the available users. 
We can't make the new endpoint available to people who don't have access to the users section as it discloses too many details that should not be available to a user of type editor (for example). The new endpoint returns: …
> Fixes #9983 - Getting kicked, if document type has a Umbraco.UserPicker property

- src/Umbraco.Infrastructure/HostedServices/HealthCheckNotifier.cs
- src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
- src/Umbraco.Infrastructure/HostedServices/LogScrubber.cs
- src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
- src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
- src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
- src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
- src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
- src/Umbraco.Infrastructure/HostedServices/TempFileCleanup.cs
This was raised in a comment by a community member, and seems correct.  We can make this method public allowing package developers and/or custom solutions creating hosted services to use our base class.
> Made recurring hosted service base class PerformExecuteAsync method public.

- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/gulp/tasks/js.js
- src/Umbraco.Web.UI.Client/gulp/util/processJs.js
This PR fixes the comments made by @Shazwazza on #9839
Run the client build and boot up the backoffice with devtools open. You should no longer see warnings in the console about missing source maps - as-is you'll see something like this:
> Add gulp comments and sourcemap dependencies

- src/Umbraco.Infrastructure/Cache/DatabaseServerMessengerNotificationHandler.cs
This resolves the error found in #9843 and allows for the install to proceed.  I did take out the check for whether or not the DB can connect, because this check happens in the `RuntimeState.GetUmbracoDatabaseState` method.  If it cannot connect, then either the Level is set to `RuntimeLevel.Install`, in which case we have the same behavior as before, or a boot exception is thrown in the `RuntimeState.DetermineRuntimeLevel` method.  In either case, we are handling the same scenarios without having to make a second connection to the database during server startup.
> #9843 - Allow install with DB string pre-configured

- src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
If there's an existing issue for this PR then this fixes #9796 
I fixed the translations for the somethingElse key which was translated to the swedish word for "Regret". The new translation is now word for word "Do something else".
Here's where you can find the translated text:
> Fix swedish translation for somethingElse.

- src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/mediatype.resource.js
- src/Umbraco.Web.UI.Client/src/common/resources/membertype.resource.js
- src/Umbraco.Web.UI.Client/src/views/documenttypes/copy.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/export.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/importdocumenttype.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/move.html
- src/Umbraco.Web.UI.Client/src/views/mediatypes/copy.html
- src/Umbraco.Web.UI.Client/src/views/mediatypes/move.html
- src/Umbraco.Web.UI.Client/src/views/membertypes/copy.controller.js
- src/Umbraco.Web.UI.Client/src/views/membertypes/copy.html
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
- src/Umbraco.Web/Editors/MemberTypeController.cs
- src/Umbraco.Web/Trees/MemberTypeAndGroupTreeControllerBase.cs
- src/Umbraco.Web/Trees/MemberTypeTreeController.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9991
This PR implement the copy feature for member type similar to how it works for content type and media type. Currently this works (almost) as expected. However unlike content/document types and media types where it use `customtreeparams="foldersonly=1"` I guess it in this context doesn't know what a folder is, so it both shows folders (or only root node) and also all member types. The member type being copied isn't selectable, but the others are, which cause an error if trying to copy a member type under another member type (which is allowed for e.g. media types).
Besides that it is a great feature and could save some time in development if working with several member types in …
> Copy member type

- src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10016
This PR fixes the changes introduced in https://github.com/umbraco/Umbraco-CMS/pull/9026 which broke  backward compatibility using custom listview layouts.
Not sure why it need to pass in the entire scope as second parameter and not just the options though, but we probably can't change that now without making another breaking change. It would probably be simpler with something like this:
```
const options = {
id: 1234,
useInfiniteEditor: true
}
```
The rest is available from `item`, but maybe it has something to do with it also need `scope.getContent(scope.contentId)`.
To make in easy to test I have create a custom listview for people in default starter kit. Unzip this …
> Ensure backward compatibility in listview edit with custom listview layout

- src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
- src/Umbraco.Web.BackOffice/Trees/TreeNodesRenderingNotification.cs
Added `TreeAlias` to the `TreeNodesRenderingNotification`, so subscribers know what tree has been rendered.
> Netcore: Added TreeAlias to TreeNodesRenderingNotification

- src/Umbraco.Web/PropertyEditors/ListViewConfiguration.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/pull/10036
This PR update casing of "Grid" listview layout which was changed a long time ago from "Grid" to "grid" in https://github.com/umbraco/Umbraco-CMS/commit/fb246de5fc27a911fe8381026218abc37fbf5a60
It seems to fix the issue with naming of "Grid" layout in "List View - Members".
For the custom listview configuration in still seemed to use the old "grid" name though.
After deleting the datatype instance an configurate a new custom listview for the document type if does use the correct "Grid" layout name.
The reason the listview "Grid" layout name sometimes was correct is because it is added here during install:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Migratio …
> Update casing of listview layout name

- src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
Listening for splitViewRequest was only unbound if the split view editor was opened. Not cleaning up the listener caused a memory leak when changing between nodes as the spit view editor was detached but not garbage-collected.
This contributes to fixing #6053 but I'm not sure if it's solved the issue entirely - GC seems to be running more efficiently, node count doesn't continue to grow when travelling around the backoffice.
> Unbind listener in variant content editor

- src/Umbraco.Web.UI.Client/src/less/forms.less
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html
This PR adjust the icons in date picker property editor to use `<umb-icon>` component and adjust the styling a bit.
> Replace icon in date picker with umb-icon component

- src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
- src/Umbraco.Web.UI.Client/gulp/config.js
- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbdatetimepicker.directive.js
- src/Umbraco.Web.UI.Client/src/index.html
- src/Umbraco.Web.UI.Client/src/views/content/umbpreview.html
- src/Umbraco.Web.UI.NetCore/umbraco/UmbracoInstall/Index.cshtml
_This is the CSS equivalent of #9839_
This PR ensures that we ship minified CSS assets and dependencies instead of minifying them at runtime.
As it happens we're already minifying the core CSS when building the backoffice, but we still tell Smidge to minify it (again) at runtime. I have changed the destination files for the backoffice CSS to have a `.min.css` extension to make it clearer that they are actually minified.
Note that the `bootstrap-social` NPM package does not ship with a `.min.css` stylesheet. But `bootstrap-social.css` is still minified, or at least almost minified, so I have chosen to include it as-is:
If the backoffice looks alright, the PR works 😄 
Also you might want to test that you can configure a color picker datatype:
..and use a date/time picker in content:
> Do not apply runtime optimization to core CSS and CSS libraries

- src/Umbraco.Web.UI.Client/src/less/buttons.less
- src/Umbraco.Web.UI.Client/src/less/main.less
- src/Umbraco.Web.UI.Client/src/less/panel.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
This PR adjust a few things in listview configuration:
- Update icons using `<umb-icon>` component
- Ensure sortable handle use `move` cursor style
- Simplified markup for icon button for system/custom icon
- Increase font size / icon size of custom app icon. Note the class is also used in icon in e.g. icon picker button on content, media and member types.
> Listview config icons

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/languages.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/templates.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Tour/backofficeTour.ts
- src/Umbraco.Tests.AcceptanceTest/package.json
Updates cypress to the latest version (6.8.0) and the failing create template tests, there is also a minor tweak to the backOfficeTour tests, and language tests.
Unforunately the create template tests is fixed with a 500 ms wait after clicking the create button, the issue is that when the ace editor is loading some javascript runs which briefly takes focus from the header field, normally this is not an issue since the script finishes after ~50 ms, however, this is enough time for cypress to type a single letter in the header field, causing the auto save event to fire, breaking the tests because there is no valid alias yet.  I tried fixing this issue some other way, but as far as I can tell there is nothing in the DOM signalling that the javascript is done.
I changed "disabled" to true …
> Update cypress and fix tests

- src/Umbraco.Core/Events/DeletingNotification.cs
- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/LocalizationService.cs
- src/Umbraco.Infrastructure/Services/Notifications/DictionaryItemDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DictionaryItemDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DictionaryItemSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DictionaryItemSavingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/LanguageDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/LanguageDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/LanguageSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/LanguageSavingNotification.cs
- src/Umbraco.PublishedCache.NuCache/Compose/NotificationsComposer.cs
- src/Umbraco.PublishedCache.NuCache/PublishedSnapshotServiceEventHandler.cs
- src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
Migrate the events in `LocalizationService` to the new `EventAggregator` pattern.
Most of this was fairly straight forward, I did run in to a bit of trouble with the integration tests, there were two issues:
1. Since we now rely on dependency injection to register events, we have to use the registered `IServerMessenger`. The default `IServerMessenger` registered in integration tests is a `NoopServerMessenger` which meant that when the events was raised nothing really happened because the `IServerMessenger` did nothing. This was fixed by registering a `LocalServerMessenger` in the `CustomTestSetup` overridden method.
2. In the `SingleItemsOnlyRepositoryCachePolicy` test, we didn't bind the `DistributedCache` until after we had populated the cache with some test objects, from what I can …
> Netcore: Migrate localization service events

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagementresults.html
- src/Umbraco.Web/Editors/ExamineManagementController.cs
- src/Umbraco.Web/Models/ContentEditing/SearchResult.cs
Examine / Lucene supports having multiple values per field, but the backoffice Examine Management dashboard only renders the first.
This PR sets to fix that by rendering all values for each field.
I have modified / cleaned up the API to return the true list of fields + values straight from the Examine results. In the backoffice values are now listed in a comma separated (`, `) list using the existing `umbCmsJoinArray` filter.
Before:
After:
> Handling multiple values per field in Examine Management

- src/Umbraco.Web/PublishedContentExtensions.cs
This adds a generic `Root<T>` extension method to `IPublishedContent` to get the root content in a specific (ModelsBuilder generated) content type, e.g. to get the `Home` content in a Razor master view:
```cshtml
@{
var home = Model.Root<Home>();
}
```
It also adds a `Breadcrumbs` extension method that basically gets the ancestors in reverse order, until a specific level or content type is found and with/without itself:
```cshtml
@foreach (var breadcrumb in Model.Breadcrumbs<Home>())
{
<a href="@breadcrumb.Url()">@breadcrumb.Name</a>
}
```
I've also fixed the obsolete usage of both `CreatorName` and `WriterName` properties (https://github.com/umbraco/Umbraco-CMS/pull/7544) with the extension methods, which was very easy, as the `IUserService` was already available 🎉
> Add Root<T> and Breadcrumbs extension methods for IPublishedContent

- src/Umbraco.Web/Trees/MemberTreeController.cs
This was reported in the Deploy tracker [here](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/3) but the fix is needed in core.
I've just added an alphabetical ordering to the member type listing used to group members in the members section, which matches what is used when member types are ordered within settings.
To Test:
- Create a member type.
- Create another one with a name that starts with a letter earlier in the alphabet than the first one.
- Check they render under the "Members" section in alphabetical order.
Replaces [this PR](https://github.com/umbraco/Umbraco-CMS/pull/10063) targetting `v8/dev`.
> Orders member type grouping of members alphabetically, matching the listing of member types.

- src/Umbraco.Web/PublishedContentExtensions.cs
Changing the properties to use the extensions is a good thing (given the props are deprecated), but causes issues deep in tests. I'm reverting that change to fix the tests, and all refs to the deprecated properties should be updated in one sweep, to deal with any other test issues that might crop up.
No changes in behavior, other than tests no longer failing.
> Revert updating deprecated WriterName/CreatorName refs

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js
- src/Umbraco.Web.UI.Client/src/less/application/umb-outline.less
- src/Umbraco.Web.UI.Client/src/less/forms.less
This PR fixes the checkbox focus state and "tabbing"-mode when a dialog has been opened. When a dialog is opened and closed, with mouse clicks only, the UI will stay in "tabbing"-mode. It makes it impossible to use the UI without using the keyboard to get out of "tabbing"-mode. See the demos below:
The PR also fixes the issue described in #9790
Before fix:
https://user-images.githubusercontent.com/6078361/112824317-ac90f600-908a-11eb-8354-a9ffac061075.mp4
After fix:
https://user-images.githubusercontent.com/6078361/112824418-caf6f180-908a-11eb-90e5-baf541235982.mp4
Zip with test dashboard if needed:
[Test.zip](https://github.com/umbraco/Umbraco-CMS/files/6221117/Test.zip)
> Fixes tabbing-mode remains active after closing modal #9790

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
This replicates what we have in V8, where we make internal classes and methods available to Umbraco Forms.
> Netcore: Made internals visible to Umbraco Forms assemblies

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/email/email.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/integer/integer.html
When a step size is configurated in integer/numeric datatype the value isn't saved if it doesn't fit with the step size.
Considering the following:
Minimum: 100
Step: 2
Maximum: 200
Values below 100 and above 200 are invalid, but also a number like 101 due how the step attribute works with HTML5 input fields.
With this change it add a nicer validation, which has already been fixed for the Decimal datatype in https://github.com/umbraco/Umbraco-CMS/pull/9334
> Fix validation of step size in integer/numeric field

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9962
How to check (based on the default install):
Set all grid rows on "Allow all editors". Without this fix, you'll not be able to move between the different rows.
The issue here was that the .allow only has the editors selected by the user. So if you were to only select RTE, it would work because .allow is ["RTE"]. If you use the selectAll editors, it will set allowAll to true, but leave .allow empty.
> 9962: Use $allowedEditors instead of allowed

- src/Umbraco.Web.UI.Client/src/common/directives/components/tabs/umbtabsnav.directive.js
Tabs navigation requires a form and the val-form-manager directive to work. These are not needed if the tabs are used inside a property editor or dashboard. I have added this to the UI documentation.
How to test:
* Run the UI Documentation from the Umbraco.Web.UI.Docs with `gulp watch`
> fixes #10021 adds ng-form and val-form-manager to the documentation

- build/NuSpecs/UmbracoCms.Core.nuspec
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/Umbraco.Web.csproj
This PR fixes #9918
Updated LightInject to version 6.4.0 and made sure that:
1. All relevant Unit Tests succeed
2. Site still runs when using the updated package
---
_This item has been added to our backlog [AB#10761](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10761)_
> Fixes #9918 - Update Lightinject to v6.4 due to memory leaks in LightInject.Microsoft.DependecyInjection

- src/Umbraco.Core/Services/Implement/ContentService.cs
- src/Umbraco.Tests/Services/ContentServiceTests.cs
Fixed the order of the Descendants nodes during the copy
I've also created a Unit Test to test it
Fixes #8033
> Fixed copy preserving sort order

- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/DomainService.cs
- src/Umbraco.Infrastructure/Services/Notifications/DomainDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DomainDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DomainSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/DomainSavingNotification.cs
- src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
Migrated the static events in `DomainService` over to the new notifications pattern. Nothing of particular interest to report on this one, everything went smoothly
The same as the other event PRs, take look at #10075, the approach is the same, just using different events.
> Netcore: Migrate domainservice events

- src/Umbraco.Core/Events/DeletedNotification.cs
- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/RelationService.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationSavingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationTypeDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationTypeDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationTypeSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/RelationTypeSavingNotification.cs
- src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
Migrated the static events in `RelationService` over to the new notifications pattern.
For some reason we don't raise the `RelationDeletingNotification` here, only the `DeletedRelationNotification`, I'm not sure I understand why we don't, we could just publish one cancelable notification with the list of relations?
DeletedNotification didn't have a constructor for IEnumerable<T>, even though it inherited EnumerableObjectNotification, I'm assuming it's because this wasn't used until now, however, it's needed for the above, so I added it.
In the `Save(IEnumerable<IRelation> relations)` method I got a multiple enumeration warning, so I turned the `IEnumerable<IRelation>` into an array.
The same as the other event PRs, take look at #10075, the approach is the same, just using different …
> Netcore: Migrate relationservice events

- src/Umbraco.Core/Mapping/UmbracoMapper.cs
- src/Umbraco.Tests/Mapping/MappingTests.cs
- src/Umbraco.Tests/Testing/TestingTests/MockTests.cs
We have a lot of mappers that makes several calls to multiple services, resulting in multiple transactions. This PR wraps all calls to the mappers' Map methods in an explicit scope, making all Map operation result in a single transaction. 
I've tried to investigate potential issues and pros and cons. I was unable to find any issues, but the benefit of this change is also the downside to it, there will always be created an explicit scope, even for the mapping operations that don't require the scope, however, as far as I can tell, it's only a matter of object allocation, and therefore I think it's a beneficial trade-off.
Another minor downside to this is that it can be argued that this introduces more "magic". If you don't take a look at the UmbracoMapper implementation, it's not obvious …
> Create explicit scope for mappers in UmbracoMapper

- src/Umbraco.Core/Events/CreatedNotification.cs
- src/Umbraco.Core/Events/CreatingNotification.cs
- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/FileService.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewCreatedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewCreatingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/PartialViewSavingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/ScriptDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/ScriptDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/ScriptSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/ScriptSavingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/StylesheetDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/StylesheetDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/StylesheetSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/StylesheetSavingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/TemplateDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/TemplateDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/TemplateSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/TemplateSavingNotification.cs
- src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
- src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs
- src/Umbraco.Web.Common/ModelsBuilder/ModelsBuilderNotificationHandler.cs
Migrated the static events in `FileService` over to the new notifications pattern. 
There are a few interesting things this time. 
For some reason `DistributedCacheBinder_Handler` bind to the `DeletedStylesheet` and `SavedStylesheet` event, but do nothing with the events, the methods are just empty. There is a note saying "TODO: our weird events handling wants this for now", but I don't see any reason why this should be necessary for the notifications pattern, so I've just removed the event bindings.
This one used what seems like an old pattern, adding "Additional data"  to the event, I added this to the Notifications classes instead.
This data is then used in the `ModelsBuilderNotificationHandler`, in the same class we also used the `UmbracoApplicationStarting` notification to bind to …
> Netcore: Migrate fileservice events

- src/Umbraco.Core/Events/TreeChangeNotification.cs
- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/MediaService.cs
- src/Umbraco.Infrastructure/Services/Notifications/MediaTreeChangeNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/TreeChangeNotification.cs
I've migrated the `MediaService` `TreeChanged` event over to the new notification pattern.
Now I don't know if we had any specific plans on how to handle the `TreeChange` aspect of it, but seeing as we also use it other places than the Events/Notifications I opted to retain this and make it so the Notification just "wrap" an `IEnumerable` of `TreeChange`
The `EventArgs` and `ToEventArgs` threw me off a bit, but I concluded that we just use this to be able to send `TreeChange` with events, so I didn't really worry about it.
> Netcore: Migrate MediaService tree changed notification

- src/Umbraco.Core/Composing/TypeLoader.cs
This deadlock can occur in both v8 and the netcore branches, this fix is for netcore (the v8 fix is #9960)
This is why:
There is actually no reason at all for GetFileBasePath to use the `_locko` lock and I believe it was used by accident and just re-using an existing lock field. The GetFileBasePath method is actually just a lazy initializer for a value so that's what it should be and that is how this is fixed. Now we have a Lazy<string> _fileBasePath which is initialized with GetFileBasePath and then _fileBasePath.Value is used where needed and this fixes the deadlock.
> Fix dead lock with TypeLoader

- src/Umbraco.Core/Constants-Security.cs
Hello,
Just a wee typo fix, but every little helps, right?
I noticed today (using audit log viewer package) when looking in audit logs the unknown user is logged as "SYTEM", I assume this is a typo of "SYSTEM". I have updated :)
Thanks,
Carole
> Updating typo in audit logging default user

- src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
- src/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
Fixes: #10073
Missing to set the default value for the models' namespace, didn't correctly map the models with their corresponding types, resulting in the issue reported in #10073.
-----------------
In the described scenario, Andy has used the Element type "_Nested Item_" as a property of the **Home** model. Meaning that we had something like:
```c#
namespace Umbraco.Cms.Web.Common.PublishedModels
{
/// <summary>Nested Item</summary>
[PublishedModel("nestedItem")]
public partial class NestedItem : PublishedElementModel
{ . . . }
/// <summary>Home</summary>
[PublishedModel("home")]
public partial class Home : PublishedContentModel
{
. . . 
// properties
///<summary>
/// Nested Items
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", …
```
> NetCore: Types from MB-generated models are not recognized without namespace value

- src/Umbraco.Web/Editors/KeepAliveController.cs
As per #10109 I have swapped the OnlyLocalRequests attribute for HttpHead so that the Ping method can be used by external health probes (Azure Web App Health Check Probe, AZFD Probe etc)
> Allow KeepAlive controller Ping method to be requested by non local requests

- src/Umbraco.Core/Services/ICacheInstructionService.cs
- src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs
- src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/CacheInstructionServiceTests.cs
Fixes #10112 
As described in the issue linked above, the problem was that the `ContentCacheRefresherNotification` was being dispatched over and over again, every 10 seconds.
The problem however was not only with the `ContentCacheRefresherNotification`, but with ***every*** `SomethingCacheRefresherNotification`, the problem lies with how the `ProcessDatabaseInstructions` method from `DatabaseServerMessenger` was migrated, it's now in a different service, the `CacheInstructionService`.
It the `CacheInstructionService` internal process method (`ProcessDatabaseInstructions`), we would always call `GetPendingInstructions` with the last id being 0, this meant that we would always get ***all** the cache instructions, causing us to process the same instructions over and over, to infinity and …
> Netcore: Only process each cache instruction from DatabaseServerMessenger once.

- src/Umbraco.Core/Services/Notifications/ContentTreeChangeNotification.cs
- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentService.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEventsTests.cs
Migrates the TreeChanged event in ContentService to the new notification pattern, I also applied some stylecop quick fixes while I was there.
The ContentEventsTests also broke because it relied on the distributed cache binders, so I changed it so we now register a LocalServerMessenger in the container, and bind the event on the distributed cache.
Same as all the other event migrations (see #10075)
> Netcore: Migrate ContentService events

- src/Umbraco.Core/Events/CancelableNotification.cs
- src/Umbraco.Core/Events/DatabaseCreationEventArgs.cs
- src/Umbraco.Infrastructure/Migrations/Events/DatabaseSchemaCreatedNotification.cs
- src/Umbraco.Infrastructure/Migrations/Events/DatabaseSchemaCreatingNotification.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreatorFactory.cs
- src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/AdvancedMigrationTests.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/DatabaseBuilderTests.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SchemaValidationTest.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SqlServerTableByTableTest.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
- src/Umbraco.Tests/TestHelpers/TestHelper.cs
- src/Umbraco.Tests/TestHelpers/TestObjects.cs
- src/Umbraco.Tests/TestHelpers/TestWithDatabaseBase.cs
- src/Umbraco.Tests/Testing/UmbracoTestBase.cs
Migrates the two events in `DatabaseSchemaCreator`
This was a bit of an odd one, the two events are essentially just empty cancelable events, and seemingly not used, but seeing how the methods that dispatched the events are virtual I assume it's used somewhere else for some integration purposes? 
I also noticed that the events were internal, so I've just made two new, very very basic, empty notifications, with one of them being cancelable.
I opted to inject IEventAggretor and use that to publish the events, partially because from the comments it seems like the notifications are expected to be published instantly, but also because when the method publishing the events are called from unattended install, it's done so out of a scope.
I tested that Umbraco still installs without issue. 
I …
> Netcore: Migrate DatabaseSchemaCreation events to notifications

- src/ApiDocs/docfx.json
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9152
Issue with generation of DocFX is that the url is always based on branch on which it was build, it means if branch is not public or was removed the link will be incorrect, to avoid that I think the best solution is to use v8/contrib branch which in most of cases will be containing the code describe with API Docs.
> use v8 branch as default for API Docs

- src/Umbraco.Infrastructure/Extensions/ScopeExtensions.cs
- src/Umbraco.Infrastructure/Scoping/IScope.cs
- src/Umbraco.Infrastructure/Scoping/Scope.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentTypeService.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
This is left over from v8's APIs where we would pass in params int[] but in most cases we are just passing in a single value yet we are then allocating arrays everytime. There's no need to allocate these, it's just extra overhead.
> Stop allocating arrays for every scope lock

- src/Umbraco.Core/Models/EmailMessage.cs
- src/Umbraco.Core/Models/EmailMessageAttachment.cs
- src/Umbraco.Infrastructure/EmailSender.cs
- src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Extensions/EmailMessageExtensionsTests.cs
This is needed for the Forms migration - where we have a needs to send emails with multiple recipient, CC, BCC, reply-to addresses, as well as attachments.  So I've extended the core abstraction and implementation using MimeKit to support these features.
> Added additional addresses and attachments to core's email sending service.

- src/Umbraco.Core/Sync/DatabaseServerMessenger.cs
- src/Umbraco.Core/Sync/ISyncBootStateAccessor.cs
- src/Umbraco.Core/Sync/NonRuntimeLevelBootStateAccessor.cs
- src/Umbraco.Core/Sync/SyncBootState.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
- src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
- src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
- src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
- src/Umbraco.Tests/TestHelpers/TestSyncBootStateAccessor.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
- src/Umbraco.Web/PublishedCache/NuCache/NuCacheComposer.cs
- src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
If there's an existing issue for this PR then this fixes #9779
What?
Lets the PublishedSnapshotService know if the servermessenger is going to cold boot so PublishedSnapshotService does not attempt to load all content and media twice.
Why?
Load content and media only once on cold boot saving significant boot time on sites with large amounts of content/media . Saves on memory as otherwise there is 2 generations of every content and media in memory at boot.
How to test?
Delete the NuCache.db and server sync state text file. The log message about loading content from the database should appear only once.
> Reduce cold boot times by loading content and media only once on cold boot

- src/Umbraco.Web.BackOffice/Extensions/ControllerContextExtensions.cs
- src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
- src/Umbraco.Web.Common/Authorization/FeatureAuthorizeRequirement.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10179
Not sure this is the best way to resolved it, but it is the only solution I was able to find.
This code is inspired by what the [AuthorizationMiddleware](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs) are doing.
It relies on the fact that our `FeatureAuthorizeHandler` are still supporting pre-.NET 5 behaviour, where the resource can be an Endpoint. 🙈
> Fix check authorization policies on nested tree requests

- src/Umbraco.Core/Logging/DisposableTimer.cs
- src/Umbraco.Core/Logging/IProfilingLogger.cs
- src/Umbraco.Core/Logging/ProfilingLogger.cs
Allows for structured logging with the IProfilingLogger.
Prior to this you couldn't use structured logging. Now you can do:
```cs
using(_profilingLogger.DebugDuration<ProfilingLogger>(
"Hello {World}, this is a Structured {Log}",
new object[] { Foo, Bar })) {
// ...
}
```
And there are other overloads for specifying start/end/failed messages and parameters. The behavior when no args are specified will execute the way it normally does.
> Allows for structured logging with the IProfilingLogger

- src/Umbraco.Core/Persistence/Repositories/ITemplateRepository.cs
- src/Umbraco.Core/Services/IFileService.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
- src/Umbraco.Infrastructure/Services/Implement/FileService.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs
There is a bunch of unreferenced/unused (and largely untested) code that originates from `IFileSystem` and spills into various file repositories. This is one of four PRs that aim to clean up all this code.
This PR relates to: **Templates**
See also #9875, #9878 and #9879
> Remove a bunch of template related, unreferenced methods

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
I noticed some styling issues with nested block lists, where the active style also affected all nested block list block elements mainly regarding the caret to visualize the active/open block element.
This happens when using inline mode for both parent and nested block lists.
**Before**
**After**
> Fix issue with active style affected nested block list elements

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
This PR update the icons in listview action dropdown to use `<umb-icon>` component, so if using custom SVG icons for content types, these will work here as well, where it currently only works with font icons.
> Use umb-icon component in listview dropdown

- src/Umbraco.Core/Cache/DefaultRepositoryCachePolicy.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/ConsentRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DictionaryRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RepositoryCacheKeys.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
- src/Umbraco.Web/Cache/ContentCacheRefresher.cs
- src/Umbraco.Web/Cache/MacroCacheRefresher.cs
- src/Umbraco.Web/Cache/MediaCacheRefresher.cs
- src/Umbraco.Web/Cache/MemberCacheRefresher.cs
- src/Umbraco.Web/Cache/RelationTypeCacheRefresher.cs
- src/Umbraco.Web/Cache/UserCacheRefresher.cs
- src/Umbraco.Web/Cache/UserGroupCacheRefresher.cs
This PR backports the fixes made by Shannon in netcore. The commit containing the netcore fixes can be seen here: https://github.com/umbraco/Umbraco-CMS/commit/8326b0428c4698552d3730ddc1167014ce7d5513
Shannon mentioned that there might be some breaking changes, however I was unable to find any since we're changing internal classes, so custom code shouldn't be affected by this.
Before you start testing you need to set up your site to allow members to login, you can follow [this video](https://umbraco.tv/videos/umbraco-v8/content-editor/administrative-content/members/role-based-protection/) if you're unsure how to do it.
1. Create a user that is not approved
2. Login using casing that is not equal to the Login on the member.
* You should not be able to log in because the member is not …
> Backport cache key fix and optimizations

- src/Umbraco.Infrastructure/Security/BackOfficeErrorDescriber.cs
- src/Umbraco.Infrastructure/Security/UmbracoErrorDescriberBase.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs
- src/Umbraco.Web.UI.NetCore/umbraco/config/lang/en_us.xml
Implementing the following error describers:
- BackOfficeErrorDescriber
- MembersErrorDescriber
By using our own translation engine, `ILocalizedTextService`,  to return localized error message from identity correctly.
Translation keys that were missing for the specific methods of error describers are added to the default language file **en_us.xml**.
---
- Every time the IdentityErrorDescriber methods mention "role" we refer to it as _group_;
- For **RecoveryCodeRedemptionFailed** I used `login/resetCodeExpired` key which I found similar to the original description `Recovery code redemption failed`. Let me know if you think that we should add a new key for that!;
- I saw that we use both  member role and member group when referring to members but I kept it as _group_ as I wasn't sure;
- …
> V9: Implementing Error Describers for translated error messages

- src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
Block List Editor and Nested Content will most likely freeze when having complex data sets in multiple levels.
The freeze happens cause `collectAllFormErrorsRecursively` runs too often and might get into an infinite loop. Most likely cause it was ran by a AngularJS `$watch`, which means it would be called a lot.
There seem to be no reason to use this recursive count of errors in the `$watch` method as the `$invalid` property also informs whether a form is valid(including child forms validity)
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9667
and https://github.com/umbraco/Umbraco-CMS/issues/9360
The previous attempt on this is still valid, but this fix is needed for more complex situations.
https://github.com/umbraco/Umbraco-CMS/pull/9677
**Test notes:**
- Make a ElementType with a …
> Block List and Nested Content browser performance problem - don't run heavy count method on `$watch`

- build/templates/UmbracoProject/.template.config/dotnetcli.host.json
- build/templates/UmbracoProject/appsettings.Development.json
- build/templates/UmbracoProject/appsettings.json
- src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
* Fixes the dotnet new template issue due to non escaped quotes
* Sets the default in code to HideTopLevel to true
* Explicitly add JSON schema URL to appsettings in case IDEs do no auto map it for the user
> Netcore: dotnet new template updates and change HideTopLevelNodeFromPath default value to `true`

- src/Umbraco.Web.UI.Client/gulp/tasks/js.js
- src/Umbraco.Web.UI.Client/gulp/util/processJs.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10200
See the linked issue (https://github.com/umbraco/Umbraco-CMS/issues/10200) for steps to reproduce. Note that this issue only happens for production builds (minified JS).
This PR prevents the JS minification from changing class and function names during compression. At the moment we need those names for locating dependencies up the scope chain (by magic strings).
Unfortunately the current JS build setup is a bit silly, so minification happens in two places. Thus this change has to be applied in both places. This took me a bit to realize, so I have added a comment in both places, referring them to their respective counterparts for future changes.
> Do not change function and class names when minifying JS

- src/Umbraco.Core/HealthChecks/Checks/Configuration/MacroErrorsCheck.cs
- src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
- src/Umbraco.Web.UI.NetCore/appsettings.json
Minor changes to appsettings and MacroErrorsCheck healthcheck
Changed the default appsettings:umbraco:cms:contentMacroErrors from '**t**hrow' => '**T**hrow'.
Changed the strings in `MacroErrorsCheck => Values`, to the `MacroErrorBehaviour `enum counterparts
> Casing in appsettings:umbraco:cms:contentMacroErrors and using MacroErrorBehaviour Enum

- src/Umbraco.Core/Packaging/CompiledPackageXmlParser.cs
Fixes issue with hardcoded '\\' as directory separator char. This caused all files in packages to be restored in the root folder with '\\' in the filename on Linux.
I tested the new beta version of Umbraco 9 on Linux. When I install any package, for example by clicking on install in the forms tab, then I get an install which results in the attached screenshot of the folder listing:
Of course I also tested this patch. With this patch any package will install into the right folders. The forms plugin ends up in the App_Plugins folder. Please see:
> Fix issue with hardcoded '\' as directory separator char.

- src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
When toggling UrlTracker in the backoffice, WebRouting:DisableRedirectUrlTracking is set as a string 'true'/'false' in appsettings.json.
Changed to a bool
> appsettings "WebRouting:DisableRedirectUrlTracking" should be a bool

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
fixes https://github.com/umbraco/Umbraco-CMS/issues/9663
The issue is that the angularJS scope when opening an infinite editor after the language switch did reference the old $scope of the property editor.
*How did that come?* well, we gave the Block Objects references to the property editor, so it easily can perform actions like Edit, Delete etc. But as the Block Objects are bonded to their data, so they can persist across variant-editors for runtime performance on editing content in split view, then we now have Block Objects that are specific for a property editor, though it could be used by several.
In the above case, the problem was made clear as the property editor reference initially baked into the Block Object wasn't alive anymore and the scope retrieved for complex validation is …
> Update block objects property editor references

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
This adds back the same SourceLink debugging feature we have on Umbraco V8
https://github.com/dotnet/sourcelink
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
Use the powershell build script in the repo in the build folder ./build.ps1
Use the GUI tool to verify if the SourceLink metadata is linked correctly
The [GUI tool on the Microsoft store](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwja09mrlbDwAhWeUhUIHaSQDgcQFjAAegQICRAD&url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fp%2Fnuget-package-explorer%2F9wzdncrdmdm3&usg=AOvVaw0dK0C_SayAFfBZduzGi693) helps to visualise & verify if SourceLink meta data has been included correctly.
If its correctly enabled it will show a green checkmark next to it in the left hand side …
> Netcore: V9 Enable Microsoft SouceLink Debugging Feature

- src/Umbraco.Infrastructure/Media/ImageDimensionExtractor.cs
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- Replaces `System.Drawing` with `ImageSharp`, and thereby fix TODO.
- Go to the media section and upload files of different types.
- The following formats are supported
- GIF : GifDecoder
- PNG : PngDecoder
- BMP : BmpDecoder
- JPEG : JpegDecoder
- TGA : TgaDecoder
> Replaces System.Drawing with ImageSharp, and thereby fix TODO.

- src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
- src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs
Reintroduce missing friendly `GetCropUrl` extensions by using the internal service locator to inject the required services.
> V9: Reintroduce missing friendly get crop url extensions

- src/Umbraco.Core/Models/PublishedContent/PublishedContentModel.cs
- src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs
- src/Umbraco.Core/Models/PublishedContent/PublishedElementModel.cs
- src/Umbraco.Core/Models/PublishedContent/PublishedElementWrapped.cs
- src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
- src/Umbraco.Tests.Common/Published/PublishedSnapshotTestObjects.cs
- src/Umbraco.Tests.Common/TestHelpers/SolidPublishedSnapshot.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Published/NestedContentTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ModelBinders/ContentModelBinderTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Views/UmbracoViewPageTests.cs
- src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
- src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10232
- Fixed issue with ModelsBuilder that was failing when you created inherited doc types
- Create an inherited doc type:
- Create some content with that nested doc type (HomePage in the image)
- Ensure you can use ModelsBuilder properties from both the child and parent doc type (Layout and Homepage in the image)
> V9: Bugfix for modelsbuilder when having inherited doctypes

- build/templates/UmbracoProject/Properties/launchSettings.json
- src/Umbraco.Web.UI.NetCore/Properties/launchSettings.json
Adds in the missing launchBrowser property to the launchSettings.json and also adds inline JSON Schema property so you can get intellisense to add the full blown IIS profile if you want to as well.
This should fix the problem that @crgrieve had at last nights learn-athon
> V9 Netcore: Fix missing launch browser param for dotnet run from template

- src/Umbraco.Core/PublishedCache/DefaultCultureAccessor.cs
- src/Umbraco.Infrastructure/Services/Implement/UserService.cs
Fixed some bugs that were caused by us saving the runtime level in the ctor, before it was determined.
1) You can use the debugger and ensure the runtime level is now not `Unknown` anymore.
2) You can change the default language and use a dictionary item in a view. Then you will now see the correct default language from the service is used instead of the one in config.
> V9: Do not save runtime level in ctors

- src/Umbraco.Web.UI.Client/src/main.controller.js
Feels a bit weird that the **Update available** link opens in the same window, so I've set the `target` option to `_blank`.
> Added target="_blank" to "Update available" link

- build/NuSpecs/UmbracoCms.Web.nuspec
- src/Umbraco.Examine/Umbraco.Examine.csproj
- src/Umbraco.Examine/UmbracoExamineIndex.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- src/Umbraco.Web/Umbraco.Web.csproj
And removes ExecutionContext workaround since it's part of Examine now.
> Updates to Examine 1.2.0

- src/Umbraco.Core/Composing/WeightedCollectionBuilderBase.cs
- src/Umbraco.Tests/Composing/CollectionBuildersTests.cs
- src/Umbraco.Web/Dashboards/DashboardCollectionBuilder.cs
Inspired by the PR of @kjac (https://github.com/umbraco/Umbraco-CMS/pull/8628), I moved the SetWeigth logic to the WeightedCollectionBuilderBase. I think this is a better place to put this as it's something that should work with all weighted collections, not just the dashboards.
Also added a test for it.
The same code as in the other PR can be used to test this:
```
using Umbraco.Core.Composing;
using Umbraco.Web;
using Umbraco.Web.Dashboards;
namespace Test
{
public class TestDashboardComposer : IUserComposer
{
public void Compose(Composition composition)
{
// place the "Redirect URL Management" dashboard before the "Getting Started" dashboard
composition.Dashboards().SetWeight<Umbraco.Web.Dashboards.RedirectUrlDashboard>(5);
}
}
}
```
> Move the SetWeight logic to WeightedCollectionBuilderBase

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
This fixes #10193 
1. Start with a fresh install with the starter kit
2. Navigate to Home and edit the page
3. Remove the existing call to action link, and add a new one
4. Navigate into the People list view
5. Type in "Hello", or anything that won't match a person in the list
6. View now correctly shows `Sorry, we can not find what you are looking for.`
> #10193 The listview search within a dialog (eg. minilistview) shows the loading indicator forever for zero results

- src/Umbraco.Core/Persistence/Repositories/IFileRepository.cs
- src/Umbraco.Core/Persistence/Repositories/IFileWithFoldersRepository.cs
- src/Umbraco.Core/Persistence/Repositories/IPartialViewRepository.cs
- src/Umbraco.Core/Persistence/Repositories/IScriptRepository.cs
- src/Umbraco.Core/Persistence/Repositories/IStylesheetRepository.cs
- src/Umbraco.Core/Persistence/Repositories/ITemplateRepository.cs
- src/Umbraco.Core/Services/IFileService.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/FileRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ScriptRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
- src/Umbraco.Infrastructure/Services/Implement/FileService.cs
As the title says, this PR is adding in some methods that weren't migrated from V8, and presumably not needed in CMS, so they are available for use in Deploy.
I've done a little tidy-up but mostly the code is just a copy from V8.
They can be tested in views for example with:
```
@inject Umbraco.Cms.Core.Services.IFileService FileService
<p>File size: @FileService.GetPartialViewFileSize(@"C:\Repos\Umbraco\Umbraco-CMS-V9\src\Umbraco.Web.UI.NetCore\Views\Partials\ChildDocType.cshtml")</p>
```
> Re-implemented various file service methods from V8 required in Deploy.

- build/templates/UmbracoProject/UmbracoProject.csproj
- src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
- src/Umbraco.Web.Common/ModelsBuilder/PureLiveModelFactory.cs
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Fixes #10213 When the models folder is included in the project the cs files have a Build Action of 'C# compiler' so they can be used in code.
As a bonus, I have fixed a couple of comments that indicate the right models' location.
> V9 - Include models folder in the project

- src/Umbraco.Core/Deploy/ArtifactBase.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs
In this PR I've removed the `[DataContract]` attribute added on `ArtifactBase` in the migration from V8 to V9, which has the effect of making all properties on derived artifacts opt-in.
And then handled the omission of the checksum value from the serialized string without taking a Json.Net dependency.
With this included and the Deploy dependency on CMS updated, that should resolve the serialization issues that would otherwise need all properties marked to opt them into serialization, and revert to the V8 behaviour where this isn't necessary.
Have verified with a test that the previous behaviour and the new with regards serialization is the same.
> Updated serialization defaults for ArtifactBase

- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
Ensures that language is available before testing on the properties of it.
test-notes etc can be found on issue:
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10274
Follow the instructions in this PR to get segments set up: #7973
> #10274 Variant sorting should take into account that there might not be any language

- build/azure-pipelines.yml
- src/Umbraco.Web.UI.Client/package-lock.json
- Have version in the generated artifact name
- Use same pipeline for nightly builds and release builds
- The new format is:
- Nightly builds (If source branch is NOT a release format)
-  e.g Version becomes `9.0.0-preview20210517.63720`  => Artifacts becomes `9.0.0-preview20210517.63720.63720` 
- Release builds  (If source branch is a release format)
-  e.g Version becomes `9.0.0-beta003` => Artifacts becomes `9.0.0-beta003.63720` 
- Also adding Azure Pipeline tags to the builds:
-  `Continuous build` vs `Release build`. These can be used to filter releases
- Please `squash and merge` instead of just `merge`. Azure Pipeline manipulations required a couple of attempts 🙈
> Update version and artifact name generated by azure pipeline

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
When closing the Save & Publish dialog on variant content, we see an issue in the consol about `infiniteEditors` being `undefined`.
This PR fixes general potential issues with infiniteEditors not being present.
I've tested my known case, but it seems there is an extensive amount of testing needed to verify that the original PR works as it should, so please find inspiration here.
The original PR is here: https://github.com/umbraco/Umbraco-CMS/pull/8522
> #10274 Variant sorting should take into account that there might not be any language (#10278)

- src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
Acquire the maindom before we do unattended installs
- Do unattended install. Before it fails with "Register called when MainDom has not been acquired"
> Bugfix: Acquire the maindom before we do unattended installs

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/prevalue/mediapicker3.crops.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/prevalue/mediapicker3.crops.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
With the new Media Picker v3 it is possible the added crops in the configuration. However if added multiple and where some of these "rows" are empty it wasn't possible the save the datatype, because of the validation.
So you would either have to fill in some dummy data temporary or refresh page, but could then potentially loose already defined crops.
These changes add a option to remove/cancel a crop row.
@madsrasmussen @nielslyngsoe
> Add option to remove/cancel added crops

- src/Umbraco.Infrastructure/Scoping/IScopeProvider.cs
- src/Umbraco.Infrastructure/Scoping/Scope.cs
- src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
- src/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Scoping/ScopedNotificationPublisherTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/LogScrubberTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Mapping/MappingTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Allows a custom `IScopedNotificationPublisher` to be injected into a scope using the `IScopeProvider.CreateScope` method.
The logic is very much the same as for the `IEventDispatcher`, not allowing you to set it anywhere but the outermost scope, I know we talked about allowing a custom publisher in inner scopes as well for a NoOpPublisher, to suppress events, but this requires some more changes on how we handle the notifications, and I think that should be a separate task. This change shouldn't compromise our ability to do that later though.
We also talked about removing the `IEventDispatcher`, but thinking more about it, I'm not sure that's the best idea, wouldn't it make it quite a bit harder to port over custom code where you might still use (and want to use) the old event pattern for …
> V9: Allow custom notification publisher in scope

- src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
If there's an existing issue for this PR then this fixes #10300 
Method name in ContentController was updated to GetEmptyBlueprint, reference in content.resource.js was updated too, but looks to have reverted at some point since, because managing merges across two diverging branches must be lots of fun.
Change here fixes the reference in the javascript - `GetEmpty` becomes `GetEmptyBlueprint`
To test, create a content blueprint, then create content using that blueprint - should see no errors and new content is created as expected, using the template.
> Fix getBlueprintScaffold endpoint

- src/Umbraco.Web/Cache/DataTypeCacheRefresher.cs
The results of this issue have been reported a couple of times on the Deploy tracker: issues [49](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/49) and [34](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/34).
The issue manifests itself by when data types are updated via Deploy, their old values are cached and not updated until a website restart. I found I could fix this by getting a reference to the appropriate "isolated cache" and clearing by key, but for other entities we don't have to do this - instead relying on the cache refreshers in core.
Then seeing this it looked like whilst we were clearing caches for related entities - e.g. content and content types - we weren't clearing for the data type itself.
If you compare e.g. `MemberCacheRefresher` and …
> Fixed issue with data types not being cleared in cache refresh operations,

- build/templates/UmbracoProject/.template.config/template.json
- build/templates/UmbracoProject/UmbracoProject.csproj
Fix for invalid chars used in dotnet new templates creations to ensure namespace is valid & compiles
* Try the dotnet new template pack before this PR with a name `Umbraco-v9-2021-05-12`
* `dotnet new umbraco --name Umbraco-v9-2021-05-12`
* This will fail to build due to invalid namespace if you do a `dotnet build`
* Install/update new dotnet template pack and retry with the same command & verify it makes the namespace safe & builds
* Retry with various other characters that could make unsafe namespace, perhaps with spaces
* `dotnet new umbraco --name "Umbraco v9 2021 05 12"`
> NETCore: Fix dotnet new template for safe namespaces

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/obsoletemediapickernotice.html
- src/Umbraco.Web/PropertyEditors/MediaPickerConfiguration.cs
This is in relation to #10308, please read that first.
Which looks like this:
> Shows a warning for people tempted to switch from the Obsolete to the new MediaPicker(v3)

- src/Umbraco.Core/Mail/IEmailSender.cs
- src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
- src/Umbraco.Core/Notifications/SendEmailNotification.cs
- src/Umbraco.Infrastructure/EmailSender.cs
- src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
In V8 we had an event you could listen to `EmailSender.SendEmail`, if this event had a handler registered, and `EmailSender` was constructed with enableEvents set to true, we would raise the event if the SMTP was not configured.
This PR reinstates this using notifications instead since it's used in deploy.
Since EmailSender is now registered in DI, I created an overload for `SendAsync` instead which accepts the bool, looking through V8 I can see that this was only used for `UsersController.SendUserInviteEmailAsync`, so I've set enableNotifications to true there.
`CanSendRequiredEmail()` now also returns true if there is a notification handler for `SendEmailNotification` registered, same as V8.
To test this I first just ran the site normally and made sure that `CanSendRequiredEmail()` …
> Enable email sender to publish an event if smtp is not configured

- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.less
This PR makes changes to allow using a custom SVG in block list editor in block card and the default views for block list editor.
> Support custom SVG icon in block list editor

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
- src/Umbraco.Core/WebAssets/CustomBackOfficeAssetsCollection.cs
- src/Umbraco.Core/WebAssets/CustomBackOfficeAssetsCollectionBuilder.cs
- src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
- src/Umbraco.Infrastructure/WebAssets/PropertyEditorAssetAttribute.cs
If there's an existing issue for this PR then this fixes #10293
This allows the bundle to be added to using C# from a composer or an extension on IUmbracoBuilder. An example of how this code would be used by a developer.
```
// injected or extended
// IUmbracoBuilder builder;
builder.BackOfficeAssets()
.Append<MyCustomJsFile>()
.Append<MyCustomCssFile>();
public class MyCustomJsFile : JavaScriptFile
{
public MyCustomJsFile() : base("/abc.js")
{
}
}
public class MyCustomCssFile : CssFile
{
public MyCustomJsFile() : base("/my-styles.css")
{
}
}
```
The files in the example are within wwwroot
Thanks
Matt
> Add a collection to allow adding CSS and JS to the back office via C#

- src/Umbraco.Core/Sync/DatabaseServerMessenger.cs
- src/Umbraco.Core/Sync/DatabaseServerMessengerOptions.cs
- src/Umbraco.Core/Sync/ISyncBootStateAccessor.cs
- src/Umbraco.Core/Sync/NonRuntimeLevelBootStateAccessor.cs
- src/Umbraco.Core/Sync/SyncBootState.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
- src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
- src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
- src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
- src/Umbraco.Tests/TestHelpers/TestSyncBootStateAccessor.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/BatchedDatabaseServerMessenger.cs
- src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
- src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComposer.cs
- src/Umbraco.Web/PublishedCache/NuCache/NuCacheComposer.cs
- src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
- src/Umbraco.Web/Search/ExamineFinalComponent.cs
- src/Umbraco.Web/Umbraco.Web.csproj
This fixes #8893 and refactors #9859.
* Moves logic for cold boot into the components responsible for what needs to happen in cold boot. This used to be in callbacks in DatabaseServerMessenger.
* Removes the callbacks from DatabaseServerMessenger and obsoletes these callbacks.
* Ensure examine rebuilds don't occur until the first http request is done instead of on a timer which could be problematic with cold boots. A reason for the #8893 can be that during cold boots, the cold boot processing would take more than 5 seconds and then after those 5 seconds indexing occurs and this will happen before custom components execute that customize those indexes.
* PublishedSnapshotService now only initializes lazily when it's needed.
* Removes BatchedDatabaseServerMessenger.Startup, startup logic is …
> Fix startup issues and timing with Examine and Nucache

- src/Umbraco.Web.UI.Client/src/less/components/card.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
- src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-child-selector.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-grid-selector.html
- src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10340
When using custom SVG icons these were not show in `<umb-child-selector>` component.
Furthermore this PR also replace the search filter markup with `<umb-search-filter>` component.
The compass icon is a custom font icon from my [Material Design Icon Pack](https://our.umbraco.com/packages/backoffice-extensions/material-design-icon-pack/), the coffee icon a custom SVG icon and the rest Umbraco core icons.
---
_This item has been added to our backlog [AB#12146](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12146)_
> Support custom SVG icon in umb-child-selector component

- src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
If using a custom SVG icon for a user group this wasn't shown in user group filter.
> Support custom SVG icon in user group filter

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
If using a custom SVG icon this wasn't shown in Nested Content. With a few adjustments this can be supported although the newer Block List editor probably is preferred on new projects.
> Support custom SVG icon in Nested Content

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js
I noticed that the example on https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbTable is actually not working. items should be replaced with vm.items.
> Updated umbtable.directive.js for a working example

- src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
Datetime values where converted to date(102) so sorting by time does not work.
By converting to 120 (yyyy-mm-dd hh:mi:ss (24h)) the time is respected.
If there's an existing issue for this PR then this fixes #10405
I've changed the ConvertDateToOrderableString in SqlSyntaxProviderBase from 
`"CONVERT(nvarchar, {0}, 102)";` which converts to yyyy.mm.dd
to
`"CONVERT(nvarchar, {0}, 120)" `which converts to yyyy-mm-dd hh:mi:ss (24h)
so that de time is respected when sorting.
I'm not sure if this will affect other parts of Umbraco. That's why please take a critical look.
> Convert date to datetime in SQL queries for sorting on date

- src/Umbraco.Web.UI.Client/src/views/content/copy.html
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
Added some danish translations and fixed a translation problem in the copy document.
I fixed a problem where English text was shown before the translated text when copying a node:
I have added some keys to the Danish translation document da.xml . The keys were found by looking at missing keys when comparing en-us.xml and da.xml . Therefore the changes can be found in multiple places. Here are some examples:
When scheduling a publish
Error when scheduling a publish
> Added danish translations and fixed a translation issue

- src/Umbraco.Core/Migrations/IMigrationPlanExecutor.cs
- src/Umbraco.Core/Migrations/MergeBuilder.cs
- src/Umbraco.Core/Migrations/MigrationPlan.cs
- src/Umbraco.Core/Packaging/PackageMigrationPlan.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
- src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/Upgrader.cs
- src/Umbraco.Infrastructure/RuntimeState.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/AdvancedMigrationTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/PostMigrationTests.cs
No logic changes, just shifting around responsibilities. Now we can have the MigrationPlan as part of the core project and a separate IMigrationPlanExecutor. 
A bunch of code cleaned up as well like injecting services where it makes sense and removing some code that was not used.
> Refactor MigrationPlan to separate the executor from the plan itself.

- src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
Fixes #10391 
This adds in a missing overload for IsAllowedTemplate that allowed you to simply pass the template alias
See the notes in 10391 about testing as out of the box in V8 and V9 it will not work until you turn on `ValidateAlternativeTemplates` to true in `WebRouting` for AppSettings configuration.
* Ensure you update your appsettings.config as noted above
* Create a home doctype with matching template
* Use this in the Razor view/template
```
@if(Model.IsAllowedTemplate("home"))
{
<h2>YEP</h2>
}
else {
<h2>NOPE</h2>
}
```
Then modify it to an invalid string that wont be found as a template
> V9: add missing overload is allowed template

- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
I spottede while playing around with MultiUrlPicker that the Link overlayer had a HTML symantic error.
While in the big picture is does not matter, but my screen reader, did a little hike up on over it.
> HTML Symantic error UL > LI >LI changes to UL > LI > UL > LI

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10430
Very small issue. The disabled attribute was mispelled.
> 10430: Fix typo

- src/Umbraco.Web.Common/ApplicationBuilder/IUmbracoApplicationBuilder.cs
- src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs
We need to split some interfaces here since this is possible but it shouldn't be:
```cs
app.UseUmbraco()
.WithWebsite()
```
The WithWebsite and WithBackOffice should only be allowed within the WithMiddleware like 
```cs
app.UseUmbraco()
.WithMiddleware(u =>
{
u.WithBackOffice();
u.WithWebsite();
})
.WithEndpoints(u =>
{
u.UseInstallerEndpoints();
u.UseBackOfficeEndpoints();
u.UseWebsiteEndpoints();
});
```
but due to how the inheritance works the previous is still possible.
> Fix interface inheritance

- build/templates/UmbracoProject/Properties/launchSettings.json
When looking at .NETCore own MVC template I noticed a new property in the Kestrel launchsettings which is undocumented
https://github.com/dotnet/aspnetcore/blob/v6.0.0-preview.5.21301.17/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Properties/launchSettings.json#L22
Doing a bit of quick googling I came across the issues that talk about this issue and implement it
https://github.com/dotnet/sdk/issues/12227
https://github.com/dotnet/sdk/pull/12581
* Create a project with `dotnet new umbraco`
* In same terminal change to directory
* Run `dotnet run` (As noted in the PR it can take a little while before you get output)
* Build template from build.ps1
* Uninstall existing template pack
* Install new template pack from build.out
* Re-test and note you get a message …
> Adds dotnetRunMessages flag to launch settings for Kestrel

- src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
- src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
This PR fixes two small issues:
- Fix exception in ReportSiteTask.cs, when running multiple times..
- The `s_httpClient.BaseAddress` and `s_httpClient.Timeout` cannot be changed after it has executed a request (This is the case every day)
- Fix issue with recurring tasks that was executed too often.
- Due to a recent fix for not executing long running tasks in parallel, another bug was introduced. So basically we executed the recurring jobs after `delay`, and then again after `delay` instead of `period`.
> V9: Fix issue with recurring services that executes too often

- src/Umbraco.Core/Notifications/UmbracoApplicationComponentsInstallingNotification.cs
- src/Umbraco.Core/Notifications/UmbracoApplicationMainDomAcquiredNotification.cs
- src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
These two notifications have been added to provide hooks for functionality that may need to run earlier in the boot process.
Specifically I'm looking to lay the ground for the migration of [this class](https://github.com/umbraco/Umbraco-Deploy/blob/v4/dev/Umbraco.Deploy.Cloud/Initializing/CloudInitializer.cs) (and the ones it depends on) in Deploy.
For more details see the [related Deploy PR](https://github.com/umbraco/Umbraco-Deploy/pull/558).
> Added two further notifications to the boot process.

- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
This PR fixes #10401 where you was unable to change your own password if using the user section.
If you used the avatar approach this was fine as it uses a different Controller Action to do so.
* Try before PR to change your own user password in the user section
* Logout and try to login with new password (it will fail)
* Verify password can be changed with the avatar approach top right
* Apply PR and re-test to see if password can be changed in user section
> Bugfix Allow you to change your own password if using user section

- src/Umbraco.Tests/Cache/DistributedCacheBinderTests.cs
- src/Umbraco.Web/Cache/DistributedCacheBinder.cs
This PR is an attempt to mitigate some issues reported on Umbraco Cloud with deployment operations containing document type changes and large databases (either numbers of nodes, versions or both).
I've observed from logs that there are repeated calls to reload the content and media cache - twice for every document type in the deployment batch - so with 5 document types, there are 10 full reloads.
This seems unnecessary - as when a document type changes _all_ content is reloaded.  There's no logic to refresh parts of the cache for different document types, hence it seems we don't really care which document type has been updated in this context, just that one has.
So I've amended the logic for refreshing the cache to handle only single content type event, even if there are several.
I …
> Avoid repeated reloads of content and media cache following Deploy operations.

- src/Umbraco.Web.UI.Client/src/views/common/dashboard.controller.js
Merged v8 and rolled back the unattended install users, as this was original implemented in v9
> V9: Merge v8/dev

- src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
Moves extension methods from `HtmlHelper` to `IHtmlHelper`, so they work out of box in views..
> Moves extension methods from HtmlHelper to IHtmlHelper

- src/Umbraco.Core/Events/SendEmailEventArgs.cs
- src/Umbraco.Core/HealthChecks/NotificationMethods/EmailNotificationMethod.cs
- src/Umbraco.Core/Mail/IEmailSender.cs
- src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
- src/Umbraco.Core/Models/Email/EmailMessage.cs
- src/Umbraco.Core/Models/Email/EmailMessageAttachment.cs
- src/Umbraco.Core/Models/Email/NotificationEmailAddress.cs
- src/Umbraco.Core/Models/Email/NotificationEmailModel.cs
- src/Umbraco.Core/Notifications/SendEmailNotification.cs
- src/Umbraco.Infrastructure/EmailSender.cs
- src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs
- src/Umbraco.Infrastructure/Services/Implement/NotificationService.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Extensions/EmailMessageExtensionsTests.cs
- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
This PR adds a new email model to be sent with email notifications.
The reason for this is to be able to both send the email address and the email display name, since this is used in Deploy.
I opted to add a new model instead of trying to change the old one, since it doesn't make much sense for that to have the display name, since it gets converted into a MimeMessage down the line.
While I was working on this I also noticed that we added the ability to fall back to a "from email" from the configuration, however the way the code currently was, the configured "from email" was never used, so I've also amended the code so that is no longer the case.
> V9: Add new email Model for notifications

- src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js
- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
This PR updates the display of packages in the back-office to add a "Certified to work on Umbraco Cloud" flag to the packages with this setting in our (now that this info is available in the our API).
The listing has been updated to add this indicator:
And the details screen to show this:
I've also hidden the "Umbraco Pro", which is empty for V8 and contains little for V7, to remove what for most people in an empty category and a concept/name that no longer exists (to my knowledge).
> Added "certified to work on Umbraco Cloud" indicator to packages section in the back-office

- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
This updates to latest Smidge which is now on Nuget and updates how package assets are delivered when in debug mode. This is based off of some discussions like https://github.com/umbraco/Umbraco-CMS/discussions/10469
> Disable composite files for package files when in debug mode. This means that the files will be delivered as-is without being processed but will contain the cache buster value. This is more like how v8 worked. This just makes it simpler for all package source debugging since you'll just be working with the raw files. I realize that the way it is now is not great for various reasons: Even if source maps worked, etc... the minify engine will remove debugging statements like debugger; or possibly even logging statements which is not good for debugging. I'm sure nuglify could …
> Updates to latest smidge and changes how debug assets work

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10429
On normal load, the code will pass through the filtered property set (https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js#L548). However, this doesn't occur when the results come from the search. I added the same logic to the search results.
> Fix: Searching in mediapicker doesn't filter according to allowedtypes #10429

- src/Umbraco.Web.UI.NetCore/Views/Partials/blocklist/default.cshtml
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10508
Currently Visual Studio shows a warning regarding the use of `@Html.Partial()` as it may result in application deadlocks.
It seems we can render the component async in .NET Core:
https://stackoverflow.com/questions/50774702/should-i-change-html-partial-to-html-partialasync-as-visual-studio-suggest/52723364#52723364
> Render Block List component partial async

- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/bootstrap3-fluid.cshtml
- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/bootstrap3.cshtml
- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/editors/base.cshtml
- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/editors/media.cshtml
- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/editors/rte.cshtml
While working on https://github.com/umbraco/Umbraco-CMS/pull/10511 I also noticed some partials in grid wasn't rendered async, but we did it for macro grid editor.
https://github.com/umbraco/Umbraco-CMS/blob/v9/9.0-beta004/src/Umbraco.Web.UI.NetCore/Views/Partials/grid/editors/macro.cshtml#L12-L14
The grid editors seems to render as expected on frontend. I guess it would also improve the performance a bit in backoffice when rendering previews of many grid editors.
> Render grid editor partial async

- src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
- src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentService.cs
Fixes #10394.
The issue was a couple injected `null`s was handled like "no nothing" instead of "clear all" as the XML docs describe.
Steps to test in the issue #10394..
> V9: Fixes issue with "Rebuild" nucache not doing anything

- src/Umbraco.Core/Models/MediaWithCrops.cs
- src/Umbraco.Core/PropertyEditors/ImageCropperConfiguration.cs
- src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs
- src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
- src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs
- src/Umbraco.Web/ImageCropperTemplateExtensions.cs
- src/Umbraco.Web/PropertyEditors/MediaPicker3Configuration.cs
- src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
- src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
- src/Umbraco.Web/UrlHelperRenderExtensions.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10308, https://github.com/umbraco/Umbraco-CMS/issues/10402 and https://github.com/umbraco/Umbraco-CMS/issues/10397.
Building upon PR https://github.com/umbraco/Umbraco-CMS/pull/10517 that introduces backwards compatibility for the stored data format between `Media Picker (legacy)` (v2) and the new `Media Picker` (v3), this PR adds compatibility to the returned models on the front-end (and includes some additional improvements).
This compatibility is added by making `MediaWithCrops` inherit from `PublishedContentWrapped`, making it an `IPublishedContent` instance again, so the following Razor/view code won't break by switching to the new picker:
```cshtml
@if (Model.Image is …
```
> Improvements to media pickers/crop handling and URL generation

- src/Umbraco.Core/Services/IContentService.cs
- src/Umbraco.Core/Services/Implement/ContentService.cs
- src/Umbraco.Web/Editors/ContentController.cs
- src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
This is a continuation of #10235, here I try to reduce the number of SQL queries used when rendering blocklists when adding new content. A lot of the queries and time spent came from mapping the empty `Content` to a `ContentItemDisplay` 
There were some low hanging fruit namely I: 
* Added a new `Create` overload to the content service which takes a content type instead of a key. Before we would get all the content types through the content type service, only to pass it to `GetEmpty` where we would then call `ContentService.Create` with the content type alias, only for the content service to then get the content type object one more time. Now we just pass the content type to `Create` which then uses it to create new content.
* Changed it so if we map something that's an element type we …
> Reduce sql queries when rendering blocklists in the content panel

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.controller.js
This PR fixes some of #10538
This fixes links that were broken when running Umbraco on Linux due to the case-sensitive file directory.
The links are used in the grid editor (This is a picture of the current behavior):
> Fix grid property editor view urls

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/textstring.html
In this tiny PR I have added the `id` attribute setting the value to the `model.alias` so click the associated label will behave as expected. The effect of the change can be seen in the GIF below.
> Textstring prevalue editor view: Set id attribute

- .github/CONTRIBUTING.md
Having had an older version of visual studio running I've been unable to build the source without making changes to the solution. However, upgrading to at least VS 16.8 has meant those changes haven't been required. This is to do with how the language target "latest" was working.  
Propose upping the min version listed here to avoid build issues being raised.
> Update contributing.md Visual Studio min version

- src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
- src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.editor.html
Scenario: 
When two nested content property editors are nested inside each other, and the inner nested content is set to mandatory. All properties inside the inner nested content will be marked with an asterisk (*). Validation doesn't kick in though.
_Before: Text 4 is not set to mandatory_
_After:_
The PR fixes so only mandatory properties are marked with an asterisk (*).
#10520
> #10520 Correct mandatory markers in nested content

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
This fixes #10520
The description of the above issue doesn't cover exactly whats going on. But from my investigation the problem appears when the Nested Content property is set to vary by culture. If so any server-side validations will not be binded correctly with the form fields, therefor its not possible to revalidate the fields by changing the value of the field. (since the field isn't connected to the server-side validation-message).
In order to fix this we needed the property to have the right culture, this was already solved in Block List Editor, so using the same approach. Parsing the NC property culture to each property of the scaffold model of each Element Type in Nested Content makes this work.
Test notes:
All tests are with a document type with a Nested Content property which …
> #10520 ensure property culture in Nested Content

- src/Umbraco.Web/CacheHelperExtensions.cs
We don't want unpublished items in cached views - possible leak to live site. Show previews using normal partial view instead.
This PR fixes #10384 
This adds a check to see if running in preview mode and using the normal non-cached partials if it is. 
The cachehelper already has a check for whether debugging is enabled and have extended this approach to allow for in-preview mode.
Due to the debugging check, you do need to remember to set debug="false" to test.
> Disable cached partials if in preview mode

- src/Umbraco.Tests.Integration/Umbraco.Web.Website/Routing/FrontEndRouteTests.cs
- src/Umbraco.Web.Common/Extensions/EndpointRouteBuilderExtensions.cs
- src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
When you created a surface controller in V8 with the `[PluginController("SomeArea")]` attribute, the surface controller would be routed like `/umbraco/{areaname}/{controllername}/{action}/{id}`, however in V9 we don't account for area names when creating the pattern, so even if you have the attribute your plugin surface controller will be routed like a normal surface controller I.E: `/umbraco/surface/{controllername}/{action}/{id}`, which might cause issues since a plugin controller might clash with a locally declared one.
I noticed that we handle this with front end API's, so I've applied the same kind of logic to the normal surface controller routing, so now a surface controller with the plugin controller attribute will be routed the same way as in V8.
I've also added an integration …
> V9: Route plugin controllers by area

- src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
As discussed at https://github.com/umbraco/Umbraco-CMS/pull/10233 I have added 3 extensions to UrlHelper. The first 2 are friendly extension methods, they could both be dropped as all could be done with the 3rd method accepting the IPublishedContent and all the other parameters
There are a few other methods in v8 such as the string method but I think these should be removed as they were added over time for compatibility https://github.com/umbraco/Umbraco-CMS/blob/809fd819821770472dec3eb2d7241f7d39f3c918/src/Umbraco.Web/UrlHelperRenderExtensions.cs#L217
> Add missing UrlHelper GetCropUrl methods

- src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
Following on from issue #6417.
The "user-dialog" dashboard, (that appears in the app header, by clicking on your user's avatar), does not render. I have amended the markup of the `user.html` view to make it work.
To test this, follow the steps to [create a custom dashboard](https://our.umbraco.com/documentation/tutorials/Creating-a-Custom-Dashboard/), make sure to set the `"sections"` to `"user-dialog"`.
> Fixed "user-dialog" dashboard markup

- src/Umbraco.Web.UI.Client/src/less/components/umb-color-swatches.less
While implementing a recent site I noticed that the color swatch label can break a little bit if the text is longer than the swatch width allows. This tiny little PR fixes the issue by substracting the padding + border width from the allowed max-width of 100%.
**Before**
**After**
> Color picker: Fix label view

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9910
When using boolean property editor in a custom property editor and the "showLabels" configuration option was configurated using the boolean prevalue editor (which store "0" or "1") the labels wasn't shown even though the toggle was enabled.
Add a **Test** folder in `App_Plugins` with the following package.manifest:
```
{
"propertyEditors": [
{
"name": "Custom toggle editor",
"alias": "CustomToggle",
"editor": {
"view": "boolean",
"valueType": "JSON"
},
"prevalues": {
"fields": [
{
"label": "Default value",
"key": "default",
"view": "boolean"
},
{
"label": "Show labels",
"key": "showLabels",
"view": "boolean"
},
{
"label": "Label on",
"key": "labelOn",
"view": "textstring"
},
{ …
```
> Adjust showLabels to be parsed as boolean

- build/templates/UmbracoProject/UmbracoProject.csproj
This fixes #10585, the template was missing the `RazorCompileOnPublish` property with a value of false, causing sites to be unable to publish when using `InMemoryAuto` for models builder. `Umbraco.Web.UI.NetCore` has this property as well, so it makes sense that templates does too.
I tested by running the build script, installing the template and ensuring that new projects has the property.
> V9: Add RazorCompileOnPublish property to UmbracoProject for template

- src/Umbraco.Infrastructure/Persistence/DbProviderFactoryCreator.cs
- src/Umbraco.Infrastructure/Persistence/IDbProviderFactoryCreator.cs
- src/Umbraco.Infrastructure/Persistence/IProviderSpecificMapperFactory.cs
- src/Umbraco.Infrastructure/Persistence/SqlServerDbProviderFactoryCreator.cs
- src/Umbraco.Infrastructure/Persistence/UmbracoDatabase.cs
- src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
- src/Umbraco.Persistence.SqlCe/SqlCeSpecificMapperFactory.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web/UmbracoDbProviderFactoryCreator.cs
Introduced `IProviderSpecificMapperFactory`, to allow some NPoco mappers to only be applied for specific providers, e.g. `SqlCe` and the `SqlCEImageMapper`.
Before this we saw issues with mapping `byte[]` when using `SqlCE`. Because the `SqlCeImageMapper `was not added to the mappers when using `UmbracoDatabase`.
I had to introduce a `IProviderSpecificMapperFactory `to ensure the `SqlCEImageMapper `was only applied when using `SqlCE`, because it failed otherwise.
> V9: SqlCeImageMapper only applied for SqlCe

- src/Umbraco.Infrastructure/ModelsBuilder/Building/Builder.cs
- src/Umbraco.Infrastructure/ModelsBuilder/RoslynCompiler.cs
- src/Umbraco.Web.Common/ModelsBuilder/InMemoryModelFactory.cs
This fixes an issue with invalid framework references when using ModelsBuilder InMemoryAuto mode. We would end up with exceptions like:
```
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
D:\Projects\Umbraco-CMS-netcore\src\Umbraco.Web.UI.NetCore\Views\Products.cshtml(28,24): error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
D:\Projects\Umbraco-CMS-netcore\src\Umbraco.Web.UI.NetCore\Views\Products.cshtml(30,51): error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly …
```
> Changes the RoslynCompiler to use assemblies resolved from the DependencyContext

- src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
If there's an existing issue for this PR then this fixes #10627 
Adds some range checking for splitting the string for localization 
if a string doesn't contain a _ then the source text is returned (localization requires an area and key separated by _)
> Fix for #10627 - UmbracoDictionaryTranslate checks.

- src/Umbraco.Core/PropertyEditors/IPropertyCacheCompression.cs
- src/Umbraco.Core/PropertyEditors/IPropertyCacheCompressionOptions.cs
- src/Umbraco.Core/PropertyEditors/NoopPropertyCacheCompressionOptions.cs
- src/Umbraco.Core/PropertyEditors/PropertyCacheCompression.cs
- src/Umbraco.Core/PropertyEditors/UnPublishedContentPropertyCacheCompressionOptions.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests/PublishedContent/ContentSerializationTests.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/IContentCacheDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/JsonContentNestedDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializerFactory.cs
- src/Umbraco.Web/PublishedCache/NuCache/NuCacheComposer.cs
- src/Umbraco.Web/PublishedCache/NuCache/NuCacheSerializerComponent.cs
- src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
Include the published state of content for IPropertyCacheCompression. This will allow having a policy of compressing all non published content. Needs to occur before 8.15 to avoid breaking changes to the interface.
Adds an out of the box implementation that compresses ntext properties for only unpublished content (typically rte/blocklist/nestedcontent).
`<add key="Umbraco.Web.PublishedCache.NuCache.CompressUnPublishedContent" value="true"/>`
Requires use of the MessagePack Serializer
`<add key="Umbraco.Web.PublishedCache.NuCache.Serializer" value="MsgPack"/>`
> 8.15RC Published State as part of IPropertyCacheCompression

- src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
This fixes #10668.
The problem was that during a merge the `Localize` extension on `ILocalizedTextService` which takes a string array of tokens was accidentally made to call itself, resulting in an endless recursion, which meant we'd get a stack overflow.
This PR calls `ConvertToDictionaryVars` before calling `Manager.Localize`, so no more recursion.
One thing I noticed while here is that we always use `Thread.CurrentThread.CurrentUICulture` even though we take `CultureInfo` as a parameter, wouldn't it make more sense to use that if available? And use `Thread.CurrentThread.CurrentUICulture` as a fallback?
See issue for steps to test
> V9: Fix recursive localize when resetting password

- src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
The issue isn't so much about dirty tracking since that is done, it was more about when the calls to `entity.SetCultureEdited(editedCultures)` were done in the DocumentRepository since these were set too late and therefore no culture changes were known. The 2nd part was that the `AdjustDates` wasn't called for saving, only for publishing.
> Fixes issue that the update culture dates were not synced with the version date like they are for the published culture dates

- src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedApiController.cs
This fixes #10658 and #10667.
As Shannon explains in #10667 this was due to ambiguous methods in `UmbracoAuthorizedApiController`, to fix this I removed the default value from the `statusCode` parameter.
After removing the default I noticed that `ValidationProblem` is used in a lot of places with some sort of `INotificationModel`, so I added another method that explicitly takes in an `INotificationModel` which still have the default status code, just to make everything a bit easier to use.
> V9: Fix validation messages

- src/Umbraco.Core/Composing/DefaultUmbracoAssemblyProvider.cs
- src/Umbraco.Core/Composing/FindAssembliesWithReferencesTo.cs
- src/Umbraco.Core/Composing/ITypeFinder.cs
- src/Umbraco.Core/Composing/RuntimeHash.cs
- src/Umbraco.Core/Composing/RuntimeHashPaths.cs
- src/Umbraco.Core/Composing/TypeFinder.cs
- src/Umbraco.Core/Composing/TypeFinderConfig.cs
- src/Umbraco.Core/Composing/TypeLoader.cs
- src/Umbraco.Core/Configuration/Models/TypeFinderSettings.cs
- src/Umbraco.Core/DependencyInjection/IUmbracoBuilder.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/HashGenerator.cs
- src/Umbraco.Core/IO/FileSystemExtensions.cs
- src/Umbraco.Core/Logging/ProfilingLogger.cs
- src/Umbraco.Core/Templates/HtmlUrlParser.cs
- src/Umbraco.Tests.Benchmarks/TypeFinderBenchmarks.cs
- src/Umbraco.Tests.Benchmarks/TypeLoaderBenchmarks.cs
- src/Umbraco.Tests.Common/TestHelperBase.cs
- src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
- src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/ComposingTestBase.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeFinderTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs
we are calculating the runtime hash incorrectly in v9. Have a look at the code in AddTypeFinder we do:
```cs
var runtimeHashPaths = new RuntimeHashPaths().AddFolder(new DirectoryInfo(Path.Combine(webHostEnvironment.ContentRootPath, "bin")));
```
There is no 'bin' folder so this will just be the same and we'll never type scan again. We need to re-think this for netcore based on the current environment. For example, if it's a published project, in which case everything exists in the root, else if it's a development project, in which case the binaries live in the /bin/....
So this fix just uses the Assembly provider to use returned assemblies for calculating the hash.
But wait... there's more! This also fixes the issue https://github.com/umbraco/Umbraco-CMS/issues/10554 where for custom apps …
> Fixes runtime hash calculation

- src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
Moved the nullcheck in the useUmbraco method to the top as `app` was already accessed before the nullcheck initially which would've caused null reference exceptions if `app` is ever null, as per request from @Shazwazza
> Moved nullcheck to top to catch possible nullreference exceptions

- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs
This PR is in support of #10666 
Added integration test as requested by @Shazwazza to highlight the issue of MemberService::CreateMemberWithIdentity not persisting a member even though the call produced no error and return a member instance.
The test method assertion will fail until the issue is resolved.
> Add integration test for MemberService::CreateMemberWithIdentity

- src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
should be Media Picker (legacy)
I haven't created an issue - hope that's ok! 
In the RC of V9 - in the list of Data Types there is a typo in the recently renamed legacy Media Picker... it is presented as
Media Picke (Legacy)
This PR just adds in an 'r'
and it becomes
Media Picker (Legacy).
To test - have a look at the list of DataTypes... is the r back!
Thanks for considering this contribution to Umbraco CMS!
> Typo in DataTypeList Media Picke (legacy)

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10431
Couldn't reproduce above issue but never the less I can see a potential code problem, as we haven't implemented the onValueChanged callback which is needed to ensure that the data is proper always.
Therefore this fix.
Test-notes: read the issue.
> #10431 ensure model value onValueChanged

- src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
If there's an existing issue for this PR then this fixes #10709 
Exposed an optional `IMvcBuilder` configuration action in the `AddBackOffice` method, to allow the end user to more easily configure extra MVC services functionality.
While not strictly required, I think it provides a better user experience.
> Exposed MVC configuration action in AddBackOffice - #10709

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
If there's an existing issue for this PR then this fixes #10708
Removes the `inert` attribute on `#mainWrapper` when `editorService.closeAll()` is called.
This code is necessary because when `closeAll` is called, there is no editor passed in `args`, and so `removeEditor` is never called, and so the `focusLockService.removeInertAttribute();` method isn't called either. 
This ensures `focusLockService.removeInertAttribute();` is called if the editor arg is null, meaning it's come from a `closeAll` call.
To test, open a dialog via `editorService.open` and then call `editorService.closeAll`. The main editor window should have the `inert` attribute added and then removed once closed.
> Removes `inert` attribute when `editorService.closeAll()` is called

- src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web/Editors/ContentController.cs
- src/Umbraco.Web/Models/ContentEditing/ContentTypesByKeys.cs
- src/Umbraco.Web/Umbraco.Web.csproj
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10718
The issue was caused by URI length of GETs requests was exceeded, to eliminate it this PR changed the call to a POST.
As well JS changes are made to ensure that the UI displays if ElementTypes are missing or didn't load properly, enhancing the experience if something isn't right.
**Test notes:**
* Test a blocklist editor property with a lot of configured Blocks, 35+(or 18+ with a Settings model for each) should reach the limit. It needs to be different ElementTypes used for each, meaning that we need 35+ unique Element Types.
> 10718 Enables more configured Blocks in Block List Editor

- src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less
- src/Umbraco.Web.UI.Client/src/less/property-editors.less
- src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10610
This PR fixes issues with checkered background not used in file upload anymore - probably after building the new media picker.
So it wasn't useful to see preview of a white SVG, GIF og PNG.
> File upload checkered background

- src/Umbraco.Core/Services/Implement/ContentService.cs
Fixes #9157 
Can be tested with the following class:
```
public class TestComposer : IUserComposer
{
public void Compose(Composition composition)
{
ContentService.Sorted += ContentService_Sorted;
ContentService.Sorting += ContentService_Sorting;
}
private void ContentService_Sorting(IContentService sender, SaveEventArgs<IContent> e)
{
e.Messages.Add(new EventMessage("Test", "Sorting"));
}
private void ContentService_Sorted(IContentService sender, SaveEventArgs<IContent> e)
{
e.Messages.Add(new EventMessage("Test", "Sorted"));
}
}
```
However, sorting actually doesn't have a way to show the event messages on the frontend. I check it by putting some breakpoints on the functions and seeing if they would be hit.
> 9157: Use the sorting event instead of the saving

- src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
Let's escape the tokens used for localization, we already have lodash here, so no need to bring our own solution for this.
> Escape HTML in localization tokens.

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/ExternalLoginTableIndexes.cs
- src/Umbraco.Infrastructure/Persistence/Dtos/ExternalLoginDto.cs
- [X ] I have added steps to test this contribution in the description below
This PR fixes #10656 
This PR updates the IX_umbracoExternalLogin_LoginProvider to include both loginProvider and userId. It also shortens the loginProvider to 400 chars instead of 4000 which was throwing a warning regarding the index anyway. 
I updated the V9 migration to make the same change to the index; however, I didn't want to shorten anybody's existing loginProvider column so I didn't change the length of that column in the migration.
This change allows more than one back office user to be able to use the same external login provider.
* Ran all unit tests (all passed)
* Ran all integration tests (all passed)
* Test on a new site:
* Build and run Umbraco.Web.UI.Netcore
* Provision a new site with a new …
> Umbraco 9 - LoginProvider Duplicate Key

- src/Umbraco.Web.UI.Client/src/less/components/umb-mini-search.less
- src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search.html
This PR fixes fixes a few issues with `<umb-mini-list-view>` component.
- Support custom SVG icon for the node icon above back button.
- Re-use `<umb-search-filter>` component, which are used in most other part of UI now.
It also replace the search icon in `<umb-mini-search>` with `<umb-icon>`.
> Modernize mini listview component to use svg icons and `umb-search-filter` component

- src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
On laptop size (1280 x 720 pixels) when opening help panel, the avatar icon is squeezed. It might doesn't have same spacing right to the avatar, but I think it looks nicer and it could optimize it further later. Maybe if "header actions" is added sometime in future: https://github.com/umbraco/Umbraco-CMS/pull/9016
**Before**
**After**
> Don't squeeze avatar when help panel is open

- src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
This fixes #10746 
There was a recursive call in this method spinning into an infinite loop, which is why there was no error messages or feedback, IIS just gives up after a while.
I also removed an unreachable method. I left some comments here with details: https://github.com/umbraco/Umbraco-CMS/pull/9671#commitcomment-54134090
Make sure to squash & commit this one after review so we only have 1 commit to cherry-pick.
> Fix: Issue when upgraded from 8.14 to 8.15 when inviting user into the backoffice. #10746

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigation.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbchildselector.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbgridselector.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/umbnestedcontent.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/util/disabletabindex.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/util/umbkeyboardlist.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/retryqueue.service.js
- src/Umbraco.Web.UI.Client/src/views/dashboard/dashboard.tabs.controller.js
- src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7718
Previous this PR https://github.com/umbraco/Umbraco-CMS/pull/7928 was submitted to replace `angular.forEach`
However it seems not all references has been replaced or maybe because other PRs has been merged afterwards.
It can use vanilla JS `array.forEach` or `Utilities.forEach`.
Current both versions are used in core, but `Utilities.forEach` is a bit safer as it only iterate if array variable not is null or undefined.
> Replace angular.forEach with Utilities.forEach

- src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
I noticed in user history it wasn't showing node icons, if using custom SVG icons.
This PR fixes that by using the `<umb-icon>` component.
**Before**
**After**
> Use umb-icon component in user history

- src/Umbraco.Core/PropertyEditors/MediaUrlGeneratorCollection.cs
This PR fixes an issue where you can't upload an image by drag and drop, after the new zip package. 
The problem was that when uploading an image with drag and drop we use `SetValue`, this would try to get the old path with the new media URL generators, but because this is a brand new media the `Umbraco.ImageCropper` property will be empty, so when calling the media URL generators, the `GetValue` will return null, leading to the `value` parameter of  `TryGetMediaPath` being null, the `MediaUrlGeneratorCollection` didn't handle this, so it would return true with a null mediaPath, causing a null reference exception because we called `mediaFileManager.FileSystem.GetRelativePath` with null.
I've added a null check to the `TryGetMediaPath` method of `MediaUrlGeneratorCollection`, so it will …
> V9: Fix drag and drop image upload

- src/Umbraco.Web.UI.Client/src/views/content/content.rights.controller.js
Fixes #10043
confirmDiscardChanges that holds the state of the dialog was not reset when saving permission changes. This PR changes that. 
- Create a simple content type
- Create a content node
- Right-click on the node and click Permissions...;
- Then click Set permissions for...;
- Pick a user group and enable or disable an action;
- Click Save.
- Now You will not see the "You have unsaved changes" dialog and if you click discard you can see that the changes are not persisted
> reset confirmDiscardChanges on save

- src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
This fixes #10645, the problem was that translations would only be shown in some places in the backoffice.
The problem was in the `BackOfficeController` `LocalizedText` endpoint that is used to get localized text for javascript. I found two problems here.
The first was that we used `_backofficeSecurityAccessor.BackOfficeSecurity.IsAuthenticated();` to try and authenticate the user, but since this is not an authorized endpoint this would always return false. I changed it to use `this.AuthenticateBackOfficeAsync()` like in the other actions. 
The other issue I found was that we used `Thread.CurrentThread.CurrentCulture` to try and get the users culture, however this won't work, because a user's backoffice language (and therefore culture), is not necessarily the same as their system, for …
> V9: Fix translations not shown everywhere

- src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
- src/Umbraco.Web.Common/Security/ConfigureMemberIdentityOptions.cs
- src/Umbraco.Web.UI.NetCore/appsettings.json
This fixes #10665
Added new config option **AllowedUserNameCharacters** to the **Security** section. This value is used when configuring         IdentityOptions for a Member to override the default member name character validation.
- Default value includes the backslash character [in addition to all characters as presently defined by ASP.NET Core]
- Value can be overridden in config
Tested using a v9 test site:
- With no local application config changes, can a username of "DOMAIN\user" be successfully a) created b) edited
- Adding the setting value of "abcd1234"application config changes, are the following usernames able to be added:
- "DOMAIN\user" - Invalid
- "abc\123" - Invalid
- "abc123" - Valid
> Support member names using Down-Level Logon Name format

- src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/AspNetCoreHostingEnvironmentTests.cs
- src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
fixes https://github.com/umbraco/Umbraco-CMS/issues/10699
- Changed HashSet<Uri> to ConcurrentHashSet<Uri>
- Changed Add to TryAdd in AspNetHostingEnviroment.EnsureApplicationMainUrl
- Added new Unit Test in AspNetCoreHostingEnviromentTest to ensure the method works
- I used this UnitTest: 
```
[AutoMoqData]
[Test]
public void EnsureApplicationMainUrl_Parralel(AspNetCoreHostingEnvironment sut)
{
Parallel.For(0, 10, i => sut.EnsureApplicationMainUrl(new Uri("http://localhost:5000/")));
}
```
And in the AspNetCoreHostingEnviroment.EnsureApplicationMainUrl method i used a Thread.Sleep(50) between Contains and Add to make sure the threads all came at once
> v9: Changed HashSet to ConcurrentHashSet to fix concurrency issues https://github.com/umbraco/Umbraco-CMS/issues/10699

- src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
This fixes a bug which would cause your page to be unable to render if you used `@Model.MyImage.GetLocalCropUrl("someAlias")`. 
This was caused by `GetLocalCropUrl` calling itself recursively and causing a stack overflow. I used the same logic as in V8, and it seems to work fine, I also marked it as obsolete like in V8, letting people know they should use `GetCrop` instead
> V9: Fix GetLocalCropUrl

- src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
- src/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
If a consuming project has Nullable Reference Types enabled, without these changes no compiler warnings will be generated when directly accessing the models properties.
With the added attribute the compiler will now properly generate warnings if accessing to the properties is done without proper null checks.
This should not affect projects that aren't using NRTs.
> Added MaybeNullAttribute to ModelsBuilder generated files

- src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
- src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
This PR fixes #10694.
Using the multi url picker would result in a 404 error when it was rendered to the front page.
The cause was that the UDI parameter was named `udi`, and with our `EntityController` we use a custom attribute `ParameterSwapControllerActionSelector` to handle ambiguous actions, however, this doesn't work if the parameters differ in name between the two actions. Since the we have a `GetUrl` action with a parameter `id` and the action is registered as such: `[ParameterSwapControllerActionSelector(nameof(GetUrl), "id", typeof(int), typeof(Udi))]`, the attribute was unable to resolve the request when the parameter was `udi`.
To fix this I renamed the `udi` parameter to `id` and reflected the change in the javascript code as well, after this the action is invoked correctly …
> V9: Fix multi url picker

- build/NuSpecs/UmbracoCms.Core.nuspec
- src/Umbraco.Core/Umbraco.Core.csproj
If there's an existing issue for this PR then this fixes #10793
This should at least fix #10793 because of a memory leak fix in Serilog.Sinks.Map 1.0.2. Also updated the rest for good measure.
Note that Serilog.Sinks.File is not upgraded to the latest version because it is a new major (4.1.0 -> 5.0.0). Also note that Serilog.Filters.Expressions is deprecated and should be replaced by Serilog.Expressions. I considered both out of scope for this fix.
For testing steps, see the linked issue.
> Update Serilog dependencies

- build/NuSpecs/UmbracoCms.Web.nuspec
- build/NuSpecs/tools/Web.config.install.xdt
- src/Umbraco.Tests/App.config
- src/Umbraco.Web.UI/web.Template.config
- src/Umbraco.Web/Umbraco.Web.csproj
Fixes #10700 
By making the dependencies for MessagePack explicit, we get the correct versions installed. 
This fixes the error experienced in #10700 which seems like it was a bug in the version of `System.Collections.Immutable` that we had. However, fixing the `System.Collections.Immutable` version led to another error since it required an updated version of `System.Buffers` which then needed updated versions of the other two dependencies.
> Install MessagePack's dependencies explicitly

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/usergrouppicker/usergrouppicker.html
- src/Umbraco.Web.UI.Client/src/views/components/users/umb-user-group-preview.html
- src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html
Previous in this PR https://github.com/umbraco/Umbraco-CMS/pull/10345 I fixed the issue when using a custom SVG icon in listviews. However in user groups table it doesn't use listview or `<umb-table>` component, so it wasn't fixed here.
**Before**
**After**
It was also an issue in user group picker:
**Before**
**After**
> Support custom SVG icons in user groups list

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/backdrop.service.js
- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
- src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
- src/Umbraco.Web.UI.Client/src/views/components/application/umb-backdrop.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10754
Various changes to context menu and other has caused backdrop from being hidden/removed e.g. when selecting a menu item in context menu. This is okay in the regular flow, but not in tour mode, where we want focus/highlight on the specific context.
I have also adjust some code to just use vanilla js and the exact same `closeBackdrop` function existed twice in code.
> Tour backdrop missing

- src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
After `<umb-button-ellipsis>` was implemented and used in tree I have noticed when starting a tour all "options" buttons in tree become visible.
I think this should be a bit more specific when the tree get focus.
In content section run tour "Create content -> Creating content".
**Before**
**After**
Could be improved further, but at least it doesn't show all `<umb-button-ellipsis>` when tour is active, but only then the tree is above backdrop.
When running this tour I also noticed the issue reported here: https://github.com/umbraco/Umbraco-CMS/issues/10754
> Only make umb-button-ellipsis visible when above backdrop

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbsearchfilter.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/application/umb-search.less
- src/Umbraco.Web.UI.Client/src/less/utilities/_spacing.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js
- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
This PR add a few adjustments to Examine dashboard in Settings section:
- Replace search input with `<umb-search-filter>` component.
- Replace icons with `<umb-icon>` component.
Currently `<umb-search-filter>` only acted on change, but not on a keypress/keydown event, e.g. search on enter.
I have handled this a bit similar to have it works in `umbMiniSearch` which has an `onSearch` function.
https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web.UI.Client/src/common/directives/components/umbminisearch.component.js#L13
We could in this case call the function `onFilter`, but I thought it might be to close to the `onChange` function.
- Check Examine search works searching via enter in search input and when clicking Search button. With default …
> Examine dashboard search adjustments

- src/Umbraco.Core/Models/Identity/BackOfficeIdentityUser.cs
- src/Umbraco.Web/Security/BackOfficeUserManager.cs
Fixes #10678
Basically, `UsersConroller.cs` `PostUnlockUsers` passes `DateTime.Now` to `UserManager.SetLockoutEndDateAsync` to unlock users. It's possible for that value to still evaluate to `==` inside `UserManager.SetLockoutEndDateAsync`. Regardless of the outcome of the if statement in `SetLockoutEndDateAsync`, that method always returns positive giving the false illusion that the user has been unlocked. Changing `>=` to just `>` should remedy this. Alternately we could also pass a date time in the past to `UserManager.SetLockoutEndDateAsync` as well. 
Line 775 could be changed to:
`var unlockResult = await UserManager.SetLockoutEndDateAsync(u, DateTimeOffset.Now.AddMinutes(-1));`
> Fixes: Unable to unlock locked-out member #10678

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/util/umbkeyboardlist.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
- src/Umbraco.Web.UI.Client/src/less/components/application/umb-search.less
- src/Umbraco.Web.UI.Client/src/utilities.js
This fixes some issues after recent PRs has been merged, e.g. `closeBackdrop` in `navigationService` which wasn't a public function. However instead of exposing `closeBackdrop` in `navigationService` I think it makes more sense the call `navigationService.hideMenu()` which also close backdrop. In fact I think `backdropService`should be responsible for logic regarding backdrops.
> Fixes various issues with javascript services

- src/Umbraco.Core/Persistence/Dtos/DictionaryDto.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DictionaryRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DomainRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/ExternalLoginRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MacroRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberGroupRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/PublicAccessRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/RelationTypeRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/TemplateRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/UserGroupRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
I noticed some SQL querying which combined some strongly typed qyerying using NPoco and static text. While we still can construct sql as strings many places we can use the constants or dto classes to avoid making typos.
There `WhereIn<T>` method makes it very easy to construct sql `IN` queries with less code.
> Refactor NPoco queries to use constants and dtos

- src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umb-property-info-button.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umbpropertyinfobutton.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10593
This PR fixes localization of title attribute in the `<umb-property-info-button>`.
I don't think the `localize` attribute directive will work in this case (or it actually ever has worked here) as it seems, it will just pass in the `@blockEditor_labelCustomViewInfoTitle` as string to the component before the localize attribute directive has localized the text.
The `buttonTitle` should still work for static text, while `buttonTitleKey` will work for localized title similar to `label` and `labelKey` in many other components.
> Fix localization of title attribute in umb-property-info-button

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treepicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treepicker.html
- src/Umbraco.Web/Editors/EntityController.cs
- src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10194
When using treepicker prevalue editor, it currently fails to show the selected entities, because it for a comma delimited string just push the value to an array and pass this into `entityResource.getByIds()`.
It should instead split by comma if the value is NOT an array.
I have attached a test property editor here with the prevalues: 
[TestPropertyEditor.zip](https://github.com/umbraco/Umbraco-CMS/files/6400079/TestPropertyEditor.zip)
> Fix issue with show selected member types on init using treepicker

- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10515
When table plugin is used in rich text editor, it has some advanced table tools, e.g. set set background and border colors.
It was possible to specify the color code / name, but not editor friendly.
The `table` plugin uses the `colorpicker` plugin, so we can add this, when plugins includes the table plugin.
**Before**
**After**
Not sure why the color picker dialog shows the title "color" and not "Color" like the demo here:
https://www.tiny.cloud/docs-4x/demo/full-featured/
Actually the basic demo here also doesn't show color picker under table advances properties, but I think it makes sense to include this, when table plugin is used. …
> Use color picker plugin when plugins includes table plugin

- src/Umbraco.Core/Services/Implement/UserService.cs
When no new users are  added, the _userRepository.GetMany is called with an empty array. The empty array causes that all backoffice users are returned instead of 0 users.
If there's an existing issue for this PR then this fixes  https://github.com/umbraco/Umbraco-CMS/issues/10679
- Create a component to catch the UserService.SavedUserGroup event.
```
public class UserGroupComponent: IComponent
{
public UserGroupComponent()
{
}
public void Initialize()
{
UserService.SavedUserGroup += UserService_SavedUserGroup;
}
private void UserService_SavedUserGroup(Umbraco.Core.Services.IUserService sender, Umbraco.Core.Events.SaveEventArgs<Umbraco.Core.Events.UserGroupWithUsers> e)
{
foreach (var group in e.SavedEntities)
{
int addedUsersCount = group.AddedUsers.Count();
int removedUsersCount = …
```
> UserService.SavedUserGroup event returns wrong list of AddedUsers 

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js
- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10526
With one of the recent Examine changes, the values are now returned as an array. This new response was already working well for the overview of values but was missing from the overview of the results.
I've added the same logic as in the overview of the values and fixed the logic with the editUrl.
Can be tested by going to the Examine Overview and searching.
> Fix examine overview not working as expected

- src/Umbraco.Core/PropertyEditors/UnPublishedContentPropertyCacheCompressionOptions.cs
- src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
Compress Umbraco.TrueFalse properties from int32 to bool.
> 8.15RC Compress Umbraco.TrueFalse properties from int32 to bool.

- src/Umbraco.Core/CompositionExtensions.cs
Registering custom mappers with Umbraco's built in object mapper is a little verbose.
In order to register custom mappers you must first get the collection builder like so:
```
composing.WithCollectionBuilder<MapDefinitionCollectionBuilder>()
```
Most of Umbraco's internal collection builders have short-hand extension methods that can be used instead – e.g. `composing.Components()` – but not for MapDefinitions for some reason... This pull request changes that!
Confusingly an extension for `.Mappers()` already exists, but this relates to the mappers used by the persistence layer. I have tried to distinguish the MapDefinitions accordingly by naming the extension method `.MapDefinitions()`
> Adding extension for MapDefinitions collection builder

- src/Umbraco.Web/Editors/RelationTypeController.cs
When creating a new relationtype, the parent and child type are stored in reverse order (parent- and childtype are switched).
When creating a new relation (via the backoffice), the parent and the child-type (for example Document => Member) are stored in wrong order (Member => Document).
> RelationType parent/child type are stored in the wrong order

- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/numberrange.html
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/numberrange.less
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
I noticed that the "Amount" label did not reference the first input field, so for the sake of consistency I've done some modifications for this to happen, which also improves accessibility.
1. Added an "id" to the first input mapping it to the `model.alias`
2. Added a visually hidden label for the "max input" field
In addition to the above I have also changed the displaying of the validation messages so they appear below the input fields instead of both appearing to the right of the last input field. I think it provides a nicer visual experience even though I know it would probably be rare that people will ever see these messages anyway.
I've added `aria-describedby` to the error messages so they're referencing the id of the input fields their messages belong to as well.
Finally I've …
> Numberrange view: Various minor improvements

- src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
1. Setup the SMTP configurations in the Web.config so Umbraco can send emails (SendGrid account or other as example)
2. Create a user with the "Invite user" in the backoffice
3. Click on the link sent by email but don't fill the password form
4. Delete the user through the backoffice
5. The user should be deleted
Fixes #10269 
I added a `DELETE` query to make sure there are no entries for the user being deleted in the table `umbracoUserLogin` before deleting the user itself in the `umbracoUser` table. Before, there would be a foreign key conflict on the `userId` column (`FK_umbracoUserLogin_umbracoUser_id`).
> Fix issue when deleting an invited user

- src/Umbraco.Core/Composing/TypeFinder.cs
This adds `JetBrains.Annotations.dll` to Umbraco's assembly exclude list, meaning Umbraco's type finder/loader won't try to resolve types within this assembly.
See issue for more information: https://github.com/umbraco/Umbraco-CMS/issues/10801
> v9: Added "JetBrains.Annotations" to assembly exclusion list to fix #10801

- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeFinderTests.cs
- src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
Fixes: #10736 
- When selecting an image for your BlockList thumbnail, the choice will be limited to only images from the static files serving directories;
- If the image is located under the webroot folder, the thumbnail path is kept as, for example, `~/media/...` instead of `~/wwwroot/media/...`.
- Set up a doc type with a BlockList property editor;
- Upload a few images in the Media section and/or under _"Umbraco.Web.UI.NetCore\App_Plugins"_ folder;
- Add a block and under **Catalogue appearance** try selecting different images for the block's thumbnail and make sure it is all working properly (the image is rendered);
- &#43; follow the "**Steps to reproduce**" from the original issue ⬆️.
-------------------
❗ NB: remember to run `npm install` and `npm run build` as there are …
> V9: Limit the BlockList thumbnail picker to only the directories serving static files 

- src/Umbraco.Web.UI.Client/src/common/directives/components/umblistviewsettings.directive.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9289
This PR doesn't fixes https://github.com/umbraco/Umbraco-CMS/issues/9289 but it may be good enough for now.
Currently it assume a custom listview is configurated if data type name matches "List View - {alias}" where alias by default is camel case, e.g. "List View - people"
It then cause issues if the data type was renamed to "List View - People" as it would then use default "List View - Content".
With this change it ignore casing, so the datatype can be renamed to "List View - People".
Additionally it could also try create the datatype name in pascal casing in first place:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/DataTypeController.cs#L179
> Check invariant name of custom listview

- src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
The problem is that `RedirectTrackingHandler` is using the IPublishedSnapshotAccessor but not checking for null which is always required when using any 'accessor' that returns a scoped based instance.
I'm unsure if this issue only occurs when the system is in Upgrade mode, or if this will throw an exception if any IContent operations are done in a background thread. But since a published snapshot is dependent on an UmbracoContext which is scoped, I suspect this will always throw if any operations are performed on background threads. 
To force a published snapshot we would need to force an Umbraco context with the IUmbracoContextFactory if we wanted this to always works.
This problem describes exactly why it can be dangerous to create accessors for scoped based instances like what has been …
> Needs a null check so it doesn't explode when saving content during a migration.

- src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
Remove unused package of `Serilog.Settings.AppSettings` that was reading the config of Serilog from XML files
NOTE: Had to add back `System.Configuration.ConfigurationManager` as the Serilog package pulled this in as a dependency and currently there are places in the CMS codebase that depend on ConfigManager still 🙈
> V9 Serilog - Remove old XML settings nuget

- src/Umbraco.Core/Packaging/PackageMigrationResource.cs
- src/Umbraco.Core/Packaging/PackagesRepository.cs
- src/Umbraco.Infrastructure/Packaging/ImportPackageBuilderExpression.cs
- src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
- src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/CreatedPackagesRepositoryTests.cs
Packages can now use both XML and Zip. Zip is only returned from the package creation if media is included, otherwise, just the XML is returned.
The automatic package migrations now support both an embedded XML or and embedded Zip. If both exist only the Zip is used.
I also fixed an issue with imports, where media was not installed if the parent was not changed.
To test this, do the following:
- Add folder to media..
- Add multiple images into the folder
- Create a package with the folder and include descendants
- Remove one of the items inside the folder + empty the recycle bin
- Install the package using auto package migration
- Add ZIP or XML into the project, and in the same folder as you create the code snippet
- Embed the ZIP or XML file in SLN/Project
```
public class …
```
> V9: Package export and import both xml and zip

- src/Umbraco.Web.Common/Templates/TemplateRenderer.cs
If there's an existing issue for this PR then this fixes #10683
In the `TemplateRenderer`, on the `ExecuteTemplateRendering` method, when calling `this._viewEngine.GetView`, `isMainPage` was set to `false` resulting in the `_ViewStart.cshtml` never being called. This has now been changed to `true`.
> Set isMainPage to true on TemplateRenderer.ExecuteTemplateRendering

- src/Umbraco.Web.UI.NetCore/Views/Partials/grid/editors/textstring.cshtml
Html.ReplaceLineBreaks calls WebUtility.HtmlEncode internally, so the text gets encoded by this method.
As far as I know, WebUtility.HtmlEncode and HttpUtility.HtmlEncode produces the same result (unlike WebUtility.UrlEncode and HttpUtility.UrlEncode which produces different results; see https://edi.wang/post/2018/11/25/netcore-webutility-urlencode-httputility-urlencode), so it should be safe to omit HttpUtility.HtmlEncode here.
If there's an existing issue for this PR then this fixes: #10841
The steps to reproduce the error is mentioned in the issue above.
> Only encode text once

- src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
- src/Umbraco.Web.UI.NetCore/appsettings.json
Fixes: #10820
- `UrlProviderMode` can be set to "Absolute", "Auto" and "Relative";
- When the mode was set to "Absolute', `RedirectToCurrentUmbracoPage()` was not working;
- Adding a check for this case to avoid the exception being thrown - `$"The value {virtualPath} for parameter {nameof(virtualPath)} must start with ~/ or /"`.
- Follow the steps in the original issue OR
</br>
- Set ⬇️ to appsettings.json
```json
"WebRouting": {
"UrlProviderMode": "Absolute"
}
```
- Create a test _SurfaceController_ and add a PostMethod like:
```c#
[HttpPost]
public IActionResult PostMethod()
{
if (!ModelState.IsValid)
{
return CurrentUmbracoPage();
}
return RedirectToCurrentUmbracoPage();
}
```
- Post to the added surface controller:
- Create a new Partial View Macro file;
- Insert the following code: …
> V9: Fix RedirectToCurrentUmbracoPage when UrlProviderMode is set to "Absolute"

- src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/PublicAccessCheckerTests.cs
- src/Umbraco.Web.Common/Security/PublicAccessChecker.cs
fixes an issue, where if you had a member, but no member groups. Restricting public access and giving permission to a member would always yield in the error page, even when you logged in as the correct member that had access.
- Removed if statement in `PublicAccessChecker.HasMemberAccessToContentAsync`
- Create a doc type and call it home page, then create an empty content page called "Home Page"
- Create a new member and choose your username and password(remember it though)
- Create a doc type with a Grid Layout property and call it GridProp
- Create a partial view macros from snippet from `Login`
- Go to the Login macro and enable "Use in rich text editor and the grid"
- Make a content page using the Grid Doc, and call it "Login"
- Choose 1 Coloum and headline, and then add a macro, …
> v9: If you didnt have a member group, restricting acces to the public would always lead to error page

- src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
fixes https://github.com/umbraco/Umbraco-CMS/pull/10688#issuecomment-880683722
- Updated CreateMemberAsync function to properly send back the ModelState
- This issue was caused because of this code which weren't migrated https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/MemberController.cs#L719-L764
- Create a member witha invalid login/password/email
- Change the invalid login/password/email to a valid one
> v9: Fixed a bug where validation didnt update properly

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
Originally I implemented `umbColorPicker` component in https://github.com/umbraco/Umbraco-CMS/pull/8812
The color plugin also has a `dragstart` and `dragstop` event, which may be useful to developers implementing the color picker component in a custom property editor, dashboard or other custom view in backoffice.
I have attached the custom dashboard as in the gif above here: 
[MyDashboard.zip](https://github.com/umbraco/Umbraco-CMS/files/6984645/MyDashboard.zip)
> Implement drag start and drag stop events

- src/Umbraco.Web.UI.Client/package.json
No real changes from noUiSlider v15.2.0 expect it now has a `keyboardMultiplier` option.
https://github.com/leongersen/noUiSlider/releases
It can potential be useful, when having a slider with a small step size as in the example here:
https://github.com/leongersen/noUiSlider/issues/992
> Upgrade to noUiSlider v15.3.0

- src/Umbraco.Web/PublishedCache/NuCache/Property.cs
`NuCache.Property` is unnecessarily tight coupled to `NuCache.PublishedSnapshot`.  
This prevents unit-testing parts of NuCache.
With this change, I'm actually able to use NuCache from btree file on disk to proper published content via the NuCache implementations. A few stubs for sure, but not that bad. Content types must be set up _before_ we "boot" per test, but otherwise the perf. & api seems quite good!
This is just a minor fix to see if we can get going with more unit testing again.  
I think the state is pretty much "as bad" still for v9, but I'm getting somewhere.  
See https://github.com/lars-erik/umbraco-unit-testing-samples/blob/master-v8/UmbracoV8.Testing.Tests/Can_I_Haz_The_Content_Cache.cs
Cross posting a bit on #10106.
> Decouple NuCache.Property from NuCache.PublishedSnapshot

- src/Umbraco.Core/Web/IUmbracoContext.cs
- src/Umbraco.Infrastructure/Routing/ContentFinderByConfigured404.cs
- src/Umbraco.Tests.UnitTests/TestHelpers/Objects/TestUmbracoContextFactory.cs
- src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
- src/Umbraco.Web.Common/UmbracoContext/UmbracoContextFactory.cs
- Removed VariationContextAccessor from IUmbracoContext
- Removed VariationContextAccessor from UmbracoContextFactory
- Set a breakpoint in `ContentFinderByConfigured404.TryFindContent()`
- Watch the local_variationContextAccessor
- Make an empty doctype and add a page of content
- Try navigating to a site that is not ur homepage, example "localhost:44331/DoesntExist"
- _variationContextAccessor should not be null
> v9: Removed VariationContextAccessor from IUmbracoContext

- src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
- src/Umbraco.Web.UI/Umbraco/config/lang/cs.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/de.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/es.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/he.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/it.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/ja.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/ko.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/nb.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/pl.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/pt.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/ru.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/zh.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/zh_tw.xml
Feature update per discussion: #10765
Add select/deselect all feature to the Log Viewer.
And it also supports localisations of the button labels (Danish included in this pull request):
> UI improvement: Add option to select/deselect all filters in Log Viewer drop-down

- src/Umbraco.Core/SystemLock.cs
Updating old broken link to Stephen Toub's
"Building Async Coordination Primitives, Part 6: AsyncLock"
> SystemLock - Update link to msdn blog

- src/Umbraco.Web.UI.Client/src/less/components/html/umb-expansion-panel.less
In Umbraco v8 the packages panel header was an `<button>` element, which inherited `box-sizing: border-box`.
In Umbraco v8 this is no longer the case as the header is just a `<div>` element, which by default has `box-sizing: content-box` and thus cause page owerflow.
With this change it looks much nicer.
> V9: Fix packages overflow

- src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs
- src/Umbraco.PublishedCache.NuCache/ContentStore.cs
- src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
Avoid mixing using of string interpolation and string formatting in log messages. The messageformat parameter gets cached and should be a constant string.
> Avoid mixing using of string interpolation and string formatting in log messages

- src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
- src/Umbraco.Web.Common/AspNetCore/AspNetCoreBackOfficeInfo.cs
- Updated AspNetCoreBackOffice to have a backing field
- Will set if AbsoluteUrl is null
- Make an empty doctype with a template
- Make a blank content page'
- In the template, inject the IBackOfficeInfo
- insert @IBackOfficeInfo.GetAbsoluteUrl in the template
- Navigate to the empty content page url
- It should give you an absolute url for your backoffice
> v9: Making backoffice path absolute

- src/Umbraco.Web/WebApi/Filters/OutgoingEditorModelEventAttribute.cs
This PR fixes #10792: `SendingContentModel` event is not raised for blocklist blocks.
The problem is that after the optimizations to the BlockList editor (#10235), we request all empty models for a blocklist in one call with `GetEmptyByKeys`, this broke the `EditorModelEventManager` because we return `IDictionary<Guid, ContentItemDisplay>`, instead of a `ContentItemDisplay`.
To fix this I've updated `OutgoingEditorModelEventAttribute` to now check if we're returning an `IDictionary`, if we are, we iterate through each `DictionaryEntry`, and raise an event with the value. 
1. Create a component and listen to the `EditorModelEventManager.SendingContentModel` event
2. Create a document type with a blocklist property with at least one available block
3. Create a piece of content using the …
> Raise SendingContentModel event for each element type in blocklist

- src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
- src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
- src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
As suggested in https://github.com/umbraco/Umbraco-CMS/pull/10794#issuecomment-895136210 we can re-use file picker and make it simpler to use.
I noticed we have both static files picker, but also the existing file picker used for custom CSS and custom view. I guess we could use static file picker as well to pick CSS and HTML?
Currently it pass in the filter function, but maybe later we want a different view than `treePicker` or some additional options, e.g. a property "allowedFileExtensions" which could be an array of file extensions.
> V9: Infinite editor file picker

- src/Umbraco.Core/Constants-PropertyEditors.cs
- src/Umbraco.Core/PropertyEditors/ValueConverters/EyeDropperValueConverter.cs
- src/Umbraco.Infrastructure/PropertyEditors/EyeDropperColorPickerConfigurationEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/EyeDropperColorPickerPropertyEditor.cs
This PR add a property value converter for Eye Dropper property editor. It related to this issue in v8 https://github.com/umbraco/Umbraco-CMS/issues/10323 but simplify the value converter to a string. Most probably only need to render the color, e.g. as inline background color.
If you want a more complex property editor and a value converter returning a complex model, you could always create your own property editor using `<umb-color-picker>` component and use `tinyColor` to store a complex JSON object with e.g. properties hex, rgba, alpha, maybe even R, G, B and A splitted in separate properties.
Furthermore it allow the property editor to be used as macro parameter editor as in this PR for v8:
https://github.com/umbraco/Umbraco-CMS/pull/9988
> V9: Eye Dropper property value converter
