umbraco/Umbraco-CMS

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
remove unused index, basicly a clean up
> remove unused index

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
The settings content app in block editor (infinite editor) should only appear if a block has settings, this PR makes that true again. This was true in an earlier state but was forgotten in later refactoring when implementing validation.
> Only append settings content app if block has settings

- src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
Fixes [AB#7593](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7593)
Just better null checking for the c# min/max validation limits. To test this, disable the client side limits in `umbBlockListPropertyEditor.component.js` inside `onAmountOfBlocksChanged` comment out the code in the ``// validate limits:` code block.
Then save data with the block editor - test when you have limits specified and without limits specified (null) and ensure it all works as expected without YSODs
> better null checking for config validation limits

- src/Umbraco.Web/Security/MembershipHelper.cs
Fix for https://github.com/umbraco/Umbraco-CMS/issues/7292
The problem with #7292 is that `MemberHasAccess` is called in a loop within a Linq query which is basically an N+1 type of issue. Calls to `MemberHasAccess` are not free since it requires a few lookups. Most of which has an underlying cache mechanism but looking up a members group's is not cached. And although it is possible to add cache to this, it is a band-aid fix which would still also incur an SQL call for each loop anyways to acquire an SQL readlock. Though this would be much much faster than before it's more ideal that there are no N+1 SQL calls.
Provider APIs to bulk query member access. 
```cs
IDictionary<string, bool> MemberHasAccess(IEnumerable<string> paths)
```
This is a single call that can be made to get a result of …
> Adds new methods to MembershipHelper for dealing with checking bulk paths for access

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/templatesections/templatesections.html
- src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
- src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.html
- src/Umbraco.Web.UI.Client/src/views/content/protect.html
- src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
- src/Umbraco.Web.UI.Client/src/views/documenttypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
- src/Umbraco.Web.UI.Client/src/views/mediatypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/membertypes/delete.html
- src/Umbraco.Web.UI.Client/src/views/packages/edit.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/orderDirection.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
- src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
- src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.html
This PR ensure all `<umb-checkbox>` and `<umb-radiobutton>` not are void elements (self-closed elements) since this turns out to  cause issues and in these examples:
https://github.com/umbraco/Umbraco-CMS/pull/8478
https://github.com/umbraco/Umbraco-CMS/pull/8540
Here is a great explanation of why it can't be self-closing: https://stackoverflow.com/a/25012451/1693918
> Fix self closing angular elements

- src/Umbraco.Web/Cache/UnpublishedPageCacheRefresher.cs
The issue is that a blueprint is also an IContent which needs to have the regular repository caches refreshed. Cache refreshers execute on ALL servers including the master and that is how the caches are refreshed there too so this needs to execute. However, blueprints aren't in the published cache and are a different object type and we weren't checking for this in the cache refresher which was the cause for the exception. The fix is to update the payload to include the IsBlueprint flag and use that accordingly to update the cache where necessary.
> Fix for V7- Error 'No Document Exists with id 'xxx' when saving a Content Template Blueprint #8499

- src/Umbraco.Web.UI.Client/gulp/tasks/views.js
- src/Umbraco.Web.UI.Client/gulp/tasks/watchTask.js
- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
- Added rename to the gulp copy task + request using lowercase
- execute both `npm run dev` and `npm run build`
- verify all files in `Umbraco.Web.UI.Netcore/wwwroot/umbraco/views` are lowercase. E.g the folder "documentTypes" are not "documenttypes
> Changed all view paths to lowercase from gulp

- src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Sort paste entries in Block List and Nested Content, shows the latest first.
---
_This item has been added to our backlog [AB#7875](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7875)_
> V8.7RC Sort paste entries by date

- src/Umbraco.Web/Cache/PageCacheRefresher.cs
If there's an existing issue for this PR then this fixes #6472
This PR makes sure the preview xml get's updated when saving and publishing
Steps to reproduce and test can be found here : https://github.com/umbraco/Umbraco-CMS/issues/6472#issuecomment-576614477
Make sure that in step 11 and 12 you publish nodes C, D and the website node.
To test the fix the easiest is to build the umbraco zip package and copy the dll's over the provided test website.
Dave
> #6472 update the preview xml on publish actions

- src/Umbraco.Web.UI.Client/src/common/directives/components/events/onOutsideClick.directive.js
I've has issues using debugger together with this. We should in general not use apply, since it will fail if its goes together within a digest.
> change to use evalAsync()

- src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
fixes https://github.com/umbraco/Umbraco-CMS/issues/8676
Only request getCount() if the current user has access to settings.
> V8.7RC Only request getCount() if the current user has access to settings.

- src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs
Issue: https://github.com/umbraco/Umbraco-CMS/issues/8816 reported on alpha001.
For testing nodes, consult the reproduction steps of the issue above ⬆️
> NetCore: Fix for mapping route param 

- src/Umbraco.Web.UI.Client/package.json
Just a minor update to use latest version of noUiSlider which fixes a few bugs: https://github.com/leongersen/noUiSlider/releases
> Update noUiSlider to v14.6.2

- src/Umbraco.Core/Constants-Web.cs
- src/Umbraco.Tests.Integration/TestServerTest/Controllers/ContentControllerTests.cs
- src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
- src/Umbraco.Web.BackOffice/Controllers/IconController.cs
- src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
- src/Umbraco.Web.BackOffice/Controllers/SectionController.cs
- src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/ContentBlueprintTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/DataTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/DictionaryTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/LanguageTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/LogViewerTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MacrosTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MemberGroupTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MemberTypeAndGroupTreeControllerBase.cs
- src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/PackagesTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/PartialViewMacrosTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/PartialViewsTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/RelationTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/UserTreeController.cs
- src/Umbraco.Web.Common/ApplicationModels/BackOfficeApplicationModelProvider.cs
- src/Umbraco.Web.Common/Filters/BackOfficeCultureFilter.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8856
- The issues turned out to because the BackOfficeApiArea was not considered part of Backoffice, when the application model was applied to controllers
> Netcore: Bugfix for user culture not used everywhere

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8773
* Test that copying from NC can paste in Bl. and the other way.
* Test NC nested inside another NC & try to copy any of those items into block list editor
---
_This item has been added to our backlog [AB#8607](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8607)_
> Cleanup NC specific data before sending it to the clipboard

- src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8929
Perform the test from issue ^^
---
_This item has been added to our backlog [AB#8600](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8600)_
> Review: Check for null since null is an object as well.

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
Fixes #8876
Fixes #8872
Based on the fix from #8878 but now target for 8.7 with a minor correction.
---
_This item has been added to our backlog [AB#8623](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8623)_
> Review: Fixing blocklist labelblock css

- src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/8868
This is a simple fix. I tried to correct the bad behavior of umb-pane and umb-dialog-body, but it's used in so many different ways across the system that I cant correct this for now, so I'm just fixing the one-pixel issue.
---
_This item has been added to our backlog [AB#8618](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8618)_
> Review: Fix one pixel in dialog

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
- src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
fixes https://github.com/umbraco/Umbraco-CMS/issues/8911
Test notes in issue.
Both test if Content Editor work when Element Type is gone.. but also check that you are able to remove the Block Type from Prevalue.
---
_This item has been added to our backlog [AB#8602](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8602)_
> Review: Check that scaffold exists

- src/Umbraco.Web.UI.Client/src/common/services/focuslock.service.js
@Shazwazza Have I addressed your concerns from #8141 correctly with this PR? 😅
> Focus lock service - Improvements

- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
If there's an existing issue for this PR then this fixes: #9043 
Changed the translation in en.xml and en_us.xml for the publish variants dialog.
> fixed publish variants dialog translation

- src/Umbraco.Tests.Common/Builders/ContentBuilder.cs
- src/Umbraco.Tests.Common/Builders/ContentTypeBuilder.cs
- src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
- src/Umbraco.Tests.Integration/Persistence/Repositories/ContentTypeRepositoryTest.cs
- src/Umbraco.Tests.Integration/Persistence/Repositories/DataTypeDefinitionRepositoryTest.cs
- src/Umbraco.Tests.Integration/Persistence/Repositories/DocumentRepositoryTest.cs
- src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- Migrated ContentTypeRepositoryTest to the new integration tests
- Had to copy some of the test helper stuff.
- Migrate DataTypeDefinitionRepositoryTest
> Netcore: Migrated Respository Tests

- src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
The title says it all - I have converted the `<i>` to `<umb-icon>` her as well 😄
> Installed packages view: Convert i to umb-icon

- src/Umbraco.Web.UI.Client/src/views/member/delete.html
Hi,
I have changed the delete button style to `btn-danger` to bring it in line with other delete overlays
Poornima
> Changed delete button style to danger on member overlay

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
Hi,
I have added `umb-icon` directive to replace the search icons in the examine management dashboard.
Poornima
> Added umb-icon directive examine management dashboard

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/scripts.ts
> Add javascript acceptance  tests

- src/Umbraco.Core/Events/SendEmailEventArgs.cs
- src/Umbraco.Core/IEmailSender.cs
- src/Umbraco.Core/Models/EmailMessage.cs
- src/Umbraco.Infrastructure/HealthCheck/NotificationMethods/EmailNotificationMethod.cs
- src/Umbraco.Infrastructure/Services/Implement/NotificationService.cs
- src/Umbraco.Infrastructure/Users/EmailSender.cs
- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
- src/Umbraco.Web/Editors/AuthenticationController.cs
Abstracting `MailMessage`, so we only expose our own types.
- Configure SMTP settings (uncomment them in _appsettings.Development.json_)
- Test the email sending functionality (it should be the same as before)
> NetCore: Email message abstraction

- src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Make sure when trying to JsonConvert.DeserializeObject it is json...
Fixes #9235 
Fixes #9237
> Update NestedContentPropertyEditor.cs to fix 2 bugs

- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
Changed the test from using `IsoCode` to `IsMandatory`, as this is not important to the test, but changing IsoCode leads PublishedSnapshotService to rebuild its caches.
An for some reason the rebuild of the cache fails due to missing connection string.. (Need to look into this in separate issue)
> Netcore : Fixed issue in ScopedRepositoryTests

- src/Umbraco.Core/ServiceCollectionExtensions.cs
- src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
Add additional "mutliple unique" registrations and rename extension for clarity.
#9323
> NetCore: Fixes registration issue (continued)

- src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
Fix for #9146. We need to take language and segment into account
> Fix failing tests

- src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
- src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.Common/Extensions/UmbracoWebServiceCollectionExtensions.cs
Quick win, 1 less ServiceProvider
> Netcore: Misc Remove BuildServiceProvider call

- src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
- src/Umbraco.Web.UI.Client/src/installer/steps/database.html
Refactoring to more explicit DB type checks where:
- _"SqlCe"_ is **0**
- _"SqlServer"_ is **1**
- _"SqlAzure"_ is **3**
- _"Custom"_ is **-1**
> NetCore: Install page db checks

- src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
- Changed type names to lowercase to reflect corresponding types in JavaScript
- File used a mix of `callback` and `function`. Updated to use `function`.
- Updated sentences to end with period.
> Updated editor.service.js for consistency

- src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
- Turkish language has been arranged according to v8.9.1.
- Missing and incorrect edits have been reworked.
* It is not possible to write one by one because there are too many deficiencies.
* The tr.xml file has been completely edited in accordance with the existing en.xml language file.
> Turkish language has been arranged according to v8

- src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbdrawer/umbdrawer.directive.js
No tests -- this is a quick documentation update for the umbdrawer
Was contributing in the [UmbSense project](https://github.com/KevinJump/UmbSense) working on adding tags that had me viewing the documentation and comments within the codebase.
Within the comments pointed to the `umbDrawerView` directive when referring to the `umbDrawerContent`.  I just made the quick update.
Please let me know if your require any additional information.  
Thank you!
> Documentation link updated - umbdrawer

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
During the work on some other PR's I noticed that while the variables names had changed the comments had not so I've done that with this PR ☺️
> Change comments to use allowed and disallowed

- .github/CONTRIBUTING.md
Update new list of Core Collaborators in contributing docs
> Update new list of Core Collaborators in contributing docs

- src/umbraco-netcore-only.sln
Added one solution file that contains only netcore compatible projects, so that it can be used to build on Mac/Linux
> Added netcore-only solution file

- src/Umbraco.Web/Umbraco.Web.csproj
- src/Umbraco.Web/UmbracoBuilderExtensions.cs
Clean up a little mess from #9415
> Netcore: Misc resolve naming issues

- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/TempFileCleanupTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs
Fixed unit tests so the pass on both windows and linux
> Netcore: Fix unit tests, so they pass on linux too

- src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
- src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
- src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
- src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
Resolves issue from https://github.com/umbraco/Umbraco-CMS/pull/9415#issuecomment-733586568
All tests green for me locally.
> Netcore: Hotfix for PublishedSnapshotService initialization

- src/Umbraco.Core/Models/Security/LoginStatusModel.cs
- src/Umbraco.Core/Security/IUmbracoWebsiteSecurity.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Security/UmbracoWebsiteSecurityTests.cs
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/EditProfile.cshtml
- src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/Login.cshtml
- src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/LoginStatus.cshtml
- src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/RegisterMember.cshtml
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
- src/Umbraco.Web.Website/Extensions/TypeLoaderExtensions.cs
- src/Umbraco.Web.Website/Security/UmbracoWebsiteSecurity.cs
- src/Umbraco.Web/Umbraco.Web.csproj
Along with the necessary methods from `MembershipHelper` into `IUmbracoWebsiteSecurity`.
There's some `TODOs` of course, pending work on the ASP.NET Core Identity setup for members.
Conscious of a couple of further amends we might consider here:
- Should we be creating and using tag helper for `BeginUmbracoForm`?
- Should we still need to ship referencing jquery?
But think they can come later, if at all.
> NetCore: Migrated member related partial views

- src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
I tested it on a local project.
Adds Swedish translation for the member section in the back office.
Have a nice day!
> Add Swedish translation for the member section.

- src/Umbraco.Web.UI.Client/src/views/membergroups/edit.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9466
---
_This item has been added to our backlog [AB#9568](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9568)_
> Review Remove this form-horizontal class from member groups info

- build/azure-pipelines.yml
Prepare pipeline for nightly builds
- Adding step that put build number in version for nuget packages
> NetCore: Prepare pipeline for nightly builds

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
- src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
- src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
- src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
- src/Umbraco.Web.BackOffice/Filters/EditorModelEventManager.cs
- src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs
Converted OutgoingEditorModelEventAttribute to a type filter and updated the code as needed (hopefully)
Issue: #8264
Matt
> Converted  OutgoingEditorModelEventAttribute to a type filter

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
Just a minor update in the documentation of the `umbColorPicker` component since it was first included in Umbraco v8.10.0
https://github.com/umbraco/Umbraco-CMS/pull/8812
> Update version umbColorPicker was introduced

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
Just noticed the "Remove all entries" on the media picker. This PR adds similar functionality to MNTP:
If this PR is accepted, I'll move on to do the same to other relevant property editors (Content Picker for example).
/cc @nielslyngsoe
> Add "Remove all entries" property action to MNTP

- .github/BUILD.md
> Corrected branch name with latest in BUILD.md readme

- src/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Extensions/HealthCheckSettingsExtensionsTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/ContentSettingsValidatorTests.cs
Sorry - I missed adding two further test classes I'd updated to match code linting rules to previous commit/PR.
> NetCore: further code clean-up (small)

- .gitignore
- src/Umbraco.Core/Configuration/LocalTempStorage.cs
- src/Umbraco.Core/Constants-SystemDirectories.cs
- src/Umbraco.Core/HealthCheck/Checks/Permissions/FolderAndFilePermissionsCheck.cs
- src/Umbraco.Core/Hosting/IHostingEnvironment.cs
- src/Umbraco.Core/Logging/ILoggingConfiguration.cs
- src/Umbraco.Infrastructure/Diagnostics/MiniDump.cs
- src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
- src/Umbraco.Tests.Common/TestHelperBase.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/ComposingTestBase.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
- src/Umbraco.Tests/TestHelpers/BaseUsingSqlCeSyntax.cs
- src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
- src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
- src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
- src/Umbraco.Web/AspNet/AspNetHostingEnvironment.cs
* Cleans up usage of SystemDirectories
* Removes App_Data usages
* Removes AspNetTemp as an option since that doesn't exist anymore
* Linting cleanup
> Cleans up usage of SystemDirectories, removes App_Data usages

- src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
Translated the word 'cheers' friendlier to Turkish :)
> Little tweak

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/querybuilder/querybuilder.html
- src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.controller.js
If there's an existing issue for this PR then this fixes #9516 
See issue for description. I removed the console.log statements in the mentioned file and in another file as well
> V8 - remove console.log statements

- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
fixes https://github.com/umbraco/Umbraco-CMS/issues/9493
> fixes 9493

- src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
- src/Umbraco.Web.UI/Umbraco/Views/Preview/Index.cshtml
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
fixes https://github.com/umbraco/Umbraco-CMS/issues/9484
see issue for test notes
> Change dialog

- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Fixed spelling mistake made in https://github.com/umbraco/Umbraco-CMS/pull/9545#pullrequestreview-551427637
> Added missing Y

- src/Umbraco.Web.UI.Client/src/common/resources/auth.resource.js
Hi,
I have tried to update the UI docs for the authresource.
Poornima
> Updated the UI docs for the authresource

- src/Umbraco.Web.UI.Client/src/common/resources/elementtype.resource.js
Hi,
I have updated ngDocs for elementTypeResource
Poornima
> Updated ngDocs for elementTypeResource

- src/Umbraco.Web.UI.Client/src/common/resources/modelsbuildermanagement.resource.js
Hi,
I have created ngdocs for modelsbuildermanagementresource. I think there might be a useful method or two in there which is good to have documentation on
> Created ngDocs for modelsBuilderManagementResource

- build/azure-pipelines.yml
- build/templates/UmbracoSolution/.template.config/template.json
Update umbraco version in template from azure pipeline continuous builds
> Netcore: Update umbraco version in template from azure pipeline

- src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
- src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceVariantsTests.cs
Resolve TODO in front-end-routing #9530
> Netcore: Dispose host on test teardown.

- src/Umbraco.Core/Services/ContentTypeServiceExtensions.cs
- src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
- src/Umbraco.Web/Editors/ContentTypeControllerBase.cs
Added ngDocs for contenttyperesource. Also fixed few typos in the service xml documentation
> Added ngDocs for contenttyperesource

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Examine/Umbraco.Examine.csproj
- src/Umbraco.Tests/Testing/TestDatabase.cs
- src/Umbraco.Tests/Umbraco.Tests.csproj
- src/Umbraco.Web/Umbraco.Web.csproj
This PR Fixes #8857 
This simply updates NPoco from 3.9.4 to 4.02
> Updated NPoco from 3.9.4 -> 4.0.2

- src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
Removes the additional checks for UmbracoRequestPaths that are no longer needed in netcore. This will improve throughput performance sine these checks are check on each request.
> removes ext checks since we don't have any server side requests with ext anymore

- src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
I found missing translations for Swedish language.
> up swedish lang config

- src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/SqlDeveloperTestDatabase.cs
- src/Umbraco.Tests.Integration/Testing/TestDatabaseFactory.cs
- src/Umbraco.Tests.Integration/Testing/TestDatabaseSettings.cs
- src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
> Netcore: test duration on CI pipeline with more databases

- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
Fixes a couple of typos in the Danish translations
> Fix typos in Danish translation

- src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
Small css change to prevent overflow of searchresults with long url's
> Prevent overflow of searchresults with long urls

- src/Umbraco.Core/Persistence/Dtos/ContentNuDto.cs
- src/Umbraco.Core/Persistence/NPocoDatabaseExtensions-Bulk.cs
- src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
Support bulk insert of binary data into SQL CE. Also fixes column order for bulk insert as it relies on the order of the properties in a class.
> Support bulk insert of binary data into SQL CE

- src/Umbraco.Web.UI.Client/package.json
A minor change to update noUiSlider dependency to v14.6.3
https://github.com/leongersen/noUiSlider/releases/tag/14.6.3
> Update to noUiSlider v14.6.3

- build/templates/UmbracoSolution/UmbracoSolution.csproj
-  Copy static files to publish directory in dotnet template
Fixes https://github.com/umbraco/Umbraco-CMS/issues/9811
> Netcore: Copy static files to publish directory in dotnet template

- src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
- src/Umbraco.Tests/Configurations/UmbracoSettings/ContentElementTests.cs
- src/Umbraco.Tests/Configurations/UmbracoSettings/umbracoSettings.config
- src/Umbraco.Web.UI/config/umbracoSettings.Release.config
> Added more extensions to disallowed upload files

- src/Umbraco.Web/AspNetHttpContextAccessor.cs
- src/Umbraco.Web/FormDataCollectionExtensions.cs
- src/Umbraco.Web/HtmlHelperRenderExtensions.cs
- src/Umbraco.Web/HttpUrlHelperExtensions.cs
- src/Umbraco.Web/HybridEventMessagesAccessor.cs
- src/Umbraco.Web/ModelStateExtensions.cs
- src/Umbraco.Web/WebApi/AngularJsonMediaTypeFormatter.cs
341 / 5000
Translation results
- [] I added steps in the description below to test this contribution
- [] I haven't made any changes in Testing Phase.
<!
* I have seen and fixed that some functions that should be async are not used as async.
**Like This**
* I tried to fix some of the code in accordance with best practice.
**Like This**
->
> Clean Code and use async methed

- src/Umbraco.Web.UI.Client/src/views/contentblueprints/intro.html
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
Updated some danish translations.
> Updating danish translations

- src/Umbraco.Core/Services/Changes/TreeChange.cs
- src/Umbraco.Core/Services/Implement/ContentService.cs
- src/Umbraco.Core/Services/Implement/MediaService.cs
As agreed with @Shazwazza in issue #9389.
> Change access level for TreeChanged event in Media and ContentService

- src/Umbraco.Web/Editors/BackOfficeController.cs
This is a PR related to existing issue  #9407 
Added [UmbracoAuthorize] attribute to ExternalLinkLoginCallback method in BackOfficeController.
> Added UmbracoAuthorize attribute for BackOfficeController.ExternalLinkLoginCallback

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/config.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/config.html
- src/Umbraco.Web.UI/config/grid.editors.config.js
> Should allow grid editors to use hash based settings

- src/Umbraco.Core/Composing/TypeLoader.cs
This deadlock can occur in both v8 and the netcore branches, this fix is for v8 (the netcore fix is #9959)
This is why:
There is actually no reason at all for GetFileBasePath to use the _locko lock and I believe it was used by accident and just re-using an existing lock field. The GetFileBasePath method is actually just a lazy initializer for a value so that's what it should be and that is how this is fixed. Now we have a Lazy _fileBasePath which is initialized with GetFileBasePath and then _fileBasePath.Value is used where needed and this fixes the deadlock.
> Fix dead lock with TypeLoader

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
- src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10030
> Netcore: Fix no authentication schema was specified bugs

- build/azure-pipelines.yml
- src/Umbraco.Tests.AcceptanceTest/cypress.json
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/languages.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/templates.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
- src/Umbraco.Tests.AcceptanceTest/package.json
This will run the acceptance tests as a separate stage in the pipeline when new pull requests are made.
Pleasse squash this commit when merging.
> Netcore: Run acceptance tests on azure pipelines

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
- src/Umbraco.Tests.AcceptanceTest/package.json
Added two new cypress tests "Content with macro in RTE" and "Content with macro in grid"
> Add new cypress tests

- src/Umbraco.Web.BackOffice/Trees/MenuRenderingNotification.cs
- src/Umbraco.Web.BackOffice/Trees/RootNodeRenderingNotification.cs
- src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10054
Added `TreeAlias` to the following notifications
- MenuRenderingNotification
- RootNodeRenderingNotification
>  Added `TreeAlias` to tree notifications

- src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
- src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
- src/Umbraco.Infrastructure/Services/Implement/MacroService.cs
- src/Umbraco.Infrastructure/Services/Notifications/MacroDeletedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/MacroDeletingNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/MacroSavedNotification.cs
- src/Umbraco.Infrastructure/Services/Notifications/MacroSavingNotification.cs
- src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
Migrated the static events in `MacroService` over to the new notifications pattern.
You can use this code for testing, when you create/delete macro you should see an entry in the log. If you want to go above and beyond you can also try cancelling the events in the "ing" notifications (such as MacroSaving) like this: ```            notification.CancelOperation(new EventMessage("Canceling", "Testing"));```
```c#
using Microsoft.Extensions.Logging;
using Umbraco.Cms.Infrastructure.Services.Notifications;
namespace Umbraco.Cms.Web.UI.NetCore
{
public class TestNotificationHandler :
INotificationHandler<MacroSavingNotification>,
INotificationHandler<MacroSavedNotification>, …
```
> Netcore: Migrate macroservice events

- src/Umbraco.Web.UI.Client/src/less/components/editor/umb-variant-switcher.less
I saw it, became annoyed, fixed it. Big stuff!
Before:
After:
> Aligned variant icon.

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Persistence/Mappers/MapperForAttribute.cs
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Web.BackOffice/Filters/FileUploadCleanupFilterAttribute.cs
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
This PR makes two internal classes public - used in the Forms package - and removes the configuration that makes all internals visible to Forms.
> Removed project configuration to expose internals to Forms and made the two used internal dependencies public.

- src/Umbraco.Infrastructure/Persistence/Querying/SqlTranslator.cs
- src/Umbraco.Web.BackOffice/Extensions/ModelStateExtensions.cs
As discussed - not sure why we didn't see these before, but they are marked internal currently not accessible from forms.
> Made two further classes public to provide access for Forms and other packages.

- src/Umbraco.Infrastructure/Security/MemberUserStore.cs
If only the last login property has changed we can issue a SQL call without write locks to make that update. This is what we do in v8.
> Ensure we don't issue a write lock on member login

- src/Umbraco.Web.BackOffice/Filters/FileUploadCleanupFilterAttribute.cs
Fixes issue #10162.
As noted in the issue, we aren't using this code path in CMS but we do in Forms.  I've tested this by implementing the code first in the Forms repo and then once verified copied into CMS for this PR.
> Fixes FileUploadCleanupFilterAttribute when incomimg model is not provided.

- src/Directory.Build.props
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
Get more green checkmarks for Nuget builds
https://github.com/clairernovotny/DeterministicBuilds
https://mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking
https://lurumad.github.io/using-source-link-in-net-projects-and-how-to-configure-visual-studio-to-use-it
> Deterministic Builds for Sourcelink 

- src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10251
> V9: Fix issue with scheduling

- src/Umbraco.Core/Models/Entities/BeingDirtyBase.cs
If there's an existing issue for this PR then this fixes N/A
Improve IsDirty() check performance.
Use ContainsKey for Dictionaries as it's O(1) instead of O(n) using Any()
How to test?
Existing ContentService tests pass.
> Improve IsDirty() check performance.

- src/Umbraco.Web/Routing/PublishedContentNotFoundHandler.cs
I think it will be useful to include a link to the documentation on how to create a custom 404
> Added a link to 404 documentation

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
- src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
- src/Umbraco.Web/Umbraco.Web.csproj
- Updated most of the nuget packages.
> Update nuget packages

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediaentryeditor/mediaentryeditor.html
fixes https://github.com/umbraco/Umbraco-CMS/issues/10306
> Use label in MediaPicker3 cropper

- src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js
Added missing dependency, to fix js issue that its undefined.
> added windowResizeListener

- src/Umbraco.Web.UI.Client/src/less/components/umb-range-slider.less
> dont remove outline

- src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyEditor.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10295
> V9: Fix issue with determining the uploaded media type

- src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.html
> Complex validation for RTE property editor

- src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/de.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/es.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/pl.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/ru.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
Added the missing CDATA tag for #10128
> added cdata on sectionMandatoryDesc for other languages

- src/Umbraco.Web.UI.Client/src/common/services/keyboard.service.js
Related to https://github.com/umbraco/Umbraco-CMS/pull/10023 and https://github.com/umbraco/Umbraco-CMS/pull/10347
> Fix issue with extend of object in keyboard service

- src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
Injected the clearAddUserForm().
This fixes #10280
> inject clearAddUserForm() to inviteUser condition

- src/Umbraco.Tests.Common/Builders/DataEditorBuilder.cs
- src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/DataTypeBuilderTests.cs
Small update to one of the unit test model builders needed to support a test in Deploy.
> Adds fields to unit test model builder for data editors.

- src/Umbraco.Core/PropertyEditors/MediaPicker3Configuration.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10289
> V9: Fixed serialization issue Amount (min and max) isn't stored and working with Media picker 3

- src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
Just a small thing I spotted in passing.
> Fixed typo in AddUnattendedInstallInstallCreateUser(this method name.

- src/Umbraco.Web.UI.Client/src/less/components/umb-list-view-settings.less
- src/Umbraco.Web.UI.Client/src/less/listview.less
Remove margin bottom at input fields
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10307
When accessing the listview configuration via the overlay from a document type, the sorting icon at "Columns Displayed" was set to zero.
> Fix styling issues with listview sorting in overlay

- build/templates/UmbracoProject/UmbracoProject.csproj
Noticed a tiny typo while trying out v9.
> fixed a typo in the UmbracoProject template

- src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
Fixes issue [#10433](https://github.com/umbraco/Umbraco-CMS/issues/10433) - View Model validation fails with any value type
> Allow value types as View Models

- src/Umbraco.Core/PropertyEditors/FileExtensionConfigItem.cs
> V9 - Adds missing DataContract to FileExtensionConfigItem 

- src/Umbraco.Infrastructure/Security/MemberIdentityUser.cs
- src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
- src/Umbraco.Web.Website/Controllers/UmbRegisterController.cs
> Approve member when created with built-in macros

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
> V9: Updated nuget dependencies

- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
> Add lang to extended valid elements for span

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
Fixes the acceptance test  "Content with contentpicker" that are failing on each run.
> Fixes the acceptance tests "Content with contentpicker"

- src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
<s>- Changing the built-in cache at **NestedContentValues** level for Content Types - before that dictionary cache was never used because it was short-lived and re-created while looping through the items. Now, it is created in **NestedContentPropertyValueEditor** and passed on, so it can be reused.</s>
- Calling `GetValueEditor()` for unique data type ids - reducing the number of objects allocated
> Nested content optimizations

- src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
> V9: Show cultures in dropdown with english names

- src/Umbraco.Web.Common/Controllers/UmbracoAuthorizedController.cs
This PR adds back the `UmbracoAuthorizedController`, this is just a helper to make a normal controller that gets authorized for back office, it's described in the V8 docs [here](https://our.umbraco.com/documentation/Reference/Routing/Authorized/#mvc-controllers-for-the-backoffice)
I've tested it out and everything seems to work, to test, first add a controller: 
```C#
using Umbraco.Cms.Web.Common.Controllers;
namespace Umbraco.Cms.Web.UI.NetCore
{
[Area("Test")]
public class AuthController : UmbracoAuthorizedController
{
public IActionResult Index()
{
return Content("Hello from authorized controller");
}
}
}
```
And register it, I used a composer, since I can re-use it for V9 docs 😉 
```C#
using Microsoft.AspNetCore.Builder;
using …
```
> V9: Add UmbracoAuthorizedController

- src/Umbraco.Web.Common/Extensions/FriendlyUrlHelperExtensions.cs
- src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
- src/Umbraco.Web/UrlHelperRenderExtensions.cs
Migrated the SurfaceAction extension methods on UrlHelper + Added friendly extensions too
> V9: Migrated surfaceaction extension methods

- src/Umbraco.Web.UI.Client/src/installer/steps/error.html
Change path of the log folder since the App_Data folder doesn't exist anymore.
> Change path to log files in error.html (installation)

- src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
- src/Umbraco.Core/Migrations/Upgrade/V_8_15_0/UpdateCmsPropertyGroupIdSeed.cs
- src/Umbraco.Core/Persistence/Dtos/PropertyTypeGroupDto.cs
- src/Umbraco.Core/Umbraco.Core.csproj
This fixes #10381. 
Turns out it was not a problem with installing packages containing document types, but instead that you simply can't create more than 39 property type groups at all before getting this error 😱.
This is because when the new media types were adding, 4 new property type groups were also added with ID 52, 53, 54, and 55, however, the identity seed was not updated to 56, but was still the old 12, meaning that once you tried to create your 40th property group the ID would be 52 and you will get a duplicate value error because the ID must be unique. This also means that this has been a problem since the new media types were added (Video, Audio, Article, Vector Graphics).
This was only a problem with SQL CE because for SQL Server we don't use the seed to determine what the …
> Fix duplicate ID when creating document types with SQL CE

- src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js
- src/Umbraco.Web.UI.Client/src/common/services/windowresizelistener.service.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10743
This PR fixes issue https://github.com/umbraco/Umbraco-CMS/issues/10743 where console was throwing an error, when selecting a crop in Media Picker v3.
> Inject windowResizeListener in Image Crop directive

- src/Umbraco.Core/Composing/CompositionExtensions.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.DistributedCache.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Uniques.cs
- src/Umbraco.Web.Website/Extensions/WebsiteUmbracoBuilderExtensions.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/10648
Updated `IUmbracoBuilder` public extension methods to return the `IUmbracoBuilder` instance to allow for method chaining.
> Updated public IUmbracoBuilder extension methods to allow chaining

- src/Umbraco.Core/Persistence/Dtos/ContentTypeDto.cs
- src/Umbraco.Core/Persistence/Dtos/PropertyTypeDto.cs
Automatically intern Alias properties for SQL queries to save on memory and improve performance.
> Automatically intern Alias properties for SQL queries

- src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.DictionaryOfPropertyDataSerializer.cs
Fixes issue of creating new Empty arrays during NuCache deserialization.
> 8.15RC Don't create new empty arrays

- src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
This fixes a part of the issue https://github.com/umbraco/Umbraco-CMS/issues/9614
In this PR I have changed the z-index of the umb-notifications component.
> Changed umb-notifications z-index

- build/templates/UmbracoProject/UmbracoProject.csproj
Fixes #10640
Fixes #10773
After installing Umbraco through the _Umbraco Templates_, when attempting to publish the project (either with the VS publish option or with the `dotnet publish` command), the output in the **/bin/net5.0/publish/umbraco** directory should contain **only** the following directories (with their corresponding content): 
- `config`
- `models`
- `PartialViewMacros`
- `UmbracoBackOffice`
- `UmbracoInstall`
- `UmbracoWebsite`
Folders like `umbraco/Logs`, `umbraco/Data` and `umbraco/MediaCache` should not be present.
---  
The folders that we want to be excluded are listed as `Content Remove`, `Compile Remove`, `EmbeddedResource Remove` and `None Remove`. 
`None Remove` is moved after `None Include` in the same `ItemGroup`.
---
- Uninstall previous template pack using …
> V9: Umbraco Templates - remove unwanted folders on publish

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.controller.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10572
> #10572 watch model value

- src/Umbraco.Web.UI.Client/package.json
This PR update noUiSlider to latest v15.4.0
https://github.com/leongersen/noUiSlider/releases/tag/15.4.0
> Update to noUiSlider v15.4.0

- src/Umbraco.Core/Diagnostics/MiniDump.cs
- src/Umbraco.Infrastructure/Persistence/LocalDb.cs
- src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
Process class needs to be disposed as it is IDisposable.
> Process requires disposal

- src/Umbraco.Web.Common/ModelsBuilder/RefreshingRazorViewEngine.cs
Cleanup _inMemoryModelFactory.ModelsChanged event on dispose in  RefreshingRazorViewEngine
> Cleanup _inMemoryModelFactory.ModelsChanged event on dispose in  RefreshingRazorViewEngine

- src/Umbraco.Core/Constants-CharArrays.cs
- src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
- src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
- src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
Reduce allocations by using existing CharArrays for TrimStart()
> Reduce allocations by using existing CharArrays for TrimStart()

- build/templates/UmbracoProject/Views/_ViewImports.cshtml
- src/Umbraco.Web.UI.NetCore/Startup.cs
- src/Umbraco.Web.UI.NetCore/Views/_ViewImports.cshtml
This just helps users who wish to use Smidge in their frontend views a little easier by adding the TagHelper and injecting SmidgeHelper to align with Shan's examples on the Smidge repo.
* From the CI build update dotnet new templates
* Create new dotnet new umbraco --name TestingSmidge
* Try some of the examples from Shan's docs
https://github.com/Shazwazza/Smidge/wiki/Declarations
https://github.com/Shazwazza/Smidge/wiki/Rendering
https://github.com/Shazwazza/Smidge/wiki/Bundling-strategies
> V9: Help improve using Smidge in FrontEnd views

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/DictionaryTablesIndexes.cs
Additional refactoring based on the [comment](https://github.com/umbraco/Umbraco-CMS/pull/10826#issuecomment-900176240) of #10826.
> V9: Keep the old indexes in case the DictionaryTablesIndexes migration fails

- src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Creating content tour (with no SK) had a problem with CSS selector as you was unable to input the text into the textarea on step 6 of 7
> Minor tour update

- src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbsearchfilter.directive.js
- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreesearchbox.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-file-icon.less
- src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less
- src/Umbraco.Web.UI.Client/src/less/forms.less
- src/Umbraco.Web.UI.Client/src/less/panel.less
- src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-box.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-file-icon.html
- src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
After PR #10805 was merged I noticed some styling issues with `<umb-file-icon>`.
I also fixed a few issues with icons in list mode.
> Adjust styling of umb-file-icon

- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Ensure Nuget dependencies are upto date except NPoco as breaking changes in major
> Ensure Nuget dependencies are upto date except NPoco as breaking changes in major

- src/Umbraco.Core/Diagnostics/MiniDump.cs
- src/Umbraco.Core/Persistence/LocalDb.cs
- src/Umbraco.Core/Sync/DatabaseServerMessenger.cs
Prevent leaks by disposing Process instance.
<!-- Thanks for contributing to Umbraco CMS! --
> DIspose Process

- build/NuSpecs/UmbracoCms.Core.nuspec
- src/Umbraco.Core/Umbraco.Core.csproj
Update Serilog.Enrichers.Process to 2.0.2 as it fixes a leak
> Update Serilog.Enrichers.Process to 2.0.2 as it fixes a leak

- src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
Fixed potential null reference exception in KeepAlive
> Fixed potential null reference exception in KeepAlive

- src/Umbraco.Web/HealthCheck/Checks/Security/HttpsCheck.cs
Dispose X509Certificate2 as it is IDisposable
> Dispose X509Certificate2 handle in https check

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
Suggestion to fix #10955
Updating ``model.value`` in ``multiUrlPickerController`` when picker dialog is submitted.
> emit formSubmitting when submitting change in multi url picker dialog

- src/Umbraco.Core/Security/MachineKeyGenerator.cs
- src/Umbraco.Core/Security/MembershipProviderBase.cs
Dispose RNGCryptoServiceProvider as it is IDisposable
Dispose KeyedHashAlgorithm
> Dispose RNGCryptoServiceProvider

- src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10927
while still support the fix for https://github.com/umbraco/Umbraco-CMS/issues/10627
> Fixed issue where keys are shown instead of values

- src/Umbraco.Web.UI.Client/src/views/content/content.delete.controller.js
Close delete dialog if response has a notification
Close delete dialog if show ysod dialog
Fixes #10980
See also:
https://github.com/umbraco/Umbraco-CMS/issues/10982#issuecomment-910307952
> Close delete dialog if response has notifications

- src/Umbraco.Core/Models/ContentEditing/NotificationStyle.cs
- src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedApiController.cs
- src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedJsonController.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/10403
- Removed attributes from UmbracoAuthorizedJsonController.cs
- Added those attributes to UmbracoAuthorizedController.cs
- Set up a new document type with a rich text editor and tags
- Try making some content and fill out a few tags
- Upload an image in the rich text editor
- Save content
- Navigate to the contents information 
- Go to settings and click published status and try to reload the Memory Cache, this should hit all affected classes and everything should work as intended 👍
> v9: Bugfix - Implemented attribute changes in controller

- src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
- src/Umbraco.Infrastructure/Persistence/DbConnectionExtensions.cs
- src/Umbraco.Web.UI.Client/package-lock.json
Fixes https://github.com/umbraco/Umbraco-CMS/issues/11056
+ missing ensured package-lock.json is up-to-date
> Fixes issue when ConnectionStrings.umbracoDbDSN is missing

- src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
The `HttpsCheck` health check stored the amount of days the certificate is valid in a static field and didn't update it in subsequent checks. Besides concurrency issues, not updating the value would cause the check to silently ignore certificates that are about to expire.
Because the static field/value is reset on an application restart and you're alerted when the certificate is valid for less than 14 days, the real-world impact will be minimal though. But once the certificate will expire within this period, it's nice to see it correctly updated in the health check message (if the application doesn't restart daily).
> Fix concurrency and certificate days to expiry issues in HttpsCheck

- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/urlpicker.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/DataTypes/dataTypes.ts
- src/Umbraco.Tests.AcceptanceTest/cypress/integration/Tabs/tabs.ts
- src/Umbraco.Tests.AcceptanceTest/package.json
- Implemented Tabs test
- Implemented UrlPicker test
- Implemented ApprovedColorPicker test
- Run a clean install of v8
- Run the installer
- Run your console
- Navigate to Umbraco.Tests.AcceptanceTest
- In your console run `npm install`
- Run `npm run ui`
- Run the tests and they should pass
> Feature - Implemented new cypress tests

- src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
Added dutch translation for the key blockEditor_addBlock
> Missing nl translation for blockEditor_addBlock

- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
- src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- src/Umbraco.Tests/Umbraco.Tests.csproj
Waiting for unit tests to succeed before merging
> Update Examine dependencies to 2.0.0

- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
> Fix for dotnet6 preview1 when using runtime compiled views (default umbraco)

- src/Umbraco.Core/Services/IContentTypeServiceBase.cs
- src/Umbraco.Core/Services/IDataTypeService.cs
- src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
- src/Umbraco.Infrastructure/Services/Implement/DataTypeService.cs
- src/Umbraco.Infrastructure/Services/Implement/EntityXmlSerializer.cs
- src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
- src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
- src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
Fixes #11170..
Adds folder keys to datatype folders and content folders..
> Add folderkeys to package xml.

- src/Umbraco.Web.UI/umbraco/config/lang/cs.xml
- src/Umbraco.Web.UI/umbraco/config/lang/cy.xml
- src/Umbraco.Web.UI/umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/umbraco/config/lang/de.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
- src/Umbraco.Web.UI/umbraco/config/lang/es.xml
- src/Umbraco.Web.UI/umbraco/config/lang/fr.xml
- src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
- src/Umbraco.Web.UI/umbraco/config/lang/pl.xml
- src/Umbraco.Web.UI/umbraco/config/lang/ru.xml
- src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
- src/Umbraco.Web.UI/umbraco/config/lang/tr.xml
- src/Umbraco.Web.UI/umbraco/config/lang/zh.xml
- src/Umbraco.Web.UI/umbraco/config/lang/zh_tw.xml
Reintroducing keys removed in #11111 as such keys were constructed programmatically and weren't detected on the first test.
> V9: Reintroducing some language keys

- src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-color-swatches.less
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.controller.js
@nathanwoulfe @nul800sebastiaan Please use this PR over #11015, which I by mistake made in the wrong repo. Think all my weird issues with too many commits etc. from my branches have finally been resolved now 😅 🤞🏻
> Use medium sized overlay

- build/templates/UmbracoProject/UmbracoProject.csproj
Added CopyRazorGenerateFilesToPublishDirectory to the template
Fixes: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/457
> Added CopyRazorGenerateFilesToPublishDirectory to the template

- src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
- src/Umbraco.Core/Models/ContentEditing/HistoryCleanup.cs
- src/Umbraco.Core/Models/ContentType.cs
- src/Umbraco.Core/Models/IContentType.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
- src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
- src/Umbraco.Core/Services/IContentVersionService.cs
- src/Umbraco.Core/Services/Implement/ContentService.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Tests.AcceptanceTest/package.json
- src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
- src/Umbraco.Tests/Scheduling/ContentVersionCleanup_Tests_UnitTests.cs
- src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
- src/Umbraco.Tests/Services/ContentVersionCleanupService_Tests_Integration.cs
- src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
- src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.controller.js
- src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
- src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
- src/Umbraco.Web/Models/ContentEditing/ContentTypeSave.cs
- src/Umbraco.Web/Models/ContentEditing/DocumentTypeDisplay.cs
- src/Umbraco.Web/Models/ContentEditing/HistoryCleanup.cs
- src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
- src/Umbraco.Web/Scheduling/ContentVersionCleanup.cs
- src/Umbraco.Web/Scheduling/SchedulerComponent.cs
- src/Umbraco.Web/Umbraco.Web.csproj
Added UI to history cleanup per doctype
+ Renamed IContentVersionCleanupService to IContentVersionService
> V8: Added UI to configure history cleanup per doc type

- src/Umbraco.Infrastructure/Services/Implement/ContentVersionService.cs
- tests/Umbraco.Tests.UnitTests/AutoFixture/AutoMoqDataAttribute.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/ContentVersionCleanupServiceTest.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Fixed up tests for ContentVersionService. 
Related to https://github.com/umbraco/Umbraco-CMS/pull/11562
> Added unit tests for ContentVersionService

- tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Users/users.ts
FYI this is for hacktoberfest 🎃 
- Switched request code to use umbracoApiRequest
- Added aftereach hook to ensure cleanup and remove duplicate code
- Changed variables to constants to remove duplicates
- Run the cypress test
- They should all pass  🙏
> v9: Update 'User' Cypress tests

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/userpicker/userpicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/userpicker/userpicker.html
If there's an existing issue for this PR then this fixes  https://github.com/umbraco/Umbraco-CMS/issues/11520
This fixes the filter of the userpicker. The search function wasn't used and has been removed. Instead, I've added a filter to the `ng-repeat`
To test this create a userpicker and try searching.
> Fixes userpicker filter

- src/Umbraco.Web.UI.Client/src/views/dashboard/content/overlays/delete.html
I have added a missing fallback text for "Confirm delete" in this PR.
> Overlay delete view: Add missing fallback text

- src/Umbraco.Core/DependencyInjection/IScopedServiceProvider.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- src/Umbraco.Infrastructure/IPublishedContentQueryAccessor.cs
- src/Umbraco.Infrastructure/PublishedContentQueryAccessor.cs
- src/Umbraco.Web.Common/DependencyInjection/ScopedServiceProvider.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
- tests/Umbraco.Tests.Integration/Umbraco.Core/PublishedContentQueryAccessorTests.cs
> Make PublishedContentQueryAccessor usable

- src/Umbraco.Web.UI.Client/src/views/scripts/create.html
Add missing fallback text ensuring a text will be rendered in case language files are out of sync.
> Create view: Add missing fallback text

- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
Add missing fallback texts ensuring a text will be available in case translation files are out of sync.
> List: Add missing fallback texts

- src/Umbraco.Core/Handlers/AuditNotificationsHandler.cs
- src/Umbraco.Core/Models/ContentEditing/UserGroupPermissionsSave.cs
- src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
- src/Umbraco.Core/Services/UserServiceExtensions.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_2_0/AddUserGroup2NodeTable.cs
- src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2NodeDto.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PermissionRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserGroupRepository.cs
- src/Umbraco.Infrastructure/Services/Implement/UserService.cs
- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
- src/Umbraco.Web.UI.Client/src/views/content/content.rights.controller.js
- src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/11458
- Run the client project;
- Follow the steps listed in the original issue;
- Test migration by upgrading from different db types.
> V9: Fix granular permissions for user groups

- src/Umbraco.Web.UI.Client/src/views/documenttypes/views/listview/listview.html
Add missing fallback texts ensruing a text will be rendered in case language files are out of sync.
> List view: Add missing fallback texts

- src/Umbraco.Web.UI.Client/src/views/media/sort.html
Add missing fallback text ensuring a text will be rendered in case language files are out of sync.
> Media Sort view: Add missing fallback text sort view media

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
Add missing fallback texts ensruing a text will be rendered in case language files are out of sync.
> Media Picker: Add missing fallback texts

- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
When using the `GetCropUrl()` extension method, you can provide a `cacheBusterValue` that is added as `rnd` query string parameter. This value is automatically set to the update date of a media item if you use this extension method on an `IPublishedContent` instance:
https://github.com/umbraco/Umbraco-CMS/blob/7524b7809cd9db1739b178001e92cb2f33d73cda/src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs#L276
Because this value changes the URL, the browser cache isn't used and the full image is requested. The response can then be cached again because of the `Cache-Control: public, must-revalidate, max-age=604800` header (the max-age can be configured using `Umbraco:CMS:Imaging:Cache:BrowserMaxAge`). If you refresh a page, it will issue a conditional request for all the …
> Change Cache-Control header when cache buster value is present

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
- src/Umbraco.Core/Media/EmbedProviders/DailyMotion.cs
- src/Umbraco.Core/Media/EmbedProviders/EmbedProviderBase.cs
- src/Umbraco.Core/Media/EmbedProviders/Flickr.cs
- src/Umbraco.Core/Media/EmbedProviders/GettyImages.cs
- src/Umbraco.Core/Media/EmbedProviders/Giphy.cs
- src/Umbraco.Core/Media/EmbedProviders/Hulu.cs
- src/Umbraco.Core/Media/EmbedProviders/Issuu.cs
- src/Umbraco.Core/Media/EmbedProviders/Kickstarter.cs
- src/Umbraco.Core/Media/EmbedProviders/OEmbedProviderBase.cs
- src/Umbraco.Core/Media/EmbedProviders/OEmbedResponse.cs
- src/Umbraco.Core/Media/EmbedProviders/Slideshare.cs
- src/Umbraco.Core/Media/EmbedProviders/SoundCloud.cs
- src/Umbraco.Core/Media/EmbedProviders/Ted.cs
- src/Umbraco.Core/Media/EmbedProviders/Twitter.cs
- src/Umbraco.Core/Media/EmbedProviders/Vimeo.cs
- src/Umbraco.Core/Media/EmbedProviders/Youtube.cs
Suggested improvements in comments: https://github.com/umbraco/Umbraco-CMS/pull/11691#issuecomment-979885262 implemented
> Rename AddOEmbedProvider() and Obsolete OEmbedProviders()

- build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.targets
Fixes #11758, please see the issue for a full explanation and reproduction steps.
> Ensure Umbraco Razor files are compiled into <project>.Views.dll

- src/Umbraco.Core/Sync/ApplicationUrlHelper.cs
- src/Umbraco.Tests/Web/Controllers/AuthenticationControllerTests.cs
- src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs
- src/Umbraco.Web/Editors/AuthenticationController.cs
- src/Umbraco.Web/Editors/UsersController.cs
I had to expand the `UsersController` and `AuthenticationController` constructors, but as I recall we don't consider this breaking changes in V8?
> Use current request for emails

- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
- src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
Use current request for emails
> V9: Use current request for emails

- src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
Add readmore key in general area (Dutch translation file)
> Localization: Add missing 'read more' translation (Dutch)

- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Updates the referenced ImageSharp.Web version to [v1.0.5](https://github.com/SixLabors/ImageSharp.Web/releases/tag/v1.0.5) which contains an important fix to ensure invalid format commands don't get processed.
> Bump ImageSharp.Web version to v1.0.5

- src/Umbraco.Core/Models/PropertyTagsExtensions.cs
- src/Umbraco.Core/PropertyEditors/DataValueEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyValueEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/MultipleTextStringPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/MultipleValueEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/TagsPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
- src/Umbraco.Infrastructure/Serialization/JsonNetSerializer.cs
- src/Umbraco.Infrastructure/Serialization/JsonToStringConverter.cs
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockEditorComponentTests.cs
Some of the changes from #11805 and #11806 couldn't be easily merged to v9: this PR should apply all of them.
> Apply changes from #11805 and #11806 to v9

- src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
- src/Umbraco.Web.BackOffice/Services/ConflictingRouteService.cs
Only conflict if the PluginControllerAttribute' area is the same..
> Add check for PluginControllerAttribute and compare area name

- src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
> Removed if-check to allow empty values from blocks

- src/Umbraco.Core/Constants-Icons.cs
- src/Umbraco.Web.BackOffice/Trees/ContentBlueprintTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
Just a few adjustments to use icons from `Constants` class and a minor change to create empty array of `IEntitySlim` instead of `IUmbracoEntity` as the GetAll() method returns `IEnumerable<IEntitySlim>` .. the variable docTypeEntities is then `IEnumerable<IEntitySlim>` instead of ``IEnumerable<IUmbracoEntity>`.
> Constant icon blueprint

- src/Umbraco.Web.UI.Client/src/views/content/content.protect.controller.js
The issue is described here: https://github.com/umbraco/Umbraco-CMS/issues/10420
> encode group name to avoid the issue

- src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
- src/Umbraco.Web.UI/Composers/ControllersAsServicesComposer.cs
Closes GH #11764
Steps to test, comment out AddControllersWithAmbiguousConstructors and try run web.UI, note exception.
> Prevent issues for those who wish use ServiceBasedControllerActivator.

- src/Umbraco.Core/Services/ITwoFactorLoginService.cs
- src/Umbraco.Infrastructure/Services/Implement/TwoFactorLoginService.cs
- src/Umbraco.Web.Common/Security/TwoFactorValidationProvider.cs
- Fixed ctor of `TwoFactorBackOfficeValidationProvider` do container can find it
- added some XML docs
- also check if a provider is added for users
> Fixed minor issues and added xml docs

- src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
Translate "Create dictionary item" to Dutch
>  Localization:  Translate "Create dictionary item" to Dutch

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/SimilarNodeName.cs
If there's an existing issue for this PR then this fixes #11977
> Temp 11977 - Fixes 11977 Content Name auto-numbering is not incrementing

- src/Umbraco.Core/Constants-HttpClients.cs
- src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
e.g. a self signed certificate for kestrel on localhost
> Ignore certificate errors for KeepAlive task.

- src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
… so content templates can be moved to content section.
When moving content templates tree to content section, editors (or users not having access to document types tree) got an error when creating a content template from Content Templates tree node.
```
public class TreeComposer : IComposer
{
{
builder.Trees().RemoveTreeController<ContentBlueprintTreeController>();
}
}
```
```
[Authorize(Policy = AuthorizationPolicies.SectionAccessContent)]
[Tree(Constants.Applications.Content, Constants.Trees.ContentBlueprints, SortOrder = 10)] //TreeGroup = Constants.Trees.Groups.Settings
[PluginController(Constants.Web.Mvc.BackOfficeTreeArea)]
[CoreTree]
public class ContentTemplatesController : ContentBlueprintTreeController
{
public …
```
> Grant access to get all content types 

- src/Umbraco.Core/Security/LegacyPasswordSecurity.cs
Add using statements for IDisposables
> Add using statements for IDisposables

- build/azure-pipelines.yml
Update docfx dependency to v2.59
> Update docfx dependency

- build/azure-pipelines.yml
- src/ApiDocs/umbracotemplate/partials/class.tmpl.partial
Fix docfx namespace
The build artifacts can be found here https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=84685&view=results
> Fix docfx namespace

- src/ApiDocs/umbracotemplate/partials/class.tmpl.partial
Fixes https://github.com/umbraco/UmbracoDocs/issues/2641
> Fix issue with namespace in api docs

- src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
Resolve various points related to deficiencies in FileSystemMainDomLocksee #12049
> Resolve various points related to deficiencies in FileSystemMainDomLock

- src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
- src/Umbraco.Infrastructure/Runtime/SqlMainDomLock.cs
- tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Runtime/FileSystemMainDomLockTests.cs
Further changes requested during review of #12049
> v9 further improvements filesystem maindomlock

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html
- src/Umbraco.Web.UI/umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
Removed and re-phrased the references to Umbraco.tv with a minor alteration to the wording. The hyperlink now points to the Umbraco Learning Base YouTube channel.
> Settings Dashboard Umbraco.tv References

- src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
- src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
- src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
Dispose ManualResetEvent as it is IDisposable.
> Prevent DatabaseServerMessenger handle leak 

- src/Umbraco.Web.UI.Client/src/common/services/mediapreview.service.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediaentryeditor/mediaentryeditor.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10943
This PR is a update of https://github.com/umbraco/Umbraco-CMS/pull/10966 for v9
https://user-images.githubusercontent.com/2919859/155784434-d215273a-81d5-4664-ab59-446a39ef0718.mp4
> Media entry editor listview children

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/Install/InstallSteps/TelemetryIdentifierStep.cs
- src/Umbraco.Core/Telemetry/ISiteIdentifierService.cs
- src/Umbraco.Core/Telemetry/SiteIdentifierService.cs
- src/Umbraco.Core/Telemetry/TelemetryService.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Installer.cs
- src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
- src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SiteIdentifierServiceTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
Implements #12035 for V9, see that PR for more info and testing steps.
> V9: Fix missing site identifier

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
Migrates #12069 up to V9, see that PR for more information and testing steps
> V9: Fix missing EditedCultures and Name in content saving notifications

- src/Umbraco.Core/Security/LegacyPasswordSecurity.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/UmbracoPasswordHasherTests.cs
Fixes for https://github.com/umbraco/Umbraco-CMS/issues/12117
Run unit tests, or see linked issue for thorough manual testing steps
> fix additional legacy password formats

- src/Umbraco.Core/Persistence/Repositories/Implement/RedirectUrlRepository.cs
See comment here: https://github.com/umbraco/Umbraco-CMS/issues/10066#issuecomment-1073745536
> Add missing null checks for redirect URLs

- src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html
- src/Umbraco.Web.UI/umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
So we can change it in the future if we need to
> Use an umbra.co link for the TV replacement channel 

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RedirectUrlRepository.cs
Implements the same fix as #12154 for version 9.
> Same fix as #12154 - fixes #10066

- src/Umbraco.Core/StaticApplicationLogging.cs
- src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs
- src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
> Amend breaking change in RecurringHostedServiceBase

- src/Umbraco.Web.Common/ModelsBuilder/InMemoryModelFactory.cs
Should also be ported to v10.
If there's an existing issue for this PR then this fixes #11169.
> Fixes #11169

- build/azure-pipelines.yml
- src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDatabaseCreator.cs
- src/Umbraco.Cms.Persistence.Sqlite/UmbracoBuilderExtensions.cs
Things to test on Linux azure app service
| Database file exists | Connection string configured | InstallMissingDatabase enabled | Unattended Install configued | Expected outcome |
| ------------- | ------------- |------------ |------------ |------------ |
| No | No | No | No | Can complete install process |
| No | Yes | No | No | Boot Failed|
| No | Yes | Yes | No | Can complete install process |
| No | Yes | No | Yes | Boot Failed|
| No | Yes | Yes | Yes | Install process performed automatically |
If it helps, I have dropped the build onto myget
```bash
$ dotnet nuget add source https://www.myget.org/F/umbraconightly/api/v3/index.json --name umbraconightly
$ dotnet new -i Umbraco.Templates::10.0.0-preview20220322.87504
$ dotnet new umbraco --name {{project name}}
```
> v10 - SQLite database creation enhancements

- src/Umbraco.Core/Models/MetricsConsentService.cs
- src/Umbraco.Core/Services/IMetricsConsentService.cs
- src/Umbraco.Core/Services/MetricsConsentService.cs
- src/Umbraco.Web.BackOffice/Controllers/AnalyticsController.cs
- tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MetricsConsentServiceTest.cs
Implements metrics consent service
> Project metrics: Implement metrics consent service

- src/JsonSchema/JsonSchema.csproj
- src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- tests/Umbraco.TestData/Umbraco.TestData.csproj
- tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Updated various nuget dependencies
> Dependency updates

- tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Languages/languages.ts
- Test was trying to click the language folder in the settings section, before it was loaded in,
- Added additional elements to wait on to fix
> Fix flaky language test

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/configuretwofactor.controller.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/configuretwofactor.html
- src/Umbraco.Web.UI/umbraco/config/lang/da.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en.xml
- src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
This PR fixes a regression where admins could no longer disable two-factor for other users.
> Allow admins to disable 2fa for other users without code

- src/JsonSchema/JsonSchema.csproj
In order to reference a couple of new configuration fields.
> Updated references to latest versions of Forms and Deploy in JSONSchema project.

- build/azure-pipelines.yml
Force use of a static global id in acceptance tests
> Use static id for acceptance tests

- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/analytics.html
- src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
- Made text localize instead of hardcoded
- Added better text to analytics dashboard
> V9: make hardcoded text localized

- src/Umbraco.Core/Extensions/StringExtensions.cs
- src/Umbraco.Core/Services/Ordering.cs
- src/Umbraco.Web.BackOffice/Controllers/ContentTypeControllerBase.cs
- src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
One more NRT related update - seems we should allow this function to take a null input, given that is one of the things it's checking for.
> Allowed IfNullOrWhiteSpace to take null input.

- src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
Updating naming and locations of dependencies following regressions from #12288
> v10: Update locations of npm dependencies

- src/Umbraco.Core/Persistence/Repositories/IRedirectUrlRepository.cs
- src/Umbraco.Core/Routing/ContentFinderByIdPath.cs
- src/Umbraco.Core/Routing/ContentFinderByPageIdQuery.cs
- src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
- src/Umbraco.Core/Routing/ContentFinderByUrl.cs
- src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
- src/Umbraco.Core/Routing/ContentFinderByUrlAndTemplate.cs
- src/Umbraco.Core/Routing/IContentFinder.cs
- src/Umbraco.Core/Routing/PublishedRouter.cs
- src/Umbraco.Core/Services/IRedirectUrlService.cs
- src/Umbraco.Core/Services/RedirectUrlService.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RedirectUrlRepository.cs
- src/Umbraco.Infrastructure/Routing/ContentFinderByConfigured404.cs
- tests/Umbraco.Tests.Common/TestLastChanceFinder.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasWithDomainsTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByIdTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByPageIdQueryTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAndTemplateTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlWithDomainsTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/DomainsAndCulturesTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UrlsWithNestedDomains.cs
Depends on https://github.com/umbraco/Umbraco-CMS/pull/12340
Improve redirect content finder scalability by using async calls to the database.
This frees up the request thread to do other work while the program waits for the database to return a result.
How to test?
Existing tests pass. Existing redirects work.
- Added more methods to `IRedirectUrlRepository` and `IRedirectUrlService.cs`
> v10: Improve redirect content finder scalability 

- src/Umbraco.Core/Deploy/IDeployContext.cs
- src/Umbraco.Core/Deploy/IImageSourceParser.cs
- src/Umbraco.Core/Deploy/IMacroParser.cs
- src/Umbraco.Core/Deploy/IServiceConnector.cs
- src/Umbraco.Core/Deploy/IValueConnector.cs
There are a few interfaces used by Deploy in Core, so I need to have these updated in order to apply NRT syntax to the implementations.
> NRT amends necessary for Deploy

- src/Umbraco.Core/Persistence/IQueryRepository.cs
- src/Umbraco.Core/Services/AuditService.cs
- src/Umbraco.Core/Services/ConsentService.cs
- src/Umbraco.Core/Services/ContentService.cs
- src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
- src/Umbraco.Core/Services/DataTypeService.cs
- src/Umbraco.Core/Services/EntityXmlSerializer.cs
- src/Umbraco.Core/Services/ExternalLoginService.cs
- src/Umbraco.Core/Services/FileService.cs
- src/Umbraco.Core/Services/IAuditService.cs
- src/Umbraco.Core/Services/IConsentService.cs
- src/Umbraco.Core/Services/IContentService.cs
- src/Umbraco.Core/Services/IContentTypeServiceBase.cs
- src/Umbraco.Core/Services/IDataTypeService.cs
- src/Umbraco.Core/Services/IExternalLoginService.cs
- src/Umbraco.Core/Services/IExternalLoginWithKeyService.cs
- src/Umbraco.Core/Services/IFileService.cs
- src/Umbraco.Core/Services/IMediaService.cs
- src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
- src/Umbraco.Infrastructure/Security/MemberUserStore.cs
Found a few more services when applying NRT to Deploy that are returning nullable collections, and have made them non-nullable.
> Further amends to NRT definitions

- src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
If there's an existing issue for this PR then this fixes #12254 
This fixes issue #12254 PreviewController returning null causes a error entry in log
> #fix 12254 return emptyresult

- src/Umbraco.Core/Deploy/ArtifactBase.cs
- src/Umbraco.Core/Deploy/ArtifactDeployState.cs
- src/Umbraco.Core/Deploy/ArtifactDeployStateOfTArtifactTEntity.cs
- src/Umbraco.Core/Deploy/IArtifactSignature.cs
- src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs
- src/Umbraco.Core/Models/Mapping/ContentVariantMapper.cs
- src/Umbraco.Core/Models/Mapping/MemberTabsAndPropertiesMapper.cs
- src/Umbraco.Core/Models/Membership/MemberExportModel.cs
- src/Umbraco.Core/Persistence/Repositories/ITemplateRepository.cs
- src/Umbraco.Core/Services/FileService.cs
- src/Umbraco.Core/Services/IFileService.cs
- src/Umbraco.Core/Services/ILocalizationService.cs
- src/Umbraco.Core/Services/IMediaService.cs
- src/Umbraco.Core/Services/IMemberService.cs
- src/Umbraco.Core/Services/IMembershipRoleService.cs
- src/Umbraco.Core/Services/LocalizationService.cs
- src/Umbraco.Core/Services/MediaService.cs
- src/Umbraco.Core/Services/MemberService.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
- src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs
Resolves a few more NRT related issues that came to light in applying the same to Deploy:
- Deploy interfaces and base classes
- Template collection responses
- Content display variant collection
- `IMediaService.GetRootMedia` collection
- `IMemberService.GetMembersByMemberType` collection
- `ILocalizationService.GetRootDictionaryItems` and `GetDictionaryItemChildren` collections
> Further NRT amends

- src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
- src/Umbraco.Infrastructure/Deploy/IGridCellValueConnector.cs
- src/Umbraco.Infrastructure/Models/GridValue.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
- src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs
This _should_ be the last ones necessary for Deploy.
> Further NRT updates for Deploy

- src/Umbraco.Core/Migrations/Upgrade/Common/CreateKeysAndIndexes.cs
> Avoid creating indexes/keys for tables which don't exist yet.

- src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
There's an existing issue for this PR, this fixes https://github.com/umbraco/Umbraco-CMS/issues/12329
No OnSaved, OnChanged events fired when copying document types in the backoffice, as mentioned in the ticket.
This PR fixes that.
> Added the Logic to fire OnSaved And OnChanged events when copying

- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NoNodes.cshtml
- src/Umbraco.Web.UI.Client/src/installer/installer.service.js
Updated the installer screen with the new Umbraco Learning Base instead of Umbraco TV
The same goes for the no nodes screen when you have installed Umbraco 
This will fix the issue https://github.com/umbraco/Umbraco-CMS/issues/12396
> Updated the installer screen, and the no NoNodes.cshtml 

- Directory.Build.props
Required a visual studio restart followed by a rebuild for me
> Fix visual studio build wrt Umbraco.GitVersioning.Extensions

- src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
This should resolve the issues with login after authorization via Umbraco ID (or other external login providers).
> Fixed null check in external login.

- Directory.Build.props
- build/azure-pipelines.yml
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- version.json
> static assets nupkg fixes

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
> Add Two Factor Auth translation (Dutch)

- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
A few adjustment regarding Danish translation for 2FA.
> Adjust Danish translation for 2FA

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
> Translate 'Configure Two Factor' (Dutch)

- src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
- src/Umbraco.Infrastructure/Scoping/LegacyIScopeProvider.cs
- src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
- tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/LegacyScopeProviderTests.cs
- tests/Umbraco.Tests.UnitTests/TestHelpers/PublishedSnapshotServiceTestBase.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/HealthCheckNotifierTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Mapping/MappingTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.PublishedCache.NuCache/SnapDictionaryTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/ContentControllerTests.cs
> Ensure legacy scope returned when using legacy scope provider

- src/Umbraco.Core/Security/IBackofficeSecurity.cs
- src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
- src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
- src/Umbraco.Web.Common/Security/BackofficeSecurity.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/ObjectExtensionsTests.cs
> Revert small breaking change with Attempt<int?>

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
> Fix options monitor setup for connectionstrings

- src/Umbraco.Infrastructure/Scoping/LegacyIScopeProvider.cs
- tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/LegacyScopeProviderTests.cs
> Fix legacy scope provider no longer implementing ICoreScopeProvider

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TwoFactorLoginRepository.cs
Closes https://github.com/umbraco/Umbraco-CMS/issues/12382
> v10: Fix unable to authorize upgrade from versions < 9.3.0

- src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
A few adjustments in `UmbracoViewPage`  to simplify code.
> Simplify code in UmbracoViewPage

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Core/Routing/UrlProvider.cs
- src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
- src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
- src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
> Merge v9.5.1 into v10

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/12538
> Fix inaccurate dependent node list

- .github/CONTRIBUTING.md
This adds a TOC to the Contributing page
> Add TOC to Contributing page

- src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
Add 'Create a new Document Type' key in button area (Swedish translation file)
> Localization: Add missing translation (Swedish)

- tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
Added a new cypress ensure that naming is correct for duplicate content.
Ensure the acceptance tests pass
> Add create content with same name test

- src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
- src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
> V9: Only send telemetry when runtime level is run

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Translate 'Referenced by the following items' to Dutch
> Localization: 'Referenced by the following items'

- src/Umbraco.Web.Common/Middleware/BootFailedMiddleware.cs
While testing PR https://github.com/umbraco/Umbraco-CMS/pull/12631, I noticed the nice BootFailed page wasn't shown. After some digging, I discovered that the `BootFailedMiddleware` was still using `File.Exists()` and `File.ReadAllTextAsync()`, which doesn't work anymore after moving the physical files into the static assets RCL.
To test, throw an exception during boot and ensure you don't have debug mode enabled.
---
_This item has been added to our backlog [AB#20461](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20461)_
> Read BootFailed.html file from WebRootFileProvider

- src/Umbraco.Web.UI.Client/src/less/components/umb-avatar.less
This PR changes the object-fit & object-position properties for umb-avatar component in backoffice to fix the avatar fit issue.
Closes #12637
> Umbraco avatar component updated to fit the image

- src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js
Tested on Umbraco Colab
Fixes: #12617
> Fix: "You have unsaved changes" on media with date picker even though I don't #12617

- src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
**Linked Issue**: #12576 
Reproduction steps are in the issue
**Before** (from the issue)
**After**
> Fix: Package view - Layout not showing correctly in respect to screen size #12576

- src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Force the allowed avatar image types
> Force the allowed avatar image types

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Added a translation item for when a BLE only has a single item available to be added
> Added translation for NL language in BLE

- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
If there's an existing issue for this PR then this fixes ](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/18)
Steps to replicate:
1) Open search modal in the top navigation (top right)
2) Modal will appear (modal is missing modal trap)
Now the focus is trap and will never escape.
> Umbraco-CMS.Accessibility.Issues#18

- src/Umbraco.Core/Extensions/CryptoServiceProviderExtensions.cs
- src/Umbraco.Core/Security/PasswordGenerator.cs
> V9: Replace usage of Random().Next with RNGCryptoServiceProvider

- src/Umbraco.Web/Editors/ContentTypeController.cs
> V8: Only expose the filename when uploading content types

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12735
Fixes broken rollback feature
> Fix broken rollback feature

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.list.controller.js
- src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
Just added a simple `umb-search-filter` in order to better find dictionary items when they start to pile up.
> Added dictionary filter by name

- umbraco.sln
This PR cleans up the solution file. 
Previously there was a lot of outdated/irrelevant stuff in the solution file, this PR removes and reorganizes this.
I've removed the Docs solution folder, there was a lot of unrelated/missing files in it, and at least for me I read the readmes on github, not in my editor, so I've removed it, since it's not really relevant development wise. It's of course important that we have documentation on getting started, but I don't think it needs to live in the solution file. 
I've removed the reference to the build.ps1 file, since it no longer exists.
I've also moved the docfx files, this now lives in the build folder, my reasoning for this is that this is a build concern.
Lastly I've added the `version.json` file to the build folder as well, because it's …
> Clean solution file

- src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
- src/Umbraco.Web.UI.Client/src/less/components/umb-range-slider.less
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12558
In noUiSlider v15.5.0 some browser compatibility issues where fixes, but it also meat it potential broke backward compatibility when overriding default CSS and the `mergeTooltips` function changes a bit: https://refreshless.com/nouislider/examples/#section-merging-tooltips
See https://github.com/leongersen/noUiSlider/issues/1217
**Before**
https://user-images.githubusercontent.com/2919859/182647752-1858620a-f22a-4110-afe4-37feeb15a025.mp4
**After**
https://user-images.githubusercontent.com/2919859/182646987-edc8b2ef-9b7b-49c9-b34b-78d50c5693d3.mp4
> Fix slider merging overlapping tooltips

- src/Umbraco.Infrastructure/Migrations/Expressions/Alter/Table/AlterTableBuilder.cs
Fixes #12676
Not pretty, but at least it is informative.
> Better exception message when using ALTER TABLE and SQLite

- src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
- src/Umbraco.Web.UI.Client/src/less/modals.less
Cherry picked #12797 into dev to fix the modal headings
> Cherry pick: Content modal heading fix (#12797)

- src/JsonSchema/AppSettings.cs
Fixes #12894, see the issue for all the details.
> Update appsettings-schema: remove {Member,User}Password from Umbraco:CMS

- tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Media/media.ts
- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
All credit to @andr317c for creating these new tests! We have some trouble with the cypress-testshelpers package, but we got it working 💪 
- Added new media tests
- Run the new cypress tests
- They should all pass 💪
> Added new media tests

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
Translate some treeHeaders to Spanish:
> Translate TreeHeaders to Spanish

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
> Translate 'settingsGroup' treeHeader to Spanish

- src/Umbraco.Core/Models/Mapping/DictionaryMapDefinition.cs
Fixes breaking change in `DictionaryMapDefinition`
> Fix breaking change in DictionaryMapDefinition

- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
- src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
- src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
- src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12908
This PR change the logo in upgrader from the bitmap logo to a vector logo instead making the logo sharp on screens with a device pixel ratio greather than 1.
**Before**
**After**
Hint: Open the two images above in two separate tabs and switch between these to see the difference.
> Use SVG logo in installer/upgrader

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
> Translate languages area to Español

- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
- src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
This fixes #12918 
Reopened PR #12926
> Fix: Media Picker creates duplicated folders (#12918)

- src/Umbraco.Cms.ManagementApi/ViewModels/Pagination/PagedViewModel.cs
Adds PagedViewModel to the management API
> Add PagedViewModel

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
> Translate content apps to spanish

- src/Umbraco.PublishedCache.NuCache/ContentCache.cs
- Added better error message when trying to publish a variant with no domains set up
> V10: Better error message for no domains

- src/Umbraco.Cms.ManagementApi/Builders/ProblemDetailsBuilder.cs
- src/Umbraco.Cms.ManagementApi/Controllers/NewInstallController.cs
- Implemented new ProblemDetailsBuilder
- Comes with type "Error" if you do call `WithType()` as this is the most common use-case
- Call the installer API with non-valid Data and assert you get the proper ProblemDetails model
- Sample bad request:
```
{
"useIntegratedAuthentication": true,
"id": "5e1ad149-1951-4b74-90bf-2ac2aada9e73",
"providerName": "Microsoft.Data.SqlClient",
"name": "NewInstaller",
"server": ".\\SQLEXPyRESS"
}
```
> New backoffice: Problem details builder

- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- Updated examine dependency, which contains this bugfix we need: https://github.com/Shazwazza/Examine/pull/289
- Follow the `Updating the valuesetvalidator` section from the new Examine documentation: https://github.com/umbraco/UmbracoDocs/pull/4319
> V10: Update examine dependency

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
> Translate "User permissions for languages" feature to dutch

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
> Translate "User permissions for languages" feature to español

- src/JsonSchema/JsonSchema.csproj
This ensures the latest configuration settings available from the most recent releases are included.
> Updated project references for Forms and Deploy in the JsonSchema project.

- src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/CollectPublishedCacheController.cs
- src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/PublishedCacheControllerBase.cs
- src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/RebuildPublishedCacheController.cs
- src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/ReloadPublishedCacheController.cs
- src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/StatusPublishedCacheController.cs
- src/Umbraco.Cms.ManagementApi/OpenApi.json
- tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs
New endpoints for the Published Status dashboard.
Reach out for a Postman collection for testing 😄
> New Backoffice: Published cache controller

- src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/SearchersExamineManagementController.cs
- Notes
- Made Searchers endpoint return `ActionResult<PagedViewModel>` instead of just `PagedViewModel`
> Searchers endpoint should return ActionResult

- src/Umbraco.Infrastructure/PropertyEditors/DropDownFlexibleConfigurationEditor.cs
Just a minor enhancement that we can use `is not` pattern matching.
> Use pattern matching to check if items is not `JArray`

- build/azure-pipelines.yml
- tests/Umbraco.Tests.AcceptanceTest/README.md
- tests/Umbraco.Tests.AcceptanceTest/createTest.js
- tests/Umbraco.Tests.AcceptanceTest/package.json
Because of the switch to playwright, we should also update the `README.md` & `package.json` to reflect this 👍
> Update acceptance test readme & scripts

- src/Umbraco.Web.UI.Client/src/common/directives/components/umblightbox.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/umb-lightbox.html
- src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js
Related to issue: [Fix A & AA accessibility issues throughout Backoffice](https://github.com/umbraco/Umbraco-CMS/issues/12546)
- [umbraco/Umbraco-CMS.Accessibility.Issues#61](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/61) (Package Details - Image Modal - Missing Modal Trap)
- [umbraco/Umbraco-CMS.Accessibility.Issues#63](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/63) (Packages - Modal - Closing returns focus to the top of the page)
**What did you do and why ?**
- Added a focus trap when the modal is open so the user is only able to navigate to the elements of the modal.
- Updated code to return focus for screen readers to the image the user clicked on to open the modal. This is to fix …
> Accessibility Fixes - Packages Modal

- src/Umbraco.Core/Constants-HealthChecks.cs
- src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
- src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
- src/Umbraco.Core/EmbeddedResources/Lang/de.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
- src/Umbraco.Core/EmbeddedResources/Lang/it.xml
- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
- src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
- src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
- src/Umbraco.Core/HealthChecks/Checks/Security/XssProtectionCheck.cs
Reverts https://github.com/umbraco/Umbraco-CMS/pull/13046 as it contained a breaking change, the pipelines should finally not error out 👍
> Revert "Removing X-XSS-Protection healthcheck"

- src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
I noticed that the close button icon was a dark color which for most of the notification types were shown on a dark'ish background. The click area for the button was also limited to the width of the icon.
This PR therefore changes the icon color to white (similar to the text color), and makes the icon fully opaque. Since the icon was only 40% opaque in it's default state, the hover effect didn't add any visual effect. Now the icon is 75% opaque on hover, making the effect more visual. IMO the text shadow didn't do anything good, so I've also removed that. While the close button previously had a width of ~12 pixels, it now has a width of 30px, making it easier to hit. 
The following three files make up a dummy dashboard that may be used for testing. The dashboard adds a sticky notification …
> Fixed accessibility issues with notification close buttons

- src/Umbraco.Web.UI.Client/src/views/content/apps/listview/listview.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13119
Make sure to build the client before testing 😄 
1. Verify that content in the recycle bin can be picked both in card and in list view.
2. Verify that members can be picked both in card and in list view.
3. Verify that no errors appear in the JS console.
> Fix broken selectable state for list view items

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13067
- Passed the node property to `umb-property` & `umb-property-editor`
- Follow steps in issue
> V10: 13067 Edit from invariant text missing

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout-flexbox.css
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13174
> Block Grid: Remove space when editor is empty

- src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoImageBlock.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13176
> Block Grid: Make Example Block Image work with drag'n drop on Firefox

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/umb-block-grid-area-allowance-editor.less
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13175
> Block Grid: More space for specific block min/max inputs in area config

- build/azure-pipelines.yml
- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/packages.spec.ts
> V11: v10 to v11

- src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoImageBlock.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
fixes https://github.com/umbraco/Umbraco-CMS/issues/13173
> Fixes areas UI overlapping other Blocks

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13181
Also renamed the label to something more specific.
> 10.3.0-RC: Change grid area input to number + change generic label

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/relationTypes.spec.ts
- Fixed up relation type test to assert on success notification like other tests instead of url
> Added proper save assert instead of checking on the route

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataTypes/dataTypes.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/ModelsBuilder/modelsbuilder.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/packages.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/macro.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/relationTypes.spec.ts
Cherry picks these 3 PR's from v11: 
https://github.com/umbraco/Umbraco-CMS/pull/13204
https://github.com/umbraco/Umbraco-CMS/pull/13209
https://github.com/umbraco/Umbraco-CMS/pull/13228
> V10: cherry pick acceptance test stabilazation from v11

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
See the video, with the help of @deanleigh we made the Logo button behaviour consistent with the other buttons in the header. 
https://user-images.githubusercontent.com/304656/197236932-2d580aff-f0c1-4120-8372-833658c5af20.mp4
> Changed Logo button behavior to be more consistent with the rest of the header

- .github/README.md
Discord server added to the Join our community section
- [n/a ] I have added steps to test this contribution in the description below
I added the discord server invite to the readme because it's missing. There's twitter and Our but it's a good idea to highlight that here too
> Adding discord server info

- tests/Umbraco.Tests.AcceptanceTest/README.md
I have added some links to support folks in getting the playwright tests running. This was based on our own experiences at the hackathon 🎃👩‍💻
> update to link to youtube tutorials

- .github/CONTRIBUTING.md
At the cancon hackathon there were folks using v10, updating docs to recommend v11/contrib now 🎃💻
> updating to reference v11/contrib, not 10

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Translation/translation.spec.ts
This requires [Added helpers for user and translation #19](https://github.com/umbraco/Umbraco.Playwright.Testhelpers/pull/19)
Implementing what I learned from the __Umbraco x Candid Contributions Hacktoberfest Hackathon 2022__ and also sending in my first contribution to Umbraco CMS. 🎃🎃🎃
I added tests and helpers for translation.
@nul800sebastiaan Kindly take a look and thank you for all your help during the event. 🙂
> Add translation acceptance test

- tests/Umbraco.Tests.AcceptanceTest/README.md
I have updated the instructions on running playwright tests to include details on how to run single tests to help authors write new tests
I also included a link to the playwright documentation so new users know where to find more into.
> Additional info for running individual tests

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
Steps to test:
check the tests still work 
I've spent some time refactoring the file, changing out hardcoded strings for constants and using the constant helper too. There's more to do, specifically, I'd like to add some of the strings into the Playwright-Testhelpers project
> Const adding for content tests

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaFiles.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/memberGroups.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/members.spec.ts
As a learning exercise, I looked to replace hard coded areas with constants in 2 sections of playwright tests
> Added constants for getTreeItem in 2 stes of tests

- src/Umbraco.Core/EmbeddedResources/Lang/de.xml
Translating some keys to german
> Added translations for german

- src/Umbraco.Cms.ManagementApi/Controllers/Telemetry/AllTelemetryController.cs
- src/Umbraco.Cms.ManagementApi/OpenApi.json
Same as #13291 see that for more information.
Was having some issues with merging, so just did it again in a new branch 😄
> New Backoffice: Return AnalyticsLevelViewModel from Telemetry/

- src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
Adding swedish backoffice translations.
> Adding swedish backoffice translations

- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
> Updated Smidge

- src/Umbraco.Cms.ManagementApi/Controllers/Search/IndexListExamineController.cs
- src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
- src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Updates nuget packages from aspnetcore to 7.0.0 final
> Updated to aspnetcore 7.0.0

- .devcontainer/devcontainer.json
Adds SQLite extension & ensures SQLite is installed to allow you to view, query and edit the SQLite database used for Umbraco
> Codespaces: Adds SQLite extension & ensures SQLite thats needed for it

- src/Umbraco.Core/EmbeddedResources/BlockGrid/items.cshtml
- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Core/Models/Blocks/BlockGridItem.cs
- src/Umbraco.Infrastructure/Models/Blocks/BlockGridLayoutItem.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockGridPropertyValueConverter.cs
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/razorhtml.temp.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umb-block-grid-entries.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umb-block-grid-entry.html
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridentries.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbblockgridentry.component.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout-flexbox.css
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout.css
- src/Umbraco.Web.UI/Views/Partials/blockgrid/items.cshtml
Removing the forced placement feature
> Block Grid Editor: Removal of the forced placement feature

- .devcontainer/devcontainer.json
Makes port 5000 discoverable for SMTP4Dev in the ports list
> Codespaces: List port 5000 for Smtp4Dev

- .github/codespaces-readme.md
Updated readme specific to CodeSpaces
> Codespaces: Updated readme

- src/Umbraco.Core/CompatibilitySuppressions.xml
- src/Umbraco.Infrastructure/CompatibilitySuppressions.xml
#13400 introduced breaking changes, however this is between RCs and therefore allowed, so this adds suppressions to we can build again
> V11: Add  compatibility suppressions

- src/Umbraco.Infrastructure/Persistence/UmbracoDatabase.cs
I've tested this change on a local build with additional logging, when running an upgrade of CMS any database calls using default NPoco functions should run with a command timeout configured in ConnectionString setting Connection Timeout.
This fixes: https://github.com/umbraco/Umbraco-CMS/issues/13354
The proposed changes add a function to set the CommandTimeout property on initialization of the class, the timeout value is taken from the configured connectionstring property "Connection Timeout" or "Connect Timeout".
This code is called in Init() function. 
I've added some comments on the new function, because setting the command timeout with a value from connection timeout is not a very pretty way of doing this, eventhough existing code already does the same (see lines 313 till 317).
*A …
> Fix for Issue: 13354

- src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoImageBlock.html
Block Grid Editor media trash state for demo block.
> Block Grid Editor media trash state for demo block

- src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
This PR makes it possible to supply explicit Swagger operation IDs for API methods where the auto generated ones just become too weird.
Supply a `Name` in the HTTP verb definition of any endpoint - i.e.:
...and verify that this `Name` is used as the operation ID in the Swagger JSON output:
> Support explicit operation IDs

- .devcontainer/devcontainer.json
Uses the SQLite DevContainer Feature I wrote as GitHub won't write one an official one that they will support.
http://github.com/warrenbuckley/SQLite-Codespace-Feature
> Codespaces: Adds SQLite to DevContainer via Features

- src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
Updated the Welsh language backoffice translation file to include new keys found in the en and en_us language files.
> Updated Welsh translations file

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/50
Adding missing caption text and made it visually hidden since the visual context should be clear enough.
> Accessibility: Fix - Missing table description: A data table is present with no description associated to it

- src/Umbraco.Core/Notifications/ContentMovedNotification.cs
- src/Umbraco.Core/Notifications/ContentMovingNotification.cs
- src/Umbraco.Core/Notifications/ContentPublishedNotification.cs
- src/Umbraco.Core/Notifications/ContentPublishingNotification.cs
- src/Umbraco.Core/Notifications/ContentSortedNotification.cs
- src/Umbraco.Core/Notifications/ContentSortingNotification.cs
- src/Umbraco.Core/Notifications/MovedNotification.cs
- src/Umbraco.Core/Notifications/MovingNotification.cs
(Nothing to test really :D)
I asked the question on Discord if it was OK to add documentation to some of the core code on things that are undocumented. It might just add a bit of descriptive information showing this on the API Docs. The answer was that this is possible, but that I need to start small in order to see if it is something I could continue with. Here is a PR which starts small, might not even be merged back because it is 6 files. But would like some feedback in order for me to continue or discontinue this side-project.
> Notification documentation

- src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
| Package  | From | To |
| ------------- | ------------- | ------------- |
| NPoco  | 5.5.0  | 5.7.0  |
| System.Security.Cryptography.Xml  | 6.0.1 | 7.0.0 |
| IPNetwork2 | 2.6.472 | 2.6.508 |
| Newtonsoft.Json | 13.0.1 | 13.0.2 |
| MessagePack | 2.4.35 | 2.4.59 |
| Microsoft.NET.Test.Sdk | 17.3.2 | 17.4.0 |
| NUnit3TestAdapter | 4.3.0 | 4.3.1 |
> Nuget updates

- src/Umbraco.Cms.Imaging.ImageSharp/Media/ImageSharpImageUrlGenerator.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Media/ImageSharpImageUrlGeneratorTests.cs
If there's an existing issue for this PR then this fixes #13378
> Solves #13378

- umbraco.sln
Check to see if the CI tests pass
A larger task to take on in the future to remove a dependency on full framework, but for now update to the latest framework version.
> Update to latest framework version in web site projects

- src/Umbraco.Core/Models/RelationItem.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
- src/Umbraco.Web.UI.Client/src/common/directives/components/references/umbtrackedreferencestable.component.js
- src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references-table.html
- src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references.html
- src/Umbraco.Web.UI.Client/src/views/media/delete.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13191
This PR add published to reference list, so it nicer indicate content nodes references, which are published or unpublished.
In delete dialog which use compact mode, I have chosen to hide status column, while the row is still dimmed.
> Show published in tracked references

- src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs
- Added closedSharedConnection() call to ensure we close the connection
> Close shared connection

- src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13539
When rollback isn't an allowed action for the node, the rollback button shouldn't be rendered.
https://user-images.githubusercontent.com/2919859/207027343-40d86558-4388-499e-8efb-11667ffcaf62.mp4
Example using `SendingContentNotification`:
```
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
private readonly IBackOfficeSecurityAccessor _backOfficeSecurity;
public EditorSendingContentNotificationHandler(
IBackOfficeSecurityAccessor backOfficeSecurity)
{
_backOfficeSecurity = backOfficeSecurity;
}
public void Handle(SendingContentNotification notification)
{
if (notification.Content.ContentTypeAlias.Equals("blogpost"))
{
var …
```
> Only show rollback button if allowed action

- src/Umbraco.Web.UI.Client/src/views/packages/overview.controller.js
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13514
Renamed the title of section Packages to "Packages" instead of "Marketplace".
To test the change: navigate to Umbraco backoffice, click on section Packages, the title on the left handside should now be "Packages" and not "Marketplace"
> Rename title marketplace to packages

- src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
- src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs
- src/Umbraco.Infrastructure/Examine/ContentIndexPopulator.cs
- src/Umbraco.Infrastructure/Examine/ValueSetValidator.cs
Just some minor improvements to the indexing performance. 
Will probably not be noticable on small sites.
Make sure that indexes get populated by checking the dashboard or via some code
> Minor improvements to indexing performance

- src/Umbraco.Core/EmbeddedResources/Lang/ua.xml
I have added Ukrainian language support.
I have made Ukrainian translation according to Language to Language Files & Localization article because Umbraco doesn't have Ukrainian language localization.
There is project for Ukrainian government institution where Umbraco solution is used. This is why I need to have Ukrainian language support.
Ukrainian language should be available in user profile dropdown. User could see Ukrainian interface after language selection.
> added Ukrainian language

- src/Umbraco.Core/EmbeddedResources/Lang/es.xml
Translate dictionary area to español
> Translate dictionary area to español

- src/Umbraco.Core/EmbeddedResources/Lang/de.xml
Updated a bunch of the missing translations for the german language.
Only bigger parts still missing are the installation process and blocklist.
> Updating german translation

- src/Umbraco.Web.UI.Client/src/less/rte.less
based on this upstream issue: https://github.com/tinymce/tinymce/issues/6431
Fixes #13614 
This workaround potentially fixes the line-height issue with TinyMCE, which was suggested in https://github.com/tinymce/tinymce/issues/6431#issuecomment-759984231
> V11: add workaround for line-height issues with TinyMCE

- .github/New BackOffice - README.md
- umbraco.sln
- Fixes the .sln file - adds the Client project correctly;
- Adds git submodule commands to README.
> **Note**
> Visual Studio might need to be reopened if you switch from another v13 branch.
> Fix sln file for the new backoffice

- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
Added and changed some translations about 2FA
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13793
> 2FA translations

- src/Umbraco.Core/PropertyEditors/IBlockValuePropertyIndexValueFactory.cs
- src/Umbraco.Core/PropertyEditors/INestedContentPropertyIndexValueFactory.cs
- src/Umbraco.Core/PropertyEditors/ITagPropertyIndexValueFactory.cs
- src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
- src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs
- src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
- src/Umbraco.Infrastructure/PropertyEditors/ColorPickerPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyIndexValueFactory.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs
- src/Umbraco.Infrastructure/PropertyEditors/TagsPropertyEditor.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/NestedContentTests.cs
- Added property index value factories for:
- Block Grid
- Block List
- Nested Content
- Tags
- Added no-op property index value factories for:
- Media Picker
- Image Cropper
- Use complex property editors and inspect the InternalIndex, Those should not be json anymore
> Added missing property index value factories

- src/JsonSchema/JsonSchema.csproj
Primarily this is to include three new configuration keys available in the latest Deploy release.
> Bumped dependencies on Forms and Deploy to latest releases in JSON schema project.

- src/Umbraco.Cms.Api.Common/Json/NamedSystemTextJsonInputFormatter.cs
- src/Umbraco.Cms.Api.Common/Json/NamedSystemTextJsonOutputFormatter.cs
- src/Umbraco.Cms.Api.Management/Controllers/Install/SetupInstallController.cs
- src/Umbraco.Cms.Api.Management/Controllers/ModelsBuilder/BuildModelsBuilderController.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/OpenApi/ConfigureUmbracoSwaggerGenOptions.cs
- src/Umbraco.Cms.Api.Management/OpenApi/ReponseHeaderOperationFilter.cs
Added operation filter that adds location header, if response is 201.
Includes this PR: https://github.com/umbraco/Umbraco-CMS/pull/13828, to avoid too many issues with OpenApi.json
> add response location header for 201

- tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
- Removes bad proj ref from csproj
> V11: remove bad proj ref

- src/Umbraco.Core/Services/AuditService.cs
- Added new ctor needed for: https://github.com/umbraco/Umbraco-CMS/pull/13842
- Obsoleted old one
> Add new AuditService constructor and obsolete old.

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorSettings.spec.ts
Added test for the settings section in the block grid editor for content
> Added test for the settings section

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/BlockGridEditor/Content/blockGridEditorContent.spec.ts
Added test for testing the content editor with a block grid editor
> Added test for testing the content editor with a block grid editor

- src/Umbraco.Core/Services/TemporaryMediaService.cs
This fixes https://github.com/umbraco/Umbraco-CMS/issues/13680
Added a `CalculateMediaStartNodeIds` method call when the `startNode` passed in as parameter is null. When this is not null and returns an array of `startNodes` the first one is being used. 
How I've tested this fix:
First I've confirmed the issue as stated in https://github.com/umbraco/Umbraco-CMS/issues/13680. I can confirm that when dragging and dropping an image from the file explorer in an Umbraco.MediaPicker3 field type, it will not be saved in  one of the users Media start nodes.
This PR fixes that issue. See the gif below for the results:
The question remains if this is desired behavior. With this implementation the user has no real control over where the file is going to go. However it will now be in one of the Media …
> Issue-13680: Uploading files to Media Picker doesn't use "User Start Node" - Fix

- src/Umbraco.Core/Configuration/Models/ContentSettings.cs
- src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs
Fixes #12200 by adding an list of allowed media hosts in content settings.
> Add allowlist of media hosts.

- src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
- src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
**Feel free to take this as feedback and make any project reference changes in another PR if that makes more sense 😄**
The changes in this PR remove project references within the Umbraco projects. All project references that have been removed are still available through the remaining project references. This means that all references removed were practically duplicate references. _(Therefore also non-breaking)_
To figure out the references in the project I used [DependenSee](https://github.com/madushans/DependenSee) (A tool for drawing out the project references). To use this to run the following command in the root of the repository (After installing DependenSee - See the GitHub page):
```bash
dependensee ./src graph.html
``` …
> Suggestion to simplify some of the project references

- src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
This migrates #13896 to V8. See that PR for more information
> Migrate search fix to V8

- src/Umbraco.Core/Routing/ContentFinderByUrl.cs
- src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
If there's an existing issue for this PR then this fixes #13852 
Fixing the installation process by adding ids to the languagdtos starting by id=1
You can test it by using the description of the bug provided in  #13852
> Fixing language install during umbraco installation

- src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
This resolves issue #13931
Changed the TimeSpan cast from int to long, this resolves the out of range exception
> Changed to cast double to long

- src/Umbraco.Web.UI.Client/src/views/components/media/umbmediapreview/umb-media-preview.less
If there's an existing issue for this PR then this fixes #13873
When uploading white SVG files the preview isn't really useful, because it doesn't have a checkered background.
Add checkered background to file upload (including SVGs added to the media library)
> Add checkered background to file upload

- src/Umbraco.Core/Configuration/Grid/GridConfig.cs
- src/Umbraco.Core/PropertyEditors/GridEditor.cs
- src/Umbraco.Core/PropertyEditors/MediaPickerConfiguration.cs
- src/Umbraco.Core/PropertyEditors/MediaPickerConfigurationEditor.cs
- src/Umbraco.Core/PropertyEditors/NestedContentConfiguration.cs
- src/Umbraco.Core/PropertyEditors/NestedContentConfigurationEditor.cs
- src/Umbraco.Core/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs
- src/Umbraco.Infrastructure/Deploy/GridCellValueConnectorExtensions.cs
- src/Umbraco.Infrastructure/Models/GridValue.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridConfiguration.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridConfigurationEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/GridPropertyIndexValueFactory.cs
- src/Umbraco.Infrastructure/PropertyEditors/MediaPickerPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyHandler.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/GridValueConverter.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentSingleValueConverter.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentValueConverterBase.cs
- src/Umbraco.Web.BackOffice/PropertyEditors/NestedContentController.cs
- src/Umbraco.Web.Common/Extensions/GridTemplateExtensions.cs
We have obsoleted data types, but we never obsoleted the code for them
- Obsolete legacy media picker
- Obsolete grid
- Obsolete nested content
> V11: obsolete legacy data types

- src/Umbraco.Core/EmbeddedResources/Lang/ro.xml
> Add Romanian language

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
This PR is a fix for the issue using a media picker to select a folder on a member property and try to open the selected folder in the Infinite Editor, shows the listview for the members and not the listview for the media as expected.
[Reported Issue](https://github.com/umbraco/Umbraco-CMS/issues/13770)
Fixes #13770
> [fix] Infinite Editor from member property with a media picker

- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/views/documentTypes/views/permissions/permissions.html
Small wording change in the Umbraco UI for the Element Type. If only for my own benefit, as I find myself tripping over explaining an Element Type, when it can be many things and not just for Nested Content.
> small wording change for Element Type description

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.area.overlay.html
Really small PR to change the use of inline style to class since we have `w-100` in the code base we might as well use it over inline styles :-)
> Block Grid Content - Change style to class

- src/Umbraco.Core/ContentApi/ApiMediaBuilder.cs
- src/Umbraco.Core/Models/ContentApi/ApiMedia.cs
- src/Umbraco.Core/Models/ContentApi/IApiMedia.cs
- src/Umbraco.Infrastructure/Models/ContentApi/ApiMediaWithCrops.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/MediaBuilderTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/MediaPickerValueConverterTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/MediaPickerWithCropsValueConverterTests.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/MultiNodeTreePickerValueConverterTests.cs
> Include umbraco properties (width, height, ...) in the Media Properties collection

- src/Umbraco.Cms.Api.Content/Controllers/ByIdContentApiController.cs
- src/Umbraco.Cms.Api.Content/Controllers/ByRouteContentApiController.cs
- src/Umbraco.Cms.Api.Content/Controllers/ContentApiControllerBase.cs
- src/Umbraco.Core/Configuration/Models/ContentApiSettings.cs
- src/Umbraco.Core/ContentApi/ApiPublishedContentCache.cs
- src/Umbraco.Core/ContentApi/IApiPublishedContentCache.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/ContentApi/PublishedContentCacheTests.cs
> Add content type deny list

- src/Umbraco.Core/Services/IsoCodeValidator.cs
Fixes the iso code validator to be case insensitive, fixes #14049
> New backoffice: Fix iso code validator

- src/Umbraco.Cms.Api.Management/Controllers/Member/Item/ItemMemberItemController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Member/Item/MemberItemControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Item/ItemStaticFileItemController.cs
- src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Item/StaticFileItemControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroups/Item/ItemUserGroupItemController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroups/Item/UserGroupItemControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/Users/Item/ItemUserItemController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Users/Item/UserItemControllerBase.cs
- src/Umbraco.Cms.Api.Management/Mapping/Items/ItemTypeMapDefinition.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/ViewModels/Member/Item/MemberItemResponseModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/UserGroups/Item/UserGroupItemResponseModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/Users/Item/UserItemResponseModel.cs
- src/Umbraco.Core/CompatibilitySuppressions.xml
- src/Umbraco.Core/Services/IMemberService.cs
- src/Umbraco.Core/Services/MemberService.cs
- Implement item endpoints for Member, User & UserGroups
- Put routing on Static file controller, as it was generating weird routing in swagger 😁 
- Create different entities for Member & Member Groups
In swagger:
- Try getting the member through the item endpoint
- Try getting the User through the item endpoint
- Try getting the User group through the item endpoint
> New backoffice: User and member item endpoints

- src/Umbraco.Cms.Api.Management/Controllers/User/InviteUsersController.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
Changes the invite endpoint to return a 201 created instead of 200 ok
> New backoffice: Return created from invite

- src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
> Save and preview translation.

- src/Umbraco.Core/Models/ContentEditing/MemberBasic.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
- src/Umbraco.Web.BackOffice/Mapping/MemberMapDefinition.cs
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/includeproperties.prevalues.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
- src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/sortby.prevalues.controller.js
This pr fixes: #13943 
I have added all the systemfield that member contains.
- Failed password attempts
- Approved
- locakedout
- lastlockoutdate
- lastlogindate
- last password change date
> Add member system fields to ListView

- src/Umbraco.Cms.ManagementApi/DependencyInjection/MappingBuilderExtensions.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.MappingProfiles.cs
- src/Umbraco.Infrastructure/Mapping/RelationModelMapDefinition.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/14150
- Moved the `RelationModelMapDefinition`, from `New.Infrastructure` to `Infrastructure` so its part of the shipped DLL's
- Install umbraco via the CLI using `dotnet new install Umbraco.Templates`
- Create a new Umbraco project using `dotnet new umbraco -n "TestProject"`
- Create a content type with a content picker and allow as root
- Create a content node named `Child`
- Create a content node named `Parent` and reference the Child node in the content picker (note down the id of the parent node)
- stop your solution
- implement the snippet below
- Set a breakpoint in the `Handle` method
- Assert it throws an exception
- Now pack this branch using `dotnet pack -o Release`
- Reference the nuget packages in your template project
- …
> V11: Move relation mapper to infrastructure

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
Update the Umbraco UI Library to latest version 1.2.1
> v10: update @umbraco-ui/uui to 1.2.1

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tabs/tabs.spec.ts
Fixes the "Click dashboard tabs" acceptance
> Fix acceptance test

- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/ByKeyUserGroupController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/CreateUserGroupController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/GetAllUserGroupController.cs
- src/Umbraco.Cms.Api.Management/Factories/IUserGroupPresentationFactory.cs
- src/Umbraco.Cms.Api.Management/Factories/UserGroupPresentationFactory.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/CreateUserGroupRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/UserGroupResponseModel.cs
Renames `UserGroupPresentationModel` to `UserGroupResponseModel`
Renames `SaveUserGroupRequestModel` to `CreateUserGroupRequestModel`
> New Backoffice: Rename UserGroup Controllers

- src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
> Sv translation

- src/Umbraco.Core/Actions/ActionToPublish.cs
- src/Umbraco.Core/Events/UserNotificationsHandler.cs
> V11: Obsolete action to publish

- src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
- src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
Added OpenIddict dependencies as we wanna use those in a minor version
> Added OpenIddict dependencies for future usage

- src/Umbraco.Infrastructure/Migrations/ExecutedMigrationPlan.cs
- src/Umbraco.Infrastructure/Migrations/IMigrationContext.cs
- src/Umbraco.Infrastructure/Migrations/MigrationContext.cs
- src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
Reintroduced some of the post-migration code to make starterkits work
> Re-added the postmigration from the migration context

- src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
- src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
Downgrades OpenIdDict, fixing a breaking change in the dependency fixes #14265
> V12: Downgrade OpenIdDict

- src/JsonSchema/JsonSchema.csproj
Updated to ensure the latest configuration keys are available in the generated schema.
> Update JSON schema package references for Forms and Deploy.

- src/Umbraco.Cms.Api.Management/Controllers/DataType/Items/ByEditorUiAliasController.cs
- src/Umbraco.Core/Services/DataTypeService.cs
- src/Umbraco.Core/Services/IDataTypeService.cs
- src/Umbraco.Infrastructure/Persistence/Mappers/DataTypeMapper.cs
Adds an endpoint to get all datatypes with a given EditorUiAlias.
> Add get ByEditorUiAlias datatype item endpoint

- src/Umbraco.Infrastructure/Models/Mapping/EntityMapDefinition.cs
Fixes issue: #14371 
The mapper was registered wrong which is why there was an issue. Now it's set correctly
> Added a mapper for the IPropertyType

- src/JsonSchema/JsonSchema.csproj
This updates the references on Forms and Deploy to the latest for generation of the Umbraco JSON schema for 10.
> Updated Forms and Deploy references in JSON schema project for Umbraco 10.

- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
Updated a few translations in Danish.
- No title case
- Two words in a single word in Danish.
> Update labels in Danish translation

- templates/UmbracoPackage/App_Plugins/UmbracoPackage/package.manifest
- templates/UmbracoPackage/App_Plugins/UmbracoPackage/umbraco-package.json
- templates/UmbracoPackageRcl/wwwroot/package.manifest
- templates/UmbracoPackageRcl/wwwroot/umbraco-package.json
Update the Umbraco.Templates for "UmbracoPackage" and "UmbracoPackageRCL" to support the new umbraco-package.json format.
> v14: update package templates with new umbraco-package.json format

- .github/workflows/pr-first-response.yml
- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
Update Backoffice JS dependencies to the latest version where possible.
> v10: Backoffice JS updates

- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/Stylesheet.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/StylesheetFolder.spec.ts
Added acceptance tests for testing the API for the Stylesheet section.
> Added acceptance tests for testing the API for the Stylesheet section.

- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/TemporaryFile/TemporaryFile.spec.ts
Added acceptance tests for testing the API for the TemporaryFiles section
> Added acceptance tests for testing the API for the TemporaryFiles section

- src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
Added missing scope to CreateCreatedPackage. Before adding the scope we were not able to create a package.
- Test that you are able to create a package through swagger or postman
> Added missing scope

- src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetPermissionsCurrentUserController.cs
- src/Umbraco.Core/Services/IUserService.cs
- src/Umbraco.Core/Services/UserService.cs
- Rework GetPermissionsAsync to attempt pattern
- call the endpoint and test it works 🙆‍♂️
> V14: refactor GetPermissions to use attempt pattern

- src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
- src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/ScriptsTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/StylesheetsTreeController.cs
- src/Umbraco.Web.BackOffice/Trees/UrlHelperExtensions.cs
- src/Umbraco.Web.UI.Client/src/common/mocks/umbraco.servervariables.js
- src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
- src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
- src/Umbraco.Web.UI.Client/src/routes.js
- src/Umbraco.Web.UI.Client/test/unit/common/services/tree-service.spec.js
This reverts PR: #14268. This is a breaking change since it moves the location of some endpoints. This should be implemented for v13 instead.
> Reverts breaking change that moves location of some endpoints

- src/Umbraco.Core/Enum.cs
Drops many unnecessary allocations.
> Improve Enum performance

- src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerSyntaxProvider.cs
- src/Umbraco.Core/Configuration/Models/ContentSettings.cs
- src/Umbraco.Core/Configuration/Models/HealthChecksNotificationMethodSettings.cs
- src/Umbraco.Core/Configuration/Models/HostingSettings.cs
- src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
- src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs
- src/Umbraco.Core/Configuration/Models/RuntimeMinificationSettings.cs
- src/Umbraco.Core/Configuration/Models/SmtpSettings.cs
- src/Umbraco.Core/Configuration/Models/WebRoutingSettings.cs
Also drops one string allocation.
> Use built-in Enum parse methods

- src/Umbraco.Web/PropertyEditors/RichTextEditorPastedImages.cs
- src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
Port the code from #14515 to V8 where embedded base64 images in the Rich Text Editor will be found an stored in the Media library.
> V8: Find & persist base64 images

- src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/ByKeyDataTypeFolderController.cs
- src/Umbraco.Cms.Api.Management/Controllers/FolderManagementControllerBase.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/ViewModels/Folder/FolderResponseModel.cs
- Rename `ReponseModel` to `ResponseModel`
Not much to test here, just make sure the tests pass 🤣
> V14: Rename folder response model

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Translate the shared label to Dutch.
> Translate 'shared' to Dutch

- src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
Adding multiple conditions, considering id, key & name as filter param
If there's an existing issue for this PR then this fixes (partly) https://github.com/umbraco/Umbraco-CMS/issues/14468
This PR allows searching content from listview by id, key & name
Issue: https://github.com/umbraco/Umbraco-CMS/issues/14468
> considering id, key & name as filter params for content listview

- src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreeitem.directive.js
- src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
Fixes https://github.com/umbraco/Umbraco-CMS/issues/14635
Avoid action menu to close when un-expanding tree items
> Avoid action menu to close when collapsing tree items

- src/Umbraco.Core/Services/ContentService.cs
Fixes #14636
Pass existing notification state to `ContentUnpublisingNotification`
> Pass notification state to content unpublising notification

- src/Umbraco.Core/EmbeddedResources/Lang/da.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
Fixes the translation keys from #12776 as pointed out by @bjarnef 
/CC @georgebid
> fix: Translations keys from #12776

- src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
Subset of #14563
This changes the DbContext registration to only use PooledDbContexts which are much more performant.
See: https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant
To test:
At the moment it's only the delivery API that uses EFCore with OpenIddict so as long as this works we should be good.
> refactor: Only use pooled DbContexts

- src/Umbraco.Cms.Persistence.EFCore/UmbracoDbContext.cs
This just improves the remarks on the `UmbracoDbContext` to give a more complete description
> docs: Improve DbContext XML docs

- src/JsonSchema/JsonSchema.csproj
This updates the references of Forms to the latest for generation of the Umbraco JSON schema for 10.
> Updated JSON schema reference for Umbraco Forms.

- src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
- src/Umbraco.Cms.Persistence.EFCore/UmbracoDbContext.cs
This PR moves the connection registration to the `UmbracoDbContext` itself. This allows for a DbContext to be available even after a connection string change as done when installing Umbraco for the first time or when you have to run the DbContext in integration tests.
More info can be found here but it includes a bunch of other things as well: https://github.com/umbraco/Umbraco-CMS/pull/14564#issuecomment-1666487375
To test this PR I created the following controller:
```csharp
using Microsoft.EntityFrameworkCore;
using Umbraco.Cms.Persistence.EFCore;
using Umbraco.Cms.Web.Common.Controllers;
public class TestController : UmbracoApiController
{
private readonly …
```
> feat: Let the DbContext handle the connection to the database

- src/Umbraco.Core/Persistence/Factories/UserGroupFactory.cs
- added commit [#1198c76d67e3aa9ef5cebeb54d66708186125165](https://github.com/umbraco/Umbraco-CMS/commit/1198c76d67e3aa9ef5cebeb54d66708186125165) manually, as files have moved
> Add PR #14721 to v8

- tests/Umbraco.TestData/Umbraco.TestData.csproj
- tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
This PR simplifies the project references for the test projects so that they don't reference individual projects but instead reference the main `Umbraco.Cms` project that should contain all active references.
This will make easy in form of adding references to the test projects as you wouldn't have to. Just make sure it's referenced in the actual Umbraco install and it's good to go.
Enforcing this rule of only referencing `Umbraco.Cms` also makes sure that a project doesn't lose a reference to the main `Umbraco.Cms` package as you wouldn't be able to test it (But this is highly unlikely to happen any ways. Just thought I put it in here 😄 )
> Suggestion to simplify test project references

- src/Umbraco.Core/ApplicationContext.cs
- src/Umbraco.Core/Security/FileStreamSecurityValidator.cs
- src/Umbraco.Core/Security/FileStreamSecurityValidatorFactory.cs
- src/Umbraco.Core/Security/IFileStreamSecurityAnalyzer.cs
- src/Umbraco.Core/Security/IFileStreamSecurityValidator.cs
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Web/Editors/MediaController.cs
- src/Umbraco.Web/Editors/UsersController.cs
- src/Umbraco.Web/PropertyEditors/FileUploadPropertyValueEditor.cs
- src/Umbraco.Web/PropertyEditors/ImageCropperPropertyValueEditor.cs
- src/Umbraco.Web/PropertyEditors/RichTextEditorPastedImages.cs
Backports #14657
Can be tested with: 
```C#
using System;
using System.IO;
using Umbraco.Core;
using Umbraco.Core.Security;
namespace Umbraco.Web.UI
{
public class MyEventHandler : ApplicationEventHandler
{
protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
{
base.ApplicationStarting(umbracoApplication, applicationContext);
ApplicationContext.Current.FileStreamSecurityValidatorFactory.AddAnalyzer(new SvgXssSecurityAnalyzer());
}
}
public class SvgXssSecurityAnalyzer : IFileStreamSecurityAnalyzer
{
public bool ShouldHandle(Stream fileStream)
{
var startBuffer = new byte[256];
var endBuffer = new byte[256];
fileStream.Read(startBuffer, 0, 256);
if (endBuffer.Length > fileStream.Length)
fileStream.Seek(0, …
```
> V7: Backport #14657

- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
> append 3 more things to the import maps of C#

- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
- src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
Update import map with latest.
> V14: Update import-map

- src/JsonSchema/JsonSchema.csproj
Updated dependencies to Forms and Deploy for JSON schema generation to match the latest releases (one of which contains a setting that's not currently included in the schema).
> Updated dependencies to Forms and Deploy for JSON schema generation.

- src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeIdentityOptions.cs
Cherry pick for https://github.com/umbraco/Umbraco-CMS/pull/14810
> Cherry pick #14810

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Translate dictionary_noItemsFound
> Translate 'noItemsFound' to Dutch

- .github/CONTRIBUTING.md
Adding unwanted changes section to the contributing docs.
> Updating contributing docs to add unwanted changes section

- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Updated Dutch translation for "import"
> Updated Dutch translation for "import"

- src/Umbraco.Web.UI.Client/src/views/logViewer/search.html
An extra closing div tag was lurking around
There was an additional closing div tag within the table structure (line 265). No real test needed to recreate!
> Corrected mark-up

- src/Umbraco.Web.BackOffice/Security/BackOfficeSecurityStampValidator.cs
- src/Umbraco.Web.BackOffice/Security/BackOfficeSessionIdValidator.cs
- src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
- src/Umbraco.Web.Common/Security/MemberSecurityStampValidator.cs
- tests/Umbraco.Tests.Integration/TestServerTest/TestAuthHandler.cs
Refactored the obsolete ISystemClock with the TimeProvider. 
Check if you are timed out of your session after logging in, Both for a user and a member.
> Refactored from ISystemClock to TimeProvider

- src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
- templates/Umbraco.Templates.csproj
Existing issue: https://github.com/umbraco/Umbraco-CMS/issues/14752
It's basically already described in the issue. I've added the checks around line #833
Did ALOT of cleanup on the code itself, I also saw a IRelationService relationService that wasn't used in the file, but perhaps it is still there for a reason?
> Fix for fallback file upload

- src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- Updated the **cy** lang file to include new keys found in the **en_us** language files.
- Translations have been checked using:
- Cysgliad: https://www.cysgliad.com/ 
- BydTermCymru: https://www.gov.wales/bydtermcymru
- Removed outdated/unused keys.
- Added 2 missing MFA related keys to the **en_us** lang file
> Updated Welsh lang file

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/HelpPanel/helpLinks.spec.ts
- [/ ] I have added steps to test this contribution in the description below
This PR contains a new Playwright test to check that the our umbraco link in the help panel works as expected. 😄 
To test:
- Make sure to run `npm ci` & `npx playwright install`
- I would suggest adding test.only to the start of the test so you don't have to watch 20+ tests run.
- run` npm run ui` 
- check to see if the test passes
> our umbraco link works as expected - playwright test.

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Login/login.spec.ts
- [/ ] I have added steps to test this contribution in the description below
This PR contains a new Playwright test to check that the 'Show password' and Hide password button works as expected on the login page 😄 
To test:
- Make sure to run `npm ci` & `npx playwright install`
- I would suggest adding test.only to the start of the test so you don't have to watch 20+ tests run.
- run` npm run ui` 
- check to see if the test passes
> New login page playwright test - Ensure Show/hide password button works as expected.

- src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
New missing language sections added for the Turkish language. Also, some sections have been updated / corrected.
> Turkish language support changes

- build/nightly-build-trigger.yml
Added "pr: none" to nightly trigger to avoid github to trigger nightly builds on each PR
> Added "pr: none" to nightly trigger

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
I have added some keys into the fr.xml that I took from different PR's that I merged and which contained updates of labels in other languages.
Also added a few in en.xml that I found in en_us.xml along the way.
> Update fr translations

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
Update @umbraco-ui/uui to 1.5.0
> V12: Bump @umbraco-ui/uui from 1.4.0 to 1.5.0

- src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
Nested Content is removed in v14, not in v13 anymore. This makes sure developers won't get confused / in panic mode
> Update NestedContentPropertyEditor.cs - Update obsolete message

- src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProvider.cs
- src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProviderSetup.cs
- src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProvider.cs
- src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProviderSetup.cs
- src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
- src/Umbraco.Core/Constants-ProviderNames.cs
Moved Provider name constants from EFCore project to Core
> Move to core

- src/Umbraco.Core/Webhooks/IWebhookEvent.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/15096
> Remove setter from WebhookEvent

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
Fix for issue: https://github.com/umbraco/Umbraco-CMS/issues/8648
Batched bulk WhereIn query to avoid To many parameters error
see: https://github.com/umbraco/Umbraco-CMS/issues/8648#issuecomment-1768527552
> Batched bulk WhereIn query to avoid To many parameters error

- global.json
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
I already created a PR to add a `global.json` file for v12 (see https://github.com/umbraco/Umbraco-CMS/pull/14720) and because I got similar issues while working on v10, decided to create this PR. I've also cleaned up the UI project file, since that contained duplicate/redundant package references.
> Add global.json and cleanup UI project file

- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/Services/IWebhookService.cs
- src/Umbraco.Core/Services/WebhookService.cs
- src/Umbraco.Core/Webhooks/Events/ContentDeleteWebhookEvent.cs
- src/Umbraco.Core/Webhooks/Events/ContentPublishWebhookEvent.cs
- src/Umbraco.Core/Webhooks/Events/ContentUnpublishWebhookEvent.cs
- src/Umbraco.Core/Webhooks/Events/MediaDeleteWebhookEvent.cs
- src/Umbraco.Core/Webhooks/Events/MediaSaveWebhookEvent.cs
- src/Umbraco.Core/Webhooks/WebhookEventBase.cs
- src/Umbraco.Core/Webhooks/WebhookEventContentBase.cs
- src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
- src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.controller.js
- src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.html
- tests/Umbraco.Tests.Integration/Umbraco.Core/Services/WebhookLogServiceTests.cs
- tests/Umbraco.Tests.Integration/Umbraco.Core/Services/WebhookServiceTests.cs
This will be breaking between 13-rc1 and rc2.
> V13: Update IWebHookService to proper casing

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Translate available keys for webhooks to Dutch
> Translate webhooks keys to Dutch

- src/JsonSchema/JsonSchema.csproj
- src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Logging/Serilog/Enrichers/ThreadAbortExceptionEnricher.cs
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Updated patch and minor version of nuget dependencies
> Updated nuget packages for v10

- src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
fixes #15195
Uses the correct ObjectType when querying for media
> Fix caching of media

- global.json
- src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
- src/Umbraco.Cms.Persistence.EFCore.Sqlite/Umbraco.Cms.Persistence.EFCore.Sqlite.csproj
- src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
- src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Updated to .NET 8 final (And a BenchmarkDotNet patch for our test project)
> Updated to .NET 8 final

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Script/Script.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Script/ScriptFolder.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Scripts.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/scripts.spec.ts
Updated API test for the scripts to work with the updated testHelpers
Added Script UI acceptance test
Follow the README.md located in tests/Umbraco.Tests.AcceptanceTest for running the test
Test the tests in tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Scripts.spec.ts
> V14 QA added Scripts acceptance tests

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialViews.spec.ts
- Follow the README.md located in tests/Umbraco.Tests.AcceptanceTest for running the test
- Test the tests in tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialViews.spec.ts
> V14 added acceptance tests for the Partial Views

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddWebhookDatabaseLock.cs
Fixes migration by changing to the right constant.
> V13: Fix AddWebhookDatabaseLock migration

- src/Umbraco.Core/Models/IWebhook.cs
- src/Umbraco.Core/Models/Webhook.cs
- src/Umbraco.Core/Notifications/WebhookDeletedNotification .cs
- src/Umbraco.Core/Notifications/WebhookDeletingNotification.cs
- src/Umbraco.Core/Notifications/WebhookSavedNotification.cs
- src/Umbraco.Core/Notifications/WebhookSavingNotification.cs
- src/Umbraco.Core/Persistence/Repositories/IWebhookRepository.cs
- src/Umbraco.Core/Services/IWebhookFiringService.cs
- src/Umbraco.Core/Services/IWebhookLogFactory.cs
- src/Umbraco.Core/Services/IWebhookService.cs
- src/Umbraco.Core/Services/ServiceContext.cs
- src/Umbraco.Core/Services/WebhookLogFactory.cs
- src/Umbraco.Core/Services/WebhookService.cs
- src/Umbraco.Core/Webhooks/WebhookEventBase.cs
- src/Umbraco.Core/Webhooks/WebhookEventContentBase.cs
- src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
- src/Umbraco.Infrastructure/Persistence/Factories/WebhookFactory.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/WebhookRepository.cs
- src/Umbraco.Infrastructure/Services/Implement/WebhookFiringService.cs
- src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
- src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
- src/Umbraco.Web.BackOffice/Services/IWebhookPresentationFactory.cs
- src/Umbraco.Web.BackOffice/Services/WebhookPresentationFactory.cs
- Refactors `Webhook` to implement the `IEntity` interface and thus using the pattern
- Adds `IWebhook` interface to use instead, to align with how we user other entities such as `ILanguage`
- Adds `WebhookService` to ServiceContext
No steps per say, everything should work same as before 🙈
> V13: Implement webook as i entity

- src/Umbraco.Core/Services/OperationStatus/WebhookOperationStatus.cs
- src/Umbraco.Core/Services/WebhookService.cs
- src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
Added backend validation for checking if a webhook has any events
Try to create a webhook with no events, you should receive an error message
Try to update an existing webhook by removing the events and try to save. You should receive an error message
> V13 Bugfix. Added backend validation for checking if a webhook has any events

- src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
- [*] I have added steps to test this contribution in the description below
If there's an existing issue for this PR then this fixes [Redirect is broken with Hebrew chars when running Linux/azure webapp linux](https://github.com/umbraco/Umbraco-CMS/issues/14733)
Steps to check:
1. create a new page name it "test"
2. browse to the page -> page loads ok.
3. change the page name to "שלום"
4. browse to /שלום - page loads ok.
5. browse to /test - page will redirect to /שלום  **this step was faulty**
the fix was adding HttpUtility.UrlPathEncode in line 93 in ContentFinderByRedirectUrl.cs
> Redirect is broken with Hebrew chars on Linux

- build/azure-pipelines.yml
- src/Directory.Packages.props
- src/JsonSchema/JsonSchema.csproj
- src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
- src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
- src/Umbraco.Cms/Umbraco.Cms.csproj
- src/Umbraco.Core/Umbraco.Core.csproj
- src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
- src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
- src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
- templates/Umbraco.Templates.csproj
- templates/UmbracoPackage/UmbracoPackage.csproj
- templates/UmbracoProject/UmbracoProject.csproj
- tests/Directory.Packages.props
- tests/Umbraco.TestData/Umbraco.TestData.csproj
- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
- tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
- tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
- tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
- umbraco.sln
This PR moves the nuget dependencies to a centralised file, which should make merging simpler in the future.
> Centralised NuGet packages

- src/Umbraco.Web.UI.Login/src/components/layouts/auth-layout.element.ts
Added CSS custom properties to control: 
* primary color (used for headline and buttons)
* text color
* border-radius on image
* border-radius on content box
* border-radius on buttons
* size of headlines (primary (small, large), secondary)
> V13: Add more css custom properties to style the login screen

- src/Umbraco.Core/Composing/TypeFinder.cs
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14598
i have added ReSharperTestRunner to KnownAssemblyExclusionFilter
> Added ReSharperTestRunner to KnownAssemblyExclusionFilter

- src/Umbraco.Web.Website/Controllers/UmbTwoFactorLoginController.cs
Fixed log message in `Verify2FACode` method as mentioned in https://github.com/umbraco/Umbraco-CMS/pull/15317#issuecomment-1833370661
> Fix log message in `Verify2FACode` method

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/PartialView/PartialView.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/PartialView/PartialViewFolder.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialViews.spec.ts
- Refactor acceptance tests for Partial View
- Refactor api test for Partial View
- Bumped version of Test Helper
###To test
Follow the README.md located in tests/Umbraco.Tests.AcceptanceTest for running the test
Test the tests in tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialViews.spec.ts
> V14 QA Refactor code of Partial View acceptance tests

- src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExternalIndexSearcherTest.cs
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExternalIndexTests.cs
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IExamineExternalIndexSearcherTest.cs
Added Integration Tests related to Examine InternalIndex Search and ExternalIndex Search.
> V12 Integration test for InternalIndex and ExternalIndex Search

- src/Umbraco.Core/ExpressionHelper.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/AllLanguageControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/ByIsoCodeLanguageControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/CreateLanguageControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/DeleteLanguageControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/Item/ItemsLanguageEntityControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Language/UpdateLanguageControllerTests.cs
Added Integration test for the Language endpoints.
Updated method for GetMethodParams to also get QueryAttributes.
> V14 QA integration test authorization for languages for ManagementApi

- build/azure-pipelines.yml
- build/nightly-build-trigger.yml
This PR cherry-picks the relevant updates from cd10d58 to improve the nightly builds.
> Update nightly build

- tests/Umbraco.Tests.Integration/ManagementApi/Template/ByKeyTemplateControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/CreateTemplateControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/DeleteTemplateControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/Item/ItemTemplateItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/Query/ExecuteTemplateQueryControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/Query/SettingsTemplateQueryControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/ScaffoldTemplateControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/Tree/ChildrenTemplateTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/Tree/RootTemplateTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Template/UpdateTemplateControllerTests.cs
Added tests for the template endpoints
> v14 QA Added integration tests for the templates

- tests/Umbraco.Tests.Integration/ManagementApi/MemberType/Item/ItemMemberTypeItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/MemberType/Tree/RootMemberTypeTreeControllerTree.cs
Added tests for MemberType endpoints
> V14 QA Added integration tests about authorization handler for Member Type endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/MemberGroup/Item/ItemMemberGroupItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/MemberGroup/Tree/RootMemberGroupTreeControllerTests.cs
Added tests for MemberGroup endpoints
> V14 QA Added integration tests about authorization handler for Member Group endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Member/Item/ItemMemberItemControllerTests.cs
Added integration tests about authorization handler for Member endpoint
> V14 QA Added integration tests about authorization handler for Member endpoint

- tests/Umbraco.Tests.Integration/ManagementApi/PropertyType/IsUsedPropertyTypeControllerTests.cs
Added tests for PropertyType endpoint
> V14 QA Added integration tests about authorization handler of PropertyType endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Profiling/GetStatusProfilingControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Profiling/UpdateStatusProfilingControllerTests.cs
Added tests for Profiling endpoints
> V14 QA Added integration tests about authorization handler of Profiling endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/ModelsBuilder/BuildModelsBuilderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/ModelsBuilder/GetModelsBuilderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/ModelsBuilder/StatusModelsBuilderControllerTests.cs
Added tests for ModelsBuilder endpoint
> V14 QA Added integration tests about authorization handler for Models Builder endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/ByPathPartialViewControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/CreatePartialViewControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/DeletePartialViewControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Folder/ByPathPartialViewFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Folder/CreatePartialViewFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Folder/DeletePartialViewFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Items/ItemPartialViewItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Snippet/ByNameControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Snippet/GetAllControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Tree/ChildrenPartialViewTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/Tree/RootPartialViewTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PartialView/UpdatePartialViewControllerTests.cs
Added integration tests about authorization handler for Partial View endpoints
> V14 QA Added integration tests about authorization handler for Partial View endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Relation/ByChildRelationControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Relation/ByRelationTypeKeyRelationControllerTests.cs
Added tests for Relation endpoints
> V14 QA Added integration tests about authorization handler of Relation endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/RedirectUrlManagement/ByKeyRedirectUrlManagementControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RedirectUrlManagement/DeleteByKeyRedirectUrlManagementControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RedirectUrlManagement/GetAllRedirectUrlManagementControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RedirectUrlManagement/GetStatusRedirectUrlManagementControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RedirectUrlManagement/SetStatusRedirectUrlManagementControllerTests.cs
Added tests for RedirectUrlManagement endpoints
> V14 QA Added integration tests about authorization handler of RedirectUrlManagement endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Item/ItemRelationTypeItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Query/ByKeyRelationTypeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Query/CreateRelationTypeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Query/DeleteRelationTypeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Query/UpdateRelationTypeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/RelationType/Tree/RootRelationTypeTreeControllerTests.cs
Added tests for RelationType endpoints
> V14 QA Added integration tests about authorization handler of RelationType endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/PublishedCache/CollectPublishedCacheControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PublishedCache/RebuildPublishedCacheControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PublishedCache/ReloadPublishedCacheControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/PublishedCache/StatusPublishedCacheControllerTests.cs
Added tests for PublishedCache endpoints
> V14 QA Added integration tests about authorization handler of PublishedCache endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Upgrade/AuthorizeUpgradeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Upgrade/SettingsUpgradeControllerTests.cs
Added integration tests for the upgrade controllers
> V14 QA Added tests for Upgrade controllers

- tests/Umbraco.Tests.Integration/ManagementApi/TrackedReference/ByIdTrackedReferenceControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/TrackedReference/DescendantsTrackedReferenceControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/TrackedReference/ItemsTrackedReferenceControllerTests.cs
Added integration tests for tracked reference endpoints
> V14 QA Added integration tests for tracked reference

- tests/Umbraco.Tests.Integration/ManagementApi/Tour/GetTourControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Tour/SetTourControllerTests.cs
Added integration tests for the tour endpoints
> vV14 QA Added integration tests for the tour endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Telemetry/AllTelemetryControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Telemetry/GetTelemetryControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Telemetry/SetTelemetryControllerTests.cs
Added tests for Telemetry endpoints
> V14 QA Added integration tests about authorization handler of Telemetry endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Tag/ByQueryTagControllerTests.cs
> V14 QA Added integration tests about authorization handler of Tag endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Searcher/AllSearcherControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Searcher/QuerySearcherControllerTests.cs
Added tests for Searcher endpoints
> V14 QA Added integration tests about authorization handler of Searcher endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Indexer/AllIndexerControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Indexer/DetailsIndexerControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Indexer/RebuildIndexerControllerTests.cs
Added integration tests about authorization handler for Indexer endpoints
> V14 QA Added integration tests about authorization handler for Indexer endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/Security/BackOfficeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Security/ResetPasswordControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Security/ResetPasswordTokenControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Security/VerifyResetPasswordTokenControllerTests.cs
Added tests for Security endpoints
> V14 QA Added integration tests about authorization handler of Security endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/StaticFile/Item/ItemStaticFileItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/StaticFile/Tree/ChildrenStaticFileTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/StaticFile/Tree/RootStaticFileTreeControllerTests.cs
Added tests for StaticFile endpoints
> V14 QA Added integration tests about authorization handler of StaticFile endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/HealthCheck/ExecuteActionHealthCheckControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/HealthCheck/Group/AllHealthCheckGroupControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/HealthCheck/Group/ByNameHealthCheckGroupControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/HealthCheck/Group/CheckHealthCheckGroupControllerTests.cs
Added integration tests for health check endpoints
> V14 QA Added authorization integration tests healthcheck

- tests/Umbraco.Tests.Integration/ManagementApi/DocumentBlueprint/Item/ItemDocumentBlueprintControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/DocumentBlueprint/Tree/RootDocumentBlueprintTreeControllerTests.cs
Added integration test for document blueprint endpoints
> V14 QA Added authorization integration tests for document blueprint

- tests/Umbraco.Tests.Integration/ManagementApi/Media/ByKeyMediaControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/CreateMediaControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/Item/ItemMediaItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/MoveMediaControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/MoveToRecycleBinMediaControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/RecycleBin/ChildrenMediaRecycleBinControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/RecycleBin/RootMediaRecycleBinControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/SortMediaControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/Tree/ChildrenMediaTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/Tree/ItemsMediaTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/Tree/RootMediaTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Media/UpdateMediaControllerTests.cs
Added tests for the media controllers
> V14 QA Added integration test for media

- src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/GetRichTextRulesByPathController.cs
Renamed GetRichTextRulesByPath controller
> V14 Fixed Stylesheet controller naming

- tests/Umbraco.Tests.Integration/ManagementApi/Script/ByPathScriptControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/CreateScriptControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/DeleteScriptControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Folder/ByPathScriptFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Folder/CreateScriptFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Folder/DeleteScriptFolderControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Item/ItemScriptItemControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Tree/ChildrenScriptTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/Tree/RootScriptTreeControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Script/UpdateScriptControllerTests.cs
Added tests for Script endpoints
> V14 QA Added integration tests about authorization handler of Added tests for Script endpoints

- tests/Umbraco.Tests.Integration/ManagementApi/TemporaryFile/ByKeyTemporaryFileControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/TemporaryFile/CreateTemporaryFileControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/TemporaryFile/DeleteTemporaryFileControllerTests.cs
Added tests for the temporary file endpoints.
> V14 QA authorization integration tests temporary file

- src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
The authorization policy was still on language controller, even though we had cherry picked the fix, must have been a weird merge 🤷 
This PR removes the restriction.
> v13: Remove sections setting authorization policy

- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs
- src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs
- src/Umbraco.Infrastructure/Examine/RebuildOnStartupHandler.cs
- tests/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs
Reimplementation of #14020
Both need to be closed when this is merged
> RebuildOnStartupHandler inject interface insteadf of ExamineIndexRebuilder

- src/Umbraco.Web/Actions/ActionCreateBlueprintFromContent.cs
- src/Umbraco.Web/Editors/ContentController.cs
- src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
This is a backport of #15482 - steps to test are outlined there 😄
> Add policies for content template handling (backport of #15482)

- tests/Umbraco.Tests.Integration/ManagementApi/Install/SettingsInstallControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Install/SetupInstallControllerTests.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Install/ValidateDatabaseInstallControllerTests.cs
Added test for the install endpoints
> V14 QA Added integration test for the install endpoints

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
Linked issue: https://github.com/umbraco/Umbraco-CMS/issues/8648
Just like the previous PR: had to add some batching to avoid passing to many nodeIds at once to the sql statement. However this time, I could not reproduce this but the person bringing it up in the issue was able to test it.
> Batched more update calls to avoid Sql paramater count error

- src/Umbraco.Cms.Api.Management/Controllers/Server/ConfigurationServerController.cs
- src/Umbraco.Cms.Api.Management/Mapping/Server/ServerConfigurationMapDefinition.cs
- src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerConfigurationResponseModel.cs
- Implemented new Security configuration endpoint
- Using swagger `server/configuration`
- should return something like:
```
"allowPasswordReset": true
```
> V14: Security configuration

- src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
Update croatian translation hr.xml file and added translations for dynamic roots, analytics and webhooks. Tested with Umbraco 13.0.0-rc4
> Update croatian translation

- src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/15504
Fixes an issue where the icon on login providers would not follow the text color, making it hard to see with some button colors.
> v13: the color on icons for external login providers should match the text

- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataType.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/DataType/DataTypeFolder.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ApprovedColor.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ImageCropper.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Numeric.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Radiobox.spec.ts
Added acceptance tests for ImageCropper
Added acceptance tests for Numeric
Added acceptance tests for Radiobox
Updated tests for Approved Color to change the way to arrange test data
Updated api tests for DataType: changed "" to '' and updated before/after methods
> V14 Added acceptance tests for Image Cropper, Numeric and Radiobox

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Textarea.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Textstring.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Upload.spec.ts
Added acceptance tests for Textarea, Textstring and Upload Article, Upload Audio, Upload File, Upload Vector Graphics, Upload Video
> V14 Added acceptance test for Textarea, Textstring, Upload

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_0_0/AddMemberPropertiesAsColumns.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_2_0/AddHasAccessToAllLanguagesColumn.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_2_0/AddUserGroup2LanguageTable.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_3_0/AddBlockGridPartialViews.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_4_0/AddBlockGridPartialViews.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_5_0/AddPrimaryKeyConstrainToContentVersionCleanupDtos.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_7_0/MigrateTagsFromNVarcharToNText.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_11_3_0/AddDomainSortOrder.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_11_4_0/AlterKeyValueDataType.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/ResetCache.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/UseNvarcharInsteadOfNText.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_1_0/AddOpenIddict.cs
- src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_1_0/TablesIndexesImprovement.cs
Obsoletes the old migration that is to be removed in V14.
> V13: Obsolete migrations

- src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
- src/Umbraco.Web.BackOffice/ModelBinders/BlueprintItemBinder.cs
- src/Umbraco.Web.BackOffice/ModelBinders/ContentItemBinder.cs
V10+ version of https://github.com/umbraco/Umbraco-CMS/pull/15638
> V10+ version of #15638

- src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Document/UnpublishDocumentController.cs
- src/Umbraco.Core/Services/OperationStatus/ContentCreatingOperationStatus.cs
`ContentControllerBase` contains a lot of operations that are only applicable to document operations. These have been moved to `DocumentControllerBase` 😃
> Move document related operations to DocumentControllerBase

- src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
This is picked from v14/dev to distinguish between Belle and Login so the correct assets are being built when you run Umbraco.Web.UI and/or build the StaticAssets project.
> Login assets should be built independently of the Backoffice

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
- src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.html
Add localization key for 'Cancel and clear query' (dynamicRoot)
> Add localization key for 'Cancel and clear query'

- tests/Umbraco.Tests.Common/Builders/ContentTypeBuilder.cs
I'd like to use it in my own tests without breaking out of the builder pattern. 🙃
> Add WithIsElement to ContentTypeBuilder

- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Dictionary/Dictionary.spec.ts
Fixed failing Dictionary tests. Also skipped tests that are unable to run because the frontend is not ready.
Decreased the timeout from 60 seconds to 40.
> V14 QA fix failing dictionary acceptance tests.

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/CreatedPackages.spec.ts
Changed the locator for saving a package
> V14 QA Fix package acceptance test

- tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiTest.cs
Removes the service for NuCacheStartupHandler
> V14 QA Authorization integration tests. Removes nucache handler

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs
Adds V14 data type configuration migration for all system data types from V7.0 and onwards.
Will be peer tested 😆
> Migrate data type configurations from V7.0+

- src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Tree/ChildrenDictionaryTreeController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Tree/RootDictionaryTreeController.cs
I found a few leftovers from the dictionary item pagination re-implementation in https://github.com/umbraco/Umbraco-CMS/pull/15308 ... this PR removes those leftovers 😄
> Clean up leftovers from old dictionary pagination

- src/Umbraco.Cms.Api.Management/OpenApi.json
The `OpenApi.json` file has drifted somewhat from the server schema. It seems to be predominantly related to newly added recycle bin operations.
This PR updates the file to match the current server schema.
> Regenerate OpenApi.json to match current server schema

- src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
- Updated the `cy` lang file to include new keys found in the `en_us` lang file.
- Translations have been checked using:
- Cysgliad: https://www.cysgliad.com/
- BydTermCymru: https://www.gov.wales/bydtermcymru
- Gweiadur: https://www.gweiadur.com/
> Update Welsh lang file

- src/Umbraco.Web.UI.Login/src/context/auth.repository.ts
This PR fixes the login function in **auth.repository.ts** on the new Login UI. _twoFactorView_ property has been added to the response to display the custom 2fa view, before that returned only status and error and displayed the default 2fa view
Issue: https://github.com/umbraco/Umbraco-CMS/issues/15781
> fix 2fa user login - add twoFactorView property to response (15781)

- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ApprovedColor.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypeFolder.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ImageCropper.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Radiobox.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Upload.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/CreatedPackages.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/InstalledPackages.spec.ts
The pipeline ends up timing out because of too many failing tests. So they will currently be skipped, so the pipeline can go through
> V14 QA Skipped failing acceptance tests.

- src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/ByIdMemberGroupController.cs
- src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/ByKeyMemberGroupController.cs
- src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/DeleteMemberGroupController.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- Had some feedback from the frontend team about a missing `ById` endpoint & the delete endpoint mentioning `key` and not `id`
- This PR should remedy these faults 😁 
- Using swagger, create a few member groups
- Assert that you can get these member groups with the new `ById` endpoint 👍
> V14: member group controllers fixes

- src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs
- src/Umbraco.Infrastructure/PropertyEditors/ValueListUniqueValueValidator.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/EnsureUniqueValuesValidatorTest.cs
Migrates checkbox list from V13 and below to V14 format.
Also fixes a bug in the value list uniqueness validator.
> V14: add checkboxlist to list of migrations

- src/Umbraco.Cms.Api.Management/Controllers/Language/AllLanguageController.cs
- src/Umbraco.Cms.Api.Management/Controllers/Webhook/AllWebhookController.cs
Added controller to fetch paged results of webhooks.
> Webhook paged results

- src/Directory.Packages.props
This PR updates ImageSharp to a minimum version that is not vulnerable
> Update ImageSharp 

- src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetPermissionsCurrentUserController.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
Added missing 404 in openapi when using current user endpoints for permissions
> Added missing 404 in openapi when using current user endpoints for permissions

- src/JsonSchema/JsonSchema.csproj
Just the usual update JSON schema for Umbraco 10 with latest references for Forms and Deploy following the releases this week.
> Updates JSON schema for Umbraco 10 with latest references for Forms and Deploy

- src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
- src/Umbraco.Cms.Api.Management/Mapping/MediaType/MediaTypeMapDefinition.cs
Fixes wrong mapping from entity.id to entityType.id
> Fix content type id mapping

- src/Umbraco.Cms.Api.Management/OpenApi.json
- Added missing endpoints to OpenApi.json.
> V14: Update OpenApi.json

- src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Fixes https://github.com/umbraco/Umbraco-CMS/issues/15774
- Cherry picks missing commit https://github.com/umbraco/Umbraco-CMS/commit/e64b5e2a5cbe5f428cdd17262c7ae41217dfb881
- Follow steps in https://github.com/umbraco/Umbraco-CMS/issues/14752
> V10: Fix for fallback file upload (#14892)

- src/Umbraco.Cms.Api.Management/Controllers/Webhook/EventsWebhookController.cs
- src/Umbraco.Cms.Api.Management/DependencyInjection/WebhooksBuilderExtensions.cs
- src/Umbraco.Cms.Api.Management/Mapping/Webhook/WebhookEventMapDefinition.cs
- src/Umbraco.Cms.Api.Management/ViewModels/Webhook/WebhookEventViewModel.cs
- Added `events` endpoint to Webhook silo
- Add new `WebhookEventMapDefinition`
- Using swagger, call the new endpoint
- Assert the 5 default events get returned 🚀
> V14: Add webhook events endpoint

- src/Umbraco.Cms.Api.Management/Controllers/User/BulkDeleteUserController.cs
- src/Umbraco.Cms.Api.Management/Controllers/User/DisableUserController.cs
- src/Umbraco.Cms.Api.Management/Controllers/User/EnableUserController.cs
- src/Umbraco.Cms.Api.Management/Controllers/User/UnlockUserController.cs
- src/Umbraco.Cms.Api.Management/Controllers/User/UpdateUserGroupsUserController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/AddUsersToUserGroupController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/BulkDeleteUserGroupsController.cs
- src/Umbraco.Cms.Api.Management/Controllers/UserGroup/RemoveUsersFromUserGroupController.cs
- src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/ViewModels/User/Current/CurrentUserResponseModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/DeleteUsersRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/DisableUserRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/EnableUserRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/UnlockUsersRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserGroupsOnUserRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserRequestModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/UserPresentationBase.cs
- src/Umbraco.Cms.Api.Management/ViewModels/User/UserResponseModel.cs
- src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/DeleteUserGroupsRequestModel.cs
- Refactor user & user group endpoints to use `ReferenceByIdModel` instead of direct Guids 
- Assert that the endpoints affected still works 😁
> V14: Refactor user and usergroups with referency by id model

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
This PR applies the temporary fix made in our test Helpers.
> V14 QA Bumped version of testHelpers

- src/Umbraco.Web.Website/Middleware/BasicAuthenticationMiddleware.cs
This PR updates the path that basic auth redirects to, when using the login screen
> Update path for basic auth redirect

- Directory.Packages.props
- tests/Directory.Packages.props
Updated nuget pacakges to latest versions anno may 23th
> Updated nuget packages

- src/Umbraco.Core/Cache/DistributedCacheExtensions.cs
Fixes an issue with the user cache, where the user was not cleared by both ID and Guid.
> V14: Fix user cache issue

- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
Decreases the amount of retries on the E2E tests
> V14 QA Decreased retry amount

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeDesignTab.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeSettingsTab.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/MediaType/MediaTypeDesignTab.spec.ts
Fixed failing acceptance tests and bumped version of testHelpers that also included fixes for the tests
> V14 QA Fix E2E tests 

- src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/Item/DocumentTypeItemResponseModel.cs
- Added description on the `DocumentTypeItemResponseModel`
- Create a few doc types with descriptions
- Call the document type items endpoint, and assert that it has descriptions 😁
> V14; Include description in doctype item

- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
> v14: Add retries to flaky tests

- src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs
This PR closes #16386
Adds a check to the `EagerMatcherPolicy` checking the type of the candidate controller, if any candidate is a `RenderController` or `SurfaceController` the matcher policy is short-circuited, ensuring that the `UmbracoRouteValueTransformer` is always hit. This is done to re-introduce a side effect of #16015.
In an ideal sense, this should not be necessary, since neither RenderControllers nor SurfaceControllers should ever be statically routed, their purpose is to interact with the Umbraco routing pipeline, I.E. Dynamic routing. If static routing is desired then a page controller is the way to go: https://docs.umbraco.com/umbraco-cms/reference/routing/custom-routes#custom-route-with-ivirtualpagecontroller
With that in mind, this fix should not be added to V14. 
Try …
> V13: Add check to ensure that RenderControllers and SurfaceControllers are always routed through the UmbracoRouteValueTransforms

- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
Decreased retry count to 2, same as in V14
> V13 QA Decreased retry count

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
We swapped faker out with the crypto library in our testHelpers and jsonBuilder
> V13 QA Updated depedencies 

- Directory.Packages.props
- src/Umbraco.Cms.Imaging.ImageSharp/Umbraco.Cms.Imaging.ImageSharp.csproj
- src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
- src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
- src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Updates all nuget packages to latest minor / patch
> V13: Update nuget packages

- src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
- Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16541;
- In the case when list view is used, `/umbraco/backoffice/umbracoapi/entity/GetPagedChildren` is called which was getting all the children without filtering out any nodes not part of the user start nodes. When list view is disabled, we use a different endpoint, which gives us the correct result;
- Renamed `GetStartNodes()` to `GetStartNodesIds()` and added `GetStartNodePaths()`.
> Verify on **v13/dev**:
- Create a doc type - allowed at root and add it to its allowed child node types + enable list view;
- Create the following content structure:
- Root
- Tree 1
- T1 Page 1
- T1 Page 2
- Tree 2
- T2 Page 1
- T2 Page 2
- Create a new user group with access to Content section and allow "Browse Node", "Copy" and "Move" in the …
> V13: Respect user start nodes when moving or copying items in list view

- src/Umbraco.Cms.Api.Management/Controllers/Tree/UserStartNodeTreeControllerBase.cs
- Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16789.
- Follow the "Steps to reproduce" in the original issue and verify that it is no longer an issue.
> V14: Fixing totalItems amount for ChildrenXTreeControllers

- Directory.Packages.props
Updated dependencies.
Most notable:
* .NET to 8.0.7
* Examine to 3.3.0
> Updated to lastest nuget minor or patch versions

- src/Umbraco.Core/Security/Authorization/IAuthorizationHelper.cs
Fixes breaking change from https://github.com/umbraco/Umbraco-CMS/pull/16836/files#r1713217953
> v14: TryGetUmbracouser default implementation

- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16806
Read more about the case on the actual issue.
> Fix: V13 ensure data change is detected on embedding media (16806)

- Directory.Packages.props
- global.json
- src/Umbraco.Cms.Api.Management/Mapping/PartialView/PartialViewViewModelsMapDefinition.cs
- src/Umbraco.Cms.Api.Management/Mapping/Script/ScriptViewModelsMapDefinition.cs
- src/Umbraco.Cms.Api.Management/Mapping/Stylesheet/StylesheetviewModelsMapDefinition.cs
- tests/Directory.Packages.props
- tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/PublishedContentQueryTests.cs
Updated to .NET 9 RC1 + fixed a few things to make it running
And updated nuget packages to latest versions
> Updated to dotnet 9 RC.1 - and other nuget packages

- src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
fixes https://github.com/umbraco/Umbraco-CMS/issues/15587
> Bug: V13.5 15587

- templates/UmbracoProject/.template.config/template.json
Updates the template to reference the newest LTS
> V15: Update template to reference 13.5

- src/Umbraco.Cms.Imaging.ImageSharp/ConfigureImageSharpMiddlewareOptions.cs
There is an error in the format code like this:
"The parameters to a C# method or indexer call or declaration are not all on the same line or each on a separate line."
This PR makes the parameters on a separate line.
> Fix error format code

- src/Umbraco.PublishedCache.HybridCache/Factories/CacheNodeFactory.cs
- tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheTemplateTests.cs
- tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheTests.cs
Reintroduce uncommented tests and fix issues they found
> Fixed issues with publishing in cache and reintroduced tests

- src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
Fixes #17220
Sort the data before sending to the front end by sortOrder
> fix(#17220): added a sort to the mapping so the UI reflects the database

- Directory.Packages.props
Updated the Microsoft.Extensions.Caching.Memory to avoid vulnerability
> V14 Updated nuget package 

- Directory.Packages.props
- src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
- src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
Added an explicit dependency to Microsoft.Extensions.Caching.Memory to force it to use a non-vulnerable version
> Added an explicit dependency to Microsoft.Extensions.Caching.Memory

- src/Directory.Packages.props
Updated ImageSharp to a non vulnerable version to 2.1.9
> Updated image sharp to a non vulnerable version

- src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs
Updated to string.empty to fix build error
> V14 bugfix updated to string empty

- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PublishStatusRepository.cs
- src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
- tests/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
- tests/Umbraco.Tests.Common/Builders/MediaTypeEditingBuilder.cs
- tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishStatusServiceTest.cs
Cleaned up build errors so our pipeline can run
> v15 bugfix Fixed build errors

- src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
If there's an existing issue for this PR then this fixes #15770 (in part)
Notice that #15770 covers two different issues:
- The original issue description.
- Other contextual issues for newly created content, raised in [this comment](https://github.com/umbraco/Umbraco-CMS/issues/15770#issuecomment-2076739278).
This PR fixes the issue described in the original issue description by reloading the contextual dialog options, if the MNTP is part of a newly created document.
Another PR will be submitted to tackle the other contextual issues, as they are indeed a whole other issue.
Follow the steps in the issue description in #15770 - it should work now after content creation. 
Please notice that the screencast in the first comment of #15770 is somewhat off; it does not follow the steps, so don't …
> MNTP: Re-initialize contextual dialog options upon content creation

- src/Directory.Packages.props
Updated messagePack to avoid build errors
> V10 updated message pack

- Directory.Packages.props
Updated version of messagePack to fix build errors
> V13 Updated version of messagepack

- build/azure-pipelines.yml
Try swapping to a windows agent for pipelines
> Swap to windows vm for build

- tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SyntaxProvider/SqlServerSyntaxProviderTests.cs
> Format sql statement

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/Permissions/UserGroup/MemberSection.spec.ts
This PR relies on the fix from #17440 so wait with merging until the the PR is in v14.
> V14 QA members section user tests

- src/Umbraco.Core/EmbeddedResources/BlockGrid/items.cshtml
- src/Umbraco.Web.UI/Views/Partials/blockgrid/items.cshtml
Updated the embedded views to not use obsolete method.
> Change udi to key i the block grid items view

- build/azure-pipelines.yml
- tests/Umbraco.Tests.AcceptanceTest/playwright.config.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/CreatedPackages.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/InstalledPackages.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/PackagesPackages.spec.ts
Decreased retry count to 1
Decreased test timeout to 30 seconds.
Added a check if we want to run the SQL Server Linux E2E tests, these were flaky
These changes should allow us for a smoother pipeline run
> V14 QA updated playwright config

- .gitignore
- src/Umbraco.Web.UI.Client/public/mockServiceWorker.js
> Fix: re-introduce service worker

- src/Umbraco.Web.UI.Client/src/packages/core/content/controller/merge-content-variant-data.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
moving some props to minimize change detection
> Feature: minimize data changes

- src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/17598
It's now wrapped correctly:
> Fixes #17598

- src/Umbraco.Web.UI.Client/src/packages/ufm/components/content-name/content-name.element.ts
Adds support for Media Picker values to the `umbContentName` UFM component.
> UFM: Adds Media Picker support to `umbContentName`

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
- src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.context.ts
- src/Umbraco.Web.UI.Client/src/packages/core/components/table/table.element.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
- src/Umbraco.Web.UI.Login/public/mockServiceWorker.js
* Updates to latest UI Library to solve selection issues.
* Fixes to Collection Table View Selection — this is fixed by UI Library but there as a temporary fix that needed to be removed to avoid double selection.
* Fixes to Document Collection Table View renders with Items Paths if opened directly — this only worked if you opened grid first and then list.
> build(deps): update @umbraco-ui/uui from 1.12.1 to 1.12.2

- templates/UmbracoExtension/README.txt
Fixed broken link
Was pointed out on Discord: https://discord.com/channels/869656431308189746/1311643841740148836
> Update broken link in readme for dotnet new umbraco-extension

- build/azure-pipelines.yml
- src/Umbraco.Cms.Persistence.EFCore/Locking/SqlServerEFCoreDistributedLockingMechanism.cs
- tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
- Fixes pipeline that builds client multiple times
- Fixes pipeline that load all of git in scenarios not needed
- Fixes memory leak in the integration tests, where the host did not dispose the service provider. (This means the tests do not lack memory anymore - And thereby executes a lot faster)
> Optimize Azure pipeline

- src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs
- src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
- src/Umbraco.Core/Serialization/IWebhookJsonSerializer.cs
- src/Umbraco.Core/Services/WebhookRequestService.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
- src/Umbraco.Infrastructure/Serialization/ContentJsonTypeResolverBase.cs
- src/Umbraco.Infrastructure/Serialization/SystemTextWebhookJsonSerializer.cs
- src/Umbraco.Infrastructure/Serialization/WebhookJsonTypeResolver.cs
- Cherry pick of #17656
- Seems like some using where removed, which is very much needed in v14, so this PR add's those back 😁
> V14: cherry pick #17656

- src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
I spotted that this code was not pushing the state but setting it, meaning the user would lose their history.
> Hotfix: block use push state

- src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Duplicate logic from block list to accept blocks in an otherwise undefined value field, which means we can safely build up the block structure even though the editor is empty.
> V15: RTE blocks do not work in an empty RTE editor

- src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
Fixes: #17497
v15 Implementation: #17762
Custom message is not shown: https://github.com/umbraco/Umbraco-CMS/issues/17764
> V14 min/max validator for mediapicker

- src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
Fixes: #17497
v14 Implementation: #17761
Custom message is not shown: https://github.com/umbraco/Umbraco-CMS/issues/17764
> V15 min/max validator for mediapicker

- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/manifests.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/types.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-content-type-alias.condition.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-entity-is-new.condition.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-entity-type.condition.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-has-collection.condition.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/workspace-action/manifests.ts
Fixes the most important problem of https://github.com/umbraco/Umbraco-CMS/issues/14541 (For v.15)
And thereby closes the issue, but there may be perspectives to take into account from a Product Design perspective.
> Fix #14541: hide "Publish with descendants" when not yet created

- src/Umbraco.Web.UI.Client/src/apps/app/app-logo.element.ts
Removes one circular dependency
> Feature: remove one circular dependency

- src/Umbraco.Web.UI.Client/src/packages/core/router/route.context.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/paths.ts
> Add workspace view path const

- src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/structure/document-type-workspace-view-structure.element.ts
Improved the wording for configuration of Collections.
> Feature: improve collection wording

- tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs
#17167 reminded me that we're not actively testing the Delivery API contract ... so this PR adds that test 😄
> Added integration test to verify the Delivery API contract

- src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
Cherry-picked #17938 into v15/dev
> Make the Delivery API "ancestors" selector work with preview (#17938)

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
- src/Umbraco.Web.UI.Login/package-lock.json
- src/Umbraco.Web.UI.Login/package.json
Update the UI library to 1.12.2.
> V13: Update @umbraco-ui/uui to 1.12.2

- src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entries.context.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.function.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.test.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/index.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17428
Cleans up validation messages based on Block that are actually present in the editor.
> Fix: 17428

- src/Umbraco.Core/EmbeddedResources/Lang/en.xml
- src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17738
> add missing new media auditTrail translation

- src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/modal/entity-create-option-action-list-modal.element.ts
This PR ensures that both create options with buttons and links close the modal.
A `UUIRefElement` does not dispatch an `open` event when configured as a link. I have added a manual handler in the create option modal to ensure that links submit it when they close.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17968
> Close modal for create options with links

- .github/BUILD.md
- src/Umbraco.Web.UI.Client/.github/README.md
Improving readme files for contributors to get started on front-end changes
> Chore: Improving readme files for contributors

- src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/packages/members/member-group/components/member-group-picker-modal/member-group-picker-modal.element.ts
This PR changes the dialog label for the member group picker making the action clearer.
This PR aims to resolve the Member Group picker label mentioned in the following issue: #16668
> Updated the dialog label for the Member Group Picker.

- src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/packages/user/user/modals/user-picker/user-picker-modal.element.ts
This PR changes the user picker's dialog label, making the action clearer.
This PR aims to resolve the User picker label mentioned in the following issue: https://github.com/umbraco/Umbraco-CMS/issues/16668
> Updated the dialog label for the User Picker label

- src/Umbraco.Web.UI.Client/src/views/webhooks/edit.controller.js
- src/Umbraco.Web.UI.Client/src/views/webhooks/edit.html
If there's an existing issue for this PR then this fixes #15274
See the linked issue for a description and instructions how to test 👍
> Add clientside validation to webhook events

- src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentControllerBase.cs
- tests/Umbraco.Tests.Common/TestHelpers/DocumentUpdateHelper.cs
- tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiTest.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Policies/UpdateDocumentTests.cs
Fixes #17890
Re-adds authorization following #17052 
Also adds additional testing plumbing and integration test 😄
> V15: Add authorization to saves

- src/Umbraco.Cms.Api.Management/Controllers/Document/CreateDocumentControllerBase.cs
- tests/Umbraco.Tests.Common/TestHelpers/DocumentUpdateHelper.cs
- tests/Umbraco.Tests.Integration/ManagementApi/Policies/CreateDocumentTests.cs
#18111 Missed the missing auth on the create endpoints, this PR adds this, and tests
> V15: Add authorization to create

- src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/Umbraco.TrueFalse.ts
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18178
Just a small fix for a copy/paste error.
> Fixed name of True/False property editor schema manifest

- src/Umbraco.Web.UI.Client/src/packages/user/user-group/modals/user-group-picker/user-group-picker-modal.element.ts
Fixes #16452.
Adds a filter search field to the User Group Picker modal, for inline filtering against the user-group's name or alias.
> User Group picker modal: adds filter input

- src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/packages/core/components/input-toggle/input-toggle.element.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/manifests.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
- Update the settings section to fix warnings about missing labels
- Adds new label for screen reader
- Reduce unneeded description
> V15/feature/toggle property editor UI

- src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/create/default/manifests.ts
> Correct icon and label for media type create option

- src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttongroup.directive.js
Fixes #18253 and #18239, follow the reproduction steps in both issues.
> Fix issues in newly added buttongroup localization

- src/Umbraco.Cms.Api.Management/Controllers/Member/MemberControllerBase.cs
- src/Umbraco.Cms.Api.Management/Controllers/User/UserOrCurrentUserControllerBase.cs
- src/Umbraco.Core/Services/OperationStatus/UserOperationStatus.cs
- src/Umbraco.Core/Services/UserService.cs
- src/Umbraco.Infrastructure/Services/MemberEditingService.cs
- src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/components/user-workspace-profile-settings/user-workspace-profile-settings.element.ts
This is the 15 version of this https://github.com/umbraco/Umbraco-CMS/pull/18261
See the linked PR for description, related issues and testing steps.
> Add validation to prevent update of a user or member to an invalid username (15)

- src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/views/edit/content-editor.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/router/components/not-found/route-not-found.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/17676
Based on https://github.com/umbraco/Umbraco-CMS/pull/18121 but somehow I broke the branch...
Also add a bit more delay to the Not found text on the Not found view and adds Localizations to these Tabs
> Fix: #17676

- src/Umbraco.Web.UI.Client/src/packages/core/modal/component/modal.element.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/18215
> Fix #18215

- src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
Umbraco 15 equivalent of https://github.com/umbraco/Umbraco-CMS/pull/18383
> Disable webhook firing if disable in configuration (15)

- src/Umbraco.PublishedCache.HybridCache/PublishedProperty.cs
Migrates #17024  as requested in https://github.com/umbraco/Umbraco-CMS/issues/16753#issuecomment-2671113565
> V15: Fall back to emptry string if null, migrate #17024

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Dictionary/Dictionary.spec.ts
Updated test helpers to fix failing add language test
Added timeout for test to avoid flakyness
> V15 QA fixed flaky language tests

- src/Umbraco.Cms.Api.Management/OpenApi.json
- src/Umbraco.Cms.Api.Management/OpenApi/BackOfficeSecurityRequirementsOperationFilterBase.cs
- src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
Relates to but doesn't fix https://github.com/umbraco/Umbraco-CMS/issues/18533
Small update to the error message displayed and logged for an unauthorized request.
> Fixed grammar of unauthorized message

- Directory.Packages.props
> v15: Update nuget packages

- src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
- tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/MediaPicker3ValueEditorValidationTests.cs
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/18531
The linked issue highlights a problem which I can replicate only when you first add an item to the media picker.  On the second attempt to update it goes through OK.  I can see the problem stems from the client not always providing the media type alias.
I had a brief look at fixing it front-end but it looked to be tricky (stemming from the fact that the media picker modal only returns the IDs of the selected media, not the types.
So I've resolved it server-side, by using the media key to find the media type aliases if we haven't been provided them.
To test, see the tests, and manually see the replication steps on the issue.
_Should be cherry-picked to the release branch once merged._
> Handle create and update validation for media picker

- src/Umbraco.Web.UI.Client/src/libs/extension-api/registry/extension.registry.ts
> Extension Registry JSDocs update

- .github/README.md
Add a NuGet badge to readme so you can immediately go to NuGet page. Also ordered related badges together.
> Add NuGet badge

- src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-element-manager.ts
- src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/repository/detail/document-blueprint-detail.server.data-source.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
@andr317c reported thatthe solution to this issue https://github.com/umbraco/Umbraco-CMS/issues/18132 was not working.
And I was able to reproduce the problem, so here is a different solution to this problem.
> Hotfix: 18132 (preventing model diff approach)

- src/Umbraco.Web.UI.Client/src/packages/tags/property-editors/tags/Umbraco.Tags.ts
> correct labels

- src/Umbraco.Web.UI.Client/src/packages/core/picker/search/picker-search-field.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/picker/search/picker-search-result.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
The vertical alignment of the search icon has changed with the latest UUI. Correction alignemnet.
> Center align search icon

- src/Umbraco.Web.UI.Client/src/packages/language/components/input-language/input-language.element.ts
- src/Umbraco.Web.UI.Client/src/packages/language/item/langauge-item-ref.element.ts
- src/Umbraco.Web.UI.Client/src/packages/language/item/manifests.ts
- src/Umbraco.Web.UI.Client/src/packages/language/manifests.ts
- src/Umbraco.Web.UI.Client/src/packages/language/repository/item/language-item.server.data-source.ts
- src/Umbraco.Web.UI.Client/src/packages/language/repository/item/types.ts
This PR registers a language item ref and implements the generic `umb-entity-item-ref` ref resolver in the input component.
> Feature: Language Item Ref

- src/Umbraco.Web.UI.Client/src/packages/documents/document-redirect-management/dashboard-redirect-management.element.ts
- src/Umbraco.Web.UI.Client/src/packages/settings/welcome/settings-welcome-dashboard.element.ts
- src/Umbraco.Web.UI.Client/src/packages/umbraco-news/umbraco-news-dashboard.element.ts
Update buttons for a less noisy look.
> Content & Settings dashboard button look

- src/Umbraco.Web.UI.Client/src/css/umb-css.css
- src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/templating/templates/global-components/input-template/input-template.element.ts
> Align card sizes

- src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
Make the numbers go to the right side:
> image cropper width height right side

- src/Umbraco.Core/Services/UserService.cs
Here I've removed one obsoleted method in `UserService` and updated the only caller to use the body of the removed method.  This only caller is itself not called in the code base.  However I've also extended it to handle GUID keys, as we can retrieve that, and seems like it was an oversight.
> Clean-up obsoletions on UserService

- src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Fixes circular dependencies in the workspace module
> Worspace: fix workspace circular

- src/Umbraco.Web.UI.Client/src/packages/user/user/repository/detail/user-detail.server.data-source.ts
- src/Umbraco.Web.UI.Client/src/packages/user/user/utils/index.ts
- src/Umbraco.Web.UI.Client/src/packages/user/user/utils/user-kind.ts
> User: Fix circular for user kind util

- src/Umbraco.Web.UI.Client/src/packages/core/property-type/index.ts
- src/Umbraco.Web.UI.Client/src/packages/core/property-type/utils/index.ts
- src/Umbraco.Web.UI.Client/src/packages/core/property-type/workspace/property-type-workspace.context.ts
Implemented a Validation Context to Property Type Workspace. This means submit will be prevented when validation issues are present.
> Feature: property type workspace validation context

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/package.json
- src/Umbraco.Web.UI.Login/package-lock.json
- src/Umbraco.Web.UI.Login/package.json
Updates to the latest Umbraco UI Library 1.13.0.
Fixes #18752
> build(deps): bump @umbraco-ui/uui from 1.12.2 to 1.13.0

- src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.element.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.element.ts
Not because its super duper great, but now it stands out a little bit — we can improve further later :-)
Result:
> Feature: make load more 100p wide

- src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/block-grid-manager.context.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-manager.context.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-manager.context.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts
Change the type so this change becomes clear in typescript
> Fix: make the deprecation discoverable from TypeScript

- src/Umbraco.Web.UI.Client/devops/circular/index.js
- src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/tree-expansion-manager.test.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/modal/public-access-modal.element.ts
Set a limit, if above this limit the test should fail.
(ignore the branch name, that was a mistake of mine, it is intended for v.15/dev, as we intend to get rid of all circular dependencies for v.16, but lets see how far we can get within reasonable time)
> Chore: set circular dependency limit

- src/Umbraco.Web.UI.Client/devops/circular/index.js
- src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block/validation/block-editor-validation-property-path-translator-base.api.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/constants.ts
Removes a few circular dependencies and lowers the default to 9...!
> V15: Block package should not import from itself

- src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoMemberAuthenticationDeliveryApiSwaggerGenOptions.cs
- src/Umbraco.Cms.Api.Management/OpenApi/BackOfficeSecurityRequirementsOperationFilterBase.cs
- src/Umbraco.Core/Composing/TypeFinder.cs
- src/Umbraco.Core/Exceptions/InvalidCompositionException.cs
- src/Umbraco.Core/Extensions/IntExtensions.cs
- src/Umbraco.Core/Extensions/StringExtensions.cs
- src/Umbraco.Core/GuidUtils.cs
- src/Umbraco.Core/HexEncoder.cs
- src/Umbraco.Core/Strings/DefaultShortStringHelper.cs
- src/Umbraco.Core/Strings/Utf8ToAsciiConverter.cs
> Avoid some heap allocations

- src/Umbraco.Cms.Api.Delivery/Services/ApiMediaQueryService.cs
- src/Umbraco.Core/Models/Membership/User.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationRepository.cs
- src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationTypeRepository.cs
- src/Umbraco.Infrastructure/Security/BackOfficeIdentityUser.cs
- src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
Avoid allocating new empty arrays, reuse existing empty array
> Avoid allocating new empty arrays, reuse existing empty array

- src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-main.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/section/section-default.element.ts
- src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user.context.ts
> Cleanup redirect to allowed section

- src/Umbraco.Core/Services/IContentSearchService.cs
- src/Umbraco.Core/Services/IContentSearchServiceOfTContent.cs
- src/Umbraco.Core/Services/IMediaSearchService.cs
- src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
- src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentListViewService.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentSearchService.cs
- src/Umbraco.Infrastructure/Services/Implement/ContentSearchServiceBase.cs
- src/Umbraco.Infrastructure/Services/Implement/MediaListViewService.cs
- src/Umbraco.Infrastructure/Services/Implement/MediaSearchService.cs
- tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentSearchServiceTests.cs
This PR introduces abstractions that allow backoffice collection views (formerly known as list views) to be powered by upcoming ["future of search"](https://github.com/umbraco/rfcs/blob/0027-the-future-of-search/cms/0027-the-future-of-search.md).
First and foremost, verify that collection views work as per usual - both for documents and media.
Next, create and register custom implementations of `IContentSearchService` and `IMediaSearchService`, and verify that they indeed power the collection views 😄 something in the lines of:
```cs
public class MyContentSearchService : IContentSearchService
{
private readonly IContentService _contentService;
public …
```
> Content search abstractions to facilitate new search in the backoffice

- src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.element.ts
- src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-apps.element.ts
- src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header.element.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/components/header-app/header-app-button.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
- src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/character-map-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user-header-app.element.ts
Yet another one of **Lee's Codesweep™** PRs! 🤪
I'd picked up on various client-side markup and style tweaks and code polish.
All nice to have for 16-RC, no breaking-changes. 🚀
> V16: Chore: Client-side markup and style code sweep

- src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/views/structure/media-type-workspace-view-structure.element.ts
This name change was maybe lost in the big merge or forgotten. Here is a fix :-)
> Hotfix: bring back media collection

- src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts
I'm not sure how this came about, but we should stop doing it.
> Hotfix: Do not reset promise on clear

- src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/number/decimal-property-value-preset.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/number/integer-property-value-preset.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/number/manifests.ts
- src/Umbraco.Web.UI.Client/src/packages/property-editors/number/types.ts
Making a Value Preset for Integer and Decimal + Fixing so a Value Preset can set a falsy value, aka. be able to set 0.
> Fix so a Preset Value can be falsy

- Directory.Packages.props
Updates Examine to latest patch, which reports suggest resolves some commonly reported issues.
See: https://github.com/umbraco/Umbraco-CMS/pull/19186
> Updates Examine to latest patch release

- src/Umbraco.Web.UI.Client/src/packages/core/collection/components/pagination/collection-pagination.element.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/document-redirect-management/dashboard-redirect-management.element.ts
- src/Umbraco.Web.UI.Client/src/packages/documents/documents/audit-log/info-app/document-history-workspace-info-app.element.ts
- src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/overview/components/log-viewer-message-templates-overview.element.ts
- src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/overview/components/log-viewer-saved-searches-overview.element.ts
- src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-messages-list.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/audit-log/info-app/media-history-workspace-info-app.element.ts
- src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
- src/Umbraco.Web.UI.Client/src/packages/packages/package-section/views/created/packages-created-overview.element.ts
- src/Umbraco.Web.UI.Client/src/packages/relations/relation-types/workspace/relation-type/views/relation-type-detail-workspace-view.element.ts
- src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.element.ts
This PR adds localization for the First, Previous, Next, Last in Pagination buttons. This PR should be merged after this PR https://github.com/umbraco/Umbraco.UI/pull/1069 is merged into Umbraco UI.
> Fix localiztion for buttons in pagination

- src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
- src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user-action.extension.ts
Fixes https://github.com/umbraco/Umbraco-CMS/issues/19312
> Hotfix: do not validate the invariant-variant entry when we vary by culture

- src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/bind-server-validation-to-form-control.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/form-control-validator.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
New take on this PR: https://github.com/umbraco/Umbraco-CMS/pull/18728
> Resolve seen issue regarding destroyed validation context

- src/Umbraco.Web.UI.Client/src/packages/clipboard/property/value-translator/copy/clipboard-copy-translator-value-resolver.ts
- src/Umbraco.Web.UI.Client/src/packages/content/content/controller/merge-content-variant-data.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/create.action.ts
- src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-cloner/property-value-clone.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/core/section/section-default.element.ts
- src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation-path-translation/validation-property-path-translation.controller.ts
- src/Umbraco.Web.UI.Client/src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
Adds setting manifest for all apis created via createExtensionApi()
> Set manifests when using createExtensionApi

- src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/submittable-tree-entity-workspace.context-token.ts
Fixes regression found here: https://github.com/umbraco/Umbraco-CMS/pull/19172/files/916e6331a58130555007d54cc33b5b09b0ed985f#r2124451661
How to test:
* ensure that the document breadscrumbs work correctly
> Fixes the UmbSubmittableTreeEntityWorkspaceContext token discriminator

- Directory.Build.props
- src/Umbraco.Web.UI.Client/package.json
- templates/UmbracoProject/.template.config/starterkits.template.json
- version.json
Bump version to 16.0.0, update starter kit reference and enable package validation.
> Prepare 16.0 release

- src/Umbraco.Core/Services/DocumentUrlService.cs
Addresses: https://github.com/umbraco/Umbraco-CMS/issues/19536
The linked issue raises a good point about lack of logging in the initialization of the `DocumentUrlService`, which should normally be quick, but wasn't due to a regression issue, since patched, in 15,4.
Some logging would have helped identify the bottleneck, so it seems a good idea to have this in place - in case of any further issues here but just also to give more information as to what's going on on start-up.
You should now expect to see (2 additional lines):
```
[14:52:17 INF] Acquiring MainDom.
[14:52:17 INF] Acquired MainDom.
[14:52:18 INF] Caching document URLs.
[14:52:18 INF] Cached 166 document URLs.
[14:52:19 INF] Starting recurring background jobs hosted services
```
Start up Umbraco and verify that you see these …
> Added start-up logging of document URL caching

- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockGrid/ContentWithBlockGrid.spec.ts
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/BlockList/ContentWithBlockList.spec.ts
Implement acceptance tests for https://github.com/umbraco/Umbraco-CMS/issues/18252
> V16 QA Added acceptance tests for the block with RTE in a Content

- src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
Fix for https://github.com/umbraco/Umbraco-CMS/issues/19824 issue
> Tiptap RTE: drag-and-drop image upload

- src/Umbraco.Web.UI.Client/src/packages/segment/collection/index.ts
- src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/index.ts
Const was already exported, so cleaning up the exports.
> clean up double exports

- src/Umbraco.Web.UI.Client/package-lock.json
- src/Umbraco.Web.UI.Client/src/external/tiptap/package.json
Upgrades the Tiptap dependencies to v2.26.1, (the latest on the v2.x branch).
> Tiptap RTE: Upgraded to latest v2.x

- src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-logo.element.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
- src/Umbraco.Web.UI.Client/src/assets/lang/es.ts
Umbraco logo label updaate label text for something more descriptive
> Umbraco logo label update

- src/Umbraco.Web.UI.Client/examples/custom-validation-workspace-context/README.md
- src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-anchor.extension.ts
- src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-figcaption.extension.ts
- src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-figure.extension.ts
- src/Umbraco.Web.UI.Client/src/mocks/data/document-type/document-type.data.ts
- src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
- src/Umbraco.Web.UI.Client/src/mocks/handlers/rte-embed.handlers.ts
- src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts
- src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/font-size.tiptap-toolbar-api.ts
Whilst working on other Tiptap RTE issues, there were a bunch of small code tidy-ups/improvements that I've bundled into a single PR. They'd be nice to have in the v16.2 codebase, but no immediate rush.
> Tiptap RTE: Codesweep for 16.2

- tests/Umbraco.Tests.AcceptanceTest/package-lock.json
- tests/Umbraco.Tests.AcceptanceTest/package.json
- tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMediaPicker.spec.ts
Added acceptance test for issue 10431
> V16 QA added acceptance test for issue 10431

- build/nightly-E2E-run-tests-template.yml
> E2E Pipeline: QA Remove continue on error condition
